Text_SwordsDanceTeach::
    .ifdef ENGLISH
    .string "Not many people come out here.\p"
    .string "If I train here, I'm convinced that\n"
    .string "I'll get stronger and stronger.\p"
    .string "Yep, stronger and stronger…\p"
    .string "How would you like to learn a move\n"
    .string "like that? It's SWORDS DANCE.$"
    .endif
    .ifdef SPANISH
    .string "Son pocos los que vienen\n"
    .string "a esta zona.\p"
    .string "Si me pusiera a entrenar aquí,\n"
    .string "seguro que me haría superfuerte.\p"
    .string "Sí, requetefuerte-fortísimo.\p"
    .string "¿Quieres aprender el movimiento\n"
    .string "DANZA ESPADA?$"
    .endif

Text_SwordsDanceDeclined::
    .ifdef ENGLISH
    .string "Well, that's fine, too.$"
    .endif
    .ifdef SPANISH
    .string "Bueno, como quieras.$"
    .endif

Text_SwordsDanceWhichMon::
    .ifdef ENGLISH
    .string "All right, pick which POKéMON\n"
    .string "I should teach it to.$"
    .endif
    .ifdef SPANISH
    .string "¿A qué POKéMON quieres que\n"
    .string "se lo enseñe?$"
    .endif

Text_SwordsDanceTaught::
    .ifdef ENGLISH
    .string "If only we could keep getting\n"
    .string "stronger and stronger, eh?$"
    .endif
    .ifdef SPANISH
    .string "Lo suyo sería que cada vez nos\n"
    .string "hiciéramos más y más fuertes, ¿eh?$"
    .endif

SevenIsland_Text_IslandSign::
    .ifdef ENGLISH
    .string "SEVEN ISLAND\n"
    .string "Quest Island of Infinity$"
    .endif
    .ifdef SPANISH
    .string "ISLA SÉTIMA\n"
    .string "Isla de aventura infinita.$"
    .endif

SevenIsland_Text_IslandsMadeInSevenDays::
    .ifdef ENGLISH
    .string "These islands are called the SEVII\n"
    .string "ISLANDS because there are seven.\p"
    .string "…Or at least that's what the young\n"
    .string "people believe.\p"
    .string "The truth is, these islands are so\n"
    .string "named because they are said to\l"
    .string "have been made in seven days.$"
    .endif
    .ifdef SPANISH
    .string "A estas islas las llamamos ARCHI7\n"
    .string "porque son siete, je.\p"
    .string "O, por lo menos, es lo que la\n"
    .string "gente joven cree.\p"
    .string "Pero en realidad es porque las\n"
    .string "islas se crearon en siete días.$"
    .endif

SevenIsland_Text_IslandVirtuallyUntouched::
    .ifdef ENGLISH
    .string "This island has been left virtually\n"
    .string "untouched in its natural state.\p"
    .string "It could be a little difficult to\n"
    .string "hike around because of that.$"
    .endif
    .ifdef SPANISH
    .string "Esta isla es prácticamente virgen,\n"
    .string "apenas ha sufrido modificaciones.\p"
    .string "Por ello, es peligroso y difícil\n"
    .string "hacer escalada por aquí.$"
    .endif

