OneIsland_PokemonCenter_1F_Text_BillHeyThereCelio::
	.string "LEO: Salut CILEO!$"

OneIsland_PokemonCenter_1F_Text_CelioCantBelieveYouCameOut::
	.string "CILEO: LEO!\p"
	.string "J'arrive pas à croire que tu\n"
	.string "sois venu.$"

OneIsland_PokemonCenter_1F_Text_BillHowsYourResearchComing::
	.string "LEO: Eh bien oui, je suis là.\p"
	.string "Alors, comment avancent tes\n"
	.string "recherches?\p"
	.string "… Oh, une seconde!$"

OneIsland_PokemonCenter_1F_Text_ThisIsMyBuddyCelio::
	.string "Il faut que je vous présente.\n"
	.string "{PLAYER}, voilà mon ami CILEO.\p"
	.string "C'est un fou d'informatique.$"

OneIsland_PokemonCenter_1F_Text_PlayerIsRisingPokemonChamp::
	.string "CILEO, je te présente {PLAYER}.\p"
	.string "{PLAYER} sera très bientôt un grand\n"
	.string "CHAMPION, j'en suis sûr!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsReigningPokemonChamp::
	.string "CILEO, je te présente {PLAYER}.\n"
	.string "Le CHAMPION en titre.$"

OneIsland_PokemonCenter_1F_Text_CelioThatsReallyImpressive::
	.string "CILEO: Impressionnant.\p"
	.string "Je dois bien avouer que je ne\n"
	.string "suis pas doué pour le combat.\p"
	.string "En tout cas, je suis ravi de te\n"
	.string "rencontrer.$"

OneIsland_PokemonCenter_1F_Text_BillBringMeUpToSpeed::
	.string "LEO: Bon, dis-moi tout.\n"
	.string "Comment fonctionne ta machine?$"

OneIsland_PokemonCenter_1F_Text_CelioPCsCantLinkWithYours::
	.string "CILEO: Plutôt pas mal.\p"
	.string "Mais le problème c'est que nous\n"
	.string "sommes éloignés de tout ici.\p"
	.string "Et le PC ne peut pas se connecter\n"
	.string "au tien, LEO.$"

OneIsland_PokemonCenter_1F_Text_BillLetMeHelpYou::
	.string "LEO: Ah oui?\n"
	.string "Laisse-moi jeter un œil.\p"
	.string "… Hum…\n"
	.string "Je crois que ça peut s'arranger.\p"
	.string "Tu veux bien que je t'aide?$"

OneIsland_PokemonCenter_1F_Text_CanYouDeliverThisMeteoritePlayer::
	.string "{PLAYER}, est-ce que je peux te\n"
	.string "demander d'attendre un peu?\p"
	.string "En fait, j'ai même un service à\n"
	.string "te demander.\p"
	.string "L'île voisine s'appelle l'ILE 2.\p"
	.string "Il y a un type qui dirige la\n"
	.string "SALLE DE JEU, c'est un\p"
	.string "passionné de pierres précieuses\n"
	.string "et de roches rares.\p"
	.string "Est-ce que tu pourrais lui\n"
	.string "apporter ce METEORITE?$"

OneIsland_PokemonCenter_1F_Text_AcceptedMeteoriteFromBill::
	.string "{PLAYER} accepte de prendre le\n"
	.string "METEORITE.$"

OneIsland_PokemonCenter_1F_Text_CelioPleaseTakeThis::
	.string "CILEO: {PLAYER}, si tu vas sur\n"
	.string "l'ILE 2, prends ça avec toi.$"

OneIsland_PokemonCenter_1F_Text_PassLetsYouTravelBetweenIslands::
	.string "C'est un PASSE pour le ferry\n"
	.string "reliant les îles entre elles.\p"
	.string "Avec ça, tu pourras aller sur les\n"
	.string "ILES 1, 2 et 3.\p"
	.string "Oh, il faudrait aussi que tu\n"
	.string "prennes ça.$"

OneIsland_PokemonCenter_1F_Text_ReceivedExtraPageForTownMap::
	.string "{PLAYER} obtient une page\n"
	.string "supplémentaire pour sa CARTE.$"

OneIsland_PokemonCenter_1F_Text_ReceivedTownMap::
	.string "{PLAYER} obtient la\n"
	.string "CARTE!$"

OneIsland_PokemonCenter_1F_Text_BillCatchYouLater::
	.string "LEO: On se revoit plus tard.\p"
	.string "Dis bonjour au type de la SALLE\n"
	.string "DE JEU pour moi.$"

OneIsland_PokemonCenter_1F_Text_HmmHowAboutLikeThis::
	.string "Hum…\n"
	.string "Et si on essayait comme ça!$"

OneIsland_PokemonCenter_1F_Text_GotPCWorkingStrollAWhileMore::
	.string "Oh, {PLAYER}!\p"
	.string "Tu as vu?\n"
	.string "Le PC fonctionne enfin!\p"
	.string "Mais j'ai encore quelques trucs\n"
	.string "à montrer à CILEO.\p"
	.string "Tu peux repasser un peu\n"
	.string "plus tard?$"

OneIsland_PokemonCenter_1F_Text_SorryForBeingPoorHost::
	.string "Je suis vraiment désolé d'accaparer\n"
	.string "LEO.\p"
	.string "J'espère que tu ne m'en voudras\n"
	.string "pas trop.$"

OneIsland_PokemonCenter_1F_Text_UsualPCServicesUnavailable::
	.string "Services habituels inaccessibles…$"

OneIsland_PokemonCenter_1F_Text_BillOhHeyPlayer::
	.string "LEO: Oh!\n"
	.string "{PLAYER}!$"

OneIsland_PokemonCenter_1F_Text_BillWeGotItDone::
	.string "LEO: Qu'est-ce qui t'a retenu\n"
	.string "comme ça?\p"
	.string "Nous, on a terminé! Les PC\n"
	.string "fonctionnent à merveille.$"

OneIsland_PokemonCenter_1F_Text_CelioJobWentQuick::
	.string "CILEO: LEO est un vrai pro.\p"
	.string "Il a réussi à tout mettre en ligne\n"
	.string "en un rien de temps.$"

OneIsland_PokemonCenter_1F_Text_BillYouveLearnedALot::
	.string "LEO: Non, non.\n"
	.string "C'était vraiment rien.\p"
	.string "Tout ça c'est grâce à toi CILEO,\n"
	.string "j'aurais rien pu faire seul.$"

OneIsland_PokemonCenter_1F_Text_CelioOhReallyEhehe::
	.string "CILEO: Oh?\n"
	.string "Merci…$"

OneIsland_PokemonCenter_1F_Text_BillWeShouldHeadBackToKanto::
	.string "LEO: Bon, maintenant que tout\n"
	.string "fonctionne, on peut repartir\p"
	.string "pour KANTO.\n"
	.string "A bientôt CILEO.$"

OneIsland_PokemonCenter_1F_Text_CelioPromiseIllShowYouAroundSometime::
	.string "CILEO: {PLAYER}, je suis vraiment\n"
	.string "désolé d'avoir passé tout ce\p"
	.string "temps sur le PC.\p"
	.string "C'est promis, la prochaine fois,\n"
	.string "je te ferai visiter les îles.$"

OneIsland_PokemonCenter_1F_Text_CelioImModifyingMyNetworkMachine::
	.string "CILEO: Salut!\p"
	.string "On dirait que tu as plein de choses\n"
	.string "à faire aujourd'hui.\p"
	.string "Comment je vais?\p"
	.string "Eh bien, j'effectue quelques mises\n"
	.string "à jour sur ma machine.\p"
	.string "Quand j'aurai terminé, j'espère\n"
	.string "que tu seras la première personne\p"
	.string "à l'utiliser, {PLAYER}.$"

OneIsland_PokemonCenter_1F_Text_CelioCaughtMoreMonMaybeICanBeUseful::
	.string "CILEO: {PLAYER}, tout se passe\n"
	.string "bien pour toi?\p"
	.string "Oh, je vois que tu as attrapé\n"
	.string "plein de POKéMON.\p"
	.string "Tu sais quoi? Je crois que je\n"
	.string "pourrais t'être utile.$"

OneIsland_PokemonCenter_1F_Text_YoullBeTradingFromTrainersFarAway::
	.string "Je suis en train d'apporter des\n"
	.string "modifications à ma machine.\p"
	.string "Quand j'aurai terminé, tu\n"
	.string "pourras échanger des POKéMON\p"
	.string "avec des DRESSEURS qui se\n"
	.string "trouvent très loin d'ici.$"

OneIsland_PokemonCenter_1F_Text_NeedsSpecialGemstone::
	.string "Il y a juste un problème.\p"
	.string "Pour que ça fonctionne, il me\n"
	.string "faut une pierre spéciale.\p"
	.string "Elle est censée se trouver\n"
	.string "sur l'ILE 1, mais je ne\p"
	.string "l'ai pas encore trouvée.\p"
	.string "Qui sait où elle peut bien se\n"
	.string "trouver?$"

OneIsland_PokemonCenter_1F_Text_TryingToFindGem::
	.string "Je cherchais déjà cette pierre\n"
	.string "pendant mes études.\p"
	.string "Résultat, je n'ai ni mon diplôme,\n"
	.string "ni la pierre…\p"
	.string "Je sais que je peux compter sur\n"
	.string "LEO pour faire avancer mes\p"
	.string "recherches. Mais cette fois, je\n"
	.string "voudrais réussir tout seul.$"

OneIsland_PokemonCenter_1F_Text_OhThats::
	.string "Oh!\n"
	.string "M-mais c'est…$"

OneIsland_PokemonCenter_1F_Text_HandedRubyToCelio::
	.string "{PLAYER} donne le RUBIS à\n"
	.string "CILEO.$"

OneIsland_PokemonCenter_1F_Text_MayIAskOneMoreFavor::
	.string "Merci!\p"
	.string "{PLAYER}, je ne sais pas comment\n"
	.string "te remercier.\p"
	.string "… … …  … … …\p"
	.string "… Est-ce que je peux te demander\n"
	.string "encore une grosse faveur?$"

OneIsland_PokemonCenter_1F_Text_PleaseINeedYourHelp::
	.string "Ce… Ce n'est pas\n"
	.string "compliqué, je t'en prie.$"

OneIsland_PokemonCenter_1F_Text_AnotherGemstoneInSeviiIslands::
	.string "Quand j'étudiais les pierres\n"
	.string "précieuses, j'ai découvert\p"
	.string "quelque chose d'important.\p"
	.string "Il y a une autre pierre qui va de\n"
	.string "pair avec ce RUBIS.\p"
	.string "Cette pierre devrait se trouver\n"
	.string "sur les ILES SEVII.\p"
	.string "{PLAYER}, pourrais-tu chercher\n"
	.string "cette pierre pour moi?\p"
	.string "Tiens, montre-moi ton PASSE\n"
	.string "et la CARTE.$"

OneIsland_PokemonCenter_1F_Text_ReturnedTriPassForRainbowPass::
	.string "{PLAYER} rend le TRI-PASSE et\n"
	.string "reçoit le PASSE PRISME.$"

OneIsland_PokemonCenter_1F_Text_ObtainedExtraMapPage::
	.string "Et reçoit une page supplémentaire\n"
	.string "pour la CARTE.$"

OneIsland_PokemonCenter_1F_Text_PassLetYouGetToAllIslands::
	.string "C'est mon PASSE personnel\n"
	.string "pour le ferry.\p"
	.string "Avec ça, tu peux aller sur les\n"
	.string "ILES SEVII.\p"
	.string "{PLAYER}, j'ai vraiment besoin de\n"
	.string "ton aide.$"

OneIsland_PokemonCenter_1F_Text_HandedSapphireToCelio::
	.string "{PLAYER} donne le SAPHIR à CILEO.$"

OneIsland_PokemonCenter_1F_Text_ThankYouGiveMeTime::
	.string "CILEO: Voilà la pierre qui va de\n"
	.string "pair avec le RUBIS.\p"
	.string "{PLAYER}, tu as dû te donner du mal\n"
	.string "pour l'obtenir, n'est-ce pas?\p"
	.string "Ne dis rien, je sais que ça a\n"
	.string "dû être difficile.\p"
	.string "Merci énormément!\p"
	.string "A mon tour de te rendre service!\n"
	.string "Donne-moi juste un instant.$"

OneIsland_PokemonCenter_1F_Text_OkayThisIsGood::
	.string "OK, c'est bon…$"

OneIsland_PokemonCenter_1F_Text_LinkedUpWithLanette::
	.string "J'ai réussi!\n"
	.string "Je me suis connecté avec ANNETTE!$"

OneIsland_PokemonCenter_1F_Text_ManagedToLinkWithHoennThankYou::
	.string "{PLAYER}…\n"
	.string "{PLAYER}, j'ai réussi!\p"
	.string "J'ai réussi à me connecter avec\n"
	.string "les DRESSEURS de HOENN.\p"
	.string "Ma machine est complètement\n"
	.string "opérationnelle!\p"
	.string "{PLAYER}, tout ça,\n"
	.string "c'est grâce à toi!\p"
	.string "Merci, mes rêves se sont enfin\n"
	.string "réalisés…$"

OneIsland_PokemonCenter_1F_Text_WishYouBestOfLuck::
	.string "…\n"
	.string "J'en ai les larmes aux yeux.\p"
	.string "En tout cas, je te souhaite de\n"
	.string "réussir dans ta quête de\p"
	.string "POKéMON exotiques.\n"
	.string "Bonne chance {PLAYER}!$"

OneIsland_PokemonCenter_1F_Text_CelioHearingRumorsAboutYou::
	.string "CILEO: Hello!\p"
	.string "{PLAYER}, j'ai entendu plein de\n"
	.string "choses sur toi.$"

OneIsland_PokemonCenter_1F_Text_BillsFirstMonWasAbra::
	.string "{PLAYER}, c'est quoi ton type\n"
	.string "de POKéMON préféré?\p"
	.string "LEO est un POKéMANIAC,\n"
	.string "il aime tous les types de POKéMON.\p"
	.string "Apparemment, son premier POKéMON\n"
	.string "était un ABRA.$"

OneIsland_PokemonCenter_1F_Text_BillsHometownInGoldenrod::
	.string "Au fait, {PLAYER}, tu es de\n"
	.string "BOURG PALETTE, non?\p"
	.string "Il paraît que c'est une petite\n"
	.string "ville très agréable.\p"
	.string "LEO vient de GOLDENROD,\n"
	.string "sa famille y habite toujours.\p"
	.string "On raconte que c'est une ville\n"
	.string "qui aime faire la fête.\p"
	.string "J'aimerais y aller un jour.$"

OneIsland_PokemonCenter_1F_Text_BillCantStomachMilk::
	.string "{PLAYER}, y a-t-il des choses que\n"
	.string "tu ne supportes pas?\p"
	.string "Apparemment, LEO est allergique\n"
	.string "au lait, c'est dingue.$"

OneIsland_PokemonCenter_1F_Text_CameFromPalletDontKnowIt::
	.string "Oh, un étranger!\n"
	.string "Salut, tu viens d'où?\p"
	.string "BOURG PALETTE?\n"
	.string "Connais pas!$"

OneIsland_PokemonCenter_1F_Text_EnormousVolcanoOnIsland::
	.string "Sur cette île, il y a un énorme\n"
	.string "volcan.\p"
	.string "Il n'est pas entré en éruption\n"
	.string "depuis longtemps.\p"
	.string "Ça te tente une petite balade?$"

OneIsland_PokemonCenter_1F_Text_WishICouldTradeWithBoyfriend::
	.string "J'adorerais pouvoir échanger des\n"
	.string "POKéMON avec mon copain\p"
	.string "qui habite très loin d'ici…$"

OneIsland_PokemonCenter_1F_Text_TradedWithFarAwayBoyfriend::
	.string "J'ai pu échanger des POKéMON\n"
	.string "avec mon copain qui\p"
	.string "habite très loin d'ici.\p"
	.string "C'est grâce à CILEO et toi que\n"
	.string "c'est enfin possible.\p"
	.string "Alors, du fond du cœur, merci!$"

OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment::
	.string "NIVEAU DE CONNEXION 0\p"
	.string "Système de gestion de POKéMON\n"
	.string "en construction.$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKanto::
	.string "NIVEAU DE CONNEXION 1\p"
	.string "Lien établi avec la région de\n"
	.string "KANTO.$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKantoAndHoenn::
	.string "NIVEAU DE CONNEXION 2\p"
	.string "Lien établi avec les régions de\n"
	.string "KANTO et HOENN.$"

OneIsland_PokemonCenter_1F_Text_ObtainedTriPass::
	.string "Obtient le TRI-PASSE!$"

