OneIsland_PokemonCenter_1F_Text_BillHeyThereCelio::
    .ifdef ENGLISH
    .string "BILL: Hey, there!\n"
    .string "CELIO!$"
    .endif
    .ifdef SPANISH
    .string "BILL: ¡Eh, oye!\n"
    .string "¡CELIO!$"
    .endif

OneIsland_PokemonCenter_1F_Text_CelioCantBelieveYouCameOut::
    .ifdef ENGLISH
    .string "CELIO: BILL!\n"
    .string "I can't believe you came out here.$"
    .endif
    .ifdef SPANISH
    .string "CELIO: ¡Hombre, BILL!\n"
    .string "¡No puedo creerme que estés aquí!$"
    .endif

OneIsland_PokemonCenter_1F_Text_BillHowsYourResearchComing::
    .ifdef ENGLISH
    .string "BILL: Well, absolutely!\n"
    .string "How's your research coming along?\p"
    .string "…Oh, wait a sec.$"
    .endif
    .ifdef SPANISH
    .string "BILL: ¡Pues claro, hombre!\n"
    .string "¿Qué tal van tus investigaciones?\p"
    .string "Eh..., ay, perdona...$"
    .endif

OneIsland_PokemonCenter_1F_Text_ThisIsMyBuddyCelio::
    .ifdef ENGLISH
    .string "{PLAYER}, this is my buddy CELIO.\n"
    .string "He's one dedicated PC MANIAC!$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER}, éste es mi amigo CELIO.\n"
    .string "Es un flipado de los ordenadores.$"
    .endif

OneIsland_PokemonCenter_1F_Text_PlayerIsRisingPokemonChamp::
    .ifdef ENGLISH
    .string "CELIO, this is {PLAYER}, a rising\n"
    .string "contender as the POKéMON CHAMP!$"
    .endif
    .ifdef SPANISH
    .string "BILL: CELIO, te presento\n"
    .string "a {PLAYER}, aspirante a ganar\l"
    .string "la LIGA POKéMON.$"
    .endif

OneIsland_PokemonCenter_1F_Text_PlayerIsReigningPokemonChamp::
    .ifdef ENGLISH
    .string "CELIO, this is {PLAYER}, the\n"
    .string "reigning POKéMON CHAMP!$"
    .endif
    .ifdef SPANISH
    .string "BILL: CELIO, te presento\n"
    .string "a {PLAYER}, ¡ha ganado la LIGA\l"
    .string "POKéMON!$"
    .endif

OneIsland_PokemonCenter_1F_Text_CelioThatsReallyImpressive::
    .ifdef ENGLISH
    .string "CELIO: That's really impressive.\p"
    .string "I hate to say it, but I have zero\n"
    .string "aptitude for battling.\p"
    .string "Anyways, I'm glad to meet you.$"
    .endif
    .ifdef SPANISH
    .string "CELIO: ¡Anda, fíjate tú!\p"
    .string "Yo la verdad es que soy un negado\n"
    .string "para los combates.\p"
    .string "Pero oye, me alegro de conocerte.$"
    .endif

OneIsland_PokemonCenter_1F_Text_BillBringMeUpToSpeed::
    .ifdef ENGLISH
    .string "BILL: So, bring me up to speed.\n"
    .string "How's your machine running?$"
    .endif
    .ifdef SPANISH
    .string "BILL: Bueno, cuéntame, cuéntame,\n"
    .string "¿qué tal va la máquina esa en la\l"
    .string "que estabas trabajando?$"
    .endif

OneIsland_PokemonCenter_1F_Text_CelioPCsCantLinkWithYours::
    .ifdef ENGLISH
    .string "CELIO: It's running fine, but we're\n"
    .string "too remote out here.\p"
    .string "The PCs on this island just can't\n"
    .string "link with your PC, BILL.$"
    .endif
    .ifdef SPANISH
    .string "CELIO: Va bien, va bien, pero es\n"
    .string "que estamos en el quinto pino\p"
    .string "y no hay forma de conectar los PCs\n"
    .string "de aquí con tu PC, BILL.$"
    .endif

OneIsland_PokemonCenter_1F_Text_BillLetMeHelpYou::
    .ifdef ENGLISH
    .string "BILL: Oh, yeah?\n"
    .string "Okay, let me take a look-see.\p"
    .string "…Hang on here…\n"
    .string "I think we can make it work.\l"
    .string "Let me help you, okay?$"
    .endif
    .ifdef SPANISH
    .string "BILL: ¿Ah, no? Mmm, ¿me dejas\n"
    .string "que eche un vistazo?\p"
    .string "Un segundo... Oye, pues yo creo\n"
    .string "que podemos conseguir que\l"
    .string "funcione. ¿Me dejas que te ayude?$"
    .endif

OneIsland_PokemonCenter_1F_Text_CanYouDeliverThisMeteoritePlayer::
    .ifdef ENGLISH
    .string "{PLAYER}, can I get you to wait for\n"
    .string "me just a bit?\p"
    .string "…Actually, can I get you to do\n"
    .string "me a favor?\p"
    .string "The island next to this one's\n"
    .string "called TWO ISLAND.\p"
    .string "There's a guy there that runs\n"
    .string "a GAME CORNER.\p"
    .string "He has this thing for rare rocks\n"
    .string "and gems.\p"
    .string "We keep in touch, being fellow\n"
    .string "maniacs.\p"
    .string "So, can I get you to deliver this\n"
    .string "METEORITE to him?$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER}, ¿te importa esperarme\n"
    .string "un momento?\p"
    .string "O, mejor, ¿me haces un favor?\p"
    .string "Cerca de aquí está ISLA SECUNDA\n"
    .string "y hay un tipo que lleva los\l"
    .string "RECREATIVOS.\p"
    .string "La cosa es que le encantan\n"
    .string "las rocas raras y las gemas.\p"
    .string "Como ves, los dos tenemos\n"
    .string "nuestras manías, por eso estamos\l"
    .string "en contacto.\p"
    .string "¿Te importaría acercarle\n"
    .string "este METEORITO?$"
    .endif

OneIsland_PokemonCenter_1F_Text_AcceptedMeteoriteFromBill::
    .ifdef ENGLISH
    .string "{PLAYER} accepted the METEORITE\n"
    .string "from BILL.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} obtuvo el METEORITO\n"
    .string "de manos de BILL.$"
    .endif

OneIsland_PokemonCenter_1F_Text_CelioPleaseTakeThis::
    .ifdef ENGLISH
    .string "CELIO: {PLAYER}, if you are going\n"
    .string "to TWO ISLAND, please take this.$"
    .endif
    .ifdef SPANISH
    .string "CELIO: {PLAYER}, toma, llévate esto\n"
    .string "si vas a ir a ISLA SECUNDA.$"
    .endif

OneIsland_PokemonCenter_1F_Text_PassLetsYouTravelBetweenIslands::
    .ifdef ENGLISH
    .string "It's a PASS for the ferry service\n"
    .string "serving the local islands.\p"
    .string "It will let you travel between the\n"
    .string "ISLANDS ONE, TWO, and THREE.\p"
    .string "Oh, you should have this, too.$"
    .endif
    .ifdef SPANISH
    .string "CELIO: Es un TICKET para el ferry\n"
    .string "que conecta las islas.\p"
    .string "Con él podrás viajar entre las\n"
    .string "ISLAS PRIMA, SECUNDA y TERA.\p"
    .string "¡Ah, y llévate esto también!$"
    .endif

OneIsland_PokemonCenter_1F_Text_ReceivedExtraPageForTownMap::
    .ifdef ENGLISH
    .string "{PLAYER} received an extra page\n"
    .string "for the TOWN MAP!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo una página más\n"
    .string "del MAPA!$"
    .endif

OneIsland_PokemonCenter_1F_Text_ReceivedTownMap::
    .ifdef ENGLISH
    .string "{PLAYER} received\n"
    .string "a TOWN MAP!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo el MAPA!$"
    .endif

OneIsland_PokemonCenter_1F_Text_BillCatchYouLater::
    .ifdef ENGLISH
    .string "BILL: I'll catch you later!\n"
    .string "Say hi to the guy for me!$"
    .endif
    .ifdef SPANISH
    .string "BILL: ¡Bueno, después nos vemos!\n"
    .string "¡Dale recuerdos de mi parte!$"
    .endif

OneIsland_PokemonCenter_1F_Text_HmmHowAboutLikeThis::
    .ifdef ENGLISH
    .string "Hmm…\p"
    .string "How about we try this like this…$"
    .endif
    .ifdef SPANISH
    .string "Mmm...\p"
    .string "¿Y si intentamos ponerlo de otra\n"
    .string "forma?...$"
    .endif

OneIsland_PokemonCenter_1F_Text_GotPCWorkingStrollAWhileMore::
    .ifdef ENGLISH
    .string "Oh, hey, {PLAYER}!\p"
    .string "Did you see?\n"
    .string "We got the PC working!\p"
    .string "I've got a few things to show\n"
    .string "CELIO here.\p"
    .string "Can you go out on a stroll or\n"
    .string "something for a while more?$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, {PLAYER}!\p"
    .string "¿Has visto? ¡Hemos conseguido\n"
    .string "la conexión con el PC!\p"
    .string "Pero aún tengo que enseñarle\n"
    .string "un par de cosas a CELIO.\p"
    .string "¿Por qué no te das un paseo\n"
    .string "mientras?$"
    .endif

OneIsland_PokemonCenter_1F_Text_SorryForBeingPoorHost::
    .ifdef ENGLISH
    .string "I'm sorry for taking up so much of\n"
    .string "BILL's time.\p"
    .string "I'm also sorry for being such a \n"
    .string "poor host on your visit here.$"
    .endif
    .ifdef SPANISH
    .string "CELIO: Siento haber entretenido\n"
    .string "tanto a BILL.\p"
    .string "Y siento también haber sido tan\n"
    .string "mal anfitrión.$"
    .endif

OneIsland_PokemonCenter_1F_Text_UsualPCServicesUnavailable::
    .ifdef ENGLISH
    .string "The usual PC services aren't\n"
    .string "available…$"
    .endif
    .ifdef SPANISH
    .string "Los servicios habituales del PC\n"
    .string "no están disponibles...$"
    .endif

OneIsland_PokemonCenter_1F_Text_BillOhHeyPlayer::
    .ifdef ENGLISH
    .string "BILL: Oh, hey!\n"
    .string "{PLAYER}!$"
    .endif
    .ifdef SPANISH
    .string "BILL: ¡Anda, {PLAYER}!\n"
    .string "¿Qué tal?$"
    .endif

OneIsland_PokemonCenter_1F_Text_BillWeGotItDone::
    .ifdef ENGLISH
    .string "BILL: What kept you so long?\n"
    .string "Been out having a good time?\p"
    .string "We got it done.\n"
    .string "The PCs are up and running!$"
    .endif
    .ifdef SPANISH
    .string "BILL: ¿Qué has estado haciendo\n"
    .string "tanto tiempo? ¿Qué tal, bien?\p"
    .string "¡Nosotros ya lo tenemos! ¡Los PCs\n"
    .string "están a punto y van de maravilla!$"
    .endif

OneIsland_PokemonCenter_1F_Text_CelioJobWentQuick::
    .ifdef ENGLISH
    .string "CELIO: The job went incredibly\n"
    .string "quick.\p"
    .string "BILL is one amazing guy…$"
    .endif
    .ifdef SPANISH
    .string "CELIO: La verdad es que ha sido\n"
    .string "más rápido de lo que pensaba.\p"
    .string "BILL es un cerebrito.$"
    .endif

OneIsland_PokemonCenter_1F_Text_BillYouveLearnedALot::
    .ifdef ENGLISH
    .string "BILL: No, no! There was almost\n"
    .string "nothing left for me to do.\p"
    .string "CELIO, I have to hand it to you.\n"
    .string "You've learned a lot.$"
    .endif
    .ifdef SPANISH
    .string "BILL: ¡Qué va, hombre! ¡Si todo\n"
    .string "estaba prácticamente hecho!\p"
    .string "CELIO, el mérito es tuyo.\n"
    .string "Sabes un montón.$"
    .endif

OneIsland_PokemonCenter_1F_Text_CelioOhReallyEhehe::
    .ifdef ENGLISH
    .string "CELIO: Oh, really?\n"
    .string "Ehehe…$"
    .endif
    .ifdef SPANISH
    .string "CELIO: ¿Tú crees?\n"
    .string "Bueno, pues vale. Je.$"
    .endif

OneIsland_PokemonCenter_1F_Text_BillWeShouldHeadBackToKanto::
    .ifdef ENGLISH
    .string "BILL: Well, there you have it.\n"
    .string "I'm finished with the job.\l"
    .string "We should head back to KANTO.\p"
    .string "CELIO, I'll be seeing you again.$"
    .endif
    .ifdef SPANISH
    .string "BILL: Bueno, pues ya está.\n"
    .string "Por mi parte, yo he acabado.\l"
    .string "Vámonos ya de vuelta a KANTO.\p"
    .string "CELIO, nos vemos.$"
    .endif

OneIsland_PokemonCenter_1F_Text_CelioPromiseIllShowYouAroundSometime::
    .ifdef ENGLISH
    .string "CELIO: {PLAYER}, I'm really sorry\n"
    .string "that we sent you off alone today.\p"
    .string "I promise, I will show you around\n"
    .string "these islands sometime.$"
    .endif
    .ifdef SPANISH
    .string "CELIO: {PLAYER}, siento mucho que\n"
    .string "hayas tenido que marcharte sin\l"
    .string "nadie que te acompañara.\p"
    .string "Te prometo que te enseñaré\n"
    .string "la isla en otra ocasión.$"
    .endif

OneIsland_PokemonCenter_1F_Text_CelioImModifyingMyNetworkMachine::
    .ifdef ENGLISH
    .string "CELIO: Hello!\n"
    .string "You look awfully busy as always.\p"
    .string "How am I doing?\p"
    .string "Well, I'm modifying my Network\n"
    .string "Machine.\p"
    .string "When I get done with the machine,\n"
    .string "I hope you'll be first to use it,\l"
    .string "{PLAYER}.$"
    .endif
    .ifdef SPANISH
    .string "CELIO: ¡Hola!\n"
    .string "¡Siempre estás de aquí para allá!\p"
    .string "¿Que qué tal voy?\p"
    .string "Pues haciendo unos retoques\n"
    .string "a la MÁQUINA de REDES.\p"
    .string "¡Espero que la uses antes que\n"
    .string "nadie cuando esté lista, {PLAYER}!$"
    .endif

OneIsland_PokemonCenter_1F_Text_CelioCaughtMoreMonMaybeICanBeUseful::
    .ifdef ENGLISH
    .string "CELIO: {PLAYER}, how have things\n"
    .string "been for you?\p"
    .string "Oh, is that right?\n"
    .string "You've caught more POKéMON.\p"
    .string "Do you know what?\n"
    .string "Maybe I can be useful to you.$"
    .endif
    .ifdef SPANISH
    .string "CELIO: {PLAYER}, ¿qué tal\n"
    .string "te ha ido?\p"
    .string "¿De verdad? ¿Has atrapado más\n"
    .string "POKéMON?\p"
    .string "Pues ¿sabes qué? A lo mejor puedo\n"
    .string "ayudarte.$"
    .endif

OneIsland_PokemonCenter_1F_Text_YoullBeTradingFromTrainersFarAway::
    .ifdef ENGLISH
    .string "I'm modifying the Network Machine\n"
    .string "right now.\p"
    .string "I'm changing it so it can handle\n"
    .string "trades over long distances.\p"
    .string "When I get finished, you'll be\n"
    .string "trading for exotic POKéMON from\l"
    .string "TRAINERS far away.$"
    .endif
    .ifdef SPANISH
    .string "En este momento estoy modificando\n"
    .string "la MÁQUINA de REDES.\p"
    .string "Estoy ajustándola para que puedan\n"
    .string "hacerse intercambios a grandes\l"
    .string "distancias.\p"
    .string "Cuando acabe, podrás recibir\n"
    .string "exóticos POKéMON de ENTRENADORES\l"
    .string "que están muy lejos de aquí.$"
    .endif

OneIsland_PokemonCenter_1F_Text_NeedsSpecialGemstone::
    .ifdef ENGLISH
    .string "But, there is a slight catch.\p"
    .string "For the link to work, the Machine\n"
    .string "needs a special gemstone.\p"
    .string "It's supposed to be on ONE ISLAND,\n"
    .string "but I haven't found one yet.\p"
    .string "Who knows where it could be.$"
    .endif
    .ifdef SPANISH
    .string "Pero falta un pequeño detalle.\p"
    .string "Para que funcione la conexión,\n"
    .string "se necesita una gema especial.\p"
    .string "Parece ser que se encuentra\n"
    .string "en ISLA PRIMA, pero yo aún\l"
    .string "no he encontrado ninguna.\p"
    .string "Averigua dónde estará...$"
    .endif

OneIsland_PokemonCenter_1F_Text_TryingToFindGem::
    .ifdef ENGLISH
    .string "I was trying to find the gem\n"
    .string "even while I was studying.\p"
    .string "As a result, I've made no headway\n"
    .string "in both my search and studies…\p"
    .string "If I relied on BILL, I'm sure my\n"
    .string "research would progress.\p"
    .string "But this time, I want to try to do\n"
    .string "things by myself.$"
    .endif
    .ifdef SPANISH
    .string "Durante mis investigaciones\n"
    .string "también he intentado encontrar\l"
    .string "la gema.\p"
    .string "Y al final, ni tengo gema ni\n"
    .string "he avanzado nada en mis estudios...\p"
    .string "Si acudiera a BILL, seguro que\n"
    .string "avanzaría en mis investigaciones.\p"
    .string "Pero en esta ocasión, quiero hacer\n"
    .string "las cosas por mí mismo.$"
    .endif

OneIsland_PokemonCenter_1F_Text_OhThats::
    .ifdef ENGLISH
    .string "Oh!\n"
    .string "Th-that's…$"
    .endif
    .ifdef SPANISH
    .string "¡Ahí va!\n"
    .string "¡Pero si es...!$"
    .endif

OneIsland_PokemonCenter_1F_Text_HandedRubyToCelio::
    .ifdef ENGLISH
    .string "{PLAYER} handed the RUBY\n"
    .string "to CELIO.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} le entregó el RUBÍ\n"
    .string "a CELIO.$"
    .endif

OneIsland_PokemonCenter_1F_Text_MayIAskOneMoreFavor::
    .ifdef ENGLISH
    .string "Thank you!\n"
    .string "{PLAYER}, you're simply amazing.\p"
    .string "… … …  … … …\p"
    .string "Um… May I ask one more giant favor\n"
    .string "of you?$"
    .endif
    .ifdef SPANISH
    .string "¡Muchas gracias!\n"
    .string "¡{PLAYER}, eres increíble!\p"
    .string "... ... ... ... ... ...\p"
    .string "Eh...\n"
    .string "¿Puedo pedirte un favor enorme?$"
    .endif

OneIsland_PokemonCenter_1F_Text_PleaseINeedYourHelp::
    .ifdef ENGLISH
    .string "It… It's not anything weird.\n"
    .string "Please, I need your help.$"
    .endif
    .ifdef SPANISH
    .string "No es ninguna cosa rara...,\n"
    .string "no te preocupes.\l"
    .string "Es que necesito que me ayudes.$"
    .endif

OneIsland_PokemonCenter_1F_Text_AnotherGemstoneInSeviiIslands::
    .ifdef ENGLISH
    .string "While I was studying gemstones,\n"
    .string "I discovered something important.\p"
    .string "There is another gem that forms\n"
    .string "a pair with this RUBY.\p"
    .string "That other gemstone is supposed to\n"
    .string "be in the SEVII ISLANDS.\p"
    .string "{PLAYER}, please, I need you to go\n"
    .string "find the other gem.\p"
    .string "{PLAYER}, may I have your ferry\n"
    .string "PASS and the TOWN MAP?$"
    .endif
    .ifdef SPANISH
    .string "Mientras estudiaba las gemas,\n"
    .string "descubrí algo importante.\p"
    .string "Hay otra que forma pareja\n"
    .string "con este RUBÍ.\p"
    .string "Y se supone que está en\n"
    .string "ARCHI7.\p"
    .string "{PLAYER}, necesito que vayas\n"
    .string "a buscarla, por favor.\p"
    .string "{PLAYER}, ¿me dejas un segundo\n"
    .string "el TICKET del ferry y el MAPA?$"
    .endif

OneIsland_PokemonCenter_1F_Text_ReturnedTriPassForRainbowPass::
    .ifdef ENGLISH
    .string "{PLAYER} returned the TRI-PASS and\n"
    .string "received the RAINBOW PASS.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} devolvió el TRI-TICKET\n"
    .string "y recibió el IRIS-TICKET.$"
    .endif

OneIsland_PokemonCenter_1F_Text_ObtainedExtraMapPage::
    .ifdef ENGLISH
    .string "Obtained an extra page for the\n"
    .string "TOWN MAP!$"
    .endif
    .ifdef SPANISH
    .string "¡Y obtuviste una página más\n"
    .string "del MAPA!$"
    .endif

OneIsland_PokemonCenter_1F_Text_PassLetYouGetToAllIslands::
    .ifdef ENGLISH
    .string "This is my own ferry PASS.\p"
    .string "It will let you get to all the\n"
    .string "SEVII ISLANDS.\p"
    .string "{PLAYER}, please, I can't do\n"
    .string "it without your help.$"
    .endif
    .ifdef SPANISH
    .string "Éste es mi TICKET para el ferry.\p"
    .string "Con él, podrás viajar entre las\n"
    .string "islas de ARCHI7.\p"
    .string "{PLAYER}, tienes que ayudarme,\n"
    .string "por favor.$"
    .endif

OneIsland_PokemonCenter_1F_Text_HandedSapphireToCelio::
    .ifdef ENGLISH
    .string "{PLAYER} handed the SAPPHIRE\n"
    .string "to CELIO.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} le entregó el ZAFIRO\n"
    .string "a CELIO.$"
    .endif

OneIsland_PokemonCenter_1F_Text_ThankYouGiveMeTime::
    .ifdef ENGLISH
    .string "CELIO: So this is the gem that\n"
    .string "forms a pair with the RUBY…\p"
    .string "{PLAYER}, you've gone through a lot\n"
    .string "to get this, didn't you?\p"
    .string "You don't have to tell me. I know\n"
    .string "it wasn't easy.\p"
    .string "Thank you so much!\p"
    .string "Now it's my turn to work for you!\n"
    .string "Please give me a little time.$"
    .endif
    .ifdef SPANISH
    .string "CELIO: Así que ésta es la\n"
    .string "compañera del RUBÍ...\p"
    .string "{PLAYER}, has debido de pasar por\n"
    .string "mil historias para conseguirla, ¿no?\p"
    .string "No hace falta que me digas nada,\n"
    .string "sé que no habrá sido nada fácil.\p"
    .string "¡Muchas gracias!\p"
    .string "Ahora me toca a mí hacer algo\n"
    .string "por ti. Dame algo de tiempo.$"
    .endif

OneIsland_PokemonCenter_1F_Text_OkayThisIsGood::
    .ifdef ENGLISH
    .string "Okay, this is good…$"
    .endif
    .ifdef SPANISH
    .string "Muy bien, a ver...$"
    .endif

OneIsland_PokemonCenter_1F_Text_LinkedUpWithLanette::
    .ifdef ENGLISH
    .string "I did it!\n"
    .string "I linked up with LANETTE!$"
    .endif
    .ifdef SPANISH
    .string "¡Ya está!\n"
    .string "¡He conseguido establecer conexión\l"
    .string "con AREDIA!$"
    .endif

OneIsland_PokemonCenter_1F_Text_ManagedToLinkWithHoennThankYou::
    .ifdef ENGLISH
    .string "{PLAYER}…\n"
    .string "{PLAYER}, I did it!\p"
    .string "I've managed to link up with\n"
    .string "TRAINERS in the HOENN region!\p"
    .string "Finally, the Network Machine is\n"
    .string "fully operational!\p"
    .string "{PLAYER}, I owe it all to you!\p"
    .string "Thanks to you, my dream came\n"
    .string "true…$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER}!\n"
    .string "¡{PLAYER}, lo he conseguido!\p"
    .string "¡He conseguido establecer conexión\n"
    .string "con ENTRENADORES de la región\l"
    .string "de HOENN!\p"
    .string "¡Por fin funciona completamente\n"
    .string "la MÁQUINA de REDES!\p"
    .string "{PLAYER}, te lo debo todo a ti.\p"
    .string "Gracias a ti, mi sueño se ha hecho\n"
    .string "realidad...$"
    .endif

OneIsland_PokemonCenter_1F_Text_WishYouBestOfLuck::
    .ifdef ENGLISH
    .string "I…\n"
    .string "I'm not crying.\p"
    .string "That's enough about me!\p"
    .string "{PLAYER}, you're going to keep\n"
    .string "looking for exotic POKéMON, right?\p"
    .string "I wish you the best of luck!$"
    .endif
    .ifdef SPANISH
    .string "No...\n"
    .string "No estoy llorando, no...\p"
    .string "Ya está, ya se me pasa...\p"
    .string "{PLAYER}, ¿a que vas a intentar\n"
    .string "conseguir exóticos POKéMON, eh?\p"
    .string "¡Que tengas mucha suerte!$"
    .endif

OneIsland_PokemonCenter_1F_Text_CelioHearingRumorsAboutYou::
    .ifdef ENGLISH
    .string "CELIO: Hello!\p"
    .string "{PLAYER}, I've been hearing rumors\n"
    .string "about you.$"
    .endif
    .ifdef SPANISH
    .string "CELIO: ¡Hola!\p"
    .string "{PLAYER}, últimamente se habla\n"
    .string "mucho sobre ti...$"
    .endif

OneIsland_PokemonCenter_1F_Text_BillsFirstMonWasAbra::
    .ifdef ENGLISH
    .string "{PLAYER}, what's your favorite kind\n"
    .string "of POKéMON?\p"
    .string "BILL is a POKéMANIAC, so he loves\n"
    .string "every kind.\p"
    .string "Apparently, the first one he caught\n"
    .string "was an ABRA.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER}, ¿qué POKéMON te gusta\n"
    .string "más?\p"
    .string "BILL es un POKéMANÍACO,\n"
    .string "a él le gustan todos.\p"
    .string "Creo que el primero que atrapó\n"
    .string "fue un ABRA.$"
    .endif

OneIsland_PokemonCenter_1F_Text_BillsHometownInGoldenrod::
    .ifdef ENGLISH
    .string "By the way, {PLAYER}, you're from\n"
    .string "PALLET TOWN, aren't you?\p"
    .string "I've heard that it's a quiet and\n"
    .string "pleasant place.\p"
    .string "BILL's hometown is GOLDENROD CITY,\n"
    .string "where his folks still live.\p"
    .string "I've heard that it's quite the\n"
    .string "festive, bustling city.\p"
    .string "I'd like to go there one day.$"
    .endif
    .ifdef SPANISH
    .string "A todo esto, {PLAYER}, tú eres\n"
    .string "de PUEBLO PALETA, ¿no?\p"
    .string "Me han comentado que es un sitio\n"
    .string "muy tranquilo y agradable.\p"
    .string "BILL es de CIUDAD TRIGAL,\n"
    .string "donde aún viven sus amigos.\p"
    .string "Dicen que es una ciudad muy\n"
    .string "alegre y animada.\p"
    .string "La verdad es que me gustaría\n"
    .string "ir algún día.$"
    .endif

OneIsland_PokemonCenter_1F_Text_BillCantStomachMilk::
    .ifdef ENGLISH
    .string "{PLAYER}, is there anything that\n"
    .string "you can't stand?\p"
    .string "Apparently, BILL simply can't\n"
    .string "stomach milk at all.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER}, ¿hay algo que te siente\n"
    .string "mal?\p"
    .string "Creo que BILL no tolera muy bien\n"
    .string "la leche. Le da dolor de estómago.$"
    .endif

OneIsland_PokemonCenter_1F_Text_CameFromPalletDontKnowIt::
    .ifdef ENGLISH
    .string "Oh, you're a stranger here!\n"
    .string "Hi! Where did you come from?\p"
    .string "…PALLET TOWN?\n"
    .string "I don't know it!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, tú no eres de aquí!\n"
    .string "¿De dónde vienes?\p"
    .string "¿PUEBLO PALETA?...\n"
    .string "¡No me suena de nada!$"
    .endif

OneIsland_PokemonCenter_1F_Text_EnormousVolcanoOnIsland::
    .ifdef ENGLISH
    .string "On this island, there's an enormous\n"
    .string "volcano.\p"
    .string "It hasn't erupted lately, so why\n"
    .string "not enjoy a hike?$"
    .endif
    .ifdef SPANISH
    .string "En esta isla hay un volcán enorme.\p"
    .string "Hace poco entró en erupción.\n"
    .string "Ahora sería buen momento\l"
    .string "para hacer escalada.$"
    .endif

OneIsland_PokemonCenter_1F_Text_WishICouldTradeWithBoyfriend::
    .ifdef ENGLISH
    .string "I wish I could trade POKéMON with\n"
    .string "my boyfriend who lives far away…$"
    .endif
    .ifdef SPANISH
    .string "Ojalá pudiera intercambiar POKéMON\n"
    .string "con mi chico, que vive muy lejos\l"
    .string "de aquí...$"
    .endif

OneIsland_PokemonCenter_1F_Text_TradedWithFarAwayBoyfriend::
    .ifdef ENGLISH
    .string "I traded POKéMON with my boyfriend\n"
    .string "far away!\p"
    .string "Everyone's saying that we can\n"
    .string "thank you and CELIO.\p"
    .string "So, thank you!$"
    .endif
    .ifdef SPANISH
    .string "¡He podido intercambiar POKéMON\n"
    .string "con mi chico!\l"
    .string "¡Con lo lejos que está!\p"
    .string "Todo el mundo dice que os\n"
    .string "lo debemos a CELIO y a ti.\p"
    .string "¡Así que gracias!$"
    .endif

OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment::
    .ifdef ENGLISH
    .string "Network Machine\n"
    .string "Link Level 0\p"
    .string "…POKéMON Storage System under\n"
    .string "adjustment…$"
    .endif
    .ifdef SPANISH
    .string "MÁQUINA de REDES\n"
    .string "Nivel de conexión: 0\p"
    .string "Sistema de Almacenamiento\n"
    .string "de POKéMON, no disponible...$"
    .endif

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKanto::
    .ifdef ENGLISH
    .string "Network Machine\n"
    .string "Link Level 1\p"
    .string "Link established with the KANTO\n"
    .string "region.$"
    .endif
    .ifdef SPANISH
    .string "MÁQUINA de REDES\n"
    .string "Nivel de conexión: 1\p"
    .string "Conexión establecida con la región\n"
    .string "de KANTO.$"
    .endif

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKantoAndHoenn::
    .ifdef ENGLISH
    .string "Network Machine\n"
    .string "Link Level 2\p"
    .string "Link established with the KANTO\n"
    .string "and HOENN regions.$"
    .endif
    .ifdef SPANISH
    .string "MÁQUINA de REDES\n"
    .string "Nivel de conexión: 2\p"
    .string "Conexión establecida con las\n"
    .string "regiones de KANTO y HOENN.$"
    .endif

OneIsland_PokemonCenter_1F_Text_ObtainedTriPass::
    .ifdef ENGLISH
    .string "Obtained the TRI-PASS!$"
    .endif
    .ifdef SPANISH
    .string "¡Obtuviste el TRI-TICKET!$"
    .endif

