SilphCo_4F_Text_CantYouSeeImHiding::
	.string "Chut!\n"
	.string "Tu n'vois pas que je me cache?$"

SilphCo_4F_Text_TeamRocketIsGone::
	.string "La TEAM ROCKET est partie? COOL!$"

SilphCo_4F_Text_Grunt1Intro::
	.string "La TEAM ROCKET contrôle\n"
	.string "la SYLPHE SARL!!!$"

SilphCo_4F_Text_Grunt1Defeat::
	.string "Arrgh!$"

SilphCo_4F_Text_Grunt1PostBattle::
	.string "Le BOSS attend ce moment depuis\n"
	.string "longtemps!$"

SilphCo_4F_Text_RodneyIntro::
	.string "Mes POKéMON me servent\n"
	.string "loyalement!!!$"

SilphCo_4F_Text_RodneyDefeat::
	.string "NAN!\n"
	.string "Saleté de POKéMON!$"

SilphCo_4F_Text_RodneyPostBattle::
	.string "Les portes sont sécurisées!\p"
	.string "Il te faut une CARTE MAGN. pour\n"
	.string "les ouvrir!$"

SilphCo_4F_Text_Grunt2Intro::
	.string "J'ai repéré un intrus!$"

SilphCo_4F_Text_Grunt2Defeat::
	.string "Mais?\n"
	.string "Qui es-tu?$"

SilphCo_4F_Text_Grunt2PostBattle::
	.string "Je dois prévenir le chef au 10ème\n"
	.string "étage!$"

SilphCo_4F_Text_FloorSign::
	.string "SYLPHE SARL.\n"
	.string "3ème étage.$"

