SilphCo_4F_Text_CantYouSeeImHiding::
	.string "Pst! Siehst du nicht, dass\n"
	.string "ich mich verstecke?$"

SilphCo_4F_Text_TeamRocketIsGone::
	.string "Das TEAM ROCKET ist verschwunden?$"

SilphCo_4F_Text_Grunt1Intro::
	.string "Das TEAM ROCKET hat die Kontrolle\n"
	.string "über SILPH CO. übernommen!!!$"

SilphCo_4F_Text_Grunt1Defeat::
	.string "Arrgh!$"

SilphCo_4F_Text_Grunt1PostBattle::
	.string "Auf diesen Moment hat der Boss\n"
	.string "sehr lange gewartet!$"

SilphCo_4F_Text_RodneyIntro::
	.string "Mein POKéMON erwartet dich!!!$"

SilphCo_4F_Text_RodneyDefeat::
	.string "Du schwächliches POKéMON! Mist!$"

SilphCo_4F_Text_RodneyPostBattle::
	.string "Die Türen sind elektronisch\n"
	.string "verriegelt! Ohne TÜRÖFFNER kommt\l"
	.string "man nicht durch!$"

SilphCo_4F_Text_Grunt2Intro::
	.string "Eindringling gesichtet!$"

SilphCo_4F_Text_Grunt2Defeat::
	.string "Wer oder was bist du?$"

SilphCo_4F_Text_Grunt2PostBattle::
	.string "Ich muss den BOSS im 10.\n"
	.string "Stock warnen!$"

SilphCo_4F_Text_FloorSign::
	.string "SILPH CO. HAUPTSITZ\n"
	.string "3 OG$"

