SilphCo_4F_Text_CantYouSeeImHiding::
    .string "¡Sssh! ¿Acaso no ves que me estoy\n"
    .string "escondiendo?$"

SilphCo_4F_Text_TeamRocketIsGone::
    .string "¿Eh?\n"
    .string "¿Que el TEAM ROCKET se ha ido?$"

SilphCo_4F_Text_Grunt1Intro::
    .string "¡El TEAM ROCKET se ha apoderado\n"
    .string "de SILPH S.A.!$"

SilphCo_4F_Text_Grunt1Defeat::
    .string "¡Arrgh!$"

SilphCo_4F_Text_Grunt1PostBattle::
    .string "¡Ja, ja, ja!\n"
    .string "¡Mi JEFE buscaba este lugar!$"

SilphCo_4F_Text_RodneyIntro::
    .string "¡Mi POKéMON es mi fiel defensor!$"

SilphCo_4F_Text_RodneyDefeat::
    .string "¡Has debilitado a mi POKéMON!$"

SilphCo_4F_Text_RodneyPostBattle::
    .string "¡Las puertas están cerradas\n"
    .string "electrónicamente!\p"
    .string "¡Las abre una LLAVE MAGNÉTICA!$"

SilphCo_4F_Text_Grunt2Intro::
    .string "¡Nos invaden!$"

SilphCo_4F_Text_Grunt2Defeat::
    .string "¿Quién eres tú?$"

SilphCo_4F_Text_Grunt2PostBattle::
    .string "¡Será mejor que se lo diga\n"
    .string "al JEFE del décimo piso!$"

SilphCo_4F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P3$"
