SilphCo_4F_Text_CantYouSeeImHiding::
    .ifdef ENGLISH
    .string "Sssh!\n"
    .string "Can't you see I'm hiding?$"
    .endif
    .ifdef SPANISH
    .string "¡Sssh! ¿Acaso no ves que me estoy\n"
    .string "escondiendo?$"
    .endif

SilphCo_4F_Text_TeamRocketIsGone::
    .ifdef ENGLISH
    .string "Huh?\n"
    .string "TEAM ROCKET is gone?$"
    .endif
    .ifdef SPANISH
    .string "¿Eh?\n"
    .string "¿Que el TEAM ROCKET se ha ido?$"
    .endif

SilphCo_4F_Text_Grunt1Intro::
    .ifdef ENGLISH
    .string "TEAM ROCKET has taken control\n"
    .string "of SILPH CO.!$"
    .endif
    .ifdef SPANISH
    .string "¡El TEAM ROCKET se ha apoderado\n"
    .string "de SILPH S.A.!$"
    .endif

SilphCo_4F_Text_Grunt1Defeat::
    .ifdef ENGLISH
    .string "Arrgh!$"
    .endif
    .ifdef SPANISH
    .string "¡Arrgh!$"
    .endif

SilphCo_4F_Text_Grunt1PostBattle::
    .ifdef ENGLISH
    .string "Fwahahaha!\n"
    .string "My BOSS has been after this place!$"
    .endif
    .ifdef SPANISH
    .string "¡Ja, ja, ja!\n"
    .string "¡Mi JEFE buscaba este lugar!$"
    .endif

SilphCo_4F_Text_RodneyIntro::
    .ifdef ENGLISH
    .string "My POKéMON is my loyal servant.$"
    .endif
    .ifdef SPANISH
    .string "¡Mi POKéMON es mi fiel defensor!$"
    .endif

SilphCo_4F_Text_RodneyDefeat::
    .ifdef ENGLISH
    .string "Darn!\n"
    .string "You weak POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Has debilitado a mi POKéMON!$"
    .endif

SilphCo_4F_Text_RodneyPostBattle::
    .ifdef ENGLISH
    .string "The doors are electronically\n"
    .string "locked.\p"
    .string "It takes a CARD KEY to open the\n"
    .string "doors here.$"
    .endif
    .ifdef SPANISH
    .string "¡Las puertas están cerradas\n"
    .string "electrónicamente!\p"
    .string "¡Las abre una LLAVE MAGNÉTICA!$"
    .endif

SilphCo_4F_Text_Grunt2Intro::
    .ifdef ENGLISH
    .string "Intruder spotted!$"
    .endif
    .ifdef SPANISH
    .string "¡Nos invaden!$"
    .endif

SilphCo_4F_Text_Grunt2Defeat::
    .ifdef ENGLISH
    .string "Who are you?$"
    .endif
    .ifdef SPANISH
    .string "¿Quién eres tú?$"
    .endif

SilphCo_4F_Text_Grunt2PostBattle::
    .ifdef ENGLISH
    .string "I better tell the BOSS on 11F!$"
    .endif
    .ifdef SPANISH
    .string "¡Será mejor que se lo diga\n"
    .string "al JEFE del décimo piso!$"
    .endif

SilphCo_4F_Text_FloorSign::
    .ifdef ENGLISH
    .string "SILPH CO. HEAD OFFICE\n"
    .string "4F$"
    .endif
    .ifdef SPANISH
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P3$"
    .endif

