PokemonMansion_1F_Text_TedIntro::
    .ifdef ENGLISH
    .string "Who are you?\n"
    .string "There shouldn't be anyone here.$"
    .endif
    .ifdef SPANISH
    .string "¿Y tú quién eres?\n"
    .string "Aquí no debería haber nadie.$"
    .endif

PokemonMansion_1F_Text_TedDefeat::
    .ifdef ENGLISH
    .string "Ouch!$"
    .endif
    .ifdef SPANISH
    .string "¡Auh!$"
    .endif

PokemonMansion_1F_Text_TedPostBattle::
    .ifdef ENGLISH
    .string "A key? I don't know what you're\n"
    .string "talking about.$"
    .endif
    .ifdef SPANISH
    .string "¿Una llave? ¡Ni idea de lo que me\n"
    .string "estás hablando!$"
    .endif

PokemonMansion_1F_Text_JohnsonIntro::
    .ifdef ENGLISH
    .string "W-w-waah! You startled me!\n"
    .string "I thought you were a ghost.$"
    .endif
    .ifdef SPANISH
    .string "¡Aaaaaaaaaah! ¡Qué susto!\n"
    .string "¡Pensaba que eras un fantasma!$"
    .endif

PokemonMansion_1F_Text_JohnsonDefeat::
    .ifdef ENGLISH
    .string "Tch!\n"
    .string "I can't get any wins.$"
    .endif
    .ifdef SPANISH
    .string "¡Uf, no hay forma de que gane!$"
    .endif

PokemonMansion_1F_Text_JohnsonPostBattle::
    .ifdef ENGLISH
    .string "I was exploring here by myself,\n"
    .string "but I feel spooked.\p"
    .string "I ought to go soon.$"
    .endif
    .ifdef SPANISH
    .string "Yo estaba aquí tranquilamente\n"
    .string "curioseando un poco, pero creo\l"
    .string "que voy a irme.\p"
    .string "Tengo un poco de miedo.$"
    .endif

