PokemonMansion_1F_Text_TedIntro::
	.string "Wer bist du?\n"
	.string "Hier hat niemand etwas zu suchen!$"

PokemonMansion_1F_Text_TedDefeat::
	.string "Autsch!$"

PokemonMansion_1F_Text_TedPostBattle::
	.string "Ein Schlüssel?\n"
	.string "Keine Ahnung, wovon du redest!$"

PokemonMansion_1F_Text_JohnsonIntro::
	.string "Oh! Du hast mich überrascht!\n"
	.string "Ich dachte, du wärst ein Geist.$"

PokemonMansion_1F_Text_JohnsonDefeat::
	.string "Ts!\n"
	.string "Ich kann nicht gewinnen!$"

PokemonMansion_1F_Text_JohnsonPostBattle::
	.string "Ich habe das Gebiet hier auf\n"
	.string "eigene Faust erforscht, aber es\l"
	.string "ist so gruselig.\p"
	.string "Ich muss bald weg!$"

