Braille_Text_Up::
	.braille "ARRIBA$"

Braille_Text_Down::
	.braille "ABAJO$"

Braille_Text_Right::
	.braille "DERECHA$"

Braille_Text_Left::
	.braille "IZQUIERDA$"

Braille_Text_Cut::
	.braille "CORTE$"

Braille_Text_ABC::
	.braille "ABC$"

Braille_Text_GHI::
	.braille "GHI$"

Braille_Text_MNO::
	.braille "MNO$"

Braille_Text_TUV::
	.braille "TUV$"

Braille_Text_DEF::
	.braille "DEF$"

Braille_Text_JKL::
	.braille "JKL$"

Braille_Text_PQRS::
	.braille "PQRS$"

Braille_Text_WXYZ::
	.braille "WXYZ$"

Braille_Text_Period::
	.braille "=*$"

Braille_Text_Comma::
	.braille "=,$"

Braille_Text_Everything::
	.braille "TODO$"

Braille_Text_HasMeaning1::
	.braille "IMPORTA$"

Braille_Text_Existence::
	.braille "EXISTENCIA$"

Braille_Text_HasMeaning2::
	.braille "IMPORTA$"

Braille_Text_BeingAlive::
	.braille "ESTAR VIVO$"

Braille_Text_HasMeaning3::
	.braille "IMPORTA$"

Braille_Text_HaveDreams::
	.braille "DESEAR$"

Braille_Text_UsePower::
	.braille "USA FUERZA$"

Braille_Text_LetTheTwo::
	.braille "DEJA A DOS$"

Braille_Text_Glittering::
	.braille "BRILLANTES$"

Braille_Text_Stones::
	.braille "PIEDRAS$"

Braille_Text_OneInRed::
	.braille "UNA ROJA$"

Braille_Text_OneInBlue::
	.braille "UNA AZUL$"

Braille_Text_ConnectThe::
	.braille "CONECTAR$"

Braille_Text_Past::
	.braille "CON PASADO$"

Braille_Text_TwoFriends::
	.braille "AMIGOS$"

Braille_Text_Sharing::
	.braille "COMPARTIR$"

Braille_Text_PowerOpen::
	.braille "FUERZA$"

Braille_Text_AWindowTo::
	.braille "ABRE PUERTA$"

Braille_Text_ANewWorld::
	.braille "A MUNDO$"

Braille_Text_ThatGlows::
	.braille "POR EXPLORAR$"

Braille_Text_TheNext::
	.braille "NUEVO MUNDO$"

Braille_Text_WorldWaits::
	.braille "OS$"

Braille_Text_ForYou::
	.braille "ESPERA$"
