@ Unused
Text_WelcomeTradeCenter::
	.string "Hola. Éste es el CENTRO de CAMBIO\n"
	.string "del CLUB del CABLE POKéMON.$"

@ Unused
Text_WelcomeColosseum::
	.string "Hola. Éste es el COLISEO del\n"
	.string "CLUB del CABLE POKéMON.$"

@ Unused
Text_WelcomeTimeCapsule::
	.string "Hola. Ésta es la CÁPSULA del\n"
	.string "TIEMPO del CLUB del CABLE\l"
	.string "POKéMON.$"

Text_PleaseComeAgain::
	.string "¡Vuelve cuando quieras!$"

@ Unused
Text_HavingDiscountSaleToday::
	.string "¡Hola!\p"
	.string "¡Hoy tenemos rebajas!$"

@ Unused
Text_PlayerWhatCanIDoForYou::
	.string "¡Hola, {PLAYER}{KUN}!\p"
	.string "¿En qué puedo ayudarte?$"
