@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "¡Totalmente lleno de libros sobre\n"
	.string "los POKéMON!$"

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "MAPA$"

Text_PokeMartShelf::
	.string "¡Uauu!\n"
	.string "¡Cantidad de artículos de POKéMON!$"

Text_DishesPlatesNeatlyLinedUp::
	.string "Hay un montón de platos y bandejas\n"
	.string "muy bien colocados.$"

Text_Kitchen::
	.string "¡Mmm, huele que alimenta!\n"
	.string "Aquí han debido de cocinar algo...$"

Text_Dresser::
	.string "Qué mueble más estupendo...\n"
	.string "Aquí caben un montón de cosas.$"

Text_Snacks::
	.string "Mmm, cuántas cosas ricas...$"

Text_PokemartSign::
	.string "TIENDAS POKéMON\n"
	.string "¡Compra aquí todos tus objetos!$"

Text_PokecenterSign::
	.string "CENTRO POKéMON\n"
	.string "¡Cura a tus POKéMON!$"

Text_Indigo_UltimateGoal::
	.string "MESETA AÑIL\p"
	.string "¡El objetivo de todo ENTRENADOR:\n"
	.string "El CG de la LIGA POKéMON!$"

Text_Indigo_HighestAuthority::
	.string "MESETA AÑIL\p"
	.string "La máxima autoridad POKéMON\n"
	.string "del CG de la LIGA POKéMON.$"

Text_Food::
	.string "Seguramente está lleno de cosas\n"
	.string "de lo más apetecibles.$"

Text_Blueprints::
	.string "Y este plano... ¿de dónde será?\p"
	.string "Tiene gráficos y anotaciones\n"
	.string "rarísimas.$"

Text_Painting::
	.string "Qué foto más bonita.\n"
	.string "El POKéMON parece estar encantado.$"

Text_PowerPlantMachine::
	.string "¿Para qué servirá?\n"
	.string "Prefiero no tocar, por si acaso...$"

Text_Telephone::
	.string "Anda, un teléfono.\n"
	.string "Paso de usarlo.$"

Text_Computer::
	.string "Qué combinación de números\n"
	.string "y letras más complicada...$"

Text_AdvertisingPoster::
	.string "Es un póster promocional\n"
	.string "con todo tipo de productos.$"

Text_TastyFood::
	.string "Mmm, ¡qué bien huele!\n"
	.string "¡Se me hace la boca agua!$"

Text_TrashBin::
	.string "A ver...\n"
	.string "... ...\p"
	.string "¡Pero si no hay nada!$"

Text_Cup::
	.string "¡Qué taza más guay!\n"
	.string "¡Tiene la huella de un POKéMON!$"

Text_PolishedWindow::
	.string "La ventana está requetelimpia.$"

Text_BeautifulSkyWindow::
	.string "Da gusto mirar por la ventana...\p"
	.string "El cielo está impresionante.$"

Text_BlinkingLights::
	.string "Cuántas lucecitas de colores\n"
	.string "que se encienden y se apagan...$"

Text_NeatlyLinedUpTools::
	.string "Hay un montón de relucientes\n"
	.string "herramientas muy bien ordenadas.$"

Text_ImpressiveMachine::
	.string "No sé qué será esta máquina,\n"
	.string "pero es impresionante.$"

Text_VideoGame::
	.string "¡Lo último en videojuegos!\n"
	.string "¡Qué guay!$"

Text_Burglary::
	.string "Salta a la vista que han entrado\n"
	.string "a robar...$"

Text_PlayerFacingTVScreen::
	.string "¡Está saliendo un POKéMON\n"
	.string "por la tele! Se le ve encantado...$"
