gOtherText_NewName::
	.string "OTRO NOMBRE$"

gNameChoice_Green::
	.string "VERTE$"

gNameChoice_Red::
	.string "JORO$"

gNameChoice_Leaf::
	.string "JAHO$"

gNameChoice_Fire::
	.string "GUEFO$"

gNameChoice_Gary::
	.string "BOSCO$"

gNameChoice_Kaz::
	.string "FLOREN$"

gNameChoice_Toru::
	.string "SILVIO$"

gNameChoice_Ash::
	.string "FURIO$"

gNameChoice_Kene::
	.string "LLAMÍN$"

gNameChoice_Geki::
	.string "CANDEL$"

gNameChoice_Jak::
	.string "JUNO$"

gNameChoice_Janne::
	.string "JUAN$"

gNameChoice_Jonn::
	.string "JUANMA$"

gNameChoice_Kamon::
	.string "ÁLVARO$"

gNameChoice_Karl::
	.string "RAL$"

gNameChoice_Taylor::
	.string "MARINO$"

gNameChoice_Oscar::
	.string "TOILO$"

gNameChoice_Hiro::
	.string "NER$"

gNameChoice_Max::
	.string "MAX$"

gNameChoice_Jon::
	.string "MOREL$"

gNameChoice_Ralph::
	.string "RAFA$"

gNameChoice_Kay::
	.string "VER$"

gNameChoice_Tosh::
	.string "LERIO$"

gNameChoice_Roak::
	.string "RODI$"

gNameChoice_Omi::
	.string "MENA$"

gNameChoice_Jodi::
	.string "CIRA$"

gNameChoice_Amanda::
	.string "MARÍA$"

gNameChoice_Hillary::
	.string "MINA$"

gNameChoice_Makey::
	.string "NENA$"

gNameChoice_Michi::
	.string "LUNA$"

gNameChoice_Paula::
	.string "BRUNA$"

gNameChoice_June::
	.string "CLAUDIA$"

gNameChoice_Cassie::
	.string "CASILDA$"

gNameChoice_Rey::
	.string "RITA$"

gNameChoice_Seda::
	.string "SELENA$"

gNameChoice_Kiko::
	.string "MATILDE$"

gNameChoice_Mina::
	.string "NURIA$"

gNameChoice_Norie::
	.string "MARINA$"

gNameChoice_Sai::
	.string "SALIA$"

gNameChoice_Momo::
	.string "MIRTA$"

gNameChoice_Suzi::
	.string "SUSA$"

gControlsGuide_Text_Intro::
	.string "La explicación de los botones\n"
	.string "se hará por orden de importancia.$"

gControlsGuide_Text_DPad::
	.string "Mover al protagonista de la\n"
	.string "historia. Seleccionar opciones.$"

gControlsGuide_Text_AButton::
	.string "Confirmar opciones, curiosear\n"
	.string "cosas, chatear y leer texto.$"

gControlsGuide_Text_BButton::
	.string "Retroceder, cancelar opciones\n"
	.string "y salir de distintos menús.$"

gControlsGuide_Text_StartButton::
	.string "Abrir el menú.$"

gControlsGuide_Text_SelectButton::
	.string "Cambiar objetos de lugar y usar\n"
	.string "el que haya registrado.$"

gControlsGuide_Text_LRButtons::
	.string "Acceder al sistema de AYUDA.$"

gOakSpeech_Text_AskPlayerGender::
	.string "Hola, ¿eres chico o chica?$"

gPikachuIntro_Text_Page1::
	.string "Estás a punto de sumergirte en un\n"
	.string "mundo lleno de aventuras de las\n"
	.string "que vas a ser protagonista.\n"
	.string "\n"
	.string "Habla con la gente y curiosea todo\n"
	.string "lo que te llame la atención, estés\n"
	.string "donde estés. Consigue información\n"
	.string "y pistas de todo lo que te rodee.$"

gPikachuIntro_Text_Page2::
	.string "Durante el largo camino, tendrás\n"
	.string "que ayudar a gente, enfrentarte\n"
	.string "a desafíos y resolver misterios.\n"
	.string "\n"
	.string "Te cruzarás con rivales y criaturas\n"
	.string "salvajes que querrán luchar\n"
	.string "contigo, pero ¡ánimo, tú puedes!$"

gPikachuIntro_Text_Page3::
	.string "Recuerda, habla con todo el mundo;\n"
	.string "crecerás como persona, y ése es\n"
	.string "tu principal objetivo.\n"
	.string "\n"
	.string "Pulsa el Botón A, ¡que comience\n"
	.string "la aventura!$"

gOakSpeech_Text_WelcomeToTheWorld::
	.string "¡Hola!\n"
	.string "¡Éste es el mundo de POKéMON!\p"
	.string "¡Me llamo OAK!\p"
	.string "¡Pero la gente me llama\n"
	.string "PROFESOR POKéMON!\p"
	.string "$"

gOakSpeech_Text_ThisWorld::
	.string "¡Este mundo está$"

gOakSpeech_Text_IsInhabitedFarAndWide::
	.string "habitado por unas criaturas\n"
	.string "llamadas POKéMON!\p"
	.string "$"

gOakSpeech_Text_IStudyPokemon::
	.string "Para algunos, los POKéMON son\n"
	.string "mascotas. Pero otros los usan\l"
	.string "para pelear.\p"
	.string "En cuanto a mí...\p"
	.string "Estudio a los POKéMON como\n"
	.string "profesión.\p"
	.string "$"

gOakSpeech_Text_TellMeALittleAboutYourself::
	.string "Bueno, cuéntame algo de ti.\p"
	.string "$"

gOakSpeech_Text_YourNameWhatIsIt::
	.string "Pero primero dime cómo te llamas.\p"
	.string "\n"
	.string "$"

gOakSpeech_Text_SoYourNameIsPlayer::
	.string "¡Bien!\n"
	.string "¡Así que te llamas {PLAYER}!$"

gOakSpeech_Text_WhatWasHisName::
	.string "Éste es mi nieto.\p"
	.string "Ha sido tu rival desde que erais\n"
	.string "pequeños.\p"
	.string "Mmm... ¿podrías decirme cómo\n"
	.string "se llama?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
	.string "¿Cómo era el nombre de tu rival?$"

gOakSpeech_Text_ConfirmRivalName::
	.string "Eh..., ¿era {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
	.string "¡Ah, sí! ¡Es verdad!\n"
	.string "¡Se llamaba {RIVAL}!\p"
	.string "$"

gOakSpeech_Text_LetsGo::
	.string "¡{PLAYER}!\p"
	.string "¡Tu propia leyenda POKéMON está\n"
	.string "a punto de comenzar!\p"
	.string "¡Te espera un mundo de sueños y\n"
	.string "aventuras con los POKéMON!\l"
	.string "¡Adelante!$"
