Text_ObtainedTheX::
	.string "¡Obtuviste {STR_VAR_2}!$"

Text_BagIsFull::
	.string "La MOCHILA está llena...$"

Text_PutItemAway::
	.string "{PLAYER} puso {STR_VAR_2}\n"
	.string "en el {STR_VAR_3}.$"

Text_FoundOneItem::
	.string "¡{PLAYER} encontró {STR_VAR_2}!$"

Text_TooBadBagFull::
	.string "¡Mala suerte!\n"
	.string "La MOCHILA está llena...$"

Text_FoundXCoins::
	.string "¡{PLAYER} encontró\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase::
	.string "{PLAYER} puso las FICHAS\n"
	.string "en el MONEDERO.$"

Text_CoinCaseIsFull::
	.string "¡Vaya!\n"
	.string "¡Tienes el MONEDERO lleno!...$"

Text_NothingToPutThemIn::
	.string "¡Vaya!\n"
	.string "¡No tienes MONEDERO!...$"

Text_FoundXItems::
	.string "{PLAYER} encontró estas unidades\n"
	.string "de {STR_VAR_2}: ¡{STR_VAR_1}!$"

Text_ObtainedTheDecor::
	.string "¡Obtuviste {STR_VAR_2}!$"

Text_NoRoomForAnotherDecor::
	.string "¡Mala suerte! No queda sitio\n"
	.string "para {STR_VAR_2}...$"

Text_DecorTransferredToPC::
	.string "Se envió {STR_VAR_2} al PC.$"
