Text_BootedUpPC::
	.string "{PLAYER} encendió el PC.$"

Text_AccessWhichPC::
	.string "¿A qué PC quieres acceder?$"

Text_AccessedSomeonesPC::
	.string "Accedió al PC de alguien.$"

Text_OpenedPkmnStorage::
	.string "Acceso al Sistema de\n"
	.string "Almacenamiento de POKéMON\l"
	.string "concedido.$"

Text_AccessedPlayersPC::
	.string "Accedió al PC de {PLAYER}.$"

Text_AccessedBillsPC::
	.string "Accedió al PC de BILL.$"
