Text_MayIHelpYou::
	.string "¡Hola! ¿Puedo ayudarte en algo?$"

Text_FillOutQuestionnaire::
	.string "Hay un cuestionario.\n"
	.string "¿Quieres rellenarlo?$"

Text_QuestionnaireThankYou::
	.string "Gracias por rellenar el\n"
	.string "cuestionario. Usaremos tus\l"
	.string "respuestas a modo de referencia.$"

Text_YouKnowThoseWords::
	.string "Hola, ¿conoces las palabras?\p"
	.string "Pues entonces debes de saber\n"
	.string "de qué va el REGALO MISTERIOSO.\p"
	.string "¡A partir de ahora, podrás recibir\n"
	.string "REGALOS MISTERIOSOS!$"

Text_YouCanAccessMysteryGift::
	.string "Una vez guardes la partida, podrás\n"
	.string "acceder al REGALO MISTERIOSO.$"

Text_ThankYouForAccessingMysteryGift::
	.string "Gracias por acceder al sistema\n"
	.string "del REGALO MISTERIOSO.$"
