Text_MakingPreparations::
	.string "じゅんびちゅうです！$"

Text_WantWhichFloor::
	.string "¿A qué piso quieres ir?$"

Text_BagItemCanBeRegistered::
	.string "Puedes asignar cualquier objeto de\n"
	.string "la MOCHILA al Botón SELECT.$"

@ Unused (email from R/S Rivals computer)
Text_TrainerSchoolEmail::
	.string "パソコンに\n"
	.string "ポケモン　トレーナー　こうざの\l"
	.string "メールが　きている！\p"
	.string "‥‥　‥‥　‥‥\p"
	.string "ポケモンが　おぼえられる　わざは　4つ！\p"
	.string "どんな　わざを　おぼえさせるかで\n"
	.string "トレーナーの　じつりょくが　とわれます！\p"
	.string "‥‥　‥‥　‥‥$"

Text_PlayerBootedUpPC::
	.string "{PLAYER} encendió el PC.$"

@ Unused
Text_LinkWasCanceled::
	.string "つうしんは　キャンセルされました$"

@ Unused
Text_GiveNicknameToReceivedMon::
	.string "¿Quieres dar un nombre al\n"
	.string "{STR_VAR_2} que has recibido?$"

gText_PkmnFainted3::
	.string "{STR_VAR_1} se debilitó... \p"
	.string "$"

Text_WelcomeWantToHealPkmn::
	.string "¡Éste es el CENTRO POKéMON!\p"
	.string "Nosotros curamos a los POKéMON\n"
	.string "debilitados.\p"
	.string "¿Quieres que nos ocupemos de los\n"
	.string "POKéMON de tu equipo?$"

Text_TakeYourPkmnForFewSeconds::
	.string "Muy bien. Ten un poco de\n"
	.string "paciencia. Será sólo un momento.$"

Text_WeHopeToSeeYouAgain::
	.string "¡Vuelve siempre que quieras!$"

Text_RestoredPkmnToFullHealth::
	.string "Gracias por esperar.\p"
	.string "Misión cumplida. Somos especialistas\n"
	.string "en devolver la forma a los\l"
	.string "POKéMON.$"
