Text_CardKeyOpenedDoor::
	.string "¡Bingo! ¡La LLAVE MAGNÉTICA\n"
	.string "abrió la puerta!$"

Text_ItNeedsCardKey::
	.string "¡Caray!\n"
	.string "¡Necesito una LLAVE MAGNÉTICA!$"

Text_AccessedProfOaksPC::
	.string "Accedes al PC del PROF. OAK.\p"
	.string "Accedes al Sistema de Evaluación\n"
	.string "de la POKéDEX.$"

Text_HavePokedexRated::
	.string "¿Quieres evaluar tu POKéDEX?$"

Text_ClosedLinkToProfOaksPC::
	.string "Cerrado el enlace al PC del PROF.\n"
	.string "OAK.$"

Text_VoiceRangOutDontRunAway::
	.string "Alguien ha dicho:\n"
	.string "“¡No huyas!”$"

@ Uncear what the below unused JP texts were for
Text_IdLikeToSeeRequest::
	.string "えっとー\n"
	.string "{STR_VAR_2}が　みてみたいなー\p"
	.string "それも　{STR_VAR_1}{STR_VAR_3}\n"
	.string "{STR_VAR_2}が　みてみたいなー$"

Text_ThankYouForShowingMe::
	.string "わぁー　すごい！\n"
	.string "{STR_VAR_1}{STR_VAR_3}{STR_VAR_2}だー！\p"
	.string "ありがとー\n"
	.string "また　よろしくねー！$"

Text_ThatsNotRight::
	.string "それっ　ちがうよー！$"

Text_ISee::
	.string "そっか‥$"

Text_TheDoorIsClosed::
	.string "ドアは　しまっている‥$"

Text_TheDoorIsOpen::
	.string "La puerta está abierta...$"
