gText_WouldYouLikeToSaveTheGame::
	.string "¿Quieres guardar la partida?$"

gText_AlreadySaveFile_WouldLikeToOverwrite::
	.string "Ya hay una partida guardada.\n"
	.string "¿Quieres sobrescribirla?$"

gText_SavingDontTurnOffThePower::
	.string "GUARDANDO...\n"
	.string "NO APAGUES LA CONSOLA.$"

gText_PlayerSavedTheGame::
	.string "{PLAYER} guardó la partida.$"

gText_SaveFailed2::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile::
	.string "¡ATENCIÓN!\p"
	.string "Ya hay una partida guardada.\p"
	.string "Si guardas, perderás los datos\n"
	.string "de la partida incluyendo los\l"
	.string "objetos y los POKéMON.\p"
	.string "¿Seguro que quieres guardar ahora\n"
	.string "y sobrescribir los otros datos?$"
