@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight::
	.string "Mmm...\n"
	.string "Qué curioso...$"

PalletTown_Text_OhLookLook::
	.string "¡Eh, mira, mira!$"

PalletTown_Text_ReadItReadIt::
	.string "¡Mira lo que pone aquí, léelo!$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu::
	.string "PISTAS ENTRENADOR\p"
	.string "¡Pulsa START para abrir el MENÚ!$"

PalletTown_Text_SignsAreUsefulArentThey::
	.string "Es básico leer lo que pone en los\n"
	.string "carteles, ¿no te parece?$"

PalletTown_Text_LookCopiedTrainerTipsSign::
	.string "¡Mira, mira!\p"
	.string "He copiado lo que ponía en uno\n"
	.string "de los carteles de PISTAS\l"
	.string "ENTRENADOR.$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy::
	.string "PISTAS ENTRENADOR\p"
	.string "¡Pulsa START para abrir el MENÚ!$"
