VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "La batería no está cargada\n"
	.string "del todo.\p"
	.string "Los pasos que te faltan para\n"
	.string "cargarla son: {STR_VAR_1}.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "No hay ENTRENADORES cerca contra\n"
	.string "los que poder luchar...\p"
	.string "El BUSCAPELEA se ha apagado.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "No parece que los otros\n"
	.string "ENTRENADORES estén listos\l"
	.string "para luchar.\p"
	.string "Habrá que esperar un poco.{PAUSE_UNTIL_PRESS}.$"

Route3_Text_ColtonRematchIntro::
	.string "¡Nos vimos en el BOSQUE VERDE!$"

Route3_Text_BenRematchIntro::
	.string "¡Hola!\n"
	.string "¡Me gustan los pantalones cortos!\p"
	.string "¡Son muy cómodos!$"

Route3_Text_JaniceRematchIntro::
	.string "Estabas mirándome ¿verdad?$"

Route3_Text_GregRematchIntro::
	.string "¿Entrenas POKéMON?\n"
	.string "¡Pues luchemos!$"

Route3_Text_SallyRematchIntro::
	.string "¡Esa mirada tuya fue de lo más\n"
	.string "misteriosa!$"

Route3_Text_CalvinRematchIntro::
	.string "¡Oye!\n"
	.string "¡No llevas pantalón corto!$"

Route3_Text_JamesRematchIntro::
	.string "Lucharé contigo junto a los\n"
	.string "POKéMON que yo mismo he criado.$"

Route3_Text_RobinRematchIntro::
	.string "¡Eh!\n"
	.string "¡Me has empujado!$"

Route4_Text_CrissyRematchIntro::
	.string "A mí me encanta buscar POKéMON\n"
	.string "hongo en el MT. MOON.$"

Route6_Text_RickyRematchIntro::
	.string "¡Tu eres la pesadilla que nos\n"
	.string "dio la paliza!$"

Route6_Text_NancyRematchIntro::
	.string "Perdona, ¿no ves que es una\n"
	.string "conversación privada?\p"
	.string "Pues ¿qué haces con la antena\n"
	.string "puesta?$"

Route6_Text_KeigoRematchIntro::
	.string "Estoy intentando encontrar un buen\n"
	.string "ejemplar, que no sea un POKéMON\l"
	.string "BICHO, pero...$"

Route6_Text_JeffRematchIntro::
	.string "¿Qué? ¿Qué quieres, luchar\n"
	.string "conmigo de nuevo?$"

Route6_Text_IsabelleRematchIntro::
	.string "¿Yo?\n"
	.string "Pues vale. ¡Vamos!$"

Route6_Text_ElijahRematchIntro::
	.string "Eh, ¡qué de tiempo!\n"
	.string "¿Eres más fuerte?$"

Route8_Text_AidanRematchIntro::
	.string "Se te dan bien los POKéMON, pero\n"
	.string "¿qué tal en química?$"

Route8_Text_StanRematchIntro::
	.string "¡Muy bien!\n"
	.string "¡Luchemos otra vez!$"

Route8_Text_GlennRematchIntro::
	.string "¡Necesitas una buena estrategia!\p"
	.string "¿Te queda claro?$"

Route8_Text_PaigeRematchIntro::
	.string "Tengo muchos NIDORAN.\n"
	.string "No quiero que evolucionen, pero...$"

Route8_Text_LeslieRematchIntro::
	.string "¡Me gusta el colegio y los\n"
	.string "POKéMON!$"

Route8_Text_AndreaRematchIntro::
	.string "¡MEOWTH y PERSIAN son ideales,\n"
	.string "ideales totales, meow, meow, meow!$"

Route8_Text_MeganRematchIntro::
	.string "Debemos de dar una imagen algo\n"
	.string "tonta, pero ¡lo importante es que\l"
	.string "yo quiero luchar!$"

Route8_Text_RichRematchIntro::
	.string "¡Soy un jugador errante!\n"
	.string "¡Y voy a ganar!$"

Route8_Text_JuliaRematchIntro::
	.string "¿Qué POKéMON es mono, redondo\n"
	.string "y blando?\p"
	.string "Lo sabes, ¿no?$"

Route8_Text_RicardoRematchIntro::
	.string "¡Mi bici sigue yendo como\n"
	.string "una moto!$"

Route8_Text_JarenRematchIntro::
	.string "Bueno, esta vez no me voy\n"
	.string "a andar con tonterías.$"

Route8_Text_EliRematchIntro::
	.string "TITA: ¡Ahora somos más fuertes!$"

Route8_Text_AnneRematchIntro::
	.string "LIN: ¡Ya somos mucho más fuertes!$"

Route9_Text_AliciaRematchIntro::
	.string "¿Vamos a luchar de nuevo?\n"
	.string "¡Pues esta vez, olvídate!$"

Route9_Text_ChrisRematchIntro::
	.string "Tú eras quien tenía esos POKéMON\n"
	.string "tan bonitos...$"

Route9_Text_DrewRematchIntro::
	.string "Quiero tomar el TÚNEL ROCA\n"
	.string "para ir a LAVANDA.\p"
	.string "¡Pero cada dos por tres se cruza\n"
	.string "alguien en mi camino!...$"

Route9_Text_CaitlinRematchIntro::
	.string "¡No te andes con contemplaciones!\n"
	.string "¡Hay que ir a por todas!$"

Route9_Text_JeremyRematchIntro::
	.string "¡Qué bien! ¡Me estaba aburriendo\n"
	.string "otra vez!$"

Route9_Text_BriceRematchIntro::
	.string "¡Jaja! ¡A ver lo fuerte que estás!$"

Route9_Text_BrentRematchIntro::
	.string "Cada día me levanto temprano para\n"
	.string "entrenar a mis POKéMON capullo.$"

Route9_Text_AlanRematchIntro::
	.string "¡Esta vez gano yo!$"

Route9_Text_ConnerRematchIntro::
	.string "¡Adelante de nuevo, mis geniales\n"
	.string "POKéMON BICHO!$"

Route10_Text_MarkRematchIntro::
	.string "Aquí estás otra vez...\n"
	.string "¿Eres como los POKéMANÍACOS?\l"
	.string "¿Quieres ver mi colección?$"

Route10_Text_ClarkRematchIntro::
	.string "¡A-a-a-achís!\n"
	.string "¡No puedo dejar de estornudar!$"

Route10_Text_HermanRematchIntro::
	.string "¡Hola!\n"
	.string "¿Te llegué a enseñar mis POKéMON?$"

Route10_Text_HeidiRematchIntro::
	.string "He vuelto a ir al GIMNASIO\n"
	.string "POKéMON.\p"
	.string "Pero he perdido, como siempre...$"

Route10_Text_TrentRematchIntro::
	.string "¡Me encanta el aire de montaña!\n"
	.string "¡Es tan bueno! ¡Me encanta!$"

Route10_Text_CarolRematchIntro::
	.string "Me está empezando a dar vueltas la\n"
	.string "cabeza. Llevo mucho escalando...$"

Route11_Text_HugoRematchIntro::
	.string "¡Gana, pierde o empata!\n"
	.string "¡Pero lucha de nuevo!$"

Route11_Text_JasperRematchIntro::
	.string "¡Competir es lo más!\n"
	.string "¡Yo no me canso de competir!$"

Route11_Text_EddieRematchIntro::
	.string "¿Luchamos otra vez?\n"
	.string "¡Vamos allá, pero no hagas\l"
	.string "trampas!$"

Route11_Text_BraxtonRematchIntro::
	.string "¡Eh, tú!\p"
	.string "¡Cuidado!\n"
	.string "¡Estoy colocando unos cables!$"

Route11_Text_DillonRematchIntro::
	.string "¡Soy un nuevo ENTRENADOR!\n"
	.string "¡Pero creo que no tengo problema\l"
	.string "para ganar!$"

Route11_Text_DirkRematchIntro::
	.string "¡Ja, ja, ja!\n"
	.string "¡No he perdido nunca!\p"
	.string "¡Y si he perdido alguna vez,\n"
	.string "no me acuerdo!$"

Route11_Text_DarianRematchIntro::
	.string "Nunca he ganado...\p"
	.string "¿Será mi destino?$"

Route11_Text_YasuRematchIntro::
	.string "¡Soy el mejor de mi clase!\n"
	.string "¡Me entreno día y noche!$"

Route11_Text_BernieRematchIntro::
	.string "¡Cuidado con esos cables!$"

Route11_Text_DaveRematchIntro::
	.string "¡Mis POKéMON ya deberían estar\n"
	.string "listos! ¡Esta vez hay que ganar!$"

Route12_Text_NedRematchIntro::
	.string "¡Bien!\n"
	.string "¡Ha picado algo!\l"
	.string "¡Esta vez seguro que es bueno!$"

Route12_Text_ChipRematchIntro::
	.string "¡Aquí estás otra vez!\n"
	.string "¡Pescar requiere tiempo!$"

Route12_Text_JustinRematchIntro::
	.string "Sigo sin PIEDRA LUNAR...\n"
	.string "¿Tienes tú una?$"

Route12_Text_LucaRematchIntro::
	.string "¡Soy un experto en electricidad!\p"
	.string "Pero de los POKéMON de agua\n"
	.string "sé poca cosa...$"

Route12_Text_HankRematchIntro::
	.string "¡El PESCADOR LOCO contra alguien\n"
	.string "que no tiene idea sobre POKéMON!\l"
	.string "¡Lucha, venga!$"

Route12_Text_ElliotRematchIntro::
	.string "A mí me encanta pescar, pero no\n"
	.string "es nada fácil que piquen, ¿sabes?$"

Route12_Text_AndrewRematchIntro::
	.string "¿No sabes cómo pescar?\p"
	.string "¡Te lo explicaré cuando acabe\n"
	.string "contigo!$"

Route12_Text_JesRematchIntro::
	.string "ARE: Voy a ganar y a pedirle a\n"
	.string "AGA que se case conmigo.$"

Route12_Text_GiaRematchIntro::
	.string "AGA: Oye, ARE, estoy aburrida\n"
	.string "de esperar...\p"
	.string "Si ganamos, ¡me caso contigo!$"

Route13_Text_SebastianRematchIntro::
	.string "¡Mis pájaros POKéMON se acuerdan\n"
	.string "de ti!$"

Route13_Text_SusieRematchIntro::
	.string "Quiero ser la mejor ENTRENADORA\n"
	.string "siendo todavía pequeña.$"

Route13_Text_ValerieRematchIntro::
	.string "¡Guau!\n"
	.string "¡Qué chulas son tus MEDALLAS!$"

Route13_Text_GwenRematchIntro::
	.string "Mis simpáticos POKéMON quieren\n"
	.string "volver a verte.$"

Route13_Text_AlmaRematchIntro::
	.string "Me he gastado mis ahorros\n"
	.string "comprando más CARBURANTE.$"

Route13_Text_PerryRematchIntro::
	.string "¡Esta vez no pienso perder!\n"
	.string "¡El viento sopla en mi dirección!$"

Route13_Text_LolaRematchIntro::
	.string "Has vuelto...\p"
	.string "Por supuesto que lucharé\n"
	.string "otra vez contigo.$"

Route13_Text_SheilaRematchIntro::
	.string "¿No te acuerdas de que luchamos\n"
	.string "en otra ocasión?$"

Route13_Text_JaredRematchIntro::
	.string "¿Qué miras?$"

Route13_Text_RobertRematchIntro::
	.string "¡Me encantan los pájaros POKéMON!\n"
	.string "¡Siempre me he dedicado a ellos!$"

Route14_Text_CarterRematchIntro::
	.string "He usado mis MT para enseñarles\n"
	.string "buenos movimientos a mis POKéMON.$"

Route14_Text_MitchRematchIntro::
	.string "Mis pájaros POKéMON deberían\n"
	.string "luchar bien esta vez.$"

Route14_Text_BeckRematchIntro::
	.string "¿Usas MT con tus POKéMON?\n"
	.string "Tenerlas en la MOCHILA sin más\l"
	.string "no sirve para nada.$"

Route14_Text_MarlonRematchIntro::
	.string "¿Has enseñado a VOLAR a tus\n"
	.string "pájaros POKéMON?\p"
	.string "Deberías hacerlo y disfrutar de\n"
	.string "la maravillosa vista.$"

Route14_Text_DonaldRematchIntro::
	.string "¿Llegaste a oír hablar de los\n"
	.string "misteriosos seres alados?$"

Route14_Text_BennyRematchIntro::
	.string "¡No me apetece luchar,\n"
	.string "pero lo haré!$"

Route14_Text_LukasRematchIntro::
	.string "¡Eh, me acuerdo de ti!\p"
	.string "¡Venga, venga!\n"
	.string "¡Vamos, vamos! ¡Adelante!$"

Route14_Text_IsaacRematchIntro::
	.string "Aquí estás otra vez, ¿eh?\n"
	.string "¡Bueno, así pasaré el rato!$"

Route14_Text_GeraldRematchIntro::
	.string "¡Nos gusta pedalear por aquí\n"
	.string "porque hay mucho espacio!$"

Route14_Text_MalikRematchIntro::
	.string "¿Quieres pelear con tus POKéMON?\n"
	.string "¡Pues vale, vamos allá!$"

Route14_Text_KiriRematchIntro::
	.string "LENA: TEA, a ver si ganamos.$"

Route14_Text_JanRematchIntro::
	.string "TEA: LENA, ¡vamos allá!\n"
	.string "¡Tenemos que ganar!$"

Route15_Text_KindraRematchIntro::
	.string "¡Déjame probar los POKéMON\n"
	.string "que me han enviado!$"

Route15_Text_BeckyRematchIntro::
	.string "¡Creo que puedo contigo!\n"
	.string "¡Voy a intentar vencerte!$"

Route15_Text_EdwinRematchIntro::
	.string "Cuando silbo, acuden varios\n"
	.string "pájaros POKéMON.\p"
	.string "¡Son monísimos!$"

Route15_Text_ChesterRematchIntro::
	.string "Mis pájaros están temblando.\n"
	.string "¡Ya te conocen!$"

Route15_Text_GraceRematchIntro::
	.string "¡Oh!\n"
	.string "¡Mira qué encanto!\l"
	.string "¡Anda, yo a ti te conozco!$"

Route15_Text_OliviaRematchIntro::
	.string "¡Cuido POKéMON porque sigo\n"
	.string "viviendo sola!$"

Route15_Text_ErnestRematchIntro::
	.string "¡Oye! ¡Ven aquí!\n"
	.string "¡Mira esto!$"

Route15_Text_AlexRematchIntro::
	.string "¡Mira, colega, si pierdes contra\n"
	.string "mí, todo tu dinero será mío!$"

Route15_Text_CeliaRematchIntro::
	.string "¿Qué mola?\n"
	.string "¡Cambiar POKéMON, claro!$"

Route15_Text_YazminRematchIntro::
	.string "¿Quieres jugar con mis POKéMON\n"
	.string "otra vez?$"

Route15_Text_MyaRematchIntro::
	.string "TINA: ¡Volvemos a vernos!\p"
	.string "¿Luchamos para que aprenda\n"
	.string "mi hermano?$"

Route15_Text_RonRematchIntro::
	.string "TIN: Mi hermana es la más fuerte.$"

Route16_Text_LaoRematchIntro::
	.string "¿Qué quieres?$"

Route16_Text_KojiRematchIntro::
	.string "¡Bonita BICI!\n"
	.string "¡Dámela ahora mismo!$"

Route16_Text_LukeRematchIntro::
	.string "¡Baja de ahí y lucha, enclenque!\n"
	.string "¡Te vas a enterar!$"

Route16_Text_HideoRematchIntro::
	.string "¡Oye! ¡Me has golpeado!\n"
	.string "¡Ahora tendrás que luchar conmigo!$"

Route16_Text_CamronRematchIntro::
	.string "¡Tengo hambre y sigo sin estar\n"
	.string "de humor!$"

Route16_Text_RubenRematchIntro::
	.string "¡Eh, vamos a echar otro rato!$"

Route16_Text_JedRematchIntro::
	.string "JOEL: ¿Vienes para comprobar que\n"
	.string "nuestro amor no conoce límites?$"

Route16_Text_LeaRematchIntro::
	.string "LIZ: ¡A veces, pienso en todo\n"
	.string "lo que nos queremos y se me pone\l"
	.string "la carne de gallina!$"

Route17_Text_RaulRematchIntro::
	.string "¡Ya te dije que no compensaba\n"
	.string "luchar con niños!$"

Route17_Text_IsaiahRematchIntro::
	.string "¿Y tú qué quieres?$"

Route17_Text_VirgilRematchIntro::
	.string "¿Qué vas, de paseo?$"

Route17_Text_BillyRematchIntro::
	.string "¡Somos los MOTORISTAS!\n"
	.string "¡Las estrellas de la autopista!$"

Route17_Text_NikolasRematchIntro::
	.string "Mis VOLTORB van a darte\n"
	.string "un calambrazo.$"

Route17_Text_ZeekRematchIntro::
	.string "¡Mi POKéMON no evoluciona!\n"
	.string "No acabo de entender por qué.$"

Route17_Text_JamalRematchIntro::
	.string "¡Necesito un poco de ejercicio\n"
	.string "y bajar peso!$"

Route17_Text_CoreyRematchIntro::
	.string "¡Sé rebelde!$"

Route17_Text_JaxonRematchIntro::
	.string "¡Tienes una BICI muy guay!\n"
	.string "¿Cómo se conduce?$"

Route17_Text_WilliamRematchIntro::
	.string "¡Lárgate!\n"
	.string "¡Estoy agotado!$"

Route18_Text_WiltonRematchIntro::
	.string "Compruebo siempre las zonas de\n"
	.string "hierba en busca de nuevos POKéMON.\p"
	.string "Pero no siempre encuentro...$"

Route18_Text_RamiroRematchIntro::
	.string "¡Cucu, cucu! ¿Ha mejorado\n"
	.string "el reclamo de mi pájaro?$"

Route18_Text_JacobRematchIntro::
	.string "¡Es mi césped!\n"
	.string "¡Fuera de aquí!\p"
	.string "¡No quiero volver a verte por\n"
	.string "aquí!$"

Route19_Text_RichardRematchIntro::
	.string "Estaba a punto de darme un baño.$"

Route19_Text_ReeceRematchIntro::
	.string "¡Alto!\n"
	.string "¡Oye, que te va a dar algo!$"

Route19_Text_MatthewRematchIntro::
	.string "¡Me gusta nadar!\n"
	.string "Seguro que a ti también.$"

Route19_Text_DouglasRematchIntro::
	.string "¿Qué hay más allá del horizonte?\n"
	.string "¿Lo sabes?$"

Route19_Text_DavidRematchIntro::
	.string "¡He buceado en busca de POKéMON,\n"
	.string "pero sigo sin ver nada!$"

Route19_Text_TonyRematchIntro::
	.string "¡Miro al mar para olvidar!\p"
	.string "Quiero olvidarme de cuando perdí\n"
	.string "contigo.$"

Route19_Text_AnyaRematchIntro::
	.string "¡Me encanta el POKéMON con\n"
	.string "el que estás haciendo SURF.\p"
	.string "¿Me lo darás si gano?$"

Route19_Text_AliceRematchIntro::
	.string "¡Nadar es genial! ¡Pero no me\n"
	.string "gusta quemarme al sol!$"

Route19_Text_AxleRematchIntro::
	.string "¡Estas aguas son traicioneras!\n"
	.string "¡No deberías volver por aquí!$"

Route19_Text_ConnieRematchIntro::
	.string "He venido nadando hasta aquí,\n"
	.string "pero ya me he cansado.\p"
	.string "¿De verdad tenemos que luchar\n"
	.string "otra vez?$"

Route19_Text_LiaRematchIntro::
	.string "CATI: Ya sabes que mi hermano\n"
	.string "acaba de hacerse ENTRENADOR.\p"
	.string "Vamos a luchar para que mejore\n"
	.string "su técnica, ¿vale?$"

Route19_Text_LucRematchIntro::
	.string "TEC: Mi hermana mayor me ha\n"
	.string "enseñado mucho sobre POKéMON.\p"
	.string "¿Soy mejor ahora?$"

Route20_Text_BarryRematchIntro::
	.string "El agua es poco profunda aquí.$"

Route20_Text_ShirleyRematchIntro::
	.string "¿Te da envidia que esté de\n"
	.string "vacaciones en las ISLAS ESPUMA?$"

Route20_Text_TiffanyRematchIntro::
	.string "¡Me gusta flotar en el agua\n"
	.string "rodeada de peces!$"

Route20_Text_IreneRematchIntro::
	.string "¿Tú también estabas de vacaciones?$"

Route20_Text_DeanRematchIntro::
	.string "¡Mira que cuerpazo tengo!\p"
	.string "¡Estoy mejor que antes!$"

Route20_Text_DarrinRematchIntro::
	.string "¿Por qué te has subido a un\n"
	.string "POKéMON? ¿Aún no sabes nadar?$"

Route20_Text_RogerRematchIntro::
	.string "¡Ha venido sobre uno de mis\n"
	.string "pájaros POKéMON!$"

Route20_Text_NoraRematchIntro::
	.string "¡Mi novio me dio unas perlas\n"
	.string "muy grandes!\p"
	.string "¡Y ahora están más grandes aún!$"

Route20_Text_MissyRematchIntro::
	.string "Vine nadando desde ISLA\n"
	.string "CANELA. Fue agotador.$"

Route20_Text_MelissaRematchIntro::
	.string "En ISLA CANELA, al oeste, hay\n"
	.string "un LABORATORIO POKéMON.\p"
	.string "Mi padre trabaja allí.$"

Route21_North_Text_RonaldRematchIntro::
	.string "¿Quieres saber si los peces pican?$"

Route21_North_Text_WadeRematchIntro::
	.string "¡Tengo una gran red!\n"
	.string "¿Quieres probarla otra vez?$"

Route21_North_Text_SpencerRematchIntro::
	.string "¡El mar limpia mi cuerpo y mi\n"
	.string "alma!$"

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro::
	.string "きょうも　およぎに\n"
	.string "きちまったぜ$"

Route21_South_Text_JackRematchIntro::
	.string "¡He conseguido a mi POKéMON\n"
	.string "en el mar, y aquí lo entreno!$"

Route21_South_Text_JeromeRematchIntro::
	.string "¡Ahora estoy en otro encuentro\n"
	.string "de triatlón!$"

Route21_South_Text_RolandRematchIntro::
	.string "¡Ah!\n"
	.string "¡Siente el sol y el viento!$"

Route21_South_Text_ClaudeRematchIntro::
	.string "¡Eh!\n"
	.string "¡Siempre asustas a los peces!$"

Route21_South_Text_NolanRematchIntro::
	.string "¡Quédate conmigo hasta que lo\n"
	.string "consiga!$"

Route21_North_Text_LilRematchIntro::
	.string "ÍA: ¿Cómo, que quieres luchar otra\n"
	.string "vez? IGOR, ¿cómo lo ves?$"

Route21_North_Text_IanRematchIntro::
	.string "IGOR: Mi hermana es un pelín vaga,\n"
	.string "¡pero si hay que luchar, hay que\l"
	.string "luchar!$"

Route25_Text_JoeyRematchIntro::
	.string "¡No pienso perder!$"

Route25_Text_DanRematchIntro::
	.string "¡Mi padre me llevó a una gran\n"
	.string "fiesta en el S.S. ANNE, en\l"
	.string "CIUDAD CARMÍN!$"

Route25_Text_FlintRematchIntro::
	.string "Soy un buen chico.\n"
	.string "¡Y tengo novia!\p"
	.string "¡Verás cómo se queda cuando\n"
	.string "me vea luchar esta vez!$"

Route25_Text_KelseyRematchIntro::
	.string "¡Hola!\n"
	.string "¡Mi chico es genial!\l"
	.string "¡Y hoy me encuentro en forma!$"

Route25_Text_ChadRematchIntro::
	.string "¡Sabía que tendría que luchar\n"
	.string "contigo otra vez!$"

Route25_Text_HaleyRematchIntro::
	.string "Mi amigo tiene POKéMON muy\n"
	.string "monos. ¡Qué envidia!$"

Route25_Text_FranklinRematchIntro::
	.string "¡Acabo de bajar del MT. MOON,\n"
	.string "pero estoy listo!$"

Route25_Text_NobRematchIntro::
	.string "¡Hay un POKéMANÍACO viviendo\n"
	.string "en el cabo!\p"
	.string "¿Has visto la colección que tiene?$"

Route25_Text_WayneRematchIntro::
	.string "¿Vas a ver a BILL otra vez?\n"
	.string "¡Pues luchemos primero!$"

Route24_Text_ShaneRematchIntro::
	.string "¡Vi tu hazaña desde la hierba!$"

Route24_Text_EthanRematchIntro::
	.string "¡Muy bien, voy a acabar contigo!$"

Route24_Text_ReliRematchIntro::
	.string "Siempre estás de aquí para allá...\n"
	.string "¿No te cansas?$"

Route24_Text_TimmyRematchIntro::
	.string "Se ve que te encanta venir\n"
	.string "al PUENTE PEPITA.$"

Route24_Text_AliRematchIntro::
	.string "Aunque perdí cuando luchamos,\n"
	.string "estuvo guay, ¿verdad?$"

Route24_Text_CaleRematchIntro::
	.string "Éste es el PUENTE PEPITA.\p"
	.string "Ya nos has machacado a todos,\n"
	.string "así que ya te puedes marchar...\p"
	.string "Aunque... no me importaría\n"
	.string "volver a enfrentarme a ti.$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
	.string "Se me pasa el tiempo volando\n"
	.string "cuando estoy disfrutando del agua,\l"
	.string "del vaivén de las olas...$"

OneIsland_KindleRoad_Text_MariaRematchIntro::
	.string "Hace un tiempo espléndido,\n"
	.string "no lo estropees.$"

OneIsland_KindleRoad_Text_AbigailRematchIntro::
	.string "Está empezando a dolerme la piel\n"
	.string "por las quemaduras.$"

OneIsland_KindleRoad_Text_FinnRematchIntro::
	.string "El MT. ASCUAS hace una sombra\n"
	.string "gigante.$"

OneIsland_KindleRoad_Text_GarrettRematchIntro::
	.string "Tengo la sensación de que esta vez\n"
	.string "te voy a ganar.$"

OneIsland_KindleRoad_Text_TommyRematchIntro::
	.string "¡Eh, eh, un momento!\n"
	.string "¡Sé que he pescado algo grande!$"

OneIsland_KindleRoad_Text_SharonRematchIntro::
	.string "¿Me ayudas a entrenarme otra vez?$"

OneIsland_KindleRoad_Text_TanyaRematchIntro::
	.string "No me pierdo ni un día de\n"
	.string "entrenamiento.$"

OneIsland_KindleRoad_Text_SheaRematchIntro::
	.string "Cada mañana, antes de desayunar,\n"
	.string "rodeo a nado la isla.\l"
	.string "¡Lo hago hasta tres veces!$"

OneIsland_KindleRoad_Text_HughRematchIntro::
	.string "¡Para luchar hay que llevar ropa\n"
	.string "adecuada! ¡Vaya pintas tienes!$"

OneIsland_KindleRoad_Text_BryceRematchIntro::
	.string "Cuando se está al aire libre, todo\n"
	.string "sabe mejor.$"

OneIsland_KindleRoad_Text_ClaireRematchIntro::
	.string "He vuelto a comer demasiado,\n"
	.string "¿luchamos para hacer algo\l"
	.string "de ejercicio?$"

OneIsland_KindleRoad_Text_KiaRematchIntro::
	.string "PÍA: ¡Mi hermano mayor y yo\n"
	.string "hacemos un equipo increíble!\p"
	.string "¡Esta vez no perderemos!$"

OneIsland_KindleRoad_Text_MikRematchIntro::
	.string "FER: ¡Junto a PÍA no tengo miedo\n"
	.string "de nada!\p"
	.string "¡Esta vez te vas a enterar!$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
	.string "¿Quieres que luchemos de nuevo?$"

ThreeIsland_BondBridge_Text_VioletRematchIntro::
	.string "¿De dónde vienes y adónde vas?$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
	.string "Estoy deseando nadar sin flotador.$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
	.string "¡POKéMON, POKéMON!\n"
	.string "¡A mí me gustan los POKéMON!$"

ThreeIsland_BondBridge_Text_TishaRematchIntro::
	.string "¡No, no, te dije que me dejaras\n"
	.string "en paz!$"

ThreeIsland_BondBridge_Text_JoyRematchIntro::
	.string "FELI: Ahora somos más fuertes.\n"
	.string "¡Mucho más!$"

ThreeIsland_BondBridge_Text_MegRematchIntro::
	.string "MATI: ¡Hoy no podrás con nosotras!$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
	.string "Hola, ¿estás criando tus POKéMON\n"
	.string "en un buen sitio?$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
	.string "¡Voy a alcanzar la victoria con mis\n"
	.string "propias manos!$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
	.string "¿Cuántas veces tengo que\n"
	.string "decírtelo? ¡Estoy intentando\l"
	.string "pintar! ¿Te quieres quitar de ahí?$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
	.string "No he avanzado nada...\n"
	.string "No acabo de encontrar el ángulo\l"
	.string "adecuado.$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
	.string "¿Vas a darme otra oportunidad\n"
	.string "para medir mis habilidades contigo?$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
	.string "Ya está casi acabada la piscina\n"
	.string "de mis POKéMON.\p"
	.string "Deberías pasarte para echarle\n"
	.string "un vistazo.$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
	.string "No hay nadie que corra más rápido\n"
	.string "que yo.$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
	.string "¡Eh, vamos a pasar un buen rato\n"
	.string "luchando!$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
	.string "Soy el mayor de los HERMANOS\n"
	.string "PÁJARO.\p"
	.string "Al que le encantaban los pájaros\n"
	.string "por los picos que tienen.$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
	.string "Soy el mediano de los HERMANOS\n"
	.string "PÁJARO.\p"
	.string "Al que le encantaban los pájaros\n"
	.string "por las alas que tienen.$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
	.string "Soy el pequeño de los HERMANOS\n"
	.string "PÁJARO.\p"
	.string "Al que le encantaban los pájaros\n"
	.string "por las plumas que tienen.$"

SixIsland_OutcastIsland_Text_TylorRematchIntro::
	.string "Sigo sin tener suerte...\n"
	.string "¡A ver si luchando contigo entro\l"
	.string "en una buena racha!$"

SixIsland_OutcastIsland_Text_MymoRematchIntro::
	.string "Ufff... Ufff...\p"
	.string "Vengo nadando otra vez desde\n"
	.string "el PUERTO de ISLA EXTA sin parar.$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
	.string "Siempre apareces cuando estoy\n"
	.string "dándome un baño.$"

SixIsland_OutcastIsland_Text_AvaRematchIntro::
	.string "ALI: ¡Vamos a echarnos otro\n"
	.string "combate disfrutando de la brisa\l"
	.string "marina!$"

SixIsland_OutcastIsland_Text_GebRematchIntro::
	.string "ROS: Mi hermanita y yo somos\n"
	.string "más fuertes que antes.$"

SixIsland_GreenPath_Text_JaclynRematchIntro::
	.string "¿Mmm?...\p"
	.string "Me pareció haber elegido mi casa\n"
	.string "con TELETRANSPORTE, pero\l"
	.string "siempre acabo en el mismo sitio.$"

SixIsland_WaterPath_Text_RoseRematchIntro::
	.string "He llegado otra vez hasta aquí\n"
	.string "dejándome llevar por un agradable\l"
	.string "aroma.$"

SixIsland_WaterPath_Text_EdwardRematchIntro::
	.string "Estoy practicando en secreto\n"
	.string "otra vez.$"

SixIsland_WaterPath_Text_SamirRematchIntro::
	.string "¿Perdona? ¿Que no te gusta\n"
	.string "la gente que hace natación\l"
	.string "como yo?\p"
	.string "¡No fastidies!\n"
	.string "¡Vamos a luchar otra vez!$"

SixIsland_WaterPath_Text_DeniseRematchIntro::
	.string "Ufff...\n"
	.string "Mi chico está liado otra vez...$"

SixIsland_WaterPath_Text_EarlRematchIntro::
	.string "Oye, dime dónde están las\n"
	.string "montañas de esta zona, anda.$"

SixIsland_WaterPath_Text_MiuRematchIntro::
	.string "MARU: ¡Queridos POKéMON!\n"
	.string "¡Vamos a jugar otra vez!$"

SixIsland_WaterPath_Text_MiaRematchIntro::
	.string "MÍA: ¡Queridos POKéMON!\n"
	.string "¡Vamos a luchar otra vez!$"

SixIsland_RuinValley_Text_StanlyRematchIntro::
	.string "Creo que en este mundo quedan\n"
	.string "misterios aún por resolver.$"

SixIsland_RuinValley_Text_FosterRematchIntro::
	.string "Yo a ti te conozco...\n"
	.string "¿Qué te trae de nuevo hasta aquí?$"

SixIsland_RuinValley_Text_LarryRematchIntro::
	.string "Dicen que hay misteriosas piedras\n"
	.string "en esta isla.\p"
	.string "¿Has descubierto algo desde\n"
	.string "la última vez que nos vimos?$"

SixIsland_RuinValley_Text_DarylRematchIntro::
	.string "¿Luchar contigo otra vez?\n"
	.string "¡Ahora mismo!$"

SixIsland_RuinValley_Text_HectorRematchIntro::
	.string "Yo me conozco bien toda esta\n"
	.string "zona.$"

SevenIsland_TrainerTower_Text_DarioRematchIntro::
	.string "He notado que te acercabas.$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
	.string "En alguna parte de esta isla,\n"
	.string "hay extraños POKéMON durmiendo.$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
	.string "¡Voy a acabar contigo en un abrir\n"
	.string "y cerrar de ojos!\p"
	.string "¡No te creas que por volver\n"
	.string "vas a ganarme!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
	.string "¡Hola, cara de bola!\n"
	.string "¿Tú no eras de mi club de fans?$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
	.string "Esta isla tiene una extensión muy\n"
	.string "particular, no es fácil patrullar.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
	.string "¡No perdono a quien se pasa con\n"
	.string "los POKéMON!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
	.string "ELE: RUS y yo queremos luchar\n"
	.string "de nuevo contigo.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
	.string "RUS: Cuando estoy con ELE,\n"
	.string "creo que no voy a perder nunca.\l"
	.string "Ahora lo veremos.$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
	.string "Vamos a luchar de nuevo.\n"
	.string "¡Estoy realmente en forma!$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
	.string "Da igual que tengas los POKéMON\n"
	.string "más fuertes...\p"
	.string "¡Lo importante es saber cómo\n"
	.string "manejarlos!$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
	.string "Yo protejo el medio ambiente\n"
	.string "y él me protege a mí.$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
	.string "La última vez que nos vimos,\n"
	.string "llevabas también esos zapatos\l"
	.string "tan llamativos.$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
	.string "¡Debes de ser más fuerte!\n"
	.string "¡Vamos a luchar, anda!$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
	.string "He recibido la mejor educación\n"
	.string "para tener la fuerza que tengo.\p"
	.string "¡No pienso perder esta vez!\n"
	.string "¡Ni en broma!$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
	.string "LINO: Mi adorada ABA, ¡vamos\n"
	.string "a ganar!$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
	.string "ABA: No defraudaré a mi maestro\n"
	.string "LINO. ¡Tenemos que ganar!$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
	.string "¿Has descubierto algo de esta\n"
	.string "cámara de piedra?$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
	.string "Dicen que aquí dentro duerme\n"
	.string "un místico POKéMON.$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
	.string "Mi profe me está enseñando\n"
	.string "nuevas técnicas de pintura.$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
	.string "Hoy, como complemento a la clase,\n"
	.string "hemos venido a visitar la cámara\l"
	.string "otra vez.$"
