SixIsland_GreenPath_Text_JaclynIntro::
	.string "… häh?\p"
	.string "Ich sah mein Haus, aber TELEPORT\n"
	.string "brachte mich hierher?$"

SixIsland_GreenPath_Text_JaclynDefeat::
	.string "Jippie!$"

SixIsland_GreenPath_Text_JaclynPostBattle::
	.string "Ich bin so kopflos!\p"
	.string "Ich muss mich konzentrieren, um\n"
	.string "mit TELEPORT zu meinem\l"
	.string "Haus zu gelangen!$"

SixIsland_GreenPath_Text_LeftRouteSign::
	.string "GRÜNER PFAD\n"
	.string "MUSTERBUSCHWALD VORAUS$"

SixIsland_GreenPath_Text_RightRouteSign::
	.string "GRÜNER PFAD\n"
	.string "Sei umweltbewusst!$"

