SixIsland_GreenPath_Text_JaclynIntro::
    .ifdef ENGLISH
    .string "…Huh?\p"
    .string "I was envisioning my house, but\n"
    .string "this is where I TELEPORT?$"
    .endif
    .ifdef SPANISH
    .string "¿Mmm?...\p"
    .string "Me pareció haber elegido mi casa\n"
    .string "con TELETRANSPORTE, pero...\l"
    .string "¿dónde estoy?$"
    .endif

SixIsland_GreenPath_Text_JaclynDefeat::
    .ifdef ENGLISH
    .string "Big boo-boo!$"
    .endif
    .ifdef SPANISH
    .string "¡Auuuuuch!$"
    .endif

SixIsland_GreenPath_Text_JaclynPostBattle::
    .ifdef ENGLISH
    .string "I am so scatterbrained!\p"
    .string "I need to focus so I can TELEPORT\n"
    .string "properly to my house!$"
    .endif
    .ifdef SPANISH
    .string "No sé muy bien dónde estoy...\p"
    .string "Debo centrarme en TELETRANSPORTE\n"
    .string "para volver a mi casa...$"
    .endif

SixIsland_GreenPath_Text_LeftRouteSign::
    .ifdef ENGLISH
    .string "GREEN PATH\n"
    .string "PATTERN BUSH AHEAD$"
    .endif
    .ifdef SPANISH
    .string "VÍA VERDE\n"
    .string "HACIA EL BOSQUEJO$"
    .endif

SixIsland_GreenPath_Text_RightRouteSign::
    .ifdef ENGLISH
    .string "GREEN PATH\n"
    .string "Think Green, Keep Nature Clean!$"
    .endif
    .ifdef SPANISH
    .string "VÍA VERDE\n"
    .string "¡Hay que tener respeto\l"
    .string "hasta por el último seto!$"
    .endif

