FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
	.string "GARDIEN: Hif fuff hefifou!\p"
	.string "Ha fof ha fif eu hafahi ho.\n"
	.string "Heff hi fwi!$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
	.string "Ah hahee ho hoo!\n"
	.string "Eef ee hafahi ho!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
	.string "Ha?\n"
	.string "Hai fou heh ha hoo ih haheh!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
	.string "{PLAYER} donne la DENT D'OR au\n"
	.string "GARDIEN!$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
	.string "Le GARDIEN peut remettre son\n"
	.string "dentier!$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
	.string "GARDIEN: Merci, gamin! C'était un\n"
	.string "peu dur de me faire comprendre.\p"
	.string "J'pouvais plus travailler!\n"
	.string "Quelle horreur!\p"
	.string "Tiens, voilà pour te remercier.$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
	.string "GARDIEN: Merci, gamine! C'était un\n"
	.string "peu dur de me faire comprendre.\p"
	.string "J'pouvais plus travailler!\n"
	.string "Quelle horreur!\p"
	.string "Tiens, voilà pour te remercier.$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
	.string "{PLAYER} reçoit la\n"
	.string "CS04!$"

FuchsiaCity_WardensHouse_Text_ExplainStrength::
	.string "GARDIEN: la CS04 contient FORCE!\p"
	.string "Tes POKéMON pourront déplacer des\n"
	.string "rochers.\p"
	.string "Au fait, as-tu trouvé la CABANE\n"
	.string "SECRETE dans le PARC SAFARI?$"

@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
	.string "なんや　にもつ\n"
	.string "いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
	.string "Photos et fossiles de POKéMON.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
	.string "Tout plein de trucs POKéMON!$"

