FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
    .ifdef ENGLISH
    .string "WARDEN: Hif fuff hefifoo!\p"
    .string "Ha lof ha feef ee hafahi ho.\n"
    .string "Heff hee fwee!$"
    .endif
    .ifdef SPANISH
    .string "GUARDA: ¡Fii, fuff, fefifu!\p"
    .string "A fof, a fif ee afahi fo.\n"
    .string "¡Eeff fi fui!$"
    .endif

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
    .ifdef ENGLISH
    .string "Ah howhee ho hoo!\n"
    .string "Eef ee hafahi ho!$"
    .endif
    .ifdef SPANISH
    .string "¡Ah fafee, oo foo!\n"
    .string "¡Eef ee afafi fo!$"
    .endif

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
    .ifdef ENGLISH
    .string "Ha?\n"
    .string "He ohay heh ha hoo ee haheh!$"
    .endif
    .ifdef SPANISH
    .string "¿Ah?\n"
    .string "¡Fai fou fee, fa foo if afee!$"
    .endif

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
    .ifdef ENGLISH
    .string "{PLAYER} gave the GOLD TEETH\n"
    .string "to the WARDEN.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} le dio los DIENTES\n"
    .string "de ORO al GUARDA!$"
    .endif

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
    .ifdef ENGLISH
    .string "The WARDEN popped in his teeth!$"
    .endif
    .ifdef SPANISH
    .string "¡El GUARDA se puso los dientes!$"
    .endif

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
    .ifdef ENGLISH
    .string "WARDEN: Thanks, son!\n"
    .string "You're a real lifesaver!\p"
    .string "No one could understand a word\n"
    .string "that I said, not a one!\p"
    .string "I was too ashamed to show my face\n"
    .string "around the OFFICE, even.\p"
    .string "Let me give you something for your\n"
    .string "trouble.$"
    .endif
    .ifdef SPANISH
    .string "GUARDA: ¡Gracias, majo!\n"
    .string "¡Menos mal!\p"
    .string "No había quien me entendiera,\n"
    .string "vamos, ¡no me entendía ni yo!\p"
    .string "¡Me daba vergüenza hasta ir\n"
    .string "a trabajar!\p"
    .string "¡Te daré algo por las molestias!$"
    .endif

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
    .ifdef ENGLISH
    .string "WARDEN: Thank you, lassie!\n"
    .string "You're a real lifesaver!\p"
    .string "No one could understand a word\n"
    .string "that I said, not a one!\p"
    .string "I was too ashamed to show my face\n"
    .string "around the OFFICE, even.\p"
    .string "Let me give you something for your\n"
    .string "trouble.$"
    .endif
    .ifdef SPANISH
    .string "GUARDA: ¡Gracias, maja!\n"
    .string "¡Menos mal!\p"
    .string "No había quien me entendiera,\n"
    .string "vamos, ¡no me entendía ni yo!\p"
    .string "¡Me daba vergüenza hasta ir\n"
    .string "a trabajar!\p"
    .string "¡Te daré algo por las molestias!$"
    .endif

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
    .ifdef ENGLISH
    .string "{PLAYER} received HM04\n"
    .string "from the WARDEN.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió la MO04\n"
    .string "de manos del GUARDA!$"
    .endif

FuchsiaCity_WardensHouse_Text_ExplainStrength::
    .ifdef ENGLISH
    .string "WARDEN: Inside HM04 you'll find\n"
    .string "STRENGTH.\p"
    .string "It lets POKéMON move boulders when\n"
    .string "you're outside of battle.\p"
    .string "Oh yes, did you find the SECRET\n"
    .string "HOUSE in the SAFARI ZONE?$"
    .endif
    .ifdef SPANISH
    .string "GUARDA: ¡La MO04 enseña FUERZA!\p"
    .string "Tus POKéMON podrán mover rocas\n"
    .string "siempre que quieras.\p"
    .string "¿Encontraste la CASA SECRETA\n"
    .string "en la ZONA del SAFARI?$"
    .endif

@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
    .string "なんや　にもつ\n"
    .string "いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
    .ifdef ENGLISH
    .string "POKéMON photos and fossils are on\n"
    .string "display.$"
    .endif
    .ifdef SPANISH
    .string "Fotos y fósiles de POKéMON.$"
    .endif

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
    .ifdef ENGLISH
    .string "Old POKéMON merchandise is on\n"
    .string "display.$"
    .endif
    .ifdef SPANISH
    .string "¡Viejos objetos de los POKéMON!$"
    .endif

