FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
	.string "WÄRTER: Hef faff heffee!\p"
	.string "Ha lof ha feef ee haffhe he.\n"
	.string "Heff hee fiee!$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
	.string "Eff heffe fefe!\n"
	.string "Eef hafahi-fone!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
	.string "Ha?\n"
	.string "Hei heff heh ha hef ee haheh!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
	.string "{PLAYER} gibt dem WÄRTER die\n"
	.string "GOLDZÄHNE!$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
	.string "Der WÄRTER setzt das Gebiss ein!$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
	.string "WÄRTER: Danke!\n"
	.string "Niemand hat auch nur ein Wort von\l"
	.string "mir verstanden!\p"
	.string "So konnte ich nicht arbeiten.\n"
	.string "Nimm das hier für deine Mühen.$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
	.string "WÄRTER: Danke!\n"
	.string "Niemand hat auch nur ein Wort von\l"
	.string "mir verstanden!\p"
	.string "So konnte ich nicht arbeiten.\n"
	.string "Nimm das hier für deine Mühen.$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
	.string "{PLAYER} erhält\n"
	.string "VM04!$"

FuchsiaCity_WardensHouse_Text_ExplainStrength::
	.string "WÄRTER: VM04 ist STÄRKE!\p"
	.string "Damit lernen POKéMON, Felsen zu\n"
	.string "verschieben, auch wenn sie nicht\l"
	.string "kämpfen!\p"
	.string "Hast du bereits das GEHEIME HAUS\n"
	.string "in der SAFARI-ZONE gefunden?$"

@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
	.string "なんや　にもつ\n"
	.string "いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
	.string "Fotos von POKéMON\n"
	.string "und Fossilien.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
	.string "Alte POKéMON-\n"
	.string "Spielsachen.$"

