SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
    .string "¡Eh, espera! ¡No digas nada!\p"
    .string "¿Tú no querías esto?$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
    .string "¡{PLAYER} recibió la MT29\n"
    .string "de manos del SR. PSÍQUICO!$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
    .string "MT29 contiene PSÍQUICO.\p"
    .string "¡Puede reducir las habilidades\n"
    .string "especiales del objetivo!$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
    .string "¿Dónde piensas poner esto?\n"
    .string "¡No te queda sitio!$"
