SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
    .ifdef ENGLISH
    .string "…Wait! Don't say a word!\p"
    .string "You wanted this!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, espera! ¡No digas nada!\p"
    .string "¿Tú no querías esto?$"
    .endif

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
    .ifdef ENGLISH
    .string "{PLAYER} received TM29\n"
    .string "from MR. PSYCHIC.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió la MT29\n"
    .string "de manos del SR. PSÍQUICO!$"
    .endif

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
    .ifdef ENGLISH
    .string "You already know, don't you?\n"
    .string "TM29 is PSYCHIC.\p"
    .string "It's an attack that may also lower\n"
    .string "the target's special stats.$"
    .endif
    .ifdef SPANISH
    .string "MT29 contiene PSÍQUICO.\p"
    .string "¡Puede reducir las habilidades\n"
    .string "especiales del objetivo!$"
    .endif

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
    .ifdef ENGLISH
    .string "Where do you plan to put this?\n"
    .string "You've no room.$"
    .endif
    .ifdef SPANISH
    .string "¿Dónde piensas poner esto?\n"
    .string "¡No te queda sitio!$"
    .endif

