SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
	.string "Warte!\n"
	.string "Sag kein Wort!\p"
	.string "Du suchst dies hier, oder?$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
	.string "{PLAYER} erhält\n"
	.string "TM29!$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
	.string "TM29 ist PSYCHOKINESE!\p"
	.string "Sie vermindert die SPEZIAL-\n"
	.string "FÄHIGKEITEN des Gegners.$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
	.string "Heh, du kannst keine Items mehr\n"
	.string "tragen!$"

