RockTunnel_B1F_Text_SofiaIntro::
    .string "Los montañeros marcan el camino\n"
    .string "con ramitas.\p"
    .string "Es la mejor forma de no perderse.$"

RockTunnel_B1F_Text_SofiaDefeat::
    .string "¡Ohhh!\n"
    .string "¡He hecho todo lo posible!$"

RockTunnel_B1F_Text_SofiaPostBattle::
    .string "¡Quiero volver a mi casa!$"

RockTunnel_B1F_Text_DudleyIntro::
    .string "¡Ja, ja, ja!\n"
    .string "¿Crees que puedes ganarme?$"

RockTunnel_B1F_Text_DudleyDefeat::
    .string "¡Vaya!\nQué ridículo...$"

RockTunnel_B1F_Text_DudleyPostBattle::
    .string "¡Prefiero la fuerza, porque no\n"
    .string "me gusta pensar!$"

RockTunnel_B1F_Text_CooperIntro::
    .string "¿Tienes una POKéDEX?\n"
    .string "¡Yo también quiero una!$"

RockTunnel_B1F_Text_CooperDefeat::
    .string "¡Brgg!\n"
    .string "¡Me das tanta envidia!$"

RockTunnel_B1F_Text_CooperPostBattle::
    .string "Cuando termines con tu POKéDEX\n"
    .string "¿me la dejarás?$"

RockTunnel_B1F_Text_SteveIntro::
    .string "¿Qué sabes de esos jugadores\n"
    .string "disfrazados?$"

RockTunnel_B1F_Text_SteveDefeat::
    .string "Pues eso es todo.$"

RockTunnel_B1F_Text_StevePostBattle::
    .string "No hay nada como disfrazarse\n"
    .string "de POKéMON para divertirse.\p"
    .string "El mejor es CLEFAIRY.$"

RockTunnel_B1F_Text_AllenIntro::
    .string "¡Mis técnicas de POKéMON te harán\n"
    .string "llorar!$"

RockTunnel_B1F_Text_AllenDefeat::
    .string "¡Me rindo!\n"
    .string "¡Tus técnicas son mejores!$"

RockTunnel_B1F_Text_AllenPostBattle::
    .string "En las montañas suele haber\n"
    .string "POKéMON del tipo ROCA.$"

RockTunnel_B1F_Text_MarthaIntro::
    .string "¡No suelo venir por aquí, pero\n"
    .string "lucharé contigo!$"

RockTunnel_B1F_Text_MarthaDefeat::
    .string "¡Oh! ¡He perdido!$"

RockTunnel_B1F_Text_MarthaPostBattle::
    .string "¡Me gustan los POKéMON pequeños!\n"
    .string "¡Los grandes son horribles!$"

RockTunnel_B1F_Text_EricIntro::
    .string "¡Lánzame tu mejor ataque!$"

RockTunnel_B1F_Text_EricDefeat::
    .string "¡Vamos, adelante!$"

RockTunnel_B1F_Text_EricPostBattle::
    .string "¡Criaré a mis POKéMON para que\n"
    .string "venzan a los tuyos!$"

RockTunnel_B1F_Text_WinstonIntro::
    .string "Cuando estoy en casa, dibujo a los\n"
    .string "POKéMON.$"

RockTunnel_B1F_Text_WinstonDefeat::
    .string "¡Uf!\n"
    .string "¡Estoy agotado!$"

RockTunnel_B1F_Text_WinstonPostBattle::
    .string "Soy un artista, no un guerrero.$"
