RockTunnel_B1F_Text_SofiaIntro::
    .ifdef ENGLISH
    .string "Do you know how you can avoid\n"
    .string "getting lost in the mountains?\p"
    .string "You can bend twigs as trail\n"
    .string "markers.$"
    .endif
    .ifdef SPANISH
    .string "Los montañeros marcan el camino\n"
    .string "con ramitas.\p"
    .string "Es la mejor forma de no perderse.$"
    .endif

RockTunnel_B1F_Text_SofiaDefeat::
    .ifdef ENGLISH
    .string "Ohhh!\n"
    .string "I did my best!$"
    .endif
    .ifdef SPANISH
    .string "¡Ohhh!\n"
    .string "¡He hecho todo lo posible!$"
    .endif

RockTunnel_B1F_Text_SofiaPostBattle::
    .ifdef ENGLISH
    .string "I want to go home!$"
    .endif
    .ifdef SPANISH
    .string "¡Quiero volver a mi casa!$"
    .endif

RockTunnel_B1F_Text_DudleyIntro::
    .ifdef ENGLISH
    .string "Hahaha!\n"
    .string "Can you beat my power?$"
    .endif
    .ifdef SPANISH
    .string "¡Ja, ja, ja!\n"
    .string "¿Crees que puedes ganarme?$"
    .endif

RockTunnel_B1F_Text_DudleyDefeat::
    .ifdef ENGLISH
    .string "Oops!\n"
    .string "Outmuscled!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya!\nQué ridículo...$"
    .endif

RockTunnel_B1F_Text_DudleyPostBattle::
    .ifdef ENGLISH
    .string "I go for power because I hate\n"
    .string "thinking.$"
    .endif
    .ifdef SPANISH
    .string "¡Prefiero la fuerza, porque no\n"
    .string "me gusta pensar!$"
    .endif

RockTunnel_B1F_Text_CooperIntro::
    .ifdef ENGLISH
    .string "You have a POKéDEX?\n"
    .string "I want one, too.$"
    .endif
    .ifdef SPANISH
    .string "¿Tienes una POKéDEX?\n"
    .string "¡Yo también quiero una!$"
    .endif

RockTunnel_B1F_Text_CooperDefeat::
    .ifdef ENGLISH
    .string "Shoot!\n"
    .string "I am so jealous!$"
    .endif
    .ifdef SPANISH
    .string "¡Brgg!\n"
    .string "¡Me das tanta envidia!$"
    .endif

RockTunnel_B1F_Text_CooperPostBattle::
    .ifdef ENGLISH
    .string "When you finish your POKéDEX,\n"
    .string "can I have it?$"
    .endif
    .ifdef SPANISH
    .string "Cuando termines con tu POKéDEX\n"
    .string "¿me la dejarás?$"
    .endif

RockTunnel_B1F_Text_SteveIntro::
    .ifdef ENGLISH
    .string "Um… Do you know about POKéMON\n"
    .string "cosplay?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué sabes de esos jugadores\n"
    .string "disfrazados?$"
    .endif

RockTunnel_B1F_Text_SteveDefeat::
    .ifdef ENGLISH
    .string "Well, that's that.$"
    .endif
    .ifdef SPANISH
    .string "Pues eso es todo.$"
    .endif

RockTunnel_B1F_Text_StevePostBattle::
    .ifdef ENGLISH
    .string "POKéMON cosplay is dressing up as\n"
    .string "POKéMON for fun.\p"
    .string "CLEFAIRY is a favorite.$"
    .endif
    .ifdef SPANISH
    .string "No hay nada como disfrazarse\n"
    .string "de POKéMON para divertirse.\p"
    .string "El mejor es CLEFAIRY.$"
    .endif

RockTunnel_B1F_Text_AllenIntro::
    .ifdef ENGLISH
    .string "My POKéMON techniques will leave\n"
    .string "you crying!$"
    .endif
    .ifdef SPANISH
    .string "¡Mis técnicas de POKéMON te harán\n"
    .string "llorar!$"
    .endif

RockTunnel_B1F_Text_AllenDefeat::
    .ifdef ENGLISH
    .string "I give!\n"
    .string "You're a better technician!$"
    .endif
    .ifdef SPANISH
    .string "¡Me rindo!\n"
    .string "¡Tus técnicas son mejores!$"
    .endif

RockTunnel_B1F_Text_AllenPostBattle::
    .ifdef ENGLISH
    .string "In mountains, you'll often find\n"
    .string "ROCK-type POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "En las montañas suele haber\n"
    .string "POKéMON del tipo ROCA.$"
    .endif

RockTunnel_B1F_Text_MarthaIntro::
    .ifdef ENGLISH
    .string "I don't often come here, but I will\n"
    .string "battle you.$"
    .endif
    .ifdef SPANISH
    .string "¡No suelo venir por aquí, pero\n"
    .string "lucharé contigo!$"
    .endif

RockTunnel_B1F_Text_MarthaDefeat::
    .ifdef ENGLISH
    .string "Oh!\n"
    .string "I lost!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh! ¡He perdido!$"
    .endif

RockTunnel_B1F_Text_MarthaPostBattle::
    .ifdef ENGLISH
    .string "I like tiny POKéMON.\n"
    .string "Big ones are too scary!$"
    .endif
    .ifdef SPANISH
    .string "¡Me gustan los POKéMON pequeños!\n"
    .string "¡Los grandes son horribles!$"
    .endif

RockTunnel_B1F_Text_EricIntro::
    .ifdef ENGLISH
    .string "Hit me with your best shot!$"
    .endif
    .ifdef SPANISH
    .string "¡Lánzame tu mejor ataque!$"
    .endif

RockTunnel_B1F_Text_EricDefeat::
    .ifdef ENGLISH
    .string "Fired away!$"
    .endif
    .ifdef SPANISH
    .string "¡Vamos, adelante!$"
    .endif

RockTunnel_B1F_Text_EricPostBattle::
    .ifdef ENGLISH
    .string "I'll raise my POKéMON to beat\n"
    .string "yours, kid.$"
    .endif
    .ifdef SPANISH
    .string "¡Criaré a mis POKéMON para que\n"
    .string "venzan a los tuyos!$"
    .endif

RockTunnel_B1F_Text_WinstonIntro::
    .ifdef ENGLISH
    .string "I draw illustrations of POKéMON\n"
    .string "when I'm home.$"
    .endif
    .ifdef SPANISH
    .string "Cuando estoy en casa, dibujo a los\n"
    .string "POKéMON.$"
    .endif

RockTunnel_B1F_Text_WinstonDefeat::
    .ifdef ENGLISH
    .string "Whew…\n"
    .string "I'm exhausted…$"
    .endif
    .ifdef SPANISH
    .string "¡Uf!\n"
    .string "¡Estoy agotado!$"
    .endif

RockTunnel_B1F_Text_WinstonPostBattle::
    .ifdef ENGLISH
    .string "I'm an artist, not a fighter.\n"
    .string "I'll go home to draw.$"
    .endif
    .ifdef SPANISH
    .string "Soy un artista, no un guerrero.$"
    .endif

