CeladonCity_Condominiums_1F_Text_Meowth::
    .ifdef ENGLISH
    .string "MEOWTH: Meow!$"
    .endif
    .ifdef SPANISH
    .string "MEOWTH: ¡Meow!$"
    .endif

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .ifdef ENGLISH
    .string "You shouldn't spend all your money\n"
    .string "on drinks.\p"
    .string "Try this instead.$"
    .endif
    .ifdef SPANISH
    .string "No deberías gastarte el dinero\n"
    .string "en latas.\p"
    .string "Toma, prueba esto.$"
    .endif

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .ifdef ENGLISH
    .string "Nothing beats thirst like some hot\n"
    .string "TEA.\p"
    .string "It really is the best.$"
    .endif
    .ifdef SPANISH
    .string "No hay nada que calme la sed\n"
    .string "mejor que el TÉ.\p"
    .string "Es lo mejor que hay.$"
    .endif

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .ifdef ENGLISH
    .string "My dear POKéMON keep me company.\n"
    .string "MEOWTH even brings money home!$"
    .endif
    .ifdef SPANISH
    .string "¡Mis queridos POKéMON me\n"
    .string "acompañan!\p"
    .string "¡Y MEOWTH hasta trae dinero a\n"
    .string "casa!$"
    .endif

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .ifdef ENGLISH
    .string "Oh, hello, dearie.\n"
    .string "Did you enjoy my TEA?\p"
    .string "By the way, dear. Are you, by any\n"
    .string "chance, from PALLET TOWN?\p"
    .string "A girl from PALLET TOWN, DAISY,\n"
    .string "she enjoys TEA every day.\p"
    .string "She visits the CELADON DEPT. STORE\n"
    .string "to buy some TEA.$"
    .endif
    .ifdef SPANISH
    .string "Hola, encanto.\n"
    .string "¿Te gustó el TÉ?\p"
    .string "Ah, te quería preguntar si eres\n"
    .string "de PUEBLO PALETA.\p"
    .string "Es que allí hay una chica, DALIA,\n"
    .string "que toma TÉ a diario.\p"
    .string "Suele comprarlo en el CENTRO\n"
    .string "COMERCIAL de AZULONA.$"
    .endif

CeladonCity_Condominiums_1F_Text_Clefairy::
    .ifdef ENGLISH
    .string "CLEFAIRY: Pi pippippi!$"
    .endif
    .ifdef SPANISH
    .string "CLEFAIRY: ¡Iry! ¡Cleclecle!$"
    .endif

CeladonCity_Condominiums_1F_Text_Nidoran::
    .ifdef ENGLISH
    .string "NIDORAN♀: Kya kyaoo!$"
    .endif
    .ifdef SPANISH
    .string "NIDORAN?: ¡Nidor! ¡Nidoorr!$"
    .endif

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .ifdef ENGLISH
    .string "CELADON MANSION\n"
    .string "Manager's Suite$"
    .endif
    .ifdef SPANISH
    .string "MANSIÓN AZULONA\n"
    .string "Suite presidencial$"
    .endif

