CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
	.string "Die POKéFLÖTE weckt POKéMON mit\n"
	.string "einem Ton, den nur POKéMON\l"
	.string "hören können!$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
	.string "Ich bin von FUCHSANIA CITY aus\n"
	.string "den RADWEG hinaufgefahren!$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
	.string "Wenn ich ein FAHRRAD hätte, würde\n"
	.string "ich den RADWEG benutzen!$"

