CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
    .ifdef ENGLISH
    .string "A POKé FLUTE awakens sleeping\n"
    .string "POKéMON. You know that.\p"
    .string "It does so with a sound that only\n"
    .string "they can hear.$"
    .endif
    .ifdef SPANISH
    .string "¡La POKé FLAUTA despierta a los\n"
    .string "POKéMON con un sonido que sólo\l"
    .string "ellos pueden oír!$"
    .endif

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
    .ifdef ENGLISH
    .string "I rode here from FUCHSIA.\p"
    .string "It's an uphill ride on CYCLING\n"
    .string "ROAD, so I'm exhausted.$"
    .endif
    .ifdef SPANISH
    .string "¡He pedaleado cuesta arriba por el\n"
    .string "CAMINO de BICIS desde FUCSIA!\p"
    .string "¡Qué agotamiento!$"
    .endif

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
    .ifdef ENGLISH
    .string "If I had a BIKE, I would go to\n"
    .string "CYCLING ROAD!$"
    .endif
    .ifdef SPANISH
    .string "¡Si tuviera una BICICLETA,\n"
    .string "iría por el CAMINO de BICIS!$"
    .endif

