CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
	.string "La POKéFLUTE réveille les POKéMON\n"
	.string "grâce aux ultrasons!$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
	.string "J'ai pris la PISTE CYCLABLE depuis\n"
	.string "PARMANIE!\p"
	.string "Je suis complètement épuisée.$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
	.string "Si j'avais une BICYCLETTE, j'irais\n"
	.string "sur la PISTE CYCLABLE!$"

