Braille_Text_Up::
	.braille "IN ALTO$"

Braille_Text_Down::
	.braille "IN BASSO$"

Braille_Text_Right::
	.braille "A DESTRA$"

Braille_Text_Left::
	.braille "A SINISTRA$"

Braille_Text_Cut::
	.braille "TAGLIO$"

Braille_Text_ABC::
	.braille "ABC$"

Braille_Text_GHI::
	.braille "GHI$"

Braille_Text_MNO::
	.braille "MNO$"

Braille_Text_TUV::
	.braille "TUV$"

Braille_Text_DEF::
	.braille "DEF$"

Braille_Text_JKL::
	.braille "JKL$"

Braille_Text_PQRS::
	.braille "PQRS$"

Braille_Text_WXYZ::
	.braille "WXYZ$"

Braille_Text_Period::
	.braille ".$"

Braille_Text_Comma::
	.braille "'"

Braille_Text_Everything::
	.braille "TUTTO$"

Braille_Text_HasMeaning1::
	.braille "HA UN SENSO$"

Braille_Text_Existence::
	.braille "LA VITA$"

Braille_Text_HasMeaning2::
	.braille "HA UN SENSO$"

Braille_Text_BeingAlive::
	.braille "ESSERE VIVI$"

Braille_Text_HasMeaning3::
	.braille "HA UN SENSO$"

Braille_Text_HaveDreams::
	.braille "SOGNA E USA$"

Braille_Text_UsePower::
	.braille "LA TUA FORZA$"

Braille_Text_LetTheTwo::
	.braille "LE DUE$"

Braille_Text_Glittering::
	.braille "PIETRE$"

Braille_Text_Stones::
	.braille "SCINTILLANTI$"

Braille_Text_OneInRed::
	.braille "UNA ROSSA$"

Braille_Text_OneInBlue::
	.braille "UNA BLU$"

Braille_Text_ConnectThe::
	.braille "TI COLLEGANO$"

Braille_Text_Past::
	.braille "AL PASSATO.$"

Braille_Text_TwoFriends::
	.braille "DUE AMICI$"

Braille_Text_Sharing::
	.braille "UNENDO LE$"

Braille_Text_PowerOpen::
	.braille "FORZE APRONO$"

Braille_Text_AWindowTo::
	.braille "UNA FINESTRA$"

Braille_Text_ANewWorld::
	.braille "SU UN NUOVO$"

Braille_Text_ThatGlows::
	.braille "MONDO.$"

Braille_Text_TheNext::
	.braille "IL PROSSIMO$"

Braille_Text_WorldWaits::
	.braille "MONDO$"

Braille_Text_ForYou::
	.braille "TI ATTENDE.$"
