@ Unused
Text_WelcomeTradeCenter::
    .string "Ti do il benvenuto al CENTRO\n"
    .string "SCAMBI del CLUB VIA CAVO POKéMON.$"

@ Unused
Text_WelcomeColosseum::
    .string "Ti do il benvenuto al COLOSSEO del\n"
    .string "CLUB VIA CAVO POKéMON.$"

@ Unused
Text_WelcomeTimeCapsule::
    .string "Ti do il benvenuto alla\n"
    .string "TEMPOCAPSULA del CLUB VIA CAVO\lPOKéMON.$"

Text_PleaseComeAgain::
    .string "Torna a trovarmi!$"

@ Unused
Text_HavingDiscountSaleToday::
    .string "Salve!\p"
    .string "Oggi ci sono le offerte speciali!$"

@ Unused
Text_PlayerWhatCanIDoForYou::
    .string "{PLAYER}{KUN}, salve!\p"
    .string "Che cosa posso fare per te?$"
