gFameCheckerFlavorText_ProfOak0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LABORATORIO del PROFESSOR OAK$"

gFameCheckerFlavorText_ProfOak1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Realizzare una guida completa di\n"
	.string "tutti i POKéMON del mondo…\p"
	.string "era questo il mio grande sogno!$"

gFameCheckerFlavorText_ProfOak2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il PROF. OAK è un'autorità in fatto\n"
	.string "di POKéMON!\p"
	.string "È molto stimato dagli ALLENATORI\n"
	.string "di POKéMON!$"

gFameCheckerFlavorText_ProfOak3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pare che MARGI e {RIVAL} vivano\n"
	.string "con il nonno, il PROF. OAK.$"

gFameCheckerFlavorText_ProfOak4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}OAK sembra molto interessato a te!\p"
	.string "Molti anni fa quel vecchietto\n"
	.string "era forte e affascinante!$"

gFameCheckerFlavorText_ProfOak5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il PROF. OAK avrà presto il suo\n"
	.string "programma radio personale.\l"
	.string "Si chiamerà L'ANGOLO POKéMON di\l"
	.string "OAK.$"

gFameCheckerFlavorText_Daisy0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Se mostri a MARGI un\n"
	.string "POKéMON, ti dirà quanto\l"
	.string "ti è amico.\p"
	.string "Potrebbe anche spazzolarne\n"
	.string "uno per te.$"

gFameCheckerFlavorText_Daisy1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Com'è questa persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ma la persona che in assoluto è\n"
	.string "più amata dai POKéMON è MARGI,\l"
	.string "credo.$"

gFameCheckerFlavorText_Daisy2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Si chiamava MARGI, se\n"
	.string "non sbaglio.\p"
	.string "Spazzolava i POKéMON con\n"
	.string "tanto amore!$"

gFameCheckerFlavorText_Daisy3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pare che MARGI e {RIVAL} vivano\n"
	.string "con il nonno, il PROF. OAK.$"

gFameCheckerFlavorText_Daisy4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}È di BIANCAVILLA e beve TÈ\n"
	.string "tutti i giorni.\p"
	.string "Va spesso a comprare TÈ\n"
	.string "al CENTRO COMMERCIALE\l"
	.string "di AZZURROPOLI.$"

gFameCheckerFlavorText_Daisy5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lo sapevi che…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Vincitrice della GARA POKéMON\n"
	.string "di quest'anno è MARGI OAK\l"
	.string "di BIANCAVILLA!$"

gFameCheckerFlavorText_Brock0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CAPOPALESTRA di PLUMBEOPOLI:\n"
	.string "BROCK\l"
	.string "L'ALLENATORE di POKéMON più forte\l"
	.string "di una roccia!$"

gFameCheckerFlavorText_Brock1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sono BROCK!\n"
	.string "Il CAPOPALESTRA di PLUMBEOPOLI!\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il mio motto è determinazione e\n"
	.string "difesa granitica!\p"
	.string "Ecco perché tutti i miei POKéMON\n"
	.string "sono del tipo ROCCIA!$"

gFameCheckerFlavorText_Brock2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Non ci sono tanti ALLENATORI di\n"
	.string "POKéMON seri qui!\p"
	.string "Sono tutti dei PIGLIAMOSCHE!\p"
	.string "Si salva solo BROCK della PALESTRA\n"
	.string "di PLUMBEOPOLI!$"

gFameCheckerFlavorText_Brock3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK è un grande. Non solo è\n"
	.string "forte, ma soprattutto ha carisma.\p"
	.string "Vorrei diventare un CAPOPALESTRA\n"
	.string "come lui.$"

gFameCheckerFlavorText_Brock4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ciao, sono venuto sul MONTE LUNA\n"
	.string "per cercare fossili sottoterra.\p"
	.string "A volte viene ad aiutarmi BROCK \n"
	.string "da PLUMBEOPOLI.$"

gFameCheckerFlavorText_Brock5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK ride di rado, ma quando\n"
	.string "inizia, non riesce più a fermarsi.$"

gFameCheckerFlavorText_Misty0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CAPOPALESTRA di CELESTOPOLI:\n"
	.string "MISTY\l"
	.string "La sirena maschiaccio!$"

gFameCheckerFlavorText_Misty1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}La mia tattica è di attacco\n"
	.string "totale con POKéMON di tipo\l"
	.string "ACQUA!{COLOR BLUE}$"

gFameCheckerFlavorText_Misty2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MISTY migliora continuamente!\p"
	.string "Non perderà certo contro di te!$"

gFameCheckerFlavorText_Misty3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lo sapevi che…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Questi posti sono frequentati da\n"
	.string "forti ALLENATORI e POKéMON di\l"
	.string "tipo ACQUA.\p"
	.string "Pare che MISTY di CELESTOPOLI\n"
	.string "si alleni da queste parti.$"

gFameCheckerFlavorText_Misty4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lo sapevi che…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Questo capo è famoso per gli\n"
	.string "appuntamenti fra innamorati.\p"
	.string "MISTY, la nostra CAPOPALESTRA, è\n"
	.string "molto legata a questo luogo.$"

gFameCheckerFlavorText_Misty5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lo sapevi che…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MISTY è una fan di LORELEI\n"
	.string "dei SUPERQUATTRO!$"

gFameCheckerFlavorText_LtSurge0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CAPOPALESTRA di ARANCIOPOLI:\n"
	.string "LT. SURGE\l"
	.string "L'americano fulminante!$"

gFameCheckerFlavorText_LtSurge1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Devi sapere che i POKéMON elettrici\n"
	.string "mi hanno salvato in guerra!$"

gFameCheckerFlavorText_LtSurge2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Quando ero nell'esercito, LT. SURGE\n"
	.string "era molto severo!$"

gFameCheckerFlavorText_LtSurge3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE è sempre stato prudente!$"

gFameCheckerFlavorText_LtSurge4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE ha messo doppi\n"
	.string "lucchetti nella PALESTRA.$"

gFameCheckerFlavorText_LtSurge5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lo sapevi che…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pare che in America, dov'è nato,\n"
	.string "facesse il pilota.\p"
	.string "Il suo aereo era alimentato con\n"
	.string "l'energia dei POKéMON.$"

gFameCheckerFlavorText_Erika0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CAPOPALESTRA di AZZURROPOLI:\n"
	.string "ERIKA\l"
	.string "La principessa amante della natura!$"

gFameCheckerFlavorText_Erika1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Studio l'arte delle composizioni\n"
	.string "floreali. I miei POKéMON sono\l"
	.string "di tipo ERBA.$"

gFameCheckerFlavorText_Erika2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ERIKA, il nostro CAPOPALESTRA,\n"
	.string "è molto tranquilla, ma altrettanto\l"
	.string "capace!$"

gFameCheckerFlavorText_Erika3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In questa PALESTRA usiamo solo\n"
	.string "POKéMON di tipo ERBA!\p"
	.string "Li usiamo persino per le nostre\n"
	.string "composizioni floreali!$"

gFameCheckerFlavorText_Erika4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Stai catalogando i POKéMON?\n"
	.string "Sono colpita!\p"
	.string "Non collezionerei mai i POKéMON\n"
	.string "bruttini.$"

gFameCheckerFlavorText_Erika5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lo sapevi che…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Quando è sola nella PALESTRA di\n"
	.string "AZZURROPOLI, pare che ERIKA\l"
	.string "ogni tanto schiacci un pisolino.$"

gFameCheckerFlavorText_Koga0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CAPOPALESTRA di FUCSIAPOLI:\n"
	.string "KOGA\l"
	.string "Il velenoso maestro ninja$"

gFameCheckerFlavorText_Koga1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Proverai la forza terrorizzante dei\n"
	.string "POKéMON di tipo VELENO!$"

gFameCheckerFlavorText_Koga2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Continuerò a seguire gli\n"
	.string "insegnamenti di KOGA,\l"
	.string "il mio maestro ninja!$"

gFameCheckerFlavorText_Koga3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mio padre è il CAPOPALESTRA\n"
	.string "di questa città.\p"
	.string "Anch'io mi alleno con i POKéMON\n"
	.string "di tipo VELENO, proprio come lui!$"

gFameCheckerFlavorText_Koga4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lo sapevi che…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pare che KOGA abbia ottime\n"
	.string "conoscenze di medicina.\p"
	.string "Spesso prepara addirittura dei\n"
	.string "medicamenti per curare i POKéMON.$"

gFameCheckerFlavorText_Koga5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Visto quanto è grande la ZONA\n"
	.string "SAFARI?\p"
	.string "Ogni tanto passa di qui KOGA,\n"
	.string "CAPOPALESTRA di FUCSIAPOLI.\p"
	.string "Grazie a lui, tutti possono giocare\n"
	.string "senza correre nessun pericolo.$"

gFameCheckerFlavorText_Sabrina0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CAPOPALESTRA di ZAFFERANOPOLI:\n"
	.string "SABRINA\l"
	.string "Regina dei POKéMON di tipo PSICO!$"

gFameCheckerFlavorText_Sabrina1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Conosci la ragazza che è\n"
	.string "CAPOPALESTRA a ZAFFERANOPOLI?\p"
	.string "Usa POKéMON di tipo PSICO, vero?$"

gFameCheckerFlavorText_Sabrina2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Già da bambina avevo poteri\n"
	.string "paranormali!\p"
	.string "Tutto è iniziato quando ho imparato\n"
	.string "a piegare i cucchiai col pensiero.$"

gFameCheckerFlavorText_Sabrina3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Odio lottare ma se vuoi ti mostrerò\n"
	.string "i miei poteri!$"

gFameCheckerFlavorText_Sabrina4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lo sapevi che…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pare che SABRINA, durante la\n"
	.string "lotta, possa comunicare con\l"
	.string "i suoi POKéMON senza parlare.$"

gFameCheckerFlavorText_Sabrina5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SABRINA ha battuto il MAESTRO di\n"
	.string "KARATE qui accanto!$"

gFameCheckerFlavorText_Blaine0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CAPOPALESTRA dell'ISOLA CANNELLA:\n"
	.string "BLAINE\l"
	.string "Il cervellotico maestro di quiz!$"

gFameCheckerFlavorText_Blaine1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I miei POKéMON inceneriranno ogni\n"
	.string "sfidante!$"

gFameCheckerFlavorText_Blaine2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BLAINE si era perso in montagna\n"
	.string "quando apparve uno spaventoso\l"
	.string "POKéMON uccello!\p"
	.string "Grazie alla sua luce, BLAINE poté\n"
	.string "ritrovare la via.$"

gFameCheckerFlavorText_Blaine3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BLAINE della PALESTRA dell'ISOLA\n"
	.string "CANNELLA è un uomo strano che\l"
	.string "vive qui da decenni.$"

gFameCheckerFlavorText_Blaine4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}È una foto di BLAINE e MR. FUJI!\p"
	.string "Sorridono, affiancati.$"

gFameCheckerFlavorText_Blaine5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lo sapevi che…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pare che BLAINE si liberi della\n"
	.string "sua aria cupa soltanto quando\l"
	.string "pensa a nuove domande per il quiz.$"

gFameCheckerFlavorText_Lorelei0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sono LORELEI dei SUPERQUATTRO!$"

gFameCheckerFlavorText_Lorelei1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Nessuno conosce i POKéMON di tipo\n"
	.string "GHIACCIO come me!$"

gFameCheckerFlavorText_Lorelei2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da dove proviene?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Su quest'isola è nata e cresciuta\n"
	.string "una ragazza che è diventata un\l"
	.string "grande ALLENATORE.\p"
	.string "È LORELEI dei SUPERQUATTRO.$"

gFameCheckerFlavorText_Lorelei3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Famosa per la freddezza e la\n"
	.string "perfezione del suo stile di lotta,\l"
	.string "LORELEI ha in serbo una sorpresa!$"

gFameCheckerFlavorText_Lorelei4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}A proposito di LORELEI: sapevi che\n"
	.string "ha centinaia di bambole di pezza?\p"
	.string "Ogni volta che torna a QUARTISOLA,\n"
	.string "aggiunge qualche bambola alla\l"
	.string "collezione!$"

gFameCheckerFlavorText_Lorelei5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il suo LAPRAS, credo che sia lo\n"
	.string "stesso che ha da quando era\l"
	.string "bambina.\p"
	.string "Credo che l'abbia catturato nella\n"
	.string "GROTTA GELATA.$"

gFameCheckerFlavorText_Bruno0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sono BRUNO dei SUPERQUATTRO!$"

gFameCheckerFlavorText_Bruno1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Nella mia vita, ho sempre allenato\n"
	.string "POKéMON di tipo LOTTA!$"

gFameCheckerFlavorText_Bruno2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pare che BRUNO sia entrato nei\n"
	.string "SUPERQUATTRO per l'ambizione\l"
	.string "di battere i migliori ALLENATORI.$"

gFameCheckerFlavorText_Bruno3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Anche BRUNO viene alle TERME\n"
	.string "di tanto in tanto.\p"
	.string "Viene per recuperare le forze dopo\n"
	.string "una lotta e rimettere in sesto i\l"
	.string "suoi POKéMON.$"

gFameCheckerFlavorText_Bruno4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lo sapevi che…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Poco fa è stato qui a SECONDISOLA\n"
	.string "un famoso ALLENATORE.\p"
	.string "Si chiama BRUNO, è uno dei\n"
	.string "SUPERQUATTRO.\p"
	.string "Purtroppo, però, temo che sia\n"
	.string "rimasto un po' deluso, perché\l"
	.string "non ha trovato ciò che cercava.$"

gFameCheckerFlavorText_Bruno5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO stesso si è allenato per\n"
	.string "parecchio tempo con un amico,\l"
	.string "un certo BRAWLY.$"

gFameCheckerFlavorText_Agatha0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sono AGATHA dei SUPERQUATTRO!$"

gFameCheckerFlavorText_Agatha1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I POKéMON di tipo SPETTRO di\n"
	.string "AGATHA sono orribilmente forti!$"

gFameCheckerFlavorText_Agatha2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Quella vecchietta è potentissima,\n"
	.string "ed è anche una testa calda!\p"
	.string "Niente la spaventa!$"

gFameCheckerFlavorText_Agatha3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lo sapevi che…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Un tempo, AGATHA e il PROF. OAK\n"
	.string "erano grandi rivali come\l"
	.string "ALLENATORI di POKéMON.$"

gFameCheckerFlavorText_Agatha4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}OAK sembra molto interessato a te!\p"
	.string "Molti anni fa quel vecchietto\n"
	.string "era forte e affascinante!$"

gFameCheckerFlavorText_Agatha5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Prendi AGATHA, per esempio!\p"
	.string "È la più anziana SUPERQUATTRO\n"
	.string "della storia!$"

gFameCheckerFlavorText_Lance0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sono il capo dei SUPERQUATTRO!\n"
	.string "Sono LANCE, l'ALLENATORE drago!$"

gFameCheckerFlavorText_Lance1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I POKéMON di tipo DRAGO sono\n"
	.string "mitici!\p"
	.string "Sono difficili da catturare e\n"
	.string "allenare, ma sono quasi\l"
	.string "imbattibili!\p"
	.string "Sono praticamente invulnerabili!$"

gFameCheckerFlavorText_Lance2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}È un paladino della giustizia!\n"
	.string "È allo stesso tempo un uomo\l"
	.string "duro e romantico.\p"
	.string "LANCE è semplicemente il più\n"
	.string "grande!$"

gFameCheckerFlavorText_Lance3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lo sapevi che…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Abbiamo un cliente fisso che si\n"
	.string "chiama LANCE.\p"
	.string "Compra sempre mantelli dello\n"
	.string "stesso colore.\p"
	.string "Credo che ne abbia l'armadio pieno!$"

gFameCheckerFlavorText_Lance4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Si dice che il nonno di LANCE\n"
	.string "fosse a capo di una leggendaria\l"
	.string "banda di domatori di draghi.$"

gFameCheckerFlavorText_Lance5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ho sentito dire che il cugino di\n"
	.string "LANCE, dei SUPERQUATTRO,\l"
	.string "è CAPOPALESTRA da qualche parte.$"

gFameCheckerFlavorText_Bill0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL è noto a tutti come\n"
	.string "POKéFANATICO!\p"
	.string "Ha inventato il Sistema Memoria\n"
	.string "POKéMON per il PC!$"

gFameCheckerFlavorText_Bill1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL ha moltissimi POKéMON!\p"
	.string "E alcuni sono rarissimi!$"

gFameCheckerFlavorText_Bill2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}È mio nipote!\p"
	.string "Fin da piccolo, ha sempre \n"
	.string "avuto la passione per le\l"
	.string "collezioni.$"

gFameCheckerFlavorText_Bill3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL, da buon POKéFANATICO,\n"
	.string "va pazzo per tutti i POKéMON.\p"
	.string "Ma sai qual è il primo che ha\n"
	.string "catturato? Un ABRA!$"

gFameCheckerFlavorText_Bill4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL viene da FIORDOROPOLI.\p"
	.string "Ho sentito dire che è una città\n"
	.string "molto allegra, vitale.$"

gFameCheckerFlavorText_Bill5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lo sapevi che…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL non beve latte. Non gli\n"
	.string "piace proprio.$"

gFameCheckerFlavorText_MrFuji0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Che cara persona!\p"
	.string "Si prende cura dei POKéMON orfani\n"
	.string "e abbandonati!$"

gFameCheckerFlavorText_MrFuji1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Questo vecchietto si è intrufolato\n"
	.string "nel nostro RIFUGIO.\p"
	.string "Poi, ha iniziato a lamentarsi,\n"
	.string "dicendo che TEAM ROCKET fa\l"
	.string "del male ai POKéMON.\p"
	.string "Ora stiamo cercando di farlo\n"
	.string "ragionare.$"

gFameCheckerFlavorText_MrFuji2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}RIVISTA FAN DEI POKéMON\n"
	.string "Concorso Mensile di Disegno\l"
	.string "POKéMON!\p"
	.string "Il modulo di iscrizione è…\p"
	.string "…è scomparso!\n"
	.string "Qualcuno dev'essersi già iscritto.$"

gFameCheckerFlavorText_MrFuji3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Lo sapevi che…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ho sentito dire che neanche\n"
	.string "MR. FUJI è originario di qui.$"

gFameCheckerFlavorText_MrFuji4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}È una foto di BLAINE e MR. FUJI!\p"
	.string "Sorridono, affiancati.$"

gFameCheckerFlavorText_MrFuji5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Purtroppo non è stato possibile\n"
	.string "ottenere un'intervista da MR. FUJI.\p"
	.string "Possiamo comunque confermare la\n"
	.string "grande gentilezza di quest'uomo,\l"
	.string "apprezzato da tutti a LAVANDONIA.$"

gFameCheckerFlavorText_Giovanni0::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TEAM ROCKET usa i POKéMON per\n"
	.string "finanziare i suoi loschi piani!$"

gFameCheckerFlavorText_Giovanni1::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}POKéMON preferiti?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Quei furfanti che hanno\n"
	.string "occupato l'edificio…\p"
	.string "Pare che il loro CAPO stia\n"
	.string "cercando dei POKéMON forti.$"

gFameCheckerFlavorText_Giovanni2::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che tipo è?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il CAPO di TEAM ROCKET\n"
	.string "è orribilmente crudele!\p"
	.string "Per lui, i POKéMON sono\n"
	.string "solo strumenti.$"

gFameCheckerFlavorText_Giovanni3::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Questo è il mio nascondiglio!\p"
	.string "Qui voglio ricostituire TEAM\n"
	.string "ROCKET!$"

gFameCheckerFlavorText_Giovanni4::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Che cosa fa?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ah, davvero?\n"
	.string "GIOVANNI era il CAPOPALESTRA di\l"
	.string "SMERALDOPOLI?$"

gFameCheckerFlavorText_Giovanni5::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Famiglia e amici?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sai che assomigli al figlio\n"
	.string "di GIOVANNI?\p"
	.string "Però il figlio di GIOVANNI\n"
	.string "ha i capelli rossi.$"

gFameCheckerPersonName_ProfOak::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PROF. OAK$"

gFameCheckerPersonQuote_ProfOak::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: PROF. OAK\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Perché i POKéMON si impegnano così\n"
	.string "tanto nella lotta, secondo te?\p"
	.string "Io credo che lo facciano per\n"
	.string "riconoscenza verso l'affetto che\l"
	.string "dimostriamo per loro.\p"
	.string "Non dimenticarlo mai!$"

gFameCheckerPersonName_Daisy::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MARGI$"

gFameCheckerPersonQuote_Daisy::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: MARGI\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mentre continuo a sorseggiare il\n"
	.string "mio tè, diventi sempre più forte!\p"
	.string "Spero che non diventerai un\n"
	.string "avversario troppo potente per il\l"
	.string "mio fratellino!$"

gFameCheckerPersonName_Brock::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BROCK$"

gFameCheckerPersonQuote_Brock::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: BROCK\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ci sono sicuramente molti grandi\n"
	.string "ALLENATORI in questo mondo.\p"
	.string "Per questo dobbiamo continuare ad\n"
	.string "allenarci e a migliorare.$"

gFameCheckerPersonName_Misty::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MISTY$"

gFameCheckerPersonQuote_Misty::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: MISTY\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Continuerò ad allenarmi qui\n"
	.string "nella PALESTRA.\p"
	.string "E quando sarò abbastanza forte,\n"
	.string "mi metterò in viaggio, come te!$"

gFameCheckerPersonName_LtSurge::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LT. SURGE$"

gFameCheckerPersonQuote_LtSurge::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: LT. SURGE\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ehi! Il tuo stile mi ha davvero\n"
	.string "elettrizzato, sai?\p"
	.string "Non sapevo che un ALLENATORE\n"
	.string "potesse avere tanto coraggio.\p"
	.string "E ho dovuto ricredermi sul tuo\n"
	.string "conto!$"

gFameCheckerPersonName_Erika::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ERIKA$"

gFameCheckerPersonQuote_Erika::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: ERIKA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sono così contenta che ci siano\n"
	.string "ALLENATORI forti come te!\p"
	.string "Il solo fatto di pensare alla tua\n"
	.string "forza mi sprona a fare sempre\l"
	.string "meglio!\p"
	.string "Torna a trovarmi, qualche volta!\n"
	.string "Zzz…$"

gFameCheckerPersonName_Koga::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}KOGA$"

gFameCheckerPersonQuote_Koga::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: KOGA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Io e te dobbiamo lavorare con\n"
	.string "sempre maggiore determinazione per\l"
	.string "raggiungere i nostri obiettivi!\p"
	.string "Ora ti saluto, devo andare ad\n"
	.string "allenare mia figlia.$"

gFameCheckerPersonName_Sabrina::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SABRINA$"

gFameCheckerPersonQuote_Sabrina::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: SABRINA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Il tuo amore verso i POKéMON…\p"
	.string "…è una forza che i miei poteri\n"
	.string "psichici non potranno mai\l"
	.string "eguagliare!$"

gFameCheckerPersonName_Blaine::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BLAINE$"

gFameCheckerPersonQuote_Blaine::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: BLAINE\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I miei POKéMON di tipo\n"
	.string "FUOCO diventano sempre più forti!\p"
	.string "Ascolta, ti faccio un quiz: sai\n"
	.string "quanti POKéMON di tipo FUOCO\l"
	.string "esistono?$"

gFameCheckerPersonName_Lorelei::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LORELEI$"

gFameCheckerPersonQuote_Lorelei::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: LORELEI\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Volevo solo ringraziarti per il tuo\n"
	.string "grande aiuto!\p"
	.string "Ma questo non significa che non\n"
	.string "voglia batterti!\p"
	.string "Fai attenzione!$"

gFameCheckerPersonName_Bruno::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BRUNO$"

gFameCheckerPersonQuote_Bruno::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: BRUNO\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ho avuto modo di vedere la grande\n"
	.string "potenza dei tuoi POKéMON.\p"
	.string "La prossima volta, però, ti\n"
	.string "insegnerò come allenarli al meglio.$"

gFameCheckerPersonName_Agatha::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AGATHA$"

gFameCheckerPersonQuote_Agatha::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: AGATHA\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Con l'età, non provare a\n"
	.string "rammollirti come quel pantofolaio\l"
	.string "di OAK!\p"
	.string "Continua a lottare, come me!$"

gFameCheckerPersonName_Lance::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LANCE$"

gFameCheckerPersonQuote_Lance::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: LANCE\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Sto pensando di tornare\n"
	.string "nella mia città natale.\p"
	.string "Là voglio continuare a potenziare i\n"
	.string "miei POKéMON di tipo DRAGO.\p"
	.string "Chissà, magari un giorno ti inviterò\n"
	.string "e ti mostrerò i luoghi dove sono\l"
	.string "cresciuto!$"

gFameCheckerPersonName_Bill::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BILL$"

gFameCheckerPersonQuote_Bill::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: BILL\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Ciao! CELIO mi ha parlato molto\n"
	.string "bene di te!\p"
	.string "Mi fa piacere, sai?\p"
	.string "Promettimi che verrai a trovarmi\n"
	.string "appena trovi un POKéMON raro!$"

gFameCheckerPersonName_MrFuji::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MR. FUJI$"

gFameCheckerPersonQuote_MrFuji::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: MR. FUJI\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Non preoccuparti solo della\n"
	.string "felicità dei tuoi POKéMON…\p"
	.string "…ma per la felicità di tutti i\n"
	.string "POKéMON del mondo!$"

gFameCheckerPersonName_Giovanni::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GIOVANNI$"

gFameCheckerPersonQuote_Giovanni::
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Da: GIOVANNI\n"
	.string "A: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Non ho proprio niente da dirti.\p"
	.string "Continuerò a concentrarmi per\n"
	.string "diventare sempre più forte. E degli\l"
	.string "altri, non mi importa!$"

gFameCheckerFlavorTextOriginLocation_ProfOak0::
	.string "BIANCAVILLA$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
	.string "LABORATORIO$"

gFameCheckerFlavorTextOriginLocation_ProfOak2::
	.string "LABORATORIO$"

gFameCheckerFlavorTextOriginLocation_ProfOak3::
	.string "SMERALDOPOLI$"

gFameCheckerFlavorTextOriginLocation_ProfOak4::
	.string "LEGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_ProfOak5::
	.string "LABORATORIO$"

gFameCheckerFlavorTextOriginLocation_Daisy0::
	.string "LABORATORIO$"

gFameCheckerFlavorTextOriginLocation_Daisy1::
	.string "ARANCIOPOLI$"

gFameCheckerFlavorTextOriginLocation_Daisy2::
	.string "LABIRINTO MARINO$"

gFameCheckerFlavorTextOriginLocation_Daisy3::
	.string "SMERALDOPOLI$"

gFameCheckerFlavorTextOriginLocation_Daisy4::
	.string "VILLAZZURRA$"

gFameCheckerFlavorTextOriginLocation_Daisy5::
	.string "QUARTISOLA$"

gFameCheckerFlavorTextOriginLocation_Brock0::
	.string "PLUMBEOPOLI$"

gFameCheckerFlavorTextOriginLocation_Brock1::
	.string "PALESTRA PLUMBEOPOLI$"

gFameCheckerFlavorTextOriginLocation_Brock2::
	.string "PLUMBEOPOLI$"

gFameCheckerFlavorTextOriginLocation_Brock3::
	.string "PERCORSO 4$"

gFameCheckerFlavorTextOriginLocation_Brock4::
	.string "MONTE LUNA$"

gFameCheckerFlavorTextOriginLocation_Brock5::
	.string "MUSEO PLUMBEOPOLI$"

gFameCheckerFlavorTextOriginLocation_Misty0::
	.string "CELESTOPOLI$"

gFameCheckerFlavorTextOriginLocation_Misty1::
	.string "PALESTRA CELESTOPOLI$"

gFameCheckerFlavorTextOriginLocation_Misty2::
	.string "PALESTRA CELESTOPOLI$"

gFameCheckerFlavorTextOriginLocation_Misty3::
	.string "ISOLE SPUMARINE$"

gFameCheckerFlavorTextOriginLocation_Misty4::
	.string "CAPO CELESTOPOLI$"

gFameCheckerFlavorTextOriginLocation_Misty5::
	.string "CELESTOPOLI$"

gFameCheckerFlavorTextOriginLocation_LtSurge0::
	.string "ARANCIOPOLI$"

gFameCheckerFlavorTextOriginLocation_LtSurge1::
	.string "PALESTRA ARANCIOPOLI$"

gFameCheckerFlavorTextOriginLocation_LtSurge2::
	.string "PALESTRA ARANCIOPOLI$"

gFameCheckerFlavorTextOriginLocation_LtSurge3::
	.string "PALESTRA ARANCIOPOLI$"

gFameCheckerFlavorTextOriginLocation_LtSurge4::
	.string "PALESTRA ARANCIOPOLI$"

gFameCheckerFlavorTextOriginLocation_LtSurge5::
	.string "ARANCIOPOLI$"

gFameCheckerFlavorTextOriginLocation_Erika0::
	.string "AZZURROPOLI$"

gFameCheckerFlavorTextOriginLocation_Erika1::
	.string "PALESTRA AZZURROPOLI$"

gFameCheckerFlavorTextOriginLocation_Erika2::
	.string "PALESTRA AZZURROPOLI$"

gFameCheckerFlavorTextOriginLocation_Erika3::
	.string "PALESTRA AZZURROPOLI$"

gFameCheckerFlavorTextOriginLocation_Erika4::
	.string "PALESTRA AZZURROPOLI$"

gFameCheckerFlavorTextOriginLocation_Erika5::
	.string "VILLAZZURRA$"

gFameCheckerFlavorTextOriginLocation_Koga0::
	.string "FUCSIAPOLI$"

gFameCheckerFlavorTextOriginLocation_Koga1::
	.string "PALESTRA FUCSIAPOLI$"

gFameCheckerFlavorTextOriginLocation_Koga2::
	.string "PALESTRA FUCSIAPOLI$"

gFameCheckerFlavorTextOriginLocation_Koga3::
	.string "FUCSIAPOLI$"

gFameCheckerFlavorTextOriginLocation_Koga4::
	.string "FUCSIAPOLI$"

gFameCheckerFlavorTextOriginLocation_Koga5::
	.string "ZONA SAFARI$"

gFameCheckerFlavorTextOriginLocation_Sabrina0::
	.string "ZAFFERANOPOLI$"

gFameCheckerFlavorTextOriginLocation_Sabrina1::
	.string "TERZISOLA$"

gFameCheckerFlavorTextOriginLocation_Sabrina2::
	.string "PALESTRA ZAFFERANOPOLI$"

gFameCheckerFlavorTextOriginLocation_Sabrina3::
	.string "PALESTRA ZAFFERANOPOLI$"

gFameCheckerFlavorTextOriginLocation_Sabrina4::
	.string "ZAFFERANOPOLI$"

gFameCheckerFlavorTextOriginLocation_Sabrina5::
	.string "PALESTRA ZAFFERANOPOLI$"

gFameCheckerFlavorTextOriginLocation_Blaine0::
	.string "ISOLA CANNELLA$"

gFameCheckerFlavorTextOriginLocation_Blaine1::
	.string "PALESTRA ISOLA CANNELLA$"

gFameCheckerFlavorTextOriginLocation_Blaine2::
	.string "PALESTRA ISOLA CANNELLA$"

gFameCheckerFlavorTextOriginLocation_Blaine3::
	.string "ISOLA CANNELLA$"

gFameCheckerFlavorTextOriginLocation_Blaine4::
	.string "PALESTRA ISOLA CANNELLA$"

gFameCheckerFlavorTextOriginLocation_Blaine5::
	.string "PERLA dei MARI$"

gFameCheckerFlavorTextOriginLocation_Lorelei0::
	.string "LEGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lorelei1::
	.string "LEGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lorelei2::
	.string "QUARTISOLA$"

gFameCheckerFlavorTextOriginLocation_Lorelei3::
	.string "QUINTISOLA$"

gFameCheckerFlavorTextOriginLocation_Lorelei4::
	.string "QUARTISOLA$"

gFameCheckerFlavorTextOriginLocation_Lorelei5::
	.string "QUARTISOLA$"

gFameCheckerFlavorTextOriginLocation_Bruno0::
	.string "LEGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_Bruno1::
	.string "LEGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_Bruno2::
	.string "ZAFFERANOPOLI$"

gFameCheckerFlavorTextOriginLocation_Bruno3::
	.string "TERME LAVICHE$"

gFameCheckerFlavorTextOriginLocation_Bruno4::
	.string "SECONDISOLA$"

gFameCheckerFlavorTextOriginLocation_Bruno5::
	.string "CANYON SEPTION$"

gFameCheckerFlavorTextOriginLocation_Agatha0::
	.string "LEGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_Agatha1::
	.string "ALTOPIANO BLU$"

gFameCheckerFlavorTextOriginLocation_Agatha2::
	.string "ALTOPIANO BLU$"

gFameCheckerFlavorTextOriginLocation_Agatha3::
	.string "SETTIMISOLA$"

gFameCheckerFlavorTextOriginLocation_Agatha4::
	.string "LEGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_Agatha5::
	.string "SESTISOLA$"

gFameCheckerFlavorTextOriginLocation_Lance0::
	.string "LEGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lance1::
	.string "LEGA POKéMON$"

gFameCheckerFlavorTextOriginLocation_Lance2::
	.string "ZAFFERANOPOLI$"

gFameCheckerFlavorTextOriginLocation_Lance3::
	.string "CENTRO C. AZZURROPOLI$"

gFameCheckerFlavorTextOriginLocation_Lance4::
	.string "ALTOPIANO BLU$"

gFameCheckerFlavorTextOriginLocation_Lance5::
	.string "ALTOPIANO BLU$"

gFameCheckerFlavorTextOriginLocation_Bill0::
	.string "CELESTOPOLI$"

gFameCheckerFlavorTextOriginLocation_Bill1::
	.string "CELESTOPOLI$"

gFameCheckerFlavorTextOriginLocation_Bill2::
	.string "FUCSIAPOLI$"

gFameCheckerFlavorTextOriginLocation_Bill3::
	.string "PRIMISOLA$"

gFameCheckerFlavorTextOriginLocation_Bill4::
	.string "PRIMISOLA$"

gFameCheckerFlavorTextOriginLocation_Bill5::
	.string "PRIMISOLA$"

gFameCheckerFlavorTextOriginLocation_MrFuji0::
	.string "LAVANDONIA$"

gFameCheckerFlavorTextOriginLocation_MrFuji1::
	.string "TORRE POKéMON$"

gFameCheckerFlavorTextOriginLocation_MrFuji2::
	.string "LAVANDONIA$"

gFameCheckerFlavorTextOriginLocation_MrFuji3::
	.string "LAVANDONIA$"

gFameCheckerFlavorTextOriginLocation_MrFuji4::
	.string "PALESTRA ISOLA CANNELLA$"

gFameCheckerFlavorTextOriginLocation_MrFuji5::
	.string "ISOLA CANNELLA$"

gFameCheckerFlavorTextOriginLocation_Giovanni0::
	.string "RIFUGIO ROCKET$"

gFameCheckerFlavorTextOriginLocation_Giovanni1::
	.string "SILPH SPA$"

gFameCheckerFlavorTextOriginLocation_Giovanni2::
	.string "SILPH SPA$"

gFameCheckerFlavorTextOriginLocation_Giovanni3::
	.string "PALESTRA SMERALDOPOLI$"

gFameCheckerFlavorTextOriginLocation_Giovanni4::
	.string "PALESTRA SMERALDOPOLI$"

gFameCheckerFlavorTextOriginLocation_Giovanni5::
	.string "MAGAZZINO ROCKET$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
	.string "CARTELLO$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
	.string "PROF. OAK$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
	.string "ASSISTENTE$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
	.string "POKéGIORNALE$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
	.string "ASSISTENTE$"

gFameCheckerFlavorTextOriginObjectName_Daisy0::
	.string "ASSISTENTE$"

gFameCheckerFlavorTextOriginObjectName_Daisy1::
	.string "DONNA$"

gFameCheckerFlavorTextOriginObjectName_Daisy2::
	.string "UOMO$"

gFameCheckerFlavorTextOriginObjectName_Daisy3::
	.string "POKéGIORNALE$"

gFameCheckerFlavorTextOriginObjectName_Daisy4::
	.string "VECCHIETTA$"

gFameCheckerFlavorTextOriginObjectName_Daisy5::
	.string "POKéGIORNALE$"

gFameCheckerFlavorTextOriginObjectName_Brock0::
	.string "CARTELLO$"

gFameCheckerFlavorTextOriginObjectName_Brock1::
	.string "BROCK$"

gFameCheckerFlavorTextOriginObjectName_Brock2::
	.string "GIOVANE$"

gFameCheckerFlavorTextOriginObjectName_Brock3::
	.string "RAGAZZO$"

gFameCheckerFlavorTextOriginObjectName_Brock4::
	.string "UOMO$"

gFameCheckerFlavorTextOriginObjectName_Brock5::
	.string "POKéGIORNALE$"

gFameCheckerFlavorTextOriginObjectName_Misty0::
	.string "CARTELLO$"

gFameCheckerFlavorTextOriginObjectName_Misty1::
	.string "MISTY$"

gFameCheckerFlavorTextOriginObjectName_Misty2::
	.string "LUIS$"

gFameCheckerFlavorTextOriginObjectName_Misty3::
	.string "GIOVANE$"

gFameCheckerFlavorTextOriginObjectName_Misty4::
	.string "SIGNORA$"

gFameCheckerFlavorTextOriginObjectName_Misty5::
	.string "POKéGIORNALE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
	.string "CARTELLO$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
	.string "LT. SURGE$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
	.string "PIERLUIGI$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
	.string "PIERLUIGI$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
	.string "AURELIO$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
	.string "POKéGIORNALE$"

gFameCheckerFlavorTextOriginObjectName_Erika0::
	.string "CARTELLO$"

gFameCheckerFlavorTextOriginObjectName_Erika1::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika2::
	.string "ALESSANDRA$"

gFameCheckerFlavorTextOriginObjectName_Erika3::
	.string "TAMIA$"

gFameCheckerFlavorTextOriginObjectName_Erika4::
	.string "ERIKA$"

gFameCheckerFlavorTextOriginObjectName_Erika5::
	.string "POKéGIORNALE$"

gFameCheckerFlavorTextOriginObjectName_Koga0::
	.string "CARTELLO$"

gFameCheckerFlavorTextOriginObjectName_Koga1::
	.string "KOGA$"

gFameCheckerFlavorTextOriginObjectName_Koga2::
	.string "KIRK$"

gFameCheckerFlavorTextOriginObjectName_Koga3::
	.string "CARINE$"

gFameCheckerFlavorTextOriginObjectName_Koga4::
	.string "POKéGIORNALE$"

gFameCheckerFlavorTextOriginObjectName_Koga5::
	.string "UOMO$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
	.string "CARTELLO$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
	.string "GIOVANE$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
	.string "SABRINA$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
	.string "POKéGIORNALE$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
	.string "TYRON$"

gFameCheckerFlavorTextOriginObjectName_Blaine0::
	.string "CARTELLO$"

gFameCheckerFlavorTextOriginObjectName_Blaine1::
	.string "BLAINE$"

gFameCheckerFlavorTextOriginObjectName_Blaine2::
	.string "LEOPOLDO$"

gFameCheckerFlavorTextOriginObjectName_Blaine3::
	.string "DONNA$"

gFameCheckerFlavorTextOriginObjectName_Blaine4::
	.string "FOTO$"

gFameCheckerFlavorTextOriginObjectName_Blaine5::
	.string "POKéGIORNALE$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "LORELEI$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "VECCHIETTO$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "POKéGIORNALE$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "BAMBINA$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "VECCHIETTA$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "BRUNO$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "POKéGIORNALE$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "MACINATORE$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "DONNA$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "MACINATORE$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "MACINATORE$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "MACINATORE$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "POKéGIORNALE$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "AGATHA$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "VECCHIETTA$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "LANCE$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "DONNA$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "BAMBINA$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "POKéGIORNALE$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "GIOVANE$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "RAGAZZINO$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "VECCHIETTO$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "CELIO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "BAMBINA$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "TEAM ROCKET$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "RIVISTA$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "UOMO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "FOTO$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "POKéGIORNALE$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "SCIENZIATO$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "SCIENZIATO$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "GIOVANNI$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "UOMO$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "GIDEON$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "POKéGIORNALE\p"
	.string "Servizio speciale su…\n"
	.string "BROCK di PLUMBEOPOLI!\p"
	.string "BROCK ride di rado, ma quando\n"
	.string "inizia, non riesce più a fermarsi!$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "POKéGIORNALE\p"
	.string "Servizio speciale su…\n"
	.string "MISTY di CELESTOPOLI!\p"
	.string "MISTY è una fan di LORELEI\n"
	.string "dei SUPERQUATTRO!$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "POKéGIORNALE\p"
	.string "Servizio speciale su…\n"
	.string "LT. SURGE di ARANCIOPOLI!\p"
	.string "Pare che in America, dov'è nato,\n"
	.string "facesse il pilota.\p"
	.string "Il suo aereo era alimentato con\n"
	.string "l'energia dei POKéMON.$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "POKéGIORNALE\p"
	.string "Servizio speciale su…\n"
	.string "ERIKA di AZZURROPOLI!\p"
	.string "Quando è sola nella PALESTRA di\n"
	.string "AZZURROPOLI, pare che ERIKA\l"
	.string "ogni tanto schiacci un pisolino.$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "POKéGIORNALE\p"
	.string "Servizio speciale su…\n"
	.string "KOGA di FUCSIAPOLI!\p"
	.string "Pare che KOGA abbia ottime\n"
	.string "conoscenze di medicina.\p"
	.string "Spesso prepara addirittura dei\n"
	.string "medicamenti per curare i POKéMON.$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "POKéGIORNALE\p"
	.string "Servizio speciale su…\n"
	.string "SABRINA di ZAFFERANOPOLI!\p"
	.string "Pare che SABRINA, durante la\n"
	.string "lotta, possa comunicare con\l"
	.string "i suoi POKéMON senza parlare.$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "POKéGIORNALE\p"
	.string "Servizio speciale su…\n"
	.string "BLAINE dell'ISOLA CANNELLA!\p"
	.string "Pare che BLAINE si liberi della\n"
	.string "sua aria cupa soltanto quando\l"
	.string "pensa a nuove domande per il quiz.$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "POKéGIORNALE\p"
	.string "Servizio speciale su…\n"
	.string "LORELEI dei SUPERQUATTRO!\p"
	.string "Famosa per la freddezza e la\n"
	.string "perfezione del suo stile di lotta,\l"
	.string "LORELEI ha in serbo una sorpresa!$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "POKéGIORNALE\p"
	.string "Servizio speciale su…\n"
	.string "BRUNO dei SUPERQUATTRO!\p"
	.string "Pare che BRUNO sia entrato nei\n"
	.string "SUPERQUATTRO per l'ambizione\l"
	.string "di battere i migliori ALLENATORI.$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "POKéGIORNALE\p"
	.string "Servizio speciale su…\n"
	.string "AGATHA dei SUPERQUATTRO!\p"
	.string "Un tempo, AGATHA e il PROF. OAK\n"
	.string "erano grandi rivali come\l"
	.string "ALLENATORI di POKéMON.$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "POKéGIORNALE\p"
	.string "Servizio speciale su…\n"
	.string "LANCE dei SUPERQUATTRO!\p"
	.string "Si dice che il nonno di LANCE\n"
	.string "fosse a capo di una leggendaria\l"
	.string "banda di domatori di draghi.$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "POKéGIORNALE\p"
	.string "Servizio speciale sul…\n"
	.string "PROF. OAK, ricercatore POKéMON!\p"
	.string "Pare che MARGI e {RIVAL} vivano\n"
	.string "con il nonno, il PROF. OAK.$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "Una vecchia copia del\n"
	.string "POKéGIORNALE…\p"
	.string "Servizio speciale sulla…\n"
	.string "GARA POKéMON di Primavera!\p"
	.string "Vincitrice della GARA POKéMON\n"
	.string "di quest'anno è MARGI OAK\l"
	.string "di BIANCAVILLA!$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "POKéGIORNALE\p"
	.string "Edizione speciale su…\n"
	.string "MR. FUJI della CASA POKéMON!\p"
	.string "Purtroppo non è stato possibile\n"
	.string "ottenere un'intervista da MR. FUJI.\p"
	.string "Possiamo comunque confermare la\n"
	.string "grande gentilezza di quest'uomo,\l"
	.string "apprezzato da tutti a LAVANDONIA.$"
