Text_CardKeyOpenedDoor::
	.string "Evviva!\n"
	.string "L'APRIPORTA ha funzionato!$"

Text_ItNeedsCardKey::
	.string "Oh, no!\n"
	.string "Ci vuole l'APRIPORTA!$"

Text_AccessedProfOaksPC::
	.string "Accesso al PC del PROF. OAK.\p"
	.string "Accesso al Sistema Valutazione\n"
	.string "POKéDEX.$"

Text_HavePokedexRated::
	.string "Vuoi far valutare il tuo POKéDEX?$"

Text_ClosedLinkToProfOaksPC::
	.string "Fine collegamento con il PC del\n"
	.string "PROF. OAK.$"

Text_VoiceRangOutDontRunAway::
	.string "Si sente una voce:\n"
	.string "“Non scappare!”.$"

@ Uncear what the below unused JP texts were for
Text_IdLikeToSeeRequest::
	.string "えっとー\n"
	.string "{STR_VAR_2}が　みてみたいなー\p"
	.string "それも　{STR_VAR_1}{STR_VAR_3}\n"
	.string "{STR_VAR_2}が　みてみたいなー$"

Text_ThankYouForShowingMe::
	.string "わぁー　すごい！\n"
	.string "{STR_VAR_1}{STR_VAR_3}{STR_VAR_2}だー！\p"
	.string "ありがとー\n"
	.string "また　よろしくねー！$"

Text_ThatsNotRight::
	.string "それっ　ちがうよー！$"

Text_ISee::
	.string "そっか‥$"

Text_TheDoorIsClosed::
	.string "ドアは　しまっている‥$"

Text_TheDoorIsOpen::
	.string "La porta è aperta…$"
