Text_OnlySkilledTrainersAllowedThrough::
	.string "Solo i veri ALLENATORI possono\n"
	.string "passare.\p"
	.string "Non hai ancora la {STR_VAR_1}!$"

Text_CantLetYouPass::
	.string "Le regole sono regole.\n"
	.string "Non puoi passare!$"

Text_OhThatsBadgeGoRightAhead::
	.string "Oh! Ma questa è la {STR_VAR_1}!\n"
	.string "Passa pure!$"

Text_OnlyPassWithBadgeDontHaveYet::
	.string "Puoi passare solo se hai la\n"
	.string "{STR_VAR_1}!\p"
	.string "Non ce l'hai ancora!\p"
	.string "Per accedere alla LEGA POKéMON,\n"
	.string "devi procurartela!$"

Text_OnlyPassWithBadgeOhGoAhead::
	.string "Puoi passare solo se hai la\n"
	.string "{STR_VAR_1}!\p"
	.string "Oh! È proprio la {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "Benissimo!\n"
	.string "Passa pure!$"
