
@ Unused, from R/S
Text_DoorOpenedFarAway::
	.string "どこか　とおくの　とびらが\n"
	.string "ひらいたような　おとだ‥‥$"

@ Unused, from R/S
Text_BigHoleInTheWall::
	.string "かべに\n"
	.string "おおきな　あなが　あいている！$"

Text_WirelessClubUndergoingAdjustments::
	.string "Sono spiacente.\n"
	.string "Il CLUB WIRELESS POKéMON\lè chiuso per lavori.$"

Text_AppearsToBeUndergoingAdjustments::
	.string "Sembra che sia chiuso per lavori.$"

Text_HandedOverItem::
	.string "{PLAYER} cede\n"
	.string "{STR_VAR_1}.$"

Text_GiveNicknameToThisMon::
	.string "Vuoi dare un soprannome a\n"
	.string "{STR_VAR_1}?$"
