FuchsiaCity_Mart_Text_DontTheyHaveSafariZonePennants::
    .ifdef ENGLISH
    .string "Don't they have any pennants\n"
    .string "promoting the SAFARI ZONE?\p"
    .string "How about some paper lanterns?\n"
    .string "Aren't there even any calendars?$"
    .endif
    .ifdef SPANISH
    .string "¿Tienes alguna bandera de la ZONA\n"
    .string "del SAFARI?\p"
    .string "¿Tienes cartas? ¿Y calendarios?$"
    .endif

FuchsiaCity_Mart_Text_DidYouTryXSpeed::
    .ifdef ENGLISH
    .string "Did you try X SPEED?\n"
    .string "It speeds up a POKéMON in battle.$"
    .endif
    .ifdef SPANISH
    .string "¿Has probado VELOCIDAD X?\n"
    .string "¡Da más velocidad a los POKéMON\l"
    .string "en combate!$"
    .endif

