Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend::
    .ifdef ENGLISH
    .string "I'm on a relaxing ride on my new\n"
    .string "bike with my girlfriend.$"
    .endif
    .ifdef SPANISH
    .string "¡Voy a darme una vuelta con mi\n"
    .string "novia!$"
    .endif

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes::
    .ifdef ENGLISH
    .string "We're going riding together on our\n"
    .string "new bikes.$"
    .endif
    .ifdef SPANISH
    .string "¡Vamos a pedalear juntos!$"
    .endif

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore::
    .ifdef ENGLISH
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It's the CELADON DEPT. STORE!$"
    .endif
    .ifdef SPANISH
    .string "Has usado los prismáticos...\p"
    .string "¡Es el CENTRO COMERCIAL\n"
    .string "de CIUDAD AZULONA!$"
    .endif

Route16_NorthEntrance_2F_Text_LongPathOverWater::
    .ifdef ENGLISH
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "There's a long path over water far\n"
    .string "away.$"
    .endif
    .ifdef SPANISH
    .string "Has usado los prismáticos...\p"
    .string "¡Hay un largo camino sobre\n"
    .string "el agua!$"
    .endif

Route16_NorthEntrance_2F_Text_GiveAmuletCoinIfCaught40::
    .ifdef ENGLISH
    .string "Hi! Remember me?\n"
    .string "I'm one of PROF. OAK's AIDES.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on 40 species, I'm supposed to\l"
    .string "give you a reward.\p"
    .string "PROF. OAK entrusted me with an\n"
    .string "AMULET COIN for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "40 kinds of POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¡Hola! ¿Te acuerdas de mí?\n"
    .string "¡Soy AYUDANTE del PROF. OAK!\p"
    .string "¡Si atrapaste 40 tipos de POKéMON,\n"
    .string "se supone que debería darte\l"
    .string "MON. AMULETO!\p"
    .string "Dime, {PLAYER}. ¿Tienes ya al menos\n"
    .string "40 tipos de POKéMON?$"
    .endif

Route16_NorthEntrance_2F_Text_GreatHereYouGo::
    .ifdef ENGLISH
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"
    .endif
    .ifdef SPANISH
    .string "¡Bien! ¡Has logrado {STR_VAR_3} tipos\n"
    .string "de POKéMON!\p"
    .string "¡Enhorabuena!\n"
    .string "¡Aquí tienes!$"
    .endif

Route16_NorthEntrance_2F_Text_ReceivedAmuletCoinFromAide::
    .ifdef ENGLISH
    .string "{PLAYER} received the AMULET COIN\n"
    .string "from the AIDE.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo MON. AMULETO\n"
    .string "de manos del AYUDANTE!$"
    .endif

Route16_NorthEntrance_2F_Text_ExplainAmuletCoin::
    .ifdef ENGLISH
    .string "An AMULET COIN is an item to be\n"
    .string "held by a POKéMON.\p"
    .string "If the POKéMON appears in a winning\n"
    .string "battle, you will earn more money.$"
    .endif
    .ifdef SPANISH
    .string "Una MONEDA AMULETO es un objeto\n"
    .string "que puede llevar un POKéMON.\p"
    .string "Si gana el POKéMON que la tenga,\n"
    .string "conseguirás más dinero.$"
    .endif

