SafariZone_East_Text_HowManyDidYouCatch::
    .ifdef ENGLISH
    .string "How many did you catch?\n"
    .string "I'm bushed from the effort!$"
    .endif
    .ifdef SPANISH
    .string "¿Cuántos has capturado? ¡Yo estoy\n"
    .string "agotado de tanto trabajar!$"
    .endif

SafariZone_East_Text_CaughtChanseyAllWorthwhile::
    .ifdef ENGLISH
    .string "I caught a CHANSEY!\p"
    .string "That makes this all worthwhile.$"
    .endif
    .ifdef SPANISH
    .string "¡Capturé un CHANSEY!\p"
    .string "¡Y por eso todos mis esfuerzos\n"
    .string "han merecido la pena!$"
    .endif

SafariZone_East_Text_TiredFromAllTheFun::
    .ifdef ENGLISH
    .string "Whew!\n"
    .string "I'm tired from all the fun!$"
    .endif
    .ifdef SPANISH
    .string "¡Ufff!\n"
    .string "¡Estoy agotado de tanta diversión!$"
    .endif

