FuchsiaCity_Text_DidYouTrySafariGame::
    .ifdef ENGLISH
    .string "Did you try the SAFARI GAME?\p"
    .string "There are some rare POKéMON that\n"
    .string "can only be caught there.$"
    .endif
    .ifdef SPANISH
    .string "¿Has probado el JUEGO del SAFARI?\p"
    .string "Algunos POKéMON sólo pueden ser\n"
    .string "atrapados allí.$"
    .endif

FuchsiaCity_Text_SafariZoneZooInFront::
    .ifdef ENGLISH
    .string "The SAFARI ZONE has a zoo in front\n"
    .string "of the entrance.\p"
    .string "Out back is the SAFARI GAME for\n"
    .string "catching POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "En la ZONA del SAFARI hay un zoo\n"
    .string "delante de la entrada.\p"
    .string "¡En su interior está el JUEGO del\n"
    .string "SAFARI, para atrapar POKéMON!$"
    .endif

FuchsiaCity_Text_WheresSara::
    .ifdef ENGLISH
    .string "ERIK: Where's SARA?\n"
    .string "I said I'd meet her here.$"
    .endif
    .ifdef SPANISH
    .string "ENRIQUE: ¿Dónde estará SARA?\n"
    .string "Quedamos en vernos aquí.$"
    .endif

FuchsiaCity_Text_ItemBallInThere::
    .ifdef ENGLISH
    .string "That item ball in there…\n"
    .string "Were you wanting that?\p"
    .string "Me, too!\n"
    .string "…Huh? That's a POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "Ese objeto redondo de ahí...\n"
    .string "¿Lo quieres?\p"
    .string "¡Yo también! ¡Anda, es un POKéMON!$"
    .endif

FuchsiaCity_Text_CitySign::
    .ifdef ENGLISH
    .string "FUCHSIA CITY\n"
    .string "Behold! It's Passion Pink!$"
    .endif
    .ifdef SPANISH
    .string "¡Mirad CIUDAD FUCSIA!\n"
    .string "¡La pasión rosa!$"
    .endif

FuchsiaCity_Text_SafariZoneSign::
    .ifdef ENGLISH
    .string "POKéMON PARADISE\n"
    .string "SAFARI ZONE$"
    .endif
    .ifdef SPANISH
    .string "ZONA SAFARI:\n"
    .string "PARAÍSO-POKéMON$"
    .endif

FuchsiaCity_Text_SafariGameSign::
    .ifdef ENGLISH
    .string "SAFARI GAME\n"
    .string "POKéMON-U-CATCH!$"
    .endif
    .ifdef SPANISH
    .string "JUEGO DEL SAFARI:\n"
    .string "¡ATRAPA-POKéMON!$"
    .endif

FuchsiaCity_Text_WardensHomeSign::
    .ifdef ENGLISH
    .string "SAFARI ZONE\n"
    .string "WARDEN'S HOME$"
    .endif
    .ifdef SPANISH
    .string "CASA DEL GUARDA\n"
    .string "DEL SAFARI$"
    .endif

FuchsiaCity_Text_SafariZoneOfficeSign::
    .ifdef ENGLISH
    .string "POKéMON PARADISE!\n"
    .string "Welcome to the SAFARI ZONE!\l"
    .string "SAFARI ZONE OFFICE$"
    .endif
    .ifdef SPANISH
    .string "ZONA SAFARI:\n"
    .string "PARAÍSO-POKéMON\l"
    .string "OFICINA ZONA SAFARI$"
    .endif

FuchsiaCity_Text_GymSign::
    .ifdef ENGLISH
    .string "FUCHSIA CITY POKéMON GYM\n"
    .string "LEADER: KOGA\l"
    .string "The Poisonous Ninja Master$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de FUCSIA: KOGA\l"
    .string "El venenoso maestro ninja.$"
    .endif

FuchsiaCity_Text_ChanseySign::
    .ifdef ENGLISH
    .string "Name: CHANSEY\n"
    .string "Catching one is all up to chance.$"
    .endif
    .ifdef SPANISH
    .string "Nombre: CHANSEY\n"
    .string "¡Atrapar uno es una cuestión\l"
    .string "de suerte!$"
    .endif

FuchsiaCity_Text_VoltorbSign::
    .ifdef ENGLISH
    .string "Name: VOLTORB\n"
    .string "The very image of a POKé BALL.$"
    .endif
    .ifdef SPANISH
    .string "Nombre: VOLTORB\n"
    .string "La viva imagen de una POKé BALL.$"
    .endif

FuchsiaCity_Text_KangaskhanSign::
    .ifdef ENGLISH
    .string "Name: KANGASKHAN\p"
    .string "A maternal POKéMON that raises its\n"
    .string "young in a pouch on its belly.$"
    .endif
    .ifdef SPANISH
    .string "Nombre: KANGASKHAN\n"
    .string "Un POKéMON maternal que cría a sus\l"
    .string "hijos en una bolsa de su barriga.$"
    .endif

FuchsiaCity_Text_SlowpokeSign::
    .ifdef ENGLISH
    .string "Name: SLOWPOKE\n"
    .string "Friendly and very slow moving.$"
    .endif
    .ifdef SPANISH
    .string "Nombre: SLOWPOKE\n"
    .string "Simpático y de movimientos\l"
    .string "muy lentos.$"
    .endif

FuchsiaCity_Text_LaprasSign::
    .ifdef ENGLISH
    .string "Name: LAPRAS\n"
    .string "AKA the king of the seas.$"
    .endif
    .ifdef SPANISH
    .string "Nombre: LAPRAS\n"
    .string "También conocido como el rey\l"
    .string "de los mares.$"
    .endif

FuchsiaCity_Text_OmanyteSign::
    .ifdef ENGLISH
    .string "Name: OMANYTE\n"
    .string "An extremely rare POKéMON that was\l"
    .string "regenerated from a fossil.$"
    .endif
    .ifdef SPANISH
    .string "Nombre: OMANYTE\n"
    .string "Un POKéMON que fue regenerado\l"
    .string "a partir de un fósil.$"
    .endif

FuchsiaCity_Text_KabutoSign::
    .ifdef ENGLISH
    .string "Name: KABUTO\n"
    .string "An extremely rare POKéMON that was\l"
    .string "regenerated from a fossil.$"
    .endif
    .ifdef SPANISH
    .string "Nombre: KABUTO\n"
    .string "Un POKéMON que fue regenerado\l"
    .string "a partir de un fósil.$"
    .endif

@ Unused. May have been meant to be the placeholder text for the zoo mons, similar to RB's "!" text
FuchsiaCity_Text_Ellipsis::
    .string "……$"

Text_SubstituteTeach::
    .ifdef ENGLISH
    .string "Aww, I wish I was a KANGASKHAN\n"
    .string "baby.\p"
    .string "I'd love to be a substitute for the\n"
    .string "baby…\p"
    .string "And snuggle in the mother\n"
    .string "KANGASKHAN's belly pouch.\p"
    .string "But only POKéMON can use the\n"
    .string "technique SUBSTITUTE…\p"
    .string "Want me to teach SUBSTITUTE to\n"
    .string "one of your POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "Me encantaría ser el bebé\n"
    .string "de un KANGASKHAN.\p"
    .string "No me importaría nada ocupar\n"
    .string "el lugar del bebé...\p"
    .string "Y acurrucarme en la bolsa de la\n"
    .string "barriga de KANGASKHAN.\p"
    .string "Pero los POKéMON son los únicos\n"
    .string "que pueden usar SUSTITUTO...\p"
    .string "¿Quieres que le enseñe SUSTITUTO\n"
    .string "a uno de tus POKéMON?$"
    .endif

Text_SubstituteDeclined::
    .ifdef ENGLISH
    .string "Oh, really?\n"
    .string "SUBSTITUTE seems so fun…$"
    .endif
    .ifdef SPANISH
    .string "¿En serio?\n"
    .string "¡Pero si SUSTITUTO está genial!$"
    .endif

Text_SubstituteWhichMon::
    .ifdef ENGLISH
    .string "Which POKéMON wants to learn\n"
    .string "SUBSTITUTE?$"
    .endif
    .ifdef SPANISH
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe SUSTITUTO?$"
    .endif

Text_SubstituteTaught::
    .ifdef ENGLISH
    .string "Boy, what I'd give to crawl inside\n"
    .string "a KANGASKHAN belly pouch…$"
    .endif
    .ifdef SPANISH
    .string "¡Ay, lo que daría por acurrucarme\n"
    .string "en la panza de un KANGASKHAN!$"
    .endif

FuchsiaCity_Text_MyFatherIsGymLeader::
    .ifdef ENGLISH
    .string "My father is the GYM LEADER of\n"
    .string "this town.\p"
    .string "I'm training to use POISON POKéMON\n"
    .string "as well as my father.$"
    .endif
    .ifdef SPANISH
    .string "Mi padre es el LÍDER del GIMNASIO\n"
    .string "de este pueblo.\p"
    .string "Yo me estoy entrenando para usar\n"
    .string "POKéMON del tipo VENENO igual\l"
    .string "que hace mi padre.$"
    .endif

