ThreeIsland_DunsparceTunnel_Text_ProspectingForGold::
    .ifdef ENGLISH
    .string "Hey, there!\n"
    .string "How's it going?\p"
    .string "What am I doing here, you ask?\n"
    .string "Why, I'm prospecting for gold!\p"
    .string "When I strike it rich, I'm buying\n"
    .string "a house in KANTO.$"
    .endif
    .ifdef SPANISH
    .string "Eh, ¿qué tal?\p"
    .string "¿Que qué hago aquí?\n"
    .string "Pues estoy buscando oro.\p"
    .string "Cuando consiga una fortuna,\n"
    .string "me compraré una casita en KANTO.$"
    .endif

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou::
    .ifdef ENGLISH
    .string "Hey, there! How's it going?\n"
    .string "Did you hear? I've struck gold!\p"
    .string "You remembered that I was\n"
    .string "prospecting, didn't you?\p"
    .string "You can't begin to imagine just\n"
    .string "how happy I am.\p"
    .string "So, I'll show you!\n"
    .string "This is for you!$"
    .endif
    .ifdef SPANISH
    .string "Eh, ¿cómo lo llevas?\n"
    .string "¿Sabes qué? ¡He encontrado oro!\p"
    .string "¿Recuerdas que te dije que estaba\n"
    .string "buscando?\p"
    .string "¡No te puedes ni imaginar lo feliz\n"
    .string "que soy!\p"
    .string "Toma, anda.\n"
    .string "Compartiré un poco contigo.$"
    .endif

ThreeIsland_DunsparceTunnel_Text_ThatsANugget::
    .ifdef ENGLISH
    .string "That's a NUGGET!\p"
    .string "I can't give you any nuggets of\n"
    .string "wisdom, so that'll have to do!$"
    .endif
    .ifdef SPANISH
    .string "Es una PEPITA.\p"
    .string "No puedo darte pepitas de la\n"
    .string "sabiduría, ¡sólo esto!$"
    .endif

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull::
    .ifdef ENGLISH
    .string "Whoops, your BAG is crammed full!\n"
    .string "I'll give this to you later.$"
    .endif
    .ifdef SPANISH
    .string "Vaya, tienes la MOCHILA hasta\n"
    .string "arriba... Bueno, otra vez será.$"
    .endif

