ThreeIsland_Text_IslandSign::
	.string "ILE 3\n"
	.string "L'île où on se sent chez soi$"

ThreeIsland_Text_IslandBelongsToUs::
	.string "Yahaaa!\p"
	.string "A partir d'aujourd'hui, cette\n"
	.string "île nous appartient!$"

ThreeIsland_Text_GoBackToKanto::
	.string "On a pas besoin de vous ici.\n"
	.string "Retournez chez vous à KANTO!$"

ThreeIsland_Text_BossIsOnHisWay::
	.string "Hé, va pleurer ailleurs. Notre boss\n"
	.string "va bientôt arriver.\p"
	.string "Quand il sera là, on va vous faire\n"
	.string "une démonstration de moto que\p"
	.string "vous risquez pas d'oublier!$"

ThreeIsland_Text_GetOffIslandNow::
	.string "Q-quoi?? Pas tant que je serai\n"
	.string "en vie! Partez tout de suite!$"

ThreeIsland_Text_WhosGonnaMakeMe::
	.string "Et qui me fera partir?$"

ThreeIsland_Text_AreYouBossGoBackToKanto::
	.string "C'est toi le chef de cette bande?\n"
	.string "Repartez pour KANTO maintenant!$"

ThreeIsland_Text_JustGotHerePal::
	.string "Hahaa?\p"
	.string "Comme c'est dommage, je\n"
	.string "viens juste d'arriver.\p"
	.string "Quel manque de courtoisie,\n"
	.string "tu arriverais presque à m'énerver.$"

ThreeIsland_Text_FollowersRaisingHavoc::
	.string "Votre gang de motards a semé la\n"
	.string "panique depuis son arrivée ici.\p"
	.string "Est-ce que vous vous rendez\n"
	.string "compte des problèmes que vous\p"
	.string "créez sur cette petite île?$"

ThreeIsland_Text_OughtToBeThankingUs::
	.string "Non, mon gars, j'me rends pas\n"
	.string "compte du tout.\p"
	.string "Regarde autour de toi.\n"
	.string "Y'a rien à faire ici, \p"
	.string "on vous apporte un peu de\n"
	.string "changement.\p"
	.string "Mais si tu tiens tant à retrouver\n"
	.string "ta vie ennuyeuse,\p"
	.string "tu peux toujours essayer de\n"
	.string "nous faire partir.$"

ThreeIsland_Text_YouCowardsToughInPack::
	.string "Grrr… Bande de lâches…\p"
	.string "Vous faites les durs parce que\n"
	.string "vous êtes en groupe…$"

ThreeIsland_Text_WannaMakeSomethingOfYourStaring::
	.string "Quoi, kess tu mates?\n"
	.string "Tu sais pas que c'est pas poli?\p"
	.string "Tu cherches vraiment à ce que\n"
	.string "je m'énerve ou quoi?$"

ThreeIsland_Text_ThatsSmart::
	.string "Bonne réponse. Alors fais-moi\n"
	.string "de l'air maintenant.$"

ThreeIsland_Text_Biker1Intro::
	.string "Hahaha, t'as du cran au moins. Tu\n"
	.string "vas te souvenir de cette raclée…$"

ThreeIsland_Text_Biker1Defeat::
	.string "Quoi…\n"
	.string "J'peux pas le croire!$"

ThreeIsland_Text_Biker1PostBattle::
	.string "Ne t'avise pas de te moquer!$"

ThreeIsland_Text_Biker2Intro::
	.string "T'es pas de KANTO? Tu devrais\n"
	.string "être de notre côté!$"

ThreeIsland_Text_Biker2Defeat::
	.string "Arrête de te la raconter!$"

ThreeIsland_Text_Biker2PostBattle::
	.string "C'est quoi ton problème?\n"
	.string "T'as pas besoin de t'énerver!\p"
	.string "Vraiment pas cool!$"

ThreeIsland_Text_Biker3Intro::
	.string "On a demandé au chef de venir\n"
	.string "ici, mais t'as tout gâché!\p"
	.string "Tu nous fous la honte!$"

ThreeIsland_Text_Biker3Defeat::
	.string "… … …   … … …$"

ThreeIsland_Text_Biker3PostBattle::
	.string "Boss, tu dois faire quelque chose\n"
	.string "contre c'mioche!$"

ThreeIsland_Text_PaxtonIntro::
	.string "Je t'ai regardé, t'en as vraiment\n"
	.string "fait assez, tu crois pas?\p"
	.string "T'es qui? T'es avec eux ou quoi?\p"
	.string "Alors tu vas te battre à leur\n"
	.string "place, OK?$"

ThreeIsland_Text_PaxtonDefeat::
	.string "OK, ça suffit!\n"
	.string "On va partir!\p"
	.string "On est bien contents de quitter\n"
	.string "cette île de vieux!$"

ThreeIsland_Text_PaxtonPostBattle::
	.string "On en avait marre de ces\n"
	.string "bouseux de toute façon!$"

ThreeIsland_Text_ThankYouOhYourMonGotHurt::
	.string "Merci du fond du cœur. Ces voyous\n"
	.string "ne créaient que des problèmes.\p"
	.string "Oh, regarde. Tu as un POKéMON\n"
	.string "blessé.$"

ThreeIsland_Text_GivenFullRestore::
	.string "{PLAYER} reçoit une\n"
	.string "GUERISON.$"

ThreeIsland_Text_OhYourBagIsFull::
	.string "Oh!\n"
	.string "Ton SAC est plein.$"

ThreeIsland_Text_YouveGotImpressiveMons::
	.string "Tes POKéMON sont vraiment\n"
	.string "impressionnants.$"

ThreeIsland_Text_LostelleWentOffTowardsBondBridge::
	.string "Si seulement quelqu'un fort\n"
	.string "comme toi pouvait habiter ici…\p"
	.string "J'espère au moins que tu resteras\n"
	.string "quelque temps.\p"
	.string "… Pardon? Oh, tu\n"
	.string "cherches LOSTELLE?\p"
	.string "Elle est partie vers le PONT DU\n"
	.string "LIEN il n'y a pas longtemps.$"

ThreeIsland_Text_WouldntWantToSeeBikersHereAgain::
	.string "L'ILE 3 est l'île la plus populaire\n"
	.string "du coin.\p"
	.string "Bon, ça manque pourtant\n"
	.string "quelquefois d'animation.\p"
	.string "Mais je souhaite vraiment que ces\n"
	.string "MOTARDS ne reviennent pas.$"

ThreeIsland_Text_WhenDodouEvolvesGoingToPlayGame::
	.string "Je vais aller dresser mon DODUO\n"
	.string "dans les BOIS BAIES.\p"
	.string "Quand il aura évolué, on ira jouer\n"
	.string "à un jeu sur l'ILE 2.$"

ThreeIsland_Text_Doduo::
	.string "DODUO: Dudoo!$"

