ThreeIsland_Text_IslandSign::
    .ifdef ENGLISH
    .string "THREE ISLAND\n"
    .string "Kin Island of Family Bonding$"
    .endif
    .ifdef SPANISH
    .string "ISLA TERA\n"
    .string "Isla familiar para familiares.$"
    .endif

ThreeIsland_Text_IslandBelongsToUs::
    .ifdef ENGLISH
    .string "Hyahoo!\p"
    .string "From this day on, this island\n"
    .string "belongs to us!$"
    .endif
    .ifdef SPANISH
    .string "¡Eeeeeh!\p"
    .string "¡A partir de hoy, esta isla\n"
    .string "nos pertenece!$"
    .endif

ThreeIsland_Text_GoBackToKanto::
    .ifdef ENGLISH
    .string "We don't need you people bringing\n"
    .string "your noise and trouble here!\p"
    .string "We're asking you to go back to\n"
    .string "KANTO!$"
    .endif
    .ifdef SPANISH
    .string "¡Aquí no queremos a nadie que nos\n"
    .string "moleste y nos traiga problemas!\p"
    .string "¡MARCHAOS A KANTO!$"
    .endif

ThreeIsland_Text_BossIsOnHisWay::
    .ifdef ENGLISH
    .string "Hey, go cry somewhere else.\n"
    .string "Our boss is on his way.\p"
    .string "When he gets here, we'll give you\n"
    .string "a k-rad motorbike show you won't\l"
    .string "soon forget!$"
    .endif
    .ifdef SPANISH
    .string "Vete a chillar a otra parte,\n"
    .string "nuestro jefe está en camino.\p"
    .string "¡Cuando llegue, vas a ver de lo\n"
    .string "que somos capaces con las motos!\p"
    .string "¡Vas a flipar!$"
    .endif

ThreeIsland_Text_GetOffIslandNow::
    .ifdef ENGLISH
    .string "W-what!? Not on your life!\n"
    .string "Get off the island now!$"
    .endif
    .ifdef SPANISH
    .string "¿Cómo? ¡Ni se os ocurra!\n"
    .string "¡FUERA DE LA ISLA AHORA MISMO!$"
    .endif

ThreeIsland_Text_WhosGonnaMakeMe::
    .ifdef ENGLISH
    .string "Who's gonna make me?$"
    .endif
    .ifdef SPANISH
    .string "¿Porque tú lo digas?$"
    .endif

ThreeIsland_Text_AreYouBossGoBackToKanto::
    .ifdef ENGLISH
    .string "Are you the boss?\n"
    .string "Go back to KANTO right now!$"
    .endif
    .ifdef SPANISH
    .string "¿Eres tú el jefe?\n"
    .string "¡A KANTO ahora mismo!$"
    .endif

ThreeIsland_Text_JustGotHerePal::
    .ifdef ENGLISH
    .string "Hah?\p"
    .string "I just got here, pal.\p"
    .string "What's with the hostile attitude?\n"
    .string "It's mighty cold of you!$"
    .endif
    .ifdef SPANISH
    .string "Eh, que yo acabo de llegar,\n"
    .string "colega.\p"
    .string "No entiendo por qué te pones tan\n"
    .string "borde. ¡Menuda bienvenida, majo!$"
    .endif

ThreeIsland_Text_FollowersRaisingHavoc::
    .ifdef ENGLISH
    .string "Your gang of followers have been\n"
    .string "raising havoc on their bikes.\p"
    .string "Do you have any idea how much\n"
    .string "trouble they've caused us on the\l"
    .string "island?$"
    .endif
    .ifdef SPANISH
    .string "Tu pandillita se ha puesto en plan\n"
    .string "chulo con las motos y se ha pasado\l"
    .string "un pelín.\p"
    .string "Y a la gente de la isla no le ha\n"
    .string "hecho nada de gracia.$"
    .endif

ThreeIsland_Text_OughtToBeThankingUs::
    .ifdef ENGLISH
    .string "No, man, I don't get it at all.\p"
    .string "Look at this place.\n"
    .string "What do you do for entertainment?\p"
    .string "You ought to be thanking us for\n"
    .string "livening up this sleepy village.\p"
    .string "But hey, if you insist, you can try\n"
    .string "making us leave.$"
    .endif
    .ifdef SPANISH
    .string "Me dejas a cuadros.\p"
    .string "¡Pero si aquí se aburren hasta\n"
    .string "las piedras!\p"
    .string "Deberíais estar agradecidos de\n"
    .string "que hayamos dado vidilla a este\l"
    .string "muermo de isla.\p"
    .string "Pero bueno, si insistes en que\n"
    .string "nos vayamos...$"
    .endif

ThreeIsland_Text_YouCowardsToughInPack::
    .ifdef ENGLISH
    .string "Grr… You cowards…\n"
    .string "So tough in a pack…$"
    .endif
    .ifdef SPANISH
    .string "Grrrr... Sois unos cobardes...\n"
    .string "Y unos pesados...$"
    .endif

ThreeIsland_Text_WannaMakeSomethingOfYourStaring::
    .ifdef ENGLISH
    .string "You, what are you staring at?\n"
    .string "Don't you know it's not polite?\p"
    .string "You wanna make something of it\n"
    .string "or what?$"
    .endif
    .ifdef SPANISH
    .string "Pero ¿qué miras? ¿Nunca te han\n"
    .string "dicho que no se debe mirar tan\l"
    .string "descaradamente a nadie?\p"
    .string "¿Quieres algo o qué?$"
    .endif

ThreeIsland_Text_ThatsSmart::
    .ifdef ENGLISH
    .string "That's smart.\n"
    .string "Keep your nose out of this.$"
    .endif
    .ifdef SPANISH
    .string "Estupendo. Así me gusta, que\n"
    .string "te mantengas al margen de esto.$"
    .endif

ThreeIsland_Text_Biker1Intro::
    .ifdef ENGLISH
    .string "Heh, I like your guts.\n"
    .string "You'll be losing money to me, but…$"
    .endif
    .ifdef SPANISH
    .string "Eh, eres muy valiente.\n"
    .string "Vas a salir perdiendo, pero...$"
    .endif

ThreeIsland_Text_Biker1Defeat::
    .ifdef ENGLISH
    .string "Wha…\n"
    .string "What is this kid?!$"
    .endif
    .ifdef SPANISH
    .string "¡¿Qué?!...\n"
    .string "Pero ¿tú de dónde sales?$"
    .endif

ThreeIsland_Text_Biker1PostBattle::
    .ifdef ENGLISH
    .string "Aww, man…\n"
    .string "Don't you dare laugh!$"
    .endif
    .ifdef SPANISH
    .string "¡Que no se te ocurra reírte!$"
    .endif

ThreeIsland_Text_Biker2Intro::
    .ifdef ENGLISH
    .string "Aren't you from KANTO?\n"
    .string "You should be on our side!$"
    .endif
    .ifdef SPANISH
    .string "Pero ¿tú no eres de KANTO?\n"
    .string "¡Pues deberías estar de nuestro\l"
    .string "lado!$"
    .endif

ThreeIsland_Text_Biker2Defeat::
    .ifdef ENGLISH
    .string "Stop fooling around!$"
    .endif
    .ifdef SPANISH
    .string "Bueno, ¡ya está bien!$"
    .endif

ThreeIsland_Text_Biker2PostBattle::
    .ifdef ENGLISH
    .string "What's the matter with you,\n"
    .string "getting all hot like that?\p"
    .string "Totally uncool, man!$"
    .endif
    .ifdef SPANISH
    .string "Pero ¿a ti qué te pasa?\n"
    .string "¡Ya te vale!$"
    .endif

ThreeIsland_Text_Biker3Intro::
    .ifdef ENGLISH
    .string "We invited the boss out here,\n"
    .string "but you had to mess it up!\p"
    .string "You embarrassed us, man!$"
    .endif
    .ifdef SPANISH
    .string "Le dijimos a nuestro jefe que\n"
    .string "viniera ¡y tú incordiando!\p"
    .string "¡Eres un petardo!$"
    .endif

ThreeIsland_Text_Biker3Defeat::
    .ifdef ENGLISH
    .string "… … …   … … …$"
    .endif
    .ifdef SPANISH
    .string "Ufff...$"
    .endif

ThreeIsland_Text_Biker3PostBattle::
    .ifdef ENGLISH
    .string "Boss, I'm telling you, you've gotta\n"
    .string "do something about this kid!$"
    .endif
    .ifdef SPANISH
    .string "Jefe, ¡no podemos dejar que\n"
    .string "nos saquen los colores!$"
    .endif

ThreeIsland_Text_PaxtonIntro::
    .ifdef ENGLISH
    .string "I've been watching you, and I'd say\n"
    .string "you've done enough.\p"
    .string "What are you, their friend or\n"
    .string "something?\p"
    .string "Then I guess you'll be battling me\n"
    .string "in their place.$"
    .endif
    .ifdef SPANISH
    .string "He estado observándote y creo que\n"
    .string "te has pasado.\p"
    .string "¿Pero tú, de parte de quién estás?\p"
    .string "Ahora te las quieres ver conmigo,\n"
    .string "¿no?$"
    .endif

ThreeIsland_Text_PaxtonDefeat::
    .ifdef ENGLISH
    .string "All right, enough!\n"
    .string "We'll leave like you wanted!\p"
    .string "We'll be happy to see the last of\n"
    .string "this boring island!$"
    .endif
    .ifdef SPANISH
    .string "Mira, ya me tienes harto.\n"
    .string "¡Nos piramos!\p"
    .string "¡Estábamos deseando\n"
    .string "marcharnos!$"
    .endif

ThreeIsland_Text_PaxtonPostBattle::
    .ifdef ENGLISH
    .string "Humph! Yeah, go right on hanging\n"
    .string "around with these hayseeds!$"
    .endif
    .ifdef SPANISH
    .string "¡Hala, que te lo pases bien\n"
    .string "en este petardo de isla!$"
    .endif

ThreeIsland_Text_ThankYouOhYourMonGotHurt::
    .ifdef ENGLISH
    .string "Thank you! Those goons were\n"
    .string "nothing but bad trouble.\p"
    .string "Oh, look, your POKéMON got hurt\n"
    .string "on my account.$"
    .endif
    .ifdef SPANISH
    .string "¡Muchas gracias! ¡La gentuza esa\n"
    .string "ha revolucionado al personal!\p"
    .string "Anda, tus POKéMON están heridos\n"
    .string "por mi culpa...$"
    .endif

ThreeIsland_Text_GivenFullRestore::
    .ifdef ENGLISH
    .string "{PLAYER} was given\n"
    .string "a FULL RESTORE.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} recibió un RESTAU. TODO.$"
    .endif

ThreeIsland_Text_OhYourBagIsFull::
    .ifdef ENGLISH
    .string "Oh?\n"
    .string "Your BAG is full.$"
    .endif
    .ifdef SPANISH
    .string "Vaya...\n"
    .string "La MOCHILA está llena...$"
    .endif

ThreeIsland_Text_YouveGotImpressiveMons::
    .ifdef ENGLISH
    .string "You've got seriously impressive\n"
    .string "POKéMON with you.$"
    .endif
    .ifdef SPANISH
    .string "Tienes unos POKéMON\n"
    .string "espectaculares.$"
    .endif

ThreeIsland_Text_LostelleWentOffTowardsBondBridge::
    .ifdef ENGLISH
    .string "It'd be fantastic if someone as\n"
    .string "strong as you lived here.\p"
    .string "I hope you'll at least stay here\n"
    .string "a while.\p"
    .string "…I beg your pardon?\n"
    .string "You're looking for LOSTELLE?\p"
    .string "LOSTELLE went off towards BOND\n"
    .string "BRIDGE a while ago.$"
    .endif
    .ifdef SPANISH
    .string "Sería estupendo que alguien como\n"
    .string "tú viviera aquí.\p"
    .string "Espero que te quedes un tiempo\n"
    .string "al menos.\p"
    .string "¿Cómo?\n"
    .string "¿Que estás buscando a PEDRITA?\p"
    .string "PEDRITA se fue en dirección al\n"
    .string "PUENTE UNIÓN hace un rato...$"
    .endif

ThreeIsland_Text_WouldntWantToSeeBikersHereAgain::
    .ifdef ENGLISH
    .string "THREE ISLAND is actually the most\n"
    .string "populous of the islands here.\p"
    .string "Still, it could be less sleepy.\p"
    .string "But I wouldn't want to see goons\n"
    .string "like those BIKERS here again.$"
    .endif
    .ifdef SPANISH
    .string "ISLA TERA es la isla más poblada\n"
    .string "de esta zona.\p"
    .string "Vale que no sea la más animada,\n"
    .string "pero mejor así que tener a los\l"
    .string "salvajes de las motos por aquí.$"
    .endif

ThreeIsland_Text_WhenDodouEvolvesGoingToPlayGame::
    .ifdef ENGLISH
    .string "I'm going to train my DODUO in the\n"
    .string "BERRY FOREST.\p"
    .string "When it evolves, I'm going to play\n"
    .string "a game on TWO ISLAND.$"
    .endif
    .ifdef SPANISH
    .string "Voy a entrenar a mi DODUO en el\n"
    .string "BOSQUE BAYA.\p"
    .string "Cuando evolucione, participaré\n"
    .string "en algún juego en ISLA SECUNDA.$"
    .endif

ThreeIsland_Text_Doduo::
    .ifdef ENGLISH
    .string "DODUO: Gigiih!$"
    .endif
    .ifdef SPANISH
    .string "DODUO: ¡Dodu, odudodu!$"
    .endif

