CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji::
    .string "Una foto de BLAINE\n"
    .string "y el SR. FUJI...\p"
    .string "Aparecen juntos con una sonrisa\n"
    .string "de oreja a oreja.$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
    .string "Aquí estudiamos a los POKéMON.\p"
    .string "La gente suele traernos POKéMON\n"
    .string "raros para analizarlos.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
    .string "¡Una foto del fundador del\n"
    .string "LABORATORIO, el DR. FUJI!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
    .string "LABORATORIO POKéMON\n"
    .string "Sala de reuniones$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
    .string "LABORATORIO POKéMON\n"
    .string "Sala de I + D$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
    .string "LABORATORIO POKéMON\n"
    .string "Sala de pruebas$"
