CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji::
    .ifdef ENGLISH
    .string "It's a photo of BLAINE and\n"
    .string "MR. FUJI.\p"
    .string "They're standing shoulder to\n"
    .string "shoulder with big grins.$"
    .endif
    .ifdef SPANISH
    .string "Una foto de BLAINE\n"
    .string "y el SR. FUJI...\p"
    .string "Aparecen juntos con una sonrisa\n"
    .string "de oreja a oreja.$"
    .endif

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
    .ifdef ENGLISH
    .string "We study POKéMON extensively\n"
    .string "every day.\p"
    .string "People often bring us rare POKéMON\n"
    .string "for examination.$"
    .endif
    .ifdef SPANISH
    .string "Aquí estudiamos a los POKéMON.\p"
    .string "La gente suele traernos POKéMON\n"
    .string "raros para analizarlos.$"
    .endif

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
    .ifdef ENGLISH
    .string "A photo of the LAB's founder…\n"
    .string "DR. FUJI?!$"
    .endif
    .ifdef SPANISH
    .string "¡Una foto del fundador del\n"
    .string "LABORATORIO, el DR. FUJI!$"
    .endif

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
    .ifdef ENGLISH
    .string "POKéMON LAB\n"
    .string "Meeting Room$"
    .endif
    .ifdef SPANISH
    .string "LABORATORIO POKéMON\n"
    .string "Sala de reuniones$"
    .endif

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
    .ifdef ENGLISH
    .string "POKéMON LAB\n"
    .string "R & D Room$"
    .endif
    .ifdef SPANISH
    .string "LABORATORIO POKéMON\n"
    .string "Sala de I + D$"
    .endif

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
    .ifdef ENGLISH
    .string "POKéMON LAB\n"
    .string "Testing Room$"
    .endif
    .ifdef SPANISH
    .string "LABORATORIO POKéMON\n"
    .string "Sala de pruebas$"
    .endif

