CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji::
	.string "Ein Foto von PYRO und MR. FUJI!\p"
	.string "Sie stehen eng beisammen und\n"
	.string "grinsen!$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
	.string "Wir erforschen hier POKéMON.\p"
	.string "Wir erstellen oft Gutachten über\n"
	.string "seltene POKéMON.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
	.string "Der Gründer des LABORATORIUMS,\n"
	.string "DR. FUJI!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
	.string "POKéMON-LABOR\n"
	.string "Konferenzraum$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
	.string "POKéMON-LABOR\n"
	.string "Forschung und Entwicklung$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
	.string "POKéMON-LABOR\n"
	.string "Versuchsabteilung$"

