MtMoon_1F_Text_MarcosIntro::
    .string "¡GUAU!\n¡Me has impresionado!\l"
    .string "¡Pero si eres muy joven!$"

MtMoon_1F_Text_MarcosDefeat::
    .string "¡Uau!\n"
    .string "¡Has vuelto a impresionarme!$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "¡No tienes edad para estar aquí!$"

MtMoon_1F_Text_JoshIntro::
    .string "¿Estás aquí para explorar?$"

MtMoon_1F_Text_JoshDefeat::
    .string "¡Perder es lo peor!$"

MtMoon_1F_Text_JoshPostBattle::
    .string "¡Vine aquí para impresionar\n"
    .string "a las chicas!$"

MtMoon_1F_Text_MiriamIntro::
    .string "¡Uau! ¡Esto es mucho más grande\n"
    .string "de lo que creía!$"

MtMoon_1F_Text_MiriamDefeat::
    .string "¡Oh!\n¡He perdido!$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "¿Cómo se sale de aquí?$"

MtMoon_1F_Text_JovanIntro::
    .string "¡Eh!\n"
    .string "¡No te pases conmigo!$"

MtMoon_1F_Text_JovanDefeat::
    .string "¡Mis POKéMON no lo han conseguido!$"

MtMoon_1F_Text_JovanPostBattle::
    .string "¡Debo encontrar POKéMON\n"
    .string "más fuertes!$"

MtMoon_1F_Text_IrisIntro::
    .string "¿Qué?\n"
    .string "Estoy esperando aquí a mis amigos.$"

MtMoon_1F_Text_IrisDefeat::
    .string "¿He perdido?$"

MtMoon_1F_Text_IrisPostBattle::
    .string "Dicen que aquí hay unos fósiles\n"
    .string "muy raros.$"

MtMoon_1F_Text_KentIntro::
    .string "En la cueva hay unos hombres\n"
    .string "muy sospechosos. ¿Y tú, qué?$"

MtMoon_1F_Text_KentDefeat::
    .string "¡Me has ganado!$"

MtMoon_1F_Text_KentPostBattle::
    .string "¡Los he visto!\n"
    .string "¡Son del TEAM ROCKET! ¡Seguro!$"

MtMoon_1F_Text_RobbyIntro::
    .string "¡Cruza esta cueva y llegarás\n"
    .string "a CIUDAD CELESTE!$"

MtMoon_1F_Text_RobbyDefeat::
    .string "He perdido.$"

MtMoon_1F_Text_RobbyPostBattle::
    .string "¡ZUBAT es muy fuerte!\n"
    .string "¡Atrapar uno sería muy útil!$"

MtMoon_1F_Text_ZubatIsABloodsucker::
    .string "¡Cuidado!\n"
    .string "¡Los ZUBAT son unos chupasangre!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "Estoy buscando fósiles en las\n"
    .string "entrañas del MT. MOON.\p"
    .string "A veces me ayuda BROCK,\n"
    .string "del GIMNASIO de PLATEADA.$"
