PokemonMansion_B1F_Text_LewisIntro::
	.string "Oh-oh.\n"
	.string "Où que je suis, moi?$"

PokemonMansion_B1F_Text_LewisDefeat::
	.string "Oups.$"

PokemonMansion_B1F_Text_LewisPostBattle::
	.string "De bons objets traînent dans\n"
	.string "le coin.$"

PokemonMansion_B1F_Text_IvanIntro::
	.string "La science?\n"
	.string "C'est le pied.$"

PokemonMansion_B1F_Text_IvanDefeat::
	.string "…\n"
	.string "Bah pourquoi?$"

PokemonMansion_B1F_Text_IvanPostBattle::
	.string "J'adore cet endroit! J'y fais mon\n"
	.string "internat!$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
	.string "Rapport: 1er Septembre.\n"
	.string "MEWTWO est trop puissant.\p"
	.string "Nous sommes impuissants face à\n"
	.string "ses pièges…$"

