PokemonMansion_B1F_Text_LewisIntro::
	.string "Wo bin ich hier gelandet?$"

PokemonMansion_B1F_Text_LewisDefeat::
	.string "Autsch!$"

PokemonMansion_B1F_Text_LewisPostBattle::
	.string "Hier liegt viel nützliches Zeug\n"
	.string "herum!$"

PokemonMansion_B1F_Text_IvanIntro::
	.string "Hier wäre der ideale Platz für ein\n"
	.string "Labor!$"

PokemonMansion_B1F_Text_IvanDefeat::
	.string "Was hab ich nur falsch gemacht?$"

PokemonMansion_B1F_Text_IvanPostBattle::
	.string "Hier gefällt es mir!\n"
	.string "Man kann prima forschen!$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
	.string "TAGEBUCH: 1. SEPTEMBER\n"
	.string "MEWTU wird immer stärker.\p"
	.string "Wir konnten die unkontrollierten\n"
	.string "Wutausbrüche nicht eindämmen!$"

