PokemonMansion_B1F_Text_LewisIntro::
    .ifdef ENGLISH
    .string "Uh-oh…\n"
    .string "Where am I now?$"
    .endif
    .ifdef SPANISH
    .string "¡Oh, oh!\n"
    .string "¿Dónde estoy ahora?$"
    .endif

PokemonMansion_B1F_Text_LewisDefeat::
    .ifdef ENGLISH
    .string "Awooh!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya!$"
    .endif

PokemonMansion_B1F_Text_LewisPostBattle::
    .ifdef ENGLISH
    .string "You can find stuff lying around.\n"
    .string "The residents must've left them.$"
    .endif
    .ifdef SPANISH
    .string "Puedes recoger cosas del suelo.$"
    .endif

PokemonMansion_B1F_Text_IvanIntro::
    .ifdef ENGLISH
    .string "This place is ideal for a lab.\n"
    .string "Look at all this space.$"
    .endif
    .ifdef SPANISH
    .string "Este lugar es ideal para un\n"
    .string "laboratorio.$"
    .endif

PokemonMansion_B1F_Text_IvanDefeat::
    .ifdef ENGLISH
    .string "What was that for?$"
    .endif
    .ifdef SPANISH
    .string "¿Era esto lo que querías?$"
    .endif

PokemonMansion_B1F_Text_IvanPostBattle::
    .ifdef ENGLISH
    .string "I like it here.\n"
    .string "It's conducive to my studies.$"
    .endif
    .ifdef SPANISH
    .string "¡Me encanta este sitio! ¡Es muy\n"
    .string "apropiado para mis estudios!$"
    .endif

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
    .ifdef ENGLISH
    .string "Diary: Sept. 1\n"
    .string "MEWTWO is far too powerful.\p"
    .string "We have failed to curb its vicious\n"
    .string "tendencies…$"
    .endif
    .ifdef SPANISH
    .string "Diario: 1 de septiembre.\n"
    .string "MEWTWO es demasiado poderoso.\p"
    .string "No hemos sabido contener sus malos\n"
    .string "instintos.$"
    .endif

