SevenIsland_TrainerTower_Text_DarioIntro::
    .ifdef ENGLISH
    .string "I sensed your approach.$"
    .endif
    .ifdef SPANISH
    .string "He notado que te acercabas.$"
    .endif

SevenIsland_TrainerTower_Text_DarioDefeat::
    .ifdef ENGLISH
    .string "Give up…$"
    .endif
    .ifdef SPANISH
    .string "Me rindo...$"
    .endif

SevenIsland_TrainerTower_Text_DarioPostBattle::
    .ifdef ENGLISH
    .string "In your future, I sense that you\n"
    .string "will meet many others.\p"
    .string "I think you will be linked to each\n"
    .string "other by a strange power.$"
    .endif
    .ifdef SPANISH
    .string "Siento que te vas a encontrar\n"
    .string "con mucha gente.\p"
    .string "Establecerás cierta conexión\n"
    .string "mediante una extraña fuerza.$"
    .endif

SevenIsland_TrainerTower_Text_RodetteIntro::
    .ifdef ENGLISH
    .string "Somewhere on this island, peculiar\n"
    .string "POKéMON are sleeping.$"
    .endif
    .ifdef SPANISH
    .string "En alguna parte de esta isla,\n"
    .string "hay extraños POKéMON durmiendo.$"
    .endif

SevenIsland_TrainerTower_Text_RodetteDefeat::
    .ifdef ENGLISH
    .string "What an amazing TRAINER!$"
    .endif
    .ifdef SPANISH
    .string "¡Tú sí que sabes entrenar POKéMON!$"
    .endif

SevenIsland_TrainerTower_Text_RodettePostBattle::
    .ifdef ENGLISH
    .string "Somewhere on this island, peculiar\n"
    .string "POKéMON are sleeping.\p"
    .string "Could it be that they're waiting\n"
    .string "for you?$"
    .endif
    .ifdef SPANISH
    .string "En alguna parte de esta isla,\n"
    .string "hay extraños POKéMON durmiendo.\p"
    .string "¿Te estarán esperando?$"
    .endif

SevenIsland_TrainerTower_Text_TrainerTowerSign::
    .ifdef ENGLISH
    .string "TRAINER TOWER ENTRANCE\n"
    .string "Rise to the Challenge, TRAINERS!$"
    .endif
    .ifdef SPANISH
    .string "ENTRADA A LA TORRE DESAFÍO\n"
    .string "¡A por todas, ENTRENADORES!$"
    .endif

SevenIsland_TrainerTower_Text_TrainerTowerAhead::
    .ifdef ENGLISH
    .string "TRAINER TOWER AHEAD$"
    .endif
    .ifdef SPANISH
    .string "HACIA LA TORRE DESAFÍO$"
    .endif

@ Unused text perhaps indicating Trainer Tower was planned to be unlocked by something
SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed::
    .string "トレーナータワーには\n"
    .string "いまは　はいれない　みたい‥$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn::
    .string "トレーナータワーが　あいてる！\n"
    .string "さっそく　はいってみよう！$"

