SevenIsland_TrainerTower_Text_DarioIntro::
    .string "He notado que te acercabas.$"

SevenIsland_TrainerTower_Text_DarioDefeat::
    .string "Me rindo...$"

SevenIsland_TrainerTower_Text_DarioPostBattle::
    .string "Siento que te vas a encontrar\n"
    .string "con mucha gente.\p"
    .string "Establecerás cierta conexión\n"
    .string "mediante una extraña fuerza.$"

SevenIsland_TrainerTower_Text_RodetteIntro::
    .string "En alguna parte de esta isla,\n"
    .string "hay extraños POKéMON durmiendo.$"

SevenIsland_TrainerTower_Text_RodetteDefeat::
    .string "¡Tú sí que sabes entrenar POKéMON!$"

SevenIsland_TrainerTower_Text_RodettePostBattle::
    .string "En alguna parte de esta isla,\n"
    .string "hay extraños POKéMON durmiendo.\p"
    .string "¿Te estarán esperando?$"

SevenIsland_TrainerTower_Text_TrainerTowerSign::
    .string "ENTRADA A LA TORRE DESAFÍO\n"
    .string "¡A por todas, ENTRENADORES!$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead::
    .string "HACIA LA TORRE DESAFÍO$"

@ Unused text perhaps indicating Trainer Tower was planned to be unlocked by something
SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed::
    .string "トレーナータワーには\n"
    .string "いまは　はいれない　みたい‥$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn::
    .string "トレーナータワーが　あいてる！\n"
    .string "さっそく　はいってみよう！$"
