VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
    .ifdef ENGLISH
    .string "Won't you admire my PIKACHU's\n"
    .string "adorable tail?$"
    .endif
    .ifdef SPANISH
    .string "¿No te gusta la adorable cola\n"
    .string "de mi PIKACHU?$"
    .endif

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
    .ifdef ENGLISH
    .string "Humph!\p"
    .string "My PIKACHU is twice as cute as\n"
    .string "that one!$"
    .endif
    .ifdef SPANISH
    .string "¡Mi PIKACHU es el doble\n"
    .string "de gracioso que ése!$"
    .endif

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
    .ifdef ENGLISH
    .string "I just adore my SEEL!\n"
    .string "It's so lovable!\p"
    .string "It squeals, “Kyuuuh,” when I\n"
    .string "hug it!$"
    .endif
    .ifdef SPANISH
    .string "¡Me encanta mi SEEL!\p"
    .string "¡Chilla cuando lo abrazo!$"
    .endif

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
    .ifdef ENGLISH
    .string "Oh, dear!\p"
    .string "My SEEL is far more attractive.\n"
    .string "By double, I would say.$"
    .endif
    .ifdef SPANISH
    .string "¡Por favor!\p"
    .string "¡Mi SEEL es mucho más atractivo!\n"
    .string "¡El doble de atractivo!$"
    .endif

VermilionCity_PokemonFanClub_Text_Pikachu::
    .ifdef ENGLISH
    .string "PIKACHU: Chu! Pikachu!$"
    .endif
    .ifdef SPANISH
    .string "PIKACHU: ¡Chu! ¡Pika, pika!$"
    .endif

VermilionCity_PokemonFanClub_Text_Seel::
    .ifdef ENGLISH
    .string "SEEL: Kyuoo!$"
    .endif
    .ifdef SPANISH
    .string "SEEL: ¡Eeel!$"
    .endif

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
    .ifdef ENGLISH
    .string "I chair the POKéMON Fan Club!\p"
    .string "I raise more than a hundred\n"
    .string "POKéMON!\p"
    .string "I'm very fussy when it comes to\n"
    .string "POKéMON! I surely am!\p"
    .string "So…\p"
    .string "Did you come visit to hear about\n"
    .string "my POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¡Yo presido el Club de Fans de los\n"
    .string "POKéMON!\p"
    .string "¡Tengo más de 100 POKéMON!\p"
    .string "¡Soy muy exigente en todo lo que\n"
    .string "se refiere a los POKéMON!\p"
    .string "Bueno...\p"
    .string "¿Has venido para saber más cosas\n"
    .string "de mis POKéMON?$"
    .endif

VermilionCity_PokemonFanClub_Text_ChairmansStory::
    .ifdef ENGLISH
    .string "Good!\n"
    .string "Then listen up!\p"
    .string "My favorite RAPIDASH…\p"
    .string "It's…cute…lovely…smart… \n"
    .string "plus…amazing…you think so?…\l"
    .string "oh yes…it's…stunning…\l"
    .string "kindly…love it!\p"
    .string "Hug it…when…sleeping…warm\n"
    .string "and cuddly…spectacular…\l"
    .string "ravishing…\l"
    .string "…Oops! Look at the time!\l"
    .string "I kept you too long!\p"
    .string "Thanks for hearing me out!\n"
    .string "I want you to have this!$"
    .endif
    .ifdef SPANISH
    .string "¡Muy bien!\n"
    .string "¡Pues escucha!\p"
    .string "Mi preferido es RAPIDASH...\p"
    .string "Es... gracioso... cariñoso... veloz\n"
    .string "e increíble... ¿No crees?...\l"
    .string "Es sorprendente... simpático...\l"
    .string "¡Yo lo adoro!\p"
    .string "Si lo abrazas... cuando duerme...\n"
    .string "es tan cálido... y mimoso... es\l"
    .string "espectacular... encantador...\l"
    .string "¡Hala, mira qué hora es!\l"
    .string "¡Hablo demasiado!\p"
    .string "¡Gracias por escucharme!\n"
    .string "¡Toma esto!$"
    .endif

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
    .ifdef ENGLISH
    .string "{PLAYER} received a BIKE VOUCHER\n"
    .string "from the CHAIRMAN.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió el BONO BICI\n"
    .string "de manos del PRESIDENTE!$"
    .endif

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
    .ifdef ENGLISH
    .string "Take that BIKE VOUCHER to the\n"
    .string "BIKE SHOP in CERULEAN CITY.\p"
    .string "Exchange that for a BICYCLE\n"
    .string "free of charge!\p"
    .string "Don't worry, my favorite FEAROW\n"
    .string "will FLY me anywhere I need to go.\p"
    .string "So, I have no need for a BICYCLE.\p"
    .string "I hope you like cycling!$"
    .endif
    .ifdef SPANISH
    .string "¡Cámbialo por una BICICLETA\n"
    .string "en la TIENDA de BICIS de CIUDAD\l"
    .string "CELESTE!\p"
    .string "¡Es gratis!\p"
    .string "¡No te apures por mí, mi FEAROW\n"
    .string "me lleva VOLANDO a donde sea!\p"
    .string "¡No necesito BICICLETA!\p"
    .string "¡Espero que te guste pedalear!$"
    .endif

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
    .ifdef ENGLISH
    .string "Oh. Come back when you want to\n"
    .string "hear my story!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh! ¡Pues vuelve cuando quieras\n"
    .string "oír mi historia!$"
    .endif

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
    .ifdef ENGLISH
    .string "Hello, {PLAYER}!\p"
    .string "Did you come see me about my\n"
    .string "POKéMON again?\p"
    .string "No?\n"
    .string "Too bad!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, {PLAYER}!\p"
    .string "¿Has vuelto para saber más cosas\n"
    .string "de mi POKéMON?\p"
    .string "¿No?\n"
    .string "¡Qué pena!$"
    .endif

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
    .ifdef ENGLISH
    .string "Make room for this!$"
    .endif
    .ifdef SPANISH
    .string "¡No tienes sitio para esto!$"
    .endif

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
    .ifdef ENGLISH
    .string "Our CHAIRMAN is very vocal about\n"
    .string "POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "El PRESIDENTE habla mucho\n"
    .string "de los POKéMON.$"
    .endif

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
    .ifdef ENGLISH
    .string "Let's all listen politely to other\n"
    .string "TRAINERS!$"
    .endif
    .ifdef SPANISH
    .string "¡Escuchemos con atención a otros\n"
    .string "ENTRENADORES!$"
    .endif

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
    .ifdef ENGLISH
    .string "If someone brags, brag right back!$"
    .endif
    .ifdef SPANISH
    .string "¡Si presumen, haz tú lo mismo!$"
    .endif

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
    .ifdef ENGLISH
    .string "Our CHAIRMAN really does adore his\n"
    .string "POKéMON.\p"
    .string "But the person who is most liked by\n"
    .string "POKéMON is DAISY, I think.$"
    .endif
    .ifdef SPANISH
    .string "A nuestro PRESIDENTE le encantan\n"
    .string "sus POKéMON.\p"
    .string "Pero los POKéMON a quien más\n"
    .string "quieren es a DALIA, creo.$"
    .endif
