FuchsiaCity_House1_Text_WardenIsOldHasFalseTeeth::
    .string "¡El GUARDA de la ZONA del SAFARI\n"
    .string "es ya mayor, pero sigue en activo!\p"
    .string "¡Y lleva dentadura postiza!$"

FuchsiaCity_House1_Text_BillIsMyGrandson::
    .string "¿Mmm?\n"
    .string "¿Conoces a BILL?\p"
    .string "¡Es mi nieto!\p"
    .string "¡Le gustaba coleccionar cosas\n"
    .string "desde niño!$"

FuchsiaCity_House1_Text_BillFilesHisOwnMonData::
    .string "¡BILL registra los datos de sus\n"
    .string "POKéMON en su PC!\p"
    .string "¿Te los ha enseñado?$"
