FuchsiaCity_House1_Text_WardenIsOldHasFalseTeeth::
    .ifdef ENGLISH
    .string "The SAFARI ZONE's WARDEN is old, \n"
    .string "but he's still very much active.\p"
    .string "All his teeth are false, though.$"
    .endif
    .ifdef SPANISH
    .string "¡El GUARDA de la ZONA del SAFARI\n"
    .string "es ya mayor, pero sigue en activo!\p"
    .string "¡Y lleva dentadura postiza!$"
    .endif

FuchsiaCity_House1_Text_BillIsMyGrandson::
    .ifdef ENGLISH
    .string "Hmm?\n"
    .string "You've met BILL?\p"
    .string "He's my grandson!\p"
    .string "He always liked collecting things,\n"
    .string "even as a child!$"
    .endif
    .ifdef SPANISH
    .string "¿Mmm?\n"
    .string "¿Conoces a BILL?\p"
    .string "¡Es mi nieto!\p"
    .string "¡Le gustaba coleccionar cosas\n"
    .string "desde niño!$"
    .endif

FuchsiaCity_House1_Text_BillFilesHisOwnMonData::
    .ifdef ENGLISH
    .string "BILL files his own POKéMON data on\n"
    .string "his PC.\p"
    .string "Did he show you?$"
    .endif
    .ifdef SPANISH
    .string "¡BILL registra los datos de sus\n"
    .string "POKéMON en su PC!\p"
    .string "¿Te los ha enseñado?$"
    .endif

