CinnabarIsland_PokemonLab_Lounge_Text_FoundFossilInMtMoon::
    .ifdef ENGLISH
    .string "I found this most remarkable fossil\n"
    .string "inside MT. MOON.\p"
    .string "I think it's of a rare, prehistoric\n"
    .string "POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Encontré este fósil tan raro\n"
    .string "en el MT. MOON!\p"
    .string "¡Creo que es un POKéMON\n"
    .string "prehistórico y raro!$"
    .endif

