SaffronCity_CopycatsHouse_1F_Text_DaughterIsSelfCentered::
	.string "Meine Tochter ist furchtbar\n"
	.string "schüchtern! Sie hat nur wenige\l"
	.string "Freunde!$"

SaffronCity_CopycatsHouse_1F_Text_DaughterLikesToMimicPeople::
	.string "Meine Tochter ahmt gerne Leute\n"
	.string "nach.\p"
	.string "Wegen ihres Mienenspiels nennt man\n"
	.string "sie die NACHAHMERIN!$"

SaffronCity_CopycatsHouse_1F_Text_Chansey::
	.string "CHANEIRA: Cha! Neera!$"

