SaffronCity_CopycatsHouse_1F_Text_DaughterIsSelfCentered::
    .ifdef ENGLISH
    .string "My daughter is so self-centered.\n"
    .string "She has but a few friends.$"
    .endif
    .ifdef SPANISH
    .string "¡Mi hija está tan metida en sí\n"
    .string "misma que tiene muy pocos amigos!$"
    .endif

SaffronCity_CopycatsHouse_1F_Text_DaughterLikesToMimicPeople::
    .ifdef ENGLISH
    .string "My daughter likes to mimic people.\n"
    .string "It's rather vexing.\p"
    .string "Her mimicry has earned her the\n"
    .string "nickname COPYCAT around here.$"
    .endif
    .ifdef SPANISH
    .string "A mi hija le gusta imitar a la\n"
    .string "gente.\p"
    .string "¡Y por eso la gente de por aquí\n"
    .string "le llama la COPIONA!$"
    .endif

SaffronCity_CopycatsHouse_1F_Text_Chansey::
    .ifdef ENGLISH
    .string "CHANSEY: Chaan! Sii!$"
    .endif
    .ifdef SPANISH
    .string "CHANSEY: ¡Chaan! ¡Chaan!$"
    .endif

