PokemonTower_7F_Text_Grunt1Intro::
    .ifdef ENGLISH
    .string "What do you want?\n"
    .string "Why are you here?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué quieres?\n"
    .string "¿Qué haces aquí?$"
    .endif

PokemonTower_7F_Text_Grunt1Defeat::
    .ifdef ENGLISH
    .string "I give up!$"
    .endif
    .ifdef SPANISH
    .string "¡Me rindo!$"
    .endif

PokemonTower_7F_Text_Grunt1PostBattle::
    .ifdef ENGLISH
    .string "I'm not going to forget this!$"
    .endif
    .ifdef SPANISH
    .string "¡Voy a olvidar todo esto!$"
    .endif

PokemonTower_7F_Text_Grunt2Intro::
    .ifdef ENGLISH
    .string "This old guy marched right up to\n"
    .string "our HIDEOUT.\p"
    .string "Then, he starts ranting about how\n"
    .string "TEAM ROCKET's abusing POKéMON.\p"
    .string "So, we're just talking it over as\n"
    .string "adults.$"
    .endif
    .ifdef SPANISH
    .string "El tipo, que ya tiene unos años,\n"
    .string "se plantó en nuestra GUARIDA.\p"
    .string "Y empezó a decir que estábamos\n"
    .string "haciendo daño a los POKéMON.\p"
    .string "¡La cosa es más que seria!$"
    .endif

PokemonTower_7F_Text_Grunt2Defeat::
    .ifdef ENGLISH
    .string "Please!\n"
    .string "No more!$"
    .endif
    .ifdef SPANISH
    .string "¡Por favor!\n¡Basta!$"
    .endif

PokemonTower_7F_Text_Grunt2PostBattle::
    .ifdef ENGLISH
    .string "POKéMON are only good for making\n"
    .string "money. Why not use them?\p"
    .string "You stay out of our business!$"
    .endif
    .ifdef SPANISH
    .string "¡Los POKéMON sólo sirven para\n"
    .string "ganar dinero!\p"
    .string "¡No te metas en nuestros asuntos!$"
    .endif

PokemonTower_7F_Text_Grunt3Intro::
    .ifdef ENGLISH
    .string "You're not saving anyone, kid!$"
    .endif
    .ifdef SPANISH
    .string "¡No vas a salvar a nadie!$"
    .endif

PokemonTower_7F_Text_Grunt3Defeat::
    .ifdef ENGLISH
    .string "Don't fight us ROCKETS!$"
    .endif
    .ifdef SPANISH
    .string "¡No luches contra nosotros,\n"
    .string "el TEAM ROCKET!$"
    .endif

PokemonTower_7F_Text_Grunt3PostBattle::
    .ifdef ENGLISH
    .string "You're not getting away with this!$"
    .endif
    .ifdef SPANISH
    .string "¡No te saldrás con la tuya así\n"
    .string "como así!$"
    .endif

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
    .ifdef ENGLISH
    .string "MR. FUJI: Heh?\n"
    .string "You came to save me?\p"
    .string "Thank you. But, I came here of my\n"
    .string "own free will.\p"
    .string "I came to calm the spirit of\n"
    .string "CUBONE's mother.\p"
    .string "I think MAROWAK's spirit has\n"
    .string "finally left us.\p"
    .string "I must thank you for your kind\n"
    .string "concern.\p"
    .string "Follow me to my home, POKéMON\n"
    .string "HOUSE, at the foot of this tower.$"
    .endif
    .ifdef SPANISH
    .string "SR. FUJI: ¿Qué?\n"
    .string "¿Has venido a salvarme?\p"
    .string "¡Gracias! Pero estoy aquí por mi\n"
    .string "propia voluntad.\p"
    .string "Vine a calmar el espíritu de la\n"
    .string "madre de CUBONE.\p"
    .string "Creo que el espíritu de MAROWAK\n"
    .string "ya está tranquilo.\p"
    .string "¡Agradezco tu interés!\p"
    .string "Acompáñame a mi casa, a la CASA\n"
    .string "POKéMON, que hay al pie de esta\l"
    .string "torre.$"
    .endif

