PokemonTower_7F_Text_Grunt1Intro::
	.string "Was willst du?\n"
	.string "Warum bist du hier?$"

PokemonTower_7F_Text_Grunt1Defeat::
	.string "Ich gebe auf!$"

PokemonTower_7F_Text_Grunt1PostBattle::
	.string "Das werde ich dir nie verzeihen!$"

PokemonTower_7F_Text_Grunt2Intro::
	.string "Da war so ein alter Knacker, der\n"
	.string "behauptet hat, wir würden POKéMON\l"
	.string "quälen!\p"
	.string "Willst du meine Meinung hören?$"

PokemonTower_7F_Text_Grunt2Defeat::
	.string "Bitte!\n"
	.string "Lass mich in Ruhe!$"

PokemonTower_7F_Text_Grunt2PostBattle::
	.string "POKéMON sind nur zum Geldverdienen\n"
	.string "gut!\p"
	.string "Halte dich aus unseren\n"
	.string "Angelegenheiten heraus!$"

PokemonTower_7F_Text_Grunt3Intro::
	.string "Du wirst niemanden retten!$"

PokemonTower_7F_Text_Grunt3Defeat::
	.string "Leg dich nicht mit dem TEAM ROCKET\n"
	.string "an!$"

PokemonTower_7F_Text_Grunt3PostBattle::
	.string "Du wirst nicht ungestraft\n"
	.string "davonkommen!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
	.string "MR. FUJI: Was?\n"
	.string "Du kommst, um mich zu retten?\p"
	.string "Vielen Dank!\n"
	.string "Aber ich bin freiwillig hier.\p"
	.string "Ich kam her, um die Seele von\n"
	.string "TRAGOSSOs Mutter zu beruhigen!\p"
	.string "Die Seele des KNOGGA sollte nun in\n"
	.string "die ewigen Jagdgründe eingekehrt\l"
	.string "sein.\p"
	.string "Trotzdem danke ich dir für deine\n"
	.string "Sorge um mich!\p"
	.string "Folge mir in das POKéMON-CLUBHAUS\n"
	.string "am Fuße dieses Turms.$"

