PokemonLeague_LancesRoom_Text_Intro::
    .ifdef ENGLISH
    .string "Ah! I've heard about you,\n"
    .string "{PLAYER}!\p"
    .string "I lead the ELITE FOUR.\p"
    .string "You can call me LANCE the dragon\n"
    .string "TRAINER.\p"
    .string "You know that dragons are\n"
    .string "mythical POKéMON.\p"
    .string "They're hard to catch and raise,\n"
    .string "but their powers are superior.\p"
    .string "They're virtually indestructible.\n"
    .string "There's no being clever with them.\p"
    .string "Well, are you ready to lose?\p"
    .string "Your LEAGUE challenge ends with\n"
    .string "me, {PLAYER}!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER}!\p"
    .string "¡Ah! ¡He oído hablar de ti,\n"
    .string "{PLAYER}!\p"
    .string "¡Dirijo al ALTO MANDO!\p"
    .string "¡Puedes llamarme LANCE,\n"
    .string "el ENTRENADOR de dragones!\p"
    .string "¡Los dragones son míticos POKéMON!\p"
    .string "¡Son difíciles de capturar y\n"
    .string "entrenar, pero sus poderes son\l"
    .string "muy superiores!\p"
    .string "¡Son casi invencibles!\p"
    .string "Bueno, sabes que vas a perder,\n"
    .string "¿no?\p"
    .string "¡Tu desafío en la LIGA termina\n"
    .string "conmigo, {PLAYER}!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif

PokemonLeague_LancesRoom_Text_RematchIntro::
    .ifdef ENGLISH
    .string "Ah!\n"
    .string "So, you've returned, {PLAYER}!\p"
    .string "I lead the ELITE FOUR.\p"
    .string "You can call me LANCE the dragon\n"
    .string "TRAINER.\p"
    .string "You know that dragons are\n"
    .string "mythical POKéMON.\p"
    .string "They're hard to catch and raise,\n"
    .string "but their powers are superior.\p"
    .string "They're virtually indestructible.\n"
    .string "There's no being clever with them.\p"
    .string "Well, are you ready to lose?\p"
    .string "Your LEAGUE challenge ends with\n"
    .string "me, {PLAYER}!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif
    .ifdef SPANISH
    .string "¡Ah!\n¡{PLAYER}, has vuelto!\p"
    .string "¡Dirijo al ALTO MANDO!\p"
    .string "¡Puedes llamarme LANCE,\n"
    .string "el ENTRENADOR de dragones!\p"
    .string "¡Los dragones son míticos POKéMON!\p"
    .string "¡Son difíciles de capturar y\n"
    .string "entrenar pero sus poderes son\l"
    .string "muy superiores!\p"
    .string "¡Son casi invencibles!\p"
    .string "Bueno, sabes que vas a perder,\n"
    .string "¿no?\p"
    .string "¡Tu desafío en la LIGA termina\n"
    .string "conmigo, {PLAYER}!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif

PokemonLeague_LancesRoom_Text_Defeat::
    .ifdef ENGLISH
    .string "That's it!\p"
    .string "I hate to admit it, but you are a\n"
    .string "POKéMON master!$"
    .endif
    .ifdef SPANISH
    .string "¡Pues sí!\p¡Odio admitirlo, pero eres una\npasada con los POKéMON!$"
    .endif

PokemonLeague_LancesRoom_Text_PostBattle::
    .ifdef ENGLISH
    .string "I still can't believe my dragons\n"
    .string "lost to you, {PLAYER}.\p"
    .string "You are now the POKéMON LEAGUE\n"
    .string "CHAMPION!\p"
    .string "…Or, you would have been, but\n"
    .string "you have one more challenge left.\p"
    .string "There is one more TRAINER to face!\n"
    .string "His name is…\p"
    .string "{RIVAL}!\p"
    .string "He beat the ELITE FOUR before\n"
    .string "you.\p"
    .string "He is the real POKéMON LEAGUE\n"
    .string "CHAMPION.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER}, sigo sin poder creerme\n"
    .string "que mis dragones hayan sucumbido\l"
    .string "a tus ataques!\p"
    .string "¡Has ganado la LIGA POKéMON!\p"
    .string "Bueno, casi, porque te espera\n"
    .string "otro desafío.\p"
    .string "¡Deberás luchar contra otro\n"
    .string "ENTRENADOR! Su nombre es...\p"
    .string "¡{RIVAL}!\p"
    .string "¡Él derrotó al ALTO MANDO antes\n"
    .string "que tú!\p"
    .string "¡Es el auténtico campeón de la\n"
    .string "LIGA POKéMON!$"
    .endif

