PewterCity_Museum_1F_Text_Its50YForChildsTicket::
    .ifdef ENGLISH
    .string "Yes, yes.\n"
    .string "It's ¥50 for a child's ticket.\p"
    .string "Would you like to come in?$"
    .endif
    .ifdef SPANISH
    .string "Los niños pagan 50¥.\p"
    .string "¿Te gustaría entrar?$"
    .endif

PewterCity_Museum_1F_Text_ComeAgain::
    .ifdef ENGLISH
    .string "Come again!$"
    .endif
    .ifdef SPANISH
    .string "¡Hasta pronto!$"
    .endif

PewterCity_Museum_1F_Text_Right50YThankYou::
    .ifdef ENGLISH
    .string "Right, ¥50!\n"
    .string "Thank you!$"
    .endif
    .ifdef SPANISH
    .string "¡50¥! ¡Vale!\n"
    .string "¡Gracias!$"
    .endif

PewterCity_Museum_1F_Text_DontHaveEnoughMoney::
    .ifdef ENGLISH
    .string "You don't have enough money.$"
    .endif
    .ifdef SPANISH
    .string "No tienes suficiente dinero.$"
    .endif

PewterCity_Museum_1F_Text_PleaseEnjoyYourself::
    .ifdef ENGLISH
    .string "Please enjoy yourself.$"
    .endif
    .ifdef SPANISH
    .string "Disfruta de la visita.$"
    .endif

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs::
    .ifdef ENGLISH
    .string "You can't sneak in the back way!\n"
    .string "Nice try, kid, but no.\p"
    .string "Oh, whatever!\n"
    .string "Do you know what AMBER is?$"
    .endif
    .ifdef SPANISH
    .string "¡No puedes entrar por detrás!\p"
    .string "¡Bueno, da igual!\n"
    .string "¿Sabes qué es el ÁMBAR?$"
    .endif

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter::
    .ifdef ENGLISH
    .string "AMBER contains the genetic matter\n"
    .string "of ancient POKéMON.\p"
    .string "There's a LAB somewhere trying to\n"
    .string "resurrect POKéMON from AMBER.$"
    .endif
    .ifdef SPANISH
    .string "¿Y sabías que el ÁMBAR contiene\n"
    .string "material genético de los POKéMON?\p"
    .string "Dicen que hay un LABORATORIO\n"
    .string "donde intentan revivir a viejos\l"
    .string "POKéMON a partir del ÁMBAR.$"
    .endif

PewterCity_Museum_1F_Text_AmberIsFossilizedSap::
    .ifdef ENGLISH
    .string "AMBER is actually sap, that gooey\n"
    .string "stuff that oozes from trees.\p"
    .string "The ancient sap fossilized over\n"
    .string "time to become rock-hard AMBER.$"
    .endif
    .ifdef SPANISH
    .string "El ÁMBAR es, en realidad, savia\n"
    .string "de árbol fosilizada.$"
    .endif

@ Unused
PewterCity_Museum_1F_Text_PleaseGoAround::
    .string "あちらへ　おまわりください$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife::
    .ifdef ENGLISH
    .string "I should be grateful for my long\n"
    .string "life.\p"
    .string "Never did I think I would get to\n"
    .string "see the bones of a dragon!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué golpe de suerte!\p"
    .string "¡Nunca pensé que conseguiría\n"
    .string "ver huesos de dragón!$"
    .endif

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined::
    .ifdef ENGLISH
    .string "Ssh! Listen, I need to share a\n"
    .string "secret with someone.\p"
    .string "I think that this chunk of AMBER\n"
    .string "contains POKéMON DNA!\p"
    .string "It would be a shattering scientific\n"
    .string "breakthrough if POKéMON could be\l"
    .string "resurrected from it.\p"
    .string "But, my colleagues just ignore\n"
    .string "what I have to say.\p"
    .string "So, I have a favor to ask!\p"
    .string "I want you to get this examined at\n"
    .string "a POKéMON LAB somewhere.$"
    .endif
    .ifdef SPANISH
    .string "¡Ssh! Voy a contarte un secreto.\p"
    .string "¡Creo que este trozo de ÁMBAR\n"
    .string "contiene ADN de POKéMON!\p"
    .string "¡Sería un descubrimiento científico\n"
    .string "increíble si se pudiera revivir a\l"
    .string "los POKéMON con esto!\p"
    .string "¡Pero mis colegas no me hacen\n"
    .string "ni caso! ¡Por eso te voy a pedir\l"
    .string "un favor!\p"
    .string "¡Lleva esto al LABORATORIO\n"
    .string "POKéMON para que lo analicen!$"
    .endif

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan::
    .ifdef ENGLISH
    .string "{PLAYER} received the OLD AMBER\n"
    .string "from the man.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió el ÁMBAR VIEJO\n"
    .string "de manos del hombre!$"
    .endif

PewterCity_Museum_1F_Text_GetOldAmberChecked::
    .ifdef ENGLISH
    .string "Ssh!\n"
    .string "Get the OLD AMBER checked!$"
    .endif
    .ifdef SPANISH
    .string "¡Ssh!\n"
    .string "¡Haz que analicen el ÁMBAR VIEJO!$"
    .endif

PewterCity_Museum_1F_Text_DontHaveSpaceForThis::
    .ifdef ENGLISH
    .string "You don't have space for this.$"
    .endif
    .ifdef SPANISH
    .string "¡No tienes sitio para esto!$"
    .endif

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit::
    .ifdef ENGLISH
    .string "We have two fossils of rare,\n"
    .string "prehistoric POKéMON on exhibit.$"
    .endif
    .ifdef SPANISH
    .string "¡Tenemos dos fósiles de unos\n"
    .string "POKéMON muy raros y prehistóricos!$"
    .endif

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber::
    .ifdef ENGLISH
    .string "There is a beautiful piece of\n"
    .string "AMBER in a clear gold color.$"
    .endif
    .ifdef SPANISH
    .string "¡El ÁMBAR es transparente y de\n"
    .string "color oro!$"
    .endif

PewterCity_Museum_1F_Text_AerodactylFossil::
    .ifdef ENGLISH
    .string "AERODACTYL Fossil\n"
    .string "A primitive and rare POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "Fósil AERODACTYL.\n"
    .string "Un primitivo y raro POKéMON.$"
    .endif

PewterCity_Museum_1F_Text_KabutopsFossil::
    .ifdef ENGLISH
    .string "KABUTOPS Fossil\n"
    .string "A primitive and rare POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "Fósil KABUTOPS.\n"
    .string "Un primitivo y raro POKéMON.$"
    .endif

