SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn::
	.string "Tanze, tanze!\n"
	.string "CHANEIRA tanze!\p"
	.string "Mach auch mit!\n"
	.string "Tanze, tanze!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance::
	.string "Möchtest du tanzen?$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance::
	.string "Komm schon, tanze!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance::
	.string "{PLAYER} tanzt den CHANEIRA-Tanz!$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow::
	.string "Ahahahaha!\p"
	.string "Jetzt geht es dir gut!\n"
	.string "Hast du ein Glück!$"

SevenIsland_SevaultCanyon_House_Text_Chansey::
	.string "CHANEIRA: Eira, Eira!$"

