SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn::
	.string "Danse, danse!\n"
	.string "Danse LEVEINARD!\p"
	.string "Tu te joins à nous?\n"
	.string "Allez, danse, danse!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance::
	.string "Tu veux danser?$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance::
	.string "Allez, sois pas timide!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance::
	.string "{PLAYER} exécute la\n"
	.string "danse de LEVEINARD!$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow::
	.string "Ahahahaha!\p"
	.string "Je suis content que ça te\n"
	.string "plaise!$"

SevenIsland_SevaultCanyon_House_Text_Chansey::
	.string "LEVEINARD: LEVEEEE!$"

