SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn::
    .string "¡A bailar el baile de CHANSEY,\n"
    .string "a bailar!\p"
    .string "¡Baila tú también!\n"
    .string "¡A bailar, a bailar!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance::
    .string "¿Quieres bailar?$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance::
    .string "¡Venga, baila!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance::
    .string "{PLAYER} bailó el baile de CHANSEY.$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow::
    .string "¡Ja, ja, ja!\p"
    .string "¡Ahora estáis más animados!\n"
    .string "¡Qué bien!$"

SevenIsland_SevaultCanyon_House_Text_Chansey::
    .string "CHANSEY: ¡Chansi, chansi!$"
