SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn::
    .ifdef ENGLISH
    .string "Dance, dance!\n"
    .string "CHANSEY Dance!\p"
    .string "You join in, too!\n"
    .string "Dance, dance!$"
    .endif
    .ifdef SPANISH
    .string "¡A bailar el baile de CHANSEY,\n"
    .string "a bailar!\p"
    .string "¡Baila tú también!\n"
    .string "¡A bailar, a bailar!$"
    .endif

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance::
    .ifdef ENGLISH
    .string "Would you like to dance?$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres bailar?$"
    .endif

SevenIsland_SevaultCanyon_House_Text_ComeOnDance::
    .ifdef ENGLISH
    .string "Come on, dance!$"
    .endif
    .ifdef SPANISH
    .string "¡Venga, baila!$"
    .endif

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance::
    .ifdef ENGLISH
    .string "{PLAYER} danced the CHANSEY Dance!$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} bailó el baile de CHANSEY.$"
    .endif

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow::
    .ifdef ENGLISH
    .string "Ahahahaha!\p"
    .string "There, you're all chipper now!\n"
    .string "Lucky!$"
    .endif
    .ifdef SPANISH
    .string "¡Ja, ja, ja!\p"
    .string "¡Ahora estáis más animados!\n"
    .string "¡Qué bien!$"
    .endif

SevenIsland_SevaultCanyon_House_Text_Chansey::
    .ifdef ENGLISH
    .string "CHANSEY: Chansi! Chansi!$"
    .endif
    .ifdef SPANISH
    .string "CHANSEY: ¡Chansi, chansi!$"
    .endif
