VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .ifdef ENGLISH
    .string "I'm getting my PIDGEY to fly a\n"
    .string "letter to SAFFRON in the north.$"
    .endif
    .ifdef SPANISH
    .string "¡Mi PIDGEY volará al norte,\n"
    .string "a CIUDAD AZAFRÁN, para llevar\l"
    .string "una carta!$"
    .endif

VermilionCity_House3_Text_Pidgey::
    .ifdef ENGLISH
    .string "PIDGEY: Kurukkoo!$"
    .endif
    .ifdef SPANISH
    .string "PIDGEY: ¡Pid, pid!$"
    .endif

VermilionCity_House3_Text_DearPippiLetter::
    .ifdef ENGLISH
    .string "Dear PIPPI,\n"
    .string "I hope to see you soon.\p"
    .string "I heard SAFFRON has problems with\n"
    .string "TEAM ROCKET.\p"
    .string "VERMILION appears to be safe.$"
    .endif
    .ifdef SPANISH
    .string "Querido PIPPI:\n"
    .string "Espero verte pronto.\p"
    .string "Dicen que en CIUDAD AZAFRÁN\n"
    .string "tienen problemas con el TEAM\l"
    .string "ROCKET.\p"
    .string "La CIUDAD CARMÍN parece segura.$"
    .endif

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
    .ifdef ENGLISH
    .string "I want to exchange MAIL with all\n"
    .string "sorts of people.\p"
    .string "I send my PIDGEY to a UNION ROOM\n"
    .string "to exchange MAIL for me.$"
    .endif
    .ifdef SPANISH
    .string "Me gustaría mandarme CARTAS\n"
    .string "con mucha gente.\p"
    .string "He mandado a mi PIDGEY a la\n"
    .string "SALA UNIÓN para que intercambie\l"
    .string "CARTAS por mí.$"
    .endif

