Route18_Text_WiltonIntro::
    .string "Compruebo siempre las zonas de\n"
    .string "hierba en busca de nuevos POKéMON.$"

Route18_Text_WiltonDefeat::
    .string "¡Tch!$"

Route18_Text_WiltonPostBattle::
    .string "¡Ojalá tuviera una BICICLETA!$"

Route18_Text_RamiroIntro::
    .string "¡Cucu, cucu!\n"
    .string "¿Te gusta el reclamo de mi pájaro?$"

Route18_Text_RamiroDefeat::
    .string "¡No he podido contigo!$"

Route18_Text_RamiroPostBattle::
    .string "¡También recojo POKéMON del mar\n"
    .string "los fines de semana!$"

Route18_Text_JacobIntro::
    .string "¡Es mi césped!\n"
    .string "¡Fuera de aquí!$"

Route18_Text_JacobDefeat::
    .string "¡Qué rabia!$"

Route18_Text_JacobPostBattle::
    .string "¡Es mi zona preferida para atrapar\n"
    .string "POKéMON!$"

Route18_Text_RouteSign::
    .string "RUTA 18:\n"
    .string "CIUDAD AZULONA - CIUDAD FUCSIA$"

Route18_Text_CyclingRoadSign::
    .string "CAMINO DE BICIS\n"
    .string "¡Prohibido el paso a los peatones!$"
