Route18_Text_WiltonIntro::
	.string "Ich laufe überall durch hohes\n"
	.string "Gras, um POKéMON aufzuspüren!$"

Route18_Text_WiltonDefeat::
	.string "Also so was!$"

Route18_Text_WiltonPostBattle::
	.string "Wenn ich nur ein FAHRRAD hätte!$"

Route18_Text_RamiroIntro::
	.string "Guruguu!\n"
	.string "Wie klingt mein Vogellockruf?$"

Route18_Text_RamiroDefeat::
	.string "Ich musste mit dir kämpfen!$"

Route18_Text_RamiroPostBattle::
	.string "Am Wochenende sammle ich immer\n"
	.string "WASSER-POKéMON!$"

Route18_Text_JacobIntro::
	.string "Das hier ist mein Gebiet!\n"
	.string "Sieh zu, dass du Land gewinnst!$"

Route18_Text_JacobDefeat::
	.string "Verdammt!$"

Route18_Text_JacobPostBattle::
	.string "Hier habe ich sehr gerne POKéMON\n"
	.string "gejagt!$"

Route18_Text_RouteSign::
	.string "ROUTE 18\n"
	.string "PRISMANIA CITY - FUCHSANIA CITY$"

Route18_Text_CyclingRoadSign::
	.string "Das Betreten des RADWEGES ist\n"
	.string "Fußgängern untersagt!$"

