Route18_Text_WiltonIntro::
    .ifdef ENGLISH
    .string "I always check every grassy area\n"
    .string "for new POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "Compruebo siempre las zonas de\n"
    .string "hierba en busca de nuevos POKéMON.$"
    .endif

Route18_Text_WiltonDefeat::
    .ifdef ENGLISH
    .string "Tch!$"
    .endif
    .ifdef SPANISH
    .string "¡Tch!$"
    .endif

Route18_Text_WiltonPostBattle::
    .ifdef ENGLISH
    .string "I wish I had a BIKE!$"
    .endif
    .ifdef SPANISH
    .string "¡Ojalá tuviera una BICICLETA!$"
    .endif

Route18_Text_RamiroIntro::
    .ifdef ENGLISH
    .string "Kurukkoo!\n"
    .string "How do you like my birdcall?$"
    .endif
    .ifdef SPANISH
    .string "¡Cucu, cucu!\n"
    .string "¿Te gusta el reclamo de mi pájaro?$"
    .endif

Route18_Text_RamiroDefeat::
    .ifdef ENGLISH
    .string "I had to bug you!$"
    .endif
    .ifdef SPANISH
    .string "¡No he podido contigo!$"
    .endif

Route18_Text_RamiroPostBattle::
    .ifdef ENGLISH
    .string "I collect sea POKéMON on weekends\n"
    .string "because the sea is so close.$"
    .endif
    .ifdef SPANISH
    .string "¡También recojo POKéMON del mar\n"
    .string "los fines de semana!$"
    .endif

Route18_Text_JacobIntro::
    .ifdef ENGLISH
    .string "This is my turf!\n"
    .string "Get out of here!$"
    .endif
    .ifdef SPANISH
    .string "¡Es mi césped!\n"
    .string "¡Fuera de aquí!$"
    .endif

Route18_Text_JacobDefeat::
    .ifdef ENGLISH
    .string "Darn!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué rabia!$"
    .endif

Route18_Text_JacobPostBattle::
    .ifdef ENGLISH
    .string "This is my fave area for catching\n"
    .string "POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Es mi zona preferida para atrapar\n"
    .string "POKéMON!$"
    .endif

Route18_Text_RouteSign::
    .ifdef ENGLISH
    .string "ROUTE 18\n"
    .string "CELADON CITY - FUCHSIA CITY$"
    .endif
    .ifdef SPANISH
    .string "RUTA 18:\n"
    .string "CIUDAD AZULONA - CIUDAD FUCSIA$"
    .endif

Route18_Text_CyclingRoadSign::
    .ifdef ENGLISH
    .string "CYCLING ROAD\n"
    .string "No pedestrians permitted!$"
    .endif
    .ifdef SPANISH
    .string "CAMINO DE BICIS\n"
    .string "¡Prohibido el paso a los peatones!$"
    .endif

