Text_SeismicTossTeach::
    .ifdef ENGLISH
    .string "The secrets of space…\n"
    .string "The mysteries of earth…\p"
    .string "There are so many things about\n"
    .string "which we know so little.\p"
    .string "But that should spur us to study\n"
    .string "harder, not toss in the towel.\p"
    .string "The only thing you should toss…\p"
    .string "Well, how about SEISMIC TOSS?\n"
    .string "Should I teach that to a POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "Los secretos del espacio...\n"
    .string "Los misterios de la tierra...\p"
    .string "Hay tantas cosas de las que\n"
    .string "sabemos tan poco...\p"
    .string "Pero eso debería movernos a\n"
    .string "investigar más y no tirar la toalla.\p"
    .string "Y hablando de movimiento...\p"
    .string "¿Conoces el MOV. SÍSMICO?\n"
    .string "¿Quieres que se lo enseñe a algún\l"
    .string "POKéMON?$"
    .endif

Text_SeismicTossDeclined::
    .ifdef ENGLISH
    .string "Is that so?\n"
    .string "I'm sure you'll be back for it.$"
    .endif
    .ifdef SPANISH
    .string "¿Ah, no?\n"
    .string "Seguro que vuelves a pedírmelo.$"
    .endif

Text_SeismicTossWhichMon::
    .ifdef ENGLISH
    .string "Which POKéMON wants to learn\n"
    .string "SEISMIC TOSS?$"
    .endif
    .ifdef SPANISH
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe MOV. SÍSMICO?$"
    .endif

Text_SeismicTossTaught::
    .ifdef ENGLISH
    .string "I hope you won't toss in the towel.\n"
    .string "Keep it up.$"
    .endif
    .ifdef SPANISH
    .string "Espero que no tires la toalla.\n"
    .string "Sigue así.$"
    .endif

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
    .ifdef ENGLISH
    .string "MOON STONE, huh?\p"
    .string "What's so special about it?\n"
    .string "Looks like an ordinary rock to me.$"
    .endif
    .ifdef SPANISH
    .string "¿La PIEDRA LUNAR?\p"
    .string "¿Por qué es tan especial?\n"
    .string "Yo no le veo nada del otro mundo.$"
    .endif

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
    .ifdef ENGLISH
    .string "July 20, 1969!\p"
    .string "Humankind first set foot on the\n"
    .string "moon that day.\p"
    .string "I bought a color TV just so I\n"
    .string "could watch that news.$"
    .endif
    .ifdef SPANISH
    .string "¡20 de julio de 1969!\p"
    .string "¡1.{SUPER_ER} alunizaje!\p"
    .string "¡Compré una tele en color para\n"
    .string "verlo!$"
    .endif

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
    .ifdef ENGLISH
    .string "This month, we're running a space\n"
    .string "exhibit.$"
    .endif
    .ifdef SPANISH
    .string "Ahora tenemos una exposición sobre\n"
    .string "el espacio.$"
    .endif

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
    .ifdef ENGLISH
    .string "I want a PIKACHU!\n"
    .string "It's so cute!\p"
    .string "I asked my daddy to catch me one!$"
    .endif
    .ifdef SPANISH
    .string "¡Quiero un PIKACHU!\n"
    .string "¡Es tan mono!\p"
    .string "¡Le pedí a mi padre que me\n"
    .string "atrapara uno!$"
    .endif

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
    .ifdef ENGLISH
    .string "Yeah, a PIKACHU soon, I promise!$"
    .endif
    .ifdef SPANISH
    .string "¡Sí, pronto tendrás a tu\n"
    .string "PIKACHU!... $"
    .endif

PewterCity_Museum_1F_Text_SpaceShuttle::
    .ifdef ENGLISH
    .string "Space Shuttle$"
    .endif
    .ifdef SPANISH
    .string "NAVE ESPACIAL$"
    .endif

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
    .ifdef ENGLISH
    .string "A meteorite that fell on MT. MOON.\n"
    .string "It is thought to be a MOON STONE.$"
    .endif
    .ifdef SPANISH
    .string "Meteorito caído en el MT. MOON.\n"
    .string "(¿PIEDRA LUNAR?)$"
    .endif

