SafariZone_Center_Text_RestHouse::
    .ifdef ENGLISH
    .string "REST HOUSE$"
    .endif
    .ifdef SPANISH
    .string "CASA DE REPOSO$"
    .endif

SafariZone_Center_Text_PressStartToCheckTime::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "Press START to check\n"
    .string "remaining time.$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "¡Pulsa START para saber cuánto\n"
    .string "tiempo te queda!$"
    .endif

SafariZone_Center_Text_CenterArea::
    .ifdef ENGLISH
    .string "CENTER AREA$"
    .endif
    .ifdef SPANISH
    .string "ZONA CENTRAL$"
    .endif

