SafariZone_SecretHouse_Text_CongratsYouveWon::
    .ifdef ENGLISH
    .string "Ah! Finally!\p"
    .string "You're the first person to reach\n"
    .string "the SECRET HOUSE!\p"
    .string "Although I made a campaign\n"
    .string "for our grand opening,\p"
    .string "I was getting worried that no one\n"
    .string "would win our campaign prize.\p"
    .string "Congratulations!\n"
    .string "You have won!$"
    .endif
    .ifdef SPANISH
    .string "¡Ah! ¡Por fin!\p"
    .string "¡Eres la primera persona que llega\n"
    .string "a la CASA SECRETA!\p"
    .string "He organizado un concurso con\n"
    .string "motivo de nuestra inauguración.\p"
    .string "Y estaba empezando a preocuparme\n"
    .string "que nadie ganara nuestro premio.\p"
    .string "¡Enhorabuena!\n"
    .string "¡Has ganado!$"
    .endif

SafariZone_SecretHouse_Text_ReceivedHM03FromAttendant::
    .ifdef ENGLISH
    .string "{PLAYER} received HM03\n"
    .string "from the attendant!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió una MO03\n"
    .string "del empleado!$"
    .endif

SafariZone_SecretHouse_Text_ExplainSurf::
    .ifdef ENGLISH
    .string "HM03 is SURF.\p"
    .string "POKéMON will be able to ferry you\n"
    .string "across water using it.\p"
    .string "And, this HM isn't disposable, so\n"
    .string "you can use it over and over.\p"
    .string "You're super lucky for winning this\n"
    .string "fabulous prize!$"
    .endif
    .ifdef SPANISH
    .string "¡La MO03 es SURF!\p"
    .string "¡Un POKéMON podrá llevarte\n"
    .string "por el agua!\p"
    .string "¡Y esta MO puede ser utilizada\n"
    .string "una y otra vez!\p"
    .string "¡Tienes muchísima suerte!\n"
    .string "¡Te llevas un fabuloso premio!$"
    .endif

SafariZone_SecretHouse_Text_DontHaveRoomForPrize::
    .ifdef ENGLISH
    .string "You don't have room for this\n"
    .string "fabulous prize!$"
    .endif
    .ifdef SPANISH
    .string "¡No tienes sitio para este premio\n"
    .string "tan fabuloso!$"
    .endif

