Route19_Text_RichardIntro::
    .ifdef ENGLISH
    .string "I have to exercise and warm up\n"
    .string "before going out for a swim.$"
    .endif
    .ifdef SPANISH
    .string "¡Tengo que calentar antes\n"
    .string "de nadar!$"
    .endif

Route19_Text_RichardDefeat::
    .ifdef ENGLISH
    .string "All warmed up!$"
    .endif
    .ifdef SPANISH
    .string "¡Ahora es cuando me encuentro\n"
    .string "en forma!$"
    .endif

Route19_Text_RichardPostBattle::
    .ifdef ENGLISH
    .string "Thanks, kid!\n"
    .string "I'm ready for a swim.$"
    .endif
    .ifdef SPANISH
    .string "¡Gracias!\n"
    .string "¡Ya puedo nadar!$"
    .endif

Route19_Text_ReeceIntro::
    .ifdef ENGLISH
    .string "Wait! Slow down!\n"
    .string "You'll have a heart attack!$"
    .endif
    .ifdef SPANISH
    .string "¡Alto!\n"
    .string "¡Te va a dar algo!$"
    .endif

Route19_Text_ReeceDefeat::
    .ifdef ENGLISH
    .string "Ooh!\n"
    .string "That's chilly!$"
    .endif
    .ifdef SPANISH
    .string "¡¡Auuu!!\n"
    .string "¡Cómo me has dejado!$"
    .endif

Route19_Text_ReecePostBattle::
    .ifdef ENGLISH
    .string "Watch out for TENTACOOL.\n"
    .string "They sting so painfully.$"
    .endif
    .ifdef SPANISH
    .string "¡Cuidado con TENTACOOL!\n"
    .string "¡Como te pique, no veas!$"
    .endif

Route19_Text_MatthewIntro::
    .ifdef ENGLISH
    .string "I love swimming!\n"
    .string "What about you?$"
    .endif
    .ifdef SPANISH
    .string "¡Me gusta nadar!\n"
    .string "¿Y a ti?$"
    .endif

Route19_Text_MatthewDefeat::
    .ifdef ENGLISH
    .string "Belly flop!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya planchazo!$"
    .endif

Route19_Text_MatthewPostBattle::
    .ifdef ENGLISH
    .string "I can beat even marine POKéMON\n"
    .string "at swimming.$"
    .endif
    .ifdef SPANISH
    .string "¡Puedo ganar a los POKéMON\n"
    .string "nadando!$"
    .endif

Route19_Text_DouglasIntro::
    .ifdef ENGLISH
    .string "What's beyond the horizon?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué habrá más allá del horizonte?$"
    .endif

Route19_Text_DouglasDefeat::
    .ifdef ENGLISH
    .string "Glub!$"
    .endif
    .ifdef SPANISH
    .string "¡Glup!$"
    .endif

Route19_Text_DouglasPostBattle::
    .ifdef ENGLISH
    .string "I see a couple of islands over\n"
    .string "yonder!$"
    .endif
    .ifdef SPANISH
    .string "¡Veo un par de islas!$"
    .endif

Route19_Text_DavidIntro::
    .ifdef ENGLISH
    .string "I tried diving for POKéMON, but it\n"
    .string "was a no-go.$"
    .endif
    .ifdef SPANISH
    .string "¡He buceado en busca de POKéMON,\n"
    .string "pero no he visto nada!$"
    .endif

Route19_Text_DavidDefeat::
    .ifdef ENGLISH
    .string "Help!$"
    .endif
    .ifdef SPANISH
    .string "¡Socorro!$"
    .endif

Route19_Text_DavidPostBattle::
    .ifdef ENGLISH
    .string "I guess you have to fish for sea\n"
    .string "POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Tienes que pescar a los POKéMON\n"
    .string "del mar!$"
    .endif

Route19_Text_TonyIntro::
    .ifdef ENGLISH
    .string "I look at the sea to forget all\n"
    .string "the bad things that happened.$"
    .endif
    .ifdef SPANISH
    .string "¡Miro al mar para olvidar!$"
    .endif

Route19_Text_TonyDefeat::
    .ifdef ENGLISH
    .string "Ooh!\n"
    .string "Traumatic!$"
    .endif
    .ifdef SPANISH
    .string "¡Oooooh!\n"
    .string "¡Qué humillación!$"
    .endif

Route19_Text_TonyPostBattle::
    .ifdef ENGLISH
    .string "I'm looking at the sea to forget\n"
    .string "the bad thing that happened!$"
    .endif
    .ifdef SPANISH
    .string "¡Miro al mar para olvidar!$"
    .endif

Route19_Text_AnyaIntro::
    .ifdef ENGLISH
    .string "Oh, I just love your ride!\n"
    .string "Can I have it if I win?$"
    .endif
    .ifdef SPANISH
    .string "¡Qué POKéMON tan guay!\n"
    .string "¿Me lo darás si gano?$"
    .endif

Route19_Text_AnyaDefeat::
    .ifdef ENGLISH
    .string "Oh! I lost!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh! ¡He perdido!$"
    .endif

Route19_Text_AnyaPostBattle::
    .ifdef ENGLISH
    .string "It's still a long way to go to\n"
    .string "SEAFOAM ISLANDS…\p"
    .string "I want to go back to FUCHSIA…$"
    .endif
    .ifdef SPANISH
    .string "Queda un largo camino hasta\n"
    .string "las ISLAS ESPUMA...\p"
    .string "Yo quiero volver a FUCSIA...$"
    .endif

Route19_Text_AliceIntro::
    .ifdef ENGLISH
    .string "Swimming's great!\n"
    .string "Sunburns aren't!$"
    .endif
    .ifdef SPANISH
    .string "¡Nadar es genial! ¡Pero no me\n"
    .string "gusta quemarme al sol!$"
    .endif

Route19_Text_AliceDefeat::
    .ifdef ENGLISH
    .string "Shocker!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué horror!$"
    .endif

Route19_Text_AlicePostBattle::
    .ifdef ENGLISH
    .string "My boyfriend wanted to swim to\n"
    .string "SEAFOAM ISLANDS.$"
    .endif
    .ifdef SPANISH
    .string "Mi novio quería nadar hasta\n"
    .string "las ISLAS ESPUMA.$"
    .endif

Route19_Text_AxleIntro::
    .ifdef ENGLISH
    .string "Ahoy, there!\n"
    .string "These waters are treacherous!$"
    .endif
    .ifdef SPANISH
    .string "¡Estas aguas son traicioneras!$"
    .endif

Route19_Text_AxleDefeat::
    .ifdef ENGLISH
    .string "Ooh!\n"
    .string "Dangerous!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué peligro!$"
    .endif

Route19_Text_AxlePostBattle::
    .ifdef ENGLISH
    .string "M-my legs! They cramped up!\n"
    .string "Glub, glub…$"
    .endif
    .ifdef SPANISH
    .string "¡Me ha dado un calambre! ¡Glup!$"
    .endif

Route19_Text_ConnieIntro::
    .ifdef ENGLISH
    .string "I swam here with my friends…\n"
    .string "I'm tired…$"
    .endif
    .ifdef SPANISH
    .string "He venido nadando hasta aquí,\n"
    .string "pero ya me he cansado.$"
    .endif

Route19_Text_ConnieDefeat::
    .ifdef ENGLISH
    .string "I'm exhausted…$"
    .endif
    .ifdef SPANISH
    .string "Estoy agotada...$"
    .endif

Route19_Text_ConniePostBattle::
    .ifdef ENGLISH
    .string "If I were to ride a POKéMON on\n"
    .string "the sea, I'd like a LAPRAS.\p"
    .string "LAPRAS is so big, I bet it\n"
    .string "would keep me dry on water.$"
    .endif
    .ifdef SPANISH
    .string "Si tuviera que montarme en un\n"
    .string "POKéMON para surcar el mar,\l"
    .string "elegiría a LAPRAS.\p"
    .string "LAPRAS es enorme, si te subes\n"
    .string "encima, seguro que no te mojas.$"
    .endif

Route19_Text_RouteSign::
    .ifdef ENGLISH
    .string "SEA ROUTE 19\n"
    .string "FUCHSIA CITY - SEAFOAM ISLANDS$"
    .endif
    .ifdef SPANISH
    .string "RUTA MARINA 19:\n"
    .string "CIUDAD FUCSIA - ISLAS ESPUMA$"
    .endif

Route19_Text_LiaIntro::
    .ifdef ENGLISH
    .string "LIA: I'm looking after my brother.\n"
    .string "He just became a TRAINER.$"
    .endif
    .ifdef SPANISH
    .string "CATI: Yo cuido de mi hermano.\n"
    .string "Acaba de hacerse ENTRENADOR.$"
    .endif

Route19_Text_LiaDefeat::
    .ifdef ENGLISH
    .string "LIA: That's no way to treat my\n"
    .string "little brother!$"
    .endif
    .ifdef SPANISH
    .string "CATI: ¡Ésa no es forma de tratar\n"
    .string "a mi hermanito!$"
    .endif

Route19_Text_LiaPostBattle::
    .ifdef ENGLISH
    .string "LIA: Do you have a younger\n"
    .string "brother?\p"
    .string "I hope you're teaching him all\n"
    .string "sorts of things.$"
    .endif
    .ifdef SPANISH
    .string "CATI: ¿Tienes un hermano pequeño?\p"
    .string "Espero que le enseñes cosas.$"
    .endif

Route19_Text_LiaNotEnoughMons::
    .ifdef ENGLISH
    .string "LIA: I want to battle together\n"
    .string "with my little brother.\p"
    .string "Don't you have two POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "CATI: A mi hermano y a mí nos\n"
    .string "gustaría luchar contigo.\p"
    .string "¿Tienes dos POKéMON?$"
    .endif

Route19_Text_LucIntro::
    .ifdef ENGLISH
    .string "LUC: My big sis taught me how\n"
    .string "to swim and train POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "TEC: Mi hermana mayor me ha\n"
    .string "enseñado a nadar y a entrenar\l"
    .string "POKéMON.$"
    .endif

Route19_Text_LucDefeat::
    .ifdef ENGLISH
    .string "LUC: Oh, wow!\n"
    .string "Someone tougher than my big sis!$"
    .endif
    .ifdef SPANISH
    .string "TEC: ¡Hala, alguien más fuerte\n"
    .string "que mi hermana!$"
    .endif

Route19_Text_LucPostBattle::
    .ifdef ENGLISH
    .string "LUC: My big sis is strong and nice.\n"
    .string "I think she's awesome!$"
    .endif
    .ifdef SPANISH
    .string "TEC: ¡Mi hermana mayor es muy\n"
    .string "fuerte y simpática! ¡Es guay!$"
    .endif

Route19_Text_LucNotEnoughMons::
    .ifdef ENGLISH
    .string "LUC: I don't want to if I can't\n"
    .string "battle you with my big sis.\p"
    .string "Don't you have two POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "TEC: Si no es con mi hermana,\n"
    .string "no lucharé contigo.\p"
    .string "Además, necesitas dos POKéMON.$"
    .endif
