VictoryRoad_1F_Text_NaomiIntro::
    .ifdef ENGLISH
    .string "I wonder if you are good enough\n"
    .string "for me?$"
    .endif
    .ifdef SPANISH
    .string "¡Me pregunto si eres lo bastante\n"
    .string "fuerte para mí!$"
    .endif

VictoryRoad_1F_Text_NaomiDefeat::
    .ifdef ENGLISH
    .string "I lost out…$"
    .endif
    .ifdef SPANISH
    .string "¡He perdido!$"
    .endif

VictoryRoad_1F_Text_NaomiPostBattle::
    .ifdef ENGLISH
    .string "I never wanted to lose to anybody,\n"
    .string "especially to a younger kid…$"
    .endif
    .ifdef SPANISH
    .string "¡A mí no me gusta perder, y mucho\n"
    .string "menos contra alguien tan joven!$"
    .endif

VictoryRoad_1F_Text_RolandoIntro::
    .ifdef ENGLISH
    .string "I can see you're good.\n"
    .string "Let me see exactly how good!$"
    .endif
    .ifdef SPANISH
    .string "¡Ya veo que eres fuerte!\n"
    .string "¡Veamos exactamente cuánto!$"
    .endif

VictoryRoad_1F_Text_RolandoDefeat::
    .ifdef ENGLISH
    .string "I had a chance…$"
    .endif
    .ifdef SPANISH
    .string "He perdido la oportunidad...$"
    .endif

VictoryRoad_1F_Text_RolandoPostBattle::
    .ifdef ENGLISH
    .string "Tch!\n"
    .string "I concede, you are better than I!$"
    .endif
    .ifdef SPANISH
    .string "¡Lo admito, eres mejor que yo!$"
    .endif

