VictoryRoad_1F_Text_NaomiIntro::
	.string "Glaubst du etwa, du kannst es mit\n"
	.string "mir aufnehmen?$"

VictoryRoad_1F_Text_NaomiDefeat::
	.string "Ich bin raus!$"

VictoryRoad_1F_Text_NaomiPostBattle::
	.string "Dabei wollte ich nie verlieren,\n"
	.string "schon gar nicht gegen\l"
	.string "ein kleines Kind…$"

VictoryRoad_1F_Text_RolandoIntro::
	.string "Ich glaube, du bist gut! Gut\n"
	.string "genug, um mich zu schlagen?$"

VictoryRoad_1F_Text_RolandoDefeat::
	.string "Immerhin hatte ich eine Chance!$"

VictoryRoad_1F_Text_RolandoPostBattle::
	.string "Ich muss gestehen, du bist besser!$"

