VictoryRoad_1F_Text_NaomiIntro::
    .string "¡Me pregunto si eres lo bastante\n"
    .string "fuerte para mí!$"

VictoryRoad_1F_Text_NaomiDefeat::
    .string "¡He perdido!$"

VictoryRoad_1F_Text_NaomiPostBattle::
    .string "¡A mí no me gusta perder, y mucho\n"
    .string "menos contra alguien tan joven!$"

VictoryRoad_1F_Text_RolandoIntro::
    .string "¡Ya veo que eres fuerte!\n"
    .string "¡Veamos exactamente cuánto!$"

VictoryRoad_1F_Text_RolandoDefeat::
    .string "He perdido la oportunidad...$"

VictoryRoad_1F_Text_RolandoPostBattle::
    .string "¡Lo admito, eres mejor que yo!$"
