SevenIsland_TanobyRuins_Text_BrandonIntro::
    .ifdef ENGLISH
    .string "Do you know anything about this\n"
    .string "stone chamber?$"
    .endif
    .ifdef SPANISH
    .string "¿Sabes algo de esta cámara\n"
    .string "de piedra?$"
    .endif

SevenIsland_TanobyRuins_Text_BrandonDefeat::
    .ifdef ENGLISH
    .string "That was uncalled for.\n"
    .string "You didn't have to be so rough.$"
    .endif
    .ifdef SPANISH
    .string "Oye, tampoco había que recurrir\n"
    .string "a la fuerza.$"
    .endif

SevenIsland_TanobyRuins_Text_BrandonPostBattle::
    .ifdef ENGLISH
    .string "The TANOBY RUINS date back at\n"
    .string "least 1,500 years.\p"
    .string "But it's a baffling mystery as to\n"
    .string "why it was built in the first place.$"
    .endif
    .ifdef SPANISH
    .string "Las RUINAS SETE tienen unos\n"
    .string "1.500 años.\p"
    .string "Pero nadie ha conseguido averiguar\n"
    .string "cuál es su razón de ser.$"
    .endif

SevenIsland_TanobyRuins_Text_BenjaminIntro::
    .ifdef ENGLISH
    .string "A mystic POKéMON is said to sleep\n"
    .string "inside here.$"
    .endif
    .ifdef SPANISH
    .string "Dicen que aquí dentro duerme\n"
    .string "un mítico POKéMON.$"
    .endif

SevenIsland_TanobyRuins_Text_BenjaminDefeat::
    .ifdef ENGLISH
    .string "I'm not much good in battle.$"
    .endif
    .ifdef SPANISH
    .string "A mí lo de los combates no se me\n"
    .string "da bien.$"
    .endif

SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
    .ifdef ENGLISH
    .string "I hear there are other ruins like\n"
    .string "the one here.\p"
    .string "Might they be the resting places\n"
    .string "of other mystic POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "Yo he oído que hay otras ruinas\n"
    .string "como éstas.\p"
    .string "¿Serán lugares de descanso de\n"
    .string "otros míticos POKéMON?$"
    .endif

SevenIsland_TanobyRuins_Text_EdnaIntro::
    .ifdef ENGLISH
    .string "CLIFFORD is teaching me how to\n"
    .string "paint.$"
    .endif
    .ifdef SPANISH
    .string "CLEN está enseñándome a pintar.$"
    .endif

SevenIsland_TanobyRuins_Text_EdnaDefeat::
    .ifdef ENGLISH
    .string "We might get in trouble for being\n"
    .string "noisy here.$"
    .endif
    .ifdef SPANISH
    .string "Igual nos llaman la atención\n"
    .string "por haber hecho tanto ruido.$"
    .endif

SevenIsland_TanobyRuins_Text_EdnaPostBattle::
    .ifdef ENGLISH
    .string "I said that I wanted to paint an\n"
    .string "old building.\p"
    .string "So CLIFFORD brought me here.$"
    .endif
    .ifdef SPANISH
    .string "Yo quería pintar un edificio\n"
    .string "antiguo.\p"
    .string "Por eso me trajo CLEN hasta aquí.$"
    .endif

SevenIsland_TanobyRuins_Text_CliffordIntro::
    .ifdef ENGLISH
    .string "Today, in addition to our lesson,\n"
    .string "we came to see the chamber.$"
    .endif
    .ifdef SPANISH
    .string "Hoy, como complemento a la clase,\n"
    .string "hemos venido a visitar la cámara.$"
    .endif

SevenIsland_TanobyRuins_Text_CliffordDefeat::
    .ifdef ENGLISH
    .string "My, how extraordinary.$"
    .endif
    .ifdef SPANISH
    .string "Qué barbaridad...$"
    .endif

SevenIsland_TanobyRuins_Text_CliffordPostBattle::
    .ifdef ENGLISH
    .string "Ah, so you are studying POKéMON\n"
    .string "on your own…\p"
    .string "Yes, you certainly are quite the\n"
    .string "extraordinary person, indeed.$"
    .endif
    .ifdef SPANISH
    .string "Así que tú estudias a los POKéMON\n"
    .string "por tu cuenta...\p"
    .string "La verdad es que es digno\n"
    .string "de admiración...$"
    .endif
