CeruleanCity_House1_Text_AnyInterestInBerries::
	.string "En utilisant de la bonne POUDRE\n"
	.string "BAIE, je peux préparer\p"
	.string "toutes sortes de médicaments.\p"
	.string "Dis-moi, tu t'y connais un peu\n"
	.string "en BAIES?$"

CeruleanCity_House1_Text_HaveJustTheThing::
	.string "Parfait! Alors j'ai juste ce qu'il\n"
	.string "te faut.$"

CeruleanCity_House1_Text_GoCrushBerriesAtDirectCorner::
	.string "Il y a du nouveau au premier\n"
	.string "étage des CENTRES POKéMON.\p"
	.string "Ils ont ajouté une machine pour\n"
	.string "broyer les BAIES dans\p"
	.string "la SALLE LINK DIRECT.\n"
	.string "C'est là que tu interviens.\p"
	.string "Pourrais-tu aller faire de la\n"
	.string "POUDRE pour moi en\p"
	.string "utilisant cette machine?\p"
	.string "N'oublie pas, la machine se trouve\n"
	.string "dans la SALLE LINK DIRECT.\p"
	.string "Je ferai une préparation juste\n"
	.string "pour toi si tu arrives à broyer\p"
	.string "des BAIES et à me ramener\n"
	.string "la POUDRE.$"

CeruleanCity_House1_Text_WhyMustYouLieNoBerries::
	.string "Pourquoi tu me mens?\n"
	.string "Tu n'as pas une seule BAIE!$"

CeruleanCity_House1_Text_TakeInterestInAllSortsOfThings::
	.string "Les BAIES t'intéressent pas?\p"
	.string "A ton âge, il faut s'intéresser à\n"
	.string "plein de choses.$"

CeruleanCity_House1_Text_HaveYouBroughtBerryPowder::
	.string "M'as-tu amené de la POUDRE BAIE?$"

CeruleanCity_House5_Text_ExchangeWithWhat::
	.string "Contre quoi veux-tu\n"
	.string "l'échanger?$"

CeruleanCity_House1_Text_YoullExchangeBerryPowderForItem::
	.string "Je vais te donner 1 {STR_VAR_1}\n"
	.string "contre la POUDRE BAIE.$"

CeruleanCity_House1_Text_DontHaveEnoughBerryPowder::
	.string "Hmm. Tu n'as pas assez de\n"
	.string "POUDRE BAIE.$"

CeruleanCity_House1_Text_TradeMoreBerryPowder::
	.string "Cette POUDRE BAIE a l'air bonne.\n"
	.string "Ça fera de bons médicaments.\p"
	.string "Tu veux échanger ce qui te reste\n"
	.string "contre autre chose?$"

CeruleanCity_House1_Text_HopeToSeeYouAgain::
	.string "Tant pis. J'espère te revoir\n"
	.string "bientôt.$"

CeruleanCity_House1_Text_SeeMeIfYoudLikeToTradePowder::
	.string "Reviens me voir si tu veux encore\n"
	.string "échanger de la POUDRE BAIE.$"

