CeruleanCity_House1_Text_AnyInterestInBerries::
    .ifdef ENGLISH
    .string "I concoct a variety of medicine\n"
    .string "from BERRY POWDER.\p"
    .string "Using good BERRY POWDER, I can\n"
    .string "make any kind of medicine.\p"
    .string "Now tell me, have you any interest\n"
    .string "in BERRIES?$"
    .endif
    .ifdef SPANISH
    .string "Yo hago una especie de medicina\n"
    .string "a partir del POLVO de BAYA.\p"
    .string "Y si el POLVO de BAYA es bueno,\n"
    .string "hago unos mejunjes espectaculares.\p"
    .string "Bueno, a todo esto, ¿te gustan\n"
    .string "las BAYAS?$"
    .endif

CeruleanCity_House1_Text_HaveJustTheThing::
    .ifdef ENGLISH
    .string "Ah, good! For you, then, I have\n"
    .string "just the thing.$"
    .endif
    .ifdef SPANISH
    .string "Ah, estupendo, pues voy a darte\n"
    .string "una cosita.$"
    .endif

CeruleanCity_House1_Text_GoCrushBerriesAtDirectCorner::
    .ifdef ENGLISH
    .string "There's something new on the second\n"
    .string "floor of POKéMON CENTERS, at the\l"
    .string "DIRECT CORNER.\p"
    .string "They installed a Wireless Adapter\n"
    .string "machine for crushing BERRIES.\p"
    .string "This is where you come in.\p"
    .string "I have a favor to ask, one that\n"
    .string "I can entrust only to you.\p"
    .string "Could you make BERRY POWDER for\n"
    .string "me using that machine?\p"
    .string "Don't forget, the machine is at the\n"
    .string "DIRECT CORNER of POKéMON CENTERS.\p"
    .string "I'll concoct medicine for you if\n"
    .string "you bring me some BERRY POWDER.\p"
    .string "Don't forget, crush BERRIES into\n"
    .string "BERRY POWDER and bring it to me.$"
    .endif
    .ifdef SPANISH
    .string "Hay algo nuevo en el primer piso\n"
    .string "de los CENTROS POKéMON, en la\l"
    .string "ZONA DIRECTA.\p"
    .string "Se ha instalado una máquina para\n"
    .string "Conectores inalámbricos de GBA,\l"
    .string "que permite MACHACAR BAYAS.\p"
    .string "¿Que para qué te cuento esto?\p"
    .string "Pues porque tengo que pedirte\n"
    .string "un favor. Sólo tú puedes ayudarme.\p"
    .string "¿Podrías hacer POLVO de BAYA\n"
    .string "usando esa máquina?\p"
    .string "Recuerda, la máquina está en la\n"
    .string "ZONA DIRECTA de los CENTROS\l"
    .string "POKéMON.\p"
    .string "Si me traes el POLVO de BAYA,\n"
    .string "elaboraré una medicina para ti.\p"
    .string "¡Hala, MACHACA algunas BAYAS\n"
    .string "y tráeme el POLVO de BAYAS!$"
    .endif

CeruleanCity_House1_Text_WhyMustYouLieNoBerries::
    .ifdef ENGLISH
    .string "Why must you lie to me?\p"
    .string "How many BERRIES do you have?\n"
    .string "Not a one!$"
    .endif
    .ifdef SPANISH
    .string "¿Por qué me mientes?\p"
    .string "¿Cuántas BAYAS tienes?\n"
    .string "¡Ni una!$"
    .endif

CeruleanCity_House1_Text_TakeInterestInAllSortsOfThings::
    .ifdef ENGLISH
    .string "You have no interest in BERRIES?\p"
    .string "Young one, it's important to take an\n"
    .string "interest in all sorts of things.$"
    .endif
    .ifdef SPANISH
    .string "¡A ti las BAYAS te importan\n"
    .string "un pimiento!\p"
    .string "Pues debes saber que hay que\n"
    .string "tener interés por todas las cosas.$"
    .endif

CeruleanCity_House1_Text_HaveYouBroughtBerryPowder::
    .ifdef ENGLISH
    .string "Er-hem! Have you brought me some\n"
    .string "BERRY POWDER?$"
    .endif
    .ifdef SPANISH
    .string "¡Eh! ¿Me has traído POLVO\n"
    .string "de BAYA?$"
    .endif

CeruleanCity_House5_Text_ExchangeWithWhat::
    .ifdef ENGLISH
    .string "With what would you like to \n"
    .string "exchange it?$"
    .endif
    .ifdef SPANISH
    .string "¿Por qué quieres que te lo cambie?$"
    .endif

CeruleanCity_House1_Text_YoullExchangeBerryPowderForItem::
    .ifdef ENGLISH
    .string "Fine, you'll exchange your BERRY\n"
    .string "POWDER for one {STR_VAR_1}?$"
    .endif
    .ifdef SPANISH
    .string "Vale, te cambio el POLVO de BAYA\n"
    .string "por una unidad de {STR_VAR_1}.$"
    .endif

CeruleanCity_House1_Text_DontHaveEnoughBerryPowder::
    .ifdef ENGLISH
    .string "Hm? You don't have enough\n"
    .string "BERRY POWDER.$"
    .endif
    .ifdef SPANISH
    .string "¿Mm? No tienes suficiente POLVO\n"
    .string "de BAYA.$"
    .endif

CeruleanCity_House1_Text_TradeMoreBerryPowder::
    .ifdef ENGLISH
    .string "This is fine BERRY POWDER indeed.\n"
    .string "It will make excellent medicine.\p"
    .string "Would you like to trade more BERRY\n"
    .string "POWDER for something else?$"
    .endif
    .ifdef SPANISH
    .string "Este POLVO de BAYA es excelente.\n"
    .string "Va a salir una medicina buenísima.\p"
    .string "¿Quieres cambiar más POLVO\n"
    .string "de BAYA por otra cosa más?$"
    .endif

CeruleanCity_House1_Text_HopeToSeeYouAgain::
    .ifdef ENGLISH
    .string "That's fine, then.\n"
    .string "I'll hope to see you back again.$"
    .endif
    .ifdef SPANISH
    .string "Muy bien, muy bien.\n"
    .string "Hasta la próxima.$"
    .endif

CeruleanCity_House1_Text_SeeMeIfYoudLikeToTradePowder::
    .ifdef ENGLISH
    .string "Come see me if you'd like to trade\n"
    .string "your BERRY POWDER.$"
    .endif
    .ifdef SPANISH
    .string "Ven a verme cuando quieras cambiar\n"
    .string "POLVO de BAYA por otra cosa.$"
    .endif

