Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
    .ifdef ENGLISH
    .string "Many POKéMON live only in forests \n"
    .string "and caves.\p"
    .string "You need to be persistent and look\n"
    .string "everywhere to get different kinds.$"
    .endif
    .ifdef SPANISH
    .string "Muchos POKéMON sólo viven\n"
    .string "en bosques y cuevas.\p"
    .string "¡Tienes que mirar por todas partes\n"
    .string "para conseguirlos todos!$"
    .endif

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
    .ifdef ENGLISH
    .string "Have you noticed the skinny trees\n"
    .string "on the roadside?\p"
    .string "They can be cut down by a special\n"
    .string "POKéMON move, I hear.$"
    .endif
    .ifdef SPANISH
    .string "¿Has visto los arbustos que hay\n"
    .string "junto al camino?\p"
    .string "Puedes cortarlos con un movimiento\n"
    .string "especial de los POKéMON.$"
    .endif

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
    .ifdef ENGLISH
    .string "Do you know the evolution-cancel\n"
    .string "technique?\p"
    .string "When a POKéMON is evolving, you\n"
    .string "can stop the process.\p"
    .string "It's a technique for raising\n"
    .string "POKéMON the way they are.$"
    .endif
    .ifdef SPANISH
    .string "¿Sabes que se puede cancelar\n"
    .string "la evolución de un POKéMON?\p"
    .string "Cuando un POKéMON esté\n"
    .string "evolucionando puedes pararlo\l"
    .string "y dejarlo como está.$"
    .endif

