Route20_Text_BarryIntro::
    .ifdef ENGLISH
    .string "The water is shallow here.\n"
    .string "There are many people swimming.$"
    .endif
    .ifdef SPANISH
    .string "El agua es poco profunda aquí.\n"
    .string "Hay mucha gente nadando.$"
    .endif

Route20_Text_BarryDefeat::
    .ifdef ENGLISH
    .string "Splash!$"
    .endif
    .ifdef SPANISH
    .string "¡Splash!$"
    .endif

Route20_Text_BarryPostBattle::
    .ifdef ENGLISH
    .string "I wish I could ride my POKéMON.\n"
    .string "I bet you're not tired.$"
    .endif
    .ifdef SPANISH
    .string "¡Ojalá pudiera subirme a mi\n"
    .string "POKéMON!$"
    .endif

Route20_Text_ShirleyIntro::
    .ifdef ENGLISH
    .string "SEAFOAM is a quiet getaway.\n"
    .string "I'm vacationing here.$"
    .endif
    .ifdef SPANISH
    .string "¡Las ISLAS ESPUMA son una fácil\n"
    .string "salida!$"
    .endif

Route20_Text_ShirleyDefeat::
    .ifdef ENGLISH
    .string "Quit it!$"
    .endif
    .ifdef SPANISH
    .string "¡Déjalo ya!$"
    .endif

Route20_Text_ShirleyPostBattle::
    .ifdef ENGLISH
    .string "There's a huge cavern underneath\n"
    .string "this island.$"
    .endif
    .ifdef SPANISH
    .string "Hay una enorme caverna debajo\n"
    .string "de esta isla.$"
    .endif

Route20_Text_TiffanyIntro::
    .ifdef ENGLISH
    .string "I love floating with the fishes\n"
    .string "here among the waves.$"
    .endif
    .ifdef SPANISH
    .string "¡Me gusta flotar en el agua\n"
    .string "rodeada de peces!$"
    .endif

Route20_Text_TiffanyDefeat::
    .ifdef ENGLISH
    .string "Yowch!$"
    .endif
    .ifdef SPANISH
    .string "¡Auchh!$"
    .endif

Route20_Text_TiffanyPostBattle::
    .ifdef ENGLISH
    .string "Want to float with me?$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres flotar conmigo?$"
    .endif

Route20_Text_IreneIntro::
    .ifdef ENGLISH
    .string "Are you on vacation, too?$"
    .endif
    .ifdef SPANISH
    .string "¿También estás de vacaciones?$"
    .endif

Route20_Text_IreneDefeat::
    .ifdef ENGLISH
    .string "No mercy at all!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué insensible eres!$"
    .endif

Route20_Text_IrenePostBattle::
    .ifdef ENGLISH
    .string "SEAFOAM used to be a single island\n"
    .string "in the distant past.$"
    .endif
    .ifdef SPANISH
    .string "¡Las ISLAS ESPUMA eran antes\n"
    .string "una sola isla!$"
    .endif

Route20_Text_DeanIntro::
    .ifdef ENGLISH
    .string "Check out my buff physique!$"
    .endif
    .ifdef SPANISH
    .string "¡Mira que cuerpazo tengo!$"
    .endif

Route20_Text_DeanDefeat::
    .ifdef ENGLISH
    .string "Wimpy!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué ridículo!$"
    .endif

Route20_Text_DeanPostBattle::
    .ifdef ENGLISH
    .string "I should've been buffing up my\n"
    .string "POKéMON, not me!$"
    .endif
    .ifdef SPANISH
    .string "¡No debería haber presumido tanto!$"
    .endif

Route20_Text_DarrinIntro::
    .ifdef ENGLISH
    .string "Why are you riding a POKéMON?\n"
    .string "Can't you swim?$"
    .endif
    .ifdef SPANISH
    .string "¿Por qué te has subido a un\n"
    .string "POKéMON? ¿No sabes nadar?$"
    .endif

Route20_Text_DarrinDefeat::
    .ifdef ENGLISH
    .string "Ouch!\n"
    .string "Torpedoed!$"
    .endif
    .ifdef SPANISH
    .string "¡Auch!\n"
    .string "¡Qué fracaso!$"
    .endif

Route20_Text_DarrinPostBattle::
    .ifdef ENGLISH
    .string "Riding a POKéMON sure looks fun!$"
    .endif
    .ifdef SPANISH
    .string "¡Subirse a un POKéMON es muy\n"
    .string "divertido!$"
    .endif

Route20_Text_RogerIntro::
    .ifdef ENGLISH
    .string "I rode my bird POKéMON here.$"
    .endif
    .ifdef SPANISH
    .string "¡He venido sobre uno de mis\n"
    .string "pájaros POKéMON!$"
    .endif

Route20_Text_RogerDefeat::
    .ifdef ENGLISH
    .string "Oh, no!\n"
    .string "Now what am I to do?$"
    .endif
    .ifdef SPANISH
    .string "¡Oh, no!$"
    .endif

Route20_Text_RogerPostBattle::
    .ifdef ENGLISH
    .string "My birds are exhausted.\n"
    .string "They can't FLY me back!$"
    .endif
    .ifdef SPANISH
    .string "¡Mis pájaros están hechos polvo\n"
    .string "para VOLAR de nuevo!$"
    .endif

Route20_Text_NoraIntro::
    .ifdef ENGLISH
    .string "My boyfriend gave me big pearls.$"
    .endif
    .ifdef SPANISH
    .string "¡Mi novio me dio unas perlas\n"
    .string "muy grandes!$"
    .endif

Route20_Text_NoraDefeat::
    .ifdef ENGLISH
    .string "Oh, no!\n"
    .string "My pearls were in them!$"
    .endif
    .ifdef SPANISH
    .string "¡Ni te acerques a mis perlas!$"
    .endif

Route20_Text_NoraPostBattle::
    .ifdef ENGLISH
    .string "Will my pearls grow bigger inside\n"
    .string "CLOYSTER?$"
    .endif
    .ifdef SPANISH
    .string "¿Crecerán más mis perlas dentro\n"
    .string "de un CLOYSTER?$"
    .endif

Route20_Text_MissyIntro::
    .ifdef ENGLISH
    .string "I swam here from CINNABAR ISLAND.\n"
    .string "It wasn't easy, I tell you.$"
    .endif
    .ifdef SPANISH
    .string "¡Vengo nadando desde ISLA\n"
    .string "CANELA! ¡Qué paliza!$"
    .endif

Route20_Text_MissyDefeat::
    .ifdef ENGLISH
    .string "I'm so disappointed!$"
    .endif
    .ifdef SPANISH
    .string "¡Estoy tan decepcionada!$"
    .endif

Route20_Text_MissyPostBattle::
    .ifdef ENGLISH
    .string "POKéMON have taken over an\n"
    .string "abandoned mansion on CINNABAR.\p"
    .string "They call it the POKéMON MANSION\n"
    .string "now.$"
    .endif
    .ifdef SPANISH
    .string "¡Los POKéMON invadieron una casa\n"
    .string "abandonada en ISLA CANELA!\p"
    .string "Es la que llaman MANSIÓN\n"
    .string "POKéMON.$"
    .endif

Route20_Text_MelissaIntro::
    .ifdef ENGLISH
    .string "CINNABAR, in the west, has a LAB\n"
    .string "for POKéMON.\p"
    .string "My daddy works there.$"
    .endif
    .ifdef SPANISH
    .string "En ISLA CANELA, al oeste, hay\n"
    .string "un LABORATORIO POKéMON.\p"
    .string "Mi papi trabaja allí.$"
    .endif

Route20_Text_MelissaDefeat::
    .ifdef ENGLISH
    .string "Wait!\n"
    .string "You're supposed to wait!$"
    .endif
    .ifdef SPANISH
    .string "¡Espera!\n"
    .string "¡Vas demasiado deprisa!$"
    .endif

Route20_Text_MelissaPostBattle::
    .ifdef ENGLISH
    .string "CINNABAR is a volcanic island.\p"
    .string "I heard it rose out of the sea\n"
    .string "when a volcano erupted.$"
    .endif
    .ifdef SPANISH
    .string "¡ISLA CANELA es volcánica!\p"
    .string "Dicen que surgió tras la erupción\n"
    .string "de un volcán.$"
    .endif

Route20_Text_SeafoamIslands::
    .ifdef ENGLISH
    .string "SEAFOAM ISLANDS$"
    .endif
    .ifdef SPANISH
    .string "ISLAS ESPUMA$"
    .endif

Route20_Text_MistyTrainsHere::
    .ifdef ENGLISH
    .string "Strong TRAINERS and WATER POKéMON\n"
    .string "are common sights in these parts.\p"
    .string "They say that MISTY of the\n"
    .string "CERULEAN GYM trains here.$"
    .endif
    .ifdef SPANISH
    .string "Por aquí hay muchos ENTRENADORES\n"
    .string "fuertes y POKéMON del tipo AGUA.\p"
    .string "Dicen que MISTY, del GIMNASIO\n"
    .string "de CELESTE, se entrena por aquí.$"
    .endif
