Route20_Text_BarryIntro::
	.string "Das Wasser ist hier sehr flach.$"

Route20_Text_BarryDefeat::
	.string "Platsch!$"

Route20_Text_BarryPostBattle::
	.string "Ich wünschte, ich könnte auf einem\n"
	.string "POKéMON reiten.$"

Route20_Text_ShirleyIntro::
	.string "Die SEESCHAUMINSELN sind ein\n"
	.string "stiller Zufluchtsort!$"

Route20_Text_ShirleyDefeat::
	.string "Schluss damit!$"

Route20_Text_ShirleyPostBattle::
	.string "Unter dieser Insel befindet sich\n"
	.string "eine riesige Höhle!$"

Route20_Text_TiffanyIntro::
	.string "Ich lasse mich gerne mit den\n"
	.string "Fischen treiben!$"

Route20_Text_TiffanyDefeat::
	.string "Autsch!$"

Route20_Text_TiffanyPostBattle::
	.string "Möchtest du mir Gesellschaft\n"
	.string "leisten?$"

Route20_Text_IreneIntro::
	.string "Machst du auch gerade Urlaub?$"

Route20_Text_IreneDefeat::
	.string "Du kennst keine Gnade!$"

Route20_Text_IrenePostBattle::
	.string "Die SEESCHAUMINSELN waren einmal\n"
	.string "EINE große Insel!$"

Route20_Text_DeanIntro::
	.string "Schau dir meinen gestählten Körper\n"
	.string "ruhig an!$"

Route20_Text_DeanDefeat::
	.string "Waschlappen!$"

Route20_Text_DeanPostBattle::
	.string "Ich hätte meine POKéMON stählen\n"
	.string "sollen, nicht meinen Körper!$"

Route20_Text_DarrinIntro::
	.string "Warum reitest du auf dem POKéMON?\n"
	.string "Kannst du nicht schwimmen?$"

Route20_Text_DarrinDefeat::
	.string "Ich wurde torpediert!$"

Route20_Text_DarrinPostBattle::
	.string "Es dürfte Spaß machen, auf einem\n"
	.string "POKéMON zu reiten!$"

Route20_Text_RogerIntro::
	.string "Mein Vogel-POKéMON hat mich\n"
	.string "hierher getragen!$"

Route20_Text_RogerDefeat::
	.string "Oh nein!$"

Route20_Text_RogerPostBattle::
	.string "Kann ich mit meinen Vogel-POKéMON\n"
	.string "noch zurückfliegen?$"

Route20_Text_NoraIntro::
	.string "Mein Freund hat mir eine große\n"
	.string "Perle geschenkt!$"

Route20_Text_NoraDefeat::
	.string "Lass die Finger von meiner Perle!$"

Route20_Text_NoraPostBattle::
	.string "Ob meine Perle in einem AUSTOS\n"
	.string "größer werden würde?$"

Route20_Text_MissyIntro::
	.string "Ich bin von der ZINNOBERINSEL\n"
	.string "herübergeschwommen!$"

Route20_Text_MissyDefeat::
	.string "Ich bin enttäuscht!$"

Route20_Text_MissyPostBattle::
	.string "Auf der ZINNOBERINSEL haben\n"
	.string "POKéMON eine verlassene Villa\l"
	.string "besiedelt!$"

Route20_Text_MelissaIntro::
	.string "Auf der ZINNOBERINSEL befindet\n"
	.string "sich ein POKéMON-LABOR.$"

Route20_Text_MelissaDefeat::
	.string "Warte!$"

Route20_Text_MelissaPostBattle::
	.string "Die ZINNOBERINSEL ist ein\n"
	.string "vulkanisches Eiland!$"

Route20_Text_SeafoamIslands::
	.string "SEESCHAUMINSELN$"

Route20_Text_MistyTrainsHere::
	.string "Starke TRAINER und WASSER-\n"
	.string "POKéMON sind hier weit verbreitet.\p"
	.string "Man sagt, dass MISTY aus der\n"
	.string "ARENA von AZURIA CITY\l"
	.string "hier häufig trainiert.$"

