SSAnne_Kitchen_Text_BusyOutOfTheWay::
	.string "Aus dem Weg, du Leichtmatrose!\n"
	.string "Wir sind schwer beschäftigt!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash::
	.string "Im Abfalleimer habe ich eine\n"
	.string "merkwürdige BEERE gesehen!\l"
	.string "Ich frage mich, was das genau\l"
	.string "war!$"

SSAnne_Kitchen_Text_SoBusyImDizzy::
	.string "Es gibt zu viel zu tun, nie kann\n"
	.string "ich mich ausruhen!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay::
	.string "Was hab ich nur verbrochen?\p"
	.string "Ich muss immer nur Kartoffeln\n"
	.string "schälen...$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton::
	.string "Hast du schon von RELAXO gehört?\p"
	.string "Es schläft und frisst den ganzen\n"
	.string "Tag!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions::
	.string "Schnief... ... Schnief...\p"
	.string "Immer muss ich die Zwiebeln\n"
	.string "schälen...$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs::
	.string "Ich bin der Chef de Cuisine!\p"
	.string "Der Hauptgang ist…$"

SSAnne_Kitchen_Text_SalmonDuSalad::
	.string "Lachs-Filet!\p"
	.string "Eine kulinarische Köstlichkeit\n"
	.string "sondergleichen!$"

SSAnne_Kitchen_Text_EelsAuBarbecue::
	.string "Currywurst!\p"
	.string "Wie kommt eine solche Banalität auf\n"
	.string "meine Karte?$"

SSAnne_Kitchen_Text_PrimeBeefsteak::
	.string "Muschel-Ragout!\p"
	.string "Die Gäste werden es lieben!$"

