SilphCo_2F_Text_ConnorIntro::
	.string "Hilfe! Ich bin ein Mitarbeiter der\n"
	.string "SILPH CO.!$"

SilphCo_2F_Text_ConnorDefeat::
	.string "Woher wusstest du, dass ich zum\n"
	.string "TEAM ROCKET gehöre?$"

SilphCo_2F_Text_ConnorPostBattle::
	.string "Ich bin ein Spion und infiltriere\n"
	.string "die SILPH CO.!$"

SilphCo_2F_Text_JerryIntro::
	.string "Hau ab!\n"
	.string "Du hast keinen Zutritt!$"

SilphCo_2F_Text_JerryDefeat::
	.string "Nicht schlecht, Herr Specht!$"

SilphCo_2F_Text_JerryPostBattle::
	.string "Aber findest du auch durch dieses\n"
	.string "Labyrinth?$"

SilphCo_2F_Text_Grunt1Intro::
	.string "Heh, du hast hier nichts verloren!$"

SilphCo_2F_Text_Grunt1Defeat::
	.string "Das ist hart! Verloren!$"

SilphCo_2F_Text_Grunt1PostBattle::
	.string "Die diamantförmigen Felder sind\n"
	.string "Teleporter!\p"
	.string "Eine Art Hi-Tech-Transportsystem!$"

SilphCo_2F_Text_Grunt2Intro::
	.string "Heh Balg!\n"
	.string "Was machst du hier?$"

SilphCo_2F_Text_Grunt2Defeat::
	.string "Ich bin ein Versager!$"

SilphCo_2F_Text_Grunt2PostBattle::
	.string "Die SILPH CO. und das TEAM ROCKET\n"
	.string "werden demnächst fusionieren!$"

Text_ThunderWaveTeach::
	.string "Zu Hilfe! Nein!\n"
	.string "Bitte nicht!\p"
	.string "Du bist gar nicht vom TEAM ROCKET!\n"
	.string "Ich dachte schon, es ginge zu\l"
	.string "Ende!\p"
	.string "Verzeihst du mir, wenn ich einem\n"
	.string "deiner POKéMON DONNERWELLE\l"
	.string "beibringe?$"

Text_ThunderWaveDeclined::
	.string "Oh…\n"
	.string "Aber DONNERWELLE ist praktisch…$"

Text_ThunderWaveWhichMon::
	.string "Welches POKéMON soll\n"
	.string "DONNERWELLE erlernen?$"

Text_ThunderWaveTaught::
	.string "DONNERWELLE verursacht\n"
	.string "Paralyse beim Gegner.\p"
	.string "Ein paralysiertes POKéMON kann\n"
	.string "sich im Kampf evtl. nicht bewegen.\p"
	.string "Da es eine Attacke der Element-\n"
	.string "klasse ELEKTRO ist, funktioniert\l"
	.string "sie bei manchen POKéMON nicht.$"

SilphCo_2F_Text_FloorSign::
	.string "SILPH CO. HAUPTSITZ\n"
	.string "1 OG$"

