SilphCo_2F_Text_ConnorIntro::
	.string "A l'aide! Je suis un employé de la\n"
	.string "SYLPHE SARL!$"

SilphCo_2F_Text_ConnorDefeat::
	.string "???\n"
	.string "Comment t'as su que j'étais de\l"
	.string "la TEAM ROCKET?$"

SilphCo_2F_Text_ConnorPostBattle::
	.string "Je travaille pour la SYLPHE SARL\n"
	.string "et la TEAM ROCKET!$"

SilphCo_2F_Text_JerryIntro::
	.string "Hop hop!\n"
	.string "Zone privée, dégage!$"

SilphCo_2F_Text_JerryDefeat::
	.string "OK.\n"
	.string "J'suis battu!$"

SilphCo_2F_Text_JerryPostBattle::
	.string "Trouve la sortie du labyrinthe!$"

SilphCo_2F_Text_Grunt1Intro::
	.string "Hé! Pas de mioches ici!$"

SilphCo_2F_Text_Grunt1Defeat::
	.string "La vache! T'es balèze.$"

SilphCo_2F_Text_Grunt1PostBattle::
	.string "Les dalles en forme de diamant sont\n"
	.string "des téléporteurs!\p"
	.string "C'est de la super technologie!$"

SilphCo_2F_Text_Grunt2Intro::
	.string "Hé, p'tite tête!\n"
	.string "Qu'est-ce tu fais là?$"

SilphCo_2F_Text_Grunt2Defeat::
	.string "Oups, j'ai perdu!$"

SilphCo_2F_Text_Grunt2PostBattle::
	.string "La SYLPHE SARL et la TEAM ROCKET\n"
	.string "vont fusionner!$"

Text_ThunderWaveTeach::
	.string "Au secours!\n"
	.string "A l'aide!\p"
	.string "Quoi?\n"
	.string "Tu n'es pas de la TEAM?\p"
	.string "Tant mieux!\n"
	.string "Tiens, prends ça!$"

Text_ThunderWaveDeclined::
	.string "Oh…\n"
	.string "Mais CAGE-ECLAIR est utile…$"

Text_ThunderWaveWhichMon::
	.string "A quel POKéMON enseigner\n"
	.string "CAGE-ECLAIR?$"

Text_ThunderWaveTaught::
	.string "CAGE-ECLAIR paralyse le\n"
	.string "POKéMON attaqué.\p"
	.string "Un POKéMON paralysé peut être\n"
	.string "incapable d'attaquer en combat.\p"
	.string "C'est une capacité de type\n"
	.string "ELECTRIK, ça ne marchera pas\l"
	.string "sur tous les POKéMON.$"

SilphCo_2F_Text_FloorSign::
	.string "SYLPHE SARL.\n"
	.string "1er étage.$"

