SilphCo_2F_Text_ConnorIntro::
    .ifdef ENGLISH
    .string "Help!\n"
    .string "I'm a SILPH employee.$"
    .endif
    .ifdef SPANISH
    .string "¡Socorro!\n"
    .string "¡Soy un empleado de SILPH S.A.!$"
    .endif

SilphCo_2F_Text_ConnorDefeat::
    .ifdef ENGLISH
    .string "How did you know\n"
    .string "I was a ROCKET?$"
    .endif
    .ifdef SPANISH
    .string "¿Cómo sabías que yo era un\n"
    .string "ROCKET?$"
    .endif

SilphCo_2F_Text_ConnorPostBattle::
    .ifdef ENGLISH
    .string "I work for both SILPH and TEAM\n"
    .string "ROCKET.$"
    .endif
    .ifdef SPANISH
    .string "¡Trabajo para SILPH S.A. y para\n"
    .string "el TEAM ROCKET!$"
    .endif

SilphCo_2F_Text_JerryIntro::
    .ifdef ENGLISH
    .string "It's off-limits here!\n"
    .string "Go home!$"
    .endif
    .ifdef SPANISH
    .string "¡Estás en zona prohibida!\n"
    .string "¡Vuelve a casa!$"
    .endif

SilphCo_2F_Text_JerryDefeat::
    .ifdef ENGLISH
    .string "You're good.$"
    .endif
    .ifdef SPANISH
    .string "¡Eres genial!$"
    .endif

SilphCo_2F_Text_JerryPostBattle::
    .ifdef ENGLISH
    .string "Can you solve the maze in here?\n"
    .string "It's not easy, I tell you!$"
    .endif
    .ifdef SPANISH
    .string "¿Puedes resolver este laberinto?$"
    .endif

SilphCo_2F_Text_Grunt1Intro::
    .ifdef ENGLISH
    .string "No kids are allowed in here!$"
    .endif
    .ifdef SPANISH
    .string "¡Aquí no pueden entrar los niños!$"
    .endif

SilphCo_2F_Text_Grunt1Defeat::
    .ifdef ENGLISH
    .string "Tough!$"
    .endif
    .ifdef SPANISH
    .string "¡Muy fuerte!$"
    .endif

SilphCo_2F_Text_Grunt1PostBattle::
    .ifdef ENGLISH
    .string "Diamond-shaped tiles are teleport\n"
    .string "blocks.\p"
    .string "They're transporters for this\n"
    .string "high-tech building.$"
    .endif
    .ifdef SPANISH
    .string "¡Las baldosas con forma\n"
    .string "de diamante son puntos\l"
    .string "de teletransporte!\p"
    .string "¡Son medios de transporte\n"
    .string "de alta tecnología!$"
    .endif

SilphCo_2F_Text_Grunt2Intro::
    .ifdef ENGLISH
    .string "Hey, kid!\n"
    .string "What are you wandering here for?$"
    .endif
    .ifdef SPANISH
    .string "¡Oye, tú!\n"
    .string "¿Qué haces aquí?$"
    .endif

SilphCo_2F_Text_Grunt2Defeat::
    .ifdef ENGLISH
    .string "I goofed!$"
    .endif
    .ifdef SPANISH
    .string "¡He metido la pata!$"
    .endif

SilphCo_2F_Text_Grunt2PostBattle::
    .ifdef ENGLISH
    .string "SILPH CO. will be associated with\n"
    .string "TEAM ROCKET!$"
    .endif
    .ifdef SPANISH
    .string "¡SILPH S.A. va a fusionarse\n"
    .string "con el TEAM ROCKET!$"
    .endif

Text_ThunderWaveTeach::
    .ifdef ENGLISH
    .string "Eeek!\n"
    .string "No! Stop! Help!\p"
    .string "Oh, you're not with TEAM ROCKET.\n"
    .string "I'm sorry, I thought…\p"
    .string "Will you forgive me if I teach\n"
    .string "you the THUNDER WAVE technique?$"
    .endif
    .ifdef SPANISH
    .string "¡Socorro!\n"
    .string "¡No! ¡Alto!\p"
    .string "¿No perteneces al TEAM ROCKET?\n"
    .string "Yo pensaba...\p"
    .string "Lo siento...\n"
    .string "Eh... ¿te enseño ONDA TRUENO?$"
    .endif

Text_ThunderWaveDeclined::
    .ifdef ENGLISH
    .string "Oh…\n"
    .string "But THUNDER WAVE is convenient…$"
    .endif
    .ifdef SPANISH
    .string "Eh...\n"
    .string "ONDA TRUENO es muy útil...$"
    .endif

Text_ThunderWaveWhichMon::
    .ifdef ENGLISH
    .string "Which POKéMON should I teach\n"
    .string "THUNDER WAVE?$"
    .endif
    .ifdef SPANISH
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe ONDA TRUENO?$"
    .endif

Text_ThunderWaveTaught::
    .ifdef ENGLISH
    .string "THUNDER WAVE causes paralysis in\n"
    .string "the target POKéMON.\p"
    .string "A paralyzed POKéMON may be unable\n"
    .string "to move in battle.\p"
    .string "It's an ELECTRIC-type move, so it\n"
    .string "won't work on some POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "ONDA TRUENO puede paralizar\n"
    .string "al POKéMON que sufre el ataque.\p"
    .string "Y cuando un POKéMON está\n"
    .string "paralizado en combate es posible\l"
    .string "que no se mueva.\p"
    .string "Es un ataque del tipo ELÉCTRICO,\n"
    .string "así que no funcionará contra\l"
    .string "algunos POKéMON.$"
    .endif

SilphCo_2F_Text_FloorSign::
    .ifdef ENGLISH
    .string "SILPH CO. HEAD OFFICE\n"
    .string "2F$"
    .endif
    .ifdef SPANISH
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P1$"
    .endif

