Route21_South_Text_JackIntro::
    .string "¡He conseguido a mi POKéMON\n"
    .string "en el mar, y aquí lo entreno!$"

Route21_South_Text_JackDefeat::
    .string "¡Splash!$"

Route21_South_Text_JackPostBattle::
    .string "¿Dónde atrapaste tus POKéMON?$"

Route21_South_Text_JeromeIntro::
    .string "¡Ahora estoy en un encuentro\n"
    .string "de triatlón!$"

Route21_South_Text_JeromeDefeat::
    .string "Ufff...\n"
    .string "Ufff... Ufff...$"

Route21_South_Text_JeromePostBattle::
    .string "¡Me has ganado! ¡Pero aún falta\n"
    .string "el ciclismo y la maratón!$"

Route21_South_Text_RolandIntro::
    .string "¡Ah!\n"
    .string "¡Siente el sol y el viento!$"

Route21_South_Text_RolandDefeat::
    .string "¡Auuu!\n"
    .string "¡He perdido!$"

Route21_South_Text_RolandPostBattle::
    .string "¡Estoy totalmente quemado!$"

Route21_South_Text_ClaudeIntro::
    .string "¡Eh!\n"
    .string "¡No asustes a los peces!$"

Route21_South_Text_ClaudeDefeat::
    .string "¡Perdona!\n"
    .string "¡No lo hice adrede!$"

Route21_South_Text_ClaudePostBattle::
    .string "¡Estaba enfadado porque no\n"
    .string "había pescado nada!$"

Route21_South_Text_NolanIntro::
    .string "¡Quédate conmigo hasta que lo\n"
    .string "consiga!$"

Route21_South_Text_NolanDefeat::
    .string "Qué forma de matar el tiempo...$"

Route21_South_Text_NolanPostBattle::
    .string "¡Eh!\n"
    .string "¡Algo ha picado! ¡Sí!$"

Route21_North_Text_LilIntro::
    .string "ÍA: ¿Cómo, que quieres luchar?\n"
    .string "IGOR, ¿cómo lo ves?$"

Route21_North_Text_LilDefeat::
    .string "ÍA: ¿Eso es lo que querías,\n"
    .string "que perdiéramos?$"

Route21_North_Text_LilPostBattle::
    .string "ÍA: Estoy cansada, ¿nos vamos ya\n"
    .string "a casa?$"

Route21_North_Text_LilNotEnoughMons::
    .string "ÍA: ¿Luchar? Con sólo un POKéMON\n"
    .string "no nos vamos a tomar la molestia.$"

Route21_North_Text_IanIntro::
    .string "IGOR: Mi hermana no se cansa\n"
    .string "de hacer ejercicio, por eso viene.$"

Route21_North_Text_IanDefeat::
    .string "IGOR: ¡Hermanita, no pasa nada!$"

Route21_North_Text_IanPostBattle::
    .string "IGOR: ¡Hermanita, así no hay forma\n"
    .string "de perder peso!$"

Route21_North_Text_IanNotEnoughMons::
    .string "IGOR: ¡A nosotros nos gusta luchar\n"
    .string "con dos POKéMON, así que...!$"
