Route21_South_Text_JackIntro::
    .ifdef ENGLISH
	.string "I caught my POKéMON at sea.$"
    .endif
    .ifdef SPANISH
    .string "¡He conseguido a mi POKéMON\n"
    .string "en el mar, y aquí lo entreno!$"
    .endif

Route21_South_Text_JackDefeat::
    .ifdef ENGLISH
	.string "Diver!!\n"
	.string "Down!!$"
    .endif
    .ifdef SPANISH
    .string "¡Splash!$"
    .endif

Route21_South_Text_JackPostBattle::
    .ifdef ENGLISH
	.string "Where'd you catch your POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¿Dónde atrapaste tus POKéMON?$"
    .endif

Route21_South_Text_JeromeIntro::
    .ifdef ENGLISH
	.string "Right now, I'm in a triathlon meet.$"
    .endif
    .ifdef SPANISH
    .string "¡Ahora estoy en un encuentro\n"
    .string "de triatlón!$"
    .endif

Route21_South_Text_JeromeDefeat::
    .ifdef ENGLISH
	.string "Pant…\n"
	.string "Pant… Pant…$"
    .endif
    .ifdef SPANISH
    .string "Ufff...\n"
    .string "Ufff... Ufff...$"
    .endif

Route21_South_Text_JeromePostBattle::
    .ifdef ENGLISH
	.string "I'm beat! But, I still have the\n"
	.string "bike race and marathon left!$"
    .endif
    .ifdef SPANISH
    .string "¡Me has ganado! ¡Pero aún falta\n"
    .string "el ciclismo y la maratón!$"
    .endif

Route21_South_Text_RolandIntro::
    .ifdef ENGLISH
	.string "Ahh!\n"
	.string "Feel the sun and the wind!$"
    .endif
    .ifdef SPANISH
    .string "¡Ah!\n"
    .string "¡Siente el sol y el viento!$"
    .endif

Route21_South_Text_RolandDefeat::
    .ifdef ENGLISH
	.string "Yow!\n"
	.string "I lost!$"
    .endif
    .ifdef SPANISH
    .string "¡Auuu!\n"
    .string "¡He perdido!$"
    .endif

Route21_South_Text_RolandPostBattle::
    .ifdef ENGLISH
	.string "I'm sunburnt to a crisp!$"
    .endif
    .ifdef SPANISH
    .string "¡Estoy totalmente quemado!$"
    .endif

Route21_South_Text_ClaudeIntro::
    .ifdef ENGLISH
	.string "Hey, don't scare away the fish!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh!\n"
    .string "¡No asustes a los peces!$"
    .endif

Route21_South_Text_ClaudeDefeat::
    .ifdef ENGLISH
	.string "Sorry! I'm just so frustrated from\n"
	.string "not catching anything.$"
    .endif
    .ifdef SPANISH
    .string "¡Perdona!\n"
    .string "¡No lo hice adrede!$"
    .endif

Route21_South_Text_ClaudePostBattle::
    .ifdef ENGLISH
	.string "Sheesh, I haven't caught a thing.\n"
	.string "Could this place actually be a\l"
	.string "giant pool or something?$"
    .endif
    .ifdef SPANISH
    .string "¡Estaba enfadado porque no\n"
    .string "había pescado nada!$"
    .endif

Route21_South_Text_NolanIntro::
    .ifdef ENGLISH
	.string "Keep me company till I get a hit.$"
    .endif
    .ifdef SPANISH
    .string "¡Quédate conmigo hasta que lo\n"
    .string "consiga!$"
    .endif

Route21_South_Text_NolanDefeat::
    .ifdef ENGLISH
	.string "That burned some time.$"
    .endif
    .ifdef SPANISH
    .string "Qué forma de matar el tiempo...$"
    .endif

Route21_South_Text_NolanPostBattle::
    .ifdef ENGLISH
	.string "Oh wait!\n"
	.string "I got a bite! Yeah!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh!\n"
    .string "¡Algo ha picado! ¡Sí!$"
    .endif

Route21_North_Text_LilIntro::
    .ifdef ENGLISH
	.string "LIL: Huh? A battle?\n"
	.string "IAN, can't you do it alone?$"
    .endif
    .ifdef SPANISH
    .string "ÍA: ¿Cómo, que quieres luchar?\n"
    .string "IGOR, ¿cómo lo ves?$"
    .endif

Route21_North_Text_LilDefeat::
    .ifdef ENGLISH
	.string "LIL: Oh, see?\n"
	.string "We lost. Happy now?$"
    .endif
    .ifdef SPANISH
    .string "ÍA: ¿Eso es lo que querías,\n"
    .string "que perdiéramos?$"
    .endif

Route21_North_Text_LilPostBattle::
    .ifdef ENGLISH
	.string "LIL: I'm tired.\n"
	.string "Can't we go home already?$"
    .endif
    .ifdef SPANISH
    .string "ÍA: Estoy cansada, ¿nos vamos ya\n"
    .string "a casa?$"
    .endif

Route21_North_Text_LilNotEnoughMons::
    .ifdef ENGLISH
	.string "LIL: Huh? A battle?\n"
	.string "I can't be bothered to do it alone.\l"
	.string "Bring two POKéMON, won't you?$"
    .endif
    .ifdef SPANISH
    .string "ÍA: ¿Luchar? Con sólo un POKéMON\n"
    .string "no nos vamos a tomar la molestia.$"
    .endif

Route21_North_Text_IanIntro::
    .ifdef ENGLISH
	.string "IAN: My sis doesn't get enough\n"
	.string "exercise, so I made her come.$"
    .endif
    .ifdef SPANISH
    .string "IGOR: Mi hermana no se cansa\n"
    .string "de hacer ejercicio, por eso viene.$"
    .endif

Route21_North_Text_IanDefeat::
    .ifdef ENGLISH
	.string "IAN: Awww, Sis!\n"
	.string "Get it together!$"
    .endif
    .ifdef SPANISH
    .string "IGOR: ¡Hermanita, no pasa nada!$"
    .endif

Route21_North_Text_IanPostBattle::
    .ifdef ENGLISH
	.string "IAN: Come on, Sis!\p"
	.string "You're not going to lose weight\n"
	.string "like this!$"
    .endif
    .ifdef SPANISH
    .string "IGOR: ¡Hermanita, así no hay forma\n"
    .string "de perder peso!$"
    .endif

Route21_North_Text_IanNotEnoughMons::
    .ifdef ENGLISH
	.string "IAN: We want a two-on-two battle.\n"
	.string "So can you bring two POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "IGOR: ¡A nosotros nos gusta luchar\n"
    .string "con dos POKéMON, así que...!$"
    .endif
