FiveIsland_WaterLabyrinth_Text_LetMeTakeLookAtMons::
    .ifdef ENGLISH
    .string "You travel all over the place,\n"
    .string "don't you?\p"
    .string "You're not driving your POKéMON\n"
    .string "too harshly, are you?\p"
    .string "Let me take a look.\n"
    .string "… … …   … … …$"
    .endif
    .ifdef SPANISH
    .string "Vas de aquí para allá, ¿no?\p"
    .string "¿Y no es mucha paliza para\n"
    .string "tus POKéMON?\p"
    .string "Voy a echarles un vistazo.\n"
    .string "... ... ... ... ... ...$"
    .endif

FiveIsland_WaterLabyrinth_Text_HmmISeeIsee::
    .ifdef ENGLISH
    .string "Ah, hmm…\n"
    .string "I see, I see…$"
    .endif
    .ifdef SPANISH
    .string "Mmm...\n"
    .string "Ya veo...$"
    .endif

FiveIsland_WaterLabyrinth_Text_TreatMonRightHaveThis::
    .ifdef ENGLISH
    .string "Oh, impressive.\n"
    .string "You treat your POKéMON right.\p"
    .string "I think you can be entrusted with\n"
    .string "this.\p"
    .string "Please, I'd like you to have this.$"
    .endif
    .ifdef SPANISH
    .string "Impresionante.\n"
    .string "Tratas muy bien a los POKéMON.\p"
    .string "No hace falta que te diga nada.\p"
    .string "Toma, quiero darte esto.$"
    .endif

FiveIsland_WaterLabyrinth_Text_ReceivedEggFromMan::
    .ifdef ENGLISH
    .string "{PLAYER} received an EGG\n"
    .string "from the man!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió un HUEVO!$"
    .endif

FiveIsland_WaterLabyrinth_Text_DontHaveSpaceInYourParty::
    .ifdef ENGLISH
    .string "…Unfortunately, you don't have\n"
    .string "space for this in your party.\p"
    .string "You'd better come back for it\n"
    .string "another time.$"
    .endif
    .ifdef SPANISH
    .string "Vaya, qué lástima..., tu equipo\n"
    .string "está completo.\p"
    .string "Vuelve a recogerlo en otro\n"
    .string "momento.$"
    .endif

@ Unused
FiveIsland_WaterLabyrinth_Text_YouveComeBackForTheEgg::
    .string "やあ\n"
    .string "タマゴを　もらいに\l"
    .string "きて　くれたんだね$"

FiveIsland_WaterLabyrinth_Text_GladIMetSomeoneLikeYou::
    .ifdef ENGLISH
    .string "I received that EGG while I was\n"
    .string "traveling.\p"
    .string "I'm glad I met someone like you.$"
    .endif
    .ifdef SPANISH
    .string "A mí me dieron ese HUEVO cuando\n"
    .string "estuve fuera.\p"
    .string "Me alegro de haber encontrado\n"
    .string "a alguien como tú.$"
    .endif

FiveIsland_WaterLabyrinth_Text_CuteMonRemindsMeOfDaisy::
    .ifdef ENGLISH
    .string "Oh, hello.\n"
    .string "That's a cute {STR_VAR_2}.\p"
    .string "Seeing it reminds me of a sweet \n"
    .string "little girl I met while traveling.\p"
    .string "She was gently grooming POKéMON…\n"
    .string "She was a little angel.\p"
    .string "That little girl's name…\n"
    .string "I think it was DAISY.$"
    .endif
    .ifdef SPANISH
    .string "Hola, ¿qué tal?\n"
    .string "¡Qué {STR_VAR_2} tan mono!\p"
    .string "Al verlo me acuerdo de una niña a\n"
    .string "la que vi cuando estaba de viaje.\p"
    .string "La chiquilla cuidaba con mimo a un\n"
    .string "POKéMON. Era un angelito, la cría.\p"
    .string "Lo que no recuerdo es el nombre...\n"
    .string "Bueno, creo que era DALIA.$"
    .endif

FiveIsland_WaterLabyrinth_Text_AlizeIntro::
    .ifdef ENGLISH
    .string "This is an excellent environment\n"
    .string "for raising POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "Éste es un sitio estupendo\n"
    .string "para criar POKéMON.$"
    .endif

FiveIsland_WaterLabyrinth_Text_AlizeDefeat::
    .ifdef ENGLISH
    .string "Your POKéMON are growing up\n"
    .string "admirably well!$"
    .endif
    .ifdef SPANISH
    .string "¡Tus POKéMON van de maravilla!$"
    .endif

FiveIsland_WaterLabyrinth_Text_AlizePostBattle::
    .ifdef ENGLISH
    .string "You know, I think you have the\n"
    .string "talent to be a good BREEDER.$"
    .endif
    .ifdef SPANISH
    .string "Creo que eres genial criando\n"
    .string "POKéMON.$"
    .endif
