FuchsiaCity_Gym_Text_KogaIntro::
    .ifdef ENGLISH
    .string "KOGA: Fwahahaha!\p"
    .string "A mere child like you dares to\n"
    .string "challenge me?\p"
    .string "The very idea makes me shiver\n"
    .string "with mirth!\p"
    .string "Very well, I shall show you true\n"
    .string "terror as a ninja master.\p"
    .string "Poison brings steady doom.\n"
    .string "Sleep renders foes helpless.\p"
    .string "Despair to the creeping horror of\n"
    .string "POISON-type POKéMON!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif
    .ifdef SPANISH
    .string "KOGA: ¡Uajajaja!\p"
    .string "¿Alguien tan enclenque como tú\n"
    .string "se atreve a desafiarme?\p"
    .string "¡Me parto de la risa!\p"
    .string "¡Como maestro ninja, te enseñaré\n"
    .string "qué es el miedo!\p"
    .string "¡Sentirás la desesperación de las\n"
    .string "técnicas del envenenamiento y del\l"
    .string "sueño!\p"
    .string "¡Adoro a mis temidos POKéMON\n"
    .string "del tipo VENENO!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif

FuchsiaCity_Gym_Text_KogaDefeat::
    .ifdef ENGLISH
    .string "Humph!\n"
    .string "You have proven your worth!\p"
    .string "Here!\n"
    .string "Take the SOULBADGE!$"
    .endif
    .ifdef SPANISH
    .string "¡Ejem!\n"
    .string "¡Has demostrado tu valor!\p"
    .string "¡Aquí tienes la MEDALLA ALMA!$"
    .endif

FuchsiaCity_Gym_Text_KogaPostBattle::
    .ifdef ENGLISH
    .string "When afflicted by TOXIC, a POKéMON\n"
    .string "suffers more and more.\p"
    .string "It suffers worsening damage as the\n"
    .string "battle wears on!\p"
    .string "It will surely terrorize foes!$"
    .endif
    .ifdef SPANISH
    .string "¡Si los POKéMON son INTOXICADOS\n"
    .string "sufrirán más y más durante el\l"
    .string "combate!\p"
    .string "¡Y lo seguirán haciendo una vez\n"
    .string "que acabe la lucha!\p"
    .string "¡El veneno aterroriza a todo\n"
    .string "el mundo!$"
    .endif

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
    .ifdef ENGLISH
    .string "Now that you have the SOULBADGE,\n"
    .string "the DEFENSE of your POKéMON rises.\p"
    .string "It also lets you SURF outside of\n"
    .string "battle.\p"
    .string "Ah!\n"
    .string "Take this, too!$"
    .endif
    .ifdef SPANISH
    .string "¡Ahora que tienes la MEDALLA ALMA,\n"
    .string "la DEFENSA de tus POKéMON\l"
    .string "aumentará!\p"
    .string "¡Y podrás hacer SURF siempre\n"
    .string "que quieras!\p"
    .string "¡Ah!\n"
    .string "¡Llévate esto también!$"
    .endif

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
    .ifdef ENGLISH
    .string "{PLAYER} received TM06\n"
    .string "from KOGA.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo la MT06\n"
    .string "de manos de KOGA!$"
    .endif

FuchsiaCity_Gym_Text_KogaExplainTM06::
    .ifdef ENGLISH
    .string "Sealed within that TM06 lies\n"
    .string "TOXIC!\p"
    .string "It is a secret technique dating\n"
    .string "back some four hundred years.$"
    .endif
    .ifdef SPANISH
    .string "¡La MT06 contiene TÓXICO!\p"
    .string "¡Es una técnica secreta de hace\n"
    .string "más de 400 años!$"
    .endif

FuchsiaCity_Gym_Text_MakeSpaceForThis::
    .ifdef ENGLISH
    .string "Make space for this, child!$"
    .endif
    .ifdef SPANISH
    .string "¡Hazle sitio a esto!$"
    .endif

FuchsiaCity_Gym_Text_KaydenIntro::
    .ifdef ENGLISH
    .string "Strength isn't the key for POKéMON.\n"
    .string "Do you understand this?\p"
    .string "POKéMON is about strategy!\p"
    .string "I'll show you how strategy can\n"
    .string "beat brute strength.$"
    .endif
    .ifdef SPANISH
    .string "La fuerza no es la clave con los\n"
    .string "POKéMON, ¿sabes?\p"
    .string "¡La estrategia es lo importante!\p"
    .string "¡Te enseñaré cómo la estrategia\n"
    .string "puede vencer a la fuerza!$"
    .endif

FuchsiaCity_Gym_Text_KaydenDefeat::
    .ifdef ENGLISH
    .string "What?\n"
    .string "Extraordinary!$"
    .endif
    .ifdef SPANISH
    .string "¡Extraordinario!$"
    .endif

FuchsiaCity_Gym_Text_KaydenPostBattle::
    .ifdef ENGLISH
    .string "So, you mix brawn with brains?\n"
    .string "Good strategy!\p"
    .string "That's remarkable for a child\n"
    .string "TRAINER.$"
    .endif
    .ifdef SPANISH
    .string "¿Mezclarás fuerza e inteligencia?\n"
    .string "¡Buena táctica!\p"
    .string "¡Es asombroso lo que sabes\n"
    .string "con lo joven que eres!$"
    .endif

FuchsiaCity_Gym_Text_KirkIntro::
    .ifdef ENGLISH
    .string "I was a magician once upon a time.\p"
    .string "But I dreamt of becoming a ninja,\n"
    .string "so I joined this GYM.$"
    .endif
    .ifdef SPANISH
    .string "¡Quería ser un ninja y por eso\n"
    .string "vine a este GIMNASIO!$"
    .endif

FuchsiaCity_Gym_Text_KirkDefeat::
    .ifdef ENGLISH
    .string "I'm done for!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya, he perdido!$"
    .endif

FuchsiaCity_Gym_Text_KirkPostBattle::
    .ifdef ENGLISH
    .string "Even though I've lost, I will keep\n"
    .string "training according to the teachings\l"
    .string "of KOGA, my ninja master.$"
    .endif
    .ifdef SPANISH
    .string "¡Seguiré entrenándome con KOGA,\n"
    .string "mi maestro ninja!$"
    .endif

FuchsiaCity_Gym_Text_NateIntro::
    .ifdef ENGLISH
    .string "Let's see you beat my special\n"
    .string "techniques!$"
    .endif
    .ifdef SPANISH
    .string "¡A ver si superas mis técnicas\n"
    .string "especiales!$"
    .endif

FuchsiaCity_Gym_Text_NateDefeat::
    .ifdef ENGLISH
    .string "You had me fooled!$"
    .endif
    .ifdef SPANISH
    .string "¡Me has dejado alucinado!$"
    .endif

FuchsiaCity_Gym_Text_NatePostBattle::
    .ifdef ENGLISH
    .string "I like poison and sleep techniques,\n"
    .string "as they linger after battle!$"
    .endif
    .ifdef SPANISH
    .string "¡Me gustan los ataques de sueño\n"
    .string "y veneno porque perduran tras\l"
    .string "el combate!$"
    .endif

FuchsiaCity_Gym_Text_PhilIntro::
    .ifdef ENGLISH
    .string "Stop right there!\p"
    .string "The famed invisible walls of\n"
    .string "FUCHSIA GYM have you frustrated?$"
    .endif
    .ifdef SPANISH
    .string "¡Alto ahí!\p"
    .string "¿Te han agobiado nuestros muros\n"
    .string "invisibles?$"
    .endif

FuchsiaCity_Gym_Text_PhilDefeat::
    .ifdef ENGLISH
    .string "Whoa!\n"
    .string "You've got it!$"
    .endif
    .ifdef SPANISH
    .string "¡Buaaa!\n"
    .string "¡Qué bien luchas!$"
    .endif

FuchsiaCity_Gym_Text_PhilPostBattle::
    .ifdef ENGLISH
    .string "You impressed me!\n"
    .string "Here's a hint!\p"
    .string "Look very closely for gaps in the\n"
    .string "invisible walls!$"
    .endif
    .ifdef SPANISH
    .string "¡Impresionante!\p"
    .string "Oye, una cosa: mira bien entre\n"
    .string "los huecos de los muros invisibles.$"
    .endif

FuchsiaCity_Gym_Text_EdgarIntro::
    .ifdef ENGLISH
    .string "I also study the way of the ninja\n"
    .string "with Master KOGA!\p"
    .string "Ninja have a long history of using\n"
    .string "animals!$"
    .endif
    .ifdef SPANISH
    .string "¡También estudio técnicas ninja\n"
    .string "con el maestro KOGA!\p"
    .string "¡Los ninja llevan mucho tiempo\n"
    .string "usando animales!$"
    .endif

FuchsiaCity_Gym_Text_EdgarDefeat::
    .ifdef ENGLISH
    .string "Awoo!$"
    .endif
    .ifdef SPANISH
    .string "¡Auuuu!$"
    .endif

FuchsiaCity_Gym_Text_EdgarPostBattle::
    .ifdef ENGLISH
    .string "I still have much to learn.$"
    .endif
    .ifdef SPANISH
    .string "¡Me queda mucho por aprender!$"
    .endif

FuchsiaCity_Gym_Text_ShawnIntro::
    .ifdef ENGLISH
    .string "Master KOGA comes from a long line\n"
    .string "of ninjas.\p"
    .string "What did you descend from?$"
    .endif
    .ifdef SPANISH
    .string "¡El maestro KOGA desciende\n"
    .string "de una gran familia de ninjas!\p"
    .string "¿Y tú de qué familia desciendes?$"
    .endif

FuchsiaCity_Gym_Text_ShawnDefeat::
    .ifdef ENGLISH
    .string "You're more skilled than I'd\n"
    .string "thought!$"
    .endif
    .ifdef SPANISH
    .string "Eres más fuerte de lo que\n"
    .string "pensaba...$"
    .endif

FuchsiaCity_Gym_Text_ShawnPostBattle::
    .ifdef ENGLISH
    .string "Where there is light, there is\n"
    .string "shadow!\p"
    .string "Light and shadow!\n"
    .string "Which do you choose?$"
    .endif
    .ifdef SPANISH
    .string "¡Donde hay luz hay sombras!\p"
    .string "¡Luz o sombra!\n"
    .string "¿Cuál eliges?$"
    .endif

FuchsiaCity_Gym_Text_GymGuyAdvice::
    .ifdef ENGLISH
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "FUCHSIA GYM is a tricked-up place.\n"
    .string "It's riddled with invisible walls!\p"
    .string "KOGA might appear close, but he's\n"
    .string "blocked off.\p"
    .string "You have to find gaps in the walls\n"
    .string "to reach him.$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, aspirante al título!\p"
    .string "¡El GIMNASIO FUCSIA está lleno de\n"
    .string "muros invisibles!\p"
    .string "¡Podría parecer que KOGA está\n"
    .string "cerca, pero hay muros invisibles\l"
    .string "que lo protegen!\p"
    .string "¡Busca huecos entre los muros\n"
    .string "para llegar hasta él!$"
    .endif

FuchsiaCity_Gym_Text_GymGuyPostVictory::
    .ifdef ENGLISH
    .string "It's amazing how ninja can terrify,\n"
    .string "even now!$"
    .endif
    .ifdef SPANISH
    .string "¡Es increíble lo terribles que\n"
    .string "pueden ser los ninjas!$"
    .endif

FuchsiaCity_Gym_Text_GymStatue::
    .ifdef ENGLISH
    .string "FUCHSIA POKéMON GYM\n"
    .string "LEADER: KOGA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de FUCSIA: KOGA\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"
    .endif

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
    .ifdef ENGLISH
    .string "FUCHSIA POKéMON GYM\n"
    .string "LEADER: KOGA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de FUCSIA: KOGA\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"
    .endif

