FuchsiaCity_Gym_Text_KogaIntro::
    .string "KOGA: Ihahahaha!\p"
    .string "Un microbo come te osa\n"
    .string "sfidarmi?\p"
    .string "Bene! T'insegnerò cos'è la paura,\n"
    .string "sono un maestro ninja!\p"
    .string "Proverai la forza terrorizzante dei\n"
    .string "POKéMON di tipo VELENO!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

FuchsiaCity_Gym_Text_KogaDefeat::
    .string "Hai provato quanto vali!\p"
    .string "Ti conferisco la MEDAGLIA ANIMA!$"

FuchsiaCity_Gym_Text_KogaPostBattle::
    .string "Se colpiti da TOSSINA, i POKéMON\n"
    .string "soffriranno sempre più durante la\l"
    .string "lotta!\p"
    .string "È lo spauracchio degli avversari!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
    .string "Ora che hai la MEDAGLIA ANIMA, la\n"
    .string "DIFESA dei tuoi POKéMON aumenterà!\p"
    .string "Potrai anche usare SURF quando non\n"
    .string "stai lottando!\p"
    .string "Ah!\n"
    .string "Prendi anche questo!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
    .string "{PLAYER} riceve\n"
    .string "la MT06!$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
    .string "La MT06 contiene la TOSSINA!\p"
    .string "È una tecnica segreta che risale a\n"
    .string "più di 400 anni fa!$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
    .string "Non hai abbastanza spazio!$"

FuchsiaCity_Gym_Text_KaydenIntro::
    .string "La forza non è tutto per i\n"
    .string "POKéMON!\p"
    .string "Ci vuole tattica!\p"
    .string "Ti insegnerò come la strategia può\n"
    .string "vincere sulla forza bruta!$"

FuchsiaCity_Gym_Text_KaydenDefeat::
    .string "Cosa?\n"
    .string "Straordinario!$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
    .string "Unisci la forza all'intelligenza?\n"
    .string "Buona tattica!$"

FuchsiaCity_Gym_Text_KirkIntro::
    .string "Sono diventato membro di questa\n"
    .string "PALESTRA perché volevo\l"
    .string "diventare un ninja!$"

FuchsiaCity_Gym_Text_KirkDefeat::
    .string "Puah! Sono esausto!$"

FuchsiaCity_Gym_Text_KirkPostBattle::
    .string "Continuerò a seguire gli\n"
    .string "insegnamenti di KOGA,\l"
    .string "il mio maestro ninja!$"

FuchsiaCity_Gym_Text_NateIntro::
    .string "Vediamo se batti le mie tecniche\n"
    .string "speciali!$"

FuchsiaCity_Gym_Text_NateDefeat::
    .string "Mi hai ingannato!$"

FuchsiaCity_Gym_Text_NatePostBattle::
    .string "Mi piacciono le tecniche del sonno\n"
    .string "e del veleno perché durano oltre\l"
    .string "la lotta!$"

FuchsiaCity_Gym_Text_PhilIntro::
    .string "Fermati lì!\p"
    .string "Hai visto i nostri muri invisibili?\n"
    .string "Ops, scusa la contraddizione.$"

FuchsiaCity_Gym_Text_PhilDefeat::
    .string "Wow!\n"
    .string "Mica male!$"

FuchsiaCity_Gym_Text_PhilPostBattle::
    .string "Impressionante!\n"
    .string "Ti do un consiglio…\p"
    .string "Cerca le fessure nel muro\n"
    .string "invisibile!$"

FuchsiaCity_Gym_Text_EdgarIntro::
    .string "Studio le tecniche ninja con il\n"
    .string "maestro KOGA!\p"
    .string "I ninja usano da sempre gli\n"
    .string "animali!$"

FuchsiaCity_Gym_Text_EdgarDefeat::
    .string "Ahiaaa!$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
    .string "Ho ancora molto da imparare!$"

FuchsiaCity_Gym_Text_ShawnIntro::
    .string "Il maestro KOGA discende da una\n"
    .string "grande famiglia di ninja!\p"
    .string "E tu da dove discendi?$"

FuchsiaCity_Gym_Text_ShawnDefeat::
    .string "Mi hai sconfitto.$"

FuchsiaCity_Gym_Text_ShawnPostBattle::
    .string "Dove c'è luce c'è anche ombra!\p"
    .string "Preferisci la luce o l'ombra?$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
    .string "Ehi!\n"
    .string "Aspirante CAMPIONE!\p"
    .string "La PALESTRA di FUCSIAPOLI è piena\n"
    .string "di muri invisibili!\p"
    .string "KOGA può sembrare vicino, ma la\n"
    .string "via è sbarrata!\p"
    .string "Trova le fessure nel muro per\n"
    .string "raggiungerlo!$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
    .string "È incredibile quanto terribili\n"
    .string "possano essere i ninja!$"

FuchsiaCity_Gym_Text_GymStatue::
    .string "CAPOPALESTRA di FUCSIAPOLI:\n"
    .string "KOGA\p"
    .string "ALLENATORI VINCENTI:\n"
    .string "{RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
    .string "CAPOPALESTRA di FUCSIAPOLI:\n"
    .string "KOGA\p"
    .string "ALLENATORI VINCENTI:\n"
    .string "{RIVAL}, {PLAYER}$"

