PokemonLeague_HallOfFame_Text_OakCongratulations::
    .ifdef ENGLISH
    .string "OAK: Er-hem!\n"
    .string "Congratulations, {PLAYER}!\p"
    .string "This floor is the POKéMON HALL OF\n"
    .string "FAME.\p"
    .string "POKéMON LEAGUE CHAMPIONS are\n"
    .string "honored for their exploits here.\p"
    .string "Their POKéMON are also recorded in\n"
    .string "the HALL OF FAME.\p"
    .string "{PLAYER}!\p"
    .string "You have worked hard to become\n"
    .string "the new LEAGUE CHAMPION.\p"
    .string "Congratulations, {PLAYER}, you and\n"
    .string "your POKéMON are HALL OF FAMERS!$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡Ejem!\n"
    .string "¡Enhorabuena, {PLAYER}!\p"
    .string "¡En este piso está el HALL de la\n"
    .string "FAMA de los POKéMON!\p"
    .string "¡Aquí son homenajeados por sus\n"
    .string "hazañas los campeones de la LIGA\l"
    .string "POKéMON!\p"
    .string "¡Sus POKéMON también son\n"
    .string "registrados en el HALL de la FAMA!\p"
    .string "¡{PLAYER}!\p"
    .string "¡Has luchado muchísimo para\n"
    .string "ganar la LIGA!\p"
    .string "¡Enhorabuena, {PLAYER}, tú y tus\n"
    .string "POKéMON ya sois famosos!$"
    .endif

