SafariZone_West_Text_RestHouse::
    .ifdef ENGLISH
    .string "REST HOUSE$"
    .endif
    .ifdef SPANISH
    .string "CASA DE REPOSO$"
    .endif

SafariZone_West_Text_PleaseFindWardensLostTeeth::
    .ifdef ENGLISH
    .string "REQUEST NOTICE\p"
    .string "Please find the SAFARI WARDEN's\n"
    .string "lost GOLD TEETH.\l"
    .string "They're around here somewhere.\p"
    .string "Reward offered!\n"
    .string "Contact: WARDEN$"
    .endif
    .ifdef SPANISH
    .string "AVISO\p"
    .string "Encuentra los DIENTES de ORO\n"
    .string "perdidos del GUARDA del SAFARI.\l"
    .string "Están por aquí.\p"
    .string "¡Se ofrece recompensa!\n"
    .string "Contactar con el GUARDA.$"
    .endif

SafariZone_West_Text_SearchForSecretHouse::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "Zone Exploration Campaign!\n"
    .string "The Search for the SECRET HOUSE!$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "¡Operación Exploración de la zona!\n"
    .string "¡La búsqueda de la CASA SECRETA!$"
    .endif

SafariZone_West_Text_AreaSign::
    .ifdef ENGLISH
    .string "AREA 3\n"
    .string "EAST: CENTER AREA$"
    .endif
    .ifdef SPANISH
    .string "ZONA 3\n"
    .string "ESTE: ZONA CENTRAL$"
    .endif

