SafariZone_West_Text_RestHouse::
	.string "RASTHAUS$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
	.string "BELOHNUNG!\p"
	.string "Wer die GOLDZÄHNE des Parkwächters\n"
	.string "der SAFARI-ZONE findet, erhält\l"
	.string "eine Belohnung!\p"
	.string "Finder melden sich bitte beim\n"
	.string "Parkwächter!$"

SafariZone_West_Text_SearchForSecretHouse::
	.string "TIPPS FÜR TRAINER\p"
	.string "Erforsche die SAFARI-ZONE!\n"
	.string "Finde das GEHEIME HAUS!$"

SafariZone_West_Text_AreaSign::
	.string "AREAL 3\n"
	.string "OSTEN: ZENTRUM$"

