SafariZone_West_Text_RestHouse::
	.string "ABRI$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
	.string "AVIS\p"
	.string "Veuillez trouver la DENT D'OR du\n"
	.string "GARDIEN. Explorez les environs.\p"
	.string "Récompense assurée!\n"
	.string "Contactez le GARDIEN.$"

SafariZone_West_Text_SearchForSecretHouse::
	.string "ASTUCE\p"
	.string "Grand concours organisé:\n"
	.string "Cherchez la CABANE SECRETE!$"

SafariZone_West_Text_AreaSign::
	.string "PARC 3\n"
	.string "EST: PARC CENTRAL$"

