VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish::
    .ifdef ENGLISH
    .string "I'm the FISHING GURU!\p"
    .string "I simply looove fishing!\n"
    .string "I can't bear to go without.\p"
    .string "Tell me, do you like to fish?$"
    .endif
    .ifdef SPANISH
    .string "¡Yo soy el GURÚ PESCADOR!\p"
    .string "¡Me encanta pescar!\n"
    .string "¡Es lo más!\p"
    .string "Y a ti, ¿te gusta pescar?$"
    .endif

VermilionCity_House1_Text_TakeThisAndFish::
    .ifdef ENGLISH
    .string "Grand! I like your style.\n"
    .string "I think we can be friends.\p"
    .string "Take this and fish, young friend!$"
    .endif
    .ifdef SPANISH
    .string "¡Fenomenal!\n"
    .string "¡Me gusta tu estilo!\p"
    .string "¡Toma esto y pesca, anda!$"
    .endif

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru::
    .ifdef ENGLISH
    .string "{PLAYER} received an OLD ROD from\n"
    .string "the FISHING GURU.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió una CAÑA VIEJA\n"
    .string "de manos del GURÚ PESCADOR!$"
    .endif

VermilionCity_House1_Text_FishingIsAWayOfLife::
    .ifdef ENGLISH
    .string "Fishing is a way of life!\n"
    .string "It is like the finest poetry.\p"
    .string "From the seas to rivers, go out\n"
    .string "and land the big one, my friend.$"
    .endif
    .ifdef SPANISH
    .string "¡La pesca es una forma de vida!\n"
    .string "¡Es un arte!\p"
    .string "¡En el mar, en los ríos, da igual,\n"
    .string "hay que pescar el más grande!$"
    .endif

VermilionCity_House1_Text_OhThatsSoDisappointing::
    .ifdef ENGLISH
    .string "Oh…\n"
    .string "That's so disappointing…$"
    .endif
    .ifdef SPANISH
    .string "Oh...\n"
    .string "Estoy tan decepcionado...$"
    .endif

VermilionCity_House1_Text_HowAreTheFishBiting::
    .ifdef ENGLISH
    .string "Hello there, {PLAYER}!\p"
    .string "How are the fish biting?$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, {PLAYER}!\p"
    .string "¿Cómo va esa pesca?$"
    .endif

VermilionCity_House1_Text_NoRoomForNiceGift::
    .ifdef ENGLISH
    .string "Oh, no!\p"
    .string "I had a nice gift for you, but you\n"
    .string "have no room for it!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh, no!\p"
    .string "¡Tenía un regalo para ti, pero no\n"
    .string "tienes sitio!$"
    .endif

