VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish::
	.string "Je suis le… MAITRE PECHEUR!\p"
	.string "La pêche… moi…\n"
	.string "J'adore ça!\p"
	.string "Et toi, p'tite tête?$"

VermilionCity_House1_Text_TakeThisAndFish::
	.string "Cool!\n"
	.string "T'as l'air de quelqu'un de bien!\p"
	.string "Prends ça! Que la Grand' Pêche\n"
	.string "soit avec toi!$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru::
	.string "{PLAYER} obtient la\n"
	.string "CANNE!$"

VermilionCity_House1_Text_FishingIsAWayOfLife::
	.string "La pêche c'est comme la vie!\p"
	.string "Quand ça mord, ça va! \n"
	.string "Quand ça mord pas, ça va pas!$"

VermilionCity_House1_Text_OhThatsSoDisappointing::
	.string "Oh… Je suis très déçu…$"

VermilionCity_House1_Text_HowAreTheFishBiting::
	.string "Tiens, salut {PLAYER}!\p"
	.string "Alors, ça mord?$"

VermilionCity_House1_Text_NoRoomForNiceGift::
	.string "Ha ben non!\p"
	.string "J'avais un cadeau pour toi, mais\n"
	.string "t'as plus de place!$"

