VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish::
	.string "Ich bin der PROFIANGLER!\p"
	.string "Ich liebe den Angelsport!\p"
	.string "Angelst du auch gerne?$"

VermilionCity_House1_Text_TakeThisAndFish::
	.string "Klasse! Du bist mir sympathisch!\p"
	.string "Nimm das hier und gehe angeln!$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru::
	.string "{PLAYER} erhält\n"
	.string "eine ANGEL!$"

VermilionCity_House1_Text_FishingIsAWayOfLife::
	.string "Angeln ist meine Leidenschaft!\p"
	.string "Suche in Seen und Flüssen und\n"
	.string "lande den großen Fang!$"

VermilionCity_House1_Text_OhThatsSoDisappointing::
	.string "Oh!\n"
	.string "Das ist so enttäuschend...$"

VermilionCity_House1_Text_HowAreTheFishBiting::
	.string "Hallo, {PLAYER}!\p"
	.string "Wie beißen die Fische?$"

VermilionCity_House1_Text_NoRoomForNiceGift::
	.string "Oh nein!\p"
	.string "Ich habe ein Geschenk für dich!\n"
	.string "Aber du kannst nichts mehr tragen!$"

