SSAnne_1F_Room6_Text_TakeAShortRest::
	.string "Du siehst müde aus!\n"
	.string "Komm, ruhe dich kurz aus!$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed::
	.string "Schön, dass alle erholt und\n"
	.string "erfrischt aussehen.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother::
	.string "Entschuldige, dass ich mich über\n"
	.string "dich aufgeregt habe. Du siehst aus\l"
	.string "wie mein kleiner Bruder…$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister::
	.string "Entschuldige, dass ich mich über\n"
	.string "dich aufgeregt habe. Du siehst aus\l"
	.string "wie meine kleine Schwester…$"

