SSAnne_1F_Room6_Text_TakeAShortRest::
    .string "¡Tienes una cara de agotamiento!\n"
    .string "¿Quieres descansar un ratito?$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed::
    .string "¡Eso ya es otra cosa! ¡Me encanta\n"
    .string "ver a todo el mundo descansado!$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother::
    .string "Bueno, yo lo decía por tu bien.\n"
    .string "Es que me recuerdas a mi hermano\l"
    .string "pequeño...$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister::
    .string "Bueno, yo lo decía por tu bien.\n"
    .string "Es que me recuerdas a mi hermana\l"
    .string "pequeña...$"
