SSAnne_1F_Room6_Text_TakeAShortRest::
	.string "Tu as fait un long voyage, non?\n"
	.string "Tu veux te reposer un moment?$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed::
	.string "Contente de voir que tout le\n"
	.string "monde va bien.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother::
	.string "Oh, désolée de t'embêter. Mais tu\n"
	.string "ressembles à mon petit frère.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister::
	.string "Oh, désolée de t'embêter. Mais tu\n"
	.string "ressembles à ma petite sœur.$"

