CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
    .string "EEVEE puede evolucionar\n"
    .string "y convertirse en tres tipos\l"
    .string "de POKéMON.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
    .string "¡Hay un correo electrónico!\p"
    .string "...\p"
    .string "Los 3 legendarios pájaros POKéMON\n"
    .string "son ARTICUNO, ZAPDOS y MOLTRES.\p"
    .string "Desconocemos sus guaridas.\p"
    .string "Pensamos explorar la cueva\n"
    .string "que hay cerca de la CELESTE.\p"
    .string "De: EQUIPO de INVESTIGACIÓN\n"
    .string "POKéMON...$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
    .string "¡Un bote de ámbar!$"
