CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
	.string "EVOLI kann sich zu einem von drei\n"
	.string "verschiedenen POKéMON entwickeln.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
	.string "Eine E-Mail ist angekommen!\p"
	.string "...\p"
	.string "ARKTOS, ZAPDOS und LAVADOS sind\n"
	.string "die drei legendären Vogel-POKéMON.\p"
	.string "Niemand weiß, in welcher Gegend sie\n"
	.string "leben.\p"
	.string "Wir werden als nächstes in der\n"
	.string "Höhle nahe AZURIA CITY suchen.\p"
	.string "\n"
	.string "Von: POKéMON-FORSCHUNGSTEAM\p"
	.string "...$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
	.string "Eine Pfeife aus Bernstein!$"

