CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
    .ifdef ENGLISH
    .string "EEVEE can evolve into one of three\n"
    .string "kinds of POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "EEVEE puede evolucionar\n"
    .string "y convertirse en tres tipos\l"
    .string "de POKéMON.$"
    .endif

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
    .ifdef ENGLISH
    .string "There's an e-mail message.\p"
    .string "… … …\p"
    .string "There are three legendary bird\n"
    .string "POKéMON.\p"
    .string "They are ARTICUNO, ZAPDOS, and\n"
    .string "MOLTRES.\p"
    .string "Their whereabouts are unknown.\p"
    .string "We plan to explore the cavern\n"
    .string "close to CERULEAN.\p"
    .string "From: POKéMON RESEARCH TEAM…$"
    .endif
    .ifdef SPANISH
    .string "¡Hay un correo electrónico!\p"
    .string "...\p"
    .string "Los 3 legendarios pájaros POKéMON\n"
    .string "son ARTICUNO, ZAPDOS y MOLTRES.\p"
    .string "Desconocemos sus guaridas.\p"
    .string "Pensamos explorar la cueva\n"
    .string "que hay cerca de la CELESTE.\p"
    .string "De: EQUIPO de INVESTIGACIÓN\n"
    .string "POKéMON...$"
    .endif

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
    .ifdef ENGLISH
    .string "An amber pipe!$"
    .endif
    .ifdef SPANISH
    .string "¡Un bote de ámbar!$"
    .endif

