Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou::
	.string "J'ai 6 POKé BALLS à ma ceinture.\p"
	.string "On ne peut transporter que 6\n"
	.string "POKéMON.$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean::
	.string "La TEAM ROCKET a encore attaqué\n"
	.string "les habitants d'AZURIA…\p"
	.string "Pas une journée sans qu'on\n"
	.string "parle d'eux.$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500::
	.string "Bonjour l'ami! J'ai une super\n"
	.string "affaire à te proposer!\p"
	.string "Je t'offre un MAGICARPE pour\n"
	.string "juste 500¥! Qu'en dis-tu?$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500::
	.string "Bonjour l'amie! J'ai une super\n"
	.string "affaire à te proposer!\p"
	.string "Je t'offre un MAGICARPE pour\n"
	.string "juste 500¥! Qu'en dis-tu?$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp::
	.string "{PLAYER} se fait avoir et achète\n"
	.string "le MAGICARPE…$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou::
	.string "Non? Allez!\n"
	.string "C'est un service que j'te rends!$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon::
	.string "Plus de place pour un POKéMON!$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney::
	.string "T'es à sec, c'est trop dommage!$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds::
	.string "Ni repris, ni échangé!$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC::
	.string "Tu devrais ranger tes POKéMON en\n"
	.string "trop en utilisant un PC!$"

Route4_PokemonCenter_1F_Text_ItsANewspaper::
	.string "C'est un journal.$"

