Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou::
    .ifdef ENGLISH
    .string "Okay, set six POKé BALLS in my\n"
    .string "belt…\p"
    .string "Yeah, that'll do it. At most, you\n"
    .string "can have six POKéMON with you.$"
    .endif
    .ifdef SPANISH
    .string "Tengo 6 POKé BALLS en mi cinturón.\p"
    .string "Puedes llevar 6 POKéMON como\n"
    .string "mucho.$"
    .endif

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean::
    .ifdef ENGLISH
    .string "TEAM ROCKET attacks CERULEAN\n"
    .string "citizens…\p"
    .string "Not a day goes by without TEAM\n"
    .string "ROCKET being in the news.$"
    .endif
    .ifdef SPANISH
    .string "El TEAM ROCKET ataca a los\n"
    .string "ciudadanos de CELESTE...\p"
    .string "¡El TEAM ROCKET siempre sale\n"
    .string "en las noticias!$"
    .endif

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500::
    .ifdef ENGLISH
    .string "MAN: Hello there, laddie!\n"
    .string "Have I got a deal just for you!\p"
    .string "I'll let you have a secret POKéMON\n"
    .string "- a MAGIKARP - for just ¥500!\p"
    .string "So, you'll buy it, am I right?$"
    .endif
    .ifdef SPANISH
    .string "HOMBRE: ¡Hola, majo!\n"
    .string "¡Tengo una oferta sólo para ti!\p"
    .string "¡Te daré un MAGIKARP por 500?\n"
    .string "de nada!\p"
    .string "¿Qué dices?$"
    .endif

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500::
    .ifdef ENGLISH
    .string "MAN: Hello there, sweetie pie!\n"
    .string "Have I got a deal just for you!\p"
    .string "I'll let you have a secret POKéMON\n"
    .string "- a MAGIKARP - for just ¥500!\p"
    .string "So, you'll buy it, am I right?$"
    .endif
    .ifdef SPANISH
    .string "HOMBRE: ¡Hola, maja!\n"
    .string "¡Tengo una oferta sólo para ti!\p"
    .string "¡Te daré un MAGIKARP por 500?\n"
    .string "de nada!\p"
    .string "¿Qué dices?$"
    .endif

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp::
    .ifdef ENGLISH
    .string "{PLAYER} paid an outrageous ¥500\n"
    .string "and bought the MAGIKARP…$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} pagó la cantidad de 500?\n"
    .string "y compró el MAGIKARP...$"
    .endif

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou::
    .ifdef ENGLISH
    .string "No? You say no? I'm only doing this\n"
    .string "as a favor to you!$"
    .endif
    .ifdef SPANISH
    .string "¿No? ¡Pues lo hacía como favor!$"
    .endif

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon::
    .ifdef ENGLISH
    .string "There's no more room for any more\n"
    .string "POKéMON, it looks like.$"
    .endif
    .ifdef SPANISH
    .string "Mmmm... Tienes demasiados POKéMON.\n"
    .string "No queda sitio para éste...$"
    .endif

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney::
    .ifdef ENGLISH
    .string "You'll need more money than that!$"
    .endif
    .ifdef SPANISH
    .string "¡No tienes suficiente dinero!$"
    .endif

Route4_PokemonCenter_1F_Text_IDontGiveRefunds::
    .ifdef ENGLISH
    .string "MAN: Well, I don't give refunds.\n"
    .string "You knew what you were getting!$"
    .endif
    .ifdef SPANISH
    .string "HOMBRE: ¡Que sepas que no acepto\n"
    .string "devoluciones!$"
    .endif

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC::
    .ifdef ENGLISH
    .string "Sometimes, you'll have too many\n"
    .string "POKéMON with you to add any more.\p"
    .string "In that case, you should just\n"
    .string "store some using any PC.$"
    .endif
    .ifdef SPANISH
    .string "¡Si tienes demasiados POKéMON,\n"
    .string "guárdalos en el PC!$"
    .endif

Route4_PokemonCenter_1F_Text_ItsANewspaper::
    .ifdef ENGLISH
    .string "It's a newspaper.$"
    .endif
    .ifdef SPANISH
    .string "Un periódico...$"
    .endif

