PokemonLeague_BrunosRoom_Text_Intro::
    .string "Sono BRUNO dei SUPERQUATTRO!\p"
    .string "Con un rigoroso allenamento, le\n"
    .string "persone e i POKéMON possono\l"
    .string "rafforzarsi!\p"
    .string "Nella mia vita, ho sempre allenato\n"
    .string "POKéMON di tipo LOTTA!\p"
    .string "{PLAYER}!\p"
    .string "Ti annienteremo con la nostra\n"
    .string "forza sovrumana!\p"
    .string "Ahahah!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_RematchIntro::
    .string "Sono BRUNO dei SUPERQUATTRO!\p"
    .string "Con un rigoroso allenamento, le\n"
    .string "persone e i POKéMON possono\l"
    .string "rafforzarsi!\p"
    .string "Nella mia vita, ho sempre allenato\n"
    .string "POKéMON di tipo LOTTA!\p"
    .string "{PLAYER}!\p"
    .string "Ti annienteremo con la nostra\n"
    .string "forza sovrumana!\p"
    .string "Ahahah!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_Defeat::
    .string "Come?\n"
    .string "Ho perso davvero?!$"

PokemonLeague_BrunosRoom_Text_PostBattle::
    .string "Il mio compito è finito! Vai!\n"
    .string "Un'altra sfida ti sta aspettando!$"

