PokemonLeague_BrunosRoom_Text_Intro::
    .ifdef ENGLISH
    .string "I am BRUNO of the ELITE FOUR!\p"
    .string "Through rigorous training, people\n"
    .string "and POKéMON can become stronger\l"
    .string "without limit.\p"
    .string "I've lived and trained with my\n"
    .string "fighting POKéMON!\l"
    .string "And that will never change!\p"
    .string "{PLAYER}!\p"
    .string "We will grind you down with our\n"
    .string "superior power!\p"
    .string "Hoo hah!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif
    .ifdef SPANISH
    .string "¡Yo soy BRUNO, del ALTO MANDO!\p"
    .string "¡Con un riguroso entrenamiento,\n"
    .string "la gente y los POKéMON pueden\l"
    .string "fortalecerse!\p"
    .string "¡Siempre he vivido con mis POKéMON\n"
    .string "del tipo LUCHA y los he entrenado\l"
    .string "yo mismo!\p"
    .string "¡{PLAYER}!\p"
    .string "¡Os machacaremos con nuestra\n"
    .string "gran fuerza!\p"
    .string "¡Ja, ja, ja!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif

PokemonLeague_BrunosRoom_Text_RematchIntro::
    .ifdef ENGLISH
    .string "I am BRUNO of the ELITE FOUR!\p"
    .string "Through rigorous training, people\n"
    .string "and POKéMON can become stronger\l"
    .string "without limit.\p"
    .string "I've lived and trained with my\n"
    .string "fighting POKéMON!\l"
    .string "And that will never change!\p"
    .string "{PLAYER}!\p"
    .string "We will grind you down with our\n"
    .string "superior power!\p"
    .string "Hoo hah!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif
    .ifdef SPANISH
    .string "¡Yo soy BRUNO, del ALTO MANDO!\p"
    .string "¡Con un riguroso entrenamiento,\n"
    .string "la gente y los POKéMON pueden\l"
    .string "fortalecerse!\p"
    .string "¡Siempre he vivido con mis POKéMON\n"
    .string "del tipo LUCHA y los he entrenado\l"
    .string "yo mismo!\p"
    .string "¡{PLAYER}!\p"
    .string "¡Os machacaremos con nuestra\n"
    .string "gran fuerza!\p"
    .string "¡Ja, ja, ja!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif

PokemonLeague_BrunosRoom_Text_Defeat::
    .ifdef ENGLISH
    .string "Why?\n"
    .string "How could I lose?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué?\n¿Cómo he podido perder?$"
    .endif

PokemonLeague_BrunosRoom_Text_PostBattle::
    .ifdef ENGLISH
    .string "My job is done.\n"
    .string "Go face your next challenge.$"
    .endif
    .ifdef SPANISH
    .string "¡Yo ya he hecho mi trabajo!\n"
    .string "¡Te espera tu próximo desafío!$"
    .endif

