PokemonLeague_BrunosRoom_Text_Intro::
	.string "Ich gehöre zu den TOP VIER!\n"
	.string "Mein Name ist BRUNO!\p"
	.string "Durch ausgiebiges Training können\n"
	.string "POKéMON sehr stark werden!\p"
	.string "Ich habe meine POKéMON pausenlos\n"
	.string "trainiert!\p"
	.string "{PLAYER}!\p"
	.string "Wir werden dich mit unserer Kraft\n"
	.string "bezwingen!\p"
	.string "Zum Angriff!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_RematchIntro::
	.string "Ich gehöre zu den TOP VIER!\n"
	.string "Mein Name ist BRUNO!\p"
	.string "Durch ausgiebiges Training können\n"
	.string "POKéMON sehr stark werden!\p"
	.string "Ich habe meine POKéMON pausenlos\n"
	.string "trainiert!\p"
	.string "{PLAYER}!\p"
	.string "Wir werden dich mit unserer Kraft\n"
	.string "bezwingen!\p"
	.string "Zum Angriff!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_BrunosRoom_Text_Defeat::
	.string "Wie konnte ich verlieren?$"

PokemonLeague_BrunosRoom_Text_PostBattle::
	.string "Ich bin erledigt! Doch die nächste\n"
	.string "Herausforderung wartet bereits...$"

