SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
    .string "CAPITÁN: ¡Puajj!\n"
    .string "Me siento fatal.\l"
    .string "Me he mareado...$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
    .string "¡{PLAYER} le dio un masaje\n"
    .string "al CAPITÁN!\p"
    .string "(Scratch)...\n"
    .string "(Scratch)...$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
    .string "CAPITÁN: ¡Uff! ¡Gracias!\n"
    .string "Ya me siento mucho mejor...\p"
    .string "¿Quieres ver mi técnica de CORTAR?\p"
    .string "Te la mostraría si no estuviera\n"
    .string "tan mareado.\p"
    .string "¡Ya sé!\n"
    .string "¡Toma esto!\p"
    .string "¡Enséñasela a tu POKéMON\n"
    .string "y en breve estará CORTANDO!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .string "¡{PLAYER} obtuvo la MO01\n"
    .string "de manos del CAPITÁN!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
    .string "Al usar CORTE, se pueden talar\n"
    .string "árboles pequeños.\p"
    .string "A lo mejor deberías probarlo con\n"
    .string "los árboles de CIUDAD CARMÍN.$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .string "CAPITÁN: ¡Bien!\p"
    .string "¡Ahora que ya no estoy mareado,\n"
    .string "creo que deberíamos irnos!\p"
    .string "¡El S.S. ANNE zarpará pronto!\p"
    .string "¡Adiós, hasta que volvamos\n"
    .string "a CIUDAD CARMÍN!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
    .string "¡Oh, no!\n"
    .string "¡No tienes sitio para esto!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .string "¡Puaj!\n"
    .string "¡No debería haber mirado!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
    .string "Cómo combatir el mareo...\n"
    .string "¡El CAPITÁN está leyendo esto!$"
