SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
	.string "KAPITÄN: Urps...\n"
	.string "Es geht mir gar nicht gut! Urps!$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
	.string "{PLAYER} massiert dem KAPITÄN den\n"
	.string "Rücken!\p"
	.string "Rubbel...\n"
	.string "Schrubb...$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
	.string "KAPITÄN: Ahhhhh! Ich danke dir!\n"
	.string "Es geht mir schon viel besser...\p"
	.string "Möchtest du den Umgang mit dem\n"
	.string "ZERSCHNEIDER lernen?\p"
	.string "Ich könnte es dir beibringen, aber\n"
	.string "mir ist so übel.\p"
	.string "Genau! Nimm einfach das hier!\p"
	.string "Damit bringst du deinen POKéMON\n"
	.string "den Umgang mit dem ZERSCHNEIDER\l"
	.string "ganz leicht bei!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
	.string "{PLAYER} erhält\n"
	.string "VM01.$"

SSAnne_CaptainsOffice_Text_ExplainCut::
	.string "Wenn du den ZERSCHNEIDER einsetzt,\n"
	.string "kannst du kleine Bäume fällen.\p"
	.string "Probiere es doch bei den Bäumen\n"
	.string "um ORANIA CITY aus!$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
	.string "KAPITÄN: Super!\p"
	.string "Endlich bin ich nicht mehr krank!\n"
	.string "Es kann losgehen!\p"
	.string "Jetzt kann die M.S. ANNE in See\n"
	.string "stechen!\p"
	.string "Auf Wiedersehen! Bis zum nächsten\n"
	.string "Besuch in ORANIA CITY!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
	.string "Oh, nein! Du hast keinen Platz für\n"
	.string "weitere Items!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
	.string "Buäh! Manche Dinge macht man\n"
	.string "besser nicht...$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
	.string "1000 natürliche Hausmittel gegen\n"
	.string "Seekrankheit...\l"
	.string "Der KAPITÄN liest dieses Buch!$"

