SixIsland_House_Text_GoodPlaceForNatureAndHistory::
    .ifdef ENGLISH
    .string "There's nothing that young people'd\n"
    .string "find exciting here on this island.\p"
    .string "But, this is a good place in terms\n"
    .string "of nature and history.\p"
    .string "Relax and enjoy your stay.$"
    .endif
    .ifdef SPANISH
    .string "Aquí la gente joven no encuentra\n"
    .string "nada de su interés.\p"
    .string "Pero éste es un lugar único por la\n"
    .string "naturaleza y la historia que tiene.\p"
    .string "Relájate y disfruta de la estancia.$"
    .endif

