PalletTown_RivalsHouse_Text_HiBrothersAtLab::
    .ifdef ENGLISH
    .string "DAISY: Hi, {PLAYER}!\p"
    .string "My brother, {RIVAL}, is out at\n"
    .string "Grandpa's LAB.$"
    .endif
    .ifdef SPANISH
    .string "DALIA: ¡Hola, {PLAYER}!\p"
    .string "¡{RIVAL} está en el laboratorio\n"
    .string "del abuelo!$"
    .endif

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
    .ifdef ENGLISH
    .string "DAISY: {PLAYER}, I heard you had\n"
    .string "a battle against {RIVAL}.\p"
    .string "I wish I'd seen that!$"
    .endif
    .ifdef SPANISH
    .string "DALIA: {PLAYER}, he oído que has\n"
    .string "luchado contra {RIVAL}.\p"
    .string "¡Me hubiera encantado estar ahí!$"
    .endif

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
    .ifdef ENGLISH
    .string "Grandpa asked you to run an\n"
    .string "errand?\p"
    .string "Gee, that's lazy of him.\n"
    .string "Here, this will help you.$"
    .endif
    .ifdef SPANISH
    .string "¿Te encargó algo el abuelo?\p"
    .string "¡Toma esto!\n"
    .string "¡Te ayudará!$"
    .endif

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
    .ifdef ENGLISH
    .string "{PLAYER} received a TOWN MAP\n"
    .string "from DAISY.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió el MAPA\n"
    .string "de manos de DALIA!$"
    .endif

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
    .ifdef ENGLISH
    .string "You don't have space for this in\n"
    .string "your BAG.$"
    .endif
    .ifdef SPANISH
    .string "Llevas demasiadas cosas\n"
    .string "en la MOCHILA.$"
    .endif

PalletTown_RivalsHouse_Text_ExplainTownMap::
    .ifdef ENGLISH
    .string "You can use the TOWN MAP to find\n"
    .string "out where you are, or check the\l"
    .string "names of places.$"
    .endif
    .ifdef SPANISH
    .string "Usa el MAPA para saber dónde\n"
    .string "te encuentras.$"
    .endif

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
    .ifdef ENGLISH
    .string "DAISY: Just like people, POKéMON\n"
    .string "are living things.\p"
    .string "When they get tired, please give\n"
    .string "them a rest.$"
    .endif
    .ifdef SPANISH
    .string "DALIA: Los POKéMON son seres que\n"
    .string "sienten, igual que las personas.\p"
    .string "Cuando se cansen, deberás dejar\n"
    .string "que se recuperen.$"
    .endif

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
    .ifdef ENGLISH
    .string "It's a big map of the KANTO region.\n"
    .string "Now this would be useful!$"
    .endif
    .ifdef SPANISH
    .string "¡Es un gran mapa de KANTO!\n"
    .string "¡Qué útil!$"
    .endif

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
    .ifdef ENGLISH
    .string "The shelves are crammed full of\n"
    .string "books on POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Está totalmente llena de libros\n"
    .string "sobre los POKéMON!$"
    .endif

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
    .ifdef ENGLISH
    .string "DAISY: Hi, {PLAYER}!\n"
    .string "Good timing.\p"
    .string "I'm about to have some tea.\n"
    .string "Would you like to join me?\p"
    .string "Oh, but look.\n"
    .string "Your POKéMON are a little dirty.\p"
    .string "Would you like me to groom one?$"
    .endif
    .ifdef SPANISH
    .string "DALIA: ¡Hola, {PLAYER}!\n"
    .string "¡Llegas a tiempo!\p"
    .string "Iba a tomarme un té.\n"
    .string "¿Quieres uno?\p"
    .string "Tus POKéMON están un poco sucios.\n"
    .string "¿Quieres que limpie a alguno?$"
    .endif

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
    .ifdef ENGLISH
    .string "You don't need any grooming done?\n"
    .string "Okay, we'll just have tea.$"
    .endif
    .ifdef SPANISH
    .string "¿No quieres que limpie a ningún\n"
    .string "POKéMON?\l"
    .string "Bueno, vamos a tomarnos el té.$"
    .endif

PalletTown_RivalsHouse_Text_GroomWhichOne::
    .ifdef ENGLISH
    .string "Which one should I groom?$"
    .endif
    .ifdef SPANISH
    .string "¿A qué POKéMON limpio?$"
    .endif

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
    .ifdef ENGLISH
    .string "DAISY: Okay, I'll get it looking\n"
    .string "nice in no time.$"
    .endif
    .ifdef SPANISH
    .string "DALIA: Vale, verás lo mono\n"
    .string "que se queda.$"
    .endif

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
    .ifdef ENGLISH
    .string "{FONT_NORMAL}{STR_VAR_1} looks dreamily content…\p"
    .string "{FONT_FEMALE}DAISY: There you go! All done.\n"
    .string "See? Doesn't it look nice?\p"
    .string "Giggle…\n"
    .string "It's such a cute POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "{FONT_NORMAL}{STR_VAR_1} parece encantado.\p"
    .string "{PALETTE 5}DALIA: ¡Ya está! ¡Listo!\n"
    .string "¿Qué? ¿Tiene buen aspecto o no?\p"
    .string "¡Qué POKéMON más mono!$"
    .endif

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
    .ifdef ENGLISH
    .string "Oh, sorry. I honestly can't\n"
    .string "groom an EGG.$"
    .endif
    .ifdef SPANISH
    .string "Lo siento, yo no sé limpiar HUEVOS.$"
    .endif

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
    .ifdef ENGLISH
    .string "DAISY: Your POKéMON grow to love\n"
    .string "you if you raise them with love.\p"
    .string "For example, {PLAYER}, may I see\n"
    .string "your first POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "DALIA: Si crías a tus POKéMON\n"
    .string "con cariño, te querrán mucho.\p"
    .string "{PLAYER}, ¿me dejas ver a tu primer\n"
    .string "POKéMON?$"
    .endif

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
    .ifdef ENGLISH
    .string "It couldn't possibly love you\n"
    .string "any more than it does now.\p"
    .string "Your POKéMON is happy beyond\n"
    .string "words.$"
    .endif
    .ifdef SPANISH
    .string "Desde luego, no podría quererte\n"
    .string "más.\p"
    .string "¡No hay palabras para expresar\n"
    .string "lo mucho que se ve que te quiere!$"
    .endif

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
    .ifdef ENGLISH
    .string "It looks very happy.\p"
    .string "I wish {RIVAL} could see this and\n"
    .string "learn something from it.$"
    .endif
    .ifdef SPANISH
    .string "Se le ve muy feliz.\p"
    .string "Ojalá {RIVAL} pudiera verlo y\n"
    .string "aprender cómo se hacen las cosas.$"
    .endif

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
    .ifdef ENGLISH
    .string "It's quite friendly with you.\n"
    .string "Keep being good to it!$"
    .endif
    .ifdef SPANISH
    .string "Se ve que se lleva muy bien\n"
    .string "contigo. ¡Que no decaiga!$"
    .endif

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
    .ifdef ENGLISH
    .string "It's warming up to you.\n"
    .string "Trust must be growing between you.$"
    .endif
    .ifdef SPANISH
    .string "Se ve que te está tomando\n"
    .string "cariño. Debes darle confianza.$"
    .endif

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
    .ifdef ENGLISH
    .string "It's not quite familiar with you\n"
    .string "yet.\p"
    .string "POKéMON are all quite wary when\n"
    .string "you first get them.$"
    .endif
    .ifdef SPANISH
    .string "No se ha adaptado del todo a ti.\p"
    .string "Los POKéMON son muy recelosos\n"
    .string "cuando los atrapas. Dale tiempo.$"
    .endif

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
    .ifdef ENGLISH
    .string "{PLAYER}, I don't like the way it\n"
    .string "glares at you.\p"
    .string "Could you try being a little nicer\n"
    .string "to it?$"
    .endif
    .ifdef SPANISH
    .string "Oye, {PLAYER}, no me gusta nada\n"
    .string "cómo te mira...\p"
    .string "Deberías ser más amable.$"
    .endif

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
    .ifdef ENGLISH
    .string "…Um, it's not easy for me to say\n"
    .string "this, but…\p"
    .string "Is there some reason why your\n"
    .string "POKéMON would hate you so much?$"
    .endif
    .ifdef SPANISH
    .string "Eh... siento decírtelo, pero...\p"
    .string "¿Qué has hecho para que te tenga\n"
    .string "tanta tirria?$"
    .endif

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
    .ifdef ENGLISH
    .string "“The lovely and sweet\n"
    .string "CLEFAIRY”$"
    .endif
    .ifdef SPANISH
    .string "El cariñoso y dulce\n"
    .string "CLEFAIRY.$"
    .endif

