PalletTown_RivalsHouse_Text_HiBrothersAtLab::
	.string "NINA: Salut {PLAYER}!\p"
	.string "{RIVAL} est dans le labo de pépé!$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
	.string "NINA: {PLAYER}, il paraît que tu as\n"
	.string "combattu {RIVAL}.\p"
	.string "J'aurais aimé voir ça!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
	.string "Tu pars explorer la région\n"
	.string "pour pépé?\p"
	.string "Prends ceci, ça peut servir!$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
	.string "{PLAYER} reçoit la\n"
	.string "CARTE!$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
	.string "Ton inventaire est plein.$"

PalletTown_RivalsHouse_Text_ExplainTownMap::
	.string "Utilise la CARTE pour connaître ta\n"
	.string "position.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
	.string "NINA: Comme les gens, les POKéMON\n"
	.string "sont des êtres vivants.\p"
	.string "Ils doivent aussi se reposer quand\n"
	.string "ils sont fatigués.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
	.string "C'est une carte!\n"
	.string "Ça peut être utile!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
	.string "Des bouquins sur les POKéMON!$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
	.string "NINA: Salut! Ça tombe bien,\n"
	.string "j'allais faire du thé. En veux-tu?\p"
	.string "Oh, tes POKéMON sont sales.\n"
	.string "Tu veux que j'en bichonne un?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
	.string "NINA: Tu ne veux pas que je m'en\n"
	.string "occupe?\l"
	.string "OK. Un peu de thé, alors…$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
	.string "NINA: Lequel dois-je bichonner?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
	.string "NINA: OK, je vais le faire beau en\n"
	.string "deux secondes.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
#ifdef BUGFIX @ The localizers missed what should be a textcolor change in the localizations.
	.string "{COLOR DARK_GRAY}{STR_VAR_1} a l'air heureux.\p"
	.string "{COLOR RED}NINA: Voilààà! C'est fini!\n"
#else @ In the JP games, gender-based text used a different font instead of different colors.
	.string "{FONT_NORMAL}{STR_VAR_1} a l'air heureux.\p"
	.string "NINA: Voilààà! C'est fini!\n"
#endif
	.string "Alors? Il est beau, hein?\p"
	.string "Un joli petit POKéMON.$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
	.string "NINA: Oh, désolée. Je ne peux pas\n"
	.string "m'occuper d'un OEUF.$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
	.string "NINA: Tes POKéMON te le rendront\n"
	.string "bien si tu les élèves avec amour.\p"
	.string "Par exemple, {PLAYER}, je peux\n"
	.string "voir ton premier POKéMON?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
	.string "Il ne pourrait pas t'aimer plus\n"
	.string "que maintenant.\p"
	.string "Ton POKéMON est vraiment\n"
	.string "heureux avec toi.$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
	.string "Il a l'air heureux.\p"
	.string "Si seulement {RIVAL} pouvait voir\n"
	.string "ça et en tirer des leçons.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
	.string "Il t'aime bien. Continue\n"
	.string "comme ça!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
	.string "Il commence à s'attacher à toi.\p"
	.string "La confiance va s'instaurer entre\n"
	.string "vous deux.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
	.string "Il n'est pas encore habitué à toi.\p"
	.string "Les POKéMON sont toujours\n"
	.string "un peu craintifs au début.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
	.string "{PLAYER}, je n'aime pas beaucoup\n"
	.string "la façon dont il te regarde.\p"
	.string "Tu devrais être un peu plus\n"
	.string "sympa avec.$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
	.string "… Ça me fait mal au cœur\n"
	.string "de dire ça, mais…\p"
	.string "Y'a-t-il une raison pour laquelle\n"
	.string "il te déteste tant?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
	.string "Le gentil et adorable MELOFEE.$"

