PalletTown_RivalsHouse_Text_HiBrothersAtLab::
    .string "DALIA: ¡Hola, {PLAYER}!\p"
    .string "¡{RIVAL} está en el laboratorio\n"
    .string "del abuelo!$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
    .string "DALIA: {PLAYER}, he oído que has\n"
    .string "luchado contra {RIVAL}.\p"
    .string "¡Me hubiera encantado estar ahí!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
    .string "¿Te encargó algo el abuelo?\p"
    .string "¡Toma esto!\n"
    .string "¡Te ayudará!$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
    .string "¡{PLAYER} recibió el MAPA\n"
    .string "de manos de DALIA!$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
    .string "Llevas demasiadas cosas\n"
    .string "en la MOCHILA.$"

PalletTown_RivalsHouse_Text_ExplainTownMap::
    .string "Usa el MAPA para saber dónde\n"
    .string "te encuentras.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
    .string "DALIA: Los POKéMON son seres que\n"
    .string "sienten, igual que las personas.\p"
    .string "Cuando se cansen, deberás dejar\n"
    .string "que se recuperen.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
    .string "¡Es un gran mapa de KANTO!\n"
    .string "¡Qué útil!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
    .string "¡Está totalmente llena de libros\n"
    .string "sobre los POKéMON!$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
    .string "DALIA: ¡Hola, {PLAYER}!\n"
    .string "¡Llegas a tiempo!\p"
    .string "Iba a tomarme un té.\n"
    .string "¿Quieres uno?\p"
    .string "Tus POKéMON están un poco sucios.\n"
    .string "¿Quieres que limpie a alguno?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
    .string "¿No quieres que limpie a ningún\n"
    .string "POKéMON?\l"
    .string "Bueno, vamos a tomarnos el té.$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
    .string "¿A qué POKéMON limpio?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
    .string "DALIA: Vale, verás lo mono\n"
    .string "que se queda.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::

    #ifdef BUGFIX
    .string "{COLOR DARK_GRAY}{STR_VAR_1} parece encantado.\p"
    .string "{COLOR RED}DALIA: ¡Ya está! ¡Listo!\n"
    #else
    .string "{FONT_NORMAL}{STR_VAR_1} parece encantado.\p"
    .string "{FONT_FEMALE}DALIA: ¡Ya está! ¡Listo!\n"
    .string "¿Qué? ¿Tiene buen aspecto o no?\p"
    .string "¡Qué POKéMON más mono!$"
    #endif

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
    .string "Lo siento, yo no sé limpiar HUEVOS.$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
    .string "DALIA: Si crías a tus POKéMON\n"
    .string "con cariño, te querrán mucho.\p"
    .string "{PLAYER}, ¿me dejas ver a tu primer\n"
    .string "POKéMON?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
    .string "Desde luego, no podría quererte\n"
    .string "más.\p"
    .string "¡No hay palabras para expresar\n"
    .string "lo mucho que se ve que te quiere!$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
    .string "Se le ve muy feliz.\p"
    .string "Ojalá {RIVAL} pudiera verlo y\n"
    .string "aprender cómo se hacen las cosas.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
    .string "Se ve que se lleva muy bien\n"
    .string "contigo. ¡Que no decaiga!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
    .string "Se ve que te está tomando\n"
    .string "cariño. Debes darle confianza.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
    .string "No se ha adaptado del todo a ti.\p"
    .string "Los POKéMON son muy recelosos\n"
    .string "cuando los atrapas. Dale tiempo.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
    .string "Oye, {PLAYER}, no me gusta nada\n"
    .string "cómo te mira...\p"
    .string "Deberías ser más amable.$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
    .string "Eh... siento decírtelo, pero...\p"
    .string "¿Qué has hecho para que te tenga\n"
    .string "tanta tirria?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
    .string "El cariñoso y dulce\n"
    .string "CLEFAIRY.$"
