SilphCo_8F_Text_WonderIfSilphIsFinished::
	.string "Ob die SILPH CO. schon erledigt\n"
	.string "ist?$"

SilphCo_8F_Text_ThanksForSavingUs::
	.string "Vielen Dank für unsere Rettung!$"

SilphCo_8F_Text_Grunt1Intro::
	.string "Endstation!\n"
	.string "Bis hierher und nicht weiter!$"

SilphCo_8F_Text_Grunt1Defeat::
	.string "Mist, der Mut hat mich verlassen!$"

SilphCo_8F_Text_Grunt1PostBattle::
	.string "Hau lieber ab, sonst rufe ich\n"
	.string "Verstärkung!$"

SilphCo_8F_Text_ParkerIntro::
	.string "Du bereitest uns nichts als Ärger!$"

SilphCo_8F_Text_ParkerDefeat::
	.string "Huch!\n"
	.string "Verloren?$"

SilphCo_8F_Text_ParkerPostBattle::
	.string "Das SILPH CO.-Gebäude ist ein\n"
	.string "wahres Labyrinth, nicht wahr?$"

SilphCo_8F_Text_Grunt2Intro::
	.string "Ich bin einer der vier berüchtigten\n"
	.string "ROCKET-BRÜDER!$"

SilphCo_8F_Text_Grunt2Defeat::
	.string "Ups!\n"
	.string "Brüder, ich habe versagt!$"

SilphCo_8F_Text_Grunt2PostBattle::
	.string "Dann werden sich meine Brüder um\n"
	.string "dich kümmern!$"

SilphCo_8F_Text_FloorSign::
	.string "SILPH CO. HAUPTSITZ\n"
	.string "7 OG$"

SilphCo_8F_Text_ToRocketBossMonsAreTools::
	.string "Der BOSS von TEAM ROCKET ist\n"
	.string "unheimlich grausam!\p"
	.string "Für ihn sind POKéMON schlicht\n"
	.string "Mittel zum Zweck.\p"
	.string "Was wird geschehen, wenn dieser\n"
	.string "Tyrann unsere Firma übernimmt…$"

