SilphCo_8F_Text_WonderIfSilphIsFinished::
    .ifdef ENGLISH
    .string "I wonder if SILPH is finished…$"
    .endif
    .ifdef SPANISH
    .string "Me pregunto si SILPH estará\n"
    .string "acabada.$"
    .endif

SilphCo_8F_Text_ThanksForSavingUs::
    .ifdef ENGLISH
    .string "Thanks for saving us!$"
    .endif
    .ifdef SPANISH
    .string "¡Gracias por salvarnos!$"
    .endif

SilphCo_8F_Text_Grunt1Intro::
    .ifdef ENGLISH
    .string "That's as far as you'll go!$"
    .endif
    .ifdef SPANISH
    .string "¡No podrás ir más lejos!$"
    .endif

SilphCo_8F_Text_Grunt1Defeat::
    .ifdef ENGLISH
    .string "Not enough grit!$"
    .endif
    .ifdef SPANISH
    .string "¡No eres tan valiente!$"
    .endif

SilphCo_8F_Text_Grunt1PostBattle::
    .ifdef ENGLISH
    .string "If you don't turn back…\n"
    .string "I'll call for backup!$"
    .endif
    .ifdef SPANISH
    .string "¡Si no retrocedes, pediré\n"
    .string "refuerzos!$"
    .endif

SilphCo_8F_Text_ParkerIntro::
    .ifdef ENGLISH
    .string "You're causing us problems!$"
    .endif
    .ifdef SPANISH
    .string "¡Nos estás dando muchos problemas!$"
    .endif

SilphCo_8F_Text_ParkerDefeat::
    .ifdef ENGLISH
    .string "Huh?\n"
    .string "I lost?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué?\n"
    .string "¿He perdido?$"
    .endif

SilphCo_8F_Text_ParkerPostBattle::
    .ifdef ENGLISH
    .string "So, what do you think of SILPH\n"
    .string "BUILDING's maze?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué opinas del laberinto del\n"
    .string "EDIFICIO SILPH?$"
    .endif

SilphCo_8F_Text_Grunt2Intro::
    .ifdef ENGLISH
    .string "I am one of the four ROCKET\n"
    .string "BROTHERS!$"
    .endif
    .ifdef SPANISH
    .string "¡Soy uno de los 4\n"
    .string "HERMANOS ROCKET!$"
    .endif

SilphCo_8F_Text_Grunt2Defeat::
    .ifdef ENGLISH
    .string "Whoo!\n"
    .string "Oh, Brothers!$"
    .endif
    .ifdef SPANISH
    .string "¡Ahhhg!\n"
    .string "¡Hermanos! ¡Tenéis que vengarme!$"
    .endif

SilphCo_8F_Text_Grunt2PostBattle::
    .ifdef ENGLISH
    .string "I'll leave you up to my brothers.$"
    .endif
    .ifdef SPANISH
    .string "¡Mis hermanos se encargarán de ti!$"
    .endif

SilphCo_8F_Text_FloorSign::
    .ifdef ENGLISH
    .string "SILPH CO. HEAD OFFICE\n"
    .string "8F$"
    .endif
    .ifdef SPANISH
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P7$"
    .endif

SilphCo_8F_Text_ToRocketBossMonsAreTools::
    .ifdef ENGLISH
    .string "TEAM ROCKET's BOSS is terribly\n"
    .string "cruel!\p"
    .string "To him, POKéMON are just tools to\n"
    .string "be used.\p"
    .string "What will happen if that tyrant\n"
    .string "takes over our company…$"
    .endif
    .ifdef SPANISH
    .string "¡El JEFE del TEAM ROCKET es muy\n"
    .string "cruel!\p"
    .string "Sólo quiere a los POKéMON para\n"
    .string "luchar.\p"
    .string "No quiero ni pensar lo que podría\n"
    .string "ocurrir si se hiciera con el mando\l"
    .string "de la compañía...$"
    .endif
