SilphCo_8F_Text_WonderIfSilphIsFinished::
    .string "Me pregunto si SILPH estará\n"
    .string "acabada.$"

SilphCo_8F_Text_ThanksForSavingUs::
    .string "¡Gracias por salvarnos!$"

SilphCo_8F_Text_Grunt1Intro::
    .string "¡No podrás ir más lejos!$"

SilphCo_8F_Text_Grunt1Defeat::
    .string "¡No eres tan valiente!$"

SilphCo_8F_Text_Grunt1PostBattle::
    .string "¡Si no retrocedes, pediré\n"
    .string "refuerzos!$"

SilphCo_8F_Text_ParkerIntro::
    .string "¡Nos estás dando muchos problemas!$"

SilphCo_8F_Text_ParkerDefeat::
    .string "¿Qué?\n"
    .string "¿He perdido?$"

SilphCo_8F_Text_ParkerPostBattle::
    .string "¿Qué opinas del laberinto del\n"
    .string "EDIFICIO SILPH?$"

SilphCo_8F_Text_Grunt2Intro::
    .string "¡Soy uno de los 4\n"
    .string "HERMANOS ROCKET!$"

SilphCo_8F_Text_Grunt2Defeat::
    .string "¡Ahhhg!\n"
    .string "¡Hermanos! ¡Tenéis que vengarme!$"

SilphCo_8F_Text_Grunt2PostBattle::
    .string "¡Mis hermanos se encargarán de ti!$"

SilphCo_8F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P7$"

SilphCo_8F_Text_ToRocketBossMonsAreTools::
    .string "¡El JEFE del TEAM ROCKET es muy\n"
    .string "cruel!\p"
    .string "Sólo quiere a los POKéMON para\n"
    .string "luchar.\p"
    .string "No quiero ni pensar lo que podría\n"
    .string "ocurrir si se hiciera con el mando\l"
    .string "de la compañía...$"
