SilphCo_8F_Text_WonderIfSilphIsFinished::
	.string "Mmm… La SYLPHE va-t-elle faire\n"
	.string "faillite?$"

SilphCo_8F_Text_ThanksForSavingUs::
	.string "Merci de nous avoir sauvés!$"

SilphCo_8F_Text_Grunt1Intro::
	.string "Hop hop hop!\n"
	.string "On ne bouge plus!$"

SilphCo_8F_Text_Grunt1Defeat::
	.string "Je suis faible!$"

SilphCo_8F_Text_Grunt1PostBattle::
	.string "Va-t-en ou j'appelle du renfort!$"

SilphCo_8F_Text_ParkerIntro::
	.string "Tu nous casses les pieds!$"

SilphCo_8F_Text_ParkerDefeat::
	.string "Heu?\n"
	.string "J'ai perdu?$"

SilphCo_8F_Text_ParkerPostBattle::
	.string "La SYLPHE est un vrai labyrinthe,\n"
	.string "hein?$"

SilphCo_8F_Text_Grunt2Intro::
	.string "Je suis l'un des 4 FRERES ROCKET!$"

SilphCo_8F_Text_Grunt2Defeat::
	.string "Whoo!\n"
	.string "Frèèèères!$"

SilphCo_8F_Text_Grunt2PostBattle::
	.string "Mes frères te dégommeront!$"

SilphCo_8F_Text_FloorSign::
	.string "SYLPHE SARL.\n"
	.string "7ème étage.$"

SilphCo_8F_Text_ToRocketBossMonsAreTools::
	.string "Le chef de la TEAM ROCKET est\n"
	.string "incroyablement cruel.\p"
	.string "Pour lui, les POKéMON ne sont que\n"
	.string "des outils.\p"
	.string "Qu'arrivera-t-il s'il arrive à\n"
	.string "s'emparer de notre compagnie?$"

