SSAnne_2F_Room4_Text_LamarIntro::
    .string "¿Qué prefieres, un POKéMON fuerte\n"
    .string "o uno raro?$"

SSAnne_2F_Room4_Text_LamarDefeat::
    .string "¡Debo felicitarte!$"

SSAnne_2F_Room4_Text_LamarPostBattle::
    .string "¡Prefiero los POKéMON fuertes\n"
    .string "y raros!$"

SSAnne_2F_Room4_Text_DawnIntro::
    .string "No te he visto en la fiesta.$"

SSAnne_2F_Room4_Text_DawnDefeat::
    .string "¡Oye!\n"
    .string "¡¡¡No había que ponerse así!!!$"

SSAnne_2F_Room4_Text_DawnPostBattle::
    .string "¡Oh!\n"
    .string "¡Adoro a tus fuertes POKéMON!$"
