SSAnne_2F_Room4_Text_LamarIntro::
	.string "Was magst du lieber?\n"
	.string "Starke oder seltene POKéMON?$"

SSAnne_2F_Room4_Text_LamarDefeat::
	.string "Ich ziehe meinen Hut vor dir! Wow!$"

SSAnne_2F_Room4_Text_LamarPostBattle::
	.string "Ich mag POKéMON, die stark und\n"
	.string "selten sind!$"

SSAnne_2F_Room4_Text_DawnIntro::
	.string "Wo warst du, als die Party lief?$"

SSAnne_2F_Room4_Text_DawnDefeat::
	.string "Mach langsam!!!$"

SSAnne_2F_Room4_Text_DawnPostBattle::
	.string "Ich bewundere die Stärke deiner\n"
	.string "POKéMON!$"

