SafariZone_East_Text_KeepAnyItemFoundOnSafari::
    .ifdef ENGLISH
    .string "You can keep any item you find in\n"
    .string "the SAFARI ZONE.\p"
    .string "But, you'll run out of time if you\n"
    .string "try for all of them at once.$"
    .endif
    .ifdef SPANISH
    .string "Puedes quedarte con cualquier\n"
    .string "objeto encontrado en esta zona.\p"
    .string "¡Pero te quedarás sin tiempo si\n"
    .string "intentas coger todos a la vez!$"
    .endif

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
    .ifdef ENGLISH
    .string "Go to the deepest part of the\n"
    .string "SAFARI ZONE. You will win a prize!$"
    .endif
    .ifdef SPANISH
    .string "Dirígete al ZONA más profunda del\n"
    .string "SAFARI. ¡Ganarás un premio!$"
    .endif

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
    .ifdef ENGLISH
    .string "My EEVEE evolved into FLAREON.\p"
    .string "But, a friend's EEVEE turned into a\n"
    .string "VAPOREON. I wonder why?$"
    .endif
    .ifdef SPANISH
    .string "¡Mi EEVEE evolucionó y\n"
    .string "se transformó en un FLAREON!\p"
    .string "¡Pero el EEVEE de un amigo se\n"
    .string "transformó en un VAPOREON!\l"
    .string "¿Por qué?$"
    .endif

