ThreeIsland_PokemonCenter_1F_Text_PCNetworkCanLinkWithKanto::
    .ifdef ENGLISH
    .string "Hey, did you hear the news?\p"
    .string "The PC network here can now link\n"
    .string "with PCs in KANTO.\p"
    .string "I don't know how that came about,\n"
    .string "but it's fantastic!$"
    .endif
    .ifdef SPANISH
    .string "Eh, ¿te has enterado?\p"
    .string "Ahora podemos estar en red\n"
    .string "con los PCs de KANTO.\p"
    .string "¡No sé quién lo habrá organizado,\n"
    .string "pero me parece una idea estupenda!$"
    .endif

ThreeIsland_PokemonCenter_1F_Text_ImpossibleToSurfBetweenIslands::
    .ifdef ENGLISH
    .string "It's impossible to SURF between the\n"
    .string "islands around these parts.\p"
    .string "The tides are too fast and\n"
    .string "treacherous.$"
    .endif
    .ifdef SPANISH
    .string "Es imposible hacer SURF\n"
    .string "entre las islas de esta zona.\p"
    .string "Hay corrientes y remolinos.$"
    .endif

ThreeIsland_PokemonCenter_1F_Text_AlwaysBerriesInBerryForest::
    .ifdef ENGLISH
    .string "Let's crush BERRIES!\n"
    .string "…That'd be wasting BERRIES?\p"
    .string "You can always find some BERRIES\n"
    .string "on the ground in BERRY FOREST.$"
    .endif
    .ifdef SPANISH
    .string "¡Vamos a MACHACAR BAYAS!\n"
    .string "¿Que sería un desperdicio de BAYAS\l"
    .string "dices?...\p"
    .string "¡Pero si el BOSQUE BAYA está hasta\n"
    .string "arriba!$"
    .endif

