ThreeIsland_PokemonCenter_1F_Text_PCNetworkCanLinkWithKanto::
	.string "Oh, t'es au courant?\p"
	.string "Notre réseau peut enfin se\n"
	.string "connecter aux PC DE KANTO.\p"
	.string "Je sais pas comment ils ont\n"
	.string "fait, mais la vache, c'est génial!$"

ThreeIsland_PokemonCenter_1F_Text_ImpossibleToSurfBetweenIslands::
	.string "Le SURF ne peut pas être pratiqué\n"
	.string "entre ces îles.\p"
	.string "Les courants sont beaucoup\n"
	.string "trop dangereux.$"

ThreeIsland_PokemonCenter_1F_Text_AlwaysBerriesInBerryForest::
	.string "Et si on broyait des BAIES?\p"
	.string "Il y en a tellement aux BOIS\n"
	.string "BAIES que ça serait pas du gâchis.$"

