ThreeIsland_PokemonCenter_1F_Text_PCNetworkCanLinkWithKanto::
	.string "Heh! Hast du schon gehört?\p"
	.string "Das PC-Netzwerk hier kann nun\n"
	.string "mit den PCs in KANTO verbunden\l"
	.string "werden.\l"
	.string "Ich weiß nicht, wie das zu Stande\l"
	.string "kam, aber es ist großartig!$"

ThreeIsland_PokemonCenter_1F_Text_ImpossibleToSurfBetweenIslands::
	.string "Es ist nicht möglich, zwischen den\n"
	.string "Inseln in dieser Gegend zu SURFen!\p"
	.string "Die Strömung ist zu stark und\n"
	.string "zu gefährlich!$"

ThreeIsland_PokemonCenter_1F_Text_AlwaysBerriesInBerryForest::
	.string "Lass uns BEEREN mahlen!\n"
	.string "… das wäre BEERENverschwendung?\p"
	.string "Im BEERENFORST kannst du stets\n"
	.string "BEEREN am Boden finden!$"

