OneIsland_KindleRoad_Text_MariaIntro::
    .ifdef ENGLISH
    .string "The weather's gorgeous!\n"
    .string "Perfect for a battle!$"
    .endif
    .ifdef SPANISH
    .string "¡Hace un día espléndido!\n"
    .string "¡El tiempo ideal para luchar!$"
    .endif

OneIsland_KindleRoad_Text_MariaDefeat::
    .ifdef ENGLISH
    .string "Aiyeeeeh!$"
    .endif
    .ifdef SPANISH
    .string "¡Ayyyyyy!$"
    .endif

OneIsland_KindleRoad_Text_MariaPostBattle::
    .ifdef ENGLISH
    .string "Please don't splash my face!\n"
    .string "You'll ruin the makeup.$"
    .endif
    .ifdef SPANISH
    .string "¡Bueno, por lo menos no me\n"
    .string "has quitado el maquillaje!$"
    .endif

OneIsland_KindleRoad_Text_AbigailIntro::
    .ifdef ENGLISH
    .string "I'm beginning to get a sunburn…$"
    .endif
    .ifdef SPANISH
    .string "Me estoy empezando a quemar...$"
    .endif

OneIsland_KindleRoad_Text_AbigailDefeat::
    .ifdef ENGLISH
    .string "Oh, you're so awful.$"
    .endif
    .ifdef SPANISH
    .string "¡Eres lo peor!$"
    .endif

OneIsland_KindleRoad_Text_AbigailPostBattle::
    .ifdef ENGLISH
    .string "I like that cap you have.\n"
    .string "Maybe I should wear one, too…$"
    .endif
    .ifdef SPANISH
    .string "Me gusta la ropa que llevas. Igual\n"
    .string "me convendría ponerme algo...$"
    .endif

OneIsland_KindleRoad_Text_FinnIntro::
    .ifdef ENGLISH
    .string "Seen from here, MT. EMBER towers\n"
    .string "into the sky.$"
    .endif
    .ifdef SPANISH
    .string "Si lo miras desde aquí, parece\n"
    .string "que el MT. ASCUAS toca el cielo.$"
    .endif

OneIsland_KindleRoad_Text_FinnDefeat::
    .ifdef ENGLISH
    .string "Well, aren't you tough?$"
    .endif
    .ifdef SPANISH
    .string "¡Ufff, eres fuerte!$"
    .endif

OneIsland_KindleRoad_Text_FinnPostBattle::
    .ifdef ENGLISH
    .string "The sky is immense around these\n"
    .string "parts.$"
    .endif
    .ifdef SPANISH
    .string "El cielo se puede observar muy\n"
    .string "bien en esta zona.$"
    .endif

OneIsland_KindleRoad_Text_GarrettIntro::
    .ifdef ENGLISH
    .string "I took a break from swimming,\n"
    .string "only to have you challenge me?$"
    .endif
    .ifdef SPANISH
    .string "¿Y he dejado de nadar para\n"
    .string "enfrentarme contigo?$"
    .endif

OneIsland_KindleRoad_Text_GarrettDefeat::
    .ifdef ENGLISH
    .string "Hey, what the…\n"
    .string "You're good, you!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye, oye, realmente eres\n"
    .string "impresionante!$"
    .endif

OneIsland_KindleRoad_Text_GarrettPostBattle::
    .ifdef ENGLISH
    .string "Instead of using SURF all the time,\n"
    .string "you should swim some.$"
    .endif
    .ifdef SPANISH
    .string "Te recomiendo que nades de vez en\n"
    .string "cuando y que no uses tanto SURF.$"
    .endif

OneIsland_KindleRoad_Text_TommyIntro::
    .ifdef ENGLISH
    .string "Wait! Wait a second!\n"
    .string "I think I've hooked a big one!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, un momento!\n"
    .string "¡Acaba de picar uno enorme!$"
    .endif

OneIsland_KindleRoad_Text_TommyDefeat::
    .ifdef ENGLISH
    .string "I've lost it all again…$"
    .endif
    .ifdef SPANISH
    .string "¡Lo he vuelto a perder!$"
    .endif

OneIsland_KindleRoad_Text_TommyPostBattle::
    .ifdef ENGLISH
    .string "Not only did I lose, the big one\n"
    .string "got away from me, too!$"
    .endif
    .ifdef SPANISH
    .string "¡No sólo he perdido, también me he\n"
    .string "quedado sin el ejemplar de antes!$"
    .endif

OneIsland_KindleRoad_Text_SharonIntro::
    .ifdef ENGLISH
    .string "Could you help me out with my\n"
    .string "training?$"
    .endif
    .ifdef SPANISH
    .string "¿Me echas una mano con mi\n"
    .string "entrenamiento?$"
    .endif

OneIsland_KindleRoad_Text_SharonDefeat::
    .ifdef ENGLISH
    .string "You were a cut above me.$"
    .endif
    .ifdef SPANISH
    .string "Me has ganado por muy poco.$"
    .endif

OneIsland_KindleRoad_Text_SharonPostBattle::
    .ifdef ENGLISH
    .string "It's clear that you're skilled.\n"
    .string "I like you!$"
    .endif
    .ifdef SPANISH
    .string "Está claro que sabes lo que haces.\n"
    .string "¡Te admiro!$"
    .endif

OneIsland_KindleRoad_Text_TanyaIntro::
    .ifdef ENGLISH
    .string "There isn't a day in which we don't\n"
    .string "train!$"
    .endif
    .ifdef SPANISH
    .string "No hay un solo día en el que no\n"
    .string "me entrene.$"
    .endif

OneIsland_KindleRoad_Text_TanyaDefeat::
    .ifdef ENGLISH
    .string "I'm such a fool!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué forma tan tonta de perder!$"
    .endif

OneIsland_KindleRoad_Text_TanyaPostBattle::
    .ifdef ENGLISH
    .string "I'll train even harder from now on!$"
    .endif
    .ifdef SPANISH
    .string "¡A partir de ahora me entrenaré\n"
    .string "más!$"
    .endif

OneIsland_KindleRoad_Text_SheaIntro::
    .ifdef ENGLISH
    .string "Every morning, before breakfast,\n"
    .string "I swim around this island.$"
    .endif
    .ifdef SPANISH
    .string "Cada mañana, antes de desayunar,\n"
    .string "rodeo a nado la isla.$"
    .endif

OneIsland_KindleRoad_Text_SheaDefeat::
    .ifdef ENGLISH
    .string "Gasp…\n"
    .string "Gasp…$"
    .endif
    .ifdef SPANISH
    .string "Agggg...\n"
    .string "Agggg...$"
    .endif

OneIsland_KindleRoad_Text_SheaPostBattle::
    .ifdef ENGLISH
    .string "I lost because I'm pooped from all\n"
    .string "the running I did…$"
    .endif
    .ifdef SPANISH
    .string "He perdido porque esta mañana\n"
    .string "corrí mucho y estoy cansado.$"
    .endif

OneIsland_KindleRoad_Text_HughIntro::
    .ifdef ENGLISH
    .string "Dress appropriately for battle!\n"
    .string "Lose that frivolous outfit!$"
    .endif
    .ifdef SPANISH
    .string "Para luchar hay que ir vestido\n"
    .string "en condiciones, ¡y no como tú!$"
    .endif

OneIsland_KindleRoad_Text_HughDefeat::
    .ifdef ENGLISH
    .string "Why me?!$"
    .endif
    .ifdef SPANISH
    .string "¡¿Por qué?!$"
    .endif

OneIsland_KindleRoad_Text_HughPostBattle::
    .ifdef ENGLISH
    .string "Even martial artists are becoming\n"
    .string "fashion conscious these days…$"
    .endif
    .ifdef SPANISH
    .string "Hasta los profesionales de las\n"
    .string "artes marciales nos preocupamos\l"
    .string "de la moda últimamente.$"
    .endif

OneIsland_KindleRoad_Text_BryceIntro::
    .ifdef ENGLISH
    .string "You know, everything tastes great\n"
    .string "when you're out in the wild.$"
    .endif
    .ifdef SPANISH
    .string "Cuando se está al aire libre,\n"
    .string "todo sabe mucho mejor.$"
    .endif

OneIsland_KindleRoad_Text_BryceDefeat::
    .ifdef ENGLISH
    .string "Awww, blown!$"
    .endif
    .ifdef SPANISH
    .string "¡Hala!$"
    .endif

OneIsland_KindleRoad_Text_BrycePostBattle::
    .ifdef ENGLISH
    .string "The water in volcanic regions is\n"
    .string "delicious.$"
    .endif
    .ifdef SPANISH
    .string "¿Sabías que el agua de las zonas\n"
    .string "volcánicas es muy buena?$"
    .endif

OneIsland_KindleRoad_Text_ClaireIntro::
    .ifdef ENGLISH
    .string "My lunch filled us up, so will you\n"
    .string "battle us for some exercise?$"
    .endif
    .ifdef SPANISH
    .string "La comida ha sido demasiado\n"
    .string "abundante. ¿Luchamos?$"
    .endif

OneIsland_KindleRoad_Text_ClaireDefeat::
    .ifdef ENGLISH
    .string "That made me all sweaty.$"
    .endif
    .ifdef SPANISH
    .string "¡Sí que he quemado calorías!$"
    .endif

OneIsland_KindleRoad_Text_ClairePostBattle::
    .ifdef ENGLISH
    .string "What should I do?\n"
    .string "I feel famished again.$"
    .endif
    .ifdef SPANISH
    .string "¿Qué hago?\n"
    .string "¡Otra vez tengo hambre!$"
    .endif

OneIsland_KindleRoad_Text_KiaIntro::
    .ifdef ENGLISH
    .string "KIA: My big brother and I make\n"
    .string "an awesome combination!$"
    .endif
    .ifdef SPANISH
    .string "PÍA: ¡Mi hermano mayor y yo\n"
    .string "hacemos un equipo increíble!$"
    .endif

OneIsland_KindleRoad_Text_KiaDefeat::
    .ifdef ENGLISH
    .string "KIA: Huh?!\n"
    .string "I can't believe it!$"
    .endif
    .ifdef SPANISH
    .string "PÍA: ¡No me lo puedo creer!$"
    .endif

OneIsland_KindleRoad_Text_KiaPostBattle::
    .ifdef ENGLISH
    .string "KIA: How could there be anyone\n"
    .string "better than my big brother?$"
    .endif
    .ifdef SPANISH
    .string "PÍA: ¿Cómo puede haber alguien\n"
    .string "mejor que mi hermano?$"
    .endif

OneIsland_KindleRoad_Text_KiaNotEnoughMons::
    .ifdef ENGLISH
    .string "KIA: If you want to battle with\n"
    .string "us, you have to bring at least two\l"
    .string "POKéMON with you.$"
    .endif
    .ifdef SPANISH
    .string "PÍA: Para luchar con nosotros,\n"
    .string "necesitas al menos dos POKéMON.$"
    .endif

OneIsland_KindleRoad_Text_MikIntro::
    .ifdef ENGLISH
    .string "MIK: Together with KIA, I'm afraid\n"
    .string "of nothing!$"
    .endif
    .ifdef SPANISH
    .string "FER: ¡Junto a PÍA no tengo miedo\n"
    .string "de nada!$"
    .endif

OneIsland_KindleRoad_Text_MikDefeat::
    .ifdef ENGLISH
    .string "MIK: Whoa!\n"
    .string "That's too much!$"
    .endif
    .ifdef SPANISH
    .string "FER: ¡Buaaaah, eres demasiado!$"
    .endif

OneIsland_KindleRoad_Text_MikPostBattle::
    .ifdef ENGLISH
    .string "MIK: How could my combination\n"
    .string "with KIA fail?$"
    .endif
    .ifdef SPANISH
    .string "FER: ¿Cómo ha podido fallar\n"
    .string "nuestro equipo?$"
    .endif

OneIsland_KindleRoad_Text_MikNotEnoughMons::
    .ifdef ENGLISH
    .string "MIK: Hey, do you want to battle\n"
    .string "with us two?\p"
    .string "Bring two or more POKéMON with\n"
    .string "you, then.$"
    .endif
    .ifdef SPANISH
    .string "FER: ¿Quieres luchar con nosotros?\p"
    .string "Pues vuelve con dos POKéMON\n"
    .string "por lo menos.$"
    .endif

OneIsland_KindleRoad_Text_RouteSign::
    .ifdef ENGLISH
    .string "This is KINDLE ROAD.\p"
    .string "Go straight for MT. EMBER.$"
    .endif
    .ifdef SPANISH
    .string "Éste es el CAMINO CANDENTE.\p"
    .string "Conduce al MT. ASCUAS.$"
    .endif

OneIsland_KindleRoad_Text_EmberSpaSign::
    .ifdef ENGLISH
    .string "Light the Fire in Your Heart!\n"
    .string "EMBER SPA$"
    .endif
    .ifdef SPANISH
    .string "BALNEARIO ASCUAS\n"
    .string "Enciende la llama que hay en ti.$"
    .endif

