PokemonTower_4F_Text_PaulaIntro::
    .ifdef ENGLISH
    .string "Ghost! No!\n"
    .string "Kwaaah!$"
    .endif
    .ifdef SPANISH
    .string "¡Un GHOST!\n¡No! ¡Guaaah!$"
    .endif

PokemonTower_4F_Text_PaulaDefeat::
    .ifdef ENGLISH
    .string "Where is the ghost?$"
    .endif
    .ifdef SPANISH
    .string "¿Dónde está GHOST?$"
    .endif

PokemonTower_4F_Text_PaulaPostBattle::
    .ifdef ENGLISH
    .string "I must have been dreaming…$"
    .endif
    .ifdef SPANISH
    .string "Debo de haberlo soñado...$"
    .endif

PokemonTower_4F_Text_LaurelIntro::
    .ifdef ENGLISH
    .string "Be cursed with me!\n"
    .string "Kwaaah!$"
    .endif
    .ifdef SPANISH
    .string "¡Te vas a enterar!\n"
    .string "¡Guaaah!$"
    .endif

PokemonTower_4F_Text_LaurelDefeat::
    .ifdef ENGLISH
    .string "What!$"
    .endif
    .ifdef SPANISH
    .string "¿Qué?$"
    .endif

PokemonTower_4F_Text_LaurelPostBattle::
    .ifdef ENGLISH
    .string "We can't determine the identity of\n"
    .string "the ghosts…$"
    .endif
    .ifdef SPANISH
    .string "¡No podemos desvelar la identidad\n"
    .string "de los GHOST!$"
    .endif

PokemonTower_4F_Text_JodyIntro::
    .ifdef ENGLISH
    .string "Huhuhu…\n"
    .string "Beat me not!$"
    .endif
    .ifdef SPANISH
    .string "Uuuuuu...\n"
    .string "¡Vencerme no, tú a mí!$"
    .endif

PokemonTower_4F_Text_JodyDefeat::
    .ifdef ENGLISH
    .string "Huh?\n"
    .string "Who? What?$"
    .endif
    .ifdef SPANISH
    .string "¿Eh?\n"
    .string "¿Quién? ¿Qué?$"
    .endif

PokemonTower_4F_Text_JodyPostBattle::
    .ifdef ENGLISH
    .string "May the departed POKéMON rest in\n"
    .string "peace…$"
    .endif
    .ifdef SPANISH
    .string "¡Que descansen los POKéMON\n"
    .string "debilitados!$"
    .endif

