PokemonTower_4F_Text_PaulaIntro::
	.string "Ein GEIST! Nein!\n"
	.string "Ahhhhh!$"

PokemonTower_4F_Text_PaulaDefeat::
	.string "Wohin ist der GEIST gegangen?$"

PokemonTower_4F_Text_PaulaPostBattle::
	.string "Ich bin sicher, ich träume das\n"
	.string "alles nur...$"

PokemonTower_4F_Text_LaurelIntro::
	.string "Ich verfluche dich!\n"
	.string "Buuuh!$"

PokemonTower_4F_Text_LaurelDefeat::
	.string "Was ist passiert?$"

PokemonTower_4F_Text_LaurelPostBattle::
	.string "Wir können die Identität der\n"
	.string "GEISTER nicht ermitteln!$"

PokemonTower_4F_Text_JodyIntro::
	.string "Buuh... buhuhu...\n"
	.string "Lass mich in Ruhe!$"

PokemonTower_4F_Text_JodyDefeat::
	.string "Wer?\n"
	.string "Was? Wo?$"

PokemonTower_4F_Text_JodyPostBattle::
	.string "Mögen die verlorenen Seelen der\n"
	.string "POKéMON in Frieden ruhen...$"

