PokemonTower_4F_Text_PaulaIntro::
    .string "¡Un GHOST!\n¡No! ¡Guaaah!$"

PokemonTower_4F_Text_PaulaDefeat::
    .string "¿Dónde está GHOST?$"

PokemonTower_4F_Text_PaulaPostBattle::
    .string "Debo de haberlo soñado...$"

PokemonTower_4F_Text_LaurelIntro::
    .string "¡Te vas a enterar!\n"
    .string "¡Guaaah!$"

PokemonTower_4F_Text_LaurelDefeat::
    .string "¿Qué?$"

PokemonTower_4F_Text_LaurelPostBattle::
    .string "¡No podemos desvelar la identidad\n"
    .string "de los GHOST!$"

PokemonTower_4F_Text_JodyIntro::
    .string "Uuuuuu...\n"
    .string "¡Vencerme no, tú a mí!$"

PokemonTower_4F_Text_JodyDefeat::
    .string "¿Eh?\n"
    .string "¿Quién? ¿Qué?$"

PokemonTower_4F_Text_JodyPostBattle::
    .string "¡Que descansen los POKéMON\n"
    .string "debilitados!$"
