PokemonTower_4F_Text_PaulaIntro::
	.string "Un SPECTRE!\n"
	.string "Rhaaaaaa!$"

PokemonTower_4F_Text_PaulaDefeat::
	.string "Ben!\n"
	.string "Où est le SPECTRE?$"

PokemonTower_4F_Text_PaulaPostBattle::
	.string "J'ai dû rêver…$"

PokemonTower_4F_Text_LaurelIntro::
	.string "Sois maudit!!!!\n"
	.string "Kwaaah!$"

PokemonTower_4F_Text_LaurelDefeat::
	.string "QUOI!$"

PokemonTower_4F_Text_LaurelPostBattle::
	.string "Nous ne pouvons pas identifier\n"
	.string "les SPECTRES.$"

PokemonTower_4F_Text_JodyIntro::
	.string "Huhuhu…\n"
	.string "Ne me frappe pas!$"

PokemonTower_4F_Text_JodyDefeat::
	.string "Hein?\n"
	.string "Qui? Quoi?$"

PokemonTower_4F_Text_JodyPostBattle::
	.string "Que les âmes des POKéMON\n"
	.string "disparus reposent en paix!$"

