CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel::
    .ifdef ENGLISH
    .string "SUPER REPEL keeps weak POKéMON at\n"
    .string "bay…\p"
    .string "Hmm, it's a more powerful REPEL.$"
    .endif
    .ifdef SPANISH
    .string "El SUPERREPEL mantiene a raya\n"
    .string "a los POKéMON débiles...\p"
    .string "¡Es un REPELENTE más fuerte!$"
    .endif

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .ifdef ENGLISH
    .string "For long outings, you should buy\n"
    .string "REVIVE.$"
    .endif
    .ifdef SPANISH
    .string "Para viajes largos deberías\n"
    .string "comprar REVIVIR.$"
    .endif

CeladonCity_DepartmentStore_2F_Text_FloorSign::
    .ifdef ENGLISH
    .string "Top-Grade Items for TRAINERS!\p"
    .string "2F: TRAINER'S MARKET$"
    .endif
    .ifdef SPANISH
    .string "Objetos de máxima calidad para los\n"
    .string "ENTRENADORES.\p"
    .string "P1: TIENDA DE LOS ENTRENADORES$"
    .endif

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
    .ifdef ENGLISH
    .string "We have a customer, LANCE, who\n"
    .string "occasionally comes.\p"
    .string "He always buys capes.\p"
    .string "I wonder… Does he have many\n"
    .string "identical capes at home?$"
    .endif
    .ifdef SPANISH
    .string "Tenemos un cliente habitual, LANCE,\n"
    .string "que suele comprar capas.\p"
    .string "La verdad es que debe de tener\n"
    .string "un montón iguales en su casa...$"
    .endif
