CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel::
    .string "El SUPERREPEL mantiene a raya\n"
    .string "a los POKéMON débiles...\p"
    .string "¡Es un REPELENTE más fuerte!$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
    .string "Para viajes largos deberías\n"
    .string "comprar REVIVIR.$"

CeladonCity_DepartmentStore_2F_Text_FloorSign::
    .string "Objetos de máxima calidad para los\n"
    .string "ENTRENADORES.\p"
    .string "P1: TIENDA DE LOS ENTRENADORES$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
    .string "Tenemos un cliente habitual, LANCE,\n"
    .string "que suele comprar capas.\p"
    .string "La verdad es que debe de tener\n"
    .string "un montón iguales en su casa...$"
