SilphCo_5F_Text_RocketsInUproarAboutIntruder::
    .string "El TEAM ROCKET está buscando\n"
    .string "a un intruso.\p"
    .string "Te buscan a ti, ¿no?$"

SilphCo_5F_Text_YoureOurHeroThankYou::
    .string "¡El TEAM ROCKET se ha ido!\n"
    .string "¡Gracias! ¡Eres nuestra salvación!$"

SilphCo_5F_Text_Grunt1Intro::
    .string "Dicen que se ha colado alguien...$"

SilphCo_5F_Text_Grunt1Defeat::
    .string "¡Boooom!$"

SilphCo_5F_Text_Grunt1PostBattle::
    .string "¡No es que sea muy inteligente\n"
    .string "provocar al TEAM ROCKET!$"

SilphCo_5F_Text_BeauIntro::
    .string "¡En este piso estudiamos la\n"
    .string "tecnología de las POKé BALL!$"

SilphCo_5F_Text_BeauDefeat::
    .string "¡Uff!\n"
    .string "¡Vaya!$"

SilphCo_5F_Text_BeauPostBattle::
    .string "¡Trabajamos en una nueva POKé\n"
    .string "BALL capaz de atraparlo todo!$"

SilphCo_5F_Text_DaltonIntro::
    .string "¿Qué?\p"
    .string "¡Aquí no debería haber niños!$"

SilphCo_5F_Text_DaltonDefeat::
    .string "¿Cómo me pasa esto a mí?$"

SilphCo_5F_Text_DaltonPostBattle::
    .string "¡Sólo has llegado al P4!\n"
    .string "¡Mi JEFE aún está muy lejos!$"

SilphCo_5F_Text_Grunt2Intro::
    .string "¡Respeta un poco al TEAM ROCKET!$"

SilphCo_5F_Text_Grunt2Defeat::
    .string "(Tos)...\n"
    .string "(Tos)...$"

SilphCo_5F_Text_Grunt2PostBattle::
    .string "Eso me recuerda que...\p"
    .string "¡KOFFING evoluciona y se\n"
    .string "transforma en WEEZING!$"

SilphCo_5F_Text_PorygonFirstVRMon::
    .string "¡Un INFORME sobre los POKéMON!\p"
    .string "PORYGON, el primer POKéMON\n"
    .string "virtual, se creó en el LABORATORIO\l"
    .string "POKéMON.$"

SilphCo_5F_Text_Over350TechniquesConfirmed::
    .string "¡Un INFORME sobre los POKéMON!\p"
    .string "¡Confirmadas más de 350 técnicas\n"
    .string "POKéMON!$"

SilphCo_5F_Text_SomeMonsEvolveWhenTraded::
    .string "¡Un INFORME sobre los POKéMON!\p"
    .string "Se ha confirmado que algunos\n"
    .string "POKéMON evolucionan cuando\l"
    .string "se realiza un intercambio.$"

SilphCo_5F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P4$"

SilphCo_5F_Text_RocketBossLookingForStrongMons::
    .string "Los tipejos esos que se apoderaron\n"
    .string "de nuestro edificio...\p"
    .string "Su JEFE dijo que estaba buscando\n"
    .string "POKéMON fuertes.\p"
    .string "Espero que nuestro PRESIDENTE\n"
    .string "se haya ocupado del tema...$"
