SilphCo_5F_Text_RocketsInUproarAboutIntruder::
    .ifdef ENGLISH
    .string "TEAM ROCKET is in an uproar over\n"
    .string "some intruder.\p"
    .string "That's you, right?$"
    .endif
    .ifdef SPANISH
    .string "El TEAM ROCKET está buscando\n"
    .string "a un intruso.\p"
    .string "Te buscan a ti, ¿no?$"
    .endif

SilphCo_5F_Text_YoureOurHeroThankYou::
    .ifdef ENGLISH
    .string "TEAM ROCKET took off!\n"
    .string "You're our hero! Thank you!$"
    .endif
    .ifdef SPANISH
    .string "¡El TEAM ROCKET se ha ido!\n"
    .string "¡Gracias! ¡Eres nuestra salvación!$"
    .endif

SilphCo_5F_Text_Grunt1Intro::
    .ifdef ENGLISH
    .string "I heard a kid was wandering\n"
    .string "around.$"
    .endif
    .ifdef SPANISH
    .string "Dicen que se ha colado alguien...$"
    .endif

SilphCo_5F_Text_Grunt1Defeat::
    .ifdef ENGLISH
    .string "Boom!$"
    .endif
    .ifdef SPANISH
    .string "¡Boooom!$"
    .endif

SilphCo_5F_Text_Grunt1PostBattle::
    .ifdef ENGLISH
    .string "It's not smart to pick a fight with\n"
    .string "TEAM ROCKET!$"
    .endif
    .ifdef SPANISH
    .string "¡No es que sea muy inteligente\n"
    .string "provocar al TEAM ROCKET!$"
    .endif

SilphCo_5F_Text_BeauIntro::
    .ifdef ENGLISH
    .string "We study POKé BALL technology on\n"
    .string "this floor.$"
    .endif
    .ifdef SPANISH
    .string "¡En este piso estudiamos la\n"
    .string "tecnología de las POKé BALL!$"
    .endif

SilphCo_5F_Text_BeauDefeat::
    .ifdef ENGLISH
    .string "Dang!\n"
    .string "Blast it!$"
    .endif
    .ifdef SPANISH
    .string "¡Uff!\n"
    .string "¡Vaya!$"
    .endif

SilphCo_5F_Text_BeauPostBattle::
    .ifdef ENGLISH
    .string "We worked on the ultimate POKé\n"
    .string "BALL which would catch anything.$"
    .endif
    .ifdef SPANISH
    .string "¡Trabajamos en una nueva POKé\n"
    .string "BALL capaz de atraparlo todo!$"
    .endif

SilphCo_5F_Text_DaltonIntro::
    .ifdef ENGLISH
    .string "Whaaat?\p"
    .string "There shouldn't be any children\n"
    .string "here!$"
    .endif
    .ifdef SPANISH
    .string "¿Qué?\p"
    .string "¡Aquí no debería haber niños!$"
    .endif

SilphCo_5F_Text_DaltonDefeat::
    .ifdef ENGLISH
    .string "Oh, goodness!$"
    .endif
    .ifdef SPANISH
    .string "¿Cómo me pasa esto a mí?$"
    .endif

SilphCo_5F_Text_DaltonPostBattle::
    .ifdef ENGLISH
    .string "You're only on 5F.\n"
    .string "It's a long way to my BOSS!$"
    .endif
    .ifdef SPANISH
    .string "¡Sólo has llegado al P4!\n"
    .string "¡Mi JEFE aún está muy lejos!$"
    .endif

SilphCo_5F_Text_Grunt2Intro::
    .ifdef ENGLISH
    .string "Show TEAM ROCKET a little respect!$"
    .endif
    .ifdef SPANISH
    .string "¡Respeta un poco al TEAM ROCKET!$"
    .endif

SilphCo_5F_Text_Grunt2Defeat::
    .ifdef ENGLISH
    .string "Cough…\n"
    .string "Cough…$"
    .endif
    .ifdef SPANISH
    .string "(Tos)...\n"
    .string "(Tos)...$"
    .endif

SilphCo_5F_Text_Grunt2PostBattle::
    .ifdef ENGLISH
    .string "Which reminds me.\p"
    .string "KOFFING evolves into WEEZING!$"
    .endif
    .ifdef SPANISH
    .string "Eso me recuerda que...\p"
    .string "¡KOFFING evoluciona y se\n"
    .string "transforma en WEEZING!$"
    .endif

SilphCo_5F_Text_PorygonFirstVRMon::
    .ifdef ENGLISH
    .string "It's a POKéMON REPORT!\p"
    .string "POKéMON LAB created PORYGON,\n"
    .string "the first virtual-reality POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Un INFORME sobre los POKéMON!\p"
    .string "PORYGON, el primer POKéMON\n"
    .string "virtual, se creó en el LABORATORIO\l"
    .string "POKéMON.$"
    .endif

SilphCo_5F_Text_Over350TechniquesConfirmed::
    .ifdef ENGLISH
    .string "It's a POKéMON REPORT!\p"
    .string "Over 350 POKéMON techniques have\n"
    .string "been confirmed.$"
    .endif
    .ifdef SPANISH
    .string "¡Un INFORME sobre los POKéMON!\p"
    .string "¡Confirmadas más de 350 técnicas\n"
    .string "POKéMON!$"
    .endif

SilphCo_5F_Text_SomeMonsEvolveWhenTraded::
    .ifdef ENGLISH
    .string "It's a POKéMON REPORT!\p"
    .string "Some POKéMON have been confirmed\n"
    .string "to evolve when they are traded.$"
    .endif
    .ifdef SPANISH
    .string "¡Un INFORME sobre los POKéMON!\p"
    .string "Se ha confirmado que algunos\n"
    .string "POKéMON evolucionan cuando\l"
    .string "se realiza un intercambio.$"
    .endif

SilphCo_5F_Text_FloorSign::
    .ifdef ENGLISH
    .string "SILPH CO. HEAD OFFICE\n"
    .string "5F$"
    .endif
    .ifdef SPANISH
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P4$"
    .endif

SilphCo_5F_Text_RocketBossLookingForStrongMons::
    .ifdef ENGLISH
    .string "Those thugs that took over our\n"
    .string "building…\p"
    .string "Their BOSS said he was looking for\n"
    .string "strong POKéMON.\p"
    .string "I hope our PRESIDENT managed to\n"
    .string "avoid trouble…$"
    .endif
    .ifdef SPANISH
    .string "Los tipejos esos que se apoderaron\n"
    .string "de nuestro edificio...\p"
    .string "Su JEFE dijo que estaba buscando\n"
    .string "POKéMON fuertes.\p"
    .string "Espero que nuestro PRESIDENTE\n"
    .string "se haya ocupado del tema...$"
    .endif
