LavenderTown_Mart_Text_SearchingForStatRaiseItems::
    .ifdef ENGLISH
    .string "I'm searching for items that raise\n"
    .string "the stats of POKéMON.\p"
    .string "They're effective over the course\n"
    .string "of a single battle.\p"
    .string "X ATTACK, X DEFEND, X SPEED, \n"
    .string "and X SPECIAL are what I'm after.\p"
    .string "Do you know where I can get them?$"
    .endif
    .ifdef SPANISH
    .string "Estoy buscando algunos objetos que\n"
    .string "aumenten las habilidades de los\l"
    .string "POKéMON en un sólo combate.\p"
    .string "Estoy buscando ATAQUE X,\n"
    .string "DEFENSA X, VELOCIDAD X y\l"
    .string "ESPECIAL X.\p"
    .string "¿Sabes dónde encontrarlos?$"
    .endif

LavenderTown_Mart_Text_DidYouBuyRevives::
    .ifdef ENGLISH
    .string "Did you buy some REVIVES?\n"
    .string "They revive any fainted POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¿Conoces REVIVIR?\n"
    .string "Devuelve la energía a los POKéMON\l"
    .string "debilitados.$"
    .endif

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
    .ifdef ENGLISH
    .string "Sometimes, a TRAINER duo will\n"
    .string "challenge you with two POKéMON\l"
    .string "at the same time.\p"
    .string "If that happens, you have to send\n"
    .string "out two POKéMON to battle, too.$"
    .endif
    .ifdef SPANISH
    .string "A veces, coincidirás con parejas\n"
    .string "de ENTRENADORES que te retarán\l"
    .string "con dos POKéMON a la vez.\p"
    .string "Cuando esto ocurra, para luchar\n"
    .string "tú también necesitarás dos POKéMON.$"
    .endif

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
    .string "この　あいだ　やまおくで\n"
    .string "きんのたまを　ひろい　ましてね！\p"
    .string "つかえない　しなもの　ですが\n"
    .string "うったら　なんと　5000¥でした$"
