LavenderTown_Mart_Text_SearchingForStatRaiseItems::
	.string "Je cherche des objets permettant\n"
	.string "d'augmenter la puissance d'un\l"
	.string "POKéMON en combat.\p"
	.string "ATTAQUE +, DEFENSE +, SPECIAL +\n"
	.string "et VITESSE +, c'est ça qu'je\l"
	.string "cherche.\p"
	.string "Sais-tu où je peux en trouver?$"

LavenderTown_Mart_Text_DidYouBuyRevives::
	.string "Connais-tu le RAPPEL? Il permet de\n"
	.string "réanimer un POKéMON KO!$"

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
	.string "Des DRESSEURS pourraient te\n"
	.string "défier avec deux POKéMON à la\p"
	.string "fois. Si ça arrive, tu devras aussi\n"
	.string "utiliser deux POKéMON.$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
	.string "この　あいだ　やまおくで\n"
	.string "きんのたまを　ひろい　ましてね！\p"
	.string "つかえない　しなもの　ですが\n"
	.string "うったら　なんと　5000¥でした$"

