PalletTown_PlayersHouse_2F_Text_PlayedWithNES::
    .ifdef ENGLISH
    .string "{PLAYER} played with the NES.\p"
    .string "…Okay!\n"
    .string "It's time to go!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} está jugando a la NES!\p"
    .string "Bueno, más vale que me ponga\n"
    .string "en marcha.$"
    .endif

PalletTown_PlayersHouse_2F_Text_PressLRForHelp::
    .ifdef ENGLISH
    .string "It's a posted notice…\p"
    .string "If you're confused, ask for HELP!\n"
    .string "Press the L or R Button!$"
    .endif
    .ifdef SPANISH
    .string "Anda, una nota...\p"
    .string "Si no sabes qué hacer, busca\n"
    .string "AYUDA. Pulsa el Botón L o R.$"
    .endif

