SaffronCity_Dojo_Text_MasterKoichiIntro::
    .ifdef ENGLISH
    .string "Grunt!\p"
    .string "I am the KARATE MASTER!\n"
    .string "I am the LEADER here!\p"
    .string "You wish to challenge us?\n"
    .string "Expect no mercy!\p"
    .string "Fwaaa!$"
    .endif
    .ifdef SPANISH
    .string "¡Grrrrr!\p"
    .string "¡Soy el MAESTRO KARATEKA!\n"
    .string "¡Y aquí yo soy el LÍDER!\p"
    .string "¿Quieres desafiarnos?\n"
    .string "¡No tendremos piedad!\p"
    .string "¡Fuaaa!$"
    .endif

SaffronCity_Dojo_Text_MasterKoichiDefeat::
    .ifdef ENGLISH
    .string "Hwa!\n"
    .string "Arrgh! Beaten!$"
    .endif
    .ifdef SPANISH
    .string "¡Fuaa!\n"
    .string "¡Arg! ¡Nos has vencido!$"
    .endif

SaffronCity_Dojo_Text_ChoosePrizedFightingMon::
    .ifdef ENGLISH
    .string "Indeed, I have lost!\p"
    .string "But, I beseech you, do not take\n"
    .string "our emblem as your trophy!\p"
    .string "In return, I will give you a prized\n"
    .string "FIGHTING POKéMON!\p"
    .string "Choose whichever one you like!$"
    .endif
    .ifdef SPANISH
    .string "¡Pues sí, he perdido!\p"
    .string "¡Pero te suplico que no te lleves\n"
    .string "nuestro emblema como trofeo!\p"
    .string "¡A cambio te daré un valioso y\n"
    .string "fuerte POKéMON!\p"
    .string "¡Elige el que quieras!$"
    .endif

SaffronCity_Dojo_Text_StayAndTrainWithUs::
    .ifdef ENGLISH
    .string "Grunt!\n"
    .string "Stay and train at karate with us!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola! ¡Quédate y practica karate\n"
    .string "con nosotros!$"
    .endif

SaffronCity_Dojo_Text_MikeIntro::
    .ifdef ENGLISH
    .string "Hoargh!\n"
    .string "Take your shoes off!$"
    .endif
    .ifdef SPANISH
    .string "¡Iiiiiiiia!\n"
    .string "¡Quítate los zapatos!$"
    .endif

SaffronCity_Dojo_Text_MikeDefeat::
    .ifdef ENGLISH
    .string "I give up!$"
    .endif
    .ifdef SPANISH
    .string "¡Me rindo!$"
    .endif

SaffronCity_Dojo_Text_MikePostBattle::
    .ifdef ENGLISH
    .string "You wait 'til you see our MASTER!\n"
    .string "I'm a small fry compared to him!$"
    .endif
    .ifdef SPANISH
    .string "¡Espera a ver a nuestro MAESTRO!\p"
    .string "¡Yo soy una birria comparado\n"
    .string "con él!$"
    .endif

SaffronCity_Dojo_Text_HidekiIntro::
    .ifdef ENGLISH
    .string "I hear you're good!\n"
    .string "Show me!$"
    .endif
    .ifdef SPANISH
    .string "¡Dicen que eres fuerte!\n"
    .string "¡Demuéstramelo!$"
    .endif

SaffronCity_Dojo_Text_HidekiDefeat::
    .ifdef ENGLISH
    .string "Judge!\n"
    .string "One point!$"
    .endif
    .ifdef SPANISH
    .string "¡Bien hecho!\n"
    .string "¡Un punto!$"
    .endif

SaffronCity_Dojo_Text_HidekiPostBattle::
    .ifdef ENGLISH
    .string "Our MASTER is a pro fighter.\n"
    .string "Be prepared to lose!$"
    .endif
    .ifdef SPANISH
    .string "¡Nuestro MAESTRO es un karateka\n"
    .string "profesional!$"
    .endif

SaffronCity_Dojo_Text_AaronIntro::
    .ifdef ENGLISH
    .string "Hiyah!\n"
    .string "I have no fear for anything tough!\p"
    .string "I shatter boulders for training\n"
    .string "every day!$"
    .endif
    .ifdef SPANISH
    .string "¡No me asustas nada!\n"
    .string "¡Rompo rocas para entrenarme!$"
    .endif

SaffronCity_Dojo_Text_AaronDefeat::
    .ifdef ENGLISH
    .string "Yow!\n"
    .string "Stubbed fingers!$"
    .endif
    .ifdef SPANISH
    .string "¡Auch!\n"
    .string "¡No he estado nada ágil!$"
    .endif

SaffronCity_Dojo_Text_AaronPostBattle::
    .ifdef ENGLISH
    .string "The only thing that frightens us is\n"
    .string "psychic power!$"
    .endif
    .ifdef SPANISH
    .string "¡Sólo nos asustan los poderes\n"
    .string "psíquicos!$"
    .endif

SaffronCity_Dojo_Text_HitoshiIntro::
    .ifdef ENGLISH
    .string "Hwaah!\p"
    .string "You're trespassing in our\n"
    .string "FIGHTING DOJO!$"
    .endif
    .ifdef SPANISH
    .string "¡Ehhh!\p"
    .string "¡No puedes entrar en nuestro DOJO-\n"
    .string "KARATE!$"
    .endif

SaffronCity_Dojo_Text_HitoshiDefeat::
    .ifdef ENGLISH
    .string "Oof!\n"
    .string "I give up!$"
    .endif
    .ifdef SPANISH
    .string "¡Uuuf!\n"
    .string "¡Me rindo!$"
    .endif

SaffronCity_Dojo_Text_HitoshiPostBattle::
    .ifdef ENGLISH
    .string "The prime fighters across the land\n"
    .string "train here.$"
    .endif
    .ifdef SPANISH
    .string "Los mejores luchadores se entrenan\n"
    .string "aquí.$"
    .endif

SaffronCity_Dojo_Text_YouWantHitmonlee::
    .ifdef ENGLISH
    .string "You want the hard-kicking\n"
    .string "HITMONLEE?$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres la dura patada de\n"
    .string "HITMONLEE?$"
    .endif

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster::
    .ifdef ENGLISH
    .string "{PLAYER} received the {STR_VAR_1}\n"
    .string "from the KARATE MASTER.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo a {STR_VAR_1}\n"
    .string "de manos del MAESTRO de KARATE!$"
    .endif

SaffronCity_Dojo_Text_YouWantHitmonchan::
    .ifdef ENGLISH
    .string "You want the piston-punching\n"
    .string "HITMONCHAN?$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres el superpuñetazo de\n"
    .string "HITMONCHAN?$"
    .endif

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2::
    .string "{PLAYER}は　カラテ　だいおう　から\n"
    .string "{STR_VAR_1}を　もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy::
    .ifdef ENGLISH
    .string "Better not get greedy…$"
    .endif
    .ifdef SPANISH
    .string "Oye, la avaricia rompe el saco...$"
    .endif

SaffronCity_Dojo_Text_EnemiesOnEverySide::
    .ifdef ENGLISH
    .string "Enemies on every side!$"
    .endif
    .ifdef SPANISH
    .string "¡Hay enemigos por todas partes!$"
    .endif

SaffronCity_Dojo_Text_GoesAroundComesAround::
    .ifdef ENGLISH
    .string "What goes around comes around.$"
    .endif
    .ifdef SPANISH
    .string "¡Que pase lo que tenga que pasar!$"
    .endif

SaffronCity_Dojo_Text_FightingDojo::
    .ifdef ENGLISH
    .string "FIGHTING DOJO$"
    .endif
    .ifdef SPANISH
    .string "DOJO-KARATE$"
    .endif

