SaffronCity_Dojo_Text_MasterKoichiIntro::
    .string "¡Grrrrr!\p"
    .string "¡Soy el MAESTRO KARATEKA!\n"
    .string "¡Y aquí yo soy el LÍDER!\p"
    .string "¿Quieres desafiarnos?\n"
    .string "¡No tendremos piedad!\p"
    .string "¡Fuaaa!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat::
    .string "¡Fuaa!\n"
    .string "¡Arg! ¡Nos has vencido!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon::
    .string "¡Pues sí, he perdido!\p"
    .string "¡Pero te suplico que no te lleves\n"
    .string "nuestro emblema como trofeo!\p"
    .string "¡A cambio te daré un valioso y\n"
    .string "fuerte POKéMON!\p"
    .string "¡Elige el que quieras!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs::
    .string "¡Hola! ¡Quédate y practica karate\n"
    .string "con nosotros!$"

SaffronCity_Dojo_Text_MikeIntro::
    .string "¡Iiiiiiiia!\n"
    .string "¡Quítate los zapatos!$"

SaffronCity_Dojo_Text_MikeDefeat::
    .string "¡Me rindo!$"

SaffronCity_Dojo_Text_MikePostBattle::
    .string "¡Espera a ver a nuestro MAESTRO!\p"
    .string "¡Yo soy una birria comparado\n"
    .string "con él!$"

SaffronCity_Dojo_Text_HidekiIntro::
    .string "¡Dicen que eres fuerte!\n"
    .string "¡Demuéstramelo!$"

SaffronCity_Dojo_Text_HidekiDefeat::
    .string "¡Bien hecho!\n"
    .string "¡Un punto!$"

SaffronCity_Dojo_Text_HidekiPostBattle::
    .string "¡Nuestro MAESTRO es un karateka\n"
    .string "profesional!$"

SaffronCity_Dojo_Text_AaronIntro::
    .string "¡No me asustas nada!\n"
    .string "¡Rompo rocas para entrenarme!$"

SaffronCity_Dojo_Text_AaronDefeat::
    .string "¡Auch!\n"
    .string "¡No he estado nada ágil!$"

SaffronCity_Dojo_Text_AaronPostBattle::
    .string "¡Sólo nos asustan los poderes\n"
    .string "psíquicos!$"

SaffronCity_Dojo_Text_HitoshiIntro::
    .string "¡Ehhh!\p"
    .string "¡No puedes entrar en nuestro DOJO-\n"
    .string "KARATE!$"

SaffronCity_Dojo_Text_HitoshiDefeat::
    .string "¡Uuuf!\n"
    .string "¡Me rindo!$"

SaffronCity_Dojo_Text_HitoshiPostBattle::
    .string "Los mejores luchadores se entrenan\n"
    .string "aquí.$"

SaffronCity_Dojo_Text_YouWantHitmonlee::
    .string "¿Quieres la dura patada de\n"
    .string "HITMONLEE?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster::
    .string "¡{PLAYER} obtuvo a {STR_VAR_1}\n"
    .string "de manos del MAESTRO de KARATE!$"

SaffronCity_Dojo_Text_YouWantHitmonchan::
    .string "¿Quieres el superpuñetazo de\n"
    .string "HITMONCHAN?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2::
    .string "{PLAYER}は　カラテ　だいおう　から\n"
    .string "{STR_VAR_1}を　もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy::
    .string "Oye, la avaricia rompe el saco...$"

SaffronCity_Dojo_Text_EnemiesOnEverySide::
    .string "¡Hay enemigos por todas partes!$"

SaffronCity_Dojo_Text_GoesAroundComesAround::
    .string "¡Que pase lo que tenga que pasar!$"

SaffronCity_Dojo_Text_FightingDojo::
    .string "DOJO-KARATE$"
