Aide_Text_HaventCaughtEnoughMonsForItem::
	.ifdef ENGLISH
	.string "Let's see…\n"
	.string "Uh-oh! You have caught only\l"
	.string "{STR_VAR_3} kinds of POKéMON!\p"
	.string "You need {STR_VAR_1} kinds\n"
	.string "if you want the {STR_VAR_2}.$"
	.endif
	.ifdef SPANISH
	.string "Veamos...\n"
	.string "¡Oh! ¡Atrapaste solamente {STR_VAR_3} tipos\l"
	.string "de POKéMON!\p"
	.string "Necesitas {STR_VAR_1} tipos si quieres\n"
	.string "{STR_VAR_2}.$"
	.endif

Aide_Text_GetEnoughMonsComeBackForItem::
	.ifdef ENGLISH
	.string "…Oh. I see.\p"
	.string "When you get {STR_VAR_1} kinds of POKéMON,\n"
	.string "come back for the {STR_VAR_2}.$"
	.endif
	.ifdef SPANISH
	.string "¡Ah! Ya veo.\p"
	.string "Cuando tengas {STR_VAR_1} tipos, vuelve\n"
	.string "a por {STR_VAR_2}.$"
	.endif

Aide_Text_DontHaveAnyRoomForItem::
	.ifdef ENGLISH
	.string "Oh! I see you don't have any\n"
	.string "room for the {STR_VAR_2}.$"
	.endif
	.ifdef SPANISH
	.string "¡Oh! Ya veo que no tienes sitio\n"
	.string "para {STR_VAR_2}.$"
	.endif
