Braille_Text_Up::
	.ifdef ENGLISH
	.braille "UP$"
	.endif
	.ifdef SPANISH
	.braille "ARRIBA$"
	.endif

Braille_Text_Down::
	.ifdef ENGLISH
	.braille "DOWN$"
	.endif
	.ifdef SPANISH
	.braille "ABAJO$"
	.endif

Braille_Text_Right::
	.ifdef ENGLISH
	.braille "RIGHT$"
	.endif
	.ifdef SPANISH
	.braille "DERECHA$"
	.endif

Braille_Text_Left::
	.ifdef ENGLISH
	.braille "LEFT$"
	.endif
	.ifdef SPANISH
	.braille "IZQUIERDA$"
	.endif

Braille_Text_Cut::
	.ifdef ENGLISH
	.braille "CUT$"
	.endif
	.ifdef SPANISH
	.braille "CORTE$"
	.endif

Braille_Text_ABC::
	.ifdef ENGLISH
	.braille "ABC$"
	.endif
	.ifdef SPANISH
	.braille "ABC$"
	.endif

Braille_Text_GHI::
	.ifdef ENGLISH
	.braille "GHI$"
	.endif
	.ifdef SPANISH
	.braille "GHI$"
	.endif

Braille_Text_MNO::
	.ifdef ENGLISH
	.braille "MNO$"
	.endif
	.ifdef SPANISH
	.braille "MNO$"
	.endif

Braille_Text_TUV::
	.ifdef ENGLISH
	.braille "TUV$"
	.endif
	.ifdef SPANISH
	.braille "TUV$"
	.endif

Braille_Text_DEF::
	.ifdef ENGLISH
	.braille "DEF$"
	.endif
	.ifdef SPANISH
	.braille "DEF$"
	.endif

Braille_Text_JKL::
	.ifdef ENGLISH
	.braille "JKL$"
	.endif
	.ifdef SPANISH
	.braille "JKL$"
	.endif

Braille_Text_PQRS::
	.ifdef ENGLISH
	.braille "PQRS$"
	.endif
	.ifdef SPANISH
	.braille "PQRS$"
	.endif

Braille_Text_WXYZ::
	.ifdef ENGLISH
	.braille "WXYZ$"
	.endif
	.ifdef SPANISH
	.braille "WXYZ$"
	.endif

Braille_Text_Period::
	.ifdef ENGLISH
	.braille ".$"
	.endif
	.ifdef SPANISH
	.braille "='$"
	.endif

Braille_Text_Comma::
	.ifdef ENGLISH
	.braille ",$"
	.endif
	.ifdef SPANISH
	.braille "=,$"
	.endif

Braille_Text_Everything::
	.ifdef ENGLISH
	.braille "EVERYTHING$"
	.endif
	.ifdef SPANISH
	.braille "TODO$"
	.endif

Braille_Text_HasMeaning1::
	.ifdef ENGLISH
	.braille "HAS MEANING$"
	.endif
	.ifdef SPANISH
	.braille "IMPORTA$"
	.endif

Braille_Text_Existence::
	.ifdef ENGLISH
	.braille "EXISTENCE$"
	.endif
	.ifdef SPANISH
	.braille "EXISTENCIA$"
	.endif

Braille_Text_HasMeaning2::
	.ifdef ENGLISH
	.braille "HAS MEANING$"
	.endif
	.ifdef SPANISH
	.braille "IMPORTA$"
	.endif

Braille_Text_BeingAlive::
	.ifdef ENGLISH
	.braille "BEING ALIVE$"
	.endif
	.ifdef SPANISH
	.braille "ESTAR VIVO$"
	.endif

Braille_Text_HasMeaning3::
	.ifdef ENGLISH
	.braille "HAS MEANING$"
	.endif
	.ifdef SPANISH
	.braille "IMPORTA$"
	.endif

Braille_Text_HaveDreams::
	.ifdef ENGLISH
	.braille "HAVE DREAMS$"
	.endif
	.ifdef SPANISH
	.braille "DESEAR$"
	.endif

Braille_Text_UsePower::
	.ifdef ENGLISH
	.braille "USE POWER.$"
	.endif
	.ifdef SPANISH
	.braille "USA FUERZA$"
	.endif

Braille_Text_LetTheTwo::
	.ifdef ENGLISH
	.braille "LET THE TWO$"
	.endif
	.ifdef SPANISH
	.braille "DEJA A DOS$"
	.endif

Braille_Text_Glittering::
	.ifdef ENGLISH
	.braille "GLITTERING$"
	.endif
	.ifdef SPANISH
	.braille "BRILLANTES$"
	.endif

Braille_Text_Stones::
	.ifdef ENGLISH
	.braille "STONES$"
	.endif
	.ifdef SPANISH
	.braille "PIEDRAS$"
	.endif

Braille_Text_OneInRed::
	.ifdef ENGLISH
	.braille "ONE IN RED$"
	.endif
	.ifdef SPANISH
	.braille "UNA ROJA$"
	.endif

Braille_Text_OneInBlue::
	.ifdef ENGLISH
	.braille "ONE IN BLUE$"
	.endif
	.ifdef SPANISH
	.braille "UNA AZUL$"
	.endif

Braille_Text_ConnectThe::
	.ifdef ENGLISH
	.braille "CONNECT THE$"
	.endif
	.ifdef SPANISH
	.braille "CONECTAR$"
	.endif

Braille_Text_Past::
	.ifdef ENGLISH
	.braille "PAST.$"
	.endif
	.ifdef SPANISH
	.braille "CON PASADO$"
	.endif

Braille_Text_TwoFriends::
	.ifdef ENGLISH
	.braille "TWO FRIENDS$"
	.endif
	.ifdef SPANISH
	.braille "AMIGOS$"
	.endif

Braille_Text_Sharing::
	.ifdef ENGLISH
	.braille "SHARING$"
	.endif
	.ifdef SPANISH
	.braille "COMPARTIR$"
	.endif

Braille_Text_PowerOpen::
	.ifdef ENGLISH
	.braille "POWER OPEN$"
	.endif
	.ifdef SPANISH
	.braille "FUERZA$"
	.endif

Braille_Text_AWindowTo::
	.ifdef ENGLISH
	.braille "A WINDOW TO$"
	.endif
	.ifdef SPANISH
	.braille "ABRE PUERTA$"
	.endif

Braille_Text_ANewWorld::
	.ifdef ENGLISH
	.braille "A NEW WORLD$"
	.endif
	.ifdef SPANISH
	.braille "A MUNDO$"
	.endif

Braille_Text_ThatGlows::
	.ifdef ENGLISH
	.braille "THAT GLOWS.$"
	.endif
	.ifdef SPANISH
	.braille "POR EXPLORAR$"
	.endif

Braille_Text_TheNext::
	.ifdef ENGLISH
	.braille "THE NEXT$"
	.endif
	.ifdef SPANISH
	.braille "NUEVO MUNDO$"
	.endif

Braille_Text_WorldWaits::
	.ifdef ENGLISH
	.braille "WORLD WAITS$"
	.endif
	.ifdef SPANISH
	.braille "OS$"
	.endif

Braille_Text_ForYou::
	.ifdef ENGLISH
	.braille "FOR YOU.$"
	.endif
	.ifdef SPANISH
	.braille "ESPERA$"
	.endif
