@ Unused
Text_WelcomeTradeCenter::
	.string "Welcome to the POKéMON CABLE CLUB\n"
	.string "TRADE CENTER.$"

@ Unused
Text_WelcomeColosseum::
	.string "Welcome to the POKéMON CABLE CLUB\n"
	.string "COLOSSEUM.$"

@ Unused
Text_WelcomeTimeCapsule::
	.string "Welcome to the POKéMON CABLE CLUB\n"
	.string "TIME CAPSULE.$"

Text_PleaseComeAgain::
	.string "Please come again!$"

@ Unused
Text_HavingDiscountSaleToday::
	.string "Welcome!\p"
	.string "We're having a discount sale today!$"

@ Unused
Text_PlayerWhatCanIDoForYou::
	.string "{PLAYER}{KUN}, welcome!\p"
	.string "What can I do for you?$"
