@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife::
	.ifdef ENGLISH
	.string "I'm the DAY-CARE MAN.\p"
	.string "I help take care of the precious\n"
	.string "POKéMON of TRAINERS.\p"
	.string "If you'd like me to raise your\n"
	.string "POKéMON, have a word with my wife.$"
	.endif
	.ifdef SPANISH
	.string "Soy el ENCARGADO de la GUARDERÍA.\p"
	.string "Ayudo a los ENTRENADORES a cuidar\n"
	.string "de sus preciosos POKéMON.\p"
	.string "Si quieres que me encargue del\n"
	.string "tuyo, ve a hablar con mi mujer.$"
	.endif

DayCare_Text_DoYouWantEgg::
	.ifdef ENGLISH
	.string "Ah, it's you!\p"
	.string "We were raising your POKéMON, and\n"
	.string "my goodness, were we surprised!\p"
	.string "Your POKéMON had an EGG!\p"
	.string "We don't know how it got there,\n"
	.string "but your POKéMON had it.\p"
	.string "You do want it, yes?$"
	.endif
	.ifdef SPANISH
	.string "¡Ah, eres tú!\p"
	.string "¡Hemos cuidado de tu POKéMON\n"
	.string "y vaya sorpresa que nos hemos\l"
	.string "llevado!\p"
	.string "¡Tu POKéMON ha tenido un HUEVO!\p"
	.string "No sabemos cómo ha sucedido,\n"
	.string "pero es de tu POKéMON, seguro.\p"
	.string "¿Lo quieres?$"
	.endif

DayCare_Text_YourMonIsDoingFine::
	.ifdef ENGLISH
	.string "Ah, it's you! Good to see you.\n"
	.string "Your {STR_VAR_1}'s doing fine.$"
	.endif
	.ifdef SPANISH
	.string "¡Ah, eres tú! Me alegro de verte.\n"
	.string "Tu {STR_VAR_1} está estupendamente.$"
	.endif

DayCare_Text_IllKeepIt::
	.ifdef ENGLISH
	.string "Well then, I'll keep it.\n"
	.string "Thanks!$"
	.endif
	.ifdef SPANISH
	.string "Muy bien, entonces me seguiré\n"
	.string "ocupando de él. ¡Gracias!$"
	.endif

DayCare_Text_YouHaveNoRoomForIt::
	.ifdef ENGLISH
	.string "You have no room for it…\n"
	.string "Come back when you've made room.$"
	.endif
	.ifdef SPANISH
	.string "No tienes sitio para él...\n"
	.string "Vuelve cuando lo tengas.$"
	.endif

DayCare_Text_ReceivedEgg::
	.ifdef ENGLISH
	.string "{PLAYER} received the EGG from\n"
	.string "the DAY-CARE MAN.$"
	.endif
	.ifdef SPANISH
	.string "¡El ENCARGADO de la GUARDERÍA\n"
	.string "le dio el HUEVO a {PLAYER}!$"
	.endif

DayCare_Text_TakeGoodCareOfIt::
	.ifdef ENGLISH
	.string "Take good care of it.$"
	.endif
	.ifdef SPANISH
	.string "Cuídalo bien.$"
	.endif

DayCare_Text_SeeWifeIfYouWantToPickUpMon::
	.string "ポケモンを　ひきとりたい　ときは\n"
	.string "ばさんに　いって　おくれ$"

DayCare_Text_YourMonsAreDoingFine::
	.ifdef ENGLISH
	.string "Ah, it's you! Your {STR_VAR_1} and\n"
	.string "{STR_VAR_2} are doing fine.$"
	.endif
	.ifdef SPANISH
	.string "¡Ah, eres tú! Tu {STR_VAR_1} y el\n"
	.string "{STR_VAR_2} están muy bien.$"
	.endif

DayCare_Text_IWillKeepDoYouWantIt::
	.ifdef ENGLISH
	.string "I really will keep it.\n"
	.string "You do want this, yes?$"
	.endif
	.ifdef SPANISH
	.string "Yo me lo quedaría, pero\n"
	.string "tú lo quieres, ¿verdad?$"
	.endif

DayCare_Text_WouldYouLikeUsToRaiseMon::
	.ifdef ENGLISH
	.string "I'm the DAY-CARE LADY.\p"
	.string "We can raise POKéMON for you.\p"
	.string "Would you like us to raise one?$"
	.endif
	.ifdef SPANISH
	.string "Soy la ENCARGADA de la GUARDERÍA.\p"
	.string "Podemos ocuparnos de tus POKéMON.\p"
	.string "¿Quieres que cuidemos de alguno?$"
	.endif

DayCare_Text_WhichMonShouldWeRaise::
	.ifdef ENGLISH
	.string "Which POKéMON should we raise for\n"
	.string "you?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué POKéMON quieres que\n"
	.string "cuidemos?$"
	.endif

DayCare_Text_WellRaiseYourMon::
	.ifdef ENGLISH
	.string "Fine, we'll raise your {STR_VAR_1}\n"
	.string "for a while.\p"
	.string "Come back for it later.$"
	.endif
	.ifdef SPANISH
	.string "Estupendo, nos ocuparemos de tu\n"
	.string "{STR_VAR_1} cuanto sea necesario.\p"
	.string "Vuelve cuando quieras.$"
	.endif

DayCare_Text_WeCanRaiseOneMore::
	.ifdef ENGLISH
	.string "We can raise two of your POKéMON.\p"
	.string "Would you like us to raise one\n"
	.string "more POKéMON for you?$"
	.endif
	.ifdef SPANISH
	.string "Podemos cuidar a dos de tus\n"
	.string "POKéMON.\p"
	.string "¿Quieres que cuidemos de otro más?$"
	.endif

DayCare_Text_HusbandWasLookingForYou::
	.ifdef ENGLISH
	.string "My husband was looking for you.$"
	.endif
	.ifdef SPANISH
	.string "Mi marido te estaba buscando.$"
	.endif

DayCare_Text_FineThenComeAgain::
	.ifdef ENGLISH
	.string "Oh, fine, then.\n"
	.string "Come again.$"
	.endif
	.ifdef SPANISH
	.string "Muy bien.\n"
	.string "Vuelve cuando quieras.$"
	.endif

DayCare_Text_NotEnoughMoney::
	.ifdef ENGLISH
	.string "You don't have enough money…$"
	.endif
	.ifdef SPANISH
	.string "No tienes bastante dinero.$"
	.endif

DayCare_Text_TakeOtherOneBackToo::
	.ifdef ENGLISH
	.string "Will you take back the other one,\n"
	.string "too?$"
	.endif
	.ifdef SPANISH
	.string "¿Quieres llevarte el otro también?$"
	.endif

DayCare_Text_ComeAgain::
	.ifdef ENGLISH
	.string "Fine.\n"
	.string "Come again.$"
	.endif
	.ifdef SPANISH
	.string "Muy bien.\n"
	.string "Vuelve cuando quieras.$"
	.endif

DayCare_Text_GoodToSeeYou::
	.ifdef ENGLISH
	.string "Ah, it's you!\n"
	.string "Good to see you.\p"
	.string "Your POKéMON can only be doing\n"
	.string "good!$"
	.endif
	.ifdef SPANISH
	.string "¡Ah, eres tú! Me alegro de verte.\n"
	.string "Todo ha ido de maravilla...$"
	.endif

DayCare_Text_YourMonHasGrownXLevels::
	.ifdef ENGLISH
	.string "By level, your {STR_VAR_1} has\n"
	.string "grown by {STR_VAR_2}.$"
	.endif
	.ifdef SPANISH
	.string "Tu {STR_VAR_1} ha crecido\n"
	.string "estos niveles: ¡{STR_VAR_2}!$"
	.endif

DayCare_Text_YourPartyIsFull::
	.ifdef ENGLISH
	.string "Your POKéMON party is full.\n"
	.string "Make room, then come see me.$"
	.endif
	.ifdef SPANISH
	.string "Tu equipo POKéMON está lleno.\n"
	.string "Haz un hueco y vuelve a verme.$"
	.endif

DayCare_Text_TakeBackWhichMon::
	.string "どっちの　ポケモンを　ひきとるかい？$"

DayCare_Text_ItWillCostX::
	.ifdef ENGLISH
	.string "If you want your {STR_VAR_1} back,\n"
	.string "it will cost ¥{STR_VAR_2}.$"
	.endif
	.ifdef SPANISH
	.string "Si quieres llevarte a tu\n"
	.string "{STR_VAR_1}, tendrás que pagar\l"
	.string "{STR_VAR_2}¥.$"
	.endif

DayCare_Text_HeresYourMon::
	.ifdef ENGLISH
	.string "Perfect!\n"
	.string "Here's your POKéMON.$"
	.endif
	.ifdef SPANISH
	.string "¡Perfecto!\n"
	.string "Aquí tienes a tu POKéMON.$"
	.endif

DayCare_Text_TookBackMon::
	.ifdef ENGLISH
	.string "{PLAYER} took back {STR_VAR_1} from\n"
	.string "the DAY-CARE LADY.$"
	.endif
	.ifdef SPANISH
	.string "{PLAYER} recogió a {STR_VAR_1} de\n"
	.string "la GUARDERÍA POKéMON.$"
	.endif

DayCare_Text_YouHaveJustOneMon::
	.ifdef ENGLISH
	.string "Oh? But you have just one\n"
	.string "POKéMON.\p"
	.string "Come back another time.$"
	.endif
	.ifdef SPANISH
	.string "Anda, pero si sólo tienes un\n"
	.string "POKéMON...\p"
	.string "Vuelve cuando tengas alguno más.$"
	.endif

DayCare_Text_TakeYourMonBack::
	.ifdef ENGLISH
	.string "Will you take your POKéMON back?$"
	.endif
	.ifdef SPANISH
	.string "¿Quieres recoger un POKéMON?$"
	.endif

DayCare_Text_WhatWillYouBattleWith::
	.ifdef ENGLISH
	.string "If you leave me that POKéMON,\n"
	.string "what will you battle with?\p"
	.string "Come back another time.$"
	.endif
	.ifdef SPANISH
	.string "Si me dejas ese POKéMON, no\n"
	.string "podrás entablar combates.\p"
	.string "Vuelve en otra ocasión.$"
	.endif

DayCare_Text_Huh::
	.ifdef ENGLISH
	.string "Huh?$"
	.endif
	.ifdef SPANISH
	.string "¿Y esto?$"
	.endif
