gFameCheckerFlavorText_ProfOak0::
	.ifdef ENGLISH @ 0x81AD106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}OAK POKéMON RESEARCH LAB$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LABORATORIO POKéMON del PROF. OAK$"
	.endif

gFameCheckerFlavorText_ProfOak1::
	.ifdef ENGLISH @ 0x81AD145
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}To make a complete guide on all\n"
	.string "the POKéMON in the world…\p"
	.string "That was my dream!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Quería hacer una guía de todos\n"
	.string "los POKéMON del mundo...\p"
	.string "¡Era mi sueño!$"
	.endif

gFameCheckerFlavorText_ProfOak2::
	.ifdef ENGLISH @ 0x81AD1BB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK may not look like much,\n"
	.string "but he's the authority on POKéMON.\p"
	.string "Many POKéMON TRAINERS hold him in\n"
	.string "high regard.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡El PROF. OAK es un experto\n"
	.string "en POKéMON!\p"
	.string "¡Es admirado por muchos de los\n"
	.string "ENTRENADORES POKéMON!$"
	.endif

gFameCheckerFlavorText_ProfOak3::
	.ifdef ENGLISH @ 0x81AD258
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK reportedly lives with his\n"
	.string "grandchildren, DAISY and {RIVAL}.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según dicen, el PROF. OAK vive\n"
	.string "con su nieta DALIA y {RIVAL}.$"
	.endif

gFameCheckerFlavorText_ProfOak4::
	.ifdef ENGLISH @ 0x81AD2B9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear OAK's taken a lot of\n"
	.string "interest in you, child.\p"
	.string "That old duff was once tough and\n"
	.string "handsome.\p"
	.string "But that was decades ago.\n"
	.string "He's a shadow of his former self.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He oído que OAK te tiene\n"
	.string "mucha admiración, criatura.\p"
	.string "Ese carcamal era fuerte y guapote,\n"
	.string "pero ya hace mucho de eso.\p"
	.string "Han pasado muchos años, sí.\n"
	.string "Es la sombra de lo que fue.$"
	.endif

gFameCheckerFlavorText_ProfOak5::
	.ifdef ENGLISH @ 0x81AD377
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK is going to have his own\n"
	.string "radio show soon.\p"
	.string "The program will be called PROF.\n"
	.string "OAK'S POKéMON SEMINAR.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}El PROF. OAK va a tener pronto\n"
	.string "su propio programa de radio.\p"
	.string "Será el SEMINARIO sobre POKéMON\n"
	.string "del PROF. OAK.$"
	.endif

gFameCheckerFlavorText_Daisy0::
	.ifdef ENGLISH @ 0x81AD40C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}If you show DAISY your POKéMON,\n"
	.string "she can tell how much it likes you.\p"
	.string "Occasionally, she will even groom\n"
	.string "a POKéMON for you.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Si le enseñas a DALIA tus POKéMON,\n"
	.string "sabrá decirte si les gustas o no.\p"
	.string "Y puede que les dé un lavado de\n"
	.string "cara para que estén presentables.$"
	.endif

gFameCheckerFlavorText_Daisy1::
	.ifdef ENGLISH @ 0x81AD4AE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}But the person who is most liked by\n"
	.string "POKéMON is DAISY, I think.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Pero los POKéMON a quien más\n"
	.string "quieren es a DALIA, creo.$"
	.endif

gFameCheckerFlavorText_Daisy2::
	.ifdef ENGLISH @ 0x81AD516
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}She was gently grooming POKéMON…\n"
	.string "She was a little angel.\p"
	.string "That little girl's name…\n"
	.string "I think it was DAISY.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}La chiquilla cuidaba con mimo a un\n"
	.string "POKéMON. Era un angelito, la cría.\p"
	.string "Lo que no recuerdo es el nombre...\n"
	.string "Bueno, creo que era DALIA.$"
	.endif

gFameCheckerFlavorText_Daisy3::
	.ifdef ENGLISH @ 0x81AD5A7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PROF. OAK reportedly lives with his\n"
	.string "grandchildren, DAISY and {RIVAL}.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según dicen, el PROF. OAK vive\n"
	.string "con su nieta DALIA y {RIVAL}.$"
	.endif

gFameCheckerFlavorText_Daisy4::
	.ifdef ENGLISH @ 0x81AD608
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}A girl from PALLET TOWN, DAISY,\n"
	.string "she enjoys TEA every day.\p"
	.string "She visits the CELADON DEPT. STORE\n"
	.string "to buy some TEA.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Es que allí hay una chica, DALIA,\n"
	.string "que toma TÉ a diario.\p"
	.string "Suele comprarlo en el CENTRO\n"
	.string "COMERCIAL de AZULONA.$"
	.endif

gFameCheckerFlavorText_Daisy5::
	.ifdef ENGLISH @ 0x81AD69F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The Spring POKéMON CONTEST's\n"
	.string "Grand Champion is DAISY OAK of\l"
	.string "PALLET TOWN!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡La campeona de la edición de\n"
	.string "primavera del CONCURSO POKéMON\l"
	.string "es DALIA OAK, de PUEBLO PALETA!$"
	.endif

gFameCheckerFlavorText_Brock0::
	.ifdef ENGLISH @ 0x81AD705
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}PEWTER CITY POKéMON GYM\n"
	.string "LEADER: BROCK\l"
	.string "The Rock-Solid POKéMON TRAINER!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LÍDER del GIMNASIO POKéMON\n"
	.string "de PLATEADA: BROCK\l"
	.string "¡Es fuerte como una roca!$"
	.endif

gFameCheckerFlavorText_Brock1::
	.ifdef ENGLISH @ 0x81AD771
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My rock-hard willpower is evident\n"
	.string "in even my POKéMON.\p"
	.string "My POKéMON are all rock hard and\n"
	.string "have true-grit determination.\p"
	.string "That's right - my POKéMON are all\n"
	.string "the ROCK type!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Creo en la gran resistencia de la\n"
	.string "roca y en la determinación!\p"
	.string "¡Por eso todos mis POKéMON son\n"
	.string "del tipo ROCA!$"
	.endif

gFameCheckerFlavorText_Brock2::
	.ifdef ENGLISH @ 0x81AD840
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}There aren't many serious POKéMON\n"
	.string "TRAINERS here.\p"
	.string "They're all like BUG CATCHERS,\n"
	.string "you know, just hobbyists.\p"
	.string "But PEWTER GYM's BROCK isn't like\n"
	.string "that, not one bit.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡No hay muchos ENTRENADORES\n"
	.string "de POKéMON por aquí!\p"
	.string "¡Todos parecen CAZABICHOS, salvo\n"
	.string "BROCK, del GIMNASIO de PLATEADA!$"
	.endif

gFameCheckerFlavorText_Brock3::
	.ifdef ENGLISH @ 0x81AD908
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK is cool. He's not just tough.\n"
	.string "People like and respect him.\p"
	.string "I want to become a GYM LEADER\n"
	.string "like him.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK es, además de fuerte, guay.\n"
	.string "Todos lo respetan y admiran mucho.\p"
	.string "Yo quiero ser LÍDER de GIMNASIO\n"
	.string "como él.$"
	.endif

gFameCheckerFlavorText_Brock4::
	.ifdef ENGLISH @ 0x81AD99A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hi, I'm excavating for fossils here\n"
	.string "under MT. MOON.\p"
	.string "Sometimes, BROCK of PEWTER GYM\n"
	.string "lends me a hand.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Estoy buscando fósiles en las\n"
	.string "entrañas del MT. MOON.\p"
	.string "A veces me ayuda BROCK,\n"
	.string "del GIMNASIO de PLATEADA.$"
	.endif

gFameCheckerFlavorText_Brock5::
	.ifdef ENGLISH @ 0x81ADA27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BROCK rarely laughs, but is said to\n"
	.string "be unable to stop if he starts.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, BROCK\n"
	.string "casi nunca se ríe, ¡pero una vez\l"
	.string "que empieza, no para!$"
	.endif

gFameCheckerFlavorText_Misty0::
	.ifdef ENGLISH @ 0x81ADA91
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CERULEAN CITY POKéMON GYM\n"
	.string "LEADER: MISTY\l"
	.string "The Tomboyish Mermaid!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LÍDER del GIMNASIO POKéMON\n"
	.string "de CELESTE: MISTY\l"
	.string "¡La sirena distorsionada!$"
	.endif

gFameCheckerFlavorText_Misty1::
	.ifdef ENGLISH @ 0x81ADAF6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My policy is an all-out offensive\n"
	.string "with WATER-type POKéMON!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Mi táctica es la ofensiva total\n"
	.string "con los POKéMON del tipo AGUA!$"
	.endif

gFameCheckerFlavorText_Misty2::
	.ifdef ENGLISH @ 0x81ADB5A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MISTY is a TRAINER who's going to\n"
	.string "keep improving.\p"
	.string "She won't lose to someone like you!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡MISTY es cada vez más fuerte!\p"
	.string "¡No perderá con alguien como tú!$"
	.endif

gFameCheckerFlavorText_Misty3::
	.ifdef ENGLISH @ 0x81ADBD9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Strong TRAINERS and WATER POKéMON\n"
	.string "are common sights in these parts.\p"
	.string "They say that MISTY of the\n"
	.string "CERULEAN GYM trains here.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Por aquí hay muchos ENTRENADORES\n"
	.string "fuertes y POKéMON del tipo AGUA.\p"
	.string "Dicen que MISTY, del GIMNASIO\n"
	.string "de CELESTE, se entrena por aquí.$"
	.endif

gFameCheckerFlavorText_Misty4::
	.ifdef ENGLISH @ 0x81ADC72
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This cape is a famous date spot.\p"
	.string "MISTY, the GYM LEADER, has high\n"
	.string "hopes about this place.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}En este cabo queda mucha gente.\p"
	.string "MISTY, la LÍDER del GIMNASIO,\n"
	.string "suele venir por aquí.$"
	.endif

gFameCheckerFlavorText_Misty5::
	.ifdef ENGLISH @ 0x81ADCEB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}MISTY is said to worship LORELEI\n"
	.string "of the ELITE FOUR.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, MISTY\n"
	.string "adora a LORELEI, del ALTO MANDO.$"
	.endif

gFameCheckerFlavorText_LtSurge0::
	.ifdef ENGLISH @ 0x81ADD3C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}VERMILION CITY POKéMON GYM\n"
	.string "LEADER: LT. SURGE\l"
	.string "The Lightning American!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LÍDER del GIMNASIO POKéMON\n"
	.string "de CARMÍN: LT. SURGE\l"
	.string "¡El Rayo americano!$"
	.endif

gFameCheckerFlavorText_LtSurge1::
	.ifdef ENGLISH @ 0x81ADDA7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I tell you, kid, electric POKéMON\n"
	.string "saved me during the war!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Los POKéMON ELÉCTRICOS\n"
	.string "me salvaron en combate!$"
	.endif

gFameCheckerFlavorText_LtSurge2::
	.ifdef ENGLISH @ 0x81ADE0B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}When I was in the Army, LT. SURGE\n"
	.string "was my strict CO.\p"
	.string "He was a hard taskmaster.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Cuando estaba en el ejército,\n"
	.string "el LT. SURGE era muy estricto!$"
	.endif

gFameCheckerFlavorText_LtSurge3::
	.ifdef ENGLISH @ 0x81ADE82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE was always famous for\n"
	.string "his cautious nature in the Army.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡El LT. SURGE siempre fue muy\n"
	.string "cuidadoso en el ejército!$"
	.endif

gFameCheckerFlavorText_LtSurge4::
	.ifdef ENGLISH @ 0x81ADEEC
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE installed the traps in\n"
	.string "the GYM himself.\p"
	.string "He set up double locks everywhere.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE colocó cerraduras\n"
	.string "dobles en el GIMNASIO.\p"
	.string "¡Las puso por todos sitios!$"
	.endif

gFameCheckerFlavorText_LtSurge5::
	.ifdef ENGLISH @ 0x81ADF6A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LT. SURGE is rumored to have been\n"
	.string "a pilot while home in America.\p"
	.string "He used the electricity generated\n"
	.string "by POKéMON to power his plane.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, LT. SURGE\n"
	.string "era piloto cuando vivía en Estados\l"
	.string "Unidos.\p"
	.string "Y se valía de la electricidad\n"
	.string "generada por sus POKéMON\l"
	.string "para poner en marcha su avión.$"
	.endif

gFameCheckerFlavorText_Erika0::
	.ifdef ENGLISH @ 0x81AE009
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CELADON CITY POKéMON GYM\n"
	.string "LEADER: ERIKA\l"
	.string "The Nature-Loving Princess!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LÍDER del GIMNASIO POKéMON\n"
	.string "de AZULONA: ERIKA\l"
	.string "¡Princesa amante de la Naturaleza!$"
	.endif

gFameCheckerFlavorText_Erika1::
	.ifdef ENGLISH @ 0x81AE072
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am a student of the art of\n"
	.string "flower arranging.\p"
	.string "My POKéMON are solely of the\n"
	.string "GRASS type.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Enseño el arte de las flores.\n"
	.string "Mis POKéMON son del tipo PLANTA.$"
	.endif

gFameCheckerFlavorText_Erika2::
	.ifdef ENGLISH @ 0x81AE0F3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Our LEADER ERIKA might be quiet,\n"
	.string "but she's famous around here.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡ERIKA, nuestra LÍDER, puede\n"
	.string "parecer muy tranquila, pero es muy\l"
	.string "hábil!$"
	.endif

gFameCheckerFlavorText_Erika3::
	.ifdef ENGLISH @ 0x81AE15B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We only use GRASS-type POKéMON at\n"
	.string "our GYM.\p"
	.string "Why? We also use them for making\n"
	.string "flower arrangements!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡En nuestro GIMNASIO sólo luchamos\n"
	.string "con POKéMON del tipo PLANTA!\p"
	.string "¡Y también los usamos para hacer\n"
	.string "adornos florales!$"
	.endif

gFameCheckerFlavorText_Erika4::
	.ifdef ENGLISH @ 0x81AE1E5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I would never collect POKéMON if\n"
	.string "they were unattractive.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}No coleccionaría POKéMON si\n"
	.string "fueran feos.$"
	.endif

gFameCheckerFlavorText_Erika5::
	.ifdef ENGLISH @ 0x81AE247
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Rumor has it that if you peek into\n"
	.string "CELADON GYM, you can often\l"
	.string "see ERIKA snoozing.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, es fácil\n"
	.string "ver a ERIKA echándose una siesta\l"
	.string "en el GIMNASIO de AZULONA.$"
	.endif

gFameCheckerFlavorText_Koga0::
	.ifdef ENGLISH @ 0x81AE2B6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}FUCHSIA CITY POKéMON GYM\n"
	.string "LEADER: KOGA\l"
	.string "The Poisonous Ninja Master$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LÍDER del GIMNASIO POKéMON\n"
	.string "de FUCSIA: KOGA\l"
	.string "El venenoso maestro ninja.$"
	.endif

gFameCheckerFlavorText_Koga1::
	.ifdef ENGLISH @ 0x81AE31D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Despair to the creeping horror of\n"
	.string "POISON-type POKéMON!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Adoro a mis temidos POKéMON\n"
	.string "del tipo VENENO!$"
	.endif

gFameCheckerFlavorText_Koga2::
	.ifdef ENGLISH @ 0x81AE37D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Even though I've lost, I will keep\n"
	.string "training according to the teachings\l"
	.string "of KOGA, my ninja master.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Seguiré entrenándome con KOGA,\n"
	.string "mi maestro ninja!$"
	.endif

gFameCheckerFlavorText_Koga3::
	.ifdef ENGLISH @ 0x81AE407
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My father is the GYM LEADER of\n"
	.string "this town.\p"
	.string "I'm training to use POISON POKéMON\n"
	.string "as well as my father.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mi padre es el LÍDER del GIMNASIO\n"
	.string "de este pueblo.\p"
	.string "Yo me estoy entrenando para usar\n"
	.string "POKéMON del tipo VENENO igual\l"
	.string "que hace mi padre.$"
	.endif

gFameCheckerFlavorText_Koga4::
	.ifdef ENGLISH @ 0x81AE48D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}KOGA is said to have a thorough\n"
	.string "knowledge of medicine.\p"
	.string "He even concocts medicine to nurse\n"
	.string "his POKéMON to health.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, KOGA\n"
	.string "tiene grandes conocimientos\l"
	.string "de medicina.\p"
	.string "Incluso elabora las medicinas\n"
	.string "que sus POKéMON necesitan.$"
	.endif

gFameCheckerFlavorText_Koga5::
	.ifdef ENGLISH @ 0x81AE51B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The SAFARI ZONE's huge, wouldn't\n"
	.string "you say?\p"
	.string "FUCHSIA's GYM LEADER, KOGA, \n"
	.string "patrols the grounds every so often.\p"
	.string "Thanks to him, we can play here\n"
	.string "knowing that we're safe.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}La ZONA del SAFARI es gigante,\n"
	.string "¿no te parece?\p"
	.string "El LÍDER del GIMNASIO de FUCSIA,\n"
	.string "KOGA, viene con mucha frecuencia\l"
	.string "por aquí.\p"
	.string "Gracias a él, podemos jugar aquí\n"
	.string "sin miedo.$"
	.endif

gFameCheckerFlavorText_Sabrina0::
	.ifdef ENGLISH @ 0x81AE5E8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SAFFRON CITY POKéMON GYM\n"
	.string "LEADER: SABRINA\l"
	.string "The Master of PSYCHIC POKéMON!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LÍDER del GIMNASIO POKéMON\n"
	.string "de AZAFRÁN: SABRINA\l"
	.string "¡Genio de los POKéMON PSÍQUICOS!$"
	.endif

gFameCheckerFlavorText_Sabrina1::
	.ifdef ENGLISH @ 0x81AE656
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You know about a girl GYM LEADER\n"
	.string "in SAFFRON CITY?\p"
	.string "She uses PSYCHIC-type POKéMON,\n"
	.string "right?$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¿Sabes algo de la LÍDER del\n"
	.string "GIMNASIO de AZAFRÁN?\p"
	.string "Usa POKéMON del tipo PSÍQUICO,\n"
	.string "¿no?$"
	.endif

gFameCheckerFlavorText_Sabrina2::
	.ifdef ENGLISH @ 0x81AE6D7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I have had psychic powers since\n"
	.string "I was a child.\p"
	.string "It started when a spoon I\n"
	.string "carelessly tossed, bent.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Tengo poderes psíquicos desde\n"
	.string "que era niña!\p"
	.string "Primero aprendí a doblar cucharas\n"
	.string "con la mente.$"
	.endif

gFameCheckerFlavorText_Sabrina3::
	.ifdef ENGLISH @ 0x81AE762
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I dislike battling, but if you wish,\n"
	.string "I will show you my powers!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Odio luchar, pero si quieres\n"
	.string "puedo enseñarte mis poderes!$"
	.endif

gFameCheckerFlavorText_Sabrina4::
	.ifdef ENGLISH @ 0x81AE7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}People say that SABRINA can\n"
	.string "communicate with her POKéMON\l"
	.string "during battle without speaking.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, SABRINA\n"
	.string "se comunica en combate con sus\l"
	.string "POKéMON, sin necesidad de hablar.$"
	.endif

gFameCheckerFlavorText_Sabrina5::
	.ifdef ENGLISH @ 0x81AE841
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}SABRINA just wiped out the KARATE\n"
	.string "MASTER next door.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡SABRINA ganó al MAESTRO de\n"
	.string "KARATE de la puerta de al lado!$"
	.endif

gFameCheckerFlavorText_Blaine0::
	.ifdef ENGLISH @ 0x81AE89E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CINNABAR ISLAND POKéMON GYM\n"
	.string "LEADER: BLAINE\l"
	.string "The Hotheaded Quiz Master!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LÍDER del GIMNASIO POKéMON\n"
	.string "de CANELA: BLAINE\l"
	.string "¡El maestro de los acertijos!$"
	.endif

gFameCheckerFlavorText_Blaine1::
	.ifdef ENGLISH @ 0x81AE90A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My fiery POKéMON are all rough\n"
	.string "and ready with intense heat!\p"
	.string "They incinerate all challengers!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Mis feroces POKéMON de FUEGO\n"
	.string "quemarán a quien me desafíe!$"
	.endif

gFameCheckerFlavorText_Blaine2::
	.ifdef ENGLISH @ 0x81AE990
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Our LEADER, BLAINE, became lost\n"
	.string "in the mountains but good.\p"
	.string "Night fell when a fiery bird\n"
	.string "POKéMON appeared.\p"
	.string "Its light allowed BLAINE to find\n"
	.string "his way down safely.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BLAINE se perdió en la montaña,\n"
	.string "y se hizo de noche...\p"
	.string "¡Pero apareció un feroz pájaro\n"
	.string "POKéMON...!\p"
	.string "¡E iluminó el camino a BLAINE\n"
	.string "para que pudiera bajar!$"
	.endif

gFameCheckerFlavorText_Blaine3::
	.ifdef ENGLISH @ 0x81AEA59
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}CINNABAR GYM's BLAINE is quite the\n"
	.string "odd fellow.\p"
	.string "He's lived on the island since way\n"
	.string "before the LAB was built.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BLAINE, del GIMNASIO CANELA,\n"
	.string "es un hombre raro que lleva años\l"
	.string "viviendo aquí.\p"
	.string "Antes de que construyeran el\n"
	.string "LABORATORIO, ya vivía aquí.$"
	.endif

gFameCheckerFlavorText_Blaine4::
	.ifdef ENGLISH @ 0x81AEAEE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}It's a photo of BLAINE and\n"
	.string "MR. FUJI.\p"
	.string "They're standing shoulder to\n"
	.string "shoulder with big grins.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Y esto?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Una foto de BLAINE\n"
	.string "y el SR. FUJI...\p"
	.string "Aparecen juntos con una sonrisa\n"
	.string "de oreja a oreja.$"
	.endif

gFameCheckerFlavorText_Blaine5::
	.ifdef ENGLISH @ 0x81AEB69
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BLAINE is said to remove his dark\n"
	.string "shades only when he is thinking up\l"
	.string "new quiz questions.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, BLAINE\n"
	.string "sólo se quita las gafas de sol\l"
	.string "cuando contesta a preguntas.$"
	.endif

gFameCheckerFlavorText_Lorelei0::
	.ifdef ENGLISH @ 0x81AEBDF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am LORELEI of the ELITE FOUR.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Yo soy LORELEI, del ALTO MANDO!$"
	.endif

gFameCheckerFlavorText_Lorelei1::
	.ifdef ENGLISH @ 0x81AEC28
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}No one can best me when it comes\n"
	.string "to icy POKéMON.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Nadie me supera con los POKéMON\n"
	.string "que congelan!$"
	.endif

gFameCheckerFlavorText_Lorelei2::
	.ifdef ENGLISH @ 0x81AEC82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Where was this person born?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We've had a great and powerful\n"
	.string "TRAINER grow up on this island.\p"
	.string "I bet even you'd know her.\n"
	.string "It's LORELEI of the ELITE FOUR!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}En esta isla nació y creció una\n"
	.string "ENTRENADORA fuerte y poderosa\l"
	.string "como pocas.\p"
	.string "Seguro que la conoces, se llama\n"
	.string "LORELEI y es del ALTO MANDO.$"
	.endif

gFameCheckerFlavorText_Lorelei3::
	.ifdef ENGLISH @ 0x81AED27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Known for her logical, calculated,\n"
	.string "and cool battling style, LORELEI\l"
	.string "has a surprising secret!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Lo que sí se conoce de ella es\n"
	.string "su estilo de lucha elegante, único\l"
	.string "y calculador.$"
	.endif

gFameCheckerFlavorText_Lorelei4::
	.ifdef ENGLISH @ 0x81AEDAA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Did you know that LORELEI has lots\n"
	.string "and lots of stuffed dolls?\p"
	.string "Every time she comes back to\n"
	.string "FOUR ISLAND, her collection grows!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¿Sabías que LORELEI tiene un\n"
	.string "montón de muñecos de peluche?\p"
	.string "¡Cada vez que vuelve a ISLA\n"
	.string "QUARTA, aumenta la colección!$"
	.endif

gFameCheckerFlavorText_Lorelei5::
	.ifdef ENGLISH @ 0x81AEE51
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The LAPRAS she has, I imagine it\n"
	.string "to be the one she met as a child.\p"
	.string "I believe it was in ICEFALL CAVE\n"
	.string "that she caught it.\p"
	.string "Perhaps that POKéMON has been with\n"
	.string "her ever since.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Creo que el LAPRAS que tiene,\n"
	.string "es el mismo que atrapó de pequeña.\p"
	.string "Yo creo que se hizo con él\n"
	.string "en la CUEVA GLACIADA...\p"
	.string "Me parece que lo tiene desde\n"
	.string "entonces.$"
	.endif

gFameCheckerFlavorText_Bruno0::
	.ifdef ENGLISH @ 0x81AEF25
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am BRUNO of the ELITE FOUR!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Yo soy BRUNO, del ALTO MANDO!$"
	.endif

gFameCheckerFlavorText_Bruno1::
	.ifdef ENGLISH @ 0x81AEF6C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I've lived and trained with my\n"
	.string "fighting POKéMON!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Siempre he vivido con mis POKéMON\n"
	.string "del tipo LUCHA y los he entrenado\l"
	.string "yo mismo!$"
	.endif

gFameCheckerFlavorText_Bruno2::
	.ifdef ENGLISH @ 0x81AEFC6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO apparently joined the ELITE\n"
	.string "FOUR out of his burning ambition to\l"
	.string "battle the best TRAINERS.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, BRUNO\n"
	.string "se unió al ALTO MANDO para luchar\l"
	.string "contra los mejores ENTRENADORES.$"
	.endif

gFameCheckerFlavorText_Bruno3::
	.ifdef ENGLISH @ 0x81AF04C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO, who's a senior ahead of me,\n"
	.string "visits the SPA on occasion.\p"
	.string "He comes to rehab injuries, both\n"
	.string "his own and his POKéMON's.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BRUNO, ejemplo al que sigo, viene\n"
	.string "al BALNEARIO cada vez que puede.\p"
	.string "No sólo para recuperarse él,\n"
	.string "también lo hace por sus POKéMON.$"
	.endif

gFameCheckerFlavorText_Bruno4::
	.ifdef ENGLISH @ 0x81AF0F0
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He's one of the ELITE FOUR.\n"
	.string "His name is BRUNO.\p"
	.string "He went away disappointed when he\n"
	.string "found out that they were all sold\l"
	.string "out of Rage Candybars.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Era uno de los miembros del ALTO\n"
	.string "MANDO. Se llamaba BRUNO.\p"
	.string "Pero se fue decepcionado cuando\n"
	.string "vio que no quedaban bastones de\l"
	.string "caramelo superfuertes.$"
	.endif

gFameCheckerFlavorText_Bruno5::
	.ifdef ENGLISH @ 0x81AF19A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Even BRUNO…\n"
	.string "He trained with a fellow by the\l"
	.string "name of BRAWLY before.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Fíjate en BRUNO...\n"
	.string "Él se entrenó con un tal MARCIAL.$"
	.endif

gFameCheckerFlavorText_Agatha0::
	.ifdef ENGLISH @ 0x81AF200
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am AGATHA of the ELITE FOUR.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Yo soy AGATHA, del ALTO MANDO!$"
	.endif

gFameCheckerFlavorText_Agatha1::
	.ifdef ENGLISH @ 0x81AF248
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}AGATHA's GHOST-type POKéMON are\n"
	.string "horrifically terrifying in toughness.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Los POKéMON del tipo FANTASMA\n"
	.string "de AGATHA son escalofriantemente\l"
	.string "fuertes.$"
	.endif

gFameCheckerFlavorText_Agatha2::
	.ifdef ENGLISH @ 0x81AF2B7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}That old lady's also got a really\n"
	.string "short fuse, too.\p"
	.string "It doesn't take anything to get\n"
	.string "that scary lady hollering.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Además ¡no sabes el genio que\n"
	.string "tiene la señora!\p"
	.string "¡Como empiece a gritar, lo llevas\n"
	.string "claro!$"
	.endif

gFameCheckerFlavorText_Agatha3::
	.ifdef ENGLISH @ 0x81AF34E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In her youth, AGATHA and PROF.\n"
	.string "OAK were rivals who vied for\l"
	.string "supremacy as TRAINERS.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, AGATHA\n"
	.string "y el PROF. OAK estuvieron\p"
	.string "enfrentados durante su formación\n"
	.string "como ENTRENADORES.$"
	.endif

gFameCheckerFlavorText_Agatha4::
	.ifdef ENGLISH @ 0x81AF3BE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear OAK's taken a lot of\n"
	.string "interest in you, child.\p"
	.string "That old duff was once tough and\n"
	.string "handsome.\p"
	.string "But that was decades ago.\n"
	.string "He's a shadow of his former self.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He oído que OAK te tiene\n"
	.string "mucha admiración, criatura.\p"
	.string "Ese carcamal era fuerte y guapote,\n"
	.string "pero ya hace mucho de eso.\p"
	.string "Han pasado muchos años, sí.\n"
	.string "Es la sombra de lo que fue.$"
	.endif

gFameCheckerFlavorText_Agatha5::
	.ifdef ENGLISH @ 0x81AF47C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Take AGATHA, for example.\p"
	.string "She set a record for being the\n"
	.string "oldest-ever ELITE FOUR member.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mira a AGATHA, por ejemplo.\p"
	.string "Es el miembro de más edad\n"
	.string "del ALTO MANDO.$"
	.endif

gFameCheckerFlavorText_Lance0::
	.ifdef ENGLISH @ 0x81AF4FD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I lead the ELITE FOUR.\p"
	.string "You can call me LANCE the dragon\n"
	.string "TRAINER.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Dirijo al ALTO MANDO!\p"
	.string "¡Puedes llamarme LANCE,\n"
	.string "el ENTRENADOR de dragones!$"
	.endif

gFameCheckerFlavorText_Lance1::
	.ifdef ENGLISH @ 0x81AF567
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You know that dragons are\n"
	.string "mythical POKéMON.\p"
	.string "They're hard to catch and raise,\n"
	.string "but their powers are superior.\p"
	.string "They're virtually indestructible.\n"
	.string "There's no being clever with them.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Los dragones son míticos POKéMON!\p"
	.string "¡Son difíciles de capturar y\n"
	.string "entrenar, pero sus poderes son\l"
	.string "muy superiores!\p"
	.string "¡Son casi invencibles!$"
	.endif

gFameCheckerFlavorText_Lance2::
	.ifdef ENGLISH @ 0x81AF641
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He stands for justice!\n"
	.string "He's cool, and yet passionate!\l"
	.string "He's the greatest, LANCE!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Es justo!\n"
	.string "¡Es admirado!\l"
	.string "¡Todos quieren estar a su lado!$"
	.endif

gFameCheckerFlavorText_Lance3::
	.ifdef ENGLISH @ 0x81AF6BA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}We have a customer, LANCE, who\n"
	.string "occasionally comes.\p"
	.string "He always buys capes.\p"
	.string "I wonder… Does he have many\n"
	.string "identical capes at home?$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tenemos un cliente habitual, LANCE,\n"
	.string "que suele comprar capas.\p"
	.string "La verdad es que debe de tener\n"
	.string "un montón iguales en su casa...$"
	.endif

gFameCheckerFlavorText_Lance4::
	.ifdef ENGLISH @ 0x81AF758
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}LANCE's grandfather is thought to\n"
	.string "be the elder of a famous clan of\l"
	.string "dragon masters.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Según fuentes cercanas, quien fundó\n"
	.string "el clan de los maestros del tipo\l"
	.string "DRAGÓN fue el abuelo de LANCE.$"
	.endif

gFameCheckerFlavorText_Lance5::
	.ifdef ENGLISH @ 0x81AF7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}From what I've heard, LANCE has\n"
	.string "a cousin who's a GYM LEADER\l"
	.string "somewhere far away.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Por lo que sé, un primo de LANCE\n"
	.string "es también LÍDER de un GIMNASIO\l"
	.string "de por ahí.$"
	.endif

gFameCheckerFlavorText_Bill0::
	.ifdef ENGLISH @ 0x81AF83E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}After all, BILL's world-famous as a\n"
	.string "POKéMANIAC.\p"
	.string "He invented the POKéMON Storage\n"
	.string "System on PC, too.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Él fue también el que inventó el\n"
	.string "Sistema de Almacenamiento de\l"
	.string "POKéMON para PC!$"
	.endif

gFameCheckerFlavorText_Bill1::
	.ifdef ENGLISH @ 0x81AF8CA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL has lots of POKéMON!\n"
	.string "He collects rare ones, too!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡BILL tiene muchísimos POKéMON!\n"
	.string "¡Y algunos son muy raros!$"
	.endif

gFameCheckerFlavorText_Bill2::
	.ifdef ENGLISH @ 0x81AF929
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He's my grandson!\p"
	.string "He always liked collecting things,\n"
	.string "even as a child!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Es mi nieto!\p"
	.string "¡Le gustaba coleccionar cosas\n"
	.string "desde niño!$"
	.endif

gFameCheckerFlavorText_Bill3::
	.ifdef ENGLISH @ 0x81AF998
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL is a POKéMANIAC, so he loves\n"
	.string "every kind.\p"
	.string "Apparently, the first one he caught\n"
	.string "was an ABRA.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué POKéMON prefiere?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL es un POKéMANÍACO,\n"
	.string "a él le gustan todos.\p"
	.string "Creo que el primero que atrapó\n"
	.string "fue un ABRA.$"
	.endif

gFameCheckerFlavorText_Bill4::
	.ifdef ENGLISH @ 0x81AFA20
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL's hometown is GOLDENROD CITY,\n"
	.string "where his folks still live.\p"
	.string "I've heard that it's quite the\n"
	.string "festive, bustling city.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BILL es de CIUDAD TRIGAL,\n"
	.string "donde aún viven sus amigos.\p"
	.string "Dicen que es una ciudad muy\n"
	.string "alegre y animada.$"
	.endif

gFameCheckerFlavorText_Bill5::
	.ifdef ENGLISH @ 0x81AFAB9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Apparently, BILL simply can't\n"
	.string "stomach milk at all.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Creo que BILL no tolera muy bien\n"
	.string "la leche. Le da dolor de estómago.$"
	.endif

gFameCheckerFlavorText_MrFuji0::
	.ifdef ENGLISH @ 0x81AFB0C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He's really kind.\p"
	.string "He looks after abandoned and\n"
	.string "orphaned POKéMON.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Es muy amable!\p"
	.string "¡Cuida de los POKéMON huérfanos\n"
	.string "y abandonados!$"
	.endif

gFameCheckerFlavorText_MrFuji1::
	.ifdef ENGLISH @ 0x81AFB76
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}This old guy marched right up to\n"
	.string "our HIDEOUT.\p"
	.string "Then, he starts ranting about how\n"
	.string "TEAM ROCKET's abusing POKéMON.\p"
	.string "So, we're just talking it over as\n"
	.string "adults.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}El tipo, que ya tiene unos años,\n"
	.string "se plantó en nuestra GUARIDA.\p"
	.string "Y empezó a decir que estábamos\n"
	.string "haciendo daño a los POKéMON.\p"
	.string "¡La cosa es para tomársela\n"
	.string "en serio!$"
	.endif

gFameCheckerFlavorText_MrFuji2::
	.ifdef ENGLISH @ 0x81AFC38
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}POKéMON FAN MAGAZINE\n"
	.string "Monthly Grand Prize Drawing!\p"
	.string "The application form is…\p"
	.string "Gone! It's been clipped out.\n"
	.string "Someone must have applied already.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}REVISTA POKéMON\n"
	.string "¡Gran concurso mensual de dibujo\l"
	.string "POKéMON!\p"
	.string "El formulario de inscripción está\n"
	.string "en...\p"
	.string "¡Anda, se lo han llevado!\n"
	.string "¡Se ha debido de inscribir alguien!$"
	.endif

gFameCheckerFlavorText_MrFuji3::
	.ifdef ENGLISH @ 0x81AFCE9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}There's a rumor…\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I hear that MR. FUJI's not from\n"
	.string "these parts originally, either.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He oído que el SR. FUJI tampoco\n"
	.string "es de por aquí.$"
	.endif

gFameCheckerFlavorText_MrFuji4::
	.ifdef ENGLISH @ 0x81AFD49
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}It's a photo of BLAINE and\n"
	.string "MR. FUJI.\p"
	.string "They're standing shoulder to\n"
	.string "shoulder with big grins.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Y esto?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Una foto de BLAINE\n"
	.string "y el SR. FUJI...\p"
	.string "Aparecen juntos con una sonrisa\n"
	.string "de oreja a oreja.$"
	.endif

gFameCheckerFlavorText_MrFuji5::
	.ifdef ENGLISH @ 0x81AFDC4
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Editor: The shy MR. FUJI turned\n"
	.string "down our interview requests.\p"
	.string "He is a kindly man who is adored\n"
	.string "and respected in LAVENDER TOWN.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ponía aquí?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Nota del editor: el tímido\n"
	.string "SR. FUJI no ha querido contestar\l"
	.string "a nuestras preguntas.\p"
	.string "Con todo, hay que decir que es una\n"
	.string "persona muy querida en PUEBLO\l"
	.string "LAVANDA.$"
	.endif

gFameCheckerFlavorText_Giovanni0::
	.ifdef ENGLISH @ 0x81AFE68
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TEAM ROCKET captures POKéMON from\n"
	.string "around the world.\p"
	.string "They're important tools for keeping\n"
	.string "our criminal enterprise going.\p"
	.string "I am the leader, GIOVANNI!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡El TEAM ROCKET necesita los\n"
	.string "POKéMON para financiar sus\l"
	.string "malvados planes!\p"
	.string "¡Yo soy GIOVANNI, su líder!$"
	.endif

gFameCheckerFlavorText_Giovanni1::
	.ifdef ENGLISH @ 0x81AFF23
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Favorite kind of POKéMON?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Those thugs that took over our\n"
	.string "building…\p"
	.string "Their BOSS said he was looking for\n"
	.string "strong POKéMON.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Los tipejos esos que se apoderaron\n"
	.string "de nuestro edificio...\p"
	.string "Su JEFE dijo que estaba buscando\n"
	.string "POKéMON fuertes.$"
	.endif

gFameCheckerFlavorText_Giovanni2::
	.ifdef ENGLISH @ 0x81AFFA8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What is this person like?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}TEAM ROCKET's BOSS is terribly\n"
	.string "cruel!\p"
	.string "To him, POKéMON are just tools to\n"
	.string "be used.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡El JEFE del TEAM ROCKET es muy\n"
	.string "cruel!\p"
	.string "Sólo quiere a los POKéMON para\n"
	.string "luchar.$"
	.endif

gFameCheckerFlavorText_Giovanni3::
	.ifdef ENGLISH @ 0x81B0022
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Welcome to my hideout!\p"
	.string "It shall be so until I can restore\n"
	.string "TEAM ROCKET to its former glory.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Ésta es mi guarida!\p"
	.string "¡Quería volver a formar al TEAM\n"
	.string "ROCKET desde aquí!$"
	.endif

gFameCheckerFlavorText_Giovanni4::
	.ifdef ENGLISH @ 0x81B00A6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}What does this person do?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Blow me away! GIOVANNI was the\n"
	.string "GYM LEADER of VIRIDIAN?$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¿Qué dices? ¿Que GIOVANNI era\n"
	.string "el LÍDER del GIMNASIO?$"
	.endif

gFameCheckerFlavorText_Giovanni5::
	.ifdef ENGLISH @ 0x81B0106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Family and friends?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You… You're not GIOVANNI's kid,\n"
	.string "are you?\p"
	.string "No, that can't be right.\n"
	.string "GIOVANNI's kid has red hair.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}¿Qué ha dicho esta persona?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tú... tú no eres el retoño\n"
	.string "de GIOVANNI, ¿verdad?\p"
	.string "No, no puede ser, el retoño\n"
	.string "de GIOVANNI es pelirrojo.$"
	.endif


gFameCheckerPersonName_ProfOak::
	.ifdef ENGLISH @ 0x81B0188
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PROF. OAK$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}PROF. OAK$"
	.endif

gFameCheckerPersonQuote_ProfOak::
	.ifdef ENGLISH @ 0x81B0198
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: PROF. OAK\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Why do POKéMON compete and battle\n"
	.string "so hard for you?\p"
	.string "They do so because they can see\n"
	.string "the love and trust you have\l"
	.string "towards POKéMON.\p"
	.string "Never forget that.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario del PROF. OAK\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¿Sabes por qué luchan y compiten\n"
	.string "tanto por ti los POKéMON?\p"
	.string "Porque ven el cariño que tienes\n"
	.string "hacia los POKéMON y lo que confías\l"
	.string "en ellos.\p"
	.string "Tenlo siempre en cuenta.$"
	.endif

gFameCheckerPersonName_Daisy::
	.ifdef ENGLISH @ 0x81B0251
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}DAISY$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}DALIA$"
	.endif

gFameCheckerPersonQuote_Daisy::
	.ifdef ENGLISH @ 0x81B025D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: DAISY\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}While I was comfortably enjoying\n"
	.string "my tea breaks, you've grown very\l"
	.string "skilled and powerful.\p"
	.string "I hope you'll remain a good rival\n"
	.string "to my little brother.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de DALIA para {PLAYER}:\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Mientras hacía una pausa para\n"
	.string "tomar té, he visto que te has\l"
	.string "vuelto muy fuerte y hábil.\p"
	.string "Espero que sigas siendo la persona\n"
	.string "ideal para luchar contra mi\l"
	.string "hermano pequeño.$"
	.endif

gFameCheckerPersonName_Brock::
	.ifdef ENGLISH @ 0x81B030F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BROCK$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BROCK$"
	.endif

gFameCheckerPersonQuote_Brock::
	.ifdef ENGLISH @ 0x81B031B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BROCK\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}In this big world of ours, there\n"
	.string "must be many tough TRAINERS.\p"
	.string "Let's both keep training and\n"
	.string "making ourselves stronger!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de BROCK para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}En este mundo nuestro tan grande,\n"
	.string "hacen falta fuertes ENTRENADORES.\p"
	.string "¡Debemos seguir entrenándonos\n"
	.string "para ser cada vez más fuertes!$"
	.endif

gFameCheckerPersonName_Misty::
	.ifdef ENGLISH @ 0x81B03B3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MISTY$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MISTY$"
	.endif

gFameCheckerPersonQuote_Misty::
	.ifdef ENGLISH @ 0x81B03BF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: MISTY\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I'm going to keep training here at\n"
	.string "this GYM.\p"
	.string "When I get better, I'd love to hit\n"
	.string "the road and travel.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de MISTY para {PLAYER}:\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Voy a seguir entrenándome aquí\n"
	.string "en el GIMNASIO.\p"
	.string "Cuando perfeccione mi técnica,\n"
	.string "me iré a viajar por ahí.$"
	.endif

gFameCheckerPersonName_LtSurge::
	.ifdef ENGLISH @ 0x81B0446
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LT. SURGE$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LT. SURGE$"
	.endif

gFameCheckerPersonQuote_LtSurge::
	.ifdef ENGLISH @ 0x81B0456
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LT. SURGE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, kid!\n"
	.string "You electrified me in our battle!\p"
	.string "I didn't know that there were\n"
	.string "gutsy TRAINERS like you.\p"
	.string "It made me change my mind about\n"
	.string "you!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de LT. SURGE\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Eh, personaje!\n"
	.string "¡Me quedé molido tras el combate!\p"
	.string "No pensé que hubiera ENTRENADORES\n"
	.string "tan valientes como tú.\p"
	.string "Conseguiste que cambiara mi opinión\n"
	.string "sobre ti.$"
	.endif

gFameCheckerPersonName_Erika::
	.ifdef ENGLISH @ 0x81B0504
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ERIKA$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ERIKA$"
	.endif

gFameCheckerPersonQuote_Erika::
	.ifdef ENGLISH @ 0x81B0510
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: ERIKA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I am so glad that there are strong\n"
	.string "TRAINERS like you.\p"
	.string "That awareness alone inspires and\n"
	.string "motivates me to try harder.\p"
	.string "Please visit me again.\n"
	.string "Zzz…$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de ERIKA\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Estoy encantada de que haya\n"
	.string "ENTRENADORES fuertes como tú.\p"
	.string "Me motiva y me ayuda a superarme\n"
	.string "a mí misma.\p"
	.string "Espero verte de nuevo.\n"
	.string "Zzz...$"
	.endif

gFameCheckerPersonName_Koga::
	.ifdef ENGLISH @ 0x81B05C2
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}KOGA$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}KOGA$"
	.endif

gFameCheckerPersonQuote_Koga::
	.ifdef ENGLISH @ 0x81B05CD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: KOGA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}You and I, we must both set our\n"
	.string "sights higher and work towards\l"
	.string "meeting our challenges.\p"
	.string "Now, I must go train my daughter.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de KOGA\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Tú y yo deberíamos exigirnos\n"
	.string "más y entrenarnos con empeño para\l"
	.string "cumplir lo que nos propongamos.\p"
	.string "Bueno, voy a entrenar a mi hija.$"
	.endif

gFameCheckerPersonName_Sabrina::
	.ifdef ENGLISH @ 0x81B0667
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SABRINA$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SABRINA$"
	.endif

gFameCheckerPersonQuote_Sabrina::
	.ifdef ENGLISH @ 0x81B0675
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: SABRINA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The love you have towards your\n"
	.string "POKéMON…\p"
	.string "It was a power that was never\n"
	.string "bested by my psychic power.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de SABRINA\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}El cariño que les tienes a tus\n"
	.string "POKéMON...\p"
	.string "Tuvo más fuerza que mis poderes\n"
	.string "psíquicos.$"
	.endif

gFameCheckerPersonName_Blaine::
	.ifdef ENGLISH @ 0x81B06FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BLAINE$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BLAINE$"
	.endif

gFameCheckerPersonQuote_Blaine::
	.ifdef ENGLISH @ 0x81B0708
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BLAINE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}My fire POKéMON!\n"
	.string "They'll become even more powerful!\p"
	.string "And now, a quiz. How many kinds of\n"
	.string "FIRE-type POKéMON are there?$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de BLAINE\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Mis POKéMON de fuego van\n"
	.string "a alcanzar una fuerza increíble!\p"
	.string "A ver, una pregunta: ¿cuántos\n"
	.string "POKéMON del tipo FUEGO hay?$"
	.endif

gFameCheckerPersonName_Lorelei::
	.ifdef ENGLISH @ 0x81B079F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LORELEI$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LORELEI$"
	.endif

gFameCheckerPersonQuote_Lorelei::
	.ifdef ENGLISH @ 0x81B07AD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LORELEI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I needed to thank you for your\n"
	.string "help.\p"
	.string "But that has nothing to do with our\n"
	.string "battles.\p"
	.string "You'd better watch out next time!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de LORELEI\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Estoy muy agradecida por tu ayuda.\p"
	.string "¡Pero no te confíes, en combate\n"
	.string "no pienso pasarte ni una!$"
	.endif

gFameCheckerPersonName_Bruno::
	.ifdef ENGLISH @ 0x81B0845
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BRUNO$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BRUNO$"
	.endif

gFameCheckerPersonQuote_Bruno::
	.ifdef ENGLISH @ 0x81B0851
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BRUNO\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}The super power of your POKéMON\n"
	.string "and you I've experienced myself.\p"
	.string "Next time, maybe I should show you\n"
	.string "how to train yourself.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de BRUNO\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}He aprendido mucho de la fuerza\n"
	.string "que tenéis tú y tus POKéMON...\p"
	.string "¡La próxima vez seré yo quien\n"
	.string "te enseñe a ti!$"
	.endif

gFameCheckerPersonName_Agatha::
	.ifdef ENGLISH @ 0x81B08EE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AGATHA$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}AGATHA$"
	.endif

gFameCheckerPersonQuote_Agatha::
	.ifdef ENGLISH @ 0x81B08FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: AGATHA\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}When you grow older, don't you\n"
	.string "dare go soft like that coot OAK!\p"
	.string "Be like me and keep battling on!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de AGATHA\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Espero que no te vuelvas como\n"
	.string "el blandengue de OAK con los años.\p"
	.string "¡Sigue mi ejemplo y no dejes\n"
	.string "de luchar!$"
	.endif

gFameCheckerPersonName_Lance::
	.ifdef ENGLISH @ 0x81B097F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LANCE$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}LANCE$"
	.endif

gFameCheckerPersonQuote_Lance::
	.ifdef ENGLISH @ 0x81B098B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: LANCE\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}I'm considering going back to my\n"
	.string "hometown.\p"
	.string "I want to retrain my DRAGON-type\n"
	.string "POKéMON and strengthen them.\p"
	.string "I'd like to invite you to my\n"
	.string "hometown one day.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de LANCE\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Me estoy planteando\n"
	.string "volver a mi lugar de origen.\p"
	.string "Quiero entrenar de nuevo a mis\n"
	.string "POKéMON y fortalecerlos un poco.\p"
	.string "Espero verte por allí algún día\n"
	.string "de estos.$"
	.endif

gFameCheckerPersonName_Bill::
	.ifdef ENGLISH @ 0x81B0A45
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BILL$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}BILL$"
	.endif

gFameCheckerPersonQuote_Bill::
	.ifdef ENGLISH @ 0x81B0A50
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: BILL\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Hey, there! CELIO had nothing but\n"
	.string "praise for you.\p"
	.string "Hearing that makes me happy.\p"
	.string "When you catch some rare POKéMON,\n"
	.string "come show me, okay? Promise!$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de BILL\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}¡Eh, oye! ¡CELIO no hace más\n"
	.string "que hablar de ti, te pone por\l"
	.string "las nubes!\p"
	.string "¡Da gusto oírle!\p"
	.string "¡Oye, si atrapas POKéMON raros,\n"
	.string "ven a verme! ¡Hasta lueguito!$"
	.endif

gFameCheckerPersonName_MrFuji::
	.ifdef ENGLISH @ 0x81B0AFF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}MR. FUJI$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}SR. FUJI$"
	.endif

gFameCheckerPersonQuote_MrFuji::
	.ifdef ENGLISH @ 0x81B0B0E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: MR. FUJI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Instead of hoping for the happiness\n"
	.string "of just your POKéMON…\p"
	.string "…Can I get you to wish for the\n"
	.string "happiness of all POKéMON?$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario del SR. FUJI\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}Espero que no pienses sólo\n"
	.string "en el bienestar de tus POKéMON...\p"
	.string "Confío en que te preocupes por\n"
	.string "todos los POKéMON que hay...$"
	.endif

gFameCheckerPersonName_Giovanni::
	.ifdef ENGLISH @ 0x81B0BA6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GIOVANNI$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}GIOVANNI$"
	.endif

gFameCheckerPersonQuote_Giovanni::
	.ifdef ENGLISH @ 0x81B0BB5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}From: GIOVANNI\n"
	.string "To: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}There is nothing that I wish to say\n"
	.string "to you.\p"
	.string "I will concentrate solely on\n"
	.string "bettering myself, and none other.$"
	.endif
	.ifdef SPANISH
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}Comentario de GIOVANNI\n"
	.string "para {PLAYER}:\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}En realidad, no quiero decirte\n"
	.string "nada.\p"
	.string "Yo voy a concentrarme en mejorar\n"
	.string "y punto.$"
	.endif

gFameCheckerFlavorTextOriginLocation_ProfOak0::
	.ifdef ENGLISH @ 0x81B0C45
	.string "PALLET TOWN$"
	.endif
	.ifdef SPANISH
	.string "PUEBLO PALETA$"
	.endif

gFameCheckerFlavorTextOriginLocation_ProfOak1::
	.ifdef ENGLISH
	.string "RESEARCH LAB$"
	.endif
	.ifdef SPANISH
	.string "LABORATORIO$"
	.endif

gFameCheckerFlavorTextOriginLocation_ProfOak2::
	.ifdef ENGLISH
	.string "RESEARCH LAB$"
	.endif
	.ifdef SPANISH
	.string "LABORATORIO$"
	.endif

gFameCheckerFlavorTextOriginLocation_ProfOak3::
	.ifdef ENGLISH
	.string "VIRIDIAN CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD VERDE$"
	.endif

gFameCheckerFlavorTextOriginLocation_ProfOak4::
	.ifdef ENGLISH
	.string "POKéMON LEAGUE$"
	.endif
	.ifdef SPANISH
	.string "LIGA POKéMON$"
	.endif

gFameCheckerFlavorTextOriginLocation_ProfOak5::
	.ifdef ENGLISH
	.string "RESEARCH LAB$"
	.endif
	.ifdef SPANISH
	.string "LABORATORIO$"
	.endif

gFameCheckerFlavorTextOriginLocation_Daisy0::
	.ifdef ENGLISH
	.string "RESEARCH LAB$"
	.endif
	.ifdef SPANISH
	.string "LABORATORIO$"
	.endif

gFameCheckerFlavorTextOriginLocation_Daisy1::
	.ifdef ENGLISH
	.string "VERMILION CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD CARMÍN$"
	.endif

gFameCheckerFlavorTextOriginLocation_Daisy2::
	.ifdef ENGLISH
	.string "WATER LABYRINTH$"
	.endif
	.ifdef SPANISH
	.string "AQUARINTO$"
	.endif

gFameCheckerFlavorTextOriginLocation_Daisy3::
	.ifdef ENGLISH
	.string "VIRIDIAN CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD VERDE$"
	.endif

gFameCheckerFlavorTextOriginLocation_Daisy4::
	.ifdef ENGLISH
	.string "CELADON MANSION$"
	.endif
	.ifdef SPANISH
	.string "MANSIÓN AZULONA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Daisy5::
	.ifdef ENGLISH
	.string "FOUR ISLAND$"
	.endif
	.ifdef SPANISH
	.string "ISLA QUARTA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Brock0::
	.ifdef ENGLISH
	.string "PEWTER CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD PLATEADA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Brock1::
	.ifdef ENGLISH
	.string "PEWTER GYM$"
	.endif
	.ifdef SPANISH
	.string "GIM. PLATEADA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Brock2::
	.ifdef ENGLISH
	.string "PEWTER CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD PLATEADA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Brock3::
	.ifdef ENGLISH
	.string "ROUTE 4$"
	.endif
	.ifdef SPANISH
	.string "RUTA 4$"
	.endif

gFameCheckerFlavorTextOriginLocation_Brock4::
	.ifdef ENGLISH
	.string "MT. MOON$"
	.endif
	.ifdef SPANISH
	.string "MT. MOON$"
	.endif

gFameCheckerFlavorTextOriginLocation_Brock5::
	.ifdef ENGLISH
	.string "PEWTER MUSEUM$"
	.endif
	.ifdef SPANISH
	.string "MUSEO PLATEADA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Misty0::
	.ifdef ENGLISH
	.string "CERULEAN CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD CELESTE$"
	.endif

gFameCheckerFlavorTextOriginLocation_Misty1::
	.ifdef ENGLISH
	.string "CERULEAN GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO CELESTE$"
	.endif

gFameCheckerFlavorTextOriginLocation_Misty2::
	.ifdef ENGLISH
	.string "CERULEAN GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO CELESTE$"
	.endif

gFameCheckerFlavorTextOriginLocation_Misty3::
	.ifdef ENGLISH
	.string "SEAFOAM ISLANDS$"
	.endif
	.ifdef SPANISH
	.string "ISLAS ESPUMA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Misty4::
	.ifdef ENGLISH
	.string "CERULEAN CAPE$"
	.endif
	.ifdef SPANISH
	.string "CABO CELESTE$"
	.endif

gFameCheckerFlavorTextOriginLocation_Misty5::
	.ifdef ENGLISH
	.string "CERULEAN CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD CELESTE$"
	.endif

gFameCheckerFlavorTextOriginLocation_LtSurge0::
	.ifdef ENGLISH
	.string "VERMILION CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD CARMÍN$"
	.endif

gFameCheckerFlavorTextOriginLocation_LtSurge1::
	.ifdef ENGLISH
	.string "VERMILION GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO CARMÍN$"
	.endif

gFameCheckerFlavorTextOriginLocation_LtSurge2::
	.ifdef ENGLISH
	.string "VERMILION GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO CARMÍN$"
	.endif

gFameCheckerFlavorTextOriginLocation_LtSurge3::
	.ifdef ENGLISH
	.string "VERMILION GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO CARMÍN$"
	.endif

gFameCheckerFlavorTextOriginLocation_LtSurge4::
	.ifdef ENGLISH
	.string "VERMILION GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO CARMÍN$"
	.endif

gFameCheckerFlavorTextOriginLocation_LtSurge5::
	.ifdef ENGLISH
	.string "VERMILION CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD CARMÍN$"
	.endif

gFameCheckerFlavorTextOriginLocation_Erika0::
	.ifdef ENGLISH
	.string "CELADON CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD AZULONA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Erika1::
	.ifdef ENGLISH
	.string "CELADON GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO AZULONA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Erika2::
	.ifdef ENGLISH
	.string "CELADON GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO AZULONA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Erika3::
	.ifdef ENGLISH
	.string "CELADON GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO AZULONA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Erika4::
	.ifdef ENGLISH
	.string "CELADON GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO AZULONA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Erika5::
	.ifdef ENGLISH
	.string "CELADON MANSION$"
	.endif
	.ifdef SPANISH
	.string "MANSIÓN AZULONA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Koga0::
	.ifdef ENGLISH
	.string "FUCHSIA CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD FUCSIA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Koga1::
	.ifdef ENGLISH
	.string "FUCHSIA GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO FUCSIA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Koga2::
	.ifdef ENGLISH
	.string "FUCHSIA GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO FUCSIA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Koga3::
	.ifdef ENGLISH
	.string "FUCHSIA CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD FUCSIA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Koga4::
	.ifdef ENGLISH
	.string "FUCHSIA CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD FUCSIA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Koga5::
	.ifdef ENGLISH
	.string "SAFARI ZONE$"
	.endif
	.ifdef SPANISH
	.string "ZONA SAFARI$"
	.endif

gFameCheckerFlavorTextOriginLocation_Sabrina0::
	.ifdef ENGLISH
	.string "SAFFRON CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD AZAFRÁN$"
	.endif

gFameCheckerFlavorTextOriginLocation_Sabrina1::
	.ifdef ENGLISH
	.string "THREE ISLAND$"
	.endif
	.ifdef SPANISH
	.string "ISLA TERA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Sabrina2::
	.ifdef ENGLISH
	.string "SAFFRON GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO AZAFRÁN$"
	.endif

gFameCheckerFlavorTextOriginLocation_Sabrina3::
	.ifdef ENGLISH
	.string "SAFFRON GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO AZAFRÁN$"
	.endif

gFameCheckerFlavorTextOriginLocation_Sabrina4::
	.ifdef ENGLISH
	.string "SAFFRON CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD AZAFRÁN$"
	.endif

gFameCheckerFlavorTextOriginLocation_Sabrina5::
	.ifdef ENGLISH
	.string "SAFFRON GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO AZAFRÁN$"
	.endif

gFameCheckerFlavorTextOriginLocation_Blaine0::
	.ifdef ENGLISH
	.string "CINNABAR ISLAND$"
	.endif
	.ifdef SPANISH
	.string "ISLA CANELA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Blaine1::
	.ifdef ENGLISH
	.string "CINNABAR GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO CANELA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Blaine2::
	.ifdef ENGLISH
	.string "CINNABAR GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO CANELA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Blaine3::
	.ifdef ENGLISH
	.string "CINNABAR ISLAND$"
	.endif
	.ifdef SPANISH
	.string "ISLA CANELA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Blaine4::
	.ifdef ENGLISH
	.string "CINNABAR GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO CANELA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Blaine5::
	.ifdef ENGLISH
	.string "RESORT GORGEOUS$"
	.endif
	.ifdef SPANISH
	.string "LUGAR DE RECREO$"
	.endif

gFameCheckerFlavorTextOriginLocation_Lorelei0::
	.ifdef ENGLISH
	.string "POKéMON LEAGUE$"
	.endif
	.ifdef SPANISH
	.string "LIGA POKéMON$"
	.endif

gFameCheckerFlavorTextOriginLocation_Lorelei1::
	.ifdef ENGLISH
	.string "POKéMON LEAGUE$"
	.endif
	.ifdef SPANISH
	.string "LIGA POKéMON$"
	.endif

gFameCheckerFlavorTextOriginLocation_Lorelei2::
	.ifdef ENGLISH
	.string "FOUR ISLAND$"
	.endif
	.ifdef SPANISH
	.string "ISLA QUARTA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Lorelei3::
	.ifdef ENGLISH
	.string "FIVE ISLAND$"
	.endif
	.ifdef SPANISH
	.string "ISLA INTA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Lorelei4::
	.ifdef ENGLISH
	.string "FOUR ISLAND$"
	.endif
	.ifdef SPANISH
	.string "ISLA QUARTA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Lorelei5::
	.ifdef ENGLISH
	.string "FOUR ISLAND$"
	.endif
	.ifdef SPANISH
	.string "ISLA QUARTA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Bruno0::
	.ifdef ENGLISH
	.string "POKéMON LEAGUE$"
	.endif
	.ifdef SPANISH
	.string "LIGA POKéMON$"
	.endif

gFameCheckerFlavorTextOriginLocation_Bruno1::
	.ifdef ENGLISH
	.string "POKéMON LEAGUE$"
	.endif
	.ifdef SPANISH
	.string "LIGA POKéMON$"
	.endif

gFameCheckerFlavorTextOriginLocation_Bruno2::
	.ifdef ENGLISH
	.string "SAFFRON CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD AZAFRÁN$"
	.endif

gFameCheckerFlavorTextOriginLocation_Bruno3::
	.ifdef ENGLISH
	.string "EMBER SPA$"
	.endif
	.ifdef SPANISH
	.string "BALNEARIO ASCUAS$"
	.endif

gFameCheckerFlavorTextOriginLocation_Bruno4::
	.ifdef ENGLISH
	.string "TWO ISLAND$"
	.endif
	.ifdef SPANISH
	.string "ISLA SECUNDA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Bruno5::
	.ifdef ENGLISH
	.string "SEVAULT CANYON$"
	.endif
	.ifdef SPANISH
	.string "CAÑÓN SÉTANO$"
	.endif

gFameCheckerFlavorTextOriginLocation_Agatha0::
	.ifdef ENGLISH
	.string "POKéMON LEAGUE$"
	.endif
	.ifdef SPANISH
	.string "LIGA POKéMON$"
	.endif

gFameCheckerFlavorTextOriginLocation_Agatha1::
	.ifdef ENGLISH
	.string "INDIGO PLATEAU$"
	.endif
	.ifdef SPANISH
	.string "MESETA AÑIL$"
	.endif

gFameCheckerFlavorTextOriginLocation_Agatha2::
	.ifdef ENGLISH
	.string "INDIGO PLATEAU$"
	.endif
	.ifdef SPANISH
	.string "MESETA AÑIL$"
	.endif

gFameCheckerFlavorTextOriginLocation_Agatha3::
	.ifdef ENGLISH
	.string "SEVEN ISLAND$"
	.endif
	.ifdef SPANISH
	.string "ISLA SÉTIMA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Agatha4::
	.ifdef ENGLISH
	.string "POKéMON LEAGUE$"
	.endif
	.ifdef SPANISH
	.string "LIGA POKéMON$"
	.endif

gFameCheckerFlavorTextOriginLocation_Agatha5::
	.ifdef ENGLISH
	.string "SIX ISLAND$"
	.endif
	.ifdef SPANISH
	.string "ISLA EXTA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Lance0::
	.ifdef ENGLISH
	.string "POKéMON LEAGUE$"
	.endif
	.ifdef SPANISH
	.string "LIGA POKéMON$"
	.endif

gFameCheckerFlavorTextOriginLocation_Lance1::
	.ifdef ENGLISH
	.string "POKéMON LEAGUE$"
	.endif
	.ifdef SPANISH
	.string "LIGA POKéMON$"
	.endif

gFameCheckerFlavorTextOriginLocation_Lance2::
	.ifdef ENGLISH
	.string "SAFFRON CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD AZAFRÁN$"
	.endif

gFameCheckerFlavorTextOriginLocation_Lance3::
	.ifdef ENGLISH
	.string "CELADON DEPT.$"
	.endif
	.ifdef SPANISH
	.string "CC AZULONA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Lance4::
	.ifdef ENGLISH
	.string "INDIGO PLATEAU$"
	.endif
	.ifdef SPANISH
	.string "MESETA AÑIL$"
	.endif

gFameCheckerFlavorTextOriginLocation_Lance5::
	.ifdef ENGLISH
	.string "INDIGO PLATEAU$"
	.endif
	.ifdef SPANISH
	.string "MESETA AÑIL$"
	.endif

gFameCheckerFlavorTextOriginLocation_Bill0::
	.ifdef ENGLISH
	.string "CERULEAN CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD CELESTE$"
	.endif

gFameCheckerFlavorTextOriginLocation_Bill1::
	.ifdef ENGLISH
	.string "CERULEAN CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD CELESTE$"
	.endif

gFameCheckerFlavorTextOriginLocation_Bill2::
	.ifdef ENGLISH
	.string "FUCHSIA CITY$"
	.endif
	.ifdef SPANISH
	.string "CIUDAD FUCSIA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Bill3::
	.ifdef ENGLISH
	.string "ONE ISLAND$"
	.endif
	.ifdef SPANISH
	.string "ISLA PRIMA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Bill4::
	.ifdef ENGLISH
	.string "ONE ISLAND$"
	.endif
	.ifdef SPANISH
	.string "ISLA PRIMA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Bill5::
	.ifdef ENGLISH
	.string "ONE ISLAND$"
	.endif
	.ifdef SPANISH
	.string "ISLA PRIMA$"
	.endif

gFameCheckerFlavorTextOriginLocation_MrFuji0::
	.ifdef ENGLISH
	.string "LAVENDER TOWN$"
	.endif
	.ifdef SPANISH
	.string "PUEBLO LAVANDA$"
	.endif

gFameCheckerFlavorTextOriginLocation_MrFuji1::
	.ifdef ENGLISH
	.string "POKéMON TOWER$"
	.endif
	.ifdef SPANISH
	.string "TORRE POKéMON$"
	.endif

gFameCheckerFlavorTextOriginLocation_MrFuji2::
	.ifdef ENGLISH
	.string "LAVENDER TOWN$"
	.endif
	.ifdef SPANISH
	.string "PUEBLO LAVANDA$"
	.endif

gFameCheckerFlavorTextOriginLocation_MrFuji3::
	.ifdef ENGLISH
	.string "LAVENDER TOWN$"
	.endif
	.ifdef SPANISH
	.string "PUEBLO LAVANDA$"
	.endif

gFameCheckerFlavorTextOriginLocation_MrFuji4::
	.ifdef ENGLISH
	.string "CINNABAR GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO CANELA$"
	.endif

gFameCheckerFlavorTextOriginLocation_MrFuji5::
	.ifdef ENGLISH
	.string "CINNABAR ISLAND$"
	.endif
	.ifdef SPANISH
	.string "ISLA CANELA$"
	.endif

gFameCheckerFlavorTextOriginLocation_Giovanni0::
	.ifdef ENGLISH
	.string "ROCKET HIDEOUT$"
	.endif
	.ifdef SPANISH
	.string "GUAR. ROCKET/CG$"
	.endif

gFameCheckerFlavorTextOriginLocation_Giovanni1::
	.ifdef ENGLISH
	.string "SILPH CO.$"
	.endif
	.ifdef SPANISH
	.string "SILPH S.A.$"
	.endif

gFameCheckerFlavorTextOriginLocation_Giovanni2::
	.ifdef ENGLISH
	.string "SILPH CO.$"
	.endif
	.ifdef SPANISH
	.string "SILPH S.A.$"
	.endif

gFameCheckerFlavorTextOriginLocation_Giovanni3::
	.ifdef ENGLISH
	.string "VIRIDIAN GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO VERDE$"
	.endif

gFameCheckerFlavorTextOriginLocation_Giovanni4::
	.ifdef ENGLISH
	.string "VIRIDIAN GYM$"
	.endif
	.ifdef SPANISH
	.string "GIMNASIO VERDE$"
	.endif

gFameCheckerFlavorTextOriginLocation_Giovanni5::
	.ifdef ENGLISH
	.string "ROCKET WAREHOUSE$"
	.endif
	.ifdef SPANISH
	.string "ALMACÉN ROCKET$"
	.endif

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
	.ifdef ENGLISH
	.string "SIGN$"
	.endif
	.ifdef SPANISH
	.string "CARTEL$"
	.endif

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
	.ifdef ENGLISH
	.string "PROF. OAK$"
	.endif
	.ifdef SPANISH
	.string "PROF. OAK$"
	.endif

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
	.ifdef ENGLISH
	.string "AIDE$"
	.endif
	.ifdef SPANISH
	.string "AYUDANTE$"
	.endif

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON$"
	.endif

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
	.ifdef ENGLISH
	.string "AGATHA$"
	.endif
	.ifdef SPANISH
	.string "AGATHA$"
	.endif

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
	.ifdef ENGLISH
	.string "AIDE$"
	.endif
	.ifdef SPANISH
	.string "AYUDANTE$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Daisy0::
	.ifdef ENGLISH
	.string "AIDE$"
	.endif
	.ifdef SPANISH
	.string "AYUDANTE$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Daisy1::
	.ifdef ENGLISH
	.string "WOMAN$"
	.endif
	.ifdef SPANISH
	.string "MUJER$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Daisy2::
	.ifdef ENGLISH
	.string "MAN$"
	.endif
	.ifdef SPANISH
	.string "HOMBRE$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Daisy3::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Daisy4::
	.ifdef ENGLISH
	.string "OLD LADY$"
	.endif
	.ifdef SPANISH
	.string "SEÑORA MAYOR$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Daisy5::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Brock0::
	.ifdef ENGLISH
	.string "SIGN$"
	.endif
	.ifdef SPANISH
	.string "CARTEL$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Brock1::
	.ifdef ENGLISH
	.string "BROCK$"
	.endif
	.ifdef SPANISH
	.string "BROCK$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Brock2::
	.ifdef ENGLISH
	.string "YOUNG MAN$"
	.endif
	.ifdef SPANISH
	.string "CHICO JOVEN$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Brock3::
	.ifdef ENGLISH
	.string "BOY$"
	.endif
	.ifdef SPANISH
	.string "CHICO$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Brock4::
	.ifdef ENGLISH
	.string "MAN$"
	.endif
	.ifdef SPANISH
	.string "HOMBRE$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Brock5::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Misty0::
	.ifdef ENGLISH
	.string "SIGN$"
	.endif
	.ifdef SPANISH
	.string "CARTEL$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Misty1::
	.ifdef ENGLISH
	.string "MISTY$"
	.endif
	.ifdef SPANISH
	.string "MISTY$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Misty2::
	.ifdef ENGLISH
	.string "LUIS$"
	.endif
	.ifdef SPANISH
	.string "LUIS$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Misty3::
	.ifdef ENGLISH
	.string "YOUNG MAN$"
	.endif
	.ifdef SPANISH
	.string "CHICO JOVEN$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Misty4::
	.ifdef ENGLISH
	.string "DAME$"
	.endif
	.ifdef SPANISH
	.string "SEÑORA$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Misty5::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON$"
	.endif

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
	.ifdef ENGLISH
	.string "SIGN$"
	.endif
	.ifdef SPANISH
	.string "CARTEL$"
	.endif

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
	.ifdef ENGLISH
	.string "LT. SURGE$"
	.endif
	.ifdef SPANISH
	.string "LT. SURGE$"
	.endif

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
	.ifdef ENGLISH
	.string "TUCKER$"
	.endif
	.ifdef SPANISH
	.string "TITO$"
	.endif

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
	.ifdef ENGLISH
	.string "TUCKER$"
	.endif
	.ifdef SPANISH
	.string "TITO$"
	.endif

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
	.ifdef ENGLISH
	.string "DWAYNE$"
	.endif
	.ifdef SPANISH
	.string "DIMAS$"
	.endif

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Erika0::
	.ifdef ENGLISH
	.string "SIGN$"
	.endif
	.ifdef SPANISH
	.string "CARTEL$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Erika1::
	.ifdef ENGLISH
	.string "ERIKA$"
	.endif
	.ifdef SPANISH
	.string "ERIKA$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Erika2::
	.ifdef ENGLISH
	.string "LOLA$"
	.endif
	.ifdef SPANISH
	.string "LOLA$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Erika3::
	.ifdef ENGLISH
	.string "TAMIA$"
	.endif
	.ifdef SPANISH
	.string "PURI$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Erika4::
	.ifdef ENGLISH
	.string "ERIKA$"
	.endif
	.ifdef SPANISH
	.string "ERIKA$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Erika5::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Koga0::
	.ifdef ENGLISH
	.string "SIGN$"
	.endif
	.ifdef SPANISH
	.string "CARTEL$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Koga1::
	.ifdef ENGLISH
	.string "KOGA$"
	.endif
	.ifdef SPANISH
	.string "KOGA$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Koga2::
	.ifdef ENGLISH
	.string "KIRK$"
	.endif
	.ifdef SPANISH
	.string "ÁNGEL$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Koga3::
	.ifdef ENGLISH
	.string "CHARINE$"
	.endif
	.ifdef SPANISH
	.string "SACHIKO$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Koga4::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Koga5::
	.ifdef ENGLISH
	.string "MAN$"
	.endif
	.ifdef SPANISH
	.string "HOMBRE$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
	.ifdef ENGLISH
	.string "SIGN$"
	.endif
	.ifdef SPANISH
	.string "CARTEL$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
	.ifdef ENGLISH
	.string "YOUNG MAN$"
	.endif
	.ifdef SPANISH
	.string "CHICO JOVEN$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
	.ifdef ENGLISH
	.string "SABRINA$"
	.endif
	.ifdef SPANISH
	.string "SABRINA$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
	.ifdef ENGLISH
	.string "SABRINA$"
	.endif
	.ifdef SPANISH
	.string "SABRINA$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
	.ifdef ENGLISH
	.string "TYRON$"
	.endif
	.ifdef SPANISH
	.string "TOR$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Blaine0::
	.ifdef ENGLISH
	.string "SIGN$"
	.endif
	.ifdef SPANISH
	.string "CARTEL$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Blaine1::
	.ifdef ENGLISH
	.string "BLAINE$"
	.endif
	.ifdef SPANISH
	.string "BLAINE$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Blaine2::
	.ifdef ENGLISH
	.string "DEREK$"
	.endif
	.ifdef SPANISH
	.string "DANTE$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Blaine3::
	.ifdef ENGLISH
	.string "WOMAN$"
	.endif
	.ifdef SPANISH
	.string "MUJER$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Blaine4::
	.ifdef ENGLISH
	.string "PHOTO$"
	.endif
	.ifdef SPANISH
	.string "FOTO$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Blaine5::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.ifdef ENGLISH
	.string "LORELEI$"
	.endif
	.ifdef SPANISH
	.string "LORELEI$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.ifdef ENGLISH
	.string "LORELEI$"
	.endif
	.ifdef SPANISH
	.string "LORELEI$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.ifdef ENGLISH
	.string "OLD MAN$"
	.endif
	.ifdef SPANISH
	.string "SEÑOR MAYOR$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.ifdef ENGLISH
	.string "LITTLE GIRL$"
	.endif
	.ifdef SPANISH
	.string "NIÑA PEQUEÑA$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.ifdef ENGLISH
	.string "OLD LADY$"
	.endif
	.ifdef SPANISH
	.string "SEÑORA MAYOR$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.ifdef ENGLISH
	.string "BRUNO$"
	.endif
	.ifdef SPANISH
	.string "BRUNO$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.ifdef ENGLISH
	.string "BRUNO$"
	.endif
	.ifdef SPANISH
	.string "BRUNO$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.ifdef ENGLISH
	.string "CRUSHER$"
	.endif
	.ifdef SPANISH
	.string "MACHACABAYAS$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.ifdef ENGLISH
	.string "WOMAN$"
	.endif
	.ifdef SPANISH
	.string "MUJER$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.ifdef ENGLISH
	.string "CRUSHER$"
	.endif
	.ifdef SPANISH
	.string "MACHACABAYAS$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.ifdef ENGLISH
	.string "AGATHA$"
	.endif
	.ifdef SPANISH
	.string "AGATHA$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.ifdef ENGLISH
	.string "CRUSHER$"
	.endif
	.ifdef SPANISH
	.string "MACHACABAYAS$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.ifdef ENGLISH
	.string "CRUSHER$"
	.endif
	.ifdef SPANISH
	.string "MACHACABAYAS$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.ifdef ENGLISH
	.string "AGATHA$"
	.endif
	.ifdef SPANISH
	.string "AGATHA$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.ifdef ENGLISH
	.string "OLD LADY$"
	.endif
	.ifdef SPANISH
	.string "SEÑORA MAYOR$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.ifdef ENGLISH
	.string "LANCE$"
	.endif
	.ifdef SPANISH
	.string "LANCE$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.ifdef ENGLISH
	.string "LANCE$"
	.endif
	.ifdef SPANISH
	.string "LANCE$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.ifdef ENGLISH
	.string "WOMAN$"
	.endif
	.ifdef SPANISH
	.string "MUJER$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.ifdef ENGLISH
	.string "LITTLE GIRL$"
	.endif
	.ifdef SPANISH
	.string "NIÑA PEQUEÑA$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.ifdef ENGLISH
	.string "YOUNG MAN$"
	.endif
	.ifdef SPANISH
	.string "CHICO JOVEN$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.ifdef ENGLISH
	.string "{RIVAL}$"
	.endif
	.ifdef SPANISH
	.string "{RIVAL}$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.ifdef ENGLISH
	.string "LITTLE BOY$"
	.endif
	.ifdef SPANISH
	.string "NIÑO PEQUEÑO$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.ifdef ENGLISH
	.string "OLD MAN$"
	.endif
	.ifdef SPANISH
	.string "SEÑOR MAYOR$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.ifdef ENGLISH
	.string "CELIO$"
	.endif
	.ifdef SPANISH
	.string "CELIO$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.ifdef ENGLISH
	.string "CELIO$"
	.endif
	.ifdef SPANISH
	.string "CELIO$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.ifdef ENGLISH
	.string "CELIO$"
	.endif
	.ifdef SPANISH
	.string "CELIO$"
	.endif

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.ifdef ENGLISH
	.string "LITTLE GIRL$"
	.endif
	.ifdef SPANISH
	.string "NIÑA PEQUEÑA$"
	.endif

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.ifdef ENGLISH
	.string "TEAM ROCKET$"
	.endif
	.ifdef SPANISH
	.string "TEAM ROCKET$"
	.endif

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.ifdef ENGLISH
	.string "MAGAZINE$"
	.endif
	.ifdef SPANISH
	.string "REVISTA$"
	.endif

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.ifdef ENGLISH
	.string "MAN$"
	.endif
	.ifdef SPANISH
	.string "HOMBRE$"
	.endif

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.ifdef ENGLISH
	.string "PHOTO$"
	.endif
	.ifdef SPANISH
	.string "FOTO$"
	.endif

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.ifdef ENGLISH
	.string "GIOVANNI$"
	.endif
	.ifdef SPANISH
	.string "GIOVANNI$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.ifdef ENGLISH
	.string "SCIENTIST$"
	.endif
	.ifdef SPANISH
	.string "CIENTÍFICO$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.ifdef ENGLISH
	.string "SCIENTIST$"
	.endif
	.ifdef SPANISH
	.string "CIENTÍFICO$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.ifdef ENGLISH
	.string "GIOVANNI$"
	.endif
	.ifdef SPANISH
	.string "GIOVANNI$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.ifdef ENGLISH
	.string "MAN$"
	.endif
	.ifdef SPANISH
	.string "HOMBRE$"
	.endif

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.ifdef ENGLISH
	.string "GIDEON$"
	.endif
	.ifdef SPANISH
	.string "GIL$"
	.endif

PokemonJournal_Text_SpecialFeatureBrock::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: PEWTER GYM\n"
	.string "LEADER BROCK!\p"
	.string "BROCK rarely laughs, but is said to\n"
	.string "be unable to stop if he starts.$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre BROCK, LÍDER\n"
	.string "del GIMNASIO de PLATEADA.\p"
	.string "Según fuentes cercanas, BROCK\n"
	.string "casi nunca se ríe, ¡pero una vez\l"
	.string "que empieza, no para!$"
	.endif

PokemonJournal_Text_SpecialFeatureMisty::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CERULEAN GYM\n"
	.string "LEADER MISTY!\p"
	.string "MISTY is said to worship LORELEI\n"
	.string "of the ELITE FOUR.$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre MISTY, LÍDER\n"
	.string "del GIMNASIO de CELESTE.\p"
	.string "Según fuentes cercanas, MISTY\n"
	.string "adora a LORELEI, del ALTO MANDO.$"
	.endif

PokemonJournal_Text_SpecialFeatureLtSurge::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: VERMILION GYM\n"
	.string "LEADER LT. SURGE!\p"
	.string "LT. SURGE is rumored to have been\n"
	.string "a pilot while home in America.\p"
	.string "He used the electricity generated\n"
	.string "by POKéMON to power his plane.$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre LT. SURGE, LÍDER\n"
	.string "del GIMNASIO de CARMÍN.\p"
	.string "Según fuentes cercanas, LT. SURGE\n"
	.string "era piloto cuando vivía en Estados\l"
	.string "Unidos.\p"
	.string "Y se valía de la electricidad\n"
	.string "generada por sus POKéMON\l"
	.string "para poner en marcha su avión.$"
	.endif

PokemonJournal_Text_SpecialFeatureErika::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CELADON GYM\n"
	.string "LEADER ERIKA!\p"
	.string "Rumor has it that if you peek into\n"
	.string "CELADON GYM, you can often\l"
	.string "see ERIKA snoozing.$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre ERIKA, LÍDER\n"
	.string "del GIMNASIO de AZULONA.\p"
	.string "Según fuentes cercanas, es fácil\n"
	.string "ver a ERIKA echándose una siesta\l"
	.string "en el GIMNASIO de AZULONA.$"
	.endif

PokemonJournal_Text_SpecialFeatureKoga::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: FUCHSIA GYM\n"
	.string "LEADER KOGA!\p"
	.string "KOGA is said to have a thorough\n"
	.string "knowledge of medicine.\p"
	.string "He even concocts medicine to nurse\n"
	.string "his POKéMON to health.$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre KOGA, LÍDER\n"
	.string "del GIMNASIO de FUCSIA.\p"
	.string "Según fuentes cercanas, KOGA\n"
	.string "tiene grandes conocimientos\l"
	.string "de medicina.\p"
	.string "Incluso elabora las medicinas\n"
	.string "que sus POKéMON necesitan.$"
	.endif

PokemonJournal_Text_SpecialFeatureSabrina::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: SAFFRON GYM\n"
	.string "LEADER SABRINA!\p"
	.string "People say that SABRINA can\n"
	.string "communicate with her POKéMON\l"
	.string "during battle without speaking.$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre SABRINA, LÍDER\n"
	.string "del GIMNASIO de AZAFRÁN.\p"
	.string "Según fuentes cercanas, SABRINA\n"
	.string "se comunica en combate con sus\l"
	.string "POKéMON, sin necesidad de hablar.$"
	.endif

PokemonJournal_Text_SpecialFeatureBlaine::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CINNABAR GYM\n"
	.string "LEADER BLAINE!\p"
	.string "BLAINE is said to remove his dark\n"
	.string "shades only when he is thinking up\l"
	.string "new quiz questions.$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre BLAINE, LÍDER\n"
	.string "del GIMNASIO de CANELA.\p"
	.string "Según fuentes cercanas, BLAINE\n"
	.string "sólo se quita las gafas de sol\l"
	.string "cuando contesta a preguntas.$"
	.endif

PokemonJournal_Text_SpecialFeatureLorelei::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's LORELEI!\p"
	.string "Known for her logical, calculated,\n"
	.string "and cool battling style, LORELEI\l"
	.string "has a surprising secret!$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre LORELEI,\n"
	.string "miembro del ALTO MANDO.\p"
	.string "Según fuentes cercanas, LORELEI\n"
	.string "guarda un gran secreto.\p"
	.string "Lo que sí se conoce de ella es\n"
	.string "su estilo de lucha elegante, único\l"
	.string "y calculador.$"
	.endif

PokemonJournal_Text_SpecialFeatureBruno::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's BRUNO!\p"
	.string "BRUNO apparently joined the ELITE\n"
	.string "FOUR out of his burning ambition to\l"
	.string "battle the best TRAINERS.$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre BRUNO,\n"
	.string "miembro del ALTO MANDO.\p"
	.string "Según fuentes cercanas, BRUNO\n"
	.string "se unió al ALTO MANDO para luchar\l"
	.string "contra los mejores ENTRENADORES.$"
	.endif

PokemonJournal_Text_SpecialFeatureAgatha::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's AGATHA!\p"
	.string "In her youth, AGATHA and PROF.\n"
	.string "OAK were rivals who vied for\l"
	.string "supremacy as TRAINERS.$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre AGATHA,\n"
	.string "miembro del ALTO MANDO.\p"
	.string "Según fuentes cercanas, AGATHA\n"
	.string "y el PROF. OAK estuvieron\p"
	.string "enfrentados durante su formación\n"
	.string "como ENTRENADORES.$"
	.endif

PokemonJournal_Text_SpecialFeatureLance::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "ELITE FOUR's LANCE!\p"
	.string "LANCE's grandfather is thought to\n"
	.string "be the elder of a famous clan of\l"
	.string "dragon masters.$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre LANCE,\n"
	.string "miembro del ALTO MANDO.\p"
	.string "Según fuentes cercanas, quien fundó\n"
	.string "el clan de los maestros del tipo\l"
	.string "DRAGÓN fue el abuelo de LANCE.$"
	.endif

PokemonJournal_Text_SpecialFeatureProfOak::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: PROF. OAK,\n"
	.string "the POKéMON Researcher!\p"
	.string "PROF. OAK reportedly lives with his\n"
	.string "grandchildren DAISY and {RIVAL}.$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre el PROF.\n"
	.string "OAK, el investigador de POKéMON.\p"
	.string "Según dicen, el PROF. OAK vive\n"
	.string "con su nieta DALIA y {RIVAL}.$"
	.endif

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.ifdef ENGLISH
	.string "This is a POKéMON JOURNAL from\n"
	.string "years ago…\p"
	.string "POKéMON JOURNAL\n"
	.string "CONTEST Special!\p"
	.string "The Spring POKéMON CONTEST's\n"
	.string "Grand Champion is DAISY OAK of\l"
	.string "PALLET TOWN!$"
	.endif
	.ifdef SPANISH
	.string "Un DIARIO POKéMON de hace\n"
	.string "unos años...\p"
	.string "¡Especial sobre el CONCURSO\n"
	.string "del DIARIO POKéMON!\p"
	.string "¡La campeona de la edición de\n"
	.string "primavera del CONCURSO POKéMON\l"
	.string "es DALIA OAK, de PUEBLO PALETA!$"
	.endif

PokemonJournal_Text_SpecialFeatureMrFuji::
	.ifdef ENGLISH
	.string "POKéMON JOURNAL\p"
	.string "Special Feature:\n"
	.string "MR. FUJI of POKéMON HOUSE!\p"
	.string "Editor: The shy MR. FUJI turned\n"
	.string "down our interview requests.\p"
	.string "He is a kindly man who is adored\n"
	.string "and respected in LAVENDER TOWN.$"
	.endif
	.ifdef SPANISH
	.string "DIARIO POKéMON\p"
	.string "Última hora sobre el SR. FUJI,\n"
	.string "de la CASA POKéMON.\p"
	.string "Nota del editor: el tímido\n"
	.string "SR. FUJI no ha querido contestar\l"
	.string "a nuestras preguntas.\p"
	.string "Con todo, hay que decir que es una\n"
	.string "persona muy querida en PUEBLO\l"
	.string "LAVANDA.$"
	.endif
