@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.ifdef ENGLISH
	.string "It's crammed full of POKéMON\n"
	.string "books.$"
	.endif
	.ifdef SPANISH
	.string "¡Totalmente lleno de libros sobre\n"
	.string "los POKéMON!$"
	.endif

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.ifdef ENGLISH
	.string "A TOWN MAP.$"
	.endif
	.ifdef SPANISH
	.string "MAPA$"
	.endif

Text_PokeMartShelf::
	.ifdef ENGLISH
	.string "Wow!\n"
	.string "Tons of POKéMON stuff!$"
	.endif
	.ifdef SPANISH
	.string "¡Uauu!\n"
	.string "¡Cantidad de artículos de POKéMON!$"
	.endif

Text_DishesPlatesNeatlyLinedUp::
	.ifdef ENGLISH
	.string "Dishes and plates are neatly\n"
	.string "lined up.$"
	.endif
	.ifdef SPANISH
	.string "Hay un montón de platos y bandejas\n"
	.string "muy bien colocados.$"
	.endif

Text_Kitchen::
	.ifdef ENGLISH
	.string "It smells delicious!\n"
	.string "Somebody's been cooking here.$"
	.endif
	.ifdef SPANISH
	.string "¡Mmm, huele que alimenta!\n"
	.string "Aquí han debido de cocinar algo...$"
	.endif

Text_Dresser::
	.ifdef ENGLISH
	.string "It's a nicely made dresser.\n"
	.string "It will hold a lot of stuff.$"
	.endif
	.ifdef SPANISH
	.string "Qué mueble más estupendo...\n"
	.string "Aquí caben un montón de cosas.$"
	.endif

Text_Snacks::
	.ifdef ENGLISH
	.string "There's a pile of snacks here.$"
	.endif
	.ifdef SPANISH
	.string "Mmm, cuántas cosas ricas...$"
	.endif

Text_PokemartSign::
	.ifdef ENGLISH
	.string "All your item needs fulfilled!\n"
	.string "POKéMON MART$"
	.endif
	.ifdef SPANISH
	.string "TIENDAS POKéMON\n"
	.string "¡Compra aquí todos tus objetos!$"
	.endif

Text_PokecenterSign::
	.ifdef ENGLISH
	.string "Heal Your POKéMON!\n"
	.string "POKéMON CENTER$"
	.endif
	.ifdef SPANISH
	.string "CENTRO POKéMON\n"
	.string "¡Cura a tus POKéMON!$"
	.endif

Text_Indigo_UltimateGoal::
	.ifdef ENGLISH
	.string "INDIGO PLATEAU\p"
	.string "The ultimate goal of TRAINERS!\n"
	.string "POKéMON LEAGUE HQ$"
	.endif
	.ifdef SPANISH
	.string "MESETA AÑIL\p"
	.string "¡El objetivo de todo ENTRENADOR:\n"
	.string "El CG de la LIGA POKéMON!$"
	.endif

Text_Indigo_HighestAuthority::
	.ifdef ENGLISH
	.string "INDIGO PLATEAU\p"
	.string "The highest POKéMON authority!\n"
	.string "POKéMON LEAGUE HQ$"
	.endif
	.ifdef SPANISH
	.string "MESETA AÑIL\p"
	.string "La máxima autoridad POKéMON\n"
	.string "del CG de la LIGA POKéMON.$"
	.endif

Text_Food::
	.ifdef ENGLISH
	.string "It should be packed with all kinds\n"
	.string "of delicious things to eat.$"
	.endif
	.ifdef SPANISH
	.string "Seguramente está lleno de cosas\n"
	.string "de lo más apetecibles.$"
	.endif

Text_Blueprints::
	.ifdef ENGLISH
	.string "It's a blueprint of some sort.\n"
	.string "It's filled with diagrams and text.$"
	.endif
	.ifdef SPANISH
	.string "Y este plano... ¿de dónde será?\p"
	.string "Tiene gráficos y anotaciones\n"
	.string "rarísimas.$"
	.endif

Text_Painting::
	.ifdef ENGLISH
	.string "It's a pretty picture of a POKéMON.\n"
	.string "It looks like it's feeling good.$"
	.endif
	.ifdef SPANISH
	.string "Qué foto más bonita.\n"
	.string "El POKéMON parece estar encantado.$"
	.endif

Text_PowerPlantMachine::
	.ifdef ENGLISH
	.string "What could this machine be?\n"
	.string "Better not mess around with it!$"
	.endif
	.ifdef SPANISH
	.string "¿Para qué servirá?\n"
	.string "Prefiero no tocar, por si acaso...$"
	.endif

Text_Telephone::
	.ifdef ENGLISH
	.string "It's a telephone.\n"
	.string "Better not use it.$"
	.endif
	.ifdef SPANISH
	.string "Anda, un teléfono.\n"
	.string "Paso de usarlo.$"
	.endif

Text_Computer::
	.ifdef ENGLISH
	.string "It's all complicated words and\n"
	.string "numbers that make no sense…$"
	.endif
	.ifdef SPANISH
	.string "Qué combinación de números\n"
	.string "y letras más complicada...$"
	.endif

Text_AdvertisingPoster::
	.ifdef ENGLISH
	.string "It's an advertising poster about\n"
	.string "all kinds of products.$"
	.endif
	.ifdef SPANISH
	.string "Es un póster promocional\n"
	.string "con todo tipo de productos.$"
	.endif

Text_TastyFood::
	.ifdef ENGLISH
	.string "Oh, that smells tasty!\n"
	.string "It might get the stomach growling!$"
	.endif
	.ifdef SPANISH
	.string "Mmm, ¡qué bien huele!\n"
	.string "¡Se me hace la boca agua!$"
	.endif

Text_TrashBin::
	.ifdef ENGLISH
	.string "Inside this…\n"
	.string "……\p"
	.string "There's nothing here!$"
	.endif
	.ifdef SPANISH
	.string "A ver...\n"
	.string "... ...\p"
	.string "¡Pero si no hay nada!$"
	.endif

Text_Cup::
	.ifdef ENGLISH
	.string "It's a cup with a POKéMON mark\n"
	.string "on it.$"
	.endif
	.ifdef SPANISH
	.string "¡Qué taza más guay!\n"
	.string "¡Tiene la huella de un POKéMON!$"
	.endif

Text_PolishedWindow::
	.ifdef ENGLISH
	.string "The window is very well polished.$"
	.endif
	.ifdef SPANISH
	.string "La ventana está requetelimpia.$"
	.endif

Text_BeautifulSkyWindow::
	.ifdef ENGLISH
	.string "Outside the window…\p"
	.string "The sky looks fantastically\n"
	.string "beautiful.$"
	.endif
	.ifdef SPANISH
	.string "Da gusto mirar por la ventana...\p"
	.string "El cielo está impresionante.$"
	.endif

Text_BlinkingLights::
	.ifdef ENGLISH
	.string "Lights in different colors are\n"
	.string "flashing on and off.$"
	.endif
	.ifdef SPANISH
	.string "Cuántas lucecitas de colores\n"
	.string "que se encienden y se apagan...$"
	.endif

Text_NeatlyLinedUpTools::
	.ifdef ENGLISH
	.string "All sorts of tools are lined up\n"
	.string "neatly.$"
	.endif
	.ifdef SPANISH
	.string "Hay un montón de relucientes\n"
	.string "herramientas muy bien ordenadas.$"
	.endif

Text_ImpressiveMachine::
	.ifdef ENGLISH
	.string "It's a machine of some sort.\n"
	.string "It sure is impressive.$"
	.endif
	.ifdef SPANISH
	.string "No sé qué será esta máquina,\n"
	.string "pero es impresionante.$"
	.endif

Text_VideoGame::
	.ifdef ENGLISH
	.string "It's the latest video game!\n"
	.string "It sure looks fun!$"
	.endif
	.ifdef SPANISH
	.string "¡Lo último en videojuegos!\n"
	.string "¡Qué guay!$"
	.endif

Text_Burglary::
	.ifdef ENGLISH
	.string "There are obvious signs of burglary\n"
	.string "here…$"
	.endif
	.ifdef SPANISH
	.string "Salta a la vista que han entrado\n"
	.string "a robar...$"
	.endif

Text_PlayerFacingTVScreen::
	.ifdef ENGLISH
	.string "There's a POKéMON on TV!\n"
	.string "It looks like it's having fun.$"
	.endif
	.ifdef SPANISH
	.string "¡Está saliendo un POKéMON\n"
	.string "por la tele! Se le ve encantado...$"
	.endif
