Help_Text_WhatShouldIDo::
	.ifdef ENGLISH
	.string "What should I do in this situation?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué debo hacer ahora?$"
	.endif

Help_Text_HowDoIDoThis::
	.ifdef ENGLISH
	.string "How do I do this?$"
	.endif
	.ifdef SPANISH
	.string "¿Cómo lo hago?$"
	.endif

Help_Text_WhatDoesThisTermMean::
	.ifdef ENGLISH
	.string "What does this term mean?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué significa esto?$"
	.endif

Help_Text_AboutThisGame::
	.ifdef ENGLISH
	.string "About this game$"
	.endif
	.ifdef SPANISH
	.string "¿Y este juego?$"
	.endif

Help_Text_TypeMatchupList::
	.ifdef ENGLISH
	.string "Type Matchup List$"
	.endif
	.ifdef SPANISH
	.string "Combinaciones de los tipos$"
	.endif

Help_Text_Exit::
	.ifdef ENGLISH
	.string "EXIT$"
	.endif
	.ifdef SPANISH
	.string "SALIR$"
	.endif

Help_Text_Cancel::
	.ifdef ENGLISH
	.string "CANCEL$"
	.endif
	.ifdef SPANISH
	.string "ATRÁS$"
	.endif

Help_Text_TryDoingItOnYourOwn::
	.string "じぶんの ちからで やってみよう！$"

Help_Text_DescWhatShouldIDo::
	.ifdef ENGLISH
	.string "Select to obtain hints for getting\n"
	.string "over challenging situations.$"
	.endif
	.ifdef SPANISH
	.string "Información útil para salir\n"
	.string "de ciertas situaciones.$"
	.endif

Help_Text_DescHowDoIDoThis::
	.ifdef ENGLISH
	.string "Detailed instructions are given for\n"
	.string "various operations.$"
	.endif
	.ifdef SPANISH
	.string "Instrucciones para realizar\n"
	.string "distintas cosas.$"
	.endif

Help_Text_DescWhatDoesThisTermMean::
	.ifdef ENGLISH
	.string "Detailed descriptions are given for\n"
	.string "terms that appear in the game.$"
	.endif
	.ifdef SPANISH
	.string "Descripciones detalladas\n"
	.string "de términos del juego.$"
	.endif

Help_Text_DescAboutThisGame::
	.ifdef ENGLISH
	.string "Detailed descriptions are given\n"
	.string "about this game.$"
	.endif
	.ifdef SPANISH
	.string "Descripciones detalladas\n"
	.string "del juego.$"
	.endif

Help_Text_DescTypeMatchupList::
	.ifdef ENGLISH
	.string "The matchups of  POKéMON types\n"
	.string "and moves are listed.$"
	.endif
	.ifdef SPANISH
	.string "Lista en la que se ve cómo se\n"
	.string "combinan los tipos y los ataques.$"
	.endif

Help_Text_DescExit::
	.ifdef ENGLISH
	.string "Select to exit the HELP System.$"
	.endif
	.ifdef SPANISH
	.string "Salir del sistema de AYUDA.$"
	.endif

Help_Text_Greetings::
	.ifdef ENGLISH
	.string "Greetings! This is the HELP System.\n"
	.string "Call me up whenever and wherever you\l"
	.string "need by pressing the L or R Button.\l"
	.string "The help messages change to suit the\l"
	.string "situation, so check them often, please.$"
	.endif
	.ifdef SPANISH
	.string "¡Hola! Éste es el sistema de\n"
	.string "AYUDA. Cuando no sepas qué hacer,\l"
	.string "basta con pulsar el Botón L o R.\l"
	.string "Las cuestiones variarán según\l"
	.string "la situación, ¡así que conviene que\l"
	.string "lo consultes con frecuencia!$"
	.endif

Help_Text_PlayingForFirstTime::
	.ifdef ENGLISH
	.string "I'm playing for the first time. Help!$"
	.endif
	.ifdef SPANISH
	.string "¡Es la primera vez que juego!$"
	.endif

Help_Text_WhatShouldIBeDoing::
	.ifdef ENGLISH
	.string "What should I be doing?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué tengo que hacer?$"
	.endif

Help_Text_CantGetOutOfRoom::
	.ifdef ENGLISH
	.string "I can't get out of a room!$"
	.endif
	.ifdef SPANISH
	.string "¿Por dónde salgo?$"
	.endif

Help_Text_CantFindPersonIWant::
	.ifdef ENGLISH
	.string "I can't find the person I want.$"
	.endif
	.ifdef SPANISH
	.string "¡No encuentro a quien busco!$"
	.endif

Help_Text_TalkedToEveryoneNowWhat::
	.ifdef ENGLISH
	.string "I've talked to everyone. Now what?$"
	.endif
	.ifdef SPANISH
	.string "¡Ya he hablado con todos!$"
	.endif

Help_Text_SomeoneBlockingMyWay::
	.ifdef ENGLISH
	.string "There's someone blocking my way!$"
	.endif
	.ifdef SPANISH
	.string "¡No me dejan pasar!$"
	.endif

Help_Text_ICantGoOn::
	.ifdef ENGLISH
	.string "I can't go on!$"
	.endif
	.ifdef SPANISH
	.string "¡No puedo avanzar!$"
	.endif

Help_Text_OutOfThingsToDo::
	.ifdef ENGLISH
	.string "I'm out of things to do.$"
	.endif
	.ifdef SPANISH
	.string "¡Ya no sé qué hacer!$"
	.endif

Help_Text_WhatHappenedToItemIGot::
	.ifdef ENGLISH
	.string "What happened to the item I got?$"
	.endif
	.ifdef SPANISH
	.string "¿Y el objeto que me han dado?$"
	.endif

Help_Text_WhatAreMyAdventureBasics::
	.ifdef ENGLISH
	.string "What are the basics of my adventure?$"
	.endif
	.ifdef SPANISH
	.string "¿Algún consejo importante?$"
	.endif

Help_Text_HowAreRoadsForestsDifferent::
	.ifdef ENGLISH
	.string "How are roads and forests different?$"
	.endif
	.ifdef SPANISH
	.string "Una ruta y un bosque, ¿son iguales?$"
	.endif

Help_Text_HowAreCavesDifferent::
	.ifdef ENGLISH
	.string "How are caves different?$"
	.endif
	.ifdef SPANISH
	.string "¿Cómo son las cuevas?$"
	.endif

Help_Text_HowDoIProgress::
	.ifdef ENGLISH
	.string "How do I progress?$"
	.endif
	.ifdef SPANISH
	.string "¿Cuál es mi objetivo?$"
	.endif

Help_Text_WhenCanIUseItem::
	.ifdef ENGLISH
	.string "When can I use items?$"
	.endif
	.ifdef SPANISH
	.string "¿Cuándo puedo usar objetos?$"
	.endif

Help_Text_WhatsABattle::
	.ifdef ENGLISH
	.string "What's a battle?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué es un combate?$"
	.endif

Help_Text_HowDoIPrepareForBattle::
	.ifdef ENGLISH
	.string "How do I prepare for battle?$"
	.endif
	.ifdef SPANISH
	.string "¿Cómo me preparo para luchar?$"
	.endif

Help_Text_WhatIsAMonsVitality::
	.ifdef ENGLISH
	.string "What is a POKéMON's vitality?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué es la energía de un POKéMON?$"
	.endif

Help_Text_MyMonsAreHurt::
	.ifdef ENGLISH
	.string "My POKéMON are hurt!$"
	.endif
	.ifdef SPANISH
	.string "¡Mis POKéMON están heridos!$"
	.endif

Help_Text_WhatIsStatusProblem::
	.ifdef ENGLISH
	.string "What is a status problem?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué son los problemas de estado?$"
	.endif

Help_Text_WhatHappensIfAllMyMonsFaint::
	.ifdef ENGLISH
	.string "What happens if all my POKéMON faint?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué pasa si se debilitan mis PKMN?$"
	.endif

Help_Text_CantCatchMons::
	.ifdef ENGLISH
	.string "I can't catch POKéMON!$"
	.endif
	.ifdef SPANISH
	.string "¡No puedo atrapar POKéMON!$"
	.endif

Help_Text_RanOutOfPotions::
	.ifdef ENGLISH
	.string "I ran out of POTIONS.$"
	.endif
	.ifdef SPANISH
	.string "¡Me he quedado sin POCIONES!$"
	.endif

Help_Text_CanIBuyPokeBalls::
	.ifdef ENGLISH
	.string "Can I buy POKé BALLS?$"
	.endif
	.ifdef SPANISH
	.string "¿Puedo comprar POKé BALLS?$"
	.endif

Help_Text_WhatsATrainer::
	.ifdef ENGLISH
	.string "What's a TRAINER?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué es un ENTRENADOR?$"
	.endif

Help_Text_HowDoIWinAgainstTrainer::
	.ifdef ENGLISH
	.string "How do I win against a TRAINER?$"
	.endif
	.ifdef SPANISH
	.string "¿Cómo se le gana a un ENTRENADOR?$"
	.endif

Help_Text_WhereDoMonsAppear::
	.ifdef ENGLISH
	.string "Where do POKéMON appear?$"
	.endif
	.ifdef SPANISH
	.string "¿Dónde hay POKéMON salvajes?$"
	.endif

Help_Text_WhatAreMoves::
	.ifdef ENGLISH
	.string "What are POKéMON moves?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué son los movimientos POKéMON?$"
	.endif

Help_Text_WhatAreHiddenMoves::
	.ifdef ENGLISH
	.string "What are HIDDEN moves?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué son los movimientos OCULTOS?$"
	.endif

Help_Text_WhatMovesShouldIUse::
	.ifdef ENGLISH
	.string "What moves should I use?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué movimientos debería usar?$"
	.endif

Help_Text_WantToAddMoreMoves::
	.ifdef ENGLISH
	.string "I want to add more moves.$"
	.endif
	.ifdef SPANISH
	.string "¿Puedo añadir más movimientos?$"
	.endif

Help_Text_WantToMakeMonStronger::
	.ifdef ENGLISH
	.string "I want to make my POKéMON stronger.$"
	.endif
	.ifdef SPANISH
	.string "¿Cómo fortalezco a mis POKéMON?$"
	.endif

Help_Text_FoeMonsTooStrong::
	.ifdef ENGLISH
	.string "The foe POKéMON are too strong!$"
	.endif
	.ifdef SPANISH
	.string "¡Mi rival es demasiado fuerte!$"
	.endif

Help_Text_WhatDoIDoInCave::
	.ifdef ENGLISH
	.string "What do I do in a cave?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué hago con las cuevas?$"
	.endif

Help_Text_NothingIWantToKnow::
	.ifdef ENGLISH
	.string "There's nothing that I want to know!$"
	.endif
	.ifdef SPANISH
	.string "No tengo ninguna pregunta.$"
	.endif

Help_Text_WhatsPokemonCenter::
	.ifdef ENGLISH
	.string "What's a POKéMON CENTER?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué es un CENTRO POKéMON?$"
	.endif

Help_Text_WhatsPokemonMart::
	.ifdef ENGLISH
	.string "What's a POKéMON MART?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué es una TIENDA POKéMON?$"
	.endif

Help_Text_WantToEndGame::
	.ifdef ENGLISH
	.string "I want to end the game.$"
	.endif
	.ifdef SPANISH
	.string "Quiero acabar la partida.$"
	.endif

Help_Text_WhatsAMon::
	.ifdef ENGLISH
	.string "What's a POKéMON?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué es un POKéMON?$"
	.endif

Help_Text_WhatIsThatPersonLike::
	.ifdef ENGLISH
	.string "What is that person like?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué sé de esta persona?$"
	.endif

Help_Text_WhatDoesHiddenMoveDo::
	.ifdef ENGLISH
	.string "What does a HIDDEN move do?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué hace un movimiento OCULTO?$"
	.endif

Help_Text_WhatDoIDoInSafari::
	.ifdef ENGLISH
	.string "What do I do in a SAFARI GAME?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué se hace en el SAFARI?$"
	.endif

Help_Text_WhatAreSafariRules::
	.ifdef ENGLISH
	.string "What are the SAFARI GAME rules?$"
	.endif
	.ifdef SPANISH
	.string "¿Cuáles son las reglas del SAFARI?$"
	.endif

Help_Text_WantToEndSafari::
	.ifdef ENGLISH
	.string "I want to end this SAFARI GAME!$"
	.endif
	.ifdef SPANISH
	.string "Quiero salir del SAFARI.$"
	.endif

Help_Text_WhatIsAGym::
	.ifdef ENGLISH
	.string "What is a GYM?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué es un GIMNASIO?$"
	.endif

Help_Text_AnswerPlayingForFirstTime::
	.ifdef ENGLISH
	.string "You become the main character,\n"
	.string "exploring the world of POKéMON.\l"
	.string "By talking to people and solving\l"
	.string "mysteries, new paths will open to you.\l"
	.string "Strive for the goal together with your\l"
	.string "wonderful POKéMON.$"
	.endif
	.ifdef SPANISH
	.string "Acabas de convertirte en\n"
	.string "protagonista de esta historia.\l"
	.string "Estás en el mundo POKéMON. Tienes\l"
	.string "que hablar con la gente y resolver\l"
	.string "los misterios que se te presenten.\l"
	.string "Ábrete camino para llegar al final\l"
	.string "junto a tus maravillosos POKéMON.$"
	.endif

Help_Text_AnswerWhatShouldIBeDoing::
	.ifdef ENGLISH
	.string "When you come across another person,\n"
	.string "go up to them and press the A Button.\l"
	.string "That will get them to talk and interact\l"
	.string "with your character. You may also\l"
	.string "examine various items and objects in\l"
	.string "the same way. Talk to people and check\l"
	.string "things often to obtain information.$"
	.endif
	.ifdef SPANISH
	.string "Cuando te cruces con alguien,\n"
	.string "acércate y pulsa el Botón A para\l"
	.string "hablar. Haz lo mismo cuando veas\l"
	.string "algo interesante y llévatelo.\l"
	.string "Son las mejores formas de obtener\l"
	.string "información.$"
	.endif

Help_Text_AnswerCantGetOutOfRoom::
	.ifdef ENGLISH
	.string "On the stairs or the exits of a\n"
	.string "building is a red mat. Move your\l"
	.string "character to stand on top of the\l"
	.string "red mat. Press the {PLUS} Control Pad \l"
	.string "toward the stairs or the exit to\l"
	.string "advance.$"
	.endif
	.ifdef SPANISH
	.string "En las escaleras o a la salida de\n"
	.string "un edificio, encontrarás un felpudo\l"
	.string "rojo. Haz que tu personaje se\l"
	.string "ponga encima y pulsa la dirección\l"
	.string "que quieras en el {PLUS} Panel de\l"
	.string "Control para avanzar.$"
	.endif

Help_Text_AnswerCantFindPersonIWant::
	.ifdef ENGLISH
	.string "This isn't something you should worry\n"
	.string "about too much.\l"
	.string "Talk to other people, check signs,\l"
	.string "check things, and so on.\l"
	.string "Sometimes, you may need to just move\l"
	.string "to a new town or place.$"
	.endif
	.ifdef SPANISH
	.string "No te preocupes, habla con otra\n"
	.string "gente, lee los carteles, curiosea\l"
	.string "cosas...\l"
	.string "En ocasiones, tendrás que ir a\l"
	.string "otros sitios.$"
	.endif

Help_Text_AnswerTalkedToEveryoneNowWhat::
	.ifdef ENGLISH
	.string "Try moving on to a new road, town, or\n"
	.string "place.$"
	.endif
	.ifdef SPANISH
	.string "Ve por otros caminos, pueblos\n"
	.string "o zonas.$"
	.endif

Help_Text_AnswerSomeoneBlockingMyWay::
	.ifdef ENGLISH
	.string "There could be something in the town\n"
	.string "or inside a building that is the cause.\l"
	.string "Try talking to the people in the area\l"
	.string "again. If there is a problem that they\l"
	.string "need solved, you may have to help.\l"
	.string "Afterwards, try talking to the person\l"
	.string "blocking your way again.$"
	.endif
	.ifdef SPANISH
	.string "Quizá la causa esté dentro del\n"
	.string "pueblo o en un edificio... Habla\l"
	.string "de nuevo con la gente. Igual\l"
	.string "alguien necesita que le ayudes\l"
	.string "con algo. Vuelve entonces a hablar\l"
	.string "con quien bloquea el camino.$"
	.endif

Help_Text_AnswerICantGoOn::
	.ifdef ENGLISH
	.string "Try talking to people by going up to\n"
	.string "them and pressing the A Button.\l"
	.string "Also, try checking things like odd trees\l"
	.string "and strange rocks with the A Button.\l"
	.string "Press the {PLUS} Control Pad and try going\l"
	.string "to places that look impassable, too.$"
	.endif
	.ifdef SPANISH
	.string "Cuando te cruces con alguien,\n"
	.string "acércate y pulsa el Botón A para\l"
	.string "hablar. Haz lo mismo cuando veas\l"
	.string "rocas y árboles raros y curiosea\l"
	.string "un poco. Usa el {PLUS} Panel de Control\l"
	.string "para acceder a sitios que parezcan\l"
	.string "inaccesibles.$"
	.endif

Help_Text_AnswerOutOfThingsToDo::
	.ifdef ENGLISH
	.string "Try going to places where you \n"
	.string "haven't visited yet.\l"
	.string "Also, check everything that looks\l"
	.string "suspicious by pressing the A Button.$"
	.endif
	.ifdef SPANISH
	.string "Ve a sitios en los que aún no\n"
	.string "has estado y curiosea todo lo que\l"
	.string "te parezca sospechoso pulsando\l"
	.string "el Botón A.$"
	.endif

Help_Text_AnswerWhatHappenedToItemIGot::
	.ifdef ENGLISH
	.string "Any item that you are given by another\n"
	.string "character goes in your BAG.\l"
	.string "The item is automatically sorted and\l"
	.string "placed in one of three pockets.\l"
	.string "For instructions on the BAG's use,\l"
	.string "please refer to the HELP System's\l"
	.string "“How do I do this?” heading.$"
	.endif
	.ifdef SPANISH
	.string "Los objetos que te den irán a tu\n"
	.string "MOCHILA directamente. Cada cosa\l"
	.string "se colocará de forma ordenada\l"
	.string "en el bolsillo que le corresponda.\l"
	.string "Para usar la MOCHILA, echa un ojo\l"
	.string "a la pregunta del sistema de AYUDA\l"
	.string "“¿Cómo lo hago?”.$"
	.endif

Help_Text_AnswerWhatAreMyAdventureBasics::
	.ifdef ENGLISH
	.string "If POKéMON are hurt in battle,\n"
	.string "take them to a POKéMON CENTER and\l"
	.string "have them healed by the staff.\l"
	.string "Get in the habit of saving your\l"
	.string "game and recording your progress.\l"
	.string "Stock up on healing items at\l"
	.string "POKéMON MARTS before traveling far.$"
	.endif
	.ifdef SPANISH
	.string "Si los POKéMON resultan heridos\n"
	.string "en combate, llévalos a un CENTRO\l"
	.string "POKéMON para que los curen. Es\l"
	.string "bueno que guardes la partida y que\l"
	.string "compres objetos curativos en las\l"
	.string "TIENDAS POKéMON cuando vayas\l"
	.string "a hacer largas distancias.$"
	.endif

Help_Text_AnswerHowAreRoadsForestsDifferent::
	.ifdef ENGLISH
	.string "Forests are basically the same as\n"
	.string "roads but they can be like mazes.\l"
	.string "All forests have a way out, so don't\l"
	.string "give up if you get lost.$"
	.endif
	.ifdef SPANISH
	.string "Básicamente no hay diferencia, pero\n"
	.string "los bosques son algo laberínticos.\l"
	.string "De todas formas, siempre tienen\l"
	.string "una salida, así que no desesperes\l"
	.string "si te pierdes.$"
	.endif

Help_Text_AnswerHowAreCavesDifferent::
	.ifdef ENGLISH
	.string "Caves are dark and dangerous. Wild\n"
	.string "POKéMON can appear anywhere in them.\l"
	.string "If there is an emergency, rush to a\l"
	.string "POKéMON CENTER or use items.\l"
	.string "New towns await discovery beyond some\l"
	.string "caves, so don't give up.$"
	.endif
	.ifdef SPANISH
	.string "Las cuevas son oscuras y\n"
	.string "peligrosas y están llenas de\l"
	.string "POKéMON salvajes. En caso de\l"
	.string "emergencia, corre a un CENTRO\l"
	.string "POKéMON o usa los objetos que\l"
	.string "tengas. Recupérate y llega hasta\l"
	.string "el otro lado; merece la pena.$"
	.endif

Help_Text_AnswerHowDoIProgress::
	.ifdef ENGLISH
	.string "The object of the game is to train\n"
	.string "your POKéMON and move forward.\l"
	.string "You must collect info and solve\l"
	.string "problems. For example, what do you\l"
	.string "need to get around an obstacle?\l"
	.string "What would get that impeding\l"
	.string "person out of the way?$"
	.endif
	.ifdef SPANISH
	.string "El objetivo del juego es entrenar\n"
	.string "a tus POKéMON y avanzar. Debes\l"
	.string "conseguir información y resolver\l"
	.string "situaciones. Tendrás que buscar la\l"
	.string "forma de esquivar un obstáculo o\l"
	.string "de conseguir que alguien se quite\l"
	.string "de tu camino, entre otras cosas.$"
	.endif

Help_Text_AnswerWhenCanIUseItem::
	.ifdef ENGLISH
	.string "There are several kinds of items.\n"
	.string "Some can be used only on the field.\l"
	.string "Some are only for use during battle.\l"
	.string "Some can be used anytime.\l"
	.string "Try using an item - if it can't be used,\l"
	.string "you will be alerted.$"
	.endif
	.ifdef SPANISH
	.string "Depende del tipo. Algunos puedes\n"
	.string "usarlos durante el viaje; y otros,\l"
	.string "en combate. Tú, inténtalo siempre,\l"
	.string "si no está permitido, se te dirá.$"
	.endif

Help_Text_AnswerWhatsABattle::
	.ifdef ENGLISH
	.string "In a battle, POKéMON try to reduce\n"
	.string "one another's vitality, expressed as\l"
	.string "HP. If a POKéMON's HP falls to zero,\l"
	.string "it faints, and the other POKéMON\l"
	.string "wins. By winning a battle, POKéMON\l"
	.string "earn EXP. Points, which help them\l"
	.string "level up (grow stronger).$"
	.endif
	.ifdef SPANISH
	.string "El encuentro en el que debes\n"
	.string "tratar de reducir la energía del\l"
	.string "rival, los PS, a cero. Cuando tu\l"
	.string "contrario se debilite, ganarás y\l"
	.string "obtendrás puntos de EXP. Cuantos\l"
	.string "más puntos de EXP. tengan tus\l"
	.string "POKéMON, antes evolucionarán.$"
	.endif

Help_Text_AnswerHowDoIPrepareForBattle::
	.ifdef ENGLISH
	.string "First, fully heal the POKéMON in your\n"
	.string "party (the POKéMON with you) at any\l"
	.string "POKéMON CENTER.\l"
	.string "You should also buy healing items for\l"
	.string "emergencies at a POKéMON MART.$"
	.endif
	.ifdef SPANISH
	.string "En primer lugar, los miembros de\n"
	.string "tu equipo (los POKéMON que te\l"
	.string "acompañan) deben estar en forma.\l"
	.string "Cúralos en un CENTRO POKéMON.\l"
	.string "Y lleva siempre encima objetos\l"
	.string "curativos de los que encontrarás\l"
	.string "en las TIENDAS POKéMON.$"
	.endif

Help_Text_AnswerWhatIsAMonsVitality::
	.ifdef ENGLISH
	.string "A POKéMON's vitality is expressed in HP.\n"
	.string "If a POKéMON is hurt in battle, HP is\l"
	.string "subtracted. If its HP drops to zero,\l"
	.string "the POKéMON faints.\l"
	.string "Heal hurt or fainted POKéMON at a\l"
	.string "POKéMON CENTER or by using items.$"
	.endif
	.ifdef SPANISH
	.string "Es la fuerza que le queda, y se\n"
	.string "expresa en PS. Si un POKéMON\l"
	.string "resulta herido en combate, sus PS\l"
	.string "bajan. Si éstos llegaran a cero, se\l"
	.string "debilitará. Cura a los POKéMON\l"
	.string "heridos o debilitados en un CENTRO\l"
	.string "POKéMON o usando objetos.$"
	.endif

Help_Text_AnswerMyMonsAreHurt::
	.ifdef ENGLISH
	.string "A POKéMON CENTER is like an inn for\n"
	.string "POKéMON. It will fully heal POKéMON of\l"
	.string "any status problems and fully restore\l"
	.string "their HP using a special machine.\l"
	.string "This service is free, so get in the\l"
	.string "habit of healing your POKéMON often.$"
	.endif
	.ifdef SPANISH
	.string "Ve a un CENTRO POKéMON.\n"
	.string "Es un lugar de recuperación para\l"
	.string "los POKéMON. A través de un\l"
	.string "proceso mecánico, recuperan los PS\l"
	.string "y eliminan los problemas de estado.\l"
	.string "Es un servicio gratuito, así que\l"
	.string "úsalo con frecuencia.$"
	.endif

Help_Text_AnswerWhatIsStatusProblem::
	.ifdef ENGLISH
	.string "A status problem refers to an ailment\n"
	.string "that is inflicted on a POKéMON by its\l"
	.string "foe's attack. These include burns,\l"
	.string "paralysis, poisoning, sleep, and\l"
	.string "freezing. These can be healed by\l"
	.string "visiting a POKéMON CENTER or using\l"
	.string "the appropriate item.$"
	.endif
	.ifdef SPANISH
	.string "Son las alteraciones que sufre un\n"
	.string "POKéMON tras recibir un ataque.\l"
	.string "Puede ser quemadura, parálisis,\l"
	.string "envenenamiento, sueño profundo\l"
	.string "y congelamiento. Pero se pueden\l"
	.string "eliminar en un CENTRO POKéMON\l"
	.string "o con el objeto adecuado.$"
	.endif

Help_Text_AnswerWhatHappensIfAllMyMonsFaint::
	.ifdef ENGLISH
	.string "If all the POKéMON in your party\n"
	.string "(all the POKéMON with you) faint, you\l"
	.string "lose some MONEY, and you are\l"
	.string "returned home or to a POKéMON\l"
	.string "CENTER. To reduce that chance, visit\l"
	.string "POKéMON CENTERS often. Also, get\l"
	.string "in the habit of saving often.$"
	.endif
	.ifdef SPANISH
	.string "Si los POKéMON de tu equipo (los\n"
	.string "que te acompañan) se debilitan,\l"
	.string "pierdes DINERO y vuelves a casa\l"
	.string "o a un CENTRO POKéMON. Para\l"
	.string "intentar que no ocurra, ve a los\l"
	.string "CENTROS POKéMON con frecuencia.\l"
	.string "¡Y no te olvides de guardar!$"
	.endif

Help_Text_AnswerCantCatchMons::
	.ifdef ENGLISH
	.string "If a wild POKéMON escapes from a POKé\n"
	.string "BALL, it's obviously still feisty.\l"
	.string "Try reducing its HP some more, and\l"
	.string "try to weaken it with paralysis or sleep\l"
	.string "before trying to catch it.\l"
	.string "If the POKé BALL rocks for a while,\l"
	.string "the quarry is close to being caught!$"
	.endif
	.ifdef SPANISH
	.string "Si un POKéMON salvaje se escapa\n"
	.string "de una POKé BALL, es que aún\l"
	.string "tiene ganas de luchar. Intenta\l"
	.string "reducir más sus PS y paralizarlo o\l"
	.string "dejarlo dormido antes de atraparlo.\l"
	.string "Si ves que la POKé BALL se mueve\l"
	.string "durante un rato, ¡es casi tuyo!$"
	.endif

Help_Text_AnswerRanOutOfPotions::
	.ifdef ENGLISH
	.string "There are shops, known as POKéMON\n"
	.string "MARTS, that sell items.\l"
	.string "You will not find POKéMON MARTS on\l"
	.string "roads, in forests, or in caves.\l"
	.string "Stock up on needed items while you are\l"
	.string "visiting a town with a POKéMON MART.$"
	.endif
	.ifdef SPANISH
	.string "Hay establecimientos, llamados\n"
	.string "TIENDAS POKéMON, en los que venden\l"
	.string "objetos. Pero ten en cuenta que en\l"
	.string "rutas, bosques y cuevas no hay.\l"
	.string "Aprovecha cuando estés en algún\l"
	.string "pueblo y compra lo que necesites.$"
	.endif

Help_Text_AnswerCanIBuyPokeBalls::
	.ifdef ENGLISH
	.string "You may buy POKé BALLS at any\n"
	.string "POKéMON MART in any town.\l"
	.string "You will not find POKéMON MARTS on\l"
	.string "roads, in forests, or in caves.\l"
	.string "Stock up on POKé BALLS while you are\l"
	.string "visiting a town with a POKéMON MART.$"
	.endif
	.ifdef SPANISH
	.string "Podrás comprar POKé BALLS\n"
	.string "en cualquier TIENDA POKéMON.\l"
	.string "Pero ten en cuenta que en\l"
	.string "rutas, bosques y cuevas no hay.\l"
	.string "Aprovecha cuando estés en algún\l"
	.string "pueblo y compra lo que necesites.$"
	.endif

Help_Text_AnswerWhatsATrainer::
	.ifdef ENGLISH
	.string "A TRAINER is a person who raises\n"
	.string "POKéMON through battling.\l"
	.string "TRAINERS will challenge you \l"
	.string "wherever they are - it could be on\l"
	.string "a road, in forests, caves, anywhere.\l"
	.string "If your eyes meet, you have to accept\l"
	.string "their challenge. So be careful!$"
	.endif
	.ifdef SPANISH
	.string "Un ENTRENADOR es alguien que cría\n"
	.string "POKéMON luchando. Siempre desafía\l"
	.string "a quien se encuentra, esté donde\l"
	.string "esté. Como cruces la mirada con\l"
	.string "alguno, tendrás que luchar.\l"
	.string "¡Mucho ojo!$"
	.endif

Help_Text_AnswerHowDoIWinAgainstTrainer::
	.ifdef ENGLISH
	.string "To beat a TRAINER in battle, use\n"
	.string "POKéMON that have type advantages\l"
	.string "over the foe's POKéMON. You may also\l"
	.string "use highly trained POKéMON with\l"
	.string "overwhelming power. Outnumbering the\l"
	.string "foe's POKéMON is another obvious\l"
	.string "tactic.$"
	.endif
	.ifdef SPANISH
	.string "Para ganar a un ENTRENADOR, usa\n"
	.string "POKéMON que tengan tipos a los que\l"
	.string "les puedas sacar ventaja. Los\l"
	.string "que estén más entrenados te serán\l"
	.string "muy útiles, igual que los de nivel\l"
	.string "superior a los de tu rival.$"
	.endif

Help_Text_AnswerWhereDoMonsAppear::
	.ifdef ENGLISH
	.string "Wild POKéMON will appear in tall grass,\n"
	.string "on roads, and in forests. They will\l"
	.string "appear anywhere in dark caves.\l"
	.string "There are no wild POKéMON or TRAINERS\l"
	.string "in towns, so they are safe places.$"
	.endif
	.ifdef SPANISH
	.string "Los POKéMON salvajes suelen salir\n"
	.string "de las zonas de hierba alta de las\l"
	.string "rutas y los bosques. En las cuevas\l"
	.string "aparecen en cualquier lugar.\l"
	.string "En los pueblos no hay POKéMON\l"
	.string "salvajes ni ENTRENADORES, así\l"
	.string "que son sitios seguros.$"
	.endif

Help_Text_AnswerWhatAreMoves::
	.ifdef ENGLISH
	.string "POKéMON may learn up to four different\n"
	.string "techniques, or moves. There is a great\l"
	.string "variety of moves including attacks and\l"
	.string "those with special effects. The kinds\l"
	.string "of moves that can be learned vary\l"
	.string "for each POKéMON. Some moves\l"
	.string "can be learned from machines.$"
	.endif
	.ifdef SPANISH
	.string "Son las técnicas que aprenden.\n"
	.string "Hay muchas e incluyen ataques\l"
	.string "y movimientos que tienen efectos\l"
	.string "especiales. Según sea el tipo del\l"
	.string "POKéMON, así serán los movimientos\l"
	.string "que pueda aprender. Algunos se\l"
	.string "aprenden a través de máquinas.$"
	.endif

Help_Text_AnswerWhatAreHiddenMoves::
	.ifdef ENGLISH
	.string "HIDDEN moves are those that are\n"
	.string "especially important for your\l"
	.string "adventure. To use such a move outside\l"
	.string "of battle, open the “POKéMON” MENU\l"
	.string "and make the POKéMON that knows the\l"
	.string "move use it. A fainted POKéMON may use\l"
	.string "a HIDDEN move outside of battle.$"
	.endif
	.ifdef SPANISH
	.string "Los movimientos OCULTOS son los\n"
	.string "más importantes para tu aventura.\l"
	.string "Para usar uno fuera de combate,\l"
	.string "tienes que abrir el menú POKéMON\l"
	.string "y hacer que el POKéMON que conoce\l"
	.string "la técnica la use. Esto funcionará\l"
	.string "aunque el POKéMON esté debilitado.$"
	.endif

Help_Text_AnswerWhatMovesShouldIUse::
	.ifdef ENGLISH
	.string "Select “FIGHT,” and the MENU of moves\n"
	.string "will appear. Consider the type\l"
	.string "matchups, and use the most effective\l"
	.string "moves. You can check the effects of\l"
	.string "moves by opening “POKéMON,”\l"
	.string "picking a POKéMON, opening “SUMMARY,”\l"
	.string "then opening “POKéMON SKILLS.”$"
	.endif
	.ifdef SPANISH
	.string "Selecciona LUCHA para ver el\n"
	.string "menú de los movimientos. Fíjate en\l"
	.string "la combinación de los tipos. Para\l"
	.string "ver qué efecto tiene un movimiento,\l"
	.string "elige POKéMON, selecciona uno,\l"
	.string "entra en DATOS y después en\l"
	.string "MOV. CONOCIDOS.$"
	.endif

Help_Text_AnswerWantToAddMoreMoves::
	.ifdef ENGLISH
	.string "The most a POKéMON can learn is four\n"
	.string "moves. They are learned as the\l"
	.string "POKéMON levels up. It can also be\l"
	.string "taught a move using a TM (Technical\l"
	.string "Machine) or HM (Hidden Machine).\l"
	.string "There are also people who teach moves.$"
	.endif
	.ifdef SPANISH
	.string "Un POKéMON aprende cuatro\n"
	.string "movimientos al ir subiendo de nivel.\l"
	.string "Pero se le puede enseñar otros\l"
	.string "usando MT (Máquinas Técnicas)\l"
	.string "o MO (Máquinas Ocultas).\l"
	.string "Además, hay mucha gente\l"
	.string "que enseña movimientos.$"
	.endif

Help_Text_AnswerWantToMakeMonStronger::
	.ifdef ENGLISH
	.string "The key to making your POKéMON\n"
	.string "strong is to battle and win often.\l"
	.string "The EXP. (Experience) Points earned\l"
	.string "by winning battles accumulate to\l"
	.string "level up POKéMON that participated in\l"
	.string "them. Battle wild POKéMON often to\l"
	.string "level up your party.$"
	.endif
	.ifdef SPANISH
	.string "Para fortalecer a tus POKéMON\n"
	.string "debes luchar y ganar a menudo. Los\l"
	.string "puntos de EXP. se repartirán entre\l"
	.string "los miembros de tu equipo que\l"
	.string "entraron en combate, y harán que\l"
	.string "suban de nivel. Con los POKéMON\l"
	.string "salvajes se puede entrenar bien.$"
	.endif

Help_Text_AnswerFoeMonsTooStrong::
	.ifdef ENGLISH
	.string "If your foes are too strong, try\n"
	.string "leveling up your POKéMON some more.\l"
	.string "Go back the way you came and battle\l"
	.string "wild POKéMON to level up your party.\l"
	.string "You may also battle TRAINERS whom you\l"
	.string "have not battled before.$"
	.endif
	.ifdef SPANISH
	.string "Si tu rival es demasiado fuerte,\n"
	.string "sube más el nivel de tus POKéMON.\l"
	.string "Busca POKéMON salvajes con los\l"
	.string "que entrenarte para que mejore el\l"
	.string "nivel de tu equipo. También puedes\l"
	.string "enfrentarte a ENTRENADORES con\l"
	.string "los que no hayas luchado todavía.$"
	.endif

Help_Text_AnswerWhatDoIDoInCave::
	.ifdef ENGLISH
	.string "Unlike roads and forests, wild POKéMON\n"
	.string "can appear anywhere in caves.\l"
	.string "If your POKéMON are hurt in a cave,\l"
	.string "rush to a POKéMON CENTER or use items\l"
	.string "to heal them right away. It is very\l"
	.string "dangerous to force your luck in caves.$"
	.endif
	.ifdef SPANISH
	.string "Ten mucho cuidado cuando vayas\n"
	.string "a atravesar una. No son como los\l"
	.string "bosques y las rutas; aquí salen\l"
	.string "POKéMON salvajes por todos lados.\l"
	.string "Si tus POKéMON resultaran heridos,\l"
	.string "llévalos a un CENTRO POKéMON o\l"
	.string "cúralos corriendo con algún objeto.$"
	.endif

Help_Text_AnswerNothingIWantToKnow::
	.ifdef ENGLISH
	.string "Trust your own knowledge and power.\n"
	.string "Believe in yourself and find your way!$"
	.endif
	.ifdef SPANISH
	.string "Confía en lo que sabes y en tu\n"
	.string "fuerza.\l"
	.string "¡Podrás hacer lo que te propongas!$"
	.endif

Help_Text_AnswerWhatsPokemonCenter::
	.ifdef ENGLISH
	.string "A POKéMON CENTER is identified by its\n"
	.string "red roof and a “P.C” sign. Every\l"
	.string "POKéMON CENTER offers such services as\l"
	.string "fully healing POKéMON and free PC use,\l"
	.string "making it essential for your travels.\l"
	.string "On the upper floor are facilities for\l"
	.string "linking with friends and others.$"
	.endif
	.ifdef SPANISH
	.string "Es la casa en la que pone “POKé”.\n"
	.string "En todos curan a los POKéMON, y\l"
	.string "hay acceso a PC, lo que es básico\l"
	.string "durante el viaje. El piso de arriba\l"
	.string "está preparado para que te\l"
	.string "conectes con tus amigos.$"
	.endif

Help_Text_AnswerWhatsPokemonMart::
	.ifdef ENGLISH
	.string "A POKéMON MART is identified by its\n"
	.string "blue roof and a “MART” sign.\l"
	.string "Items can be bought and sold at any\l"
	.string "POKéMON MART. Some MARTS carry items\l"
	.string "that are available only in their towns.$"
	.endif
	.ifdef SPANISH
	.string "Es la casa del tejado azul en la\n"
	.string "que pone “SHOP”. En ellas se\l"
	.string "pueden comprar o vender objetos, y\l"
	.string "algunas tienen objetos exclusivos.$"
	.endif

Help_Text_AnswerWantToEndGame::
	.ifdef ENGLISH
	.string "You can safely end your game by\n"
	.string "selecting “SAVE” on the MENU.\l"
	.string "Once you have saved, the game can be\l"
	.string "safely turned off. When the game is\l"
	.string "turned back on, you can resume from\l"
	.string "where you last saved.$"
	.endif
	.ifdef SPANISH
	.string "Cuando quieras, podrás seleccionar\n"
	.string "“GUARDAR” en el menú.\l"
	.string "Cuando hayas guardado la partida,\l"
	.string "podrás apagar la consola (OFF),\l"
	.string "así podrás continuar cuando quieras\l"
	.string "desde el mismo lugar en el que\l"
	.string "te quedaste al guardar la partida.$"
	.endif

Help_Text_AnswerWhatsAMon::
	.ifdef ENGLISH
	.string "POKéMON are living beings about which\n"
	.string "many mysteries still remain. You may\l"
	.string "see them in grass, the sea, and caves.\l"
	.string "They appear to obey the wishes of the\l"
	.string "TRAINERS that caught them.$"
	.endif
	.ifdef SPANISH
	.string "Los POKéMON son unas criaturas\n"
	.string "de las que aún no se sabe todo.\l"
	.string "Es fácil verlas entre la hierba,\l"
	.string "en el mar, y en las cuevas.\l"
	.string "En general, suelen obedecer\l"
	.string "los deseos de su ENTRENADOR.$"
	.endif

Help_Text_AnswerWhatIsThatPersonLike::
	.ifdef ENGLISH
	.string "Use the FAME CHECKER among the\n"
	.string "KEY ITEMS in your BAG.\l"
	.string "It may give you a hint, so try it out.$"
	.endif
	.ifdef SPANISH
	.string "Usa el MEMORÍN que tienes en el\n"
	.string "BOLSILLO de los OBJETOS CLAVES\l"
	.string "de la MOCHILA. Seguro que te da\l"
	.string "información muy útil.$"
	.endif

Help_Text_AnswerWhatDoesHiddenMoveDo::
	.ifdef ENGLISH
	.string "A HIDDEN move is taught to a POKéMON\n"
	.string "using an HM (Hidden Machine).\l"
	.string "A HIDDEN move is important for helping\l"
	.string "your adventure. For example, one is\l"
	.string "used to light up dark caves. Another\l"
	.string "cuts down small trees. There is one\l"
	.string "for traveling on water, and so on.$"
	.endif
	.ifdef SPANISH
	.string "Los movimientos OCULTOS se enseñan\n"
	.string "usando una MO (Máquina Oculta).\l"
	.string "Son muy importantes para tu viaje.\l"
	.string "Por ejemplo, con uno iluminas\l"
	.string "cuevas oscuras, y con otro, cortas\l"
	.string "árboles pequeños. También hay uno\l"
	.string "para desplazarse por el agua...$"
	.endif

Help_Text_AnswerWhatDoIDoInSafari::
	.ifdef ENGLISH
	.string "Try to catch wild POKéMON by throwing\n"
	.string "the special SAFARI BALLS.\l"
	.string "You may keep any item you find, too.$"
	.endif
	.ifdef SPANISH
	.string "Intenta atrapar POKéMON salvajes\n"
	.string "lanzando las especiales SAFARI\l"
	.string "BALLS. ¡Y guarda los objetos\l"
	.string "que encuentres!$"
	.endif

Help_Text_AnswerWhatAreSafariRules::
	.ifdef ENGLISH
	.string "Your SAFARI GAME ends once you have\n"
	.string "traveled a certain distance or thrown\l"
	.string "all your SAFARI BALLS.\l"
	.string "Open the MENU to check the remaining\l"
	.string "number of steps and SAFARI BALLS.$"
	.endif
	.ifdef SPANISH
	.string "Tu estancia en el SAFARI acaba al\n"
	.string "recorrer cierta distancia o quedarte\l"
	.string "sin SAFARI BALLS. Abre el menú\l"
	.string "para ver cuántos pasos has dado\l"
	.string "y las SAFARI BALLS que te quedan.$"
	.endif

Help_Text_AnswerWantToEndSafari::
	.ifdef ENGLISH
	.string "If you would like to cut your SAFARI\n"
	.string "GAME short, open the MENU and select\l"
	.string "“RETIRE” at the top of the list.$"
	.endif
	.ifdef SPANISH
	.string "Si quieres retirarte del SAFARI,\n"
	.string "abre el menú y selecciona RETIR.$"
	.endif

Help_Text_AnswerWhatIsAGym::
	.ifdef ENGLISH
	.string "POKéMON GYMS are operated by the\n"
	.string "POKéMON LEAGUE and are training\l"
	.string "facilities for TRAINERS. They are all\l"
	.string "across the land in cities and towns.\l"
	.string "Each one is headed by a LEADER, who\l"
	.string "is a very skilled TRAINER. Beat the\l"
	.string "LEADER to collect a BADGE.$"
	.endif
	.ifdef SPANISH
	.string "Un GIMNASIO POKéMON es el lugar\n"
	.string "en el que luchan los ENTRENADORES\l"
	.string "de la LIGA POKéMON. Hay por toda\l"
	.string "la zona y los dirigen LÍDERES muy\l"
	.string "experimentados. Para ganar la\l"
	.string "MEDALLA del GIMNASIO, hay que\l"
	.string "vencer al LÍDER.$"
	.endif

Help_Text_UsingPokedex::
	.ifdef ENGLISH
	.string " Using “POKéDEX”$"
	.endif
	.ifdef SPANISH
	.string "Usando POKéDEX.$"
	.endif

Help_Text_UsingPokemon::
	.ifdef ENGLISH
	.string " Using “POKéMON”$"
	.endif
	.ifdef SPANISH
	.string "Usando POKéMON.$"
	.endif

Help_Text_UsingSummary::
	.ifdef ENGLISH
	.string "  Using “SUMMARY”$"
	.endif
	.ifdef SPANISH
	.string "  Usando DATOS.$"
	.endif

Help_Text_UsingSwitch::
	.ifdef ENGLISH
	.string "  Using “SWITCH”$"
	.endif
	.ifdef SPANISH
	.string "  Usando CAMBIO.$"
	.endif

Help_Text_UsingItem::
	.ifdef ENGLISH
	.string "  Using “ITEM”$"
	.endif
	.ifdef SPANISH
	.string "  Usando OBJETO.$"
	.endif

Help_Text_UsingBag::
	.ifdef ENGLISH
	.string " Using “BAG”$"
	.endif
	.ifdef SPANISH
	.string "Usando MOCHILA.$"
	.endif

Help_Text_UsingAnItem::
	.ifdef ENGLISH
	.string "  Using an item$"
	.endif
	.ifdef SPANISH
	.string "  Usando un objeto.$"
	.endif

Help_Text_UsingKeyItem::
	.ifdef ENGLISH
	.string "  Using a key item$"
	.endif
	.ifdef SPANISH
	.string "  Usando un objeto clave.$"
	.endif

Help_Text_UsingPokeBall::
	.ifdef ENGLISH
	.string "  Using a POKé BALL$"
	.endif
	.ifdef SPANISH
	.string "  Usando una POKé BALL.$"
	.endif

Help_Text_UsingPlayer::
	.ifdef ENGLISH
	.string " Using “{PLAYER}”$"
	.endif
	.ifdef SPANISH
	.string "Usando {PLAYER}.$"
	.endif

Help_Text_UsingSave::
	.ifdef ENGLISH
	.string " Using “SAVE”$"
	.endif
	.ifdef SPANISH
	.string "Usando GUARDAR.$"
	.endif

Help_Text_UsingOption::
	.ifdef ENGLISH
	.string " Using “OPTION”$"
	.endif
	.ifdef SPANISH
	.string "Usando OPCIONES.$"
	.endif

Help_Text_UsingPotion::
	.ifdef ENGLISH
	.string "    Using a POTION$"
	.endif
	.ifdef SPANISH
	.string "    Usando una POCIÓN.$"
	.endif

Help_Text_UsingTownMap::
	.ifdef ENGLISH
	.string "    Using the TOWN MAP$"
	.endif
	.ifdef SPANISH
	.string "    Usando el MAPA.$"
	.endif

Help_Text_UsingTM::
	.ifdef ENGLISH
	.string "    Using a TM$"
	.endif
	.ifdef SPANISH
	.string "    Usando una MT.$"
	.endif

Help_Text_UsingHM::
	.ifdef ENGLISH
	.string "    Using an HM$"
	.endif
	.ifdef SPANISH
	.string "    Usando una MO.$"
	.endif

Help_Text_UsingMoveOutsideOfBattle::
	.ifdef ENGLISH
	.string "Using a move outside of battle$"
	.endif
	.ifdef SPANISH
	.string "Usando un ataque fuera de combate.$"
	.endif

Help_Text_RidingBicycle::
	.ifdef ENGLISH
	.string "    Riding the BICYCLE$"
	.endif
	.ifdef SPANISH
	.string "    Usando la BICI.$"
	.endif

Help_Text_EnteringName::
	.ifdef ENGLISH
	.string "Entering a name$"
	.endif
	.ifdef SPANISH
	.string "Escribiendo un nombre.$"
	.endif

Help_Text_UsingPC::
	.ifdef ENGLISH
	.string "Using a PC$"
	.endif
	.ifdef SPANISH
	.string "Usando un PC.$"
	.endif

Help_Text_UsingBillsPC::
	.ifdef ENGLISH
	.string " Using “{STR_VAR_1}'S PC”$"
	.endif
	.ifdef SPANISH
	.string "Usando el PC de {STR_VAR_1}.$"
	.endif

Help_Text_UsingWithdraw::
	.ifdef ENGLISH
	.string "  Using “WITHDRAW”$"
	.endif
	.ifdef SPANISH
	.string "  Usando SACAR.$"
	.endif

Help_Text_UsingDeposit::
	.ifdef ENGLISH
	.string "  Using “DEPOSIT”$"
	.endif
	.ifdef SPANISH
	.string "  Usando DEJAR.$"
	.endif

Help_Text_UsingMove::
	.ifdef ENGLISH
	.string "  Using “MOVE”$"
	.endif
	.ifdef SPANISH
	.string "  Usando MOVER.$"
	.endif

Help_Text_MovingItems::
	.ifdef ENGLISH
	.string "  Moving items$"
	.endif
	.ifdef SPANISH
	.string "  Moviendo objetos.$"
	.endif

Help_Text_UsingPlayersPC::
	.ifdef ENGLISH
	.string " Using “{PLAYER}'s PC”$"
	.endif
	.ifdef SPANISH
	.string " Usando el PC de {PLAYER}.$"
	.endif

Help_Text_UsingWithdrawItem::
	.ifdef ENGLISH
	.string "  Using “WITHDRAW ITEM”$"
	.endif
	.ifdef SPANISH
	.string "  Usando SACAR OBJETO.$"
	.endif

Help_Text_UsingDepositItem::
	.ifdef ENGLISH
	.string "  Using “DEPOSIT ITEM”$"
	.endif
	.ifdef SPANISH
	.string "  Usando DEJAR OBJETO.$"
	.endif

Help_Text_UsingMailbox::
	.ifdef ENGLISH
	.string "  Using “MAILBOX”$"
	.endif
	.ifdef SPANISH
	.string "  Usando BUZÓN.$"
	.endif

Help_Text_UsingProfOaksPC::
	.ifdef ENGLISH
	.string " Using “PROF. OAK'S PC”$"
	.endif
	.ifdef SPANISH
	.string " Usando el PC del PROF. OAK.$"
	.endif

Help_Text_OpeningMenu::
	.ifdef ENGLISH
	.string "Opening the MENU$"
	.endif
	.ifdef SPANISH
	.string "Abriendo el menú.$"
	.endif

Help_Text_UsingFight::
	.ifdef ENGLISH
	.string " Using “FIGHT”$"
	.endif
	.ifdef SPANISH
	.string " Usando LUCHA.$"
	.endif

Help_Text_UsingPokemon2::
	.ifdef ENGLISH
	.string " Using “POKéMON”$"
	.endif
	.ifdef SPANISH
	.string " Usando POKéMON.$"
	.endif

Help_Text_UsingShift::
	.ifdef ENGLISH
	.string "  Using “SHIFT”$"
	.endif
	.ifdef SPANISH
	.string "  Usando CAMBIO.$"
	.endif

Help_Text_UsingSummary2::
	.ifdef ENGLISH
	.string "  Using “SUMMARY”$"
	.endif
	.ifdef SPANISH
	.string "  Usando DATOS.$"
	.endif

Help_Text_UsingBag2::
	.ifdef ENGLISH
	.string " Using “BAG”$"
	.endif
	.ifdef SPANISH
	.string " Usando MOCHILA.$"
	.endif

Help_Text_ReadingPokedex::
	.ifdef ENGLISH
	.string " Reading the “POKéDEX”$"
	.endif
	.ifdef SPANISH
	.string " Leyendo la POKéDEX.$"
	.endif

Help_Text_UsingHomePC::
	.ifdef ENGLISH
	.string "Using the PC at home$"
	.endif
	.ifdef SPANISH
	.string "Usando el PC de casa.$"
	.endif

Help_Text_UsingItemStorage::
	.ifdef ENGLISH
	.string "Using the Item Storage System$"
	.endif
	.ifdef SPANISH
	.string "Usando el Sist. de Almacenamiento.$"
	.endif

Help_Text_UsingWithdrawItem2::
	.ifdef ENGLISH
	.string "  Using “WITHDRAW ITEM”$"
	.endif
	.ifdef SPANISH
	.string "  Usando SACAR OBJETO.$"
	.endif

Help_Text_UsingDepositItem2::
	.ifdef ENGLISH
	.string "  Using “DEPOSIT ITEM”$"
	.endif
	.ifdef SPANISH
	.string "  Usando DEJAR OBJETO.$"
	.endif

Help_Text_UsingMailbox2::
	.ifdef ENGLISH
	.string "Using the MAILBOX$"
	.endif
	.ifdef SPANISH
	.string "Usando el BUZÓN.$"
	.endif

Help_Text_UsingRun::
	.ifdef ENGLISH
	.string " Using “RUN”$"
	.endif
	.ifdef SPANISH
	.string "Usando HUIDA.$"
	.endif

Help_Text_RegisterKeyItem::
	.ifdef ENGLISH
	.string "  “REGISTER” a key item$"
	.endif
	.ifdef SPANISH
	.string "  ASIGNANDO un objeto clave.$"
	.endif

Help_Text_UsingBall::
	.ifdef ENGLISH
	.string " Using “BALL”$"
	.endif
	.ifdef SPANISH
	.string "Usando BALL.$"
	.endif

Help_Text_UsingBait::
	.ifdef ENGLISH
	.string " Using “BAIT”$"
	.endif
	.ifdef SPANISH
	.string "Usando CEBO.$"
	.endif

Help_Text_UsingRock::
	.ifdef ENGLISH
	.string " Using “ROCK”$"
	.endif
	.ifdef SPANISH
	.string "Usando ROCA.$"
	.endif

Help_Text_UsingHallOfFame::
	.ifdef ENGLISH
	.string " Using “HALL OF FAME”$"
	.endif
	.ifdef SPANISH
	.string "Usando HALL FAMA.$"
	.endif

Help_Text_HowToUsePokedex::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “POKéDEX” on the MENU.\n"
	.string "{CIRCLE_2} Choose POKéMON using commands such\n"
	.string "   as “POKéMON LIST,”\n"
	.string "   “HABITATS OF POKéMON,” and\n"
	.string "   “SEARCH.”\n"
	.string "{CIRCLE_3} Select a POKéMON to obtain detailed\n"
	.string "   information.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona POKéDEX en el menú.\n"
	.string "{CIRCLE_2} Busca POKéMON según criterios\n"
	.string "   como LAS POKéDEX o POKéMON\n"
	.string "   SEGÚN SU HÁBITAT.\n"
	.string "{CIRCLE_3} Selecciona el POKéMON que\n"
	.string "   quieras para ver los detalles.$"
	.endif

Help_Text_HowToUsePokemon::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “POKéMON” on the MENU.\n"
	.string "{CIRCLE_2} Choose a POKéMON in your party.\n"
	.string "{CIRCLE_3} Select “SUMMARY,” “SWITCH,”\n"
	.string "   or “ITEM.”$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona POKéMON en el menú.\n"
	.string "{CIRCLE_2} Elige un POKéMON de tu equipo.\n"
	.string "{CIRCLE_3} Selecciona DATOS, CAMBIO\n"
	.string "   u OBJETO.$"
	.endif

Help_Text_HowToUseSummary::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “SUMMARY.”\n"
	.string "{CIRCLE_2} Press left or right on the {PLUS} Control\n"
	.string "   Pad to check the information:\n"
	.string "   “POKéMON INFO”\n"
	.string "   “POKéMON SKILLS”\n"
	.string "   “KNOWN MOVES”$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona DATOS.\n"
	.string "{CIRCLE_2} Pulsa izquierda o derecha en el\n"
	.string "   {PLUS} Panel de Control para ver:\n"
	.string "   INFO. POKéMON,\n"
	.string "   HABIL. POKéMON\n"
	.string "   o MOV. CONOCIDOS.$"
	.endif

Help_Text_HowToUseSwitch::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Choose the POKéMON you want to\n"
	.string "   switch around.\n"
	.string "{CIRCLE_2} Select “SWITCH.”\n"
	.string "{CIRCLE_3} Select the POKéMON to switch with\n"
	.string "   the first one.\n"
	.string "The POKéMON at the left of the screen\n"
	.string "will be the first one out in a battle.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Elige el POKéMON que quieras\n"
	.string "   cambiar de posición.\n"
	.string "{CIRCLE_2} Selecciona CAMBIO.\n"
	.string "{CIRCLE_3} Selecciona el POKéMON con el\n"
	.string "   que quieras cambiar al primero.\n"
	.string "El que aparezca en la parte izqda\n"
	.string "será el primero en luchar.$"
	.endif

Help_Text_HowToUseItem::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “ITEM.”\n"
	.string "{CIRCLE_2} Select whether you want to “GIVE”\n"
	.string "   an item to the POKéMON to hold,\n"
	.string "   or “TAKE” an item it is holding.\n"
	.string "A POKéMON can hold no more than one\n"
	.string "item!$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona OBJETO.\n"
	.string "{CIRCLE_2} Decide si quieres DAR un objeto\n"
	.string "   a un POKéMON,\n"
	.string "   o QUITAR un objeto que lleve.\n"
	.string "¡Los POKéMON no pueden llevar más\n"
	.string "de un objeto!$"
	.endif

Help_Text_HowToUseBag::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “BAG” on the MENU.\n"
	.string "{CIRCLE_2} Press left or right on the {PLUS} Control\n"
	.string "   Pad to check the data headings:\n"
	.string "   “ITEMS”\n"
	.string "   “KEY ITEMS”\n"
	.string "   “POKé BALLS”\n"
	.string "   Press up or down to select an item.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona MOCHILA en el menú.\n"
	.string "{CIRCLE_2} Pulsa izquierda o derecha en el\n"
	.string "   {PLUS} Panel de Control para ver:\n"
	.string "   OBJETOS, OBJ. CLAVE\n"
	.string "   o POKé BALLS.\n"
	.string "   Pulsa arriba o abajo para\n"
	.string "   seleccionar un objeto.$"
	.endif

Help_Text_HowToUseAnItem::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select the “ITEMS” POCKET.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad to select an item.\n"
	.string "{CIRCLE_3} Select “USE” to use the selected\n"
	.string "   item.\n"
	.string "Some items may not be used depending\n"
	.string "on the place and/or situation.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona el BOLSILLO de los\n"
	.string "OBJETOS.\n"
	.string "{CIRCLE_2} Pulsa arriba o abajo en el {PLUS}\n"
	.string "   Panel de Control para elegir uno.\n"
	.string "{CIRCLE_3} Selecciona USAR para usarlo.\n"
	.string "Habrá objetos que no puedas usar\n"
	.string "según el sitio y la situación.$"
	.endif

Help_Text_HowToUseKeyItem::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select the “KEY ITEMS” POCKET.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad to select a key item.\n"
	.string "{CIRCLE_3} Select “USE” to use the selected\n"
	.string "   key item.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona el BOLSILLO de los\n"
	.string "OBJ. CLAVE.\n"
	.string "{CIRCLE_2} Pulsa arriba o abajo en el {PLUS}\n"
	.string "   Panel de Control para elegir uno.\n"
	.string "{CIRCLE_3} Selecciona USAR para usarlo.$"
	.endif

Help_Text_HowToUsePokeBall::
	.ifdef ENGLISH
	.string "{CIRCLE_1} While battling a wild POKéMON,\n"
	.string "   select the BAG's “POKé BALLS”\n"
	.string "   POCKET.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad to select a POKé BALL.\n"
	.string "{CIRCLE_3} Select “USE” to throw the selected\n"
	.string "   POKé BALL.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Cuando luches con un POKéMON\n"
	.string "   salvaje, selecciona el BOLSILLO\n"
	.string "   de las POKé BALLS.\n"
	.string "{CIRCLE_2} Pulsa arriba o abajo en el {PLUS}\n"
	.string "   Panel de Control para elegir una\n"
	.string "   POKé BALL.\n"
	.string "{CIRCLE_3} Selecciona USAR para lanzarla.$"
	.endif

Help_Text_HowToUsePlayer::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “{PLAYER}” on the MENU.\n"
	.string "{CIRCLE_2} Your TRAINER CARD is displayed face\n"
	.string "   up with basic information. Press the\n"
	.string "   A Button to turn the CARD over.\n"
	.string "{CIRCLE_3} A variety of data can be found on\n"
	.string "   the reverse side of the CARD.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona {PLAYER} en el menú.\n"
	.string "{CIRCLE_2} Aparecerá boca arriba tu FICHA\n"
	.string "   de ENTRENADOR con información\n"
	.string "   básica. Pulsa el Botón A para\n"
	.string "   darle la vuelta.\n"
	.string "{CIRCLE_3} Verás los distintos datos\n"
	.string "   que hay.$"
	.endif

Help_Text_HowToUseSave::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “SAVE” on the MENU.\n"
	.string "{CIRCLE_2} Select “YES” and your progress is\n"
	.string "   recorded in the save file.\n"
	.string "Once the game is saved, you may turn\n"
	.string "off the game. Your game can be resumed\n"
	.string "from where you saved.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona GUARDAR en el menú.\n"
	.string "{CIRCLE_2} Selecciona SÍ para guardar\n"
	.string "   la partida.\n"
	.string "Cuando guardes, puedes apagar\n"
	.string "(OFF) la consola. Cuando quieras\n"
	.string "jugar de nuevo, podrás continuar\n"
	.string "desde donde lo dejaste.$"
	.endif

Help_Text_HowToUseOption::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “OPTION” on the MENU.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad to select an optional item, then\n"
	.string "   press left or right to alter the\n"
	.string "   settings.\n"
	.string "{CIRCLE_3} Select “CANCEL” or press the\n"
	.string "   B Button after making changes.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona OPCIONES en el menú.\n"
	.string "{CIRCLE_2} Pulsa arriba o abajo en el {PLUS}\n"
	.string "   Panel de Control para elegir\n"
	.string "   lo que quieras cambiar y hazlo\n"
	.string "   pulsando izquierda o derecha.\n"
	.string "{CIRCLE_3} Selecciona SALIR o pulsa el\n"
	.string "   Botón B cuando hayas acabado.$"
	.endif

Help_Text_HowToUsePotion::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Open the MENU.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad and select “BAG.”\n"
	.string "{CIRCLE_3} Select “POTION” in the “ITEMS”\n"
	.string "   POCKET.\n"
	.string "{CIRCLE_4} Select “USE.”\n"
	.string "{CIRCLE_5} Select the POKéMON to be healed.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Abre el menú.\n"
	.string "{CIRCLE_2} Pulsa arriba o abajo en el {PLUS}\n"
	.string "   Panel de Control y elige MOCHILA.\n"
	.string "{CIRCLE_3} Selecciona POCIÓN en el\n"
	.string "   BOLSILLO de los OBJETOS.\n"
	.string "{CIRCLE_4} Selecciona USAR.\n"
	.string "{CIRCLE_5} Selecciona qué POKéMON curas.$"
	.endif

Help_Text_HowToUseTownMap::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Open the MENU.\n"
	.string "{CIRCLE_2} Press up or down on the {PLUS} Control\n"
	.string "   Pad and select “BAG.”\n"
	.string "{CIRCLE_3} Press left or right to open the\n"
	.string "   “KEY ITEMS” POCKET, then press\n"
	.string "   up or down to select “TOWN MAP.” \n"
	.string "{CIRCLE_4} Select “USE” to open the TOWN MAP.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Abre el menú.\n"
	.string "{CIRCLE_2} Pulsa arriba o abajo en el {PLUS}\n"
	.string "   Panel de Control y elige MOCHILA.\n"
	.string "{CIRCLE_3} Pulsa izqda o dcha para abrir\n"
	.string "   el BOLSILLO de los OBJ. CLAVE, y\n"
	.string "   arriba y abajo para elegir MAPA.\n"
	.string "{CIRCLE_4} Selecciona USAR para abrirlo.$"
	.endif

Help_Text_HowToUseTM::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Open the MENU.\n"
	.string "{CIRCLE_2} Open the “KEY ITEMS” POCKET in the\n"
	.string "   “BAG.”\n"
	.string "{CIRCLE_3} “OPEN” the TM CASE.\n"
	.string "{CIRCLE_4} Select and “USE” a TM.\n"
	.string "{CIRCLE_5} Select a POKéMON that can learn the\n"
	.string "   move in the TM.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Abre el menú.\n"
	.string "{CIRCLE_2} Abre el BOLSILLO de los OBJ.\n"
	.string "   CLAVE de la MOCHILA.\n"
	.string "{CIRCLE_3} Selecciona TUBO MT-MO y ABRIR.\n"
	.string "{CIRCLE_4} Selecciona una MT y elige USAR.\n"
	.string "{CIRCLE_5} Elige qué POKéMON la aprenderá.$"
	.endif

Help_Text_HowToUseHM::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Open the MENU.\n"
	.string "{CIRCLE_2} Open the “KEY ITEMS” POCKET in the\n"
	.string "   “BAG.”\n"
	.string "{CIRCLE_3} “OPEN” the TM CASE.\n"
	.string "{CIRCLE_4} Select and “USE” an HM.\n"
	.string "{CIRCLE_5} Select a POKéMON that can learn it.\n"
	.string "HMs are hard to remove, so be careful!$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Abre el menú.\n"
	.string "{CIRCLE_2} Abre el BOLSILLO de los OBJ.\n"
	.string "   CLAVE de la MOCHILA.\n"
	.string "{CIRCLE_3} Selecciona TUBO MT-MO y ABRIR.\n"
	.string "{CIRCLE_4} Selecciona una MO y elige USAR.\n"
	.string "{CIRCLE_5} Elige qué POKéMON la aprenderá.\n"
	.string "   ¡Recuerda que cuesta olvidarlas!$"
	.endif

Help_Text_HowToUseMoveOutsideOfBattle::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Open the MENU.\n"
	.string "{CIRCLE_2} Select “POKéMON.”\n"
	.string "{CIRCLE_3} Select a POKéMON that knows an\n"
	.string "   HM move. The usable HM move(s)\n"
	.string "   will be shown in blue. Select and\n"
	.string "   use the desired move to destroy an\n"
	.string "   obstacle, fly, surf, etc.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Abre el menú.\n"
	.string "{CIRCLE_2} Selecciona POKéMON.\n"
	.string "{CIRCLE_3} Selecciona uno que sepa usar\n"
	.string "   una MO, aparecerán en azul.\n"
	.string "   Elige la que quieras y destruye\n"
	.string "   obstáculos, vuela, haz surf...$"
	.endif

Help_Text_HowToRideBicycle::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Open the MENU. Open the\n"
	.string "   “KEY ITEMS” POCKET in the “BAG”\n"
	.string "   and select the “BICYCLE.”\n"
	.string "{CIRCLE_2} The BICYCLE can be ridden by\n"
	.string "   selecting “USE.” You may also\n"
	.string "   “REGISTER” it for instant use by\n"
	.string "   pressing SELECT.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Abre el menú. Abre el BOLSILLO\n"
	.string "   de los OBJ. CLAVE de la\n"
	.string "   MOCHILA. Selecciona la BICI.\n"
	.string "{CIRCLE_2} Selecciona USAR para montarte o\n"
	.string "   ASIGNAR para usarla al instante\n"
	.string "   pulsando SELECT.$"
	.endif

Help_Text_HowToEnterName::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Move the cursor to the letter you\n"
	.string "   want with the {PLUS} Control Pad, then\n"
	.string "   press the A Button to enter it.\n"
	.string "{CIRCLE_2} Press the B Button to back up.\n"
	.string "{CIRCLE_3} Press SELECT to switch between\n"
	.string "   uppercase and lowercase letters.\n"
	.string "{CIRCLE_4} Press the A Button on “OK.”$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Coloca el cursor en la letra que\n"
	.string "   quieras con el {PLUS} Panel de Control\n"
	.string "   y escríbela pulsando el Botón A.\n"
	.string "{CIRCLE_2} Pulsa el Botón B para borrarla.\n"
	.string "{CIRCLE_3} Pulsa SELECT para elegir entre\n"
	.string "   mayúsculas y minúsculas.\n"
	.string "{CIRCLE_4} Elige FIN y pulsa el Botón A.$"
	.endif

Help_Text_HowToUsePC::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Go to any POKéMON CENTER, go up\n"
	.string "   to the PC, then press the A Button.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Ve a un CENTRO POKéMON,\n"
	.string "   acércate al PC y pulsa el Botón\n"
	.string "   A.$"
	.endif

Help_Text_HowToUseBillsPC::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “{STR_VAR_1}'S PC” on the PC.\n"
	.string "{CIRCLE_2} Select from one of the top three\n"
	.string "   MENU items to access the POKéMON\n"
	.string "   Storage System.\n"
	.string "If you catch a POKéMON when you have\n"
	.string "six in your party, the POKéMON is sent\n"
	.string "automatically to a BOX in the System!$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona PC de {STR_VAR_1}.\n"
	.string "{CIRCLE_2} Selecciona una de las opciones\n"
	.string "   para acceder al Sistema de\n"
	.string "   Almacenamiento POKéMON.\n"
	.string "Si atrapas algún POKéMON cuando\n"
	.string "ya tienes seis en tu equipo, irá de\n"
	.string "forma automática a una CAJA.$"
	.endif

Help_Text_HowToUseWithdraw::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select a POKéMON in the open BOX\n"
	.string "   with the {PLUS} Control Pad.\n"
	.string "{CIRCLE_2} Select “WITHDRAW” to remove the\n"
	.string "   POKéMON from the BOX and add it to\n"
	.string "   your party.\n"
	.string "You may not withdraw a POKéMON if you\n"
	.string "already have six POKéMON with you!$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona un POKéMON de la\n"
	.string "   CAJA con el {PLUS} Panel de Control.\n"
	.string "{CIRCLE_2} Selecciona SACAR para retirarlo\n"
	.string "   de la CAJA y añadirlo al equipo.\n"
	.string "Si ya tienes los seis POKéMON de\n"
	.string "tu equipo, ¡no podrás sacar más!$"
	.endif

Help_Text_HowToUseDeposit::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select a POKéMON in your party with\n"
	.string "   the {PLUS} Control Pad.\n"
	.string "{CIRCLE_2} Select “DEPOSIT.”\n"
	.string "{CIRCLE_3} Select the BOX, then press the\n"
	.string "   A Button to store the POKéMON.\n"
	.string "If you have only one POKéMON with you,\n"
	.string "it may not be stored!$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona un POKéMON de tu\n"
	.string "   equipo con el {PLUS} Panel de Control.\n"
	.string "{CIRCLE_2} Selecciona DEJAR.\n"
	.string "{CIRCLE_3} Selecciona una CAJA y pulsa\n"
	.string "   el Botón A para colocarlo.\n"
	.string "Si sólo tienes un POKéMON contigo,\n"
	.string "¡no podrás dejarlo!$"
	.endif

Help_Text_HowToUseMove::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select a POKéMON in the open BOX.\n"
	.string "{CIRCLE_2} Pick up the POKéMON by selecting\n"
	.string "   “MOVE” and move it anywhere with\n"
	.string "   the {PLUS} Control Pad.\n"
	.string "{CIRCLE_3} Move the POKéMON to the BOX name\n"
	.string "   and press left or right to move it\n"
	.string "   to another BOX.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona un POKéMON.\n"
	.string "{CIRCLE_2} Elige un POKéMON seleccionando\n"
	.string "   MOVER y colócalo donde quieras\n"
	.string "   con el {PLUS} Panel de Control.\n"
	.string "{CIRCLE_3} Pon al POKéMON sobre el nombre\n"
	.string "   de una CAJA y pulsa izqda o dcha\n"
	.string "   para elegir dónde lo dejas.$"
	.endif

Help_Text_HowToMoveItems::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Faintly shown POKéMON can be made\n"
	.string "   to hold an item by selecting it and\n"
	.string "   pressing the A Button.\n"
	.string "{CIRCLE_2} Clearly shown POKéMON can be made\n"
	.string "   to give the item they are holding to\n"
	.string "   another POKéMON, or return the item\n"
	.string "   to the BAG with the A Button.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Los POKéMON que no salen nítidos\n"
	.string "   pueden llevar objetos. Elige uno\n"
	.string "   y confirma con el Botón A.\n"
	.string "{CIRCLE_2} Los POKéMON que salen nítidos\n"
	.string "   pueden darle a otro POKéMON\n"
	.string "   el objeto que lleven o devolverlo\n"
	.string "   a la MOCHILA con el Botón A.$"
	.endif

Help_Text_HowToUsePlayersPC::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “{PLAYER}'s PC” on the PC.\n"
	.string "{CIRCLE_2} Select either “ITEM STORAGE” or\n"
	.string "   “MAILBOX.”\n"
	.string "You may store things in your own PC\n"
	.string "if your BAG is full. You may also\n"
	.string "withdraw items stored in your PC.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona el PC de {PLAYER}.\n"
	.string "{CIRCLE_2} Selecciona ALMACÉN OBJ. o\n"
	.string "   BUZÓN.\n"
	.string "Cuando tengas llena la MOCHILA,\n"
	.string "podrás guardar cosas en el PC.\n"
	.string "Si quieres sacar objetos, podrás\n"
	.string "hacerlo también.$"
	.endif

Help_Text_HowToUseWithdrawItem::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “WITHDRAW ITEM.”\n"
	.string "{CIRCLE_2} Select the item to be withdrawn.\n"
	.string "{CIRCLE_3} The item can be withdrawn and\n"
	.string "   placed in the BAG's ITEMS POCKET.\n"
	.string "   It may also be directly given to a\n"
	.string "   POKéMON to hold.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona SACAR OBJETO.\n"
	.string "{CIRCLE_2} Elige el objeto que quieras\n"
	.string "   sacar.\n"
	.string "{CIRCLE_3} Cuando lo saques, podrás\n"
	.string "   colocarlo en el BOLSILLO de\n"
	.string "   los OBJETOS de la MOCHILA o\n"
	.string "   dárselo sin más a un POKéMON.$"
	.endif

Help_Text_HowToUseDepositItem::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “DEPOSIT ITEM.”\n"
	.string "{CIRCLE_2} Select the item in the BAG to be\n"
	.string "   deposited using the {PLUS} Control Pad.\n"
	.string "{CIRCLE_3} If there is more than one \n"
	.string "   item to be deposited, enter the\n"
	.string "   quantity with the {PLUS} Control Pad,\n"
	.string "   then press the A Button.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona DEJAR OBJETO.\n"
	.string "{CIRCLE_2} Elige con el {PLUS} Panel de\n"
	.string "   Control el que quieras dejar.\n"
	.string "{CIRCLE_3} Si quieres dejar más de uno,\n"
	.string "   decide la cantidad con el {PLUS}\n"
	.string "   Panel de Control y confirma con\n"
	.string "   el Botón A.$"
	.endif

Help_Text_HowToUseMailbox::
	.ifdef ENGLISH
	.string "When MAIL is taken from a POKéMON,\n"
	.string "it is moved to the MAILBOX. If it has\n"
	.string "no MAIL, the MAILBOX can't be used.\n"
	.string "{CIRCLE_1} Select “{PLAYER}'S PC” on the PC.\n"
	.string "{CIRCLE_2} Select “MAILBOX” to read MAIL or\n"
	.string "   make a POKéMON hold MAIL.$"
	.endif
	.ifdef SPANISH
	.string "Cuando retires una CARTA de un\n"
	.string "POKéMON, irá al BUZÓN. Sólo podrás\n"
	.string "usar el BUZÓN cuando haya CARTAS.\n"
	.string "{CIRCLE_1} Selecciona el PC de {PLAYER}.\n"
	.string "{CIRCLE_2} Selecciona BUZÓN para leer\n"
	.string "   la CARTA o para dársela a un\n"
	.string "   POKéMON.$"
	.endif

Help_Text_HowToUseProfOaksPC::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “PROF. OAK'S PC” on the PC.\n"
	.string "{CIRCLE_2} PROF. OAK will evaluate your\n"
	.string "   POKéDEX.\n"
	.string "His evaluations should give you hints\n"
	.string "for catching more POKéMON!$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona el PC del PROF. OAK.\n"
	.string "{CIRCLE_2} El PROF. OAK le echará un ojo\n"
	.string "   a tu POKéDEX.\n"
	.string "Presta atención a lo que te diga\n"
	.string "para completarla.$"
	.endif

Help_Text_HowToOpenMenu::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Press START.\n"
	.string "{CIRCLE_2} The MENU will open on the right.\n"
	.string "{CIRCLE_3} Depending on the situation, the MENU\n"
	.string "   may feature different headings.\n"
	.string "The MENU will not open in certain\n"
	.string "situations such as when talking, doing\n"
	.string "something, battling, etc.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Pulsa START.\n"
	.string "{CIRCLE_2} A la derecha, aparecerá el menú.\n"
	.string "{CIRCLE_3} Las opciones variarán dependiendo\n"
	.string "   de la situación en la que estés.\n"
	.string "Habrá momentos en los que el menú\n"
	.string "no se abrirá: cuando hables con\n"
	.string "alguien, hagas algo, luches, etc.$"
	.endif

Help_Text_HowToUseFight::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “FIGHT.”\n"
	.string "{CIRCLE_2} Select one of the moves shown,\n"
	.string "and that move will be used!$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona LUCHA.\n"
	.string "{CIRCLE_2} Selecciona uno de los\n"
	.string "movimientos que aparezcan para\n"
	.string "usarlo.$"
	.endif

Help_Text_HowToUsePokemon2::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “POKéMON.”\n"
	.string "{CIRCLE_2} Select the POKéMON in your party\n"
	.string "   that you want to use.\n"
	.string "{CIRCLE_3} If you have two or more POKéMON\n"
	.string "   with you, they may be switched by\n"
	.string "   selecting “SHIFT.” Check POKéMON\n"
	.string "   data by selecting “SUMMARY.”$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona POKéMON.\n"
	.string "{CIRCLE_2} Selecciona al POKéMON de tu\n"
	.string "   equipo que quieras.\n"
	.string "{CIRCLE_3} Si tienes dos o más, podrás\n"
	.string "   cambiarlos de sitio eligiendo\n"
	.string "   CAMBIO. Para ver datos de los\n"
	.string "   POKéMON, selecciona DATOS.$"
	.endif

Help_Text_HowToUseShift::
	.ifdef ENGLISH
	.string "This command switches the POKéMON in\n"
	.string "battle with another one in your party.\n"
	.string "{CIRCLE_1} Select the POKéMON to be sent out.\n"
	.string "{CIRCLE_2} Select “SHIFT.”\n"
	.string "{CIRCLE_3} The selected POKéMON will switch\n"
	.string "   places with the POKéMON in battle!$"
	.endif
	.ifdef SPANISH
	.string "Podrás sustituir al POKéMON que\n"
	.string "está luchando por otro de tu equipo.\n"
	.string "{CIRCLE_1} Selecciona al POKéMON que\n"
	.string "quieres que salga.\n"
	.string "{CIRCLE_2} Selecciona CAMBIAR.\n"
	.string "{CIRCLE_3} El POKéMON elegido sustituirá\n"
	.string "   al POKéMON que está en combate.$"
	.endif

Help_Text_HowToUseSummary2::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “SUMMARY.”\n"
	.string "{CIRCLE_2} Press left or right on the {PLUS} Control\n"
	.string "   Pad to check the information:\n"
	.string "   “POKéMON INFO”\n"
	.string "   “POKéMON SKILLS”\n"
	.string "   “KNOWN MOVES”$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona DATOS.\n"
	.string "{CIRCLE_2} Pulsa izquierda o derecha en el\n"
	.string "   {PLUS} Panel de Control para ver:\n"
	.string "   INFO. POKéMON\n"
	.string "   HABIL. POKéMON\n"
	.string "   o MOV. CONOCIDOS.$"
	.endif

Help_Text_HowToUseBag2::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “BAG.”\n"
	.string "{CIRCLE_2} Press left or right on the {PLUS} Control\n"
	.string "   Pad to check the data headings:\n"
	.string "   “ITEMS”\n"
	.string "   “KEY ITEMS”\n"
	.string "   “POKé BALLS”\n"
	.string "   Press up or down to select an item.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona MOCHILA en el menú.\n"
	.string "{CIRCLE_2} Pulsa izquierda o derecha en el\n"
	.string "   {PLUS} Panel de Control para ver:\n"
	.string "   OBJETOS, OBJ. CLAVE\n"
	.string "   o POKé BALLS.\n"
	.string "   Pulsa arriba o abajo para\n"
	.string "   seleccionar un objeto.$"
	.endif

Help_Text_HowToReadPokedex::
	.ifdef ENGLISH
	.string "{CIRCLE_1} POKéMON that you have caught are\n"
	.string "   identified by a POKé BALL mark on\n"
	.string "   the POKéDEX list.\n"
	.string "{CIRCLE_2} A caught POKéMON will provide a\n"
	.string "   large amount of data.\n"
	.if REVISION < 1
	.string "{CIRCLE_3} Select “AREA” to display the TOWN\n"
	.string "   MAP with the POKéMON's habitat(s).$"
	.else
	.string "{CIRCLE_3} Select “NEXT DATA” to display the\n"
	.string "   TOWN MAP with its habitat(s).$"
	.endif
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Cuando atrapes un POKéMON,\n"
	.string "   aparecerá una POKé BALL junto\n"
	.string "   a su nombre en LAS POKéDEX.\n"
	.string "{CIRCLE_2} Atrapar POKéMON proporciona\n"
	.string "   mucha información.\n"
	.string "{CIRCLE_3} Selecciona MÁS DATOS para ver\n"
	.string "   el MAPA y las zonas que habita.$"
	.endif

Help_Text_HowToUseHomePC::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Go up to the PC at home, then press\n"
	.string "   the A Button.\n"
	.string "{CIRCLE_2} The PC will turn on.\n"
	.string "{CIRCLE_3} Select either “ITEM STORAGE” or\n"
	.string "   “MAILBOX.”$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Acércate al PC que hay arriba\n"
	.string "   y pulsa el Botón A.\n"
	.string "{CIRCLE_2} El PC se encenderá.\n"
	.string "{CIRCLE_3} Selecciona ALMACÉN OBJ. o\n"
	.string "   BUZÓN.$"
	.endif

Help_Text_HowToUseItemStorage::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “WITHDRAW ITEM” to withdraw\n"
	.string "   an item stored on your PC.\n"
	.string "{CIRCLE_2} Select “DEPOSIT ITEM” to put \n"
	.string "   an item from your BAG into your PC.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona SACAR OBJETO\n"
	.string "   para sacar del PC un objeto\n"
	.string "   de los que salgan.\n"
	.string "{CIRCLE_2} Selecciona DEJAR OBJETO \n"
	.string "   para dejar en el PC un objeto\n"
	.string "   de los que salgan.$"
	.endif

Help_Text_HowToUseWithdrawItem2::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “WITHDRAW ITEM.”\n"
	.string "{CIRCLE_2} Select the item to be withdrawn.\n"
	.string "{CIRCLE_3} The item can be withdrawn and\n"
	.string "   placed in the BAG's ITEMS POCKET.\n"
	.string "   It may also be directly given to a\n"
	.string "   POKéMON to hold.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona SACAR OBJETO.\n"
	.string "{CIRCLE_2} Elige el objeto que quieras\n"
	.string "   sacar.\n"
	.string "{CIRCLE_3} Cuando lo saques, podrás\n"
	.string "   colocarlo en el BOLSILLO de\n"
	.string "   los OBJETOS de la MOCHILA o\n"
	.string "   dárselo sin más a un POKéMON.$"
	.endif

Help_Text_HowToUseDepositItem2::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “DEPOSIT ITEM.”\n"
	.string "{CIRCLE_2} Select the item in the BAG to be\n"
	.string "   deposited using the {PLUS} Control Pad.\n"
	.string "{CIRCLE_3} If there is nothing in the BAG, this\n"
	.string "   command can't be used!$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona DEJAR OBJETO.\n"
	.string "{CIRCLE_2} Elige el objeto que quieras\n"
	.string "   dejar con el {PLUS} Panel de\n"
	.string "   Control.\n"
	.string "{CIRCLE_3} Si no hay nada en la MOCHILA,\n"
	.string "   ¡no podrás usar esta opción!$"
	.endif

Help_Text_HowToUseMailbox2::
	.ifdef ENGLISH
	.string "When MAIL is taken from a POKéMON,\n"
	.string "it is moved to the MAILBOX. If it has\n"
	.string "no MAIL, the MAILBOX can't be used.\n"
	.string "{CIRCLE_1} Select MAIL by name to read it or\n"
	.string "   make a POKéMON hold it.$"
	.endif
	.ifdef SPANISH
	.string "Cuando retires una CARTA de un\n"
	.string "POKéMON, irá a parar al BUZÓN.\n"
	.string "Sólo podrás usar el BUZÓN cuando\n"
	.string "haya CARTAS.\n"
	.string "{CIRCLE_1} Selecciona la CARTA que quieras\n"
	.string "   para leerla o para dársela a un\n"
	.string "   POKéMON.$"
	.endif

Help_Text_HowToUseRun::
	.ifdef ENGLISH
	.string "You may not “RUN” from a TRAINER\n"
	.string "battle!\n"
	.string "{CIRCLE_1} You may “RUN” from a wild POKéMON.\n"
	.string "{CIRCLE_2} Your chance of escape is improved\n"
	.string "   if your POKéMON in battle is fast.$"
	.endif
	.ifdef SPANISH
	.string "¡Si luchas contra ENTRENADORES\n"
	.string "no puedes usar HUIDA!\n"
	.string "{CIRCLE_1} Sólo podrás usarla cuando\n"
	.string "   luches contra POKéMON salvajes.\n"
	.string "{CIRCLE_2} Cuanto más rápido sea tu\n"
	.string "   POKéMON, más fácil te resultará\n"
	.string "   huir.$"
	.endif

Help_Text_HowToRegisterKeyItem::
	.ifdef ENGLISH
	.string "You may “REGISTER” a key item for\n"
	.string "instant use by pressing SELECT!\n"
	.string "{CIRCLE_1} Open the “KEY ITEMS” POCKET.\n"
	.string "{CIRCLE_2} Select the key item, then select\n"
	.string "   “REGISTER.”$"
	.endif
	.ifdef SPANISH
	.string "Podrás ASIGNAR objetos clave para\n"
	.string "usarlos al instante pulsando SELECT.\n"
	.string "{CIRCLE_1} Abre el BOLSILLO de los\n"
	.string "   OBJ. CLAVE .\n"
	.string "{CIRCLE_2} Selecciona un objeto clave; y,\n"
	.string "   a continuación, ASIGNAR.$"
	.endif

Help_Text_HowToUseBall::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select to throw the special POKé\n"
	.string "   BALL used only in the SAFARI ZONE.\n"
	.string "When wild POKéMON appear, throw lots\n"
	.string "of SAFARI BALLS to catch them!$"
	.endif
	.ifdef SPANISH
	.string "   Con esta opción, podrás lanzar\n"
	.string "   SAFARI BALLS, que sólo se usan\n"
	.string "   en la ZONA del SAFARI.\n"
	.string "Cuando veas POKéMON salvajes,\n"
	.string "lánzales muchas SAFARI BALLS\n"
	.string "para hacerte con ellos.$"
	.endif

Help_Text_HowToUseBait::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select to throw the special food\n"
	.string "   used only in the SAFARI ZONE.\n"
	.string "It is POKéMON food rolled up into\n"
	.string "a ball for easy eating. When BAIT is\n"
	.string "thrown, the wild POKéMON may get\n"
	.string "attracted by it, and may not flee!$"
	.endif
	.ifdef SPANISH
	.string "   Con esta opción, podrás echar\n"
	.string "   comida especial, que sólo se\n"
	.string "   usa en la ZONA del SAFARI.\n"
	.string "La comida POKéMON está hecha una\n"
	.string "bola para facilitar la ingestión. Si\n"
	.string "tiras CEBO, atraerás a los POKéMON\n"
	.string "salvajes y puede que no huyan.$"
	.endif

Help_Text_HowToUseRock::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select to throw a rock lying on\n"
	.string "   the ground in the SAFARI ZONE.\n"
	.string "Throwing a rock at a POKéMON may \n"
	.string "make it run away, but it becomes easier\n"
	.string "to catch!$"
	.endif
	.ifdef SPANISH
	.string "   Con esta opción, podrás lanzar\n"
	.string "   una roca en la ZONA del SAFARI.\n"
	.string "Si le tiras una roca a un POKéMON,\n"
	.string "puede que huya, pero si no lo\n"
	.string "hace, te será más fácil atraparlo.$"
	.endif

Help_Text_HowToUseHallOfFame::
	.ifdef ENGLISH
	.string "{CIRCLE_1} Select “HALL OF FAME” on the PC.\n"
	.string "{CIRCLE_2} The POKéMON that have entered the\n"
	.string "   HALL OF FAME can be examined.$"
	.endif
	.ifdef SPANISH
	.string "{CIRCLE_1} Selecciona HALL FAMA.\n"
	.string "{CIRCLE_2} Podrás echar un vistazo a los\n"
	.string "   POKéMON que estén en él.$"
	.endif

Help_Text_HP::
	.ifdef ENGLISH
	.string "HP$"
	.endif
	.ifdef SPANISH
	.string "PS$"
	.endif

Help_Text_EXP::
	.ifdef ENGLISH
	.string "EXP. {LEFT_PAREN}EXP. Points{RIGHT_PAREN}$"
	.endif
	.ifdef SPANISH
	.string "EXP. {LEFT_PAREN}Puntos de EXP.{RIGHT_PAREN}$"
	.endif

Help_Text_Moves::
	.ifdef ENGLISH
	.string "MOVES$"
	.endif
	.ifdef SPANISH
	.string "MOVIMIENTOS$"
	.endif

Help_Text_Attack::
	.ifdef ENGLISH
	.string "ATTACK$"
	.endif
	.ifdef SPANISH
	.string "ATAQUE$"
	.endif

Help_Text_Defense::
	.ifdef ENGLISH
	.string "DEFENSE$"
	.endif
	.ifdef SPANISH
	.string "DEFENSA$"
	.endif

Help_Text_SpAtk::
	.ifdef ENGLISH
	.string "SP. ATK$"
	.endif
	.ifdef SPANISH
	.string "AT. ESP.$"
	.endif

Help_Text_SpDef::
	.ifdef ENGLISH
	.string "SP. DEF$"
	.endif
	.ifdef SPANISH
	.string "DEF. ESP.$"
	.endif

Help_Text_Speed::
	.ifdef ENGLISH
	.string "SPEED$"
	.endif
	.ifdef SPANISH
	.string "VELOCID.$"
	.endif

Help_Text_Level::
	.ifdef ENGLISH
	.string "Lv. {LEFT_PAREN}Level{RIGHT_PAREN}$"
	.endif
	.ifdef SPANISH
	.string "Nv. {LEFT_PAREN}Nivel{RIGHT_PAREN}$"
	.endif

Help_Text_Type::
	.ifdef ENGLISH
	.string "TYPE$"
	.endif
	.ifdef SPANISH
	.string "TIPO$"
	.endif

Help_Text_OT::
	.ifdef ENGLISH
	.string "OT$"
	.endif
	.ifdef SPANISH
	.string "EO$"
	.endif

Help_Text_Item::
	.ifdef ENGLISH
	.string "ITEM$"
	.endif
	.ifdef SPANISH
	.string "OBJETO$"
	.endif

Help_Text_Ability::
	.ifdef ENGLISH
	.string "ABILITY$"
	.endif
	.ifdef SPANISH
	.string "HABILIDAD$"
	.endif

Help_Text_Money::
	.ifdef ENGLISH
	.string "MONEY$"
	.endif
	.ifdef SPANISH
	.string "DINERO$"
	.endif

Help_Text_MoveType::
	.ifdef ENGLISH
	.string "MOVE TYPE$"
	.endif
	.ifdef SPANISH
	.string "TIPO de MOVIMIENTO$"
	.endif

Help_Text_Nature::
	.ifdef ENGLISH
	.string "NATURE$"
	.endif
	.ifdef SPANISH
	.string "NATURALEZA$"
	.endif

Help_Text_IDNo::
	.ifdef ENGLISH
	.string "ID No.$"
	.endif
	.ifdef SPANISH
	.string "N.ºID.$"
	.endif

Help_Text_PP::
	.ifdef ENGLISH
	.string "PP$"
	.endif
	.ifdef SPANISH
	.string "PP$"
	.endif

Help_Text_Power::
	.ifdef ENGLISH
	.string "POWER$"
	.endif
	.ifdef SPANISH
	.string "POTENC.$"
	.endif

Help_Text_Accuracy::
	.ifdef ENGLISH
	.string "ACCURACY$"
	.endif
	.ifdef SPANISH
	.string "PRECIS.$"
	.endif

Help_Text_FNT::
	.ifdef ENGLISH
	.string "FNT$"
	.endif
	.ifdef SPANISH
	.string "DEB$"
	.endif

Help_Text_Items::
	.ifdef ENGLISH
	.string "ITEMS$"
	.endif
	.ifdef SPANISH
	.string "OBJETOS$"
	.endif

Help_Text_KeyItems::
	.ifdef ENGLISH
	.string "KEY ITEMS$"
	.endif
	.ifdef SPANISH
	.string "OBJ. CLAVE$"
	.endif

Help_Text_PokeBalls::
	.ifdef ENGLISH
	.string "POKé BALLS$"
	.endif
	.ifdef SPANISH
	.string "POKé BALLS$"
	.endif

Help_Text_Pokedex::
	.ifdef ENGLISH
	.string "POKéDEX$"
	.endif
	.ifdef SPANISH
	.string "POKéDEX$"
	.endif

Help_Text_PlayTime::
	.ifdef ENGLISH
	.string "PLAY TIME$"
	.endif
	.ifdef SPANISH
	.string "TIEMPO J.$"
	.endif

Help_Text_Badges::
	.ifdef ENGLISH
	.string "BADGES$"
	.endif
	.ifdef SPANISH
	.string "MEDALLAS$"
	.endif

Help_Text_TextSpeed::
	.ifdef ENGLISH
	.string "TEXT SPEED$"
	.endif
	.ifdef SPANISH
	.string "VELOC. TEXTO$"
	.endif

Help_Text_BattleScene::
	.ifdef ENGLISH
	.string "BATTLE SCENE$"
	.endif
	.ifdef SPANISH
	.string "ANIM. COMBATE$"
	.endif

Help_Text_BattleStyle::
	.ifdef ENGLISH
	.string "BATTLE STYLE$"
	.endif
	.ifdef SPANISH
	.string "TIPO COMBATE$"
	.endif

Help_Text_Sound::
	.ifdef ENGLISH
	.string "SOUND$"
	.endif
	.ifdef SPANISH
	.string "SONIDO$"
	.endif

Help_Text_ButtonMode::
	.ifdef ENGLISH
	.string "BUTTON MODE$"
	.endif
	.ifdef SPANISH
	.string "CONTROLES$"
	.endif

Help_Text_Frame::
	.ifdef ENGLISH
	.string "FRAME$"
	.endif
	.ifdef SPANISH
	.string "IMAGEN$"
	.endif

Help_Text_Cancel2::
	.ifdef ENGLISH
	.string "CANCEL$"
	.endif
	.ifdef SPANISH
	.string "SALIR$"
	.endif

Help_Text_TM::
	.ifdef ENGLISH
	.string "TM$"
	.endif
	.ifdef SPANISH
	.string "MT$"
	.endif

Help_Text_HM::
	.ifdef ENGLISH
	.string "HM$"
	.endif
	.ifdef SPANISH
	.string "MO$"
	.endif

Help_Text_HMMove::
	.ifdef ENGLISH
	.string "HM MOVE$"
	.endif
	.ifdef SPANISH
	.string "MOVIMIENTO MO$"
	.endif

Help_Text_Evolution::
	.ifdef ENGLISH
	.string "EVOLUTION$"
	.endif
	.ifdef SPANISH
	.string "EVOLUCIÓN$"
	.endif

Help_Text_StatusProblem::
	.ifdef ENGLISH
	.string "STATUS PROBLEM$"
	.endif
	.ifdef SPANISH
	.string "PROBLEMA de ESTADO$"
	.endif

Help_Text_Pokemon::
	.ifdef ENGLISH
	.string "POKéMON$"
	.endif
	.ifdef SPANISH
	.string "POKéMON$"
	.endif

Help_Text_IDNo2::
	.ifdef ENGLISH
	.string "ID No.$"
	.endif
	.ifdef SPANISH
	.string "N.ºID.$"
	.endif

Help_Text_Money2::
	.ifdef ENGLISH
	.string "MONEY$"
	.endif
	.ifdef SPANISH
	.string "DINERO$"
	.endif

Help_Text_Badges2::
	.ifdef ENGLISH
	.string "BADGES$"
	.endif
	.ifdef SPANISH
	.string "MEDALLAS$"
	.endif

Help_Text_DefineHP::
	.ifdef ENGLISH
	.string "HP indicates a POKéMON's vitality.\n"
	.string "If a POKéMON's HP drops to zero, it\l"
	.string "faints and is unable to battle.\l"
	.string "So, the key in battle is to try to\l"
	.string "reduce the foe's HP to zero.\l"
	.string "If your POKéMON are hurt, restore their\l"
	.string "HP at a POKéMON CENTER or use items.$"
	.endif
	.ifdef SPANISH
	.string "Los PS indican la fuerza que le\n"
	.string "queda a un POKéMON. Si llegan a\l"
	.string "cero, éste se debilita y no puede\l"
	.string "seguir luchando. ¡Intenta que el\l"
	.string "rival se quede sin PS! Si tus\l"
	.string "POKéMON están heridos, cúralos en\l"
	.string "un CENTRO POKéMON o con objetos.$"
	.endif

Help_Text_DefineEXP::
	.ifdef ENGLISH
	.string "EXP. Points stands for “Experience\n"
	.string "Points.” POKéMON gain EXP. Points by\l"
	.string "participating in winning battles.\l"
	.string "When a POKéMON accumulates sufficient\l"
	.string "EXP. Points, it levels up. The EXP. Bar\l"
	.string "indicates accumulated EXP. Points.\l"
	.string "It returns to zero upon leveling up.$"
	.endif
	.ifdef SPANISH
	.string "Los puntos de EXP. representan\n"
	.string "la experiencia que va ganando un\l"
	.string "POKéMON al vencer en combate.\l"
	.string "Al alcanzar un número determinado,\l"
	.string "sube de nivel. La barra de EXP. \l"
	.string "muestra los puntos acumulados, y\l"
	.string "vuelve a 0 cuando se sube un nivel.$"
	.endif

Help_Text_DefineMoves::
	.ifdef ENGLISH
	.string "POKéMON may learn up to four different\n"
	.string "moves. There are many kinds of moves\l"
	.string "including attacks and those with\l"
	.string "special effects. The kinds of moves\l"
	.string "that can be learned vary for each\l"
	.string "POKéMON. Some moves can be learned\l"
	.string "from items.$"
	.endif
	.ifdef SPANISH
	.string "Los POKéMON pueden aprender hasta\n"
	.string "cuatro movimientos diferentes. Hay\l"
	.string "varios tipos incluyendo los ataques\l"
	.string "y los que tienen efectos especiales.\l"
	.string "Cada POKéMON aprende distintos\l"
	.string "movimientos. Hay algunos que se\l"
	.string "aprenden gracias a ciertos objetos.$"
	.endif

Help_Text_DefineAttack::
	.ifdef ENGLISH
	.string "ATTACK indicates the power of an\n"
	.string "offensive move. The higher this stat,\l"
	.string "the more powerful the move.\l"
	.string "It is applied for the following move\l"
	.string "types: NORMAL, POISON, GROUND,\l"
	.string "FLYING, BUG, FIGHTING, ROCK, GHOST,\l"
	.string "and STEEL.$"
	.endif
	.ifdef SPANISH
	.string "El ATAQUE indica la potencia de un\n"
	.string "ataque. Cuanto mayor sea, más\l"
	.string "potencia tendrá el ataque. Va con\l"
	.string "los siguientes tipos: NORMAL,\l"
	.string "VENENO, TIERRA, VOLADOR, BICHO,\l"
	.string "LUCHA, ROCA, FANTASMA y ACERO.$"
	.endif

Help_Text_DefineDefense::
	.ifdef ENGLISH
	.string "DEFENSE indicates the resistance a\n"
	.string "POKéMON has against physical attacks.\l"
	.string "The higher this stat, the less damage\l"
	.string "sustained from a foe's physical hit.$"
	.endif
	.ifdef SPANISH
	.string "La DEFENSA indica la resistencia\n"
	.string "que tiene un POKéMON contra los\l"
	.string "ataques físicos. Cuanto mayor sea,\l"
	.string "menor será el daño infligido por el\l"
	.string "ataque físico del enemigo.$"
	.endif

Help_Text_DefineSpAtk::
	.ifdef ENGLISH
	.string "SP. ATK (Special Attack) indicates the\n"
	.string "power of a special attack move.\l"
	.string "The higher this stat, the more powerful\l"
	.string "the special attack move.\l"
	.string "It is applied for the following move\l"
	.string "types: FIRE, WATER, ELECTRIC, GRASS,\l"
	.string "ICE, PSYCHIC, DRAGON, and DARK.$"
	.endif
	.ifdef SPANISH
	.string "El AT. ESP. (Ataque Especial)\n"
	.string "indica la potencia de un ataque\l"
	.string "especial. Cuanto mayor sea, más\l"
	.string "potencia tendrá el ataque.\l"
	.string "Va con los siguientes tipos: FUEGO,\l"
	.string "AGUA, ELÉCTRICO, PLANTA, HIELO,\l"
	.string "PSÍQUICO, DRAGÓN y SINIESTRO.$"
	.endif

Help_Text_DefineSpDef::
	.ifdef ENGLISH
	.string "SP. DEF (Special Defense) indicates\n"
	.string "the resistance a POKéMON has against\l"
	.string "special attacks.\l"
	.string "The higher this stat, the less damage\l"
	.string "sustained from a foe's special attack.$"
	.endif
	.ifdef SPANISH
	.string "La DEF. ESP. (Defensa Especial)\n"
	.string "indica la resistencia contra los\l"
	.string "ataques especiales. Cuanto mayor\l"
	.string "sea, menor será el daño infligido\l"
	.string "por el at. especial del enemigo.$"
	.endif

Help_Text_DefineSpeed::
	.ifdef ENGLISH
	.string "SPEED indicates the agility of a\n"
	.string "POKéMON. If this stat exceeds the foe's\l"
	.string "in battle, the POKéMON can make a move\l"
	.string "before its slower opponent.$"
	.endif
	.ifdef SPANISH
	.string "La VELOCIDAD indica la agilidad de\n"
	.string "un POKéMON. Si supera la del rival\l"
	.string "en combate, el POKéMON podrá usar\l"
	.string "un movimiento antes que él.$"
	.endif

Help_Text_DefineLevel::
	.ifdef ENGLISH
	.string "Lv. (Level) indicates the growth and\n"
	.string "strength of a POKéMON.\l"
	.string "In general, when a POKéMON levels up,\l"
	.string "its stats such as HP, ATTACK, and\l"
	.string "DEFENSE rise, making it stronger.\l"
	.string "POKéMON may learn a new move upon\l"
	.string "leveling up.$"
	.endif
	.ifdef SPANISH
	.string "El Nv. (Nivel) indica el momento\n"
	.string "de crecimiento y la fuerza de un\l"
	.string "POKéMON. Normalmente, al subir\l"
	.string "de nivel, aumentan PS, ATAQUE y\l"
	.string "DEFENSA, con lo que el POKéMON\l"
	.string "se hace más fuerte. Además, puede\l"
	.string "que aprenda otro movimiento.$"
	.endif

Help_Text_DefineType::
	.ifdef ENGLISH
	.string "POKéMON and moves are classified by\n"
	.string "type. Every type has advantageous and\l"
	.string "disadvantageous matchups against\l"
	.string "other types. For example, like a rock-\l"
	.string "paper-scissors game, the WATER type is\l"
	.string "strong against the FIRE type and weak\l"
	.string "against the GRASS type.$"
	.endif
	.ifdef SPANISH
	.string "Los POKéMON y sus movimientos\n"
	.string "se clasifican por tipos. Según se\l"
	.string "combinen, así será el resultado. La\l"
	.string "mecánica es igual que la del juego\l"
	.string "“Piedra, papel, tijera”; el tipo\l"
	.string "AGUA sería fuerte frente al FUEGO,\l"
	.string "pero débil frente al tipo PLANTA.$"
	.endif

Help_Text_DefineOT::
	.ifdef ENGLISH
	.string "OT stands for “Original TRAINER,”\n"
	.string "the first TRAINER to have caught the\l"
	.string "selected POKéMON.\l"
	.string "Even if the POKéMON is traded, the OT\l"
	.string "name will remain unchanged.$"
	.endif
	.ifdef SPANISH
	.string "EO es la sigla de ENTRENADOR\n"
	.string "Original. Hace referencia al primer\l"
	.string "ENTRENADOR que atrapó a un\l"
	.string "POKéMON determinado. El nombre del\l"
	.string "EO no se puede cambiar, aunque se\l"
	.string "envíe al POKéMON a otro cartucho.$"
	.endif

Help_Text_DefineItem::
	.ifdef ENGLISH
	.string "All POKéMON can be made to hold one\n"
	.string "item each. Some items will be used by\l"
	.string "the POKéMON automatically in certain\l"
	.string "situations. To make a POKéMON hold an\l"
	.string "item, select the item from the BAG and\l"
	.string "“GIVE” it to the POKéMON.$"
	.endif
	.ifdef SPANISH
	.string "Todos los POKéMON pueden llevar un\n"
	.string "objeto y algunos podrás usarlos de\l"
	.string "forma automática en determinadas\l"
	.string "situaciones. Para darles un objeto,\l"
	.string "selecciona el que quieras de la\l"
	.string "MOCHILA y, a continuación, DAR.$"
	.endif

Help_Text_DefineAbility::
	.ifdef ENGLISH
	.string "All POKéMON have a special ABILITY.\n"
	.string "There are many different kinds of these\l"
	.string "abilities, some used in battle, some\l"
	.string "elsewhere. The abilities differ from\l"
	.string "species to species. Some species may\l"
	.string "have more than one kind of ability.$"
	.endif
	.ifdef SPANISH
	.string "Todos los POKéMON tienen una\n"
	.string "HABILIDAD especial. Algunas pueden\l"
	.string "usarse en combate; y otras, fuera.\l"
	.string "Las habilidades varían según la\l"
	.string "especie. Hay especies que tienen\l"
	.string "más de una habilidad.$"
	.endif

Help_Text_DefineMoney::
	.ifdef ENGLISH
	.string "Whenever you win a battle against a\n"
	.string "TRAINER, you are given prize money.\l"
	.string "Save up your prize money so you can\l"
	.string "enjoy shopping at POKéMON MARTS!$"
	.endif
	.ifdef SPANISH
	.string "Cuando vences a un ENTRENADOR,\n"
	.string "ganas un premio en metálico.\l"
	.string "¡Ahorra para poder comprar útiles\l"
	.string "artículos en las TIENDAS POKéMON!$"
	.endif

Help_Text_DefineMoveType::
	.ifdef ENGLISH
	.string "Moves are also classified by types.\n"
	.string "If a POKéMON of a certain type uses\l"
	.string "a move of the same type, the move's\l"
	.string "power is boosted. If the move's type\l"
	.string "has a matchup advantage against the\l"
	.string "target, its effectiveness is also\l"
	.string "boosted.$"
	.endif
	.ifdef SPANISH
	.string "Los movimientos también se\n"
	.string "clasifican por tipos. Si un POKéMON\l"
	.string "usa uno de su tipo, tendrá mayor\l"
	.string "efecto. Si no es del mismo tipo,\l"
	.string "pero es una buena combinación,\l"
	.string "también tendrá mayor efecto.$"
	.endif

Help_Text_DefineNature::
	.ifdef ENGLISH
	.string "All POKéMON have a personality,\n"
	.string "or “NATURE.” The POKéMON's\l"
	.string "nature appears to affect how the\l"
	.string "POKéMON will grow upon leveling up.$"
	.endif
	.ifdef SPANISH
	.string "Todos los POKéMON tienen cierta\n"
	.string "personalidad o NATURALEZA, que\l"
	.string "influye en la forma de crecer del\l"
	.string "POKéMON a medida que va subiendo\l"
	.string "de nivel.$"
	.endif

Help_Text_DefineIDNo::
	.ifdef ENGLISH
	.string "The ID No. is a special number assigned\n"
	.string "specifically to you as a TRAINER.\l"
	.string "Together with the OT name, the ID No.\l"
	.string "is used to precisely identify the\l"
	.string "Original TRAINER.\l"
	.string "The ID No. does not change even if the\l"
	.string "POKéMON is traded.$"
	.endif
	.ifdef SPANISH
	.string "El N.º es un número único que se\n"
	.string "te asigna como ENTRENADOR. Junto\l"
	.string "con el nombre de EO, el N.º se usa\l"
	.string "para identificar al ENTRENADOR\l"
	.string "Original. El N.º no se puede\l"
	.string "cambiar, aunque se envíe al\l"
	.string "POKéMON a otro cartucho.$"
	.endif

Help_Text_DefinePP::
	.ifdef ENGLISH
	.string "PP stands for “Power Points.”\n"
	.string "It indicates the number of times a\l"
	.string "certain move can be used in battle.\l"
	.string "Like HP, PP can be restored by visiting\l"
	.string "a POKéMON CENTER or using certain\l"
	.string "items.$"
	.endif
	.ifdef SPANISH
	.string "PP es la sigla de PUNTOS de\n"
	.string "POTENCIA. Indican las veces que se\l"
	.string "ha usado un movimiento en combate.\l"
	.string "Podrás recuperar PP igual que\l"
	.string "restauras PS: en los CENTROS\l"
	.string "POKéMON o usando determinados\l"
	.string "objetos.$"
	.endif

Help_Text_DefinePower::
	.ifdef ENGLISH
	.string "POWER indicates the strength of an\n"
	.string "attack. The higher this number, the\l"
	.string "greater the damage that can be\l"
	.string "inflicted on the foe!$"
	.endif
	.ifdef SPANISH
	.string "La POTENCIA indica la fuerza que\n"
	.string "tiene un ataque. Cuanto mayor sea,\l"
	.string "mayor será el daño causado al\l"
	.string "enemigo.$"
	.endif

Help_Text_DefineAccuracy::
	.ifdef ENGLISH
	.string "ACCURACY indicates the probability of\n"
	.string "the move hitting the foe.\l"
	.string "The higher this number, the more likely\l"
	.string "the move will strike the target.$"
	.endif
	.ifdef SPANISH
	.string "La PRECISIÓN indica la\n"
	.string "probabilidad de alcanzar al rival.\l"
	.string "Cuanto mayor sea, mayor será\l"
	.string "la posibilidad de que el ataque\l"
	.string "alcance al enemigo.$"
	.endif

Help_Text_DefineFNT::
	.ifdef ENGLISH
	.string "FNT stands for “fainted.”\n"
	.string "A POKéMON faints if its HP is reduced\l"
	.string "to zero. It becomes incapable of taking\l"
	.string "part in battle.\l"
	.string "Restore a fainted POKéMON at a POKéMON\l"
	.string "CENTER, or use an item.$"
	.endif
	.ifdef SPANISH
	.string "DEB indica que un POKéMON está\n"
	.string "debilitado. Un POKéMON se debilita\l"
	.string "cuando sus PS llegan a cero. Si\l"
	.string "esto ocurre, no puede participar\l"
	.string "en combate. Para restaurar a tus\l"
	.string "POKéMON debilitados, ve a un\l"
	.string "CENTRO POKéMON o usa un objeto.$"
	.endif

Help_Text_DefineItems::
	.ifdef ENGLISH
	.string "Ordinary items bought at any POKéMON\n"
	.string "MART are placed in the ITEMS POCKET.\l"
	.string "Items may be used, given to a POKéMON\l"
	.string "to hold, or tossed out as garbage.$"
	.endif
	.ifdef SPANISH
	.string "Los objetos comunes comprados en\n"
	.string "las TIENDAS POKéMON se colocan\l"
	.string "en el BOLSILLO de los OBJETOS.\l"
	.string "Podrás usarlos, dárselos a tus\l"
	.string "POKéMON o tirarlos si no los\l"
	.string "quieres.$"
	.endif

Help_Text_DefineKeyItems::
	.ifdef ENGLISH
	.string "Important items that you find or \n"
	.string "receive from people are placed in the\l"
	.string "KEY ITEMS POCKET.\l"
	.string "Key items may be used, or registered\l"
	.string "for use instantly with SELECT. Once\l"
	.string "registered, the item can be used\l"
	.string "without opening the MENU and BAG.$"
	.endif
	.ifdef SPANISH
	.string "Los objetos importantes que\n"
	.string "encuentres o recibas se ponen en el\l"
	.string "BOLSILLO de OBJETOS CLAVE, donde\l"
	.string "podrás acceder para usarlos. Con\l"
	.string "todo, puedes elegir uno y asignarlo\l"
	.string "a SELECT para no tener que abrir\l"
	.string "la MOCHILA, y usarlo de inmediato.$"
	.endif

Help_Text_DefinePokeBalls::
	.ifdef ENGLISH
	.string "POKé BALLS, which are used for\n"
	.string "catching wild POKéMON, are placed in\l"
	.string "the POKé BALLS POCKET.\l"
	.string "POKé BALLS may be bought at POKéMON\l"
	.string "MARTS. They may be used, given to a\l"
	.string "POKéMON to hold, or tossed out as\l"
	.string "garbage.$"
	.endif
	.ifdef SPANISH
	.string "Las POKé BALLS se usan para atrapar\n"
	.string "POKéMON salvajes, y se colocan\l"
	.string "en el BOLSILLO de las POKé BALLS.\l"
	.string "Podrás comprarlas en las TIENDAS\l"
	.string "POKéMON y usarlas, dárselas a tus\l"
	.string "POKéMON o tirarlas cuando no las\l"
	.string "quieras.$"
	.endif

Help_Text_DefinePokedex::
	.ifdef ENGLISH
	.string "This indicates the number of species of\n"
	.string "POKéMON you have caught and/or\l"
	.string "evolved to fill the POKéDEX.\l"
	.string "Try hard to catch all sorts of\l"
	.string "POKéMON!$"
	.endif
	.ifdef SPANISH
	.string "Es el registro de las especies de\n"
	.string "POKéMON que has visto y atrapado.\l"
	.string "¡Hazte con todos los que puedas!$"
	.endif

Help_Text_DefinePlayTime::
	.ifdef ENGLISH
	.string "This is the total amount of time that\n"
	.string "you have played this game.$"
	.endif
	.ifdef SPANISH
	.string "Es el total del tiempo que has\n"
	.string "pasado jugando al juego.$"
	.endif

Help_Text_DefineBadges::
	.ifdef ENGLISH
	.string "The POKéMON LEAGUE BADGES that you\n"
	.string "have won are registered and shown.\l"
	.string "Earn BADGES by defeating GYM LEADERS\l"
	.string "in various cities and towns.$"
	.endif
	.ifdef SPANISH
	.string "Son las MEDALLAS de la LIGA\n"
	.string "POKéMON que llevas conseguidas.\l"
	.string "Para ganar las MEDALLAS, deberás\l"
	.string "vencer a los LÍDERES de los\l"
	.string "GIMNASIOS de las ciudades\l"
	.string "y los pueblos que hay.$"
	.endif

Help_Text_DefineTextSpeed::
	.ifdef ENGLISH
	.string "You can adjust how quickly the text is\n"
	.string "displayed. Choose one: SLOW, MID,\l"
	.string "or FAST.$"
	.endif
	.ifdef SPANISH
	.string "Puedes cambiarla para que los\n"
	.string "mensajes salgan a velocidad\l"
	.string "LENTA, MEDIA o RÁPIDA.$"
	.endif

Help_Text_DefineBattleScene::
	.ifdef ENGLISH
	.string "You can choose to turn the battle\n"
	.string "animation ON or OFF.$"
	.endif
	.ifdef SPANISH
	.string "Sirve para activar o desactivar\n"
	.string "la animación de los combates.$"
	.endif

Help_Text_DefineBattleStyle::
	.ifdef ENGLISH
	.string "You can choose whether or not a\n"
	.string "TRAINER can switch a POKéMON after\l"
	.string "it has made its foe faint.\l"
	.string "Set to “SHIFT” if you would like the\l"
	.string "chance to switch a POKéMON after it\l"
	.string "has made its foe faint.$"
	.endif
	.ifdef SPANISH
	.string "Decide si quieres tener la opción\n"
	.string "de cambiar de POKéMON cada vez\l"
	.string "que se debilita uno de tus POKéMON\l"
	.string "en combate.\l"
	.string "De ser así, selecciona CAMBIAR.$"
	.endif

Help_Text_DefineSound::
	.ifdef ENGLISH
	.string "You can choose between MONO and\n"
	.string "STEREO sound output.$"
	.endif
	.ifdef SPANISH
	.string "Elige entre MONO o ESTÉREO.$"
	.endif

Help_Text_DefineButtonMode::
	.ifdef ENGLISH
	.string "Set to “HELP” to display help messages\n"
	.string "by pressing the L or R Button.\l"
	.string "Set to “LR” to enable the switching\l"
	.string "of the POKéDEX pages and BAG POCKETS\l"
	.string "using the L and R Buttons.\l"
	.string "Set to “L=A” to make the L Button\l"
	.string "work the same as the A Button.$"
	.endif
	.ifdef SPANISH
	.string "Con AYUDA, al pulsar los Botones L\n"
	.string "o R saldrá la ayuda. Si dejas LR,\l"
	.string "pasarás las páginas de la POKéDEX\l"
	.string "y los BOLSILLOS de la MOCHILA con\l"
	.string "los Botones L y R. Si dejas L=A,\l"
	.string "el Botón L tendrá las mismas\l"
	.string "funciones que el Botón A.$"
	.endif

Help_Text_DefineFrame::
	.ifdef ENGLISH
	.string "You may choose the design of the frame\n"
	.string "around certain menus. Try them out and\l"
	.string "see what you like.$"
	.endif
	.ifdef SPANISH
	.string "Echa un vistazo a los bordes que\n"
	.string "les puedes poner a algunos menús.$"
	.endif

Help_Text_DefineCancel2::
	.ifdef ENGLISH
	.string "The settings will be changed to the\n"
	.string "selections shown in red, and you will\l"
	.string "return to the MENU.$"
	.endif
	.ifdef SPANISH
	.string "Con esta opción, dejarás los\n"
	.string "valores que aparecen en rojo\l"
	.string "y volverás al menú.$"
	.endif

Help_Text_DefineTM::
	.ifdef ENGLISH
	.string "A TM (Technical Machine) is a device\n"
	.string "used to teach a move to a POKéMON.\l"
	.string "There are many different kinds.\l"
	.string "Moves can be taught only to those\l"
	.string "POKéMON capable of using them.\l"
	.string "A TM breaks after a single use.$"
	.endif
	.ifdef SPANISH
	.string "Las MT (Maquinas Técnicas) se usan\n"
	.string "para enseñar movimientos a los\l"
	.string "POKéMON capaces de usarlos.\l"
	.string "Hay muchos tipos, y al usarlas\l"
	.string "una vez, se rompen.$"
	.endif

Help_Text_DefineHM::
	.ifdef ENGLISH
	.string "An HM (Hidden Machine) is a device used\n"
	.string "to teach a HIDDEN move to a POKéMON.\l"
	.string "A HIDDEN move can be taught only to\l"
	.string "those POKéMON capable of using it.\l"
	.string "Unlike a TM, an HM can be used over\l"
	.string "and over. A HIDDEN move can be tough\l"
	.string "for a POKéMON to forget.$"
	.endif
	.ifdef SPANISH
	.string "Las MO (Maquinas Ocultas) se usan\n"
	.string "para enseñar movimientos OCULTOS\l"
	.string "a los POKéMON capaces de usarlos.\l"
	.string "A diferencia de las MT, se pueden\l"
	.string "usar más de una vez y los\l"
	.string "movimientos se pueden olvidar.$"
	.endif

Help_Text_DefineHMMove::
	.ifdef ENGLISH
	.string "HIDDEN moves are those that are\n"
	.string "especially important for your\l"
	.string "adventure. To use such a move outside\l"
	.string "of battle, open the “POKéMON” MENU\l"
	.string "and make the POKéMON that knows the\l"
	.string "move use it. A fainted POKéMON may use\l"
	.string "a HIDDEN move outside of battle.$"
	.endif
	.ifdef SPANISH
	.string "Los movimientos OCULTOS son los\n"
	.string "más importantes para tu aventura.\l"
	.string "Para usar uno fuera de combate,\l"
	.string "tienes que abrir el menú POKéMON\l"
	.string "y hacer que el POKéMON que conoce\l"
	.string "la técnica la use. Esto funcionará\l"
	.string "aunque el POKéMON esté debilitado.$"
	.endif

Help_Text_DefineEvolution::
	.ifdef ENGLISH
	.string "Among POKéMON, there are some that\n"
	.string "undergo major changes (evolution) upon\l"
	.string "growing to certain levels. Evolution\l"
	.string "causes a POKéMON to alter form, change\l"
	.string "its name, and perhaps change the moves\l"
	.string "it may learn. Some POKéMON evolve\l"
	.string "due to reasons other than leveling up.$"
	.endif
	.ifdef SPANISH
	.string "Algunos POKéMON sufren cambios\n"
	.string "cuando van subiendo de nivel, y\l"
	.string "evolucionan. Pueden cambiar de\l"
	.string "forma, de nombre y hasta pueden\l"
	.string "aprender nuevos movimientos.\l"
	.string "Otros, evolucionan por razones\l"
	.string "ajenas al aumento de nivel.$"
	.endif

Help_Text_DefineStatusProblem::
	.ifdef ENGLISH
	.string "Status problems include:\n"
	.string "Sleep: Can't use moves.\l"
	.string "Poison: Causes steady HP loss.\l"
	.string "Paralysis: May prevent moves.\l"
	.string "Burn: HP loss and lowers ATTACK.\l"
	.string "Freeze: Can't use moves.\l"
	.string "These can be healed with items, etc.$"
	.endif
	.ifdef SPANISH
	.string "Los problemas de estado incluyen:\n"
	.string "Dormido: no puedes usar mov.\l"
	.string "Envenenado: reduce PS.\l"
	.string "Paralizado: difícil usar mov.\l"
	.string "Quemado: reduce PS y baja ATAQUE.\l"
	.string "Congelado: imposible usar mov.\l"
	.string "Tienen solución con objetos, etc.$"
	.endif

Help_Text_DefinePokemon::
	.ifdef ENGLISH
	.string "POKéMON is a name given to describe\n"
	.string "wondrous creatures that inhabit all\l"
	.string "corners of this world.\l"
	.string "People raise POKéMON to be their pets,\l"
	.string "use them for battling, and so on.$"
	.endif
	.ifdef SPANISH
	.string "POKéMON es el nombre que reciben\n"
	.string "las extraordinarias criaturas que\l"
	.string "habitan este mundo. La gente los\l"
	.string "cría a modo de mascota, para\l"
	.string "luchar, etc.$"
	.endif

Help_Text_DefineIDNo2::
	.ifdef ENGLISH
	.string "The ID No. is a special number assigned\n"
	.string "specifically to you as a TRAINER.\l"
	.string "Together with the OT name, the ID No.\l"
	.string "is used to precisely identify the\l"
	.string "Original TRAINER.\l"
	.string "The ID No. does not change even if the\l"
	.string "POKéMON is traded.$"
	.endif
	.ifdef SPANISH
	.string "El N.º es un número único que se\n"
	.string "te asigna como ENTRENADOR. Junto\l"
	.string "con el nombre de EO, el N.º se usa\l"
	.string "para identificar al ENTRENADOR\l"
	.string "Original. El N.º no se puede\l"
	.string "cambiar, aunque se envíe al\l"
	.string "POKéMON a otro cartucho.$"
	.endif

Help_Text_DefineMoney2::
	.ifdef ENGLISH
	.string "Whenever you win a battle against a\n"
	.string "TRAINER, you are given prize money.\l"
	.string "Save up your prize money so you can\l"
	.string "enjoy shopping at POKéMON MARTS!$"
	.endif
	.ifdef SPANISH
	.string "Cuando vences a un ENTRENADOR,\n"
	.string "ganas un premio en metálico.\l"
	.string "¡Ahorra para poder comprar útiles\l"
	.string "artículos en las TIENDAS POKéMON!$"
	.endif

Help_Text_DefineBadges2::
	.ifdef ENGLISH
	.string "This indicates the number of POKéMON\n"
	.string "LEAGUE BADGES that you have won.\l"
	.string "Earn BADGES by defeating GYM LEADERS\l"
	.string "in various cities and towns.$"
	.endif
	.ifdef SPANISH
	.string "Son las MEDALLAS de la LIGA\n"
	.string "POKéMON que llevas conseguidas.\l"
	.string "Para ganar las MEDALLAS, deberás\l"
	.string "vencer a los LÍDERES de los\l"
	.string "GIMNASIOS de las ciudades\l"
	.string "y los pueblos que hay.$"
	.endif

Help_Text_TheHelpSystem::
	.ifdef ENGLISH
	.string "The HELP System$"
	.endif
	.ifdef SPANISH
	.string "El sistema de AYUDA.$"
	.endif

Help_Text_TheGame::
	.ifdef ENGLISH
	.string "The game$"
	.endif
	.ifdef SPANISH
	.string "El juego.$"
	.endif

Help_Text_WirelessAdapter::
	.ifdef ENGLISH
	.string "Wireless Adapter$"
	.endif
	.ifdef SPANISH
	.string "El Conector inalámbrico de GBA.$"
	.endif

Help_Text_GameFundamentals1::
	.ifdef ENGLISH
	.string "Game fundamentals 1$"
	.endif
	.ifdef SPANISH
	.string "Nociones básicas 1.$"
	.endif

Help_Text_GameFundamentals2::
	.ifdef ENGLISH
	.string "Game fundamentals 2$"
	.endif
	.ifdef SPANISH
	.string "Nociones básicas 2.$"
	.endif

Help_Text_GameFundamentals3::
	.ifdef ENGLISH
	.string "Game fundamentals 3$"
	.endif
	.ifdef SPANISH
	.string "Nociones básicas 3.$"
	.endif

Help_Text_WhatArePokemon::
	.ifdef ENGLISH
	.string "What are POKéMON?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué son los POKéMON?$"
	.endif

Help_Text_DescTheHelpSystem::
	.ifdef ENGLISH
	.string "The help messages change depending on\n"
	.string "how much you have progressed in the\l"
	.string "game. They are designed to support you\l"
	.string "when you need them. If there is\l"
	.string "anything that you don't understand,\l"
	.string "please look up the HELP System!$"
	.endif
	.ifdef SPANISH
	.string "Los mensajes de ayuda cambian\n"
	.string "según tu progreso. Están pensados\l"
	.string "para ayudarte cuando te hagan\l"
	.string "falta. Si no entiendes algo, ¡echa\l"
	.string "un vistazo al sistema de AYUDA!$"
	.endif

Help_Text_DescTheGame::
	.ifdef ENGLISH
	.string "You become the main character to\n"
	.string "explore the world of POKéMON!\l"
	.string "By talking to people and solving\l"
	.string "mysteries, new paths will open to you.\l"
	.string "Strive for the goal together with your\l"
	.string "wonderful POKéMON!$"
	.endif
	.ifdef SPANISH
	.string "Acabas de convertirte en\n"
	.string "protagonista de esta historia.\l"
	.string "Estás en el mundo POKéMON. Tienes\l"
	.string "que hablar con la gente y resolver\l"
	.string "los misterios que se te presenten.\l"
	.string "Ábrete camino para llegar al final\l"
	.string "junto a tus maravillosos POKéMON.$"
	.endif

Help_Text_DescWirelessAdapter::
	.ifdef ENGLISH
	.string "This game communicates over a wireless\n"
	.string "link using the Wireless Adapter.\p"
	.string "Go wireless anywhere, anytime, and\n"
	.string "with anybody!\p"
	.string "Try playing with the Wireless Adapter\n"
	.string "always attached!$"
	.endif
	.ifdef SPANISH
	.string "Este juego ofrece la posibilidad\n"
	.string "de conexión inalámbrica usando\l"
	.string "el Conector inalámbrico de GBA.\p"
	.string "¡Conéctate sin cables donde,\n"
	.string "cuando y con quien quieras!\p"
	.string "¡Juega con el Conector inalámbrico\n"
	.string "de GBA siempre conectado!$"
	.endif

Help_Text_DescGameFundamentals1::
	.ifdef ENGLISH
	.string "Visit every city and town, travel every\n"
	.string "road, explore every cave, and face\l"
	.string "every challenge as you strive to\l"
	.string "become the greatest TRAINER of\l"
	.string "POKéMON!$"
	.endif
	.ifdef SPANISH
	.string "No te pierdas nada, visita pueblos,\n"
	.string "ciudades, pasa por rutas, cuevas...\l"
	.string "¡Cada rincón supone un paso en tu\l"
	.string "carrera hacia el éxito entrenando\l"
	.string "POKéMON!$"
	.endif

Help_Text_DescGameFundamentals2::
	.ifdef ENGLISH
	.string "On your adventure, you will be faced\n"
	.string "with many obstacles. Every obstacle\l"
	.string "can be overcome by doing something\l"
	.string "or by solving mysteries. Some obstacles\l"
	.string "are affected by something that happens\l"
	.string "far away.$"
	.endif
	.ifdef SPANISH
	.string "Durante tu aventura, tendrás que\n"
	.string "hacer frente a muchos obstáculos.\l"
	.string "Deberás hacer distintas cosas y\l"
	.string "resolver diferentes enigmas para\l"
	.string "superarlos. Habrá obstáculos que\l"
	.string "haya que salvar a mucha distancia\l"
	.string "de su auténtico escenario...$"
	.endif

Help_Text_DescGameFundamentals3::
	.ifdef ENGLISH
	.string "Some of the obstacles in your way can\n"
	.string "be removed once your POKéMON learn\l"
	.string "specific moves.$"
	.endif
	.ifdef SPANISH
	.string "Habrá obstáculos que deberás\n"
	.string "salvar usando determinados\l"
	.string "movimientos de los que pueden\l"
	.string "aprender tus POKéMON.$"
	.endif

Help_Text_DescWhatArePokemon::
	.ifdef ENGLISH
	.string "POKéMON are wondrous creatures that\n"
	.string "are shrouded in mystery. You may meet\l"
	.string "them all over the world…in tall\l"
	.string "grass, caves, the sea, and more.\l"
	.string "They appear to grow obedient to the\l"
	.string "TRAINERS that caught them.$"
	.endif
	.ifdef SPANISH
	.string "Los POKéMON son unas maravillosas\n"
	.string "y misteriosas criaturas. Los verás\l"
	.string "por todos los sitios de este mundo...\l"
	.string "entre la hierba, en las cuevas, en\l"
	.string "el agua... Son muy obedientes\l"
	.string "con su ENTRENADOR.$"
	.endif

Help_Text_UsingTypeMatchupList::
	.ifdef ENGLISH
	.string "Using the Type Matchup List$"
	.endif
	.ifdef SPANISH
	.string "Usando la tabla de combinaciones.$"
	.endif

Help_Text_OwnMoveDark::
	.ifdef ENGLISH
	.string "Own move type: DARK$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: SINIESTRO.$"
	.endif

Help_Text_OwnPokemonDark::
	.ifdef ENGLISH
	.string "Own POKéMON type: DARK$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: SINIESTRO.$"
	.endif

Help_Text_OwnMoveRock::
	.ifdef ENGLISH
	.string "Own move type: ROCK$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: ROCA.$"
	.endif

Help_Text_OwnPokemonRock::
	.ifdef ENGLISH
	.string "Own POKéMON type: ROCK$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: ROCA.$"
	.endif

Help_Text_OwnMovePsychic::
	.ifdef ENGLISH
	.string "Own move type: PSYCHIC$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: PSÍQUICO.$"
	.endif

Help_Text_OwnPokemonPsychic::
	.ifdef ENGLISH
	.string "Own POKéMON type: PSYCHIC$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: PSÍQUICO.$"
	.endif

Help_Text_OwnMoveFighting::
	.ifdef ENGLISH
	.string "Own move type: FIGHTING$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: LUCHA.$"
	.endif

Help_Text_OwnPokemonFighting::
	.ifdef ENGLISH
	.string "Own POKéMON type: FIGHTING$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: LUCHA.$"
	.endif

Help_Text_OwnMoveGrass::
	.ifdef ENGLISH
	.string "Own move type: GRASS$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: PLANTA.$"
	.endif

Help_Text_OwnPokemonGrass::
	.ifdef ENGLISH
	.string "Own POKéMON type: GRASS$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: PLANTA.$"
	.endif

Help_Text_OwnMoveGhost::
	.ifdef ENGLISH
	.string "Own move type: GHOST$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: FANTASMA.$"
	.endif

Help_Text_OwnPokemonGhost::
	.ifdef ENGLISH
	.string "Own POKéMON type: GHOST$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: FANTASMA.$"
	.endif

Help_Text_OwnMoveIce::
	.ifdef ENGLISH
	.string "Own move type: ICE$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: HIELO.$"
	.endif

Help_Text_OwnPokemonIce::
	.ifdef ENGLISH
	.string "Own POKéMON type: ICE$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: HIELO.$"
	.endif

Help_Text_OwnMoveGround::
	.ifdef ENGLISH
	.string "Own move type: GROUND$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: TIERRA.$"
	.endif

Help_Text_OwnPokemonGround::
	.ifdef ENGLISH
	.string "Own POKéMON type: GROUND$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: TIERRA.$"
	.endif

Help_Text_OwnMoveElectric::
	.ifdef ENGLISH
	.string "Own move type: ELECTRIC$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: ELÉCTRICO.$"
	.endif

Help_Text_OwnPokemonElectric::
	.ifdef ENGLISH
	.string "Own POKéMON type: ELECTRIC$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: ELÉCTRICO.$"
	.endif

Help_Text_OwnMovePoison::
	.ifdef ENGLISH
	.string "Own move type: POISON$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: VENENO.$"
	.endif

Help_Text_OwnPokemonPoison::
	.ifdef ENGLISH
	.string "Own POKéMON type: POISON$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: VENENO.$"
	.endif

Help_Text_OwnMoveDragon::
	.ifdef ENGLISH
	.string "Own move type: DRAGON$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: DRAGÓN.$"
	.endif

Help_Text_OwnPokemonDragon::
	.ifdef ENGLISH
	.string "Own POKéMON type: DRAGON$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: DRAGÓN.$"
	.endif

Help_Text_OwnMoveNormal::
	.ifdef ENGLISH
	.string "Own move type: NORMAL$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: NORMAL.$"
	.endif

Help_Text_OwnPokemonNormal::
	.ifdef ENGLISH
	.string "Own POKéMON type: NORMAL$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: NORMAL.$"
	.endif

Help_Text_OwnMoveSteel::
	.ifdef ENGLISH
	.string "Own move type: STEEL$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: ACERO.$"
	.endif

Help_Text_OwnPokemonSteel::
	.ifdef ENGLISH
	.string "Own POKéMON type: STEEL$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: ACERO.$"
	.endif

Help_Text_OwnMoveFlying::
	.ifdef ENGLISH
	.string "Own move type: FLYING$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: VOLADOR.$"
	.endif

Help_Text_OwnPokemonFlying::
	.ifdef ENGLISH
	.string "Own POKéMON type: FLYING$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: VOLADOR.$"
	.endif

Help_Text_OwnMoveFire::
	.ifdef ENGLISH
	.string "Own move type: FIRE$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: FUEGO.$"
	.endif

Help_Text_OwnPokemonFire::
	.ifdef ENGLISH
	.string "Own POKéMON type: FIRE$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: FUEGO.$"
	.endif

Help_Text_OwnMoveWater::
	.ifdef ENGLISH
	.string "Own move type: WATER$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: AGUA.$"
	.endif

Help_Text_OwnPokemonWater::
	.ifdef ENGLISH
	.string "Own POKéMON type: WATER$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: AGUA.$"
	.endif

Help_Text_OwnMoveBug::
	.ifdef ENGLISH
	.string "Own move type: BUG$"
	.endif
	.ifdef SPANISH
	.string "Tipo mov. propio: BICHO.$"
	.endif

Help_Text_OwnPokemonBug::
	.ifdef ENGLISH
	.string "Own POKéMON type: BUG$"
	.endif
	.ifdef SPANISH
	.string "Tipo PKMN propio: BICHO.$"
	.endif

Help_Text_HowToUseTypeMatchupList::
	.ifdef ENGLISH
	.string "Depending on the matchup of the\n"
	.string "move type and the target POKéMON's\l"
	.string "type, the move's effectiveness varies:\l"
	.string "{CIRCLE_DOT}: Super effective!\l"
	.string "{TRIANGLE}: Not very effective\l"
	.string "{BIG_MULT_X}: Not effective at all\l"
	.string "(No changes for other matchups.)$"
	.endif
	.ifdef SPANISH
	.string "Según sea la combinación del tipo\n"
	.string "del movimiento y el tipo del\l"
	.string "POKéMON rival, variará la eficacia:\l"
	.string "{CIRCLE_DOT}: ¡Es muy eficaz!\l"
	.string "{TRIANGLE}: No es muy eficaz...\l"
	.string "{BIG_MULT_X}: No es nada eficaz...\l"
	.string "(Común a las otras combinaciones).$"
	.endif

Help_Text_TypeMatchupOwnMoveDark::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {CIRCLE_DOT}: PSYCHIC, GHOST\p"
	.string "   {TRIANGLE}: FIGHTING, DARK, STEEL$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: PSÍQUICO, FANTASMA\p"
	.string "   {TRIANGLE}: LUCHA, SINIESTRO, ACERO$"
	.endif

Help_Text_TypeMatchupOwnPokemonDark::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: FIGHTING, BUG\p"
	.string "   {TRIANGLE}: GHOST, DARK\p"
	.string "   {BIG_MULT_X}: PSYCHIC$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: LUCHA, BICHO\p"
	.string "   {TRIANGLE}: FANTASMA, SINIESTRO\p"
	.string "   {BIG_MULT_X}: PSÍQUICO$"
	.endif

Help_Text_TypeMatchupOwnMoveRock::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {CIRCLE_DOT}: FIRE, ICE, FLYING, BUG\p"
	.string "   {TRIANGLE}: FIGHTING, GROUND, STEEL$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: FUEGO, HIELO, VOLADOR,\n"
	.string "       BICHO\p"
	.string "   {TRIANGLE}: LUCHA, TIERRA, ACERO$"
	.endif

Help_Text_TypeMatchupOwnPokemonRock::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: WATER, GRASS, FIGHTING,\n"
	.string "       GROUND, STEEL\p"
	.string "   {TRIANGLE}: NORMAL, FIRE, POISON, FLYING$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: AGUA, PLANTA, LUCHA,\n"
	.string "       TIERRA, ACERO\p"
	.string "   {TRIANGLE}: NORMAL, FUEGO, VENENO,\n"
	.string "       VOLADOR$"
	.endif

Help_Text_TypeMatchupOwnMovePsychic::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {CIRCLE_DOT}: FIGHTING, POISON\p"
	.string "   {TRIANGLE}: PSYCHIC, STEEL\p"
	.string "   {BIG_MULT_X}: DARK$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: LUCHA, VENENO\p"
	.string "   {TRIANGLE}: PSÍQUICO, ACERO\p"
	.string "   {BIG_MULT_X}: SINIESTRO$"
	.endif

Help_Text_TypeMatchupOwnPokemonPsychic::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: BUG, GHOST, DARK\p"
	.string "   {TRIANGLE}: FIGHTING, PSYCHIC$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: BICHO, FANTASMA, SINIESTRO\p"
	.string "   {TRIANGLE}: LUCHA, PSÍQUICO$"
	.endif

Help_Text_TypeMatchupOwnMoveFighting::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {CIRCLE_DOT}: NORMAL, ICE, ROCK, DARK, STEEL\p"
	.string "   {TRIANGLE}: POISON, FLYING, PSYCHIC, BUG\p"
	.string "   {BIG_MULT_X}: GHOST$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: NORMAL, HIELO, ROCA,\n"
	.string "       SINIESTRO, ACERO\p"
	.string "   {TRIANGLE}: VENENO, VOLADOR, PSÍQUICO,\n"
	.string "       BICHO\p"
	.string "   {BIG_MULT_X}: FANTASMA$"
	.endif

Help_Text_TypeMatchupOwnPokemonFighting::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: FLYING, PSYCHIC\p"
	.string "   {TRIANGLE}: BUG, ROCK, DARK$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: VOLADOR, PSÍQUICO\p"
	.string "   {TRIANGLE}: BICHO, ROCA, SINIESTRO$"
	.endif

Help_Text_TypeMatchupOwnMoveGrass::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {CIRCLE_DOT}: WATER, GROUND, ROCK\p"
	.string "   {TRIANGLE}: FIRE, GRASS, POISON, FLYING,\n"
	.string "       BUG, DRAGON, STEEL$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: AGUA, TIERRA, ROCA\p"
	.string "   {TRIANGLE}: FUEGO, PLANTA, VENENO,\n"
	.string "       BICHO, DRAGÓN, ACERO$"
	.endif

Help_Text_TypeMatchupOwnPokemonGrass::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: FIRE, ICE, POISON, FLYING, BUG\p"
	.string "   {TRIANGLE}: WATER, ELECTRIC, GRASS, GROUND$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: FUEGO, HIELO, VENENO,\n"
	.string "       VOLADOR, BICHO\p"
	.string "   {TRIANGLE}: AGUA, ELÉCTRICO, PLANTA,\n"
	.string "       TIERRA$"
	.endif

Help_Text_TypeMatchupOwnMoveGhost::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {CIRCLE_DOT}: PSYCHIC, GHOST\p"
	.string "   {TRIANGLE}: DARK, STEEL\p"
	.string "   {BIG_MULT_X}: NORMAL$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: PSÍQUICO, FANTASMA\p"
	.string "   {TRIANGLE}: SINIESTRO, ACERO\p"
	.string "   {BIG_MULT_X}: NORMAL$"
	.endif

Help_Text_TypeMatchupOwnPokemonGhost::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: GHOST, DARK\p"
	.string "   {TRIANGLE}: POISON, BUG\p"
	.string "   {BIG_MULT_X}: NORMAL, FIGHTING$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: FANTASMA, SINIESTRO\p"
	.string "   {TRIANGLE}: VENENO, BICHO\p"
	.string "   {BIG_MULT_X}: NORMAL, LUCHA$"
	.endif

Help_Text_TypeMatchupOwnMoveIce::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {CIRCLE_DOT}: GRASS, GROUND, FLYING, DRAGON\p"
	.string "   {TRIANGLE}: FIRE, WATER, ICE, STEEL$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: PLANTA, TIERRA, VOLADOR\n"
	.string "       DRAGÓN\p"
	.string "   {TRIANGLE}: FUEGO, AGUA, HIELO, ACERO$"
	.endif

Help_Text_TypeMatchupOwnPokemonIce::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: FIRE, FIGHTING, ROCK, STEEL\p"
	.string "   {TRIANGLE}: ICE$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: FUEGO, LUCHA, ROCA, ACERO\p"
	.string "   {TRIANGLE}: HIELO$"
	.endif

Help_Text_TypeMatchupOwnMoveGround::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {CIRCLE_DOT}: FIRE, ELECTRIC, POISON, ROCK,\n"
	.string "       STEEL\p"
	.string "   {TRIANGLE}: GRASS, BUG\n"
	.string "   {BIG_MULT_X}: FLYING$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: FUEGO, ELÉCTRICO, VENENO,\n"
	.string "       ROCA, ACERO\p"
	.string "   {TRIANGLE}: PLANTA, BICHO\n"
	.string "   {BIG_MULT_X}: VOLADOR$"
	.endif

Help_Text_TypeMatchupOwnPokemonGround::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: WATER, GRASS, ICE\p"
	.string "   {TRIANGLE}: POISON, ROCK\p"
	.string "   {BIG_MULT_X}: ELECTRIC$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: AGUA, PLANTA, HIELO\p"
	.string "   {TRIANGLE}: VENENO, ROCA\p"
	.string "   {BIG_MULT_X}: ELÉCTRICO$"
	.endif

Help_Text_TypeMatchupOwnMoveElectric::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {CIRCLE_DOT}: WATER, FLYING\p"
	.string "   {TRIANGLE}: ELECTRIC, GRASS, DRAGON\p"
	.string "   {BIG_MULT_X}: GROUND$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: AGUA, VOLADOR\p"
	.string "   {TRIANGLE}: ELÉCTRICO, PLANTA, DRAGÓN\p"
	.string "   {BIG_MULT_X}: TIERRA$"
	.endif

Help_Text_TypeMatchupOwnPokemonElectric::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: GROUND\p"
	.string "   {TRIANGLE}: ELECTRIC, FLYING, STEEL$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: TIERRA\p"
	.string "   {TRIANGLE}: ELÉCTRICO, VOLADOR, ACERO$"
	.endif

Help_Text_TypeMatchupOwnMovePoison::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {CIRCLE_DOT}: GRASS\p"
	.string "   {TRIANGLE}: POISON, GROUND, ROCK, GHOST\p"
	.string "   {BIG_MULT_X}: STEEL$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: PLANTA\p"
	.string "   {TRIANGLE}: VENENO, TIERRA, ROCA,\n"
	.string "       FANTASMA\p"
	.string "   {BIG_MULT_X}: ACERO$"
	.endif

Help_Text_TypeMatchupOwnPokemonPoison::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: GROUND, PSYCHIC\p"
	.string "   {TRIANGLE}: GRASS, FIGHTING, POISON, BUG$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: TIERRA, PSÍQUICO\p"
	.string "   {TRIANGLE}: PLANTA, LUCHA, VENENO,\n"
	.string "       BICHO$"
	.endif

Help_Text_TypeMatchupOwnMoveDragon::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {CIRCLE_DOT}: DRAGON\p"
	.string "   {TRIANGLE}: STEEL$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: DRAGÓN\p"
	.string "   {TRIANGLE}: ACERO$"
	.endif

Help_Text_TypeMatchupOwnPokemonDragon::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: ICE, DRAGON\p"
	.string "   {TRIANGLE}: FIRE, WATER, ELECTRIC, GRASS$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: HIELO, DRAGÓN\p"
	.string "   {TRIANGLE}: FUEGO, AGUA, ELÉCTRICO,\n"
	.string "       PLANTA$"
	.endif

Help_Text_TypeMatchupOwnMoveNormal::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {TRIANGLE}: ROCK, STEEL\p"
	.string "   {BIG_MULT_X}: GHOST$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {TRIANGLE}: ROCA, ACERO\p"
	.string "   {BIG_MULT_X}: FANTASMA$"
	.endif

Help_Text_TypeMatchupOwnPokemonNormal::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: FIGHTING\p"
	.string "   {BIG_MULT_X}: GHOST$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: LUCHA\p"
	.string "   {BIG_MULT_X}: FANTASMA$"
	.endif

Help_Text_TypeMatchupOwnMoveSteel::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {CIRCLE_DOT}: ICE, ROCK\p"
	.string "   {TRIANGLE}: FIRE, WATER, ELECTRIC, STEEL$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: HIELO, ROCA\p"
	.string "   {TRIANGLE}: FUEGO, AGUA, ELÉCTRICO,\n"
	.string "       ACERO$"
	.endif

Help_Text_TypeMatchupOwnPokemonSteel::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: FIRE, FIGHTING, GROUND\n"
	.string "   {TRIANGLE}: NORMAL, GRASS, ICE, FLYING,\l"
	.string "       PSYCHIC, BUG, ROCK, GHOST,\l"
	.string "       DRAGON, DARK, STEEL\l"
	.string "   {BIG_MULT_X}: POISON$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: FUEGO, LUCHA, TIERRA\n"
	.string "   {TRIANGLE}: NORMAL, PLANTA, HIELO,\l"
	.string "       VOL., PSÍQ., BICHO, ROCA,\l"
	.string "       FANT., DRAG., SINI., ACERO\l"
	.string "   {BIG_MULT_X}: VENENO$"
	.endif

Help_Text_TypeMatchupOwnMoveFlying::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {CIRCLE_DOT}: GRASS, FIGHTING, BUG\p"
	.string "   {TRIANGLE}: ELECTRIC, ROCK, STEEL$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: PLANTA, LUCHA, BICHO\p"
	.string "   {TRIANGLE}: ELÉCTRICO, ROCA, ACERO$"
	.endif

Help_Text_TypeMatchupOwnPokemonFlying::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: ELECTRIC, ICE, ROCK\p"
	.string "   {TRIANGLE}: GRASS, FIGHTING, BUG\p"
	.string "   {BIG_MULT_X}: GROUND$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: ELÉCTRICO, HIELO, ROCA\p"
	.string "   {TRIANGLE}: PLANTA, LUCHA, BICHO\p"
	.string "   {BIG_MULT_X}: TIERRA$"
	.endif

Help_Text_TypeMatchupOwnMoveFire::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {CIRCLE_DOT}: GRASS, ICE, BUG, STEEL\p"
	.string "   {TRIANGLE}: FIRE, WATER, ROCK, DRAGON$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: PLANTA, HIELO, BICHO,\n"
	.string "       ACERO\p"
	.string "   {TRIANGLE}: FUEGO, AGUA, ROCA,\n"
	.string "       DRAGÓN$"
	.endif

Help_Text_TypeMatchupOwnPokemonFire::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: WATER, GROUND, ROCK\p"
	.string "   {TRIANGLE}: FIRE, GRASS, ICE, BUG, STEEL$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: AGUA, TIERRA, ROCA\p"
	.string "   {TRIANGLE}: FUEGO, PLANTA, HIELO,\n"
	.string "       BICHO, ACERO$"
	.endif

Help_Text_TypeMatchupOwnMoveWater::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {CIRCLE_DOT}: FIRE, GROUND, ROCK\p"
	.string "   {TRIANGLE}: WATER, GRASS, DRAGON$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: FUEGO, TIERRA, ROCA\p"
	.string "   {TRIANGLE}: AGUA, PLANTA, DRAGÓN$"
	.endif

Help_Text_TypeMatchupOwnPokemonWater::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: ELECTRIC, GRASS\p"
	.string "   {TRIANGLE}: FIRE, WATER, ICE, STEEL$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: ELÉCTRICO, PLANTA\p"
	.string "   {TRIANGLE}: FUEGO, AGUA, HIELO, ACERO$"
	.endif

Help_Text_TypeMatchupOwnMoveBug::
	.ifdef ENGLISH
	.string "Effect on the opposing POKéMON:\p"
	.string "   {CIRCLE_DOT}: GRASS, PSYCHIC, DARK\p"
	.string "   {TRIANGLE}: FIRE, FIGHTING, POISON,\n"
	.string "       FLYING, GHOST, STEEL$"
	.endif
	.ifdef SPANISH
	.string "Efecto en el POKéMON rival:\p"
	.string "   {CIRCLE_DOT}: PLANTA, PSÍQUICO, SINIESTRO\p"
	.string "   {TRIANGLE}: FUEGO, LUCHA, VENENO,\n"
	.string "       VOLADOR, FANTASMA, ACERO$"
	.endif

Help_Text_TypeMatchupOwnPokemonBug::
	.ifdef ENGLISH
	.string "Effect of foe's move on own POKéMON:\p"
	.string "   {CIRCLE_DOT}: FIRE, FLYING, ROCK\p"
	.string "   {TRIANGLE}: GRASS, FIGHTING, GROUND$"
	.endif
	.ifdef SPANISH
	.string "Efecto del mov. rival en mis PKMN:\p"
	.string "   {CIRCLE_DOT}: FUEGO, VOLADOR, ROCA\p"
	.string "   {TRIANGLE}: PLANTA, LUCHA, TIERRA$"
	.endif

