Trade_Text_LookingForMonWannaTradeForMon::
	.ifdef ENGLISH
	.string "I'm looking for the POKéMON\n"
	.string "{STR_VAR_1}!\p"
	.string "Wanna trade one for my\n"
	.string "{STR_VAR_2}?$"
	.endif
	.ifdef SPANISH
	.string "¡Busco un {STR_VAR_1}!\p"
	.string "¿Quieres cambiarlo por\n"
	.string "{STR_VAR_2}?$"
	.endif

Trade_Text_AwwOhWell::
	.ifdef ENGLISH
	.string "Awww!\n"
	.string "Oh, well…$"
	.endif
	.ifdef SPANISH
	.string "¿No?\n"
	.string "Pues vale...$"
	.endif

Trade_Text_WhatThatsNoMon::
	.ifdef ENGLISH
	.string "What?\n"
	.string "That's no {STR_VAR_1}!$"
	.endif
	.ifdef SPANISH
	.string "¿Qué?\n"
	.string "¡Ése no es {STR_VAR_1}!$"
	.endif

Trade_Text_HeyThanks::
	.ifdef ENGLISH
	.string "Hey, thanks!$"
	.endif
	.ifdef SPANISH
	.string "¡Muchas gracias!$"
	.endif

Trade_Text_IsntMyOldMonGreat::
	.ifdef ENGLISH
	.string "Isn't my old {STR_VAR_2} great?$"
	.endif
	.ifdef SPANISH
	.string "¿No es estupendo mi {STR_VAR_2}?$"
	.endif

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.ifdef ENGLISH
	.string "Hello, there! Do you happen to\n"
	.string "have a {STR_VAR_1}?\p"
	.string "Would you agree to a trade for\n"
	.string "my {STR_VAR_2}?$"
	.endif
	.ifdef SPANISH
	.string "¡Hola!\p"
	.string "¿Quieres cambiar tu {STR_VAR_1}\n"
	.string "por {STR_VAR_2}?$"
	.endif

Trade_Text_WellIfYouDontWantTo::
	.ifdef ENGLISH
	.string "Well, if you don't want to…$"
	.endif
	.ifdef SPANISH
	.string "Vale, si no quieres...$"
	.endif

Trade_Text_ThisIsntMon::
	.ifdef ENGLISH
	.string "Hmmm?\n"
	.string "This isn't a {STR_VAR_1}.\p"
	.string "Think of me if you get one.$"
	.endif
	.ifdef SPANISH
	.string "¿Qué?\n"
	.string "Éste no es {STR_VAR_1}.\p"
	.string "Cuando tengas uno piensa en mí.$"
	.endif

Trade_Text_Thanks::
	.ifdef ENGLISH
	.string "Thanks!$"
	.endif
	.ifdef SPANISH
	.string "¡Gracias!$"
	.endif

Trade_Text_HasTradedMonGrownStronger::
	.ifdef ENGLISH
	.string "The {STR_VAR_2} that I traded you,\n"
	.string "has it grown stronger?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué tal va el {STR_VAR_2} que te\n"
	.string "envié, más fuerte?$"
	.endif

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.ifdef ENGLISH
	.string "Hi!\n"
	.string "Do you have a {STR_VAR_1}?\p"
	.string "Want to trade it for my\n"
	.string "{STR_VAR_2}?$"
	.endif
	.ifdef SPANISH
	.string "¡Hola!\n"
	.string "¿Tienes un {STR_VAR_1}?\p"
	.string "¿Quieres cambiarlo\n"
	.string "por {STR_VAR_2}?$"
	.endif

Trade_Text_ThatsTooBad::
	.ifdef ENGLISH
	.string "That's too bad.$"
	.endif
	.ifdef SPANISH
	.string "¡Qué pena!$"
	.endif

Trade_Text_ThisIsNoMon::
	.ifdef ENGLISH
	.string "…This is no {STR_VAR_1}.\p"
	.string "If you get one, trade it with me.$"
	.endif
	.ifdef SPANISH
	.string "Éste no es un {STR_VAR_1}.\p"
	.string "¡Si consigues uno, te lo cambio!$"
	.endif

Trade_Text_ThanksYoureAPal::
	.ifdef ENGLISH
	.string "Thanks, you're a pal!$"
	.endif
	.ifdef SPANISH
	.string "¡Gracias, contigo da gusto!$"
	.endif

Trade_Text_HowIsMyOldMon::
	.ifdef ENGLISH
	.string "How is my old {STR_VAR_2}?\n"
	.string "My {STR_VAR_1} is doing great!$"
	.endif
	.ifdef SPANISH
	.string "¿Cómo está mi viejo {STR_VAR_2}?\n"
	.string "¡Mi {STR_VAR_1} está fenomenal!$"
	.endif
