gOtherText_NewName::
    .ifdef ENGLISH
    .string "NEW NAME$"
    .endif
    .ifdef SPANISH
    .string "OTRO NOMBRE$"
    .endif

gNameChoice_Green::
    .ifdef ENGLISH
    .string "GREEN$"
    .endif
    .ifdef SPANISH
    .string "VERTE$"
    .endif

gNameChoice_Red::
    .ifdef ENGLISH
    .string "RED$"
    .endif
    .ifdef SPANISH
    .string "JORO$"
    .endif

gNameChoice_Leaf::
    .ifdef ENGLISH
    .string "LEAF$"
    .endif
    .ifdef SPANISH
    .string "JAHO$"
    .endif

gNameChoice_Fire::
    .ifdef ENGLISH
    .string "FIRE$"
    .endif
    .ifdef SPANISH
    .string "GUEFO$"
    .endif

gNameChoice_Gary::
    .ifdef ENGLISH
    .string "GARY$"
    .endif
    .ifdef SPANISH
    .string "BOSCO$"
    .endif

gNameChoice_Kaz::
    .ifdef ENGLISH
    .string "KAZ$"
    .endif
    .ifdef SPANISH
    .string "FLOREN$"
    .endif

gNameChoice_Toru::
    .ifdef ENGLISH
    .string "TORU$"
    .endif
    .ifdef SPANISH
    .string "SILVIO$"
    .endif

gNameChoice_Ash::
    .ifdef ENGLISH
    .string "ASH$"
    .endif
    .ifdef SPANISH
    .string "FURIO$"
    .endif

gNameChoice_Kene::
    .ifdef ENGLISH
    .string "KENE$"
    .endif
    .ifdef SPANISH
    .string "LLAMÍN$"
    .endif

gNameChoice_Geki::
    .ifdef ENGLISH
    .string "GEKI$"
    .endif
    .ifdef SPANISH
    .string "CANDEL$"
    .endif

gNameChoice_Jak::
    .ifdef ENGLISH
    .string "JAK$"
    .endif
    .ifdef SPANISH
    .string "JUNO$"
    .endif

gNameChoice_Janne::
    .ifdef ENGLISH
    .string "JANNE$"
    .endif
    .ifdef SPANISH
    .string "JUAN$"
    .endif

gNameChoice_Jonn::
    .ifdef ENGLISH
    .string "JONN$"
    .endif
    .ifdef SPANISH
    .string "JUANMA$"
    .endif

gNameChoice_Kamon::
    .ifdef ENGLISH
    .string "KAMON$"
    .endif
    .ifdef SPANISH
    .string "ÁLVARO$"
    .endif

gNameChoice_Karl::
    .ifdef ENGLISH
    .string "KARL$"
    .endif
    .ifdef SPANISH
    .string "RAL$"
    .endif

gNameChoice_Taylor::
    .ifdef ENGLISH
    .string "TAYLOR$"
    .endif
    .ifdef SPANISH
    .string "MARINO$"
    .endif

gNameChoice_Oscar::
    .ifdef ENGLISH
    .string "OSCAR$"
    .endif
    .ifdef SPANISH
    .string "TOILO$"
    .endif

gNameChoice_Hiro::
    .ifdef ENGLISH
    .string "HIRO$"
    .endif
    .ifdef SPANISH
    .string "NER$"
    .endif

gNameChoice_Max::
    .ifdef ENGLISH
    .string "MAX$"
    .endif
    .ifdef SPANISH
    .string "MAX$"
    .endif

gNameChoice_Jon::
    .ifdef ENGLISH
    .string "JON$"
    .endif
    .ifdef SPANISH
    .string "MOREL$"
    .endif

gNameChoice_Ralph::
    .ifdef ENGLISH
    .string "RALPH$"
    .endif
    .ifdef SPANISH
    .string "RAFA$"
    .endif

gNameChoice_Kay::
    .ifdef ENGLISH
    .string "KAY$"
    .endif
    .ifdef SPANISH
    .string "VER$"
    .endif

gNameChoice_Tosh::
    .ifdef ENGLISH
    .string "TOSH$"
    .endif
    .ifdef SPANISH
    .string "LERIO$"
    .endif

gNameChoice_Roak::
    .ifdef ENGLISH
    .string "ROAK$"
    .endif
    .ifdef SPANISH
    .string "RODI$"
    .endif

gNameChoice_Omi::
    .ifdef ENGLISH
    .string "OMI$"
    .endif
    .ifdef SPANISH
    .string "MENA$"
    .endif

gNameChoice_Jodi::
    .ifdef ENGLISH
    .string "JODI$"
    .endif
    .ifdef SPANISH
    .string "CIRA$"
    .endif

gNameChoice_Amanda::
    .ifdef ENGLISH
    .string "AMANDA$"
    .endif
    .ifdef SPANISH
    .string "MARÍA$"
    .endif

gNameChoice_Hillary::
    .ifdef ENGLISH
    .string "HILLARY$"
    .endif
    .ifdef SPANISH
    .string "MINA$"
    .endif

gNameChoice_Makey::
    .ifdef ENGLISH
    .string "MAKEY$"
    .endif
    .ifdef SPANISH
    .string "NENA$"
    .endif

gNameChoice_Michi::
    .ifdef ENGLISH
    .string "MICHI$"
    .endif
    .ifdef SPANISH
    .string "LUNA$"
    .endif

gNameChoice_Paula::
    .ifdef ENGLISH
    .string "PAULA$"
    .endif
    .ifdef SPANISH
    .string "BRUNA$"
    .endif

gNameChoice_June::
    .ifdef ENGLISH
    .string "JUNE$"
    .endif
    .ifdef SPANISH
    .string "CLAUDIA$"
    .endif

gNameChoice_Cassie::
    .ifdef ENGLISH
    .string "CASSIE$"
    .endif
    .ifdef SPANISH
    .string "CASILDA$"
    .endif

gNameChoice_Rey::
    .ifdef ENGLISH
    .string "REY$"
    .endif
    .ifdef SPANISH
    .string "RITA$"
    .endif

gNameChoice_Seda::
    .ifdef ENGLISH
    .string "SEDA$"
    .endif
    .ifdef SPANISH
    .string "SELENA$"
    .endif

gNameChoice_Kiko::
    .ifdef ENGLISH
    .string "KIKO$"
    .endif
    .ifdef SPANISH
    .string "MATILDE$"
    .endif

gNameChoice_Mina::
    .ifdef ENGLISH
    .string "MINA$"
    .endif
    .ifdef SPANISH
    .string "NURIA$"
    .endif

gNameChoice_Norie::
    .ifdef ENGLISH
    .string "NORIE$"
    .endif
    .ifdef SPANISH
    .string "MARINA$"
    .endif

gNameChoice_Sai::
    .ifdef ENGLISH
    .string "SAI$"
    .endif
    .ifdef SPANISH
    .string "SALIA$"
    .endif

gNameChoice_Momo::
    .ifdef ENGLISH
    .string "MOMO$"
    .endif
    .ifdef SPANISH
    .string "MIRTA$"
    .endif

gNameChoice_Suzi::
    .ifdef ENGLISH
    .string "SUZI$"
    .endif
    .ifdef SPANISH
    .string "SUSA$"
    .endif

gNewGame_HelpDocs1::
    .ifdef ENGLISH
    .string "The various buttons will be explained in\n"
    .string "the order of their importance.$"
    .endif
    .ifdef SPANISH
    .string "La explicación de los botones\n"
    .string "se hará por orden de importancia.$"
    .endif

gNewGame_HelpDocs2::
    .ifdef ENGLISH
    .string "Moves the main character.\n"
    .string "Also used to choose various data\n"
    .string "headings.$"
    .endif
    .ifdef SPANISH
    .string "Mover al protagonista de la\n"
    .string "historia. Seleccionar opciones.$"
    .endif

gNewGame_HelpDocs3::
    .ifdef ENGLISH
    .string "Used to confirm a choice, check\n"
    .string "things, chat, and scroll text.$"
    .endif
    .ifdef SPANISH
    .string "Confirmar opciones, curiosear\n"
    .string "cosas, chatear y leer texto.$"
    .endif

gNewGame_HelpDocs4::
    .ifdef ENGLISH
    .string "Used to exit, cancel a choice,\n"
    .string "and cancel a mode.$"
    .endif
    .ifdef SPANISH
    .string "Retroceder, cancelar opciones\n"
    .string "y salir de distintos menús.$"
    .endif

gNewGame_HelpDocs5::
    .ifdef ENGLISH
    .string "Press this button to open the\n"
    .string "MENU.$"
    .endif
    .ifdef SPANISH
    .string "Abrir el menú.$"
    .endif

gNewGame_HelpDocs6::
    .ifdef ENGLISH
    .string "Used to shift items and to use\n"
    .string "a registered item.$"
    .endif
    .ifdef SPANISH
    .string "Cambiar objetos de lugar y usar\n"
    .string "el que haya registrado.$"
    .endif

gNewGame_HelpDocs7::
    .ifdef ENGLISH
    .string "If you need help playing the\n"
    .string "game, or on how to do things,\n"
    .string "press the L or R Button.$"
    .endif
    .ifdef SPANISH
    .string "Acceder al sistema de AYUDA.$"
    .endif

gOakText_AskPlayerGender::
    .ifdef ENGLISH
    .string "Now tell me. Are you a boy?\n"
    .string "Or are you a girl?$"
    .endif
    .ifdef SPANISH
    .string "Hola, ¿eres chico o chica?$"
    .endif

gNewGameAdventureIntro1::
    .ifdef ENGLISH
    .string "In the world which you are about to\n"
    .string "enter, you will embark on a grand\n"
    .string "adventure with you as the hero.\n"
    .string "\n"
    .string "Speak to people and check things\n"
    .string "wherever you go, be it towns, roads,\n"
    .string "or caves. Gather information and\n"
    .string "hints from every source.$"
    .endif
    .ifdef SPANISH
    .string "Estás a punto de sumergirte en un\n"
    .string "mundo lleno de aventuras de las\n"
    .string "que vas a ser protagonista.\n"
    .string "\n"
    .string "Habla con la gente y curiosea todo\n"
    .string "lo que te llame la atención, estés\n"
    .string "donde estés. Consigue información\n"
    .string "y pistas de todo lo que te rodee.$"
    .endif

gNewGameAdventureIntro2::
    .ifdef ENGLISH
    .string "New paths will open to you by helping\n"
    .string "people in need, overcoming challenges,\n"
    .string "and solving mysteries.\n"
    .string "\n"
    .string "At times, you will be challenged by\n"
    .string "others and attacked by wild creatures.\n"
    .string "Be brave and keep pushing on.$"
    .endif
    .ifdef SPANISH
    .string "Durante el largo camino, tendrás\n"
    .string "que ayudar a gente, enfrentarte\n"
    .string "a desafíos y resolver misterios.\n"
    .string "\n"
    .string "Te cruzarás con rivales y criaturas\n"
    .string "salvajes que querrán luchar\n"
    .string "contigo, pero ¡ánimo, tú puedes!$"
    .endif

gNewGameAdventureIntro3::
    .ifdef ENGLISH
    .string "Through your adventure, we hope\n"
    .string "that you will interact with all sorts\n"
    .string "of people and achieve personal growth.\n"
    .string "That is our biggest objective.\n"
    .string "\n"
    .string "Press the A Button, and let your\n"
    .string "adventure begin!$"
    .endif
    .ifdef SPANISH
    .string "Recuerda, habla con todo el mundo;\n"
    .string "crecerás como persona, y ése es\n"
    .string "tu principal objetivo.\n"
    .string "\n"
    .string "Pulsa el Botón A, ¡que comience\n"
    .string "la aventura!$"
    .endif

gOakText_WelcomeToTheWorld::
    .ifdef ENGLISH
    .string "Hello, there!\n"
    .string "Glad to meet you!\pWelcome to the world of POKéMON!\pMy name is OAK.\pPeople affectionately refer to me\n"
    .string "as the POKéMON PROFESSOR.\p$"
    .endif
    .ifdef SPANISH
    .string "¡Hola!\n"
    .string "¡Éste es el mundo de POKéMON!\p"
    .string "¡Me llamo OAK!\p"
    .string "¡Pero la gente me llama\n"
    .string "PROFESOR POKéMON!\p"
    .string "$"
    .endif

gOakText_WorldInhabited1::
    .ifdef ENGLISH
    .string "This world…$"
    .endif
    .ifdef SPANISH
    .string "¡Este mundo está$"
    .endif

gOakText_WorldInhabited2::
    .ifdef ENGLISH
    .string "…is inhabited far and wide by\n"
    .string "creatures called POKéMON.\p$"
    .endif
    .ifdef SPANISH
    .string "habitado por unas criaturas\n"
    .string "llamadas POKéMON!\p"
    .string "$"
    .endif

gOakText_PetsBattlingStudy::
    .ifdef ENGLISH
    .string "For some people, POKéMON are pets.\n"
    .string "Others use them for battling.\pAs for myself…\pI study POKéMON as a profession.\p$"
    .endif
    .ifdef SPANISH
    .string "Para algunos, los POKéMON son\n"
    .string "mascotas. Pero otros los usan\l"
    .string "para pelear.\p"
    .string "En cuanto a mí...\p"
    .string "Estudio a los POKéMON como\n"
    .string "profesión.\p"
    .string "$"
    .endif

gOakText_TellMeALittleAboutYourself::
    .ifdef ENGLISH
    .string "But first, tell me a little about\n"
    .string "yourself.\p$"
    .endif
    .ifdef SPANISH
    .string "Bueno, cuéntame algo de ti.\p"
    .string "$"
    .endif

gOakText_AskPlayerName::
    .ifdef ENGLISH
    .string "Let's begin with your name.\n"
    .string "What is it?\p$"
    .endif
    .ifdef SPANISH
    .string "Pero primero dime cómo te llamas.\p"
    .string "\n"
    .string "$"
    .endif

gOakText_FinalizePlayerName::
    .ifdef ENGLISH
    .string "Right…\n"
    .string "So your name is {PLAYER}.$"
    .endif
    .ifdef SPANISH
    .string "¡Bien!\n"
    .string "¡Así que te llamas {PLAYER}!$"
    .endif

gOakText_IntroduceRival::
    .ifdef ENGLISH
    .string "This is my grandson.\pHe's been your rival since you both\n"
    .string "were babies.\p…Erm, what was his name now?$"
    .endif
    .ifdef SPANISH
    .string "Éste es mi nieto.\p"
    .string "Ha sido tu rival desde que erais\n"
    .string "pequeños.\p"
    .string "Mmm... ¿podrías decirme cómo\n"
    .string "se llama?$"
    .endif

gOakText_AskRivalName::
    .ifdef ENGLISH
    .string "Your rival's name, what was it now?$"
    .endif
    .ifdef SPANISH
    .string "¿Cómo era el nombre de tu rival?$"
    .endif

gOakText_ConfirmRivalName::
    .ifdef ENGLISH
    .string "…Er, was it {RIVAL}?$"
    .endif
    .ifdef SPANISH
    .string "Eh..., ¿era {RIVAL}?$"
    .endif

gOakText_RememberRivalName::
    .ifdef ENGLISH
    .string "That's right! I remember now!\n"
    .string "His name is {RIVAL}!\p$"
    .endif
    .ifdef SPANISH
    .string "¡Ah, sí! ¡Es verdad!\n"
    .string "¡Se llamaba {RIVAL}!\p"
    .string "$"
    .endif

gOakText_LegendAboutToUnfold::
    .ifdef ENGLISH
    .string "{PLAYER}!\pYour very own POKéMON legend is\n"
    .string "about to unfold!\pA world of dreams and adventures\n"
    .string "with POKéMON awaits! Let's go!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER}!\p"
    .string "¡Tu propia leyenda POKéMON está\n"
    .string "a punto de comenzar!\p"
    .string "¡Te espera un mundo de sueños y\n"
    .string "aventuras con los POKéMON!\l"
    .string "¡Adelante!$"
    .endif
