Text_ObtainedTheX::
	.ifdef ENGLISH
	.string "Obtained the {STR_VAR_2}!$"
	.endif
	.ifdef SPANISH
	.string "¡Obtuviste {STR_VAR_2}!$"
	.endif

Text_BagIsFull::
	.ifdef ENGLISH
	.string "The BAG is full…$"
	.endif
	.ifdef SPANISH
	.string "La MOCHILA está llena...$"
	.endif

Text_PutItemAway::
	.ifdef ENGLISH
	.string "{PLAYER} put the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3}.$"
	.endif
	.ifdef SPANISH
	.string "{PLAYER} puso {STR_VAR_2}\n"
	.string "en el {STR_VAR_3}.$"
	.endif

Text_FoundOneItem::
	.ifdef ENGLISH
	.string "{PLAYER} found one {STR_VAR_2}!$"
	.endif
	.ifdef SPANISH
	.string "¡{PLAYER} encontró {STR_VAR_2}!$"
	.endif

Text_TooBadBagFull::
	.ifdef ENGLISH
	.string "Too bad!\n"
	.string "The BAG is full…$"
	.endif
	.ifdef SPANISH
	.string "¡Mala suerte!\n"
	.string "La MOCHILA está llena...$"
	.endif

Text_FoundXCoins::
	.ifdef ENGLISH
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"
	.endif
	.ifdef SPANISH
	.string "¡{PLAYER} encontró\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"
	.endif

Text_PutCoinsAwayInCoinCase::
	.ifdef ENGLISH
	.string "{PLAYER} put the COINS away in\n"
	.string "the COIN CASE.$"
	.endif
	.ifdef SPANISH
	.string "{PLAYER} puso las FICHAS\n"
	.string "en el MONEDERO.$"
	.endif

Text_CoinCaseIsFull::
	.ifdef ENGLISH
	.string "Too bad!\n"
	.string "The COIN CASE is full…$"
	.endif
	.ifdef SPANISH
	.string "¡Vaya!\n"
	.string "¡Tienes el MONEDERO lleno!...$"
	.endif

Text_NothingToPutThemIn::
	.ifdef ENGLISH
	.string "Too bad!\n"
	.string "There's nothing to put them in…$"
	.endif
	.ifdef SPANISH
	.string "¡Vaya!\n"
	.string "¡No tienes MONEDERO!...$"
	.endif

Text_FoundXItems::
	.ifdef ENGLISH
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"
	.endif
	.ifdef SPANISH
	.string "{PLAYER} encontró estas unidades\n"
	.string "de {STR_VAR_2}: ¡{STR_VAR_1}!$"
	.endif

Text_ObtainedTheDecor::
	.ifdef ENGLISH
	.string "Obtained the {STR_VAR_2}!$"
	.endif
	.ifdef SPANISH
	.string "¡Obtuviste {STR_VAR_2}!$"
	.endif

Text_NoRoomForAnotherDecor::
	.ifdef ENGLISH
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"
	.endif
	.ifdef SPANISH
	.string "¡Mala suerte! No queda sitio\n"
	.string "para {STR_VAR_2}...$"
	.endif

Text_DecorTransferredToPC::
	.ifdef ENGLISH
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"
	.endif
	.ifdef SPANISH
	.string "Se envió {STR_VAR_2} al PC.$"
	.endif
