Text_BootedUpPC::
	.ifdef ENGLISH
	.string "{PLAYER} booted up the PC.$"
	.endif
	.ifdef SPANISH
	.string "{PLAYER} encendió el PC.$"
	.endif

Text_AccessWhichPC::
	.ifdef ENGLISH
	.string "Which PC should be accessed?$"
	.endif
	.ifdef SPANISH
	.string "¿A qué PC quieres acceder?$"
	.endif

Text_AccessedSomeonesPC::
	.ifdef ENGLISH
	.string "Accessed Someone's PC.$"
	.endif
	.ifdef SPANISH
	.string "Accedió al PC de alguien.$"
	.endif

Text_OpenedPkmnStorage::
	.ifdef ENGLISH
	.string "POKéMON Storage System opened.$"
	.endif
	.ifdef SPANISH
	.string "Acceso al Sistema de\n"
	.string "Almacenamiento de POKéMON\l"
	.string "concedido.$"
	.endif

Text_AccessedPlayersPC::
	.ifdef ENGLISH
	.string "Accessed {PLAYER}'s PC.$"
	.endif
	.ifdef SPANISH
	.string "Accedió al PC de {PLAYER}.$"
	.endif

Text_AccessedBillsPC::
	.ifdef ENGLISH
	.string "Accessed BILL's PC.$"
	.endif
	.ifdef SPANISH
	.string "Accedió al PC de BILL.$"
	.endif
