Text_MakingPreparations::
	.string "じゅんびちゅうです！$"

Text_WantWhichFloor::
	.string "Which floor do you want?$"

Text_BagItemCanBeRegistered::
	.string "An item in the BAG can be\n"
	.string "registered to SELECT for easy use.$"

@ Unused (email from R/S Rivals computer)
Text_TrainerSchoolEmail::
	.string "パソコンに\n"
	.string "ポケモン　トレーナー　こうざの\l"
	.string "メールが　きている！\p"
	.string "‥‥　‥‥　‥‥\p"
	.string "ポケモンが　おぼえられる　わざは　4つ！\p"
	.string "どんな　わざを　おぼえさせるかで\n"
	.string "トレーナーの　じつりょくが　とわれます！\p"
	.string "‥‥　‥‥　‥‥$"

Text_PlayerBootedUpPC::
	.string "{PLAYER} booted up the PC.$"

@ Unused
Text_LinkWasCanceled::
	.string "つうしんは　キャンセルされました$"

@ Unused
Text_GiveNicknameToReceivedMon::
	.string "Want to give a nickname to the\n"
	.string "{STR_VAR_2} you received?$"

gText_PkmnFainted3::
	.string "{STR_VAR_1} fainted…\p"
	.string "$"

Text_WelcomeWantToHealPkmn::
	.string "Welcome to our POKéMON CENTER!\p"
	.string "Would you like me to heal your\n"
	.string "POKéMON back to perfect health?$"

Text_TakeYourPkmnForFewSeconds::
	.string "Okay, I'll take your POKéMON for a\n"
	.string "few seconds.$"

Text_WeHopeToSeeYouAgain::
	.string "We hope to see you again!$"

Text_RestoredPkmnToFullHealth::
	.string "Thank you for waiting.\n"
	.string "We've restored your POKéMON to\l"
	.string "full health.$"
