Pokedude_Text_SpeedierBattlerGoesFirst::
	.ifdef ENGLISH
	.string "POKé DUDE: The speedier of the\n"
	.string "battlers gets to attack first.$"
	.endif
	.ifdef SPANISH
	.string "POKéLOTODO: El más rápido atacará\n"
	.string "primero.$"
	.endif

Pokedude_Text_MyRattataFasterThanPidgey::
	.ifdef ENGLISH
	.string "It looks like my RATTATA was\n"
	.string "faster than the PIDGEY.$"
	.endif
	.ifdef SPANISH
	.string "Se ve que mi RATTATA ha sido\n"
	.string "más rápido que este PIDGEY.$"
	.endif

Pokedude_Text_BattlersTakeTurnsAttacking::
	.ifdef ENGLISH
	.string "The battlers take turns attacking\n"
	.string "and reducing each other's HP.$"
	.endif
	.ifdef SPANISH
	.string "Se lucha por turnos. ¡Hay que\n"
	.string "intentar dejar sin PS al rival!$"
	.endif

Pokedude_Text_MyRattataWonGetsEXP::
	.ifdef ENGLISH
	.string "My RATTATA reduced the foe's HP\n"
	.string "to zero, so it wins!\p"
	.string "The POKéMON that took part in the\n"
	.string "battle get EXP. Points.\p"
	.string "When a POKéMON collects enough\n"
	.string "EXP. Points, it levels up.\p"
	.string "Leveling up makes your POKéMON\n"
	.string "stronger than before.$"
	.endif
	.ifdef SPANISH
	.string "Como mi RATTATA ha dejado sin PS\n"
	.string "al enemigo, ¡gana el combate!\p"
	.string "Todos los POKéMON participantes\n"
	.string "en la lucha ganan puntos de EXP.\p"
	.string "Y cuando ganan suficientes puntos\n"
	.string "de EXP., pueden subir de nivel.\p"
	.string "Con el aumento de nivel, los\n"
	.string "POKéMON se hacen más fuertes.$"
	.endif

Pokedude_Text_UhOhRattataPoisoned::
	.ifdef ENGLISH
	.string "POKé DUDE: Uh-oh…\n"
	.string "My RATTATA has been poisoned…\p"
	.string "If a POKéMON is poisoned, it loses\n"
	.string "HP steadily.$"
	.endif
	.ifdef SPANISH
	.string "POKéLOTODO: Vaya fastidio...\n"
	.string "Mi RATTATA se ha envenenado...\p"
	.string "Cuando un POKéMON se envenena,\n"
	.string "vaya, cuando lo envenenan,\l"
	.string "va perdiendo PS poco a poco.$"
	.endif

Pokedude_Text_HealStatusRightAway::
	.ifdef ENGLISH
	.string "If a POKéMON develops a status\n"
	.string "problem, heal it right away.$"
	.endif
	.ifdef SPANISH
	.string "Si un POKéMON tiene problemas de\n"
	.string "estado, hay que curarlo corriendo.$"
	.endif

Pokedude_Text_UsingItemTakesTurn::
	.ifdef ENGLISH
	.string "Using an item on a POKéMON uses\n"
	.string "up one turn, though.\p"
	.string "Now, it's the opponent's turn!$"
	.endif
	.ifdef SPANISH
	.string "¡Pero si se usa un objeto en un\n"
	.string "POKéMON, se usa también un turno!\p"
	.string "¡Ahora, le toca al enemigo!$"
	.endif

Pokedude_Text_YayWeManagedToWin::
	.ifdef ENGLISH
	.string "Yay!\n"
	.string "We managed to win!$"
	.endif
	.ifdef SPANISH
	.string "¡Yupi!\n"
	.string "¡Hemos ganado!$"
	.endif

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
	.ifdef ENGLISH
	.string "POKé DUDE: The move BUBBLE is\n"
	.string "a WATER-type attack.\p"
	.string "The targeted ODDISH is a\n"
	.string "GRASS/POISON-type POKéMON.\p"
	.string "The WATER-type attack is absorbed\n"
	.string "by the GRASS-type POKéMON…\p"
	.string "As a result, the move becomes not\n"
	.string "very effective, and inflicts only\l"
	.string "half the usual damage.$"
	.endif
	.ifdef SPANISH
	.string "POKéLOTODO: El movimiento BURBUJA\n"
	.string "es un ataque del tipo AGUA.\p"
	.string "Y nuestro objetivo, ODDISH, es un\n"
	.string "POKéMON del tipo PLANTA-VENENO.\p"
	.string "Así que el tipo PLANTA absorberá\n"
	.string "el efecto del tipo AGUA.\p"
	.string "Vamos, que el movimiento no es\n"
	.string "muy eficaz y causa la mitad\l"
	.string "de daño.$"
	.endif

Pokedude_Text_GrassEffectiveAgainstWater::
	.ifdef ENGLISH
	.string "Uh-oh, this is not good!\p"
	.string "The ABSORB attack you just saw\n"
	.string "is a GRASS-type move.\p"
	.string "POLIWAG is a WATER-type POKéMON.\p"
	.string "So, ABSORB becomes super\n"
	.string "effective, doubling the damage.$"
	.endif
	.ifdef SPANISH
	.string "Vaya, mal asunto...\p"
	.string "El ataque ABSORBER que ha usado\n"
	.string "es un movimiento del tipo PLANTA.\p"
	.string "Y POLIWAG es un POKéMON\n"
	.string "del tipo AGUA...\p"
	.string "Vamos, que ABSORBER es muy eficaz\n"
	.string "y causa el doble de daño.$"
	.endif

Pokedude_Text_LetsTryShiftingMons::
	.ifdef ENGLISH
	.string "It's not going to be easy to win\n"
	.string "with this matchup…\p"
	.string "Let's try shifting POKéMON!$"
	.endif
	.ifdef SPANISH
	.string "Con esta combinación, lo tenemos\n"
	.string "crudo para ganar...\p"
	.string "¡Vamos a cambiar de POKéMON!$"
	.endif

Pokedude_Text_ShiftingUsesTurn::
	.ifdef ENGLISH
	.string "Shifting POKéMON in and out uses\n"
	.string "up one turn.\p"
	.string "Now, it's the opponent's turn.$"
	.endif
	.ifdef SPANISH
	.string "Claro que al cambiar de POKéMON\n"
	.string "se usa un turno...\p"
	.string "¡Ahora, le toca al enemigo!$"
	.endif

Pokedude_Text_ButterfreeDoubleResistsGrass::
	.ifdef ENGLISH
	.string "BUTTERFREE is a BUG/FLYING-type\n"
	.string "POKéMON.\p"
	.string "Against this POKéMON, a GRASS-\n"
	.string "type attack…\p"
	.string "…inflicts only half the usual\n"
	.string "damage on a BUG-type POKéMON…\p"
	.string "…And, it also causes only half the\n"
	.string "damage on a FLYING-type POKéMON.\p"
	.string "Therefore, BUTTERFREE, being a\n"
	.string "BUG/FLYING POKéMON, only takes\l"
	.string "one quarter of the usual damage.$"
	.endif
	.ifdef SPANISH
	.string "BUTTERFREE es un POKéMON\n"
	.string "del tipo BICHO-VOLADOR.\p"
	.string "Un movimiento del tipo PLANTA...\p"
	.string "Hace la mitad de daño a los\n"
	.string "POKéMON del tipo BICHO...\p"
	.string "Y también causa la mitad de daño\n"
	.string "a los POKéMON del tipo VOLADOR.\p"
	.string "Vamos, que BUTTERFREE, al ser\n"
	.string "del tipo BICHO-VOLADOR, sólo\l"
	.string "recibe una cuarta parte del daño.$"
	.endif

Pokedude_Text_ButterfreeGoodAgainstOddish::
	.ifdef ENGLISH
	.string "ODDISH is a GRASS/POISON-type\n"
	.string "POKéMON.\p"
	.string "A FLYING- or PSYCHIC-type attack\n"
	.string "is super effective against it.\p"
	.string "One of those types of attacks will\n"
	.string "inflict double the usual damage.\p"
	.string "Okay, here we go!$"
	.endif
	.ifdef SPANISH
	.string "ODDISH es un POKéMON del tipo\n"
	.string "PLANTA-VENENO.\p"
	.string "Los movimientos de los tipos\n"
	.string "VOLADOR o PSÍQUICO son\l"
	.string "muy eficaces contra él.\p"
	.string "Vamos, que le harán el doble\n"
	.string "de daño de lo habitual.\p"
	.string "¡Bueno, vamos allá!$"
	.endif

Pokedude_Text_YeahWeWon::
	.ifdef ENGLISH
	.string "Yeah!\n"
	.string "We won!$"
	.endif
	.ifdef SPANISH
	.string "¡Yupi!\n"
	.string "¡Hemos ganado!$"
	.endif

Pokedude_Text_WeakenMonBeforeCatching::
	.ifdef ENGLISH
	.string "POKé DUDE: When you're trying to\n"
	.string "catch a POKéMON, don't throw any\l"
	.string "POKé BALLS right away.\p"
	.string "First, you need to weaken it by\n"
	.string "reducing its HP.$"
	.endif
	.ifdef SPANISH
	.string "POKéLOTODO: Para atrapar POKéMON,\n"
	.string "no hay que ponerse a tirar POKé\l"
	.string "BALLS sin más.\p"
	.string "Primero hay que bajar sus PS todo\n"
	.string "lo que se pueda.$"
	.endif

Pokedude_Text_BestIfTargetStatused::
	.ifdef ENGLISH
	.string "Okay, that should be good enough.\p"
	.string "But, if it's possible, it would be\n"
	.string "best if the target has a status\l"
	.string "problem.\p"
	.string "For instance, it would be easier\n"
	.string "to catch if it were asleep or\l"
	.string "paralyzed.$"
	.endif
	.ifdef SPANISH
	.string "Bueno, yo creo que es suficiente.\p"
	.string "Aunque, claro, lo ideal sería que\n"
	.string "tuviera algún problema de estado.\p"
	.string "Vamos, que sería más fácil si\n"
	.string "estuviera dormido o paralizado.$"
	.endif

Pokedude_Text_CantDoubleUpOnStatus::
	.ifdef ENGLISH
	.string "This will make the POKéMON a lot\n"
	.string "easier to catch!\p"
	.string "Oh, yes. If you paralyze a\n"
	.string "POKéMON, you can't make it fall\l"
	.string "asleep on top of paralysis.\p"
	.string "In other words, you can't double\n"
	.string "up status problems, okay?$"
	.endif
	.ifdef SPANISH
	.string "¡Así es mucho más sencillo atrapar\n"
	.string "al POKéMON!\p"
	.string "Aunque, claro, si se paraliza a un\n"
	.string "POKéMON, ¡no se le podrá dormir!\p"
	.string "Vamos, que no se pueden causar\n"
	.string "dos problemas de estado a la vez.$"
	.endif

Pokedude_Text_LetMeThrowBall::
	.ifdef ENGLISH
	.string "Okay!\n"
	.string "Let me throw my POKé BALL!$"
	.endif
	.ifdef SPANISH
	.string "¡Bueno, vamos a lanzar una POKé\n"
	.string "BALL!$"
	.endif

Pokedude_Text_PickBestKindOfBall::
	.ifdef ENGLISH
	.string "Before you throw a POKé BALL,\n"
	.string "consider the condition and the\l"
	.string "type of POKéMON, and pick the kind\l"
	.string "of BALL that would work best.$"
	.endif
	.ifdef SPANISH
	.string "Antes de lanzar una POKé BALL,\n"
	.string "hay que tener en cuenta el estado\l"
	.string "y el tipo del POKéMON.\p"
	.string "Así, se podrá elegir la BALL que\n"
	.string "va mejor.$"
	.endif
