Text_MayIHelpYou::
	.ifdef ENGLISH
	.string "Hi, there!\n"
	.string "May I help you?$"
	.endif
	.ifdef SPANISH
	.string "¡Hola! ¿Puedo ayudarte en algo?$"
	.endif

Text_FillOutQuestionnaire::
	.ifdef ENGLISH
	.string "There is a questionnaire.\n"
	.string "Would you like to fill it out?$"
	.endif
	.ifdef SPANISH
	.string "Hay un cuestionario.\n"
	.string "¿Quieres rellenarlo?$"
	.endif

Text_QuestionnaireThankYou::
	.ifdef ENGLISH
	.string "Thank you for taking the time to\n"
	.string "fill out our questionnaire.\p"
	.string "Your feedback will be used for\n"
	.string "future reference.$"
	.endif
	.ifdef SPANISH
	.string "Gracias por rellenar el\n"
	.string "cuestionario. Usaremos tus\l"
	.string "respuestas a modo de referencia.$"
	.endif

Text_YouKnowThoseWords::
	.ifdef ENGLISH
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must know about\n"
	.string "the MYSTERY GIFT.\p"
	.string "From now on, you should be\n"
	.string "receiving MYSTERY GIFTS!$"
	.endif
	.ifdef SPANISH
	.string "Hola, ¿conoces las palabras?\p"
	.string "Pues entonces debes de saber\n"
	.string "de qué va el REGALO MISTERIOSO.\p"
	.string "¡A partir de ahora, podrás recibir\n"
	.string "REGALOS MISTERIOSOS!$"
	.endif

Text_YouCanAccessMysteryGift::
	.ifdef ENGLISH
	.string "Once you save your game, you can\n"
	.string "access the MYSTERY GIFT.$"
	.endif
	.ifdef SPANISH
	.string "Una vez guardes la partida, podrás\n"
	.string "acceder al REGALO MISTERIOSO.$"
	.endif

Text_ThankYouForAccessingMysteryGift::
	.ifdef ENGLISH
	.string "Thank you for accessing the\n"
	.string "MYSTERY GIFT System.$"
	.endif
	.ifdef SPANISH
	.string "Gracias por acceder al sistema\n"
	.string "del REGALO MISTERIOSO.$"
	.endif
