PokedexRating_Text_HowIsPokedexComingAlong::
	.ifdef ENGLISH
	.string "OAK: Good to see you!\n"
	.string "How is your POKéDEX coming along?\p"
	.string "Here, let me take a look.$"
	.endif
	.ifdef SPANISH
	.string "OAK: ¡Encantado de verte!\n"
	.string "¿Cómo va tu POKéDEX?\p"
	.string "¡Déjame que le eche un vistazo!$"
	.endif

PokedexRating_Text_SeenXOwnedY::
	.ifdef ENGLISH
	.string "The amount of progress you've made\n"
	.string "on your POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.\p"
	.string "{FONT_NORMAL}PROF. OAK's rating:$"
	.endif
	.ifdef SPANISH
	.string "Nivel POKéDEX:\p"
	.string "Has visto {STR_VAR_1} POKéMON\n"
	.string "Tienes {STR_VAR_2} POKéMON\p"
	.string "Evaluación del PROF. OAK:$"
	.endif

PokedexRating_Text_LessThan10::
	.ifdef ENGLISH
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for POKéMON!$"
	.endif
	.ifdef SPANISH
	.string "Te queda mucho por hacer.\p"
	.string "¡Busca a los POKéMON en las zonas\n"
	.string "de hierba!$"
	.endif

PokedexRating_Text_LessThan20::
	.ifdef ENGLISH
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my AIDES a FLASH\n"
	.string "HM. Make sure you go get it!$"
	.endif
	.ifdef SPANISH
	.string "¡Estás en buen camino!\p"
	.string "¡Pídele a uno de mis AYUDANTES\n"
	.string "la MO DESTELLO que le\l"
	.string "he dado para ti!$"
	.endif

PokedexRating_Text_LessThan30::
	.ifdef ENGLISH
	.string "Your POKéDEX could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "POKéMON!$"
	.endif
	.ifdef SPANISH
	.string "¡Necesitas más POKéMON!\n"
	.string "¡Intenta capturar otras especies!$"
	.endif

PokedexRating_Text_LessThan40::
	.ifdef ENGLISH
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my AIDES an\n"
	.string "ITEMFINDER. Be sure to collect it!$"
	.endif
	.ifdef SPANISH
	.string "¡Muy bien!\p"
	.string "¡Pídele a uno de mis AYUDANTES\n"
	.string "un BUSCAOBJETOS que le\l"
	.string "he dado para ti!$"
	.endif

PokedexRating_Text_LessThan50::
	.ifdef ENGLISH
	.string "Your POKéDEX is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my AIDES an\n"
	.string "AMULET COIN. Be sure to get it!$"
	.endif
	.ifdef SPANISH
	.string "¡Tu POKéDEX va de maravilla!\p"
	.string "¡Pídele a uno de mis AYUDANTES\n"
	.string "la MONEDA AMULETO que le\l"
	.string "he dado para ti!$"
	.endif

PokedexRating_Text_LessThan60::
	.ifdef ENGLISH
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my AIDES an EXP.\n"
	.string "SHARE. Be sure to go get it!$"
	.endif
	.ifdef SPANISH
	.string "¡Ya has conseguido 50 especies!\p"
	.string "¡Pídele a uno de mis AYUDANTES\n"
	.string "el REPARTIR EXP. que le he dado\l"
	.string "para ti!$"
	.endif

PokedexRating_Text_LessThan70::
	.ifdef ENGLISH
	.string "Hoho! This is turning into quite the\n"
	.string "respectable POKéDEX!$"
	.endif
	.ifdef SPANISH
	.string "¡Oh!\n"
	.string "¡Lo estás haciendo genial!$"
	.endif

PokedexRating_Text_LessThan80::
	.ifdef ENGLISH
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "POKéMON by going fishing!$"
	.endif
	.ifdef SPANISH
	.string "¡Excelente!\p"
	.string "¡Ve a pescar algunos POKéMON\n"
	.string "del mar!$"
	.endif

PokedexRating_Text_LessThan90::
	.ifdef ENGLISH
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"
	.endif
	.ifdef SPANISH
	.string "¡Magnífico!\n"
	.string "Te encanta coleccionar cosas, ¿eh?$"
	.endif

PokedexRating_Text_LessThan100::
	.ifdef ENGLISH
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"
	.endif
	.ifdef SPANISH
	.string "¡Impresionante!\n"
	.string "¡Debe de haber sido muy difícil!$"
	.endif

PokedexRating_Text_LessThan110::
	.ifdef ENGLISH
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"
	.endif
	.ifdef SPANISH
	.string "¡Por fin tienes 100 especies!\n"
	.string "¡Se te da genial!$"
	.endif

PokedexRating_Text_LessThan120::
	.ifdef ENGLISH
	.string "You even have the evolved forms\n"
	.string "of POKéMON! Super!$"
	.endif
	.ifdef SPANISH
	.string "¡Y has conseguido hasta transformar\n"
	.string "a tus POKéMON! ¡Eres genial!$"
	.endif

PokedexRating_Text_LessThan130::
	.ifdef ENGLISH
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"
	.endif
	.ifdef SPANISH
	.string "¡Excelente! ¡Intercambia con tus\n"
	.string "amigos y tendrás más!$"
	.endif

PokedexRating_Text_LessThan140::
	.ifdef ENGLISH
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"
	.endif
	.ifdef SPANISH
	.string "¡Impresionante!\n"
	.string "¡Eres muy profesional!$"
	.endif

PokedexRating_Text_LessThan150::
	.ifdef ENGLISH
	.string "I have nothing left to say!\n"
	.string "You're the POKéMON PROFESSOR now!$"
	.endif
	.ifdef SPANISH
	.string "¡No tengo nada más que decir!\n"
	.string "¡Ahora eres una eminencia!$"
	.endif

PokedexRating_Text_Complete::
	.ifdef ENGLISH
	.string "Your POKéDEX is entirely complete!\n"
	.string "Congratulations!!$"
	.endif
	.ifdef SPANISH
	.string "¡Tu POKéDEX está completa!\n"
	.string "¡Enhorabuena!$"
	.endif

PokedexRating_Text_NationalDexSeenXOwnedY::
	.ifdef ENGLISH
	.string "And your NATIONAL POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.$"
	.endif
	.ifdef SPANISH
	.string "A ver cómo llevas la POKéDEX\n"
	.string "NACIONAL:\p"
	.string "POKéMON avistados: {STR_VAR_1}\n"
	.string "POKéMON atrapados: {STR_VAR_2}$"
	.endif

PokedexRating_Text_LookForwardToFilledNationalDex::
	.ifdef ENGLISH
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL POKéDEX!$"
	.endif
	.ifdef SPANISH
	.string "¡Estoy deseando ver cómo completas\n"
	.string "la POKéDEX NACIONAL!$"
	.endif

PokedexRating_Text_YouveCompletedDex::
	.ifdef ENGLISH
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "POKéDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"
	.endif
	.ifdef SPANISH
	.string "¡Por fin!\p"
	.string "¡Ya has completado la POKéDEX!\p"
	.string "¡Magnífico!\n"
	.string "¡De verdad, no era tarea fácil!$"
	.endif

PokedexRating_Text_Wroooaaarrr::
	.ifdef ENGLISH
	.string "Wroooooooaaaaaarrrr!$"
	.endif
	.ifdef SPANISH
	.string "¡Guuuaaaaauuuuu!$"
	.endif

PokedexRating_Text_HaHa::
	.string "はあ はあ‥$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.ifdef ENGLISH
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"
	.endif
	.ifdef SPANISH
	.string "¡Gracias, {PLAYER}!\n"
	.string "Gracias de verdad.\l"
	.string "¡Has hecho mi sueño realidad!$"
	.endif

PokedexRating_Text_LoveSeeingYourPokedex::
	.ifdef ENGLISH
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your POKéDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see…$"
	.endif
	.ifdef SPANISH
	.string "OAK: ¡Hola!\p"
	.string "¿Qué tal llevas la POKéDEX?\p"
	.string "A ver...\p"
	.string "La verdad es que sé cómo es, pero\n"
	.string "me gusta verla de todas formas.\p"
	.string "A ver, a ver...$"
	.endif
