Text_OnlySkilledTrainersAllowedThrough::
	.ifdef ENGLISH
	.string "Only truly skilled TRAINERS are\n"
	.string "allowed through.\p"
	.string "You don't have the {STR_VAR_1}\n"
	.string "yet!$"
	.endif
	.ifdef SPANISH
	.string "Sólo pueden pasar los\n"
	.string "ENTRENADORES expertos.\p"
	.string "¡Aún no tienes la {STR_VAR_1}!$"
	.endif

Text_CantLetYouPass::
	.ifdef ENGLISH
	.string "Rules are rules.\n"
	.string "I can't let you pass.$"
	.endif
	.ifdef SPANISH
	.string "Las reglas son las reglas.\n"
	.string "¡No puedes pasar!$"
	.endif

Text_OhThatsBadgeGoRightAhead::
	.ifdef ENGLISH
	.string "Oh! That is the {STR_VAR_1}!\n"
	.string "Go right ahead.$"
	.endif
	.ifdef SPANISH
	.string "¡Oh! ¡Ésa es la {STR_VAR_1}!\n"
	.string "¡Puedes pasar!$"
	.endif

Text_OnlyPassWithBadgeDontHaveYet::
	.ifdef ENGLISH
	.string "You can pass here only if you have\n"
	.string "the {STR_VAR_1}.\p"
	.string "You don't have the {STR_VAR_1}\n"
	.string "yet.\p"
	.string "You have to have it to get to\n"
	.string "the POKéMON LEAGUE.$"
	.endif
	.ifdef SPANISH
	.string "¡Sólo podrás entrar aquí si tienes\n"
	.string "la {STR_VAR_1}!\p"
	.string "¡Aún no tienes la {STR_VAR_1}!\p"
	.string "¡Debes tenerla para acceder\n"
	.string "a la LIGA POKéMON!$"
	.endif

Text_OnlyPassWithBadgeOhGoAhead::
	.ifdef ENGLISH
	.string "You can pass here only if you have\n"
	.string "the {STR_VAR_1}.\p"
	.string "Oh! That is the {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "Okay, then.\n"
	.string "Please, go right ahead.$"
	.endif
	.ifdef SPANISH
	.string "¡Sólo podrás entrar aquí si tienes\n"
	.string "la {STR_VAR_1}!\p"
	.string "¡Anda! ¡Ésa es la {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "¡Muy bien!\n"
	.string "¡Puedes pasar!$"
	.endif
