@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight::
	.ifdef ENGLISH
	.string "Hmm…\n"
	.string "Is that right…$"
	.endif
	.ifdef SPANISH
	.string "Mmm...\n"
	.string "Qué curioso...$"
	.endif

PalletTown_Text_OhLookLook::
	.ifdef ENGLISH
	.string "Oh!\n"
	.string "Look, look!$"
	.endif
	.ifdef SPANISH
	.string "¡Eh, mira, mira!$"
	.endif

PalletTown_Text_ReadItReadIt::
	.ifdef ENGLISH
	.string "Read it, read it!$"
	.endif
	.ifdef SPANISH
	.string "¡Mira lo que pone aquí, léelo!$"
	.endif

@ Used by sign
PalletTown_Text_PressStartToOpenMenu::
	.ifdef ENGLISH
	.string "TRAINER TIPS\p"
	.string "Press START to open the MENU!$"
	.endif
	.ifdef SPANISH
	.string "PISTAS ENTRENADOR\p"
	.string "¡Pulsa START para abrir el MENÚ!$"
	.endif

PalletTown_Text_SignsAreUsefulArentThey::
	.ifdef ENGLISH
	.string "Signs are useful, aren't they?$"
	.endif
	.ifdef SPANISH
	.string "Es básico leer lo que pone en los\n"
	.string "carteles, ¿no te parece?$"
	.endif

PalletTown_Text_LookCopiedTrainerTipsSign::
	.ifdef ENGLISH
	.string "Look, look!\p"
	.string "I copied what it said on one of\n"
	.string "those TRAINER TIPS signs!$"
	.endif
	.ifdef SPANISH
	.string "¡Mira, mira!\p"
	.string "He copiado lo que ponía en uno\n"
	.string "de los carteles de PISTAS\l"
	.string "ENTRENADOR.$"
	.endif

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy::
	.ifdef ENGLISH
	.string "TRAINER TIPS!\p"
	.string "Press START to open the MENU!$"
	.endif
	.ifdef SPANISH
	.string "PISTAS ENTRENADOR\p"
	.string "¡Pulsa START para abrir el MENÚ!$"
	.endif
