Text_WantToSurf::
	.ifdef ENGLISH
	.string "The water is dyed a deep blue…\n"
	.string "Would you like to SURF?$"
	.endif
	.ifdef SPANISH
	.string "El agua tiene buena pinta...\n"
	.string "¿Quieres hacer SURF?$"
	.endif

Text_UsedSurf::
	.ifdef ENGLISH
	.string "{STR_VAR_1} used SURF!$"
	.endif
	.ifdef SPANISH
	.string "¡{STR_VAR_1} usó SURF!$"
	.endif

Text_CurrentTooFast::
	.ifdef ENGLISH
	.string "The current is much too fast!\n"
	.string "SURF can't be used here…$"
	.endif
	.ifdef SPANISH
	.string "¡Esto es una zona de rápidos!\n"
	.string "¡Aquí no se puede hacer SURF!...$"
	.endif
