VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.ifdef ENGLISH
	.string "The battery isn't charged enough.\p"
	.string "No. of steps required to fully\n"
	.string "charge the battery: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"
	.endif
	.ifdef SPANISH
	.string "La batería no está cargada\n"
	.string "del todo.\p"
	.string "Los pasos que te faltan para\n"
	.string "cargarla son: {STR_VAR_1}.{PAUSE_UNTIL_PRESS}$"
	.endif

VSSeeker_Text_NoTrainersWithinRange::
	.ifdef ENGLISH
	.string "There are no TRAINERS within range\n"
	.string "who can battle…\p"
	.string "The VS SEEKER was turned off.{PAUSE_UNTIL_PRESS}$"
	.endif
	.ifdef SPANISH
	.string "No hay ENTRENADORES cerca contra\n"
	.string "los que poder luchar...\p"
	.string "El BUSCAPELEA se ha apagado.{PAUSE_UNTIL_PRESS}$"
	.endif

VSSeeker_Text_TrainersNotReady::
	.ifdef ENGLISH
	.string "The other TRAINERS don't appear\n"
	.string "to be ready for battle.\p"
	.string "Let's wait till later.{PAUSE_UNTIL_PRESS}$"
	.endif
	.ifdef SPANISH
	.string "No parece que los otros\n"
	.string "ENTRENADORES estén listos\l"
	.string "para luchar.\p"
	.string "Habrá que esperar un poco.{PAUSE_UNTIL_PRESS}.$"
	.endif

Route3_Text_ColtonRematchIntro::
	.ifdef ENGLISH
	.string "Hey!\n"
	.string "I saw you in VIRIDIAN FOREST!$"
	.endif
	.ifdef SPANISH
	.string "¡Nos vimos en el BOSQUE VERDE!$"
	.endif

Route3_Text_BenRematchIntro::
	.ifdef ENGLISH
	.string "Hi! I like shorts!\n"
	.string "They're comfy and easy to wear!\p"
	.string "You should be wearing shorts, too!$"
	.endif
	.ifdef SPANISH
	.string "¡Hola!\n"
	.string "¡Me gustan los pantalones cortos!\p"
	.string "¡Son muy cómodos!$"
	.endif

Route3_Text_JaniceRematchIntro::
	.ifdef ENGLISH
	.string "Excuse me!\n"
	.string "You keep looking at me, don't you?$"
	.endif
	.ifdef SPANISH
	.string "Estabas mirándome ¿verdad?$"
	.endif

Route3_Text_GregRematchIntro::
	.ifdef ENGLISH
	.string "You're a TRAINER, aren't you?\n"
	.string "Let's get with it right away!$"
	.endif
	.ifdef SPANISH
	.string "¿Entrenas POKéMON?\n"
	.string "¡Pues luchemos!$"
	.endif

Route3_Text_SallyRematchIntro::
	.ifdef ENGLISH
	.string "That look you give me…\n"
	.string "It intrigues me so!$"
	.endif
	.ifdef SPANISH
	.string "¡Esa mirada tuya fue de lo más\n"
	.string "misteriosa!$"
	.endif

Route3_Text_CalvinRematchIntro::
	.ifdef ENGLISH
	.string "Hey! What's wrong with you?\n"
	.string "You're still not wearing shorts!$"
	.endif
	.ifdef SPANISH
	.string "¡Oye!\n"
	.string "¡No llevas pantalón corto!$"
	.endif

Route3_Text_JamesRematchIntro::
	.ifdef ENGLISH
	.string "I'll battle you with the POKéMON\n"
	.string "I started raising.$"
	.endif
	.ifdef SPANISH
	.string "Lucharé contigo junto a los\n"
	.string "POKéMON que yo mismo he criado.$"
	.endif

Route3_Text_RobinRematchIntro::
	.ifdef ENGLISH
	.string "Eek!\n"
	.string "Did you push me?$"
	.endif
	.ifdef SPANISH
	.string "¡Eh!\n"
	.string "¡Me has empujado!$"
	.endif

Route4_Text_CrissyRematchIntro::
	.ifdef ENGLISH
	.string "I always catch mushroom POKéMON\n"
	.string "on MT. MOON.$"
	.endif
	.ifdef SPANISH
	.string "A mí me encanta buscar POKéMON\n"
	.string "hongo en el MT. MOON.$"
	.endif

Route6_Text_RickyRematchIntro::
	.ifdef ENGLISH
	.string "Oh! You're that nosy kid who\n"
	.string "eavesdropped on us!$"
	.endif
	.ifdef SPANISH
	.string "¡Tu eres la pesadilla que nos\n"
	.string "dio la paliza!$"
	.endif

Route6_Text_NancyRematchIntro::
	.ifdef ENGLISH
	.string "Excuse me! Didn't I tell you that\n"
	.string "this is a private conversation?\p"
	.string "You shouldn't be listening in,\n"
	.string "you uncouth person!$"
	.endif
	.ifdef SPANISH
	.string "Perdona, ¿no ves que es una\n"
	.string "conversación privada?\p"
	.string "Pues ¿qué haces con la antena\n"
	.string "puesta?$"
	.endif

Route6_Text_KeigoRematchIntro::
	.ifdef ENGLISH
	.string "I'm trying to find something good\n"
	.string "that's not a BUG POKéMON, but…$"
	.endif
	.ifdef SPANISH
	.string "Estoy intentando encontrar un buen\n"
	.string "ejemplar, que no sea un POKéMON\l"
	.string "BICHO, pero...$"
	.endif

Route6_Text_JeffRematchIntro::
	.ifdef ENGLISH
	.string "Huh?\n"
	.string "You want to go with me again?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué? ¿Qué quieres, luchar\n"
	.string "conmigo de nuevo?$"
	.endif

Route6_Text_IsabelleRematchIntro::
	.ifdef ENGLISH
	.string "Me?\n"
	.string "Well, okay. I'll play this once.$"
	.endif
	.ifdef SPANISH
	.string "¿Yo?\n"
	.string "Pues vale. ¡Vamos!$"
	.endif

Route6_Text_ElijahRematchIntro::
	.ifdef ENGLISH
	.string "Hey, long time!\n"
	.string "Have you gotten better?$"
	.endif
	.ifdef SPANISH
	.string "Eh, ¡qué de tiempo!\n"
	.string "¿Eres más fuerte?$"
	.endif

Route8_Text_AidanRematchIntro::
	.ifdef ENGLISH
	.string "You are good at POKéMON, but how\n"
	.string "is your chemistry grade?$"
	.endif
	.ifdef SPANISH
	.string "Se te dan bien los POKéMON, pero\n"
	.string "¿qué tal en química?$"
	.endif

Route8_Text_StanRematchIntro::
	.ifdef ENGLISH
	.string "All right!\n"
	.string "Let's play another game!$"
	.endif
	.ifdef SPANISH
	.string "¡Muy bien!\n"
	.string "¡Luchemos otra vez!$"
	.endif

Route8_Text_GlennRematchIntro::
	.ifdef ENGLISH
	.string "You need strategy to win at\n"
	.string "battling.\p"
	.string "Are you following my advice?$"
	.endif
	.ifdef SPANISH
	.string "¡Necesitas una buena estrategia!\p"
	.string "¿Te queda claro?$"
	.endif

Route8_Text_PaigeRematchIntro::
	.ifdef ENGLISH
	.string "I've collected many NIDORAN.\n"
	.string "I don't want them to evolve, but…$"
	.endif
	.ifdef SPANISH
	.string "Tengo muchos NIDORAN.\n"
	.string "No quiero que evolucionen, pero...$"
	.endif

Route8_Text_LeslieRematchIntro::
	.ifdef ENGLISH
	.string "School is fun, but I still think\n"
	.string "POKéMON are fun, too.$"
	.endif
	.ifdef SPANISH
	.string "¡Me gusta el colegio y los\n"
	.string "POKéMON!$"
	.endif

Route8_Text_AndreaRematchIntro::
	.ifdef ENGLISH
	.string "MEOWTH and PERSIAN are so cute,\n"
	.string "meow, meow, meow!$"
	.endif
	.ifdef SPANISH
	.string "¡MEOWTH y PERSIAN son ideales,\n"
	.string "ideales totales, meow, meow, meow!$"
	.endif

Route8_Text_MeganRematchIntro::
	.ifdef ENGLISH
	.string "We may look silly standing here\n"
	.string "like this, but I can still battle.$"
	.endif
	.ifdef SPANISH
	.string "Debemos de dar una imagen algo\n"
	.string "tonta, pero ¡lo importante es que\l"
	.string "yo quiero luchar!$"
	.endif

Route8_Text_RichRematchIntro::
	.ifdef ENGLISH
	.string "I'm a rambling, gaming dude!\n"
	.string "I'm on a winning streak!$"
	.endif
	.ifdef SPANISH
	.string "¡Soy un jugador errante!\n"
	.string "¡Y voy a ganar!$"
	.endif

Route8_Text_JuliaRematchIntro::
	.ifdef ENGLISH
	.string "What's a cute, round, and fluffy\n"
	.string "POKéMON?\p"
	.string "You already know, don't you?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué POKéMON es mono, redondo\n"
	.string "y blando?\p"
	.string "Lo sabes, ¿no?$"
	.endif

Route8_Text_RicardoRematchIntro::
	.ifdef ENGLISH
	.string "My bike's still acting up, man.$"
	.endif
	.ifdef SPANISH
	.string "¡Mi bici sigue yendo como\n"
	.string "una moto!$"
	.endif

Route8_Text_JarenRematchIntro::
	.ifdef ENGLISH
	.string "Okay, kid!\n"
	.string "Don't expect mercy this time!$"
	.endif
	.ifdef SPANISH
	.string "Bueno, esta vez no me voy\n"
	.string "a andar con tonterías.$"
	.endif

Route8_Text_EliRematchIntro::
	.ifdef ENGLISH
	.string "ELI: Our twin power became even\n"
	.string "better!$"
	.endif
	.ifdef SPANISH
	.string "TITA: ¡Ahora somos más fuertes!$"
	.endif

Route8_Text_AnneRematchIntro::
	.ifdef ENGLISH
	.string "ANNE: Our twin power powered up!$"
	.endif
	.ifdef SPANISH
	.string "LIN: ¡Ya somos mucho más fuertes!$"
	.endif

Route9_Text_AliciaRematchIntro::
	.ifdef ENGLISH
	.string "We're to battle again?\n"
	.string "This time, you're mine!$"
	.endif
	.ifdef SPANISH
	.string "¿Vamos a luchar de nuevo?\n"
	.string "¡Pues esta vez, olvídate!$"
	.endif

Route9_Text_ChrisRematchIntro::
	.ifdef ENGLISH
	.string "I haven't forgotten you were with\n"
	.string "those good-looking POKéMON.$"
	.endif
	.ifdef SPANISH
	.string "Tú eras quien tenía esos POKéMON\n"
	.string "tan bonitos...$"
	.endif

Route9_Text_DrewRematchIntro::
	.ifdef ENGLISH
	.string "I'm taking ROCK TUNNEL to go to\n"
	.string "LAVENDER…\p"
	.string "But I keep getting stopped by\n"
	.string "everyone along the way…$"
	.endif
	.ifdef SPANISH
	.string "Quiero tomar el TÚNEL ROCA\n"
	.string "para ir a LAVANDA.\p"
	.string "¡Pero cada dos por tres se cruza\n"
	.string "alguien en mi camino!...$"
	.endif

Route9_Text_CaitlinRematchIntro::
	.ifdef ENGLISH
	.string "Don't you dare patronize me today!\n"
	.string "We're playing for keeps!$"
	.endif
	.ifdef SPANISH
	.string "¡No te andes con contemplaciones!\n"
	.string "¡Hay que ir a por todas!$"
	.endif

Route9_Text_JeremyRematchIntro::
	.ifdef ENGLISH
	.string "Bwahaha!\n"
	.string "Great! I was bored again, eh!$"
	.endif
	.ifdef SPANISH
	.string "¡Qué bien! ¡Me estaba aburriendo\n"
	.string "otra vez!$"
	.endif

Route9_Text_BriceRematchIntro::
	.ifdef ENGLISH
	.string "Hahaha!\n"
	.string "A little toughie, as always!$"
	.endif
	.ifdef SPANISH
	.string "¡Jaja! ¡A ver lo fuerte que estás!$"
	.endif

Route9_Text_BrentRematchIntro::
	.ifdef ENGLISH
	.string "I got up early every day to train\n"
	.string "my POKéMON from cocoons!$"
	.endif
	.ifdef SPANISH
	.string "Cada día me levanto temprano para\n"
	.string "entrenar a mis POKéMON capullo.$"
	.endif

Route9_Text_AlanRematchIntro::
	.ifdef ENGLISH
	.string "Hahahaha!\n"
	.string "I'll win this time!$"
	.endif
	.ifdef SPANISH
	.string "¡Esta vez gano yo!$"
	.endif

Route9_Text_ConnerRematchIntro::
	.ifdef ENGLISH
	.string "Go win, my super BUG POKéMON!$"
	.endif
	.ifdef SPANISH
	.string "¡Adelante de nuevo, mis geniales\n"
	.string "POKéMON BICHO!$"
	.endif

Route10_Text_MarkRematchIntro::
	.ifdef ENGLISH
	.string "Wow, you came here again?\n"
	.string "Maybe you're a POKéMANIAC, too?\l"
	.string "Want to see my collection?$"
	.endif
	.ifdef SPANISH
	.string "Aquí estás otra vez...\n"
	.string "¿Eres como los POKéMANÍACOS?\l"
	.string "¿Quieres ver mi colección?$"
	.endif

Route10_Text_ClarkRematchIntro::
	.ifdef ENGLISH
	.string "Ha-hahah-ah-ha!\n"
	.string "I can't stop sneezing!$"
	.endif
	.ifdef SPANISH
	.string "¡A-a-a-achís!\n"
	.string "¡No puedo dejar de estornudar!$"
	.endif

Route10_Text_HermanRematchIntro::
	.ifdef ENGLISH
	.string "Hi, kid!\n"
	.string "Did I show you my POKéMON?$"
	.endif
	.ifdef SPANISH
	.string "¡Hola!\n"
	.string "¿Te llegué a enseñar mis POKéMON?$"
	.endif

Route10_Text_HeidiRematchIntro::
	.ifdef ENGLISH
	.string "I went out to a POKéMON GYM again.\p"
	.string "…But I lost as usual.$"
	.endif
	.ifdef SPANISH
	.string "He vuelto a ir al GIMNASIO\n"
	.string "POKéMON.\p"
	.string "Pero he perdido, como siempre...$"
	.endif

Route10_Text_TrentRematchIntro::
	.ifdef ENGLISH
	.string "Ah!\n"
	.string "This mountain air is delicious!\l"
	.string "It's so good, I can't leave!$"
	.endif
	.ifdef SPANISH
	.string "¡Me encanta el aire de montaña!\n"
	.string "¡Es tan bueno! ¡Me encanta!$"
	.endif

Route10_Text_CarolRematchIntro::
	.ifdef ENGLISH
	.string "My head is starting to spin.\n"
	.string "I've been hiking for too long…$"
	.endif
	.ifdef SPANISH
	.string "Me está empezando a dar vueltas la\n"
	.string "cabeza. Llevo mucho escalando...$"
	.endif

Route11_Text_HugoRematchIntro::
	.ifdef ENGLISH
	.string "Win, lose, or draw!\n"
	.string "Now for our rematch!$"
	.endif
	.ifdef SPANISH
	.string "¡Gana, pierde o empata!\n"
	.string "¡Pero lucha de nuevo!$"
	.endif

Route11_Text_JasperRematchIntro::
	.ifdef ENGLISH
	.string "Competing is the ultimate thrill.\n"
	.string "I still can't get enough!$"
	.endif
	.ifdef SPANISH
	.string "¡Competir es lo más!\n"
	.string "¡Yo no me canso de competir!$"
	.endif

Route11_Text_EddieRematchIntro::
	.ifdef ENGLISH
	.string "You know, right?\n"
	.string "Let's go, but don't cheat!$"
	.endif
	.ifdef SPANISH
	.string "¿Luchamos otra vez?\n"
	.string "¡Vamos allá, pero no hagas\l"
	.string "trampas!$"
	.endif

Route11_Text_BraxtonRematchIntro::
	.ifdef ENGLISH
	.string "Hi, there!\p"
	.string "But be careful!\n"
	.string "I'm still laying down some cables!$"
	.endif
	.ifdef SPANISH
	.string "¡Eh, tú!\p"
	.string "¡Cuidado!\n"
	.string "¡Estoy colocando unos cables!$"
	.endif

Route11_Text_DillonRematchIntro::
	.ifdef ENGLISH
	.string "I became a TRAINER a while ago.\n"
	.string "But, I think I can win.$"
	.endif
	.ifdef SPANISH
	.string "¡Soy un nuevo ENTRENADOR!\n"
	.string "¡Pero creo que no tengo problema\l"
	.string "para ganar!$"
	.endif

Route11_Text_DirkRematchIntro::
	.ifdef ENGLISH
	.string "Fwahaha!\n"
	.string "I have never lost!\p"
	.string "…And if I did, I've forgotten all\n"
	.string "about it!$"
	.endif
	.ifdef SPANISH
	.string "¡Ja, ja, ja!\n"
	.string "¡No he perdido nunca!\p"
	.string "¡Y si he perdido alguna vez,\n"
	.string "no me acuerdo!$"
	.endif

Route11_Text_DarianRematchIntro::
	.ifdef ENGLISH
	.string "I have never won before…\p"
	.string "Perhaps I am destined to remain\n"
	.string "that way…$"
	.endif
	.ifdef SPANISH
	.string "Nunca he ganado...\p"
	.string "¿Será mi destino?$"
	.endif

Route11_Text_YasuRematchIntro::
	.ifdef ENGLISH
	.string "I'm the best in my class.\n"
	.string "I train every morning and night!$"
	.endif
	.ifdef SPANISH
	.string "¡Soy el mejor de mi clase!\n"
	.string "¡Me entreno día y noche!$"
	.endif

Route11_Text_BernieRematchIntro::
	.ifdef ENGLISH
	.string "Keep your eyes out for live wires!$"
	.endif
	.ifdef SPANISH
	.string "¡Cuidado con esos cables!$"
	.endif

Route11_Text_DaveRematchIntro::
	.ifdef ENGLISH
	.string "I raised my POKéMON carefully.\n"
	.string "They should be ready by now.\l"
	.string "This time, they should win, too.$"
	.endif
	.ifdef SPANISH
	.string "¡Mis POKéMON ya deberían estar\n"
	.string "listos! ¡Esta vez hay que ganar!$"
	.endif

Route12_Text_NedRematchIntro::
	.ifdef ENGLISH
	.string "Yeah!\n"
	.string "I got a bite, here!\l"
	.string "Th-this might be the real thing!$"
	.endif
	.ifdef SPANISH
	.string "¡Bien!\n"
	.string "¡Ha picado algo!\l"
	.string "¡Esta vez seguro que es bueno!$"
	.endif

Route12_Text_ChipRematchIntro::
	.ifdef ENGLISH
	.string "You're finally here.\n"
	.string "Fishing is a waiting game.$"
	.endif
	.ifdef SPANISH
	.string "¡Aquí estás otra vez!\n"
	.string "¡Pescar requiere tiempo!$"
	.endif

Route12_Text_JustinRematchIntro::
	.ifdef ENGLISH
	.string "Still can't find a MOON STONE…\n"
	.string "Have you found one?$"
	.endif
	.ifdef SPANISH
	.string "Sigo sin PIEDRA LUNAR...\n"
	.string "¿Tienes tú una?$"
	.endif

Route12_Text_LucaRematchIntro::
	.ifdef ENGLISH
	.string "Electricity has always been my\n"
	.string "specialty.\p"
	.string "I don't know a thing about POKéMON\n"
	.string "of the sea, though.$"
	.endif
	.ifdef SPANISH
	.string "¡Soy un experto en electricidad!\p"
	.string "Pero de los POKéMON de agua\n"
	.string "sé poca cosa...$"
	.endif

Route12_Text_HankRematchIntro::
	.ifdef ENGLISH
	.string "The FISHING FOOL vs. POKéMON KID!\n"
	.string "Another round, fight!$"
	.endif
	.ifdef SPANISH
	.string "¡El PESCADOR LOCO contra alguien\n"
	.string "que no tiene idea sobre POKéMON!\l"
	.string "¡Lucha, venga!$"
	.endif

Route12_Text_ElliotRematchIntro::
	.ifdef ENGLISH
	.string "I love fishing, don't get me wrong.\n"
	.string "But, I wish I had more work…\l"
	.string "…It's hard to give up fishing!$"
	.endif
	.ifdef SPANISH
	.string "A mí me encanta pescar, pero no\n"
	.string "es nada fácil que piquen, ¿sabes?$"
	.endif

Route12_Text_AndrewRematchIntro::
	.ifdef ENGLISH
	.string "What's catching?\p"
	.string "You'll never know unless you beat\n"
	.string "me!$"
	.endif
	.ifdef SPANISH
	.string "¿No sabes cómo pescar?\p"
	.string "¡Te lo explicaré cuando acabe\n"
	.string "contigo!$"
	.endif

Route12_Text_JesRematchIntro::
	.ifdef ENGLISH
	.string "JES: I'll win here today and\n"
	.string "propose to my GIA.$"
	.endif
	.ifdef SPANISH
	.string "ARE: Voy a ganar y a pedirle a\n"
	.string "AGA que se case conmigo.$"
	.endif

Route12_Text_GiaRematchIntro::
	.ifdef ENGLISH
	.string "GIA: Hey, JES…\n"
	.string "I've been waiting a long time now.\p"
	.string "If we win today, I'll marry you!$"
	.endif
	.ifdef SPANISH
	.string "AGA: Oye, ARE, estoy aburrida\n"
	.string "de esperar...\p"
	.string "Si ganamos, ¡me caso contigo!$"
	.endif

Route13_Text_SebastianRematchIntro::
	.ifdef ENGLISH
	.string "My bird POKéMON remember you!$"
	.endif
	.ifdef SPANISH
	.string "¡Mis pájaros POKéMON se acuerdan\n"
	.string "de ti!$"
	.endif

Route13_Text_SusieRematchIntro::
	.ifdef ENGLISH
	.string "I want to be the best TRAINER \n"
	.string "while I'm a kid!$"
	.endif
	.ifdef SPANISH
	.string "Quiero ser la mejor ENTRENADORA\n"
	.string "siendo todavía pequeña.$"
	.endif

Route13_Text_ValerieRematchIntro::
	.ifdef ENGLISH
	.string "Wow!\n"
	.string "You got more cool BADGES!$"
	.endif
	.ifdef SPANISH
	.string "¡Guau!\n"
	.string "¡Qué chulas son tus MEDALLAS!$"
	.endif

Route13_Text_GwenRematchIntro::
	.ifdef ENGLISH
	.string "My cutely grown POKéMON wish to\n"
	.string "become reacquainted with you.$"
	.endif
	.ifdef SPANISH
	.string "Mis simpáticos POKéMON quieren\n"
	.string "volver a verte.$"
	.endif

Route13_Text_AlmaRematchIntro::
	.ifdef ENGLISH
	.string "I cleaned out my savings and\n"
	.string "bought more CARBOS.$"
	.endif
	.ifdef SPANISH
	.string "Me he gastado mis ahorros\n"
	.string "comprando más CARBURANTE.$"
	.endif

Route13_Text_PerryRematchIntro::
	.ifdef ENGLISH
	.string "I'm not going to lose this time.\n"
	.string "The wind's blowing my way!$"
	.endif
	.ifdef SPANISH
	.string "¡Esta vez no pienso perder!\n"
	.string "¡El viento sopla en mi dirección!$"
	.endif

Route13_Text_LolaRematchIntro::
	.ifdef ENGLISH
	.string "Oh, you're back?\p"
	.string "Sure, I'll play again with you,\n"
	.string "sweetie.$"
	.endif
	.ifdef SPANISH
	.string "Has vuelto...\p"
	.string "Por supuesto que lucharé\n"
	.string "otra vez contigo.$"
	.endif

Route13_Text_SheilaRematchIntro::
	.ifdef ENGLISH
	.string "Can't you forget that you battled\n"
	.string "with me?$"
	.endif
	.ifdef SPANISH
	.string "¿No te acuerdas de que luchamos\n"
	.string "en otra ocasión?$"
	.endif

Route13_Text_JaredRematchIntro::
	.ifdef ENGLISH
	.string "What're you starin' at?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué miras?$"
	.endif

Route13_Text_RobertRematchIntro::
	.ifdef ENGLISH
	.string "I always go with bird POKéMON.\n"
	.string "I've dedicated myself to them.$"
	.endif
	.ifdef SPANISH
	.string "¡Me encantan los pájaros POKéMON!\n"
	.string "¡Siempre me he dedicado a ellos!$"
	.endif

Route14_Text_CarterRematchIntro::
	.ifdef ENGLISH
	.string "I used TMs to teach good moves\n"
	.string "to my POKéMON.$"
	.endif
	.ifdef SPANISH
	.string "He usado mis MT para enseñarles\n"
	.string "buenos movimientos a mis POKéMON.$"
	.endif

Route14_Text_MitchRematchIntro::
	.ifdef ENGLISH
	.string "My bird POKéMON should be ready\n"
	.string "for battle this time.$"
	.endif
	.ifdef SPANISH
	.string "Mis pájaros POKéMON deberían\n"
	.string "luchar bien esta vez.$"
	.endif

Route14_Text_BeckRematchIntro::
	.ifdef ENGLISH
	.string "Are you using TMs on POKéMON?\n"
	.string "Just holding them is useless.$"
	.endif
	.ifdef SPANISH
	.string "¿Usas MT con tus POKéMON?\n"
	.string "Tenerlas en la MOCHILA sin más\l"
	.string "no sirve para nada.$"
	.endif

Route14_Text_MarlonRematchIntro::
	.ifdef ENGLISH
	.string "Have you taught your bird POKéMON\n"
	.string "how to FLY?\p"
	.string "You'll be able to soar with it into\n"
	.string "the sky! Give it a try.$"
	.endif
	.ifdef SPANISH
	.string "¿Has enseñado a VOLAR a tus\n"
	.string "pájaros POKéMON?\p"
	.string "Deberías hacerlo y disfrutar de\n"
	.string "la maravillosa vista.$"
	.endif

Route14_Text_DonaldRematchIntro::
	.ifdef ENGLISH
	.string "The legend of the winged mirages…\n"
	.string "You've heard it, right?$"
	.endif
	.ifdef SPANISH
	.string "¿Llegaste a oír hablar de los\n"
	.string "misteriosos seres alados?$"
	.endif

Route14_Text_BennyRematchIntro::
	.ifdef ENGLISH
	.string "I'm really not into it, but okay.\n"
	.string "Let's go!$"
	.endif
	.ifdef SPANISH
	.string "¡No me apetece luchar,\n"
	.string "pero lo haré!$"
	.endif

Route14_Text_LukasRematchIntro::
	.ifdef ENGLISH
	.string "Hey!\n"
	.string "I remember you!\p"
	.string "C'mon, c'mon.\n"
	.string "Let's go, let's go, let's go!$"
	.endif
	.ifdef SPANISH
	.string "¡Eh, me acuerdo de ti!\p"
	.string "¡Venga, venga!\n"
	.string "¡Vamos, vamos! ¡Adelante!$"
	.endif

Route14_Text_IsaacRematchIntro::
	.ifdef ENGLISH
	.string "You're here again, huh?\n"
	.string "Shut up and battle.$"
	.endif
	.ifdef SPANISH
	.string "Aquí estás otra vez, ¿eh?\n"
	.string "¡Bueno, así pasaré el rato!$"
	.endif

Route14_Text_GeraldRematchIntro::
	.ifdef ENGLISH
	.string "We've been riding here because of\n"
	.string "the wide-open spaces.$"
	.endif
	.ifdef SPANISH
	.string "¡Nos gusta pedalear por aquí\n"
	.string "porque hay mucho espacio!$"
	.endif

Route14_Text_MalikRematchIntro::
	.ifdef ENGLISH
	.string "POKéMON battle, right?\n"
	.string "Cool! Rumble!$"
	.endif
	.ifdef SPANISH
	.string "¿Quieres pelear con tus POKéMON?\n"
	.string "¡Pues vale, vamos allá!$"
	.endif

Route14_Text_KiriRematchIntro::
	.ifdef ENGLISH
	.string "KIRI: JAN, I hope we win today.$"
	.endif
	.ifdef SPANISH
	.string "LENA: TEA, a ver si ganamos.$"
	.endif

Route14_Text_JanRematchIntro::
	.ifdef ENGLISH
	.string "JAN: KIRI, here we go!\n"
	.string "Let's win for sure this time!$"
	.endif
	.ifdef SPANISH
	.string "TEA: LENA, ¡vamos allá!\n"
	.string "¡Tenemos que ganar!$"
	.endif

Route15_Text_KindraRematchIntro::
	.ifdef ENGLISH
	.string "I'm going to keep battling with the\n"
	.string "POKéMON I got in trades.$"
	.endif
	.ifdef SPANISH
	.string "¡Déjame probar los POKéMON\n"
	.string "que me han enviado!$"
	.endif

Route15_Text_BeckyRematchIntro::
	.ifdef ENGLISH
	.string "You look gentle, so I think I can\n"
	.string "beat you.\p"
	.string "I'll give it one more go!$"
	.endif
	.ifdef SPANISH
	.string "¡Creo que puedo contigo!\n"
	.string "¡Voy a intentar vencerte!$"
	.endif

Route15_Text_EdwinRematchIntro::
	.ifdef ENGLISH
	.string "When I whistle, bird POKéMON\n"
	.string "gather around.\p"
	.string "They're amazingly cute!$"
	.endif
	.ifdef SPANISH
	.string "Cuando silbo, acuden varios\n"
	.string "pájaros POKéMON.\p"
	.string "¡Son monísimos!$"
	.endif

Route15_Text_ChesterRematchIntro::
	.ifdef ENGLISH
	.string "Hmm? My birds are shivering!\n"
	.string "Wait, aren't you that TRAINER…$"
	.endif
	.ifdef SPANISH
	.string "Mis pájaros están temblando.\n"
	.string "¡Ya te conocen!$"
	.endif

Route15_Text_GraceRematchIntro::
	.ifdef ENGLISH
	.string "Oh, you're a little cutie!\n"
	.string "So like a darling POKéMON!\l"
	.string "I remember you now!$"
	.endif
	.ifdef SPANISH
	.string "¡Oh!\n"
	.string "¡Mira qué encanto!\l"
	.string "¡Anda, yo a ti te conozco!$"
	.endif

Route15_Text_OliviaRematchIntro::
	.ifdef ENGLISH
	.string "I raise POKéMON for protection\n"
	.string "because I live alone.\p"
	.string "That hasn't changed.$"
	.endif
	.ifdef SPANISH
	.string "¡Cuido POKéMON porque sigo\n"
	.string "viviendo sola!$"
	.endif

Route15_Text_ErnestRematchIntro::
	.ifdef ENGLISH
	.string "Hey, kid! C'mon!\n"
	.string "I got these off some loser!$"
	.endif
	.ifdef SPANISH
	.string "¡Oye! ¡Ven aquí!\n"
	.string "¡Mira esto!$"
	.endif

Route15_Text_AlexRematchIntro::
	.ifdef ENGLISH
	.string "Fork over all your cash when you\n"
	.string "lose to me, kid!$"
	.endif
	.ifdef SPANISH
	.string "¡Mira, colega, si pierdes contra\n"
	.string "mí, todo tu dinero será mío!$"
	.endif

Route15_Text_CeliaRematchIntro::
	.ifdef ENGLISH
	.string "What's cool and happening?\n"
	.string "Trading POKéMON, of course.$"
	.endif
	.ifdef SPANISH
	.string "¿Qué mola?\n"
	.string "¡Cambiar POKéMON, claro!$"
	.endif

Route15_Text_YazminRematchIntro::
	.ifdef ENGLISH
	.string "Want to play with my POKéMON\n"
	.string "again?$"
	.endif
	.ifdef SPANISH
	.string "¿Quieres jugar con mis POKéMON\n"
	.string "otra vez?$"
	.endif

Route15_Text_MyaRematchIntro::
	.ifdef ENGLISH
	.string "MYA: Hi, we keep meeting,\n"
	.string "don't we?\p"
	.string "Help me train my little brother\n"
	.string "again?$"
	.endif
	.ifdef SPANISH
	.string "TINA: ¡Volvemos a vernos!\p"
	.string "¿Luchamos para que aprenda\n"
	.string "mi hermano?$"
	.endif

Route15_Text_RonRematchIntro::
	.ifdef ENGLISH
	.string "RON: My sister's gotten more\n"
	.string "powerful…$"
	.endif
	.ifdef SPANISH
	.string "TIN: Mi hermana es la más fuerte.$"
	.endif

Route16_Text_LaoRematchIntro::
	.ifdef ENGLISH
	.string "What do you want?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué quieres?$"
	.endif

Route16_Text_KojiRematchIntro::
	.ifdef ENGLISH
	.string "Nice BIKE!\n"
	.string "Hand it over quick!$"
	.endif
	.ifdef SPANISH
	.string "¡Bonita BICI!\n"
	.string "¡Dámela ahora mismo!$"
	.endif

Route16_Text_LukeRematchIntro::
	.ifdef ENGLISH
	.string "Come out and play, little mouse.\n"
	.string "I'll treat you right!$"
	.endif
	.ifdef SPANISH
	.string "¡Baja de ahí y lucha, enclenque!\n"
	.string "¡Te vas a enterar!$"
	.endif

Route16_Text_HideoRematchIntro::
	.ifdef ENGLISH
	.string "Hey, wait a second!\n"
	.string "Don't call me and then run away!$"
	.endif
	.ifdef SPANISH
	.string "¡Oye! ¡Me has golpeado!\n"
	.string "¡Ahora tendrás que luchar conmigo!$"
	.endif

Route16_Text_CamronRematchIntro::
	.ifdef ENGLISH
	.string "I'm feeling hungry and mean!\n"
	.string "I really need a punching bag!$"
	.endif
	.ifdef SPANISH
	.string "¡Tengo hambre y sigo sin estar\n"
	.string "de humor!$"
	.endif

Route16_Text_RubenRematchIntro::
	.ifdef ENGLISH
	.string "Hey, there!\n"
	.string "We'll have ourselves a good time!$"
	.endif
	.ifdef SPANISH
	.string "¡Eh, vamos a echar otro rato!$"
	.endif

Route16_Text_JedRematchIntro::
	.ifdef ENGLISH
	.string "JED: Are you here to see our\n"
	.string "love, which knows no bounds?$"
	.endif
	.ifdef SPANISH
	.string "JOEL: ¿Vienes para comprobar que\n"
	.string "nuestro amor no conoce límites?$"
	.endif

Route16_Text_LeaRematchIntro::
	.ifdef ENGLISH
	.string "LEA: Sometimes, the intensity of\n"
	.string "our love scares me.$"
	.endif
	.ifdef SPANISH
	.string "LIZ: ¡A veces, pienso en todo\n"
	.string "lo que nos queremos y se me pone\l"
	.string "la carne de gallina!$"
	.endif

Route17_Text_RaulRematchIntro::
	.ifdef ENGLISH
	.string "I told you, there's no getting rich\n"
	.string "quick in battling kids.$"
	.endif
	.ifdef SPANISH
	.string "¡Ya te dije que no compensaba\n"
	.string "luchar con niños!$"
	.endif

Route17_Text_IsaiahRematchIntro::
	.ifdef ENGLISH
	.string "I'm mighty proud of my bod, kiddo.\n"
	.string "Come on!$"
	.endif
	.ifdef SPANISH
	.string "¿Y tú qué quieres?$"
	.endif

Route17_Text_VirgilRematchIntro::
	.ifdef ENGLISH
	.string "You out for a stroll?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué vas, de paseo?$"
	.endif

Route17_Text_BillyRematchIntro::
	.ifdef ENGLISH
	.string "We're BIKERS!\n"
	.string "We rule the roads, man!$"
	.endif
	.ifdef SPANISH
	.string "¡Somos los MOTORISTAS!\n"
	.string "¡Las estrellas de la autopista!$"
	.endif

Route17_Text_NikolasRematchIntro::
	.ifdef ENGLISH
	.string "VOLTORB's going to seriously\n"
	.string "electrify you today!$"
	.endif
	.ifdef SPANISH
	.string "Mis VOLTORB van a darte\n"
	.string "un calambrazo.$"
	.endif

Route17_Text_ZeekRematchIntro::
	.ifdef ENGLISH
	.string "I leveled up my POKéMON, but it\n"
	.string "absolutely won't evolve. Why?$"
	.endif
	.ifdef SPANISH
	.string "¡Mi POKéMON no evoluciona!\n"
	.string "No acabo de entender por qué.$"
	.endif

Route17_Text_JamalRematchIntro::
	.ifdef ENGLISH
	.string "Gaah! I really need to exercise\n"
	.string "and seriously trim some flab!$"
	.endif
	.ifdef SPANISH
	.string "¡Necesito un poco de ejercicio\n"
	.string "y bajar peso!$"
	.endif

Route17_Text_CoreyRematchIntro::
	.ifdef ENGLISH
	.string "Be a rebel!$"
	.endif
	.ifdef SPANISH
	.string "¡Sé rebelde!$"
	.endif

Route17_Text_JaxonRematchIntro::
	.ifdef ENGLISH
	.string "Yep, that's a nice BIKE!\n"
	.string "How's it handle?$"
	.endif
	.ifdef SPANISH
	.string "¡Tienes una BICI muy guay!\n"
	.string "¿Cómo se conduce?$"
	.endif

Route17_Text_WilliamRematchIntro::
	.ifdef ENGLISH
	.string "Get lost, kid!\n"
	.string "I'm bushed!$"
	.endif
	.ifdef SPANISH
	.string "¡Lárgate!\n"
	.string "¡Estoy agotado!$"
	.endif

Route18_Text_WiltonRematchIntro::
	.ifdef ENGLISH
	.string "I've been checking every grassy\n"
	.string "area for new POKéMON.\p"
	.string "But it's not always easy…$"
	.endif
	.ifdef SPANISH
	.string "Compruebo siempre las zonas de\n"
	.string "hierba en busca de nuevos POKéMON.\p"
	.string "Pero no siempre encuentro...$"
	.endif

Route18_Text_RamiroRematchIntro::
	.ifdef ENGLISH
	.string "Koorukukukoo!\n"
	.string "Is my birdcall getting better?$"
	.endif
	.ifdef SPANISH
	.string "¡Cucu, cucu! ¿Ha mejorado\n"
	.string "el reclamo de mi pájaro?$"
	.endif

Route18_Text_JacobRematchIntro::
	.ifdef ENGLISH
	.string "I warned you before, this is my\n"
	.string "turf!\p"
	.string "I don't want you coming around.$"
	.endif
	.ifdef SPANISH
	.string "¡Es mi césped!\n"
	.string "¡Fuera de aquí!\p"
	.string "¡No quiero volver a verte por\n"
	.string "aquí!$"
	.endif

Route19_Text_RichardRematchIntro::
	.ifdef ENGLISH
	.string "I'm almost warmed up to go\n"
	.string "out for a swim.$"
	.endif
	.ifdef SPANISH
	.string "Estaba a punto de darme un baño.$"
	.endif

Route19_Text_ReeceRematchIntro::
	.ifdef ENGLISH
	.string "Wait! Slow down!\n"
	.string "What if you have a heart attack?$"
	.endif
	.ifdef SPANISH
	.string "¡Alto!\n"
	.string "¡Oye, que te va a dar algo!$"
	.endif

Route19_Text_MatthewRematchIntro::
	.ifdef ENGLISH
	.string "I love swimming!\n"
	.string "I guess you're the surfing type.$"
	.endif
	.ifdef SPANISH
	.string "¡Me gusta nadar!\n"
	.string "Seguro que a ti también.$"
	.endif

Route19_Text_DouglasRematchIntro::
	.ifdef ENGLISH
	.string "What's beyond the horizon?\n"
	.string "Have you seen?$"
	.endif
	.ifdef SPANISH
	.string "¿Qué hay más allá del horizonte?\n"
	.string "¿Lo sabes?$"
	.endif

Route19_Text_DavidRematchIntro::
	.ifdef ENGLISH
	.string "I tried diving for POKéMON again,\n"
	.string "but it was a no-go like before.$"
	.endif
	.ifdef SPANISH
	.string "¡He buceado en busca de POKéMON,\n"
	.string "pero sigo sin ver nada!$"
	.endif

Route19_Text_TonyRematchIntro::
	.ifdef ENGLISH
	.string "I look at the sea to forget all\n"
	.string "the bad things that happened.\p"
	.string "…Like losing to you the last time!$"
	.endif
	.ifdef SPANISH
	.string "¡Miro al mar para olvidar!\p"
	.string "Quiero olvidarme de cuando perdí\n"
	.string "contigo.$"
	.endif

Route19_Text_AnyaRematchIntro::
	.ifdef ENGLISH
	.string "You always get to ride your\n"
	.string "POKéMON…\p"
	.string "It looks so relaxing.\n"
	.string "Can I have it if I win?$"
	.endif
	.ifdef SPANISH
	.string "¡Me encanta el POKéMON con\n"
	.string "el que estás haciendo SURF.\p"
	.string "¿Me lo darás si gano?$"
	.endif

Route19_Text_AliceRematchIntro::
	.ifdef ENGLISH
	.string "Swimming's great!\n"
	.string "Sunburns aren't!$"
	.endif
	.ifdef SPANISH
	.string "¡Nadar es genial! ¡Pero no me\n"
	.string "gusta quemarme al sol!$"
	.endif

Route19_Text_AxleRematchIntro::
	.ifdef ENGLISH
	.string "These waters are treacherous!\n"
	.string "You shouldn't come back here!$"
	.endif
	.ifdef SPANISH
	.string "¡Estas aguas son traicioneras!\n"
	.string "¡No deberías volver por aquí!$"
	.endif

Route19_Text_ConnieRematchIntro::
	.ifdef ENGLISH
	.string "I swam here with my friends…\n"
	.string "I'm tired…\l"
	.string "Must we really battle again?$"
	.endif
	.ifdef SPANISH
	.string "He venido nadando hasta aquí,\n"
	.string "pero ya me he cansado.\p"
	.string "¿De verdad tenemos que luchar\n"
	.string "otra vez?$"
	.endif

Route19_Text_LiaRematchIntro::
	.ifdef ENGLISH
	.string "LIA: You know my brother just\n"
	.string "became a TRAINER, right?\p"
	.string "I want to make him better, so I\n"
	.string "need your help again.$"
	.endif
	.ifdef SPANISH
	.string "CATI: Ya sabes que mi hermano\n"
	.string "acaba de hacerse ENTRENADOR.\p"
	.string "Vamos a luchar para que mejore\n"
	.string "su técnica, ¿vale?$"
	.endif

Route19_Text_LucRematchIntro::
	.ifdef ENGLISH
	.string "LUC: My big sis taught me all\n"
	.string "about POKéMON.\p"
	.string "I wonder if I'm better?$"
	.endif
	.ifdef SPANISH
	.string "TEC: Mi hermana mayor me ha\n"
	.string "enseñado mucho sobre POKéMON.\p"
	.string "¿Soy mejor ahora?$"
	.endif

Route20_Text_BarryRematchIntro::
	.ifdef ENGLISH
	.string "The water is shallow here.\n"
	.string "There are many people swimming.$"
	.endif
	.ifdef SPANISH
	.string "El agua es poco profunda aquí.$"
	.endif

Route20_Text_ShirleyRematchIntro::
	.ifdef ENGLISH
	.string "Are you jealous that I'm\n"
	.string "vacationing on SEAFOAM?$"
	.endif
	.ifdef SPANISH
	.string "¿Te da envidia que esté de\n"
	.string "vacaciones en las ISLAS ESPUMA?$"
	.endif

Route20_Text_TiffanyRematchIntro::
	.ifdef ENGLISH
	.string "I love floating with the fishes\n"
	.string "here among the waves.$"
	.endif
	.ifdef SPANISH
	.string "¡Me gusta flotar en el agua\n"
	.string "rodeada de peces!$"
	.endif

Route20_Text_IreneRematchIntro::
	.ifdef ENGLISH
	.string "Were you on vacation, too?$"
	.endif
	.ifdef SPANISH
	.string "¿Tú también estabas de vacaciones?$"
	.endif

Route20_Text_DeanRematchIntro::
	.ifdef ENGLISH
	.string "Check out my physique!\p"
	.string "It's even more buff than ever\n"
	.string "before!$"
	.endif
	.ifdef SPANISH
	.string "¡Mira que cuerpazo tengo!\p"
	.string "¡Estoy mejor que antes!$"
	.endif

Route20_Text_DarrinRematchIntro::
	.ifdef ENGLISH
	.string "Why are you riding a POKéMON?\n"
	.string "Haven't you learned to swim yet?$"
	.endif
	.ifdef SPANISH
	.string "¿Por qué te has subido a un\n"
	.string "POKéMON? ¿Aún no sabes nadar?$"
	.endif

Route20_Text_RogerRematchIntro::
	.ifdef ENGLISH
	.string "I rode my bird POKéMON here.$"
	.endif
	.ifdef SPANISH
	.string "¡Ha venido sobre uno de mis\n"
	.string "pájaros POKéMON!$"
	.endif

Route20_Text_NoraRematchIntro::
	.ifdef ENGLISH
	.string "My boyfriend gave me big pearls.\n"
	.string "And, they've grown bigger!$"
	.endif
	.ifdef SPANISH
	.string "¡Mi novio me dio unas perlas\n"
	.string "muy grandes!\p"
	.string "¡Y ahora están más grandes aún!$"
	.endif

Route20_Text_MissyRematchIntro::
	.ifdef ENGLISH
	.string "I swam here from CINNABAR ISLAND.\n"
	.string "It wasn't easy, like I said.$"
	.endif
	.ifdef SPANISH
	.string "Vine nadando desde ISLA\n"
	.string "CANELA. Fue agotador.$"
	.endif

Route20_Text_MelissaRematchIntro::
	.ifdef ENGLISH
	.string "CINNABAR, in the west, has a LAB\n"
	.string "for POKéMON.\p"
	.string "My daddy works there.$"
	.endif
	.ifdef SPANISH
	.string "En ISLA CANELA, al oeste, hay\n"
	.string "un LABORATORIO POKéMON.\p"
	.string "Mi padre trabaja allí.$"
	.endif

Route21_North_Text_RonaldRematchIntro::
	.ifdef ENGLISH
	.string "You want to know if the fish are\n"
	.string "biting?$"
	.endif
	.ifdef SPANISH
	.string "¿Quieres saber si los peces pican?$"
	.endif

Route21_North_Text_WadeRematchIntro::
	.ifdef ENGLISH
	.string "I got a big haul again!\n"
	.string "Wanna go for it once more?$"
	.endif
	.ifdef SPANISH
	.string "¡Tengo una gran red!\n"
	.string "¿Quieres probarla otra vez?$"
	.endif

Route21_North_Text_SpencerRematchIntro::
	.ifdef ENGLISH
	.string "The sea cleanses my body and soul!$"
	.endif
	.ifdef SPANISH
	.string "¡El mar limpia mi cuerpo y mi\n"
	.string "alma!$"
	.endif

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro::
	.string "きょうも　およぎに\n"
	.string "きちまったぜ$"

Route21_South_Text_JackRematchIntro::
	.ifdef ENGLISH
	.string "I caught my POKéMON at sea.\n"
	.string "And that's where I train them.$"
	.endif
	.ifdef SPANISH
	.string "¡He conseguido a mi POKéMON\n"
	.string "en el mar, y aquí lo entreno!$"
	.endif

Route21_South_Text_JeromeRematchIntro::
	.ifdef ENGLISH
	.string "Right now, I'm in another triathlon\n"
	.string "meet!$"
	.endif
	.ifdef SPANISH
	.string "¡Ahora estoy en otro encuentro\n"
	.string "de triatlón!$"
	.endif

Route21_South_Text_RolandRematchIntro::
	.ifdef ENGLISH
	.string "Ahh!\n"
	.string "Feel the sun and the wind!$"
	.endif
	.ifdef SPANISH
	.string "¡Ah!\n"
	.string "¡Siente el sol y el viento!$"
	.endif

Route21_South_Text_ClaudeRematchIntro::
	.ifdef ENGLISH
	.string "Hey, cut it out already.\n"
	.string "You always scare away the fish!$"
	.endif
	.ifdef SPANISH
	.string "¡Eh!\n"
	.string "¡Siempre asustas a los peces!$"
	.endif

Route21_South_Text_NolanRematchIntro::
	.ifdef ENGLISH
	.string "Keep me company till I get a hit.$"
	.endif
	.ifdef SPANISH
	.string "¡Quédate conmigo hasta que lo\n"
	.string "consiga!$"
	.endif

Route21_North_Text_LilRematchIntro::
	.ifdef ENGLISH
	.string "LIL: Huh? A battle again?\n"
	.string "IAN, can't you do it alone?$"
	.endif
	.ifdef SPANISH
	.string "ÍA: ¿Cómo, que quieres luchar otra\n"
	.string "vez? IGOR, ¿cómo lo ves?$"
	.endif

Route21_North_Text_IanRematchIntro::
	.ifdef ENGLISH
	.string "IAN: My sis is still a slob.\n"
	.string "Help me get her into shape!$"
	.endif
	.ifdef SPANISH
	.string "IGOR: Mi hermana es un pelín vaga,\n"
	.string "¡pero si hay que luchar, hay que\l"
	.string "luchar!$"
	.endif

Route25_Text_JoeyRematchIntro::
	.ifdef ENGLISH
	.string "I won't lose while I'm here!$"
	.endif
	.ifdef SPANISH
	.string "¡No pienso perder!$"
	.endif

Route25_Text_DanRematchIntro::
	.ifdef ENGLISH
	.string "Dad took me to a great party on\n"
	.string "the S.S. ANNE at VERMILION CITY.$"
	.endif
	.ifdef SPANISH
	.string "¡Mi padre me llevó a una gran\n"
	.string "fiesta en el S.S. ANNE, en\l"
	.string "CIUDAD CARMÍN!$"
	.endif

Route25_Text_FlintRematchIntro::
	.ifdef ENGLISH
	.string "I'm a cool guy.\n"
	.string "I've got a girlfriend!\p"
	.string "I'll show her how cool I am for\n"
	.string "sure this time!$"
	.endif
	.ifdef SPANISH
	.string "Soy un buen chico.\n"
	.string "¡Y tengo novia!\p"
	.string "¡Verás cómo se queda cuando\n"
	.string "me vea luchar esta vez!$"
	.endif

Route25_Text_KelseyRematchIntro::
	.ifdef ENGLISH
	.string "Hi!\n"
	.string "My boyfriend is cool!\l"
	.string "My conditioning's good today!$"
	.endif
	.ifdef SPANISH
	.string "¡Hola!\n"
	.string "¡Mi chico es genial!\l"
	.string "¡Y hoy me encuentro en forma!$"
	.endif

Route25_Text_ChadRematchIntro::
	.ifdef ENGLISH
	.string "I had this feeling…\n"
	.string "I knew I had to battle you again!$"
	.endif
	.ifdef SPANISH
	.string "¡Sabía que tendría que luchar\n"
	.string "contigo otra vez!$"
	.endif

Route25_Text_HaleyRematchIntro::
	.ifdef ENGLISH
	.string "My friend has many cute POKéMON.\n"
	.string "I'm so jealous!$"
	.endif
	.ifdef SPANISH
	.string "Mi amigo tiene POKéMON muy\n"
	.string "monos. ¡Qué envidia!$"
	.endif

Route25_Text_FranklinRematchIntro::
	.ifdef ENGLISH
	.string "I just trained up on MT. MOON,\n"
	.string "but I've still got gas in the tank!$"
	.endif
	.ifdef SPANISH
	.string "¡Acabo de bajar del MT. MOON,\n"
	.string "pero estoy listo!$"
	.endif

Route25_Text_NobRematchIntro::
	.ifdef ENGLISH
	.string "A POKéMANIAC lives on the cape.\n"
	.string "Have you seen his collection?$"
	.endif
	.ifdef SPANISH
	.string "¡Hay un POKéMANÍACO viviendo\n"
	.string "en el cabo!\p"
	.string "¿Has visto la colección que tiene?$"
	.endif

Route25_Text_WayneRematchIntro::
	.ifdef ENGLISH
	.string "You're going to see BILL again?\n"
	.string "First, we battle!$"
	.endif
	.ifdef SPANISH
	.string "¿Vas a ver a BILL otra vez?\n"
	.string "¡Pues luchemos primero!$"
	.endif

Route24_Text_ShaneRematchIntro::
	.ifdef ENGLISH
	.string "I saw your feat from the grass!$"
	.endif
	.ifdef SPANISH
	.string "¡Vi tu hazaña desde la hierba!$"
	.endif

Route24_Text_EthanRematchIntro::
	.ifdef ENGLISH
	.string "Okay!\n"
	.string "I'll stomp you!$"
	.endif
	.ifdef SPANISH
	.string "¡Muy bien, voy a acabar contigo!$"
	.endif

Route24_Text_ReliRematchIntro::
	.ifdef ENGLISH
	.string "You always look so busy…\n"
	.string "Aren't you getting tired?$"
	.endif
	.ifdef SPANISH
	.string "Siempre estás de aquí para allá...\n"
	.string "¿No te cansas?$"
	.endif

Route24_Text_TimmyRematchIntro::
	.ifdef ENGLISH
	.string "You really must love coming to\n"
	.string "NUGGET BRIDGE.$"
	.endif
	.ifdef SPANISH
	.string "Se ve que te encanta venir\n"
	.string "al PUENTE PEPITA.$"
	.endif

Route24_Text_AliRematchIntro::
	.ifdef ENGLISH
	.string "The time we battled…\p"
	.string "Even though I was the second in\n"
	.string "line, I was the best, wasn't I?$"
	.endif
	.ifdef SPANISH
	.string "Aunque perdí cuando luchamos,\n"
	.string "estuvo guay, ¿verdad?$"
	.endif

Route24_Text_CaleRematchIntro::
	.ifdef ENGLISH
	.string "People call this the NUGGET\n"
	.string "BRIDGE!\p"
	.string "You've already beaten us, so you're\n"
	.string "not allowed to take the challenge…\p"
	.string "…But, you're welcome to battle with\n"
	.string "us again.$"
	.endif
	.ifdef SPANISH
	.string "Éste es el PUENTE PEPITA.\p"
	.string "Ya nos has machacado a todos,\n"
	.string "así que ya te puedes marchar...\p"
	.string "Aunque... no me importaría\n"
	.string "volver a enfrentarme a ti.$"
	.endif

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
	.ifdef ENGLISH
	.string "Lying back, rocked by the waves…\n"
	.string "I don't notice time slipping by…$"
	.endif
	.ifdef SPANISH
	.string "Se me pasa el tiempo volando\n"
	.string "cuando estoy disfrutando del agua,\l"
	.string "del vaivén de las olas...$"
	.endif

OneIsland_KindleRoad_Text_MariaRematchIntro::
	.ifdef ENGLISH
	.string "The weather's gorgeous!\n"
	.string "I'll try not to spoil it.$"
	.endif
	.ifdef SPANISH
	.string "Hace un tiempo espléndido,\n"
	.string "no lo estropees.$"
	.endif

OneIsland_KindleRoad_Text_AbigailRematchIntro::
	.ifdef ENGLISH
	.string "My sunburn is starting to hurt…$"
	.endif
	.ifdef SPANISH
	.string "Está empezando a dolerme la piel\n"
	.string "por las quemaduras.$"
	.endif

OneIsland_KindleRoad_Text_FinnRematchIntro::
	.ifdef ENGLISH
	.string "The fire bird's mountain casts\n"
	.string "a huge shadow…$"
	.endif
	.ifdef SPANISH
	.string "El MT. ASCUAS hace una sombra\n"
	.string "gigante.$"
	.endif

OneIsland_KindleRoad_Text_GarrettRematchIntro::
	.ifdef ENGLISH
	.string "I have this strong feeling that\n"
	.string "I can win this time!$"
	.endif
	.ifdef SPANISH
	.string "Tengo la sensación de que esta vez\n"
	.string "te voy a ganar.$"
	.endif

OneIsland_KindleRoad_Text_TommyRematchIntro::
	.ifdef ENGLISH
	.string "Wait! Wait a second!\n"
	.string "I'm sure I've hooked a big one!$"
	.endif
	.ifdef SPANISH
	.string "¡Eh, eh, un momento!\n"
	.string "¡Sé que he pescado algo grande!$"
	.endif

OneIsland_KindleRoad_Text_SharonRematchIntro::
	.ifdef ENGLISH
	.string "You'll help me out with my\n"
	.string "training again?$"
	.endif
	.ifdef SPANISH
	.string "¿Me ayudas a entrenarme otra vez?$"
	.endif

OneIsland_KindleRoad_Text_TanyaRematchIntro::
	.ifdef ENGLISH
	.string "We haven't missed a single day of\n"
	.string "training yet!$"
	.endif
	.ifdef SPANISH
	.string "No me pierdo ni un día de\n"
	.string "entrenamiento.$"
	.endif

OneIsland_KindleRoad_Text_SheaRematchIntro::
	.ifdef ENGLISH
	.string "Every morning, before breakfast,\n"
	.string "I swim around this island…\l"
	.string "Three times!$"
	.endif
	.ifdef SPANISH
	.string "Cada mañana, antes de desayunar,\n"
	.string "rodeo a nado la isla.\l"
	.string "¡Lo hago hasta tres veces!$"
	.endif

OneIsland_KindleRoad_Text_HughRematchIntro::
	.ifdef ENGLISH
	.string "Dress appropriately for battle!\n"
	.string "Lose that frivolous outfit, I said!$"
	.endif
	.ifdef SPANISH
	.string "¡Para luchar hay que llevar ropa\n"
	.string "adecuada! ¡Vaya pintas tienes!$"
	.endif

OneIsland_KindleRoad_Text_BryceRematchIntro::
	.ifdef ENGLISH
	.string "You know, everything tastes great\n"
	.string "when you're out in the wild.$"
	.endif
	.ifdef SPANISH
	.string "Cuando se está al aire libre, todo\n"
	.string "sabe mejor.$"
	.endif

OneIsland_KindleRoad_Text_ClaireRematchIntro::
	.ifdef ENGLISH
	.string "I ate too much again, so will you\n"
	.string "battle us for some exercise?$"
	.endif
	.ifdef SPANISH
	.string "He vuelto a comer demasiado,\n"
	.string "¿luchamos para hacer algo\l"
	.string "de ejercicio?$"
	.endif

OneIsland_KindleRoad_Text_KiaRematchIntro::
	.ifdef ENGLISH
	.string "KIA: My big brother and I make\n"
	.string "an awesome combination!\p"
	.string "We won't lose this time!$"
	.endif
	.ifdef SPANISH
	.string "PÍA: ¡Mi hermano mayor y yo\n"
	.string "hacemos un equipo increíble!\p"
	.string "¡Esta vez no perderemos!$"
	.endif

OneIsland_KindleRoad_Text_MikRematchIntro::
	.ifdef ENGLISH
	.string "MIK: Together with KIA, we're\n"
	.string "afraid of nothing!\p"
	.string "We'll prove it to you this time!$"
	.endif
	.ifdef SPANISH
	.string "FER: ¡Junto a PÍA no tengo miedo\n"
	.string "de nada!\p"
	.string "¡Esta vez te vas a enterar!$"
	.endif

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
	.ifdef ENGLISH
	.string "Are we to battle again?$"
	.endif
	.ifdef SPANISH
	.string "¿Quieres que luchemos de nuevo?$"
	.endif

ThreeIsland_BondBridge_Text_VioletRematchIntro::
	.ifdef ENGLISH
	.string "From where have you come, and\n"
	.string "where are you bound?$"
	.endif
	.ifdef SPANISH
	.string "¿De dónde vienes y adónde vas?$"
	.endif

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
	.ifdef ENGLISH
	.string "I want to swim without my float\n"
	.string "ring soon.$"
	.endif
	.ifdef SPANISH
	.string "Estoy deseando nadar sin flotador.$"
	.endif

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
	.ifdef ENGLISH
	.string "Yay, yay!\n"
	.string "POKéMON!$"
	.endif
	.ifdef SPANISH
	.string "¡POKéMON, POKéMON!\n"
	.string "¡A mí me gustan los POKéMON!$"
	.endif

ThreeIsland_BondBridge_Text_TishaRematchIntro::
	.ifdef ENGLISH
	.string "Oh, no, didn't I tell you already?\n"
	.string "Please, stay away from me!$"
	.endif
	.ifdef SPANISH
	.string "¡No, no, te dije que me dejaras\n"
	.string "en paz!$"
	.endif

ThreeIsland_BondBridge_Text_JoyRematchIntro::
	.ifdef ENGLISH
	.string "JOY: We've gotten stronger!\n"
	.string "Lots and lots!$"
	.endif
	.ifdef SPANISH
	.string "FELI: Ahora somos más fuertes.\n"
	.string "¡Mucho más!$"
	.endif

ThreeIsland_BondBridge_Text_MegRematchIntro::
	.ifdef ENGLISH
	.string "MEG: You can't beat us today!$"
	.endif
	.ifdef SPANISH
	.string "MATI: ¡Hoy no podrás con nosotras!$"
	.endif

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
	.ifdef ENGLISH
	.string "Oh, hello!\p"
	.string "Are you raising your POKéMON in a\n"
	.string "good environment?$"
	.endif
	.ifdef SPANISH
	.string "Hola, ¿estás criando tus POKéMON\n"
	.string "en un buen sitio?$"
	.endif

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
	.ifdef ENGLISH
	.string "With these hands, I will create\n"
	.string "my victory today.$"
	.endif
	.ifdef SPANISH
	.string "¡Voy a alcanzar la victoria con mis\n"
	.string "propias manos!$"
	.endif

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
	.ifdef ENGLISH
	.string "Must I repeat myself?\n"
	.string "I'm trying to paint.\l"
	.string "Please keep out of my sight!$"
	.endif
	.ifdef SPANISH
	.string "¿Cuántas veces tengo que\n"
	.string "decírtelo? ¡Estoy intentando\l"
	.string "pintar! ¿Te quieres quitar de ahí?$"
	.endif

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
	.ifdef ENGLISH
	.string "I haven't made any progress…\n"
	.string "I still can't get the right angle…$"
	.endif
	.ifdef SPANISH
	.string "No he avanzado nada...\n"
	.string "No acabo de encontrar el ángulo\l"
	.string "adecuado.$"
	.endif

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
	.ifdef ENGLISH
	.string "Oh, you will give me another\n"
	.string "opportunity to match wits with you?$"
	.endif
	.ifdef SPANISH
	.string "¿Vas a darme otra oportunidad\n"
	.string "para medir mis habilidades contigo?$"
	.endif

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
	.ifdef ENGLISH
	.string "They're almost finished making the\n"
	.string "pool for my POKéMON.\p"
	.string "You must drop in for a visit.$"
	.endif
	.ifdef SPANISH
	.string "Ya está casi acabada la piscina\n"
	.string "de mis POKéMON.\p"
	.string "Deberías pasarte para echarle\n"
	.string "un vistazo.$"
	.endif

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
	.ifdef ENGLISH
	.string "I'm a good runner.\n"
	.string "I've gotten even faster!$"
	.endif
	.ifdef SPANISH
	.string "No hay nadie que corra más rápido\n"
	.string "que yo.$"
	.endif

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
	.ifdef ENGLISH
	.string "I say, friend!\n"
	.string "Let us enjoy our time together!$"
	.endif
	.ifdef SPANISH
	.string "¡Eh, vamos a pasar un buen rato\n"
	.string "luchando!$"
	.endif

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
	.ifdef ENGLISH
	.string "I'm the eldest of the BIRD\n"
	.string "BROTHERS. Remember me?\p"
	.string "That's right, I'm the one who loves\n"
	.string "birds for their beaks!$"
	.endif
	.ifdef SPANISH
	.string "Soy el mayor de los HERMANOS\n"
	.string "PÁJARO.\p"
	.string "Al que le encantaban los pájaros\n"
	.string "por los picos que tienen.$"
	.endif

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
	.ifdef ENGLISH
	.string "I'm the middle kid of the BIRD\n"
	.string "BROTHERS.\p"
	.string "I'm the one that loves wings.\n"
	.string "Let's battle again!$"
	.endif
	.ifdef SPANISH
	.string "Soy el mediano de los HERMANOS\n"
	.string "PÁJARO.\p"
	.string "Al que le encantaban los pájaros\n"
	.string "por las alas que tienen.$"
	.endif

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
	.ifdef ENGLISH
	.string "I'm the youngest of the BIRD\n"
	.string "BROTHERS.\p"
	.string "I love birds for their down.\n"
	.string "I didn't think I'd see you again!$"
	.endif
	.ifdef SPANISH
	.string "Soy el pequeño de los HERMANOS\n"
	.string "PÁJARO.\p"
	.string "Al que le encantaban los pájaros\n"
	.string "por las plumas que tienen.$"
	.endif

SixIsland_OutcastIsland_Text_TylorRematchIntro::
	.ifdef ENGLISH
	.string "I'm still having no luck at all.\n"
	.string "A battle'd be a change of pace!$"
	.endif
	.ifdef SPANISH
	.string "Sigo sin tener suerte...\n"
	.string "¡A ver si luchando contigo entro\l"
	.string "en una buena racha!$"
	.endif

SixIsland_OutcastIsland_Text_MymoRematchIntro::
	.ifdef ENGLISH
	.string "Gasp… Gasp…\p"
	.string "I swam here from SIX ISLAND's port\n"
	.string "in one go again.$"
	.endif
	.ifdef SPANISH
	.string "Ufff... Ufff...\p"
	.string "Vengo nadando otra vez desde\n"
	.string "el PUERTO de ISLA EXTA sin parar.$"
	.endif

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
	.ifdef ENGLISH
	.string "You always come along while I'm\n"
	.string "swimming.$"
	.endif
	.ifdef SPANISH
	.string "Siempre apareces cuando estoy\n"
	.string "dándome un baño.$"
	.endif

SixIsland_OutcastIsland_Text_AvaRematchIntro::
	.ifdef ENGLISH
	.string "AVA: Let's have another\n"
	.string "two-on-two marine battle today!$"
	.endif
	.ifdef SPANISH
	.string "ALI: ¡Vamos a echarnos otro\n"
	.string "combate disfrutando de la brisa\l"
	.string "marina!$"
	.endif

SixIsland_OutcastIsland_Text_GebRematchIntro::
	.ifdef ENGLISH
	.string "GEB: My big sister and I are way\n"
	.string "tougher than before!$"
	.endif
	.ifdef SPANISH
	.string "ROS: Mi hermanita y yo somos\n"
	.string "más fuertes que antes.$"
	.endif

SixIsland_GreenPath_Text_JaclynRematchIntro::
	.ifdef ENGLISH
	.string "…Huh?\p"
	.string "I envision my house, but TELEPORT\n"
	.string "always brings me here!$"
	.endif
	.ifdef SPANISH
	.string "¿Mmm?...\p"
	.string "Me pareció haber elegido mi casa\n"
	.string "con TELETRANSPORTE, pero\l"
	.string "siempre acabo en el mismo sitio.$"
	.endif

SixIsland_WaterPath_Text_RoseRematchIntro::
	.ifdef ENGLISH
	.string "Oh, hello.\n"
	.string "A pleasant breeze is blowing again.$"
	.endif
	.ifdef SPANISH
	.string "He llegado otra vez hasta aquí\n"
	.string "dejándome llevar por un agradable\l"
	.string "aroma.$"
	.endif

SixIsland_WaterPath_Text_EdwardRematchIntro::
	.ifdef ENGLISH
	.string "Hehehe, I'm practicing in secret\n"
	.string "again.$"
	.endif
	.ifdef SPANISH
	.string "Estoy practicando en secreto\n"
	.string "otra vez.$"
	.endif

SixIsland_WaterPath_Text_SamirRematchIntro::
	.ifdef ENGLISH
	.string "What, you're sick of seeing\n"
	.string "SWIMMERS like me?\p"
	.string "Aww, don't be hatin'!\n"
	.string "Battle with me again.$"
	.endif
	.ifdef SPANISH
	.string "¿Perdona? ¿Que no te gusta\n"
	.string "la gente que hace natación\l"
	.string "como yo?\p"
	.string "¡No fastidies!\n"
	.string "¡Vamos a luchar otra vez!$"
	.endif

SixIsland_WaterPath_Text_DeniseRematchIntro::
	.ifdef ENGLISH
	.string "Sigh…\n"
	.string "My boyfriend's busy again…$"
	.endif
	.ifdef SPANISH
	.string "Ufff...\n"
	.string "Mi chico está liado otra vez...$"
	.endif

SixIsland_WaterPath_Text_EarlRematchIntro::
	.ifdef ENGLISH
	.string "Come on, tell me, where are the\n"
	.string "mountains around these parts?$"
	.endif
	.ifdef SPANISH
	.string "Oye, dime dónde están las\n"
	.string "montañas de esta zona, anda.$"
	.endif

SixIsland_WaterPath_Text_MiuRematchIntro::
	.ifdef ENGLISH
	.string "MIU: Hello, POKéMON!\n"
	.string "It's time to play again!$"
	.endif
	.ifdef SPANISH
	.string "MARU: ¡Queridos POKéMON!\n"
	.string "¡Vamos a jugar otra vez!$"
	.endif

SixIsland_WaterPath_Text_MiaRematchIntro::
	.ifdef ENGLISH
	.string "MIA: Hello, POKéMON!\n"
	.string "It's time to battle again!$"
	.endif
	.ifdef SPANISH
	.string "MÍA: ¡Queridos POKéMON!\n"
	.string "¡Vamos a luchar otra vez!$"
	.endif

SixIsland_RuinValley_Text_StanlyRematchIntro::
	.ifdef ENGLISH
	.string "There appear to be many secrets\n"
	.string "still unsolved in this world.$"
	.endif
	.ifdef SPANISH
	.string "Creo que en este mundo quedan\n"
	.string "misterios aún por resolver.$"
	.endif

SixIsland_RuinValley_Text_FosterRematchIntro::
	.ifdef ENGLISH
	.string "Hi, didn't we meet before?\n"
	.string "What compelled you to come back?$"
	.endif
	.ifdef SPANISH
	.string "Yo a ti te conozco...\n"
	.string "¿Qué te trae de nuevo hasta aquí?$"
	.endif

SixIsland_RuinValley_Text_LarryRematchIntro::
	.ifdef ENGLISH
	.string "It's been said that there are\n"
	.string "mysterious stones on this island.\p"
	.string "Have you discovered anything since\n"
	.string "we last met?$"
	.endif
	.ifdef SPANISH
	.string "Dicen que hay misteriosas piedras\n"
	.string "en esta isla.\p"
	.string "¿Has descubierto algo desde\n"
	.string "la última vez que nos vimos?$"
	.endif

SixIsland_RuinValley_Text_DarylRematchIntro::
	.ifdef ENGLISH
	.string "A rematch with you, so high up!$"
	.endif
	.ifdef SPANISH
	.string "¿Luchar contigo otra vez?\n"
	.string "¡Ahora mismo!$"
	.endif

SixIsland_RuinValley_Text_HectorRematchIntro::
	.ifdef ENGLISH
	.string "I'm pretty familiar with the land\n"
	.string "around these parts.$"
	.endif
	.ifdef SPANISH
	.string "Yo me conozco bien toda esta\n"
	.string "zona.$"
	.endif

SevenIsland_TrainerTower_Text_DarioRematchIntro::
	.ifdef ENGLISH
	.string "I sensed your approach.$"
	.endif
	.ifdef SPANISH
	.string "He notado que te acercabas.$"
	.endif

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
	.ifdef ENGLISH
	.string "Somewhere on this island, peculiar\n"
	.string "POKéMON are sleeping.$"
	.endif
	.ifdef SPANISH
	.string "En alguna parte de esta isla,\n"
	.string "hay extraños POKéMON durmiendo.$"
	.endif

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
	.ifdef ENGLISH
	.string "Kyahaha!\p"
	.string "Coming back won't change a thing.\n"
	.string "I'll flick you away effortlessly!$"
	.endif
	.ifdef SPANISH
	.string "¡Voy a acabar contigo en un abrir\n"
	.string "y cerrar de ojos!\p"
	.string "¡No te creas que por volver\n"
	.string "vas a ganarme!$"
	.endif

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
	.ifdef ENGLISH
	.string "Howdy! You're a member of my\n"
	.string "fan club, isn't that right?$"
	.endif
	.ifdef SPANISH
	.string "¡Hola, cara de bola!\n"
	.string "¿Tú no eras de mi club de fans?$"
	.endif

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
	.ifdef ENGLISH
	.string "This island is too spread out…\n"
	.string "Patrolling the place is a drag…$"
	.endif
	.ifdef SPANISH
	.string "Esta isla tiene una extensión muy\n"
	.string "particular, no es fácil patrullar.$"
	.endif

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
	.ifdef ENGLISH
	.string "I don't forgive people who abuse\n"
	.string "POKéMON!$"
	.endif
	.ifdef SPANISH
	.string "¡No perdono a quien se pasa con\n"
	.string "los POKéMON!$"
	.endif

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
	.ifdef ENGLISH
	.string "EVE: I'll team up with JON and\n"
	.string "battle together again.$"
	.endif
	.ifdef SPANISH
	.string "ELE: RUS y yo queremos luchar\n"
	.string "de nuevo contigo.$"
	.endif

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
	.ifdef ENGLISH
	.string "JON: When I'm with EVE, it feels\n"
	.string "like we could never lose, not ever.$"
	.endif
	.ifdef SPANISH
	.string "RUS: Cuando estoy con ELE,\n"
	.string "creo que no voy a perder nunca.\l"
	.string "Ahora lo veremos.$"
	.endif

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
	.ifdef ENGLISH
	.string "Let's have another battle.\n"
	.string "My conditioning's in top form!$"
	.endif
	.ifdef SPANISH
	.string "Vamos a luchar de nuevo.\n"
	.string "¡Estoy realmente en forma!$"
	.endif

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
	.ifdef ENGLISH
	.string "It doesn't matter if you happen to\n"
	.string "have the strongest POKéMON…\p"
	.string "It doesn't mean a thing if you don't\n"
	.string "know how to use them properly!$"
	.endif
	.ifdef SPANISH
	.string "Da igual que tengas los POKéMON\n"
	.string "más fuertes...\p"
	.string "¡Lo importante es saber cómo\n"
	.string "manejarlos!$"
	.endif

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
	.ifdef ENGLISH
	.string "I work to protect the environment.\n"
	.string "In turn, nature protects me!$"
	.endif
	.ifdef SPANISH
	.string "Yo protejo el medio ambiente\n"
	.string "y él me protege a mí.$"
	.endif

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
	.ifdef ENGLISH
	.string "Every time we meet, you have those\n"
	.string "snazzy shoes on.$"
	.endif
	.ifdef SPANISH
	.string "La última vez que nos vimos,\n"
	.string "llevabas también esos zapatos\l"
	.string "tan llamativos.$"
	.endif

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
	.ifdef ENGLISH
	.string "You must have gotten tougher.\n"
	.string "Let me battle you, please!$"
	.endif
	.ifdef SPANISH
	.string "¡Debes de ser más fuerte!\n"
	.string "¡Vamos a luchar, anda!$"
	.endif

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
	.ifdef ENGLISH
	.string "I was given the best possible\n"
	.string "education to become this strong.\p"
	.string "I won't lose this time.\n"
	.string "Absolutely not!$"
	.endif
	.ifdef SPANISH
	.string "He recibido la mejor educación\n"
	.string "para tener la fuerza que tengo.\p"
	.string "¡No pienso perder esta vez!\n"
	.string "¡Ni en broma!$"
	.endif

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
	.ifdef ENGLISH
	.string "LEX: My darling NYA, together\n"
	.string "we will win for certain!$"
	.endif
	.ifdef SPANISH
	.string "LINO: Mi adorada ABA, ¡vamos\n"
	.string "a ganar!$"
	.endif

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
	.ifdef ENGLISH
	.string "NYA: I won't drag down my mentor\n"
	.string "LEX! We're going to win!$"
	.endif
	.ifdef SPANISH
	.string "ABA: No defraudaré a mi maestro\n"
	.string "LINO. ¡Tenemos que ganar!$"
	.endif

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
	.ifdef ENGLISH
	.string "Have you discovered anything about\n"
	.string "this stone chamber?$"
	.endif
	.ifdef SPANISH
	.string "¿Has descubierto algo de esta\n"
	.string "cámara de piedra?$"
	.endif

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
	.ifdef ENGLISH
	.string "A mystic POKéMON is said to sleep\n"
	.string "inside here.$"
	.endif
	.ifdef SPANISH
	.string "Dicen que aquí dentro duerme\n"
	.string "un místico POKéMON.$"
	.endif

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
	.ifdef ENGLISH
	.string "My teacher is showing me how to\n"
	.string "paint some more.$"
	.endif
	.ifdef SPANISH
	.string "Mi profe me está enseñando\n"
	.string "nuevas técnicas de pintura.$"
	.endif

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
	.ifdef ENGLISH
	.string "Today, in addition to our lesson,\n"
	.string "we came to see the chamber again.$"
	.endif
	.ifdef SPANISH
	.string "Hoy, como complemento a la clase,\n"
	.string "hemos venido a visitar la cámara\l"
	.string "otra vez.$"
	.endif
