CeladonCity_GameCorner_Text_TryPokemonPrinter::
	.ifdef ENGLISH
	.string "It's a POKéMON PRINTER!\p"
	.string "It can put a print of your POKéMON\n"
	.string "on the back of your TRAINER CARD.\p"
	.string "It costs only ¥50.\n"
	.string "Would you like to try it?$"
	.endif
	.ifdef SPANISH
	.string "¡Un POKéMATÓN!\p"
	.string "Hazles una foto a los miembros\n"
	.string "de tu equipo POKéMON y decora\p"
	.string "el reverso de tu FICHA\n"
	.string "de ENTRENADOR.\p"
	.string "Sólo cuesta 50¥.\n"
	.string "¿Quieres probar?$"
	.endif

CeladonCity_GameCorner_Text_DontHaveEnoughMoney::
	.ifdef ENGLISH
	.string "You don't have enough money.$"
	.endif
	.ifdef SPANISH
	.string "No tengo suficiente dinero...$"
	.endif

CeladonCity_GameCorner_Text_ChoosePrintType::
	.ifdef ENGLISH
	.string "Please choose the print type.$"
	.endif
	.ifdef SPANISH
	.string "¿Cómo quieres que salga la foto?$"
	.endif

CeladonCity_GameCorner_Text_BigSmileForPhoto::
	.ifdef ENGLISH
	.string "A big smile for the photo, please!\n"
	.string "Three… Two… One…\p"
	.string "Flash!$"
	.endif
	.ifdef SPANISH
	.string "A ver...\n"
	.string "Una sonrisita para la cámara...\p"
	.string "¡Foto va!$"
	.endif

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard::
	.ifdef ENGLISH
	.string "Your POKéMON print is ready!\n"
	.string "Check your TRAINER CARD.$"
	.endif
	.ifdef SPANISH
	.string "¡Ya se han revelado las fotos!\n"
	.string "¡Échale un vistazo a tu FICHA\l"
	.string "de ENTRENADOR!$"
	.endif

FourIsland_House2_Text_WishICouldShowOffStickers::
	.ifdef ENGLISH
	.string "Giggle…\n"
	.string "I collected a ton of STICKERS.\l"
	.string "I wish I could show them off…$"
	.endif
	.ifdef SPANISH
	.string "Je, je... He coleccionado\n"
	.string "un montón de CROMOS. ¡Me gustaría\l"
	.string "que los viera todo el mundo!$"
	.endif

FourIsland_House2_Text_GiveYouStickerIfYouBrag::
	.ifdef ENGLISH
	.string "Oh, excellent!\n"
	.string "You've come to the right place!\p"
	.string "Look, look! See? See?\n"
	.string "These are my STICKERS!\l"
	.string "Look how many I got!\p"
	.string "I bet you want some.\n"
	.string "I bet you do!\p"
	.string "I'll give a STICKER if you can tell\n"
	.string "me something awesome about\l"
	.string "yourself.\p"
	.string "What will you brag about?$"
	.endif
	.ifdef SPANISH
	.string "¡Hola, me alegro de verte por\n"
	.string "aquí! ¡Estupendo, estupendo!\p"
	.string "Mira, mira, ¿ves, ves?\n"
	.string "Éstos son mis CROMOS.\l"
	.string "¡Mira cuántos tengo!\p"
	.string "Sé que quieres alguno.\n"
	.string "Se te nota.\p"
	.string "Te daré un CROMO si me cuentas\n"
	.string "algo sorprendente sobre ti.\p"
	.string "¿Qué me dices?$"
	.endif

FourIsland_House2_Text_BragAboutSomethingForMe::
	.ifdef ENGLISH
	.string "Brag about something for me.\n"
	.string "I'll give you a STICKER.$"
	.endif
	.ifdef SPANISH
	.string "Vamos a cotillear un poco. Si me\n"
	.string "cuentas algo, te doy un CROMO.$"
	.endif

FourIsland_House2_Text_BragAboutWhatToday::
	.ifdef ENGLISH
	.string "Oh, hi!\n"
	.string "Here comes the braggart.\p"
	.string "What are you going to brag about\n"
	.string "today?$"
	.endif
	.ifdef SPANISH
	.string "¡Anda, mira a quién tenemos aquí!\n"
	.string "¡Lo más cotilla de la zona!\p"
	.string "¿De qué vienes a hablarme?$"
	.endif

FourIsland_House2_Text_WowHoFLowest::
	.ifdef ENGLISH
	.string "Oh, wow, you made it into the\n"
	.string "HALL OF FAME.\p"
	.string "That's pretty good, yup!\n"
	.string "I'll give you one of these.$"
	.endif
	.ifdef SPANISH
	.string "¡Guau, has entrado en el HALL\n"
	.string "de la FAMA!\p"
	.string "¡Qué guay!\n"
	.string "Toma, te lo has ganado.$"
	.endif

FourIsland_House2_Text_WowHoFLow::
	.ifdef ENGLISH
	.string "Oh, wow, you've entered the\n"
	.string "HALL OF FAME often!\p"
	.string "That's impressive, yup!\n"
	.string "I'll give you one of these.$"
	.endif
	.ifdef SPANISH
	.string "¡Guau, has entrado en el HALL\n"
	.string "de la FAMA más de una vez!\p"
	.string "¡Impresionante!\n"
	.string "Toma, te lo has ganado.$"
	.endif

FourIsland_House2_Text_WowHoFHigh::
	.ifdef ENGLISH
	.string "Whoa! You've made it into the\n"
	.string "HALL OF FAME that often?\l"
	.string "That's seriously incredible, yup!\p"
	.string "You own the POKéMON LEAGUE!\n"
	.string "I'll give you one of these.$"
	.endif
	.ifdef SPANISH
	.string "¡Guau, has entrado en el HALL\n"
	.string "de la FAMA muchas veces!\l"
	.string "¡Es impresionante! \p"
	.string "¡La LIGA POKéMON es tuya!\n"
	.string "Toma, te lo has ganado.$"
	.endif

FourIsland_House2_Text_WowHoFHighest::
	.ifdef ENGLISH
	.string "No way! You've gone into the\n"
	.string "HALL OF FAME that many times?\p"
	.string "You're beyond incredible, yup!\n"
	.string "That's it, I have to give you this.$"
	.endif
	.ifdef SPANISH
	.string "¡Venga ya! ¿De verdad has entrado\n"
	.string "tantas veces en el HALL de la\l"
	.string "FAMA?\p"
	.string "¡Eres la repera!\n"
	.string "Toma, te lo has ganado a pulso.$"
	.endif

FourIsland_House2_Text_HoFStickerApplied::
	.ifdef ENGLISH
	.string "The HALL OF FAME STICKER was\n"
	.string "applied to the TRAINER CARD.$"
	.endif
	.ifdef SPANISH
	.string "Se ha puesto el CROMO del\n"
	.string "HALL de la FAMA en tu FICHA\l"
	.string "de ENTRENADOR.$"
	.endif

FourIsland_House2_Text_ComeBackWithBetterStoryHoF::
	.ifdef ENGLISH
	.string "Hmm…\p"
	.string "Come back with a better story next\n"
	.string "time, okay?$"
	.endif
	.ifdef SPANISH
	.string "Mmm...\p"
	.string "Vuelve cuando tengas un tema\n"
	.string "más interesante, ¿vale?$"
	.endif

FourIsland_House2_Text_LivingLegendHoF::
	.ifdef ENGLISH
	.string "Oh, no, no can do.\p"
	.string "You're practically a living legend.\n"
	.string "I have no SITCKERS left to give.$"
	.endif
	.ifdef SPANISH
	.string "No puede ser...\p"
	.string "¡Eres una leyenda viva! ¡Ya no\n"
	.string "me quedan CROMOS que darte!$"
	.endif

FourIsland_House2_Text_WowEggsLowest::
	.ifdef ENGLISH
	.string "Oh, wow, there are POKéMON EGGS?\n"
	.string "I didn't know that!\p"
	.string "That's pretty good, yup!\n"
	.string "I'll give you one of these.$"
	.endif
	.ifdef SPANISH
	.string "Anda, ¿hay HUEVOS POKéMON?\n"
	.string "¡No lo sabía!\p"
	.string "¡Qué bueno! ¡Es genial!\n"
	.string "Toma, anda, te lo mereces.$"
	.endif

FourIsland_House2_Text_WowEggsLow::
	.ifdef ENGLISH
	.string "You've hatched that many EGGS?\n"
	.string "You really must like them!\p"
	.string "That's impressive, yup!\n"
	.string "I'll give you one of these.$"
	.endif
	.ifdef SPANISH
	.string "¿Has conseguido que se abrieran\n"
	.string "todos esos HUEVOS?\l"
	.string "¡Deben de encantarte!\p"
	.string "¡Me parece alucinante, sí, sí!\n"
	.string "Toma, anda, te lo mereces.$"
	.endif

FourIsland_House2_Text_WowEggsHigh::
	.ifdef ENGLISH
	.string "Whoa! You've hatched a whole\n"
	.string "bunch of EGGS!\p"
	.string "You're an EGG-hatching machine!\n"
	.string "I'll give you one of these.$"
	.endif
	.ifdef SPANISH
	.string "¡Guau, has conseguido que se\n"
	.string "abrieran un montón de HUEVOS!\p"
	.string "¡Eres una máquina con los HUEVOS,\n"
	.string "sí, sí! Toma, anda, te lo mereces.$"
	.endif

FourIsland_House2_Text_WowEggsHighest::
	.ifdef ENGLISH
	.string "Wh… You hatched that many EGGS?\p"
	.string "What's behind your love of EGGS?\n"
	.string "It's beyond incredible, yup!\p"
	.string "You're too awesome, I tell you.\n"
	.string "That's it, I have to give you this.$"
	.endif
	.ifdef SPANISH
	.string "¡Qué pasada!... ¿De verdad que\n"
	.string "has conseguido que se abrieran\l"
	.string "tantos HUEVOS?\p"
	.string "¡Lo tuyo con los HUEVOS no es\n"
	.string "normal! ¡Qué barbaridad!\p"
	.string "¡Me dejas sin palabras! Toma,\n"
	.string "no tengo más remedio que dártelo.$"
	.endif

FourIsland_House2_Text_EggStickerApplied::
	.ifdef ENGLISH
	.string "The EGG STICKER was applied\n"
	.string "to the TRAINER CARD.$"
	.endif
	.ifdef SPANISH
	.string "Se ha puesto el CROMO de los\n"
	.string "HUEVOS en tu FICHA de ENTRENADOR.$"
	.endif

FourIsland_House2_Text_ComeBackWithBetterStoryEggs::
	.ifdef ENGLISH
	.string "Hmm…\p"
	.string "Come back with a better story next\n"
	.string "time, okay?$"
	.endif
	.ifdef SPANISH
	.string "Mmm...\p"
	.string "Vuelve cuando tengas un tema\n"
	.string "más interesante, ¿vale?$"
	.endif

FourIsland_House2_Text_LivingLegendEggs::
	.ifdef ENGLISH
	.string "Oh, no, no can do.\p"
	.string "You're practically a living legend.\n"
	.string "I have no SITCKERS left to give.$"
	.endif
	.ifdef SPANISH
	.string "No puede ser...\p"
	.string "¡Eres una leyenda viva! ¡Ya no\n"
	.string "me quedan CROMOS que darte!$"
	.endif

FourIsland_House2_Text_WowLinkWinsLowest::
	.ifdef ENGLISH
	.string "Oh, wow, you've had success\n"
	.string "link battling?\p"
	.string "You're pretty strong, yup!\n"
	.string "I'll give you one of these.$"
	.endif
	.ifdef SPANISH
	.string "Oye, te ha ido bien luchando\n"
	.string "con tus amigos, ¿eh?\p"
	.string "¡Eres muy fuerte, sí, sí!\n"
	.string "Toma, anda, te lo mereces.$"
	.endif

FourIsland_House2_Text_WowLinkWinsLow::
	.ifdef ENGLISH
	.string "You've beaten your friends a lot\n"
	.string "link battling, huh?\p"
	.string "You're impressively strong, yup!\n"
	.string "I'll give you one of these.$"
	.endif
	.ifdef SPANISH
	.string "Oye, te ha ido muy bien luchando\n"
	.string "con tus amigos, ¿eh?\p"
	.string "¡Eres realmente fuerte, sí, sí!\n"
	.string "Toma, anda, te lo mereces.$"
	.endif

FourIsland_House2_Text_WowLinkWinsHigh::
	.ifdef ENGLISH
	.string "Whoa! You've beaten your friends\n"
	.string "a frightful number of times.\p"
	.string "Have you lost friends over this?\n"
	.string "I'll give you one of these.$"
	.endif
	.ifdef SPANISH
	.string "Oye, te ha ido más que bien\n"
	.string "luchando con tus amigos, ¿eh?\p"
	.string "¿Y no se han enfadado contigo?\n"
	.string "Toma, anda, te lo mereces.$"
	.endif

FourIsland_House2_Text_WowLinkWinsHighest::
	.ifdef ENGLISH
	.string "Wh… Wickedly whoa!\n"
	.string "You've won mind-blowingly often!\p"
	.string "It just knocks me out thinking\n"
	.string "about how tough you are.\p"
	.string "You're the stuff of nightmares!\n"
	.string "That's it, I have to give you this.$"
	.endif
	.ifdef SPANISH
	.string "¡Alucinante!... ¡Has ganado\n"
	.string "muchísimas veces!\p"
	.string "¡No sé lo que me entra de pensar\n"
	.string "lo fuerte que eres!\p"
	.string "¡Eres invencible! Toma, no tengo\n"
	.string "más remedio que dártelo.$"
	.endif

FourIsland_House2_Text_VictoryStickerApplied::
	.ifdef ENGLISH
	.string "The VICTORY STICKER was applied\n"
	.string "to the TRAINER CARD.$"
	.endif
	.ifdef SPANISH
	.string "Se ha puesto el CROMO\n"
	.string "de la VICTORIA en tu FICHA\l"
	.string "de ENTRENADOR.$"
	.endif

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins::
	.ifdef ENGLISH
	.string "Hmm…\p"
	.string "Come back with a better story next\n"
	.string "time, okay?$"
	.endif
	.ifdef SPANISH
	.string "Mmm...\p"
	.string "Vuelve cuando tengas un tema\n"
	.string "más interesante, ¿vale?$"
	.endif

FourIsland_House2_Text_LivingLegendLinkWins::
	.ifdef ENGLISH
	.string "Oh, no, no can do.\p"
	.string "You're practically a living legend.\n"
	.string "I have no SITCKERS left to give.$"
	.endif
	.ifdef SPANISH
	.string "No puede ser...\p"
	.string "¡Eres una leyenda viva! ¡Ya no\n"
	.string "me quedan CROMOS que darte!$"
	.endif
