Text_FirstShouldRestoreMonsHealth::
	.ifdef ENGLISH
	.string "First, you should restore your\n"
	.string "POKéMON to full health.$"
	.endif
	.ifdef SPANISH
	.string "Primero, deberías devolverles\n"
	.string "la forma a tus POKéMON.$"
	.endif

Text_MonsHealedShouldBuyPotions::
	.ifdef ENGLISH
	.string "Your POKéMON have been healed\n"
	.string "to perfect health.\p"
	.string "If your POKéMON's energy, HP,\n"
	.string "is down, please come see us.\p"
	.string "If you're planning to go far in the\n"
	.string "field, you should buy some POTIONS\l"
	.string "at the POKéMON MART.\p"
	.string "We hope you excel!$"
	.endif
	.ifdef SPANISH
	.string "Tus POKéMON están de nuevo\n"
	.string "en forma.\p"
	.string "Ven a vernos cuando la energía\n"
	.string "de tus POKéMON, los PS, estén\l"
	.string "bajos de nivel.\p"
	.string "Cuando vayas a hacer un largo\n"
	.string "viaje, conviene que compres\l"
	.string "POCIONES en la TIENDA POKéMON.\p"
	.string "¡Demuestra lo que vales!$"
	.endif

Text_MonsHealed::
	.ifdef ENGLISH
	.string "Your POKéMON have been healed\n"
	.string "to perfect health.\p"
	.string "We hope you excel!$"
	.endif
	.ifdef SPANISH
	.string "Tus POKéMON están de nuevo\n"
	.string "en forma.\p"
	.string "¡Esperamos que te vaya bien!$"
	.endif

Text_HadQuiteAnExperienceTakeRest::
	.ifdef ENGLISH
	.string "MOM: {PLAYER}!\n"
	.string "Welcome home.\p"
	.string "It sounds like you had quite\n"
	.string "an experience.\p"
	.string "Maybe you should take a quick\n"
	.string "rest.$"
	.endif
	.ifdef SPANISH
	.string "MAMÁ: ¡{PLAYER}!\n"
	.string "¡Hola, cielo!\p"
	.string "¡Tienes cara de haber aprendido\n"
	.string "bastante!\p"
	.string "¡Descansa un poco, criatura!$"
	.endif

Text_MomExplainHPGetPotions::
	.ifdef ENGLISH
	.string "MOM: Oh, good! You and your\n"
	.string "POKéMON are looking great.\p"
	.string "I just heard from PROF. OAK.\p"
	.string "He said that POKéMON's energy is\n"
	.string "measured in HP.\p"
	.string "If your POKéMON lose their HP,\n"
	.string "you can restore them at any\l"
	.string "POKéMON CENTER.\p"
	.string "If you're going to travel far away,\n"
	.string "the smart TRAINER stocks up on\l"
	.string "POTIONS at the POKéMON MART.\p"
	.string "Make me proud, honey!\p"
	.string "Take care!$"
	.endif
	.ifdef SPANISH
	.string "MAMÁ: ¡Muy bien! ¡Tú y tus\n"
	.string "POKéMON estáis en plena forma!\p"
	.string "Me ha dicho el PROF. OAK que la\n"
	.string "energía de los POKéMON se mide\l"
	.string "por PS.\p"
	.string "Si tus POKéMON pierden los PS,\n"
	.string "puedes recuperarlos en cualquier\l"
	.string "CENTRO POKéMON.\p"
	.string "Para viajes largos, los ENTRENA-\n"
	.string "DORES más espabilados compran\p"
	.string "unas cuantas POCIONES en la\n"
	.string "TIENDA POKéMON.\p"
	.string "¡Demuestra a todos quien eres,\n"
	.string "cariño! ¡Cuídate mucho, tesoro!$"
	.endif

Text_WhitedOutLostMoney::
	.ifdef ENGLISH
	.string "{PLAYER} is out of usable\n"
	.string "POKéMON!\p"
	.string "{PLAYER} panicked and lost ¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} whited out!$"
	.endif
	.ifdef SPANISH
	.string "¡A {PLAYER} no le quedan\n"
	.string "más POKéMON!\p"
	.string "¡{PLAYER} se ha asustado\n"
	.string "y ha perdido {STR_VAR_1}¥!...\p"
	.string "... ... ... ...\p"
	.string "¡{PLAYER} está fuera de combate!$"
	.endif

Text_WhitedOut::
	.ifdef ENGLISH
	.string "{PLAYER} is out of usable\n"
	.string "POKéMON!\p"
	.string "{PLAYER} whited out!$"
	.endif
	.ifdef SPANISH
	.string "¡A {PLAYER} no le quedan\n"
	.string "más POKéMON!\p"
	.string "¡{PLAYER} está fuera de combate!$"
	.endif
