SevenIsland_PokemonCenter_1F_Text_EventsDependingOnConnections::
    .ifdef ENGLISH
    .string "On this island, different events\n"
    .string "occur depending on connections.\p"
    .string "What are those connections?\p"
    .string "They are for you to discover on\n"
    .string "your own.$"
    .endif
    .ifdef SPANISH
    .string "En la isla, ocurren distintas cosas\n"
    .string "según las conexiones.\p"
    .string "¿Que qué son las conexiones?\p"
    .string "Eso tendrás que descubrirlo sin\n"
    .string "ayuda de nadie.$"
    .endif

SevenIsland_PokemonCenter_1F_Text_DidYouRideSeagallopHere::
    .ifdef ENGLISH
    .string "Did you ride a SEAGALLOP ferry\n"
    .string "to get here?\p"
    .string "There are at least ten of those\n"
    .string "high-speed ships.\p"
    .string "I don't know where they all go,\n"
    .string "though.$"
    .endif
    .ifdef SPANISH
    .string "¿Has venido a bordo del SURCAMAR?\p"
    .string "Creo que en total hay diez barcos\n"
    .string "rápidos de esos.\p"
    .string "Pero no sé las rutas que cubren.$"
    .endif

SevenIsland_PokemonCenter_1F_Text_CheckOutTrainerTower::
    .ifdef ENGLISH
    .string "If you're confident, you should\n"
    .string "check out TRAINER TOWER.$"
    .endif
    .ifdef SPANISH
    .string "Si te sientes con fuerzas, deberías\n"
    .string "visitar la TORRE DESAFÍO.$"
    .endif

