SevenIsland_SevaultCanyon_Text_CyndyIntro::
    .ifdef ENGLISH
    .string "My conditioning's in top form!$"
    .endif
    .ifdef SPANISH
    .string "¡Estoy realmente en forma!$"
    .endif

SevenIsland_SevaultCanyon_Text_CyndyDefeat::
    .ifdef ENGLISH
    .string "Huh?\n"
    .string "Something's not right…$"
    .endif
    .ifdef SPANISH
    .string "¿Mmm?\n"
    .string "Aquí hay algo que falla...$"
    .endif

SevenIsland_SevaultCanyon_Text_CyndyPostBattle::
    .ifdef ENGLISH
    .string "The way I am now, I may have to\n"
    .string "hold off on TRAINER TOWER…$"
    .endif
    .ifdef SPANISH
    .string "Así no puedo presentarme a la\n"
    .string "TORRE DESAFÍO...$"
    .endif

SevenIsland_SevaultCanyon_Text_EvanIntro::
    .ifdef ENGLISH
    .string "It doesn't matter if you happen to\n"
    .string "have the strongest POKéMON…\p"
    .string "It doesn't mean a thing if you don't\n"
    .string "know how to use them properly!$"
    .endif
    .ifdef SPANISH
    .string "Da igual que tengas los POKéMON\n"
    .string "más fuertes...\p"
    .string "¡Lo importante es saber cómo\n"
    .string "tratarlos!$"
    .endif

SevenIsland_SevaultCanyon_Text_EvanDefeat::
    .ifdef ENGLISH
    .string "You're a master at this.$"
    .endif
    .ifdef SPANISH
    .string "Sabes bien lo que haces...$"
    .endif

SevenIsland_SevaultCanyon_Text_EvanPostBattle::
    .ifdef ENGLISH
    .string "You see them every so often,\n"
    .string "TRAINERS with awesome POKéMON\l"
    .string "who have no idea what to do.\p"
    .string "Before training POKéMON, TRAINERS\n"
    .string "themselves need to grow up.$"
    .endif
    .ifdef SPANISH
    .string "Hay mucho ENTRENADOR por ahí\n"
    .string "suelto con POKéMON increíbles y sin\l"
    .string "idea de cómo hay que tratarlos.\p"
    .string "Antes de entrenar POKéMON,\n"
    .string "son los propios ENTRENADORES los\l"
    .string "que deben crecer como personas.$"
    .endif

SevenIsland_SevaultCanyon_Text_JacksonIntro::
    .ifdef ENGLISH
    .string "I work to protect the environment.\n"
    .string "In turn, nature protects me!$"
    .endif
    .ifdef SPANISH
    .string "Yo protejo el medio ambiente\n"
    .string "y él me protege a mí.$"
    .endif

SevenIsland_SevaultCanyon_Text_JacksonDefeat::
    .ifdef ENGLISH
    .string "Whoa! You're tough!\n"
    .string "How about protecting me?$"
    .endif
    .ifdef SPANISH
    .string "¡Buah, eres fuerte!\n"
    .string "¿Y a mí quién me protege ahora?$"
    .endif

SevenIsland_SevaultCanyon_Text_JacksonPostBattle::
    .ifdef ENGLISH
    .string "From far out among the stars, our\n"
    .string "planet is just a drop of water.\p"
    .string "But we want to protect that drop\n"
    .string "of water for everyone.$"
    .endif
    .ifdef SPANISH
    .string "Visto desde las estrellas, nuestro\n"
    .string "planeta es un granito de arena.\p"
    .string "Y debemos proteger ese granito\n"
    .string "de arena por el bien de todos.$"
    .endif

SevenIsland_SevaultCanyon_Text_KatelynIntro::
    .ifdef ENGLISH
    .string "Those shoes you have are pretty\n"
    .string "snazzy.$"
    .endif
    .ifdef SPANISH
    .string "Tienes unos zapatos muy llamativos.$"
    .endif

SevenIsland_SevaultCanyon_Text_KatelynDefeat::
    .ifdef ENGLISH
    .string "You're hot stuff in spite of your\n"
    .string "cute looks.$"
    .endif
    .ifdef SPANISH
    .string "¡Cualquiera diría que eres tan\n"
    .string "fuerte! ¡No lo aparentas!$"
    .endif

SevenIsland_SevaultCanyon_Text_KatelynPostBattle::
    .ifdef ENGLISH
    .string "Your mom bought those snazzy\n"
    .string "RUNNING SHOES for you?\p"
    .string "She must adore you.$"
    .endif
    .ifdef SPANISH
    .string "¿Te ha comprado tu mamá esas\n"
    .string "DEPORTIVAS tan chulas?\p"
    .string "¡Debe de adorarte!$"
    .endif

SevenIsland_SevaultCanyon_Text_LeroyIntro::
    .ifdef ENGLISH
    .string "You look strong.\n"
    .string "Let me battle you, please!$"
    .endif
    .ifdef SPANISH
    .string "¡Pareces fuerte!\n"
    .string "¡Vamos a luchar, anda!$"
    .endif

SevenIsland_SevaultCanyon_Text_LeroyDefeat::
    .ifdef ENGLISH
    .string "I knew it!\n"
    .string "You're as tough as I thought!$"
    .endif
    .ifdef SPANISH
    .string "¡Lo sabía!\n"
    .string "¡Sabía que eras increíble!$"
    .endif

SevenIsland_SevaultCanyon_Text_LeroyPostBattle::
    .ifdef ENGLISH
    .string "The way you battle has given me\n"
    .string "a lot of useful data.\p"
    .string "Thanks so much!$"
    .endif
    .ifdef SPANISH
    .string "La forma de luchar que tienes\n"
    .string "dice mucho de ti.\p"
    .string "¡Gracias!$"
    .endif

SevenIsland_SevaultCanyon_Text_MichelleIntro::
    .ifdef ENGLISH
    .string "I was given the best possible\n"
    .string "education to become this strong.\p"
    .string "I don't want to lose to anyone!$"
    .endif
    .ifdef SPANISH
    .string "He recibido la mejor educación\n"
    .string "para tener la fuerza que tengo.\p"
    .string "¡No pienso perder ante nadie!$"
    .endif

SevenIsland_SevaultCanyon_Text_MichelleDefeat::
    .ifdef ENGLISH
    .string "Thank you. I feel like I've been\n"
    .string "set free by losing to you.$"
    .endif
    .ifdef SPANISH
    .string "Gracias, ya no tengo la presión\n"
    .string "de antes.$"
    .endif

SevenIsland_SevaultCanyon_Text_MichellePostBattle::
    .ifdef ENGLISH
    .string "For some reason, I get furious\n"
    .string "over the slightest thing.\p"
    .string "I'll calm myself by breathing\n"
    .string "deeply.$"
    .endif
    .ifdef SPANISH
    .string "La cosa más mínima, me ponía\n"
    .string "de mal humor.\p"
    .string "Ahora, con respirar hondo,\n"
    .string "se me pasa.$"
    .endif

SevenIsland_SevaultCanyon_Text_LexIntro::
    .ifdef ENGLISH
    .string "LEX: My darling NYA, together\n"
    .string "we could win!$"
    .endif
    .ifdef SPANISH
    .string "LINO: Mi adorada ABA, ¡no hay\n"
    .string "nadie que pueda con nosotros!$"
    .endif

SevenIsland_SevaultCanyon_Text_LexDefeat::
    .ifdef ENGLISH
    .string "LEX: I seem to have been too\n"
    .string "careless…$"
    .endif
    .ifdef SPANISH
    .string "LINO: Me parece que he bajado\n"
    .string "la guardia...$"
    .endif

SevenIsland_SevaultCanyon_Text_LexPostBattle::
    .ifdef ENGLISH
    .string "LEX: I think it was a good\n"
    .string "experience for NYA.\p"
    .string "You have my gratitude.$"
    .endif
    .ifdef SPANISH
    .string "LINO: Creo que ha sido una buena\n"
    .string "experiencia para ABA. Gracias.$"
    .endif

SevenIsland_SevaultCanyon_Text_LexNotEnoughMons::
    .ifdef ENGLISH
    .string "LEX: May I ask you to battle the\n"
    .string "both of us at the same time?$"
    .endif
    .ifdef SPANISH
    .string "LINO: ¿Podrías luchar con los dos\n"
    .string "a la vez?$"
    .endif

SevenIsland_SevaultCanyon_Text_NyaIntro::
    .ifdef ENGLISH
    .string "NYA: I'll do my best so I won't\n"
    .string "drag down my mentor, LEX!$"
    .endif
    .ifdef SPANISH
    .string "ABA: Me esforzaré mucho para no\n"
    .string "defraudar a mi maestro LINO.$"
    .endif

SevenIsland_SevaultCanyon_Text_NyaDefeat::
    .ifdef ENGLISH
    .string "NYA: Oh, no…\n"
    .string "I'm so sorry, I…$"
    .endif
    .ifdef SPANISH
    .string "ABA: Oooh... Lo siento...$"
    .endif

SevenIsland_SevaultCanyon_Text_NyaPostBattle::
    .ifdef ENGLISH
    .string "NYA: I think I'm going to need\n"
    .string "much more seasoning and tutoring\l"
    .string "under LEX…\p"
    .string "…So, LEX, please, may I stay with\n"
    .string "you like this?$"
    .endif
    .ifdef SPANISH
    .string "ABA: Creo que voy a necesitar que\n"
    .string "LINO me tutele y me oriente más...\p"
    .string "LINO, ¿te parece bien?...$"
    .endif

SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons::
    .ifdef ENGLISH
    .string "NYA: I'm sorry, but may we battle\n"
    .string "in two-on-two style?$"
    .endif
    .ifdef SPANISH
    .string "ABA: Lo siento, pero queremos\n"
    .string "luchar dos contra dos.$"
    .endif

SevenIsland_SevaultCanyon_Text_RouteSign::
    .ifdef ENGLISH
    .string "SEVAULT CANYON\n"
    .string "TANOBY RUINS AHEAD$"
    .endif
    .ifdef SPANISH
    .string "CAÑÓN SÉTANO\n"
    .string "HACIA LAS RUINAS SETE$"
    .endif

SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly::
    .ifdef ENGLISH
    .string "Training by oneself is certainly\n"
    .string "not a bad thing.\p"
    .string "But it's also not bad to aim for\n"
    .string "the top with a partner.\p"
    .string "Even BRUNO…\n"
    .string "He trained with a fellow by the\l"
    .string "name of BRAWLY before.$"
    .endif
    .ifdef SPANISH
    .string "Entrenarse uno mismo no está mal.\p"
    .string "Pero tampoco está mal buscar\n"
    .string "una buena pareja de combate.\p"
    .string "Fíjate en BRUNO...\n"
    .string "Él se entrenó con un tal MARCIAL.$"
    .endif
