OneIsland_Text_BillLetsGoSeeCelio::
    .ifdef ENGLISH
    .string "BILL: Here we are!\n"
    .string "This is ONE ISLAND.\p"
    .string "There are several islands around\n"
    .string "here, and this is one of them.\p"
    .string "My friend CELIO sent the boat to\n"
    .string "fetch me here.\p"
    .string "He's in charge of the island's PC\n"
    .string "network by his lonesome.\p"
    .string "…Why am I telling you this now?\n"
    .string "Let's just go see CELIO!$"
    .endif
    .ifdef SPANISH
    .string "BILL: Bueno, ya estamos aquí.\n"
    .string "Esto es ISLA PRIMA.\p"
    .string "Como indica su nombre,\n"
    .string "no es la única isla de por aquí.\p"
    .string "Mi amigo CELIO fue el que\n"
    .string "envió el barco.\p"
    .string "Él es el encargado de la red\n"
    .string "local de la isla. Se pasa el día\l"
    .string "con eso.\p"
    .string "Bueno, que me enrollo como las\n"
    .string "persianas, ¡vamos a ver a CELIO!$"
    .endif

Text_WhereDoYouWantToSail::
    .ifdef ENGLISH
    .string "Ahoy, there!\n"
    .string "Where do you want to sail?$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, caracola!\n"
    .string "¿Adónde vamos?$"
    .endif

OneIsland_Text_LuckyToHaveCelioHere::
    .ifdef ENGLISH
    .string "Here we are on an island smack in\n"
    .string "the middle of nowhere.\p"
    .string "We're lucky to have an upstanding\n"
    .string "young man like CELIO here.\p"
    .string "My granddaughter was in a tizzy\n"
    .string "over CELIO's friend.\p"
    .string "Something about a famous\n"
    .string "POKéMANIAC?\p"
    .string "I'm not sure what that means, but\n"
    .string "CELIO is quite the man!$"
    .endif
    .ifdef SPANISH
    .string "La verdad es que esta isla está\n"
    .string "plantada en medio de la nada,\l"
    .string "pero bueno...\p"
    .string "Menos mal que tenemos a un\n"
    .string "chicarrón hecho y derecho como\l"
    .string "CELIO.\p"
    .string "Mi nieta estaba un poco nerviosa\n"
    .string "con la llegada del amigo de CELIO.\p"
    .string "¿Será un POKéMANÍACO?\p"
    .string "En fin..., yo lo que sé es que\n"
    .string "estamos encantados con CELIO.$"
    .endif

OneIsland_Text_HavePCLinkageWithKanto::
    .ifdef ENGLISH
    .string "My granddaughter was in a tizzy\n"
    .string "over a new breakthrough.\p"
    .string "She said we now have PC linkage\n"
    .string "with people in KANTO.\p"
    .string "I'm not sure what that means, but\n"
    .string "CELIO is quite the man!$"
    .endif
    .ifdef SPANISH
    .string "Mi nieta estaba un poco nerviosa\n"
    .string "por un reciente descubrimiento.\p"
    .string "Según dijo, ahora tenemos conexión\n"
    .string "vía PC con la gente de KANTO.\p"
    .string "En fin..., yo lo que sé es que\n"
    .string "estamos encantados con CELIO.$"
    .endif

OneIsland_Text_HavePCLinkageWithHoenn::
    .ifdef ENGLISH
    .string "My granddaughter was in a tizzy\n"
    .string "over a new breakthrough.\p"
    .string "She said we finally have PC linkage\n"
    .string "with people in HOENN.\p"
    .string "I'm not sure what that means, but\n"
    .string "CELIO is quite the man.\p"
    .string "He would make a fine husband for\n"
    .string "my granddaughter!$"
    .endif
    .ifdef SPANISH
    .string "Mi nieta estaba un poco nerviosa\n"
    .string "por un reciente descubrimiento.\p"
    .string "Según dijo, ahora tenemos conexión\n"
    .string "vía PC con la gente de HOENN.\p"
    .string "En fin..., yo lo que sé es que\n"
    .string "estamos encantados con CELIO.\p"
    .string "¡La verdad es que sería el marido\n"
    .string "perfecto para mi nieta!$"
    .endif

OneIsland_Text_IslandSign::
    .ifdef ENGLISH
    .string "ONE ISLAND\n"
    .string "Friends Gather at Knot Island$"
    .endif
    .ifdef SPANISH
    .string "ISLA PRIMA\n"
    .string "Punto de encuentro para todos.$"
    .endif

OneIsland_Text_PokemonNetCenterSign::
    .ifdef ENGLISH
    .string "Expanding the POKéMON World!\n"
    .string "POKéMON NET CENTER$"
    .endif
    .ifdef SPANISH
    .string "CENTRO DE RED POKéMON\n"
    .string "¡Un mundo POKéMON en conexión!$"
    .endif

@ Unused
OneIsland_Text_ReturnToCinnabar::
    .string "グレンタウンに　もどりますか？$"

OneIsland_Text_IsntWarmClimateHereGreat::
    .ifdef ENGLISH
    .string "Hi, sight-seeing, are you?\n"
    .string "Isn't the warm climate here great?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué? ¿Disfrutando del paisaje?\n"
    .string "El tiempo es fabuloso, ¿eh?$"
    .endif

