LavenderTown_Text_DoYouBelieveInGhosts::
    .string "¿Crees en los GHOST?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "¿De verdad?\n"
    .string "Hay quien no cree...$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "¡Jajaja! Yo tampoco.\p"
    .string "Esa mano blanca en tu hombro no es\n"
    .string "real.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "A este pueblo se lo conoce como\n"
    .string "el lugar de reposo de los POKéMON.\p"
    .string "Los homenajes se celebran en la\n"
    .string "TORRE POKéMON.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "Los GHOST aparecieron en la TORRE\n"
    .string "POKéMON.\p"
    .string "Creo que son espíritus de POKéMON\n"
    .string "debilitados por los ROCKET.$"

LavenderTown_Text_TownSign::
    .string "PUEBLO LAVANDA\n"
    .string "El noble pueblo púrpura.$"

LavenderTown_Text_SilphScopeNotice::
    .string "SILPH S.A.\p"
    .string "¡El nuevo SCOPE SILPH!\n"
    .string "¡Hace visible lo invisible!$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "CASA POKéMON DE VOLUNTARIOS\n"
    .string "DE PUEBLO LAVANDA$"

LavenderTown_Text_PokemonTowerSign::
    .string "TORRE POKéMON: Que las almas de\n"
    .string "los POKéMON descansen en paz.$"
