LavenderTown_Text_DoYouBelieveInGhosts::
    .ifdef ENGLISH
    .string "Do you believe in ghosts?$"
    .endif
    .ifdef SPANISH
    .string "¿Crees en los GHOST?$"
    .endif

LavenderTown_Text_SoThereAreBelievers::
    .ifdef ENGLISH
    .string "Really?\n"
    .string "So there are believers…$"
    .endif
    .ifdef SPANISH
    .string "¿De verdad?\n"
    .string "Hay quien no cree...$"
    .endif

LavenderTown_Text_JustImaginingWhiteHand::
    .ifdef ENGLISH
    .string "Hahaha, I guess not.\p"
    .string "That white hand on your shoulder…\n"
    .string "I'm just imagining it.$"
    .endif
    .ifdef SPANISH
    .string "¡Jajaja! Yo tampoco.\p"
    .string "Esa mano blanca en tu hombro no es\n"
    .string "real.$"
    .endif

LavenderTown_Text_TownKnownAsMonGraveSite::
    .ifdef ENGLISH
    .string "This town is known as the grave\n"
    .string "site of POKéMON.\p"
    .string "Memorial services are held in\n"
    .string "POKéMON TOWER.$"
    .endif
    .ifdef SPANISH
    .string "A este pueblo se lo conoce como\n"
    .string "el lugar de reposo de los POKéMON.\p"
    .string "Los homenajes se celebran en la\n"
    .string "TORRE POKéMON.$"
    .endif

LavenderTown_Text_GhostsAppearedInTower::
    .ifdef ENGLISH
    .string "Ghosts appeared in POKéMON TOWER.\p"
    .string "I think they're the spirits of\n"
    .string "POKéMON that the ROCKETS killed.$"
    .endif
    .ifdef SPANISH
    .string "Los GHOST aparecieron en la TORRE\n"
    .string "POKéMON.\p"
    .string "Creo que son espíritus de POKéMON\n"
    .string "debilitados por los ROCKET.$"
    .endif

LavenderTown_Text_TownSign::
    .ifdef ENGLISH
    .string "LAVENDER TOWN\n"
    .string "The Noble Purple Town$"
    .endif
    .ifdef SPANISH
    .string "PUEBLO LAVANDA\n"
    .string "El noble pueblo púrpura.$"
    .endif

LavenderTown_Text_SilphScopeNotice::
    .ifdef ENGLISH
    .string "New SILPH SCOPE!\n"
    .string "Make the Invisible Plain to See!\p"
    .string "SILPH CO.$"
    .endif
    .ifdef SPANISH
    .string "SILPH S.A.\p"
    .string "¡El nuevo SCOPE SILPH!\n"
    .string "¡Hace visible lo invisible!$"
    .endif

LavenderTown_Text_VolunteerPokemonHouse::
    .ifdef ENGLISH
    .string "LAVENDER VOLUNTEER\n"
    .string "POKéMON HOUSE$"
    .endif
    .ifdef SPANISH
    .string "CASA POKéMON DE VOLUNTARIOS\n"
    .string "DE PUEBLO LAVANDA$"
    .endif

LavenderTown_Text_PokemonTowerSign::
    .ifdef ENGLISH
    .string "POKéMON TOWER\n"
    .string "Becalm the Spirits of POKéMON$"
    .endif
    .ifdef SPANISH
    .string "TORRE POKéMON: Que las almas de\n"
    .string "los POKéMON descansen en paz.$"
    .endif

