LavenderTown_Text_DoYouBelieveInGhosts::
	.string "Glaubst du an GEISTER?$"

LavenderTown_Text_SoThereAreBelievers::
	.string "Echt?\n"
	.string "Hätte ich nicht gedacht!$"

LavenderTown_Text_JustImaginingWhiteHand::
	.string "Hahaha, natürlich nicht!\p"
	.string "Und diese weiße Hand da auf deiner\n"
	.string "Schulter ist natürlich nicht echt!$"

LavenderTown_Text_TownKnownAsMonGraveSite::
	.string "Diese Stadt ist als Ruhestätte für\n"
	.string "POKéMON bekannt.\p"
	.string "Im POKéMON-TURM werden Andachten\n"
	.string "gehalten.$"

LavenderTown_Text_GhostsAppearedInTower::
	.string "GEISTER spuken im POKéMON-TURM.\p"
	.string "Ich glaube, das sind die Geister\n"
	.string "jener POKéMON, die das TEAM\l"
	.string "ROCKET auf dem Gewissen hat!$"

LavenderTown_Text_TownSign::
	.string "LAVANDIA\n"
	.string "Die edle, violette Stadt!$"

LavenderTown_Text_SilphScopeNotice::
	.string "SILPH SCOPE!\n"
	.string "Macht das Unsichtbare sichtbar!\p"
	.string "SILPH CO.$"

LavenderTown_Text_VolunteerPokemonHouse::
	.string "LAVANDIA \n"
	.string "POKéMON-HAUS$"

LavenderTown_Text_PokemonTowerSign::
	.string "Mögen die Seelen der POKéMON im\n"
	.string "POKéMON-TURM in Frieden ruhen!$"

