PokemonMansion_Text_PressSecretSwitchJP::
    .string "ひみつの　スイッチが　ある！\p"
    .string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt::
    .string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
    .string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro::
    .ifdef ENGLISH
    .string "This place is, like, huge!$"
    .endif
    .ifdef SPANISH
    .string "Este lugar es...\n"
    .string "¡Gigantesco!$"
    .endif

PokemonMansion_1F_Text_SimonDefeat::
    .ifdef ENGLISH
    .string "Ayah!$"
    .endif
    .ifdef SPANISH
    .string "¡Ayah!$"
    .endif

PokemonMansion_1F_Text_SimonPostBattle::
    .ifdef ENGLISH
    .string "I wonder where my partner went.$"
    .endif
    .ifdef SPANISH
    .string "Me pregunto adónde habrá ido\n"
    .string "mi compañero.$"
    .endif

PokemonMansion_1F_Text_BraydonIntro::
    .ifdef ENGLISH
    .string "My mentor once lived here.$"
    .endif
    .ifdef SPANISH
    .string "Mi maestro vivió aquí hace tiempo.$"
    .endif

PokemonMansion_1F_Text_BraydonDefeat::
    .ifdef ENGLISH
    .string "Whew!\n"
    .string "Overwhelming!$"
    .endif
    .ifdef SPANISH
    .string "¡Uau!\n"
    .string "¡Impresionante!$"
    .endif

PokemonMansion_1F_Text_BraydonPostBattle::
    .ifdef ENGLISH
    .string "So, you're stuck?\n"
    .string "Try jumping off over there!$"
    .endif
    .ifdef SPANISH
    .string "¿No sabes por dónde ir?\n"
    .string "¡Tírate por ahí!$"
    .endif

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
    .ifdef ENGLISH
    .string "Diary: Feb. 6\n"
    .string "MEW gave birth.\p"
    .string "We named the newborn MEWTWO.$"
    .endif
    .ifdef SPANISH
    .string "Diario: 6 de febrero.\n"
    .string "MEW dio a luz.\p"
    .string "Llamamos al pequeño: MEWTWO.$"
    .endif

