PokemonMansion_Text_PressSecretSwitchJP::
	.string "ひみつの　スイッチが　ある！\p"
	.string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt::
	.string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
	.string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro::
	.string "Dieses Gebiet hier ist riesig!$"

PokemonMansion_1F_Text_SimonDefeat::
	.string "Tschüss!$"

PokemonMansion_1F_Text_SimonPostBattle::
	.string "Ich frage mich, wo mein Partner\n"
	.string "wohl sein mag!?$"

PokemonMansion_1F_Text_BraydonIntro::
	.string "Mein Mentor lebte einst hier...$"

PokemonMansion_1F_Text_BraydonDefeat::
	.string "Wow!\n"
	.string "Unglaublich!$"

PokemonMansion_1F_Text_BraydonPostBattle::
	.string "Du kommst nicht weiter? Springe\n"
	.string "einfach da drüben herunter!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
	.string "TAGEBUCH: 6. FEBRUAR\n"
	.string "MEW hat ein Junges geboren!\p"
	.string "Wir haben es MEWTU genannt.$"

