PokemonMansion_Text_PressSecretSwitchJP::
	.string "ひみつの　スイッチが　ある！\p"
	.string "おして　みますか？$"

PokemonMansion_Text_LetsTryIt::
	.string "おしてみよう！　‥ポチッとな$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
	.string "おすのは　あきらめた$"

PokemonMansion_1F_Text_SimonIntro::
	.string "Fouiii…\n"
	.string "C'est grand ici!$"

PokemonMansion_1F_Text_SimonDefeat::
	.string "Yargl!$"

PokemonMansion_1F_Text_SimonPostBattle::
	.string "Mais où est donc mon complice?$"

PokemonMansion_1F_Text_BraydonIntro::
	.string "Mon mentor vivait ici autrefois.$"

PokemonMansion_1F_Text_BraydonDefeat::
	.string "!!!\n"
	.string "Impressionnant!$"

PokemonMansion_1F_Text_BraydonPostBattle::
	.string "T'as perdu ton chemin?\n"
	.string "Essaie de sauter par là-bas!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
	.string "Rapport: 6 Février.\n"
	.string "MEW est papa (ou maman?).\p"
	.string "Le petit a été baptisé MEWTWO.$"

