LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney::
    .ifdef ENGLISH
    .string "TEAM ROCKET will do anything for\n"
    .string "the sake of money!\p"
    .string "There is no job too dirty, no deed\n"
    .string "too heinous, no crime too wicked!$"
    .endif
    .ifdef SPANISH
    .string "¡El TEAM ROCKET hará lo que sea\n"
    .string "por el oro!\p"
    .string "¡No hay trabajo sucio ni actos\n"
    .string "vandálicos que no sean capaces\l"
    .string "de hacer!$"
    .endif

LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets::
    .ifdef ENGLISH
    .string "I saw CUBONE's mother trying to\n"
    .string "escape from TEAM ROCKET.\p"
    .string "She was killed trying to get away…$"
    .endif
    .ifdef SPANISH
    .string "¡Vi a la madre de CUBONE\n"
    .string "intentando huir del TEAM ROCKET!\p"
    .string "La pobre no lo consiguió...$"
    .endif

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls::
    .ifdef ENGLISH
    .string "You know how the CUBONE species\n"
    .string "wears skulls, right?\p"
    .string "People will pay a lot for one.$"
    .endif
    .ifdef SPANISH
    .string "Los CUBONE llevan cráneos,\n"
    .string "¿verdad?\p"
    .string "¡La gente pagaría mucho por uno\n"
    .string "de ellos!$"
    .endif

