Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
	.string "Salut! Tu te rappelles de moi?\n"
	.string "Je suis un assistant du PROF. CHEN!\p"
	.string "Si tu attrapes dix POKéMON\n"
	.string "différents, je suis censé t'offrir…\p"
	.string "cette CS05!\p"
	.string "Alors {PLAYER}, as-tu attrapé au\n"
	.string "moins dix POKéMON différents?$"

Route2_EastBuilding_Text_GreatHereYouGo::
	.string "Super! Tu as {STR_VAR_3} POKéMON\n"
	.string "différents!\p"
	.string "Félicitations!\n"
	.string "Voici ta récompense!$"

Route2_EastBuilding_Text_ReceivedHM05FromAide::
	.string "{PLAYER} obtient\n"
	.string "CS05!$"

Route2_EastBuilding_Text_ExplainHM05::
	.string "La CS FLASH peut éclairer les\n"
	.string "endroits sombres.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
	.string "Si un POKéMON a appris FLASH,\n"
	.string "tu pourras traverser la GROTTE.$"

