Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
    .ifdef ENGLISH
    .string "Hi! Remember me?\n"
    .string "I'm one of PROF. OAK's AIDES.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on ten species, I'm supposed to\l"
    .string "give you a reward.\p"
    .string "PROF. OAK entrusted me with\n"
    .string "HM05 for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "ten kinds of POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¡Hola! ¿Te acuerdas de mí?\n"
    .string "¡Soy AYUDANTE del PROF. OAK!\p"
    .string "¡Si ya tienes 10 tipos de POKéMON,\n"
    .string "se supone que debería darte MO05!\p"
    .string "Dime, {PLAYER}. ¿Tienes ya al menos\n"
    .string "10 tipos de POKéMON?$"
    .endif

Route2_EastBuilding_Text_GreatHereYouGo::
    .ifdef ENGLISH
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"
    .endif
    .ifdef SPANISH
    .string "¡Bien! ¡Has logrado {STR_VAR_3} tipos\n"
    .string "de POKéMON!\p"
    .string "¡Enhorabuena!\n"
    .string "¡Aquí tienes!$"
    .endif

Route2_EastBuilding_Text_ReceivedHM05FromAide::
    .ifdef ENGLISH
    .string "{PLAYER} received HM05\n"
    .string "from the AIDE.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo la MO05\n"
    .string "de manos del AYUDANTE!$"
    .endif

Route2_EastBuilding_Text_ExplainHM05::
    .ifdef ENGLISH
    .string "HM05 contains the hidden move\n"
    .string "FLASH.\p"
    .string "FLASH lights up even the darkest\n"
    .string "of caves and dungeons.$"
    .endif
    .ifdef SPANISH
    .string "El DESTELLO de la MO ilumina hasta\n"
    .string "las más oscuras mazmorras.$"
    .endif

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
    .ifdef ENGLISH
    .string "Once a POKéMON learns FLASH, you\n"
    .string "can get through ROCK TUNNEL.$"
    .endif
    .ifdef SPANISH
    .string "Si un POKéMON aprende DESTELLO,\n"
    .string "podrás cruzar el TÚNEL ROCA.$"
    .endif

