Route17_Text_RaulIntro::
    .ifdef ENGLISH
    .string "There's no getting rich quick in\n"
    .string "battling kids.$"
    .endif
    .ifdef SPANISH
    .string "¡No compensa luchar con niños!$"
    .endif

Route17_Text_RaulDefeat::
    .ifdef ENGLISH
    .string "Burned out!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué chasco!$"
    .endif

Route17_Text_RaulPostBattle::
    .ifdef ENGLISH
    .string "You can find good stuff lying\n"
    .string "around on CYCLING ROAD.\p"
    .string "There's good money in picking them\n"
    .string "up and selling them.$"
    .endif
    .ifdef SPANISH
    .string "¡Por el CAMINO de BICIS\n"
    .string "hay cosas estupendas!\p"
    .string "¡Se puede ganar mucha pasta\n"
    .string "vendiendo lo que se encuentra!$"
    .endif

Route17_Text_IsaiahIntro::
    .ifdef ENGLISH
    .string "I'm mighty proud of my bod, kiddo.\n"
    .string "Come on!$"
    .endif
    .ifdef SPANISH
    .string "¿Y tú qué quieres?$"
    .endif

Route17_Text_IsaiahDefeat::
    .ifdef ENGLISH
    .string "Whoo!$"
    .endif
    .ifdef SPANISH
    .string "¡Uauuu!$"
    .endif

Route17_Text_IsaiahPostBattle::
    .ifdef ENGLISH
    .string "I could belly-bump you outta\n"
    .string "here!$"
    .endif
    .ifdef SPANISH
    .string "¡Podría echarte de aquí de\n"
    .string "un barrigazo!$"
    .endif

Route17_Text_VirgilIntro::
    .ifdef ENGLISH
    .string "You heading to FUCHSIA?$"
    .endif
    .ifdef SPANISH
    .string "¿Te diriges a CIUDAD FUCSIA?$"
    .endif

Route17_Text_VirgilDefeat::
    .ifdef ENGLISH
    .string "Crash and burn!$"
    .endif
    .ifdef SPANISH
    .string "¡Destrozado y vencido!$"
    .endif

Route17_Text_VirgilPostBattle::
    .ifdef ENGLISH
    .string "I love racing downhill!$"
    .endif
    .ifdef SPANISH
    .string "Me gusta pedalear cuesta abajo.$"
    .endif

Route17_Text_BillyIntro::
    .ifdef ENGLISH
    .string "We're BIKERS!\n"
    .string "We rule the roads, man!$"
    .endif
    .ifdef SPANISH
    .string "¡Somos los MOTORISTAS!\n"
    .string "¡Las estrellas de la autopista!$"
    .endif

Route17_Text_BillyDefeat::
    .ifdef ENGLISH
    .string "Smoked!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué trompazo!$"
    .endif

Route17_Text_BillyPostBattle::
    .ifdef ENGLISH
    .string "Are you looking for adventure?$"
    .endif
    .ifdef SPANISH
    .string "¿Vas en busca de aventuras?$"
    .endif

Route17_Text_NikolasIntro::
    .ifdef ENGLISH
    .string "Let VOLTORB electrify you!$"
    .endif
    .ifdef SPANISH
    .string "¡Deja que VOLTORB te dé un poco\n"
    .string "de su energía!$"
    .endif

Route17_Text_NikolasDefeat::
    .ifdef ENGLISH
    .string "Grounded out!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué bajón!$"
    .endif

Route17_Text_NikolasPostBattle::
    .ifdef ENGLISH
    .string "I got my VOLTORB at the abandoned\n"
    .string "POWER PLANT.$"
    .endif
    .ifdef SPANISH
    .string "¡Atrapé mis VOLTORB en la\n"
    .string "CENTRAL de ENERGÍA abandonada!$"
    .endif

Route17_Text_ZeekIntro::
    .ifdef ENGLISH
    .string "I leveled up my POKéMON, but it\n"
    .string "won't evolve. Why?$"
    .endif
    .ifdef SPANISH
    .string "¡Mi POKéMON no evoluciona!\n"
    .string "¿Por qué será?$"
    .endif

Route17_Text_ZeekDefeat::
    .ifdef ENGLISH
    .string "Why, you!$"
    .endif
    .ifdef SPANISH
    .string "¡Tú tienes la culpa!$"
    .endif

Route17_Text_ZeekPostBattle::
    .ifdef ENGLISH
    .string "Maybe some POKéMON need element\n"
    .string "STONES to evolve.$"
    .endif
    .ifdef SPANISH
    .string "Puede que ciertos POKéMON\n"
    .string "necesiten PIEDRAS para\l"
    .string "evolucionar.$"
    .endif

Route17_Text_JamalIntro::
    .ifdef ENGLISH
    .string "I need a little exercise!$"
    .endif
    .ifdef SPANISH
    .string "¡Necesito un poco de ejercicio!$"
    .endif

Route17_Text_JamalDefeat::
    .ifdef ENGLISH
    .string "Whew!\n"
    .string "Good workout!$"
    .endif
    .ifdef SPANISH
    .string "¡Ufff!\n"
    .string "¡Qué buen entrenamiento!$"
    .endif

Route17_Text_JamalPostBattle::
    .ifdef ENGLISH
    .string "I'm sure I lost weight there!$"
    .endif
    .ifdef SPANISH
    .string "¡Seguro que he perdido peso!$"
    .endif

Route17_Text_CoreyIntro::
    .ifdef ENGLISH
    .string "Be a rebel!$"
    .endif
    .ifdef SPANISH
    .string "¡Sé rebelde!$"
    .endif

Route17_Text_CoreyDefeat::
    .ifdef ENGLISH
    .string "Aaaargh!$"
    .endif
    .ifdef SPANISH
    .string "¡Aaaargh!$"
    .endif

Route17_Text_CoreyPostBattle::
    .ifdef ENGLISH
    .string "Be ready to fight for your beliefs!$"
    .endif
    .ifdef SPANISH
    .string "¡Prepárate para luchar\n"
    .string "por tus ideas!$"
    .endif

Route17_Text_JaxonIntro::
    .ifdef ENGLISH
    .string "Nice BIKE!\n"
    .string "How's it handle?$"
    .endif
    .ifdef SPANISH
    .string "¡Bonita BICI!\n"
    .string "¿Cómo se conduce?$"
    .endif

Route17_Text_JaxonDefeat::
    .ifdef ENGLISH
    .string "Shoot!$"
    .endif
    .ifdef SPANISH
    .string "¡Me dejas fuera de juego!$"
    .endif

Route17_Text_JaxonPostBattle::
    .ifdef ENGLISH
    .string "The slope makes it hard to steer.$"
    .endif
    .ifdef SPANISH
    .string "¡La pendiente dificulta\n"
    .string "la conducción!$"
    .endif

Route17_Text_WilliamIntro::
    .ifdef ENGLISH
    .string "Get lost, kid!\n"
    .string "I'm bushed!$"
    .endif
    .ifdef SPANISH
    .string "¡Lárgate!\n"
    .string "¡Estoy agotado!$"
    .endif

Route17_Text_WilliamDefeat::
    .ifdef ENGLISH
    .string "Are you satisfied?$"
    .endif
    .ifdef SPANISH
    .string "¿Te has quedado a gusto?$"
    .endif

Route17_Text_WilliamPostBattle::
    .ifdef ENGLISH
    .string "I need to catch a few z's!$"
    .endif
    .ifdef SPANISH
    .string "¡Tengo que recuperar sueño\n"
    .string "atrasado!$"
    .endif

Route17_Text_WatchOutForDiscardedItems::
    .ifdef ENGLISH
    .string "It's a notice.\p"
    .string "Watch out for discarded items.$"
    .endif
    .ifdef SPANISH
    .string "¡Aviso!\p"
    .string "¡Ojo con las cosas que hay\n"
    .string "por el suelo!$"
    .endif

Route17_Text_SameSpeciesGrowDifferentRates::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "All POKéMON are unique.\p"
    .string "Even POKéMON of the same species\n"
    .string "and level grow at different rates.$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "Todo POKéMON es único.\p"
    .string "Hasta los POKéMON del mismo tipo\n"
    .string "y nivel crecen a diferente ritmo.$"
    .endif

Route17_Text_PressBToStayInPlace::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "Press the B Button to stay in place\n"
    .string "while on a slope.$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "Pulsa el Botón B para no moverte\n"
    .string "sobre una pendiente.$"
    .endif

Route17_Text_RouteSign::
    .ifdef ENGLISH
    .string "ROUTE 17\n"
    .string "CELADON CITY - FUCHSIA CITY$"
    .endif
    .ifdef SPANISH
    .string "RUTA 17:\n"
    .string "CIUDAD AZULONA - CIUDAD FUCSIA$"
    .endif

Route17_Text_DontThrowGameThrowBalls::
    .ifdef ENGLISH
    .string "It's a notice!\p"
    .string "Don't throw the game, throw POKé\n"
    .string "BALLS instead!$"
    .endif
    .ifdef SPANISH
    .string "¡Aviso!\p"
    .string "¡No tires el juego, mejor tira\n"
    .string "POKé BALLS!$"
    .endif

Route17_Text_CyclingRoadSign::
    .ifdef ENGLISH
    .string "CYCLING ROAD\n"
    .string "Slope ends here!$"
    .endif
    .ifdef SPANISH
    .string "CAMINO DE BICIS\n"
    .string "¡La pendiente termina aquí!$"
    .endif

