Route17_Text_RaulIntro::
	.string "Es lohnt sich nicht, Kinder\n"
	.string "auszurauben!$"

Route17_Text_RaulDefeat::
	.string "Die Luft ist raus!$"

Route17_Text_RaulPostBattle::
	.string "Auf dem RADWEG liegen nützliche\n"
	.string "Items herum!$"

Route17_Text_IsaiahIntro::
	.string "Was willst du, Tröte?$"

Route17_Text_IsaiahDefeat::
	.string "Hoho!$"

Route17_Text_IsaiahPostBattle::
	.string "Ich könnte dich mit einem\n"
	.string "Bauchplatscher plattmachen!$"

Route17_Text_VirgilIntro::
	.string "Willst du nach FUCHSANIA CITY?$"

Route17_Text_VirgilDefeat::
	.string "Ich habe mein Bestes gegeben!$"

Route17_Text_VirgilPostBattle::
	.string "Ich liebe es, bergab Rennen zu\n"
	.string "fahren!$"

Route17_Text_BillyIntro::
	.string "Wir sind BIKER, Könige des\n"
	.string "Highways!$"

Route17_Text_BillyDefeat::
	.string "Ich bin voll auf die Nase\n"
	.string "gefallen!$"

Route17_Text_BillyPostBattle::
	.string "Suchst du das Abenteuer?$"

Route17_Text_NikolasIntro::
	.string "VOLTOBAL wird dich unter Strom\n"
	.string "setzen!$"

Route17_Text_NikolasDefeat::
	.string "Du hast mich geerdet!$"

Route17_Text_NikolasPostBattle::
	.string "Ich habe VOLTOBAL im verlassenen\n"
	.string "KRAFTWERK gefangen.$"

Route17_Text_ZeekIntro::
	.string "Mein POKéMON entwickelt sich nicht\n"
	.string "weiter!$"

Route17_Text_ZeekDefeat::
	.string "Heh, was sollte das?$"

Route17_Text_ZeekPostBattle::
	.string "Manche POKéMON benötigen\n"
	.string "spezielle STEINE, um sich zu\l"
	.string "entwickeln.$"

Route17_Text_JamalIntro::
	.string "Ich muss ein wenig abnehmen!$"

Route17_Text_JamalDefeat::
	.string "Puh!\n"
	.string "Eine gute Übung!$"

Route17_Text_JamalPostBattle::
	.string "Ich habe sicher an Gewicht\n"
	.string "verloren!$"

Route17_Text_CoreyIntro::
	.string "Sei ein Rebell!$"

Route17_Text_CoreyDefeat::
	.string "Arrrgh!$"

Route17_Text_CoreyPostBattle::
	.string "Setze dich für deine Ideale ein!$"

Route17_Text_JaxonIntro::
	.string "Du besitzt ein schickes FAHRRAD!\n"
	.string "Fährt es sich gut?$"

Route17_Text_JaxonDefeat::
	.string "Mist!$"

Route17_Text_JaxonPostBattle::
	.string "Das Gefälle macht das Lenken sehr\n"
	.string "schwer!$"

Route17_Text_WilliamIntro::
	.string "Zieh Leine!\n"
	.string "Ich bin erschöpft!$"

Route17_Text_WilliamDefeat::
	.string "Bist du nun zufrieden?$"

Route17_Text_WilliamPostBattle::
	.string "Ich muss mich eine Runde aufs Ohr\n"
	.string "legen!$"

Route17_Text_WatchOutForDiscardedItems::
	.string "Ein Hinweis!\p"
	.string "Achte auf weggeworfene Items!$"

Route17_Text_SameSpeciesGrowDifferentRates::
	.string "TIPPS FÜR TRAINER\p"
	.string "Jedes POKéMON ist einzigartig.\p"
	.string "Selbst gleiche POKéMON mit\n"
	.string "identischem Level unterscheiden\l"
	.string "sich voneinander.$"

Route17_Text_PressBToStayInPlace::
	.string "TIPPS FÜR TRAINER\p"
	.string "Drücke den B-Knopf, um auch bei\n"
	.string "Gefälle die Position zu halten.$"

Route17_Text_RouteSign::
	.string "ROUTE 17\n"
	.string "PRISMANIA CITY - FUCHSANIA CITY$"

Route17_Text_DontThrowGameThrowBalls::
	.string "Ein Hinweis!\p"
	.string "Gib niemals auf! Versuche dein\n"
	.string "Glück mit POKéBÄLLEN!$"

Route17_Text_CyclingRoadSign::
	.string "Der RADWEG endet hier!$"

