Route5_PokemonDayCare_Text_WantMeToRaiseMon::
    .ifdef ENGLISH
	.string "I run the DAY-CARE service.\p"
	.string "Would you like me to raise one of\n"
	.string "your POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "Esta GUARDERÍA es mía.\p"
    .string "¿Quieres que cuide de alguno\n"
    .string "de tus POKéMON?$"
    .endif

Route5_PokemonDayCare_Text_ComeAgain::
    .ifdef ENGLISH
	.string "Come again.$"
    .endif
    .ifdef SPANISH
    .string "Vuelve en otro momento.$"
    .endif

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
    .ifdef ENGLISH
	.string "Which POKéMON should I raise?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué POKéMON quieres que cuide?$"
    .endif

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
    .ifdef ENGLISH
	.string "Fine.\n"
	.string "Come anytime you like.$"
    .endif
    .ifdef SPANISH
    .string "Vale...\n"
    .string "Vuelve cuando quieras.$"
    .endif

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
    .ifdef ENGLISH
	.string "Fine, I'll look after your\n"
	.string "{STR_VAR_1} for a while.$"
    .endif
    .ifdef SPANISH
    .string "Muy bien, cuidaré de {STR_VAR_1}\n"
    .string "un rato.$"
    .endif

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
    .ifdef ENGLISH
	.string "Come see me in a while.$"
    .endif
    .ifdef SPANISH
    .string "Vuelve dentro de un rato.$"
    .endif

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
    .ifdef ENGLISH
	.string "You're back already?\p"
	.string "Your {STR_VAR_1} needs to spend\n"
	.string "some more time with me.$"
    .endif
    .ifdef SPANISH
    .string "¿Ya de vuelta?\p"
    .string "Tu {STR_VAR_1} aún necesita de mis\n"
    .string "cuidados.$"
    .endif

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
    .ifdef ENGLISH
	.string "You owe me ¥{STR_VAR_2} for the return\n"
	.string "of this POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "Me debes {STR_VAR_2}¥ por este\n"
    .string "POKéMON.$"
    .endif

Route5_PokemonDayCare_Text_ThankYouHeresMon::
    .ifdef ENGLISH
	.string "Thank you!\n"
	.string "Here's your POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Gracias!\n"
    .string "¡Aquí está tu POKéMON!$"
    .endif

Route5_PokemonDayCare_Text_PlayerGotMonBack::
    .ifdef ENGLISH
	.string "{PLAYER} got {STR_VAR_1} back\n"
	.string "from the DAY-CARE MAN.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recuperó a {STR_VAR_1}!$"
    .endif

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
    .ifdef ENGLISH
	.string "Oh? You only have one POKéMON\n"
	.string "with you.$"
    .endif
    .ifdef SPANISH
    .string "Sólo tienes un POKéMON contigo.$"
    .endif

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
    .ifdef ENGLISH
	.string "If you leave me that POKéMON,\n"
	.string "what will you battle with?$"
    .endif
    .ifdef SPANISH
    .string "Si me dejas ese POKéMON, no\n"
    .string "podrás entablar combates.$"
    .endif

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
    .ifdef ENGLISH
	.string "Your {STR_VAR_1} has grown a lot.\n"
	.string "Yes, quite a lot, I'd say.\p"
	.string "Let me see…\n"
	.string "By level, it's grown by {STR_VAR_2}.\p"
	.string "Aren't I great?$"
    .endif
    .ifdef SPANISH
    .string "¡Tu {STR_VAR_1} ha crecido mucho!\p"
    .string "¡Su nivel ha subido {STR_VAR_2}!\p"
    .string "¿No soy genial?$"
    .endif

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
    .ifdef ENGLISH
	.string "You can't take this POKéMON back\n"
	.string "if you've got no room for it.$"
    .endif
    .ifdef SPANISH
    .string "¡No tienes sitio para este POKéMON!$"
    .endif

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
    .ifdef ENGLISH
	.string "You don't have enough money.$"
    .endif
    .ifdef SPANISH
    .string "¡Oye, no tienes bastante dinero!$"
    .endif

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
    .string "きみの\n"
    .string "みてみるかね？$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
    .string "わるいけど　ひでんのわざを　もった\n"
    .string "ポケモンは　あずかれないなぁ$"
