SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
    .ifdef ENGLISH
    .string "Kyahaha!\n"
    .string "I'll flick you away effortlessly!$"
    .endif
    .ifdef SPANISH
    .string "¡Voy a acabar contigo en un abrir\n"
    .string "y cerrar de ojos!$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
    .ifdef ENGLISH
    .string "Tch!\n"
    .string "Too strong for me!$"
    .endif
    .ifdef SPANISH
    .string "¡Ufff... demasiado para mí!$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
    .ifdef ENGLISH
    .string "What's that?\n"
    .string "I don't act the way I look?\p"
    .string "Heh, that's a part of my strategy!$"
    .endif
    .ifdef SPANISH
    .string "¿Cómo? ¿Que las apariencias\n"
    .string "engañan?\p"
    .string "¡Eh, es parte de mi estrategia!$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
    .ifdef ENGLISH
    .string "Howdy!\n"
    .string "Are you a member of my fan club?$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, cara de bola!\n"
    .string "¿Eres de mi club de fans?$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
    .ifdef ENGLISH
    .string "Oh, so you're not a fan…\p"
    .string "Well, I can change that.\n"
    .string "Let me sing for you!$"
    .endif
    .ifdef SPANISH
    .string "O sea, que de fan nada...\p"
    .string "Pues ¿qué le vamos a hacer?\n"
    .string "¿Y si te canto un poco?$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
    .ifdef ENGLISH
    .string "Lalalah…\n"
    .string "My POKéMON, I send them out,\l"
    .string "all the girls scream and shout!$"
    .endif
    .ifdef SPANISH
    .string "Oye el boom, boom...\p"
    .string "Oye el boom, boom, boom, de mis\n"
    .string "POKéMON, ven y dime tú, no me\l"
    .string "digas no...$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
    .ifdef ENGLISH
    .string "This island is too spread out…\n"
    .string "It's not easy patrolling the place.$"
    .endif
    .ifdef SPANISH
    .string "Esta isla tiene una extensión muy\n"
    .string "particular, no es fácil patrullar.$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
    .ifdef ENGLISH
    .string "Uh-huh…$"
    .endif
    .ifdef SPANISH
    .string "Vaya...$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
    .ifdef ENGLISH
    .string "TRAINERS like you from cities,\n"
    .string "they sure are tough.\p"
    .string "You'll be headed for the TOWER,\n"
    .string "won't you?$"
    .endif
    .ifdef SPANISH
    .string "Los ENTRENADORES de ciudad,\n"
    .string "como tú, deben de ser fuertes.\p"
    .string "Tú irás a la TORRE, ¿no?$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
    .ifdef ENGLISH
    .string "I punish people who abuse\n"
    .string "POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡La gente que se pasa con los\n"
    .string "POKéMON se las ve conmigo!$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
    .ifdef ENGLISH
    .string "You don't seem to be a problem\n"
    .string "TRAINER.$"
    .endif
    .ifdef SPANISH
    .string "¡Tú te portas como debe ser!$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
    .ifdef ENGLISH
    .string "If you treat your POKéMON with\n"
    .string "kindness, they'll understand.$"
    .endif
    .ifdef SPANISH
    .string "Si tratas a los POKéMON con\n"
    .string "amabilidad, reaccionarán bien.$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
    .ifdef ENGLISH
    .string "EVE: I'll team up with JON and\n"
    .string "battle together.$"
    .endif
    .ifdef SPANISH
    .string "ELE: Yo formo equipo con RUS\n"
    .string "para luchar.$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
    .ifdef ENGLISH
    .string "EVE: Me and JON, we lost.\n"
    .string "Ehehe.$"
    .endif
    .ifdef SPANISH
    .string "ELE: Pues hemos perdido RUS\n"
    .string "y yo, je.$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
    .ifdef ENGLISH
    .string "EVE: I'm going to work harder with\n"
    .string "JON.$"
    .endif
    .ifdef SPANISH
    .string "ELE: Tengo que entrenarme más con\n"
    .string "RUS.$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
    .ifdef ENGLISH
    .string "EVE: I want to team up with JON\n"
    .string "when I battle you.\p"
    .string "Come back with two POKéMON, okay?$"
    .endif
    .ifdef SPANISH
    .string "ELE: Junto a RUS, me gustaría\n"
    .string "luchar contra ti.\p"
    .string "¡Pero necesitas al menos dos\n"
    .string "POKéMON!$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
    .ifdef ENGLISH
    .string "JON: When I'm with EVE, it feels\n"
    .string "like we could never lose.$"
    .endif
    .ifdef SPANISH
    .string "RUS: Cuando estoy con ELE,\n"
    .string "creo que no voy a perder nunca.$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
    .ifdef ENGLISH
    .string "JON: When I'm with EVE,\n"
    .string "it doesn't feel like I've lost!$"
    .endif
    .ifdef SPANISH
    .string "RUS: Cuando estoy con ELE,\n"
    .string "no tengo sensación de derrota.$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
    .ifdef ENGLISH
    .string "JON: When I'm with EVE, I feel\n"
    .string "giddy whether I win or lose.\p"
    .string "It's magical!$"
    .endif
    .ifdef SPANISH
    .string "RUS: Cuando estoy con ELE,\n"
    .string "me da igual ganar o perder.\p"
    .string "¡Es una sensación inexplicable!$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
    .ifdef ENGLISH
    .string "JON: If it's with EVE, I'll be\n"
    .string "happy to battle with you.\p"
    .string "So, I'd like to make it a\n"
    .string "two-on-two battle, if I may.$"
    .endif
    .ifdef SPANISH
    .string "RUS: Si es junto a ELE,\n"
    .string "me encantará luchar contra ti.\p"
    .string "¡Pero para eso, tendrás que tener\n"
    .string "al menos dos POKéMON!$"
    .endif

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
    .ifdef ENGLISH
    .string "SEVAULT CANYON ENTRANCE\p"
    .string "TRAINERS are asked to refrain from\n"
    .string "damaging plants in the CANYON.$"
    .endif
    .ifdef SPANISH
    .string "ENTRADA AL CAÑÓN SÉTANO\p"
    .string "Se ruega a los ENTRENADORES\n"
    .string "respetar la vegetación del CAÑÓN.$"
    .endif

