SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
    .string "¡Voy a acabar contigo en un abrir\n"
    .string "y cerrar de ojos!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
    .string "¡Ufff... demasiado para mí!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
    .string "¿Cómo? ¿Que las apariencias\n"
    .string "engañan?\p"
    .string "¡Eh, es parte de mi estrategia!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
    .string "¡Hola, cara de bola!\n"
    .string "¿Eres de mi club de fans?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
    .string "O sea, que de fan nada...\p"
    .string "Pues ¿qué le vamos a hacer?\n"
    .string "¿Y si te canto un poco?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
    .string "Oye el boom, boom...\p"
    .string "Oye el boom, boom, boom, de mis\n"
    .string "POKéMON, ven y dime tú, no me\l"
    .string "digas no...$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
    .string "Esta isla tiene una extensión muy\n"
    .string "particular, no es fácil patrullar.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
    .string "Vaya...$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
    .string "Los ENTRENADORES de ciudad,\n"
    .string "como tú, deben de ser fuertes.\p"
    .string "Tú irás a la TORRE, ¿no?$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
    .string "¡La gente que se pasa con los\n"
    .string "POKéMON se las ve conmigo!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
    .string "¡Tú te portas como debe ser!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
    .string "Si tratas a los POKéMON con\n"
    .string "amabilidad, reaccionarán bien.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
    .string "ELE: Yo formo equipo con RUS\n"
    .string "para luchar.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
    .string "ELE: Pues hemos perdido RUS\n"
    .string "y yo, je.$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
    .string "ELE: Tengo que entrenarme más con\n"
    .string "RUS.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
    .string "ELE: Junto a RUS, me gustaría\n"
    .string "luchar contra ti.\p"
    .string "¡Pero necesitas al menos dos\n"
    .string "POKéMON!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
    .string "RUS: Cuando estoy con ELE,\n"
    .string "creo que no voy a perder nunca.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
    .string "RUS: Cuando estoy con ELE,\n"
    .string "no tengo sensación de derrota.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
    .string "RUS: Cuando estoy con ELE,\n"
    .string "me da igual ganar o perder.\p"
    .string "¡Es una sensación inexplicable!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
    .string "RUS: Si es junto a ELE,\n"
    .string "me encantará luchar contra ti.\p"
    .string "¡Pero para eso, tendrás que tener\n"
    .string "al menos dos POKéMON!$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
    .string "ENTRADA AL CAÑÓN SÉTANO\p"
    .string "Se ruega a los ENTRENADORES\n"
    .string "respetar la vegetación del CAÑÓN.$"
