SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
	.string "Hugh!\n"
	.string "Ich besiege dich mit links!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
	.string "Tss!\n"
	.string "Zu stark für mich!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
	.string "Wie war das?\n"
	.string "Ich handle nicht nach meinem\l"
	.string "Aussehen?\l"
	.string "Heh, das ist ein Teil meiner\l"
	.string "Strategie!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
	.string "Servus!\n"
	.string "Bist du in meinem Fanclub?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
	.string "Oh, du bist kein Fan…\p"
	.string "Nun, das kann ich ändern.\n"
	.string "Ich singe nur für dich!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
	.string "Lalala…\n"
	.string "Ich schicke meine POKéMON\l"
	.string "hinaus und die Mädchen schreien!$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
	.string "Die Insel ist so weitläufig…\n"
	.string "Es ist schwierig, sie zu bewachen.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
	.string "Uh-uh…$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
	.string "TRAINER, die wie du aus Städten\n"
	.string "kommen, sind stark.\p"
	.string "Du bist auf dem Weg zum TURM, \n"
	.string "nicht wahr?$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
	.string "Ich bestrafe Leute, die POKéMON\n"
	.string "missbrauchen!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
	.string "Du scheinst kein Problem dar-\n"
	.string "zustellen, TRAINER.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
	.string "Behandelst du deine POKéMON\n"
	.string "freundlich, verstehen sie dich.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
	.string "TIZIA: Ich bilde ein Team mit TILL\n"
	.string "und wir kämpfen gemeinsam.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
	.string "TIZIA: TILL und ich haben\n"
	.string "verloren. Hehe!$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
	.string "TIZIA: Ich muss härter mit TILL\n"
	.string "trainieren.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
	.string "TIZIA: Ich möchte gemeinsam\n"
	.string "mit TILL gegen dich antreten.\p"
	.string "Komme mit zwei POKéMON wieder!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
	.string "TILL: Wenn ich an der Seite von\n"
	.string "TIZIA bin, fühle ich, dass wir\l"
	.string "nicht verlieren können…$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
	.string "TILL: Wenn ich an der Seite von\n"
	.string "TIZIA bin, fühle ich, dass wir\l"
	.string "nicht verloren haben…$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
	.string "TILL: Wenn ich an der Seite von\n"
	.string "TIZIA bin, ist mir schwindelig,\l"
	.string "egal, ob ich gewinne oder verliere.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
	.string "TILL: Wenn ich mit TIZIA gegen\n"
	.string "dich kämpfe, bin ich glücklich.\p"
	.string "Ich möchte also einen Zwei-gegen-\n"
	.string "Zwei-Kampf mit dir austragen.$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
	.string "EINGANG zur 7-SCHATZSCHLUCHT\p"
	.string "TRAINER werden gebeten, die\n"
	.string "Pflanzen in der SCHLUCHT\l"
	.string "nicht zu beschädigen!$"

