Route12_Text_MonSprawledOutInSlumber::
    .string "¡Un POKéMON dormido bloquea\n"
    .string "el camino!$"

Text_SnorlaxWokeUp::
    .string "¡SNORLAX se ha despertado!\p"
    .string "¡Se ha enfadado mucho\n"
    .string "y te quiere atacar!$"

Text_SnorlaxReturnedToMountains::
    .string "SNORLAX se ha calmado.\n"
    .string "¡Y tras bostezar se ha marchado\l"
    .string "a las montañas!$"

Text_WantToUsePokeFlute::
    .string "¿Quieres usar la POKé FLAUTA?$"

Text_PlayedPokeFlute::
    .string "{PLAYER} tocó la POKé FLAUTA.$"

Route12_Text_NedIntro::
    .string "¡Bien!\n"
    .string "¡Ha picado algo!$"

Route12_Text_NedDefeat::
    .string "¡Bah!\n"
    .string "¡Era muy pequeñajo!$"

Route12_Text_NedPostBattle::
    .string "¡Alto!\n"
    .string "¡Mi sedal está enganchado!$"

Route12_Text_ChipIntro::
    .string "¡Ten paciencia!\n"
    .string "¡Pescar requiere tiempo!$"

Route12_Text_ChipDefeat::
    .string "¡Ése se escapó!$"

Route12_Text_ChipPostBattle::
    .string "¡Con una CAÑA mejor podría pescar\n"
    .string "mejores POKéMON!$"

Route12_Text_JustinIntro::
    .string "¿Has encontrado una PIEDRA LUNAR?$"

Route12_Text_JustinDefeat::
    .string "¡Auuuu!$"

Route12_Text_JustinPostBattle::
    .string "¡Podría haber transformado a mis\n"
    .string "POKéMON con una PIEDRA LUNAR!\p"
    .string "¡Y podría haber ganado!$"

Route12_Text_LucaIntro::
    .string "¡Soy un experto en electricidad!\p"
    .string "Pero no sé nada sobre los POKéMON\n"
    .string "de mar.$"

Route12_Text_LucaDefeat::
    .string "¡Se acabó!$"

Route12_Text_LucaPostBattle::
    .string "El agua conduce la electricidad.\n"
    .string "¡Deberías poder atrapar a los\l"
    .string "POKéMON de mar!$"

Route12_Text_HankIntro::
    .string "¡El PESCADOR LOCO contra alguien\n"
    .string "que no tiene idea sobre POKéMON!$"

Route12_Text_HankDefeat::
    .string "¡Te has pasado!$"

Route12_Text_HankPostBattle::
    .string "¡Me has ganado con los POKéMON,\n"
    .string "pero yo soy muy bueno pescando!\p"
    .string "Supongo que hay que hacer lo que\n"
    .string "mejor se le da a cada uno...$"

Route12_Text_ElliotIntro::
    .string "A mí me encanta pescar, ¡pero\n"
    .string "es que no pican ni a la de tres!$"

Route12_Text_ElliotDefeat::
    .string "No es fácil...$"

Route12_Text_ElliotPostBattle::
    .string "Está bien.\n"
    .string "Perder ya no me importa.$"

Route12_Text_AndrewIntro::
    .string "¡Nunca se sabe lo que puedes\n"
    .string "pescar!$"

Route12_Text_AndrewDefeat::
    .string "¡He perdido!$"

Route12_Text_AndrewPostBattle::
    .string "Es fácil pescar MAGIKARP,\n"
    .string "¡son tan débiles!$"

Route12_Text_RouteSign::
    .string "RUTA 12:\n"
    .string "LAVANDA, al norte$"

Route12_Text_SportfishingArea::
    .string "ZONA DE PESCA$"

Route12_Text_JesIntro::
    .string "ARE: Si gano, le pediré a AGA\n"
    .string "que se case conmigo.$"

Route12_Text_JesDefeat::
    .string "ARE: ¿Puedes dejarnos ganar,\n"
    .string "por favor?$"

Route12_Text_JesPostBattle::
    .string "ARE: AGA, ¡lo siento, cariño!$"

Route12_Text_JesNotEnoughMons::
    .string "ARE: AGA y yo vamos a estar juntos\n"
    .string "toda la vida.\p"
    .string "¡Y no lucharemos hasta que no\n"
    .string "tengas dos POKéMON!$"

Route12_Text_GiaIntro::
    .string "AGA: Oye, ARE...\p"
    .string "Si ganamos, ¡me caso contigo!$"

Route12_Text_GiaDefeat::
    .string "AGA: Oh... ¿Por qué?$"

Route12_Text_GiaPostBattle::
    .string "AGA: ¡ARE, eres medio lelo! ¡Todo\n"
    .string "se ha fastidiado por tu culpa!$"

Route12_Text_GiaNotEnoughMons::
    .string "AGA: ¡No pienso luchar sin mi ARE!\p"
    .string "¿No tienes dos POKéMON?$"
