Route12_Text_MonSprawledOutInSlumber::
    .ifdef ENGLISH
    .string "A POKéMON is sprawled out in\n"
    .string "a deep and comfortable slumber.$"
    .endif
    .ifdef SPANISH
    .string "¡Un POKéMON dormido bloquea\n"
    .string "el camino!$"
    .endif

Text_SnorlaxWokeUp::
    .ifdef ENGLISH
    .string "SNORLAX woke up!\p"
    .string "It attacked in a grumpy rage!$"
    .endif
    .ifdef SPANISH
    .string "¡SNORLAX se ha despertado!\p"
    .string "¡Se ha enfadado mucho\n"
    .string "y te quiere atacar!$"
    .endif

Text_SnorlaxReturnedToMountains::
    .ifdef ENGLISH
    .string "SNORLAX calmed down.\n"
    .string "It gave a huge yawn…\l"
    .string "And returned to the mountains.$"
    .endif
    .ifdef SPANISH
    .string "SNORLAX se ha calmado.\n"
    .string "¡Y tras bostezar se ha marchado\l"
    .string "a las montañas!$"
    .endif

Text_WantToUsePokeFlute::
    .ifdef ENGLISH
    .string "Want to use the POKé FLUTE?$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres usar la POKé FLAUTA?$"
    .endif

Text_PlayedPokeFlute::
    .ifdef ENGLISH
    .string "{PLAYER} played the POKé FLUTE.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} tocó la POKé FLAUTA.$"
    .endif

Route12_Text_NedIntro::
    .ifdef ENGLISH
    .string "Yeah!\n"
    .string "I got a bite here!$"
    .endif
    .ifdef SPANISH
    .string "¡Bien!\n"
    .string "¡Ha picado algo!$"
    .endif

Route12_Text_NedDefeat::
    .ifdef ENGLISH
    .string "Tch!\n"
    .string "Just a small fry…$"
    .endif
    .ifdef SPANISH
    .string "¡Bah!\n"
    .string "¡Era muy pequeñajo!$"
    .endif

Route12_Text_NedPostBattle::
    .ifdef ENGLISH
    .string "Hang on!\n"
    .string "My line's snagged!$"
    .endif
    .ifdef SPANISH
    .string "¡Alto!\n"
    .string "¡Mi sedal está enganchado!$"
    .endif

Route12_Text_ChipIntro::
    .ifdef ENGLISH
    .string "Be patient.\n"
    .string "Fishing is a waiting game.$"
    .endif
    .ifdef SPANISH
    .string "¡Ten paciencia!\n"
    .string "¡Pescar requiere tiempo!$"
    .endif

Route12_Text_ChipDefeat::
    .ifdef ENGLISH
    .string "That one got away!$"
    .endif
    .ifdef SPANISH
    .string "¡Ése se escapó!$"
    .endif

Route12_Text_ChipPostBattle::
    .ifdef ENGLISH
    .string "With a better ROD, I could catch\n"
    .string "better POKéMON…$"
    .endif
    .ifdef SPANISH
    .string "¡Con una CAÑA mejor podría pescar\n"
    .string "mejores POKéMON!$"
    .endif

Route12_Text_JustinIntro::
    .ifdef ENGLISH
    .string "I'm searching for a MOON STONE.\n"
    .string "Have you found one?$"
    .endif
    .ifdef SPANISH
    .string "¿Has encontrado una PIEDRA LUNAR?$"
    .endif

Route12_Text_JustinDefeat::
    .ifdef ENGLISH
    .string "Oww!$"
    .endif
    .ifdef SPANISH
    .string "¡Auuuu!$"
    .endif

Route12_Text_JustinPostBattle::
    .ifdef ENGLISH
    .string "I could have made my POKéMON\n"
    .string "evolve with a MOON STONE.\p"
    .string "I would have won then, I bet.$"
    .endif
    .ifdef SPANISH
    .string "¡Podría haber transformado a mis\n"
    .string "POKéMON con una PIEDRA LUNAR!\p"
    .string "¡Y podría haber ganado!$"
    .endif

Route12_Text_LucaIntro::
    .ifdef ENGLISH
    .string "Electricity is my specialty.\p"
    .string "I don't know a thing about POKéMON\n"
    .string "of the sea, though.$"
    .endif
    .ifdef SPANISH
    .string "¡Soy un experto en electricidad!\p"
    .string "Pero no sé nada sobre los POKéMON\n"
    .string "de mar.$"
    .endif

Route12_Text_LucaDefeat::
    .ifdef ENGLISH
    .string "Unplugged!$"
    .endif
    .ifdef SPANISH
    .string "¡Se acabó!$"
    .endif

Route12_Text_LucaPostBattle::
    .ifdef ENGLISH
    .string "Water conducts electricity, so you\n"
    .string "should zap sea POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "El agua conduce la electricidad.\n"
    .string "¡Deberías poder atrapar a los\l"
    .string "POKéMON de mar!$"
    .endif

Route12_Text_HankIntro::
    .ifdef ENGLISH
    .string "The FISHING FOOL versus POKéMON\n"
    .string "KID!$"
    .endif
    .ifdef SPANISH
    .string "¡El PESCADOR LOCO contra alguien\n"
    .string "que no tiene idea sobre POKéMON!$"
    .endif

Route12_Text_HankDefeat::
    .ifdef ENGLISH
    .string "Touch too much!$"
    .endif
    .ifdef SPANISH
    .string "¡Te has pasado!$"
    .endif

Route12_Text_HankPostBattle::
    .ifdef ENGLISH
    .string "I guess you get to be good at\n"
    .string "what you like.\p"
    .string "Well, you beat me at POKéMON,\n"
    .string "but you can't top me at fishing.$"
    .endif
    .ifdef SPANISH
    .string "¡Me has ganado con los POKéMON,\n"
    .string "pero yo soy muy bueno pescando!\p"
    .string "Supongo que hay que hacer lo que\n"
    .string "mejor se le da a cada uno...$"
    .endif

Route12_Text_ElliotIntro::
    .ifdef ENGLISH
    .string "I love fishing, don't get me wrong.\p"
    .string "But it'd be best if I also had more\n"
    .string "work.$"
    .endif
    .ifdef SPANISH
    .string "A mí me encanta pescar, ¡pero\n"
    .string "es que no pican ni a la de tres!$"
    .endif

Route12_Text_ElliotDefeat::
    .ifdef ENGLISH
    .string "It's not easy…$"
    .endif
    .ifdef SPANISH
    .string "No es fácil...$"
    .endif

Route12_Text_ElliotPostBattle::
    .ifdef ENGLISH
    .string "It's all right.\n"
    .string "Losing doesn't bug me anymore.$"
    .endif
    .ifdef SPANISH
    .string "Está bien.\n"
    .string "Perder ya no me importa.$"
    .endif

Route12_Text_AndrewIntro::
    .ifdef ENGLISH
    .string "What's catching?\p"
    .string "You never know what you could\n"
    .string "catch!$"
    .endif
    .ifdef SPANISH
    .string "¡Nunca se sabe lo que puedes\n"
    .string "pescar!$"
    .endif

Route12_Text_AndrewDefeat::
    .ifdef ENGLISH
    .string "Lost it!$"
    .endif
    .ifdef SPANISH
    .string "¡He perdido!$"
    .endif

Route12_Text_AndrewPostBattle::
    .ifdef ENGLISH
    .string "What, MAGIKARP?\p"
    .string "I catch them all the time, sure.\n"
    .string "But, boy are they wimpy.$"
    .endif
    .ifdef SPANISH
    .string "Es fácil pescar MAGIKARP,\n"
    .string "¡son tan débiles!$"
    .endif

Route12_Text_RouteSign::
    .ifdef ENGLISH
    .string "ROUTE 12 \n"
    .string "North to LAVENDER$"
    .endif
    .ifdef SPANISH
    .string "RUTA 12:\n"
    .string "LAVANDA, al norte$"
    .endif

Route12_Text_SportfishingArea::
    .ifdef ENGLISH
    .string "SPORTFISHING AREA$"
    .endif
    .ifdef SPANISH
    .string "ZONA DE PESCA$"
    .endif

Route12_Text_JesIntro::
    .ifdef ENGLISH
    .string "JES: If I win, I'm going to\n"
    .string "propose to GIA.$"
    .endif
    .ifdef SPANISH
    .string "ARE: Si gano, le pediré a AGA\n"
    .string "que se case conmigo.$"
    .endif

Route12_Text_JesDefeat::
    .ifdef ENGLISH
    .string "JES: Oh, please, why couldn't you\n"
    .string "let us win?$"
    .endif
    .ifdef SPANISH
    .string "ARE: ¿Puedes dejarnos ganar,\n"
    .string "por favor?$"
    .endif

Route12_Text_JesPostBattle::
    .ifdef ENGLISH
    .string "JES: Oh, GIA, forgive me,\n"
    .string "my love!$"
    .endif
    .ifdef SPANISH
    .string "ARE: AGA, ¡lo siento, cariño!$"
    .endif

Route12_Text_JesNotEnoughMons::
    .ifdef ENGLISH
    .string "JES: GIA and I, we'll be\n"
    .string "together forever.\p"
    .string "We won't battle unless you have\n"
    .string "two POKéMON of your own.$"
    .endif
    .ifdef SPANISH
    .string "ARE: AGA y yo vamos a estar juntos\n"
    .string "toda la vida.\p"
    .string "¡Y no lucharemos hasta que no\n"
    .string "tengas dos POKéMON!$"
    .endif

Route12_Text_GiaIntro::
    .ifdef ENGLISH
    .string "GIA: Hey, JES…\p"
    .string "If we win, I'll marry you!$"
    .endif
    .ifdef SPANISH
    .string "AGA: Oye, ARE...\p"
    .string "Si ganamos, ¡me caso contigo!$"
    .endif

Route12_Text_GiaDefeat::
    .ifdef ENGLISH
    .string "GIA: Oh, but why?$"
    .endif
    .ifdef SPANISH
    .string "AGA: Oh... ¿Por qué?$"
    .endif

Route12_Text_GiaPostBattle::
    .ifdef ENGLISH
    .string "GIA: JES, you silly!\n"
    .string "You ruined this!$"
    .endif
    .ifdef SPANISH
    .string "AGA: ¡ARE, eres medio lelo! ¡Todo\n"
    .string "se ha fastidiado por tu culpa!$"
    .endif

Route12_Text_GiaNotEnoughMons::
    .ifdef ENGLISH
    .string "GIA: I can't bear to battle\n"
    .string "without my JES!\p"
    .string "Don't you have one more POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "AGA: ¡No pienso luchar sin mi ARE!\p"
    .string "¿No tienes dos POKéMON?$"
    .endif
