Route12_Text_MonSprawledOutInSlumber::
	.string "Ein schlafendes POKéMON\n"
	.string "versperrt den Weg!$"

Text_SnorlaxWokeUp::
	.string "RELAXO ist aufgewacht!\p"
	.string "Es ist brummig und greift\n"
	.string "verschlafen an!$"

Text_SnorlaxReturnedToMountains::
	.string "RELAXO hat sich wieder beruhigt!\n"
	.string "Es gähnt und läuft in die Berge\l"
	.string "zurück!$"

Text_WantToUsePokeFlute::
	.string "Die POKéFLÖTE spielen?$"

Text_PlayedPokeFlute::
	.string "{PLAYER} spielt die POKéFLÖTE.$"

Route12_Text_NedIntro::
	.string "Cool!\n"
	.string "Mir ist etwas ins Netz gegangen!$"

Route12_Text_NedDefeat::
	.string "Mist!\n"
	.string "Bloß ein kleiner Fisch!$"

Route12_Text_NedPostBattle::
	.string "Irgendwann werde ich den großen\n"
	.string "Fang machen!$"

Route12_Text_ChipIntro::
	.string "Nur mit der Ruhe!\n"
	.string "Als Angler muss man geduldig sein!$"

Route12_Text_ChipDefeat::
	.string "Der ist mir entwischt!$"

Route12_Text_ChipPostBattle::
	.string "Hätte ich eine bessere ANGEL,\n"
	.string "würde ich bessere POKéMON fangen!$"

Route12_Text_JustinIntro::
	.string "Besitzt du einen MONDSTEIN?$"

Route12_Text_JustinDefeat::
	.string "Aua!$"

Route12_Text_JustinPostBattle::
	.string "Wenn ich einen MONDSTEIN hätte,\n"
	.string "könnten sich meine POKéMON\l"
	.string "weiterentwickeln!$"

Route12_Text_LucaIntro::
	.string "Elektrizität ist meine Stärke!$"

Route12_Text_LucaDefeat::
	.string "Stromkreis unterbrochen!$"

Route12_Text_LucaPostBattle::
	.string "Wasser leitet Elektrizität. Greife\n"
	.string "WASSER-POKéMON mit Elektrizität an!$"

Route12_Text_HankIntro::
	.string "Der ANGELKÖNIG gegen das POKéMON-\n"
	.string "KIND!$"

Route12_Text_HankDefeat::
	.string "Das war spitze!$"

Route12_Text_HankPostBattle::
	.string "Von POKéMON verstehst du sehr\n"
	.string "viel, doch ich bin der bessere\l"
	.string "Angler!$"

Route12_Text_ElliotIntro::
	.string "Eigentlich würde ich lieber\n"
	.string "arbeiten...$"

Route12_Text_ElliotDefeat::
	.string "Das war wahrlich kein\n"
	.string "Zuckerschlecken!$"

Route12_Text_ElliotPostBattle::
	.string "O.K., mit der Zeit gewöhnt man sich\n"
	.string "daran, zu verlieren!$"

Route12_Text_AndrewIntro::
	.string "Man weiß nie, was der nächste Fang\n"
	.string "sein wird!$"

Route12_Text_AndrewDefeat::
	.string "Ich habe verloren!$"

Route12_Text_AndrewPostBattle::
	.string "Ich fange immer KARPADOR. Doch\n"
	.string "sie sind so schwach!$"

Route12_Text_RouteSign::
	.string "ROUTE 12\n"
	.string "NORDEN: LAVANDIA$"

Route12_Text_SportfishingArea::
	.string "SPORTANGEL-ZONE$"

Route12_Text_JesIntro::
	.string "DENIZ: Falls ich gewinne, mache\n"
	.string "ich SIRA einen Heiratsantrag!$"

Route12_Text_JesDefeat::
	.string "DENIZ: Oh, Mist! Warum konntest du\n"
	.string "uns nicht gewinnen lassen?$"

Route12_Text_JesPostBattle::
	.string "DENIZ: OH, SIRA, meine Liebste,\n"
	.string "verzeih mir!$"

Route12_Text_JesNotEnoughMons::
	.string "DENIZ: SIRA und ich werden für\n"
	.string "immer zusammen sein.\p"
	.string "Wir werden nicht kämpfen, ehe du\n"
	.string "nicht zwei POKéMON mitbringst.$"

Route12_Text_GiaIntro::
	.string "SIRA: HEH, DENIZ…\p"
	.string "wenn wir gewinnen, heiraten wir!$"

Route12_Text_GiaDefeat::
	.string "SIRA: Aber warum nur?$"

Route12_Text_GiaPostBattle::
	.string "SIRA: DENIZ, du Dummerchen!\n"
	.string "Du hast es vermasselt!$"

Route12_Text_GiaNotEnoughMons::
	.string "SIRA: Ich ertrage es nicht, ohne\n"
	.string "meinen DENIZ zu kämpfen.\p"
	.string "Hast du nicht noch ein weiteres\n"
	.string "POKéMON?$"

