SaffronCity_Gym_Text_SabrinaIntro::
	.string "Eine Vision hat mir deine Ankunft\n"
	.string "vorausgesagt!\p"
	.string "Ich beherrsche die PSYCHOKINESE,\n"
	.string "seit ich ein Kind war.\p"
	.string "Zunächst habe ich gelernt, mit\n"
	.string "PSYCHOKINESE Löffel zu verbiegen.\p"
	.string "Ich verabscheue den Kampf!\n"
	.string "Aber wenn du es wünschst, beweise\l"
	.string "ich dir meine Kräfte!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

SaffronCity_Gym_Text_SabrinaDefeat::
	.string "Ich bin erschüttert!\n"
	.string "Aber verloren ist verloren.\p"
	.string "Ich muss gestehen, ich habe mich\n"
	.string "nicht allzu sehr angestrengt!\p"
	.string "Ich schenke dir den SUMPFORDEN!$"

SaffronCity_Gym_Text_SabrinaPostBattle::
	.string "Theoretisch könnte jeder die\n"
	.string "PSYCHOKINESE erlernen.\p"
	.string "Viele wissen es nur nicht!$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
	.string "Der SUMPFORDEN lässt POKéMON bis\n"
	.string "Level 70 deinen Befehlen folgen!\p"
	.string "Stärkere POKéMON könnten sich dir\n"
	.string "widersetzen und deine Befehle\l"
	.string "ignorieren!\p"
	.string "Achte darauf, dass du deine\n"
	.string "POKéMON jederzeit unter Kontrolle\l"
	.string "hast!\p"
	.string "Warte! Nimm noch diese TM von mir!$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
	.string "{PLAYER} erhält\n"
	.string "TM04!$"

SaffronCity_Gym_Text_ExplainTM04::
	.string "TM04 ist GEDANKENGUT!\p"
	.string "Das POKéMON konzentriert sich,\n"
	.string "um sowohl den SP. ANG.\l"
	.string "als auch die SP. VER. zu\l"
	.string "steigern.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
	.string "Dein Rucksack ist zu voll!$"

SaffronCity_Gym_Text_AmandaIntro::
	.string "SABRINA ist jünger als ich.\n"
	.string "Trotzdem habe ich Respekt vor ihr!$"

SaffronCity_Gym_Text_AmandaDefeat::
	.string "Ich bin nicht gut genug!$"

SaffronCity_Gym_Text_AmandaPostBattle::
	.string "Sind zwei Gegner gleich stark, so\n"
	.string "wird der entschlossenere Kämpfer\l"
	.string "gewinnen!\p"
	.string "Wenn du SABRINA schlagen willst,\n"
	.string "konzentriere dich auf den Sieg!$"

SaffronCity_Gym_Text_JohanIntro::
	.string "Machen dir unsere PSYKRÄFTE Angst?$"

SaffronCity_Gym_Text_JohanDefeat::
	.string "Ich glaube es nicht:\n"
	.string "Ich hab verloren!$"

SaffronCity_Gym_Text_JohanPostBattle::
	.string "PSYCHO-POKéMON fürchten sich nur\n"
	.string "vor Käfern und Geistern!$"

SaffronCity_Gym_Text_StacyIntro::
	.string "POKéMON passen sich ihrem TRAINER\n"
	.string "an.\p"
	.string "Deine POKéMON müssen demnach sehr\n"
	.string "zäh sein!$"

SaffronCity_Gym_Text_StacyDefeat::
	.string "Ich wusste es!$"

SaffronCity_Gym_Text_StacyPostBattle::
	.string "Meine POKéMON müssen stärkere\n"
	.string "Attacken lernen!$"

SaffronCity_Gym_Text_TyronIntro::
	.string "Du weißt, dass man\n"
	.string "mit Stärke allein\l"
	.string "nicht weit kommt,\l"
	.string "oder?$"

SaffronCity_Gym_Text_TyronDefeat::
	.string "Das ist unfassbar!$"

SaffronCity_Gym_Text_TyronPostBattle::
	.string "SABRINA hat den KARATE-MEISTER in\n"
	.string "der ARENA nebenan besiegt!$"

SaffronCity_Gym_Text_TashaIntro::
	.string "Du gegen mich!\n"
	.string "Unsere POKéMON sollen kämpfen!$"

SaffronCity_Gym_Text_TashaDefeat::
	.string "Ich habe nun doch verloren!$"

SaffronCity_Gym_Text_TashaPostBattle::
	.string "Ich ahnte, dass es passieren\n"
	.string "würde!$"

SaffronCity_Gym_Text_CameronIntro::
	.string "Obwohl SABRINA noch jung ist, ist\n"
	.string "sie unsere ARENALEITERIN!\p"
	.string "Wir lassen dich nicht einfach so zu\n"
	.string "ihr gehen!$"

SaffronCity_Gym_Text_CameronDefeat::
	.string "Ich habe die Konzentration\n"
	.string "verloren!$"

SaffronCity_Gym_Text_CameronPostBattle::
	.string "In SAFFRONIA CITY gab es zwei\n"
	.string "POKéMON-ARENEN.\p"
	.string "Allerdings hat das KAMPF-DOJO den\n"
	.string "Status als POKéMON-ARENA verloren,\l"
	.string "weil wir die TRAINER besiegten!$"

SaffronCity_Gym_Text_PrestonIntro::
	.string "Die POKéMON in der ARENA von\n"
	.string "SAFFRONIA CITY sind für ihre\l"
	.string "übernatürlichen Kräfte bekannt!\p"
	.string "Ich weiß, dass du SABRINA\n"
	.string "herausfordern möchtest!$"

SaffronCity_Gym_Text_PrestonDefeat::
	.string "Arrrgh!$"

SaffronCity_Gym_Text_PrestonPostBattle::
	.string "Ich habe deine Gedanken gelesen!$"

SaffronCity_Gym_Text_GymGuyAdvice::
	.string "Heh!\n"
	.string "Warte, du Champion in spe!\p"
	.string "Die POKéMON von SABRINA benutzen\n"
	.string "PSYCHOKINESE anstelle von\l"
	.string "physischen Kräften!\p"
	.string "KAMPF-POKéMON sind PSYCHOKINESE\n"
	.string "nicht gewachsen!\p"
	.string "Sie haben nicht einmal den Hauch\n"
	.string "einer Chance!$"

SaffronCity_Gym_Text_GymGuyPostVictory::
	.string "PSYCHOKINESE?\p"
	.string "Wenn ich sie hätte, würde ich in\n"
	.string "der Spielhalle reich werden!$"

SaffronCity_Gym_Text_GymStatue::
	.string "SAFFRONIA POKéMON-ARENA\n"
	.string "LEITUNG: SABRINA\p"
	.string "BISHERIGE SIEGER:\n"
	.string "{RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
	.string "SAFFRONIA POKéMON-ARENA\n"
	.string "LEITUNG: SABRINA\p"
	.string "BISHERIGE SIEGER:\n"
	.string "{RIVAL}, {PLAYER}$"

