SaffronCity_Gym_Text_SabrinaIntro::
    .ifdef ENGLISH
    .string "I had a vision of your arrival.\p"
    .string "I have had psychic powers since\n"
    .string "I was a child.\p"
    .string "It started when a spoon I\n"
    .string "carelessly tossed, bent.\p"
    .string "I dislike battling, but if you wish,\n"
    .string "I will show you my powers!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif
    .ifdef SPANISH
    .string "¡He visto que venías!\p"
    .string "¡Tengo poderes psíquicos desde\n"
    .string "que era niña!\p"
    .string "Primero aprendí a doblar cucharas\n"
    .string "con la mente.\p"
    .string "¡Odio luchar, pero si quieres\n"
    .string "puedo enseñarte mis poderes!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif

SaffronCity_Gym_Text_SabrinaDefeat::
    .ifdef ENGLISH
    .string "This loss shocks me!\n"
    .string "But, a loss is a loss.\p"
    .string "I admit, I didn't work hard enough\n"
    .string "to win.\p"
    .string "Your victory has earned you the\n"
    .string "MARSHBADGE.$"
    .endif
    .ifdef SPANISH
    .string "¡Estoy impresionada!\n"
    .string "Acepto mi derrota.\p"
    .string "¡Admito que no he sido lo bastante\n"
    .string "fuerte y por eso he perdido!\p"
    .string "¡Has ganado la MEDALLA PANTANO!$"
    .endif

SaffronCity_Gym_Text_SabrinaPostBattle::
    .ifdef ENGLISH
    .string "Psychic power isn't something that\n"
    .string "only a few people have.\p"
    .string "Everyone has psychic power.\n"
    .string "People just don't realize it.$"
    .endif
    .ifdef SPANISH
    .string "Todo el mundo tiene poderes\n"
    .string "mentales, pero la gente no lo\l"
    .string "sabe.\p"
    .string "La mente es muy poderosa, pero\n"
    .string "no todo el mundo la aprovecha.$"
    .endif

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
    .ifdef ENGLISH
    .string "The MARSHBADGE makes POKéMON up\n"
    .string "to Lv. 70 obey you.\p"
    .string "Stronger POKéMON will become wild,\n"
    .string "ignoring your orders in battle.\p"
    .string "Just don't raise your POKéMON too\n"
    .string "much to avoid that problem.\p"
    .string "Wait, please take this TM with you.$"
    .endif
    .ifdef SPANISH
    .string "¡Con la MEDALLA PANTANO, todo\n"
    .string "POKéMON con nivel inferior a 70 te\l"
    .string "obedecerá!\p"
    .string "¡Los POKéMON más fuertes\n"
    .string "suelen desobedecer las órdenes\l"
    .string "en combate!\p"
    .string "¡No entrenes demasiado a tus\n"
    .string "POKéMON para evitar este\l"
    .string "problema!\p"
    .string "¡Espera, llévate esta MT!$"
    .endif

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .ifdef ENGLISH
    .string "{PLAYER} received TM04 from\n"
    .string "SABRINA.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo la MT04\n"
    .string "de manos de SABRINA!$"
    .endif

SaffronCity_Gym_Text_ExplainTM04::
    .ifdef ENGLISH
    .string "TM04 is CALM MIND.\p"
    .string "It makes the POKéMON concentrate\n"
    .string "to raise both SP. ATK and SP. DEF.$"
    .endif
    .ifdef SPANISH
    .string "¡La MT04 contiene PAZ MENTAL!\p"
    .string "Hace concentrarse a los POKéMON\n"
    .string "para que aumente su AT. ESP. \l"
    .string "y su DEF. ESP.$"
    .endif

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .ifdef ENGLISH
    .string "Your BAG is full of other items.$"
    .endif
    .ifdef SPANISH
    .string "¡Tu mochila está llena de otros\n"
    .string "objetos!$"
    .endif

SaffronCity_Gym_Text_AmandaIntro::
    .ifdef ENGLISH
    .string "SABRINA is far younger than I,\n"
    .string "but she has earned my respect.$"
    .endif
    .ifdef SPANISH
    .string "¡SABRINA es más joven que yo,\n"
    .string "pero la respeto!$"
    .endif

SaffronCity_Gym_Text_AmandaDefeat::
    .ifdef ENGLISH
    .string "Not good enough!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya fallo!$"
    .endif

SaffronCity_Gym_Text_AmandaPostBattle::
    .ifdef ENGLISH
    .string "In a battle of equals, the one\n"
    .string "with the stronger will wins.\p"
    .string "If you wish to beat SABRINA, focus\n"
    .string "and will yourself to victory.$"
    .endif
    .ifdef SPANISH
    .string "¡En una pelea de iguales, ganará\n"
    .string "quien tenga más voluntad!\p"
    .string "¡Si quieres ganar a SABRINA,\n"
    .string "piensa sólo en ganar!$"
    .endif

SaffronCity_Gym_Text_JohanIntro::
    .ifdef ENGLISH
    .string "Does our unseen power scare you?$"
    .endif
    .ifdef SPANISH
    .string "¿Te asusta nuestro poder oculto?$"
    .endif

SaffronCity_Gym_Text_JohanDefeat::
    .ifdef ENGLISH
    .string "I never foresaw this!$"
    .endif
    .ifdef SPANISH
    .string "¡Jamás lo hubiera pensado!$"
    .endif

SaffronCity_Gym_Text_JohanPostBattle::
    .ifdef ENGLISH
    .string "PSYCHIC POKéMON fear only ghosts\n"
    .string "and bugs!$"
    .endif
    .ifdef SPANISH
    .string "¡Los POKéMON psíquicos temen sólo\n"
    .string "a los bichos y a los fantasmas!$"
    .endif

SaffronCity_Gym_Text_StacyIntro::
    .ifdef ENGLISH
    .string "POKéMON take on the appearance of\n"
    .string "their TRAINERS.\p"
    .string "Your POKéMON must be tough, then!$"
    .endif
    .ifdef SPANISH
    .string "Los POKéMON acaban pareciéndose\n"
    .string "a sus ENTRENADORES.\p"
    .string "¡Pues tus POKéMON parecen fuertes!$"
    .endif

SaffronCity_Gym_Text_StacyDefeat::
    .ifdef ENGLISH
    .string "I knew it!$"
    .endif
    .ifdef SPANISH
    .string "¡Lo sabía!$"
    .endif

SaffronCity_Gym_Text_StacyPostBattle::
    .ifdef ENGLISH
    .string "I have much to learn still…\p"
    .string "I must master PSYCHIC and teach it\n"
    .string "to my POKéMON…$"
    .endif
    .ifdef SPANISH
    .string "¡Debo enseñarles mejores técnicas\n"
    .string "a mis POKéMON!\p"
    .string "¡Sobre todo del tipo PSÍQUICO!$"
    .endif

SaffronCity_Gym_Text_TyronIntro::
    .ifdef ENGLISH
    .string "You understand, don't you?\p"
    .string "That power alone isn't enough to\n"
    .string "win in the world of POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "Sabes que tu fuerza no bastará\n"
    .string "para ganar en el mundo de los\l"
    .string "POKéMON, ¿no?$"
    .endif

SaffronCity_Gym_Text_TyronDefeat::
    .ifdef ENGLISH
    .string "I don't believe this!$"
    .endif
    .ifdef SPANISH
    .string "¡No me lo puedo creer!$"
    .endif

SaffronCity_Gym_Text_TyronPostBattle::
    .ifdef ENGLISH
    .string "SABRINA just wiped out the KARATE\n"
    .string "MASTER next door.$"
    .endif
    .ifdef SPANISH
    .string "¡SABRINA ganó al MAESTRO de\n"
    .string "KARATE de la puerta de al lado!$"
    .endif

SaffronCity_Gym_Text_TashaIntro::
    .ifdef ENGLISH
    .string "You and I, our POKéMON shall\n"
    .string "battle!$"
    .endif
    .ifdef SPANISH
    .string "¡Tú y yo!\n"
    .string "Nuestros POKéMON deben luchar.$"
    .endif

SaffronCity_Gym_Text_TashaDefeat::
    .ifdef ENGLISH
    .string "I lost after all!$"
    .endif
    .ifdef SPANISH
    .string "¡He perdido al final!$"
    .endif

SaffronCity_Gym_Text_TashaPostBattle::
    .ifdef ENGLISH
    .string "I knew that this was going to take\n"
    .string "place.$"
    .endif
    .ifdef SPANISH
    .string "Sabía que esto iba a pasar.$"
    .endif

SaffronCity_Gym_Text_CameronIntro::
    .ifdef ENGLISH
    .string "SABRINA is young, but she's also\n"
    .string "our highly skilled LEADER.\p"
    .string "You won't reach her easily!$"
    .endif
    .ifdef SPANISH
    .string "¡SABRINA es joven, pero es nuestra\n"
    .string "LÍDER!\p"
    .string "¡No llegarás a ella fácilmente!$"
    .endif

SaffronCity_Gym_Text_CameronDefeat::
    .ifdef ENGLISH
    .string "Ow!\n"
    .string "Down and out!$"
    .endif
    .ifdef SPANISH
    .string "¡No he podido concentrarme!$"
    .endif

SaffronCity_Gym_Text_CameronPostBattle::
    .ifdef ENGLISH
    .string "There used to be two POKéMON GYMS\n"
    .string "in SAFFRON.\p"
    .string "The FIGHTING DOJO next door lost\n"
    .string "its GYM status, though.\p"
    .string "We simply creamed them when we\n"
    .string "decided to have just one GYM.$"
    .endif
    .ifdef SPANISH
    .string "En AZAFRÁN había dos\n"
    .string "GIMNASIOS POKéMON.\p"
    .string "¡El DOJO-KARATE de aquí al lado\n"
    .string "perdió su condición de GIMNASIO\l"
    .string "cuando los machacamos!$"
    .endif

SaffronCity_Gym_Text_PrestonIntro::
    .ifdef ENGLISH
    .string "SAFFRON POKéMON GYM is famous for\n"
    .string "training psychics.\p"
    .string "You want to see SABRINA, don't\n"
    .string "you? I can tell!$"
    .endif
    .ifdef SPANISH
    .string "¡El GIMNASIO POKéMON de AZAFRÁN\n"
    .string "es famoso por sus médiums!\p"
    .string "¡Quieres ver a SABRINA!\n"
    .string "¡Lo sé!$"
    .endif

SaffronCity_Gym_Text_PrestonDefeat::
    .ifdef ENGLISH
    .string "Arrrgh!$"
    .endif
    .ifdef SPANISH
    .string "¡Arrrgg!$"
    .endif

SaffronCity_Gym_Text_PrestonPostBattle::
    .ifdef ENGLISH
    .string "That's right! I used telepathy to\n"
    .string "read your mind!$"
    .endif
    .ifdef SPANISH
    .string "¡Tienes razón! ¡Usé la telepatía\n"
    .string "para leer tu mente!$"
    .endif

SaffronCity_Gym_Text_GymGuyAdvice::
    .ifdef ENGLISH
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "SABRINA's POKéMON use psychic\n"
    .string "power instead of force.\p"
    .string "FIGHTING POKéMON are especially\n"
    .string "weak against PSYCHIC POKéMON.\p"
    .string "They'll get destroyed before they\n"
    .string "can even aim a punch!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, aspirante al título!\p"
    .string "¡Los POKéMON de SABRINA usan el\n"
    .string "poder de la mente, no la fuerza!\p"
    .string "¡Los POKéMON del tipo LUCHA\n"
    .string "son débiles contra los de tipo\l"
    .string "PSÍQUICO!\p"
    .string "¡Se debilitan casi antes de poder\n"
    .string "prepararse!$"
    .endif

SaffronCity_Gym_Text_GymGuyPostVictory::
    .ifdef ENGLISH
    .string "Psychic power, huh?\p"
    .string "If I had that, I'd make a bundle\n"
    .string "at the slots!$"
    .endif
    .ifdef SPANISH
    .string "¿Poder mental?\p"
    .string "¡Si yo lo tuviera me haría rico en\n"
    .string "las tragaperras!$"
    .endif

SaffronCity_Gym_Text_GymStatue::
    .ifdef ENGLISH
    .string "SAFFRON POKéMON GYM\n"
    .string "LEADER: SABRINA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de AZAFRÁN: SABRINA\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"
    .endif

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .ifdef ENGLISH
    .string "SAFFRON POKéMON GYM\n"
    .string "LEADER: SABRINA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de AZAFRÁN: SABRINA\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"
    .endif

