PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy::
    .ifdef ENGLISH
    .string "A shady old guy sucked me into\n"
    .string "buying this weird fish POKéMON!\p"
    .string "It's totally weak and it cost ¥500!$"
    .endif
    .ifdef SPANISH
    .string "¡Un misterioso anciano me vendió\n"
    .string "este extraño pez POKéMON!\p"
    .string "¡Es muy débil y cuesta 500?!$"
    .endif

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently::
    .ifdef ENGLISH
    .string "Good things can happen if you raise\n"
    .string "POKéMON diligently.\p"
    .string "Even the weak ones can surprise\n"
    .string "you if you don't give up on them.$"
    .endif
    .ifdef SPANISH
    .string "¡Podrían suceder cosas buenas si\n"
    .string "entrenaras rápidamente a tus\l"
    .string "POKéMON, hasta a los más débiles!$"
    .endif

