PokemonTower_6F_Text_AngelicaIntro::
	.string "Ich... brauche...\n"
	.string "Blut...$"

PokemonTower_6F_Text_AngelicaDefeat::
	.string "Wo bin ich?$"

PokemonTower_6F_Text_AngelicaPostBattle::
	.string "Ich fühle mich so blutleer und\n"
	.string "schwach...$"

PokemonTower_6F_Text_EmiliaIntro::
	.string "Buuh... buhuhu!$"

PokemonTower_6F_Text_EmiliaDefeat::
	.string "Irgendetwas hat mich verlassen!$"

PokemonTower_6F_Text_EmiliaPostBattle::
	.string "Es war ein böser Geist, der Besitz\n"
	.string "von mir ergriffen hatte!$"

PokemonTower_6F_Text_JenniferIntro::
	.string "Buh...\n"
	.string "Buh... buhuhu...$"

PokemonTower_6F_Text_JenniferDefeat::
	.string "Buuh!$"

PokemonTower_6F_Text_JenniferPostBattle::
	.string "Was geht hier vor?$"

PokemonTower_6F_Text_BeGoneIntruders::
	.string "Verschwindet...\n"
	.string "Eindringlinge...$"

PokemonTower_6F_Text_GhostWasCubonesMother::
	.string "Der GEIST war die rastlose Seele\n"
	.string "der Mutter eines TRAGOSSO!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
	.string "Ihre Seele hat Frieden gefunden.\p"
	.string "Sie ist in das Jenseits\n"
	.string "eingekehrt...$"

