PokemonTower_6F_Text_AngelicaIntro::
    .string "Da... me...\n"
    .string "tu... ser...$"

PokemonTower_6F_Text_AngelicaDefeat::
    .string "¡Grrr!$"

PokemonTower_6F_Text_AngelicaPostBattle::
    .string "Me siento anémica y débil...$"

PokemonTower_6F_Text_EmiliaIntro::
    .string "Uuff...\n"
    .string "¡Guaa!$"

PokemonTower_6F_Text_EmiliaDefeat::
    .string "¡Algo se ha caído!$"

PokemonTower_6F_Text_EmiliaPostBattle::
    .string "¡No me lo creo!\n"
    .string "¡Era un malvado espíritu!$"

PokemonTower_6F_Text_JenniferIntro::
    .string "¡¡¡Ki...ki...\n"
    .string "ki...ki...ki!!!$"

PokemonTower_6F_Text_JenniferDefeat::
    .string "¡Kiii!$"

PokemonTower_6F_Text_JenniferPostBattle::
    .string "¿Qué está pasando aquí?$"

PokemonTower_6F_Text_BeGoneIntruders::
    .string "Fuera...\n"
    .string "Intrusos...$"

PokemonTower_6F_Text_GhostWasCubonesMother::
    .string "¡Ese GHOST era el inquieto\n"
    .string "espíritu de la madre de CUBONE!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
    .string "El espíritu de la madre descansa\n"
    .string "tranquilo.\p"
    .string "¡Y ha partido al más allá!$"
