PokemonTower_6F_Text_AngelicaIntro::
	.string "Ton… sang…\n"
	.string "Donne…$"

PokemonTower_6F_Text_AngelicaDefeat::
	.string "Grargh!$"

PokemonTower_6F_Text_AngelicaPostBattle::
	.string "Je me sens faible…$"

PokemonTower_6F_Text_EmiliaIntro::
	.string "Urff… Kwaah!$"

PokemonTower_6F_Text_EmiliaDefeat::
	.string "Haaa!\n"
	.string "Je me sens mieux!$"

PokemonTower_6F_Text_EmiliaPostBattle::
	.string "J'étais sous l'emprise d'un\n"
	.string "esprit!$"

PokemonTower_6F_Text_JenniferIntro::
	.string "Ke… ke… ke….\n"
	.string "ke… ke… ke!!$"

PokemonTower_6F_Text_JenniferDefeat::
	.string "Keee!$"

PokemonTower_6F_Text_JenniferPostBattle::
	.string "Mais qu'est-ce qui se passe ici?$"

PokemonTower_6F_Text_BeGoneIntruders::
	.string "Fuis…\n"
	.string "Misérable…$"

PokemonTower_6F_Text_GhostWasCubonesMother::
	.string "Le SPECTRE était l'esprit damné de\n"
	.string "la mère d'OSSELAIT!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
	.string "L'âme de la mère a été apaisée.\p"
	.string "Elle est partie vers l'autre monde!$"

