PokemonTower_6F_Text_AngelicaIntro::
    .ifdef ENGLISH
    .string "Give…me…\n"
    .string "blood…$"
    .endif
    .ifdef SPANISH
    .string "Da... me...\n"
    .string "tu... ser...$"
    .endif

PokemonTower_6F_Text_AngelicaDefeat::
    .ifdef ENGLISH
    .string "Groan!$"
    .endif
    .ifdef SPANISH
    .string "¡Grrr!$"
    .endif

PokemonTower_6F_Text_AngelicaPostBattle::
    .ifdef ENGLISH
    .string "I feel anemic and weak…$"
    .endif
    .ifdef SPANISH
    .string "Me siento anémica y débil...$"
    .endif

PokemonTower_6F_Text_EmiliaIntro::
    .ifdef ENGLISH
    .string "Urff…\n"
    .string "Kwaah!$"
    .endif
    .ifdef SPANISH
    .string "Uuff...\n"
    .string "¡Guaa!$"
    .endif

PokemonTower_6F_Text_EmiliaDefeat::
    .ifdef ENGLISH
    .string "Something fell out!$"
    .endif
    .ifdef SPANISH
    .string "¡Algo se ha caído!$"
    .endif

PokemonTower_6F_Text_EmiliaPostBattle::
    .ifdef ENGLISH
    .string "My hair didn't fall out!\n"
    .string "It was a malevolent spirit!$"
    .endif
    .ifdef SPANISH
    .string "¡No me lo creo!\n"
    .string "¡Era un malvado espíritu!$"
    .endif

PokemonTower_6F_Text_JenniferIntro::
    .ifdef ENGLISH
    .string "Ke…ke…ke…\n"
    .string "ke…ke…ke!$"
    .endif
    .ifdef SPANISH
    .string "¡¡¡Ki...ki...\n"
    .string "ki...ki...ki!!!$"
    .endif

PokemonTower_6F_Text_JenniferDefeat::
    .ifdef ENGLISH
    .string "Keee!$"
    .endif
    .ifdef SPANISH
    .string "¡Kiii!$"
    .endif

PokemonTower_6F_Text_JenniferPostBattle::
    .ifdef ENGLISH
    .string "What's going on here?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué está pasando aquí?$"
    .endif

PokemonTower_6F_Text_BeGoneIntruders::
    .ifdef ENGLISH
    .string "Be gone…\n"
    .string "Intruders…$"
    .endif
    .ifdef SPANISH
    .string "Fuera...\n"
    .string "Intrusos...$"
    .endif

PokemonTower_6F_Text_GhostWasCubonesMother::
    .ifdef ENGLISH
    .string "The ghost was the restless spirit\n"
    .string "of CUBONE's mother!$"
    .endif
    .ifdef SPANISH
    .string "¡Ese GHOST era el inquieto\n"
    .string "espíritu de la madre de CUBONE!$"
    .endif

PokemonTower_6F_Text_MothersSpiritWasCalmed::
    .ifdef ENGLISH
    .string "The mother's spirit was calmed.\p"
    .string "It departed to the afterlife…$"
    .endif
    .ifdef SPANISH
    .string "El espíritu de la madre descansa\n"
    .string "tranquilo.\p"
    .string "¡Y ha partido al más allá!$"
    .endif

