VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
    .ifdef ENGLISH
    .string "There are wicked people who will\n"
    .string "use POKéMON for criminal acts.\p"
    .string "TEAM ROCKET traffics in rare\n"
    .string "POKéMON, for example.\p"
    .string "They also abandon POKéMON that\n"
    .string "they consider unpopular or useless.\p"
    .string "That's the sort of horrid people\n"
    .string "they are, TEAM ROCKET.$"
    .endif
    .ifdef SPANISH
    .string "Hay gente mala que utiliza a los\n"
    .string "POKéMON para cometer sus actos\l"
    .string "delictivos.\p"
    .string "El TEAM ROCKET trafica con\n"
    .string "POKéMON raros.\p"
    .string "Y prescinde de aquellos POKéMON\n"
    .string "que no son muy populares o útiles.$"
    .endif

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
    .ifdef ENGLISH
    .string "I think POKéMON can be good or\n"
    .string "bad. It depends on the TRAINER.$"
    .endif
    .ifdef SPANISH
    .string "Creo que los POKéMON pueden ser\n"
    .string "buenos o malos. Todo depende del\l"
    .string "ENTRENADOR.$"
    .endif

