Text_ExplosionTeach::
    .ifdef ENGLISH
    .string "Can you imagine?\n"
    .string "If this volcano were to erupt?\p"
    .string "The explosion would be the end of\n"
    .string "us. How terrifying is that?\p"
    .string "While we're terrified, would you\n"
    .string "like me to teach EXPLOSION?$"
    .endif
    .ifdef SPANISH
    .string "¿Te imaginas que este volcán\n"
    .string "entrara en erupción?\p"
    .string "Sería nuestro fin. ¡Qué horror!\p"
    .string "A todo esto, ¿quieres aprender\n"
    .string "EXPLOSIÓN?$"
    .endif

Text_ExplosionDeclined::
    .ifdef ENGLISH
    .string "Yeah, you're right.\n"
    .string "It is too terrifying.$"
    .endif
    .ifdef SPANISH
    .string "Te entiendo, sólo oír el nombre\n"
    .string "pone los pelos de punta.$"
    .endif

Text_ExplosionWhichMon::
    .ifdef ENGLISH
    .string "You're terribly brave!\p"
    .string "Which POKéMON should I teach\n"
    .string "EXPLOSION?$"
    .endif
    .ifdef SPANISH
    .string "¡Sí, señor!\p"
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe EXPLOSIÓN?$"
    .endif

Text_ExplosionTaught::
    .ifdef ENGLISH
    .string "Using EXPLOSION while on this\n"
    .string "volcano…\p"
    .string "What a terrifying thrill!$"
    .endif
    .ifdef SPANISH
    .string "Imagínate lo que tiene que ser\n"
    .string "usar EXPLOSIÓN en este volcán...\p"
    .string "¡Lo pienso y no sé lo que me\n"
    .string "entra!$"
    .endif

@ Below 4 are unused JP versions of the above texts
Text_ExplosionTeachJP::
    .string "こ　この　かざんが\n"
    .string "もし　だいばくはつ　したら\l"
    .string "お　おれら　ひとたまりも\l"
    .string "ないなあ　‥ブルブル！\p"
    .string "こ　こわい　ついでに\n"
    .string "だいばくはつ　でも　おぼえてみる？$"

Text_ExplosionDeclinedJP::
    .string "や　やっぱ　こわいもんな\n"
    .string "ブルブル$"

Text_ExplosionWhichMonJP::
    .string "つ　つよきだね！\n"
    .string "じゃあ　どの　ポケモンに　する？$"

Text_ExplosionTaughtJP::
    .string "かざんで　だいばくはつを‥\n"
    .string "す　すごい　スリル！$"

MtEmber_Exterior_Text_WellTryDiggingHere::
    .ifdef ENGLISH
    .string "Over here.\n"
    .string "We'll try digging here.\p"
    .string "That treasure the ADMINS've been\n"
    .string "talking about should be here.$"
    .endif
    .ifdef SPANISH
    .string "Aquí, aquí.\n"
    .string "Vamos a intentar cavar aquí.\p"
    .string "Yo creo que el tesoro del que\n"
    .string "hablaban los ADMINISTRADORES\l"
    .string "está aquí.$"
    .endif

MtEmber_Exterior_Text_YoureInTheWayGetLost::
    .ifdef ENGLISH
    .string "What the…?\n"
    .string "You're in the way. Get lost.$"
    .endif
    .ifdef SPANISH
    .string "Pero...\n¿Te quieres quitar de aquí?$"
    .endif

MtEmber_Exterior_Text_PunchedThroughAtLast::
    .ifdef ENGLISH
    .string "Whew, punched through at last.\n"
    .string "Let's go treasure hunting!$"
    .endif
    .ifdef SPANISH
    .string "¡Por fin lo hemos conseguido!\n¡A por el tesoro!$"
    .endif

MtEmber_Exterior_Text_WhatsPasswordAgain::
    .ifdef ENGLISH
    .string "Any treasure we find, we haul back\n"
    .string "to the WAREHOUSE, understood?\p"
    .string "…Oh, and what're the passwords?\n"
    .string "At the ROCKET WAREHOUSE, I mean.$"
    .endif
    .ifdef SPANISH
    .string "Cosa que encontremos, cosa que\n"
    .string "llevamos al ALMACÉN, ¿eh?\p"
    .string "Eh... ¿y cuáles eran las\n"
    .string "contraseñas?\l"
    .string "Me refiero a las del ALMACÉN...$"
    .endif

MtEmber_Exterior_Text_FirstPasswordGoldeen::
    .ifdef ENGLISH
    .string "What, you forgot the password?\n"
    .string "There're actually two.\p"
    .string "The first one's “GOLDEEN need\n"
    .string "log.”\p"
    .string "And the second one is…$"
    .endif
    .ifdef SPANISH
    .string "¿No te acuerdas de la contraseña?\n"
    .string "Bueno, en realidad son dos.\p"
    .string "La primera es “ARON ama\n"
    .string "a NORA”.\p"
    .string "Y la segunda...$"
    .endif

MtEmber_Exterior_Text_SnoopsBeenListeningIn::
    .ifdef ENGLISH
    .string "Hey!\n"
    .string "This snoop's been listening in!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, que por aquí se están\n"
    .string "quedando con la copla! ¡Cotilla!$"
    .endif

MtEmber_Exterior_Text_Grunt1Intro::
    .ifdef ENGLISH
    .string "You've been eavesdropping on us,\n"
    .string "haven't you?$"
    .endif
    .ifdef SPANISH
    .string "Has estado espiándonos, ¿eh?$"
    .endif

MtEmber_Exterior_Text_Grunt1Defeat::
    .ifdef ENGLISH
    .string "Huh, what?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué ha pasado?$"
    .endif

MtEmber_Exterior_Text_Grunt1PostBattle::
    .ifdef ENGLISH
    .string "Why'd you have to win?$"
    .endif
    .ifdef SPANISH
    .string "¿Por qué me has ganado?$"
    .endif

MtEmber_Exterior_Text_Grunt2Intro::
    .ifdef ENGLISH
    .string "Trying to horn in on our treasure?\n"
    .string "Don't bet on it!$"
    .endif
    .ifdef SPANISH
    .string "¿Te crees que vas a pillar cacho\n"
    .string "de nuestro tesoro? ¡Ni lo sueñes!$"
    .endif

MtEmber_Exterior_Text_Grunt2Defeat::
    .ifdef ENGLISH
    .string "Wait!\n"
    .string "But how?$"
    .endif
    .ifdef SPANISH
    .string "¡Ahora quien está soñando soy yo!$"
    .endif

MtEmber_Exterior_Text_Grunt2PostBattle::
    .ifdef ENGLISH
    .string "Develop amnesia conveniently and\n"
    .string "forget everything you heard!$"
    .endif
    .ifdef SPANISH
    .string "Hazme un favorcito, olvídate de lo\n"
    .string "que has oído, anda.$"
    .endif

MtEmber_Exterior_Text_WellRegroupDontStepInsideThere::
    .ifdef ENGLISH
    .string "What a setback…\n"
    .string "We'll have to regroup.\p"
    .string "You! Don't even think about taking\n"
    .string "a step inside here!\p"
    .string "If you know what's good for you,\n"
    .string "don't even think about this!$"
    .endif
    .ifdef SPANISH
    .string "¡Menudo revés!...\n"
    .string "¡Vámonos con el resto!\p"
    .string "¡Tú, no te atrevas a entrar!\p"
    .string "¡Te lo digo por tu bien!\n"
    .string "¡Ni te lo plantees!$"
    .endif

MtEmber_Exterior_Text_LoganIntro::
    .ifdef ENGLISH
    .string "An active volcano is one that's\n"
    .string "erupting, or about to.$"
    .endif
    .ifdef SPANISH
    .string "Se dice que un volcán está activo,\n"
    .string "cuando entra en erupción o está\l"
    .string "a punto.$"
    .endif

MtEmber_Exterior_Text_LoganDefeat::
    .ifdef ENGLISH
    .string "Whew… That was hot!\n"
    .string "Sweat's erupting from me!$"
    .endif
    .ifdef SPANISH
    .string "Guau... ¡qué pasada!\n"
    .string "¡Me ha entrado un calor!$"
    .endif

MtEmber_Exterior_Text_LoganPostBattle::
    .ifdef ENGLISH
    .string "They say there're over 1,500\n"
    .string "active volcanoes in the world.\p"
    .string "Just thinking about them makes me\n"
    .string "feel all hot and gooey inside!$"
    .endif
    .ifdef SPANISH
    .string "Dicen que hay unos 1.500 volcanes\n"
    .string "activos en todo el mundo.\p"
    .string "Cada vez que lo pienso, ¡me entra\n"
    .string "una cosa!$"
    .endif

MtEmber_Exterior_Text_BethIntro::
    .ifdef ENGLISH
    .string "Do you know how caves form inside\n"
    .string "volcanoes?$"
    .endif
    .ifdef SPANISH
    .string "¿Sabes cómo se forman las cuevas\n"
    .string "en el interior de los volcanes?$"
    .endif

MtEmber_Exterior_Text_BethDefeat::
    .ifdef ENGLISH
    .string "Atchah!\n"
    .string "You're shockingly good!$"
    .endif
    .ifdef SPANISH
    .string "¡Aaaah!\n¡Eres increíble!$"
    .endif

MtEmber_Exterior_Text_BethPostBattle::
    .ifdef ENGLISH
    .string "When lava at the surface of magma\n"
    .string "hardens, and the magma inside flows\l"
    .string "out, caverns are left behind.$"
    .endif
    .ifdef SPANISH
    .string "Cuando la lava de la superficie se\n"
    .string "solidifica, aún puede quedar magma\l"
    .string "por salir.\p"
    .string "Y son los conductos que abre\n"
    .string "en su camino al exterior, los que\l"
    .string "pasan a ser las cuevas.$"
    .endif

MtEmber_Exterior_Text_JocelynIntro::
    .ifdef ENGLISH
    .string "I've been in training so I can mend\n"
    .string "my broken heart…\p"
    .string "It toughened me up physically at\n"
    .string "least! Hi-yah!$"
    .endif
    .ifdef SPANISH
    .string "He estado entrenándome para\n"
    .string "recuperar mi fuerza interior...\p"
    .string "¡Y lo que sin duda he conseguido\n"
    .string "ha sido ponerme en forma!$"
    .endif

MtEmber_Exterior_Text_JocelynDefeat::
    .ifdef ENGLISH
    .string "I think I tried to overdo it…$"
    .endif
    .ifdef SPANISH
    .string "Creo que he exagerado...$"
    .endif

MtEmber_Exterior_Text_JocelynPostBattle::
    .ifdef ENGLISH
    .string "The way you battle, it reminds me\n"
    .string "of the guy who dumped me…$"
    .endif
    .ifdef SPANISH
    .string "Luchando me recuerdas a mi antiguo\n"
    .string "noviete...$"
    .endif

