SSAnne_B1F_Room4_Text_LeonardIntro::
	.string "Du weißt, wir Seeleute lieben es zu\n"
	.string "kämpfen!$"

SSAnne_B1F_Room4_Text_LeonardDefeat::
	.string "JA!\n"
	.string "Was für ein Kampf!!!$"

SSAnne_B1F_Room4_Text_LeonardPostBattle::
	.string "Willst du zur See fahren?$"

SSAnne_B1F_Room4_Text_DuncanIntro::
	.string "Mein Ruf als Seebär steht auf dem\n"
	.string "Spiel!!!$"

SSAnne_B1F_Room4_Text_DuncanDefeat::
	.string "Kiel unter!\n"
	.string "Das war es für mich!$"

SSAnne_B1F_Room4_Text_DuncanPostBattle::
	.string "Hast du schon den PROFI-ANGLER in\n"
	.string "ORANIA CITY besucht?$"

