SSAnne_B1F_Room4_Text_LeonardIntro::
    .string "¡Ya sabes lo que dicen sobre\n"
    .string "los marineros y las peleas!$"

SSAnne_B1F_Room4_Text_LeonardDefeat::
    .string "¡Has peleado muy bien, sí, sí!$"

SSAnne_B1F_Room4_Text_LeonardPostBattle::
    .string "¡Ajá!\n"
    .string "¿Quieres unirte a los marineros?$"

SSAnne_B1F_Room4_Text_DuncanIntro::
    .string "¡Está en juego mi fama de\n"
    .string "marinero!$"

SSAnne_B1F_Room4_Text_DuncanDefeat::
    .string "¡Menuda paliza!$"

SSAnne_B1F_Room4_Text_DuncanPostBattle::
    .string "¿Viste al GURÚ de los PESCADORES\n"
    .string "en CIUDAD CARMÍN?$"
