SixIsland_Text_IslandSign::
    .ifdef ENGLISH
    .string "SIX ISLAND\n"
    .string "Fortune Island of Aged Wisdom$"
    .endif
    .ifdef SPANISH
    .string "ISLA EXTA\n"
    .string "Isla de la fortuna y el saber.$"
    .endif

SixIsland_Text_ThatWayToWaterPathRuinValley::
    .ifdef ENGLISH
    .string "Keep going this way and you'll get\n"
    .string "to the WATER PATH.\p"
    .string "Stay on that and you'll get to\n"
    .string "the RUIN VALLEY.$"
    .endif
    .ifdef SPANISH
    .string "Si sigues por aquí, llegarás a la\n"
    .string "VÍA ACUÁTICA.\p"
    .string "Cuando alcances la VÍA,\n"
    .string "ve hacia el sur si quieres ir\l"
    .string "al VALLE de las RUINAS.$"
    .endif

SixIsland_Text_SkyAtNightIsFantastic::
    .ifdef ENGLISH
    .string "When you're this far away from the\n"
    .string "city, the sky at night is fantastic.$"
    .endif
    .ifdef SPANISH
    .string "Al estar tan lejos de las ciudades,\n"
    .string "por la noche el cielo se ve muy\l"
    .string "despejado.$"
    .endif

