Text_RockSlideTeach::
	.string "A la montagne, il faut faire\n"
	.string "attention aux chutes de pierres.\p"
	.string "Tu imagines? Des rochers en train\n"
	.string "de tomber sur toi?\p"
	.string "Brrrr, ça serait terrible!\p"
	.string "Ça te fait pas peur? Tu voudrais\n"
	.string "apprendre EBOULEMENT?$"

Text_RockSlideDeclined::
	.string "Oh, donc ça te fait peur…$"

Text_RockSlideWhichMon::
	.string "A quel POKéMON enseigner\n"
	.string "EBOULEMENT?$"

Text_RockSlideTaught::
	.string "Il vaudrait peut-être mieux éviter\n"
	.string "de l'utiliser dans ce tunnel…$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
	.string "Les rochers peuvent faire changer\n"
	.string "le niveau de l'eau!$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
	.string "DANGER!\n"
	.string "Rapides!$"

