Text_RockSlideTeach::
	.string "Wenn du so hoch oben im steinigen\n"
	.string "Gebirge bist wie hier, stellen\l"
	.string "Gerölllawinen eine Gefahr dar.\l"
	.string "Kannst du dir vorstellen, dass dir\l"
	.string "Felsen auf den Kopf fallen?\p"
	.string "Das wäre doch…\n"
	.string "Einfach unvorstellbar schrecklich!\p"
	.string "Du scheinst keine Angst zu haben.\n"
	.string "Soll ein POKéMON STEINHAGEL\l"
	.string "erlernen?$"

Text_RockSlideDeclined::
	.string "Oh, du hast also doch Angst!$"

Text_RockSlideWhichMon::
	.string "Welches POKéMON soll\n"
	.string "STEINHAGEL erlernen?$"

Text_RockSlideTaught::
	.string "Es wäre sehr gruselig, das in\n"
	.string "diesem Tunnel einzusetzen…$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
	.string "Felsen könnten die Strömung\n"
	.string "vielleicht umlenken!$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
	.string "VORSICHT!\n"
	.string "GEFÄHRLICHE STRÖMUNG!$"

