Text_RockSlideTeach::
    .ifdef ENGLISH
    .string "When you're up on a rocky mountain\n"
    .string "like this, rockslides are a threat.\p"
    .string "Can you imagine?\n"
    .string "Boulders tumbling down on you?\p"
    .string "That'd be, like, waaaaaaaaaaah!\n"
    .string "Total terror!\p"
    .string "You don't seem to be scared.\n"
    .string "Want to try using ROCK SLIDE?$"
    .endif
    .ifdef SPANISH
    .string "En montañas como ésta, hay peligro\nde desprendimientos.\pImagínate qué horror que empiecen\na caerte rocas encima.\p¡Aaaaaaaaaaaaaaah!\nUn horror, vamos.\p¿No te da miedo?\n¿Quieres aprender AVALANCHA?$"
    .endif

Text_RockSlideDeclined::
    .ifdef ENGLISH
    .string "Oh, so you are scared after all.$"
    .endif
    .ifdef SPANISH
    .string "Te da miedo, no lo niegues.$"
    .endif

Text_RockSlideWhichMon::
    .ifdef ENGLISH
    .string "Which POKéMON should I teach\n"
    .string "ROCK SLIDE?$"
    .endif
    .ifdef SPANISH
    .string "¿A qué POKéMON quieres que\nle enseñe AVALANCHA?$"
    .endif

Text_RockSlideTaught::
    .ifdef ENGLISH
    .string "It might be scary to use it in this\n"
    .string "tunnel…$"
    .endif
    .ifdef SPANISH
    .string "Yo no lo usaría en un túnel...$"
    .endif

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
    .ifdef ENGLISH
    .string "Hint: Boulders might change the\n"
    .string "flow of water.$"
    .endif
    .ifdef SPANISH
    .string "¡Las ROCAS pueden cambiar\nel flujo del agua!$"
    .endif

SeafoamIslands_B4F_Text_DangerFastCurrent::
    .ifdef ENGLISH
    .string "DANGER\n"
    .string "Fast current!$"
    .endif
    .ifdef SPANISH
    .string "¡PELIGRO!\n¡Rápidos!$"
    .endif

