CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
    .ifdef ENGLISH
    .string "Me?\n"
    .string "I'm the programmer!$"
    .endif
    .ifdef SPANISH
    .string "¿Yo?\n"
    .string "¡Soy el programador!$"
    .endif

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
    .ifdef ENGLISH
    .string "I'm the graphic artist!\n"
    .string "I drew you!$"
    .endif
    .ifdef SPANISH
    .string "¡Soy el diseñador gráfico!\n"
    .string "¡Yo te dibujé!$"
    .endif

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
    .ifdef ENGLISH
    .string "I wrote the story!\n"
    .string "Isn't ERIKA cute?\p"
    .string "I like MISTY a lot, too!\n"
    .string "Oh, and SABRINA, I like her!$"
    .endif
    .ifdef SPANISH
    .string "¡Yo escribí la historia!\n"
    .string "¿A que es guapa ERIKA?\p"
    .string "¡También me gusta mucho MISTY!\n"
    .string "¡Y también me gusta SABRINA!$"
    .endif

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
    .ifdef ENGLISH
    .string "Is that right?\p"
    .string "I'm the game designer!\p"
    .string "Filling up your POKéDEX is tough,\n"
    .string "but don't quit!\p"
    .string "When you finish, come tell me!$"
    .endif
    .ifdef SPANISH
    .string "¿Sabes?\p"
    .string "¡Soy el diseñador del juego!\p"
    .string "¡Completar tu POKéDEX es difícil,\n"
    .string "pero no te rindas!\p"
    .string "¡Cuando termines ven a decírmelo!$"
    .endif

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
    .ifdef ENGLISH
    .string "Wow! Excellent!\n"
    .string "You completed your POKéDEX!\l"
    .string "Congratulations!\l"
    .string "…$"
    .endif
    .ifdef SPANISH
    .string "¡Uauu! ¡Genial!\n"
    .string "¡Has completado tu POKéDEX!\l"
    .string "¡Enhorabuena!$"
    .endif

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
    .ifdef ENGLISH
    .string "It's the game program! Messing with\n"
    .string "it could bug out the game!$"
    .endif
    .ifdef SPANISH
    .string "¡Es el programa del juego!\n"
    .string "¡No lo toques, no vaya a ser que\l"
    .string "se estropee!$"
    .endif

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
    .ifdef ENGLISH
    .string "Someone's playing a game instead of\n"
    .string "working!$"
    .endif
    .ifdef SPANISH
    .string "¡Alguien está jugando en lugar\n"
    .string "de trabajar!$"
    .endif

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
    .ifdef ENGLISH
    .string "It's the script!\n"
    .string "Better not look at the ending!$"
    .endif
    .ifdef SPANISH
    .string "¡Es el guión del juego!\n"
    .string "¡No leas el final!$"
    .endif

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
    .ifdef ENGLISH
    .string "GAME FREAK Development Room$"
    .endif
    .ifdef SPANISH
    .string "Sala de desarrollo de GAME FREAK$"
    .endif

