CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
    .ifdef ENGLISH
    .string "POKéMON stat enhancers can be\n"
    .string "bought only here.\p"
    .string "HP UP increases the base HP of a\n"
    .string "POKéMON.\p"
    .string "CALCIUM raises the base SP. ATK\n"
    .string "stat of one POKéMON.\p"
    .string "ZINC boosts the base SP. DEF stat\n"
    .string "of one POKéMON.\p"
    .string "CARBOS enhances the base SPEED\n"
    .string "stat.$"
    .endif
    .ifdef SPANISH
    .string "¡Los dispositivos de mejora de los\n"
    .string "POKéMON sólo se venden aquí!\p"
    .string "MÁS PS aumenta los PS básicos\n"
    .string "de un POKéMON.\p"
    .string "Usa CALCIO para aumentar las\n"
    .string "habilidades ESPECIALES.\p"
    .string "ZINC aumenta la DEF. ESP.\n"
    .string "de un POKéMON.\p"
    .string "Usa CARBURANTE para aumentar\n"
    .string "la VELOCIDAD.$"
    .endif

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
    .ifdef ENGLISH
    .string "I'm here for POKéMON stat\n"
    .string "enhancers.\p"
    .string "PROTEIN increases the base ATTACK\n"
    .string "power.\p"
    .string "IRON increases the base DEFENSE\n"
    .string "stat.$"
    .endif
    .ifdef SPANISH
    .string "¡He venido a por dispositivos de\n"
    .string "mejora de los POKéMON!\p"
    .string "Las PROTEÍNAS aumentan la potencia\n"
    .string "del ATAQUE.\p"
    .string "El HIERRO aumenta la DEFENSA.$"
    .endif

CeladonCity_DepartmentStore_5F_Text_Drugstore::
    .ifdef ENGLISH
    .string "5F: DRUGSTORE$"
    .endif
    .ifdef SPANISH
    .string "P4: FARMACIA$"
    .endif

