SilphCo_7F_Text_HaveMonForSavingUs::
	.string "Oh! Tu n'es pas un ROCKET! Es-tu\n"
	.string "là pour nous sauver? Merci!\p"
	.string "Prends donc ce joli POKéMON en\n"
	.string "cadeau.$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
	.string "{PLAYER} reçoit un LOKHLASS.$"

SilphCo_7F_Text_ExplainLapras::
	.string "C'est un LOKHLASS.\n"
	.string "Il est très intelligent.\p"
	.string "Nous le gardions dans le labo,\n"
	.string "mais il sera mieux avec toi!\p"
	.string "Tu seras un bon DRESSEUR\n"
	.string "pour LOKHLASS!\p"
	.string "C'est un bon nageur, il pourra même\n"
	.string "te transporter sur l'eau!$"

SilphCo_7F_Text_RocketBossWentToBoardroom::
	.string "Le chef de la TEAM ROCKET est\n"
	.string "dans la salle du conseil…\p"
	.string "Le PDG va bien?\n"
	.string "Je suis très inquiet.$"

SilphCo_7F_Text_OhNo::
	.string "あ‥　もう　もてないぞ$"

SilphCo_7F_Text_SavedAtLast::
	.string "たすかったよ　ありがと！$"

SilphCo_7F_Text_RocketsAfterMasterBall::
	.string "La TEAM ROCKET voulait s'emparer\n"
	.string "de la MASTER BALL pouvant\l"
	.string "attraper n'importe quel POKéMON!$"

SilphCo_7F_Text_CanceledMasterBallProject::
	.string "Le projet MASTER BALL fut annulé\n"
	.string "à cause de la TEAM ROCKET.$"

SilphCo_7F_Text_BadIfTeamRocketTookOver::
	.string "Grâce au ciel, la TEAM ROCKET\n"
	.string "n'a pas pu investir la SYLPHE ou\l"
	.string "voler nos POKéMON!$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
	.string "Woah!\p"
	.string "Tu as vraiment battu la\n"
	.string "TEAM ROCKET?$"

SilphCo_7F_Text_ReallyDangerousHere::
	.string "Hé toi!\n"
	.string "C'est dangereux par ici!\p"
	.string "Tu es là pour me sauver?\n"
	.string "Impossible!$"

SilphCo_7F_Text_ThankYouSoMuch::
	.string "Enfin libre!\n"
	.string "Merci merci!$"

SilphCo_7F_Text_Grunt3Intro::
	.string "Heu?\n"
	.string "Alerte! Alerte!$"

SilphCo_7F_Text_Grunt3Defeat::
	.string "Oups.\n"
	.string "Perdu! Perdu!$"

SilphCo_7F_Text_Grunt3PostBattle::
	.string "Tu ne pourras pas trouver mon\n"
	.string "chef juste en te baladant!$"

SilphCo_7F_Text_JoshuaIntro::
	.string "Nyah ha ha!\p"
	.string "Tu me prends pour un employé de\n"
	.string "la SYLPHE?$"

SilphCo_7F_Text_JoshuaDefeat::
	.string "…\n"
	.string "Fichu!$"

SilphCo_7F_Text_JoshuaPostBattle::
	.string "Bien que tu sois jeune, tu te\n"
	.string "débrouilles pas trop mal!$"

SilphCo_7F_Text_Grunt1Intro::
	.string "Je suis l'un des 4 FRERES ROCKET!$"

SilphCo_7F_Text_Grunt1Defeat::
	.string "Yaaah!\n"
	.string "Frères! A l'aide!$"

SilphCo_7F_Text_Grunt1PostBattle::
	.string "Pas grave. Mes frères se\n"
	.string "chargeront de toi, mon petit!$"

SilphCo_7F_Text_Grunt2Intro::
	.string "Un jeune intrus?\n"
	.string "Mais! C'est toi!$"

SilphCo_7F_Text_Grunt2Defeat::
	.string "OK.\n"
	.string "J'ai perdu.$"

SilphCo_7F_Text_Grunt2PostBattle::
	.string "Rentre chez toi!\n"
	.string "Mon chef est sans pitié!$"

SilphCo_7F_Text_RivalWhatKeptYou::
	.string "{RIVAL}: Qu'est-ce qui t'a retenu\n"
	.string "{PLAYER}?$"

SilphCo_7F_Text_RivalIntro::
	.string "{RIVAL}: Hahaha! J'étais sûr que\n"
	.string "tu passerais par là!\p"
	.string "La TEAM ROCKET te pose des\n"
	.string "problèmes? Quel dommage!\p"
	.string "Je t'ai vu à SAFRANIA.\n"
	.string "T'as fait des progrès?$"

SilphCo_7F_Text_RivalDefeat::
	.string "Oh non!\n"
	.string "Tu vas affronter le chef de\l"
	.string "la TEAM ROCKET!$"

SilphCo_7F_Text_RivalVictory::
	.string "{RIVAL}“おまえなあ‥\p"
	.string "こんな　うでまえじゃ\n"
	.string "まだまだ‥\l"
	.string "いちにんまえ　とは　いえないぜ$"

SilphCo_7F_Text_RivalPostBattle::
	.string "OK, {PLAYER}!\p"
	.string "Je décampe!\p"
	.string "Grâce à mon joli POKéDEX, je\n"
	.string "découvre qui est fort et quelles\l"
	.string "sont toutes les évolutions!\p"
	.string "Je vais à la LIGUE POKéMON\n"
	.string "pour détrôner le CONSEIL 4!\p"
	.string "Je serai bientôt le DRESSEUR le\n"
	.string "plus puissant du monde!\p"
	.string "Bonne chance, {PLAYER}!\p"
	.string "Tu en auras besoin.\n"
	.string "Tchao!$"

SilphCo_7F_Text_FloorSign::
	.string "SYLPHE SARL.\n"
	.string "6ème étage.$"

