SilphCo_7F_Text_HaveMonForSavingUs::
    .string "¡Hola! ¡Tú no eres de los ROCKET!\n"
    .string "¿Has venido a salvarnos?\l"
    .string "¡Pues gracias!\p"
    .string "Voy a darte este POKéMON\n"
    .string "por habernos salvado.$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
    .string "¡{PLAYER} obtuvo un LAPRAS\n"
    .string "del empleado de SILPH S.A.!$"

SilphCo_7F_Text_ExplainLapras::
    .string "Es un LAPRAS.\n"
    .string "Es muy inteligente.\p"
    .string "Lo teníamos en el laboratorio,\n"
    .string "pero estará mucho mejor contigo.\p"
    .string "Seguro que lo entrenarás muy bien.\p"
    .string "Es muy buen nadador.\n"
    .string "¡Podría llevarte incluso!$"

SilphCo_7F_Text_RocketBossWentToBoardroom::
    .string "¡El JEFE del TEAM ROCKET fue\n"
    .string "a la sala del consejo!\p"
    .string "¿Está bien el PRESIDENTE?$"

SilphCo_7F_Text_OhNo::
    .string "あ‥　もう　もてないぞ$"

SilphCo_7F_Text_SavedAtLast::
    .string "たすかったよ　ありがと！$"

SilphCo_7F_Text_RocketsAfterMasterBall::
    .string "¡El TEAM ROCKET buscaba la MASTER\n"
    .string "BALL para poder atrapar cualquier\l"
    .string "tipo de POKéMON!$"

SilphCo_7F_Text_CanceledMasterBallProject::
    .string "Cancelamos el proyecto de la\n"
    .string "MASTER BALL por culpa del \l"
    .string "TEAM ROCKET.$"

SilphCo_7F_Text_BadIfTeamRocketTookOver::
    .string "¡Sería horrible que el TEAM\n"
    .string "ROCKET se hiciera con SILPH S.A.\l"
    .string "o con nuestros POKéMON!$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
    .string "¡Uauu!\p"
    .string "¿Echaste tú al TEAM ROCKET?$"

SilphCo_7F_Text_ReallyDangerousHere::
    .string "¡Oye!\n"
    .string "¡Este lugar es muy peligroso!\p"
    .string "¿Has venido a salvarme?\n"
    .string "¡Pues no puedes!$"

SilphCo_7F_Text_ThankYouSoMuch::
    .string "¡Por fin a salvo! ¡Muchas gracias!$"

SilphCo_7F_Text_Grunt3Intro::
    .string "¡Oh, oh!\n"
    .string "¿Qué tenemos por aquí?$"

SilphCo_7F_Text_Grunt3Defeat::
    .string "¡Luces fuera!$"

SilphCo_7F_Text_Grunt3PostBattle::
    .string "¡No encontrarás a mi JEFE con sólo\n"
    .string "merodear por ahí!$"

SilphCo_7F_Text_JoshuaIntro::
    .string "¡Ejem!\p"
    .string "¿Me confundiste con un empleado\n"
    .string "de SILPH?$"

SilphCo_7F_Text_JoshuaDefeat::
    .string "¡Estoy acabado!$"

SilphCo_7F_Text_JoshuaPostBattle::
    .string "¡A pesar de tu edad, eres genial\n"
    .string "entrenando POKéMON!$"

SilphCo_7F_Text_Grunt1Intro::
    .string "¡Soy uno de los 4 HERMANOS\n"
    .string "ROCKET!$"

SilphCo_7F_Text_Grunt1Defeat::
    .string "¡Auch!\n"
    .string "¡Hermanos, he perdido!$"

SilphCo_7F_Text_Grunt1PostBattle::
    .string "No importa. ¡Mis hermanos\n"
    .string "te devolverán el favor!$"

SilphCo_7F_Text_Grunt2Intro::
    .string "¿Que nos invaden?\n"
    .string "¿No serás tú?$"

SilphCo_7F_Text_Grunt2Defeat::
    .string "¡Vale!\n"
    .string "¡He perdido!$"

SilphCo_7F_Text_Grunt2PostBattle::
    .string "¡Vete a casa antes de que\n"
    .string "se enfade mi JEFE!$"

SilphCo_7F_Text_RivalWhatKeptYou::
    .string "{RIVAL}: ¿Qué te retrasó,\n"
    .string "{PLAYER}?$"

SilphCo_7F_Text_RivalIntro::
    .string "{RIVAL}: ¡Jaja! ¡Sabía que\n"
    .string "aparecerías si esperaba aquí!\p"
    .string "¡Supongo que el TEAM ROCKET\n"
    .string "te retrasó!\l"
    .string "¡Aunque no es que me importe!\p"
    .string "¡Te vi en CIUDAD AZAFRÁN, y\n"
    .string "decidí esperar a ver si mejorabas!$"

SilphCo_7F_Text_RivalDefeat::
    .string "¡Ajá! Así que ya estás para\n"
    .string "luchar contra el JEFE ROCKET...$"

SilphCo_7F_Text_RivalVictory::
    .string "{RIVAL}“おまえなあ‥\p"
    .string "こんな　うでまえじゃ\n"
    .string "まだまだ‥\l"
    .string "いちにんまえ　とは　いえないぜ$"

SilphCo_7F_Text_RivalPostBattle::
    .string "¡Bien, {PLAYER}!\n"
    .string "¡Sigo mejorando y avanzando!\p"
    .string "¡Consultando mi POKéDEX puedo\n"
    .string "saber cuáles son los más fuertes\l"
    .string "y cómo evolucionan!\p"
    .string "¡Voy a la LIGA POKéMON para\n"
    .string "derrotar al ALTO MANDO!\p"
    .string "¡Voy a ser el mejor ENTRENADOR\n"
    .string "del mundo!\p"
    .string "¡{PLAYER}, que tengas suerte!\n"
    .string "¡No te des demasiada paliza!\l"
    .string "¡Hasta luego!$"

SilphCo_7F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P6$"
