SilphCo_7F_Text_HaveMonForSavingUs::
    .ifdef ENGLISH
    .string "Oh! Hi! You're not a ROCKET!\n"
    .string "You came to save us?\l"
    .string "Why, thank you!\p"
    .string "I want you to have this POKéMON\n"
    .string "for saving us.$"
    .endif
    .ifdef SPANISH
    .string "¡Hola! ¡Tú no eres de los ROCKET!\n"
    .string "¿Has venido a salvarnos?\l"
    .string "¡Pues gracias!\p"
    .string "Voy a darte este POKéMON\n"
    .string "por habernos salvado.$"
    .endif

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
    .ifdef ENGLISH
    .string "{PLAYER} obtained a LAPRAS from\n"
    .string "the SILPH employee!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo un LAPRAS\n"
    .string "del empleado de SILPH S.A.!$"
    .endif

SilphCo_7F_Text_ExplainLapras::
    .ifdef ENGLISH
    .string "It's a LAPRAS.\n"
    .string "It's a very intelligent POKéMON.\p"
    .string "We kept it in our lab, but it will\n"
    .string "be much better off with you.\p"
    .string "I think you will be a good TRAINER\n"
    .string "for LAPRAS!\p"
    .string "It's a good swimmer.\n"
    .string "It'll give you a lift across water!$"
    .endif
    .ifdef SPANISH
    .string "Es un LAPRAS.\n"
    .string "Es muy inteligente.\p"
    .string "Lo teníamos en el laboratorio,\n"
    .string "pero estará mucho mejor contigo.\p"
    .string "Seguro que lo entrenarás muy bien.\p"
    .string "Es muy buen nadador.\n"
    .string "¡Podría llevarte incluso!$"
    .endif

SilphCo_7F_Text_RocketBossWentToBoardroom::
    .ifdef ENGLISH
    .string "TEAM ROCKET's BOSS went to the\n"
    .string "boardroom!\p"
    .string "Is our PRESIDENT okay?\n"
    .string "I'm worried.$"
    .endif
    .ifdef SPANISH
    .string "¡El JEFE del TEAM ROCKET fue\n"
    .string "a la sala del consejo!\p"
    .string "¿Está bien el PRESIDENTE?$"
    .endif

SilphCo_7F_Text_OhNo::
    .string "あ‥　もう　もてないぞ$"

SilphCo_7F_Text_SavedAtLast::
    .string "たすかったよ　ありがと！$"

SilphCo_7F_Text_RocketsAfterMasterBall::
    .ifdef ENGLISH
    .string "TEAM ROCKET was after the MASTER\n"
    .string "BALL, which catches any POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡El TEAM ROCKET buscaba la MASTER\n"
    .string "BALL para poder atrapar cualquier\l"
    .string "tipo de POKéMON!$"
    .endif

SilphCo_7F_Text_CanceledMasterBallProject::
    .ifdef ENGLISH
    .string "We canceled the MASTER BALL\n"
    .string "project because of TEAM ROCKET.$"
    .endif
    .ifdef SPANISH
    .string "Cancelamos el proyecto de la\n"
    .string "MASTER BALL por culpa del \l"
    .string "TEAM ROCKET.$"
    .endif

SilphCo_7F_Text_BadIfTeamRocketTookOver::
    .ifdef ENGLISH
    .string "It would be bad if TEAM ROCKET\n"
    .string "took over SILPH or our POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Sería horrible que el TEAM\n"
    .string "ROCKET se hiciera con SILPH S.A.\l"
    .string "o con nuestros POKéMON!$"
    .endif

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
    .ifdef ENGLISH
    .string "Wow!\p"
    .string "You chased off TEAM ROCKET all by\n"
    .string "yourself?$"
    .endif
    .ifdef SPANISH
    .string "¡Uauu!\p"
    .string "¿Echaste tú al TEAM ROCKET?$"
    .endif

SilphCo_7F_Text_ReallyDangerousHere::
    .ifdef ENGLISH
    .string "You!\n"
    .string "It's really dangerous here!\p"
    .string "You came to save me?\n"
    .string "You can't!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye!\n"
    .string "¡Este lugar es muy peligroso!\p"
    .string "¿Has venido a salvarme?\n"
    .string "¡Pues no puedes!$"
    .endif

SilphCo_7F_Text_ThankYouSoMuch::
    .ifdef ENGLISH
    .string "Thank you so much!$"
    .endif
    .ifdef SPANISH
    .string "¡Por fin a salvo! ¡Muchas gracias!$"
    .endif

SilphCo_7F_Text_Grunt3Intro::
    .ifdef ENGLISH
    .string "Uh-oh!\n"
    .string "I smell a little mouse!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh, oh!\n"
    .string "¿Qué tenemos por aquí?$"
    .endif

SilphCo_7F_Text_Grunt3Defeat::
    .ifdef ENGLISH
    .string "Lights out!$"
    .endif
    .ifdef SPANISH
    .string "¡Luces fuera!$"
    .endif

SilphCo_7F_Text_Grunt3PostBattle::
    .ifdef ENGLISH
    .string "You won't find my BOSS by just\n"
    .string "scurrying around!$"
    .endif
    .ifdef SPANISH
    .string "¡No encontrarás a mi JEFE con sólo\n"
    .string "merodear por ahí!$"
    .endif

SilphCo_7F_Text_JoshuaIntro::
    .ifdef ENGLISH
    .string "Heheh!\p"
    .string "You mistook me for a SILPH worker?$"
    .endif
    .ifdef SPANISH
    .string "¡Ejem!\p"
    .string "¿Me confundiste con un empleado\n"
    .string "de SILPH?$"
    .endif

SilphCo_7F_Text_JoshuaDefeat::
    .ifdef ENGLISH
    .string "I'm done!$"
    .endif
    .ifdef SPANISH
    .string "¡Estoy acabado!$"
    .endif

SilphCo_7F_Text_JoshuaPostBattle::
    .ifdef ENGLISH
    .string "Despite your age, you are a\n"
    .string "skilled TRAINER!$"
    .endif
    .ifdef SPANISH
    .string "¡A pesar de tu edad, eres genial\n"
    .string "entrenando POKéMON!$"
    .endif

SilphCo_7F_Text_Grunt1Intro::
    .ifdef ENGLISH
    .string "I am one of the four ROCKET\n"
    .string "BROTHERS!$"
    .endif
    .ifdef SPANISH
    .string "¡Soy uno de los 4 HERMANOS\n"
    .string "ROCKET!$"
    .endif

SilphCo_7F_Text_Grunt1Defeat::
    .ifdef ENGLISH
    .string "Aack!\n"
    .string "Brothers, I lost!$"
    .endif
    .ifdef SPANISH
    .string "¡Auch!\n"
    .string "¡Hermanos, he perdido!$"
    .endif

SilphCo_7F_Text_Grunt1PostBattle::
    .ifdef ENGLISH
    .string "Doesn't matter.\n"
    .string "My brothers will repay the favor!$"
    .endif
    .ifdef SPANISH
    .string "No importa. ¡Mis hermanos\n"
    .string "te devolverán el favor!$"
    .endif

SilphCo_7F_Text_Grunt2Intro::
    .ifdef ENGLISH
    .string "A child intruder?\n"
    .string "That must be you!$"
    .endif
    .ifdef SPANISH
    .string "¿Que nos invaden?\n"
    .string "¿No serás tú?$"
    .endif

SilphCo_7F_Text_Grunt2Defeat::
    .ifdef ENGLISH
    .string "Fine!\n"
    .string "I lost!$"
    .endif
    .ifdef SPANISH
    .string "¡Vale!\n"
    .string "¡He perdido!$"
    .endif

SilphCo_7F_Text_Grunt2PostBattle::
    .ifdef ENGLISH
    .string "Go on home before my BOSS gets\n"
    .string "ticked off!$"
    .endif
    .ifdef SPANISH
    .string "¡Vete a casa antes de que\n"
    .string "se enfade mi JEFE!$"
    .endif

SilphCo_7F_Text_RivalWhatKeptYou::
    .ifdef ENGLISH
    .string "{RIVAL}: What kept you, {PLAYER}?$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¿Qué te retrasó,\n"
    .string "{PLAYER}?$"
    .endif

SilphCo_7F_Text_RivalIntro::
    .ifdef ENGLISH
    .string "{RIVAL}: Hahaha! I thought you'd\n"
    .string "turn up if I waited here!\p"
    .string "I guess TEAM ROCKET slowed you\n"
    .string "down! Not that I care!\p"
    .string "I saw you in SAFFRON, so I decided\n"
    .string "to see if you got better!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Jaja! ¡Sabía que\n"
    .string "aparecerías si esperaba aquí!\p"
    .string "¡Supongo que el TEAM ROCKET\n"
    .string "te retrasó!\l"
    .string "¡Aunque no es que me importe!\p"
    .string "¡Te vi en CIUDAD AZAFRÁN, y\n"
    .string "decidí esperar a ver si mejorabas!$"
    .endif

SilphCo_7F_Text_RivalDefeat::
    .ifdef ENGLISH
    .string "Oh, man!\n"
    .string "So, you are ready for BOSS\l"
    .string "ROCKET!$"
    .endif
    .ifdef SPANISH
    .string "¡Ajá! Así que ya estás para\n"
    .string "luchar contra el JEFE ROCKET...$"
    .endif

SilphCo_7F_Text_RivalVictory::
    .string "{RIVAL}“おまえなあ‥\p"
    .string "こんな　うでまえじゃ\n"
    .string "まだまだ‥\l"
    .string "いちにんまえ　とは　いえないぜ$"

SilphCo_7F_Text_RivalPostBattle::
    .ifdef ENGLISH
    .string "Well, {PLAYER}!\n"
    .string "I'm moving on up and ahead!\p"
    .string "By checking my POKéDEX, I'm\n"
    .string "starting to see what's strong and\l"
    .string "how they evolve!\p"
    .string "Am I a genius or what?\p"
    .string "I'm going to the POKéMON LEAGUE to\n"
    .string "boot out the ELITE FOUR.\p"
    .string "I'll become the world's most\n"
    .string "powerful TRAINER!\p"
    .string "{PLAYER}, well, good luck to you!\n"
    .string "Don't sweat it!\l"
    .string "Smell ya!$"
    .endif
    .ifdef SPANISH
    .string "¡Bien, {PLAYER}!\n"
    .string "¡Sigo mejorando y avanzando!\p"
    .string "¡Consultando mi POKéDEX puedo\n"
    .string "saber cuáles son los más fuertes\l"
    .string "y cómo evolucionan!\p"
    .string "¡Voy a la LIGA POKéMON para\n"
    .string "derrotar al ALTO MANDO!\p"
    .string "¡Voy a ser el mejor ENTRENADOR\n"
    .string "del mundo!\p"
    .string "¡{PLAYER}, que tengas suerte!\n"
    .string "¡No te des demasiada paliza!\l"
    .string "¡Hasta luego!$"
    .endif

SilphCo_7F_Text_FloorSign::
    .ifdef ENGLISH
    .string "SILPH CO. HEAD OFFICE\n"
    .string "7F$"
    .endif
    .ifdef SPANISH
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P6$"
    .endif

