Route8_WestEntrance_Text_ThirstyOnGuardDuty::
    .string "Estoy de guardia. ¡Uauu!\n"
    .string "¡Qué sed tengo!\p"
    .string "Espera. La ruta está cerrada.$"

Route8_WestEntrance_Text_ThatTeaLooksTasty::
    .string "Mmm, ese TÉ que llevas ahí...\n"
    .string "Tiene una pinta buenísima...$"

Route8_WestEntrance_Text_ThanksIllShareTeaWithGuards::
    .string "¿Cómo? ¿Que me lo puedo tomar?\n"
    .string "¡Vaya, gracias!\l"
    .string "... ...\l"
    .string "Glug, glug...\l"
    .string "... ...\l"
    .string "Gulp...\l"
    .string "Si quieres ir a CIUDAD AZAFRÁN...\l"
    .string "Por mí puedes pasar.\p"
    .string "Le daré un poco de TÉ a mis\n"
    .string "compañeros.$"

Route8_WestEntrance_Text_HiHowsItGoing::
    .string "¡Oye! ¡Gracias por las bebidas!$"
