Route8_WestEntrance_Text_ThirstyOnGuardDuty::
    .ifdef ENGLISH
    .string "I'm on guard duty.\n"
    .string "Gee, I'm thirsty, though!\p"
    .string "Oh, wait there, the road's closed.$"
    .endif
    .ifdef SPANISH
    .string "Estoy de guardia. ¡Uauu!\n"
    .string "¡Qué sed tengo!\p"
    .string "Espera. La ruta está cerrada.$"
    .endif

Route8_WestEntrance_Text_ThatTeaLooksTasty::
    .ifdef ENGLISH
    .string "Oh, that TEA…\n"
    .string "It looks awfully tasty…$"
    .endif
    .ifdef SPANISH
    .string "Mmm, ese TÉ que llevas ahí...\n"
    .string "Tiene una pinta buenísima...$"
    .endif

Route8_WestEntrance_Text_ThanksIllShareTeaWithGuards::
    .ifdef ENGLISH
    .string "Huh? I can have this drink?\n"
    .string "Gee, thanks!\l"
    .string "… …\l"
    .string "Glug, glug…\l"
    .string "… …\l"
    .string "Gulp…\l"
    .string "If you want to go to SAFFRON\l"
    .string "CITY…\l"
    .string "… …\l"
    .string "You can go on through.\p"
    .string "I'll share this TEA with the other\n"
    .string "guards!$"
    .endif
    .ifdef SPANISH
    .string "¿Cómo? ¿Que me lo puedo tomar?\n"
    .string "¡Vaya, gracias!\l"
    .string "... ...\l"
    .string "Glug, glug...\l"
    .string "... ...\l"
    .string "Gulp...\l"
    .string "Si quieres ir a CIUDAD AZAFRÁN...\l"
    .string "Por mí puedes pasar.\p"
    .string "Le daré un poco de TÉ a mis\n"
    .string "compañeros.$"
    .endif

Route8_WestEntrance_Text_HiHowsItGoing::
    .ifdef ENGLISH
    .string "Hi, how's it going?$"
    .endif
    .ifdef SPANISH
    .string "¡Oye! ¡Gracias por las bebidas!$"
    .endif

