ThreeIsland_House1_Text_YoureAlwaysSoCool::
    .ifdef ENGLISH
    .string "LOSTELLE: Hi, {PLAYER}!\n"
    .string "You're always so cool!\p"
    .string "I'll make lunch for you, too, one\n"
    .string "day, {PLAYER}.$"
    .endif
    .ifdef SPANISH
    .string "PEDRITA: ¡Hola, {PLAYER}!\n"
    .string "¡Iempre edes guay!\p"
    .string "¡He hecho comidita pada ti,\n"
    .string "{PLAYER}!$"
    .endif

ThreeIsland_House1_Text_RareRocksGemsDisplayed::
    .ifdef ENGLISH
    .string "Rare rocks and gems are displayed.$"
    .endif
    .ifdef SPANISH
    .string "Hay rocas raras y gemas.$"
    .endif

