SixIsland_WaterPath_House1_Text_LoveItNeedItHeracross::
    .ifdef ENGLISH
    .string "Hera, hera, HERACROSS!\n"
    .string "Big and shiny, it's the bug boss!\l"
    .string "Love it, need it, HERACROSS!$"
    .endif
    .ifdef SPANISH
    .string "¡Hera, hera, HERACROSS!\n"
    .string "¡Es muy grande, es el mejor!\l"
    .string "¡Hera, hera, HERACROSS!$"
    .endif

SixIsland_WaterPath_House1_Text_MayIMeasureHeracross::
    .ifdef ENGLISH
    .string "Eeeeek!\n"
    .string "That's a HERACROSS!\p"
    .string "Please, please, may I measure how\n"
    .string "big it is?$"
    .endif
    .ifdef SPANISH
    .string "¡Aaaaaaah!\n"
    .string "¡Tienes un HERACROSS!\p"
    .string "Porfa, porfa, ¿puedo ver cuánto\n"
    .string "mide?$"
    .endif

SixIsland_WaterPath_House1_Text_ItsXInchesDeserveReward::
    .ifdef ENGLISH
    .string "Eeeek, it's {STR_VAR_2} inches!\n"
    .string "I've never seen anything like this!\l"
    .string "You deserve a reward!$"
    .endif
    .ifdef SPANISH
    .string "¡Guau, {STR_VAR_2} cm!\n"
    .string "¡Nunca he visto nada igual!\l"
    .string "¡Toma, te mereces este premio!$"
    .endif

SixIsland_WaterPath_House1_Text_WantToSeeBiggerOne::
    .ifdef ENGLISH
    .string "I want to see a much, much bigger\n"
    .string "HERACROSS than that one.\p"
    .string "Oh, how I adore them, big\n"
    .string "HERACROSS!$"
    .endif
    .ifdef SPANISH
    .string "Me encantaría ver un HERACROSS\n"
    .string "mucho más grande que ése.\p"
    .string "¡Es que me alucinan los HERACROSS\n"
    .string "grandes!$"
    .endif

SixIsland_WaterPath_House1_Text_ItsXInchesSameAsBefore::
    .ifdef ENGLISH
    .string "Huh? This {STR_VAR_2}-inch measurement…\n"
    .string "Oh, boo! It's the same as before.$"
    .endif
    .ifdef SPANISH
    .string "¿Mmm? {STR_VAR_2} cm...\n"
    .string "¡Pero si es lo mismo que antes!$"
    .endif

SixIsland_WaterPath_House1_Text_ItsXInchesYInchesWasBiggest::
    .ifdef ENGLISH
    .string "Oh, it's just {STR_VAR_2} inches.\n"
    .string "The HERACROSS before was bigger.\p"
    .string "It was {STR_VAR_3} inches, the biggest\n"
    .string "HERACROSS you've brought me.$"
    .endif
    .ifdef SPANISH
    .string "Vaya, {STR_VAR_2} cm sólo...\n"
    .string "El HERACROSS de antes era mayor.\p"
    .string "Medía {STR_VAR_3} cm, ése ha sido el\n"
    .string "HERACROSS más grande que me\l"
    .string "has traído hasta ahora.$"
    .endif

SixIsland_WaterPath_House1_Text_ThisWontDo::
    .ifdef ENGLISH
    .string "Oh, no! This won't do!\p"
    .string "HERACROSS looks much more macho\n"
    .string "and cool, and has a lovely horn!$"
    .endif
    .ifdef SPANISH
    .string "¡No, no y no!\p"
    .string "HERACROSS es mucho mejor,\n"
    .string "es más guay y se ve más fuerte.\l"
    .string "¡Y tiene un cuerno chulísimo!$"
    .endif

SixIsland_WaterPath_House1_Text_YourBagIsFull::
    .ifdef ENGLISH
    .string "Your BAG is full.\n"
    .string "My reward won't fit.$"
    .endif
    .ifdef SPANISH
    .string "Tienes la MOCHILA hasta arriba.\n"
    .string "No hay sitio para mi premio.$"
    .endif

SixIsland_WaterPath_House1_Text_BiggestHeracrossIsXInches::
    .ifdef ENGLISH
    .string "The biggest HERACROSS that I have\n"
    .string "ever seen measured so far is:\p"
    .string "{STR_VAR_3} inches!$"
    .endif
    .ifdef SPANISH
    .string "El mayor HERACROSS que he\n"
    .string "medido hasta ahora alcanzaba:\p"
    .string "¡{STR_VAR_3} cm!$"
    .endif

SixIsland_WaterPath_House1_Text_BlankChartOfSomeSort::
    .ifdef ENGLISH
    .string "It's a blank chart of some sort.\p"
    .string "It has spaces for writing in\n"
    .string "records of some kind.$"
    .endif
    .ifdef SPANISH
    .string "Es una especie de cuadro y\n"
    .string "está en blanco.\p"
    .string "Tiene casillas para anotar cosas.$"
    .endif

