ViridianCity_Gym_Text_GiovanniIntro::
    .ifdef ENGLISH
    .string "Fwahahaha!\n"
    .string "Welcome to my hideout!\p"
    .string "It shall be so until I can restore\n"
    .string "TEAM ROCKET to its former glory.\p"
    .string "But, you have found me again.\n"
    .string "So be it.\l"
    .string "This time, I'm not holding back!\p"
    .string "Once more, you shall face\n"
    .string "GIOVANNI, the greatest TRAINER!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"
    .endif
    .ifdef SPANISH
    .string "¡Je, je, je!\n"
    .string "¡Ésta es mi guarida!\p"
    .string "¡Quería volver a formar al TEAM\n"
    .string "ROCKET desde aquí!\p"
    .string "¡Pero has vuelto a encontrarme!\n"
    .string "¡Estoy que me subo por las\l"
    .string "paredes! ¡Esta vez, verás!\p"
    .string "¡Volverás a enfrentarte al gran\n"
    .string "GIOVANNI, al mejor de los\l"
    .string "ENTRENADORES!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"
    .endif

ViridianCity_Gym_Text_GiovanniDefeat::
    .ifdef ENGLISH
    .string "Ha!\n"
    .string "That was a truly intense fight.\l"
    .string "You have won!\p"
    .string "As proof, here is the EARTHBADGE!\n"
    .string "{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"
    .endif
    .ifdef SPANISH
    .string "¡Ja!\n"
    .string "¡Ha sido un duro combate!\l"
    .string "¡Y has ganado!\p"
    .string "¡Como premio, toma esta MEDALLA\n"
    .string "TIERRA!{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"
    .endif

ViridianCity_Gym_Text_GiovanniPostBattle::
    .ifdef ENGLISH
    .string "Having lost in this fashion, \n"
    .string "I can't face my followers.\l"
    .string "I have betrayed their trust.\p"
    .string "As of today, TEAM ROCKET is\n"
    .string "finished forever!\p"
    .string "As for myself, I shall dedicate\n"
    .string "my life to training again.\p"
    .string "Let us meet again someday!\n"
    .string "Farewell!$"
    .endif
    .ifdef SPANISH
    .string "¡He perdido, ya no soy digno\n"
    .string "de dirigir a mis secuaces!\p"
    .string "¡Se acabó el TEAM ROCKET!\p"
    .string "¡Dedicaré mi vida al estudio\n"
    .string "de los POKéMON!\p"
    .string "¡Espero que nos volvamos a ver!\n"
    .string "¡Adiós!$"
    .endif

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
    .ifdef ENGLISH
    .string "The EARTHBADGE makes POKéMON of\n"
    .string "any level obey without question.\p"
    .string "It is evidence of your mastery as\n"
    .string "a POKéMON TRAINER.\p"
    .string "With it, you can challenge the\n"
    .string "POKéMON LEAGUE.\p"
    .string "Also, take this TM.\p"
    .string "Consider it a gift for your POKéMON\n"
    .string "LEAGUE challenge.$"
    .endif
    .ifdef SPANISH
    .string "¡Con la MEDALLA TIERRA, todos\n"
    .string "los POKéMON te obedecerán!\p"
    .string "¡Es una prueba de tu maestría\n"
    .string "entrenando POKéMON!\p"
    .string "¡Con ella podrás acceder\n"
    .string "a la LIGA POKéMON!\p"
    .string "¡Es mi regalo por desafiar\n"
    .string "a la LIGA POKéMON!$"
    .endif

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
    .ifdef ENGLISH
    .string "{PLAYER} received TM26\n"
    .string "from GIOVANNI.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo la MT26\n"
    .string "de manos de GIOVANNI!$"
    .endif

ViridianCity_Gym_Text_ExplainTM26::
    .ifdef ENGLISH
    .string "TM26 contains EARTHQUAKE.\p"
    .string "It is a powerful attack that causes\n"
    .string "a massive tremor.\p"
    .string "I made it when I ran the GYM here,\n"
    .string "far too long ago… $"
    .endif
    .ifdef SPANISH
    .string "¡La MT26 es TERREMOTO!\p"
    .string "¡Es muy potente, causa un\n"
    .string "temblor devastador!\p"
    .string "La inventé cuando dirigía este\n"
    .string "GIMNASIO, hace ya mucho tiempo...$"
    .endif

ViridianCity_Gym_Text_YouDoNotHaveSpace::
    .ifdef ENGLISH
    .string "You do not have space for this!$"
    .endif
    .ifdef SPANISH
    .string "¡Llevas muchas cosas!$"
    .endif

ViridianCity_Gym_Text_YujiIntro::
    .ifdef ENGLISH
    .string "Heh!\n"
    .string "You must be running out of steam\l"
    .string "by now!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye!\n"
    .string "Ya no debe de quedarte nada\l"
    .string "de energía, ¿no?$"
    .endif

ViridianCity_Gym_Text_YujiDefeat::
    .ifdef ENGLISH
    .string "I ran out of gas!$"
    .endif
    .ifdef SPANISH
    .string "¡Me he quedado sin fuerza!$"
    .endif

ViridianCity_Gym_Text_YujiPostBattle::
    .ifdef ENGLISH
    .string "You'll need power to keep up with\n"
    .string "our GYM LEADER.$"
    .endif
    .ifdef SPANISH
    .string "¡Necesitas potencia para luchar\n"
    .string "contra el LÍDER del GIMNASIO!$"
    .endif

ViridianCity_Gym_Text_AtsushiIntro::
    .ifdef ENGLISH
    .string "Rrrroar!\n"
    .string "I'm working myself into a rage!$"
    .endif
    .ifdef SPANISH
    .string "¡Groaar!\n"
    .string "¡Me estoy mosqueando!$"
    .endif

ViridianCity_Gym_Text_AtsushiDefeat::
    .ifdef ENGLISH
    .string "Wargh!$"
    .endif
    .ifdef SPANISH
    .string "¡Rargh!$"
    .endif

ViridianCity_Gym_Text_AtsushiPostBattle::
    .ifdef ENGLISH
    .string "I'm still not worthy!$"
    .endif
    .ifdef SPANISH
    .string "¡No me merezco nada!$"
    .endif

ViridianCity_Gym_Text_JasonIntro::
    .ifdef ENGLISH
    .string "POKéMON and I, we make wonderful\n"
    .string "music together!$"
    .endif
    .ifdef SPANISH
    .string "¡Mis POKéMON y yo hacemos\n"
    .string "muy buena música!$"
    .endif

ViridianCity_Gym_Text_JasonDefeat::
    .ifdef ENGLISH
    .string "You are in perfect harmony!$"
    .endif
    .ifdef SPANISH
    .string "¡Estás en perfecta armonía!$"
    .endif

ViridianCity_Gym_Text_JasonPostBattle::
    .ifdef ENGLISH
    .string "Do you know the identity of our\n"
    .string "GYM LEADER?$"
    .endif
    .ifdef SPANISH
    .string "¿Sabes quién es el LÍDER de\n"
    .string "nuestro GIMNASIO?$"
    .endif

ViridianCity_Gym_Text_KiyoIntro::
    .ifdef ENGLISH
    .string "Karate is the ultimate form of\n"
    .string "martial arts!$"
    .endif
    .ifdef SPANISH
    .string "¡El karate es lo máximo en artes\n"
    .string "marciales!$"
    .endif

ViridianCity_Gym_Text_KiyoDefeat::
    .ifdef ENGLISH
    .string "Aiyah!$"
    .endif
    .ifdef SPANISH
    .string "¡Ayyyy!$"
    .endif

ViridianCity_Gym_Text_KiyoPostBattle::
    .ifdef ENGLISH
    .string "If my POKéMON were as good at\n"
    .string "karate as I…$"
    .endif
    .ifdef SPANISH
    .string "Si mis POKéMON fueran buenos\n"
    .string "karatekas...$"
    .endif

ViridianCity_Gym_Text_WarrenIntro::
    .ifdef ENGLISH
    .string "The truly talented win with style.$"
    .endif
    .ifdef SPANISH
    .string "¡Los más hábiles ganan con estilo!$"
    .endif

ViridianCity_Gym_Text_WarrenDefeat::
    .ifdef ENGLISH
    .string "I lost my grip!$"
    .endif
    .ifdef SPANISH
    .string "¡He perdido el control!$"
    .endif

ViridianCity_Gym_Text_WarrenPostBattle::
    .ifdef ENGLISH
    .string "The LEADER will scold me for\n"
    .string "losing this way…$"
    .endif
    .ifdef SPANISH
    .string "¡El LÍDER me va a reñir!$"
    .endif

ViridianCity_Gym_Text_TakashiIntro::
    .ifdef ENGLISH
    .string "I'm the KARATE KING!\n"
    .string "Your fate rests with me!$"
    .endif
    .ifdef SPANISH
    .string "¡Soy el REY del KARATE!\n"
    .string "¡Te tengo en mis manos!$"
    .endif

ViridianCity_Gym_Text_TakashiDefeat::
    .ifdef ENGLISH
    .string "Ayah!$"
    .endif
    .ifdef SPANISH
    .string "¡Aaah!$"
    .endif

ViridianCity_Gym_Text_TakashiPostBattle::
    .ifdef ENGLISH
    .string "The POKéMON LEAGUE?\n"
    .string "You? Don't get cocky!$"
    .endif
    .ifdef SPANISH
    .string "¿La LIGA POKéMON? ¿Tú?\n"
    .string "¿Pero quién te crees que eres?$"
    .endif

ViridianCity_Gym_Text_ColeIntro::
    .ifdef ENGLISH
    .string "Your POKéMON will cower at the\n"
    .string "crack of my whip!$"
    .endif
    .ifdef SPANISH
    .string "¡Tus POKéMON se arrodillarán\n"
    .string "de un solo latigazo!$"
    .endif

ViridianCity_Gym_Text_ColeDefeat::
    .ifdef ENGLISH
    .string "Yowch!\n"
    .string "Whiplash!$"
    .endif
    .ifdef SPANISH
    .string "¡Auch!\n"
    .string "¡Vaya latigazo!$"
    .endif

ViridianCity_Gym_Text_ColePostBattle::
    .ifdef ENGLISH
    .string "Wait!\n"
    .string "I was just careless!$"
    .endif
    .ifdef SPANISH
    .string "¡Espera!\n"
    .string "¡No he tenido ningún cuidado!$"
    .endif

ViridianCity_Gym_Text_SamuelIntro::
    .ifdef ENGLISH
    .string "VIRIDIAN GYM was closed for a\n"
    .string "long time.\p"
    .string "But now, our LEADER is back!$"
    .endif
    .ifdef SPANISH
    .string "¡El GIMNASIO de VERDE estuvo\n"
    .string "cerrado mucho tiempo, pero nuestro\l"
    .string "LÍDER ha vuelto!$"
    .endif

ViridianCity_Gym_Text_SamuelDefeat::
    .ifdef ENGLISH
    .string "I was beaten?$"
    .endif
    .ifdef SPANISH
    .string "¿Me has ganado?$"
    .endif

ViridianCity_Gym_Text_SamuelPostBattle::
    .ifdef ENGLISH
    .string "You can go on to the POKéMON\n"
    .string "LEAGUE only by defeating our GYM\l"
    .string "LEADER!$"
    .endif
    .ifdef SPANISH
    .string "¡Accederás a la LIGA POKéMON\n"
    .string "si ganas a nuestro LÍDER!$"
    .endif

ViridianCity_Gym_Text_GymGuyAdvice::
    .ifdef ENGLISH
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "Even I don't know the VIRIDIAN\n"
    .string "LEADER's identity.\p"
    .string "But one thing's certain.\n"
    .string "This will be the toughest of all\l"
    .string "the GYM LEADERS.\p"
    .string "Also, I heard that the TRAINERS\n"
    .string "here like GROUND-type POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, aspirante al título!\p"
    .string "¡Ni yo conozco la identidad del\n"
    .string "LÍDER de VERDE!\p"
    .string "¡Debe de ser el más duro de todos\n"
    .string "los LÍDERES de GIMNASIO!\p"
    .string "¡Dicen que estos ENTRENADORES usan\n"
    .string "los POKéMON del tipo TIERRA!$"
    .endif

ViridianCity_Gym_Text_GymGuyPostVictory::
    .ifdef ENGLISH
    .string "Blow me away! GIOVANNI was the\n"
    .string "GYM LEADER of VIRIDIAN?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué dices? ¿Que GIOVANNI era\n"
    .string "el LÍDER del GIMNASIO?$"
    .endif

ViridianCity_Gym_Text_GymStatue::
    .ifdef ENGLISH
    .string "VIRIDIAN POKéMON GYM\n"
    .string "LEADER: ?\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CIUDAD VERDE: (?)\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"
    .endif

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .ifdef ENGLISH
    .string "VIRIDIAN POKéMON GYM\n"
    .string "LEADER: GIOVANNI\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CIUDAD VERDE: GIOVANNI\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"
    .endif

