ViridianCity_Gym_Text_GiovanniIntro::
	.string "Haha! Willkommen in meinem\n"
	.string "Geheimversteck!\p"
	.string "Hier wollte ich das TEAM ROCKET\n"
	.string "wiederauferstehen lassen!\p"
	.string "Aber du hast mich schon wieder\n"
	.string "aufgespürt! Also gut! Dieses Mal\l"
	.string "kenne ich keine Gnade!\p"
	.string "Ich, GIOVANNI, der größte aller\n"
	.string "TRAINER, fordere Revanche!{PLAY_BGM MUS_ENCOUNTER_ROCKET}$"

ViridianCity_Gym_Text_GiovanniDefeat::
	.string "Ha!\n"
	.string "Der Kampf war hart, aber fair!\l"
	.string "Du hast gewonnen!\p"
	.string "Nimm bitte den ERDORDEN zum\n"
	.string "Zeichen meiner Anerkennung!{PAUSE_MUSIC}{PLAY_BGM MUS_OBTAIN_BADGE}{PAUSE}\n"
	.string "{PAUSE 86}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_GiovanniPostBattle::
	.string "Ich habe meinen Meister gefunden!\n"
	.string "Meine Taten waren schlecht...\l"
	.string "Ich löse das TEAM ROCKET auf!\p"
	.string "Von nun an widme ich mein Leben\n"
	.string "dem Studium der POKéMON!\p"
	.string "Vielleicht sehen wir uns eines\n"
	.string "Tages wieder! Lebe wohl!$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
	.string "Als Träger des ERDORDENS werden\n"
	.string "dir alle POKéMON jeglichen Levels\l"
	.string "gehorchen!\p"
	.string "Er stellt den Beweis deines Könnens\n"
	.string "als POKéMON TRAINER dar!\p"
	.string "Außerdem gewährt er dir den Zugang\n"
	.string "zur POKéMON LIGA!\p"
	.string "Nimm dieses Geschenk mit in dein\n"
	.string "POKéMON LIGA-Abenteuer!$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
	.string "{PLAYER} erhält\n"
	.string "TM26!$"

ViridianCity_Gym_Text_ExplainTM26::
	.string "TM26 ist ERDBEBEN!\p"
	.string "Eine sehr starke Attacke, die ein\n"
	.string "starkes Beben verursacht.\p"
	.string "Ich habe sie vor langer Zeit\n"
	.string "geschaffen, als ich hier noch\l"
	.string "ARENALEITER war.$"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
	.string "Du kannst keine weiteren Items mehr\n"
	.string "tragen!$"

ViridianCity_Gym_Text_YujiIntro::
	.string "Hehe!\n"
	.string "So langsam geht dir die Luft aus!$"

ViridianCity_Gym_Text_YujiDefeat::
	.string "Mir gehen die POKéMON aus!!!$"

ViridianCity_Gym_Text_YujiPostBattle::
	.string "Du musst stark sein, um unserem\n"
	.string "ARENALEITER entgegenzutreten!$"

ViridianCity_Gym_Text_AtsushiIntro::
	.string "Kiai! Mit diesem Kampfschrei\n"
	.string "mobilisiere ich meine Kräfte!$"

ViridianCity_Gym_Text_AtsushiDefeat::
	.string "Meister, verzeihe er mir!$"

ViridianCity_Gym_Text_AtsushiPostBattle::
	.string "Ich bin deiner Gnade unwürdig!$"

ViridianCity_Gym_Text_JasonIntro::
	.string "Ich bilde mit meinen POKéMON eine\n"
	.string "Einheit wie Yin und Yang!$"

ViridianCity_Gym_Text_JasonDefeat::
	.string "Deine POKéMON harmonieren gut mit\n"
	.string "dir!$"

ViridianCity_Gym_Text_JasonPostBattle::
	.string "Kennst du die Identität unseres\n"
	.string "ARENALEITERs?$"

ViridianCity_Gym_Text_KiyoIntro::
	.string "Karate ist die Königsdisziplin des\n"
	.string "Kampfsports!$"

ViridianCity_Gym_Text_KiyoDefeat::
	.string "Ahh!$"

ViridianCity_Gym_Text_KiyoPostBattle::
	.string "Ach, wären meine POKéMON doch\n"
	.string "auch so starke Karateka wie ich!$"

ViridianCity_Gym_Text_WarrenIntro::
	.string "Der Stil zeichnet einen großen\n"
	.string "Kämpfer aus!$"

ViridianCity_Gym_Text_WarrenDefeat::
	.string "Ich habe den Halt verloren!$"

ViridianCity_Gym_Text_WarrenPostBattle::
	.string "Der Meister wird mich schelten!$"

ViridianCity_Gym_Text_TakashiIntro::
	.string "Ich bin der KARATE-KÖNIG!\n"
	.string "Ich besiegle dein Schicksal!$"

ViridianCity_Gym_Text_TakashiDefeat::
	.string "Ahh!$"

ViridianCity_Gym_Text_TakashiPostBattle::
	.string "Du willst in die POKéMON LIGA? Du?\n"
	.string "Werde bloß nicht größenwahnsinnig!$"

ViridianCity_Gym_Text_ColeIntro::
	.string "Allein mein Anblick lässt deine\n"
	.string "POKéMON schaudern!$"

ViridianCity_Gym_Text_ColeDefeat::
	.string "Sie kringeln sich vor Lachen! NEIN!$"

ViridianCity_Gym_Text_ColePostBattle::
	.string "Moment!\n"
	.string "Ich war sorglos!$"

ViridianCity_Gym_Text_SamuelIntro::
	.string "Die ARENAHALLE von VERTANIA CITY\n"
	.string "war lange Zeit geschlossen, doch\l"
	.string "nun ist der MEISTER zurück!$"

ViridianCity_Gym_Text_SamuelDefeat::
	.string "Ich wurde besiegt?$"

ViridianCity_Gym_Text_SamuelPostBattle::
	.string "Du kannst nur in die POKéMON LIGA,\n"
	.string "wenn du unseren ARENALEITER\l"
	.string "besiegst!$"

ViridianCity_Gym_Text_GymGuyAdvice::
	.string "Heh!\n"
	.string "Warte, du Champion in spe!\p"
	.string "Nicht einmal ich kenne die\n"
	.string "Identität des ARENALEITERs\l"
	.string "von VERTANIA CITY!\p"
	.string "Soweit ich weiß, ist er von allen\n"
	.string "ARENALEITERn der gefährlichste!\p"
	.string "Die TRAINER hier setzen gerne\n"
	.string "BODEN-POKéMON ein!$"

ViridianCity_Gym_Text_GymGuyPostVictory::
	.string "Das gibt es nicht!\n"
	.string "GIOVANNI war hier ARENALEITER?$"

ViridianCity_Gym_Text_GymStatue::
	.string "VERTANIA POKéMON-ARENA\n"
	.string "LEITUNG: ?\p"
	.string "BISHERIGE SIEGER:\n"
	.string "{RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
	.string "VERTANIA POKéMON-ARENA\n"
	.string "LEITUNG: GIOVANNI\p"
	.string "BISHERIGE SIEGER:\n"
	.string "{RIVAL}, {PLAYER}$"

