RocketHideout_B1F_Text_Grunt1Intro::
    .string "¿Quién eres tú?\n"
    .string "¿Y cómo has llegado aquí?$"

RocketHideout_B1F_Text_Grunt1Defeat::
    .string "¡Auuu!\n"
    .string "¡He perdido!$"

RocketHideout_B1F_Text_Grunt1PostBattle::
    .string "¿Vas a luchar contra el TEAM\n"
    .string "ROCKET?$"

RocketHideout_B1F_Text_Grunt2Intro::
    .string "¡Has destrozado nuestros planes!$"

RocketHideout_B1F_Text_Grunt2Defeat::
    .string "¡Chamuscado!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
    .string "¡No te vas a salir con la tuya,\n"
    .string "impresentable!$"

RocketHideout_B1F_Text_Grunt3Intro::
    .string "¡Alerta! ¡Nos invaden!$"

RocketHideout_B1F_Text_Grunt3Defeat::
    .string "¡¡¡No lo he conseguido!!!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
    .string "¿El SCOPE SILPH?\n"
    .string "¡No sé dónde está!$"

RocketHideout_B1F_Text_Grunt4Intro::
    .string "¿Por qué has venido aquí?$"

RocketHideout_B1F_Text_Grunt4Defeat::
    .string "¡Esto no funcionará!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
    .string "¡Vale, hablaré! ¡Toma el ascensor\n"
    .string "para ver a mi JEFE!$"

RocketHideout_B1F_Text_Grunt5Intro::
    .string "¿Te has perdido? Pobre...$"

RocketHideout_B1F_Text_Grunt5Defeat::
    .string "¿Por qué...?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
    .string "¡Con tanto lío se ha abierto\n"
    .string "la puerta!$"
