RocketHideout_B1F_Text_Grunt1Intro::
	.string "T'es qui? T'as fait comment\n"
	.string "pour entrer ici?$"

RocketHideout_B1F_Text_Grunt1Defeat::
	.string "Aïe!\n"
	.string "J'suis battu!$"

RocketHideout_B1F_Text_Grunt1PostBattle::
	.string "Qu'est-ce que tu as contre\n"
	.string "la TEAM ROCKET?$"

RocketHideout_B1F_Text_Grunt2Intro::
	.string "Tu as cassé nos plans!!!$"

RocketHideout_B1F_Text_Grunt2Defeat::
	.string "Enfer!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
	.string "Non, non! Tu ne t'en tireras pas\n"
	.string "comme ça!$"

RocketHideout_B1F_Text_Grunt3Intro::
	.string "Intrus! \n"
	.string "ALERTE! ALERTE!$"

RocketHideout_B1F_Text_Grunt3Defeat::
	.string "J'ai…\n"
	.string "échoué!!!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
	.string "SCOPE SYLPHE?\n"
	.string "C'est quoi donc?$"

RocketHideout_B1F_Text_Grunt4Intro::
	.string "Tiens, pourquoi t'es là?$"

RocketHideout_B1F_Text_Grunt4Defeat::
	.string "J'suis pas à la hauteur!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
	.string "OK, OK, je parle! Prends donc\n"
	.string "l'ascenseur et tu verras mon chef!$"

RocketHideout_B1F_Text_Grunt5Intro::
	.string "T'as perdu ton chemin?$"

RocketHideout_B1F_Text_Grunt5Defeat::
	.string "Quoi…?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
	.string "Oups, ce combat a ouvert la porte!$"

