RocketHideout_B1F_Text_Grunt1Intro::
	.string "Wie kommst du hierher?$"

RocketHideout_B1F_Text_Grunt1Defeat::
	.string "Autsch!\n"
	.string "Geschlagen!$"

RocketHideout_B1F_Text_Grunt1PostBattle::
	.string "Willst du dich mit dem TEAM ROCKET\n"
	.string "anlegen?$"

RocketHideout_B1F_Text_Grunt2Intro::
	.string "Du hast Mut, hier hereinzuplatzen!$"

RocketHideout_B1F_Text_Grunt2Defeat::
	.string "Mist! Versagt!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
	.string "Unsere Rache wird grauenvoll, du\n"
	.string "Rotzblag!$"

RocketHideout_B1F_Text_Grunt3Intro::
	.string "Alarm!\n"
	.string "Eindringlinge!$"

RocketHideout_B1F_Text_Grunt3Defeat::
	.string "Ich konnte ihn nicht stoppen!!!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
	.string "SILPH SCOPE?\n"
	.string "Ich weiß nicht, wovon du redest!$"

RocketHideout_B1F_Text_Grunt4Intro::
	.string "Was willst du überhaupt hier?$"

RocketHideout_B1F_Text_Grunt4Defeat::
	.string "Das kann nicht funktionieren!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
	.string "O.K., O.K., ich packe aus!\n"
	.string "Benutze den Aufzug zum BOSS!$"

RocketHideout_B1F_Text_Grunt5Intro::
	.string "Was hast du hier verloren?$"

RocketHideout_B1F_Text_Grunt5Defeat::
	.string "Was ist passiert?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
	.string "Ups, die Tür ist aufgegangen!$"

