RocketHideout_B1F_Text_Grunt1Intro::
    .ifdef ENGLISH
    .string "Who are you?\n"
    .string "How did you get here?$"
    .endif
    .ifdef SPANISH
    .string "¿Quién eres tú?\n"
    .string "¿Y cómo has llegado aquí?$"
    .endif

RocketHideout_B1F_Text_Grunt1Defeat::
    .ifdef ENGLISH
    .string "Oww!\n"
    .string "Beaten!$"
    .endif
    .ifdef SPANISH
    .string "¡Auuu!\n"
    .string "¡He perdido!$"
    .endif

RocketHideout_B1F_Text_Grunt1PostBattle::
    .ifdef ENGLISH
    .string "Blast it… You're dissing TEAM\n"
    .string "ROCKET, aren't you?$"
    .endif
    .ifdef SPANISH
    .string "¿Vas a luchar contra el TEAM\n"
    .string "ROCKET?$"
    .endif

RocketHideout_B1F_Text_Grunt2Intro::
    .ifdef ENGLISH
    .string "You broke into TEAM ROCKET's\n"
    .string "operation? What nerve!$"
    .endif
    .ifdef SPANISH
    .string "¡Has destrozado nuestros planes!$"
    .endif

RocketHideout_B1F_Text_Grunt2Defeat::
    .ifdef ENGLISH
    .string "Boom!$"
    .endif
    .ifdef SPANISH
    .string "¡Chamuscado!$"
    .endif

RocketHideout_B1F_Text_Grunt2PostBattle::
    .ifdef ENGLISH
    .string "You're not going to get away with\n"
    .string "this, brat!$"
    .endif
    .ifdef SPANISH
    .string "¡No te vas a salir con la tuya,\n"
    .string "impresentable!$"
    .endif

RocketHideout_B1F_Text_Grunt3Intro::
    .ifdef ENGLISH
    .string "Intruder alert!$"
    .endif
    .ifdef SPANISH
    .string "¡Alerta! ¡Nos invaden!$"
    .endif

RocketHideout_B1F_Text_Grunt3Defeat::
    .ifdef ENGLISH
    .string "I can't do it!$"
    .endif
    .ifdef SPANISH
    .string "¡¡¡No lo he conseguido!!!$"
    .endif

RocketHideout_B1F_Text_Grunt3PostBattle::
    .ifdef ENGLISH
    .string "SILPH SCOPE? Humph!\n"
    .string "I don't know where it is.$"
    .endif
    .ifdef SPANISH
    .string "¿El SCOPE SILPH?\n"
    .string "¡No sé dónde está!$"
    .endif

RocketHideout_B1F_Text_Grunt4Intro::
    .ifdef ENGLISH
    .string "Why did you come here?$"
    .endif
    .ifdef SPANISH
    .string "¿Por qué has venido aquí?$"
    .endif

RocketHideout_B1F_Text_Grunt4Defeat::
    .ifdef ENGLISH
    .string "This won't do!$"
    .endif
    .ifdef SPANISH
    .string "¡Esto no funcionará!$"
    .endif

RocketHideout_B1F_Text_Grunt4PostBattle::
    .ifdef ENGLISH
    .string "Okay, I'll talk…\n"
    .string "Take the elevator to see my BOSS.$"
    .endif
    .ifdef SPANISH
    .string "¡Vale, hablaré! ¡Toma el ascensor\n"
    .string "para ver a mi JEFE!$"
    .endif

RocketHideout_B1F_Text_Grunt5Intro::
    .ifdef ENGLISH
    .string "Are you lost, you little mouse?$"
    .endif
    .ifdef SPANISH
    .string "¿Te has perdido? Pobre...$"
    .endif

RocketHideout_B1F_Text_Grunt5Defeat::
    .ifdef ENGLISH
    .string "Why…?$"
    .endif
    .ifdef SPANISH
    .string "¿Por qué...?$"
    .endif

RocketHideout_B1F_Text_Grunt5PostBattle::
    .ifdef ENGLISH
    .string "Uh-oh, that ruckus somehow opened\n"
    .string "the door!$"
    .endif
    .ifdef SPANISH
    .string "¡Con tanto lío se ha abierto\n"
    .string "la puerta!$"
    .endif

