SaffronCity_Mart_Text_MaxRepelMoreEffectiveThanSuper::
    .ifdef ENGLISH
    .string "MAX REPEL keeps weaker POKéMON\n"
    .string "from appearing.\p"
    .string "MAX REPEL stays effective longer\n"
    .string "than SUPER REPEL.$"
    .endif
    .ifdef SPANISH
    .string "¡MÁX. REPEL dura más que el\n"
    .string "SUPERREPEL; mantiene alejados\l"
    .string "más tiempo a los POKéMON débiles!$"
    .endif

SaffronCity_Mart_Text_ReviveIsCostly::
    .ifdef ENGLISH
    .string "REVIVE is costly, but it revives\n"
    .string "fainted POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡REVIVIR es caro, pero hace\n"
    .string "revivir a los POKéMON debilitados!$"
    .endif

