SixIsland_PokemonCenter_1F_Text_SomethingHiddenOnThisIsland::
    .ifdef ENGLISH
    .string "For ten years, I've searched for\n"
    .string "RUINS.\p"
    .string "No, make that twenty years.\p"
    .string "I get this feeling that there's\n"
    .string "something hidden on this island.$"
    .endif
    .ifdef SPANISH
    .string "Llevo diez años buscando\n"
    .string "las RUINAS.\p"
    .string "No, mucho más, ¡llevo veinte!\p"
    .string "Creo que en esta isla hay algo\n"
    .string "raro.$"
    .endif

SixIsland_PokemonCenter_1F_Text_SomeMonsEvolveByTradingWithHeldItem::
    .ifdef ENGLISH
    .string "You know of POKéMON that evolve\n"
    .string "only upon trading, yes?\p"
    .string "But did you know that there are\n"
    .string "still others?\p"
    .string "Some POKéMON evolve only when\n"
    .string "traded while holding specific items.$"
    .endif
    .ifdef SPANISH
    .string "Tú ya sabes que hay POKéMON que\n"
    .string "evolucionan durante el intercambio,\l"
    .string "¿no?\p"
    .string "¿Y sabes que algunos necesitan un\n"
    .string "objeto concreto para evolucionar\l"
    .string "durante el intercambio?$"
    .endif

SixIsland_PokemonCenter_1F_Text_RivalImpossibleToGetAllMonsAroundHere::
    .ifdef ENGLISH
    .string "{RIVAL}: Hey, {PLAYER}!\n"
    .string "How's your POKéDEX filling up?\p"
    .string "It looks like it's impossible to get\n"
    .string "all the POKéMON by hanging around\l"
    .string "just these parts.\p"
    .string "Maybe there are POKéMON we don't\n"
    .string "know about somewhere far away…\p"
    .string "… … …  … … …  … … …\p"
    .string "Well, if I can't do it, there's no\n"
    .string "way for you to get it done.\p"
    .string "I'm not going to get all desperate\n"
    .string "over this.\p"
    .string "I'll keep collecting POKéMON at my\n"
    .string "own pace while I train them.\p"
    .string "That's what I'll do.\n"
    .string "So there's no point staying here.\l"
    .string "I may as well leave for home.\p"
    .string "That's that, then!\n"
    .string "Smell ya later!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Eh, {PLAYER}!\n"
    .string "¿Qué tal llevas la POKéDEX?\p"
    .string "Parece imposible conseguir todos\n"
    .string "los POKéMON paseando sólo por\l"
    .string "esta zona, ¿eh?\p"
    .string "A lo mejor hay otros POKéMON\n"
    .string "lejos de aquí...\p"
    .string "... ... ... ... ... ... ... ... ...\p"
    .string "Desde luego, si yo no lo consigo,\n"
    .string "tampoco vas a conseguirlo tú.\p"
    .string "Bueno, tampoco voy a obsesionarme\n"
    .string "mucho con el tema.\p"
    .string "Seguiré coleccionando POKéMON\n"
    .string "a mi ritmo y los entrenaré.\p"
    .string "Eso es lo que voy a hacer.\n"
    .string "No merece la pena estar aquí,\l"
    .string "creo que me voy a casa.\p"
    .string "Pues eso.\n"
    .string "¡Nos vemos!$"
    .endif

