Route2_House_Text_FaintedMonsCanUseFieldMoves::
    .ifdef ENGLISH
    .string "A fainted POKéMON just has no\n"
    .string "energy left to battle.\p"
    .string "It can still use moves like CUT\n"
    .string "outside of battle.$"
    .endif
    .ifdef SPANISH
    .string "Un POKéMON debilitado no puede\n"
    .string "luchar.\p"
    .string "¡Pero puede usar movimientos\n"
    .string "como el de CORTAR!$"
    .endif

