RocketHideout_B4F_Text_GiovanniIntro::
    .ifdef ENGLISH
    .string "So! I must say, I am impressed you\n"
    .string "got here.\p"
    .string "TEAM ROCKET captures POKéMON from\n"
    .string "around the world.\p"
    .string "They're important tools for keeping\n"
    .string "our criminal enterprise going.\p"
    .string "I am the leader, GIOVANNI!\p"
    .string "For your insolence, you will feel a\n"
    .string "world of pain!$"
    .endif
    .ifdef SPANISH
    .string "¡Mmm! ¡Estoy muy impresionado\n"
    .string "de que hayas llegado hasta aquí!\p"
    .string "¡El TEAM ROCKET necesita los\n"
    .string "POKéMON para financiar sus\l"
    .string "malvados planes!\p"
    .string "¡Yo soy GIOVANNI, su líder!\p"
    .string "¡Y te las vas a tener que ver\n"
    .string "conmigo, metomentodo!$"
    .endif

RocketHideout_B4F_Text_GiovanniDefeat::
    .ifdef ENGLISH
    .string "WHAT!\n"
    .string "This can't be!$"
    .endif
    .ifdef SPANISH
    .string "¿QUÉ?\n"
    .string "¡Esto es imposible!$"
    .endif

RocketHideout_B4F_Text_GiovanniPostBattle::
    .ifdef ENGLISH
    .string "I see that you raise POKéMON with\n"
    .string "utmost care.\p"
    .string "A child like you would never\n"
    .string "understand what I hope to achieve.\p"
    .string "I shall step aside this time!\p"
    .string "I hope we meet again…$"
    .endif
    .ifdef SPANISH
    .string "Ya veo que has entrenado a tus\n"
    .string "POKéMON con mucho cuidado.\p"
    .string "¡Pero jamás entenderías\n"
    .string "cuáles son mis planes!\p"
    .string "¡En esta ocasión te dejaré pasar!\p"
    .string "Espero que nos volvamos a ver.$"
    .endif

RocketHideout_B4F_Text_Grunt2Intro::
    .ifdef ENGLISH
    .string "I know you!\n"
    .string "You ruined our plans at MT. MOON!$"
    .endif
    .ifdef SPANISH
    .string "¡Te conozco! ¡Tú arruinaste\n"
    .string "nuestros planes en MT. MOON!$"
    .endif

RocketHideout_B4F_Text_Grunt2Defeat::
    .ifdef ENGLISH
    .string "Burned again!$"
    .endif
    .ifdef SPANISH
    .string "¡Me han vuelto a machacar!$"
    .endif

RocketHideout_B4F_Text_Grunt2PostBattle::
    .ifdef ENGLISH
    .string "Do you have something against TEAM\n"
    .string "ROCKET?$"
    .endif
    .ifdef SPANISH
    .string "¿Tienes algo en contra del TEAM\n"
    .string "ROCKET?$"
    .endif

RocketHideout_B4F_Text_Grunt3Intro::
    .ifdef ENGLISH
    .string "How can you not see the beauty of\n"
    .string "our evil?$"
    .endif
    .ifdef SPANISH
    .string "¿Acaso no ves la belleza de\n"
    .string "nuestros actos malvados?$"
    .endif

RocketHideout_B4F_Text_Grunt3Defeat::
    .ifdef ENGLISH
    .string "Ayaya!$"
    .endif
    .ifdef SPANISH
    .string "¡Ayayay!$"
    .endif

RocketHideout_B4F_Text_Grunt3PostBattle::
    .ifdef ENGLISH
    .string "BOSS!\n"
    .string "I'm sorry I failed you!$"
    .endif
    .ifdef SPANISH
    .string "¡JEFE!\n"
    .string "¡Siento haberle fallado!$"
    .endif

RocketHideout_B4F_Text_Grunt1Intro::
    .ifdef ENGLISH
    .string "The elevator doesn't work?\n"
    .string "Who has the LIFT KEY?$"
    .endif
    .ifdef SPANISH
    .string "¿No funciona el ascensor? ¿Quién\n"
    .string "tiene la LLAVE del ASCENSOR?$"
    .endif

RocketHideout_B4F_Text_Grunt1Defeat::
    .ifdef ENGLISH
    .string "No!$"
    .endif
    .ifdef SPANISH
    .string "¡No!$"
    .endif

RocketHideout_B4F_Text_Grunt1PostBattle::
    .ifdef ENGLISH
    .string "Oh, no!\n"
    .string "I dropped the LIFT KEY!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh, no! ¡He perdido la LLAVE\n"
    .string "del ASCENSOR!$"
    .endif

