RocketHideout_B4F_Text_GiovanniIntro::
	.string "Hmm! Tu me surprends. T'es dans le\n"
	.string "genre coriace!\p"
	.string "Pour financer ses plans, la TEAM\n"
	.string "ROCKET a besoin de POKéMON!\p"
	.string "Pour ça, nous en capturons dans le\n"
	.string "monde entier.\p"
	.string "Et je suis le chef, moi…\n"
	.string "GIOVANNI!\p"
	.string "Je vais te punir pour ton\n"
	.string "insolence!$"

RocketHideout_B4F_Text_GiovanniDefeat::
	.string "QUOI?\n"
	.string "Damnation!$"

RocketHideout_B4F_Text_GiovanniPostBattle::
	.string "Tu élèves tes POKéMON avec\n"
	.string "le plus grand soin.\p"
	.string "Un gosse comme toi ne peut\n"
	.string "comprendre mes plans!\p"
	.string "Tu as gagné cette bataille, mais\n"
	.string "pas la guerre…\p"
	.string "On se retrouvera, et cette fois…$"

RocketHideout_B4F_Text_Grunt2Intro::
	.string "Je te reconnais!\n"
	.string "Tu as ruiné nos plans au\l"
	.string "MONT SELENITE!$"

RocketHideout_B4F_Text_Grunt2Defeat::
	.string "Enfer!\n"
	.string "Et encore enfer!$"

RocketHideout_B4F_Text_Grunt2PostBattle::
	.string "Je comprends pas, t'aimes pas la\n"
	.string "TEAM ROCKET?$"

RocketHideout_B4F_Text_Grunt3Intro::
	.string "Tu ne trouves pas que nos plans\n"
	.string "maléfiques sont super cool?$"

RocketHideout_B4F_Text_Grunt3Defeat::
	.string "Ayayargh!$"

RocketHideout_B4F_Text_Grunt3PostBattle::
	.string "CHEF! Pardon!\n"
	.string "J'ai échoué…$"

RocketHideout_B4F_Text_Grunt1Intro::
	.string "L'ascenseur ne marche pas?\n"
	.string "Il faut la CLE ASC.!$"

RocketHideout_B4F_Text_Grunt1Defeat::
	.string "Argh!$"

RocketHideout_B4F_Text_Grunt1PostBattle::
	.string "Mince! J'ai laissé tomber\n"
	.string "la CLE ASC.!$"

