SixIsland_RuinValley_Text_CantFigureOutHowToGetInside::
    .ifdef ENGLISH
    .string "I can't figure out how I'm supposed\n"
    .string "to get inside.$"
    .endif
    .ifdef SPANISH
    .string "No tengo ni idea de cómo puedo\n"
    .string "entrar.$"
    .endif

SixIsland_RuinValley_Text_IFoundThisPlace::
    .ifdef ENGLISH
    .string "Let me tell you, I found this\n"
    .string "place.\p"
    .string "Don't look so envious, will you?$"
    .endif
    .ifdef SPANISH
    .string "Para tu información, fui yo quien\n"
    .string "encontró este lugar.\p"
    .string "Tampoco es para que pongas\n"
    .string "esa cara de envidia...$"
    .endif

SixIsland_RuinValley_Text_CheckDoorMoreThoroughly::
    .ifdef ENGLISH
    .string "The door doesn't budge at all.\n"
    .string "Check it more thoroughly?$"
    .endif
    .ifdef SPANISH
    .string "La puerta no cede ni un milímetro.\n"
    .string "¿Quieres examinarla un poco?$"
    .endif

SixIsland_RuinValley_Text_LeftDoorAlone::
    .ifdef ENGLISH
    .string "{PLAYER} left the door alone.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} dejó tranquila la puerta.$"
    .endif

SixIsland_RuinValley_Text_SeveralDotsOnTheDoor::
    .ifdef ENGLISH
    .string "On closer inspection, there are\n"
    .string "several dots on the door…$"
    .endif
    .ifdef SPANISH
    .string "Tras mirarla con más detenimiento,\n"
    .string "vio que estaba punteada...$"
    .endif

SixIsland_RuinValley_Text_DoorIsOpen::
    .ifdef ENGLISH
    .string "The door is open.$"
    .endif
    .ifdef SPANISH
    .string "La puerta está abierta.$"
    .endif

SixIsland_RuinValley_Text_StanlyIntro::
    .ifdef ENGLISH
    .string "There appear to be many secrets\n"
    .string "still unsolved in this world.$"
    .endif
    .ifdef SPANISH
    .string "Creo que en este mundo quedan\n"
    .string "misterios por resolver.$"
    .endif

SixIsland_RuinValley_Text_StanlyDefeat::
    .ifdef ENGLISH
    .string "Hmm…$"
    .endif
    .ifdef SPANISH
    .string "Mmmm...$"
    .endif

SixIsland_RuinValley_Text_StanlyPostBattle::
    .ifdef ENGLISH
    .string "I suggest to you that you, too,\n"
    .string "give a thought to the secrets and\l"
    .string "mysteries of our world once a day.$"
    .endif
    .ifdef SPANISH
    .string "Creo que también deberías dedicar\n"
    .string "un tiempo a pensar en la cantidad\l"
    .string "de cosas que hay por averiguar.$"
    .endif

SixIsland_RuinValley_Text_FosterIntro::
    .ifdef ENGLISH
    .string "I'm curious, what compelled you to\n"
    .string "come here?$"
    .endif
    .ifdef SPANISH
    .string "Oye, ¿qué te trae hasta aquí?$"
    .endif

SixIsland_RuinValley_Text_FosterDefeat::
    .ifdef ENGLISH
    .string "It's been so long since I battled,\n"
    .string "my instincts are off.$"
    .endif
    .ifdef SPANISH
    .string "Llevo tanto sin luchar que no\n"
    .string "tengo reflejos...$"
    .endif

SixIsland_RuinValley_Text_FosterPostBattle::
    .ifdef ENGLISH
    .string "There are several ruins on the\n"
    .string "SEVII ISLANDS.\p"
    .string "The majority of them date back\n"
    .string "a long way.$"
    .endif
    .ifdef SPANISH
    .string "Hay varias ruinas en ARCHI7.\p"
    .string "La mayoría datan de tiempos\n"
    .string "inmemoriales.$"
    .endif

SixIsland_RuinValley_Text_LarryIntro::
    .ifdef ENGLISH
    .string "It's been said that there are\n"
    .string "mysterious stones on this island.\p"
    .string "I suspect it has something to do\n"
    .string "with the ruins here.$"
    .endif
    .ifdef SPANISH
    .string "Dicen que hay misteriosas piedras\n"
    .string "en esta isla.\p"
    .string "Supongo que tendrán algo que ver\n"
    .string "con las ruinas de aquí.$"
    .endif

SixIsland_RuinValley_Text_LarryDefeat::
    .ifdef ENGLISH
    .string "Oh, interesting.$"
    .endif
    .ifdef SPANISH
    .string "Eh... muy interesante.$"
    .endif

SixIsland_RuinValley_Text_LarryPostBattle::
    .ifdef ENGLISH
    .string "Those ruins over there…\p"
    .string "I haven't had any luck in finding\n"
    .string "how I can get inside.$"
    .endif
    .ifdef SPANISH
    .string "Las ruinas de ahí...\p"
    .string "Son rarísimas, yo no he conseguido\n"
    .string "entrar todavía.$"
    .endif

SixIsland_RuinValley_Text_DarylIntro::
    .ifdef ENGLISH
    .string "A battle with you, so high up!$"
    .endif
    .ifdef SPANISH
    .string "¿Luchar contigo?\n"
    .string "¡Ahora mismo!$"
    .endif

SixIsland_RuinValley_Text_DarylDefeat::
    .ifdef ENGLISH
    .string "Oh, the heartbreak of losing so\n"
    .string "easily to you!$"
    .endif
    .ifdef SPANISH
    .string "No soporto el sabor de la derrota\n"
    .string "ante ti...$"
    .endif

SixIsland_RuinValley_Text_DarylPostBattle::
    .ifdef ENGLISH
    .string "Experience the joy of climbing!$"
    .endif
    .ifdef SPANISH
    .string "Deberías hacer escalada.$"
    .endif

SixIsland_RuinValley_Text_HectorIntro::
    .ifdef ENGLISH
    .string "I'm pretty familiar with the land\n"
    .string "around these parts.$"
    .endif
    .ifdef SPANISH
    .string "Yo me conozco bien toda esta\n"
    .string "zona.$"
    .endif

SixIsland_RuinValley_Text_HectorDefeat::
    .ifdef ENGLISH
    .string "You don't need to be so pushy.\n"
    .string "I'll be happy to tell you.$"
    .endif
    .ifdef SPANISH
    .string "Tampoco es para ponerse así.\n"
    .string "Puedes preguntarme lo que quieras.$"
    .endif

SixIsland_RuinValley_Text_HectorPostBattle::
    .ifdef ENGLISH
    .string "The door to the ruins…\n"
    .string "It has these strange patterns\l"
    .string "engraved on the outside.\p"
    .string "I don't know what they mean,\n"
    .string "though.$"
    .endif
    .ifdef SPANISH
    .string "La entrada a las ruinas...\n"
    .string "Tiene unos dibujos extrañísimos\l"
    .string "grabados.\p"
    .string "Y no tengo ni idea de lo que\n"
    .string "significan.$"
    .endif
