SafariZone_North_Text_RestHouse::
    .ifdef ENGLISH
    .string "REST HOUSE$"
    .endif
    .ifdef SPANISH
    .string "CASA DE REPOSO$"
    .endif

SafariZone_North_Text_SecretHouseStillAhead::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "The SECRET HOUSE is still ahead.$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "¡La CASA SECRETA sigue estando\n"
    .string "justo delante!$"
    .endif

SafariZone_North_Text_Area2::
    .ifdef ENGLISH
    .string "AREA 2$"
    .endif
    .ifdef SPANISH
    .string "ZONA 2$"
    .endif

SafariZone_North_Text_ZigzagThroughTallGrass::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "POKéMON hide in tall grass.\p"
    .string "Zigzag through grassy areas to\n"
    .string "flush them out.$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "¡Los POKéMON se ocultan entre la\n"
    .string "alta hierba!\p"
    .string "Zigzaguea por zonas de hierba para\n"
    .string "que salgan.$"
    .endif

SafariZone_North_Text_WinFreeHMFindSecretHouse::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "Win a free HM for finding the\n"
    .string "SECRET HOUSE.$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "¡Encuentra la CASA SECRETA\n"
    .string "y ganarás una MO!$"
    .endif

