SafariZone_North_Text_RestHouse::
	.string "ABRI$"

SafariZone_North_Text_SecretHouseStillAhead::
	.string "ASTUCE\p"
	.string "La CABANE SECRETE est tout droit!$"

SafariZone_North_Text_Area2::
	.string "PARC 2$"

SafariZone_North_Text_ZigzagThroughTallGrass::
	.string "ASTUCE\p"
	.string "Les POKéMON se cachent dans les\n"
	.string "hautes herbes!\p"
	.string "Explorez ces zones pour les faire\n"
	.string "sortir.$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
	.string "ASTUCE\p"
	.string "Découvrez la CABANE SECRETE et\n"
	.string "gagnez une CS!$"

