VictoryRoad_2F_Text_DawsonIntro::
    .string "¡Si puedes pasar por aquí, podrás\n"
    .string "enfrentarte al ALTO MANDO!$"

VictoryRoad_2F_Text_DawsonDefeat::
    .string "¡No!\n"
    .string "¡Increíble!$"

VictoryRoad_2F_Text_DawsonPostBattle::
    .string "¡Puedo vencerte en cuanto a\n"
    .string "conocimientos sobre los POKéMON!$"

VictoryRoad_2F_Text_DaisukeIntro::
    .string "¡La CALLE VICTORIA es la prueba\n"
    .string "final de todo ENTRENADOR!$"

VictoryRoad_2F_Text_DaisukeDefeat::
    .string "¡Ayyyy!$"

VictoryRoad_2F_Text_DaisukePostBattle::
    .string "¡Prueba a mover las rocas\n"
    .string "si tienes el paso cortado!$"

VictoryRoad_2F_Text_NelsonIntro::
    .string "¡Ah!\n"
    .string "¿Quieres desafiar al ALTO MANDO?$"

VictoryRoad_2F_Text_NelsonDefeat::
    .string "¡Me has ganado!$"

VictoryRoad_2F_Text_NelsonPostBattle::
    .string "¡{RIVAL} también vino por aquí!$"

VictoryRoad_2F_Text_VincentIntro::
    .string "¡Adelante!\n"
    .string "¡Te daré una paliza!$"

VictoryRoad_2F_Text_VincentDefeat::
    .string "¡Me has machacado!$"

VictoryRoad_2F_Text_VincentPostBattle::
    .string "¡Ahora puedes recorrer la CALLE\n"
    .string "VICTORIA!$"

VictoryRoad_2F_Text_GregoryIntro::
    .string "¿Es muy dura la CALLE VICTORIA?$"

VictoryRoad_2F_Text_GregoryDefeat::
    .string "¡Bien hecho!$"

VictoryRoad_2F_Text_GregoryPostBattle::
    .string "¡Muchos de los ENTRENADORES\n"
    .string "se rinden aquí!$"

@ Unused, old text for Moltres
VictoryRoad_2F_Text_Gyaoo::
    .string "ギヤーオ！$"
