VictoryRoad_2F_Text_DawsonIntro::
	.string "Wenn du an mir vorbeikommst, kannst\n"
	.string "du zu den TOP VIER gehen!$"

VictoryRoad_2F_Text_DawsonDefeat::
	.string "Nein!\n"
	.string "Unglaublich!$"

VictoryRoad_2F_Text_DawsonPostBattle::
	.string "Und wenn schon... dafür übersteigt\n"
	.string "mein Wissen über POKéMON deines bei\l"
	.string "weitem!$"

VictoryRoad_2F_Text_DaisukeIntro::
	.string "Die SIEGESSTRASSE stellt eine Art\n"
	.string "Abschlussprüfung für TRAINER dar!$"

VictoryRoad_2F_Text_DaisukeDefeat::
	.string "Ahh!$"

VictoryRoad_2F_Text_DaisukePostBattle::
	.string "Wenn du nicht vorankommst,\n"
	.string "versuche, die Felsen zu\l"
	.string "verschieben!$"

VictoryRoad_2F_Text_NelsonIntro::
	.string "Du möchtest also die TOP VIER\n"
	.string "herausfordern?$"

VictoryRoad_2F_Text_NelsonDefeat::
	.string "Voll erwischt!$"

VictoryRoad_2F_Text_NelsonPostBattle::
	.string "Auch {RIVAL} kam hier vorbei!$"

VictoryRoad_2F_Text_VincentIntro::
	.string "Komm nur her!\n"
	.string "Ich werde dich besiegen!$"

VictoryRoad_2F_Text_VincentDefeat::
	.string "Auweia!\n"
	.string "Ich bin besiegt!$"

VictoryRoad_2F_Text_VincentPostBattle::
	.string "Du beschreitest die SIEGESSTRASSE\n"
	.string "nicht ohne Grund!$"

VictoryRoad_2F_Text_GregoryIntro::
	.string "Die SIEGESSTRASSE ist sehr schwer\n"
	.string "zu meistern!$"

VictoryRoad_2F_Text_GregoryDefeat::
	.string "Gut gemacht!$"

VictoryRoad_2F_Text_GregoryPostBattle::
	.string "Schon viele TRAINER haben hier\n"
	.string "aufgegeben!$"

@ Unused, old text for Moltres
VictoryRoad_2F_Text_Gyaoo::
	.string "ギヤーオ！$"

