VictoryRoad_2F_Text_DawsonIntro::
    .ifdef ENGLISH
    .string "If you can get through here,\n"
    .string "you can go meet the ELITE FOUR.$"
    .endif
    .ifdef SPANISH
    .string "¡Si puedes pasar por aquí, podrás\n"
    .string "enfrentarte al ALTO MANDO!$"
    .endif

VictoryRoad_2F_Text_DawsonDefeat::
    .ifdef ENGLISH
    .string "No!\n"
    .string "Unbelievable!$"
    .endif
    .ifdef SPANISH
    .string "¡No!\n"
    .string "¡Increíble!$"
    .endif

VictoryRoad_2F_Text_DawsonPostBattle::
    .ifdef ENGLISH
    .string "I can beat you when it comes to\n"
    .string "knowledge about POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Puedo vencerte en cuanto a\n"
    .string "conocimientos sobre los POKéMON!$"
    .endif

VictoryRoad_2F_Text_DaisukeIntro::
    .ifdef ENGLISH
    .string "This here is VICTORY ROAD.\n"
    .string "It's the final test for TRAINERS!$"
    .endif
    .ifdef SPANISH
    .string "¡La CALLE VICTORIA es la prueba\n"
    .string "final de todo ENTRENADOR!$"
    .endif

VictoryRoad_2F_Text_DaisukeDefeat::
    .ifdef ENGLISH
    .string "Atcho!$"
    .endif
    .ifdef SPANISH
    .string "¡Ayyyy!$"
    .endif

VictoryRoad_2F_Text_DaisukePostBattle::
    .ifdef ENGLISH
    .string "If you get stuck, try moving some\n"
    .string "boulders around.$"
    .endif
    .ifdef SPANISH
    .string "¡Prueba a mover las rocas\n"
    .string "si tienes el paso cortado!$"
    .endif

VictoryRoad_2F_Text_NelsonIntro::
    .ifdef ENGLISH
    .string "Ah, so you wish to challenge the\n"
    .string "ELITE FOUR?$"
    .endif
    .ifdef SPANISH
    .string "¡Ah!\n"
    .string "¿Quieres desafiar al ALTO MANDO?$"
    .endif

VictoryRoad_2F_Text_NelsonDefeat::
    .ifdef ENGLISH
    .string "You got me!$"
    .endif
    .ifdef SPANISH
    .string "¡Me has ganado!$"
    .endif

VictoryRoad_2F_Text_NelsonPostBattle::
    .ifdef ENGLISH
    .string "{RIVAL} also came through here.$"
    .endif
    .ifdef SPANISH
    .string "¡{RIVAL} también vino por aquí!$"
    .endif

VictoryRoad_2F_Text_VincentIntro::
    .ifdef ENGLISH
    .string "Come on!\n"
    .string "I'll whip you!$"
    .endif
    .ifdef SPANISH
    .string "¡Adelante!\n"
    .string "¡Te daré una paliza!$"
    .endif

VictoryRoad_2F_Text_VincentDefeat::
    .ifdef ENGLISH
    .string "I got whipped!$"
    .endif
    .ifdef SPANISH
    .string "¡Me has machacado!$"
    .endif

VictoryRoad_2F_Text_VincentPostBattle::
    .ifdef ENGLISH
    .string "You earned the right to be on\n"
    .string "VICTORY ROAD…$"
    .endif
    .ifdef SPANISH
    .string "¡Ahora puedes recorrer la CALLE\n"
    .string "VICTORIA!$"
    .endif

VictoryRoad_2F_Text_GregoryIntro::
    .ifdef ENGLISH
    .string "Is VICTORY ROAD too tough?$"
    .endif
    .ifdef SPANISH
    .string "¿Es muy dura la CALLE VICTORIA?$"
    .endif

VictoryRoad_2F_Text_GregoryDefeat::
    .ifdef ENGLISH
    .string "Well done!$"
    .endif
    .ifdef SPANISH
    .string "¡Bien hecho!$"
    .endif

VictoryRoad_2F_Text_GregoryPostBattle::
    .ifdef ENGLISH
    .string "Many TRAINERS give up their\n"
    .string "challenge here and go home.$"
    .endif
    .ifdef SPANISH
    .string "¡Muchos de los ENTRENADORES\n"
    .string "se rinden aquí!$"
    .endif

@ Unused, old text for Moltres
VictoryRoad_2F_Text_Gyaoo::
    .string "ギヤーオ！$"

