SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
    .ifdef ENGLISH
    .string "The SAFARI ZONE's huge, wouldn't\n"
    .string "you say?\p"
    .string "FUCHSIA's GYM LEADER, KOGA, \n"
    .string "patrols the grounds every so often.\p"
    .string "Thanks to him, we can play here\n"
    .string "knowing that we're safe.$"
    .endif
    .ifdef SPANISH
    .string "La ZONA del SAFARI es gigante,\n"
    .string "¿no te parece?\p"
    .string "El LÍDER del GIMNASIO de FUCSIA,\n"
    .string "KOGA, viene con mucha frecuencia\l"
    .string "por esta zona.\p"
    .string "Gracias a él, podemos jugar aquí\n"
    .string "sin miedo.$"
    .endif

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
    .ifdef ENGLISH
    .string "Tossing ROCKS at POKéMON might\n"
    .string "make them run, but they'll be\l"
    .string "easier to catch.$"
    .endif
    .ifdef SPANISH
    .string "Tirar PIEDRAS a los POKéMON\n"
    .string "podría hacerles huir, pero hará\l"
    .string "que sean más fáciles de atrapar.$"
    .endif

SafariZone_West_Text_BaitMakesMonStickAround::
    .ifdef ENGLISH
    .string "Using BAIT will make POKéMON more\n"
    .string "likely to stick around if they get\l"
    .string "busy eating.$"
    .endif
    .ifdef SPANISH
    .string "Utilizar CEBO te permitirá atrapar\n"
    .string "más fácilmente a los POKéMON.$"
    .endif

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
    .ifdef ENGLISH
    .string "I hiked a lot, but I didn't see any\n"
    .string "POKéMON I wanted.$"
    .endif
    .ifdef SPANISH
    .string "Caminé mucho, pero no he visto\n"
    .string "a los POKéMON que quería.$"
    .endif

