Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "Mal schauen...\n"
	.string "Oh! Du hast erst {STR_VAR_3} verschiedene\l"
	.string "POKéMON gefangen!\p"
	.string "Du benötigst {STR_VAR_1}, um das Geschenk\n"
	.string "zu erhalten.$"

Aide_Text_GetEnoughMonsComeBackForItem::
	.string "Ich habe eine gute Idee.\p"
	.string "Komm wieder, wenn du {STR_VAR_1} POKéMON\n"
	.string "besitzt. Ich hebe dir dein Geschenk\l"
	.string "auf.$"

Aide_Text_DontHaveAnyRoomForItem::
	.string "Oh! Du hast momentan keinen Platz\n"
	.string "für den {STR_VAR_2}.$"
