Braille_Text_Up::
	.braille "HINAUF$"

Braille_Text_Down::
	.braille "HINUNTER$"

Braille_Text_Right::
	.braille "RECHTS$"

Braille_Text_Left::
	.braille "LINKS$"

Braille_Text_Cut::
	.braille "ZERSCHNEIDER$"

Braille_Text_ABC::
	.braille "ABC$"

Braille_Text_GHI::
	.braille "GHI$"

Braille_Text_MNO::
	.braille "MNO$"

Braille_Text_TUV::
	.braille "TUV$"

Braille_Text_DEF::
	.braille "DEF$"

Braille_Text_JKL::
	.braille "JKL$"

Braille_Text_PQRS::
	.braille "PQRS$"

Braille_Text_WXYZ::
	.braille "WXYZ$"

Braille_Text_Period::
	.braille "=*$"

Braille_Text_Comma::
	.braille "=,$"

Braille_Text_Everything::
	.braille "ALLES$"

Braille_Text_HasMeaning1::
	.braille "MACHT SINN$"

Braille_Text_Existence::
	.braille "EXISTENZ$"

Braille_Text_HasMeaning2::
	.braille "MACHT SINN$"

Braille_Text_BeingAlive::
	.braille "LEBENDIG$"

Braille_Text_HasMeaning3::
	.braille "MACHT SINN$"

Braille_Text_HaveDreams::
	.braille "TR@UMT$"

Braille_Text_UsePower::
	.braille "KRAFTEINSATZ$"

Braille_Text_LetTheTwo::
	.braille "LASS ZWEI$"

Braille_Text_Glittering::
	.braille "SCHIMMERND$"

Braille_Text_Stones::
	.braille "STEINE$"

Braille_Text_OneInRed::
	.braille "EINS IN ROT$"

Braille_Text_OneInBlue::
	.braille "EINS IN BLAU$"

Braille_Text_ConnectThe::
	.braille "VERBINDE$"

Braille_Text_Past::
	.braille "GESCHICHTE$"

Braille_Text_TwoFriends::
	.braille "ZWEI FREUNDE$"

Braille_Text_Sharing::
	.braille "TEILEN$"

Braille_Text_PowerOpen::
	.braille "KRAFT DA$"

Braille_Text_AWindowTo::
	.braille "EIN FENSTER$"

Braille_Text_ANewWorld::
	.braille "NEUE WELT$"

Braille_Text_ThatGlows::
	.braille "DIE GL^HT$"

Braille_Text_TheNext::
	.braille "ALS N@CHSTES$"

Braille_Text_WorldWaits::
	.braille "WELT WARTET$"

Braille_Text_ForYou::
	.braille "AUF DICH$"
