@ Unused
Text_WelcomeTradeCenter::
	.string "Willkommen im POKéMON KABEL-CLUB-\n"
	.string "HANDELSCENTER.$"

@ Unused
Text_WelcomeColosseum::
	.string "Willkommen im POKéMON KABEL-CLUB-\n"
	.string "KOLOSSEUM.$"

@ Unused
Text_WelcomeTimeCapsule::
	.string "Willkommen in der POKéMON KABEL-\n"
	.string "CLUB-ZEITKAPSEL.$"

Text_PleaseComeAgain::
	.string "Bitte komm bald wieder!$"

@ Unused
Text_HavingDiscountSaleToday::
	.string "Willkommen!\p"
	.string "Wir bieten heute Sonderangebote\n"
	.string "an!$"

@ Unused
Text_PlayerWhatCanIDoForYou::
	.string "{PLAYER}{KUN}, willkommen!\p"
	.string "Wie kann ich dir behilflich sein?$"
