Help_Text_WhatShouldIDo::
	.string "Was soll ich in dieser Situation tun?$"

Help_Text_HowDoIDoThis::
	.string "Wie stelle ich das an?$"

Help_Text_WhatDoesThisTermMean::
	.string "Was bedeutet dieser Begriff?$"

Help_Text_AboutThisGame::
	.string "Über dieses Spiel$"

Help_Text_TypeMatchupList::
	.string "Elementklassen-Liste$"

Help_Text_Exit::
	.string "BEENDEN$"

Help_Text_Cancel::
	.string "ZURÜCK$"

Help_Text_TryDoingItOnYourOwn::
	.string "じぶんの ちからで やってみよう！$"

Help_Text_DescWhatShouldIDo::
	.string "Hier erhältst du Tipps, um\n"
	.string "knifflige Situationen zu meistern.$"

Help_Text_DescHowDoIDoThis::
	.string "Hier erhältst du detaillierte Hin-\n"
	.string "weise zu etlichen Möglichkeiten.$"

Help_Text_DescWhatDoesThisTermMean::
	.string "Begriffe, die im Spiel auftauchen,\n"
	.string "werden hier erklärt.$"

Help_Text_DescAboutThisGame::
	.string "Du erhältst nähere Informationen\n"
	.string "über dieses Spiel.$"

Help_Text_DescTypeMatchupList::
	.string "Verhältnis der Elementklassen und\n"
	.string "die Attacken sind hier aufgelistet.$"

Help_Text_DescExit::
	.string "Beendet das HILFE-Menü.$"

Help_Text_Greetings::
	.string "Servus! Ich bin das HILFE-Menü!\n"
	.string "Rufe mich auf, wann und wo\l"
	.string "immer du möchtest. Drücke dazu\l"
	.string "einfach die L- bzw. R-Taste.\l"
	.string "Meine Hilfe richtet sich nach der\l"
	.string "Situation, also solltest du oft\l"
	.string "nachsehen.$"

Help_Text_PlayingForFirstTime::
	.string "Ich spiele zum ersten Mal! Hilfe!$"

Help_Text_WhatShouldIBeDoing::
	.string "Was soll ich tun?$"

Help_Text_CantGetOutOfRoom::
	.string "Ich kann ein Zimmer nicht verlassen?$"

Help_Text_CantFindPersonIWant::
	.string "Ich finde nicht die richtige Person?$"

Help_Text_TalkedToEveryoneNowWhat::
	.string "Ich sprach mit allen? Was nun?$"

Help_Text_SomeoneBlockingMyWay::
	.string "Jemand versperrt mir den Weg!$"

Help_Text_ICantGoOn::
	.string "Ich kann nicht weitermachen!$"

Help_Text_OutOfThingsToDo::
	.string "Ich weiß nicht, was ich tun soll?$"

Help_Text_WhatHappenedToItemIGot::
	.string "Was ist mit dem erhaltenen Item?$"

Help_Text_WhatAreMyAdventureBasics::
	.string "Worin besteht mein Abenteuer?$"

Help_Text_HowAreRoadsForestsDifferent::
	.string "Unterscheiden sich Straß. u. Wälder?$"

Help_Text_HowAreCavesDifferent::
	.string "Worin unterscheiden sich Höhlen?$"

Help_Text_HowDoIProgress::
	.string "Wie komme ich voran?$"

Help_Text_WhenCanIUseItem::
	.string "Wann kann ich Items einsetzen?$"

Help_Text_WhatsABattle::
	.string "Was ist ein Kampf?$"

Help_Text_HowDoIPrepareForBattle::
	.string "Vorbereitungen auf einen Kampf?$"

Help_Text_WhatIsAMonsVitality::
	.string "Was ist die “Vitalität” eines PKMN?$"

Help_Text_MyMonsAreHurt::
	.string "Meine POKéMON sind verletzt!$"

Help_Text_WhatIsStatusProblem::
	.string "Was ist ein Statusproblem?$"

Help_Text_WhatHappensIfAllMyMonsFaint::
	.string "Was, wenn alle PKMN besiegt sind?$"

Help_Text_CantCatchMons::
	.string "Ich kann kein POKéMON fangen!$"

Help_Text_RanOutOfPotions::
	.string "Ich habe keine TRÄNKE mehr!$"

Help_Text_CanIBuyPokeBalls::
	.string "Kann ich POKéBÄLLE kaufen?$"

Help_Text_WhatsATrainer::
	.string "Was ist ein TRAINER?$"

Help_Text_HowDoIWinAgainstTrainer::
	.string "Wie gewinne ich geg. einen TRAINER?$"

Help_Text_WhereDoMonsAppear::
	.string "Wo tauchen POKéMON auf?$"

Help_Text_WhatAreMoves::
	.string "Was sind POKéMON-Attacken?$"

Help_Text_WhatAreHiddenMoves::
	.string "Was sind VERSTECKTE Attacken?$"

Help_Text_WhatMovesShouldIUse::
	.string "Welche Attacken soll ich einsetzen?$"

Help_Text_WantToAddMoreMoves::
	.string "Ich möchte mehr Attacken!$"

Help_Text_WantToMakeMonStronger::
	.string "Wie wird mein POKéMON stärker?$"

Help_Text_FoeMonsTooStrong::
	.string "Die gegnerischen PKMN sind zu stark!$"

Help_Text_WhatDoIDoInCave::
	.string "Was mache ich in einer Höhle?$"

Help_Text_NothingIWantToKnow::
	.string "Es gibt nichts, was ich wissen will!$"

Help_Text_WhatsPokemonCenter::
	.string "Was ist ein POKéMON-CENTER?$"

Help_Text_WhatsPokemonMart::
	.string "Was ist ein POKéMON-SUPERMARKT?$"

Help_Text_WantToEndGame::
	.string "Ich möchte das Spiel beenden!$"

Help_Text_WhatsAMon::
	.string "Was ist ein POKéMON?$"

Help_Text_WhatIsThatPersonLike::
	.string "Wie ist diese Person?$"

Help_Text_WhatDoesHiddenMoveDo::
	.string "Wofür ist eine VERSTECKTE Att. gut?$"

Help_Text_WhatDoIDoInSafari::
	.string "Was mache ich in der SAFARI-ZONE?$"

Help_Text_WhatAreSafariRules::
	.string "Die Regeln in der SAFARI-ZONE?$"

Help_Text_WantToEndSafari::
	.string "Ich will die SAFARI-ZONE verlassen?$"

Help_Text_WhatIsAGym::
	.string "Was ist eine ARENA?$"

Help_Text_AnswerPlayingForFirstTime::
	.string "Du bist der Protagonist, der die\n"
	.string "Welt der POKéMON erforscht.\l"
	.string "Indem du mit den Menschen\l"
	.string "sprichst und Rätsel löst, öffnen\l"
	.string "sich neue Wege. Erreiche dein\l"
	.string "Ziel zusammen mit deinen\l"
	.string "wunderbaren POKéMON.$"

Help_Text_AnswerWhatShouldIBeDoing::
	.string "Drücke den A-Knopf, wenn du Leuten\n"
	.string "begegnest. So kannst du mit ihnen\l"
	.string "sprechen und sie interagieren mit dir.\l"
	.string "Auf diese Weise kannst du auch Items\l"
	.string "und Objekte untersuchen. Sprich mit\l"
	.string "den Leuten und untersuche alles, um\l"
	.string "Informationen zu erhalten.$"

Help_Text_AnswerCantGetOutOfRoom::
	.string "Vor der Treppe und dem Ausgang\n"
	.string "eines Gebäudes ist ein roter\l"
	.string "Abstreifer. Bewege die Spielfigur\l"
	.string "darauf und drücke {PLUS} in Richtung\l"
	.string "der Treppe bzw. des Ausgangs,\l"
	.string "um fortzufahren.$"

Help_Text_AnswerCantFindPersonIWant::
	.string "Darüber solltest du dir nicht zu\n"
	.string "viele Sorgen machen. Sprich mit\l"
	.string "den Leuten, lies Schilder,\l"
	.string "untersuche alles und so weiter…\l"
	.string "Manchmal musst du nur in eine neue\l"
	.string "Stadt oder an einen neuen Ort.$"

Help_Text_AnswerTalkedToEveryoneNowWhat::
	.string "Begib dich auf eine neue ROUTE,\n"
	.string "in eine Stadt oder einen neuen Ort.$"

Help_Text_AnswerSomeoneBlockingMyWay::
	.string "Die Ursache könnte in einer Stadt\n"
	.string "oder in einem Gebäude sein. Sprich\l"
	.string "erneut mit den Leuten in diesem\l"
	.string "Gebiet. Falls sie ein Problem haben,\l"
	.string "könntest du ihnen helfen. Sprich\l"
	.string "anschließend mit der Person, die\l"
	.string "dir den Weg versperrt.$"

Help_Text_AnswerICantGoOn::
	.string "Sprich mit den Leuten, indem du auf\n"
	.string "sie zugehst und den A-Knopf drückst.\l"
	.string "Untersuche z.B. merkwürdige Bäume\l"
	.string "oder Steine, indem du den A-Knopf\l"
	.string "drückst. Begib dich an Stellen, die\l"
	.string "unpassierbar erscheinen und drücke\l"
	.string "dort den A-Knopf.$"

Help_Text_AnswerOutOfThingsToDo::
	.string "Begib dich an Orte, die du noch\n"
	.string "nicht besucht hast. Untersuche\l"
	.string "alles, das irgendwie verdächtig\l"
	.string "erscheint, durch Drücken des\l"
	.string "A-Knopfs.$"

Help_Text_AnswerWhatHappenedToItemIGot::
	.string "Jedes Item, das du erhältst, kommt\n"
	.string "in deinen BEUTEL. Das Item wird\l"
	.string "automatisch sortiert und in der\l"
	.string "jeweiligen Tasche abgelegt.\l"
	.string "Um Näheres über den BEUTEL zu\l"
	.string "erfahren, sieh im HILFE-Menü unter\l"
	.string "“Wie stelle ich das an?” nach.$"

Help_Text_AnswerWhatAreMyAdventureBasics::
	.string "PKMN, die sich im Kampf verletzt\n"
	.string "haben, können in einem PKMN-CENTER\l"
	.string "geheilt werden. Gewöhne es dir an,\l"
	.string "dein Spiel regelmäßig zu sichern.\l"
	.string "Stocke deinen Vorrat an heilenden\l"
	.string "Items in PKMN-SUPERMÄRKTEN\l"
	.string "auf, ehe du auf Reisen gehst.$"

Help_Text_AnswerHowAreRoadsForestsDifferent::
	.string "Straßen und Wälder sind prinzipiell\n"
	.string "gleich, aber manche Wälder sind\l"
	.string "Irrgärten. Aus jedem Wald gibt es\l"
	.string "einen Ausgang, also gib nicht auf,\l"
	.string "wenn du dich verlaufen hast.$"

Help_Text_AnswerHowAreCavesDifferent::
	.string "Höhlen sind dunkel und gefährlich!\n"
	.string "Wilde POKéMON können überall\l"
	.string "auftauchen. Im Notfall kannst du in\l"
	.string "ein POKéMON-CENTER oder\l"
	.string "Items einsetzen. In neuen Städten\l"
	.string "gibt es nicht nur neue Höhlen zu\l"
	.string "erforschen, also gib nicht auf.$"

Help_Text_AnswerHowDoIProgress::
	.string "Ziel des Spiels ist es, deine PKMN zu\n"
	.string "trainieren und voranzuschreiten. Du\l"
	.string "musst nach Informationen suchen und\l"
	.string "Rätsel lösen. Z.B. wie du um ein Hin-\l"
	.string "dernis kommst oder wie es dir gelingt,\l"
	.string "die Person, die dir im Weg steht,\l"
	.string "zu überreden, Platz zu machen.$"

Help_Text_AnswerWhenCanIUseItem::
	.string "Es gibt verschiedene Items. Manche\n"
	.string "können nur beim Erforschen der\l"
	.string "Gegend, manche nur im Kampf und\l"
	.string "manche jederzeit eingesetzt werden.\l"
	.string "Versuche ein Item einzusetzen. Ist\l"
	.string "dies nicht möglich, wird dir das\l"
	.string "angezeigt.$"

Help_Text_AnswerWhatsABattle::
	.string "Im Kampf versuchen die PKMN, die\n"
	.string "Lebensenergie, genannt KP, des ande-\l"
	.string "ren zu reduzieren. Betragen die KP\l"
	.string "eines PKMN null, ist es besiegt und\l"
	.string "das andere PKMN gewinnt. Durch den\l"
	.string "Sieg erhält das PKMN E.-Punkte, \l"
	.string "durch die es stärker wird.$"

Help_Text_AnswerHowDoIPrepareForBattle::
	.string "Zunächst solltest du alle POKéMON\n"
	.string "in deinem Team (die POKéMON, die\l"
	.string "du bei dir hast) in einem POKéMON-\l"
	.string "CENTER heilen. Du solltest auch\l"
	.string "heilende Items in einem PKMN-\l"
	.string "SUPERMARKT für Notfälle kaufen.$"

Help_Text_AnswerWhatIsAMonsVitality::
	.string "Die Lebensenergie eines PKMN wird in\n"
	.string "KP angegeben. Wird ein PKMN in einem\l"
	.string "Kampf verletzt, werden KP abgezogen.\l"
	.string "Erreicht der KP-Wert null, ist das\l"
	.string "PKMN besiegt. Heile verletzte oder\l"
	.string "besiegte PKMN in einem\l"
	.string "PKMN-CENTER oder mit Items.$"

Help_Text_AnswerMyMonsAreHurt::
	.string "Ein POKéMON-CENTER ist wie eine\n"
	.string "Herberge für POKéMON. Mit einer\l"
	.string "speziellen Maschine werden die\l"
	.string "POKéMON vollständig geheilt und\l"
	.string "alle Statusprobleme beseitigt.\l"
	.string "Diese Dienstleistung ist kostenlos,\l"
	.string "mach also häufig von ihr Gebrauch.$"

Help_Text_AnswerWhatIsStatusProblem::
	.string "Ein Statusproblem ist ein Gebrechen,\n"
	.string "das ein PKMN aufgrund einer er-\l"
	.string "littenen Attacke hat. Dazu zählen\l"
	.string "Verbrennungen, Paralyse, Vergiftung.,\l"
	.string "Schlaf und Einfrieren. Ein Besuch im\l"
	.string "PKMN-CENTER oder ein passendes\l"
	.string "Item können diese Probleme heilen.$"

Help_Text_AnswerWhatHappensIfAllMyMonsFaint::
	.string "Werden alle PKMN in deinem Team\n"
	.string "besiegt, verlierst du Geld und du\l"
	.string "wirst entweder nach Hause oder in ein\l"
	.string "PKMN-CENTER gebracht. Um dem\l"
	.string "vorzubeugen, solltest du häufig\l"
	.string "PKMN-CENTER aufsuchen. \l"
	.string "Gewöhne dir an, häufig zu sichern.$"

Help_Text_AnswerCantCatchMons::
	.string "Bricht ein wildes PKMN aus einem\n"
	.string "POKéBALL aus, ist es zu stark.\l"
	.string "Reduziere seine KP noch weiter\l"
	.string "und schwäche es durch Paralyse\l"
	.string "oder Schlaf. Bewegt sich der\l"
	.string "POKéBALL eine Zeit lang,\l"
	.string "ist es fast gefangen.$"

Help_Text_AnswerRanOutOfPotions::
	.string "Es gibt Läden, die PKMN-SUPERMÄRKTE\n"
	.string "genannt werden und Items verkaufen.\l"
	.string "Diese PKMN-SUPERMÄRKTE gibt\l"
	.string "es nicht auf Straßen, in Wäldern oder\l"
	.string "Höhlen. Stocke deinen Vorrat auf,\l"
	.string "solange du in der Stadt bist.$"

Help_Text_AnswerCanIBuyPokeBalls::
	.string "Du kannst in jedem PKMN-SUPER-\n"
	.string "MARKT der Stadt POKéBÄLLE\l"
	.string "kaufen. Diese PKMN-SUPERMÄRKTE\l"
	.string "gibt es nicht auf Straßen, in Wäldern\l"
	.string "oder Höhlen. Stocke deinen Vorrat\l"
	.string "auf, solange du in der Stadt bist.$"

Help_Text_AnswerWhatsATrainer::
	.string "Ein TRAINER trainiert POKéMON,\n"
	.string "indem er mit ihnen kämpft.\l"
	.string "TRAINER werden dich überall\l"
	.string "herausfordern. Auf einer Straße, im\l"
	.string "Wald, in einer Höhle, überall.\l"
	.string "Schaust du ihnen in die Augen,\l"
	.string "musst du gegen sie antreten.$"

Help_Text_AnswerHowDoIWinAgainstTrainer::
	.string "Um einen TRAINER zu besiegen, soll-\n"
	.string "test du PKMN einsetzen, die den Geg-\l"
	.string "nern aufgrund ihrer Elementklasse\l"
	.string "überlegen sind. Du kannst auch starke\l"
	.string "PKMN einsetzen, die aufgrund ihrer\l"
	.string "Kraft gewinnen. Auch eine zahlen-\l"
	.string "mäßige Überlegenheit führt zum Sieg.$"

Help_Text_AnswerWhereDoMonsAppear::
	.string "Wilde POKéMON tauchen in hohem\n"
	.string "Gras, auf Straßen und in Wäldern auf.\l"
	.string "Auch in dunklen Höhlen können sie\l"
	.string "überall auftauchen. In Städten gibt\l"
	.string "es keine wilden POKéMON oder\l"
	.string "TRAINER, dort bist du sicher.$"

Help_Text_AnswerWhatAreMoves::
	.string "PKMN können bis zu vier Attacken er-\n"
	.string "lernen. Es gibt eine schier unendliche\l"
	.string "Anzahl an Attacken, darunter einige\l"
	.string "mit Spezialeffekten. Welche Attacken\l"
	.string "erlernt werden können, hängt vom\l"
	.string "PKMN ab. Einige Attacken können\l"
	.string "durch Maschinen gelernt werden.$"

Help_Text_AnswerWhatAreHiddenMoves::
	.string "VERSTECKTE Attacken sind wichtig. Um\n"
	.string "solch eine Attacke außerhalb eines\l"
	.string "Kampfes anzuwenden, musst du das\l"
	.string "“POKéMON-MENÜ” öffnen und das PKMN\l"
	.string "mit der Attacke muss sie benutzen.\l"
	.string "Ein bes. PKMN kann eine VM-Att. auch\l"
	.string "außerhalb des Kampfes einsetzen.$"

Help_Text_AnswerWhatMovesShouldIUse::
	.string "Wähle “KÄMPFEN” aus, um die\n"
	.string "ATTACKEN anzeigen zu lassen. Berück-\l"
	.string "sichtige dabei die Elementklasse.\l"
	.string "Öffne das Menü “POKéMON”, wähle ein\l"
	.string "PKMN und anschließend “BERICHT” aus\l"
	.string "sowie “ATTACKEN”, um die Wirkung\l"
	.string "der Attacke zu erfahren.$"

Help_Text_AnswerWantToAddMoreMoves::
	.string "Ein PKMN kann maximal vier Attacken\n"
	.string "lernen. Es lernt sie beim Level-\l"
	.string "anstieg. Eine neue Attacke kann auch\l"
	.string "durch eine TM (Technische Maschine)\l"
	.string "oder VM (Versteckte Maschine)\l"
	.string "gelernt werden. Weiterhin gibt\l"
	.string "es auch Leute, die Attacken lehren.$"

Help_Text_AnswerWantToMakeMonStronger::
	.string "Das Geheimnis starker PKMN liegt\n"
	.string "darin, mit ihnen zu kämpfen und zu\l"
	.string "gewinnen. Die in Kämpfen erhaltenen\l"
	.string "Erfahrungspunkte (E.-Punkte) führen\l"
	.string "zum Levelanstieg. Kämpfe oft gegen\l"
	.string "wilde POKéMON, um dein\l"
	.string "Team zu stärken.$"

Help_Text_AnswerFoeMonsTooStrong::
	.string "Sind deine Gegner zu stark, musst du\n"
	.string "deine PKMN noch mehr stärken. Gehe\l"
	.string "deinen Weg zurück und kämpfe gegen\l"
	.string "wilde PKMN, um dein Team zu stärken.\l"
	.string "Du kannst auch gegen TRAINER\l"
	.string "kämpfen, gegen die du noch nicht\l"
	.string "gekämpft hast.$"

Help_Text_AnswerWhatDoIDoInCave::
	.string "Anders als auf Straßen und im Wald\n"
	.string "können wilde PKMN in Höhlen immer\l"
	.string "auftauchen. Wird dein PKMN in einer\l"
	.string "Höhle verletzt, kannst du entweder in\l"
	.string "ein PKMN-CENTER eilen oder es mit\l"
	.string "Items sofort heilen. Höhlen stellen\l"
	.string "eine besondere Herausforderung dar.$"

Help_Text_AnswerNothingIWantToKnow::
	.string "Vertraue deinem Wissen und deiner\n"
	.string "Stärke. Glaube an dich und finde\l"
	.string "deinen Weg.$"

Help_Text_AnswerWhatsPokemonCenter::
	.string "Ein PKMN-CENTER erkennst du an dem\n"
	.string "roten Dach und dem “POKé”-Schild.\l"
	.string "In jedem PKMN-CENTER kannst du deine\l"
	.string "PKMN gratis heilen und den PC be-\l"
	.string "nutzen. Im oberen Stockwerk sind Ein-\l"
	.string "richtungen, mit denen du eine Verbin-\l"
	.string "dung zu Freunden herstellen kannst.$"

Help_Text_AnswerWhatsPokemonMart::
	.string "Einen PKMN-SUPERMARKT erkennst du am\n"
	.string "blauen Dach und dem “MRKT”-Schild.\l"
	.string "In einem PKMN-SUPERMARKT können\l"
	.string "Items jederzeit ge- und verkauft\l"
	.string "werden. In manchen SUPERMÄRKTEN\l"
	.string "gibt es Items, die nur in dieser Stadt\l"
	.string "verkauft werden.$"

Help_Text_AnswerWantToEndGame::
	.string "Beende dein Spiel, wenn du “SICHERN”\n"
	.string "im MENÜ auswählst. Nach dem\l"
	.string "Speichern kann es abgeschaltet\l"
	.string "werden. Möchtest du weiterspielen,\l"
	.string "brauchst du lediglich das Spiel\l"
	.string "einzuschalten und kannst direkt dort\l"
	.string "fortfahren, wo du gesichert hast.$"

Help_Text_AnswerWhatsAMon::
	.string "POKéMON sind Lebewesen, um\n"
	.string "die sich noch viele Geheimnisse\l"
	.string "ranken. Du kannst sie im Gras,\l"
	.string "im Wasser und in Höhlen treffen.\l"
	.string "Es scheint, dass sie den\l"
	.string "Anweisungen des TRAINERs,\l"
	.string "der sie gefangen hat, gehorchen.$"

Help_Text_AnswerWhatIsThatPersonLike::
	.string "Setze die RUHMESDATEI aus der\n"
	.string "BASIS-ITEM-TASCHE in deinem\l"
	.string "BEUTEL ein.$"

Help_Text_AnswerWhatDoesHiddenMoveDo::
	.string "Eine VERSTECKTE Attacke kann einem\n"
	.string "PKMN durch eine VM (Versteckte\l"
	.string "Maschine) beigebracht werden.\l"
	.string "VM-Attacken sind wichtig. Es gibt z.B.\l"
	.string "eine, um dunkle Höhlen zu erleuchten.\l"
	.string "Mit einer anderen kannst du kleine\l"
	.string "Bäume fällen.$"

Help_Text_AnswerWhatDoIDoInSafari::
	.string "Versuche wilde POKéMON zu\n"
	.string "fangen, indem du spezielle\l"
	.string "SAFARIBÄLLE benutzt. Jedes\l"
	.string "Item, das du findest, darfst\l"
	.string "du behalten.$"

Help_Text_AnswerWhatAreSafariRules::
	.string "Dein Aufenthalt in der SAFARI-ZONE\n"
	.string "endet, wenn du entweder eine\l"
	.string "bestimmte Distanz zurückgelegt hast\l"
	.string "oder alle SAFARIBÄLLE verbraucht\l"
	.string "hast. Sieh im MENÜ nach, um die\l"
	.string "Anzahl der restlichen Schritte und\l"
	.string "der SAFARIBÄLLE zu überprüfen.$"

Help_Text_AnswerWantToEndSafari::
	.string "Wenn du deinen Aufenthalt in der\n"
	.string "SAFARI-ZONE beenden möchtest,\l"
	.string "öffne das MENÜ und wähle\l"
	.string "“SCHLUSS” vom Anfang der\l"
	.string "Liste aus.$"

Help_Text_AnswerWhatIsAGym::
	.string "POKéMON-ARENEN werden von\n"
	.string "der POKéMON LIGA betrieben und\l"
	.string "dienen als Übungsstätte. In jeder\l"
	.string "Stadt gibt es eine ARENA. Ihnen voran\l"
	.string "steht der LEITER, der ein begabter\l"
	.string "TRAINER ist. Besiege den LEITER\l"
	.string "und verdiene dir so den ORDEN.$"

Help_Text_UsingPokedex::
	.string "“POKéDEX” benutzen?$"

Help_Text_UsingPokemon::
	.string "“POKéMON” benutzen?$"

Help_Text_UsingSummary::
	.string "“BERICHT” lesen?$"

Help_Text_UsingSwitch::
	.string "“TAUSCH” benutzen?$"

Help_Text_UsingItem::
	.string "“ITEM” benutzen?$"

Help_Text_UsingBag::
	.string "“BEUTEL” benutzen?$"

Help_Text_UsingAnItem::
	.string "Ein Item benutzen?$"

Help_Text_UsingKeyItem::
	.string "Ein BASIS-ITEM benutzen?$"

Help_Text_UsingPokeBall::
	.string "Einen POKéBALL benutzen?$"

Help_Text_UsingPlayer::
	.string "“{PLAYER}” benutzen?$"

Help_Text_UsingSave::
	.string "“SICHERN” benutzen?$"

Help_Text_UsingOption::
	.string "“OPTIONEN” benutzen?$"

Help_Text_UsingPotion::
	.string "Einen Trank benutzen?$"

Help_Text_UsingTownMap::
	.string "Die Karte benutzen?$"

Help_Text_UsingTM::
	.string "Eine TM benutzen?$"

Help_Text_UsingHM::
	.string "Eine VM benutzen?$"

Help_Text_UsingMoveOutsideOfBattle::
	.string "Att. außerhalb d. Kampfes benutzen?$"

Help_Text_RidingBicycle::
	.string "FAHRRAD fahren?$"

Help_Text_EnteringName::
	.string "Einen Namen eingeben?$"

Help_Text_UsingPC::
	.string "Den PC benutzen?$"

Help_Text_UsingBillsPC::
	.string "“PC von {STR_VAR_1}” benutzen?$"

Help_Text_UsingWithdraw::
	.string "“NEHMEN” benutzen?$"

Help_Text_UsingDeposit::
	.string "“ABLEGEN” benutzen?$"

Help_Text_UsingMove::
	.string "“BEWEGEN” benutzen?$"

Help_Text_MovingItems::
	.string "Item bewegen!$"

Help_Text_UsingPlayersPC::
	.string "“PC von {PLAYER}” benutzen?$"

Help_Text_UsingWithdrawItem::
	.string "“ITEM NEHMEN” benutzen?$"

Help_Text_UsingDepositItem::
	.string "“ITEM ABLEGEN” benutzen?$"

Help_Text_UsingMailbox::
	.string "“BRIEFBOX” benutzen?$"

Help_Text_UsingProfOaksPC::
	.string "“PROF. EICHs PC” benutzen?$"

Help_Text_OpeningMenu::
	.string "MENÜ öffnen?$"

Help_Text_UsingFight::
	.string "“KAMPF” benutzen?$"

Help_Text_UsingPokemon2::
	.string "“POKéMON” benutzen?$"

Help_Text_UsingShift::
	.string "“TAUSCH” benutzen?$"

Help_Text_UsingSummary2::
	.string "“BERICHT” lesen?$"

Help_Text_UsingBag2::
	.string "“BEUTEL” benutzen?$"

Help_Text_ReadingPokedex::
	.string "“POKéDEX” lesen?$"

Help_Text_UsingHomePC::
	.string "Den PC zu Hause benutzen?$"

Help_Text_UsingItemStorage::
	.string "Item-Lagerungs-System benutzen?$"

Help_Text_UsingWithdrawItem2::
	.string "“ITEM NEHMEN” benutzen?$"

Help_Text_UsingDepositItem2::
	.string "“ITEM ABLEGEN” benutzen?$"

Help_Text_UsingMailbox2::
	.string "Die BRIEFBOX benutzen?$"

Help_Text_UsingRun::
	.string "“FLUCHT” benutzen?$"

Help_Text_RegisterKeyItem::
	.string "Ein BASIS-ITEM “SELECT” zuweisen?$"

Help_Text_UsingBall::
	.string "“BALL” benutzen?$"

Help_Text_UsingBait::
	.string "“KÖDER” benutzen?$"

Help_Text_UsingRock::
	.string "“STEIN” benutzen?$"

Help_Text_UsingHallOfFame::
	.string "“RUHMESHALLE” einsehen?$"

Help_Text_HowToUsePokedex::
	.string "{CIRCLE_1} Wähle “POKéDEX” im MENÜ aus.\n"
	.string "{CIRCLE_2} Wähle beim POKéDEX die Punkte\n"
	.string "“POKéMON-LISTE”, “POKéMON-\n"
	.string "HABITATE” und “SUCHE” aus.\n"
	.string "{CIRCLE_3} Wähle ein POKéMON, um de-\n"
	.string "taillierte Informationen zu erhalten.$"

Help_Text_HowToUsePokemon::
	.string "{CIRCLE_1} Wähle “POKéMON” im\n"
	.string "MENÜ aus.\n"
	.string "{CIRCLE_2} Wähle das POKéMON in deinem\n"
	.string "Team aus.\n"
	.string "{CIRCLE_3} Wähle “BERICHT”, “TAUSCH”\n"
	.string "oder “ITEMS” aus.$"

Help_Text_HowToUseSummary::
	.string "{CIRCLE_1} Wähle “BERICHT” aus.\n"
	.string "{CIRCLE_2} Drücke {PLUS} nach links oder\n"
	.string "rechts, um die Informationen\n"
	.string "durchzuschalten.\n"
	.string "“POKéMON-INFO”\n"
	.string "“POKéMON-FÄHIG.”\n"
	.string "“ATTACKEN”$"

Help_Text_HowToUseSwitch::
	.string "{CIRCLE_1} Wähle das POKéMON, das getauscht\n"
	.string "werden soll.\n"
	.string "{CIRCLE_2} Wähle “TAUSCH” aus.\n"
	.string "{CIRCLE_3} Wähle PKMN aus, das mit dem an\n"
	.string "erster Stelle getauscht werden soll.\n"
	.string "Das PKMN, das links im Bildschirm\n"
	.string "steht, ist das erste im Team.$"

Help_Text_HowToUseItem::
	.string "{CIRCLE_1} Wähle “ITEMS” aus.\n"
	.string "{CIRCLE_2} Wähle, ob du das Item einem\n"
	.string "POKéMON zum Halten “GEBEN”\n"
	.string "oder es von einem POKéMON\n"
	.string "“NEHMEN” möchtest.\n"
	.string "Ein POKéMON kann nicht mehr als\n"
	.string "ein Item halten!$"

Help_Text_HowToUseBag::
	.string "{CIRCLE_1} Wähle “BEUTEL” im MENÜ aus.\n"
	.string "{CIRCLE_2} Drücke {PLUS} nach links oder rechts,\n"
	.string "um die Überschriften zu lesen:\n"
	.string "“ITEMS”\n"
	.string "“BASIS-ITEM”\n"
	.string "“POKéBALL”\n"
	.string "Drücke hier {PLUS} nach oben bzw. unten!$"

Help_Text_HowToUseAnItem::
	.string "{CIRCLE_1} Wähle die “ITEM-Tasche” aus.\n"
	.string "{CIRCLE_2} Drücke {PLUS} nach oben bzw. unten,\n"
	.string "um ein Item auszuwählen.\n"
	.string "{CIRCLE_3} Wähle “O.K.”, um\n"
	.string "ein Item zu benutzen.\n"
	.string "Einige Items können aufgrund der\n"
	.string "Situation nicht eingesetzt werden.$"

Help_Text_HowToUseKeyItem::
	.string "{CIRCLE_1} Wähle die “BASIS-ITEM-Tasche”\n"
	.string "aus.\n"
	.string "{CIRCLE_2} Drücke {PLUS} nach oben bzw. unten,\n"
	.string "um ein Item auszuwählen.\n"
	.string "{CIRCLE_3} Wähle “O.K.”, um\n"
	.string "das ausgewählte BASIS-ITEM\n"
	.string "zu benutzen.$"

Help_Text_HowToUsePokeBall::
	.string "{CIRCLE_1} Wähle, während du gegen ein\n"
	.string "wildes PKMN kämpfst, die\n"
	.string "“POKéBALL-Tasche” aus.\n"
	.string "{CIRCLE_2} Drücke {PLUS} nach oben bzw. unten,\n"
	.string "um einen POKéBALL auszuwählen.\n"
	.string "{CIRCLE_3} Wähle “O.K.” aus,\n"
	.string "um den gewählten POKéBALL zu werfen.$"

Help_Text_HowToUsePlayer::
	.string "{CIRCLE_1} Wähle “{PLAYER}” im MENÜ aus.\n"
	.string "{CIRCLE_2} Dein TRAINERPASS wird mit der\n"
	.string "Frontseite, auf der die Basisinfo\n"
	.string "steht, angezeigt. Drücke den A-Knopf,\n"
	.string "um den PASS umzudrehen.\n"
	.string "{CIRCLE_3} Eine Menge verschiedener Infos\n"
	.string "steht auf der Rückseite des PASS'.$"

Help_Text_HowToUseSave::
	.string "{CIRCLE_1} Wähle “SICHERN” im MENÜ aus.\n"
	.string "{CIRCLE_2} Wähle “JA” aus\n"
	.string "und dein Fortschritt wird gespeichert.\n"
	.string "Wenn gespeichert wurde, kann das\n"
	.string "Spiel abgeschaltet werden. Das\n"
	.string "Spiel kann von der gespeicherten\n"
	.string "Stelle aus fortgesetzt werden.$"

Help_Text_HowToUseOption::
	.string "{CIRCLE_1} Wähle “OPTIONEN” im MENÜ aus.\n"
	.string "{CIRCLE_2} Drücke {PLUS} nach oben bzw. unten,\n"
	.string "um eine Option auszuwählen und nach\n"
	.string "links bzw. rechts, um sie zu ändern.\n"
	.string "{CIRCLE_3} Wähle “ZURÜCK” oder drücke\n"
	.string "den A- oder B-Knopf, nachdem\n"
	.string "die Änderung vorgenommen wurde.$"

Help_Text_HowToUsePotion::
	.string "{CIRCLE_1} Öffne das MENÜ.\n"
	.string "{CIRCLE_2} Drücke {PLUS} nach oben bzw. unten,\n"
	.string "um “BEUTEL” auszuwählen.\n"
	.string "{CIRCLE_3} Wähle “TRANK” in der\n"
	.string "“ITEM-Tasche” aus.\n"
	.string "{CIRCLE_4} Wähle “O.K.” aus.\n"
	.string "{CIRCLE_5} Wähle das zu heilende POKéMON.$"

Help_Text_HowToUseTownMap::
	.string "{CIRCLE_1} Öffne das MENÜ.\n"
	.string "{CIRCLE_2} Drücke {PLUS} nach oben bzw. unten,\n"
	.string "um “BEUTEL” auszuwählen.\n"
	.string "{CIRCLE_3} Drücke {PLUS} nach links bzw. rechts,\n"
	.string "öffne die “BASIS-ITEM-Tasche” und\n"
	.string "bewege den Cursor auf “KARTE”.\n"
	.string "{CIRCLE_4} Wähle anschließend “O.K.” aus.$"

Help_Text_HowToUseTM::
	.string "{CIRCLE_1} Öffne das MENÜ.\n"
	.string "{CIRCLE_2} Drücke {PLUS} nach oben bzw. unten\n"
	.string "und öffne die “BASIS-ITEM-Tasche”\n"
	.string "des “BEUTELs”.\n"
	.string "{CIRCLE_3} Öffne die “VM/TM-BOX”.\n"
	.string "{CIRCLE_4} Wähle nun “O.K.” aus.\n"
	.string "{CIRCLE_5} Wähle ein PKMN für die TM aus.$"

Help_Text_HowToUseHM::
	.string "{CIRCLE_1} Öffne das MENÜ.\n"
	.string "{CIRCLE_2} Öffne die “BASIS-ITEM-Tasche”\n"
	.string "des “BEUTELs”.\n"
	.string "{CIRCLE_3} Öffne die “VM/TM-BOX”.\n"
	.string "{CIRCLE_4} Wähle die VM und “O.K.”.\n"
	.string "{CIRCLE_5} Wähle ein PKMN aus, das die Att.\n"
	.string "der VM erlernen kann.$"

Help_Text_HowToUseMoveOutsideOfBattle::
	.string "{CIRCLE_1} Öffne das MENÜ.\n"
	.string "{CIRCLE_2} Wähle “POKéMON” aus.\n"
	.string "{CIRCLE_3} Wähle ein POKéMON, das eine\n"
	.string "VM beherrscht. Die möglichen\n"
	.string "Attacken werden blau dargestellt.\n"
	.string "Wähle die gewünschte Attacke aus\n"
	.string "und entferne ein Hindernis usw.$"

Help_Text_HowToRideBicycle::
	.string "{CIRCLE_1} Öffne das MENÜ und anschließend\n"
	.string "die “BASIS-ITEM-Tasche” deines\n"
	.string "“BEUTELs”. Wähle “FAHRRAD” aus.\n"
	.string "{CIRCLE_2} Wähle FAHRRAD und “O.K.” aus.\n"
	.string "Das FAHRRAD kann auf SELECT gelegt\n"
	.string "werden, um sofort aufzusteigen,\n"
	.string "wenn SELECT gedrückt wird.$"

Help_Text_HowToEnterName::
	.string "{CIRCLE_1} Drücke {PLUS}, um Cursor auf\n"
	.string "Buchstaben zu bewegen. Drücke\n"
	.string "A-Knopf, um deine Wahl zu bestätigen.\n"
	.string "{CIRCLE_2} Drücke B-Knopf zum Widerrufen.\n"
	.string "{CIRCLE_3} Drücke SELECT, um Groß- und\n"
	.string "Kleinbuchstaben zu wechseln.\n"
	.string "{CIRCLE_4} Drücke den A-Knopf bei “O.K.”$"

Help_Text_HowToUsePC::
	.string "{CIRCLE_1} Begib dich in ein\n"
	.string "POKéMON-CENTER, geh zum\n"
	.string "PC und drücke den A-Knopf.$"

Help_Text_HowToUseBillsPC::
	.string "{CIRCLE_1} Wähle “{STR_VAR_1}s PC” am PC.\n"
	.string "{CIRCLE_2} Wähle eine der obersten drei\n"
	.string "MENÜ-Optionen, um in das POKéMON-\n"
	.string "Lagerungs-System zu gelangen. Fängst\n"
	.string "du ein POKéMON und hast bereits 6 in\n"
	.string "deinem Team, wird es automatisch in\n"
	.string "1 BOX im Lagerungs-System geschickt.$"

Help_Text_HowToUseWithdraw::
	.string "{CIRCLE_1} Wähle ein POKéMON aus der geöff-\n"
	.string "neten BOX durch Drücken von {PLUS} aus.\n"
	.string "{CIRCLE_2} Wähle “NEHMEN”, um\n"
	.string "das POKéMON aus der BOX zu nehmen\n"
	.string "und es in dein Team aufzunehmen.\n"
	.string "Hast du bereits 6 PKMN im Team,\n"
	.string "kannst du kein PKMN mehr mitnehmen.$"

Help_Text_HowToUseDeposit::
	.string "{CIRCLE_1} Wähle ein POKéMON aus deinem\n"
	.string "Team durch Drücken von {PLUS} aus.\n"
	.string "{CIRCLE_2} Wähle “ABLEGEN” aus.\n"
	.string "{CIRCLE_3} Wähle die BOX, in der das PKMN\n"
	.string "abgelegt wird u. drücke den A-Knopf.\n"
	.string "Wenn du nur ein PKMN im Team\n"
	.string "hast, kannst du kein POKéMON ablegen.$"

Help_Text_HowToUseMove::
	.string "{CIRCLE_1} Wähle ein PKMN aus der Box.\n"
	.string "{CIRCLE_2} Nimm das POKéMON, indem du\n"
	.string "“BEWEGEN” auswählst\n"
	.string "und bewege es durch Drücken von {PLUS}.\n"
	.string "{CIRCLE_3} Bewege das PKMN zum Namen der\n"
	.string "BOX und drücke {PLUS} nach links bzw.\n"
	.string "rechts für eine andere BOX.$"

Help_Text_HowToMoveItems::
	.string "{CIRCLE_1} Transparent dargestellte PKMN\n"
	.string "können ein Item halten. Wähle das\n"
	.string "Item aus und drücke den A-Knopf.\n"
	.string "{CIRCLE_2} Undurchsichtige PKMN können das\n"
	.string "gehaltene Item einem anderen PKMN\n"
	.string "geben oder es durch Drücken des\n"
	.string "A-Knopfs zurück in den BEUTEL legen.$"

Help_Text_HowToUsePlayersPC::
	.string "{CIRCLE_1} Wähle “PC von {PLAYER}” am PC.\n"
	.string "{CIRCLE_2} Wähle entweder “ITEM-LAGER”\n"
	.string "oder “BRIEFBOX” aus.\n"
	.string "Falls dein BEUTEL voll ist,\n"
	.string "kannst du Items in deinem PC\n"
	.string "ablegen. Von dort kannst du\n"
	.string "auch Items aufnehmen.$"

Help_Text_HowToUseWithdrawItem::
	.string "{CIRCLE_1} Wähle “ITEM NEHMEN” aus.\n"
	.string "{CIRCLE_2} Wähle das Item, das\n"
	.string "aufgenommen werden soll aus.\n"
	.string "{CIRCLE_3} Das Item kann direkt in die\n"
	.string "ITEM-Tasche des BEUTELs\n"
	.string "gelegt oder einem POKéMON\n"
	.string "zum Halten gegeben werden.$"

Help_Text_HowToUseDepositItem::
	.string "{CIRCLE_1} Wähle “ITEM ABLEGEN” aus.\n"
	.string "{CIRCLE_2} Wähle das Item, das abgelegt\n"
	.string "werden soll durch Drücken von {PLUS} aus.\n"
	.string "{CIRCLE_3} Falls mehr als ein Exemplar von\n"
	.string "diesem Item abgelegt werden kann,\n"
	.string "kann die abzulegende Anzahl durch\n"
	.string "Drücken von {PLUS} verändert werden.$"

Help_Text_HowToUseMailbox::
	.string "Wird einem PKMN ein BRIEF genommen,\n"
	.string "kommt er in die BRIEFBOX. Ohne\n"
	.string "BRIEF kann die BRIEFBOX nicht\n"
	.string "benutzt werden.\n"
	.string "{CIRCLE_1} Wähle “PC von {PLAYER}” am PC.\n"
	.string "{CIRCLE_2} Wähle “BRIEFBOX”, um BRIEFe zu\n"
	.string "lesen oder sie einem PKMN zu geben.$"

Help_Text_HowToUseProfOaksPC::
	.string "{CIRCLE_1} Wähle “PROF. EICHs PC” am PC.\n"
	.string "{CIRCLE_2} PROF. EICH wird deinen POKéDEX\n"
	.string "bewerten.\n"
	.string "Seine Bewertung hilft dir noch mehr\n"
	.string "POKéMON zu fangen!$"

Help_Text_HowToOpenMenu::
	.string "{CIRCLE_1} Drücke START.\n"
	.string "{CIRCLE_2} Das MENÜ öffnet sich rechts.\n"
	.string "{CIRCLE_3} Die Möglichkeiten im MENÜ\n"
	.string "ändern sich situationsabhängig.\n"
	.string "Das MENÜ lässt sich in gewissen Situ-\n"
	.string "ationen wie z.B. während einer Unter-\n"
	.string "haltung oder im Kampf nicht öffnen.$"

Help_Text_HowToUseFight::
	.string "{CIRCLE_1} Wähle “KAMPF” aus.\n"
	.string "{CIRCLE_2} Wähle eine der aufgelisteten\n"
	.string "Attacken und drücke den A-Knopf, um\n"
	.string "sie einzusetzen.$"

Help_Text_HowToUsePokemon2::
	.string "{CIRCLE_1} Wähle “POKéMON” aus.\n"
	.string "{CIRCLE_2} Wähle das POKéMON aus deinem\n"
	.string "TEAM, das eingesetzt werden soll.\n"
	.string "{CIRCLE_3} Falls du 2 oder mehr PKMN hast,\n"
	.string "können sie durch “TAUSCH” ausgewech-\n"
	.string "selt werden. Überprüfe die Daten der\n"
	.string "PKMN, indem du “BERICHT” auswählst.$"

Help_Text_HowToUseShift::
	.string "Mit diesem Befehl kannst du das\n"
	.string "POKéMON im Kampf auswechseln.\n"
	.string "{CIRCLE_1} Wähle das POKéMON, das du\n"
	.string "einsetzen möchtest.\n"
	.string "{CIRCLE_2} Wähle “TAUSCH” aus.\n"
	.string "{CIRCLE_3} Das ausgewählte POKéMON wird\n"
	.string "mit dem im Kampf ausgetauscht!$"

Help_Text_HowToUseSummary2::
	.string "{CIRCLE_1} Wähle “BERICHT” aus.\n"
	.string "{CIRCLE_2} Drücke {PLUS} nach links oder\n"
	.string "rechts, um die Informationen\n"
	.string "durchzuschalten.\n"
	.string "“POKéMON-INFO”\n"
	.string "“POKéMON-FÄHIG.”\n"
	.string "“ATTACKEN”$"

Help_Text_HowToUseBag2::
	.string "{CIRCLE_1} Wähle “BEUTEL” aus.\n"
	.string "{CIRCLE_2} Drücke {PLUS} nach links bzw. rechts,\n"
	.string "um die Überschriften zu lesen.\n"
	.string "“ITEMS”\n"
	.string "“BASIS-ITEM”\n"
	.string "“POKéBALL”\n"
	.string "{PLUS} nach oben bzw. unten zur Auswahl.$"

Help_Text_HowToReadPokedex::
	.string "{CIRCLE_1} Gefangene PKMN werden durch ein\n"
	.string "POKéBALL-Symbol in der POKéDEX-Liste\n"
	.string "angezeigt.\n"
	.string "{CIRCLE_2} Beim Fangen eines POKéMON\n"
	.string "gibt es eine Menge neuer Infos.\n"
	.string "{CIRCLE_3} Wähle “MEHR INFO” aus,\n"
	.string "um das Habitat des PKMN anzusehen.$"

Help_Text_HowToUseHomePC::
	.string "{CIRCLE_1} Begib dich zu deinem PC\n"
	.string "zu Hause und drücke den A-Knopf.\n"
	.string "{CIRCLE_2} Der PC wird hochgefahren.\n"
	.string "{CIRCLE_3} Wähle entweder “ITEM-LAGER”\n"
	.string "oder “BRIEFBOX” aus.$"

Help_Text_HowToUseItemStorage::
	.string "{CIRCLE_1} Wähle “ITEM NEHMEN” aus,\n"
	.string "um ein Item, das auf deinem\n"
	.string "PC liegt, zu nehmen.\n"
	.string "{CIRCLE_2} Wähle “ITEM ABLEGEN” aus,\n"
	.string "um ein Item aus dem BEUTEL\n"
	.string "im PC zu lagern.$"

Help_Text_HowToUseWithdrawItem2::
	.string "{CIRCLE_1} Wähle “ITEM NEHMEN” aus.\n"
	.string "{CIRCLE_2} Wähle das Item aus, das\n"
	.string "aufgenommen werden soll.\n"
	.string "{CIRCLE_3} Das Item kann direkt in die\n"
	.string "ITEM-Tasche des BEUTELs\n"
	.string "gelegt oder einem POKéMON\n"
	.string "zum Halten gegeben werden.$"

Help_Text_HowToUseDepositItem2::
	.string "{CIRCLE_1} Wähle “ITEM ABLEGEN” aus.\n"
	.string "{CIRCLE_2} Wähle das Item, das aus dem\n"
	.string "BEUTEL abgelegt werden soll, durch\n"
	.string "Drücken von {PLUS} aus.\n"
	.string "{CIRCLE_3} Falls dein BEUTEL leer ist,\n"
	.string "kann dieser Befehl nicht verwendet\n"
	.string "werden.$"

Help_Text_HowToUseMailbox2::
	.string "Falls ein BRIEF einem PKMN genommen\n"
	.string "wird, kommt er in die BRIEFBOX. Ohne\n"
	.string "BRIEF kann die BRIEFBOX\n"
	.string "nicht genutzt werden.\n"
	.string "{CIRCLE_1} Wähle die BRIEFe nach ihrer\n"
	.string "Bezeichnung aus, um sie zu lesen\n"
	.string "oder gib sie einem PKMN zu tragen.$"

Help_Text_HowToUseRun::
	.string "Du kannst den Befehl “FLUCHT”\n"
	.string "in TRAINER-Kämpfen nicht anwenden!\n"
	.string "{CIRCLE_1} Du kannst den Befehl “FLUCHT”\n"
	.string "im Kampf mit wilden PKMN benutzen.\n"
	.string "{CIRCLE_2} Deine Chance zu entkommen\n"
	.string "ist höher, wenn dein POKéMON einen\n"
	.string "hohen INITIATIVE-Wert hat.$"

Help_Text_HowToRegisterKeyItem::
	.string "Du kannst “SELECT” ein\n"
	.string "Basis-Item zuweisen.\n"
	.string "{CIRCLE_1} Öffne die “BASIS-ITEM-Tasche”.\n"
	.string "{CIRCLE_2} Wähle das Basis-Item aus und\n"
	.string "anschließend “SELECT”.$"

Help_Text_HowToUseBall::
	.string "Wirf den speziellen POKéBALL\n"
	.string "für die SAFARI-ZONE.\n"
	.string "Taucht ein wildes POKéMON auf,\n"
	.string "solltest du viele SAFARIBÄLLE\n"
	.string "werfen, um es zu fangen.$"

Help_Text_HowToUseBait::
	.string "Wirf den speziellen KÖDER für die\n"
	.string "SAFARI-ZONE. Er besteht aus\n"
	.string "POKéMON-Nahrung, die zu einem\n"
	.string "Ball gerollt wurde, um sie leichter\n"
	.string "zu essen. Durch den Einsatz des\n"
	.string "KÖDERs werden wilde PKMN angelockt\n"
	.string "und fliehen nicht so schnell.$"

Help_Text_HowToUseRock::
	.string "Wirf einen Stein, der am\n"
	.string "Boden der SAFARI-ZONE liegt.\n"
	.string "Dadurch fliehen die POKéMON\n"
	.string "zwar eher, sind aber einfacher\n"
	.string "zu fangen.$"

Help_Text_HowToUseHallOfFame::
	.string "{CIRCLE_1} Wähle “RUHMESHALLE”\n"
	.string "am PC aus.\n"
	.string "{CIRCLE_2} Die POKéMON, die in die\n"
	.string "RUHMESHALLE aufgenommen\n"
	.string "wurden, können betrachtet werden.$"

Help_Text_HP::
	.string "KP$"

Help_Text_EXP::
	.string "ERF. {LEFT_PAREN}E.-Punkte{RIGHT_PAREN}$"

Help_Text_Moves::
	.string "ATTACKEN$"

Help_Text_Attack::
	.string "ANGRIFF$"

Help_Text_Defense::
	.string "VERT.$"

Help_Text_SpAtk::
	.string "SP. ANG.$"

Help_Text_SpDef::
	.string "SP. VER.$"

Help_Text_Speed::
	.string "INIT.$"

Help_Text_Level::
	.string "Lv. {LEFT_PAREN}Level{RIGHT_PAREN}$"

Help_Text_Type::
	.string "TYP$"

Help_Text_OT::
	.string "OT$"

Help_Text_Item::
	.string "ITEMS$"

Help_Text_Ability::
	.string "FÄHIGKEIT$"

Help_Text_Money::
	.string "GELD$"

Help_Text_MoveType::
	.string "ELEMENTKLASSE der ATTACKE$"

Help_Text_Nature::
	.string "WESEN$"

Help_Text_IDNo::
	.string "IDNr.$"

Help_Text_PP::
	.string "AP$"

Help_Text_Power::
	.string "STÄRKE$"

Help_Text_Accuracy::
	.string "GENAU.$"

Help_Text_FNT::
	.string "BSG$"

Help_Text_Items::
	.string "ITEMS$"

Help_Text_KeyItems::
	.string "BASIS-ITEM$"

Help_Text_PokeBalls::
	.string "POKéBÄLLE$"

Help_Text_Pokedex::
	.string "POKéDEX$"

Help_Text_PlayTime::
	.string "SPIELZEIT$"

Help_Text_Badges::
	.string "ORDEN$"

Help_Text_TextSpeed::
	.string "TEXT-TEMPO$"

Help_Text_BattleScene::
	.string "ANIMATION$"

Help_Text_BattleStyle::
	.string "KAMPFSTIL$"

Help_Text_Sound::
	.string "TON$"

Help_Text_ButtonMode::
	.string "KNOPFBELEGUNG$"

Help_Text_Frame::
	.string "RAHMEN$"

Help_Text_Cancel2::
	.string "ZURÜCK$"

Help_Text_TM::
	.string "TM$"

Help_Text_HM::
	.string "VM$"

Help_Text_HMMove::
	.string "VM-ATTACKE$"

Help_Text_Evolution::
	.string "ENTWICKLUNG$"

Help_Text_StatusProblem::
	.string "STATUSPROBLEM$"

Help_Text_Pokemon::
	.string "POKéMON$"

Help_Text_IDNo2::
	.string "IDNr.$"

Help_Text_Money2::
	.string "GELD$"

Help_Text_Badges2::
	.string "ORDEN$"

Help_Text_DefineHP::
	.string "Die KP geben die Lebensenergie eines\n"
	.string "PKMN an. Fallen die KP auf null, kann\l"
	.string "das PKMN nicht mehr kämpfen. Der\l"
	.string "Schlüssel zum Sieg ist die gegn. KP.\l"
	.string "Sind deine PKMN verletzt, kannst du\l"
	.string "sie in einem PKMN-CENTER oder\l"
	.string "durch Items heilen.$"

Help_Text_DefineEXP::
	.string "E.-PUNKTE steht für\n"
	.string "“ERFAHRUNGSPUNKTE”. PKMN erhalten\l"
	.string "E.-PUNKTE, wenn sie erfolgreich\l"
	.string "kämpfen. Hat ein PKMN genug\l"
	.string "E.-PUNKTE, steigt sein Level. Die\l"
	.string "E.-PUNKT-Anzeige gibt die\l"
	.string "erhaltenen E.-PUNKTE an.$"

Help_Text_DefineMoves::
	.string "PKMN können bis zu vier Attacken\n"
	.string "erlernen. Es gibt eine schier unend-\l"
	.string "liche Anzahl an Attacken, darunter\l"
	.string "einige mit Spezialeffekten. Welche\l"
	.string "Attacken erlernt werden können,\l"
	.string "hängt vom PKMN ab. Einige Attacken\l"
	.string "können von Items gelernt werden.$"

Help_Text_DefineAttack::
	.string "ANGRIFF gibt die Stärke einer\n"
	.string "Attacke an. Je höher dieser Wert\l"
	.string "ist, desto stärker ist die Attacke.\l"
	.string "Dies gilt für die folgenden\l"
	.string "Elementklassen: NORMAL, GIFT,\l"
	.string "BODEN, FLUG, KÄFER, KAMPF,\l"
	.string "GESTEIN, GEIST und STAHL.$"

Help_Text_DefineDefense::
	.string "VERT. (VERTEIDIGUNG) gibt\n"
	.string "die Widerstandskraft eines\l"
	.string "POKéMON gegen eine\l"
	.string "physische Attacke an. Je höher\l"
	.string "dieser Wert ist, desto weniger\l"
	.string "Schaden nimmt ein POKéMON\l"
	.string "bei einem physischen Angriff.$"

Help_Text_DefineSpAtk::
	.string "SP. ANG. (Spezial-Angriff) gibt die\n"
	.string "Stärke einer Spezial-Angriff-Attacke\l"
	.string "an. Je höher der Wert ist, desto\l"
	.string "stärker ist der Spezial-Angriff. Dies\l"
	.string "gilt für die folgenden Elementklassen:\l"
	.string "FEUER, WASSER, ELEKTRO, PFLANZE,\l"
	.string "EIS, PSYCHO, DRACHEN und UNLICHT.$"

Help_Text_DefineSpDef::
	.string "SP. VER. (Spezial-Verteidigung) gibt\n"
	.string "die Widerstandskraft eines POKéMON\l"
	.string "gegen eine Spezial-Angriff-Attacke\l"
	.string "an. Je höher dieser Wert ist, desto\l"
	.string "weniger Schaden nimmt ein\l"
	.string "POKéMON bei einer\l"
	.string "Spezial-Angriff-Attacke.$"

Help_Text_DefineSpeed::
	.string "INIT. (INITIATIVE) gibt die\n"
	.string "Beweglichkeit eines POKéMON\l"
	.string "an. Ist dieser Wert höher\l"
	.string "als der des Gegners, darf dein\l"
	.string "POKéMON zuerst angreifen.$"

Help_Text_DefineLevel::
	.string "Lv. (Level) gibt das Wachstum und\n"
	.string "die Stärke des PKMN an. Generell\l"
	.string "gilt, dass die Werte für KP, ANGRIFF\l"
	.string "und VERTEIDIGUNG beim Levelanstieg\l"
	.string "eines PKMN steigen und es somit stär-\l"
	.string "ker wird. Vielleicht lernt das PKMN\l"
	.string "beim Levelanstieg eine neue Attacke.$"

Help_Text_DefineType::
	.string "PKMN und Attacken sind in Element-\n"
	.string "klassen eingeordnet. Jede Klasse hat\l"
	.string "einen Vor- bzw. Nachteil gegenüber\l"
	.string "einer anderen. Es ist das Prinzip von\l"
	.string "Stein-Papier-Schere. Z.B. ist\l"
	.string "WASSER stark gegen FEUER\l"
	.string "und schwach gegen PFLANZE.$"

Help_Text_DefineOT::
	.string "OT steht für “ORIGINAL-TRAINER”.\n"
	.string "OT ist der TRAINER, der das\l"
	.string "POKéMON zuerst gefangen hat.\l"
	.string "Auch wenn das POKéMON\l"
	.string "getauscht wird, bleibt der\l"
	.string "Name des OT unverändert.$"

Help_Text_DefineItem::
	.string "Jedem POKéMON kann ein Item\n"
	.string "zum Halten gegeben werden. Einige\l"
	.string "Items werden vom POKéMON\l"
	.string "automatisch in bestimmten\l"
	.string "Situationen benutzt. Um einem\l"
	.string "PKMN ein Item zum Halten zu geben,\l"
	.string "wähle im BEUTEL “GEBEN” aus.$"

Help_Text_DefineAbility::
	.string "Jedes POKéMON verfügt über eine\n"
	.string "Spezial-FÄHIGKEIT. Es gibt viele\l"
	.string "verschiedene Fähigkeiten. Manche\l"
	.string "kommen im Kampf zum Einsatz,\l"
	.string "manche außerhalb. Die Fähigkeit ist\l"
	.string "von Art zu Art verschieden. Manche\l"
	.string "Arten haben mehr als eine Fähigkeit.$"

Help_Text_DefineMoney::
	.string "Bei jedem Sieg gegen einen\n"
	.string "gegnerischen TRAINER\l"
	.string "erhältst du ein Preisgeld. Spare\l"
	.string "dieses Geld, um im POKéMON-\l"
	.string "SUPERMARKT einkaufen zu gehen.$"

Help_Text_DefineMoveType::
	.string "Auch Attacken werden Elementklassen\n"
	.string "zugeordnet. Setzt ein POKéMON einer\l"
	.string "Klasse eine Attacke derselben Klasse\l"
	.string "ein, wird die Attacke verstärkt.\l"
	.string "Falls die Klasse der Attacke dem\l"
	.string "Ziel gegenüber im Vorteil ist,\l"
	.string "wird die Attacke noch stärker.$"

Help_Text_DefineNature::
	.string "Jedes POKéMON besitzt eine\n"
	.string "Persönlichkeit, die hier “WESEN”\l"
	.string "genannt wird. Vom Wesen hängt\l"
	.string "ab, wie sich das POKéMON\l"
	.string "beim Levelanstieg verhält.$"

Help_Text_DefineIDNo::
	.string "Die ID-Nr. ist eine spezielle Nummer,\n"
	.string "die dir als TRAINER zugewiesen\l"
	.string "wurde. Zusammen mit dem OT-Namen\l"
	.string "kann der Original-TRAINER genau\l"
	.string "identifiziert werden. Die ID-Nr.\l"
	.string "ändert sich nicht, selbst wenn ein\l"
	.string "POKéMON getauscht wird.$"

Help_Text_DefinePP::
	.string "AP steht für “ANGRIFFSPUNKTE”.\n"
	.string "Die Anzahl gibt an, wie oft eine\l"
	.string "Attacke im Kampf eingesetzt werden\l"
	.string "kann. Wie bei KP gilt auch für AP,\l"
	.string "dass sie in einem POKéMON-CENTER\l"
	.string "oder durch den Einsatz gewisser\l"
	.string "Items aufgefüllt werden können.$"

Help_Text_DefinePower::
	.string "STÄRKE gibt die Stärke einer\n"
	.string "Attacke an. Je höher diese\l"
	.string "Zahl ist, desto mehr Schaden\l"
	.string "richtet diese Attacke beim\l"
	.string "Gegner an.$"

Help_Text_DefineAccuracy::
	.string "GENAU. (Genauigkeit) gibt die\n"
	.string "Trefferwahrscheinlichkeit der\l"
	.string "Attacke an. Je höher die\l"
	.string "Zahl, desto wahrscheinlicher\l"
	.string "wird der Gegner getroffen.$"

Help_Text_DefineFNT::
	.string "BSG steht für “BESIEGT”.\n"
	.string "Ein POKéMON ist besiegt, wenn\l"
	.string "seine KP null erreichen. Es kann\l"
	.string "nicht mehr am Kampf teilnehmen.\l"
	.string "Heile ein besiegtes POKéMON\l"
	.string "in einem POKéMON-CENTER\l"
	.string "oder durch ein Item.$"

Help_Text_DefineItems::
	.string "Gewöhnliche Items, die in einem\n"
	.string "POKéMON-SUPERMARKT gekauft\l"
	.string "wurden, werden in die ITEM-Tasche\l"
	.string "gelegt. Sie können verwendet,\l"
	.string "einem POKéMON zum Halten\l"
	.string "gegeben oder weggeworfen werden.$"

Help_Text_DefineKeyItems::
	.string "Wichtige Items, die du findest oder\n"
	.string "von Leuten erhältst, werden in der\l"
	.string "BASIS-ITEM-TASCHE verstaut. BASIS-\l"
	.string "ITEMs können verwendet oder SELECT\l"
	.string "zugewiesen werden. Ein SELECT\l"
	.string "zugewiesenes Item kann durch Drücken\l"
	.string "von SELECT direkt benutzt werden.$"

Help_Text_DefinePokeBalls::
	.string "POKéBÄLLE, die beim Fang von wilden\n"
	.string "PKMN eingesetzt werden, finden in der\l"
	.string "POKéBALL-Tasche Platz. POKéBÄLLE\l"
	.string "können in POKéMON-SUPERMÄRKTEN\l"
	.string "gekauft werden. Sie können verwendet,\l"
	.string "einem POKéMON zum Halten gegeben\l"
	.string "oder weggeworfen werden.$"

Help_Text_DefinePokedex::
	.string "Hier werden alle verschiedenen\n"
	.string "POKéMON, die du gefangen\l"
	.string "hast oder die sich bei dir\l"
	.string "entwickelt haben, aufgelistet.\l"
	.string "Streng dich an und versuche\l"
	.string "alle zu fangen!$"

Help_Text_DefinePlayTime::
	.string "Dies ist die gesamte Spielzeit!$"

Help_Text_DefineBadges::
	.string "Die ORDEN der POKéMON LIGA, die\n"
	.string "du gewonnen hast, sind hier auf-\l"
	.string "gelistet und abgebildet. Gewinne\l"
	.string "ORDEN, indem du die ARENA-\l"
	.string "LEITER der verschiedenen\l"
	.string "Städte besiegst.$"

Help_Text_DefineTextSpeed::
	.string "Du kannst einstellen, in welcher\n"
	.string "Geschwindigkeit der Text\l"
	.string "eingeblendet wird. Wähle\l"
	.string "zwischen: LANGSAM, NORMAL\l"
	.string "oder SCHNELL!$"

Help_Text_DefineBattleScene::
	.string "Du kannst die Kampfanimationen\n"
	.string "EIN- oder AUSschalten!$"

Help_Text_DefineBattleStyle::
	.string "Lege fest, ob es einem TRAINER\n"
	.string "gestattet ist, das POKéMON zu\l"
	.string "wechseln, wenn es einen Gegner\l"
	.string "besiegt hat oder nicht. Wähle\l"
	.string "“WECHSEL” aus, wenn\l"
	.string "du den Wechsel gestatten möchtest.$"

Help_Text_DefineSound::
	.string "Du kannst zwischen MONO und\n"
	.string "STEREO wählen.$"

Help_Text_DefineButtonMode::
	.string "Stelle “HILFE” ein, um den Hilfe-\n"
	.string "modus durch Drücken der L- bzw.\l"
	.string "R-Taste zu aktivieren. Bei “L/R”\l"
	.string "kannst du POKéDEX und BEUTEL durch\l"
	.string "Drücken der L- bzw. R-Taste\l"
	.string "durchschalten. Bei “L=A”\l"
	.string "ist die L-Taste wie der A-Knopf.$"

Help_Text_DefineFrame::
	.string "Du kannst das Design der Rahmen\n"
	.string "in manchen Menüs ändern. Such dir\l"
	.string "ein Design aus, das dir gefällt.$"

Help_Text_DefineCancel2::
	.string "Die Einstellungen werden in den\n"
	.string "in rot dargestellten Optionen\l"
	.string "festgelegt und du kehrst\l"
	.string "ins MENÜ zurück.$"

Help_Text_DefineTM::
	.string "Eine TM (Technische Maschine) ist ein\n"
	.string "Gerät, mit dem einem PKMN eine Att.\l"
	.string "gelehrt werden kann. Es gibt sehr\l"
	.string "viele unterschiedliche Att. Die Att.\l"
	.string "können nur den PKMN gelehrt\l"
	.string "werden, die sie auch einsetzen kön-\l"
	.string "nen. Eine TM ist nur 1-mal einsetzbar.$"

Help_Text_DefineHM::
	.string "Eine VM (Versteckte Maschine) ist ein\n"
	.string "Gerät, mit dem einem PKMN eine\l"
	.string "VERSTECKTE Attacke gelehrt werden\l"
	.string "kann. Die Attacke kann nur dem PKMN\l"
	.string "gelehrt werden, das sie auch ein-\l"
	.string "setzen kann. Anders als eine TM kann\l"
	.string "eine VM wieder verwendet werden.$"

Help_Text_DefineHMMove::
	.string "VERSTECKTE Attacken sind wichtig.\n"
	.string "Um solch eine Att. außerhalb eines\l"
	.string "Kampfes anzuwenden, musst du das\l"
	.string "“POKéMON-MENÜ” öffnen und das PKMN,\l"
	.string "das die Att. kann, veranlassen, sie zu\l"
	.string "benutzen. Ein besiegtes PKMN kann sie\l"
	.string "außerhalb des Kampfes anwenden.$"

Help_Text_DefineEvolution::
	.string "Es gibt PKMN, die starke Änderungen\n"
	.string "vollziehen (Entwicklung), wenn sie\l"
	.string "einen gewissen Level erreichen.\l"
	.string "Beim Entwickeln verändert ein PKMN\l"
	.string "Aussehen, Namen und evtl. lernt es\l"
	.string "andere Att. Einige PKMN entwickeln\l"
	.string "sich nicht durch Levelanstieg.$"

Help_Text_DefineStatusProblem::
	.string "Als Statusprobleme gelten:\n"
	.string "Schlaf: Keine Attacken möglich!\l"
	.string "Gift: Steter KP-Verlust!\l"
	.string "Paralyse: Evtl. keine Attacken!\l"
	.string "Verbrennung: KP-Verlust u. kaum ANG.\l"
	.string "Eingefroren: Keine Attacken möglich!\l"
	.string "Items können das beheben.$"

Help_Text_DefinePokemon::
	.string "POKéMON heißen die\n"
	.string "wundervollen Geschöpfe, die\l"
	.string "überall in dieser Welt leben.\l"
	.string "Die Menschen halten POKéMON\l"
	.string "als Haustiere, tragen Kämpfe\l"
	.string "mit ihnen aus usw.$"

Help_Text_DefineIDNo2::
	.string "Die ID-Nr. ist eine spezielle Nummer,\n"
	.string "die dir als TRAINER zugewiesen\l"
	.string "wurde. Zusammen mit dem\l"
	.string "OT-Namen kann der Original-\l"
	.string "TRAINER genau identifiziert werden.\l"
	.string "Die ID-Nr. ändert sich nicht, selbst\l"
	.string "wenn ein POKéMON getauscht wird.$"

Help_Text_DefineMoney2::
	.string "Bei jedem Sieg gegen einen\n"
	.string "gegnerischen TRAINER\l"
	.string "erhältst du ein Preisgeld. Spare\l"
	.string "dieses Geld, um im POKéMON-\l"
	.string "SUPERMARKT einkaufen zu gehen.$"

Help_Text_DefineBadges2::
	.string "Die ORDEN der POKéMON LIGA, die\n"
	.string "du gewonnen hast, sind hier auf-\l"
	.string "gelistet. Gewinne ORDEN, indem\l"
	.string "du die ARENALEITER der\l"
	.string "verschiedenen Städte besiegst.$"

Help_Text_TheHelpSystem::
	.string "Das HILFE-Menü$"

Help_Text_TheGame::
	.string "Das Spiel$"

Help_Text_WirelessAdapter::
	.string "Drahtloser GBA-Adapter$"

Help_Text_GameFundamentals1::
	.string "Grundlegendes zum Spiel 1$"

Help_Text_GameFundamentals2::
	.string "Grundlegendes zum Spiel 2$"

Help_Text_GameFundamentals3::
	.string "Grundlegendes zum Spiel 3$"

Help_Text_WhatArePokemon::
	.string "Was sind POKéMON?$"

Help_Text_DescTheHelpSystem::
	.string "Die Tipps im HILFE-Menü ändern\n"
	.string "sich mit deinem Fortschritt im\l"
	.string "Spiel. Sie sollen dir helfen, wenn\l"
	.string "du sie brauchst. Gibt es etwas,\l"
	.string "das du nicht verstehst, kannst\l"
	.string "du es im HILFE-Menü nachschlagen!$"

Help_Text_DescTheGame::
	.string "Deine Aufgabe als Protagonist\n"
	.string "besteht darin, die Welt der\l"
	.string "POKéMON zu erforschen! Indem\l"
	.string "du mit Leuten sprichst und Rätsel\l"
	.string "löst, öffnest du neue Wege.\l"
	.string "Erreiche dein Ziel zusammen mit \l"
	.string "deinen wunderbaren POKéMON.$"

Help_Text_DescWirelessAdapter::
	.string "Bei diesem Spiel wird die\n"
	.string "drahtlose Datenübertragung mittels\l"
	.string "des Drahtlosen Adapters eingesetzt.\l"
	.string "Mache davon überall, jederzeit und\l"
	.string "mit jedem Gebrauch! Versuche beim\l"
	.string "Spielen den Drahtlosen Adapter stets\l"
	.string "angeschlossen zu lassen!$"

Help_Text_DescGameFundamentals1::
	.string "Statte jeder Stadt einen Besuch\n"
	.string "ab. Begib dich auf jede Straße.\l"
	.string "Erforsche jede Höhle und stelle\l"
	.string "dich jeder Herausforderung, um\l"
	.string "der beste POKéMON TRAINER\l"
	.string "zu werden.$"

Help_Text_DescGameFundamentals2::
	.string "Auf deinem Abenteuer stößt du auf\n"
	.string "zahlreiche Hindernisse. Aber sie \l"
	.string "alle können überwunden\l"
	.string "werden. Manche Hindernisse lassen\l"
	.string "sich durch etwas, das weit weg\l"
	.string "geschieht, überwinden.$"

Help_Text_DescGameFundamentals3::
	.string "Einige der Hindernisse können\n"
	.string "von POKéMON entfernt werden,\l"
	.string "wenn sie eine spezielle\l"
	.string "Attacke erlernt haben.$"

Help_Text_DescWhatArePokemon::
	.string "POKéMON sind Lebewesen, um\n"
	.string "die sich noch viele Geheimnisse\l"
	.string "ranken. Du kannst sie im Gras,\l"
	.string "im Wasser und in Höhlen treffen.\l"
	.string "Es scheint, dass sie den\l"
	.string "Anweisungen des TRAINERs,\l"
	.string "der sie gefangen hat, gehorchen.$"

Help_Text_UsingTypeMatchupList::
	.string "Elementklassen-Liste benutzen$"

Help_Text_OwnMoveDark::
	.string "Eigene Attacke ist: UNLICHT$"

Help_Text_OwnPokemonDark::
	.string "Eigenes POKéMON ist: UNLICHT$"

Help_Text_OwnMoveRock::
	.string "Eigene Attacke ist: GESTEIN$"

Help_Text_OwnPokemonRock::
	.string "Eigenes POKéMON ist: GESTEIN$"

Help_Text_OwnMovePsychic::
	.string "Eigene Attacke ist: PSYCHO$"

Help_Text_OwnPokemonPsychic::
	.string "Eigenes POKéMON ist: PSYCHO$"

Help_Text_OwnMoveFighting::
	.string "Eigene Attacke ist: KAMPF$"

Help_Text_OwnPokemonFighting::
	.string "Eigenes POKéMON ist: KAMPF$"

Help_Text_OwnMoveGrass::
	.string "Eigene Attacke ist: PFLANZE$"

Help_Text_OwnPokemonGrass::
	.string "Eigenes POKéMON ist: PFLANZE$"

Help_Text_OwnMoveGhost::
	.string "Eigene Attacke ist: GEIST$"

Help_Text_OwnPokemonGhost::
	.string "Eigenes POKéMON ist: GEIST$"

Help_Text_OwnMoveIce::
	.string "Eigene Attacke ist: EIS$"

Help_Text_OwnPokemonIce::
	.string "Eigenes POKéMON ist: EIS$"

Help_Text_OwnMoveGround::
	.string "Eigene Attacke ist: BODEN$"

Help_Text_OwnPokemonGround::
	.string "Eigenes POKéMON ist: BODEN$"

Help_Text_OwnMoveElectric::
	.string "Eigene Attacke ist: ELEKTRO$"

Help_Text_OwnPokemonElectric::
	.string "Eigenes POKéMON ist: ELEKTRO$"

Help_Text_OwnMovePoison::
	.string "Eigene Attacke ist: GIFT$"

Help_Text_OwnPokemonPoison::
	.string "Eigenes POKéMON ist: GIFT$"

Help_Text_OwnMoveDragon::
	.string "Eigene Attacke ist: DRACHE$"

Help_Text_OwnPokemonDragon::
	.string "Eigenes POKéMON ist: DRACHE$"

Help_Text_OwnMoveNormal::
	.string "Eigene Attacke ist: NORMAL$"

Help_Text_OwnPokemonNormal::
	.string "Eigenes POKéMON ist: NORMAL$"

Help_Text_OwnMoveSteel::
	.string "Eigene Attacke ist: STAHL$"

Help_Text_OwnPokemonSteel::
	.string "Eigenes POKéMON ist: STAHL$"

Help_Text_OwnMoveFlying::
	.string "Eigene Attacke ist: FLUG$"

Help_Text_OwnPokemonFlying::
	.string "Eigenes POKéMON ist: FLUG$"

Help_Text_OwnMoveFire::
	.string "Eigene Attacke ist: FEUER$"

Help_Text_OwnPokemonFire::
	.string "Eigenes POKéMON ist: FEUER$"

Help_Text_OwnMoveWater::
	.string "Eigene Attacke ist: WASSER$"

Help_Text_OwnPokemonWater::
	.string "Eigenes POKéMON ist: WASSER$"

Help_Text_OwnMoveBug::
	.string "Eigene Attacke ist: KÄFER$"

Help_Text_OwnPokemonBug::
	.string "Eigenes POKéMON ist: KÄFER$"

Help_Text_HowToUseTypeMatchupList::
	.string "Die Effektivität einer Att. hängt von\n"
	.string "der Elementkl. der Att. und des\l"
	.string "PKMN, das sie benutzt, ab!\l"
	.string "{CIRCLE_DOT}: sehr effektiv\l"
	.string "{TRIANGLE}: nicht sehr effektiv\l"
	.string "{BIG_MULT_X}: Keine Auswirkung\l"
	.string "(Keine Änderung bei and. Elementkl.!)$"

Help_Text_TypeMatchupOwnMoveDark::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{CIRCLE_DOT}: PSYCHO, GEIST\p"
	.string "{TRIANGLE}: KAMPF, UNLICHT, STAHL$"

Help_Text_TypeMatchupOwnPokemonDark::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: KAMPF, KÄFER\p"
	.string "{TRIANGLE}: GEIST, UNLICHT\p"
	.string "{BIG_MULT_X}: PSYCHO$"

Help_Text_TypeMatchupOwnMoveRock::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{CIRCLE_DOT}: FEUER, EIS, FLUG, KÄFER\p"
	.string "{TRIANGLE}: KAMPF, BODEN, STAHL$"

Help_Text_TypeMatchupOwnPokemonRock::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: WASSER, PFLANZE, KAMPF\n"
	.string "BODEN, STAHL\p"
	.string "{TRIANGLE}: NORMAL, FEUER, GIFT, FLUG$"

Help_Text_TypeMatchupOwnMovePsychic::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{CIRCLE_DOT}: KAMPF, GIFT\p"
	.string "{TRIANGLE}: PSYCHO, STAHL\p"
	.string "{BIG_MULT_X}: UNLICHT$"

Help_Text_TypeMatchupOwnPokemonPsychic::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: KÄFER, GEIST, UNLICHT\p"
	.string "{TRIANGLE}: KAMPF, PSYCHO$"

Help_Text_TypeMatchupOwnMoveFighting::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{CIRCLE_DOT}: NORMAL, EIS, GESTEIN,\n"
	.string "UNLICHT, STAHL\p"
	.string "{TRIANGLE}: GIFT, FLUG, PSYCHO, KÄFER\p"
	.string "{BIG_MULT_X}: GEIST$"

Help_Text_TypeMatchupOwnPokemonFighting::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: FLUG, PSYCHO\p"
	.string "{TRIANGLE}: KÄFER, GESTEIN, UNLICHT$"

Help_Text_TypeMatchupOwnMoveGrass::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{CIRCLE_DOT}: WASSER, BODEN, GESTEIN\p"
	.string "{TRIANGLE}: FEUER, PFLANZE, GIFT, FLUG,\n"
	.string "KÄFER, DRACHEN, STAHL$"

Help_Text_TypeMatchupOwnPokemonGrass::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: FEUER, EIS, GIFT, FLUG, KÄFER\p"
	.string "{TRIANGLE}: WASSER, ELEKTRO, PFLANZE, \n"
	.string "BODEN$"

Help_Text_TypeMatchupOwnMoveGhost::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{CIRCLE_DOT}: PSYCHO, GEIST\p"
	.string "{TRIANGLE}: UNLICHT, STAHL\p"
	.string "{BIG_MULT_X}: NORMAL$"

Help_Text_TypeMatchupOwnPokemonGhost::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: GEIST, UNLICHT\p"
	.string "{TRIANGLE}: GIFT, KÄFER\p"
	.string "{BIG_MULT_X}: NORMAL, KAMPF$"

Help_Text_TypeMatchupOwnMoveIce::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{CIRCLE_DOT}: PFLANZE, BODEN, FLUG, DRACHEN\p"
	.string "{TRIANGLE}: FEUER, WASSER, EIS, STAHL$"

Help_Text_TypeMatchupOwnPokemonIce::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: FEUER, KAMPF, GESTEIN, STAHL\p"
	.string "{TRIANGLE}: EIS$"

Help_Text_TypeMatchupOwnMoveGround::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{CIRCLE_DOT}: FEUER, ELEKTRO, GIFT,\n"
	.string "GESTEIN, STAHL\p"
	.string "{TRIANGLE}: PFLANZE, KÄFER\n"
	.string "{BIG_MULT_X}: FLUG$"

Help_Text_TypeMatchupOwnPokemonGround::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: WASSER, PFLANZE, EIS\p"
	.string "{TRIANGLE}: GIFT, GESTEIN\p"
	.string "{BIG_MULT_X}: ELEKTRO$"

Help_Text_TypeMatchupOwnMoveElectric::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{CIRCLE_DOT}: WASSER, FLUG\p"
	.string "{TRIANGLE}: ELEKTRO, PFLANZE, DRACHEN\p"
	.string "{BIG_MULT_X}: BODEN$"

Help_Text_TypeMatchupOwnPokemonElectric::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: BODEN\p"
	.string "{TRIANGLE}: ELEKTRO, FLUG, STAHL$"

Help_Text_TypeMatchupOwnMovePoison::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{CIRCLE_DOT}: PFLANZE\p"
	.string "{TRIANGLE}: GIFT, BODEN, GESTEIN, GEIST\p"
	.string "{BIG_MULT_X}: STAHL$"

Help_Text_TypeMatchupOwnPokemonPoison::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: BODEN, PSYCHO\p"
	.string "{TRIANGLE}: PFLANZE, KAMPF, GIFT, KÄFER$"

Help_Text_TypeMatchupOwnMoveDragon::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{CIRCLE_DOT}: DRACHEN\p"
	.string "{TRIANGLE}: STAHL$"

Help_Text_TypeMatchupOwnPokemonDragon::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: EIS, DRACHEN\p"
	.string "{TRIANGLE}: FEUER, WASSER, ELEKTRO, \n"
	.string "PFLANZE$"

Help_Text_TypeMatchupOwnMoveNormal::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{TRIANGLE}: GESTEIN, STAHL\p"
	.string "{BIG_MULT_X}: GEIST$"

Help_Text_TypeMatchupOwnPokemonNormal::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: KAMPF\p"
	.string "{BIG_MULT_X}: GEIST$"

Help_Text_TypeMatchupOwnMoveSteel::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{CIRCLE_DOT}: EIS, GESTEIN\p"
	.string "{TRIANGLE}: FEUER, WASSER, ELEKTRO, STAHL$"

Help_Text_TypeMatchupOwnPokemonSteel::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: FEUER, KAMPF, GESTEIN\n"
	.string "{TRIANGLE}: NORMAL, PFLANZE, EIS, FLUG,\l"
	.string "PSYCHO, KÄFER, GESTEIN, GEIST,\l"
	.string "DRACHEN, UNLICHT, STAHL\l"
	.string "{BIG_MULT_X}: GIFT$"

Help_Text_TypeMatchupOwnMoveFlying::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{CIRCLE_DOT}: PFLANZE, KAMPF, KÄFER\p"
	.string "{TRIANGLE}: ELEKTRO, GESTEIN, STAHL$"

Help_Text_TypeMatchupOwnPokemonFlying::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: ELEKTRO, EIS, GESTEIN\p"
	.string "{TRIANGLE}: PFLANZE, KAMPF, KÄFER\p"
	.string "{BIG_MULT_X}: BODEN$"

Help_Text_TypeMatchupOwnMoveFire::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{CIRCLE_DOT}: PFLANZE, EIS, KÄFER, STAHL\p"
	.string "{CIRCLE_DOT}: FEUER, WASSER, GESTEIN,\n"
	.string "DRACHEN$"

Help_Text_TypeMatchupOwnPokemonFire::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: WASSER, BODEN, GESTEIN\p"
	.string "{TRIANGLE}: FEUER, PFLANZE, EIS, KÄFER,\n"
	.string "STAHL$"

Help_Text_TypeMatchupOwnMoveWater::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{CIRCLE_DOT}: FEUER, BODEN, GESTEIN\p"
	.string "{TRIANGLE}: WASSER, PFLANZE, DRACHEN$"

Help_Text_TypeMatchupOwnPokemonWater::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: ELEKTRO, PFLANZE\p"
	.string "{TRIANGLE}: FEUER, WASSER, EIS, STAHL$"

Help_Text_TypeMatchupOwnMoveBug::
	.string "Wirkung auf das geg. POKéMON:\p"
	.string "{CIRCLE_DOT}: PFLANZE, PSYCHO, UNLICHT\p"
	.string "{TRIANGLE}: FEUER, KAMPF, GIFT, FLUG,\n"
	.string "GEIST, STAHL$"

Help_Text_TypeMatchupOwnPokemonBug::
	.string "Wirkung der gegnerischen Attacke\n"
	.string "auf eigenes PKMN:\p"
	.string "{CIRCLE_DOT}: FEUER, FLUG, GESTEIN\p"
	.string "{TRIANGLE}: PFLANZE, KAMPF, BODEN$"
