gOtherText_NewName::
	.string "NEUER NAME$"

gNameChoice_Green::
	.string "GRÜN$"

gNameChoice_Red::
	.string "ROT$"

gNameChoice_Leaf::
	.string "BLATT$"

gNameChoice_Fire::
	.string "FEUER$"

gNameChoice_Gary::
	.string "GARY$"

gNameChoice_Kaz::
	.string "HUGO$"

gNameChoice_Toru::
	.string "MICHAEL$"

gNameChoice_Ash::
	.string "SVEN$"

gNameChoice_Kene::
	.string "GERD$"

gNameChoice_Geki::
	.string "HANS$"

gNameChoice_Jak::
	.string "JACK$"

gNameChoice_Janne::
	.string "JAN$"

gNameChoice_Jonn::
	.string "JOHN$"

gNameChoice_Kamon::
	.string "DANIEL$"

gNameChoice_Karl::
	.string "HELGE$"

gNameChoice_Taylor::
	.string "ULI$"

gNameChoice_Oscar::
	.string "TOBI$"

gNameChoice_Hiro::
	.string "UDO$"

gNameChoice_Max::
	.string "BERT$"

gNameChoice_Jon::
	.string "JON$"

gNameChoice_Ralph::
	.string "RALF$"

gNameChoice_Kay::
	.string "UWE$"

gNameChoice_Tosh::
	.string "CHRIS$"

gNameChoice_Roak::
	.string "ROLF$"

gNameChoice_Omi::
	.string "MANDY$"

gNameChoice_Jodi::
	.string "ANDREA$"

gNameChoice_Amanda::
	.string "SINA$"

gNameChoice_Hillary::
	.string "MARTINA$"

gNameChoice_Makey::
	.string "TANJA$"

gNameChoice_Michi::
	.string "ELENA$"

gNameChoice_Paula::
	.string "BIRGIT$"

gNameChoice_June::
	.string "DIANA$"

gNameChoice_Cassie::
	.string "KATRIN$"

gNameChoice_Rey::
	.string "SUSI$"

gNameChoice_Seda::
	.string "UTE$"

gNameChoice_Kiko::
	.string "DANIELA$"

gNameChoice_Mina::
	.string "SILKE$"

gNameChoice_Norie::
	.string "SIMONE$"

gNameChoice_Sai::
	.string "JAMIE$"

gNameChoice_Momo::
	.string "PIA$"

gNameChoice_Suzi::
	.string "EVA$"

gControlsGuide_Text_Intro::
	.string "Die Knöpfe und Tasten werden\n"
	.string "ihrer Wichtigkeit nach erklärt.$"

gControlsGuide_Text_DPad::
	.string "Bewegt Protagonisten. Wird auch\n"
	.string "bei der Auswahl der \n"
	.string "Datenüberschriften verwendet.$"

gControlsGuide_Text_AButton::
	.string "Bestätigt Auswahl, überprüft\n"
	.string "Dinge, Dialoge, scrollt Text.$"

gControlsGuide_Text_BButton::
	.string "Beendet eine Aktion, widerruft\n"
	.string "eine Auswahl.$"

gControlsGuide_Text_StartButton::
	.string "Drücke START, um das MENÜ\n"
	.string "aufzurufen!$"

gControlsGuide_Text_SelectButton::
	.string "Items bewegen und SELECT\n"
	.string "zugewiesene Items benutzen.$"

gControlsGuide_Text_LRButtons::
	.string "Brauchst du Hilfe beim Spiel o.\n"
	.string "wie du etwas anstellen sollst,\n"
	.string "drücke die L- bzw. die R-Taste.$"

gOakSpeech_Text_AskPlayerGender::
	.string "Verrätst du mir, ob du ein\n"
	.string "Junge oder ein Mädchen bist?$"

gPikachuIntro_Text_Page1::
	.string "Die Welt, in die du jetzt gelangst,\n"
	.string "wird dir ein Abenteuer bescheren,\n"
	.string "in dem du der Held bist.\n"
	.string "Rede mit den Leuten und überprüfe\n"
	.string "Dinge, wo immer du bist, in\n"
	.string "Städten, auf Straßen oder in\n"
	.string "Höhlen. Sammle überall\n"
	.string "Informationen.$"

gPikachuIntro_Text_Page2::
	.string "Neue Wege werden sich auftun,\n"
	.string "indem du Menschen in Not hilfst,\n"
	.string "Herausforderungen meisterst und\n"
	.string "Rätsel löst.\n"
	.string "Manchmal wirst du von anderen\n"
	.string "herausgefordert und von wilden\n"
	.string "Geschöpfen angegriffen. Sei\n"
	.string "tapfer und lass dich nicht beirren!$"

gPikachuIntro_Text_Page3::
	.string "Während deines Abenteuers\n"
	.string "interagierst du hoffentlich mit\n"
	.string "allen möglichen Personen, um\n"
	.string "deinen Charakter zu festigen.\n"
	.string "Das ist unser Hauptziel.\n"
	.string "Drücke den A-Knopf, um das\n"
	.string "Abenteuer zu beginnen!$"

gOakSpeech_Text_WelcomeToTheWorld::
	.string "Hallo!\p"
	.string "Herzlich willkommen in der Welt der\n"
	.string "POKéMON!\p"
	.string "Mein Name ist EICH!\p"
	.string "Man nennt mich den POKéMON-\n"
	.string "PROFESSOR!\p"
	.string "$"

gOakSpeech_Text_ThisWorld::
	.string "Diese Welt wird von Wesen bewohnt,\n"
	.string "$"

gOakSpeech_Text_IsInhabitedFarAndWide::
	.string "die man POKéMON nennt!\p"
	.string "\n"
	.string "$"

gOakSpeech_Text_IStudyPokemon::
	.string "Für manche Leute sind POKéMON\n"
	.string "Haustiere, andere tragen Kämpfe mit\l"
	.string "ihnen aus.\p"
	.string "Ich selbst...\p"
	.string "... habe mein Hobby zum Beruf\n"
	.string "gemacht und studiere POKéMON.\p"
	.string "$"

gOakSpeech_Text_TellMeALittleAboutYourself::
	.string "Zunächst solltest du mir etwas\n"
	.string "von dir erzählen!\p"
	.string "$"

gOakSpeech_Text_YourNameWhatIsIt::
	.string "Wie lautet dein Name?\p"
	.string "\n"
	.string "$"

gOakSpeech_Text_SoYourNameIsPlayer::
	.string "Genau…\n"
	.string "Dein Name ist also {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
	.string "Dies ist mein Enkel.\p"
	.string "Von jeher wollt ihr einander\n"
	.string "übertrumpfen!\p"
	.string "Hmm, wie war noch gleich sein\n"
	.string "Name?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
	.string "Wie war der Name deines Rivalen\n"
	.string "gleich noch?$"

gOakSpeech_Text_ConfirmRivalName::
	.string "… ah, war es {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
	.string "{RIVAL}! Stimmt!\n"
	.string "Es lag mir auf der Zunge!\p"
	.string "$"

gOakSpeech_Text_LetsGo::
	.string "{PLAYER}!\p"
	.string "Eine unglaubliche Reise in die Welt\n"
	.string "der POKéMON erwartet dich!\p"
	.string "Eine Welt voller Wunder, Abenteuer\n"
	.string "und Geheimnisse! Kurz gesagt, ein\l"
	.string "Traum wird wahr!$"
