Text_ObtainedTheX::
	.string "{STR_VAR_2} erhalten!$"

Text_BagIsFull::
	.string "Der BEUTEL ist voll...$"

Text_PutItemAway::
	.string "{PLAYER} packt {STR_VAR_2} in\n"
	.string "{STR_VAR_3}.$"

Text_FoundOneItem::
	.string "{PLAYER} hat {STR_VAR_2}\n"
	.string "gefunden!$"

Text_TooBadBagFull::
	.string "Zu schade!\n"
	.string "Der BEUTEL ist voll...$"

Text_FoundXCoins::
	.string "{PLAYER} findet\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

Text_PutCoinsAwayInCoinCase::
	.string "{PLAYER} legt die MÜNZEN in den\n"
	.string "MÜNZKORB.$"

Text_CoinCaseIsFull::
	.string "Dein MÜNZKORB ist voll.$"

Text_NothingToPutThemIn::
	.string "Schade! Es gibt nichts,\n"
	.string "wo sie aufbewahrt werden können!$"

Text_FoundXItems::
	.string "{PLAYER} hat {STR_VAR_1}-mal\n"
	.string "{STR_VAR_2} gefunden!$"

Text_ObtainedTheDecor::
	.string "{STR_VAR_2} erhalten!$"

Text_NoRoomForAnotherDecor::
	.string "Zu schade! Es ist kein Platz für\n"
	.string "{STR_VAR_2}...$"

Text_DecorTransferredToPC::
	.string "{STR_VAR_2} wurde auf den PC\n"
	.string "übertragen.$"
