Text_BootedUpPC::
	.string "{PLAYER} schaltet den PC ein.$"

Text_AccessWhichPC::
	.string "Zugriff auf wessen PC?$"

Text_AccessedSomeonesPC::
	.string "Verbindung zu JEMANDES PC\n"
	.string "hergestellt.$"

Text_OpenedPkmnStorage::
	.string "POKéMON-Lagerungs-System geöffnet.$"

Text_AccessedPlayersPC::
	.string "Verbindung mit PC von {PLAYER}.$"

Text_AccessedBillsPC::
	.string "Verbindung zu BILLs PC\n"
	.string "hergestellt.$"
