Text_MonSentToBoxInSomeonesPC::
	.string "{STR_VAR_2} wurde auf JEMANDES PC\n"
	.string "übertragen.\p"
	.string "Es wurde in BOX\n"
	.string "“{STR_VAR_1}” abgelegt.$"

Text_MonSentToBoxInBillsPC::
	.string "{STR_VAR_2} wurde auf BILLs PC\n"
	.string "übertragen.\p"
	.string "Es wurde in BOX\n"
	.string "“{STR_VAR_1}” abgelegt.$"

Text_MonSentToBoxSomeonesBoxFull::
	.string "BOX “{STR_VAR_3}” in\n"
	.string "JEMANDES PC ist voll.\p"
	.string "{STR_VAR_2} wurde in BOX\n"
	.string "“{STR_VAR_1}” übertragen.$"

Text_MonSentToBoxBillsBoxFull::
	.string "BOX “{STR_VAR_3}” in\n"
	.string "BILLs PC ist voll.\p"
	.string "{STR_VAR_2} wurde in BOX\n"
	.string "“{STR_VAR_1}” übertragen.$"

Text_PlayerObtainedTheMon::
	.string "{PLAYER} erhält das {STR_VAR_1}!$"

@ Unused. Translated below
@ You cannot carry any more Pokemon, so {STR_VAR_2} was sent to PC Box {STR_VAR_1}!
Text_MonSentToBoxInPC::
	.string "ポケモンを　もちきれないので\n"
	.string "パソコンの　ボックス“{STR_VAR_1}”　に\l"
	.string "{STR_VAR_2}を　てんそうした！$"

Text_NoMoreRoomForPokemon::
	.string "Es ist kein Platz mehr für POKéMON\n"
	.string "vorhanden!\p"
	.string "Die POKéMON BOXEN sind voll und\n"
	.string "es kann kein POKéMON mehr\l"
	.string "abgelegt werden!$"
