PokedexRating_Text_HowIsPokedexComingAlong::
	.string "PROF. EICH: Ich freue mich, dich\n"
	.string "zu sehen! Was macht dein POKéDEX?\p"
	.string "Zeig ihn mir!$"

PokedexRating_Text_SeenXOwnedY::
	.string "In deinem POKéDEX steht:\p"
	.string "Gesehen: {STR_VAR_1} POKéMON\n"
	.string "  Besitz: {STR_VAR_2} POKéMON\p"
	.string "PROF. EICHs Bewertung:$"

PokedexRating_Text_LessThan10::
	.string "Du hast noch eine Menge Arbeit vor\n"
	.string "dir.\p"
	.string "Suche in hohem Gras nach POKéMON!$"

PokedexRating_Text_LessThan20::
	.string "Das sieht schon ganz gut aus!\p"
	.string "Hole dir bei meinem ASSISTENTEN\n"
	.string "die VM BLITZ ab!$"

PokedexRating_Text_LessThan30::
	.string "Du benötigst noch weitere!\p"
	.string "Fange also die verschiedensten\n"
	.string "POKéMON!$"

PokedexRating_Text_LessThan40::
	.string "Sehr gut!\n"
	.string "Du gibst dir sehr viel Mühe!\p"
	.string "Hole dir bei meinem ASSISTENTEN\n"
	.string "einen DETEKTOR ab!$"

PokedexRating_Text_LessThan50::
	.string "Dein POKéDEX macht gute\n"
	.string "Fortschritte!\p"
	.string "Ich habe einem meiner\n"
	.string "ASSISTENTEN ein MÜNZAMULETT\l"
	.string "gegeben. Hol es dir!$"

PokedexRating_Text_LessThan60::
	.string "Ah, nun hast du mehr als 50!\p"
	.string "Ich habe einem meiner\n"
	.string "ASSISTENTEN einen EP-TEILER\l"
	.string "gegeben. Hol in dir!$"

PokedexRating_Text_LessThan70::
	.string "Heh!\n"
	.string "Es wird immer besser!$"

PokedexRating_Text_LessThan80::
	.string "Fantastisch!\p"
	.string "Du solltest dir WASSER-POKéMON\n"
	.string "angeln!$"

PokedexRating_Text_LessThan90::
	.string "Wundervoll! Du bist ein\n"
	.string "leidenschaftlicher Sammler!$"

PokedexRating_Text_LessThan100::
	.string "Ich bin wirklich beeindruckt!\n"
	.string "Das war sicher eine Menge Arbeit!$"

PokedexRating_Text_LessThan110::
	.string "Du hast bereits 100 verschiedene\n"
	.string "POKéMON! Du leistest hervorragende\l"
	.string "Arbeit!$"

PokedexRating_Text_LessThan120::
	.string "Super! Einige deiner POKéMON haben\n"
	.string "sich sogar entwickelt!$"

PokedexRating_Text_LessThan130::
	.string "Ausgezeichnet! Tausche POKéMON mit\n"
	.string "Freunden, um weitere zu erhalten!$"

PokedexRating_Text_LessThan140::
	.string "Überragend! Du hast dich zu einem\n"
	.string "echten Profi gemausert!$"

PokedexRating_Text_LessThan150::
	.string "Ich bin sprachlos!\p"
	.string "Von nun an giltst du als Autorität\n"
	.string "für POKéMON!$"

PokedexRating_Text_Complete::
	.string "Dein POKéDEX ist komplett\n"
	.string "fertig gestellt!\l"
	.string "Herzlichen Glückwunsch!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "In deinem NATIONALEN POKéDEX\n"
	.string "steht:\p"
	.string "Gesehen: {STR_VAR_1} POKéMON\n"
	.string "Besitz: {STR_VAR_2} POKéMON.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "Ich bin gespannt, ob du den\n"
	.string "NATIONALEN POKéDEX füllen kannst.$"

PokedexRating_Text_YouveCompletedDex::
	.string "Endlich…\p"
	.string "Dein POKéDEX ist komplett!\p"
	.string "Das ist traumhaft!\n"
	.string "Wirklich fantastisch!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Woahhh!$"

PokedexRating_Text_HaHa::
	.string "はあ はあ‥$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Danke, {PLAYER}!\n"
	.string "Meinen aufrichtigen Dank!\l"
	.string "Du hast meinen Traum erfüllt.$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "EICH: Ah, willkommen!\p"
	.string "Wie ist es um deinen POKéDEX\n"
	.string "bestellt?\p"
	.string "Wow!\p"
	.string "Ich weiß es natürlich, aber ich\n"
	.string "liebe es trotzdem!\p"
	.string "Zeig ihn mir…$"
