Text_CardKeyOpenedDoor::
	.string "Bingo!\n"
	.string "Der TÜRÖFFNER hat die Tür\l"
	.string "entriegelt!$"

Text_ItNeedsCardKey::
	.string "Mist! Die Tür geht nur mit dem\n"
	.string "TÜRÖFFNER auf!$"

Text_AccessedProfOaksPC::
	.string "Die Verbindung zu PROF. EICHs PC\n"
	.string "wurde hergestellt.\p"
	.string "Du hast Zugriff auf die POKéDEX-\n"
	.string "BEWERTUNG.$"

Text_HavePokedexRated::
	.string "Soll dein POKéDEX bewertet werden?$"

Text_ClosedLinkToProfOaksPC::
	.string "Die Verbindung zu PROF. EICHs PC\n"
	.string "wurde getrennt.$"

Text_VoiceRangOutDontRunAway::
	.string "EINE STIMME: Lauf nicht davon!$"

@ Uncear what the below unused JP texts were for
Text_IdLikeToSeeRequest::
	.string "えっとー\n"
	.string "{STR_VAR_2}が　みてみたいなー\p"
	.string "それも　{STR_VAR_1}{STR_VAR_3}\n"
	.string "{STR_VAR_2}が　みてみたいなー$"

Text_ThankYouForShowingMe::
	.string "わぁー　すごい！\n"
	.string "{STR_VAR_1}{STR_VAR_3}{STR_VAR_2}だー！\p"
	.string "ありがとー\n"
	.string "また　よろしくねー！$"

Text_ThatsNotRight::
	.string "それっ　ちがうよー！$"

Text_ISee::
	.string "そっか‥$"

Text_TheDoorIsClosed::
	.string "ドアは　しまっている‥$"

Text_TheDoorIsOpen::
	.string "Die Türe ist offen…$"
