@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight::
	.string "Hmm…\nIst das richtig…$"

PalletTown_Text_OhLookLook::
	.string "Oh!\nSieh nur!$"

PalletTown_Text_ReadItReadIt::
	.string "Lies es! Lies es!$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu::
	.string "Drücke START, um das MENÜ\n"
	.string "aufzurufen!$"

PalletTown_Text_SignsAreUsefulArentThey::
	.string "Schilder sind hilfreich, nicht?$"

PalletTown_Text_LookCopiedTrainerTipsSign::
	.string "Sieh nur!\p"
	.string "Ich habe das, was auf einem dieser\n"
	.string "TIPPS für TRAINER-Schilder\l"
	.string "steht, abgeschrieben!$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy::
	.string "Drücke START, um das MENÜ\naufzurufen!$"
