VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "Die Batterie ist nicht genügend\n"
	.string "aufgeladen.\l"
	.string "Anzahl der nötigen Schritte, um\l"
	.string "die Batterie vollständig\l"
	.string "aufzuladen: {STR_VAR_1}{PAUSE_UNTIL_PRESS}!$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "Es gibt in der Reichweite keine\n"
	.string "TRAINER, die kämpfen können…\l"
	.string "Der KAMPFFAHNDER wurde\l"
	.string "abgeschaltet.{PAUSE_UNTIL_PRESS}.$"

VSSeeker_Text_TrainersNotReady::
	.string "Es scheint, dass die anderen\n"
	.string "TRAINER nicht zum Kampf\l"
	.string "bereit sind.\l"
	.string "Warte noch ein wenig!{PAUSE_UNTIL_PRESS}$"

Route3_Text_ColtonRematchIntro::
	.string "Heh! Ich kenne dich aus dem\n"
	.string "VERTANIA-WALD!$"

Route3_Text_BenRematchIntro::
	.string "Überall sind Brennnesseln! Und ich\n"
	.string "trage Shorts! So ein MIST!$"

Route3_Text_JaniceRematchIntro::
	.string "Was starrst du mich so an?$"

Route3_Text_GregRematchIntro::
	.string "Bist du auch ein TRAINER?\n"
	.string "Lass uns kämpfen!$"

Route3_Text_SallyRematchIntro::
	.string "Warum schaust du mich so fasziniert\n"
	.string "an?$"

Route3_Text_CalvinRematchIntro::
	.string "Hehe! Ich habe meinem Bruder\n"
	.string "gesagt, er soll Shorts anziehen!$"

Route3_Text_JamesRematchIntro::
	.string "Ich setzte beim Kampf gegen dich\n"
	.string "die POKéMON ein, die ich\l"
	.string "von Grund auf trainiert habe.$"

Route3_Text_RobinRematchIntro::
	.string "Iiih!\n"
	.string "Hast du mich gestoßen?$"

Route4_Text_CrissyRematchIntro::
	.string "Ich fange immer Pilz-POKéMON\n"
	.string "am MONDBERG.$"

Route6_Text_RickyRematchIntro::
	.string "Oh! Du bist dieses neugierige Kind,\n"
	.string "das uns belauscht hat.$"

Route6_Text_NancyRematchIntro::
	.string "Entschuldigung! Hatte ich dir nicht\n"
	.string "gesagt, dass dies ein\l"
	.string "Privatgespräch ist?\l"
	.string "Du solltest uns nicht belauschen,\l"
	.string "das gehört sich nicht!$"

Route6_Text_KeigoRematchIntro::
	.string "Ich suche nach etwas Gutem,\n"
	.string "das kein KÄFER-POKéMON\l"
	.string "ist, aber…$"

Route6_Text_JeffRematchIntro::
	.string "Häh!\n"
	.string "Du möchtest erneut mit mir kommen?$"

Route6_Text_IsabelleRematchIntro::
	.string "Kämpfen? Meinst du mich?\n"
	.string "Na gut!$"

Route6_Text_ElijahRematchIntro::
	.string "Heh, lange nicht gesehen!\n"
	.string "Geht es dir besser?$"

Route8_Text_AidanRematchIntro::
	.string "Du weißt viel über POKéMON!\n"
	.string "Doch wie sieht es mit Chemie aus?$"

Route8_Text_StanRematchIntro::
	.string "O.K.!\n"
	.string "Die Spiele mögen beginnen!$"

Route8_Text_GlennRematchIntro::
	.string "Um zu gewinnen, benötigst du eine\n"
	.string "gute Strategie!\p"
	.string "Befolgst du meinen Rat?$"

Route8_Text_PaigeRematchIntro::
	.string "Ich habe viele NIDORAN gefangen!\n"
	.string "Ich möchte nicht, dass sie sich\l"
	.string "entwickeln, aber…$"

Route8_Text_LeslieRematchIntro::
	.string "Die Schule macht Spaß! POKéMON zu\n"
	.string "trainieren aber auch!$"

Route8_Text_AndreaRematchIntro::
	.string "MAUZI ist so süß!\n"
	.string "Miau, miauz!$"

Route8_Text_MeganRematchIntro::
	.string "Es mag dämlich aussehen, wie wir\n"
	.string "hier herumstehen, aber ich kann\l"
	.string "dennoch kämpfen!$"

Route8_Text_RichRematchIntro::
	.string "Ich bin ein weit herumgekommener\n"
	.string "Glücksspieler!$"

Route8_Text_JuliaRematchIntro::
	.string "Welches POKéMON ist süß, pummelig\n"
	.string "und kuschlig?$"

Route8_Text_RicardoRematchIntro::
	.string "Mein Motorrad macht immer\n"
	.string "noch Mucken!$"

Route8_Text_JarenRematchIntro::
	.string "O.K., Kiddie!\n"
	.string "Dieses Mal bin ich nicht so gnädig!$"

Route8_Text_EliRematchIntro::
	.string "NORA: Zusammen sind wir jetzt\n"
	.string "noch stärker!$"

Route8_Text_AnneRematchIntro::
	.string "JO: Zwillinge sind doppelt stark!$"

Route9_Text_AliciaRematchIntro::
	.string "Kämpfen wir erneut?\n"
	.string "Dieses Mal bist du dran!$"

Route9_Text_ChrisRematchIntro::
	.string "Ich habe nicht vergessen, dass du\n"
	.string "mit diesen bezaubernden\l"
	.string "POKéMON unterwegs bist.$"

Route9_Text_DrewRematchIntro::
	.string "Ich gehe über den FELSTUNNEL\n"
	.string "nach LAVANDIA…\l"
	.string "Aber auf meinem Weg dorthin\l"
	.string "halten mich alle, denen ich\l"
	.string "begegne, auf…$"

Route9_Text_CaitlinRematchIntro::
	.string "Wage nicht, mich heute zu ärgern!\n"
	.string "Heute meinen wir es ernst!$"

Route9_Text_JeremyRematchIntro::
	.string "Endlich kommt jemand!\n"
	.string "Mir war richtig langweilig!$"

Route9_Text_BriceRematchIntro::
	.string "Du hast keine Chance, Kiddie!$"

Route9_Text_BrentRematchIntro::
	.string "Jeden Tag stehe ich auf, um meine\n"
	.string "POKéMON von klein auf zu\l"
	.string "trainieren!$"

Route9_Text_AlanRematchIntro::
	.string "Hahahaha!\n"
	.string "Dieses Mal werde ich gewinnen!$"

Route9_Text_ConnerRematchIntro::
	.string "Du hast keine Chance gegen meine\n"
	.string "KÄFER-POKéMON!$"

Route10_Text_MarkRematchIntro::
	.string "Wow, du bist zurück? Vielleicht\n"
	.string "bist du auch ein POKéMANIAC?\l"
	.string "Möchtest du meine Sammlung sehen?$"

Route10_Text_ClarkRematchIntro::
	.string "Ha-haha-hatschi!\n"
	.string "Ich kann nicht aufhören, zu niesen!$"

Route10_Text_HermanRematchIntro::
	.string "Hullo Kind!\n"
	.string "Habe ich dir schon meine POKéMON\l"
	.string "gezeigt?$"

Route10_Text_HeidiRematchIntro::
	.string "Ich bin erneut zu einer POKéMON-\n"
	.string "ARENA gegangen.$"

Route10_Text_TrentRematchIntro::
	.string "Ahh! Die Bergluft ist so wunderbar\n"
	.string "erfrischend! Ich muss einfach\l"
	.string "hier bleiben!$"

Route10_Text_CarolRematchIntro::
	.string "In meinem Kopf dreht sich schon\n"
	.string "alles. Ich bin zu lange gewandert…$"

Route11_Text_HugoRematchIntro::
	.string "Sieg, Niederlage oder Remis?\n"
	.string "Auf in den Rückkampf!$"

Route11_Text_JasperRematchIntro::
	.string "Wettkämpfe!\n"
	.string "Ich kann ihnen nicht widerstehen!$"

Route11_Text_EddieRematchIntro::
	.string "Du weißt Bescheid, oder?\n"
	.string "Los, aber wehe du mogelst!$"

Route11_Text_BraxtonRematchIntro::
	.string "Guten Tag!\p"
	.string "Vorsicht!\n"
	.string "Ich verlege hier immer noch Kabel!$"

Route11_Text_DillonRematchIntro::
	.string "Ich bin schon seit geraumer Zeit\n"
	.string "POKéMON TRAINER, also\l"
	.string "kann ich dich besiegen!$"

Route11_Text_DirkRematchIntro::
	.string "Haha!\n"
	.string "Bisher habe ich noch nie verloren!\p"
	.string "… und falls doch, hätte ich das\n"
	.string "längst vergessen!$"

Route11_Text_DarianRematchIntro::
	.string "Ich habe noch nie gewonnen…\p"
	.string "Vielleicht ist dies auch meine\n"
	.string "Bestimmung…$"

Route11_Text_YasuRematchIntro::
	.string "In meiner Klasse bin ich der Beste!\n"
	.string "Ich trainiere Tag und Nacht!$"

Route11_Text_BernieRematchIntro::
	.string "Nimm dich vor Hochspannung in\n"
	.string "Acht!$"

Route11_Text_DaveRematchIntro::
	.string "Meine POKéMON müssten bereit sein!\n"
	.string "Dieses Mal gewinne ich!$"

Route12_Text_NedRematchIntro::
	.string "Cool!\n"
	.string "Mir ist etwas ins Netz gegangen!\l"
	.string "Dieses Mal aber wirklich!$"

Route12_Text_ChipRematchIntro::
	.string "Endlich bist du da!\n"
	.string "Als Angler muss man geduldig sein!$"

Route12_Text_JustinRematchIntro::
	.string "Ich habe immer noch keinen\n"
	.string "MONDSTEIN finden können!\l"
	.string "Hast du einen?$"

Route12_Text_LucaRematchIntro::
	.string "Elektrizität war schon immer\n"
	.string "meine Stärke!\p"
	.string "Ich habe allerdings von\n"
	.string "WASSER-POKéMON keine Ahnung!$"

Route12_Text_HankRematchIntro::
	.string "Der ANGELKÖNIG gegen das POKéMON-\n"
	.string "KIND! Runde 2!$"

Route12_Text_ElliotRematchIntro::
	.string "Versteh mich nicht falsch…\n"
	.string "Ich liebe das Angeln, dennoch\l"
	.string "würde ich lieber arbeiten…\l"
	.string "… das Angeln aufzugeben ist\l"
	.string "schwer!$"

Route12_Text_AndrewRematchIntro::
	.string "Was ich fange?\p"
	.string "Das wirst du nie herausfinden, wenn\n"
	.string "du mich nicht schlägst.$"

Route12_Text_JesRematchIntro::
	.string "DENIZ: Gewinne ich heute, werde\n"
	.string "ich SIRA einen Antrag machen!$"

Route12_Text_GiaRematchIntro::
	.string "SIRA: Heh, DENIZ…\n"
	.string "Ich habe jetzt schon so lange\l"
	.string "gewartet.\l"
	.string "Falls wir heute gewinnen,\l"
	.string "werden wir heiraten!$"

Route13_Text_SebastianRematchIntro::
	.string "Meine Vogel-POKéMON\n"
	.string "erinnern sich an dich!$"

Route13_Text_SusieRematchIntro::
	.string "Ich wollte als Kind der beste\n"
	.string "TRAINER sein!$"

Route13_Text_ValerieRematchIntro::
	.string "Wow!\n"
	.string "Du hast noch mehr coole ORDEN!$"

Route13_Text_GwenRematchIntro::
	.string "Meine niedlichen POKéMON möchten\n"
	.string "dich erneut gern kennen lernen.$"

Route13_Text_AlmaRematchIntro::
	.string "Ich habe meine Ersparnisse\n"
	.string "zusammengekratzt und mehr\l"
	.string "CARBON gekauft.$"

Route13_Text_PerryRematchIntro::
	.string "Dieses Mal werde ich nicht\n"
	.string "verlieren! Ich bin unterwegs\l"
	.string "und habe Rückenwind…$"

Route13_Text_LolaRematchIntro::
	.string "Oh, du bist zurück!\p"
	.string "Natürlich trete ich erneut gegen\n"
	.string "dich an!$"

Route13_Text_SheilaRematchIntro::
	.string "Kannst du nicht einfach vergessen,\n"
	.string "dass du gegen mich gekämpft hast?$"

Route13_Text_JaredRematchIntro::
	.string "Was glotzt du so?$"

Route13_Text_RobertRematchIntro::
	.string "Meine Vogel-POKéMON begleiten\n"
	.string "mich immer!$"

Route14_Text_CarterRematchIntro::
	.string "Ich habe meinen POKéMON mit\n"
	.string "TMs gute Attacken beigebracht.$"

Route14_Text_MitchRematchIntro::
	.string "Meine Vogel-POKéMON sind dieses\n"
	.string "Mal noch besser vorbereitet!$"

Route14_Text_BeckRematchIntro::
	.string "Setzt du TMs bei POKéMON ein?\n"
	.string "Sie einfach nur zu besitzen, macht\l"
	.string "keinen Sinn!$"

Route14_Text_MarlonRematchIntro::
	.string "Hast du einem Vogel-POKéMON\n"
	.string "schon das FLIEGEN beigebracht?$"

Route14_Text_DonaldRematchIntro::
	.string "Die Legende der Illusionen mit\n"
	.string "Flügeln…\l"
	.string "Du hast davon gehört, oder?$"

Route14_Text_BennyRematchIntro::
	.string "Ich will nicht unbedingt, aber lass\n"
	.string "uns dennoch kämpfen!$"

Route14_Text_LukasRematchIntro::
	.string "Heh, ich kenne dich!\p"
	.string "Los, los! Lass uns kämpfen. Auf in\n"
	.string "den Kampf! Los!$"

Route14_Text_IsaacRematchIntro::
	.string "Du schon wieder? Schnauze und los!$"

Route14_Text_GeraldRematchIntro::
	.string "Wir kommen öfter her, weil es hier\n"
	.string "so unglaublich viel Platz gibt!$"

Route14_Text_MalikRematchIntro::
	.string "Ein POKéMON-KAMPF?\n"
	.string "Cool! Leg los, Kiddie!$"

Route14_Text_KiriRematchIntro::
	.string "BERTA: ENKE, ich hoffe, wir\n"
	.string "gewinnen!$"

Route14_Text_JanRematchIntro::
	.string "ENKE: BERTA, los!\n"
	.string "Dieses Mal gewinnen wir sicher!$"

Route15_Text_KindraRematchIntro::
	.string "Wunderbar! Ich werde mit den\n"
	.string "getauschten POKéMON\l"
	.string "weiterhin mein Glück versuchen.$"

Route15_Text_BeckyRematchIntro::
	.string "Du siehst lammfromm aus!\n"
	.string "Dann habe ich eine Chance!\p"
	.string "Einen Versuch habe ich noch!$"

Route15_Text_EdwinRematchIntro::
	.string "Vogel-POKéMON versammeln sich,\n"
	.string "wenn ich pfeife!\l"
	.string "Sie sind bewundernswert süß!$"

Route15_Text_ChesterRematchIntro::
	.string "Hmm? Meine Vögel erschaudern?\n"
	.string "Moment, du bist doch dieser\l"
	.string "TRAINER…$"

Route15_Text_GraceRematchIntro::
	.string "Du bist aber niedlich!\n"
	.string "Wie ein kleines, süßes POKéMON!\l"
	.string "Jetzt erinnere ich mich an dich!$"

Route15_Text_OliviaRematchIntro::
	.string "Ich trainiere POKéMON, weil ich\n"
	.string "alleine lebe!\p"
	.string "Das hat sich nicht geändert!$"

Route15_Text_ErnestRematchIntro::
	.string "Heh, Kind!\n"
	.string "Lass uns kämpfen!$"

Route15_Text_AlexRematchIntro::
	.string "Her mit deinen\n"
	.string "Moneten! Wenn du\l"
	.string "verlierst, gibst\l"
	.string "du mir dein Geld!$"

Route15_Text_CeliaRematchIntro::
	.string "POKéMON zu tauschen ist wirklich\n"
	.string "cool!$"

Route15_Text_YazminRematchIntro::
	.string "Möchtest du noch einmal mit\n"
	.string "meinen POKéMON spielen?$"

Route15_Text_MyaRematchIntro::
	.string "EVA: Hallo, wir treffen uns öfter,\n"
	.string "nicht wahr?\p"
	.string "Hilfst du mir erneut, meinen kleinen\n"
	.string "Bruder zu trainieren?$"

Route15_Text_RonRematchIntro::
	.string "SERGIO: Meine Schwester ist noch\n"
	.string "stärker geworden…$"

Route16_Text_LaoRematchIntro::
	.string "Was willst du?$"

Route16_Text_KojiRematchIntro::
	.string "Du besitzt ein schönes FAHRRAD!\n"
	.string "Her damit!$"

Route16_Text_LukeRematchIntro::
	.string "Komm lass uns spielen,\n"
	.string "Hasenfuß! Ich weiß jetzt\l"
	.string "mit dir umzugehen!$"

Route16_Text_HideoRematchIntro::
	.string "Heh, warte doch! Erst rufst du\n"
	.string "mich und dann haust du ab.$"

Route16_Text_CamronRematchIntro::
	.string "Ich habe Hunger und bin fies! Ich\n"
	.string "brauche jetzt wirklich einen\l"
	.string "Sandsack!$"

Route16_Text_RubenRematchIntro::
	.string "Heh, du!\n"
	.string "Wir werden uns jetzt amüsieren!$"

Route16_Text_JedRematchIntro::
	.string "UWE: Bist du hier, um unsere\n"
	.string "grenzenlose Liebe zu sehen?$"

Route16_Text_LeaRematchIntro::
	.string "LENA: Manchmal macht mir die\n"
	.string "Intensität unserer Liebe Angst!$"

Route17_Text_RaulRematchIntro::
	.string "Ich hab es dir doch schon gesagt!\n"
	.string "Es lohnt sich nicht, Kinder\l"
	.string "auszurauben!$"

Route17_Text_IsaiahRematchIntro::
	.string "Ich bin mächtig stolz auf mein\n"
	.string "Team, Kiddie! Komm schon!$"

Route17_Text_VirgilRematchIntro::
	.string "Gehst du spazieren?$"

Route17_Text_BillyRematchIntro::
	.string "Wir sind BIKER, Könige des\n"
	.string "Highways!$"

Route17_Text_NikolasRematchIntro::
	.string "VOLTOBAL wird dich heute\n"
	.string "ernsthaft frizzeln!$"

Route17_Text_ZeekRematchIntro::
	.string "Ich habe mein POKéMON trainiert,\n"
	.string "aber es entwickelt sich einfach\l"
	.string "nicht! Warum?$"

Route17_Text_JamalRematchIntro::
	.string "Ich muss ein wenig abnehmen\n"
	.string "und wirklich mehr trainieren!$"

Route17_Text_CoreyRematchIntro::
	.string "Sei ein Rebell!$"

Route17_Text_JaxonRematchIntro::
	.string "Du besitzt ein schickes FAHRRAD!\n"
	.string "Fährt es sich gut?$"

Route17_Text_WilliamRematchIntro::
	.string "Zieh Leine!\n"
	.string "Ich bin erschöpft!$"

Route18_Text_WiltonRematchIntro::
	.string "Ich suche in jeder neuen Wiese,\n"
	.string "die ich finde, nach neuen POKéMON!\p"
	.string "Das ist nicht immer leicht…$"

Route18_Text_RamiroRematchIntro::
	.string "Guruguu!\n"
	.string "Wird mein Vogellockruf besser?$"

Route18_Text_JacobRematchIntro::
	.string "Ich sagte dir bereits, das hier ist\n"
	.string "mein Gebiet! Sieh zu, dass du\l"
	.string "Land gewinnst!$"

Route19_Text_RichardRematchIntro::
	.string "Ich bin fast genug aufgewärmt,\n"
	.string "um draußen zu schwimmen!$"

Route19_Text_ReeceRematchIntro::
	.string "Warte! Sonst bekommst du einen\n"
	.string "Herzinfarkt!$"

Route19_Text_MatthewRematchIntro::
	.string "Ich gehe gerne schwimmen!\n"
	.string "Du bist wohl eher für das\l"
	.string "Surfen zu begeistern, oder?$"

Route19_Text_DouglasRematchIntro::
	.string "Was mag sich hinter dem Horizont\n"
	.string "verbergen? Hast du es bereits\l"
	.string "herausgefunden?$"

Route19_Text_DavidRematchIntro::
	.string "Ich wollte schon wieder nach\n"
	.string "POKéMON tauchen und wieder\l"
	.string "war es keine gute Idee!$"

Route19_Text_TonyRematchIntro::
	.string "Ich schaue auf das Meer, um zu\n"
	.string "vergessen!\p"
	.string "… wie meine Niederlage\n"
	.string "gegen dich!$"

Route19_Text_AnyaRematchIntro::
	.string "Du reitest immer auf deinem\n"
	.string "POKéMON…\p"
	.string "Das sieht so entspannend aus! Kann\n"
	.string "ich es haben, wenn ich gewinne?$"

Route19_Text_AliceRematchIntro::
	.string "Schwimmen macht Spaß, aber man\n"
	.string "holt sich schnell einen\l"
	.string "Sonnenbrand!$"

Route19_Text_AxleRematchIntro::
	.string "Diese Gewässer sind trügerisch!\n"
	.string "Du hättest nicht wieder herkommen\l"
	.string "dürfen!$"

Route19_Text_ConnieRematchIntro::
	.string "Ich bin mit meinen Freunden hier-\n"
	.string "her geschwommen…\l"
	.string "Müssen wir wirklich erneut kämpfen?$"

Route19_Text_LiaRematchIntro::
	.string "NORA: Du weißt, dass mein Bruder\n"
	.string "erst vor kurzem ein TRAINER wurde!\p"
	.string "Ich will, dass er besser wird, also\n"
	.string "brauche ich deine Hilfe!$"

Route19_Text_LucRematchIntro::
	.string "TOM: Meine große Schwester hat mir\n"
	.string "alles über POKéMON beigebracht!\p"
	.string "Ich frage mich, ob ich besser bin?$"

Route20_Text_BarryRematchIntro::
	.string "Das Wasser ist hier sehr flach.$"

Route20_Text_ShirleyRematchIntro::
	.string "Bist du neidisch, dass ich meinen\n"
	.string "Urlaub auf den SEESCHAUM-\l"
	.string "INSELN verbringe?$"

Route20_Text_TiffanyRematchIntro::
	.string "Ich lasse mich gerne mit den\n"
	.string "Fischen treiben!$"

Route20_Text_IreneRematchIntro::
	.string "Bist du auch auf Urlaub hier?$"

Route20_Text_DeanRematchIntro::
	.string "Schau dir meinen gestählten Körper\n"
	.string "ruhig an!\p"
	.string "Er ist noch durchtrainierter jetzt!$"

Route20_Text_DarrinRematchIntro::
	.string "Warum reitest du ein POKéMON?\n"
	.string "Kannst du noch nicht schwimmen?$"

Route20_Text_RogerRematchIntro::
	.string "Mein Vogel-POKéMON hat mich\n"
	.string "hierher getragen!$"

Route20_Text_NoraRematchIntro::
	.string "Mein Freund hat mir große Perlen\n"
	.string "gegeben und sie sind immer\l"
	.string "größer geworden!$"

Route20_Text_MissyRematchIntro::
	.string "Ich bin von der ZINNOBERINSEL\n"
	.string "herübergeschwommen!$"

Route20_Text_MelissaRematchIntro::
	.string "Auf der ZINNOBERINSEL befindet\n"
	.string "sich ein POKéMON-LABOR.$"

Route21_North_Text_RonaldRematchIntro::
	.string "Möchtest du wissen, ob die Fische\n"
	.string "beißen?$"

Route21_North_Text_WadeRematchIntro::
	.string "Ich habe schon wieder einen Großen\n"
	.string "gefangen! Willst du noch ein Match?$"

Route21_North_Text_SpencerRematchIntro::
	.string "Die See reinigt Körper und Seele!$"

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro::
	.string "きょうも　およぎに\n"
	.string "きちまったぜ$"

Route21_South_Text_JackRematchIntro::
	.string "Ich habe meine POKéMON im\n"
	.string "Wasser gefangen und dort\l"
	.string "trainiere ich auch mit ihnen.$"

Route21_South_Text_JeromeRematchIntro::
	.string "Ich nehme gerade an einem\n"
	.string "weiteren Triathlon teil!$"

Route21_South_Text_RolandRematchIntro::
	.string "Ahh!\n"
	.string "Genieße die Sonne und den Wind!$"

Route21_South_Text_ClaudeRematchIntro::
	.string "Heh, halte dich zurück!\n"
	.string "Du verscheuchst immer die Fische!$"

Route21_South_Text_NolanRematchIntro::
	.string "Leiste mir Gesellschaft, bis etwas\n"
	.string "anbeißt!$"

Route21_North_Text_LilRematchIntro::
	.string "EWE: Häh? Ein Kampf? Schon wieder?\n"
	.string "TOBI, schaffst du das nicht\l"
	.string "alleine?$"

Route21_North_Text_IanRematchIntro::
	.string "TOBI: Meine Schwester ist faul!\n"
	.string "Hilf mir, sie in Form zu bringen!$"

Route25_Text_JoeyRematchIntro::
	.string "Ich werde nicht verlieren,\n"
	.string "während ich hier bin!$"

Route25_Text_DanRematchIntro::
	.string "Ich habe in ORANIA CITY mit\n"
	.string "meinem Papa auf der M.S. ANNE eine\l"
	.string "Party besucht!$"

Route25_Text_FlintRematchIntro::
	.string "Ich bin richtig cool!\n"
	.string "Ich habe eine Freundin!\p"
	.string "Ich beweise ihr dieses Mal,\n"
	.string "wie cool ich wirklich bin!$"

Route25_Text_KelseyRematchIntro::
	.string "Hallo!\n"
	.string "Mein Freund ist cool!\l"
	.string "Ich fühle mich heute gut!$"

Route25_Text_ChadRematchIntro::
	.string "Ich hatte dieses Gefühl…\n"
	.string "Ich wusste, dass wir erneut\l"
	.string "miteinander kämpfen würden!$"

Route25_Text_HaleyRematchIntro::
	.string "Meine Freundin hat so ein süßes\n"
	.string "POKéMON! Ich bin furchtbar\l"
	.string "neidisch!$"

Route25_Text_FranklinRematchIntro::
	.string "Ich habe auf dem MONDBERG\n"
	.string "trainiert und immer noch Benzin\l"
	.string "im Tank!$"

Route25_Text_NobRematchIntro::
	.string "Ich bin auf dem Weg zu einem\n"
	.string "POKéMANIAC am Kap!\l"
	.string "Kennst du seine Sammlung?$"

Route25_Text_WayneRematchIntro::
	.string "Du möchtest wieder zu BILL?\n"
	.string "Aber erst wird gekämpft!$"

Route24_Text_ShaneRematchIntro::
	.string "Ich habe deine Vorstellung aus dem\n"
	.string "Gras heraus beobachtet!$"

Route24_Text_EthanRematchIntro::
	.string "O.K.!\n"
	.string "Dich mache ich platt!$"

Route24_Text_ReliRematchIntro::
	.string "Du siehst immer so beschäftigt aus!\n"
	.string "Wirst du nicht müde?$"

Route24_Text_TimmyRematchIntro::
	.string "Du musst es wirklich lieben, zur\n"
	.string "NUGGET-BRÜCKE zu kommen.$"

Route24_Text_AliRematchIntro::
	.string "Als wir kämpften…\p"
	.string "Obwohl ich nur an zweiter Stelle\n"
	.string "stand, war ich die Beste, oder?$"

Route24_Text_CaleRematchIntro::
	.string "Die Leute nennen das hier die\n"
	.string "NUGGET-BRÜCKE!\p"
	.string "Du hast uns bereits besiegt, also\n"
	.string "darfst du an der Herausforderung\l"
	.string "nicht mehr teilnehmen…\l"
	.string "… aber du darfst gerne\l"
	.string "wieder mit uns kämpfen!$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
	.string "Beim Entspannen habe ich mich\n"
	.string "von den Wellen treiben lassen\l"
	.string "und die Zeit vergessen…$"

OneIsland_KindleRoad_Text_MariaRematchIntro::
	.string "Das Wetter ist fantastisch! Ich\n"
	.string "versuche es nicht zu vermiesen!$"

OneIsland_KindleRoad_Text_AbigailRematchIntro::
	.string "Mein Sonnenbrand fängt an\n"
	.string "zu schmerzen…$"

OneIsland_KindleRoad_Text_FinnRematchIntro::
	.string "Der Berg des Feuervogels wirft\n"
	.string "einen riesigen Schatten…$"

OneIsland_KindleRoad_Text_GarrettRematchIntro::
	.string "Ich spüre genau, dass ich\n"
	.string "dieses Mal gewinnen kann!$"

OneIsland_KindleRoad_Text_TommyRematchIntro::
	.string "Warte! Einen Moment noch!\n"
	.string "Ich bin sicher, dass ich einen\l"
	.string "Großen am Haken habe!$"

OneIsland_KindleRoad_Text_SharonRematchIntro::
	.string "Du hilfst mir erneut beim Training?$"

OneIsland_KindleRoad_Text_TanyaRematchIntro::
	.string "Wir haben bis jetzt jeden Tag\n"
	.string "trainiert!$"

OneIsland_KindleRoad_Text_SheaRematchIntro::
	.string "Jeden Morgen vorm Frühstück\n"
	.string "schwimme ich um diese Insel…\l"
	.string "und das dreimal!$"

OneIsland_KindleRoad_Text_HughRematchIntro::
	.string "Zieh dich kampfgemäß an!\n"
	.string "Zieh dich um, hab ich gesagt!$"

OneIsland_KindleRoad_Text_BryceRematchIntro::
	.string "Weißt du, dass in der Natur alles\n"
	.string "großartig schmeckt?$"

OneIsland_KindleRoad_Text_ClaireRematchIntro::
	.string "Ich habe erneut zu viel gegessen!\n"
	.string "Kämpfst du gegen uns, um ein\l"
	.string "wenig zu trainieren?$"

OneIsland_KindleRoad_Text_KiaRematchIntro::
	.string "HEIDI: Mein großer Bruder und ich\n"
	.string "sind eine grandiose Mischung!\p"
	.string "Dieses Mal verlieren wir nicht!$"

OneIsland_KindleRoad_Text_MikRematchIntro::
	.string "DIRK: An der Seite von HEIDI\n"
	.string "habe ich vor nichts Angst!\p"
	.string "Dieses Mal beweisen wir es dir!$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
	.string "Sollen wir erneut kämpfen?$"

ThreeIsland_BondBridge_Text_VioletRematchIntro::
	.string "Wo kommst du her und wohin\n"
	.string "willst du?$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
	.string "Ich möchte bald ohne\n"
	.string "Schwimmreifen schwimmen.$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
	.string "Jo, jo!\n"
	.string "POKéMON!$"

ThreeIsland_BondBridge_Text_TishaRematchIntro::
	.string "Oh, nein, habe ich es dir nicht\n"
	.string "bereits gesagt? Lass mich in Ruhe!$"

ThreeIsland_BondBridge_Text_JoyRematchIntro::
	.string "UTE: Wir sind jetzt stärker!\n"
	.string "Und zwar gewaltig stärker!$"

ThreeIsland_BondBridge_Text_MegRematchIntro::
	.string "IDA: Heute besiegst du uns nicht!$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
	.string "Oh, hallo!\p"
	.string "Trainierst du deine POKéMON in\n"
	.string "netter Umgebung?$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
	.string "Diese Hände werden heute den\n"
	.string "Sieg davontragen!$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
	.string "Muss ich mich wiederholen?\n"
	.string "Ich male!\l"
	.string "Geh mir aus der Sicht!$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
	.string "Ich habe keinen Fortschritt\n"
	.string "gemacht…\l"
	.string "Ich kann immer noch nicht den\l"
	.string "richtigen Winkel finden…$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
	.string "Du gibst mir erneut Gelegenheit,\n"
	.string "meine Kräfte mit dir zu messen?$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
	.string "Der Pool für meine POKéMON ist\n"
	.string "fast fertig.\p"
	.string "Du musst ihn dir anschauen!$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
	.string "Ich bin ein starker Läufer!\n"
	.string "Ich bin noch schneller jetzt!$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
	.string "Heh, mein Kamerad! Lass uns\n"
	.string "die Zeit zusammen genießen!$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
	.string "Ich bin der älteste der\n"
	.string "VOGEL-BRÜDER. Erinnerst du dich?\p"
	.string "Genau, ich bin derjenige, der\n"
	.string "Vögel wegen ihrer Schnäbel liebt!$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
	.string "Ich bin der zweitälteste der\n"
	.string "VOGEL-BRÜDER.\p"
	.string "Ich bin derjenige, der Vögel\n"
	.string "wegen ihrer Flügel liebt!\l"
	.string "Lass uns erneut kämpfen!$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
	.string "Ich bin der jüngste der\n"
	.string "VOGEL-BRÜDER.\p"
	.string "Ich liebe Vögel ihres Gefieders\n"
	.string "wegen. Ich dachte nicht,\l"
	.string "dass wir uns wieder sehen\l"
	.string "würden.$"

SixIsland_OutcastIsland_Text_TylorRematchIntro::
	.string "Ich habe immer noch kein Glück!\n"
	.string "Ein Kampf wäre ein Tempowechsel!$"

SixIsland_OutcastIsland_Text_MymoRematchIntro::
	.string "Schnauf… schnauf…\p"
	.string "Ich bin erneut von EILAND SECHS\n"
	.string "ohne Pause hierher geschwommen.$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
	.string "Beim Schwimmen treffe ich immer\n"
	.string "auf dich!$"

SixIsland_OutcastIsland_Text_AvaRematchIntro::
	.string "TINA: Auf in einen erneuten\n"
	.string "Zwei-gegen-Zwei-Kampf im Wasser!$"

SixIsland_OutcastIsland_Text_GebRematchIntro::
	.string "TINO: Meine große Schwester und\n"
	.string "ich sind viel stärker als früher!$"

SixIsland_GreenPath_Text_JaclynRematchIntro::
	.string "… Häh?\p"
	.string "Ich sehe mein Haus vor meinem\n"
	.string "inneren Auge, aber TELEPORT\l"
	.string "bringt mich stets hierher!$"

SixIsland_WaterPath_Text_RoseRematchIntro::
	.string "Oh, hallo!\n"
	.string "Erneut weht ein\l"
	.string "angenehmes Lüftchen!$"

SixIsland_WaterPath_Text_EdwardRematchIntro::
	.string "Hehe! Ich trainiere schon\n"
	.string "wieder heimlich!$"

SixIsland_WaterPath_Text_SamirRematchIntro::
	.string "Wie? Du kannst keine SCHWIMMER\n"
	.string "wie mich mehr sehen?\p"
	.string "Ah! Sei doch nicht so!\n"
	.string "Lass uns lieber erneut kämpfen!$"

SixIsland_WaterPath_Text_DeniseRematchIntro::
	.string "Seufz…\n"
	.string "Mein Freund ist schon wieder\l"
	.string "beschäftigt…$"

SixIsland_WaterPath_Text_EarlRematchIntro::
	.string "Sag mir, wo in dieser Gegend die\n"
	.string "Berge liegen!$"

SixIsland_WaterPath_Text_MiuRematchIntro::
	.string "LEA: Hallo POKéMON!\n"
	.string "Lass uns erneut spielen!$"

SixIsland_WaterPath_Text_MiaRematchIntro::
	.string "MIA: Hallo POKéMON!\n"
	.string "Lass uns erneut kämpfen!$"

SixIsland_RuinValley_Text_StanlyRematchIntro::
	.string "Es gibt noch sehr viele ungelöste\n"
	.string "Rätsel in dieser Welt!$"

SixIsland_RuinValley_Text_FosterRematchIntro::
	.string "Hallo! Kennen wir uns nicht?\n"
	.string "Warum bist du zurückgekommen?$"

SixIsland_RuinValley_Text_LarryRematchIntro::
	.string "Man sagt, dass es auf dieser Insel\n"
	.string "geheimnisvolle Steine geben soll.\p"
	.string "Hast du seit unserem letzten\n"
	.string "Treffen etwas herausgefunden?$"

SixIsland_RuinValley_Text_DarylRematchIntro::
	.string "Ein Rückkampf mit dir, hier oben?$"

SixIsland_RuinValley_Text_HectorRematchIntro::
	.string "Ich kenne mich in dieser Gegend\n"
	.string "recht gut aus!$"

SevenIsland_TrainerTower_Text_DarioRematchIntro::
	.string "Ich spürte, dass du kommst!$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
	.string "Irgendwo auf dieser Insel schlafen\n"
	.string "gewisse POKéMON!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
	.string "Hyah!\p"
	.string "Deine Rückkehr ändert nichts, ich\n"
	.string "werde dich mühelos pulverisieren!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
	.string "Alles fit? Du bist in meinem\n"
	.string "Fanclub, oder?$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
	.string "Diese Insel ist zu weitläufig…\n"
	.string "Hier Wache zu halten ist mühsam…$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
	.string "Menschen, die POKéMON\n"
	.string "missbrauchen, kann ich nicht\l"
	.string "vergeben!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
	.string "TIZIA: Ich kämpfe wieder mit TILL\n"
	.string "zusammen!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
	.string "TILL: An der Seite von TIZIA habe\n"
	.string "ich stets das Gefühl, nicht\l"
	.string "verlieren zu können.$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
	.string "Lass uns erneut kämpfen!\n"
	.string "Ich bin heute in Topform!$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
	.string "Es macht nichts, wenn du die\n"
	.string "stärksten POKéMON hast…\p"
	.string "Wenn du mit ihnen nicht umzugehen\n"
	.string "weißt, bringt es dir nichts!$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
	.string "Ich arbeite im Naturschutz!\n"
	.string "Die Natur beschützt mich dafür!$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
	.string "Bei jedem Treffen trägst du diese\n"
	.string "coolen Schuhe!$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
	.string "Du musst stärker geworden sein!\n"
	.string "Darf ich gegen dich kämpfen?$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
	.string "Mir wurde die beste Ausbildung\n"
	.string "zuteil, um so stark zu werden!\p"
	.string "Dieses Mal verliere ich nicht.\n"
	.string "Bestimmt nicht!$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
	.string "OLE: Geliebte GRIT, zusammen\n"
	.string "werden wir gewinnen!$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
	.string "GRIT: Ich enttäusche meinen Mentor\n"
	.string "OLE nicht! Wir werden gewinnen!$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
	.string "Hast du irgendetwas über diese\n"
	.string "Steinkammer herausgefunden?$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
	.string "Man sagt, ein geheimnisvolles\n"
	.string "POKéMON würde hier schlafen!$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
	.string "Mein Lehrer zeigt mir, wie ich noch\n"
	.string "mehr malen kann.$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
	.string "Heute sind wir nach dem Unterricht\n"
	.string "erneut in die Kammer gegangen!$"
