FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
    .ifdef ENGLISH
    .string "LORELEI: Keep your filthy hands\n"
    .string "off the POKéMON in the cave!\p"
    .string "Do as I say, or you'll have me to\n"
    .string "answer to!$"
    .endif
    .ifdef SPANISH
    .string "LORELEI: ¡Ni te acerques a los\n"
    .string "POKéMON que hay en la cueva!\p"
    .string "Si no, te las tendrás que ver\n"
    .string "conmigo.$"
    .endif

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
    .ifdef ENGLISH
    .string "Aww, shut it, lady, and leave\n"
    .string "us be.\p"
    .string "Don't let your glasses get all\n"
    .string "steamed up!$"
    .endif
    .ifdef SPANISH
    .string "Venga ya, señora, no incordie.\p"
    .string "¡Chicos, sigamos a lo nuestro!$"
    .endif

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
    .ifdef ENGLISH
    .string "LORELEI: {PLAYER}?!\n"
    .string "What are you doing here?\p"
    .string "No, we can catch up later.\n"
    .string "Right now, I need your help.\p"
    .string "Help me kick these poachers out\n"
    .string "before they do anything else.\p"
    .string "They've been catching POKéMON\n"
    .string "here, then selling them off!\p"
    .string "Are you ready?\n"
    .string "You take that one, please!$"
    .endif
    .ifdef SPANISH
    .string "LORELEI: ¡¿{PLAYER}?!\n"
    .string "¿Qué haces aquí?\p"
    .string "Bueno, ya charlaremos después.\n"
    .string "Ayúdame con estos elementos.\p"
    .string "Necesito que me eches una mano\n"
    .string "para frenar a esta gentuza.\p"
    .string "Han estado atrapando POKéMON\n"
    .string "aquí, y vendiéndolos por ahí.\p"
    .string "¿Vas a ayudarme?\n"
    .string "¡Pues adelante!$"
    .endif

FourIsland_IcefallCave_Back_Text_GruntIntro::
    .ifdef ENGLISH
    .string "W-what?!\p"
    .string "Who says we can't do what we want\n"
    .string "with the POKéMON we catch?$"
    .endif
    .ifdef SPANISH
    .string "¿Perdón?\p"
    .string "¿Quién dice aquí lo que podemos\n"
    .string "o no podemos hacer con los\l"
    .string "POKéMON que atrapamos?$"
    .endif

FourIsland_IcefallCave_Back_Text_GruntDefeat::
    .ifdef ENGLISH
    .string "We didn't plan on this!$"
    .endif
    .ifdef SPANISH
    .string "¡No me esperaba yo esto!$"
    .endif

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
    .ifdef ENGLISH
    .string "LORELEI: Humph.\n"
    .string "So despicably weak.\p"
    .string "You!\n"
    .string "Tell me!\p"
    .string "Where have you taken the captured\n"
    .string "POKéMON?\p"
    .string "I'm smashing your ring once and\n"
    .string "for all!$"
    .endif
    .ifdef SPANISH
    .string "LORELEI: Ja.\n"
    .string "Qué cosa más endeble...\p"
    .string "A ver, tú.\n"
    .string "Dime.\p"
    .string "¿Dónde tenéis a los POKéMON\n"
    .string "que habéis capturado?\p"
    .string "Dímelo ahora mismo si no quieres\n"
    .string "que te dé una zurra.$"
    .endif

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
    .ifdef ENGLISH
    .string "N-no way!\n"
    .string "I'm not telling you that!$"
    .endif
    .ifdef SPANISH
    .string "¡Ni en broma!\n"
    .string "¡No pienso decírtelo!$"
    .endif

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
    .ifdef ENGLISH
    .string "LORELEI: If you won't confess,\n"
    .string "we'll deep-freeze you.\p"
    .string "My LAPRAS is furious for what\n"
    .string "you've done to its friends.\p"
    .string "Go, LAPRAS!\n"
    .string "ICE BEAM…$"
    .endif
    .ifdef SPANISH
    .string "LORELEI: Como no me lo digas,\n"
    .string "¡acabarás congelado!\p"
    .string "Mi LAPRAS está que trina por lo\n"
    .string "que les habéis hecho a sus amigos.\p"
    .string "¡Venga, LAPRAS!\n¡RAYO HIELO!...$"
    .endif

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
    .ifdef ENGLISH
    .string "Wawaah! Okay!\n"
    .string "I'll talk!\p"
    .string "The POKéMON are in the ROCKET\n"
    .string "WAREHOUSE on FIVE ISLAND.\p"
    .string "There! I said it!\n"
    .string "We'll be going now!\p"
    .string "…But I doubt you'll ever make it\n"
    .string "into the ROCKET WAREHOUSE!\p"
    .string "Heheheheh!$"
    .endif
    .ifdef SPANISH
    .string "¡Aaaaah!\n"
    .string "¡Para, para, que te lo digo!\p"
    .string "Los POKéMON están en el ALMACÉN\n"
    .string "ROCKET de ISLA INTA.\p"
    .string "¡Hala, ya lo he dicho!\n"
    .string "¡Vámonos ya de aquí!\p"
    .string "¡Pero que sepas que dudo mucho\n"
    .string "que puedas entrar en el ALMACÉN\l"
    .string "ROCKET!\p"
    .string "¡Ja, ja, ja!$"
    .endif

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
    .ifdef ENGLISH
    .string "{PLAYER}, thank you.\n"
    .string "But this is awful…\p"
    .string "I was born and raised here on\n"
    .string "these islands.\p"
    .string "I had no idea that those horrible\n"
    .string "criminals were loose here…$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER}, gracias.\n"
    .string "Ha sido horrible...\p"
    .string "Yo he nacido aquí y he pasado\n"
    .string "toda mi vida en estas islas.\p"
    .string "No sabía que esos golfos\n"
    .string "estuvieran por aquí sueltos...$"
    .endif

