CeruleanCity_House2_Text_RocketsStoleTMForDig::
    .ifdef ENGLISH
    .string "Those miserable ROCKETS!\p"
    .string "Look what they've done to my\n"
    .string "house!\p"
    .string "They stole a TM for teaching\n"
    .string "POKéMON how to DIG holes!\p"
    .string "I was going to use it on a\n"
    .string "MANKEY or a SANDSHREW…\p"
    .string "That cost me a bundle, it did!$"
    .endif
    .ifdef SPANISH
    .string "¡Esos dichosos ROCKET!\p"
    .string "¡Mira lo que hicieron aquí!\p"
    .string "¡Robaron una MT para enseñar a\n"
    .string "los POKéMON cómo EXCAVAR hoyos!\p"
    .string "Yo que quería enseñárselo a\n"
    .string "MANKEY o a SANDSHREW... \p"
    .string "¡Menuda faena!$"
    .endif

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM::
    .ifdef ENGLISH
    .string "I figure what's lost is lost.\p"
    .string "I decided to teach DIGLETT how to\n"
    .string "DIG without a TM.$"
    .endif
    .ifdef SPANISH
    .string "¡Lo perdido, perdido está!\p"
    .string "¡He decidido enseñar a DIGLETT\n"
    .string "cómo EXCAVAR sin tener una MT!$"
    .endif

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood::
    .ifdef ENGLISH
    .string "TEAM ROCKET must be trying to DIG\n"
    .string "their way into no good!$"
    .endif
    .ifdef SPANISH
    .string "¡El TEAM ROCKET estará intentando\n"
    .string "EXCAVAR para hacer alguna de las\l"
    .string "suyas!$"
    .endif

CeruleanCity_House2_Text_TeamRocketLeftWayOut::
    .ifdef ENGLISH
    .string "TEAM ROCKET left a way out!$"
    .endif
    .ifdef SPANISH
    .string "¡El TEAM ROCKET abrió una nueva\n"
    .string "salida!$"
    .endif

