SilphCo_1F_Text_WelcomePresidentInBoardroom::
    .ifdef ENGLISH
    .string "Welcome.\p"
    .string "The PRESIDENT is in the boardroom\n"
    .string "on 11F.$"
    .endif
    .ifdef SPANISH
    .string "¡Hola!\p"
    .string "¡El PRESIDENTE está en la sala\n"
    .string "de reuniones del P10!$"
    .endif

@ Tentative translation. Unknown origin
SilphCo_1F_Text_DestroyedWontBeFixedForWhile::
    .string "めちゃめちゃに　こわされてる\n"
    .string "とうぶん　なおりそうに　ない‥$"

SilphCo_1F_Text_FloorSign::
    .ifdef ENGLISH
    .string "SILPH CO. HEAD OFFICE\n"
    .string "1F$"
    .endif
    .ifdef SPANISH
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "PB$"
    .endif

