LavenderTown_House1_Text_Cubone::
    .ifdef ENGLISH
    .string "CUBONE: Kyarugoo!$"
    .endif
    .ifdef SPANISH
    .string "CUBONE: ¡Cubon!$"
    .endif

LavenderTown_House1_Text_RocketsKilledCubonesMother::
    .ifdef ENGLISH
    .string "Those horrible ROCKETS!\n"
    .string "They deserve no mercy!\p"
    .string "That poor CUBONE's mother…\p"
    .string "It was killed trying to escape from\n"
    .string "TEAM ROCKET.$"
    .endif
    .ifdef SPANISH
    .string "¡Odio a esos horribles ROCKET!\p"
    .string "La pobre madre de CUBONE...\p"
    .string "¡Intentó escapar del TEAM ROCKET,\n"
    .string "pero no lo consiguió!...$"
    .endif

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone::
    .ifdef ENGLISH
    .string "The ghost of POKéMON TOWER is\n"
    .string "gone!\p"
    .string "Someone must have soothed its\n"
    .string "restless spirit!$"
    .endif
    .ifdef SPANISH
    .string "¡El GHOST de la TORRE POKéMON\n"
    .string "se ha ido!\p"
    .string "¡Alguien debe de haber calmado\n"
    .string "su atormentada alma!$"
    .endif

