SaffronCity_House_Text_DontLookAtMyLetter::
    .ifdef ENGLISH
    .string "…Thank you for writing.\n"
    .string "I hope to see you soon!\p"
    .string "…Hey!\n"
    .string "Don't look at my letter!$"
    .endif
    .ifdef SPANISH
    .string "Gracias por escribir.\n"
    .string "¡Espero verte pronto!\p"
    .string "¡Oye!\n"
    .string "¡No mires mi carta!$"
    .endif

SaffronCity_House_Text_Pidgey::
    .ifdef ENGLISH
    .string "PIDGEY: Kurukkoo!$"
    .endif
    .ifdef SPANISH
    .string "PIDGEY: ¡Pid, pid!$"
    .endif

SaffronCity_House_Text_GettingCopycatPokeDoll::
    .ifdef ENGLISH
    .string "The COPYCAT is cute!\n"
    .string "I'm getting her a POKé DOLL.$"
    .endif
    .ifdef SPANISH
    .string "¡La COPIONA es muy mona!\n"
    .string "¡Voy a darle un POKé MUÑECO!$"
    .endif

SaffronCity_House_Text_ExplainPPUp::
    .ifdef ENGLISH
    .string "I was given a PP UP as a gift.\p"
    .string "It's used to increase the PP of\n"
    .string "a POKéMON's move.\p"
    .string "I should use it on a powerful move\n"
    .string "with only a few PP.$"
    .endif
    .ifdef SPANISH
    .string "Recibí MÁS PP como regalo.\p"
    .string "¡Sirve para aumentar los PP de\n"
    .string "un movimiento de un POKéMON!\p"
    .string "Creo que voy a usarlo con un\n"
    .string "movimiento potente, que tenga\l"
    .string "pocos PP.$"
    .endif

