SaffronCity_House_Text_DontLookAtMyLetter::
	.string "... vielen Dank für deinen Brief!\n"
	.string "Bis bald...\p"
	.string "Heh!\n"
	.string "Lies meinen Brief nicht!$"

SaffronCity_House_Text_Pidgey::
	.string "TAUBSI: TAUBSI!$"

SaffronCity_House_Text_GettingCopycatPokeDoll::
	.string "Ich mag die NACHAHMERIN!\n"
	.string "Ich kaufe ihr eine POKéPUPPE!$"

SaffronCity_House_Text_ExplainPPUp::
	.string "Ich habe ein AP-PLUS geschenkt\n"
	.string "bekommen!\p"
	.string "Es erhöht die ANGRIFFSPUNKTE einer\n"
	.string "Attacke!\p"
	.string "Ich sollte es bei einer mächtigen\n"
	.string "Attacke, die wenig AP hat,\l"
	.string "einsetzen.$"

