CinnabarIsland_Mart_Text_DontTheyHaveXAttack::
    .ifdef ENGLISH
    .string "Don't they have X ATTACK?\p"
    .string "I like it because it raises the\n"
    .string "ATTACK stat in battle.$"
    .endif
    .ifdef SPANISH
    .string "¿No tienes ATAQUE X?\p"
    .string "¡Es estupendo para luchar!$"
    .endif

CinnabarIsland_Mart_Text_ExtraItemsNeverHurt::
    .ifdef ENGLISH
    .string "It never hurts to have extra items.\n"
    .string "You never know what might happen.$"
    .endif
    .ifdef SPANISH
    .string "¡Está bien tener más objetos!$"
    .endif

