FourIsland_LoreleisHouse_Text_IfAnythingWereToHappenToIsland::
    .ifdef ENGLISH
    .string "LORELEI: There's something weighing\n"
    .string "heavily on my mind.\p"
    .string "If anything were to happen on\n"
    .string "the island where I was born…\p"
    .string "I wouldn't know about it if I were\n"
    .string "in the POKéMON LEAGUE.\p"
    .string "I wonder if that would make me\n"
    .string "irresponsible to my home…$"
    .endif
    .ifdef SPANISH
    .string "LORELEI: No me puedo quitar una\n"
    .string "cosa de la cabeza...\p"
    .string "Si ocurriera algo a la isla en la\n"
    .string "que nací...\p"
    .string "No me enteraría si estuviera\n"
    .string "en la LIGA POKéMON.\p"
    .string "Entonces, sería responsable\n"
    .string "de lo ocurrido, ¿no?$"
    .endif

FourIsland_LoreleisHouse_Text_IllReturnToLeagueInShortWhile::
    .ifdef ENGLISH
    .string "LORELEI: So, you managed to solve\n"
    .string "all the problems here?\p"
    .string "That's wonderful.\p"
    .string "That means there isn't any reason\n"
    .string "for me to be here all the time.\p"
    .string "Thank you…\p"
    .string "I'll return to the POKéMON LEAGUE\n"
    .string "in a short while.$"
    .endif
    .ifdef SPANISH
    .string "LORELEI: ¿Que tú has solucionado\n"
    .string "todos los problemas?\p"
    .string "Qué maravilla...\p"
    .string "Entonces, no tengo que quedarme\n"
    .string "aquí todo el tiempo...\p"
    .string "¡Gracias!\p"
    .string "¡En ese caso, me volveré a la\n"
    .string "LIGA POKéMON!$"
    .endif

FourIsland_LoreleisHouse_Text_WillDoWhatICanHereAndNow::
    .ifdef ENGLISH
    .string "I don't know what will happen in\n"
    .string "the future, but…\p"
    .string "I will do what I can here and now.\n"
    .string "That's all I can do.$"
    .endif
    .ifdef SPANISH
    .string "No sé qué pasará dentro de un\n"
    .string "tiempo, así que...\p"
    .string "Haré lo que tenga que hacer\n"
    .string "aquí y ahora.$"
    .endif

FourIsland_LoreleisHouse_Text_StuffedMonDollsGalore::
    .ifdef ENGLISH
    .string "Stuffed POKéMON dolls galore!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué cantidad de MUÑECOS POKéMON\n"
    .string "de peluche!$"
    .endif

