Route4_Text_TrippedOverGeodude::
    .ifdef ENGLISH
    .string "Ouch! I tripped over a rocky\n"
    .string "POKéMON, GEODUDE!$"
    .endif
    .ifdef SPANISH
    .string "¡Auch! ¡Tropecé con un POKéMON\n"
    .string "rocoso, GEODUDE!$"
    .endif

Route4_Text_CrissyIntro::
    .ifdef ENGLISH
    .string "I came to MT. MOON in search of\n"
    .string "mushroom POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Vine a recoger mis hongos\n"
    .string "POKéMON!$"
    .endif

Route4_Text_CrissyDefeat::
    .ifdef ENGLISH
    .string "After all I did to catch them!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh! ¡Mi pobre hongo POKéMON!$"
    .endif

Route4_Text_CrissyPostBattle::
    .ifdef ENGLISH
    .string "There might not be any more\n"
    .string "mushrooms here.\p"
    .string "I think I got them all.$"
    .endif
    .ifdef SPANISH
    .string "¡Puede que no haya más hongos\n"
    .string "por aquí!\p"
    .string "Creo que ya los tengo todos.$"
    .endif

Route4_Text_MtMoonEntrance::
    .ifdef ENGLISH
    .string "MT. MOON\n"
    .string "Tunnel Entrance$"
    .endif
    .ifdef SPANISH
    .string "MT. MOON:\n"
    .string "Entrada al túnel$"
    .endif

Route4_Text_RouteSign::
    .ifdef ENGLISH
    .string "ROUTE 4\n"
    .string "MT. MOON - CERULEAN CITY$"
    .endif
    .ifdef SPANISH
    .string "RUTA 4:\n"
    .string "MT. MOON - CIUDAD CELESTE$"
    .endif

Text_MegaPunchTeach::
    .ifdef ENGLISH
    .string "A punch of roaring ferocity!\p"
    .string "Packed with destructive power!\p"
    .string "When the chips are down,\n"
    .string "MEGA PUNCH is the ultimate attack!\l"
    .string "You agree, yes?\p"
    .string "Now!\n"
    .string "Let me teach it to your POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Un puñetazo con rabia\n"
    .string "contenida!\p"
    .string "¡Condimentado con fuerza\n"
    .string "descomunal!\p"
    .string "¡Cuando no queda energía,\n"
    .string "MEGAPUÑO es el ataque definitivo!\p"
    .string "¿Qué?\n"
    .string "¿Se lo enseño a algún POKéMON?$"
    .endif

Text_MegaPunchDeclined::
    .ifdef ENGLISH
    .string "You'll be back when you understand\n"
    .string "the worth of MEGA PUNCH.$"
    .endif
    .ifdef SPANISH
    .string "¡Cuando comprendas el significado\n"
    .string "de MEGAPUÑO, volverás!$"
    .endif

Text_MegaPunchWhichMon::
    .ifdef ENGLISH
    .string "Fine!\n"
    .string "Which POKéMON will learn it?$"
    .endif
    .ifdef SPANISH
    .string "¿A qué POKéMON quieres que se\n"
    .string "lo enseñe?$"
    .endif

Text_MegaPunchTaught::
    .ifdef ENGLISH
    .string "Now, we are comrades in the way of\n"
    .string "punching!\p"
    .string "You should go before you're seen\n"
    .string "by the misguided fool who trains\l"
    .string "only his silly kicking over there.$"
    .endif
    .ifdef SPANISH
    .string "¡Ya usamos los puños de la\n"
    .string "misma forma!\p"
    .string "¡Hala, vete antes de que le entren\n"
    .string "ganas de luchar a mi colega:\l"
    .string "es un flipado de las patadas!$"
    .endif

Text_MegaKickTeach::
    .ifdef ENGLISH
    .string "A kick of brutal ferocity!\p"
    .string "Packed with destructive power!\p"
    .string "When you get right down to it,\n"
    .string "MEGA KICK is the ultimate attack!\l"
    .string "Don't you agree?\p"
    .string "Okay!\n"
    .string "I'll teach it to your POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Una buena patada con rabia\n"
    .string "contenida!\p"
    .string "¡Condimentada con fuerza\n"
    .string "descomunal!\p"
    .string "¡Cuando no quede energía,\n"
    .string "MEGAPATADA es el ataque\l"
    .string "definitivo!\p"
    .string "¿Qué?\n"
    .string "¿Se lo enseño a algún POKéMON?$"
    .endif

Text_MegaKickDeclined::
    .ifdef ENGLISH
    .string "You'll come crawling back when you\n"
    .string "realize the value of MEGA KICK.$"
    .endif
    .ifdef SPANISH
    .string "¡Cuando comprendas el significado\n"
    .string "de MEGAPATADA, volverás llorando!$"
    .endif

Text_MegaKickWhichMon::
    .ifdef ENGLISH
    .string "All right!\n"
    .string "Which POKéMON wants to learn it?$"
    .endif
    .ifdef SPANISH
    .string "¿A qué POKéMON quieres que se\n"
    .string "lo enseñe?$"
    .endif

Text_MegaKickTaught::
    .ifdef ENGLISH
    .string "Now, we are soul mates in the way\n"
    .string "of kicking!\p"
    .string "You should run before you're seen\n"
    .string "by the deluded nitwit who trains\l"
    .string "only simple punching over there.$"
    .endif
    .ifdef SPANISH
    .string "¡Ya damos patadas de la\n"
    .string "misma forma!\p"
    .string "¡Hala, vete antes de que le entren\n"
    .string "ganas de luchar a mi colega:\l"
    .string "es un flipado de los puñetazos!$"
    .endif

Route4_Text_PeopleLikeAndRespectBrock::
    .ifdef ENGLISH
    .string "Oh, wow, that's the BOULDERBADGE!\n"
    .string "You got it from BROCK, didn't you?\p"
    .string "BROCK is cool. He's not just tough.\n"
    .string "People like and respect him.\p"
    .string "I want to become a GYM LEADER\n"
    .string "like him.$"
    .endif
    .ifdef SPANISH
    .string "¡Anda, la MEDALLA ROCA!\n"
    .string "Te la ha dado BROCK, ¿no?\p"
    .string "BROCK es, además de fuerte, guay.\n"
    .string "Todos lo respetan y admiran mucho.\p"
    .string "Yo quiero ser LÍDER de GIMNASIO\n"
    .string "como él.$"
    .endif
