VermilionCity_Text_GrimerMultipliesInSludge::
    .ifdef ENGLISH
    .string "We're careful about pollution here.\p"
    .string "We've heard GRIMER multiplies in\n"
    .string "toxic sludge.$"
    .endif
    .ifdef SPANISH
    .string "¡Nos preocupa la contaminación!\p"
    .string "¡Dicen que GRIMER se convierte\n"
    .string "en cantidades enormes de residuos\l"
    .string "tóxicos!$"
    .endif

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
    .ifdef ENGLISH
    .string "Did you see the S.S. ANNE moored\n"
    .string "in the harbor?$"
    .endif
    .ifdef SPANISH
    .string "¿Viste al S.S. ANNE anclado en el\n"
    .string "puerto?$"
    .endif

VermilionCity_Text_SSAnneHasDepartedForYear::
    .ifdef ENGLISH
    .string "So, the S.S. ANNE has departed?\p"
    .string "She'll be back in VERMILION about\n"
    .string "this time next year.$"
    .endif
    .ifdef SPANISH
    .string "¡El S.S. ANNE ha zarpado!\n"
    .string "Volverá a CARMÍN en un año.$"
    .endif

VermilionCity_Text_BuildingOnThisLand::
    .ifdef ENGLISH
    .string "I'm putting up a building on this\n"
    .string "plot of land. I own it all.\p"
    .string "My POKéMON is tamping the land\n"
    .string "to lay the foundation.$"
    .endif
    .ifdef SPANISH
    .string "Voy a construir un edificio en este\n"
    .string "trozo de tierra.\p"
    .string "Mi POKéMON está apisonando\n"
    .string "el terreno.$"
    .endif

VermilionCity_Text_Machop::
    .ifdef ENGLISH
    .string "MACHOP: Guoh! Gogogoh!$"
    .endif
    .ifdef SPANISH
    .string "MACHOP: ¡Chop! ¡Chop!$"
    .endif

VermilionCity_Text_MachopStompingLandFlat::
    .ifdef ENGLISH
    .string "A MACHOP is stomping the land flat.$"
    .endif
    .ifdef SPANISH
    .string "¡Un MACHOP está apisonando\n"
    .string "el terreno!$"
    .endif

VermilionCity_Text_SSAnneVisitsOnceAYear::
    .ifdef ENGLISH
    .string "The S.S. ANNE is a famous luxury\n"
    .string "cruise ship.\p"
    .string "It visits VERMILION once a year.$"
    .endif
    .ifdef SPANISH
    .string "El S.S. ANNE es un famoso y lujoso\n"
    .string "crucero.\p"
    .string "Visitamos CARMÍN una vez al año.$"
    .endif

VermilionCity_Text_CitySign::
    .ifdef ENGLISH
    .string "VERMILION CITY\n"
    .string "The Port of Exquisite Sunsets$"
    .endif
    .ifdef SPANISH
    .string "CIUDAD CARMÍN\n"
    .string "El puerto de los ocasos exquisitos.$"
    .endif

VermilionCity_Text_SnorlaxBlockingRoute12::
    .ifdef ENGLISH
    .string "NOTICE!\p"
    .string "ROUTE 12 may be blocked off by a\n"
    .string "sleeping POKéMON.\p"
    .string "Detour through ROCK TUNNEL to\n"
    .string "LAVENDER TOWN.\p"
    .string "VERMILION POLICE$"
    .endif
    .ifdef SPANISH
    .string "¡AVISO!\p"
    .string "La RUTA 12 podría estar bloqueada\n"
    .string "por un POKéMON dormido.\p"
    .string "Desvíate a través del TÚNEL ROCA\n"
    .string "a PUEBLO LAVANDA.\p"
    .string "POLICÍA de CARMÍN$"
    .endif

VermilionCity_Text_PokemonFanClubSign::
    .ifdef ENGLISH
    .string "POKéMON FAN CLUB\n"
    .string "All POKéMON fans welcome!$"
    .endif
    .ifdef SPANISH
    .string "CLUB DE FANS DE POKéMON\n"
    .string "¡Bienvenidos todos!$"
    .endif

VermilionCity_Text_GymSign::
    .ifdef ENGLISH
    .string "VERMILION CITY POKéMON GYM\n"
    .string "LEADER: LT. SURGE\l"
    .string "The Lightning American!$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CARMÍN: LT. SURGE\l"
    .string "¡El Rayo americano!$"
    .endif

VermilionCity_Text_VermilionHarbor::
    .ifdef ENGLISH
    .string "VERMILION HARBOR$"
    .endif
    .ifdef SPANISH
    .string "PUERTO CARMÍN$"
    .endif

VermilionCity_Text_WelcomeToTheSSAnne::
    .ifdef ENGLISH
    .string "Welcome to the S.S. ANNE!$"
    .endif
    .ifdef SPANISH
    .string "¡Éste es el S.S. ANNE!$"
    .endif

VermilionCity_Text_DoYouHaveATicket::
    .ifdef ENGLISH
    .string "Welcome to the S.S. ANNE!\p"
    .string "Excuse me, do you have a ticket?$"
    .endif
    .ifdef SPANISH
    .string "¡Éste es el S.S. ANNE!\p"
    .string "Disculpe, ¿tiene su ticket?$"
    .endif

VermilionCity_Text_FlashedSSTicket::
    .ifdef ENGLISH
    .string "{FONT_NORMAL}{PLAYER} flashed the S.S. TICKET!\p"
    .string "{FONT_MALE}Great!\n"
    .string "Welcome to the S.S. ANNE!$"
    .endif
    .ifdef SPANISH
    .string "{FONT_NORMAL}¡{PLAYER} enseñó el TICKET\n"
    .string "del BARCO!\p"
    .string "{FONT_MALE}¡OK!\n"
    .string "¡Adelante!$"
    .endif

VermilionCity_Text_DontHaveNeededSSTicket::
    .ifdef ENGLISH
    .string "{FONT_NORMAL}{PLAYER} doesn't have the needed\n"
    .string "S.S. TICKET.\p"
    .string "{FONT_MALE}Sorry!\p"
    .string "You need a ticket to get aboard.$"
    .endif
    .ifdef SPANISH
    .string "{FONT_NORMAL}{PLAYER} no tiene el TICKET del\n"
    .string "BARCO.\p"
    .string "{FONT_MALE}¡Lo siento!\p"
    .string "Necesita un ticket para subir a\n"
    .string "bordo.$"
    .endif

VermilionCity_Text_TheShipSetSail::
    .ifdef ENGLISH
    .string "The ship set sail.$"
    .endif
    .ifdef SPANISH
    .string "El barco zarpó.$"
    .endif

VermilionCity_Text_BoardSeagallopTriPass::
    .ifdef ENGLISH
    .string "Ah, you have a TRI-PASS.\p"
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"
    .endif
    .ifdef SPANISH
    .string "Ah, tienes el TRI-TICKET.\p"
    .string "¿Quieres subir a bordo del\n"
    .string "SURCAMAR?$"
    .endif

VermilionCity_Text_Seagallop7Departing::
    .ifdef ENGLISH
    .string "Okay, everything's in order.\p"
    .string "SEAGALLOP HI-SPEED 7 will be\n"
    .string "departing immediately.$"
    .endif
    .ifdef SPANISH
    .string "Estupendo, todo en regla.\p"
    .string "El SURCAMAR VELOCE 7\n"
    .string "va a zarpar en breve.$"
    .endif

VermilionCity_Text_BoardSeagallopRainbowPass::
    .ifdef ENGLISH
    .string "Ah, you have a RAINBOW PASS.\p"
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"
    .endif
    .ifdef SPANISH
    .string "Ah, tienes el IRIS-TICKET.\p"
    .string "¿Quieres subir a bordo del\n"
    .string "SURCAMAR?$"
    .endif

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
    .ifdef ENGLISH
    .string "Oh! That's a MYSTICTICKET!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "NAVEL ROCK anytime.$"
    .endif
    .ifdef SPANISH
    .string "¡Anda, el MISTI-TICKET!\n"
    .string "¡Qué curioso!\p"
    .string "Estaremos encantados de llevarte\n"
    .string "a ROCA OMBLIGO cuando quieras.$"
    .endif

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
    .ifdef ENGLISH
    .string "Oh! That's an AURORATICKET!\n"
    .string "Now that is rare.\p"
    .string "We'll be happy to take you to\n"
    .string "BIRTH ISLAND anytime.$"
    .endif
    .ifdef SPANISH
    .string "¡Anda, el ORI-TICKET!\n"
    .string "¡Qué curioso!\p"
    .string "Estaremos encantados de llevarte\n"
    .string "a ISLA ORIGEN cuando quieras.$"
    .endif

VermilionCity_Text_BoardSeagallopFerry::
    .ifdef ENGLISH
    .string "Would you like to board\n"
    .string "a SEAGALLOP ferry?$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres subir a bordo del\n"
    .string "SURCAMAR?$"
    .endif

VermilionCity_Text_Seagallop10Departing::
    .ifdef ENGLISH
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "SEAGALLOP HI-SPEED 10 will be\n"
    .string "departing immediately.$"
    .endif
    .ifdef SPANISH
    .string "Estupendo, todo está listo para\n"
    .string "que subas a bordo de un ferry\l"
    .string "muy especial.\p"
    .string "El SURCAMAR VELOCE 10\n"
    .string "va a zarpar en breve.$"
    .endif

VermilionCity_Text_Seagallop12Departing::
    .ifdef ENGLISH
    .string "Okay, everything's in order for you\n"
    .string "to board a special ferry.\p"
    .string "SEAGALLOP HI-SPEED 12 will be\n"
    .string "departing immediately.$"
    .endif
    .ifdef SPANISH
    .string "Estupendo, todo está listo para\n"
    .string "que subas a bordo de un ferry\l"
    .string "muy especial.\p"
    .string "El SURCAMAR VELOCE 12\n"
    .string "va a zarpar en breve.$"
    .endif

VermilionCity_Text_Route2AideHasPackageForYou::
    .ifdef ENGLISH
    .string "Oh, hello, {PLAYER}!\n"
    .string "How are you doing?\p"
    .string "It's me, one of PROF. OAK's AIDES.\p"
    .string "Did you meet the other AIDE?\p"
    .string "He had a package from PROF. OAK\n"
    .string "for you, {PLAYER}.\p"
    .string "He said he'd look for you around\n"
    .string "ROUTE 2, {PLAYER}.\p"
    .string "If you're in the ROUTE 2 area,\n"
    .string "please look for him.$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, {PLAYER}!\n"
    .string "¿Qué tal lo llevas?\p"
    .string "Soy uno de los AYUDANTES\n"
    .string "del PROF. OAK.\p"
    .string "¿Has visto ya al otro AYUDANTE?\p"
    .string "Tenía algo que entregarte de parte\n"
    .string "del PROF. OAK, {PLAYER}.\p"
    .string "Comentó que iría a buscarte por\n"
    .string "la RUTA 2, {PLAYER}.\p"
    .string "Si pasas por la RUTA 2, búscalo.$"
    .endif

