@ All Trainer Tower text (Lobby and Roof) is interleaved here

TrainerTower_Lobby_Text_WelcomeToTrainerTower::
	.string "Bonjour.\p"
	.string "Bienvenue à la TOUR DRESSEURS\p"
	.string "où les DRESSEURS viennent\n"
	.string "du monde entier.$"

TrainerTower_Lobby_Text_TrainersUpToFloorNum::
	.string "Les DRESSEURS du monde entier\n"
	.string "viennent ici pour combattre.\p"
	.string "Un instant…\p"
	.string "En ce moment, il n'y a\n"
	.string "des DRESSEURS que\p"
	.string "jusqu'au niveau {STR_VAR_1}.$"

TrainerTower_Lobby_Text_TrainersUpEighthFloor::
	.string "Les DRESSEURS attendent pour vous\n"
	.string "défier jusqu'au 8ème niveau.$"

TrainerTower_Lobby_Text_LikeToChallengeTrainers::
	.string "Voulez-vous affronter les\n"
	.string "DRESSEURS qui patientent?$"

TrainerTower_Lobby_Text_StartClockGetSetGo::
	.string "OK, je compte sur vous pour\n"
	.string "avoir un beau spectacle.\p"
	.string "Je mets le chrono en marche.\p"
	.string "A vos marques…\p"
	.string "Prêts…\p"
	.string "Partez!$"

TrainerTower_Lobby_Text_PleaseVisitUsAgain::
	.string "Revenez nous voir.$"

TrainerTower_Lobby_Text_TooBadComeBackTryAgain::
	.string "Quel dommage.\p"
	.string "Vous avez pourtant fait de\n"
	.string "votre mieux.\p"
	.string "Mais n'hésitez pas à revenir\n"
	.string "nous voir.$"

TrainerTower_Lobby_Text_GiveItYourBest::
	.string "Vous avez fait de votre mieux.$"

TrainerTower_Lobby_Text_MoveCounterHereWhenTrainersSwitch::
	.string "Ça peut être assez mouvementé\n"
	.string "quand les DRESSEURS changent\p"
	.string "de place. C'est pour ça qu'on est\n"
	.string "installés ici.\p"
	.string "Désolé pour ça.$"

TrainerTower_Roof_Text_ImOwnerBattledPerfectly::
	.string "Bonjour…\p"
	.string "Je suis le propriétaire de cette\n"
	.string "TOUR.\p"
	.string "La vue qu'on a depuis le toit\n"
	.string "frise la perfection…\p"
	.string "Ta façon de combattre aussi,\n"
	.string "c'était formidable…$"

TrainerTower_Roof_Text_ThisIsForYou::
	.string "C'est pour toi…$"

TrainerTower_Roof_Text_DoneItInRecordTime::
	.string "Oh!\n"
	.string "Incroyable!\p"
	.string "C'est incroyable de te voir arriver\n"
	.string "ici aussi vite!\p"
	.string "C'est même un temps record…\p"
	.string "Je vais l'afficher à la réception.$"

TrainerTower_Roof_Text_TookSweetTimeGettingHere::
	.string "On dirait que tu as pris ton\n"
	.string "temps pour venir…$"

TrainerTower_Roof_Text_IdLikeToSeeBetterTime::
	.string "Je sais que tu peux faire un\n"
	.string "meilleur temps…\p"
	.string "Je compte sur toi.\p"
	.string "A la prochaine alors…$"

TrainerTower_Text_XMinYZSec::
	.string "{STR_VAR_1} min. {STR_VAR_2},{STR_VAR_3} sec.$"

TrainerTower_Lobby_Text_HereAreTheResults::
	.string "せいせきひょうです$"

TrainerTower_Lobby_Text_NeedTwoMonsForDouble::
	.string "C'est un combat deux contre deux.\p"
	.string "Vous ne pouvez pas combattre\n"
	.string "avec un seul POKéMON.$"

TrainerTower_Lobby_Text_ExplainTrainerTower::
	.string "A la TOUR DRESSEURS, il y a\n"
	.string "une épreuve de CONTRE-LA-MONTRE.\p"
	.string "Le chronomètre partira à partir\n"
	.string "d'ici et jusqu'au PROPRIETAIRE qui\p"
	.string "se trouve sur le toit. Les\n"
	.string "meilleurs temps sont affichés ici.\p"
	.string "Essayez d'affronter des amis pour\n"
	.string "voir qui est le plus rapide.\p"
	.string "Vous ne gagnerez pas de points\n"
	.string "EXP. ni d'argent en battant\p"
	.string "ces DRESSEURS.$"

TrainerTower_Lobby_Text_ThanksForCompeting::
	.string "Merci de participer!$"

TrainerTower_Lobby_Text_WonderWhatKindsOfTrainers::
	.string "Je suis ici pour voir à quel point\n"
	.string "je suis douée.\p"
	.string "Je me demande quel type de\n"
	.string "DRESSEUR peut bien m'attendre.\p"
	.string "C'est stressant.$"

TrainerTower_Lobby_Text_StairsTougherThanAnyBattle::
	.string "… … …\p"
	.string "Ces escaliers… …\p"
	.string "Je suis épuisé avant d'avoir\n"
	.string "combattu…$"

