@ All Trainer Tower text (Lobby and Roof) is interleaved here

TrainerTower_Lobby_Text_WelcomeToTrainerTower::
    .ifdef ENGLISH
    .string "Hello!\p"
    .string "Welcome to TRAINER TOWER where\n"
    .string "TRAINERS gather from all over!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola!\p"
    .string "¡Ésta es la TORRE DESAFÍO, punto\n"
    .string "de encuentro de ENTRENADORES\l"
    .string "de todos sitios!$"
    .endif

TrainerTower_Lobby_Text_TrainersUpToFloorNum::
    .ifdef ENGLISH
    .string "TRAINERS from all over the world\n"
    .string "gather here to battle.\p"
    .string "Let me see…\p"
    .string "Right now, there are TRAINERS only\n"
    .string "up to Floor {STR_VAR_1}.$"
    .endif
    .ifdef SPANISH
    .string "Aquí vienen ENTRENADORES de todo\n"
    .string "el mundo para luchar.\p"
    .string "A ver, ahora mismo...\p"
    .string "Hay ENTRENADORES hasta\n"
    .string "el piso {STR_VAR_1}.$"
    .endif

TrainerTower_Lobby_Text_TrainersUpEighthFloor::
    .ifdef ENGLISH
    .string "TRAINERS are awaiting your\n"
    .string "challenge up to the eighth floor.$"
    .endif
    .ifdef SPANISH
    .string "Hay ENTRENADORES esperándote\n"
    .string "para luchar hasta el octavo piso.$"
    .endif

TrainerTower_Lobby_Text_LikeToChallengeTrainers::
    .ifdef ENGLISH
    .string "Would you like to challenge the\n"
    .string "waiting TRAINERS?$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres enfrentarte a ellos?$"
    .endif

TrainerTower_Lobby_Text_StartClockGetSetGo::
    .ifdef ENGLISH
    .string "Okay, I'll get the clock started,\n"
    .string "so give it everything you have.\p"
    .string "On your marks…\p"
    .string "Get set…\p"
    .string "Go!$"
    .endif
    .ifdef SPANISH
    .string "Muy bien, voy a poner el reloj\n"
    .string "en hora. ¡A por todas!\p"
    .string "A sus puestos...\p"
    .string "Preparados..., listos...\p"
    .string "¡Ya!$"
    .endif

TrainerTower_Lobby_Text_PleaseVisitUsAgain::
    .ifdef ENGLISH
    .string "Please do visit us again!$"
    .endif
    .ifdef SPANISH
    .string "¡Vuelve cuando quieras!$"
    .endif

TrainerTower_Lobby_Text_TooBadComeBackTryAgain::
    .ifdef ENGLISH
    .string "That was too bad.\p"
    .string "I think you put in a tremendous\n"
    .string "effort in your battling.\p"
    .string "Please come back and try again!$"
    .endif
    .ifdef SPANISH
    .string "Qué pena...\p"
    .string "La verdad es que te has esforzado\n"
    .string "mucho.\p"
    .string "¡Bueno, otra vez será!$"
    .endif

TrainerTower_Lobby_Text_GiveItYourBest::
    .ifdef ENGLISH
    .string "I hope you give it your best.$"
    .endif
    .ifdef SPANISH
    .string "¡Demuestra lo que sabes!$"
    .endif

TrainerTower_Lobby_Text_MoveCounterHereWhenTrainersSwitch::
    .ifdef ENGLISH
    .string "When the TRAINERS switch places,\n"
    .string "the movement can be hectic.\p"
    .string "To avoid the stampede, we moved\n"
    .string "the reception counter here.\p"
    .string "I'm sorry for the inconvenience.$"
    .endif
    .ifdef SPANISH
    .string "Cuando los ENTRENADORES se\n"
    .string "cambian de sitio, organizan una...\l"
    .string "tremenda.\p"
    .string "Para evitar tanto follón pusimos\n"
    .string "la recepción aquí.\p"
    .string "Disculpa las molestias.$"
    .endif

TrainerTower_Roof_Text_ImOwnerBattledPerfectly::
    .ifdef ENGLISH
    .string "Hello…\p"
    .string "I am the owner of this TOWER…\p"
    .string "How the sky soars above this\n"
    .string "rooftop…\p"
    .string "The caress of the winds up here…\p"
    .string "It's all so perfect…\p"
    .string "The way you battled…\n"
    .string "It, too, was perfection…$"
    .endif
    .ifdef SPANISH
    .string "Hola.\p"
    .string "Soy el dueño de esta TORRE.\p"
    .string "La forma en que el cielo se\n"
    .string "extiende por encima de nosotros...\p"
    .string "La manera en que nos acaricia\n"
    .string "el viento...\p"
    .string "¡Es una maravilla!...\p"
    .string "Y la forma en que has luchado...\n"
    .string "es también espectacular...$"
    .endif

TrainerTower_Roof_Text_ThisIsForYou::
    .ifdef ENGLISH
    .string "This is for you…$"
    .endif
    .ifdef SPANISH
    .string "Esto es para ti...$"
    .endif

TrainerTower_Roof_Text_DoneItInRecordTime::
    .ifdef ENGLISH
    .string "Oh!\n"
    .string "Stupendous!\p"
    .string "It's marvelous how you've come up\n"
    .string "here so quickly.\p"
    .string "The fact is, you've done it in\n"
    .string "record time…\p"
    .string "I'll have your record posted at\n"
    .string "the reception counter.$"
    .endif
    .ifdef SPANISH
    .string "¡Estupendo!\n"
    .string "¡Maravilloso!\p"
    .string "¡Es extraordinario que hayas\n"
    .string "llegado tan rápido!\p"
    .string "La cosa es que lo has conseguido\n"
    .string "en tiempo récord...\p"
    .string "Voy a ponerlo junto a uno de los\n"
    .string "mostradores de la recepción.$"
    .endif

TrainerTower_Roof_Text_TookSweetTimeGettingHere::
    .ifdef ENGLISH
    .string "You seem to have taken your sweet\n"
    .string "time getting here…$"
    .endif
    .ifdef SPANISH
    .string "Se ve que no te has dado mucha\n"
    .string "prisa en llegar hasta aquí...$"
    .endif

TrainerTower_Roof_Text_IdLikeToSeeBetterTime::
    .ifdef ENGLISH
    .string "What I would like to see is a\n"
    .string "better time out of you…\p"
    .string "I'm counting on you.\p"
    .string "Until then, farewell…$"
    .endif
    .ifdef SPANISH
    .string "Me gustaría ver que consigues\n"
    .string "un tiempo mejor...\p"
    .string "Espero que no me defraudes.\p"
    .string "Nos vemos.$"
    .endif

TrainerTower_Text_XMinYZSec::
    .ifdef ENGLISH
    .string "{STR_VAR_1} min. {STR_VAR_2}.{STR_VAR_3} sec.$"
    .endif
    .ifdef SPANISH
    .string "{STR_VAR_1} min {STR_VAR_2},{STR_VAR_3} s$"
    .endif

TrainerTower_Lobby_Text_HereAreTheResults::
    .string "せいせきひょうです$"

TrainerTower_Lobby_Text_NeedTwoMonsForDouble::
    .ifdef ENGLISH
    .string "This is a two-on-two battle.\p"
    .string "You may not battle unless you have\n"
    .string "at least two POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "Esto es un combate doble.\p"
    .string "Si no tienes dos POKéMON,\n"
    .string "no podrás participar.$"
    .endif

TrainerTower_Lobby_Text_ExplainTrainerTower::
    .ifdef ENGLISH
    .string "Here at TRAINER TOWER, there is an\n"
    .string "event called TIME ATTACK.\p"
    .string "You will be timed on how quickly\n"
    .string "you can get from the reception\l"
    .string "counter to the OWNER on the roof.\p"
    .string "The best times will be recorded on\n"
    .string "the Time Board.\p"
    .string "Try competing with friends to see\n"
    .string "who can beat it the fastest.\p"
    .string "You will not earn any EXP. Points\n"
    .string "or money by beating TRAINERS here.$"
    .endif
    .ifdef SPANISH
    .string "En la TORRE DESAFÍO, se lucha\n"
    .string "a CONTRARRELOJ.\p"
    .string "Cronometraremos lo que tardes\n"
    .string "en alcanzar al DUEÑO en el último\l"
    .string "piso, en cuanto dejes la recepción.\p"
    .string "Los mejores tiempos podrán verse\n"
    .string "en el marcador.\p"
    .string "Compite con tus amigos para ver\n"
    .string "quién tarda menos.\p"
    .string "¡Ah, piensa que aquí no se ganan\n"
    .string "puntos de EXP. ni dinero!$"
    .endif

TrainerTower_Lobby_Text_ThanksForCompeting::
    .ifdef ENGLISH
    .string "Thank you for competing!$"
    .endif
    .ifdef SPANISH
    .string "¡Gracias por participar!$"
    .endif

TrainerTower_Lobby_Text_WonderWhatKindsOfTrainers::
    .ifdef ENGLISH
    .string "I'm here to see how good I am.\p"
    .string "I wonder what kinds of TRAINERS\n"
    .string "are waiting for me?\p"
    .string "It's nerve-racking!$"
    .endif
    .ifdef SPANISH
    .string "Yo he venido para ver lo fuerte\n"
    .string "que soy.\p"
    .string "¿Cómo serán los ENTRENADORES con\n"
    .string "los que me tendré que enfrentar?\p"
    .string "¡Qué nervios!$"
    .endif

TrainerTower_Lobby_Text_StairsTougherThanAnyBattle::
    .ifdef ENGLISH
    .string "Gasp, gasp…\n"
    .string "Gasp…\p"
    .string "Never mind battling! These stairs…\n"
    .string "They're tougher than any battle…$"
    .endif
    .ifdef SPANISH
    .string "Uffffff...\n"
    .string "Estoy agotado...\p"
    .string "¡No por los combates, no!\n"
    .string "¡Es por las escaleras!...\l"
    .string "¡Son peores que las peleas!$"
    .endif

