PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .string "¡Los POKéMON aprenden nuevos\n"
    .string "ataques a medida que crecen!\p"
    .string "¡Pero hay ciertos ataques que\n"
    .string "hay que enseñarles!$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .string "¡Los POKéMON serán más fáciles\n"
    .string "de atrapar si están heridos o\l"
    .string "dormidos!\p"
    .string "¡Pero no siempre es así!$"
