PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
    .ifdef ENGLISH
    .string "POKéMON learn new techniques as\n"
    .string "they grow.\p"
    .string "But some moves must be taught to\n"
    .string "them by people.$"
    .endif
    .ifdef SPANISH
    .string "¡Los POKéMON aprenden nuevos\n"
    .string "ataques a medida que crecen!\p"
    .string "¡Pero hay ciertos ataques que\n"
    .string "hay que enseñarles!$"
    .endif

PewterCity_House2_Text_MonsEasierCatchIfStatused::
    .ifdef ENGLISH
    .string "A POKéMON becomes easier to \n"
    .string "catch if it has a status problem.\p"
    .string "Sleep, poison, burn, or paralysis…\n"
    .string "Those are all effective.\p"
    .string "But catching POKéMON is never\n"
    .string "a sure thing!$"
    .endif
    .ifdef SPANISH
    .string "¡Los POKéMON serán más fáciles\n"
    .string "de atrapar si están heridos o\l"
    .string "dormidos!\p"
    .string "¡Pero no siempre es así!$"
    .endif

