PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
	.string "Mit wachsender Erfahrung lernen\n"
	.string "POKéMON neue Attacken!\p"
	.string "Manche Attacken kann ihnen jedoch\n"
	.string "nur ein TRAINER beibringen!$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
	.string "POKéMON sind einfacher zu fangen,\n"
	.string "wenn sie verletzt sind oder\l"
	.string "schlafen!\p"
	.string "Trotzdem gibt es keine\n"
	.string "Erfolgsgarantie!$"

