ThreeIsland_House5_Text_ImNotLostelle::
    .ifdef ENGLISH
    .string "Me?\n"
    .string "I'm not LOSTELLE.\p"
    .string "She's probably gone to the\n"
    .string "BERRY FOREST, I think.\p"
    .string "She picks BERRIES there for making\n"
    .string "lunch.$"
    .endif
    .ifdef SPANISH
    .string "¿Yo?\n"
    .string "No, yo no soy PEDRITA.\p"
    .string "Yo creo que se ha ido al BOSQUE\n"
    .string "BAYA.\p"
    .string "Se dedica a recoger BAYAS para\n"
    .string "hacer la comida.$"
    .endif

ThreeIsland_House5_Text_IllGoPlayWithLostelle::
    .ifdef ENGLISH
    .string "I think I'll go play with LOSTELLE\n"
    .string "today.$"
    .endif
    .ifdef SPANISH
    .string "Creo que voy a irme a jugar\n"
    .string "con PEDRITA.$"
    .endif

