PokemonLeague_LoreleisRoom_Text_Intro::
    .string "Ti do il benvenuto alla LEGA\n"
    .string "POKéMON!\p"
    .string "Sono LORELEI dei SUPERQUATTRO!\p"
    .string "Nessuno conosce i POKéMON di tipo\n"
    .string "GHIACCIO come me!\p"
    .string "Il congelamento è potentissimo!\p"
    .string "Trasformerò i tuoi POKéMON in\n"
    .string "innocui ghiaccioli!\p"
    .string "Ahahah!\n"
    .string "Cominciamo?{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .string "Ti do il benvenuto alla LEGA\n"
    .string "POKéMON!\p"
    .string "Sono LORELEI dei\n"
    .string "SUPERQUATTRO! Non è la prima\l"
    .string "volta che ci vediamo!\p"
    .string "Beh, sai già cosa sto per dirti:\n"
    .string "nessuno conosce i POKéMON di tipo\l"
    .string "GHIACCIO come me!\p"
    .string "Il congelamento è potentissimo!\p"
    .string "Trasformerò i tuoi POKéMON in\n"
    .string "innocui ghiaccioli!\p"
    .string "Ahahah!\n"
    .string "Cominciamo?{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
    .string "Questo non era previsto…$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .string "Sei più forte di quanto pensassi!\n"
    .string "Vai avanti!\p"
    .string "Questo era solo un assaggio della\n"
    .string "potenza della LEGA POKéMON!$"

