PokemonLeague_LoreleisRoom_Text_Intro::
    .ifdef ENGLISH
    .string "Welcome to the POKéMON LEAGUE.\p"
    .string "I am LORELEI of the ELITE FOUR.\p"
    .string "No one can best me when it comes\n"
    .string "to icy POKéMON.\p"
    .string "Freezing moves are powerful.\p"
    .string "Your POKéMON will be at my mercy\n"
    .string "when they are frozen solid.\p"
    .string "Hahaha!\n"
    .string "Are you ready?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif
    .ifdef SPANISH
    .string "¡Ésta es la LIGA POKéMON!\p"
    .string "¡Yo soy LORELEI, del ALTO MANDO!\p"
    .string "¡Nadie me supera con los POKéMON\n"
    .string "que congelan!\p"
    .string "¡Los movimientos que hielan son\n"
    .string "muy potentes!\p"
    .string "¡Tus POKéMON estarán a mi merced\n"
    .string "cuando los congele!\p"
    .string "¡Ja! ¡Ja! ¡Ja!\n"
    .string "¿Comenzamos?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif

PokemonLeague_LoreleisRoom_Text_RematchIntro::
    .ifdef ENGLISH
    .string "Welcome to the POKéMON LEAGUE.\p"
    .string "I, LORELEI of the ELITE FOUR,\n"
    .string "have returned!\p"
    .string "You know how it goes.\n"
    .string "No one can best me when it comes\l"
    .string "to icy POKéMON.\p"
    .string "Freezing moves are powerful.\p"
    .string "Your POKéMON will be at my mercy\n"
    .string "when they are frozen solid.\p"
    .string "Hahaha!\n"
    .string "Are you ready?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif
    .ifdef SPANISH
    .string "¡Ésta es la LIGA POKéMON!\p"
    .string "¡Yo soy LORELEI, del ALTO MANDO!\n"
    .string "¡Aquí me tienes de nuevo!\p"
    .string "¡Ya sabes que nadie me supera\n"
    .string "con los POKéMON que congelan!\p"
    .string "¡Los movimientos que hielan son\n"
    .string "muy potentes!\p"
    .string "¡Tus POKéMON estarán a mi merced\n"
    .string "cuando los congele!\p"
    .string "¡Ja! ¡Ja! ¡Ja!\n"
    .string "¿Comenzamos?{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif

PokemonLeague_LoreleisRoom_Text_Defeat::
    .ifdef ENGLISH
    .string "…Things shouldn't be this way!$"
    .endif
    .ifdef SPANISH
    .string "¡Esto no debería ser así!...$"
    .endif

PokemonLeague_LoreleisRoom_Text_PostBattle::
    .ifdef ENGLISH
    .string "You're better than I thought.\n"
    .string "Go on ahead.\p"
    .string "You only got a taste of the\n"
    .string "POKéMON LEAGUE's power.$"
    .endif
    .ifdef SPANISH
    .string "¡Eres mejor de lo que yo pensaba!\n"
    .string "¡Adelante!\p"
    .string "¡Pero la LIGA POKéMON te reserva\n"
    .string "otras sorpresas!$"
    .endif

