CeladonCity_Gym_Text_ErikaIntro::
    .ifdef ENGLISH
    .string "Hello…\n"
    .string "Lovely weather, isn't it?\l"
    .string "It's so pleasant…\p"
    .string "…Oh, dear…\n"
    .string "I must have dozed off. Welcome.\p"
    .string "My name is ERIKA.\n"
    .string "I am the LEADER of CELADON GYM.\p"
    .string "I am a student of the art of\n"
    .string "flower arranging.\p"
    .string "My POKéMON are solely of the\n"
    .string "GRASS type.\p"
    .string "…Oh, I'm sorry, I had no idea that\n"
    .string "you wished to challenge me.\p"
    .string "Very well, but I shall not lose.{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"
    .endif
    .ifdef SPANISH
    .string "¡Hola! ¡Qué buen tiempo hace!\n"
    .string "Es tan agradable.\p"
    .string "¡Ah, hola!... ¡Debo de haberme\n"
    .string "dormido! ¿Qué tal?\p"
    .string "Me llamo ERIKA. Soy la LÍDER del\n"
    .string "GIMNASIO de CIUDAD AZULONA.\p"
    .string "Enseño el arte de las flores.\n"
    .string "Mis POKéMON son del tipo PLANTA.\p"
    .string "¡Oh, perdona! ¡No tenía ni idea de\n"
    .string "que quisieras desafiarme!\p"
    .string "¡Como quieras! ¡No pienso perder!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif

CeladonCity_Gym_Text_ErikaDefeat::
    .ifdef ENGLISH
    .string "Oh!\n"
    .string "I concede defeat.\l"
    .string "You are remarkably strong.\p"
    .string "I must confer on you the\n"
    .string "RAINBOWBADGE.$"
    .endif
    .ifdef SPANISH
    .string "¡Reconozco mi derrota!\p"
    .string "Eres muy fuerte.\p"
    .string "Te voy a dar la MEDALLA ARCOIRIS.$"
    .endif

CeladonCity_Gym_Text_ErikaPostBattle::
    .ifdef ENGLISH
    .string "You are cataloging POKéMON?\n"
    .string "I must say I'm impressed.\p"
    .string "I would never collect POKéMON if\n"
    .string "they were unattractive.$"
    .endif
    .ifdef SPANISH
    .string "¿Estás estudiando a los POKéMON?\n"
    .string "Admito que me has impresionado.\p"
    .string "No coleccionaría POKéMON si\n"
    .string "fueran feos.$"
    .endif

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis::
    .ifdef ENGLISH
    .string "The RAINBOWBADGE will make\n"
    .string "POKéMON up to Lv. 50 obey.\p"
    .string "It also allows POKéMON to use\n"
    .string "STRENGTH in and out of battle.\p"
    .string "Please also take this with you.$"
    .endif
    .ifdef SPANISH
    .string "La MEDALLA ARCOIRIS hará que los\n"
    .string "POKéMON de nivel inferior a 50 te\l"
    .string "obedezcan.\p"
    .string "Y permitirá que los POKéMON usen\n"
    .string "FUERZA siempre que quieras.\p"
    .string "¡Ah, llévate esto también!$"
    .endif

CeladonCity_Gym_Text_ReceivedTM19FromErika::
    .ifdef ENGLISH
    .string "{PLAYER} received TM19\n"
    .string "from ERIKA.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió la MT19\n"
    .string "de manos de ERIKA!$"
    .endif

CeladonCity_Gym_Text_ExplainTM19::
    .ifdef ENGLISH
    .string "TM19 contains GIGA DRAIN.\p"
    .string "Half the damage it inflicts is\n"
    .string "drained to heal your POKéMON.\p"
    .string "Wouldn't you agree that it's a\n"
    .string "wonderful move?$"
    .endif
    .ifdef SPANISH
    .string "La MT19 contiene GIGADRENADO.\p"
    .string "La mitad del daño que produce es\n"
    .string "usado para curar a tus POKéMON.\p"
    .string "No me digas que no es estupenda.$"
    .endif

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
    .ifdef ENGLISH
    .string "You should make room for this.$"
    .endif
    .ifdef SPANISH
    .string "Deberías hacerle sitio a esto.$"
    .endif

CeladonCity_Gym_Text_KayIntro::
    .ifdef ENGLISH
    .string "I should tell you about this GYM.\p"
    .string "Only real ladies are allowed in\n"
    .string "here!$"
    .endif
    .ifdef SPANISH
    .string "¿Sabes una cosa de este GIMNASIO?\p"
    .string "¡Es sólo para chicas!$"
    .endif

CeladonCity_Gym_Text_KayDefeat::
    .ifdef ENGLISH
    .string "You're too rough!$"
    .endif
    .ifdef SPANISH
    .string "¡Eres demasiado fuerte!$"
    .endif

CeladonCity_Gym_Text_KayPostBattle::
    .ifdef ENGLISH
    .string "Bleaah!\n"
    .string "I hope ERIKA wipes you out!$"
    .endif
    .ifdef SPANISH
    .string "¡Eeeh!\n"
    .string "¡Espero que ERIKA acabe contigo!$"
    .endif

CeladonCity_Gym_Text_BridgetIntro::
    .ifdef ENGLISH
    .string "Oh, welcome.\n"
    .string "I was getting bored.$"
    .endif
    .ifdef SPANISH
    .string "Ah, hola.\n"
    .string "Estaba empezando a aburrirme.$"
    .endif

CeladonCity_Gym_Text_BridgetDefeat::
    .ifdef ENGLISH
    .string "My makeup!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh! ¡Mi maquillaje!$"
    .endif

CeladonCity_Gym_Text_BridgetPostBattle::
    .ifdef ENGLISH
    .string "GRASS-type POKéMON are tough\n"
    .string "against the WATER type.\p"
    .string "They also have an edge on ROCK-\n"
    .string "and GROUND-type POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Los POKéMON del tipo PLANTA\n"
    .string "son difíciles para los acuáticos!\p"
    .string "¡Y tienen ventaja sobre los del\n"
    .string "tipo ROCA y los del tipo TIERRA!$"
    .endif

CeladonCity_Gym_Text_TinaIntro::
    .ifdef ENGLISH
    .string "…Weren't you peeking in here\n"
    .string "earlier?$"
    .endif
    .ifdef SPANISH
    .string "Pero ¿tú no has estado ya por\n"
    .string "aquí?$"
    .endif

CeladonCity_Gym_Text_TinaDefeat::
    .ifdef ENGLISH
    .string "You're an eye-opener!$"
    .endif
    .ifdef SPANISH
    .string "¡Estoy impresionada!$"
    .endif

CeladonCity_Gym_Text_TinaPostBattle::
    .ifdef ENGLISH
    .string "Oh, you were looking at ERIKA…\n"
    .string "You weren't looking at me…$"
    .endif
    .ifdef SPANISH
    .string "Ah, estabas buscando a ERIKA,\n"
    .string "no a mí.$"
    .endif

CeladonCity_Gym_Text_TamiaIntro::
    .ifdef ENGLISH
    .string "Look, look!\n"
    .string "See my POKéMON!\p"
    .string "I like the GRASS type.\n"
    .string "I like how they're easy to raise.$"
    .endif
    .ifdef SPANISH
    .string "¡Mira mis POKéMON del tipo\n"
    .string "PLANTA!\p"
    .string "¡Son tan fáciles de entrenar!...$"
    .endif

CeladonCity_Gym_Text_TamiaDefeat::
    .ifdef ENGLISH
    .string "No!$"
    .endif
    .ifdef SPANISH
    .string "¡No!$"
    .endif

CeladonCity_Gym_Text_TamiaPostBattle::
    .ifdef ENGLISH
    .string "We only use GRASS-type POKéMON at\n"
    .string "our GYM.\p"
    .string "Why? We also use them for making\n"
    .string "flower arrangements!$"
    .endif
    .ifdef SPANISH
    .string "¡En nuestro GIMNASIO sólo luchamos\n"
    .string "con POKéMON del tipo PLANTA!\p"
    .string "¡Y también los usamos para hacer\n"
    .string "adornos florales!$"
    .endif

CeladonCity_Gym_Text_LisaIntro::
    .ifdef ENGLISH
    .string "Oh, hey!\p"
    .string "We don't like BUG- or FIRE-type\n"
    .string "POKéMON in here!$"
    .endif
    .ifdef SPANISH
    .string "¡Aquí no pueden entrar los POKéMON\n"
    .string "del tipo FUEGO o del tipo BICHO!$"
    .endif

CeladonCity_Gym_Text_LisaDefeat::
    .ifdef ENGLISH
    .string "Oh!\n"
    .string "You!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh!\n"
    .string "¡Cómo eres!$"
    .endif

CeladonCity_Gym_Text_LisaPostBattle::
    .ifdef ENGLISH
    .string "Our LEADER ERIKA might be quiet,\n"
    .string "but she's famous around here.$"
    .endif
    .ifdef SPANISH
    .string "¡ERIKA, nuestra LÍDER, puede\n"
    .string "parecer muy tranquila, pero es muy\l"
    .string "hábil!$"
    .endif

CeladonCity_Gym_Text_LoriIntro::
    .ifdef ENGLISH
    .string "Pleased to meet you.\n"
    .string "My hobby is POKéMON training.$"
    .endif
    .ifdef SPANISH
    .string "Encantada de conocerte. A mí\n"
    .string "me encanta entrenar POKéMON.$"
    .endif

CeladonCity_Gym_Text_LoriDefeat::
    .ifdef ENGLISH
    .string "Oh!\n"
    .string "Splendid!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh!\n"
    .string "¡Espléndido!$"
    .endif

CeladonCity_Gym_Text_LoriPostBattle::
    .ifdef ENGLISH
    .string "I have a blind date coming up.\n"
    .string "I have to learn to be polite,\l"
    .string "especially if I have to battle.$"
    .endif
    .ifdef SPANISH
    .string "Voy a tener una cita a ciegas.\n"
    .string "¡Y debo aprender buenos modales!$"
    .endif

CeladonCity_Gym_Text_MaryIntro::
    .ifdef ENGLISH
    .string "Welcome to CELADON GYM!\p"
    .string "You'd better not underestimate\n"
    .string "the nice ladies here.$"
    .endif
    .ifdef SPANISH
    .string "¡Éste es el GIMNASIO de AZULONA!\p"
    .string "¡Las encantadoras chicas que hay\n"
    .string "aquí son muy fuertes!$"
    .endif

CeladonCity_Gym_Text_MaryDefeat::
    .ifdef ENGLISH
    .string "Oh!\n"
    .string "Beaten!$"
    .endif
    .ifdef SPANISH
    .string "¡Me has ganado!$"
    .endif

CeladonCity_Gym_Text_MaryPostBattle::
    .ifdef ENGLISH
    .string "I didn't bring my best POKéMON.\n"
    .string "Wait until next time!$"
    .endif
    .ifdef SPANISH
    .string "¡No he traído a mis mejores\n"
    .string "POKéMON! ¡Ya verás la próxima\l"
    .string "vez!$"
    .endif

CeladonCity_Gym_Text_GymStatue::
    .ifdef ENGLISH
    .string "CELADON POKéMON GYM\n"
    .string "LEADER: ERIKA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de AZULONA: ERIKA\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"
    .endif

CeladonCity_Gym_Text_GymStatuePlayerWon::
    .ifdef ENGLISH
    .string "CELADON POKéMON GYM\n"
    .string "LEADER: ERIKA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de AZULONA: ERIKA\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"
    .endif

