CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink::
	.string "J'ai soif!\n"
	.string "Je voudrais boire un truc!\p"
	.string "{FONT_NORMAL}Lui offrir à boire?$"

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink::
	.string "Quelle boisson lui offrir?$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis::
	.string "Ouais ouais!\p"
	.string "De l'EAU FRAICHE!\p"
	.string "C'est cool!\n"
	.string "Tiens… c'est pour toi!$"

Text_ReceivedItemFromLittleGirl::
	.string "{PLAYER} reçoit\n"
	.string "la {STR_VAR_2}!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16::
	.string "CT16:\n"
	.string "MUR LUMIERE!\p"
	.string "C'est une capacité qui affaiblit\n"
	.string "l'attaque spéciale de l'ennemi.$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis::
	.string "Ouaiiis!\p"
	.string "Du SODA COOL!\p"
	.string "Merciiii!\n"
	.string "Tiens, prends ça!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20::
	.string "CT20:\n"
	.string "RUNE PROTECT!\p"
	.string "C'est une capacité qui empêche\n"
	.string "les problèmes de statut.$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis::
	.string "Ouaiiis!\p"
	.string "D'la LIMONADE!\p"
	.string "Merci beaucoup!\n"
	.string "V'là pour toi!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33::
	.string "CT33:\n"
	.string "PROTECTION!\p"
	.string "C'est une capacité qui affaiblit les\n"
	.string "attaques physiques de l'ennemi.$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis::
	.string "Plus de place!$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll::
	.string "Heu… Non merci.\n"
	.string "J'ai plus soif en fait!$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature::
	.string "Ma sœur est DRESSEUR.\n"
	.string "Tu le crois, ça?\p"
	.string "Mais c'est une p'tite peste!\n"
	.string "Elle m'agace!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink::
	.string "J'ai soif!\n"
	.string "Je veux boire!$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign::
	.string "TOIT:\n"
	.string "DISTRIBUTEURS$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave::
	.string "Un distributeur!\n"
	.string "Que choisir?$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney::
	.string "Oups! Pas assez d'argent!$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut::
	.string "Et hop! {STR_VAR_1}!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff::
	.string "L'inventaire est plein!$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty::
	.string "Pas soif!$"

