CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink::
    .ifdef ENGLISH
    .string "I'm thirsty!\n"
    .string "I want something to drink!\p"
    .string "{FONT_NORMAL}Give her a drink?$"
    .endif
    .ifdef SPANISH
    .string "¡Tengo sed!\n"
    .string "¡Me gustaría beber algo!\p"
    .string "{FONT_NORMAL}¿Le das algo de beber?$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink::
    .ifdef ENGLISH
    .string "Give her which drink?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué bebida quieres darle?$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis::
    .ifdef ENGLISH
    .string "Yay!\p"
    .string "FRESH WATER!\p"
    .string "Thank you!\n"
    .string "You can have this from me!$"
    .endif
    .ifdef SPANISH
    .string "¡Yay!\p"
    .string "¡AGUA!\p"
    .string "¡Gracias!\n"
    .string "¡Tómala, toda tuya!$"
    .endif

Text_ReceivedItemFromLittleGirl::
    .ifdef ENGLISH
    .string "{PLAYER} received a {STR_VAR_2}\n"
    .string "from the little girl.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió la {STR_VAR_2}\n"
    .string "de manos de la chica!$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16::
    .ifdef ENGLISH
    .string "TM16 contains LIGHT SCREEN.\p"
    .string "It's a move that weakens the power\n"
    .string "of special attacks by your foe.$"
    .endif
    .ifdef SPANISH
    .string "¡MT16 contiene PANTALLA LUZ!\p"
    .string "Reduce la fuerza de los AT. ESP.\n"
    .string "del rival.$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis::
    .ifdef ENGLISH
    .string "Yay!\p"
    .string "SODA POP!\p"
    .string "Thank you!\n"
    .string "You can have this from me!$"
    .endif
    .ifdef SPANISH
    .string "¡Genial!\p"
    .string "¡Un REFRESCO!\p"
    .string "¡Gracias!\n"
    .string "¡Tómala, toda tuya!$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20::
    .ifdef ENGLISH
    .string "TM20 contains SAFEGUARD.\p"
    .string "It's a move that prevents status\n"
    .string "problems among your POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡MT20 contiene VELO SAGRADO!\p"
    .string "Evita los problemas de estado\n"
    .string "a tus POKéMON.$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis::
    .ifdef ENGLISH
    .string "Yay!\p"
    .string "LEMONADE!\p"
    .string "Thank you!\n"
    .string "You can have this from me!$"
    .endif
    .ifdef SPANISH
    .string "¡Genial!\p"
    .string "¡LIMONADA!\p"
    .string "¡Gracias!\n"
    .string "¡Tómala, toda tuya!$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33::
    .ifdef ENGLISH
    .string "TM33 contains REFLECT.\p"
    .string "It's a move that weakens the power\n"
    .string "of physical attacks by your foe.$"
    .endif
    .ifdef SPANISH
    .string "¡La MT33 contiene REFLEJO!\p"
    .string "Reduce la fuerza de los ataques\n"
    .string "físicos del rival.$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis::
    .ifdef ENGLISH
    .string "You don't have space for this!$"
    .endif
    .ifdef SPANISH
    .string "¡No tienes sitio para esto!$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll::
    .ifdef ENGLISH
    .string "No, thank you!\n"
    .string "I'm not thirsty after all!$"
    .endif
    .ifdef SPANISH
    .string "¡No, gracias!\n"
    .string "¡Ya no tengo tanta sed!$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature::
    .ifdef ENGLISH
    .string "My sister is a TRAINER, believe it\n"
    .string "or not.\p"
    .string "But, she's so immature, she drives\n"
    .string "me nuts!$"
    .endif
    .ifdef SPANISH
    .string "Mi hermana es ENTRENADORA,\n"
    .string "¡de verdad!\p"
    .string "¡Pero es tan infantil que me vuelve\n"
    .string "loco!$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink::
    .ifdef ENGLISH
    .string "I'm thirsty!\n"
    .string "I want something to drink!$"
    .endif
    .ifdef SPANISH
    .string "¡Tengo sed!\n"
    .string "¡Me gustaría beber algo!$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_FloorSign::
    .ifdef ENGLISH
    .string "ROOFTOP SQUARE:\n"
    .string "VENDING MACHINES$"
    .endif
    .ifdef SPANISH
    .string "ÚLTIMO PISO:\n"
    .string "DISTRIBUIDORES$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave::
    .ifdef ENGLISH
    .string "A vending machine!\n"
    .string "What does it have?$"
    .endif
    .ifdef SPANISH
    .string "¡Un distribuidor!\n"
    .string "¡A ver el menú!$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney::
    .ifdef ENGLISH
    .string "Oops, not enough money!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya, no tengo suficiente dinero!$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut::
    .ifdef ENGLISH
    .string "A can of {STR_VAR_1} popped out!$"
    .endif
    .ifdef SPANISH
    .string "¡Una lata de {STR_VAR_1}!$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff::
    .ifdef ENGLISH
    .string "There's no more room for stuff!$"
    .endif
    .ifdef SPANISH
    .string "¡No tienes sitio para más cosas!$"
    .endif

CeladonCity_DepartmentStore_Roof_Text_NotThirsty::
    .ifdef ENGLISH
    .string "Not thirsty!$"
    .endif
    .ifdef SPANISH
    .string "¡No tengo sed!$"
    .endif

