CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink::
	.string "Ich bin durstig!\n"
	.string "Ich möchte etwas trinken!\p"
	.string "{FONT_NORMAL}Gibst du dem Mädchen ein Getränk?$"

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink::
	.string "Welches Getränk möchtest du ihr\n"
	.string "geben?$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis::
	.string "Ja!\p"
	.string "TAFELWASSER!\p"
	.string "Vielen Dank!\n"
	.string "Nimm bitte dieses Geschenk!$"

Text_ReceivedItemFromLittleGirl::
	.string "{PLAYER} erhält\n"
	.string "{STR_VAR_2}!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16::
	.string "TM16 ist LICHTSCHILD!\p"
	.string "Damit schwächst du die gegne-\n"
	.string "rischen Spezial-Attacken.$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis::
	.string "Cool!\p"
	.string "SPRUDEL!\p"
	.string "Vielen Dank!\n"
	.string "Nimm bitte dieses Geschenk!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20::
	.string "TM20 ist BODYGUARD!\p"
	.string "Diese Attacke verhindert\n"
	.string "Statusprobleme bei deinen\l"
	.string "POKéMON!$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis::
	.string "Cool!\p"
	.string "LIMONADE!\p"
	.string "Vielen Dank!\n"
	.string "Nimm bitte dieses Geschenk!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33::
	.string "TM33 ist REFLEKTOR!\p"
	.string "Diese Attacke schwächt\n"
	.string "physische Angriffe des Gegners.$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis::
	.string "Du hast keinen Platz dafür!$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll::
	.string "Das ist nett gemeint, aber ich habe\n"
	.string "keinen Durst!$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature::
	.string "Ob du es glaubst oder nicht: Meine\n"
	.string "Schwester ist eine TRAINERin!\p"
	.string "Aber sie ist so kindisch! Ich werde\n"
	.string "noch ganz verrückt!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink::
	.string "Ich bin durstig!\n"
	.string "Ein Königreich für ein Getränk!$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign::
	.string "DACHGARTEN:\n"
	.string "AUTOMATEN$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave::
	.string "Ein Automat!\n"
	.string "Zur Auswahl stehen:$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney::
	.string "Ups, nicht genug Geld!$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut::
	.string "Eine Flasche {STR_VAR_1} liegt im\n"
	.string "Schacht!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff::
	.string "Du kannst keine weiteren Items\n"
	.string "tragen!$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty::
	.string "Kein Durst!$"

