SSAnne_1F_Room2_Text_TylerIntro::
    .string "¡Me gustan los POKéMON!\n"
    .string "¿Y a ti?$"

SSAnne_1F_Room2_Text_TylerDefeat::
    .string "¡Guauu!\n"
    .string "¡Eres genial!$"

SSAnne_1F_Room2_Text_TylerPostBattle::
    .string "Seamos amigos, ¿vale?\p"
    .string "¡Y así podremos intercambiar\n"
    .string "POKéMON!$"

SSAnne_1F_Room2_Text_AnnIntro::
    .string "¡He atrapado POKéMON por todo\n"
    .string "el mundo!$"

SSAnne_1F_Room2_Text_AnnDefeat::
    .string "¡Vaya!\n"
    .string "¡Con lo que he viajado por ellos!$"

SSAnne_1F_Room2_Text_AnnPostBattle::
    .string "¡Les has hecho daño a mis pobres\n"
    .string "POKéMON!\p"
    .string "¡¡¡Y exijo que los cures en un\n"
    .string "CENTRO POKéMON!!!$"

SSAnne_1F_Room2_Text_CruisingAroundWorld::
    .string "¡Viajamos en crucero por todo\n"
    .string "el mundo!$"
