SSAnne_1F_Room2_Text_TylerIntro::
	.string "Ich bin total in POKéMON vernarrt!\n"
	.string "Du auch?$"

SSAnne_1F_Room2_Text_TylerDefeat::
	.string "Wow!\n"
	.string "Du bist cool!$"

SSAnne_1F_Room2_Text_TylerPostBattle::
	.string "Lass uns Freunde werden, O.K.?\p"
	.string "Dann können wir POKéMON tauschen!$"

SSAnne_1F_Room2_Text_AnnIntro::
	.string "Auf meinen Reisen um die Welt habe\n"
	.string "ich unzählige POKéMON gefangen!$"

SSAnne_1F_Room2_Text_AnnDefeat::
	.string "Nein! Ich habe die ganze Welt für\n"
	.string "diese POKéMON bereist!$"

SSAnne_1F_Room2_Text_AnnPostBattle::
	.string "So behandelt man keine POKéMON von\n"
	.string "Weltklasse!\p"
	.string "Ich verlange eine Kur in einem\n"
	.string "POKéMON-CENTER für meine\l"
	.string "POKéMON!!!$"

SSAnne_1F_Room2_Text_CruisingAroundWorld::
	.string "Wir machen eine große Weltreise!$"

