FuchsiaCity_House2_Text_DoYouLikeToFish::
    .ifdef ENGLISH
    .string "I'm the FISHING GURU's older\n"
    .string "brother.\p"
    .string "I simply looove fishing!\n"
    .string "I can't bear to go without.\p"
    .string "Tell me, do you like to fish?$"
    .endif
    .ifdef SPANISH
    .string "¡Soy el hermano mayor del GURÚ\n"
    .string "PESCADOR!\p"
    .string "¡Me encanta pescar!\p"
    .string "¿Y a ti, te gusta pescar?$"
    .endif

FuchsiaCity_House2_Text_LikeYourStyleTakeThis::
    .ifdef ENGLISH
    .string "Grand! I like your style.\n"
    .string "I think we can be friends.\p"
    .string "Take this and fish, young friend!$"
    .endif
    .ifdef SPANISH
    .string "¡Fenomenal!\n"
    .string "¡Me gusta tu estilo!\p"
    .string "¡Toma esto y pesca, anda!$"
    .endif

FuchsiaCity_House2_Text_ReceivedGoodRod::
    .ifdef ENGLISH
    .string "{PLAYER} received a GOOD ROD from\n"
    .string "the FISHING GURU's brother.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió una CAÑA BUENA\n"
    .string "de manos del hermano del GURÚ\l"
    .string "PESCADOR!$"
    .endif

FuchsiaCity_House2_Text_GoodRodCanCatchBetterMons::
    .ifdef ENGLISH
    .string "Fishing is a way of life!\n"
    .string "It is like the finest poetry.\p"
    .string "A crummy OLD ROD could only catch\n"
    .string "MAGIKARP, yes?\p"
    .string "But with a GOOD ROD, you can\n"
    .string "catch much better POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡La pesca es una forma de vida!\n"
    .string "¡Es un arte!\p"
    .string "Con una CAÑA VIEJA de nada, lo\n"
    .string "máximo que se puede pescar es\l"
    .string "un MAGIKARP, ¿no?\p"
    .string "Pero con una CAÑA BUENA se pueden\n"
    .string "pescar POKéMON mucho mejores.$"
    .endif

FuchsiaCity_House2_Text_OhThatsDisappointing::
    .ifdef ENGLISH
    .string "Oh…\n"
    .string "That's so disappointing…$"
    .endif
    .ifdef SPANISH
    .string "Oh...\n"
    .string "Estoy tan decepcionado...$"
    .endif

FuchsiaCity_House2_Text_HowAreTheFishBiting::
    .ifdef ENGLISH
    .string "Hello there, {PLAYER}!\p"
    .string "How are the fish biting?$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, {PLAYER}!\p"
    .string "¿Qué, pican los peces?$"
    .endif

FuchsiaCity_House2_Text_YouHaveNoRoomForGift::
    .ifdef ENGLISH
    .string "Oh, no!\p"
    .string "I had a gift for you, but you have\n"
    .string "no room for it!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh, no!\p"
    .string "¡Tenía un regalo para ti, pero no\n"
    .string "tienes sitio!$"
    .endif

