FuchsiaCity_House2_Text_DoYouLikeToFish::
	.string "Ich bin der\n"
	.string "ältere Bruder des\l"
	.string "PROFIANGLERS!\p"
	.string "Ich liebe\n"
	.string "den Angelsport!\p"
	.string "Angelst du auch\n"
	.string "gerne?$"

FuchsiaCity_House2_Text_LikeYourStyleTakeThis::
	.string "Klasse! Du bist\n"
	.string "mir sympathisch!\p"
	.string "Nimm das hier\n"
	.string "und gehe angeln!$"

FuchsiaCity_House2_Text_ReceivedGoodRod::
	.string "{PLAYER} erhält\n"
	.string "eine PROFIANGEL!$"

FuchsiaCity_House2_Text_GoodRodCanCatchBetterMons::
	.string "Angeln ist meine Leidenschaft!\n"
	.string "Es ist ein Gedicht.\p"
	.string "Mit einer ANGEL fängst du nur\n"
	.string "KARPADOR!\p"
	.string "Aber mit der PROFIANGEL kannst\n"
	.string "du bessere POKéMON fangen.$"

FuchsiaCity_House2_Text_OhThatsDisappointing::
	.string "Oh!\n"
	.string "Das ist so enttäuschend...$"

FuchsiaCity_House2_Text_HowAreTheFishBiting::
	.string "Hallo, {PLAYER}!\p"
	.string "Wie beißen die Fische?$"

FuchsiaCity_House2_Text_YouHaveNoRoomForGift::
	.string "Oh nein!\p"
	.string "Ich habe ein Geschenk für dich!\n"
	.string "Aber du kannst nichts mehr tragen!$"

