IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .ifdef ENGLISH
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "At the POKéMON LEAGUE, you will\n"
    .string "face the ELITE FOUR all in a row.\p"
    .string "If you lose, you have to start all\n"
    .string "over again!\p"
    .string "This is it!\n"
    .string "Go for it!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, aspirante al título!\p"
    .string "En la LIGA POKéMON tendrás que\n"
    .string "luchar contra todos los miembros\l"
    .string "del ALTO MANDO, uno tras otro.\p"
    .string "¡Si pierdes, tendrás que volver\n"
    .string "a empezar!\p"
    .string "¡Eso es todo!\n"
    .string "¡A por ellos!$"
    .endif

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck::
    .ifdef ENGLISH
    .string "From here on, you face the\n"
    .string "ELITE FOUR one by one.\p"
    .string "If you win, a door opens to the\n"
    .string "next TRAINER. Good luck!$"
    .endif
    .ifdef SPANISH
    .string "¡Ahora lucharás contra todos los\n"
    .string "del ALTO MANDO, sin excepción!\p"
    .string "¡Si ganas, se abrirá una puerta\n"
    .string "y pasarás al siguiente ENTRENADOR!\l"
    .string "¡Buena suerte!$"
    .endif

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .ifdef ENGLISH
    .string "I am so sorry, but you've wasted\n"
    .string "your time coming here.\p"
    .string "LORELEI of the ELITE FOUR is\n"
    .string "absent, you see.\p"
    .string "As a result, the POKéMON LEAGUE is\n"
    .string "closed for the time being.$"
    .endif
    .ifdef SPANISH
    .string "Lo siento, pero has perdido\n"
    .string "el tiempo viniendo hasta aquí.\p"
    .string "LORELEI, del ALTO MANDO,\n"
    .string "no está, como puedes comprobar.\p"
    .string "Así que la LIGA POKéMON está\n"
    .string "cerrada de momento.$"
    .endif

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
    .ifdef ENGLISH
    .string "AGATHA's GHOST-type POKéMON are\n"
    .string "horrifically terrifying in toughness.\p"
    .string "I took my FIGHTING-type POKéMON\n"
    .string "and raised them to the max.\p"
    .string "I went at AGATHA feeling pretty\n"
    .string "confident, but she whupped us.\p"
    .string "That old lady's also got a really\n"
    .string "short fuse, too.\p"
    .string "It doesn't take anything to get\n"
    .string "that scary lady hollering.$"
    .endif
    .ifdef SPANISH
    .string "Los POKéMON de tipo FANTASMA\n"
    .string "de AGATHA son escalofriantemente\l"
    .string "fuertes.\p"
    .string "Yo me puse a criar a mis POKéMON\n"
    .string "del tipo LUCHA con todas las ganas\l"
    .string "del mundo...\p"
    .string "Y me planté ante AGATHA convencido\n"
    .string "de que podría ganar... y no quiero\l"
    .string "ni contarte la paliza que me dio.\p"
    .string "Además, ¡no sabes el genio que\n"
    .string "tiene la señora!\p"
    .string "¡Como empiece a gritar, lo llevas\n"
    .string "claro!$"
    .endif


IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
    .ifdef ENGLISH
    .string "Maybe becoming an ELITE FOUR\n"
    .string "member is in the blood.\p"
    .string "From what I've heard, LANCE has\n"
    .string "a cousin who's a GYM LEADER\l"
    .string "somewhere far away.$"
    .endif
    .ifdef SPANISH
    .string "Yo creo que lo de ser del ALTO\n"
    .string "MANDO se lleva en la sangre.\p"
    .string "Por lo que sé, un primo de LANCE\n"
    .string "es también LÍDER de un GIMNASIO\l"
    .string "de por ahí.$"
    .endif

