Text_MetronomeTeach::
	.string "Tak-tak-tak!\n"
	.string "Ich kann einem POKéMON eine\l"
	.string "tolle Attacke beibringen!\p"
	.string "Die Attacke heißt METRONOM!\n"
	.string "Könnte sie dir gefallen?$"

Text_MetronomeDeclined::
	.string "Ich sage dir, es macht viel Spaß!$"

Text_MetronomeWhichMon::
	.string "O.K.! Welches POKéMON\n"
	.string "soll sie erlernen?$"

Text_MetronomeTaught::
	.string "Tak-tak-tak!\n"
	.string "So klingt ein METRONOM!\p"
	.string "Damit setzt dein POKéMON Attacken\n"
	.string "ein, die es gar nicht kennt!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe::
	.string "Hallo!\p"
	.string "Ich leite hier die Forschungen!\p"
	.string "Wir erforschen Fossilien von\n"
	.string "URZEIT-POKéMON!\p"
	.string "Hast du ein Fossil für mich?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
	.string "Nein?\n"
	.string "Zu schade!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP::
	.string "ちょっと　じかん　かかるよ！\p"
	.string "そこらへんを　すこし\n"
	.string "ブラブラ　してくると　よろしー！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
	.string "Wo warst du? Wir haben\n"
	.string "dein Fossil wieder belebt!\p"
	.string "Ein {STR_VAR_1}, ganz wie ich es\n"
	.string "vermutet habe!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
	.string "{PLAYER} erhält\n"
	.string "{STR_VAR_1}!$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon::
	.string "ポケモン　いっぱいで　もてないね！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
	.string "Oh!\n"
	.string "Das ist ein {STR_VAR_2}!\p"
	.string "Es ist ein Fossil von {STR_VAR_1},\n"
	.string "einem schon lange ausgestorbenen\l"
	.string "POKéMON!\p"
	.string "Dank modernster Technik können wir\n"
	.string "POKéMON aus Fossilien\l"
	.string "wieder beleben!$"

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
	.string "Gib es schnell her, damit ich\n"
	.string "fortfahren kann!\p"
	.string "{FONT_NORMAL}{PLAYER} übergibt das\n"
	.string "{STR_VAR_2}!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
	.string "Es wird einige Zeit dauern!\n"
	.string "Komm einfach später wieder vorbei!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
	.string "Du bist jederzeit willkommen!$"

