Text_MetronomeTeach::
    .ifdef ENGLISH
    .string "Tch-tch-tch!\n"
    .string "I'll teach you a nifty move.\p"
    .string "Teach it to a POKéMON, and watch\n"
    .string "the fun unfold!\p"
    .string "It's a move called METRONOME.\n"
    .string "Does it strike your fancy?$"
    .endif
    .ifdef SPANISH
    .string "¡Tac-tac-tac! Voy a enseñarte\n"
    .string "un movimiento estupendo.\p"
    .string "Enséñaselo a un POKéMON,\n"
    .string "verás qué guay es.\p"
    .string "Se llama METRÓNOMO, no me\n"
    .string "digas que no suena bien...$"
    .endif

Text_MetronomeDeclined::
    .ifdef ENGLISH
    .string "I tell you, it's a lot of fun!$"
    .endif
    .ifdef SPANISH
    .string "Te lo digo, es el no va más.$"
    .endif

Text_MetronomeWhichMon::
    .ifdef ENGLISH
    .string "Okay!\n"
    .string "Which POKéMON should I teach?$"
    .endif
    .ifdef SPANISH
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe METRÓNOMO?$"
    .endif

Text_MetronomeTaught::
    .ifdef ENGLISH
    .string "Tch-tch-tch!\n"
    .string "That's the sound of a METRONOME.\p"
    .string "It tweaks your POKéMON's brain into\n"
    .string "using moves it doesn't even know.$"
    .endif
    .ifdef SPANISH
    .string "¡Tac-tac-tac!\n"
    .string "¡Ése es el sonido de un METRÓNOMO!\p"
    .string "¡Lleva al POKéMON a usar ataques\n"
    .string "que no conoce!$"
    .endif

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe::
    .ifdef ENGLISH
    .string "Hiya!\p"
    .string "I am important doctor.\n"
    .string "Yes, very much so, indeed.\p"
    .string "Here, I study rare POKéMON fossils.\n"
    .string "All the time, I study.\p"
    .string "You!\n"
    .string "Have you a fossil for me?$"
    .endif
    .ifdef SPANISH
    .string "¡Hola!\p"
    .string "¡Soy un científico muy importante!\n"
    .string "Mucho, sí, sí.\p"
    .string "¡Y me dedico a estudiar fósiles\n"
    .string "de POKéMON raros!\p"
    .string "¿Tienes algún fósil para mí?$"
    .endif

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
    .ifdef ENGLISH
    .string "No!\n"
    .string "Is too bad!$"
    .endif
    .ifdef SPANISH
    .string "¡No!\n"
    .string "¡Qué pena!$"
    .endif

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP::
    .string "ちょっと　じかん　かかるよ！\p"
    .string "そこらへんを　すこし\n"
    .string "ブラブラ　してくると　よろしー！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
    .ifdef ENGLISH
    .string "You late.\n"
    .string "Where were you?\p"
    .string "Your fossil is back to life!\n"
    .string "It was {STR_VAR_1} like I think!$"
    .endif
    .ifdef SPANISH
    .string "¿Dónde estabas?\p"
    .string "¡Tu fósil ha revivido!\n"
    .string "¡Sabía que era un {STR_VAR_1}!$"
    .endif

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
    .ifdef ENGLISH
    .string "{PLAYER} received the {STR_VAR_1}\n"
    .string "from the doctor.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió {STR_VAR_1}\n"
    .string "de manos del científico!$"
    .endif

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon::
    .string "ポケモン　いっぱいで　もてないね！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
    .ifdef ENGLISH
    .string "Oh!\n"
    .string "That is {STR_VAR_2}, it is!\p"
    .string "It is fossil of {STR_VAR_1},\n"
    .string "a POKéMON that is already extinct!\p"
    .string "My Resurrection Machine will make\n"
    .string "that POKéMON live again!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh! ¡Es un {STR_VAR_2}!\p"
    .string "¡Es un fósil de {STR_VAR_1},\n"
    .string "un POKéMON ya extinto!\p"
    .string "¡Mi máquina recuperadora\n"
    .string "hará que este POKéMON reviva!$"
    .endif

@ TODO: Resolve text dump error below?
CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
    .ifdef ENGLISH
    .string "So!\n"
    .string "You hurry and give me that!\p"
    .string "{FONT_NORMAL}{PLAYER} handed over the\n"
    .string "{STR_VAR_2} to the weird doctor.$"
    .endif
    .ifdef SPANISH
    .string "¡Date prisa y dame eso!\p"
    .string "{FONT_NORMAL}¡{PLAYER} le dio {STR_VAR_2}\n"
    .string "al extraño científico!$"
    .endif

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
    .ifdef ENGLISH
    .string "I take a little time!\n"
    .string "You go for walk a little while!$"
    .endif
    .ifdef SPANISH
    .string "¡Tardaré un poco!\p"
    .string "¡Date un paseo mientras tanto!$"
    .endif

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
    .ifdef ENGLISH
    .string "Aiyah!\n"
    .string "You come again!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh!\n"
    .string "¡Has venido a molestarme!$"
    .endif

