Route21_North_Text_RonaldIntro::
    .ifdef ENGLISH
	.string "You want to know if the fish are\n"
	.string "biting?$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres saber si los peces pican?$"
    .endif

Route21_North_Text_RonaldDefeat::
    .ifdef ENGLISH
	.string "Dang!$"
    .endif
    .ifdef SPANISH
    .string "¡Vale, vale!$"
    .endif

Route21_North_Text_RonaldPostBattle::
    .ifdef ENGLISH
	.string "I can't catch anything good.\n"
	.string "Not one good POKéMON to be had!$"
    .endif
    .ifdef SPANISH
    .string "¡No puedo pescar nada bueno!\n"
    .string "¡No hay ni un POKéMON bueno!$"
    .endif

Route21_North_Text_WadeIntro::
    .ifdef ENGLISH
	.string "I got a big haul!\n"
	.string "Wanna go for it?$"
    .endif
    .ifdef SPANISH
    .string "¡Tengo una gran red!\n"
    .string "¿Quieres probarla?$"
    .endif

Route21_North_Text_WadeDefeat::
    .ifdef ENGLISH
	.string "Heheh, MAGIKARP just don't make\n"
	.string "the grade, do they?$"
    .endif
    .ifdef SPANISH
    .string "¡MAGIKARP, qué bochorno!$"
    .endif

Route21_North_Text_WadePostBattle::
    .ifdef ENGLISH
	.string "I seem to only catch MAGIKARP!$"
    .endif
    .ifdef SPANISH
    .string "¡Se ve que sólo pesco MAGIKARP!$"
    .endif

Route21_North_Text_SpencerIntro::
    .ifdef ENGLISH
	.string "The sea cleanses my body and soul!$"
    .endif
    .ifdef SPANISH
    .string "¡El mar limpia mi cuerpo y mi\n"
    .string "alma!$"
    .endif

Route21_North_Text_SpencerDefeat::
    .ifdef ENGLISH
	.string "Ayah!$"
    .endif
    .ifdef SPANISH
    .string "¡Aaayyy!$"
    .endif

Route21_North_Text_SpencerPostBattle::
    .ifdef ENGLISH
	.string "The sea is great and all, but I\n"
	.string "like the mountains, too.$"
    .endif
    .ifdef SPANISH
    .string "¡A mí también me gusta la montaña!$"
    .endif

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro::
	.string "おれだって　たまには\n"
	.string "およぎに　くるぜ！$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat::
	.string "ぐわわ！$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle::
	.string "うきやすそう　だと？\n"
	.string "うるせー　おおきな　おせわだッ！$"
