Route21_North_Text_RonaldIntro::
    .string "Vuoi sapere se i pesci abboccano?$"

Route21_North_Text_RonaldDefeat::
    .string "Che botta!$"

Route21_North_Text_RonaldPostBattle::
    .string "Non pesco niente di buono!$"

Route21_North_Text_WadeIntro::
    .string "Ho preso un bel po' di POKéMON!\n"
    .string "Guarda!$"

Route21_North_Text_WadeDefeat::
    .string "Che noia, questi MAGIKARP!$"

Route21_North_Text_WadePostBattle::
    .string "Pesco solo MAGIKARP!$"

Route21_North_Text_SpencerIntro::
    .string "Il mare pulisce il corpo e l'anima!$"

Route21_North_Text_SpencerDefeat::
    .string "Ahiahi!$"

Route21_North_Text_SpencerPostBattle::
    .string "Mi piace anche la montagna!$"

@ Below is the battle text for the Cue Ball that was on Route 21 in Gen 1.
@ This trainer wasnt used in Gen 3 so their text goes unused/untranslated
@ Interestingly they did add a rematch intro text for this trainer
@ English translations from RB are listed

@ "What's wrong with me swimming?"
Route21_North_Text_CueBallIntro::
    .string "おれだって　たまには\n"
    .string "およぎに　くるぜ！$"

@ "Cheap shot!"
Route21_North_Text_CueBallDefeat::
    .string "ぐわわ！$"

@ "I look like what? A studded inner tube? Get lost!"
Route21_North_Text_CueBallPostBattle::
    .string "うきやすそう　だと？\n"
    .string "うるせー　おおきな　おせわだッ！$"

