SafariZone_East_Text_RestHouse::
    .ifdef ENGLISH
    .string "REST HOUSE$"
    .endif
    .ifdef SPANISH
    .string "CASA DE REPOSO$"
    .endif

SafariZone_East_Text_TimeDeclinesOnlyWhileYouWalk::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "The remaining time declines only\n"
    .string "while you walk.$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "¡El tiempo restante sólo se verá\n"
    .string "reducido cuando camines!$"
    .endif

SafariZone_East_Text_AreaSign::
    .ifdef ENGLISH
    .string "AREA 1\n"
    .string "WEST: CENTER AREA$"
    .endif
    .ifdef SPANISH
    .string "ZONA 1\n"
    .string "OESTE: ZONA CENTRAL$"
    .endif

