Route15_Text_KindraIntro::
    .ifdef ENGLISH
    .string "I just got some POKéMON in trades.\n"
    .string "Can I try them out on you?$"
    .endif
    .ifdef SPANISH
    .string "¡Déjame probar los POKéMON\n"
    .string "que acabo de cambiar!$"
    .endif

Route15_Text_KindraDefeat::
    .ifdef ENGLISH
    .string "Not good enough!$"
    .endif
    .ifdef SPANISH
    .string "¡No ha sido suficiente!$"
    .endif

Route15_Text_KindraPostBattle::
    .ifdef ENGLISH
    .string "You can't change the nickname of\n"
    .string "any POKéMON you get in a trade.\p"
    .string "Only the Original TRAINER can get\n"
    .string "the nickname changed.$"
    .endif
    .ifdef SPANISH
    .string "No puedes variar el mote de ningún\n"
    .string "POKéMON que hayas cambiado.\p"
    .string "¡El ENTRENADOR original es el\n"
    .string "único que puede!$"
    .endif

Route15_Text_BeckyIntro::
    .ifdef ENGLISH
    .string "You look gentle, so I think I can\n"
    .string "beat you.\p"
    .string "I'll give it a go!$"
    .endif
    .ifdef SPANISH
    .string "¡Pareces manejable!\n"
    .string "¡Creo que podría vencerte!\p"
    .string "¡Voy a intentarlo!$"
    .endif

Route15_Text_BeckyDefeat::
    .ifdef ENGLISH
    .string "No, wrong!$"
    .endif
    .ifdef SPANISH
    .string "No, ¡muy mal!$"
    .endif

Route15_Text_BeckyPostBattle::
    .ifdef ENGLISH
    .string "I'm afraid of BIKERS. They look so\n"
    .string "ugly and mean!$"
    .endif
    .ifdef SPANISH
    .string "¡Me dan miedo los MOTORISTAS,\n"
    .string "son gamberros, horribles!$"
    .endif

Route15_Text_EdwinIntro::
    .ifdef ENGLISH
    .string "When I whistle, I can summon bird\n"
    .string "POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Silbando puedo llamar a los\n"
    .string "pájaros POKéMON!$"
    .endif

Route15_Text_EdwinDefeat::
    .ifdef ENGLISH
    .string "Ow!\n"
    .string "That's tragic!$"
    .endif
    .ifdef SPANISH
    .string "¡Ooh!\n"
    .string "¡Qué tragedia!$"
    .endif

Route15_Text_EdwinPostBattle::
    .ifdef ENGLISH
    .string "Maybe I'm not cut out for battles.\n"
    .string "I'm not the right type, I guess.$"
    .endif
    .ifdef SPANISH
    .string "Puede que no esté hecho para\n"
    .string "luchar contra otros.$"
    .endif

Route15_Text_ChesterIntro::
    .ifdef ENGLISH
    .string "Hmm? My birds are shivering!\n"
    .string "You're good, aren't you?$"
    .endif
    .ifdef SPANISH
    .string "Mis pájaros están temblando.\n"
    .string "Eres muy fuerte, ¿no?$"
    .endif

Route15_Text_ChesterDefeat::
    .ifdef ENGLISH
    .string "Just as I thought!$"
    .endif
    .ifdef SPANISH
    .string "¡Lo que pensaba!$"
    .endif

Route15_Text_ChesterPostBattle::
    .ifdef ENGLISH
    .string "This is so obvious, you should know\n"
    .string "this, but…\p"
    .string "Moves like EARTHQUAKE and FISSURE\n"
    .string "have no effect on bird POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "No sé si decirte esto, supongo\n"
    .string "que ya lo sabes...\p"
    .string "¿Sabías que los movimientos\n"
    .string "como TERREMOTO o FISURA\l"
    .string "no afectan a los pájaros?$"
    .endif

Route15_Text_GraceIntro::
    .ifdef ENGLISH
    .string "Oh, you're a little cutie!\n"
    .string "So like a darling POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh!\n"
    .string "¡Mira qué encanto!$"
    .endif

Route15_Text_GraceDefeat::
    .ifdef ENGLISH
    .string "You looked so cute, too!$"
    .endif
    .ifdef SPANISH
    .string "¡Pensaba que eras un encanto!$"
    .endif

Route15_Text_GracePostBattle::
    .ifdef ENGLISH
    .string "I forgive you.\n"
    .string "I can take it.\l"
    .string "I'm a big girl now.$"
    .endif
    .ifdef SPANISH
    .string "¡Te perdono!\n"
    .string "¡Eres adorable!$"
    .endif

Route15_Text_OliviaIntro::
    .ifdef ENGLISH
    .string "I raise POKéMON for protection\n"
    .string "because I live alone.$"
    .endif
    .ifdef SPANISH
    .string "¡Cuido POKéMON porque vivo sola\n"
    .string "y hacen que me sienta segura!$"
    .endif

Route15_Text_OliviaDefeat::
    .ifdef ENGLISH
    .string "POKéMON isn't about winning or\n"
    .string "losing for me.$"
    .endif
    .ifdef SPANISH
    .string "¡Yo no quería un final así!$"
    .endif

Route15_Text_OliviaPostBattle::
    .ifdef ENGLISH
    .string "I love having my POKéMON greet me\n"
    .string "when I get home.\p"
    .string "It's so reassuring.$"
    .endif
    .ifdef SPANISH
    .string "¡Me gusta ir a casa para estar\n"
    .string "con mis POKéMON!\p"
    .string "Es una tranquilidad...$"
    .endif

Route15_Text_ErnestIntro::
    .ifdef ENGLISH
    .string "Hey, kid! C'mon!\n"
    .string "I just got these off some loser!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye! ¡Ven aquí!\n"
    .string "¡Mira esto!$"
    .endif

Route15_Text_ErnestDefeat::
    .ifdef ENGLISH
    .string "Why not?$"
    .endif
    .ifdef SPANISH
    .string "¡No sé qué decir!$"
    .endif

Route15_Text_ErnestPostBattle::
    .ifdef ENGLISH
    .string "Life's too short.\n"
    .string "It's cool to live as an outlaw.\l"
    .string "TEAM ROCKET RULES!$"
    .endif
    .ifdef SPANISH
    .string "¡Sólo se vive una vez, y yo vivo\n"
    .string "como un forajido!\l"
    .string "¡NORMAS del TEAM ROCKET!$"
    .endif

Route15_Text_AlexIntro::
    .ifdef ENGLISH
    .string "Fork over all your cash when you\n"
    .string "lose to me, kid!$"
    .endif
    .ifdef SPANISH
    .string "¡Mira, colega, si pierdes contra\n"
    .string "mí, todo tu dinero será mío!$"
    .endif

Route15_Text_AlexDefeat::
    .ifdef ENGLISH
    .string "That can't be true!$"
    .endif
    .ifdef SPANISH
    .string "¡No puede ser!$"
    .endif

Route15_Text_AlexPostBattle::
    .ifdef ENGLISH
    .string "I was just joking about the money.\n"
    .string "Don't take me all serious.$"
    .endif
    .ifdef SPANISH
    .string "¡Oye, que lo del dinero era broma!\n"
    .string "¡No me hagas caso!$"
    .endif

Route15_Text_CeliaIntro::
    .ifdef ENGLISH
    .string "What's cool and happening?\n"
    .string "Trading POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¿Qué mola?\n"
    .string "¡Cambiar POKéMON!$"
    .endif

Route15_Text_CeliaDefeat::
    .ifdef ENGLISH
    .string "I said trade!$"
    .endif
    .ifdef SPANISH
    .string "¡He dicho cambiar!$"
    .endif

Route15_Text_CeliaPostBattle::
    .ifdef ENGLISH
    .string "I trade POKéMON with my friends\n"
    .string "all the time.$"
    .endif
    .ifdef SPANISH
    .string "¡Cambio POKéMON con mis amigos!$"
    .endif

Route15_Text_YazminIntro::
    .ifdef ENGLISH
    .string "Want to play with my POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres jugar con mis POKéMON?$"
    .endif

Route15_Text_YazminDefeat::
    .ifdef ENGLISH
    .string "I was too impatient!$"
    .endif
    .ifdef SPANISH
    .string "¡Estaba demasiado impaciente!$"
    .endif

Route15_Text_YazminPostBattle::
    .ifdef ENGLISH
    .string "I'll go train with weaker people.$"
    .endif
    .ifdef SPANISH
    .string "¡Me entrenaré con gente más débil!$"
    .endif

Route15_Text_RouteSign::
    .ifdef ENGLISH
    .string "ROUTE 15\n"
    .string "West to FUCHSIA CITY$"
    .endif
    .ifdef SPANISH
    .string "RUTA 15:\n"
    .string "CIUDAD FUCSIA, al oeste$"
    .endif

Route15_Text_MyaIntro::
    .ifdef ENGLISH
    .string "MYA: You're perfect.\n"
    .string "Help me train my little brother?$"
    .endif
    .ifdef SPANISH
    .string "TINA: Eres genial. ¿Luchamos para\n"
    .string "que aprenda mi hermano?$"
    .endif

Route15_Text_MyaDefeat::
    .ifdef ENGLISH
    .string "MYA: RON, you have to focus!\n"
    .string "Concentrate on what you're doing!$"
    .endif
    .ifdef SPANISH
    .string "TINA: ¡TIN, concéntrate! ¡Hay que\n"
    .string "concentrarse en lo que se hace!$"
    .endif

Route15_Text_MyaPostBattle::
    .ifdef ENGLISH
    .string "MYA: Okay, we'll turn it up.\n"
    .string "I'll add to our training menu!$"
    .endif
    .ifdef SPANISH
    .string "TINA: Tenemos que hacer algo,\n"
    .string "¡debemos entrenarnos más!$"
    .endif

Route15_Text_MyaNotEnoughMons::
    .ifdef ENGLISH
    .string "MYA: Do you want to challenge us?\n"
    .string "You'll need two POKéMON, though.$"
    .endif
    .ifdef SPANISH
    .string "TINA: ¿Quieres desafiarnos?\n"
    .string "¡Pues necesitas dos POKéMON!$"
    .endif

Route15_Text_RonIntro::
    .ifdef ENGLISH
    .string "RON: My sister gets scary when we\n"
    .string "lose.$"
    .endif
    .ifdef SPANISH
    .string "TIN: Mi hermana se asusta cuando\n"
    .string "perdemos.$"
    .endif

Route15_Text_RonDefeat::
    .ifdef ENGLISH
    .string "RON: Oh, no, no…\n"
    .string "Sis, I'm sorry!$"
    .endif
    .ifdef SPANISH
    .string "TIN: Vaya, hermanita, lo siento...$"
    .endif

Route15_Text_RonPostBattle::
    .ifdef ENGLISH
    .string "RON: Oh, bleah…\n"
    .string "I wish I had a nice sister…$"
    .endif
    .ifdef SPANISH
    .string "TIN: Mi hermana se pone un poco\n"
    .string "pesada...$"
    .endif

Route15_Text_RonNotEnoughMons::
    .ifdef ENGLISH
    .string "RON: Did you want to battle with\n"
    .string "my sister and me?\p"
    .string "You need two POKéMON, then.$"
    .endif
    .ifdef SPANISH
    .string "TIN: ¿Te gustaría luchar\n"
    .string "con nosotros?\p"
    .string "¡Pues vente con dos POKéMON!$"
    .endif
