CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor::
	.string "Bienvenue!\p"
	.string "Echangez vos JETONS contre des\n"
	.string "prix à côté.$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins::
	.string "Bienvenue au CASINO ROCKET!\p"
	.string "Désirez-vous acheter\n"
	.string "des JETONS?$"

CeladonCity_GameCorner_Text_ComePlaySometime::
	.string "Non?\n"
	.string "Ben pourquoi?$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase::
	.string "Il vous faut une BOITE JETON!$"

CeladonCity_GameCorner_Text_CoinCaseIsFull::
	.string "Oups!\n"
	.string "Votre BOITE est pleine.$"

CeladonCity_GameCorner_Text_CantAffordCoins::
	.string "Pas d'sous. Pas d'JETONS.$"

CeladonCity_GameCorner_Text_HereAreYourCoins::
	.string "Merci!\n"
	.string "Voici vos JETONS!$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace::
	.string "Ecoute donc ça…\p"
	.string "On raconte que ce tripot est tenu\n"
	.string "par la TEAM ROCKET.$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds::
	.string "Ces machines ont des mécanismes\n"
	.string "différents… Ça c'est sûr!$"

CeladonCity_GameCorner_Text_DoYouWantToPlay::
	.string "Petit… Tu veux jouer?$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan::
	.string "{PLAYER} reçoit\n"
	.string "10 JETONS!$"

CeladonCity_GameCorner_Text_DontNeedMyCoins::
	.string "T'as pas besoin d'mes JETONS!$"

CeladonCity_GameCorner_Text_WinsComeAndGo::
	.string "La chance…\n"
	.string "Ça va, ça vient.$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck::
	.string "Ce que j'peux m'éclater!\n"
	.string "Yaaa!$"

CeladonCity_GameCorner_Text_GymGuyAdvice::
	.string "Hé toi!\p"
	.string "Sacré toi, va…\n"
	.string "Une vraie graine de CHAMPION!\p"
	.string "ERIKA est le CHAMPION de\n"
	.string "l'ARENE de CELADOPOLE! Elle\l"
	.string "utilise des POKéMON PLANTE!\p"
	.string "Elle te semblera douce et tout ça,\n"
	.string "mais… c'est un piège!$"

CeladonCity_GameCorner_Text_RareMonsForCoins::
	.string "De très rares POKéMON sont à\n"
	.string "échanger contre des JETONS.\p"
	.string "Mais c'est trop dur de gagner!$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked::
	.string "Jouer! Jouer! Encore jouer!\n"
	.string "Jouer et jouer! Gaaa.$"

CeladonCity_GameCorner_Text_WantSomeCoins::
	.string "Quoi ça?\n"
	.string "Tu veux des JETONS?$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy::
	.string "{PLAYER} reçoit\n"
	.string "20 JETONS!$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins::
	.string "T'en as des JETONS, toi!$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant::
	.string "Méga-mince! Y m'faut des JETONS\n"
	.string "pour acheter un joli POKéMON!$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo::
	.string "Hein? Des JETONS? En voilà! Mais…\n"
	.string "Comment dire… Dégage!$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan::
	.string "{PLAYER} reçoit\n"
	.string "20 JETONS!$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins::
	.string "T'as tes JETONS?\n"
	.string "Alors va jouer…$"

CeladonCity_GameCorner_Text_WatchReelsClosely::
	.string "Le truc c'est de regarder l'écran\n"
	.string "comme un dingue!$"

CeladonCity_GameCorner_Text_GruntIntro::
	.string "Je surveille le poster!\n"
	.string "Bouge de là!$"

CeladonCity_GameCorner_Text_GruntDefeat::
	.string "Grââ!$"

CeladonCity_GameCorner_Text_GruntPostBattle::
	.string "Not' cachette va être découverte!\n"
	.string "J'va prév'nir l'CHEF!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt::
	.string "Oh!\p"
	.string "Un bouton secret derrière le\n"
	.string "poster!? Allez, hop!$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired::
	.string "Vous n'avez pas de BOITE JETON!$"

CeladonCity_GameCorner_Text_DontHaveCoinCase::
	.string "Oups!\n"
	.string "Pas de BOITE JETON!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay::
	.string "Une machine à sous! On joue?$"

CeladonCity_GameCorner_Text_OutOfOrder::
	.string "EN PANNE\n"
	.string "La machine est cassée.$"

CeladonCity_GameCorner_Text_OutToLunch::
	.string "PARTI MANGER\n"
	.string "Machine réservée.$"

CeladonCity_GameCorner_Text_SomeonesKeys::
	.string "Des clés!\n"
	.string "Bah? C'est à qui?$"

