CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor::
	.string "Willkommen!\p"
	.string "Nebenan kannst du deine\n"
	.string "MÜNZEN gegen Preise tauschen.$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins::
	.string "Willkommen in der ROCKET\n"
	.string "SPIELHALLE!\p"
	.string "Benötigst du Spiel-MÜNZEN?$"

CeladonCity_GameCorner_Text_ComePlaySometime::
	.string "Nein? Dann komm vorbei, wenn du\n"
	.string "spielen möchtest!$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase::
	.string "Du benötigst einen MÜNZKORB!$"

CeladonCity_GameCorner_Text_CoinCaseIsFull::
	.string "Dein MÜNZKORB ist voll!$"

CeladonCity_GameCorner_Text_CantAffordCoins::
	.string "Du hast nicht genug Geld!$"

CeladonCity_GameCorner_Text_HereAreYourCoins::
	.string "Danke!\n"
	.string "Hier sind deine MÜNZEN!$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace::
	.string "Pst! Höre mir zu!\p"
	.string "Man sagt, diese SPIELHALLE gehöre\n"
	.string "dem TEAM ROCKET!$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds::
	.string "Ich glaube, jeder Spielautomat hat\n"
	.string "eine andere Gewinnchance!$"

CeladonCity_GameCorner_Text_DoYouWantToPlay::
	.string "Möchtest du auch spielen?$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan::
	.string "{PLAYER} erhält\n"
	.string "10 MÜNZEN!$"

CeladonCity_GameCorner_Text_DontNeedMyCoins::
	.string "Du brauchst meine MÜNZEN nicht!$"

CeladonCity_GameCorner_Text_WinsComeAndGo::
	.string "Man gewinnt, man verliert!$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck::
	.string "Herrlich!\n"
	.string "Das macht Spaß!$"

CeladonCity_GameCorner_Text_GymGuyAdvice::
	.string "Heh!\p"
	.string "Du hast Wichtigeres zu tun,\n"
	.string "Champion in spe!\p"
	.string "Die ARENALEITERIN von PRISMANIA\n"
	.string "CITY heißt ERIKA.\p"
	.string "Sie trainiert PFLANZEN-POKéMON!\p"
	.string "Sie wirkt sanft, doch man sollte\n"
	.string "sie nicht unterschätzen!$"

CeladonCity_GameCorner_Text_RareMonsForCoins::
	.string "Man kann die MÜNZEN gegen seltene\n"
	.string "POKéMON eintauschen.\p"
	.string "Aber ich habe kein Glück im Spiel!$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked::
	.string "Glücksspiele sind unheimlich!\n"
	.string "Man wird schnell davon abhängig!$"

CeladonCity_GameCorner_Text_WantSomeCoins::
	.string "Wie geht es dir?\n"
	.string "Brauchst du ein paar MÜNZEN?$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy::
	.string "{PLAYER} erhält\n"
	.string "20 MÜNZEN!$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins::
	.string "Heh, du besitzt genug MÜNZEN!$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant::
	.string "Mist! Ich habe noch immer nicht\n"
	.string "genug MÜNZEN für das POKéMON!$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo::
	.string "Heh! Willst du mich ablenken?\n"
	.string "Hier, nimm ein paar MÜNZEN!$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan::
	.string "{PLAYER} erhält\n"
	.string "20 MÜNZEN!$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins::
	.string "Du hast deine eigenen MÜNZEN!$"

CeladonCity_GameCorner_Text_WatchReelsClosely::
	.string "Du musst die Walzen genau im Auge\n"
	.string "behalten!$"

CeladonCity_GameCorner_Text_GruntIntro::
	.string "Verschwinde von dem Poster, oder\n"
	.string "ich muss...$"

CeladonCity_GameCorner_Text_GruntDefeat::
	.string "Mist!$"

CeladonCity_GameCorner_Text_GruntPostBattle::
	.string "Ich muss dem BOSS sagen, dass\n"
	.string "unser Versteck entdeckt werden\l"
	.string "könnte!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt::
	.string "Seltsam!\p"
	.string "Hinter dem Poster ist ein Schalter!\n"
	.string "Tja…$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired::
	.string "Du benötigst einen MÜNZKORB!$"

CeladonCity_GameCorner_Text_DontHaveCoinCase::
	.string "Ups!\n"
	.string "Ich habe den MÜNZKORB vergessen!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay::
	.string "Ein einarmiger Bandit!\n"
	.string "Möchtest du spielen?$"

CeladonCity_GameCorner_Text_OutOfOrder::
	.string "AUSSER BETRIEB!$"

CeladonCity_GameCorner_Text_OutToLunch::
	.string "BIN ZU TISCH!\n"
	.string "Oh, dieser Platz ist besetzt.$"

CeladonCity_GameCorner_Text_SomeonesKeys::
	.string "Da liegt ein Schlüsselbund.\n"
	.string "Der Platz scheint besetzt zu sein.$"

