CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor::
    .ifdef ENGLISH
    .string "Welcome!\p"
    .string "You can exchange your COINS for\n"
    .string "fabulous prizes next door.$"
    .endif
    .ifdef SPANISH
    .string "¡Hola!\p"
    .string "En la puerta de al lado puedes\n"
    .string "cambiar tus FICHAS por grandes\l"
    .string "premios.$"
    .endif

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins::
    .ifdef ENGLISH
    .string "Welcome to ROCKET GAME CORNER!\p"
    .string "Do you need some game COINS?\n"
    .string "Would you like to buy some?$"
    .endif
    .ifdef SPANISH
    .string "¡Éste es el CASINO ROCKET!\p"
    .string "¿Necesitas FICHAS?\n"
    .string "¿Quieres comprar más?$"
    .endif

CeladonCity_GameCorner_Text_ComePlaySometime::
    .ifdef ENGLISH
    .string "No?\n"
    .string "Please come play sometime!$"
    .endif
    .ifdef SPANISH
    .string "¿No?\n"
    .string "¡Ven a jugar cuando quieras!$"
    .endif

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase::
    .ifdef ENGLISH
    .string "Oh, I'm sorry.\n"
    .string "You don't have a COIN CASE.$"
    .endif
    .ifdef SPANISH
    .string "¡No tienes MONEDERO!$"
    .endif

CeladonCity_GameCorner_Text_CoinCaseIsFull::
    .ifdef ENGLISH
    .string "Whoops!\n"
    .string "Your COIN CASE is full.$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya!\n"
    .string "Tu MONEDERO está lleno.$"
    .endif

CeladonCity_GameCorner_Text_CantAffordCoins::
    .ifdef ENGLISH
    .string "You can't afford the COINS.$"
    .endif
    .ifdef SPANISH
    .string "¡No tienes dinero para las FICHAS!$"
    .endif

CeladonCity_GameCorner_Text_HereAreYourCoins::
    .ifdef ENGLISH
    .string "Thank you.\n"
    .string "Here are your COINS!$"
    .endif
    .ifdef SPANISH
    .string "¡Gracias!\n"
    .string "¡Toma las FICHAS!$"
    .endif

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace::
    .ifdef ENGLISH
    .string "Keep this quiet.\p"
    .string "It's rumored that this place is run\n"
    .string "by TEAM ROCKET.$"
    .endif
    .ifdef SPANISH
    .string "Escucha y calla.\p"
    .string "Dicen que este lugar lo dirige\n"
    .string "el TEAM ROCKET.$"
    .endif

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds::
    .ifdef ENGLISH
    .string "I think these machines have\n"
    .string "different odds.$"
    .endif
    .ifdef SPANISH
    .string "¡Creo que estas máquinas están\n"
    .string "trucadas!$"
    .endif

CeladonCity_GameCorner_Text_DoYouWantToPlay::
    .ifdef ENGLISH
    .string "Kid, do you want to play?$"
    .endif
    .ifdef SPANISH
    .string "¡Oye!\n"
    .string "¿Quieres jugar?$"
    .endif

CeladonCity_GameCorner_Text_Received10CoinsFromMan::
    .ifdef ENGLISH
    .string "{PLAYER} received 10 COINS\n"
    .string "from the man.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo 10 FICHAS\n"
    .string "de manos del hombre!$"
    .endif

CeladonCity_GameCorner_Text_DontNeedMyCoins::
    .ifdef ENGLISH
    .string "You don't need my COINS!$"
    .endif
    .ifdef SPANISH
    .string "¡No necesitas mis FICHAS!$"
    .endif

CeladonCity_GameCorner_Text_WinsComeAndGo::
    .ifdef ENGLISH
    .string "Wins seem to come and go.\n"
    .string "Nothing's a sure thing.$"
    .endif
    .ifdef SPANISH
    .string "La suerte viene y se va.\n"
    .string "Hay pocas cosas seguras.$"
    .endif

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck::
    .ifdef ENGLISH
    .string "These slot games…\n"
    .string "Win or lose, it's only by luck.$"
    .endif
    .ifdef SPANISH
    .string "¡Me lo estoy pasando genial!\n"
    .string "Aunque pierda, las tragaperras\l"
    .string "son estupendas.$"
    .endif

CeladonCity_GameCorner_Text_GymGuyAdvice::
    .ifdef ENGLISH
    .string "Hey!\p"
    .string "You have better things to do,\n"
    .string "champ in the making!\p"
    .string "CELADON GYM's LEADER is ERIKA.\p"
    .string "She is a user of GRASS-type\n"
    .string "POKéMON, and at one with nature.\p"
    .string "She might appear docile because of\n"
    .string "her flower arranging…\p"
    .string "But she's not one to be taken\n"
    .string "lightly!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye!\p"
    .string "¡Aún te queda mucho por hacer,\n"
    .string "aspirante al título!\p"
    .string "¡ERIKA es la LÍDER del GIMNASIO\n"
    .string "de AZULONA!\p"
    .string "¡Y usa POKéMON del tipo PLANTA!\p"
    .string "Puede parecer muy dócil, ¡pero ten\n"
    .string "mucho cuidado!\p"
    .string "¡No te confíes!$"
    .endif

CeladonCity_GameCorner_Text_RareMonsForCoins::
    .ifdef ENGLISH
    .string "They offer rare POKéMON that can\n"
    .string "be exchanged for your COINS.\p"
    .string "But, I just can't seem to win!$"
    .endif
    .ifdef SPANISH
    .string "¡Te ofrecen raros POKéMON que\n"
    .string "pueden ser cambiados por tus\l"
    .string "FICHAS!\p"
    .string "¡Y yo aquí, sin ganar!$"
    .endif

CeladonCity_GameCorner_Text_SoEasyToGetHooked::
    .ifdef ENGLISH
    .string "Games are scary!\n"
    .string "It's so easy to get hooked!$"
    .endif
    .ifdef SPANISH
    .string "¡Los juegos dan miedo!\n"
    .string "¡Es tan fácil enviciarse!$"
    .endif

CeladonCity_GameCorner_Text_WantSomeCoins::
    .ifdef ENGLISH
    .string "What's up?\n"
    .string "Want some COINS?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué?\n"
    .string "¿Quieres algunas FICHAS?$"
    .endif

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy::
    .ifdef ENGLISH
    .string "{PLAYER} received 20 COINS\n"
    .string "from the nice guy.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo 20 FICHAS\n"
    .string "de manos del chico encantador!$"
    .endif

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins::
    .ifdef ENGLISH
    .string "You have lots of COINS!$"
    .endif
    .ifdef SPANISH
    .string "¡Tienes muchas FICHAS!$"
    .endif

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant::
    .ifdef ENGLISH
    .string "Darn! I need more COINS for the\n"
    .string "POKéMON I want!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya! ¡Necesito más FICHAS\n"
    .string "para los POKéMON que quiero!$"
    .endif

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo::
    .ifdef ENGLISH
    .string "Hey, what? You're throwing me off!\n"
    .string "Here are some COINS, so shoo!$"
    .endif
    .ifdef SPANISH
    .string "¿Qué? ¿Me estás echando?\n"
    .string "¡Aquí tienes algunas FICHAS!$"
    .endif

CeladonCity_GameCorner_Text_Received20CoinsFromMan::
    .ifdef ENGLISH
    .string "{PLAYER} received 20 COINS\n"
    .string "from the man.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo 20 FICHAS\n"
    .string "de manos del hombre!$"
    .endif

CeladonCity_GameCorner_Text_YouveGotPlentyCoins::
    .ifdef ENGLISH
    .string "You've got plenty of your own\n"
    .string "COINS!$"
    .endif
    .ifdef SPANISH
    .string "¡Ya tienes tus propias FICHAS!$"
    .endif

CeladonCity_GameCorner_Text_WatchReelsClosely::
    .ifdef ENGLISH
    .string "The trick is to watch the reels\n"
    .string "closely.$"
    .endif
    .ifdef SPANISH
    .string "¡El truco está en mirar atentamente\n"
    .string "las pantallas!$"
    .endif

CeladonCity_GameCorner_Text_GruntIntro::
    .ifdef ENGLISH
    .string "I'm guarding this poster!\n"
    .string "Go away, or else!$"
    .endif
    .ifdef SPANISH
    .string "¡Yo protejo este cartel!\n"
    .string "¡Lárgate de aquí!$"
    .endif

CeladonCity_GameCorner_Text_GruntDefeat::
    .ifdef ENGLISH
    .string "Dang!$"
    .endif
    .ifdef SPANISH
    .string "¡Auuu!$"
    .endif

CeladonCity_GameCorner_Text_GruntPostBattle::
    .ifdef ENGLISH
    .string "The TEAM ROCKET HIDEOUT might\n"
    .string "be discovered!\p"
    .string "I better tell BOSS!$"
    .endif
    .ifdef SPANISH
    .string "¡Nuestra GUARIDA podría ser\n"
    .string "descubierta!\p"
    .string "¡Voy a decírselo al JEFE!$"
    .endif

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt::
    .ifdef ENGLISH
    .string "Hey!\p"
    .string "A switch behind the poster!?\n"
    .string "Let's push it!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye!\p"
    .string "¿¡Hay un botón detrás del cartel!?\n"
    .string "¡Vamos a pulsarlo!$"
    .endif

CeladonCity_GameCorner_Text_CoinCaseIsRequired::
    .ifdef ENGLISH
    .string "A COIN CASE is required…$"
    .endif
    .ifdef SPANISH
    .string "¡Se requiere un MONEDERO!$"
    .endif

CeladonCity_GameCorner_Text_DontHaveCoinCase::
    .ifdef ENGLISH
    .string "Oops!\n"
    .string "Don't have the COIN CASE!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya!\n"
    .string "¡Olvidé el MONEDERO!$"
    .endif

CeladonCity_GameCorner_Text_SlotMachineWantToPlay::
    .ifdef ENGLISH
    .string "A slot machine!\n"
    .string "Want to play?$"
    .endif
    .ifdef SPANISH
    .string "¡Una máquina tragaperras!\n"
    .string "¿Quieres jugar?$"
    .endif

CeladonCity_GameCorner_Text_OutOfOrder::
    .ifdef ENGLISH
    .string "OUT OF ORDER\n"
    .string "This is broken.$"
    .endif
    .ifdef SPANISH
    .string "NO FUNCIONA\n"
    .string "Está rota.$"
    .endif

CeladonCity_GameCorner_Text_OutToLunch::
    .ifdef ENGLISH
    .string "OUT TO LUNCH\n"
    .string "This is reserved.$"
    .endif
    .ifdef SPANISH
    .string "ESTAMOS COMIENDO\n"
    .string "Máquina reservada.$"
    .endif

CeladonCity_GameCorner_Text_SomeonesKeys::
    .ifdef ENGLISH
    .string "Someone's keys!\n"
    .string "They'll be back.$"
    .endif
    .ifdef SPANISH
    .string "¡Unas llaves!\n"
    .string "Ya vendrán a por ellas.$"
    .endif

