SixIsland_WaterPath_Text_RoseIntro::
    .string "He llegado hasta aquí dejándome\n"
    .string "llevar por un agradable aroma.$"

SixIsland_WaterPath_Text_RoseDefeat::
    .string "Ganas en encanto cuando muestras\n"
    .string "la fuerza que tienes.$"

SixIsland_WaterPath_Text_RosePostBattle::
    .string "Me gustaría ir al bosque que hay\n"
    .string "por ahí, pero...\p"
    .string "Está lleno de POKéMON del tipo\n"
    .string "BICHO, y me dan mucho miedo.$"

SixIsland_WaterPath_Text_EdwardIntro::
    .string "Practico en secreto para que\n"
    .string "no me vea nadie.$"

SixIsland_WaterPath_Text_EdwardDefeat::
    .string "No me habrá visto nadie, ¿no?$"

SixIsland_WaterPath_Text_EdwardPostBattle::
    .string "Como artista, no me gusta\n"
    .string "que nadie me vea cuando ensayo.$"

SixIsland_WaterPath_Text_SamirIntro::
    .string "¿Perdona? ¿Que no te gusta\n"
    .string "la gente que hace natación\l"
    .string "como yo?\p"
    .string "¡No fastidies!$"

SixIsland_WaterPath_Text_SamirDefeat::
    .string "¡Vale, me queda claro!$"

SixIsland_WaterPath_Text_SamirPostBattle::
    .string "Vaya, no he conseguido dejar alto\n"
    .string "el pabellón de natación...$"

SixIsland_WaterPath_Text_DeniseIntro::
    .string "Como mi chico está siempre liado,\n"
    .string "me voy a nadar yo sola.$"

SixIsland_WaterPath_Text_DeniseDefeat::
    .string "¡Sabía que acabaría así!$"

SixIsland_WaterPath_Text_DenisePostBattle::
    .string "Cuando mi chico está ocupado,\n"
    .string "me entretengo con los POKéMON\l"
    .string "que me dio.$"

SixIsland_WaterPath_Text_EarlIntro::
    .string "Oye, ¿dónde están las montañas\n"
    .string "de esta zona?$"

SixIsland_WaterPath_Text_EarlDefeat::
    .string "¡Me he perdido con tanta lucha!$"

SixIsland_WaterPath_Text_EarlPostBattle::
    .string "¿Hay montañas por aquí o no?$"

SixIsland_WaterPath_Text_MiuIntro::
    .string "MARU: ¡Queridos POKéMON!\n"
    .string "¡Vamos a jugar!$"

SixIsland_WaterPath_Text_MiuDefeat::
    .string "MARU: ¡Nooooo!\n"
    .string "¡Mamiiiiiii!$"

SixIsland_WaterPath_Text_MiuPostBattle::
    .string "MARU: Cuando pierdo me pongo\n"
    .string "muy triste...$"

SixIsland_WaterPath_Text_MiuNotEnoughMons::
    .string "MARU: MÍA y yo somos gemelas.\n"
    .string "Nos encanta luchar juntas.$"

SixIsland_WaterPath_Text_MiaIntro::
    .string "MÍA: ¡Queridos POKéMON!\n"
    .string "¡Vamos a luchar!$"

SixIsland_WaterPath_Text_MiaDefeat::
    .string "MÍA: ¡Hay que ver cómo eres!\n"
    .string "¡No está bien que ganes!$"

SixIsland_WaterPath_Text_MiaPostBattle::
    .string "MÍA: Ooooh...\n"
    .string "Lo siento, queridos POKéMON...$"

SixIsland_WaterPath_Text_MiaNotEnoughMons::
    .string "MÍA: ¿Sólo tienes un POKéMON?\p"
    .string "¿Y no te da pena?$"

SixIsland_WaterPath_Text_WantedUltimateHorn::
    .string "Se busca el cuerno perdido.$"

SixIsland_WaterPath_Text_RouteSign::
    .string "VÍA ACUÁTICA\n"
    .string "LLEVA AL VALLE DE LAS RUINAS$"
