SixIsland_WaterPath_Text_RoseIntro::
    .ifdef ENGLISH
    .string "I let a pleasant breeze lead me\n"
    .string "all the way here.$"
    .endif
    .ifdef SPANISH
    .string "He llegado hasta aquí dejándome\n"
    .string "llevar por un agradable aroma.$"
    .endif

SixIsland_WaterPath_Text_RoseDefeat::
    .ifdef ENGLISH
    .string "Giggle… You're so cute when you're\n"
    .string "determined.$"
    .endif
    .ifdef SPANISH
    .string "Ganas en encanto cuando muestras\n"
    .string "la fuerza que tienes.$"
    .endif

SixIsland_WaterPath_Text_RosePostBattle::
    .ifdef ENGLISH
    .string "I want to go to the woods over\n"
    .string "there, but…\p"
    .string "There are lots of BUG POKéMON.\n"
    .string "They scare me a little.$"
    .endif
    .ifdef SPANISH
    .string "Me gustaría ir al bosque que hay\n"
    .string "por ahí, pero...\p"
    .string "Está lleno de POKéMON del tipo\n"
    .string "BICHO, y me dan mucho miedo.$"
    .endif

SixIsland_WaterPath_Text_EdwardIntro::
    .ifdef ENGLISH
    .string "I'm practicing in secret so no one\n"
    .string "can see me.$"
    .endif
    .ifdef SPANISH
    .string "Practico en secreto para que\n"
    .string "no me vea nadie.$"
    .endif

SixIsland_WaterPath_Text_EdwardDefeat::
    .ifdef ENGLISH
    .string "Nobody saw me losing, right?$"
    .endif
    .ifdef SPANISH
    .string "No me habrá visto nadie, ¿no?$"
    .endif

SixIsland_WaterPath_Text_EdwardPostBattle::
    .ifdef ENGLISH
    .string "As a performer, I don't want people\n"
    .string "to know about the effort I put in.$"
    .endif
    .ifdef SPANISH
    .string "Como artista, no me gusta\n"
    .string "que nadie me vea cuando ensayo.$"
    .endif

SixIsland_WaterPath_Text_SamirIntro::
    .ifdef ENGLISH
    .string "What, you're suggesting that you're\n"
    .string "sick of seeing SWIMMERS like me?\p"
    .string "Aww, don't be hatin'!$"
    .endif
    .ifdef SPANISH
    .string "¿Perdona? ¿Que no te gusta\n"
    .string "la gente que hace natación\l"
    .string "como yo?\p"
    .string "¡No fastidies!$"
    .endif

SixIsland_WaterPath_Text_SamirDefeat::
    .ifdef ENGLISH
    .string "Oh, no, no, no.$"
    .endif
    .ifdef SPANISH
    .string "¡Vale, me queda claro!$"
    .endif

SixIsland_WaterPath_Text_SamirPostBattle::
    .ifdef ENGLISH
    .string "I couldn't lift the stigma of being\n"
    .string "a SWIMMER…$"
    .endif
    .ifdef SPANISH
    .string "Vaya, no he conseguido dejar alto\n"
    .string "el pabellón de natación...$"
    .endif

SixIsland_WaterPath_Text_DeniseIntro::
    .ifdef ENGLISH
    .string "My boyfriend's always busy, so I\n"
    .string "come swimming by myself.$"
    .endif
    .ifdef SPANISH
    .string "Como mi chico está siempre liado,\n"
    .string "me voy a nadar yo sola.$"
    .endif

SixIsland_WaterPath_Text_DeniseDefeat::
    .ifdef ENGLISH
    .string "Awww, I knew this would happen!$"
    .endif
    .ifdef SPANISH
    .string "¡Sabía que acabaría así!$"
    .endif

SixIsland_WaterPath_Text_DenisePostBattle::
    .ifdef ENGLISH
    .string "When I can't be with my boyfriend,\n"
    .string "I spend time with the POKéMON he\l"
    .string "gave me.$"
    .endif
    .ifdef SPANISH
    .string "Cuando mi chico está ocupado,\n"
    .string "me entretengo con los POKéMON\l"
    .string "que me dio.$"
    .endif

SixIsland_WaterPath_Text_EarlIntro::
    .ifdef ENGLISH
    .string "Tell me, where are the mountains\n"
    .string "around these parts?$"
    .endif
    .ifdef SPANISH
    .string "Oye, ¿dónde están las montañas\n"
    .string "de esta zona?$"
    .endif

SixIsland_WaterPath_Text_EarlDefeat::
    .ifdef ENGLISH
    .string "I lost my way while I was busy\n"
    .string "battling!$"
    .endif
    .ifdef SPANISH
    .string "¡Me he perdido con tanta lucha!$"
    .endif

SixIsland_WaterPath_Text_EarlPostBattle::
    .ifdef ENGLISH
    .string "Aren't there any mountains around\n"
    .string "these parts?$"
    .endif
    .ifdef SPANISH
    .string "¿Hay montañas por aquí o no?$"
    .endif

SixIsland_WaterPath_Text_MiuIntro::
    .ifdef ENGLISH
    .string "MIU: Hello, POKéMON!\n"
    .string "It's time to play!$"
    .endif
    .ifdef SPANISH
    .string "MARU: ¡Queridos POKéMON!\n"
    .string "¡Vamos a jugar!$"
    .endif

SixIsland_WaterPath_Text_MiuDefeat::
    .ifdef ENGLISH
    .string "MIU: Oh, no!\n"
    .string "Mommy!$"
    .endif
    .ifdef SPANISH
    .string "MARU: ¡Nooooo!\n"
    .string "¡Mamiiiiiii!$"
    .endif

SixIsland_WaterPath_Text_MiuPostBattle::
    .ifdef ENGLISH
    .string "MIU: It makes me all sad inside\n"
    .string "when we lose…$"
    .endif
    .ifdef SPANISH
    .string "MARU: Cuando pierdo me pongo\n"
    .string "muy triste...$"
    .endif

SixIsland_WaterPath_Text_MiuNotEnoughMons::
    .ifdef ENGLISH
    .string "MIU: MIA and I are TWINS.\n"
    .string "We want to battle together.$"
    .endif
    .ifdef SPANISH
    .string "MARU: MÍA y yo somos gemelas.\n"
    .string "Nos encanta luchar juntas.$"
    .endif

SixIsland_WaterPath_Text_MiaIntro::
    .ifdef ENGLISH
    .string "MIA: Hello, POKéMON!\n"
    .string "It's time to battle!$"
    .endif
    .ifdef SPANISH
    .string "MÍA: ¡Queridos POKéMON!\n"
    .string "¡Vamos a luchar!$"
    .endif

SixIsland_WaterPath_Text_MiaDefeat::
    .ifdef ENGLISH
    .string "MIA: You're mean!\n"
    .string "You're bad for winning!$"
    .endif
    .ifdef SPANISH
    .string "MÍA: ¡Hay que ver cómo eres!\n"
    .string "¡No está bien que ganes!$"
    .endif

SixIsland_WaterPath_Text_MiaPostBattle::
    .ifdef ENGLISH
    .string "MIA: Ohh…\n"
    .string "I'm sorry, my POKéMON…$"
    .endif
    .ifdef SPANISH
    .string "MÍA: Ooooh...\n"
    .string "Lo siento, queridos POKéMON...$"
    .endif

SixIsland_WaterPath_Text_MiaNotEnoughMons::
    .ifdef ENGLISH
    .string "MIA: Oh, you only have one\n"
    .string "POKéMON?\p"
    .string "Don't you feel lonesome?$"
    .endif
    .ifdef SPANISH
    .string "MÍA: ¿Sólo tienes un POKéMON?\p"
    .string "¿Y no te da pena?$"
    .endif

SixIsland_WaterPath_Text_WantedUltimateHorn::
    .ifdef ENGLISH
    .string "Wanted!\n"
    .string "The Ultimate Horn!$"
    .endif
    .ifdef SPANISH
    .string "Se busca el cuerno perdido.$"
    .endif

SixIsland_WaterPath_Text_RouteSign::
    .ifdef ENGLISH
    .string "WATER PATH\n"
    .string "Leads to RUIN VALLEY$"
    .endif
    .ifdef SPANISH
    .string "VÍA ACUÁTICA\n"
    .string "LLEVA AL VALLE DE LAS RUINAS$"
    .endif

