Route18_EastEntrance_1F_Text_NeedBicycleForCyclingRoad::
    .ifdef ENGLISH
    .string "You need a BICYCLE to go out on\n"
    .string "CYCLING ROAD!$"
    .endif
    .ifdef SPANISH
    .string "¡Necesitas una BICI para ir\n"
    .string "por el CAMINO de BICIS!$"
    .endif

Route18_EastEntrance_1F_Text_CyclingRoadAllUphillFromHere::
    .ifdef ENGLISH
    .string "CYCLING ROAD is all uphill from\n"
    .string "here.$"
    .endif
    .ifdef SPANISH
    .string "Desde aquí todo el CAMINO\n"
    .string "de BICIS va cuesta arriba.$"
    .endif

Route18_EastEntrance_1F_Text_ExcuseMe::
    .ifdef ENGLISH
    .string "Excuse me!$"
    .endif
    .ifdef SPANISH
    .string "¡Perdona!$"
    .endif

