CinnabarIsland_Text_DoorIsLocked::
    .ifdef ENGLISH
    .string "The door is locked…$"
    .endif
    .ifdef SPANISH
    .string "La puerta está cerrada...$"
    .endif

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab::
    .ifdef ENGLISH
    .string "CINNABAR GYM's BLAINE is quite the\n"
    .string "odd fellow.\p"
    .string "He's lived on the island since way\n"
    .string "before the LAB was built.$"
    .endif
    .ifdef SPANISH
    .string "BLAINE, del GIMNASIO CANELA,\n"
    .string "es un hombre raro que lleva años\l"
    .string "viviendo aquí.\p"
    .string "Antes de que construyeran el\n"
    .string "LABORATORIO, ya vivía aquí.$"
    .endif

CinnabarIsland_Text_ScientistsExperimentInMansion::
    .ifdef ENGLISH
    .string "Scientists conduct experiments \n"
    .string "in the burned-out building.\p"
    .string "You know, the one they call the\n"
    .string "POKéMON MANSION.$"
    .endif
    .ifdef SPANISH
    .string "Los científicos experimentan\n"
    .string "en el edificio quemado.\p"
    .string "Es el mismo edificio al que llaman\n"
    .string "MANSIÓN POKéMON.$"
    .endif

CinnabarIsland_Text_IslandSign::
    .ifdef ENGLISH
    .string "CINNABAR ISLAND\n"
    .string "The Fiery Town of Burning Desire$"
    .endif
    .ifdef SPANISH
    .string "ISLA CANELA\n"
    .string "La feroz ciudad del ardiente\l"
    .string "deseo.$"
    .endif

CinnabarIsland_Text_PokemonLab::
    .ifdef ENGLISH
    .string "POKéMON LAB$"
    .endif
    .ifdef SPANISH
    .string "LABORATORIO POKéMON$"
    .endif

CinnabarIsland_Text_GymSign::
    .ifdef ENGLISH
    .string "CINNABAR ISLAND POKéMON GYM\n"
    .string "LEADER: BLAINE\l"
    .string "The Hotheaded Quiz Master!$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CANELA: BLAINE\l"
    .string "¡El maestro de los acertijos!$"
    .endif

CinnabarIsland_Text_HeyIfItIsntPlayer::
    .ifdef ENGLISH
    .string "Huh?\n"
    .string "Hey, if it isn't {PLAYER}!$"
    .endif
    .ifdef SPANISH
    .string "¡Anda!\n"
    .string "¡Pero si es {PLAYER}!$"
    .endif

CinnabarIsland_Text_ComeWithMeToOneIsland::
    .ifdef ENGLISH
    .string "Look, it's me, BILL.\n"
    .string "Long time no see!\p"
    .string "I hope you're still using my\n"
    .string "PC system.\p"
    .string "Well, listen, since we met up here,\n"
    .string "how about spending time with me?\p"
    .string "There's this little island in the far\n"
    .string "south called ONE ISLAND.\p"
    .string "A friend invited me, so I'm on my\n"
    .string "way out there.\p"
    .string "How about it?\n"
    .string "Do you feel like coming with me?$"
    .endif
    .ifdef SPANISH
    .string "Eh, soy BILL.\n"
    .string "¡Qué de tiempo!\p"
    .string "Espero que sigas usando mi sistema\n"
    .string "para PC.\p"
    .string "Oye, ya que hemos coincidido,\n"
    .string "¿qué tal si te quedas un rato?\p"
    .string "Hay una islita hacia el sur,\n"
    .string "llamada ISLA PRIMA.\p"
    .string "Un colega mío me ha dicho\n"
    .string "que fuera.\p"
    .string "¿Qué te parece?\n"
    .string "¿Te apetece venirte conmigo?$"
    .endif

CinnabarIsland_Text_AllRightLetsGo::
    .ifdef ENGLISH
    .string "All right, then.\n"
    .string "Let's go!$"
    .endif
    .ifdef SPANISH
    .string "Guay, pues venga.$"
    .endif

CinnabarIsland_Text_IllBeWaitingInPokeCenter::
    .ifdef ENGLISH
    .string "What, are you too busy?\p"
    .string "Well, all right.\n"
    .string "The boat hasn't arrived yet anyway.\p"
    .string "I'll be waiting at the POKéMON\n"
    .string "CENTER over there.\p"
    .string "Come see me when you're done with\n"
    .string "your business here.$"
    .endif
    .ifdef SPANISH
    .string "¿No tienes tiempo o qué?\p"
    .string "Bueno, pues vale. De todas formas\n"
    .string "el barco no ha llegado aún.\p"
    .string "Voy a esperar en el CENTRO\n"
    .string "POKéMON de ahí.\p"
    .string "Cuando hayas acabado de hacer\n"
    .string "tus cosas, ya sabes dónde estoy.$"
    .endif

CinnabarIsland_Text_MyPalsBoatArrived::
    .ifdef ENGLISH
    .string "Looks like my pal's boat arrived,\n"
    .string "too.\p"
    .string "He sent it specially here to\n"
    .string "CINNABAR to pick me up.$"
    .endif
    .ifdef SPANISH
    .string "Anda, el barco de mi amigo\n"
    .string "ha llegado también...\p"
    .string "¡Lo ha mandado expresamente\n"
    .string "a CANELA para que pueda ir\l"
    .string "a verlo!$"
    .endif

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain::
    .ifdef ENGLISH
    .string "Hey, wasn't that a long cruise?\p"
    .string "My buddy CELIO seemed to enjoy\n"
    .string "your company.\p"
    .string "I'm sure he'd welcome you if you\n"
    .string "were to visit him again.\p"
    .string "If you have a TRI-PASS, you can\n"
    .string "always take a ferry there from\l"
    .string "VERMILION PORT.\p"
    .string "All right, thanks for your company!$"
    .endif
    .ifdef SPANISH
    .string "Eh, menudo viajecito, ¿eh?\p"
    .string "Creo que le has caído genial\n"
    .string "a mi colega CELIO.\p"
    .string "Seguro que le encantará que\n"
    .string "vuelvas a verlo en otra ocasión.\p"
    .string "Si tienes un TRI-TICKET, puedes\n"
    .string "ir siempre en ferry desde el\l"
    .string "PUERTO de CARMÍN.\p"
    .string "¡Bueno, gracias por la compañía!$"
    .endif

