FiveIsland_House2_Text_MeadowBelongedToFamily::
    .ifdef ENGLISH
    .string "That MEADOW has belonged to our\n"
    .string "family for generations.\p"
    .string "I should have had a giant mansion\n"
    .string "built on it.\p"
    .string "It would be preferable to having\n"
    .string "those thugs run wild on it!$"
    .endif
    .ifdef SPANISH
    .string "El PRADO ha pertenecido a nuestra\n"
    .string "familia durante generaciones.\p"
    .string "Tendría que haber aprovechado\n"
    .string "para construir una mansión gigante.\p"
    .string "Mejor eso, a tener a la gentuza\n"
    .string "pisoteándolo a sus anchas.$"
    .endif

