OneIsland_KindleRoad_EmberSpa_Text_WaterWarmsMeToCore::
    .ifdef ENGLISH
    .string "Hm!\n"
    .string "Haaaaaaaaaaah!\p"
    .string "Aaaah! This is heavenly!\n"
    .string "The water warms me to my core!\p"
    .string "You should jump in, too.\p"
    .string "Go to the middle, relax, and get\n"
    .string "good and warm!$"
    .endif
    .ifdef SPANISH
    .string "¡Mmmmm!\n"
    .string "¡Qué maravilla!\p"
    .string "¡Ooooooooh! ¡Esto es vida!\n"
    .string "¡Es de lo más reconfortante!\p"
    .string "¡No me digas que no!\p"
    .string "Quédate aquí un ratito y relájate.\n"
    .string "Qué agradable sentir el calor...$"
    .endif

OneIsland_KindleRoad_EmberSpa_Text_EnjoyBowlOfChowder::
    .ifdef ENGLISH
    .string "My favorite part of bathing comes\n"
    .string "up right after this.\p"
    .string "I enjoy a bowl of chowder to\n"
    .string "warm me from the inside, too!$"
    .endif
    .ifdef SPANISH
    .string "La mejor parte del baño viene\n"
    .string "cuando me salgo del agua.\p"
    .string "No hay nada como tomar un buen\n"
    .string "plato de sopa de pescado caliente\l"
    .string "para conservar el calorcito. Mmm...$"
    .endif

OneIsland_KindleRoad_EmberSpa_Text_WaterExquisiteFullyRefreshed::
    .ifdef ENGLISH
    .string "The water is perfectly warm.\n"
    .string "It feels exquisite…\p"
    .string "{PLAYER} and the POKéMON were\n"
    .string "fully refreshed!$"
    .endif
    .ifdef SPANISH
    .string "El agua está en su punto.\n"
    .string "Tiene la temperatura ideal...\p"
    .string "¡{PLAYER} y sus POKéMON están\n"
    .string "en forma de nuevo!$"
    .endif

OneIsland_KindleRoad_EmberSpa_Text_HotSpringIsTherapeutic::
    .ifdef ENGLISH
    .string "Soaking in a hot spring pool is\n"
    .string "therapeutic, people say.$"
    .endif
    .ifdef SPANISH
    .string "Dicen que los baños termales\n"
    .string "son terapéuticos.$"
    .endif

OneIsland_KindleRoad_EmberSpa_Text_SeeHowSmoothMySkinIs::
    .ifdef ENGLISH
    .string "Have a look at my face.\n"
    .string "See how smooth my skin is?\p"
    .string "The hot spring's water keeps my\n"
    .string "skin younger than my age.$"
    .endif
    .ifdef SPANISH
    .string "¿Has visto cómo tengo la piel?\n"
    .string "Suave y tersa como la de un bebé.\p"
    .string "¡Las aguas termales me están\n"
    .string "dejando hecha una rosa!$"
    .endif

OneIsland_KindleRoad_EmberSpa_Text_BrunoVisitsSpaOnOccasion::
    .ifdef ENGLISH
    .string "After an honest day of training,\n"
    .string "nothing beats a relaxing soak in\l"
    .string "the hot spring pool.\p"
    .string "BRUNO, who's a senior ahead of me,\n"
    .string "visits the SPA on occasion.\p"
    .string "He comes to rehab injuries, both\n"
    .string "his own and his POKéMON's.$"
    .endif
    .ifdef SPANISH
    .string "Tras un duro día de entrenamiento,\n"
    .string "no hay nada como un buen baño\l"
    .string "termal.\p"
    .string "BRUNO, ejemplo al que sigo, viene\n"
    .string "al BALNEARIO cada vez que puede.\p"
    .string "No sólo para recuperarse él,\n"
    .string "también lo hace por sus POKéMON.$"
    .endif

OneIsland_KindleRoad_EmberSpa_Text_UsedThisToMakeEmberSpa::
    .ifdef ENGLISH
    .string "Hot springs go hand-in-hand with\n"
    .string "volcanoes.\p"
    .string "The EMBER SPA here, well,\n"
    .string "I made it years ago.\p"
    .string "I hewed the pool right out of a\n"
    .string "gigantic boulder by hand.\p"
    .string "I was using this at the time.\n"
    .string "I suppose I can part with it.$"
    .endif
    .ifdef SPANISH
    .string "Las aguas termales tienen una\n"
    .string "relación estrecha con los volcanes.\p"
    .string "Yo fui quien montó el BALNEARIO\n"
    .string "ASCUAS hace unos años.\p"
    .string "En enormes cantos que había,\n"
    .string "hice las piscinas termales picando\l"
    .string "la piedra con mis propias manos.\p"
    .string "Entonces, usé esto. Creo que\n"
    .string "ya puedo desprenderme de ello.$"
    .endif

OneIsland_KindleRoad_EmberSpa_Text_ExplainHM06::
    .ifdef ENGLISH
    .string "That shatters boulders as if they\n"
    .string "were made of crackers.$"
    .endif
    .ifdef SPANISH
    .string "Podrás destrozar rocas como\n"
    .string "si fueran nueces.$"
    .endif

