SilphCo_6F_Text_RocketsTookOverBuilding::
    .ifdef ENGLISH
    .string "The ROCKETS came and took over\n"
    .string "the building!$"
    .endif
    .ifdef SPANISH
    .string "¡Los ROCKET vinieron y se\n"
    .string "apoderaron de todo el edificio!$"
    .endif

SilphCo_6F_Text_BetterGetBackToWork::
    .ifdef ENGLISH
    .string "Well, better get back to work.$"
    .endif
    .ifdef SPANISH
    .string "¡Más vale que vuelva al trabajo!$"
    .endif

SilphCo_6F_Text_HelpMePlease::
    .ifdef ENGLISH
    .string "Oh dear, oh dear.\n"
    .string "Help me, please!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh, por favor!\n"
    .string "¡Ayúdame!$"
    .endif

SilphCo_6F_Text_WeGotEngaged::
    .ifdef ENGLISH
    .string "We got engaged.\n"
    .string "Heheh!$"
    .endif
    .ifdef SPANISH
    .string "¡Somos novios!\n"
    .string "¡Jaja!$"
    .endif

SilphCo_6F_Text_ThatManIsSuchACoward::
    .ifdef ENGLISH
    .string "That man next to me…\n"
    .string "He's such a coward!$"
    .endif
    .ifdef SPANISH
    .string "¡Míralo!\n"
    .string "¡Es tan cobarde!$"
    .endif

SilphCo_6F_Text_NeedsMeToLookAfterHim::
    .ifdef ENGLISH
    .string "He's so helpless, he needed\n"
    .string "someone like me to look after him.$"
    .endif
    .ifdef SPANISH
    .string "¡Me daba tanta pena, que decidí\n"
    .string "ocuparme de él!$"
    .endif

SilphCo_6F_Text_RocketsTryingToConquerWorld::
    .ifdef ENGLISH
    .string "TEAM ROCKET is trying to conquer\n"
    .string "the world with POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡El TEAM ROCKET quiere conquistar\n"
    .string "el mundo con sus POKéMON!$"
    .endif

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
    .ifdef ENGLISH
    .string "TEAM ROCKET ran away, and it's all\n"
    .string "because of you!$"
    .endif
    .ifdef SPANISH
    .string "¡El TEAM ROCKET se escapó\n"
    .string "por tu culpa!$"
    .endif

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
    .ifdef ENGLISH
    .string "They must have targeted SILPH for\n"
    .string "our POKéMON products.$"
    .endif
    .ifdef SPANISH
    .string "Deben de haber elegido SILPH\n"
    .string "por nuestros productos POKéMON.$"
    .endif

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
    .ifdef ENGLISH
    .string "Come work for SILPH when you\n"
    .string "get older.$"
    .endif
    .ifdef SPANISH
    .string "¡Ven a trabajar para SILPH cuando\n"
    .string "seas mayor!$"
    .endif

SilphCo_6F_Text_Grunt1Intro::
    .ifdef ENGLISH
    .string "I am one of the four ROCKET\n"
    .string "BROTHERS!$"
    .endif
    .ifdef SPANISH
    .string "¡Soy uno de los 4 HERMANOS\n"
    .string "ROCKET!$"
    .endif

SilphCo_6F_Text_Grunt1Defeat::
    .ifdef ENGLISH
    .string "Flame out!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué paliza!$"
    .endif

SilphCo_6F_Text_Grunt1PostBattle::
    .ifdef ENGLISH
    .string "No matter!\n"
    .string "My brothers will avenge me!$"
    .endif
    .ifdef SPANISH
    .string "¡No importa!\n"
    .string "¡Mis hermanos me vengarán!$"
    .endif

SilphCo_6F_Text_TaylorIntro::
    .ifdef ENGLISH
    .string "That rotten PRESIDENT!\p"
    .string "Serves him right for shipping me\n"
    .string "off to the TIKSI BRANCH!\p"
    .string "That's why TEAM ROCKET came after\n"
    .string "us, I'm sure of it!$"
    .endif
    .ifdef SPANISH
    .string "No puedo con el PRESIDENTE...\p"
    .string "¡No debía haberme enviado a la\n"
    .string "SUCURSAL TIKSI!\p"
    .string "¡Seguro que el TEAM ROCKET\n"
    .string "nos habría dejado en paz!$"
    .endif

SilphCo_6F_Text_TaylorDefeat::
    .ifdef ENGLISH
    .string "Shoot!$"
    .endif
    .ifdef SPANISH
    .string "¡Estoy acabado!$"
    .endif

SilphCo_6F_Text_TaylorPostBattle::
    .ifdef ENGLISH
    .string "TIKSI BRANCH?\n"
    .string "It's in Russian no-man's-land!$"
    .endif
    .ifdef SPANISH
    .string "¿La SUCURSAL TIKSI?\n"
    .string "¡Está en medio de la nada!$"
    .endif

SilphCo_6F_Text_Grunt2Intro::
    .ifdef ENGLISH
    .string "You dare betray TEAM ROCKET?$"
    .endif
    .ifdef SPANISH
    .string "¿Te atreves a traicionar al TEAM\n"
    .string "ROCKET?$"
    .endif

SilphCo_6F_Text_Grunt2Defeat::
    .ifdef ENGLISH
    .string "You traitor!$"
    .endif
    .ifdef SPANISH
    .string "¡Debería darte vergüenza!$"
    .endif

SilphCo_6F_Text_Grunt2PostBattle::
    .ifdef ENGLISH
    .string "If you stand for justice, you\n"
    .string "betray us bad guys!$"
    .endif
    .ifdef SPANISH
    .string "¡Si apoyas la justicia, traicionarás\n"
    .string "al malvado!$"
    .endif

SilphCo_6F_Text_FloorSign::
    .ifdef ENGLISH
    .string "SILPH CO. HEAD OFFICE\n"
    .string "6F$"
    .endif
    .ifdef SPANISH
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P5$"
    .endif

