SilphCo_6F_Text_RocketsTookOverBuilding::
	.string "La TEAM ROCKET a investi tout\n"
	.string "l'immeuble!$"

SilphCo_6F_Text_BetterGetBackToWork::
	.string "Allez, hop! \n"
	.string "Au boulot!$"

SilphCo_6F_Text_HelpMePlease::
	.string "Pitié, pitié…\n"
	.string "Aidez-moi!$"

SilphCo_6F_Text_WeGotEngaged::
	.string "On va s'marier!\n"
	.string "Haha!$"

SilphCo_6F_Text_ThatManIsSuchACoward::
	.string "Regarde-moi ça!\n"
	.string "Quel froussard celui-là!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim::
	.string "Il a besoin de quelqu'un…\n"
	.string "Alors je vais l'épouser!$"

SilphCo_6F_Text_RocketsTryingToConquerWorld::
	.string "La TEAM ROCKET veut dominer le\n"
	.string "monde avec des POKéMON!$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
	.string "Tu as fait fuir la TEAM ROCKET!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
	.string "Les produits POKéMON de la SYLPHE\n"
	.string "devaient les intéresser.$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
	.string "Travaille donc pour la SYLPHE\n"
	.string "quand tu auras l'âge!$"

SilphCo_6F_Text_Grunt1Intro::
	.string "Je suis l'un des 4 FRERES ROCKET!$"

SilphCo_6F_Text_Grunt1Defeat::
	.string "Oups…\n"
	.string "Dans le vent!$"

SilphCo_6F_Text_Grunt1PostBattle::
	.string "Pas grave!\n"
	.string "Mes frères me vengeront!$"

SilphCo_6F_Text_TaylorIntro::
	.string "Quel pourri ce PDG!\p"
	.string "Il a décidé de me muter au siège\n"
	.string "de TRIFOUILLI!$"

SilphCo_6F_Text_TaylorDefeat::
	.string "Zut!$"

SilphCo_6F_Text_TaylorPostBattle::
	.string "TRIFOUILLI?\n"
	.string "C'est au beau milieu de nulle part!$"

SilphCo_6F_Text_Grunt2Intro::
	.string "Tu oses défier la TEAM ROCKET?$"

SilphCo_6F_Text_Grunt2Defeat::
	.string "C'est pas juste.$"

SilphCo_6F_Text_Grunt2PostBattle::
	.string "Si t'es gentil, t'es pas méchant!$"

SilphCo_6F_Text_FloorSign::
	.string "SYLPHE SARL.\n"
	.string "5ème étage.$"

