SilphCo_6F_Text_RocketsTookOverBuilding::
	.string "Das TEAM ROCKET hat die Kontrolle\n"
	.string "über das Gebäude übernommen!$"

SilphCo_6F_Text_BetterGetBackToWork::
	.string "O.K., die Arbeit ruft!\n"
	.string "Los geht's!$"

SilphCo_6F_Text_HelpMePlease::
	.string "Oje, ojemine!\n"
	.string "Bitte hilf mir!$"

SilphCo_6F_Text_WeGotEngaged::
	.string "Wir sind verlobt!$"

SilphCo_6F_Text_ThatManIsSuchACoward::
	.string "Schau ihn dir an, den Feigling!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim::
	.string "Ich glaube, ich werde ihn aus\n"
	.string "Mitleid heiraten!$"

SilphCo_6F_Text_RocketsTryingToConquerWorld::
	.string "Das TEAM ROCKET benutzt die\n"
	.string "POKéMON bei dem Versuch, die Welt\l"
	.string "zu erobern!$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
	.string "Du hast das TEAM ROCKET in die\n"
	.string "Flucht geschlagen!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
	.string "Sie müssen es wegen unserer\n"
	.string "POKéMON-Produkte auf die SILPH\l"
	.string "CO. abgesehen haben!$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
	.string "Wir würden uns sehr freuen, wenn\n"
	.string "du später einmal für die\l"
	.string "SILPH CO. arbeiten würdest!$"

SilphCo_6F_Text_Grunt1Intro::
	.string "Ich bin einer der vier berüchtigten\n"
	.string "ROCKET-BRÜDER!$"

SilphCo_6F_Text_Grunt1Defeat::
	.string "Nein!\n"
	.string "Ich bin raus!$"

SilphCo_6F_Text_Grunt1PostBattle::
	.string "Egal!\n"
	.string "Meine Brüder werden mich rächen!$"

SilphCo_6F_Text_TaylorIntro::
	.string "Dieser verdammte PRÄSIDENT!\p"
	.string "Warum will er ausgerechnet mich\n"
	.string "nach TIKSI schicken?$"

SilphCo_6F_Text_TaylorDefeat::
	.string "Mist!$"

SilphCo_6F_Text_TaylorPostBattle::
	.string "TIKSI?\n"
	.string "Das liegt tief im Niemandsland!$"

SilphCo_6F_Text_Grunt2Intro::
	.string "Du wagst es, dich dem TEAM\n"
	.string "ROCKET zu widersetzen?$"

SilphCo_6F_Text_Grunt2Defeat::
	.string "Du elender Verräter!$"

SilphCo_6F_Text_Grunt2PostBattle::
	.string "Wenn du ehrlich und rechtschaffen\n"
	.string "bist, bekämpfst du das Böse!$"

SilphCo_6F_Text_FloorSign::
	.string "SILPH CO. HAUPTSITZ\n"
	.string "5 OG$"

