SilphCo_6F_Text_RocketsTookOverBuilding::
    .string "¡Los ROCKET vinieron y se\n"
    .string "apoderaron de todo el edificio!$"

SilphCo_6F_Text_BetterGetBackToWork::
    .string "¡Más vale que vuelva al trabajo!$"

SilphCo_6F_Text_HelpMePlease::
    .string "¡Oh, por favor!\n"
    .string "¡Ayúdame!$"

SilphCo_6F_Text_WeGotEngaged::
    .string "¡Somos novios!\n"
    .string "¡Jaja!$"

SilphCo_6F_Text_ThatManIsSuchACoward::
    .string "¡Míralo!\n"
    .string "¡Es tan cobarde!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim::
    .string "¡Me daba tanta pena, que decidí\n"
    .string "ocuparme de él!$"

SilphCo_6F_Text_RocketsTryingToConquerWorld::
    .string "¡El TEAM ROCKET quiere conquistar\n"
    .string "el mundo con sus POKéMON!$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
    .string "¡El TEAM ROCKET se escapó\n"
    .string "por tu culpa!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
    .string "Deben de haber elegido SILPH\n"
    .string "por nuestros productos POKéMON.$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
    .string "¡Ven a trabajar para SILPH cuando\n"
    .string "seas mayor!$"

SilphCo_6F_Text_Grunt1Intro::
    .string "¡Soy uno de los 4 HERMANOS\n"
    .string "ROCKET!$"

SilphCo_6F_Text_Grunt1Defeat::
    .string "¡Qué paliza!$"

SilphCo_6F_Text_Grunt1PostBattle::
    .string "¡No importa!\n"
    .string "¡Mis hermanos me vengarán!$"

SilphCo_6F_Text_TaylorIntro::
    .string "No puedo con el PRESIDENTE...\p"
    .string "¡No debía haberme enviado a la\n"
    .string "SUCURSAL TIKSI!\p"
    .string "¡Seguro que el TEAM ROCKET\n"
    .string "nos habría dejado en paz!$"

SilphCo_6F_Text_TaylorDefeat::
    .string "¡Estoy acabado!$"

SilphCo_6F_Text_TaylorPostBattle::
    .string "¿La SUCURSAL TIKSI?\n"
    .string "¡Está en medio de la nada!$"

SilphCo_6F_Text_Grunt2Intro::
    .string "¿Te atreves a traicionar al TEAM\n"
    .string "ROCKET?$"

SilphCo_6F_Text_Grunt2Defeat::
    .string "¡Debería darte vergüenza!$"

SilphCo_6F_Text_Grunt2PostBattle::
    .string "¡Si apoyas la justicia, traicionarás\n"
    .string "al malvado!$"

SilphCo_6F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P5$"
