ThreeIsland_House2_Text_CantMakeThisSpoonBend::
    .string "¡Urrrrrrrrgggg!...\n"
    .string "¡Fffwaaaaah!\p"
    .string "¡Nada!... ¡No hay manera!\n"
    .string "¡No consigo doblar la cuchara\l"
    .string "con la mente!\p"
    .string "A ver si va a resultar que no\n"
    .string "tengo poderes psíquicos...$"

ThreeIsland_House2_Text_IAdmireSabrina::
    .string "¿Sabes algo de la LÍDER del\n"
    .string "GIMNASIO de AZAFRÁN?\p"
    .string "Usa POKéMON del tipo PSÍQUICO,\n"
    .string "¿no?\p"
    .string "Yo la admiro, la verdad.\p"
    .string "He oído que es guay y, además,\n"
    .string "muy mona.$"
