ThreeIsland_House2_Text_CantMakeThisSpoonBend::
    .ifdef ENGLISH
    .string "Urrrrrrrrgggghhhh…\n"
    .string "Kwaaaaah!\p"
    .string "…It's useless! I can't make this\n"
    .string "spoon bend with my mind.\p"
    .string "Maybe I really don't have any\n"
    .string "psychic powers.$"
    .endif
    .ifdef SPANISH
    .string "¡Urrrrrrrrgggg!...\n"
    .string "¡Fffwaaaaah!\p"
    .string "¡Nada!... ¡No hay manera!\n"
    .string "¡No consigo doblar la cuchara\l"
    .string "con la mente!\p"
    .string "A ver si va a resultar que no\n"
    .string "tengo poderes psíquicos...$"
    .endif

ThreeIsland_House2_Text_IAdmireSabrina::
    .ifdef ENGLISH
    .string "You know about a girl GYM LEADER\n"
    .string "in SAFFRON CITY?\p"
    .string "She uses PSYCHIC-type POKéMON,\n"
    .string "right?\p"
    .string "I admire her, I really do.\p"
    .string "I've heard that she's one cool\n"
    .string "customer and beautiful, too.$"
    .endif
    .ifdef SPANISH
    .string "¿Sabes algo de la LÍDER del\n"
    .string "GIMNASIO de AZAFRÁN?\p"
    .string "Usa POKéMON del tipo PSÍQUICO,\n"
    .string "¿no?\p"
    .string "Yo la admiro, la verdad.\p"
    .string "He oído que es guay y, además,\n"
    .string "muy mona.$"
    .endif

