FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon::
    .ifdef ENGLISH
    .string "You can't become a good TRAINER\n"
    .string "with just one strong POKéMON.\p"
    .string "But raising many POKéMON evenly\n"
    .string "is no easy task, either.$"
    .endif
    .ifdef SPANISH
    .string "No puedes ganar sólo con\n"
    .string "un POKéMON fuerte.\p"
    .string "Es difícil, pero conviene\n"
    .string "entrenarlos a todos por igual.$"
    .endif

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian::
    .ifdef ENGLISH
    .string "There's a narrow trail west of\n"
    .string "VIRIDIAN CITY.\p"
    .string "It goes to the POKéMON LEAGUE HQ.\n"
    .string "The HQ governs all TRAINERS.$"
    .endif
    .ifdef SPANISH
    .string "Hay un estrecho camino al oeste\n"
    .string "de CIUDAD VERDE.\p"
    .string "Lleva al CG de la LIGA POKéMON.\n"
    .string "El CG gobierna a todos los\l"
    .string "ENTRENADORES.$"
    .endif

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex::
    .ifdef ENGLISH
    .string "If you're working on a POKéDEX,\n"
    .string "visit the SAFARI ZONE.\p"
    .string "All sorts of rare POKéMON breed\n"
    .string "there.$"
    .endif
    .ifdef SPANISH
    .string "Visita la ZONA del SAFARI si estás\n"
    .string "estudiando a los POKéMON.\p"
    .string "¡Allí encontrarás todo tipo de\n"
    .string "POKéMON raros!$"
    .endif

