CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
	.string "Dieser BILL!\p"
	.string "Ich hörte, für seltene POKéMON\n"
	.string "würde er alles tun!$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
	.string "Hat man dir schon von BILL\n"
	.string "erzählt?\p"
	.string "Jeder nennt ihn den POKéMANIAC!\p"
	.string "Aber ich glaube, die Leute sind\n"
	.string "bloß neidisch auf BILL.\p"
	.string "Wer würde denn nicht mit seinen\n"
	.string "POKéMON prahlen?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
	.string "BILL besitzt viele POKéMON!\p"
	.string "Er hat einige sehr seltene in\n"
	.string "seiner Sammlung!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
	.string "Warum gehst du nicht nach oben und\n"
	.string "tauschst POKéMON mit deinen\l"
	.string "Freunden?\l"
	.string "Dadurch erhöht sich die Vielfalt\l"
	.string "deiner POKéMON.\p"
	.string "Der Level der POKéMON, die du\n"
	.string "durch Tausch erhältst, steigt\l"
	.string "schnell.$"

