CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
    .ifdef ENGLISH
    .string "That BILL!\p"
    .string "I heard that he'll do whatever it\n"
    .string "takes to get rare POKéMON.\p"
    .string "He's not above doing all sorts\n"
    .string "of things, I've heard.$"
    .endif
    .ifdef SPANISH
    .string "¡Este BILL!\p"
    .string "¡Dicen que haría lo que fuera para\n"
    .string "conseguir POKéMON raros!$"
    .endif

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
    .ifdef ENGLISH
    .string "Have you heard about BILL?\p"
    .string "Everyone calls him a POKéMANIAC!\p"
    .string "I think people are just jealous of\n"
    .string "BILL, though.\p"
    .string "Who wouldn't want to boast about\n"
    .string "their POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¿Has oído hablar de BILL?\p"
    .string "¡Dicen que es un POKéMANÍACO!\p"
    .string "Pero yo creo que la gente le tiene\n"
    .string "mucha envidia.\p"
    .string "¿Quién no querría presumir de sus\n"
    .string "POKéMON?$"
    .endif

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
    .ifdef ENGLISH
    .string "BILL has lots of POKéMON!\n"
    .string "He collects rare ones, too!$"
    .endif
    .ifdef SPANISH
    .string "¡BILL tiene muchísimos POKéMON!\n"
    .string "¡Y algunos son muy raros!$"
    .endif

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
    .ifdef ENGLISH
    .string "Why don't you go upstairs and try\n"
    .string "trading POKéMON with your friends?\p"
    .string "You could get a lot more variety\n"
    .string "by trading.\p"
    .string "The POKéMON you get in trades grow\n"
    .string "quickly, too.$"
    .endif
    .ifdef SPANISH
    .string "¿Por qué no subes e intercambias\n"
    .string "POKéMON con tus amigos?\p"
    .string "¡Así se pueden conseguir POKéMON\n"
    .string "muy distintos!\p"
    .string "Además, los que consigues por\n"
    .string "intercambio, crecen antes.$"
    .endif

