SaffronCity_Text_WhatDoYouWantGetLost::
    .ifdef ENGLISH
    .string "What do you want?\n"
    .string "Get lost!$"
    .endif
    .ifdef SPANISH
    .string "¿Qué quieres?\n"
    .string "¡Lárgate!$"
    .endif

SaffronCity_Text_BossTakeTownForTeamRocket::
    .ifdef ENGLISH
    .string "BOSS said he'll take this town\n"
    .string "in the name of TEAM ROCKET!$"
    .endif
    .ifdef SPANISH
    .string "¡El JEFE dice que invadirá esta\n"
    .string "ciudad en nombre del TEAM ROCKET!$"
    .endif

SaffronCity_Text_DontGetDefiantOrIllHurtYou::
    .ifdef ENGLISH
    .string "Don't get defiant!\n"
    .string "Or I'll have to hurt you!$"
    .endif
    .ifdef SPANISH
    .string "¡Fuera de mi camino!\n"
    .string "¡Te lo digo por las buenas!$"
    .endif

SaffronCity_Text_SaffronBelongsToTeamRocket::
    .ifdef ENGLISH
    .string "SAFFRON belongs to TEAM ROCKET!$"
    .endif
    .ifdef SPANISH
    .string "¡AZAFRÁN es del TEAM ROCKET!$"
    .endif

SaffronCity_Text_CriminalLifeMakesMeFeelAlive::
    .ifdef ENGLISH
    .string "My life as a criminal makes me feel\n"
    .string "so alive!$"
    .endif
    .ifdef SPANISH
    .string "¡Ser así me hace sentir tan vivo!$"
    .endif

SaffronCity_Text_WatchWhereYoureWalking::
    .ifdef ENGLISH
    .string "Ow!\n"
    .string "Watch where you're walking!$"
    .endif
    .ifdef SPANISH
    .string "¡Au!\n"
    .string "¡Cuidado por donde caminas!$"
    .endif

SaffronCity_Text_WeCanExploitMonsAroundWorld::
    .ifdef ENGLISH
    .string "With SILPH under control, we can\n"
    .string "exploit POKéMON around the world!\p"
    .string "We'll get stinking rich, yeahah!$"
    .endif
    .ifdef SPANISH
    .string "¡Con SILPH bajo control, podemos\n"
    .string "explotar a los POKéMON de todo el\l"
    .string "mundo!\p"
    .string "¡Nos vamos a forrar, je, je!$"
    .endif

SaffronCity_Text_YouBeatTeamRocket::
    .ifdef ENGLISH
    .string "You beat TEAM ROCKET all alone?\n"
    .string "That's amazing!$"
    .endif
    .ifdef SPANISH
    .string "¿Venciste sin ayuda al TEAM\n"
    .string "ROCKET? ¡Qué increíble!$"
    .endif

SaffronCity_Text_SafeToGoOutAgain::
    .ifdef ENGLISH
    .string "Yeah! TEAM ROCKET is gone!\n"
    .string "It's safe to go out again!$"
    .endif
    .ifdef SPANISH
    .string "¡El TEAM ROCKET se ha marchado!\n"
    .string "¡Ahora podemos salir otra vez!$"
    .endif

SaffronCity_Text_PeopleComingBackToSaffron::
    .ifdef ENGLISH
    .string "People fled from here in droves\n"
    .string "when those ROCKETS came.\p"
    .string "They should be flocking back to\n"
    .string "SAFFRON now.$"
    .endif
    .ifdef SPANISH
    .string "La gente salió huyendo de aquí\n"
    .string "cuando llegó el TEAM ROCKET.\p"
    .string "Pero ahora todo el mundo puede\n"
    .string "regresar a AZAFRÁN.$"
    .endif

SaffronCity_Text_FlewHereOnPidgeot::
    .ifdef ENGLISH
    .string "I flew here on my PIDGEOT when\n"
    .string "I read about SILPH.\p"
    .string "It's already over?\n"
    .string "I missed the media action…$"
    .endif
    .ifdef SPANISH
    .string "Vine volando con mi PIDGEOT\n"
    .string "cuando supe lo de SILPH.\p"
    .string "¿Ya se ha acabado todo?\n"
    .string "Me pierdo las mejores...$"
    .endif

SaffronCity_Text_Pidgeot::
    .ifdef ENGLISH
    .string "PIDGEOT: Bi bibii!$"
    .endif
    .ifdef SPANISH
    .string "PIDGEOT: ¡Pid, pid!$"
    .endif

SaffronCity_Text_SawRocketBossEscaping::
    .ifdef ENGLISH
    .string "I saw the ROCKET BOSS escaping\n"
    .string "SILPH's building.$"
    .endif
    .ifdef SPANISH
    .string "Vi al JEFE ROCKET escapando\n"
    .string "del edificio SILPH.$"
    .endif

SaffronCity_Text_ImASecurityGuard::
    .ifdef ENGLISH
    .string "I'm a security guard.\p"
    .string "Suspicious kids I don't allow in!$"
    .endif
    .ifdef SPANISH
    .string "Soy el guarda de seguridad.\p"
    .string "¡No permito entrar a gente\n"
    .string "sospechosa!$"
    .endif

SaffronCity_Text_HesTakingASnooze::
    .ifdef ENGLISH
    .string "…\n"
    .string "Snore…\p"
    .string "Hah! He's taking a snooze!$"
    .endif
    .ifdef SPANISH
    .string "Grfiiiuuu...\p"
    .string "¡Ja! ¡Está durmiendo la siesta!$"
    .endif

SaffronCity_Text_CitySign::
    .ifdef ENGLISH
    .string "SAFFRON CITY\n"
    .string "Shining, Golden Land of Commerce$"
    .endif
    .ifdef SPANISH
    .string "CIUDAD AZAFRÁN\n"
    .string "La brillante y dorada tierra del\l"
    .string "comercio.$"
    .endif

SaffronCity_Text_FightingDojo::
    .ifdef ENGLISH
    .string "FIGHTING DOJO$"
    .endif
    .ifdef SPANISH
    .string "DOJO-KARATE$"
    .endif

SaffronCity_Text_GymSign::
    .ifdef ENGLISH
    .string "SAFFRON CITY POKéMON GYM\n"
    .string "LEADER: SABRINA\l"
    .string "The Master of PSYCHIC POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de AZAFRÁN: SABRINA\l"
    .string "¡Genio de los POKéMON PSÍQUICOS!$"
    .endif

SaffronCity_Text_FullHealCuresStatus::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "FULL HEAL cures all ailments like\n"
    .string "burns, paralysis, poisoning,\l"
    .string "freezing, and sleep.\p"
    .string "It costs a bit more, but it's more\n"
    .string "convenient than buying other items.$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "CURA TOTAL cura todo malestar,\n"
    .string "como el sueño y las quemaduras.\p"
    .string "Cuesta un poco más, pero merece\n"
    .string "la pena.$"
    .endif

SaffronCity_Text_GreatBallImprovedCatchRate::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "The new GREAT BALL offers improved\n"
    .string "catching rates.\p"
    .string "Try it on those hard-to-catch\n"
    .string "POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "La nueva SUPERBALL ofrece\n"
    .string "mayor velocidad de captura.\p"
    .string "Pruébala con los POKéMON\n"
    .string "difíciles de atrapar.$"
    .endif

SaffronCity_Text_SilphCoSign::
    .ifdef ENGLISH
    .string "SILPH CO. OFFICE BUILDING$"
    .endif
    .ifdef SPANISH
    .string "EDIFICIO-OFICINAS DE SILPH S.A.$"
    .endif

SaffronCity_Text_MrPsychicsHouse::
    .ifdef ENGLISH
    .string "MR. PSYCHIC'S HOUSE$"
    .endif
    .ifdef SPANISH
    .string "CASA DEL SR. PSÍQUICO$"
    .endif

SaffronCity_Text_SilphsLatestProduct::
    .ifdef ENGLISH
    .string "SILPH's latest product!\n"
    .string "Release to be determined…$"
    .endif
    .ifdef SPANISH
    .string "¡Lo último de SILPH!\p"
    .string "Lanzado para ser decisivo...$"
    .endif

SaffronCity_Text_TrainerFanClubSign::
    .ifdef ENGLISH
    .string "POKéMON TRAINER FAN CLUB\p"
    .string "Many TRAINERS have scribbled their\n"
    .string "names on this sign.$"
    .endif
    .ifdef SPANISH
    .string "CLUB DE FANS DE ENTRENADORES\n"
    .string "POKéMON\p"
    .string "En el cartel hay garabateados\n"
    .string "un montón de nombres de\l"
    .string "ENTRENADORES...$"
    .endif

SaffronCity_Text_HowCanClubNotRecognizeLance::
    .ifdef ENGLISH
    .string "This FAN CLUB…\n"
    .string "No one here has a clue!\p"
    .string "How could they not recognize\n"
    .string "the brilliance that is LANCE?\p"
    .string "He stands for justice!\n"
    .string "He's cool, and yet passionate!\l"
    .string "He's the greatest, LANCE!$"
    .endif
    .ifdef SPANISH
    .string "¡En este CLUB de FANS hay gente...\n"
    .string "que de POKéMON nada entiende!\p"
    .string "Nadie tiene ni idea de que LANCE\n"
    .string "es quien mejor pelea.\p"
    .string "¡Es justo!\n"
    .string "¡Es admirado!\l"
    .string "¡Todos quieren estar a su lado!$"
    .endif

