SaffronCity_Text_WhatDoYouWantGetLost::
    .string "¿Qué quieres?\n"
    .string "¡Lárgate!$"

SaffronCity_Text_BossTakeTownForTeamRocket::
    .string "¡El JEFE dice que invadirá esta\n"
    .string "ciudad en nombre del TEAM ROCKET!$"

SaffronCity_Text_DontGetDefiantOrIllHurtYou::
    .string "¡Fuera de mi camino!\n"
    .string "¡Te lo digo por las buenas!$"

SaffronCity_Text_SaffronBelongsToTeamRocket::
    .string "¡AZAFRÁN es del TEAM ROCKET!$"

SaffronCity_Text_CriminalLifeMakesMeFeelAlive::
    .string "¡Ser así me hace sentir tan vivo!$"

SaffronCity_Text_WatchWhereYoureWalking::
    .string "¡Au!\n"
    .string "¡Cuidado por donde caminas!$"

SaffronCity_Text_WeCanExploitMonsAroundWorld::
    .string "¡Con SILPH bajo control, podemos\n"
    .string "explotar a los POKéMON de todo el\l"
    .string "mundo!\p"
    .string "¡Nos vamos a forrar, je, je!$"

SaffronCity_Text_YouBeatTeamRocket::
    .string "¿Venciste sin ayuda al TEAM\n"
    .string "ROCKET? ¡Qué increíble!$"

SaffronCity_Text_SafeToGoOutAgain::
    .string "¡El TEAM ROCKET se ha marchado!\n"
    .string "¡Ahora podemos salir otra vez!$"

SaffronCity_Text_PeopleComingBackToSaffron::
    .string "La gente salió huyendo de aquí\n"
    .string "cuando llegó el TEAM ROCKET.\p"
    .string "Pero ahora todo el mundo puede\n"
    .string "regresar a AZAFRÁN.$"

SaffronCity_Text_FlewHereOnPidgeot::
    .string "Vine volando con mi PIDGEOT\n"
    .string "cuando supe lo de SILPH.\p"
    .string "¿Ya se ha acabado todo?\n"
    .string "Me pierdo las mejores...$"

SaffronCity_Text_Pidgeot::
    .string "PIDGEOT: ¡Pid, pid!$"

SaffronCity_Text_SawRocketBossEscaping::
    .string "Vi al JEFE ROCKET escapando\n"
    .string "del edificio SILPH.$"

SaffronCity_Text_ImASecurityGuard::
    .string "Soy el guarda de seguridad.\p"
    .string "¡No permito entrar a gente\n"
    .string "sospechosa!$"

SaffronCity_Text_HesTakingASnooze::
    .string "Grfiiiuuu...\p"
    .string "¡Ja! ¡Está durmiendo la siesta!$"

SaffronCity_Text_CitySign::
    .string "CIUDAD AZAFRÁN\n"
    .string "La brillante y dorada tierra del\l"
    .string "comercio.$"

SaffronCity_Text_FightingDojo::
    .string "DOJO-KARATE$"

SaffronCity_Text_GymSign::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de AZAFRÁN: SABRINA\l"
    .string "¡Genio de los POKéMON PSÍQUICOS!$"

SaffronCity_Text_FullHealCuresStatus::
    .string "PISTAS ENTRENADOR\p"
    .string "CURA TOTAL cura todo malestar,\n"
    .string "como el sueño y las quemaduras.\p"
    .string "Cuesta un poco más, pero merece\n"
    .string "la pena.$"

SaffronCity_Text_GreatBallImprovedCatchRate::
    .string "PISTAS ENTRENADOR\p"
    .string "La nueva SUPERBALL ofrece\n"
    .string "mayor velocidad de captura.\p"
    .string "Pruébala con los POKéMON\n"
    .string "difíciles de atrapar.$"

SaffronCity_Text_SilphCoSign::
    .string "EDIFICIO-OFICINAS DE SILPH S.A.$"

SaffronCity_Text_MrPsychicsHouse::
    .string "CASA DEL SR. PSÍQUICO$"

SaffronCity_Text_SilphsLatestProduct::
    .string "¡Lo último de SILPH!\p"
    .string "Lanzado para ser decisivo...$"

SaffronCity_Text_TrainerFanClubSign::
    .string "CLUB DE FANS DE ENTRENADORES\n"
    .string "POKéMON\p"
    .string "En el cartel hay garabateados\n"
    .string "un montón de nombres de\l"
    .string "ENTRENADORES...$"

SaffronCity_Text_HowCanClubNotRecognizeLance::
    .string "¡En este CLUB de FANS hay gente...\n"
    .string "que de POKéMON nada entiende!\p"
    .string "Nadie tiene ni idea de que LANCE\n"
    .string "es quien mejor pelea.\p"
    .string "¡Es justo!\n"
    .string "¡Es admirado!\l"
    .string "¡Todos quieren estar a su lado!$"
