TwoIsland_Text_IslandSign::
    .ifdef ENGLISH
    .string "TWO ISLAND\n"
    .string "Boon Island for Two$"
    .endif
    .ifdef SPANISH
    .string "ISLA SECUNDA\n"
    .string "Isla ideal para dos.$"
    .endif

TwoIsland_Text_JoyfulGameCornerSign::
    .ifdef ENGLISH
    .string "Skip & Chomp!\n"
    .string "Joyful GAME CORNER$"
    .endif
    .ifdef SPANISH
    .string "RECREATIVOS\n"
    .string "¡Salta y atrapa!$"
    .endif

TwoIsland_Text_DangerFastCurrent::
    .ifdef ENGLISH
    .string "DANGER! FAST CURRENT!\n"
    .string "Fishing and surfing prohibited!$"
    .endif
    .ifdef SPANISH
    .string "¡PELIGRO! ¡FUERTES RÁPIDOS!\n"
    .string "Queda terminantemente prohibido\l"
    .string "pescar y bañarse.$"
    .endif

TwoIsland_Text_WelcomeToShopMerchandiseLimited::
    .ifdef ENGLISH
    .string "Oh!\n"
    .string "Hello, welcome to my shop!\p"
    .string "We've only opened up recently.\p"
    .string "Our merchandise is limited, but I\n"
    .string "hope we can serve your needs.$"
    .endif
    .ifdef SPANISH
    .string "¡Hola!\n"
    .string "¡Ésta es mi tienda!\p"
    .string "Hemos abierto hace muy poco.\p"
    .string "Aún no tenemos mucha variedad\n"
    .string "de artículos, pero espero que\l"
    .string "encuentres lo que buscas.$"
    .endif

TwoIsland_Text_AddedMerchandiseForLostelle::
    .ifdef ENGLISH
    .string "I can't tell you how grateful I am\n"
    .string "for your rescue of LOSTELLE.\p"
    .string "Thanks to your feat, the people of\n"
    .string "THREE ISLAND have changed their\l"
    .string "attitudes about KANTO people.\p"
    .string "And, I'm from KANTO, you see.\p"
    .string "The people of THREE ISLAND\n"
    .string "helped me add to my merchandise.$"
    .endif
    .ifdef SPANISH
    .string "No sabes cómo te agradecemos\n"
    .string "que hayas rescatado a PEDRITA.\p"
    .string "Gracias a ti, la gente de ISLA\n"
    .string "TERA, tiene otra actitud hacia\l"
    .string "los habitantes de KANTO.\p"
    .string "Y yo soy de KANTO, ¿sabes?\p"
    .string "Por los habitantes de ISLA TERA,\n"
    .string "he aumentado el número\l"
    .string "de artículos.$"
    .endif

TwoIsland_Text_HopeYouGiveItYourBest::
    .ifdef ENGLISH
    .string "Hi! I'm giving it my best here.\n"
    .string "I hope you do too, {PLAYER}.$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, yo aquí hago lo que puedo!\n"
    .string "¡Espero que tú, también, {PLAYER}!$"
    .endif

TwoIsland_Text_BringingItemsFromDistantLands::
    .ifdef ENGLISH
    .string "Oh, hello, {PLAYER}!\n"
    .string "Welcome!\p"
    .string "I've started bringing in items from\n"
    .string "distant lands.\p"
    .string "I've got some rare items in, too.\n"
    .string "Please have a look!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, {PLAYER}!\n"
    .string "¿Qué tal?\p"
    .string "He estado importando artículos\n"
    .string "de otras islas de por ahí.\p"
    .string "Y tengo unas cosas rarísimas.\n"
    .string "¡Échales un vistazo!$"
    .endif

TwoIsland_Text_FellowMovedFromCeladonCity::
    .ifdef ENGLISH
    .string "That fellow there, he moved here\n"
    .string "from CELADON CITY.\p"
    .string "He started up a shop with his\n"
    .string "younger brother.\p"
    .string "You have to wonder if he knew what\n"
    .string "he was getting into.$"
    .endif
    .ifdef SPANISH
    .string "Ese tipo de ahí, vino de CIUDAD\n"
    .string "AZULONA para instalarse aquí.\p"
    .string "Montó una tienda con su hermano\n"
    .string "pequeño.\p"
    .string "Me parece a mí que no sabía en\n"
    .string "lo que se metía.$"
    .endif

TwoIsland_Text_ShopkeepersBrotherWorksGameCorner::
    .ifdef ENGLISH
    .string "The shopkeeper's brother took\n"
    .string "a job at the GAME CORNER.\p"
    .string "He's trying to pull together money\n"
    .string "so they can buy more merchandise.$"
    .endif
    .ifdef SPANISH
    .string "El hermano del tendero encontró\n"
    .string "trabajo en los RECREATIVOS.\p"
    .string "Y pretende ahorrar dinero\n"
    .string "para comprar más artículos\l"
    .string "para la tienda.$"
    .endif

TwoIsland_Text_BrunoCameToIslandWhileBack::
    .ifdef ENGLISH
    .string "Listen, listen.\n"
    .string "Did you know?\p"
    .string "A famous TRAINER came to the\n"
    .string "ISLAND a little while back.\p"
    .string "He's one of the ELITE FOUR.\n"
    .string "His name is BRUNO.\p"
    .string "He went away disappointed when he\n"
    .string "found out that they were all sold\l"
    .string "out of Rage Candybars.$"
    .endif
    .ifdef SPANISH
    .string "Oye, oye, ¿sabes una cosa?\p"
    .string "Hace poco, vino un ENTRENADOR\n"
    .string "a la ISLA.\p"
    .string "Era uno de los miembros del ALTO\n"
    .string "MANDO. Se llamaba BRUNO.\p"
    .string "Pero se fue decepcionado cuando\n"
    .string "vio que no quedaban bastones de\l"
    .string "caramelo superfuertes.$"
    .endif

TwoIsland_Text_BuyRareItemsHere::
    .ifdef ENGLISH
    .string "The discerning TRAINER knows to\n"
    .string "buy rare items here!$"
    .endif
    .ifdef SPANISH
    .string "¡El experto ENTRENADOR sabe\n"
    .string "comprar objetos raros!$"
    .endif

TwoIsland_Text_OldWomanLivesOutOnCape::
    .ifdef ENGLISH
    .string "There's an old woman who lives in\n"
    .string "a cottage out on the cape.\p"
    .string "She gives the eye to POKéMON.\n"
    .string "It's a bit unnerving.$"
    .endif
    .ifdef SPANISH
    .string "Hay una señora que vive en una\n"
    .string "casita en el cabo.\p"
    .string "Es un poco desconcertante,\n"
    .string "¡le tira los tejos a los POKéMON!$"
    .endif

TwoIsland_Text_HaveYouTriedJumpingGame::
    .ifdef ENGLISH
    .string "Boing! Boing!\n"
    .string "Have you tried the jumping game?\p"
    .string "The POKéMON you can enter…\n"
    .string "Boing!\p"
    .string "Some go boing!\p"
    .string "And some go boooooooing!\p"
    .string "Did you know that?\n"
    .string "Boing!$"
    .endif
    .ifdef SPANISH
    .string "¡Boing! ¡Boing!\n"
    .string "¿Has probado el juego de los\l"
    .string "saltos?\p"
    .string "Los POKéMON que pueden\n"
    .string "participar...\l"
    .string "¡Boing! ¡Boing!\p"
    .string "¡Algunos dan saltos!\p"
    .string "¡Y otros, dan saaaaaaaaaaaltos!\p"
    .string "¿Lo sabías?\n"
    .string "¡Boing! ¡Boing!$"
    .endif

