TwoIsland_PokemonCenter_1F_Text_HaveYouVisitedGameCorner::
    .ifdef ENGLISH
    .string "Have you visited the GAME CORNER\n"
    .string "already?\p"
    .string "It's no good to go alone.\n"
    .string "You have to take a friend along.$"
    .endif
    .ifdef SPANISH
    .string "¿Conoces ya los RECREATIVOS?\p"
    .string "Lo suyo es ir al menos con\n"
    .string "un amigo. Si no, es un rollo.$"
    .endif

TwoIsland_PokemonCenter_1F_Text_OldLadyLivesOutOnCape::
    .ifdef ENGLISH
    .string "Not many people live on\n"
    .string "TWO ISLAND.\p"
    .string "There is this old lady who lives\n"
    .string "out on the cape.\p"
    .string "She's been there since I don't know\n"
    .string "when.$"
    .endif
    .ifdef SPANISH
    .string "ISLA SECUNDA tiene muy pocos\n"
    .string "habitantes.\p"
    .string "En el mismo cabo vive una señora\n"
    .string "mayor.\p"
    .string "Lleva allí ni se sabe...$"
    .endif

