FiveIsland_ResortGorgeous_House_Text_PleaseHearMyWish::
    .ifdef ENGLISH
    .string "SELPHY: Oh?\n"
    .string "Do I know you from somewhere?\p"
    .string "Oh, but that doesn't matter.\p"
    .string "I am exquisitely bored.\n"
    .string "Please, hear my wish.$"
    .endif
    .ifdef SPANISH
    .string "CONSU: ¿Mmm?\n"
    .string "¿No te conozco de algo?\p"
    .string "Bueno, da igual.\p"
    .string "Me aburro como una ostra, ¿tienes\n"
    .string "un segundito para mí?\l"
    .string "¿Sabes lo que me gustaría hacer?$"
    .endif

FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPlease::
    .ifdef ENGLISH
    .string "I wish to see a POKéMON.\n"
    .string "A darling {STR_VAR_1}.\p"
    .string "I want to see one right away.\n"
    .string "Please, make my wish come true.$"
    .endif
    .ifdef SPANISH
    .string "Me gustaría ver algún POKéMON,\n"
    .string "uno de esos {STR_VAR_1} adorables.\p"
    .string "¡Y quiero verlo ahora!\n"
    .string "Enséñame uno, anda.$"
    .endif

FiveIsland_ResortGorgeous_House_Text_OhImTiredOfWaiting::
    .ifdef ENGLISH
    .string "SELPHY: Oh, I'm tired of this.\n"
    .string "I'm tired of waiting for you.\p"
    .string "I'll forgive you this time, but\n"
    .string "please don't fail me next time.$"
    .endif
    .ifdef SPANISH
    .string "CONSU: Estoy hasta el gorro.\n"
    .string "¡Llevo esperándote un montón!\p"
    .string "Por esta vez, te perdono,\n"
    .string "pero no me falles la próxima.$"
    .endif

FiveIsland_ResortGorgeous_House_Text_MonYouCaughtForMeThankYou::
    .ifdef ENGLISH
    .string "SELPHY: Oh, hello, there.\p"
    .string "Oh, my gracious. That must be the\n"
    .string "{STR_VAR_1} you caught for me.\p"
    .string "Giggle…\n"
    .string "I see a resemblance to you.\p"
    .string "Thank you so kindly.\p"
    .string "… …  … …  … …\n"
    .string "Is something the matter?\p"
    .string "You may leave.\p"
    .string "… …  … …  … …\n"
    .string "Oh, fine. I understand now.\p"
    .string "SEBASTIAN!\n"
    .string "I need you here this instant!$"
    .endif
    .ifdef SPANISH
    .string "CONSU: Hola.\p"
    .string "¡Anda, ése debe de ser el \n"
    .string "{STR_VAR_1} que atrapaste para mí!\p"
    .string "Ja, ja, ja...\n"
    .string "Os parecéis un poco...\p"
    .string "Muchísimas gracias.\p"
    .string "... ... ... ... ... ...\n"
    .string "Eh... ¿pasa algo?\p"
    .string "Puedes irte.\p"
    .string "... ... ... ... ... ...\n"
    .string "Ah, vale, de acuerdo.\p"
    .string "¡SEBASTIÁN!\n"
    .string "¡Ven aquí ahora mismo!$"
    .endif

FiveIsland_ResortGorgeous_House_Text_ButlerYesMyLady::
    .ifdef ENGLISH
    .string "Butler: Yes, my lady.$"
    .endif
    .ifdef SPANISH
    .string "MAYORDOMO: Sí, señora.$"
    .endif

FiveIsland_ResortGorgeous_House_Text_SelphyGiveTokenOfAppreciation::
    .ifdef ENGLISH
    .string "SELPHY: See to it that this person\n"
    .string "is given a token of appreciation.$"
    .endif
    .ifdef SPANISH
    .string "CONSU: Muéstrale lo agradecida\n"
    .string "que estoy.$"
    .endif

FiveIsland_ResortGorgeous_House_Text_ButlerIShallDoAsYouBid::
    .ifdef ENGLISH
    .string "Butler: I shall do as you bid,\n"
    .string "my lady.$"
    .endif
    .ifdef SPANISH
    .string "MAYORDOMO: Como desee, señora.$"
    .endif

FiveIsland_ResortGorgeous_House_Text_ButlerPleaseAcceptThisAsHerThanks::
    .ifdef ENGLISH
    .string "Butler: I sincerely thank you for\n"
    .string "pleasing Lady SELPHY.\p"
    .string "Please accept this as her thanks…$"
    .endif
    .ifdef SPANISH
    .string "MAYORDOMO: Gracias de verdad por\n"
    .string "haber agradado a la Señora CONSU.\p"
    .string "Acepte esto como agradecimiento.$"
    .endif

FiveIsland_ResortGorgeous_House_Text_ButlerBagAppearsToBeFull::
    .ifdef ENGLISH
    .string "Butler: Your BAG appears to be\n"
    .string "unfortunately full.$"
    .endif
    .ifdef SPANISH
    .string "MAYORDOMO: Desafortunadamente,\n"
    .string "parece que tiene la MOCHILA llena.$"
    .endif

FiveIsland_ResortGorgeous_House_Text_OhHowDisappointing::
    .ifdef ENGLISH
    .string "Oh…\n"
    .string "How disappointing.$"
    .endif
    .ifdef SPANISH
    .string "Vaya...\n"
    .string "Qué pena.$"
    .endif

FiveIsland_ResortGorgeous_House_Text_SelphyWishYouBestOfLuck::
    .ifdef ENGLISH
    .string "SELPHY: I wish you the best of\n"
    .string "luck.$"
    .endif
    .ifdef SPANISH
    .string "CONSU: Espero que te vaya \n"
    .string "muy bien.$"
    .endif

FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun::
    .ifdef ENGLISH
    .string "Butler: The smile of Lady SELPHY\n"
    .string "has the brilliance of the sun.\p"
    .string "Please, I beg you to bring joy\n"
    .string "to Lady SELPHY.$"
    .endif
    .ifdef SPANISH
    .string "MAYORDOMO: La Señora CONSU\n"
    .string "tiene una sonrisa deslumbrante.\p"
    .string "Espero que no se le borre.$"
    .endif

