FiveIsland_ResortGorgeous_House_Text_PleaseHearMyWish::
	.string "THEMIS: Oh?\n"
	.string "Est-ce qu'on se connaît?\p"
	.string "Oh, mais c'est pas grave.\p"
	.string "Je m'ennuie, tu voudrais pas\n"
	.string "me rendre un service?$"

FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPlease::
	.string "Il y a un POKéMON que j'aimerais\n"
	.string "voir. C'est {STR_VAR_1}.\p"
	.string "Je veux en voir un maintenant.\n"
	.string "Exauce mon souhait!$"

FiveIsland_ResortGorgeous_House_Text_OhImTiredOfWaiting::
	.string "THEMIS: Oh, je m'ennuie tellement.\n"
	.string "J'en ai assez de t'attendre.\p"
	.string "Je te pardonne pour cette fois,\n"
	.string "mais ne recommence pas.$"

FiveIsland_ResortGorgeous_House_Text_MonYouCaughtForMeThankYou::
	.string "THEMIS: Tiens, salut.\p"
	.string "Oh, mais… c'est le {STR_VAR_1}\n"
	.string "que tu devais me ramener.\p"
	.string "C'est marrant, il te ressemble\n"
	.string "un peu, tu trouves pas?\p"
	.string "En tout cas, c'est très gentil\n"
	.string "de ta part!\p"
	.string "… …  … …  … …\n"
	.string "Eh bien? Il y a un problème?\p"
	.string "Tu peux disposer maintenant.\p"
	.string "… …  … …  … …\n"
	.string "Ah oui, je comprends.\p"
	.string "SEBASTIAN!\n"
	.string "Veuillez venir s'il vous plaît!$"

FiveIsland_ResortGorgeous_House_Text_ButlerYesMyLady::
	.string "MAJORDOME: Oui?$"

FiveIsland_ResortGorgeous_House_Text_SelphyGiveTokenOfAppreciation::
	.string "THEMIS: SEBASTIAN, veuillez donner\n"
	.string "à cette personne la preuve de\p"
	.string "ma reconnaissance.$"

FiveIsland_ResortGorgeous_House_Text_ButlerIShallDoAsYouBid::
	.string "MAJORDOME: Oui mademoiselle.\n"
	.string "Comme vous voudrez.$"

FiveIsland_ResortGorgeous_House_Text_ButlerPleaseAcceptThisAsHerThanks::
	.string "MAJORDOME: Veuillez recevoir ceci\n"
	.string "de la part de mademoiselle THEMIS.$"

FiveIsland_ResortGorgeous_House_Text_ButlerBagAppearsToBeFull::
	.string "MAJORDOME: Quel dommage, votre\n"
	.string "SAC semble être déjà plein.$"

FiveIsland_ResortGorgeous_House_Text_OhHowDisappointing::
	.string "Oh…\n"
	.string "Comme c'est dommage.$"

FiveIsland_ResortGorgeous_House_Text_SelphyWishYouBestOfLuck::
	.string "THEMIS: Je vous souhaite toute\n"
	.string "la réussite possible.$"

FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun::
	.string "MAJORDOME: Le sourire de\n"
	.string "mademoiselle THEMIS a l'éclat\l"
	.string "du soleil.\p"
	.string "J'espère que vous réussirez à\n"
	.string "le lui rendre. $"

