FiveIsland_ResortGorgeous_House_Text_PleaseHearMyWish::
    .string "CONSU: ¿Mmm?\n"
    .string "¿No te conozco de algo?\p"
    .string "Bueno, da igual.\p"
    .string "Me aburro como una ostra, ¿tienes\n"
    .string "un segundito para mí?\l"
    .string "¿Sabes lo que me gustaría hacer?$"

FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPlease::
    .string "Me gustaría ver algún POKéMON,\n"
    .string "uno de esos {STR_VAR_1} adorables.\p"
    .string "¡Y quiero verlo ahora!\n"
    .string "Enséñame uno, anda.$"

FiveIsland_ResortGorgeous_House_Text_OhImTiredOfWaiting::
    .string "CONSU: Estoy hasta el gorro.\n"
    .string "¡Llevo esperándote un montón!\p"
    .string "Por esta vez, te perdono,\n"
    .string "pero no me falles la próxima.$"

FiveIsland_ResortGorgeous_House_Text_MonYouCaughtForMeThankYou::
    .string "CONSU: Hola.\p"
    .string "¡Anda, ése debe de ser el \n"
    .string "{STR_VAR_1} que atrapaste para mí!\p"
    .string "Ja, ja, ja...\n"
    .string "Os parecéis un poco...\p"
    .string "Muchísimas gracias.\p"
    .string "... ... ... ... ... ...\n"
    .string "Eh... ¿pasa algo?\p"
    .string "Puedes irte.\p"
    .string "... ... ... ... ... ...\n"
    .string "Ah, vale, de acuerdo.\p"
    .string "¡SEBASTIÁN!\n"
    .string "¡Ven aquí ahora mismo!$"

FiveIsland_ResortGorgeous_House_Text_ButlerYesMyLady::
    .string "MAYORDOMO: Sí, señora.$"

FiveIsland_ResortGorgeous_House_Text_SelphyGiveTokenOfAppreciation::
    .string "CONSU: Muéstrale lo agradecida\n"
    .string "que estoy.$"

FiveIsland_ResortGorgeous_House_Text_ButlerIShallDoAsYouBid::
    .string "MAYORDOMO: Como desee, señora.$"

FiveIsland_ResortGorgeous_House_Text_ButlerPleaseAcceptThisAsHerThanks::
    .string "MAYORDOMO: Gracias de verdad por\n"
    .string "haber agradado a la Señora CONSU.\p"
    .string "Acepte esto como agradecimiento.$"

FiveIsland_ResortGorgeous_House_Text_ButlerBagAppearsToBeFull::
    .string "MAYORDOMO: Desafortunadamente,\n"
    .string "parece que tiene la MOCHILA llena.$"

FiveIsland_ResortGorgeous_House_Text_OhHowDisappointing::
    .string "Vaya...\n"
    .string "Qué pena.$"

FiveIsland_ResortGorgeous_House_Text_SelphyWishYouBestOfLuck::
    .string "CONSU: Espero que te vaya \n"
    .string "muy bien.$"

FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun::
    .string "MAYORDOMO: La Señora CONSU\n"
    .string "tiene una sonrisa deslumbrante.\p"
    .string "Espero que no se le borre.$"
