FiveIsland_LostCave_Room4_Text_LauraIntro::
    .ifdef ENGLISH
    .string "I think there is a mysterious power\n"
    .string "at work in this cave.$"
    .endif
    .ifdef SPANISH
    .string "A mí me parece que en esta cueva\n"
    .string "se está cociendo algo.$"
    .endif

FiveIsland_LostCave_Room4_Text_LauraDefeat::
    .ifdef ENGLISH
    .string "If you don't go into the right\n"
    .string "tunnel, you won't get ahead.$"
    .endif
    .ifdef SPANISH
    .string "Como no tomes el túnel adecuado,\n"
    .string "no conseguirás avanzar.$"
    .endif

FiveIsland_LostCave_Room4_Text_LauraPostBattle::
    .ifdef ENGLISH
    .string "Earlier, a lady went into the caves\n"
    .string "ahead.$"
    .endif
    .ifdef SPANISH
    .string "Hace poco entró una señora\n"
    .string "en las cuevas de ahí.$"
    .endif

