FiveIsland_LostCave_Room4_Text_LauraIntro::
	.string "Ich glaube, dass in dieser\n"
	.string "Höhle eine geheimnisvolle\l"
	.string "Kraft wirkt.$"

FiveIsland_LostCave_Room4_Text_LauraDefeat::
	.string "Wenn du nicht den richtigen\n"
	.string "Tunnel erwischst, kommst\l"
	.string "du nie voran!$"

FiveIsland_LostCave_Room4_Text_LauraPostBattle::
	.string "Vor kurzem ging eine Frau\n"
	.string "in diese Höhlen.$"

