Route16_Text_LaoIntro::
    .ifdef ENGLISH
    .string "What do you want?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué quieres?$"
    .endif

Route16_Text_LaoDefeat::
    .ifdef ENGLISH
    .string "Don't you dare laugh!$"
    .endif
    .ifdef SPANISH
    .string "¡No te atrevas a reírte!$"
    .endif

Route16_Text_LaoPostBattle::
    .ifdef ENGLISH
    .string "We like just hanging here.\n"
    .string "What's it to you?$"
    .endif
    .ifdef SPANISH
    .string "Nos gusta correr por aquí.\n"
    .string "¿Y a ti?$"
    .endif

Route16_Text_KojiIntro::
    .ifdef ENGLISH
    .string "Nice BIKE!\n"
    .string "Hand it over!$"
    .endif
    .ifdef SPANISH
    .string "¡Bonita BICI!\n"
    .string "¡Dámela!$"
    .endif

Route16_Text_KojiDefeat::
    .ifdef ENGLISH
    .string "Knockout!$"
    .endif
    .ifdef SPANISH
    .string "¡Fuera de combate!$"
    .endif

Route16_Text_KojiPostBattle::
    .ifdef ENGLISH
    .string "Forget it, who needs your BIKE!$"
    .endif
    .ifdef SPANISH
    .string "¡Olvídalo, nadie necesita tu BICI!$"
    .endif

Route16_Text_LukeIntro::
    .ifdef ENGLISH
    .string "Come out and play, little mouse!$"
    .endif
    .ifdef SPANISH
    .string "¡Baja de ahí y lucha, enclenque!$"
    .endif

Route16_Text_LukeDefeat::
    .ifdef ENGLISH
    .string "You little rat!$"
    .endif
    .ifdef SPANISH
    .string "¡Eres lo peor!$"
    .endif

Route16_Text_LukePostBattle::
    .ifdef ENGLISH
    .string "I hate losing!\n"
    .string "Get out of my face!$"
    .endif
    .ifdef SPANISH
    .string "¡Odio perder!\n"
    .string "¡No te acerques a mí!$"
    .endif

Route16_Text_HideoIntro::
    .ifdef ENGLISH
    .string "Hey, you just bumped me!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye! ¡Me has dado!$"
    .endif

Route16_Text_HideoDefeat::
    .ifdef ENGLISH
    .string "Kaboom!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué golpe!$"
    .endif

Route16_Text_HideoPostBattle::
    .ifdef ENGLISH
    .string "We'll always be hanging around here\n"
    .string "even if you don't like it.\p"
    .string "You can detour to VERMILION from\n"
    .string "FUCHSIA going along the coast.$"
    .endif
    .ifdef SPANISH
    .string "Te guste o no, de aquí no nos\n"
    .string "va a echar nadie.\p"
    .string "A FUCSIA puedes llegar también\n"
    .string "desde CARMÍN, por la costa.$"
    .endif

Route16_Text_CamronIntro::
    .ifdef ENGLISH
    .string "I'm feeling hungry and mean!\n"
    .string "I need a punching bag!$"
    .endif
    .ifdef SPANISH
    .string "¡Tengo hambre y no estoy\n"
    .string "de humor!$"
    .endif

Route16_Text_CamronDefeat::
    .ifdef ENGLISH
    .string "Bad, bad, bad!$"
    .endif
    .ifdef SPANISH
    .string "¡Mal, mal, muy mal!$"
    .endif

Route16_Text_CamronPostBattle::
    .ifdef ENGLISH
    .string "If I'm going to have POKéMON, they\n"
    .string "may as well be ferocious.\p"
    .string "I'd use them to leave my enemies\n"
    .string "in tatters.$"
    .endif
    .ifdef SPANISH
    .string "¡Me gustan mis fuertes POKéMON!\n"
    .string "¡Son tremendos contra mis enemigos!$"
    .endif

Route16_Text_RubenIntro::
    .ifdef ENGLISH
    .string "Hey, there!\n"
    .string "Let's have ourselves a good time!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, vamos a echar el rato!$"
    .endif

Route16_Text_RubenDefeat::
    .ifdef ENGLISH
    .string "Don't make me mad!$"
    .endif
    .ifdef SPANISH
    .string "¡No me fastidies!$"
    .endif

Route16_Text_RubenPostBattle::
    .ifdef ENGLISH
    .string "I get my kicks by harassing people\n"
    .string "with my stinking POKéMON.\p"
    .string "They're great for startling people.\n"
    .string "And, they bite, too.$"
    .endif
    .ifdef SPANISH
    .string "Yo me parto tomándole el pelo\n"
    .string "a la gente con mis POKéMON.\p"
    .string "¡Son los mejores para asustar\n"
    .string "a la gente y, además, muerden!$"
    .endif

Route16_Text_MonSprawledOutInSlumber::
    .ifdef ENGLISH
    .string "A POKéMON is sprawled out in\n"
    .string "a deep and comfortable slumber.$"
    .endif
    .ifdef SPANISH
    .string "¡Un POKéMON dormido bloquea\n"
    .string "el camino!$"
    .endif

Route16_Text_CyclingRoadSign::
    .ifdef ENGLISH
    .string "Enjoy the slope!\n"
    .string "CYCLING ROAD$"
    .endif
    .ifdef SPANISH
    .string "CAMINO DE BICIS\n"
    .string "¡Buen descenso!$"
    .endif

Route16_Text_RouteSign::
    .ifdef ENGLISH
    .string "ROUTE 16\n"
    .string "CELADON CITY - FUCHSIA CITY$"
    .endif
    .ifdef SPANISH
    .string "RUTA 16:\n"
    .string "CIUDAD AZULONA - CIUDAD FUCSIA$"
    .endif

Route16_Text_JedIntro::
    .ifdef ENGLISH
    .string "JED: Our love knows no bounds.\n"
    .string "We're in love and we show it!$"
    .endif
    .ifdef SPANISH
    .string "JOEL: Nuestro amor no conoce\n"
    .string "límites.\p"
    .string "Estamos enamorados y no lo\n"
    .string "ocultamos.$"
    .endif

Route16_Text_JedDefeat::
    .ifdef ENGLISH
    .string "JED: Oh, no!\n"
    .string "My love has seen me as a loser!$"
    .endif
    .ifdef SPANISH
    .string "JOEL: ¡He perdido, pero no\n"
    .string "en el amor!$"
    .endif

Route16_Text_JedPostBattle::
    .ifdef ENGLISH
    .string "JED: Listen, LEA.\n"
    .string "You need to focus less on me.$"
    .endif
    .ifdef SPANISH
    .string "JOEL: ¡Oye, LIZ, no te quedes\n"
    .string "embobada conmigo!$"
    .endif

Route16_Text_JedNotEnoughMons::
    .ifdef ENGLISH
    .string "JED: You have just one POKéMON?\n"
    .string "Is there no love in your heart?$"
    .endif
    .ifdef SPANISH
    .string "JOEL: ¿Sólo tienes un POKéMON?\n"
    .string "¿Y no te da pena?$"
    .endif

Route16_Text_LeaIntro::
    .ifdef ENGLISH
    .string "LEA: Sometimes, the intensity of\n"
    .string "our love scares me.$"
    .endif
    .ifdef SPANISH
    .string "LIZ: ¡A veces, pienso en todo\n"
    .string "lo que nos queremos y se me pone\l"
    .string "la carne de gallina!$"
    .endif

Route16_Text_LeaDefeat::
    .ifdef ENGLISH
    .string "LEA: Ohh! But JED looks cool\n"
    .string "even in a loss!$"
    .endif
    .ifdef SPANISH
    .string "LIZ: ¡JOEL me gusta hasta cuando\n"
    .string "pierde!$"
    .endif

Route16_Text_LeaPostBattle::
    .ifdef ENGLISH
    .string "LEA: Ehehe, I'm sorry.\n"
    .string "JED is so cool.$"
    .endif
    .ifdef SPANISH
    .string "LIZ: Lo siento, pero no hay nadie\n"
    .string "como JOEL.$"
    .endif

Route16_Text_LeaNotEnoughMons::
    .ifdef ENGLISH
    .string "LEA: Oh, you don't have two\n"
    .string "POKéMON with you?\p"
    .string "Doesn't it feel lonely for you or\n"
    .string "your POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "LIZ: ¿No tienes dos POKéMON?\p"
    .string "¿Y no os sentís solos?$"
    .endif
