Route16_Text_LaoIntro::
    .string "¿Qué quieres?$"

Route16_Text_LaoDefeat::
    .string "¡No te atrevas a reírte!$"

Route16_Text_LaoPostBattle::
    .string "Nos gusta correr por aquí.\n"
    .string "¿Y a ti?$"

Route16_Text_KojiIntro::
    .string "¡Bonita BICI!\n"
    .string "¡Dámela!$"

Route16_Text_KojiDefeat::
    .string "¡Fuera de combate!$"

Route16_Text_KojiPostBattle::
    .string "¡Olvídalo, nadie necesita tu BICI!$"

Route16_Text_LukeIntro::
    .string "¡Baja de ahí y lucha, enclenque!$"

Route16_Text_LukeDefeat::
    .string "¡Eres lo peor!$"

Route16_Text_LukePostBattle::
    .string "¡Odio perder!\n"
    .string "¡No te acerques a mí!$"

Route16_Text_HideoIntro::
    .string "¡Oye! ¡Me has dado!$"

Route16_Text_HideoDefeat::
    .string "¡Qué golpe!$"

Route16_Text_HideoPostBattle::
    .string "Te guste o no, de aquí no nos\n"
    .string "va a echar nadie.\p"
    .string "A FUCSIA puedes llegar también\n"
    .string "desde CARMÍN, por la costa.$"

Route16_Text_CamronIntro::
    .string "¡Tengo hambre y no estoy\n"
    .string "de humor!$"

Route16_Text_CamronDefeat::
    .string "¡Mal, mal, muy mal!$"

Route16_Text_CamronPostBattle::
    .string "¡Me gustan mis fuertes POKéMON!\n"
    .string "¡Son tremendos contra mis enemigos!$"

Route16_Text_RubenIntro::
    .string "¡Eh, vamos a echar el rato!$"

Route16_Text_RubenDefeat::
    .string "¡No me fastidies!$"

Route16_Text_RubenPostBattle::
    .string "Yo me parto tomándole el pelo\n"
    .string "a la gente con mis POKéMON.\p"
    .string "¡Son los mejores para asustar\n"
    .string "a la gente y, además, muerden!$"

Route16_Text_MonSprawledOutInSlumber::
    .string "¡Un POKéMON dormido bloquea\n"
    .string "el camino!$"

Route16_Text_CyclingRoadSign::
    .string "CAMINO DE BICIS\n"
    .string "¡Buen descenso!$"

Route16_Text_RouteSign::
    .string "RUTA 16:\n"
    .string "CIUDAD AZULONA - CIUDAD FUCSIA$"

Route16_Text_JedIntro::
    .string "JOEL: Nuestro amor no conoce\n"
    .string "límites.\p"
    .string "Estamos enamorados y no lo\n"
    .string "ocultamos.$"

Route16_Text_JedDefeat::
    .string "JOEL: ¡He perdido, pero no\n"
    .string "en el amor!$"

Route16_Text_JedPostBattle::
    .string "JOEL: ¡Oye, LIZ, no te quedes\n"
    .string "embobada conmigo!$"

Route16_Text_JedNotEnoughMons::
    .string "JOEL: ¿Sólo tienes un POKéMON?\n"
    .string "¿Y no te da pena?$"

Route16_Text_LeaIntro::
    .string "LIZ: ¡A veces, pienso en todo\n"
    .string "lo que nos queremos y se me pone\l"
    .string "la carne de gallina!$"

Route16_Text_LeaDefeat::
    .string "LIZ: ¡JOEL me gusta hasta cuando\n"
    .string "pierde!$"

Route16_Text_LeaPostBattle::
    .string "LIZ: Lo siento, pero no hay nadie\n"
    .string "como JOEL.$"

Route16_Text_LeaNotEnoughMons::
    .string "LIZ: ¿No tienes dos POKéMON?\p"
    .string "¿Y no os sentís solos?$"
