Route6_Text_RickyIntro::
    .ifdef ENGLISH
    .string "Who's there?\n"
    .string "Quit listening in on us!$"
    .endif
    .ifdef SPANISH
    .string "¿Quién está ahí?\n"
    .string "¡Deja de espiarnos!$"
    .endif

Route6_Text_RickyDefeat::
    .ifdef ENGLISH
    .string "I just can't win!$"
    .endif
    .ifdef SPANISH
    .string "¡Sencillamente, no puedo ganar!$"
    .endif

Route6_Text_RickyPostBattle::
    .ifdef ENGLISH
    .string "Whisper…\n"
    .string "Whisper…$"
    .endif
    .ifdef SPANISH
    .string "(Pues sí que...)$"
    .endif

Route6_Text_NancyIntro::
    .ifdef ENGLISH
    .string "Excuse me!\n"
    .string "This is a private conversation!$"
    .endif
    .ifdef SPANISH
    .string "¡Perdona!\n"
    .string "¡Esta conversación es privada!$"
    .endif

Route6_Text_NancyDefeat::
    .ifdef ENGLISH
    .string "Ugh!\n"
    .string "I hate losing.$"
    .endif
    .ifdef SPANISH
    .string "¡Odio perder!$"
    .endif

Route6_Text_NancyPostBattle::
    .ifdef ENGLISH
    .string "Whisper…\n"
    .string "Whisper…$"
    .endif
    .ifdef SPANISH
    .string "(Pues sí que...)$"
    .endif

Route6_Text_KeigoIntro::
    .ifdef ENGLISH
    .string "There aren't many bugs out here.$"
    .endif
    .ifdef SPANISH
    .string "No hay muchos bichos por aquí.$"
    .endif

Route6_Text_KeigoDefeat::
    .ifdef ENGLISH
    .string "No!\n"
    .string "You're kidding!$"
    .endif
    .ifdef SPANISH
    .string "¡No!\n"
    .string "¿Estás de broma?$"
    .endif

Route6_Text_KeigoPostBattle::
    .ifdef ENGLISH
    .string "I like bugs, so I'm going back to\n"
    .string "VIRIDIAN FOREST.$"
    .endif
    .ifdef SPANISH
    .string "Me gustan los bichos. Voy a\n"
    .string "regresar al BOSQUE VERDE.$"
    .endif

Route6_Text_JeffIntro::
    .ifdef ENGLISH
    .string "Huh?\n"
    .string "You want to talk to me?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué?\n"
    .string "¿Quieres hablar conmigo?$"
    .endif

Route6_Text_JeffDefeat::
    .ifdef ENGLISH
    .string "This stinks…\n"
    .string "I couldn't beat your challenge…$"
    .endif
    .ifdef SPANISH
    .string "¡Has empezado tú!$"
    .endif

Route6_Text_JeffPostBattle::
    .ifdef ENGLISH
    .string "I should bring more POKéMON with\n"
    .string "me. I'll feel safer that way.$"
    .endif
    .ifdef SPANISH
    .string "Debería llevar más POKéMON\n"
    .string "para protegerme.$"
    .endif

Route6_Text_IsabelleIntro::
    .ifdef ENGLISH
    .string "Me?\n"
    .string "Well, okay. I'll play!$"
    .endif
    .ifdef SPANISH
    .string "¿Yo?\n"
    .string "Pues vale. ¡Jugaré!$"
    .endif

Route6_Text_IsabelleDefeat::
    .ifdef ENGLISH
    .string "Things just didn't work…$"
    .endif
    .ifdef SPANISH
    .string "¡No ha podido ser!$"
    .endif

Route6_Text_IsabellePostBattle::
    .ifdef ENGLISH
    .string "I want to get stronger.\n"
    .string "What's your secret?$"
    .endif
    .ifdef SPANISH
    .string "¡Quiero ser más fuerte!\n"
    .string "¿Cuál es tu secreto?$"
    .endif

Route6_Text_ElijahIntro::
    .ifdef ENGLISH
    .string "I've never seen you around.\n"
    .string "Are you good?$"
    .endif
    .ifdef SPANISH
    .string "¡Jamás te había visto por aquí!\n"
    .string "¿Eres fuerte?$"
    .endif

Route6_Text_ElijahDefeat::
    .ifdef ENGLISH
    .string "You're too good!$"
    .endif
    .ifdef SPANISH
    .string "¡Eres demasiado fuerte!$"
    .endif

Route6_Text_ElijahPostBattle::
    .ifdef ENGLISH
    .string "Are my POKéMON weak?\n"
    .string "Or, am I just bad?\l"
    .string "Which do you think?$"
    .endif
    .ifdef SPANISH
    .string "¿Es débil mi POKéMON o soy yo\n"
    .string "muy malo?$"
    .endif

Route6_Text_UndergroundPathSign::
    .ifdef ENGLISH
    .string "UNDERGROUND PATH\n"
    .string "CERULEAN CITY - VERMILION CITY$"
    .endif
    .ifdef SPANISH
    .string "VÍA SUBTERRÁNEA:\n"
    .string "CIUDAD CELESTE - CIUDAD CARMÍN$"
    .endif

