CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
    .ifdef ENGLISH
    .string "Only skilled TRAINERS can collect\n"
    .string "POKéMON BADGES.\p"
    .string "I see you have at least one.\p"
    .string "Those BADGES have amazing secrets,\n"
    .string "did you know?$"
    .endif
    .ifdef SPANISH
    .string "Sólo tienen MEDALLAS los\n"
    .string "ENTRENADORES más hábiles.\p"
    .string "Ya veo que tienes una por lo\n"
    .string "menos.\p"
    .string "¡Esas MEDALLAS guardan secretos\n"
    .string "increíbles!$"
    .endif

CeruleanCity_House1_Text_DescribeWhichBadge::
    .ifdef ENGLISH
    .string "Now then…\p"
    .string "Which of the eight BADGES should\n"
    .string "I describe?$"
    .endif
    .ifdef SPANISH
    .string "Dime...\p"
    .string "¿Cuál de las 8 MEDALLAS debería\n"
    .string "describirte?$"
    .endif

CeruleanCity_House1_Text_ComeVisitAnytime::
    .ifdef ENGLISH
    .string "Come visit me anytime you wish.$"
    .endif
    .ifdef SPANISH
    .string "Ven a verme cuando quieras.$"
    .endif

CeruleanCity_House1_Text_AttackStatFlash::
    .ifdef ENGLISH
    .string "The ATTACK stat of all your\n"
    .string "POKéMON increases a little bit.\p"
    .string "It also lets you use the move\n"
    .string "FLASH outside of battle.$"
    .endif
    .ifdef SPANISH
    .string "Hace que aumente un poco\n"
    .string "el ATAQUE de los POKéMON.\p"
    .string "Y permite usar DESTELLO siempre\n"
    .string "que quieras.$"
    .endif

CeruleanCity_House1_Text_ObeyLv30Cut::
    .ifdef ENGLISH
    .string "POKéMON up to Lv. 30 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "POKéMON of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "CUT outside of battle.$"
    .endif
    .ifdef SPANISH
    .string "Hace que te obedezcan los POKéMON\n"
    .string "de nivel inferior a 30.\p"
    .string "Y no sólo los tuyos, sino también\n"
    .string "los forasteros obtenidos\l"
    .string "por intercambio.\p"
    .string "¡Los de nivel superior, serán\n"
    .string "incontrolables!\p"
    .string "También permite usar CORTAR\n"
    .string "fuera del combate.$"
    .endif

CeruleanCity_House1_Text_SpeedStatFly::
    .ifdef ENGLISH
    .string "The SPEED stat of all your\n"
    .string "POKéMON increases a little bit.\p"
    .string "It also lets you use the move\n"
    .string "FLY outside of battle.$"
    .endif
    .ifdef SPANISH
    .string "Hace que aumente un poco\n"
    .string "la VELOCIDAD de los POKéMON.\p"
    .string "Y permite usar VOLAR siempre\n"
    .string "que quieras.$"
    .endif

CeruleanCity_House1_Text_ObeyLv50Strength::
    .ifdef ENGLISH
    .string "POKéMON up to Lv. 50 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "POKéMON of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "STRENGTH outside of battle.$"
    .endif
    .ifdef SPANISH
    .string "Hace que te obedezcan los POKéMON\n"
    .string "de nivel inferior a 50.\p"
    .string "Y no sólo los tuyos, sino también\n"
    .string "los forasteros obtenidos\l"
    .string "por intercambio.\p"
    .string "¡Los de nivel superior, serán\n"
    .string "incontrolables!\p"
    .string "También permite usar FUERZA\n"
    .string "fuera del combate.$"
    .endif

CeruleanCity_House1_Text_DefenseStatSurf::
    .ifdef ENGLISH
    .string "The DEFENSE stat of all your\n"
    .string "POKéMON increases a little bit.\p"
    .string "It also lets you use the move\n"
    .string "SURF outside of battle.$"
    .endif
    .ifdef SPANISH
    .string "Hace que aumente un poco\n"
    .string "la DEFENSA de los POKéMON.\p"
    .string "Y permite usar SURF siempre\n"
    .string "que quieras.$"
    .endif

CeruleanCity_House1_Text_ObeyLv70RockSmash::
    .ifdef ENGLISH
    .string "POKéMON up to Lv. 70 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "POKéMON of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "ROCK SMASH outside of battle.$"
    .endif
    .ifdef SPANISH
    .string "Hace que te obedezcan los POKéMON\n"
    .string "de nivel inferior a 70.\p"
    .string "Y no sólo los tuyos, sino también\n"
    .string "los forasteros obtenidos\l"
    .string "por intercambio.\p"
    .string "¡Los de nivel superior, serán\n"
    .string "incontrolables!\p"
    .string "También permite usar GOLPE\n"
    .string "ROCA fuera del combate.$"
    .endif

CeruleanCity_House1_Text_SpStatsWaterfall::
    .ifdef ENGLISH
    .string "The SP. ATK and SP. DEF stats of\n"
    .string "all your POKéMON rise a little bit.\p"
    .string "It also lets you use the move\n"
    .string "WATERFALL outside of battle.$"
    .endif
    .ifdef SPANISH
    .string "Hace que aumenten un poco\n"
    .string "el AT. ESP. y la DEF. ESP.\l"
    .string "de los POKéMON.\p"
    .string "Y permite usar CASCADA siempre\n"
    .string "que quieras.$"
    .endif

CeruleanCity_House1_Text_AllMonsWillObeyYou::
    .ifdef ENGLISH
    .string "All POKéMON will obey you!$"
    .endif
    .ifdef SPANISH
    .string "¡Todos los POKéMON te obedecerán!$"
    .endif

