CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
    .string "Sólo tienen MEDALLAS los\n"
    .string "ENTRENADORES más hábiles.\p"
    .string "Ya veo que tienes una por lo\n"
    .string "menos.\p"
    .string "¡Esas MEDALLAS guardan secretos\n"
    .string "increíbles!$"

CeruleanCity_House1_Text_DescribeWhichBadge::
    .string "Dime...\p"
    .string "¿Cuál de las 8 MEDALLAS debería\n"
    .string "describirte?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
    .string "Ven a verme cuando quieras.$"

CeruleanCity_House1_Text_AttackStatFlash::
    .string "Hace que aumente un poco\n"
    .string "el ATAQUE de los POKéMON.\p"
    .string "Y permite usar DESTELLO siempre\n"
    .string "que quieras.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
    .string "Hace que te obedezcan los POKéMON\n"
    .string "de nivel inferior a 30.\p"
    .string "Y no sólo los tuyos, sino también\n"
    .string "los forasteros obtenidos\l"
    .string "por intercambio.\p"
    .string "¡Los de nivel superior, serán\n"
    .string "incontrolables!\p"
    .string "También permite usar CORTAR\n"
    .string "fuera del combate.$"

CeruleanCity_House1_Text_SpeedStatFly::
    .string "Hace que aumente un poco\n"
    .string "la VELOCIDAD de los POKéMON.\p"
    .string "Y permite usar VOLAR siempre\n"
    .string "que quieras.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
    .string "Hace que te obedezcan los POKéMON\n"
    .string "de nivel inferior a 50.\p"
    .string "Y no sólo los tuyos, sino también\n"
    .string "los forasteros obtenidos\l"
    .string "por intercambio.\p"
    .string "¡Los de nivel superior, serán\n"
    .string "incontrolables!\p"
    .string "También permite usar FUERZA\n"
    .string "fuera del combate.$"

CeruleanCity_House1_Text_DefenseStatSurf::
    .string "Hace que aumente un poco\n"
    .string "la DEFENSA de los POKéMON.\p"
    .string "Y permite usar SURF siempre\n"
    .string "que quieras.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
    .string "Hace que te obedezcan los POKéMON\n"
    .string "de nivel inferior a 70.\p"
    .string "Y no sólo los tuyos, sino también\n"
    .string "los forasteros obtenidos\l"
    .string "por intercambio.\p"
    .string "¡Los de nivel superior, serán\n"
    .string "incontrolables!\p"
    .string "También permite usar GOLPE\n"
    .string "ROCA fuera del combate.$"

CeruleanCity_House1_Text_SpStatsWaterfall::
    .string "Hace que aumenten un poco\n"
    .string "el AT. ESP. y la DEF. ESP.\l"
    .string "de los POKéMON.\p"
    .string "Y permite usar CASCADA siempre\n"
    .string "que quieras.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
    .string "¡Todos los POKéMON te obedecerán!$"
