ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "Puedes usar ese PC de la esquina.\p"
    .string "¡Me lo dijo la recepcionista!\n"
    .string "¡Es muy amable!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "Hay un CENTRO POKéMON en todas\n"
    .string "las ciudades.\p"
    .string "¡Y todos son gratuitos!$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "¡Los CENTROS POKéMON curan a tus\n"
    .string "POKéMON heridos o debilitados!$"
