ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
	.string "Du kannst den PC in der Ecke dort\n"
	.string "drüben benutzen!\p"
	.string "Darauf hat man mich am Empfang\n"
	.string "freundlicherweise hingewiesen.$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
	.string "Es gibt in jeder Stadt ein\n"
	.string "POKéMON-CENTER.\p"
	.string "Dort behandelt man deine POKéMON\n"
	.string "kostenlos!$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
	.string "Im POKéMON-CENTER kannst du müde,\n"
	.string "verletzte und besiegte POKéMON\l"
	.string "heilen!$"

