ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .ifdef ENGLISH
    .string "Please feel free to use that PC in\n"
    .string "the corner.\p"
    .string "The receptionist told me so.\n"
    .string "It's so kind of her!$"
    .endif
    .ifdef SPANISH
    .string "Puedes usar ese PC de la esquina.\p"
    .string "¡Me lo dijo la recepcionista!\n"
    .string "¡Es muy amable!$"
    .endif

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .ifdef ENGLISH
    .string "There's a POKéMON CENTER in every\n"
    .string "town ahead.\p"
    .string "They charge no money, so don't\n"
    .string "be shy about healing POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "Hay un CENTRO POKéMON en todas\n"
    .string "las ciudades.\p"
    .string "¡Y todos son gratuitos!$"
    .endif

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .ifdef ENGLISH
    .string "POKéMON CENTERS heal your tired,\n"
    .string "hurt, or fainted POKéMON.\p"
    .string "They make all POKéMON completely\n"
    .string "healthy.$"
    .endif
    .ifdef SPANISH
    .string "¡Los CENTROS POKéMON curan a tus\n"
    .string "POKéMON heridos o debilitados!$"
    .endif

