Route3_Text_TunnelFromCeruleanTiring::
    .ifdef ENGLISH
    .string "Whew… I better take a rest…\n"
    .string "Groan…\p"
    .string "That tunnel from CERULEAN takes a\n"
    .string "lot out of you!$"
    .endif
    .ifdef SPANISH
    .string "¡Uff!... Voy a descansar.\n"
    .string "Ufff...\p"
    .string "¡Ese túnel a CELESTE es agotador!$"
    .endif

Route3_Text_ColtonIntro::
    .ifdef ENGLISH
    .string "Hey!\n"
    .string "I saw you in VIRIDIAN FOREST!$"
    .endif
    .ifdef SPANISH
    .string "¡Nos vimos en el BOSQUE VERDE!$"
    .endif

Route3_Text_ColtonDefeat::
    .ifdef ENGLISH
    .string "You beat me again!$"
    .endif
    .ifdef SPANISH
    .string "¡Has ganado otra vez!$"
    .endif

Route3_Text_ColtonPostBattle::
    .ifdef ENGLISH
    .string "There are other kinds of POKéMON\n"
    .string "than the ones you find in forests.$"
    .endif
    .ifdef SPANISH
    .string "¡Hay otros tipos de POKéMON\n"
    .string "diferentes a los del bosque!$"
    .endif

Route3_Text_BenIntro::
    .ifdef ENGLISH
    .string "Hi!\n"
    .string "I like shorts!\p"
    .string "They're delightfully comfy and\n"
    .string "easy to wear!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola!\n"
    .string "¡Me gustan los pantalones cortos!\p"
    .string "¡Son muy cómodos!$"
    .endif

Route3_Text_BenDefeat::
    .ifdef ENGLISH
    .string "I don't believe it!$"
    .endif
    .ifdef SPANISH
    .string "¡No me lo puedo creer!$"
    .endif

Route3_Text_BenPostBattle::
    .ifdef ENGLISH
    .string "Are you using a POKéMON CENTER's\n"
    .string "PC for storing your POKéMON?\p"
    .string "Each BOX can hold up to\n"
    .string "30 POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¿Estás guardando a tus POKéMON\n"
    .string "en el PC?\p"
    .string "¡Cada CAJA puede tener 30\n"
    .string "POKéMON!$"
    .endif

Route3_Text_JaniceIntro::
    .ifdef ENGLISH
    .string "Excuse me!\n"
    .string "You looked at me, didn't you?$"
    .endif
    .ifdef SPANISH
    .string "Estabas mirándome, ¿verdad?$"
    .endif

Route3_Text_JaniceDefeat::
    .ifdef ENGLISH
    .string "You're mean!$"
    .endif
    .ifdef SPANISH
    .string "¡Eres de lo que no hay!$"
    .endif

Route3_Text_JanicePostBattle::
    .ifdef ENGLISH
    .string "You shouldn't be staring if you\n"
    .string "don't want to battle!$"
    .endif
    .ifdef SPANISH
    .string "¡Deja de mirarme si no quieres\n"
    .string "luchar!$"
    .endif

Route3_Text_GregIntro::
    .ifdef ENGLISH
    .string "Are you a TRAINER?\n"
    .string "Let's get with it right away!$"
    .endif
    .ifdef SPANISH
    .string "¿Entrenas POKéMON?\n"
    .string "¡Pues luchemos!$"
    .endif

Route3_Text_GregDefeat::
    .ifdef ENGLISH
    .string "If I had new POKéMON, I would've\n"
    .string "won!$"
    .endif
    .ifdef SPANISH
    .string "¡Con nuevos POKéMON te habría\n"
    .string "ganado!$"
    .endif

Route3_Text_GregPostBattle::
    .ifdef ENGLISH
    .string "If a POKéMON BOX on the PC gets\n"
    .string "full, just switch to another BOX.$"
    .endif
    .ifdef SPANISH
    .string "¡Si una CAJA de POKéMON del PC\n"
    .string "está llena, cambia a otra CAJA!$"
    .endif

Route3_Text_SallyIntro::
    .ifdef ENGLISH
    .string "That look you gave me…\n"
    .string "It's so intriguing!$"
    .endif
    .ifdef SPANISH
    .string "¡Esa mirada tuya fue de lo más\n"
    .string "misteriosa!$"
    .endif

Route3_Text_SallyDefeat::
    .ifdef ENGLISH
    .string "Be nice!$"
    .endif
    .ifdef SPANISH
    .string "¡Sé amable!$"
    .endif

Route3_Text_SallyPostBattle::
    .ifdef ENGLISH
    .string "You can avoid battles by not\n"
    .string "letting TRAINERS see you.$"
    .endif
    .ifdef SPANISH
    .string "¡Para evitar luchar, procura que\n"
    .string "no te vean!$"
    .endif

Route3_Text_CalvinIntro::
    .ifdef ENGLISH
    .string "Hey! You're not wearing shorts!\n"
    .string "What's wrong with you?$"
    .endif
    .ifdef SPANISH
    .string "¡Oye!\n"
    .string "¡No llevas pantalón corto!$"
    .endif

Route3_Text_CalvinDefeat::
    .ifdef ENGLISH
    .string "Lost!\n"
    .string "Lost! Lost!$"
    .endif
    .ifdef SPANISH
    .string "¡He perdido!\n"
    .string "¡He perdido!$"
    .endif

Route3_Text_CalvinPostBattle::
    .ifdef ENGLISH
    .string "I always wear shorts, even in\n"
    .string "winter. That's my policy.$"
    .endif
    .ifdef SPANISH
    .string "Llevo pantalones cortos hasta\n"
    .string "en invierno.$"
    .endif

Route3_Text_JamesIntro::
    .ifdef ENGLISH
    .string "I'll battle you with the POKéMON\n"
    .string "I just caught.$"
    .endif
    .ifdef SPANISH
    .string "¡Puedes luchar contra mis nuevos\n"
    .string "POKéMON!$"
    .endif

Route3_Text_JamesDefeat::
    .ifdef ENGLISH
    .string "Done like dinner!$"
    .endif
    .ifdef SPANISH
    .string "¡Estoy acabado!$"
    .endif

Route3_Text_JamesPostBattle::
    .ifdef ENGLISH
    .string "Trained POKéMON are stronger than\n"
    .string "the wild ones.$"
    .endif
    .ifdef SPANISH
    .string "¡Los POKéMON entrenados son más\n"
    .string "fuertes que los salvajes!$"
    .endif

Route3_Text_RobinIntro::
    .ifdef ENGLISH
    .string "Eek!\n"
    .string "Did you touch me?$"
    .endif
    .ifdef SPANISH
    .string "¡Oye!\n"
    .string "¿Por qué me has tocado?$"
    .endif

Route3_Text_RobinDefeat::
    .ifdef ENGLISH
    .string "That's it?$"
    .endif
    .ifdef SPANISH
    .string "¿Eso es todo?$"
    .endif

Route3_Text_RobinPostBattle::
    .ifdef ENGLISH
    .string "ROUTE 4 is at the foot of\n"
    .string "MT. MOON.$"
    .endif
    .ifdef SPANISH
    .string "La RUTA 4 está debajo del MT.\n"
    .string "MOON.$"
    .endif

Route3_Text_RouteSign::
    .ifdef ENGLISH
    .string "ROUTE 3\n"
    .string "MT. MOON AHEAD$"
    .endif
    .ifdef SPANISH
    .string "RUTA 3:\n"
    .string "HACIA EL MT. MOON$"
    .endif

