SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn::
    .ifdef ENGLISH
    .string "POKéMON have personalities of their\n"
    .string "own, just like people.\p"
    .string "My PIKACHU has a HASTY nature,\n"
    .string "so it grew to be a speedy POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "Los POKéMON tienen su propia\n"
    .string "personalidad, como cualquiera.\p"
    .string "Mi PIKACHU, por ejemplo, tiene\n"
    .string "una naturaleza ACTIVA, y realmente\l"
    .string "no para.$"
    .endif

SevenIsland_Mart_Text_PreparationsCompleteForRuins::
    .ifdef ENGLISH
    .string "Okay, preparations are complete\n"
    .string "for me to explore the RUINS.$"
    .endif
    .ifdef SPANISH
    .string "Bueno, ya lo tengo todo para\n"
    .string "explorar las RUINAS.$"
    .endif

SevenIsland_Mart_Text_NeedToFishOnSevenIsland::
    .ifdef ENGLISH
    .string "I need to fish on SEVEN ISLAND.\p"
    .string "That will complete my fishing tour\n"
    .string "of the SEVII ISLANDS.\p"
    .string "I'd better stock up on some\n"
    .string "POKé BALLS first, though.$"
    .endif
    .ifdef SPANISH
    .string "Tengo que pescar en ISLA SÉTIMA.\p"
    .string "Es la que me falta para completar\n"
    .string "mi ruta por ARCHI7.\p"
    .string "Pero antes, voy a hacerme con\n"
    .string "unas cuantas POKé BALLS.$"
    .endif

