Text_DoubleEdgeTeach::
    .ifdef ENGLISH
    .string "You should be proud of yourself,\n"
    .string "having battled your way through\l"
    .string "VICTORY ROAD so courageously.\p"
    .string "In recognition of your feat,\n"
    .string "I'll teach you DOUBLE-EDGE.\p"
    .string "Would you like me to teach that\n"
    .string "technique?$"
    .endif
    .ifdef SPANISH
    .string "Has conseguido abrirte paso por\n"
    .string "la CALLE VICTORIA con mucho\l"
    .string "valor; es para alegrarse.\p"
    .string "Como reconocimiento a tu hazaña,\n"
    .string "te enseñaré DOBLE FILO.\p"
    .string "¿Quieres?$"
    .endif

Text_DoubleEdgeDeclined::
    .ifdef ENGLISH
    .string "I'll teach you the technique\n"
    .string "anytime.$"
    .endif
    .ifdef SPANISH
    .string "Bueno, otra vez será.$"
    .endif

Text_DoubleEdgeWhichMon::
    .ifdef ENGLISH
    .string "Which POKéMON should I teach\n"
    .string "DOUBLE-EDGE?$"
    .endif
    .ifdef SPANISH
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe DOBLE FILO?$"
    .endif

Text_DoubleEdgeTaught::
    .ifdef ENGLISH
    .string "Keep that drive going for the\n"
    .string "POKéMON LEAGUE!\p"
    .string "Take a run at them and knock 'em\n"
    .string "out!$"
    .endif
    .ifdef SPANISH
    .string "¡No bajes la guardia para la LIGA\n"
    .string "POKéMON!\p"
    .string "¡A por ella, acaba con todos!$"
    .endif

VictoryRoad_3F_Text_GeorgeIntro::
    .ifdef ENGLISH
    .string "I heard rumors of a child prodigy.$"
    .endif
    .ifdef SPANISH
    .string "¡Los rumores hablan de un\n"
    .string "ENTRENADOR espectacular!$"
    .endif

VictoryRoad_3F_Text_GeorgeDefeat::
    .ifdef ENGLISH
    .string "The rumors were true!$"
    .endif
    .ifdef SPANISH
    .string "¡Los rumores eran ciertos!$"
    .endif

VictoryRoad_3F_Text_GeorgePostBattle::
    .ifdef ENGLISH
    .string "So, it was you who beat GIOVANNI\n"
    .string "of TEAM ROCKET?$"
    .endif
    .ifdef SPANISH
    .string "¿Derrotaste a GIOVANNI\n"
    .string "del TEAM ROCKET?$"
    .endif

VictoryRoad_3F_Text_AlexaIntro::
    .ifdef ENGLISH
    .string "TRAINERS live to seek stronger\n"
    .string "opponents.$"
    .endif
    .ifdef SPANISH
    .string "¡Los ENTRENADORES sólo viven para\n"
    .string "buscar enemigos más fuertes!$"
    .endif

VictoryRoad_3F_Text_AlexaDefeat::
    .ifdef ENGLISH
    .string "Oh!\n"
    .string "So strong!$"
    .endif
    .ifdef SPANISH
    .string "¡Oooooh!\n"
    .string "¡Eres tan fuerte!$"
    .endif

VictoryRoad_3F_Text_AlexaPostBattle::
    .ifdef ENGLISH
    .string "By fighting tough battles, you get\n"
    .string "stronger.$"
    .endif
    .ifdef SPANISH
    .string "¡Librar duros combates te hará\n"
    .string "más fuerte!$"
    .endif

VictoryRoad_3F_Text_CarolineIntro::
    .ifdef ENGLISH
    .string "I'll show you just how good you\n"
    .string "are. Not!$"
    .endif
    .ifdef SPANISH
    .string "¡Te demostraré lo fuerte que eres\n"
    .string "de verdad!$"
    .endif

VictoryRoad_3F_Text_CarolineDefeat::
    .ifdef ENGLISH
    .string "I'm furious!$"
    .endif
    .ifdef SPANISH
    .string "¡Argh! ¡Eres increíble!$"
    .endif

VictoryRoad_3F_Text_CarolinePostBattle::
    .ifdef ENGLISH
    .string "You showed me just how good\n"
    .string "I was…$"
    .endif
    .ifdef SPANISH
    .string "¡Yo soy la que ha aprendido\n"
    .string "la lección!$"
    .endif

VictoryRoad_3F_Text_ColbyIntro::
    .ifdef ENGLISH
    .string "Only the chosen can pass here!$"
    .endif
    .ifdef SPANISH
    .string "¡Aquí sólo pueden pasar\n"
    .string "los elegidos!$"
    .endif

VictoryRoad_3F_Text_ColbyDefeat::
    .ifdef ENGLISH
    .string "I don't believe it!$"
    .endif
    .ifdef SPANISH
    .string "¡No me lo puedo creer!$"
    .endif

VictoryRoad_3F_Text_ColbyPostBattle::
    .ifdef ENGLISH
    .string "All TRAINERS here are headed to\n"
    .string "the POKéMON LEAGUE.\p"
    .string "Don't let down your guard.$"
    .endif
    .ifdef SPANISH
    .string "¡Todos estos ENTRENADORES van a\n"
    .string "participar en la LIGA POKéMON!\p"
    .string "¡Ten cuidado!$"
    .endif

VictoryRoad_3F_Text_RayIntro::
    .ifdef ENGLISH
    .string "RAY: Together, the two of us are\n"
    .string "destined for greatness!$"
    .endif
    .ifdef SPANISH
    .string "DESI: ¡Juntos lucharemos contra\n"
    .string "quien sea!$"
    .endif

VictoryRoad_3F_Text_RayDefeat::
    .ifdef ENGLISH
    .string "RAY: Ludicrous!\n"
    .string "This can't be!$"
    .endif
    .ifdef SPANISH
    .string "DESI: ¡No me lo puedo creer!$"
    .endif

VictoryRoad_3F_Text_RayPostBattle::
    .ifdef ENGLISH
    .string "RAY: You've beaten us.\n"
    .string "Greatness remains elusive…$"
    .endif
    .ifdef SPANISH
    .string "DESI: ¡Has acabado con nosotros!$"
    .endif

VictoryRoad_3F_Text_RayNotEnoughMons::
    .ifdef ENGLISH
    .string "RAY: Together, the two of us are\n"
    .string "striving for the pinnacle.\p"
    .string "We need you to bring two POKéMON\n"
    .string "into battle with us.$"
    .endif
    .ifdef SPANISH
    .string "DESI: Acabaríamos contigo\n"
    .string "en un abrir y cerrar de ojos.\p"
    .string "Para luchar con nosotros, hay\n"
    .string "que tener dos POKéMON.$"
    .endif

VictoryRoad_3F_Text_TyraIntro::
    .ifdef ENGLISH
    .string "TYRA: We're trying to become\n"
    .string "champions together.$"
    .endif
    .ifdef SPANISH
    .string "TULA: ¡Tenemos intención de\n"
    .string "convertirnos en campeones!$"
    .endif

VictoryRoad_3F_Text_TyraDefeat::
    .ifdef ENGLISH
    .string "TYRA: Oh, but…$"
    .endif
    .ifdef SPANISH
    .string "TULA: Eh..., en fin...$"
    .endif

VictoryRoad_3F_Text_TyraPostBattle::
    .ifdef ENGLISH
    .string "TYRA: You've taught me that power\n"
    .string "can be infinite in shape and form.$"
    .endif
    .ifdef SPANISH
    .string "TULA: De ti he aprendido la\n"
    .string "verdadera dimensión de la fuerza.$"
    .endif

VictoryRoad_3F_Text_TyraNotEnoughMons::
    .ifdef ENGLISH
    .string "TYRA: You can't battle with us if\n"
    .string "you have only one POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "TULA: No podrás con nosotros\n"
    .string "si no tienes dos POKéMON.$"
    .endif

