Text_DoubleEdgeTeach::
    .string "Has conseguido abrirte paso por\n"
    .string "la CALLE VICTORIA con mucho\l"
    .string "valor; es para alegrarse.\p"
    .string "Como reconocimiento a tu hazaña,\n"
    .string "te enseñaré DOBLE FILO.\p"
    .string "¿Quieres?$"

Text_DoubleEdgeDeclined::
    .string "Bueno, otra vez será.$"

Text_DoubleEdgeWhichMon::
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe DOBLE FILO?$"

Text_DoubleEdgeTaught::
    .string "¡No bajes la guardia para la LIGA\n"
    .string "POKéMON!\p"
    .string "¡A por ella, acaba con todos!$"

VictoryRoad_3F_Text_GeorgeIntro::
    .string "¡Los rumores hablan de un\n"
    .string "ENTRENADOR espectacular!$"

VictoryRoad_3F_Text_GeorgeDefeat::
    .string "¡Los rumores eran ciertos!$"

VictoryRoad_3F_Text_GeorgePostBattle::
    .string "¿Derrotaste a GIOVANNI\n"
    .string "del TEAM ROCKET?$"

VictoryRoad_3F_Text_AlexaIntro::
    .string "¡Los ENTRENADORES sólo viven para\n"
    .string "buscar enemigos más fuertes!$"

VictoryRoad_3F_Text_AlexaDefeat::
    .string "¡Oooooh!\n"
    .string "¡Eres tan fuerte!$"

VictoryRoad_3F_Text_AlexaPostBattle::
    .string "¡Librar duros combates te hará\n"
    .string "más fuerte!$"

VictoryRoad_3F_Text_CarolineIntro::
    .string "¡Te demostraré lo fuerte que eres\n"
    .string "de verdad!$"

VictoryRoad_3F_Text_CarolineDefeat::
    .string "¡Argh! ¡Eres increíble!$"

VictoryRoad_3F_Text_CarolinePostBattle::
    .string "¡Yo soy la que ha aprendido\n"
    .string "la lección!$"

VictoryRoad_3F_Text_ColbyIntro::
    .string "¡Aquí sólo pueden pasar\n"
    .string "los elegidos!$"

VictoryRoad_3F_Text_ColbyDefeat::
    .string "¡No me lo puedo creer!$"

VictoryRoad_3F_Text_ColbyPostBattle::
    .string "¡Todos estos ENTRENADORES van a\n"
    .string "participar en la LIGA POKéMON!\p"
    .string "¡Ten cuidado!$"

VictoryRoad_3F_Text_RayIntro::
    .string "DESI: ¡Juntos lucharemos contra\n"
    .string "quien sea!$"

VictoryRoad_3F_Text_RayDefeat::
    .string "DESI: ¡No me lo puedo creer!$"

VictoryRoad_3F_Text_RayPostBattle::
    .string "DESI: ¡Has acabado con nosotros!$"

VictoryRoad_3F_Text_RayNotEnoughMons::
    .string "DESI: Acabaríamos contigo\n"
    .string "en un abrir y cerrar de ojos.\p"
    .string "Para luchar con nosotros, hay\n"
    .string "que tener dos POKéMON.$"

VictoryRoad_3F_Text_TyraIntro::
    .string "TULA: ¡Tenemos intención de\n"
    .string "convertirnos en campeones!$"

VictoryRoad_3F_Text_TyraDefeat::
    .string "TULA: Eh..., en fin...$"

VictoryRoad_3F_Text_TyraPostBattle::
    .string "TULA: De ti he aprendido la\n"
    .string "verdadera dimensión de la fuerza.$"

VictoryRoad_3F_Text_TyraNotEnoughMons::
    .string "TULA: No podrás con nosotros\n"
    .string "si no tienes dos POKéMON.$"
