Text_DoubleEdgeTeach::
	.string "Je suis impressionné, tu as\n"
	.string "réussi à arriver jusque-là si\l"
	.string "courageusement.\p"
	.string "Pour la peine, je veux bien\n"
	.string "t'apprendre DAMOCLES.\p"
	.string "Veux-tu que j'enseigne cette\n"
	.string "technique à un de tes POKéMON?$"

Text_DoubleEdgeDeclined::
	.string "Très bien. N'hésite pas à revenir\n"
	.string "si tu changes d'avis.$"

Text_DoubleEdgeWhichMon::
	.string "A quel POKéMON enseigner\n"
	.string "DAMOCLES?$"

Text_DoubleEdgeTaught::
	.string "Continue comme ça jusqu'à la\n"
	.string "LIGUE POKéMON!\p"
	.string "Je sais que tu peux tous les\n"
	.string "battre facilement.$"

VictoryRoad_3F_Text_GeorgeIntro::
	.string "J'ai entendu parler de quelqu'un\n"
	.string "de très doué!$"

VictoryRoad_3F_Text_GeorgeDefeat::
	.string "…\n"
	.string "C'était vrai!$"

VictoryRoad_3F_Text_GeorgePostBattle::
	.string "Alors c'était vrai?\p"
	.string "Tu as bien battu GIOVANNI de la\n"
	.string "TEAM ROCKET?$"

VictoryRoad_3F_Text_AlexaIntro::
	.string "Un DRESSEUR est toujours en quête\n"
	.string "d'adversaires plus puissants!$"

VictoryRoad_3F_Text_AlexaDefeat::
	.string "Oh!\n"
	.string "Tu plaisantes pas toi!$"

VictoryRoad_3F_Text_AlexaPostBattle::
	.string "Il faut se battre souvent pour\n"
	.string "progresser.$"

VictoryRoad_3F_Text_CarolineIntro::
	.string "Je vais te montrer ma puissance!$"

VictoryRoad_3F_Text_CarolineDefeat::
	.string "Non!\n"
	.string "Je suis furieuse!$"

VictoryRoad_3F_Text_CarolinePostBattle::
	.string "Ben, j'suis pas si forte que ça!$"

VictoryRoad_3F_Text_ColbyIntro::
	.string "Seuls les élus peuvent passer!$"

VictoryRoad_3F_Text_ColbyDefeat::
	.string "Oh!\n"
	.string "J'y crois pas!$"

VictoryRoad_3F_Text_ColbyPostBattle::
	.string "Ces DRESSEURS sont de la\n"
	.string "LIGUE POKéMON!\p"
	.string "Fais attention!$"

VictoryRoad_3F_Text_RayIntro::
	.string "ROMEO: Nous sommes destinés\n"
	.string "à de grandes choses.$"

VictoryRoad_3F_Text_RayDefeat::
	.string "ROMEO: Ridicule!\n"
	.string "C'est pas possible.$"

VictoryRoad_3F_Text_RayPostBattle::
	.string "ROMEO: Tu nous a battus.\n"
	.string "J'étais pourtant sûr de moi.$"

VictoryRoad_3F_Text_RayNotEnoughMons::
	.string "ROMEO: Tous les deux, nous\n"
	.string "atteindrons les sommets.\p"
	.string "Mais tu dois avoir un deuxième\n"
	.string "POKéMON pour te battre avec nous.$"

VictoryRoad_3F_Text_TyraIntro::
	.string "TYRA: Nous allons devenir champions\n"
	.string "ensemble.$"

VictoryRoad_3F_Text_TyraDefeat::
	.string "TYRA: Oh, mais…$"

VictoryRoad_3F_Text_TyraPostBattle::
	.string "TYRA: Grâce à toi, j'ai enfin\n"
	.string "compris que la puissance seule\l"
	.string "ne suffit pas.$"

VictoryRoad_3F_Text_TyraNotEnoughMons::
	.string "TYRA: Tu ne peux pas te battre\n"
	.string "contre nous avec un seul POKéMON.$"

