FiveIsland_Text_IslandSign::
    .ifdef ENGLISH
    .string "FIVE ISLAND\n"
    .string "Chrono Island: Where Time Goes$"
    .endif
    .ifdef SPANISH
    .string "ISLA INTA\n"
    .string "Isla que marca el paso del tiempo.$"
    .endif

FiveIsland_Text_WeirdBuildingInMeadow::
    .ifdef ENGLISH
    .string "Oh, this stinks. I wanted to play in\n"
    .string "the MEADOW.\p"
    .string "But they put up a weird building\n"
    .string "on it, so I can't play there.$"
    .endif
    .ifdef SPANISH
    .string "Uf, qué rollo, yo quería jugar\n"
    .string "en el PRADO...\p"
    .string "Pero han puesto un raro edificio\n"
    .string "en medio y ya no hay dónde jugar.$"
    .endif

FiveIsland_Text_BeenGettingBusierAroundHere::
    .ifdef ENGLISH
    .string "It's been getting busier around\n"
    .string "these parts lately.\p"
    .string "I haven't been catching many good\n"
    .string "fish lately, either.$"
    .endif
    .ifdef SPANISH
    .string "Últimamente ha habido mucho\n"
    .string "movimiento por aquí...\p"
    .string "Y la pesca no ha sido buena...\n"
    .string "Mmmm...$"
    .endif

