FiveIsland_Text_IslandSign::
    .string "ISLA INTA\n"
    .string "Isla que marca el paso del tiempo.$"

FiveIsland_Text_WeirdBuildingInMeadow::
    .string "Uf, qué rollo, yo quería jugar\n"
    .string "en el PRADO...\p"
    .string "Pero han puesto un raro edificio\n"
    .string "en medio y ya no hay dónde jugar.$"

FiveIsland_Text_BeenGettingBusierAroundHere::
    .string "Últimamente ha habido mucho\n"
    .string "movimiento por aquí...\p"
    .string "Y la pesca no ha sido buena...\n"
    .string "Mmmm...$"
