SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles::
	.string "Je sais que c'est dur à croire,\n"
	.string "mais quand j'étais plus jeune,\p"
	.string "j'adorais être sur les routes pour\n"
	.string "affronter tous les DRESSEURS\p"
	.string "que je pouvais rencontrer.\p"
	.string "Maintenant, ma seule source de\n"
	.string "distraction est de me rappeler\p"
	.string "du passé en regardant des\n"
	.string "combats.$"

SevenIsland_House_Room1_Text_SlightBreezeAroundBox::
	.string "Il y a un courant d'air derrière\n"
	.string "les cartons.$"

SevenIsland_House_Room1_Text_ChallengeVisitingTrainer::
	.string "Bienvenue!\p"
	.string "Je vais t'avouer une chose, il\n"
	.string "y a une salle cachée dans la cave.\p"
	.string "Un DRESSEUR appelé {STR_VAR_1}\n"
	.string "t'y attend en ce moment.\p"
	.string "Tu es là pour l'affronter,\n"
	.string "n'est-ce pas?$"

SevenIsland_House_Room1_Text_OhYouWontBattle::
	.string "Oh…\n"
	.string "Tu ne veux pas te battre?\p"
	.string "Je vois, je vois.\n"
	.string "…\p"
	.string "Bon, si jamais tu changes d'avis.$"

SevenIsland_House_Room1_Text_LimitThreeMonsPerSide::
	.string "Ah! Tu veux bien te battre alors!\p"
	.string "Donc ça valait le coup que je\n"
	.string "déplace tous ces cartons.\p"
	.string "… …\n"
	.string "Mais il y a juste un problème.\p"
	.string "La salle n'est pas très solide,\n"
	.string "tu sais.\p"
	.string "Je peux te demander de ne\n"
	.string "prendre que trois POKéMON\p"
	.string "avec toi pour pas tout casser?$"

SevenIsland_House_Room1_Text_SaveProgressBeforeBattle::
	.string "Bien! Veux-tu sauvegarder avant\n"
	.string "de combattre?$"

SevenIsland_House_Room1_Text_DontHoldAnythingBack::
	.string "Parfait.\n"
	.string "Bon courage.$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_1::
	.string "{STR_VAR_1}$"

SevenIsland_House_Room2_Text_MatchEndedUpDraw::
	.string "Il y a égalité.$"

SevenIsland_House_Room1_Text_DrawWasIt::
	.string "Match nul, hein?\p"
	.string "Mais laisse-moi te dire que\n"
	.string "le match était époustouflant.\p"
	.string "Je dirais que c'était un combat\n"
	.string "d'une grande profondeur!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_2::
	.string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_AstoundingBattle::
	.string "Bravo!\n"
	.string "Toutes mes félicitations!\p"
	.string "J'en ai les larmes aux yeux!\p"
	.string "Je n'avais encore jamais vu\n"
	.string "quelqu'un maîtriser ainsi toutes\p"
	.string "ces capacités!\n"
	.string "Un vrai combat de titans!\p"
	.string "Pfiu, laisse-moi un moment\n"
	.string "pour m'en remettre.$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_3::
	.string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_FeelYourDisappointment::
	.string "Quel dommage!\n"
	.string "Je comprends ta déception.\p"
	.string "Mais c'est dans la défaite qu'on\n"
	.string "devient un vrai DRESSEUR.\p"
	.string "Sers-toi de ce combat comme\n"
	.string "d'une leçon, et tu verras,\p"
	.string "tu t'en souviendras plus tard\n"
	.string "comme d'un bon souvenir.$"

