SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles::
    .ifdef ENGLISH
    .string "I may not look like much now,\n"
    .string "but when I was younger…\p"
    .string "I flew everywhere, challenging\n"
    .string "TRAINERS wherever I found them.\p"
    .string "Now, my only source of enjoyment\n"
    .string "is reminiscing about the past while\l"
    .string "watching battles.$"
    .endif
    .ifdef SPANISH
    .string "Ahora no lo aparento, pero cuando\n"
    .string "era más joven...\p"
    .string "Iba volando de aquí para allá,\n"
    .string "desafiando a los ENTRENADORES\l"
    .string "con los que me encontraba.\p"
    .string "Ahora, me conformo recordando\n"
    .string "viejos tiempos y viendo combates.$"
    .endif

SevenIsland_House_Room1_Text_SlightBreezeAroundBox::
    .ifdef ENGLISH
    .string "There is a slight breeze blowing\n"
    .string "around the box.$"
    .endif
    .ifdef SPANISH
    .string "Alrededor de la caja hay\n"
    .string "corriente...$"
    .endif

SevenIsland_House_Room1_Text_ChallengeVisitingTrainer::
    .ifdef ENGLISH
    .string "Ah!\n"
    .string "Welcome, my friend!\p"
    .string "Let me tell you something. There's\n"
    .string "a hidden room in the basement.\p"
    .string "A TRAINER named {STR_VAR_1} is\n"
    .string "waiting there now.\p"
    .string "Tell me, you did come to challenge\n"
    .string "{STR_VAR_1}, am I right?$"
    .endif
    .ifdef SPANISH
    .string "¡Hola!\n"
    .string "¿Qué tal?\p"
    .string "¿Sabes una cosa? En el sótano\n"
    .string "hay una sala secreta.\p"
    .string "Y te está esperando {STR_VAR_1}.\p"
    .string "Tú querías luchar con {STR_VAR_1},\n"
    .string "¿no?$"
    .endif

SevenIsland_House_Room1_Text_OhYouWontBattle::
    .ifdef ENGLISH
    .string "Oh…\n"
    .string "You won't battle…\p"
    .string "I see, I see.\n"
    .string "… …\p"
    .string "Well, perhaps if you change your\n"
    .string "mind, do come back.$"
    .endif
    .ifdef SPANISH
    .string "Oh...\n"
    .string "No vas a luchar...\p"
    .string "Vale, vale...\p"
    .string "Bueno, vuelve si cambias\n"
    .string "de opinión.$"
    .endif

SevenIsland_House_Room1_Text_LimitThreeMonsPerSide::
    .ifdef ENGLISH
    .string "Ah!\n"
    .string "You will battle for me?\p"
    .string "It was worth my time moving the\n"
    .string "box aside, then.\p"
    .string "… …\n"
    .string "But there is one slight problem.\p"
    .string "This hidden room is not built very\n"
    .string "sturdy.\p"
    .string "Can I get you to limit it to\n"
    .string "battles of three POKéMON per side?$"
    .endif
    .ifdef SPANISH
    .string "¡Hola!\n"
    .string "¿Vas a luchar por mí?\p"
    .string "Entonces ha merecido la pena\n"
    .string "mover la caja.\p"
    .string "Pero... hay un pequeño\n"
    .string "problema.\p"
    .string "La construcción de esta sala\n"
    .string "deja un poco que desear.\p"
    .string "¿Te parece que sólo participen\n"
    .string "tres POKéMON por cada lado?$"
    .endif

SevenIsland_House_Room1_Text_SaveProgressBeforeBattle::
    .ifdef ENGLISH
    .string "Fine! Before your battle, would\n"
    .string "you like to save your game?$"
    .endif
    .ifdef SPANISH
    .string "¡Bien! ¿Quieres guardar la partida\n"
    .string "antes de luchar?$"
    .endif

SevenIsland_House_Room1_Text_DontHoldAnythingBack::
    .ifdef ENGLISH
    .string "All right.\n"
    .string "Don't hold anything back!$"
    .endif
    .ifdef SPANISH
    .string "¡Muy bien!\n"
    .string "¡Pues a por todas!$"
    .endif

@ Unused
SevenIsland_House_Room1_Text_StrVar1_1::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room2_Text_MatchEndedUpDraw::
    .ifdef ENGLISH
    .string "The match ended up a draw.$"
    .endif
    .ifdef SPANISH
    .string "El combate ha acabado en empate.$"
    .endif

SevenIsland_House_Room1_Text_DrawWasIt::
    .ifdef ENGLISH
    .string "A draw, was it?\p"
    .string "However, let me say that it was\n"
    .string "a worthy spectacle.\p"
    .string "I'd say it was a wonderful battle\n"
    .string "with a real sense of depth!$"
    .endif
    .ifdef SPANISH
    .string "¿Habéis empatado?\p"
    .string "Con todo, ha sido un espectáculo\n"
    .string "apasionante.\p"
    .string "¿Qué digo?\n"
    .string "¡Apasionante y con mucha miga!$"
    .endif

@ Unused
SevenIsland_House_Room1_Text_StrVar1_2::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_AstoundingBattle::
    .ifdef ENGLISH
    .string "Bravo!\p"
    .string "Bravo, indeed!\n"
    .string "What an astounding battle!\p"
    .string "It was so astounding, why, it keeps\n"
    .string "filling my eyes with tears!\p"
    .string "The thrust and parry of expertly\n"
    .string "used techniques!\p"
    .string "The clash of power upon power!\p"
    .string "Yes!\n"
    .string "It was sheer magnificence!$"
    .endif
    .ifdef SPANISH
    .string "¡Bravo!\p"
    .string "¡Bravo, bravísimo!\n"
    .string "¡Qué combate, señores!\p"
    .string "¡Me he emocionado y todo!\p"
    .string "¡Qué manera de usar las técnicas,\n"
    .string "con qué seguridad y destreza!\p"
    .string "¡Qué pulso!\n"
    .string "¡Fuerza contra fuerza!\p"
    .string "¡Sí, señor!\n"
    .string "¡Magnífico, colosal, apoteósico!$"
    .endif

@ Unused
SevenIsland_House_Room1_Text_StrVar1_3::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_FeelYourDisappointment::
    .ifdef ENGLISH
    .string "Too bad!\n"
    .string "I feel your disappointment.\p"
    .string "However, that disappointment is\n"
    .string "what will make you better.\p"
    .string "Use it, learn from it, and make it\n"
    .string "motivate you to seek greatness.\p"
    .string "Forget not this disappointment\n"
    .string "and redouble your training!$"
    .endif
    .ifdef SPANISH
    .string "Vaya...\n"
    .string "Sé que estás triste...\p"
    .string "Pero no te desanimes, esa tristeza\n"
    .string "te hará más fuerte.\p"
    .string "Úsala, aprende de ella, ¡apóyate\n"
    .string "en ella para seguir adelante!\p"
    .string "¡No te olvides de esta derrota\n"
    .string "y entrénate el doble!$"
    .endif

