MtMoon_B2F_Text_MiguelIntro::
	.string "Hep! Toi là!\p"
	.string "Ces fossiles sont à moi!\n"
	.string "Pas touche!$"

MtMoon_B2F_Text_MiguelDefeat::
	.string "Bon, OK!\n"
	.string "On partage!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
	.string "Chacun le sien!\n"
	.string "Comme ça, pas de jaloux!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
	.string "OK, je prends celui-ci!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
	.string "Loin d'ici, sur CRAMOIS'ILE, se\n"
	.string "trouve un LABO POKéMON.\p"
	.string "On essaye d'y régénérer des\n"
	.string "fossiles de POKéMON.$"

MtMoon_B2F_Text_Grunt1Intro::
	.string "La TEAM ROCKET trouvera les \n"
	.string "fossiles et fera fortune en les \l"
	.string "vendant!$"

MtMoon_B2F_Text_Grunt1Defeat::
	.string "Grrr!\n"
	.string "J'suis vert!$"

MtMoon_B2F_Text_Grunt1PostBattle::
	.string "A cause de toi, j'suis vert!\n"
	.string "La TEAM ROCKET me vengera!$"

MtMoon_B2F_Text_Grunt2Intro::
	.string "La TEAM ROCKET?\n"
	.string "C'est nous!\l"
	.string "Les voleurs de POKéMON!$"

MtMoon_B2F_Text_Grunt2Defeat::
	.string "NOOOONNN!\n"
	.string "J'ai perdu!$"

MtMoon_B2F_Text_Grunt2PostBattle::
	.string "Hein?\n"
	.string "Mes compagnons vont me venger!$"

MtMoon_B2F_Text_Grunt3Intro::
	.string "Ça bosse dur ici!\n"
	.string "Alors du balai!$"

MtMoon_B2F_Text_Grunt3Defeat::
	.string "OK, j'ai perdu…$"

MtMoon_B2F_Text_Grunt3PostBattle::
	.string "Si tu trouves un fossile, tu me le\n"
	.string "donnes et tu décampes, pigé?$"

MtMoon_B2F_Text_Grunt4Intro::
	.string "Les p'tits gamins ne s'occupent pas\n"
	.string "des affaires des grands!$"

MtMoon_B2F_Text_Grunt4Defeat::
	.string "…\n"
	.string "J'suis épuisé!$"

MtMoon_B2F_Text_Grunt4PostBattle::
	.string "Les POKéMON existaient bien avant\n"
	.string "les Hommes…$"

MtMoon_B2F_Text_YouWantDomeFossil::
	.string "Tu veux le fossile DOME?$"

MtMoon_B2F_Text_YouWantHelixFossil::
	.string "Tu veux le fossile NAUTILE?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
	.string "Fossile NAUTILE obtenu!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
	.string "Fossile DOME obtenu!$"

