MtMoon_B2F_Text_MiguelIntro::
	.string "Stopp! Hände weg!\p"
	.string "Wer zuerst kommt, mahlt zuerst!\n"
	.string "Die Fossilien gehören MIR!$"

MtMoon_B2F_Text_MiguelDefeat::
	.string "Na gut!\n"
	.string "Ich gebe dir eines ab!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
	.string "Heh, nicht so gierig!\n"
	.string "Ich sagte, ich gebe dir EINES ab!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
	.string "O.K., dann gehört das hier mir!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
	.string "Auf der fernen ZINNOBERINSEL\n"
	.string "gibt es ein POKéMON-LABOR.\p"
	.string "Dort versucht man, aus fossilem\n"
	.string "Gen-Material POKéMON zu\l"
	.string "erschaffen.$"

MtMoon_B2F_Text_Grunt1Intro::
	.string "Wir vom TEAM ROCKET werden die\n"
	.string "Fossilien finden, die POKéMON wie-\l"
	.string "der beleben und teuer verkaufen!$"

MtMoon_B2F_Text_Grunt1Defeat::
	.string "Grr!\n"
	.string "Das gibt es nicht!$"

MtMoon_B2F_Text_Grunt1PostBattle::
	.string "Du machst mich irre! Das TEAM\n"
	.string "ROCKET wird dich im Auge behalten!$"

MtMoon_B2F_Text_Grunt2Intro::
	.string "Wir sind das TEAM ROCKET, die\n"
	.string "POKéMON-Räuber!$"

MtMoon_B2F_Text_Grunt2Defeat::
	.string "NEIN!\n"
	.string "Ich hab es vermasselt!$"

MtMoon_B2F_Text_Grunt2PostBattle::
	.string "Verdammt! Wie erkläre ich das\n"
	.string "meinen Partnern?$"

MtMoon_B2F_Text_Grunt3Intro::
	.string "Wir drehen hier ein dickes Ding!\n"
	.string "Mach dich vom Acker!$"

MtMoon_B2F_Text_Grunt3Defeat::
	.string "Du bist 'ne harte Nuss, Kiddie!$"

MtMoon_B2F_Text_Grunt3PostBattle::
	.string "Wenn du ein Fossil hast, gib es her\n"
	.string "und verschwinde!$"

MtMoon_B2F_Text_Grunt4Intro::
	.string "Geh Erwachsenen nicht auf den\n"
	.string "Wecker, du Nervensäge!$"

MtMoon_B2F_Text_Grunt4Defeat::
	.string "Ich bin sauer!$"

MtMoon_B2F_Text_Grunt4PostBattle::
	.string "Schon lange vor den Menschen\n"
	.string "haben POKéMON hier gelebt...$"

MtMoon_B2F_Text_YouWantDomeFossil::
	.string "Möchtest du das DOMFOSSIL?$"

MtMoon_B2F_Text_YouWantHelixFossil::
	.string "Möchtest du das HELIXFOSSIL?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
	.string "HELIXFOSSIL erhalten!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
	.string "DOMFOSSIL erhalten!$"

