FiveIsland_LostCave_Room1_Text_LawsonIntro::
    .ifdef ENGLISH
    .string "Aiyeeeeeh!\p"
    .string "I thought this was an ancient ruin.\n"
    .string "But it's teeming with ghosts!$"
    .endif
    .ifdef SPANISH
    .string "¡Ay, mamaíta, qué miedo!\p"
    .string "Yo pensaba que en estas ruinas tan\n"
    .string "antiguas no había nada de nada,\l"
    .string "¡pero creo que hay fantasmas!$"
    .endif

FiveIsland_LostCave_Room1_Text_LawsonDefeat::
    .ifdef ENGLISH
    .string "Aiyeeeeeh!\n"
    .string "Mercy!$"
    .endif
    .ifdef SPANISH
    .string "¡Aaaaaah!\n"
    .string "¡Estoy temblando de miedo!$"
    .endif

FiveIsland_LostCave_Room1_Text_LawsonPostBattle::
    .ifdef ENGLISH
    .string "I'm trying to get out of here, but\n"
    .string "I always end up at the same spot.\p"
    .string "Maybe the number of boulders is\n"
    .string "a hint…$"
    .endif
    .ifdef SPANISH
    .string "Estoy intentando salir de aquí,\n"
    .string "pero siempre llego al mismo sitio.\p"
    .string "Yo creo que el número de piedras\n"
    .string "que hay, quiere decir algo...$"
    .endif

