FiveIsland_LostCave_Room1_Text_LawsonIntro::
	.string "Aaaaah!\p"
	.string "Je croyais que c'étaient des ruines\n"
	.string "anciennes sans danger.\p"
	.string "Mais ça grouille de fantômes!$"

FiveIsland_LostCave_Room1_Text_LawsonDefeat::
	.string "Aaaaïlle!\n"
	.string "Pitiéééé!!$"

FiveIsland_LostCave_Room1_Text_LawsonPostBattle::
	.string "J'essaie de sortir d'ici, mais je me\n"
	.string "retrouve toujours au même endroit.\p"
	.string "Peut-être que le nombre de rochers\n"
	.string "est un indice…$"

