TwoIsland_JoyfulGameCorner_Text_WhereHasLostelleGottenTo::
    .string "¿Dónde se habrá metido PEDRITA\n"
    .string "hoy?\p"
    .string "Siempre me trae la comida\n"
    .string "a tiempo, pero hoy...$"

TwoIsland_JoyfulGameCorner_Text_PleaseHelpFindLostelle::
    .string "¡Oye, sí, tú!\n"
    .string "¿Conoces a PEDRITA?\p"
    .string "¿La has visto por algún sitio?\n"
    .string "No tengo ni idea de dónde se habrá\l"
    .string "metido, pero tarda un montón.\p"
    .string "Es una monada de niña, espero\n"
    .string "que no le haya pasado nada...\p"
    .string "¡Como le haya pasado algo a mi\n"
    .string "PEDRITA!\p"
    .string "¡Por favor, ayúdame a buscarla!\n"
    .string "¿Irías a ISLA TERA a ver si está?$"

TwoIsland_JoyfulGameCorner_Text_IsThisOnlyThreeIsland::
    .string "¿Y éstos son los RECREATIVOS?\n"
    .string "¡POR FAVOR!\p"
    .string "Qué birria...\p"
    .string "¿No se supone que hemos quedado\n"
    .string "aquí? ¿Dónde está la gente?\p"
    .string "¡Eh, tú! ¿Hay otra ISLA TERA\n"
    .string "por ahí o es ésta la única?$"

TwoIsland_JoyfulGameCorner_Text_ThisIsTwoIslandMoveIt::
    .string "¡Vaya empanada mental que tienes,\n"
    .string "chaval!\p"
    .string "¡Esto es ISLA SECUNDA!\p"
    .string "¡Anda, pon en marcha la moto\n"
    .string "y tira!$"

TwoIsland_JoyfulGameCorner_Text_TheseIslandsAreConfusing::
    .string "Eh...\n"
    .string "Ah, vale.\p"
    .string "Eh...\n"
    .string "¡Me he liado con tanta isla!$"

TwoIsland_JoyfulGameCorner_Text_PunkScuffedUpMyFloor::
    .string "¿Será posible?\n"
    .string "¡El gamberro ese me ha rayado\l"
    .string "el suelo!$"

TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland::
    .string "Por favor, tienes que ir a ISLA\n"
    .string "TERA.\p"
    .string "Si le pasara algo a mi PEDRITA...\p"
    .string "Mi casa está en ISLA TERA, es la\n"
    .string "del tejado rojo.\p"
    .string "Yo no quiero moverme de aquí,\n"
    .string "no vaya a ser que aparezca en\l"
    .string "algún momento.\p"
    .string "Por eso te pido que me ayudes.$"

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday::
    .string "Lo siento.\n"
    .string "En este momento no se puede jugar\l"
    .string "a nada.$"

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon::
    .string "Vuelve dentro de un tiempo.$"

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle::
    .string "¡¿Has rescatado a PEDRITA?!\n"
    .string "¡No sabes cómo te lo agradezco!\p"
    .string "¡PEDRITA, cielo, perdóname!\p"
    .string "¡Papá no sabía que estuvieras\n"
    .string "asustada y no te atrevieras\l"
    .string "a volver!$"

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy::
    .string "PEDRITA: No asa nada, api.\n"
    .string "{PLAYER}, es amigui.$"

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe::
    .string "¿Cómo?\n"
    .string "¿Que es para mí?\p"
    .string "¿Y cómo sabes que me gustan\n"
    .string "las rocas raras y las gemas?\p"
    .string "Desde luego, has dado en el clavo.$"

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy::
    .string "{PLAYER} le entregó el METEORITO\n"
    .string "al papá de PEDRITA.$"

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill::
    .string "¡Ah, que lo envía BILL!\n"
    .string "¡Dale las gracias de mi parte!\p"
    .string "No tengo palabras para agradecerte\n"
    .string "todo lo que has hecho.\l"
    .string "Me gustaría darte esto.$"

TwoIsland_JoyfulGameCorner_Text_ReceivedMoonStoneFromLostellesDaddy::
    .string "¡{PLAYER} obtuvo una PIEDRA LUNAR\n"
    .string "de manos del papá de PEDRITA!$"

TwoIsland_JoyfulGameCorner_Text_NotGoingToFitInBag::
    .string "En la MOCHILA no cabe nada\n"
    .string "más...$"

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning::
    .string "Bueno, ya podemos poner en marcha\n"
    .string "los RECREATIVOS.\p"
    .string "Vente con algún amigo para jugar\n"
    .string "a algo.$"

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool::
    .string "¡Eh, eh!\p"
    .string "¡Ede guay, tú hace aggo guay!$"
