TwoIsland_JoyfulGameCorner_Text_WhereHasLostelleGottenTo::
    .ifdef ENGLISH
    .string "Now, where's LOSTELLE gotten to\n"
    .string "today?\p"
    .string "She always brings me lunch every\n"
    .string "day right about now…$"
    .endif
    .ifdef SPANISH
    .string "¿Dónde se habrá metido PEDRITA\n"
    .string "hoy?\p"
    .string "Siempre me trae la comida\n"
    .string "a tiempo, pero hoy...$"
    .endif

TwoIsland_JoyfulGameCorner_Text_PleaseHelpFindLostelle::
    .ifdef ENGLISH
    .string "Hm? You, there!\n"
    .string "Are you a friend of LOSTELLE's?\p"
    .string "Have you seen LOSTELLE around?\n"
    .string "I don't know where she might be.\l"
    .string "She should've been here long ago.\p"
    .string "LOSTELLE's a cutie - she got my\n"
    .string "looks - so what if someone…\p"
    .string "What if something's happened to\n"
    .string "my LOSTELLE?!\p"
    .string "Please, help me find her!\n"
    .string "Please go search THREE ISLAND!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye, sí, tú!\n"
    .string "¿Conoces a PEDRITA?\p"
    .string "¿La has visto por algún sitio?\n"
    .string "No tengo ni idea de dónde se habrá\l"
    .string "metido, pero tarda un montón.\p"
    .string "Es una monada de niña, espero\n"
    .string "que no le haya pasado nada...\p"
    .string "¡Como le haya pasado algo a mi\n"
    .string "PEDRITA!\p"
    .string "¡Por favor, ayúdame a buscarla!\n"
    .string "¿Irías a ISLA TERA a ver si está?$"
    .endif

TwoIsland_JoyfulGameCorner_Text_IsThisOnlyThreeIsland::
    .ifdef ENGLISH
    .string "Hah? What is this GAME CORNER?\n"
    .string "How much sadder can this get?\p"
    .string "Those clowns…\p"
    .string "They said they'd be waiting on the\n"
    .string "island, so where are they?\p"
    .string "Hey, you! Is this the only THREE\n"
    .string "ISLAND around here?$"
    .endif
    .ifdef SPANISH
    .string "¿Y éstos son los RECREATIVOS?\n"
    .string "¡POR FAVOR!\p"
    .string "Qué birria...\p"
    .string "¿No se supone que hemos quedado\n"
    .string "aquí? ¿Dónde está la gente?\p"
    .string "¡Eh, tú! ¿Hay otra ISLA TERA\n"
    .string "por ahí o es ésta la única?$"
    .endif

TwoIsland_JoyfulGameCorner_Text_ThisIsTwoIslandMoveIt::
    .ifdef ENGLISH
    .string "Try waking up before you crawl out\n"
    .string "of bed, you punk.\p"
    .string "This is TWO ISLAND!\p"
    .string "Move it! Get your filthy motorbike\n"
    .string "out of my place!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya empanada mental que tienes,\n"
    .string "chaval!\p"
    .string "¡Esto es ISLA SECUNDA!\p"
    .string "¡Anda, pon en marcha la moto\n"
    .string "y tira!$"
    .endif

TwoIsland_JoyfulGameCorner_Text_TheseIslandsAreConfusing::
    .ifdef ENGLISH
    .string "Huh…\n"
    .string "Oh, oh, gotcha.\p"
    .string "Tch…\n"
    .string "These islands are confusing…$"
    .endif
    .ifdef SPANISH
    .string "Eh...\n"
    .string "Ah, vale.\p"
    .string "Eh...\n"
    .string "¡Me he liado con tanta isla!$"
    .endif

TwoIsland_JoyfulGameCorner_Text_PunkScuffedUpMyFloor::
    .ifdef ENGLISH
    .string "Would you look at that?\n"
    .string "That punk scuffed up my floor.$"
    .endif
    .ifdef SPANISH
    .string "¿Será posible?\n"
    .string "¡El gamberro ese me ha rayado\l"
    .string "el suelo!$"
    .endif

TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland::
    .ifdef ENGLISH
    .string "Hey, but listen! I'm begging you,\n"
    .string "you have to go to THREE ISLAND.\p"
    .string "If anything were to happen to my\n"
    .string "LOSTELLE…\p"
    .string "My place is the house with the red\n"
    .string "roof on THREE ISLAND.\p"
    .string "She may just show up late here,\n"
    .string "so I can't run off anywhere.\p"
    .string "That's why I have to get you to do\n"
    .string "me this big favor.$"
    .endif
    .ifdef SPANISH
    .string "Por favor, tienes que ir a ISLA\n"
    .string "TERA.\p"
    .string "Si le pasara algo a mi PEDRITA...\p"
    .string "Mi casa está en ISLA TERA, es la\n"
    .string "del tejado rojo.\p"
    .string "Yo no quiero moverme de aquí,\n"
    .string "no vaya a ser que aparezca en\l"
    .string "algún momento.\p"
    .string "Por eso te pido que me ayudes.$"
    .endif

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday::
    .ifdef ENGLISH
    .string "I'm sorry.\n"
    .string "We're not running any games today.$"
    .endif
    .ifdef SPANISH
    .string "Lo siento.\n"
    .string "En este momento no se puede jugar\l"
    .string "a nada.$"
    .endif

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon::
    .ifdef ENGLISH
    .string "We'll get the games going soon\n"
    .string "for you!$"
    .endif
    .ifdef SPANISH
    .string "Vuelve dentro de un tiempo.$"
    .endif

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle::
    .ifdef ENGLISH
    .string "So you rescued LOSTELLE?\n"
    .string "How can I thank you?\p"
    .string "LOSTELLE, darling, forgive me!\p"
    .string "Daddy didn't know you were scared\n"
    .string "and in trouble!$"
    .endif
    .ifdef SPANISH
    .string "¡¿Has rescatado a PEDRITA?!\n"
    .string "¡No sabes cómo te lo agradezco!\p"
    .string "¡PEDRITA, cielo, perdóname!\p"
    .string "¡Papá no sabía que estuvieras\n"
    .string "asustada y no te atrevieras\l"
    .string "a volver!$"
    .endif

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy::
    .ifdef ENGLISH
    .string "LOSTELLE: It's okay, Daddy.\n"
    .string "I got to be friends with {PLAYER}!$"
    .endif
    .ifdef SPANISH
    .string "PEDRITA: No asa nada, api.\n"
    .string "{PLAYER}, es amigui.$"
    .endif

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe::
    .ifdef ENGLISH
    .string "Oh, what's that?\n"
    .string "You're saying that this is for me?\p"
    .string "How did you know that I love rare\n"
    .string "rocks and gems?\p"
    .string "You sure know how to make a guy\n"
    .string "happy.$"
    .endif
    .ifdef SPANISH
    .string "¿Cómo?\n"
    .string "¿Que es para mí?\p"
    .string "¿Y cómo sabes que me gustan\n"
    .string "las rocas raras y las gemas?\p"
    .string "Desde luego, has dado en el clavo.$"
    .endif

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy::
    .ifdef ENGLISH
    .string "{PLAYER} handed the METEORITE\n"
    .string "to LOSTELLE's daddy.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} le entregó el METEORITO\n"
    .string "al papá de PEDRITA.$"
    .endif

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill::
    .ifdef ENGLISH
    .string "Oh, I see, this is from BILL!\n"
    .string "You have to thank him for me!\p"
    .string "You know, you've been fantastic.\n"
    .string "I want you to have this.$"
    .endif
    .ifdef SPANISH
    .string "¡Ah, que lo envía BILL!\n"
    .string "¡Dale las gracias de mi parte!\p"
    .string "No tengo palabras para agradecerte\n"
    .string "todo lo que has hecho.\l"
    .string "Me gustaría darte esto.$"
    .endif

TwoIsland_JoyfulGameCorner_Text_ReceivedMoonStoneFromLostellesDaddy::
    .ifdef ENGLISH
    .string "{PLAYER} received a MOON STONE\n"
    .string "from LOSTELLE's daddy.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo una PIEDRA LUNAR\n"
    .string "de manos del papá de PEDRITA!$"
    .endif

TwoIsland_JoyfulGameCorner_Text_NotGoingToFitInBag::
    .ifdef ENGLISH
    .string "Your BAG's not going to fit another\n"
    .string "thing…$"
    .endif
    .ifdef SPANISH
    .string "En la MOCHILA no cabe nada\n"
    .string "más...$"
    .endif

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning::
    .ifdef ENGLISH
    .string "All right, I'll get the GAME CORNER\n"
    .string "running right away.\p"
    .string "You have to come visit with a\n"
    .string "friend.$"
    .endif
    .ifdef SPANISH
    .string "Bueno, ya podemos poner en marcha\n"
    .string "los RECREATIVOS.\p"
    .string "Vente con algún amigo para jugar\n"
    .string "a algo.$"
    .endif

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool::
    .ifdef ENGLISH
    .string "Listen, listen!\p"
    .string "Please show me you being cool\n"
    .string "again!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, eh!\p"
    .string "¡Ede guay, tú hace aggo guay!$"
    .endif

