Route22_Text_EarlyRivalIntro::
    .ifdef ENGLISH
	.string "{RIVAL}: Hey! {PLAYER}!\p"
	.string "You're off to the POKéMON LEAGUE?\n"
	.string "Forget about it!\p"
	.string "You probably don't have any\n"
	.string "BADGES, do you?\p"
	.string "The guard won't let you through\n"
	.string "without them.\p"
	.string "By the way, did your POKéMON get\n"
	.string "any stronger?$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Eh! ¡{PLAYER}!\p"
    .string "¿Vas a la LIGA POKéMON?\p"
    .string "¡Olvídalo! ¡Seguro que no tienes\n"
    .string "ninguna MEDALLA!\p"
    .string "¡El guardia no te dejará pasar!\p"
    .string "Dime, ¿ya son más fuertes tus\n"
    .string "POKéMON?$"
    .endif

Route22_Text_EarlyRivalDefeat::
    .ifdef ENGLISH
	.string "Awww!\n"
	.string "You just lucked out!$"
    .endif
    .ifdef SPANISH
    .string "¡Auuu!\n"
    .string "¡Has tenido mucha suerte!$"
    .endif

Route22_Text_EarlyRivalPostBattle::
    .ifdef ENGLISH
	.string "I heard the POKéMON LEAGUE is\n"
	.string "crawling with tough TRAINERS.\p"
	.string "I have to figure out how to get\n"
	.string "past them.\p"
	.string "You should quit dawdling and get a\n"
	.string "move on!$"
    .endif
    .ifdef SPANISH
    .string "¡Dicen que los ENTRENADORES de la\n"
    .string "LIGA POKéMON son muy fuertes!\p"
    .string "¡Tengo que buscar una forma de\n"
    .string "vencerles!\p"
    .string "¡Deja de perder el tiempo y\n"
    .string "muévete!$"
    .endif

@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}“なんだ？\n"
	.string "ポケモン　2ひきも\l"
	.string "もってるの　なぜか　だって？\p"
	.string "おまえも\n"
	.string "つかまえれば　いい　じゃん！$"

Route22_Text_LateRivalIntro::
    .ifdef ENGLISH
	.string "{RIVAL}: What? {PLAYER}!\n"
	.string "What a surprise to see you here!\p"
	.string "So you're going to the POKéMON\n"
	.string "LEAGUE?\p"
	.string "You collected all the BADGES, too?\n"
	.string "That's cool!\p"
	.string "Then I'll whip you, {PLAYER}, as a\n"
	.string "warm-up for the POKéMON LEAGUE!\p"
	.string "Come on!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¿Qué? ¡{PLAYER}!\n"
    .string "¡Qué sorpresa verte aquí!\p"
    .string "¿Vas a ir a la LIGA POKéMON?\p"
    .string "¿Y tienes todas las MEDALLAS?\n"
    .string "¡Genial!\p"
    .string "¡Lucharé contra ti, {PLAYER}, como\n"
    .string "preparación para la LIGA POKéMON!\p"
    .string "¡Vamos allá!$"
    .endif

Route22_Text_LateRivalDefeat::
    .ifdef ENGLISH
	.string "What!?\p"
	.string "I was just careless, you!$"
    .endif
    .ifdef SPANISH
    .string "¿¡Qué!?\p"
    .string "¡Es que no he tenido cuidado!$"
    .endif

Route22_Text_LateRivalPostBattle::
    .ifdef ENGLISH
	.string "That loosened me up.\n"
	.string "I'm ready for the POKéMON LEAGUE!\p"
	.string "{PLAYER}, you need more practice.\p"
	.string "But hey, you know that!\n"
	.string "I'm out of here. Smell ya!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué buen calentamiento!\n"
    .string "¡Listo para la LIGA POKéMON!\p"
    .string "¡{PLAYER}, necesitas más práctica!\p"
    .string "¡Ya lo sabes! ¡Yo me largo!\n"
    .string "¡Hasta luego!$"
    .endif

@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory::
	.string "{RIVAL}“ひゃははッ　{PLAYER}ー！\n"
	.string "それで　がんばってるのかよ！\l"
	.string "おれの　さいのうに　くらべりゃ\l"
	.string "{PLAYER}は　まだまだ　だな！\p"
	.string "もっと　れんしゅう　こいよ！\n"
	.string "あははーッ！$"

Route22_Text_LeagueGateSign::
    .ifdef ENGLISH
	.string "POKéMON LEAGUE\n"
	.string "Front Gate$"
    .endif
    .ifdef SPANISH
    .string "LIGA POKéMON\n"
    .string "Puerta delantera$"
    .endif

