OneIsland_TreasureBeach_Text_AmaraIntro::
    .ifdef ENGLISH
    .string "Lying back, rocked by the waves…\n"
    .string "It's exquisite.$"
    .endif
    .ifdef SPANISH
    .string "¡Me encanta quedarme flotando\n"
    .string "y notar el movimiento de las olas!$"
    .endif

OneIsland_TreasureBeach_Text_AmaraDefeat::
    .ifdef ENGLISH
    .string "I lost…\n"
    .string "It feels awful.$"
    .endif
    .ifdef SPANISH
    .string "¡He perdido!\n"
    .string "¡Eso ya no me gusta nada!$"
    .endif

OneIsland_TreasureBeach_Text_AmaraPostBattle::
    .ifdef ENGLISH
    .string "The sea is pleasantly warm in these\n"
    .string "parts.$"
    .endif
    .ifdef SPANISH
    .string "El mar tiene una temperatura\n"
    .string "increíble en esta zona.$"
    .endif

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
    .ifdef ENGLISH
    .string "Good things get washed up by the\n"
    .string "ocean current onto this beach.\p"
    .string "That's why I often come here for\n"
    .string "some beachcombing.$"
    .endif
    .ifdef SPANISH
    .string "Muchas veces la marea trae objetos\n"
    .string "de gran valor a la playa.\p"
    .string "Por eso vengo con frecuencia\n"
    .string "a peinar la arena.$"
    .endif

