OneIsland_TreasureBeach_Text_AmaraIntro::
    .string "¡Me encanta quedarme flotando\n"
    .string "y notar el movimiento de las olas!$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
    .string "¡He perdido!\n"
    .string "¡Eso ya no me gusta nada!$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
    .string "El mar tiene una temperatura\n"
    .string "increíble en esta zona.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
    .string "Muchas veces la marea trae objetos\n"
    .string "de gran valor a la playa.\p"
    .string "Por eso vengo con frecuencia\n"
    .string "a peinar la arena.$"
