SilphCo_11F_Text_ThanksForSavingMeDearBoy::
	.string "PRESIDENT: Merci d'avoir sauvé\n"
	.string "la SYLPHE, mon garçon!\p"
	.string "Je n'oublierai jamais\n"
	.string "cet exploit!\p"
	.string "Tu mérites une récompense!\p"
	.string "L'argent n'est pas un problème\n"
	.string "pour moi!\p"
	.string "Tiens… Je crois que ceci\n"
	.string "te fera plaisir!$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
	.string "PRESIDENT: Merci d'avoir sauvé\n"
	.string "la SYLPHE, jeune fille!\p"
	.string "Je n'oublierai jamais\n"
	.string "cet exploit!\p"
	.string "Tu mérites une récompense!\p"
	.string "L'argent n'est pas un problème\n"
	.string "pour moi!\p"
	.string "Tiens… Je crois que ceci\n"
	.string "te fera plaisir!$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
	.string "{PLAYER} obtient une MASTER BALL\n"
	.string "du PRESIDENT!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
	.string "PRESIDENT: Tu ne peux en acheter\n"
	.string "nulle part!\p"
	.string "C'est notre prototype secret:\n"
	.string "la MASTER BALL!\p"
	.string "Elle peut attraper n'importe\n"
	.string "quel POKéMON!\p"
	.string "Alors utilise-la avec sagesse.$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
	.string "Tu n'as pas assez de place sur toi.$"

SilphCo_11F_Text_ThanksForRescuingUs::
	.string "SECRETAIRE: Merci de nous avoir\n"
	.string "tous sauvés!\p"
	.string "Ton courage est exemplaire.$"

SilphCo_11F_Text_GiovanniIntro::
	.string "Ah, {PLAYER}!\n"
	.string "Une fois encore, nos routes se\l"
	.string "croisent…\p"
	.string "Le PRESIDENT et moi discutons\n"
	.string "d'une affaire très importante.\p"
	.string "Viens pas te mêler de tout ça…\p"
	.string "Ou prépare-toi à souffrir!$"

SilphCo_11F_Text_GiovanniDefeat::
	.string "Arrgh!!\n"
	.string "Encore perdu!?$"

SilphCo_11F_Text_GiovanniPostBattle::
	.string "NOoOoOoOon!\p"
	.string "Notre invasion de la SYLPHE est\n"
	.string "fichue!\p"
	.string "Mais la TEAM ROCKET est\n"
	.string "invincible!\p"
	.string "{PLAYER}! N'oublie jamais que tous\n"
	.string "les POKéMON sont pour la TEAM\l"
	.string "ROCKET!\p"
	.string "Je pars, mais…\n"
	.string "Je reviendrai bientôt.$"

SilphCo_11F_Text_Grunt2Intro::
	.string "Holà toi!\n"
	.string "On bouge pas!$"

SilphCo_11F_Text_Grunt2Defeat::
	.string "Non…\n"
	.string "Pitié!$"

SilphCo_11F_Text_Grunt2PostBattle::
	.string "Tu cherches mon chef?\n"
	.string "Tu tiens à avoir des problèmes?$"

SilphCo_11F_Text_Grunt1Intro::
	.string "Halte! As-tu un rendez-vous en\n"
	.string "règle avec mon chef?$"

SilphCo_11F_Text_Grunt1Defeat::
	.string "Gaah!\n"
	.string "J'me suis fait démolir!$"

SilphCo_11F_Text_Grunt1PostBattle::
	.string "Prends garde…\p"
	.string "Les POKéMON de mon chef sont\n"
	.string "terribles!$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
	.string "Des POKéMON sur le moniteur!$"

SilphCo_11F_Text_FloorSign::
	.string "SYLPHE SARL.\n"
	.string "10ème étage.$"

