SilphCo_11F_Text_ThanksForSavingMeDearBoy::
    .string "PRESIDENTE: ¡Gracias por salvar\n"
    .string "a SILPH!\p"
    .string "¡Jamás olvidaré que nos salvaste\n"
    .string "en este peligroso momento!\p"
    .string "¡Me gustaría agradecértelo\n"
    .string "de alguna forma!\p"
    .string "¡Yo puedo darte muchas cosas!\p"
    .string "¡Toma, puede que te interese!$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
    .string "PRESIDENTE: ¡Gracias por salvar\n"
    .string "a SILPH!\p"
    .string "¡Jamás olvidaré que nos salvaste\n"
    .string "en este peligroso momento!\p"
    .string "¡Me gustaría agradecértelo\n"
    .string "de alguna forma!\p"
    .string "¡Yo puedo darte muchas cosas!\p"
    .string "¡Toma, puede que te interese!$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
    .string "¡{PLAYER} recibió una MASTER\n"
    .string "BALL del PRESIDENTE!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
    .string "PRESIDENTE: ¡No puedes comprarla\n"
    .string "en ningún sitio!\p"
    .string "¡Es nuestro prototipo secreto\n"
    .string "de la MASTER BALL!\p"
    .string "¡Puede atrapar a cualquier tipo\n"
    .string "de POKéMON!\p"
    .string "Pero mejor que no se lo digas\n"
    .string "a nadie.$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
    .string "No tienes sitio para esto.$"

SilphCo_11F_Text_ThanksForRescuingUs::
    .string "SECRETARIA: ¡Gracias por\n"
    .string "salvarnos!\p"
    .string "Todos los que trabajamos para el\n"
    .string "PRESIDENTE admiramos tu valor.$"

SilphCo_11F_Text_GiovanniIntro::
    .string "¡Hola, {PLAYER}!\n"
    .string "¡Volvemos a encontrarnos!\p"
    .string "¡El PRESIDENTE y yo estamos\n"
    .string "hablando de algo muy importante!\p"
    .string "¡No te metas en los asuntos\n"
    .string "de los mayores!\p"
    .string "¡O sufrirás mi ira!$"

SilphCo_11F_Text_GiovanniDefeat::
    .string "¡¡Arr!!\n"
    .string "¿¡He vuelto a perder!?$"

SilphCo_11F_Text_GiovanniPostBattle::
    .string "¡Qué mal! ¡Arruinaste nuestros\n"
    .string "planes con respecto a SILPH!\p"
    .string "¡Pero el TEAM ROCKET no caerá\n"
    .string "jamás!\p"
    .string "¡{PLAYER}, no olvides jamás que\n"
    .string "todos los POKéMON son para\l"
    .string "el TEAM ROCKET!\p"
    .string "¡Ahora debo irme, pero volveré!$"

SilphCo_11F_Text_Grunt2Intro::
    .string "¡Alto ahí!\n"
    .string "¡No te muevas!$"

SilphCo_11F_Text_Grunt2Defeat::
    .string "No...\n"
    .string "¡Por favor!$"

SilphCo_11F_Text_Grunt2PostBattle::
    .string "¿¡Qué!?\n"
    .string "¿Quieres ver a mi JEFE?$"

SilphCo_11F_Text_Grunt1Intro::
    .string "¡Alto!\n"
    .string "¿Tienes una cita con mi JEFE?$"

SilphCo_11F_Text_Grunt1Defeat::
    .string "¡Auch!\n"
    .string "¡Me han derribado!$"

SilphCo_11F_Text_Grunt1PostBattle::
    .string "Ten cuidado, ¡Los POKéMON\n"
    .string "de mi JEFE son terribles!$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
    .string "¡Hay un POKéMON en el monitor!$"

SilphCo_11F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P10$"
