SilphCo_11F_Text_ThanksForSavingMeDearBoy::
    .ifdef ENGLISH
    .string "PRESIDENT: Oh, dear boy!\n"
    .string "Thank you for saving SILPH.\p"
    .string "I will never forget you saved us in\n"
    .string "our moment of peril.\p"
    .string "I have to thank you in some way.\p"
    .string "Because I am rich, I can give you\n"
    .string "anything.\p"
    .string "Here, maybe this will do.$"
    .endif
    .ifdef SPANISH
    .string "PRESIDENTE: ¡Gracias por salvar\n"
    .string "a SILPH!\p"
    .string "¡Jamás olvidaré que nos salvaste\n"
    .string "en este peligroso momento!\p"
    .string "¡Me gustaría agradecértelo\n"
    .string "de alguna forma!\p"
    .string "¡Yo puedo darte muchas cosas!\p"
    .string "¡Toma, puede que te interese!$"
    .endif

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
    .ifdef ENGLISH
    .string "PRESIDENT: Oh, dear girl!\n"
    .string "Thank you for saving SILPH.\p"
    .string "I will never forget you saved us in\n"
    .string "our moment of peril.\p"
    .string "I have to thank you in some way.\p"
    .string "Because I am rich, I can give you\n"
    .string "anything.\p"
    .string "Here, maybe this will do.$"
    .endif
    .ifdef SPANISH
    .string "PRESIDENTE: ¡Gracias por salvar\n"
    .string "a SILPH!\p"
    .string "¡Jamás olvidaré que nos salvaste\n"
    .string "en este peligroso momento!\p"
    .string "¡Me gustaría agradecértelo\n"
    .string "de alguna forma!\p"
    .string "¡Yo puedo darte muchas cosas!\p"
    .string "¡Toma, puede que te interese!$"
    .endif

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
    .ifdef ENGLISH
    .string "{PLAYER} obtained a MASTER BALL\n"
    .string "from the PRESIDENT!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió una MASTER\n"
    .string "BALL del PRESIDENTE!$"
    .endif

SilphCo_11F_Text_ThatsOurSecretPrototype::
    .ifdef ENGLISH
    .string "PRESIDENT: You can't buy that\n"
    .string "anywhere.\p"
    .string "It's our secret prototype MASTER\n"
    .string "BALL.\p"
    .string "It will catch any POKéMON without\n"
    .string "fail!\p"
    .string "You should be quiet about using it,\n"
    .string "though.$"
    .endif
    .ifdef SPANISH
    .string "PRESIDENTE: ¡No puedes comprarla\n"
    .string "en ningún sitio!\p"
    .string "¡Es nuestro prototipo secreto\n"
    .string "de la MASTER BALL!\p"
    .string "¡Puede atrapar a cualquier tipo\n"
    .string "de POKéMON!\p"
    .string "Pero mejor que no se lo digas\n"
    .string "a nadie.$"
    .endif

SilphCo_11F_Text_YouHaveNoRoomForThis::
    .ifdef ENGLISH
    .string "You have no room for this.$"
    .endif
    .ifdef SPANISH
    .string "No tienes sitio para esto.$"
    .endif

SilphCo_11F_Text_ThanksForRescuingUs::
    .ifdef ENGLISH
    .string "SECRETARY: Thank you for rescuing\n"
    .string "all of us.\p"
    .string "We, from the PRESIDENT down,\n"
    .string "are indebted to you.$"
    .endif
    .ifdef SPANISH
    .string "SECRETARIA: ¡Gracias por\n"
    .string "salvarnos!\p"
    .string "Todos los que trabajamos para el\n"
    .string "PRESIDENTE admiramos tu valor.$"
    .endif

SilphCo_11F_Text_GiovanniIntro::
    .ifdef ENGLISH
    .string "Ah, {PLAYER}!\n"
    .string "So we meet again!\p"
    .string "The PRESIDENT and I are discussing\n"
    .string "a vital business proposition.\p"
    .string "Keep your nose out of grown-up\n"
    .string "matters…\p"
    .string "Or, experience a world of pain!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, {PLAYER}!\n"
    .string "¡Volvemos a encontrarnos!\p"
    .string "¡El PRESIDENTE y yo estamos\n"
    .string "hablando de algo muy importante!\p"
    .string "¡No te metas en los asuntos\n"
    .string "de los mayores!\p"
    .string "¡O sufrirás mi ira!$"
    .endif

SilphCo_11F_Text_GiovanniDefeat::
    .ifdef ENGLISH
    .string "Arrgh!!\n"
    .string "I lost again!?$"
    .endif
    .ifdef SPANISH
    .string "¡¡Arr!!\n"
    .string "¿¡He vuelto a perder!?$"
    .endif

SilphCo_11F_Text_GiovanniPostBattle::
    .ifdef ENGLISH
    .string "Blast it all!\n"
    .string "You ruined our plans for SILPH!\p"
    .string "But, TEAM ROCKET will never fall!\p"
    .string "{PLAYER}! Never forget that all\n"
    .string "POKéMON exist for TEAM ROCKET!\p"
    .string "I must go, but I shall return!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué mal! ¡Arruinaste nuestros\n"
    .string "planes con respecto a SILPH!\p"
    .string "¡Pero el TEAM ROCKET no caerá\n"
    .string "jamás!\p"
    .string "¡{PLAYER}, no olvides jamás que\n"
    .string "todos los POKéMON son para\l"
    .string "el TEAM ROCKET!\p"
    .string "¡Ahora debo irme, pero volveré!$"
    .endif

SilphCo_11F_Text_Grunt2Intro::
    .ifdef ENGLISH
    .string "Stop right there!\n"
    .string "Don't you move!$"
    .endif
    .ifdef SPANISH
    .string "¡Alto ahí!\n"
    .string "¡No te muevas!$"
    .endif

SilphCo_11F_Text_Grunt2Defeat::
    .ifdef ENGLISH
    .string "Don't…\n"
    .string "Please!$"
    .endif
    .ifdef SPANISH
    .string "No...\n"
    .string "¡Por favor!$"
    .endif

SilphCo_11F_Text_Grunt2PostBattle::
    .ifdef ENGLISH
    .string "So, you want to see my BOSS?$"
    .endif
    .ifdef SPANISH
    .string "¿¡Qué!?\n"
    .string "¿Quieres ver a mi JEFE?$"
    .endif

SilphCo_11F_Text_Grunt1Intro::
    .ifdef ENGLISH
    .string "Halt! Do you have an appointment\n"
    .string "with my BOSS?$"
    .endif
    .ifdef SPANISH
    .string "¡Alto!\n"
    .string "¿Tienes una cita con mi JEFE?$"
    .endif

SilphCo_11F_Text_Grunt1Defeat::
    .ifdef ENGLISH
    .string "Gaah!\n"
    .string "Demolished!$"
    .endif
    .ifdef SPANISH
    .string "¡Auch!\n"
    .string "¡Me han derribado!$"
    .endif

SilphCo_11F_Text_Grunt1PostBattle::
    .ifdef ENGLISH
    .string "Watch your step…\n"
    .string "My BOSS likes his POKéMON tough!$"
    .endif
    .ifdef SPANISH
    .string "Ten cuidado, ¡Los POKéMON\n"
    .string "de mi JEFE son terribles!$"
    .endif

SilphCo_11F_Text_MonitorHasMonsOnIt::
    .ifdef ENGLISH
    .string "The monitor has POKéMON on it!$"
    .endif
    .ifdef SPANISH
    .string "¡Hay un POKéMON en el monitor!$"
    .endif

SilphCo_11F_Text_FloorSign::
    .ifdef ENGLISH
    .string "SILPH CO. HEAD OFFICE\n"
    .string "11F$"
    .endif
    .ifdef SPANISH
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P10$"
    .endif

