PokemonMansion_Text_PressSecretSwitch::
    .ifdef ENGLISH
    .string "A secret switch!\p"
    .string "Press it?$"
    .endif
    .ifdef SPANISH
    .string "Un botón secreto.\p"
    .string "¿Lo pulso?$"
    .endif

PokemonMansion_Text_WhoWouldnt::
    .ifdef ENGLISH
    .string "Who wouldn't?$"
    .endif
    .ifdef SPANISH
    .string "¿Y quién no lo haría?$"
    .endif

PokemonMansion_Text_NotQuiteYet::
    .ifdef ENGLISH
    .string "Not quite yet!$"
    .endif
    .ifdef SPANISH
    .string "¡Todavía no!$"
    .endif

PokemonMansion_1F_Text_ArnieIntro::
    .ifdef ENGLISH
    .string "I can't get out!\n"
    .string "This old place is one big puzzle.$"
    .endif
    .ifdef SPANISH
    .string "¡No sé salir! ¡Este viejo lugar\n"
    .string "es un enorme laberinto!$"
    .endif

PokemonMansion_1F_Text_ArnieDefeat::
    .ifdef ENGLISH
    .string "Oh, no!\n"
    .string "My bag of loot!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh, no!\n"
    .string "¡Mi botín!$"
    .endif

PokemonMansion_1F_Text_ArniePostBattle::
    .ifdef ENGLISH
    .string "The switches here open and close\n"
    .string "alternating sets of doors.$"
    .endif
    .ifdef SPANISH
    .string "¡Los botones abren y cierran\n"
    .string "alternativamente los grupos\l"
    .string "de puertas!$"
    .endif

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle::
    .ifdef ENGLISH
    .string "Diary: July 5\n"
    .string "Guyana, South America\p"
    .string "A new POKéMON was discovered deep\n"
    .string "in the jungle.$"
    .endif
    .ifdef SPANISH
    .string "Diario: 5 de julio.\n"
    .string "Guyana, Suramérica.\p"
    .string "Un nuevo tipo de POKéMON fue\n"
    .string "descubierto en el interior de la\l"
    .string "selva.$"
    .endif

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
    .ifdef ENGLISH
    .string "Diary: July 10\n"
    .string "We christened the newly discovered\l"
    .string "POKéMON, MEW.$"
    .endif
    .ifdef SPANISH
    .string "Diario: 10 de julio.\n"
    .string "Hemos llamado a este nuevo\l"
    .string "POKéMON, MEW.$"
    .endif

