PokemonMansion_Text_PressSecretSwitch::
	.string "Un bouton secret!\p"
	.string "Appuyer dessus?$"

PokemonMansion_Text_WhoWouldnt::
	.string "Qui ne le ferait pas?$"

PokemonMansion_Text_NotQuiteYet::
	.string "Pas vraiment!$"

PokemonMansion_1F_Text_ArnieIntro::
	.string "Mais…\n"
	.string "J'suis complètement paumé!$"

PokemonMansion_1F_Text_ArnieDefeat::
	.string "Non!\n"
	.string "Mon butin!$"

PokemonMansion_1F_Text_ArniePostBattle::
	.string "Les interrupteurs ouvrent et\n"
	.string "ferment alternativement les portes!$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle::
	.string "Rapport: 5 Juillet.\n"
	.string "Jungle X.\p"
	.string "Un nouveau type de POKéMON\n"
	.string "a été découvert.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
	.string "Rapport: 10 Juillet.\n"
	.string "Le POKéMON a été baptisé MEW.$"

