CinnabarIsland_Gym_Text_BlaineIntro::
	.string "Haha!\p"
	.string "Ich bin PYRO, der\n"
	.string "ARENALEITER der\l"
	.string "ZINNOBERINSEL!\p"
	.string "Meine FEUER-\n"
	.string "POKéMON lassen\l"
	.string "die Siegesträume\l"
	.string "meiner Gegner in\l"
	.string "Flammen aufgehen!\p"
	.string "Du solltest FEUERHEILER\n"
	.string "parat halten!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

CinnabarIsland_Gym_Text_BlaineDefeat::
	.string "Mein Feuer ist erloschen!\p"
	.string "Du hast dir den VULKANORDEN\n"
	.string "redlich verdient.$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
	.string "FEUERSTURM ist die mächtigste\n"
	.string "Feuerattacke!\p"
	.string "Allerdings ist sie gegen WASSER-\n"
	.string "POKéMON machtlos!$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
	.string "Haha!\p"
	.string "Der VULKANORDEN steigert die\n"
	.string "SPEZIAL-FÄHIGKEITEN deiner\l"
	.string "POKéMON!\p"
	.string "Nimm zusätzlich dieses Geschenk!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
	.string "{PLAYER} erhält\n"
	.string "TM38!$"

CinnabarIsland_Gym_Text_BlainePostBattle::
	.string "TM38 ist FEUERSTURM!\p"
	.string "FEUER-POKéMON können diese Attacke\n"
	.string "erlernen!\p"
	.string "GLUTEXO und VULPIX sind dafür\n"
	.string "prädestiniert!$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
	.string "Schaffe Platz für mein Geschenk!$"

CinnabarIsland_Gym_Text_ErikIntro::
	.string "Was glaubst du, wie heiß der\n"
	.string "Feueratem eines POKéMON werden\l"
	.string "kann?$"

CinnabarIsland_Gym_Text_ErikDefeat::
	.string "Autsch!\n"
	.string "Heiß, sehr heiß!$"

CinnabarIsland_Gym_Text_ErikPostBattle::
	.string "Feuer, oder präziser, die\n"
	.string "Verbrennung...\p"
	.string "Bla, bla, bla, bla...$"

CinnabarIsland_Gym_Text_QuinnIntro::
	.string "Ich war ein Dieb! Doch nun bin ich\n"
	.string "ein ehrenhafter TRAINER!$"

CinnabarIsland_Gym_Text_QuinnDefeat::
	.string "Ich ergebe mich!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
	.string "Ich kann nicht aufhören, anderen\n"
	.string "Leuten POKéMON zu stehlen!$"

CinnabarIsland_Gym_Text_AveryIntro::
	.string "Du hast keine Chance!\n"
	.string "Ich bin POKéMON-Profi!$"

CinnabarIsland_Gym_Text_AveryDefeat::
	.string "Nein!\n"
	.string "Das war unprofessionell!$"

CinnabarIsland_Gym_Text_AveryPostBattle::
	.string "Du kannst meine Arbeitsweise nicht\n"
	.string "verstehen!$"

CinnabarIsland_Gym_Text_RamonIntro::
	.string "Ich setze mit Vorliebe FEUER-\n"
	.string "POKéMON ein!$"

CinnabarIsland_Gym_Text_RamonDefeat::
	.string "Du bist brandgefährlich!$"

CinnabarIsland_Gym_Text_RamonPostBattle::
	.string "Ach, könnte ich doch nur deine\n"
	.string "POKéMON stehlen!$"

CinnabarIsland_Gym_Text_DerekIntro::
	.string "Ich weiß, warum PYRO ein TRAINER\n"
	.string "geworden ist!$"

CinnabarIsland_Gym_Text_DerekDefeat::
	.string "Autsch!$"

CinnabarIsland_Gym_Text_DerekPostBattle::
	.string "PYRO hatte sich als Kind in den\n"
	.string "Bergen verlaufen, als über ihm ein\l"
	.string "FEUERVOGEL erschien!\p"
	.string "Der Schein dieses POKéMON wies\n"
	.string "PYRO den Rückweg!$"

CinnabarIsland_Gym_Text_DustyIntro::
	.string "Ich war in vielen POKéMON-ARENEN,\n"
	.string "doch diese mag ich am liebsten!$"

CinnabarIsland_Gym_Text_DustyDefeat::
	.string "Autsch!\n"
	.string "Du bist zu stark!$"

CinnabarIsland_Gym_Text_DustyPostBattle::
	.string "PONITA und VULNONA sind die\n"
	.string "Lieblings-POKéMON aller Pyromanen!$"

CinnabarIsland_Gym_Text_ZacIntro::
	.string "Gegen Wasser kann Feuer nichts\n"
	.string "ausrichten!$"

CinnabarIsland_Gym_Text_ZacDefeat::
	.string "Oh!\n"
	.string "Ich habe verloren!$"

CinnabarIsland_Gym_Text_ZacPostBattle::
	.string "Wasser löscht Feuer, doch Feuer\n"
	.string "schmilzt Eis!$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
	.string "Heh!\n"
	.string "Warte, du Champion in spe!\p"
	.string "Der hitzköpfige PYRO ist ein\n"
	.string "FEUER-POKéMON-Spezialist!\p"
	.string "Du solltest sein Mütchen mit Wasser\n"
	.string "kühlen!\p"
	.string "Und besorge dir FEUERHEILER!$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
	.string "{PLAYER}! Du hast den Unruhestifter\n"
	.string "gebrandmarkt!$"

CinnabarIsland_Gym_Text_GymStatue::
	.string "ZINNOBERINSEL POKéMON-ARENA\n"
	.string "LEITUNG: PYRO\p"
	.string "BISHERIGE SIEGER:\n"
	.string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
	.string "ZINNOBERINSEL POKéMON-ARENA\n"
	.string "LEITUNG: PYRO\p"
	.string "BISHERIGE SIEGER:\n"
	.string "{RIVAL}, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
	.string "Willkommen beim POKéMON-Quiz!\p"
	.string "Weißt du die richtige Antwort, dann\n"
	.string "öffnet sich die Tür!\p"
	.string "Ist die Antwort falsch, dann musst\n"
	.string "du kämpfen...\p"
	.string "Je mehr Antworten du weißt, desto\n"
	.string "fitter sind deine POKéMON beim\l"
	.string "Kampf gegen den ARENALEITER!\p"
	.string "Lass uns beginnen!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
	.string "Entwickelt sich RAUPY zu SAFCON?$"

CinnabarIsland_Gym_Text_QuizQuestion2::
	.string "Gibt es neun offizielle POKéMON-\n"
	.string "ORDEN?$"

CinnabarIsland_Gym_Text_QuizQuestion3::
	.string "Entwickelt sich QUAPSEL dreimal?$"

CinnabarIsland_Gym_Text_QuizQuestion4::
	.string "Sind ELEKTRO-ATTACKEN gegen\n"
	.string "BODEN-POKéMON sehr effektiv?$"

CinnabarIsland_Gym_Text_QuizQuestion5::
	.string "Unterscheiden sich zwei gleiche\n"
	.string "POKéMON mit gleichem Level?$"

CinnabarIsland_Gym_Text_QuizQuestion6::
	.string "Ist TM28 die FROSCH-ATTACKE?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
	.string "Und die Antwort ist... RICHTIG!\p"
	.string "Geh weiter!$"

CinnabarIsland_Gym_Text_SorryBadCall::
	.string "FALSCH!\n"
	.string "So ein Pech!$"

