CinnabarIsland_Gym_Text_BlaineIntro::
    .ifdef ENGLISH
    .string "Hah!\p"
    .string "I am BLAINE, the red-hot LEADER\n"
    .string "of CINNABAR GYM!\p"
    .string "My fiery POKéMON are all rough\n"
    .string "and ready with intense heat!\p"
    .string "They incinerate all challengers!\p"
    .string "Hah!\n"
    .string "You better have BURN HEAL!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif
    .ifdef SPANISH
    .string "¡Ja!\p"
    .string "¡Soy BLAINE! ¡LÍDER del GIMNASIO\n"
    .string "de CANELA!\p"
    .string "¡Mis feroces POKéMON de FUEGO\n"
    .string "quemarán a quien me desafíe!\p"
    .string "¡Ja! ¡Más vale que tengas\n"
    .string "ANTIQUEMAR!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif

CinnabarIsland_Gym_Text_BlaineDefeat::
    .ifdef ENGLISH
    .string "I have burned down to nothing!\n"
    .string "Not even ashes remain!\p"
    .string "You have earned the VOLCANOBADGE.$"
    .endif
    .ifdef SPANISH
    .string "¡Me has machacado!\n"
    .string "¡He quedado reducido a nada!\p"
    .string "¡Has ganado la MEDALLA VOLCÁN!$"
    .endif

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
    .ifdef ENGLISH
    .string "FIRE BLAST is the ultimate fire\n"
    .string "technique.\p"
    .string "Don't waste it on WATER POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡LLAMARADA es lo máximo en la\n"
    .string "técnica de las quemaduras!\p"
    .string "¡No la malgastes con los POKéMON\n"
    .string "acuáticos!$"
    .endif

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
    .ifdef ENGLISH
    .string "Hah!\p"
    .string "The VOLCANOBADGE heightens the\n"
    .string "SPECIAL stats of your POKéMON.\p"
    .string "Here, you can have this, too!$"
    .endif
    .ifdef SPANISH
    .string "¡Ja!\p"
    .string "¡La MEDALLA VOLCÁN mejora las\n"
    .string "habilidades ESPECIALES de tus\l"
    .string "POKéMON!\p"
    .string "¡Mira, también te daré esto!$"
    .endif

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
    .ifdef ENGLISH
    .string "{PLAYER} received TM38\n"
    .string "from BLAINE.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió la MT38\n"
    .string "de manos de BLAINE!$"
    .endif

CinnabarIsland_Gym_Text_BlainePostBattle::
    .ifdef ENGLISH
    .string "TM38 contains FIRE BLAST.\n"
    .string "Teach it to FIRE-type POKéMON.\p"
    .string "VULPIX or CHARMELEON would be\n"
    .string "ideal for that move.$"
    .endif
    .ifdef SPANISH
    .string "¡La MT38 contiene LLAMARADA!\p"
    .string "¡Enseña este ataque a los POKéMON\n"
    .string "del tipo FUEGO!\p"
    .string "¡CHARMELEON o PONYTA serían\n"
    .string "las mejores apuestas!$"
    .endif

CinnabarIsland_Gym_Text_MakeSpaceForThis::
    .ifdef ENGLISH
    .string "Make space for this, child!$"
    .endif
    .ifdef SPANISH
    .string "¡Hazle sitio a esto, anda!$"
    .endif

CinnabarIsland_Gym_Text_ErikIntro::
    .ifdef ENGLISH
    .string "Do you know how hot POKéMON fire\n"
    .string "breath can get?$"
    .endif
    .ifdef SPANISH
    .string "¿Sabes el calor que puede dar el\n"
    .string "aliento de fuego de un POKéMON?$"
    .endif

CinnabarIsland_Gym_Text_ErikDefeat::
    .ifdef ENGLISH
    .string "Yow!\n"
    .string "Hot, hot, hot!$"
    .endif
    .ifdef SPANISH
    .string "¡Ay!\n"
    .string "¡Quema, quema!$"
    .endif

CinnabarIsland_Gym_Text_ErikPostBattle::
    .ifdef ENGLISH
    .string "Fire, or to be more precise,\n"
    .string "combustion…\p"
    .string "…Oxygen in the air…\n"
    .string "Blah, blah, blah, blah…$"
    .endif
    .ifdef SPANISH
    .string "Fuego o, para ser más preciso,\n"
    .string "combustión...\p"
    .string "¡Bla, bla, bla, bla!...$"
    .endif

CinnabarIsland_Gym_Text_QuinnIntro::
    .ifdef ENGLISH
    .string "I was a thief, but I went straight\n"
    .string "as a TRAINER.$"
    .endif
    .ifdef SPANISH
    .string "Yo era ladrón, pero me hice\n"
    .string "honrado cuando me convertí\l"
    .string "en ENTRENADOR.$"
    .endif

CinnabarIsland_Gym_Text_QuinnDefeat::
    .ifdef ENGLISH
    .string "I surrender!$"
    .endif
    .ifdef SPANISH
    .string "¡Me rindo!$"
    .endif

CinnabarIsland_Gym_Text_QuinnPostBattle::
    .ifdef ENGLISH
    .string "I get this uncontrollable urge to\n"
    .string "steal other people's POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡No puedo evitar robar los POKéMON\n"
    .string "de otras personas!$"
    .endif

CinnabarIsland_Gym_Text_AveryIntro::
    .ifdef ENGLISH
    .string "I've studied POKéMON thoroughly.\n"
    .string "You can't win!$"
    .endif
    .ifdef SPANISH
    .string "¡No puedes ganar!\n"
    .string "¡Soy un experto en POKéMON!$"
    .endif

CinnabarIsland_Gym_Text_AveryDefeat::
    .ifdef ENGLISH
    .string "Waah!\n"
    .string "My studies were insufficient!$"
    .endif
    .ifdef SPANISH
    .string "¡Au!\n"
    .string "¡Tanta teoría para nada!$"
    .endif

CinnabarIsland_Gym_Text_AveryPostBattle::
    .ifdef ENGLISH
    .string "My theories are too complicated\n"
    .string "for you to understand.$"
    .endif
    .ifdef SPANISH
    .string "¡Mis teorías son muy complicadas\n"
    .string "para ti!$"
    .endif

CinnabarIsland_Gym_Text_RamonIntro::
    .ifdef ENGLISH
    .string "I like using FIRE-type POKéMON.\n"
    .string "I just do.$"
    .endif
    .ifdef SPANISH
    .string "¡Me encanta usar POKéMON\n"
    .string "del tipo FUEGO!$"
    .endif

CinnabarIsland_Gym_Text_RamonDefeat::
    .ifdef ENGLISH
    .string "Too hot to handle!$"
    .endif
    .ifdef SPANISH
    .string "¡No hay quien pueda contigo!$"
    .endif

CinnabarIsland_Gym_Text_RamonPostBattle::
    .ifdef ENGLISH
    .string "I wish there were a thief POKéMON.\n"
    .string "I'd use that!$"
    .endif
    .ifdef SPANISH
    .string "¡Ojalá hubiera un POKéMON ladrón!\n"
    .string "¡Me encantaría utilizarlo!$"
    .endif

CinnabarIsland_Gym_Text_DerekIntro::
    .ifdef ENGLISH
    .string "I know why BLAINE became a\n"
    .string "TRAINER.$"
    .endif
    .ifdef SPANISH
    .string "¡Ya sé por qué BLAINE se hizo\n"
    .string "ENTRENADOR!$"
    .endif

CinnabarIsland_Gym_Text_DerekDefeat::
    .ifdef ENGLISH
    .string "Ow!$"
    .endif
    .ifdef SPANISH
    .string "¡Auuuuuuuuuu!$"
    .endif

CinnabarIsland_Gym_Text_DerekPostBattle::
    .ifdef ENGLISH
    .string "Our LEADER, BLAINE, became lost\n"
    .string "in the mountains but good.\p"
    .string "Night fell when a fiery bird\n"
    .string "POKéMON appeared.\p"
    .string "Its light allowed BLAINE to find\n"
    .string "his way down safely.$"
    .endif
    .ifdef SPANISH
    .string "BLAINE se perdió en la montaña,\n"
    .string "y se hizo de noche...\p"
    .string "¡Pero apareció un feroz pájaro\n"
    .string "POKéMON...!\p"
    .string "¡E iluminó el camino a BLAINE\n"
    .string "para que pudiera bajar!$"
    .endif

CinnabarIsland_Gym_Text_DustyIntro::
    .ifdef ENGLISH
    .string "I've been to many GYMS, but this\n"
    .string "one best suits my style.$"
    .endif
    .ifdef SPANISH
    .string "¡He estado en muchos GIMNASIOS,\n"
    .string "pero éste es mi preferido!$"
    .endif

CinnabarIsland_Gym_Text_DustyDefeat::
    .ifdef ENGLISH
    .string "Yowza!\n"
    .string "Too hot!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya!\n"
    .string "¡Eso quema!$"
    .endif

CinnabarIsland_Gym_Text_DustyPostBattle::
    .ifdef ENGLISH
    .string "PONYTA, NINETALES…\n"
    .string "Those are popular FIRE POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡A nosotros, los seguidores de los\n"
    .string "POKéMON de fuego, nos gustan\l"
    .string "PONYTA y NINETALES!$"
    .endif

CinnabarIsland_Gym_Text_ZacIntro::
    .ifdef ENGLISH
    .string "Fire is weak against H2O.$"
    .endif
    .ifdef SPANISH
    .string "El fuego es débil contra el H2O.$"
    .endif

CinnabarIsland_Gym_Text_ZacDefeat::
    .ifdef ENGLISH
    .string "Oh!\n"
    .string "Snuffed out!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh!\n"
    .string "¡Esto se acabó!$"
    .endif

CinnabarIsland_Gym_Text_ZacPostBattle::
    .ifdef ENGLISH
    .string "Water beats fire, of course.\p"
    .string "But fire melts ice, so the FIRE\n"
    .string "type beats ICE-type POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡El agua apaga el fuego!\p"
    .string "¡Pero el fuego derrite a los\n"
    .string "POKéMON de hielo!$"
    .endif

CinnabarIsland_Gym_Text_GymGuyAdvice::
    .ifdef ENGLISH
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "The hotheaded BLAINE is a FIRE\n"
    .string "POKéMON pro.\p"
    .string "Douse his spirits with water!\p"
    .string "You'd better take some\n"
    .string "BURN HEALS, too.$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, aspirante al título!\p"
    .string "¡BLAINE es un profesional\n"
    .string "de los POKéMON de fuego!\p"
    .string "¡Bájale los humos con agua!\p"
    .string "¡Más vale que lleves\n"
    .string "ANTIQUEMAR!$"
    .endif

CinnabarIsland_Gym_Text_GymGuyPostVictory::
    .ifdef ENGLISH
    .string "{PLAYER}!\n"
    .string "You beat that firebrand!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER}, has ganado a esa\n"
    .string "antorcha con patas!$"
    .endif

CinnabarIsland_Gym_Text_GymStatue::
    .ifdef ENGLISH
    .string "CINNABAR POKéMON GYM\n"
    .string "LEADER: BLAINE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CANELA: BLAINE\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"
    .endif

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
    .ifdef ENGLISH
    .string "CINNABAR POKéMON GYM\n"
    .string "LEADER: BLAINE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CANELA: BLAINE\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"
    .endif

CinnabarIsland_Gym_Text_PokemonQuizRules::
    .ifdef ENGLISH
    .string "POKéMON Quiz!\p"
    .string "Get it right, and the door opens to\n"
    .string "the next room.\p"
    .string "Get it wrong, and face a TRAINER!\p"
    .string "If you want to conserve your\n"
    .string "POKéMON for the GYM LEADER…\p"
    .string "Then get it right!\n"
    .string "Here we go!$"
    .endif
    .ifdef SPANISH
    .string "¡POKéACERTIJO!\p"
    .string "¡Responde bien y abrirás la puerta\n"
    .string "a la siguiente habitación!\p"
    .string "¡Responde mal y lucharás contra\n"
    .string "un ENTRENADOR!\p"
    .string "Si prefieres reservar tus POKéMON\n"
    .string "para el LÍDER del GIMNASIO...\p"
    .string "¡Hazlo bien!\n"
    .string "¡Vamos allá!$"
    .endif

CinnabarIsland_Gym_Text_QuizQuestion1::
    .ifdef ENGLISH
    .string "CATERPIE evolves into METAPOD?$"
    .endif
    .ifdef SPANISH
    .string "¿Evoluciona CATERPIE y\n"
    .string "se transforma en METAPOD?$"
    .endif

CinnabarIsland_Gym_Text_QuizQuestion2::
    .ifdef ENGLISH
    .string "There are nine certified POKéMON\n"
    .string "LEAGUE BADGES?$"
    .endif
    .ifdef SPANISH
    .string "¿Hay 9 MEDALLAS oficiales\n"
    .string "de la LIGA POKéMON?$"
    .endif

CinnabarIsland_Gym_Text_QuizQuestion3::
    .ifdef ENGLISH
    .string "POLIWAG evolves three times?$"
    .endif
    .ifdef SPANISH
    .string "¿Evoluciona POLIWAG 3 veces?$"
    .endif

CinnabarIsland_Gym_Text_QuizQuestion4::
    .ifdef ENGLISH
    .string "Are electric moves effective\n"
    .string "against GROUND-type POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¿Afectan los movimientos del tipo\n"
    .string "ELÉCTRICO a los POKéMON\l"
    .string "del tipo TIERRA?$"
    .endif

CinnabarIsland_Gym_Text_QuizQuestion5::
    .ifdef ENGLISH
    .string "POKéMON of the same kind and level\n"
    .string "are not identical?$"
    .endif
    .ifdef SPANISH
    .string "¿Son distintos los POKéMON del\n"
    .string "mismo tipo y del mismo nivel?$"
    .endif

CinnabarIsland_Gym_Text_QuizQuestion6::
    .ifdef ENGLISH
    .string "TM28 contains TOMBSTONY?$"
    .endif
    .ifdef SPANISH
    .string "¿Contiene la MT28 TUMBAPIEDRA?$"
    .endif

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
    .ifdef ENGLISH
    .string "You're absolutely correct!\p"
    .string "Go on through!$"
    .endif
    .ifdef SPANISH
    .string "¡Respuesta correcta!\p"
    .string "¡Adelante!$"
    .endif

CinnabarIsland_Gym_Text_SorryBadCall::
    .ifdef ENGLISH
    .string "Sorry!\n"
    .string "Bad call!$"
    .endif
    .ifdef SPANISH
    .string "¡Mal!\n"
    .string "¡Lo siento!$"
    .endif

