CinnabarIsland_Gym_Text_BlaineIntro::
	.string "Salutations!\p"
	.string "Mon nom est… AUGUSTE! Je suis le\n"
	.string "CHAMPION de l'ARENE de\l"
	.string "CRAMOIS'ILE!\p"
	.string "Mes POKéMON flamboyants vont te\n"
	.string "réduire en cendres!\p"
	.string "Haha! J'espère que tu as de\n"
	.string "l'ANTI-BRULE! Y va bientôt faire\l"
	.string "très chaud!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

CinnabarIsland_Gym_Text_BlaineDefeat::
	.string "Vlouff!\n"
	.string "Je me suis fait vaporiser!\p"
	.string "Tu as gagné le BADGE VOLCAN!$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
	.string "DEFLAGRATION est la technique de\n"
	.string "feu ultime!\p"
	.string "Ne la donne pas à un POKéMON EAU,\n"
	.string "ça serait du gâchis!$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
	.string "Haha!\p"
	.string "Le BADGE VOLCAN augmente le\n"
	.string "SPECIAL de tes POKéMON!\p"
	.string "Prends ça aussi!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
	.string "{PLAYER} obtient\n"
	.string "la CT38!$"

CinnabarIsland_Gym_Text_BlainePostBattle::
	.string "CT38 : DEFLAGRATION!\n"
	.string "Elle convient à un POKéMON FEU!\p"
	.string "REPTINCEL ou PONYTA sont\n"
	.string "parfaits pour cette capacité!$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
	.string "Gnaaaa!!!\n"
	.string "Ton inventaire est plein!$"

CinnabarIsland_Gym_Text_ErikIntro::
	.string "Un POKéMON FEU, c'est chaud\n"
	.string "à dresser!$"

CinnabarIsland_Gym_Text_ErikDefeat::
	.string "Yaha!\n"
	.string "Fait chaud, non?$"

CinnabarIsland_Gym_Text_ErikPostBattle::
	.string "Le feu est le résultat de\n"
	.string "la combustion…\p"
	.string "… de l'oxygène dans l'air\n"
	.string "et… bla bla bla.$"

CinnabarIsland_Gym_Text_QuinnIntro::
	.string "Avant, j'étais un voleur, pas de\n"
	.string "quoi être fier… Aujourd'hui je\l"
	.string "suis un DRESSEUR honnête!$"

CinnabarIsland_Gym_Text_QuinnDefeat::
	.string "Ah!\n"
	.string "J'ai honte, je me rends!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
	.string "Je vole, j'y peux rien. Il faut\n"
	.string "que je vole des POKéMON aux gens!$"

CinnabarIsland_Gym_Text_AveryIntro::
	.string "Les POKéMON, je maîtrise, alors\n"
	.string "toi, tu peux pas gagner!$"

CinnabarIsland_Gym_Text_AveryDefeat::
	.string "Baah! Et toutes ces heures à\n"
	.string "étudier?$"

CinnabarIsland_Gym_Text_AveryPostBattle::
	.string "J'suis un cérébral, tu peux pas\n"
	.string "comprendre!$"

CinnabarIsland_Gym_Text_RamonIntro::
	.string "Les POKéMON FEU, j'adore!\n"
	.string "Y'a rien de mieux.$"

CinnabarIsland_Gym_Text_RamonDefeat::
	.string "Trop chaud à utiliser!$"

CinnabarIsland_Gym_Text_RamonPostBattle::
	.string "Si y'avait des POKéMON voleurs,\n"
	.string "j'en aurais des tas! Moi, c'que\l"
	.string "j'aime, c'est les cambriolages!$"

CinnabarIsland_Gym_Text_DerekIntro::
	.string "Héhé! Je sais pourquoi AUGUSTE\n"
	.string "est devenu DRESSEUR!$"

CinnabarIsland_Gym_Text_DerekDefeat::
	.string "Ouch!$"

CinnabarIsland_Gym_Text_DerekPostBattle::
	.string "Tout petit, AUGUSTE aimait se\n"
	.string "promener dans les montagnes.\p"
	.string "Une nuit, il s'est retrouvé\n"
	.string "complètement perdu! Mais un\l"
	.string "POKéMON oiseau apparut…\p"
	.string "La lumière de ses ailes enflammées\n"
	.string "permit à AUGUSTE de retrouver son\p"
	.string "chemin! Depuis il adore les\n"
	.string "POKéMON FEU!$"

CinnabarIsland_Gym_Text_DustyIntro::
	.string "J'ai bourlingué dans pas mal\n"
	.string "d'ARENES mon p'tit! Mais ma\l"
	.string "préférée c'est celle-ci!$"

CinnabarIsland_Gym_Text_DustyDefeat::
	.string "Yacha!\n"
	.string "Fait très chaud!$"

CinnabarIsland_Gym_Text_DustyPostBattle::
	.string "PONYTA… FEUNARD…\p"
	.string "Ce sont des POKéMON FEU très\n"
	.string "populaires!$"

CinnabarIsland_Gym_Text_ZacIntro::
	.string "Tu sais quoi?\n"
	.string "L'eau c'est fort contre le feu!$"

CinnabarIsland_Gym_Text_ZacDefeat::
	.string "Oh!\n"
	.string "Tu l'savais!$"

CinnabarIsland_Gym_Text_ZacPostBattle::
	.string "L'eau éteint le feu!\p"
	.string "Mais le feu fond la glace!\n"
	.string "Et la glace… J'sais plus!$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
	.string "Salut!\n"
	.string "Graine de champion!\p"
	.string "AUGUSTE, le flamboyant, est un pro\n"
	.string "des POKéMON FEU!\p"
	.string "C'est le moment de jeter de l'eau\n"
	.string "sur le feu!\p"
	.string "Prends donc des ANTI-BRULE avec\n"
	.string "toi! Ça peut toujours servir!$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
	.string "{PLAYER}!\n"
	.string "Tu as battu AUGUSTE!$"

CinnabarIsland_Gym_Text_GymStatue::
	.string "ARENE POKéMON de CRAMOIS'ILE\n"
	.string "CHAMPION: AUGUSTE\p"
	.string "VAINQUEURS:\n"
	.string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
	.string "ARENE POKéMON de CRAMOIS'ILE\n"
	.string "CHAMPION: AUGUSTE\p"
	.string "VAINQUEURS:\n"
	.string "{RIVAL}, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
	.string "Quiz POKéMON!\p"
	.string "Une bonne réponse ouvrira la\n"
	.string "porte!\p"
	.string "Une erreur et tu devras affronter\n"
	.string "un DRESSEUR!\p"
	.string "Pour préserver une équipe avant\n"
	.string "d'affronter le CHAMPION…\p"
	.string "Mieux vaut éviter les erreurs!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
	.string "CHENIPAN évolue en CHRYSACIER?$"

CinnabarIsland_Gym_Text_QuizQuestion2::
	.string "Il existe 9 BADGES POKéMON?$"

CinnabarIsland_Gym_Text_QuizQuestion3::
	.string "PTITARD évolue 3 fois?$"

CinnabarIsland_Gym_Text_QuizQuestion4::
	.string "Les capacités ELECTRIK sont\n"
	.string "efficaces contre les POKéMON SOL?$"

CinnabarIsland_Gym_Text_QuizQuestion5::
	.string "Les POKéMON du même type et du\n"
	.string "même niveau sont différents?$"

CinnabarIsland_Gym_Text_QuizQuestion6::
	.string "CT28 contient FOSSE?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
	.string "Bonne réponse!\p"
	.string "En avant!$"

CinnabarIsland_Gym_Text_SorryBadCall::
	.string "Dommage!\n"
	.string "Mauvaise réponse.$"

