PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
	.string "Was!?\p"
	.string "Das TEAM ROCKET befindet sich auf\n"
	.string "dem MONDBERG? Das muss ich sofort\l"
	.string "melden!\p"
	.string "Verschwinde!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
	.string "PUMMELUFF: Puup pupuu!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
	.string "Gähn!\p"
	.string "Von PUMMELUFFs GESANG werden\n"
	.string "POKéMON ganz müde...\p"
	.string "Ich auch...\n"
	.string "Schnarch...$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
	.string "Ich möchte unbedingt ein PIKACHU\n"
	.string "und tausche mein PIEPI dafür!$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
	.string "Ich tausche POKéMON mit dem\n"
	.string "Kind dort drüben!\p"
	.string "Da ich zwei PIKACHU besaß, konnte\n"
	.string "ich eines tauschen.$"

