PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
    .ifdef ENGLISH
    .string "What!?\p"
    .string "TEAM ROCKET is at MT. MOON?\n"
    .string "Huh?\p"
    .string "I'm on the phone!\n"
    .string "Scram!$"
    .endif
    .ifdef SPANISH
    .string "¿¡Qué!?\p"
    .string "¿Que el TEAM ROCKET está en el\n"
    .string "MT. MOON?\p"
    .string "¡Estoy hablando por teléfono!\n"
    .string "¿Será posible?$"
    .endif

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
    .ifdef ENGLISH
    .string "JIGGLYPUFF: Puu pupuu!$"
    .endif
    .ifdef SPANISH
    .string "JIGGLYPUFF: ¡Puf! ¡Puuuff!$"
    .endif

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
    .ifdef ENGLISH
    .string "Yawn!\p"
    .string "When JIGGLYPUFF sings, POKéMON get\n"
    .string "drowsy…\p"
    .string "…Me, too…\n"
    .string "Snore…$"
    .endif
    .ifdef SPANISH
    .string "Aaah..., qué sueño...\p"
    .string "Cuando JIGGLYPUFF canta, los\n"
    .string "POKéMON se duermen...\p"
    .string "Y yo también...\n"
    .string "Qué sueño...$"
    .endif

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
    .ifdef ENGLISH
    .string "I really want a PIKACHU, so I'm\n"
    .string "trading my CLEFAIRY for one.$"
    .endif
    .ifdef SPANISH
    .string "¡Yo quiero un PIKACHU, así que\n"
    .string "voy a intercambiar a mi CLEFAIRY\l"
    .string "por uno!$"
    .endif

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
    .ifdef ENGLISH
    .string "I'm trading POKéMON with that kid\n"
    .string "there.\p"
    .string "I had two PIKACHU, so I figured\n"
    .string "I might as well trade one.$"
    .endif
    .ifdef SPANISH
    .string "Voy a intercambiar mi POKéMON\n"
    .string "con ese chico de ahí.\p"
    .string "Como tengo dos PIKACHU,\n"
    .string "voy a pasarle uno.$"
    .endif

