SSAnne_B1F_Room1_Text_PhillipIntro::
    .string "¡Como pierdas, caminarás\n"
    .string "por el tablón!$"

SSAnne_B1F_Room1_Text_PhillipDefeat::
    .string "¡Argh! ¡Derrotado por alguien\n"
    .string "más joven que yo!$"

SSAnne_B1F_Room1_Text_PhillipPostBattle::
    .string "A veces, algunas medusas caen\n"
    .string "dentro del barco.$"

SSAnne_B1F_Room1_Text_BarnyIntro::
    .string "¡Eh, tú!\p"
    .string "¡No sé si eres de tierra o mar, \n"
    .string "pero para y habla conmigo!\p"
    .string "¡Todos mis POKéMON vienen del mar!$"

SSAnne_B1F_Room1_Text_BarnyDefeat::
    .string "¡Vaya!\n"
    .string "¡He dejado que te escaparas!$"

SSAnne_B1F_Room1_Text_BarnyPostBattle::
    .string "¡Yo también te iba a hacer\n"
    .string "mi ayudante!$"
