ThreeIsland_House4_Text_GhostsInBerryForest::
    .ifdef ENGLISH
    .string "You must never, ever go out to\n"
    .string "the BERRY FOREST alone.\p"
    .string "Why?\n"
    .string "There are ghosts there.$"
    .endif
    .ifdef SPANISH
    .string "Que no se te ocurra ir nunca al\n"
    .string "BOSQUE BAYA sin compañía.\p"
    .string "¡Está lleno de fantasmas!$"
    .endif

ThreeIsland_House4_Text_PapaKeepsLyingToMe::
    .ifdef ENGLISH
    .string "Papa keeps lying to me, and won't\n"
    .string "let me go out and play!$"
    .endif
    .ifdef SPANISH
    .string "¡Mi padre me cuenta unas historias\n"
    .string "que no se las cree ni él!\l"
    .string "¡Y no me deja salir a jugar!$"
    .endif

