Route25_SeaCottage_Text_ImBillHelpMeOutPal::
    .string "¡Hola! Soy un POKéMON...\n"
    .string "¡No, no lo soy!\p"
    .string "¡Llámame BILL!\n"
    .string "¡Soy un auténtico POKéMANÍACO!\p"
    .string "¿No me crees?\n"
    .string "¡Hablo en serio!\p"
    .string "¡Arruiné un experimento y me\n"
    .string "mezclé con un POKéMON!\p"
    .string "¿Qué me dices?\n"
    .string "¡Ayúdame a salir!$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
    .string "¡Hola! Soy un POKéMON...\n"
    .string "¡No, no lo soy!\p"
    .string "¡Llámame BILL!\n"
    .string "¡Soy un auténtico POKéMANÍACO!\p"
    .string "¿No me crees?\n"
    .string "¡Estoy en serio!\p"
    .string "¡Arruiné un experimento y me\n"
    .string "mezclé con un POKéMON!\p"
    .string "¿Qué me dices?\n"
    .string "¡Ayúdame a salir!$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
    .string "¡Cuando esté en el TELETRANSPORTE\n"
    .string "vete a mi PC y ejecuta la\l"
    .string "Separación Celular!$"

Route25_SeaCottage_Text_NoPleaseChief::
    .string "¿¡No!?\n"
    .string "¡Debes ayudarme!\p"
    .string "¡Tengo graves problemas!\p"
    .string "¿Qué dices, jefe?\n"
    .string "¿Por favor? ¿OK?\l"
    .string "¡Muy bien!$"

Route25_SeaCottage_Text_NoPleaseBeautiful::
    .string "¿¡No!?\n"
    .string "¡Debes ayudarme!\p"
    .string "¡Tengo graves problemas!\p"
    .string "¿Qué dices, eh?\n"
    .string "¿Por favor? ¿OK?\l"
    .string "¡Muy bien!$"

Route25_SeaCottage_Text_ThanksBudTakeThis::
    .string "BILL: ¡Yuuju!\n"
    .string "¡Gracias! ¡Te debo una!\p"
    .string "Has venido a ver mi colección de\n"
    .string "POKéMON, ¿no?\p"
    .string "¡Bien hecho!\p"
    .string "Te lo agradezco...\n"
    .string "¡Toma esto como recompensa!$"

Route25_SeaCottage_Text_ThanksLadyTakeThis::
    .string "BILL: ¡Yuuju!\n"
    .string "¡Gracias! ¡Te debo una!\p"
    .string "Has venido a ver mi colección de\n"
    .string "POKéMON, ¿no?\p"
    .string "¡Bien hecho!\p"
    .string "Te lo agradezco...\n"
    .string "¡Toma esto como recompensa!$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
    .string "¡{PLAYER} obtuvo un TICKET\n"
    .string "de BARCO de manos de BILL!$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff::
    .string "Llevas demasiadas cosas.$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
    .string "El crucero S.S. ANNE, está\n"
    .string "en CIUDAD CARMÍN.\p"
    .string "¡Sus pasajeros son ENTRENADORES!\p"
    .string "Me invitaron a su fiesta, pero yo\n"
    .string "las odio.\p"
    .string "¿Por qué no vas tú en mi lugar?$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
    .string "BILL: Mira, tengo algunos POKéMON\n"
    .string "muy raros en mi PC.$"

Route25_SeaCottage_Text_TeleporterIsDisplayed::
    .string "¡En el monitor del PC aparece el\n"
    .string "TELETRANSPORTE!$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
    .string "¡{PLAYER} inició el Separador\n"
    .string "Celular del TELETRANSPORTE!$"

Route25_SeaCottage_Text_BillsFavoriteMonList::
    .string "¡Es la lista de los POKéMON\n"
    .string "favoritos de BILL!$"

Route25_SeaCottage_Text_SeeWhichMon::
    .string "¿Qué POKéMON te gustaría ver?$"
