Route25_SeaCottage_Text_ImBillHelpMeOutPal::
    .ifdef ENGLISH
    .string "Hiya! I'm a POKéMON…\n"
    .string "…No I'm not!\p"
    .string "Call me BILL!\n"
    .string "I'm a true-blue POKéMANIAC!\p"
    .string "Hey!\n"
    .string "What's with that skeptical look?\p"
    .string "I'm not joshing you, pal.\p"
    .string "I screwed up an experiment and got\n"
    .string "combined with a POKéMON!\p"
    .string "So, how about it?\n"
    .string "Help me out here!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola! Soy un POKéMON...\n"
    .string "¡No, no lo soy!\p"
    .string "¡Llámame BILL!\n"
    .string "¡Soy un auténtico POKéMANÍACO!\p"
    .string "¿No me crees?\n"
    .string "¡Hablo en serio!\p"
    .string "¡Arruiné un experimento y me\n"
    .string "mezclé con un POKéMON!\p"
    .string "¿Qué me dices?\n"
    .string "¡Ayúdame a salir!$"
    .endif

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
    .ifdef ENGLISH
    .string "Hiya! I'm a POKéMON…\n"
    .string "…No I'm not!\p"
    .string "Call me BILL!\n"
    .string "I'm a true-blue POKéMANIAC!\p"
    .string "Hey!\n"
    .string "What's with that skeptical look?\p"
    .string "I'm not joshing you, lady.\p"
    .string "I screwed up an experiment and got\n"
    .string "combined with a POKéMON!\p"
    .string "So, how about it?\n"
    .string "Help me out here!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola! Soy un POKéMON...\n"
    .string "¡No, no lo soy!\p"
    .string "¡Llámame BILL!\n"
    .string "¡Soy un auténtico POKéMANÍACO!\p"
    .string "¿No me crees?\n"
    .string "¡Estoy en serio!\p"
    .string "¡Arruiné un experimento y me\n"
    .string "mezclé con un POKéMON!\p"
    .string "¿Qué me dices?\n"
    .string "¡Ayúdame a salir!$"
    .endif

Route25_SeaCottage_Text_RunCellSeparationOnPC::
    .ifdef ENGLISH
    .string "Wait till I get inside the\n"
    .string "TELEPORTER.\p"
    .string "When I do, go to my PC and run\n"
    .string "the Cell Separation System.$"
    .endif
    .ifdef SPANISH
    .string "¡Cuando esté en el TELETRANSPORTE\n"
    .string "vete a mi PC y ejecuta la\l"
    .string "Separación Celular!$"
    .endif

Route25_SeaCottage_Text_NoPleaseChief::
    .ifdef ENGLISH
    .string "No!?\n"
    .string "Now don't be so cold!\p"
    .string "Come on, you gotta help a guy in\n"
    .string "deep, deep trouble!\p"
    .string "What do you say, chief?\n"
    .string "Please?\l"
    .string "Okay?\l"
    .string "All right!$"
    .endif
    .ifdef SPANISH
    .string "¿¡No!?\n"
    .string "¡Debes ayudarme!\p"
    .string "¡Tengo graves problemas!\p"
    .string "¿Qué dices, jefe?\n"
    .string "¿Por favor? ¿OK?\l"
    .string "¡Muy bien!$"
    .endif

Route25_SeaCottage_Text_NoPleaseBeautiful::
    .ifdef ENGLISH
    .string "No!?\n"
    .string "Now don't be so cold!\p"
    .string "Come on, you gotta help a guy in\n"
    .string "deep, deep trouble!\p"
    .string "What do you say, beautiful?\n"
    .string "Please?\l"
    .string "Okay?\l"
    .string "All right!$"
    .endif
    .ifdef SPANISH
    .string "¿¡No!?\n"
    .string "¡Debes ayudarme!\p"
    .string "¡Tengo graves problemas!\p"
    .string "¿Qué dices, eh?\n"
    .string "¿Por favor? ¿OK?\l"
    .string "¡Muy bien!$"
    .endif

Route25_SeaCottage_Text_ThanksBudTakeThis::
    .ifdef ENGLISH
    .string "BILL: Yeehah!\n"
    .string "Thanks, bud! I owe you one!\p"
    .string "So, did you come to see my\n"
    .string "POKéMON collection?\p"
    .string "You didn't?\n"
    .string "That's a bummer.\p"
    .string "I've got to thank you…\n"
    .string "Oh, here, maybe this'll do.$"
    .endif
    .ifdef SPANISH
    .string "BILL: ¡Yuuju!\n"
    .string "¡Gracias! ¡Te debo una!\p"
    .string "Has venido a ver mi colección de\n"
    .string "POKéMON, ¿no?\p"
    .string "¡Bien hecho!\p"
    .string "Te lo agradezco...\n"
    .string "¡Toma esto como recompensa!$"
    .endif

Route25_SeaCottage_Text_ThanksLadyTakeThis::
    .ifdef ENGLISH
    .string "BILL: Yeehah!\n"
    .string "Thanks, lady! I owe you one!\p"
    .string "So, did you come to see my\n"
    .string "POKéMON collection?\p"
    .string "You didn't?\n"
    .string "That's a bummer.\p"
    .string "I've got to thank you…\n"
    .string "Oh, here, maybe this'll do.$"
    .endif
    .ifdef SPANISH
    .string "BILL: ¡Yuuju!\n"
    .string "¡Gracias! ¡Te debo una!\p"
    .string "Has venido a ver mi colección de\n"
    .string "POKéMON, ¿no?\p"
    .string "¡Bien hecho!\p"
    .string "Te lo agradezco...\n"
    .string "¡Toma esto como recompensa!$"
    .endif

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
    .ifdef ENGLISH
    .string "{PLAYER} received an S.S. TICKET\n"
    .string "from BILL.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo un TICKET\n"
    .string "de BARCO de manos de BILL!$"
    .endif

Route25_SeaCottage_Text_YouveGotTooMuchStuff::
    .ifdef ENGLISH
    .string "You've got too much stuff!$"
    .endif
    .ifdef SPANISH
    .string "Llevas demasiadas cosas.$"
    .endif

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
    .ifdef ENGLISH
    .string "That cruise ship S.S. ANNE is in\n"
    .string "VERMILION CITY.\p"
    .string "I hear there are lots of TRAINERS\n"
    .string "on board, too.\p"
    .string "They invited me to their party, but\n"
    .string "I can't stand fancy do's.\p"
    .string "Why don't you go instead of me?\n"
    .string "Go on and have a good time.$"
    .endif
    .ifdef SPANISH
    .string "El crucero S.S. ANNE, está\n"
    .string "en CIUDAD CARMÍN.\p"
    .string "¡Sus pasajeros son ENTRENADORES!\p"
    .string "Me invitaron a su fiesta, pero yo\n"
    .string "las odio.\p"
    .string "¿Por qué no vas tú en mi lugar?$"
    .endif

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
    .ifdef ENGLISH
    .string "BILL: Feel like checking out some\n"
    .string "of my rare POKéMON on my PC?\p"
    .string "Go on, check out my PC.$"
    .endif
    .ifdef SPANISH
    .string "BILL: Mira, tengo algunos POKéMON\n"
    .string "muy raros en mi PC.$"
    .endif

Route25_SeaCottage_Text_TeleporterIsDisplayed::
    .ifdef ENGLISH
    .string "TELEPORTER is displayed on the PC\n"
    .string "monitor.$"
    .endif
    .ifdef SPANISH
    .string "¡En el monitor del PC aparece el\n"
    .string "TELETRANSPORTE!$"
    .endif

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
    .ifdef ENGLISH
    .string "{PLAYER} initiated the TELEPORTER's\n"
    .string "Cell Separator.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} inició el Separador\n"
    .string "Celular del TELETRANSPORTE!$"
    .endif

Route25_SeaCottage_Text_BillsFavoriteMonList::
    .ifdef ENGLISH
    .string "BILL's favorite POKéMON list!$"
    .endif
    .ifdef SPANISH
    .string "¡Es la lista de los POKéMON\n"
    .string "favoritos de BILL!$"
    .endif

Route25_SeaCottage_Text_SeeWhichMon::
    .ifdef ENGLISH
    .string "Which POKéMON do you want to see?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué POKéMON te gustaría ver?$"
    .endif

