Route25_SeaCottage_Text_ImBillHelpMeOutPal::
	.string "Yah! Je suis un POKéMON…\n"
	.string "…\l"
	.string "Heu, en fait non!\p"
	.string "Appelle-moi LEO!\n"
	.string "Je suis un vrai POKéMANIAC!\l"
	.string "Tu ne me crois pas?\p"
	.string "Mais c'est vrai!\n"
	.string "J'ai raté une expérience et me\l"
	.string "voilà changé en POKéMON!\p"
	.string "Tu me crois maintenant?\n"
	.string "Tu m'aides alors?$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
	.string "Yah! Je suis un POKéMON…\n"
	.string "…\l"
	.string "Heu, en fait non!\p"
	.string "Appelle-moi LEO!\n"
	.string "Je suis un vrai POKéMANIAC!\l"
	.string "Tu ne me crois pas?\p"
	.string "Mais c'est vrai!\n"
	.string "J'ai raté une expérience et me\l"
	.string "voilà changé en POKéMON!\p"
	.string "Tu me crois maintenant?\n"
	.string "Tu m'aides alors?$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
	.string "Je vais dans le TELEPORTEUR.\p"
	.string "Attends que je sois dedans et\n"
	.string "lance le programme sur mon PC!$"

Route25_SeaCottage_Text_NoPleaseChief::
	.string "Non!? Hé, mais tu dois m'aider, je\n"
	.string "suis un mec cool!\p"
	.string "Bon, allez!\n"
	.string "S'te plaît!\p"
	.string "OK?\n"
	.string "Tant pis!$"

Route25_SeaCottage_Text_NoPleaseBeautiful::
	.string "Non!? Hé, mais tu dois m'aider,\n"
	.string "sois pas cruelle!\p"
	.string "Bon, allez!\n"
	.string "S'te plaît!\p"
	.string "OK?\n"
	.string "Tant pis!$"

Route25_SeaCottage_Text_ThanksBudTakeThis::
	.string "LEO: Yahou!\n"
	.string "Merci, mec! Je t'en dois une!\p"
	.string "Bon, tu es venu pour voir ma\n"
	.string "collection de POKéMON?\p"
	.string "Non?\n"
	.string "Tu rigoles!\p"
	.string "Bon, ben, prends ça en\n"
	.string "remerciement!$"

Route25_SeaCottage_Text_ThanksLadyTakeThis::
	.string "LEO: Yahou!\n"
	.string "Merci, ma belle! Je t'en dois une!\p"
	.string "Bon, tu es venue pour voir ma\n"
	.string "collection de POKéMON?\p"
	.string "Non?\n"
	.string "Tu rigoles!\p"
	.string "Bon, ben, prends ça en\n"
	.string "remerciement!$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
	.string "{PLAYER} obtient le\n"
	.string "PASSE BATEAU!$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff::
	.string "Ton inventaire est plein!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
	.string "L'OCEANE est à CARMIN SUR MER.\n"
	.string "Les passagers sont des DRESSEURS!\p"
	.string "Je suis invité à leur fête mais je\n"
	.string "ne supporte pas ces mariolles!\p"
	.string "Vas-y à ma place.$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
	.string "LEO: N'hésite pas à regarder mes\n"
	.string "POKéMON sur mon PC.\p"
	.string "J'en ai de très rares!$"

Route25_SeaCottage_Text_TeleporterIsDisplayed::
	.string "Le TELEPORTEUR est affiché\n"
	.string "sur le moniteur du PC!$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
	.string "{PLAYER} enclenche le TELEPORTEUR!$"

Route25_SeaCottage_Text_BillsFavoriteMonList::
	.string "La liste des POKéMON favoris\n"
	.string "de LEO!$"

Route25_SeaCottage_Text_SeeWhichMon::
	.string "Quel POKéMON voulez-vous voir?$"

