@ Male and female text identical, differ (presumably) in JP
Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale::
    .ifdef ENGLISH
    .string "My POKéMON's ashes are stored in\n"
    .string "POKéMON TOWER.\p"
    .string "You can have this TM.\n"
    .string "I don't need it anymore…$"
    .endif
    .ifdef SPANISH
    .string "Las cenizas de mis POKéMON están\n"
    .string "guardadas en la TORRE POKéMON.\p"
    .string "Puedes quedarte con mi MT. Ya no\n"
    .string "la necesito...$"
    .endif

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale::
    .ifdef ENGLISH
    .string "My POKéMON's ashes are stored in\n"
    .string "POKéMON TOWER.\p"
    .string "You can have this TM.\n"
    .string "I don't need it anymore…$"
    .endif
    .ifdef SPANISH
    .string "Las cenizas de mis POKéMON están\n"
    .string "guardadas en la TORRE POKéMON.\p"
    .string "Puedes quedarte con mi MT. Ya no\n"
    .string "la necesito...$"
    .endif

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl::
    .ifdef ENGLISH
    .string "{PLAYER} received TM27\n"
    .string "from the little girl.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo la MT27\n"
    .string "de manos de la chica!$"
    .endif

Route12_NorthEntrance_2F_Text_ExplainTM27::
    .ifdef ENGLISH
    .string "TM27 is a move called RETURN…\p"
    .string "If you treat your POKéMON good,\n"
    .string "it will return your love by working\l"
    .string "its hardest in battle.$"
    .endif
    .ifdef SPANISH
    .string "¡La MT27 es un ataque que se\n"
    .string "llama RETROCESO!\p"
    .string "Si tratas bien a tus POKéMON,\n"
    .string "aumentará sus efectos en\l"
    .string "combate.$"
    .endif

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis::
    .ifdef ENGLISH
    .string "You don't have room for this.$"
    .endif
    .ifdef SPANISH
    .string "¡No tienes sitio para esto!$"
    .endif

Route12_NorthEntrance_2F_Text_TheresManFishing::
    .ifdef ENGLISH
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "There's a man fishing!$"
    .endif
    .ifdef SPANISH
    .string "Has usado los prismáticos...\p"
    .string "¡Un hombre está pescando!$"
    .endif

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
    .ifdef ENGLISH
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It's POKéMON TOWER!$"
    .endif
    .ifdef SPANISH
    .string "Has usado los prismáticos...\p"
    .string "¡Es la TORRE POKéMON!$"
    .endif

