@ Male and female text identical, differ (presumably) in JP
Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale::
	.string "Les cendres de mes POKéMON sont\n"
	.string "dans la TOUR POKéMON.\p"
	.string "Tiens! Prends cette CT. Je n'en ai\n"
	.string "plus besoin…$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale::
	.string "Les cendres de mes POKéMON sont\n"
	.string "dans la TOUR POKéMON.\p"
	.string "Tiens! Prends cette CT. Je n'en ai\n"
	.string "plus besoin…$"

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl::
	.string "{PLAYER} obtient\n"
	.string "CT27!$"

Route12_NorthEntrance_2F_Text_ExplainTM27::
	.string "La CT27 s'appelle RETOUR.\p"
	.string "Si tu traites bien tes POKéMON,\n"
	.string "ils te le rendront en se donnant\p"
	.string "plus de mal au combat.$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis::
	.string "Ton inventaire est plein!$"

Route12_NorthEntrance_2F_Text_TheresManFishing::
	.string "Vous regardez dans les jumelles.\p"
	.string "Vous voyez un pêcheur!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
	.string "Vous regardez dans les jumelles.\p"
	.string "Vous voyez la TOUR POKéMON!$"

