CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked::
    .ifdef ENGLISH
    .string "I came to visit the CINNABAR GYM,\n"
    .string "but the door is locked tight.\p"
    .string "There should be a key for it\n"
    .string "somewhere.\p"
    .string "Could it be in that burned-out\n"
    .string "mansion?\p"
    .string "The GYM LEADER's friend used to\n"
    .string "live there, they say.$"
    .endif
    .ifdef SPANISH
    .string "Quería entrar en el GIMNASIO\n"
    .string "de CANELA, pero la puerta\l"
    .string "está cerrada a cal y canto.\p"
    .string "Debe de haber una llave por\n"
    .string "algún sitio.\p"
    .string "¿Estará en la mansión quemada\n"
    .string "esa?\p"
    .string "Dicen que está habitada por un\n"
    .string "amigo del LÍDER del GIMNASIO.$"
    .endif

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom::
    .ifdef ENGLISH
    .string "Do you have lots of friends?\p"
    .string "Linking up with the usual friends\n"
    .string "is fun, of course.\p"
    .string "But how about visiting the\n"
    .string "UNION ROOM every so often?\p"
    .string "Who knows, you may end up making\n"
    .string "new friends.\p"
    .string "I think it would be worth your time\n"
    .string "to check the UNION ROOM.$"
    .endif
    .ifdef SPANISH
    .string "¿Tienes muchos amigos?\p"
    .string "Está muy bien que te conectes\n"
    .string "con ellos, por supuesto.\p"
    .string "Pero si visitas la SALA UNIÓN\n"
    .string "de vez en cuando, puede que\l"
    .string "hagas nuevos amigos.\p"
    .string "Creo que merecería la pena que\n"
    .string "fueras a la SALA UNIÓN.$"
    .endif

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves::
    .ifdef ENGLISH
    .string "POKéMON can still learn techniques\n"
    .string "after canceling evolution.\p"
    .string "Evolution can wait until new moves\n"
    .string "have been learned.$"
    .endif
    .ifdef SPANISH
    .string "Los POKéMON pueden seguir\n"
    .string "aprendiendo técnicas aunque hayas\l"
    .string "cancelado su evolución.\p"
    .string "La evolución puede esperar hasta\n"
    .string "que hayan aprendido nuevos\l"
    .string "movimientos.$"
    .endif

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland::
    .ifdef ENGLISH
    .string "BILL: Hey, you kept me waiting!\n"
    .string "Ready to set sail to ONE ISLAND?$"
    .endif
    .ifdef SPANISH
    .string "BILL: ¡Eh, llevo la tira\n"
    .string "esperando!\l"
    .string "¿Nos vamos a ISLA PRIMA?$"
    .endif

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet::
    .ifdef ENGLISH
    .string "Oh, you're still not done yet?$"
    .endif
    .ifdef SPANISH
    .string "¿Todavía no?$"
    .endif

CinnabarIsland_PokemonCenter_1F_Text_LetsGo::
    .ifdef ENGLISH
    .string "Well, that's it.\n"
    .string "Let's go!$"
    .endif
    .ifdef SPANISH
    .string "Venga, pues vamos.$"
    .endif

