RocketHideout_B2F_Text_GruntIntro::
    .ifdef ENGLISH
    .string "BOSS said you can see ghosts with\n"
    .string "the SILPH SCOPE.$"
    .endif
    .ifdef SPANISH
    .string "¡El JEFE dijo que se pueden ver\n"
    .string "fantasmas con el SCOPE SILPH!$"
    .endif

RocketHideout_B2F_Text_GruntDefeat::
    .ifdef ENGLISH
    .string "I surrender!$"
    .endif
    .ifdef SPANISH
    .string "¡Me rindo!$"
    .endif

RocketHideout_B2F_Text_GruntPostBattle::
    .ifdef ENGLISH
    .string "The TEAM ROCKET HQ has four\n"
    .string "underground floors.\p"
    .string "Think you can reach the BOSS?$"
    .endif
    .ifdef SPANISH
    .string "El CG del TEAM ROCKET tiene\n"
    .string "4 sótanos.\p"
    .string "¿Podrás llegar al JEFE?$"
    .endif

