PokemonTower_2F_Text_RivalIntro::
    .ifdef ENGLISH
    .string "{RIVAL}: Hey, {PLAYER}!\n"
    .string "What brings you here?\l"
    .string "Is your POKéMON dead?\p"
    .string "Hey! It's alive!\p"
    .string "I can at least make them faint!\n"
    .string "Let's go!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Oye, {PLAYER}!\n"
    .string "¿Qué haces por aquí?\l"
    .string "¿Están tus POKéMON debilitados?\p"
    .string "¡Menos mal!\p"
    .string "¡Pero yo puedo conseguir que\n"
    .string "se debiliten! ¡Vamos!$"
    .endif

PokemonTower_2F_Text_RivalDefeat::
    .ifdef ENGLISH
    .string "What?\n"
    .string "You stinker!\p"
    .string "I took it easy on you, too!$"
    .endif
    .ifdef SPANISH
    .string "¿Qué?\n"
    .string "¡Cómo eres!\p"
    .string "¡Y te había tomado en serio!$"
    .endif

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory::
    .string "{RIVAL}“あーあ‥！\n"
    .string "ほんとに　くたばっちまったぞ！\l"
    .string "よわいなー！\l"
    .string "もっと　ちゃんと　そだてて　やれよ$"

PokemonTower_2F_Text_RivalPostBattle::
    .ifdef ENGLISH
    .string "How's your POKéDEX coming?\n"
    .string "I just caught a CUBONE!\p"
    .string "I can't find the bigger MAROWAK.\n"
    .string "Where could they be?\p"
    .string "I bet there aren't any left!\p"
    .string "Well, I better get going.\n"
    .string "I've got a lot to accomplish,\l"
    .string "unlike you.\p"
    .string "Smell ya later!$"
    .endif
    .ifdef SPANISH
    .string "¿Qué tal va tu POKéDEX?\n"
    .string "¡Acabo de capturar un CUBONE!\p"
    .string "¡Todavía no he encontrado al\n"
    .string "MAROWAK adulto!\p"
    .string "¡No creo que quede ninguno!\p"
    .string "¡Creo que me voy a marchar!\n"
    .string "¡Me queda mucho por hacer!\p"
    .string "¡Hasta luego!$"
    .endif

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
    .ifdef ENGLISH
    .string "Even we could not identify the\n"
    .string "wayward ghosts.\p"
    .string "A SILPH SCOPE might be able to\n"
    .string "unmask them.$"
    .endif
    .ifdef SPANISH
    .string "¡Ni siquiera pudimos identificar\n"
    .string "a los GHOST!\p"
    .string "El SCOPE SILPH podría\n"
    .string "desenmascararlos.$"
    .endif

