CeruleanCity_Gym_Text_MistyIntro::
    .string "¡Hola! ¡Tú no eres de por aquí!\p"
    .string "¡Los ENTRENADORES profesionales\n"
    .string "deben tener una estrategia para\l"
    .string "sus POKéMON!\p"
    .string "¿Qué táctica sigues tú para\n"
    .string "atrapar y entrenar POKéMON?\p"
    .string "¡Mi táctica es la ofensiva total\n"
    .string "con los POKéMON del tipo AGUA!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "¡La MT03 enseña HIDROPULSO!\p"
    .string "¡Úsala con los POKéMON del tipo\n"
    .string "AGUA!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .string "¡La MEDALLA CASCADA obligará a\n"
    .string "todos los POKéMON por debajo del\l"
    .string "nivel 30 a obedecer!\p"
    .string "¡Incluidos los forasteros!\p"
    .string "¡Y podrás usar CORTAR siempre que\n"
    .string "quieras!\p"
    .string "¡Puedes CORTAR pequeños arbustos\n"
    .string "para abrir nuevos caminos!\p"
    .string "¡Voy a darte mi MT favorita!$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "¡{PLAYER} obtuvo la MT03\n"
    .string "de manos de MISTY!$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "¡Más vale que le hagas sitio!$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "¡Uauuu!\n"
    .string "¡Eres demasiado!\p"
    .string "¡Muy bien!\p"
    .string "¡Toma la MEDALLA CASCADA para que\n"
    .string "todos sepan que me has ganado!$"

CeruleanCity_Gym_Text_DianaIntro::
    .string "¡Soy demasiado buena para ti!\p"
    .string "¡MISTY puede esperar!$"

CeruleanCity_Gym_Text_DianaDefeat::
    .string "¡Me has machacado!$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "Tienes que luchar contra otros\n"
    .string "ENTRENADORES para saber lo fuerte\l"
    .string "que eres.$"

CeruleanCity_Gym_Text_LuisIntro::
    .string "¡Splash!\p"
    .string "¡Soy el primero!\n"
    .string "¡Al ataque!$"

CeruleanCity_Gym_Text_LuisDefeat::
    .string "¡No puede ser!$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "¡MISTY es cada vez más fuerte!\p"
    .string "¡No perderá con alguien como tú!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
    .string "¡Hola, aspirante al título!\p"
    .string "¡Un consejo!\p"
    .string "¡La LÍDER, MISTY, es profesional\n"
    .string "y usa POKéMON acuáticos!\p"
    .string "¡Puedes absorber toda su agua con\n"
    .string "los POKéMON del tipo PLANTA!\p"
    .string "¡O dejarlos hechos polvo usando\n"
    .string "POKéMON del tipo ELÉCTRICO!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
    .string "¡Has ganado a MISTY!\n"
    .string "¡No sé qué decirte!\p"
    .string "¡Tú y yo formaríamos un equipo\n"
    .string "invencible!$"

CeruleanCity_Gym_Text_GymStatue::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CELESTE: MISTY\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CELESTE: MISTY\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"
