CeruleanCity_Gym_Text_MistyIntro::
    .ifdef ENGLISH
    .string "Hi, you're a new face!\p"
    .string "Only those TRAINERS who have a\n"
    .string "policy about POKéMON can turn pro.\p"
    .string "What is your approach when you\n"
    .string "catch and train POKéMON?\p"
    .string "My policy is an all-out offensive\n"
    .string "with WATER-type POKéMON!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif
    .ifdef SPANISH
    .string "¡Hola! ¡Tú no eres de por aquí!\p"
    .string "¡Los ENTRENADORES profesionales\n"
    .string "deben tener una estrategia para\l"
    .string "sus POKéMON!\p"
    .string "¿Qué táctica sigues tú para\n"
    .string "atrapar y entrenar POKéMON?\p"
    .string "¡Mi táctica es la ofensiva total\n"
    .string "con los POKéMON del tipo AGUA!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif

CeruleanCity_Gym_Text_ExplainTM03::
    .ifdef ENGLISH
    .string "TM03 teaches WATER PULSE.\p"
    .string "Use it on an aquatic POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡La MT03 enseña HIDROPULSO!\p"
    .string "¡Úsala con los POKéMON del tipo\n"
    .string "AGUA!$"
    .endif

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .ifdef ENGLISH
    .string "The CASCADEBADGE makes all\n"
    .string "POKéMON up to Lv. 30 obey.\p"
    .string "That includes even outsiders you\n"
    .string "got in trades.\p"
    .string "There's more. You can now use CUT\n"
    .string "anytime, even out of battle.\p"
    .string "You can CUT down small trees to\n"
    .string "open new pathways.\p"
    .string "You can also have my favorite TM.$"
    .endif
    .ifdef SPANISH
    .string "¡La MEDALLA CASCADA obligará a\n"
    .string "todos los POKéMON por debajo del\l"
    .string "nivel 30 a obedecer!\p"
    .string "¡Incluidos los forasteros!\p"
    .string "¡Y podrás usar CORTAR siempre que\n"
    .string "quieras!\p"
    .string "¡Puedes CORTAR pequeños arbustos\n"
    .string "para abrir nuevos caminos!\p"
    .string "¡Voy a darte mi MT favorita!$"
    .endif

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .ifdef ENGLISH
    .string "{PLAYER} received TM03\n"
    .string "from MISTY.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo la MT03\n"
    .string "de manos de MISTY!$"
    .endif

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .ifdef ENGLISH
    .string "You better make room for this!$"
    .endif
    .ifdef SPANISH
    .string "¡Más vale que le hagas sitio!$"
    .endif

CeruleanCity_Gym_Text_MistyDefeat::
    .ifdef ENGLISH
    .string "Wow!\n"
    .string "You're too much!\p"
    .string "All right!\p"
    .string "You can have the CASCADEBADGE to\n"
    .string "show you beat me.$"
    .endif
    .ifdef SPANISH
    .string "¡Uauuu!\n"
    .string "¡Eres demasiado!\p"
    .string "¡Muy bien!\p"
    .string "¡Toma la MEDALLA CASCADA para que\n"
    .string "todos sepan que me has ganado!$"
    .endif

CeruleanCity_Gym_Text_DianaIntro::
    .ifdef ENGLISH
    .string "What? You?\n"
    .string "I'm more than good enough for you!\p"
    .string "MISTY won't have to be bothered.$"
    .endif
    .ifdef SPANISH
    .string "¡Soy demasiado buena para ti!\p"
    .string "¡MISTY puede esperar!$"
    .endif

CeruleanCity_Gym_Text_DianaDefeat::
    .ifdef ENGLISH
    .string "You overwhelmed me!$"
    .endif
    .ifdef SPANISH
    .string "¡Me has machacado!$"
    .endif

CeruleanCity_Gym_Text_DianaPostBattle::
    .ifdef ENGLISH
    .string "You have to face other TRAINERS\n"
    .string "to see how good you really are.$"
    .endif
    .ifdef SPANISH
    .string "Tienes que luchar contra otros\n"
    .string "ENTRENADORES para saber lo fuerte\l"
    .string "que eres.$"
    .endif

CeruleanCity_Gym_Text_LuisIntro::
    .ifdef ENGLISH
    .string "Splash!\p"
    .string "I'm first up!\n"
    .string "Let's do it!$"
    .endif
    .ifdef SPANISH
    .string "¡Splash!\p"
    .string "¡Soy el primero!\n"
    .string "¡Al ataque!$"
    .endif

CeruleanCity_Gym_Text_LuisDefeat::
    .ifdef ENGLISH
    .string "That can't be!$"
    .endif
    .ifdef SPANISH
    .string "¡No puede ser!$"
    .endif

CeruleanCity_Gym_Text_LuisPostBattle::
    .ifdef ENGLISH
    .string "MISTY is a TRAINER who's going to\n"
    .string "keep improving.\p"
    .string "She won't lose to someone like you!$"
    .endif
    .ifdef SPANISH
    .string "¡MISTY es cada vez más fuerte!\p"
    .string "¡No perderá con alguien como tú!$"
    .endif

CeruleanCity_Gym_Text_GymGuyAdvice::
    .ifdef ENGLISH
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "Let me give you some advice!\p"
    .string "The LEADER, MISTY, is a pro who\n"
    .string "uses WATER-type POKéMON.\p"
    .string "You can drain all their water with\n"
    .string "GRASS-type POKéMON.\p"
    .string "Or, you might use ELECTRIC-type\n"
    .string "POKéMON and zap them!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, aspirante al título!\p"
    .string "¡Un consejo!\p"
    .string "¡La LÍDER, MISTY, es profesional\n"
    .string "y usa POKéMON acuáticos!\p"
    .string "¡Puedes absorber toda su agua con\n"
    .string "los POKéMON del tipo PLANTA!\p"
    .string "¡O dejarlos hechos polvo usando\n"
    .string "POKéMON del tipo ELÉCTRICO!$"
    .endif

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
    .ifdef ENGLISH
    .string "You beat MISTY!\n"
    .string "See, what'd I tell ya?\p"
    .string "You and me, kid, we make a pretty\n"
    .string "darn-good team!$"
    .endif
    .ifdef SPANISH
    .string "¡Has ganado a MISTY!\n"
    .string "¡No sé qué decirte!\p"
    .string "¡Tú y yo formaríamos un equipo\n"
    .string "invencible!$"
    .endif

CeruleanCity_Gym_Text_GymStatue::
    .ifdef ENGLISH
    .string "CERULEAN POKéMON GYM\n"
    .string "LEADER: MISTY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CELESTE: MISTY\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"
    .endif

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .ifdef ENGLISH
    .string "CERULEAN POKéMON GYM\n"
    .string "LEADER: MISTY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CELESTE: MISTY\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"
    .endif

