FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .string "Eh... Ah, hola.\n"
    .string "Soy el QUITA-MOVIMIENTOS.\p"
    .string "Puedo hacer que los POKéMON\n"
    .string "olviden sus movimientos.\p"
    .string "¿Quieres que me ocupe de los\n"
    .string "tuyos?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
    .string "¿Qué POKéMON debería olvidar\n"
    .string "algún movimiento?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
    .string "¿Qué movimiento debería olvidar?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
    .string "Parece que {STR_VAR_1} sólo sabe\n"
    .string "un movimiento...$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
    .string "Ajá.\n"
    .string "¿{STR_VAR_2} de {STR_VAR_1}?\l"
    .string "¿Ése quieres? ¿De verdad?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
    .string "¡Ha salido de perlas!\p"
    .string "{STR_VAR_1} ha olvidado\n"
    .string "completamente {STR_VAR_2}.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
    .string "Vuelve por aquí si quieres que tus\n"
    .string "POKéMON olviden algún movimiento.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
    .string "¿Cómo? Un HUEVO no puede saber\n"
    .string "ningún movimiento.$"
