FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .ifdef ENGLISH
    .string "Uh…\n"
    .string "Oh, yes, I'm the MOVE DELETER.\p"
    .string "I can make POKéMON forget their\n"
    .string "moves.\p"
    .string "Would you like me to do that?$"
    .endif
    .ifdef SPANISH
    .string "Eh... Ah, hola.\n"
    .string "Soy el QUITA-MOVIMIENTOS.\p"
    .string "Puedo hacer que los POKéMON\n"
    .string "olviden sus movimientos.\p"
    .string "¿Quieres que me ocupe de los\n"
    .string "tuyos?$"
    .endif

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
    .ifdef ENGLISH
    .string "Which POKéMON should forget a\n"
    .string "move?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué POKéMON debería olvidar\n"
    .string "algún movimiento?$"
    .endif

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
    .ifdef ENGLISH
    .string "Which move should be forgotten?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué movimiento debería olvidar?$"
    .endif

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
    .ifdef ENGLISH
    .string "{STR_VAR_1} seems to know only one\n"
    .string "move…$"
    .endif
    .ifdef SPANISH
    .string "Parece que {STR_VAR_1} sólo sabe\n"
    .string "un movimiento...$"
    .endif

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
    .ifdef ENGLISH
    .string "Hm! {STR_VAR_1}'s {STR_VAR_2}?\n"
    .string "That move should be forgotten?$"
    .endif
    .ifdef SPANISH
    .string "Ajá.\n"
    .string "¿{STR_VAR_2} de {STR_VAR_1}?\l"
    .string "¿Ése quieres? ¿De verdad?$"
    .endif

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
    .ifdef ENGLISH
    .string "It worked to perfection!\p"
    .string "{STR_VAR_1} has forgotten\n"
    .string "{STR_VAR_2} completely.$"
    .endif
    .ifdef SPANISH
    .string "¡Ha salido de perlas!\p"
    .string "{STR_VAR_1} ha olvidado\n"
    .string "completamente {STR_VAR_2}.$"
    .endif

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
    .ifdef ENGLISH
    .string "Come again if there are other\n"
    .string "moves to be forgotten.$"
    .endif
    .ifdef SPANISH
    .string "Vuelve por aquí si quieres que tus\n"
    .string "POKéMON olviden algún movimiento.$"
    .endif

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
    .ifdef ENGLISH
    .string "What?\n"
    .string "No EGG should know any moves.$"
    .endif
    .ifdef SPANISH
    .string "¿Cómo? Un HUEVO no puede saber\n"
    .string "ningún movimiento.$"
    .endif

