FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
	.string "Äh... oh, ja. Ich bin der\n"
	.string "ATTACKEN-VERLERNER.\p"
	.string "Ich sorge dafür, dass die POKéMON\n"
	.string "ihre Attacken vergessen.\p"
	.string "Möchtest du, dass ich dir helfe?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
	.string "Welches POKéMON soll eine Attacke\n"
	.string "vergessen?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
	.string "Welche Attacke soll vergessen\n"
	.string "werden?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
	.string "{STR_VAR_1} kennt scheinbar nur eine\n"
	.string "einzige Attacke...$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
	.string "Hm! {STR_VAR_2} von {STR_VAR_1}?\n"
	.string "Diese Attacke soll vergessen\l"
	.string "werden?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
	.string "Das klappte doch perfekt!\p"
	.string "{STR_VAR_1} hat {STR_VAR_2}\n"
	.string "komplett vergessen.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
	.string "Komm wieder, wenn es andere\n"
	.string "Attacken gibt, die vergessen werden\l"
	.string "sollen.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
	.string "Was?\n"
	.string "Ein EI kennt doch keine Attacken!$"

