Text_DreamEaterTeach::
    .ifdef ENGLISH
    .string "Yawn!\n"
    .string "I must have dozed off in the sun.\p"
    .string "I had this weird dream about\n"
    .string "a DROWZEE eating my dream.\p"
    .string "And…\n"
    .string "I learned how to eat dreams…\p"
    .string "Oogh, this is too spooky!\p"
    .string "Let me teach it to a POKéMON so\n"
    .string "I can forget about it!$"
    .endif
    .ifdef SPANISH
    .string "¡Uaaaahuuh...!\n"
    .string "Debo de haberme dormido al sol...\p"
    .string "He soñado que un DROWZEE\n"
    .string "se comía mi sueño.\p"
    .string "¡¡Y he aprendido a comer sueños!!\n"
    .string "¡¡¡Qué miedo!!!\p"
    .string "¿Quieres que se lo enseñe\n"
    .string "a un POKéMON?$"
    .endif

Text_DreamEaterDeclined::
    .ifdef ENGLISH
    .string "…Snore…$"
    .endif
    .ifdef SPANISH
    .string "Pues vaya... Zz... Zzzzzz...$"
    .endif

Text_DreamEaterWhichMon::
    .ifdef ENGLISH
    .string "Which POKéMON wants to learn\n"
    .string "DREAM EATER?$"
    .endif
    .ifdef SPANISH
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe COME SUEÑOS?$"
    .endif

Text_DreamEaterTaught::
    .ifdef ENGLISH
    .string "…ZZZ…\n"
    .string "I…can't eat…anymore…$"
    .endif
    .ifdef SPANISH
    .string "Yo... Ya no puedo comer más...\n"
    .string "Zz... Zzzzz...$"
    .endif

PewterCity_Text_ClefairyCameFromMoon::
    .ifdef ENGLISH
    .string "CLEFAIRY came from the moon.\n"
    .string "That's what the rumor is.\p"
    .string "They appeared after MOON STONES\n"
    .string "fell on MT. MOON.$"
    .endif
    .ifdef SPANISH
    .string "¡Dicen que los CLEFAIRY vinieron\n"
    .string "de la Luna!\p"
    .string "¡Aparecieron tras la caída de\n"
    .string "varias PIEDRAS LUNARES\l"
    .string "en el MT. MOON!$"
    .endif

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .ifdef ENGLISH
    .string "There aren't many serious POKéMON\n"
    .string "TRAINERS here.\p"
    .string "They're all like BUG CATCHERS,\n"
    .string "you know, just hobbyists.\p"
    .string "But PEWTER GYM's BROCK isn't like\n"
    .string "that, not one bit.$"
    .endif
    .ifdef SPANISH
    .string "¡No hay muchos ENTRENADORES\n"
    .string "de POKéMON por aquí!\p"
    .string "¡Todos parecen CAZABICHOS, salvo\n"
    .string "BROCK, del GIMNASIO de PLATEADA!$"
    .endif

PewterCity_Text_DidYouCheckOutMuseum::
    .ifdef ENGLISH
    .string "Did you check out the MUSEUM?$"
    .endif
    .ifdef SPANISH
    .string "¿Has estado en el MUSEO?$"
    .endif

PewterCity_Text_WerentThoseFossilsAmazing::
    .ifdef ENGLISH
    .string "Weren't those fossils from MT. MOON\n"
    .string "amazing?$"
    .endif
    .ifdef SPANISH
    .string "¿No eran geniales esos fósiles\n"
    .string "del MT. MOON?$"
    .endif

PewterCity_Text_ReallyYouHaveToGo::
    .ifdef ENGLISH
    .string "Really?\n"
    .string "You absolutely have to go!$"
    .endif
    .ifdef SPANISH
    .string "¿De verdad?\n"
    .string "¡Pues tienes que ir!$"
    .endif

PewterCity_Text_ThisIsTheMuseum::
    .ifdef ENGLISH
    .string "This is it, the MUSEUM.\p"
    .string "You have to pay to get in, but it's\n"
    .string "worth it. See you around!$"
    .endif
    .ifdef SPANISH
    .string "¡Está aquí mismo!\p"
    .string "¡Hay que pagar para entrar, pero\n"
    .string "vale la pena! ¡Hasta luego!$"
    .endif

PewterCity_Text_DoYouKnowWhatImDoing::
    .ifdef ENGLISH
    .string "Psssst!\n"
    .string "Do you know what I'm doing?$"
    .endif
    .ifdef SPANISH
    .string "¡Pssss!\n"
    .string "¿Sabes lo que estoy haciendo?$"
    .endif

PewterCity_Text_ThatsRightItsHardWork::
    .ifdef ENGLISH
    .string "That's right!\n"
    .string "It's hard work!$"
    .endif
    .ifdef SPANISH
    .string "¡Eso es!\n"
    .string "¡Un trabajo tremendo!$"
    .endif

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .ifdef ENGLISH
    .string "I'm spraying REPEL to keep wild\n"
    .string "POKéMON out of my garden!$"
    .endif
    .ifdef SPANISH
    .string "¡Utilizo el REPELENTE para echar\n"
    .string "de mi jardín a los POKéMON!$"
    .endif

PewterCity_Text_BrocksLookingForChallengersFollowMe::
    .ifdef ENGLISH
    .string "You're a TRAINER, right?\p"
    .string "BROCK's looking for new\n"
    .string "challengers. Follow me!$"
    .endif
    .ifdef SPANISH
    .string "¿Entrenas POKéMON?\p"
    .string "¡BROCK está buscando a nuevos\n"
    .string "adversarios! ¡Sígueme!$"
    .endif

PewterCity_Text_GoTakeOnBrock::
    .ifdef ENGLISH
    .string "If you have the right stuff,\n"
    .string "go take on BROCK!$"
    .endif
    .ifdef SPANISH
    .string "¡Si eres valiente, pelearás contra\n"
    .string "BROCK!$"
    .endif

PewterCity_Text_TrainerTipsEarningEXP::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "All POKéMON that appear in battle,\n"
    .string "however briefly, earn EXP Points.$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "¡Todo POKéMON que luche en un\n"
    .string "combate ganará EXPERIENCIA!$"
    .endif

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .ifdef ENGLISH
    .string "NOTICE!\p"
    .string "Thieves have been stealing POKéMON\n"
    .string "fossils from MT. MOON.\p"
    .string "Please call the PEWTER POLICE if\n"
    .string "you have any information.$"
    .endif
    .ifdef SPANISH
    .string "¡AVISO!\p"
    .string "¡Unos ladrones han robado fósiles\n"
    .string "de POKéMON del MT. MOON!\p"
    .string "¡Avisad a la POLICÍA de CIUDAD\n"
    .string "PLATEADA si sabéis algo!$"
    .endif

PewterCity_Text_MuseumOfScience::
    .ifdef ENGLISH
    .string "PEWTER MUSEUM OF SCIENCE$"
    .endif
    .ifdef SPANISH
    .string "MUSEO DE LA CIENCIA DE\n"
    .string "CIUDAD PLATEADA$"
    .endif

PewterCity_Text_GymSign::
    .ifdef ENGLISH
    .string "PEWTER CITY POKéMON GYM\n"
    .string "LEADER: BROCK\l"
    .string "The Rock-Solid POKéMON TRAINER!$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de PLATEADA: BROCK\l"
    .string "¡Es fuerte como una roca!$"
    .endif

PewterCity_Text_CitySign::
    .ifdef ENGLISH
    .string "PEWTER CITY\n"
    .string "A Stone Gray City$"
    .endif
    .ifdef SPANISH
    .string "CIUDAD PLATEADA\n"
    .string "Una ciudad de roca grisácea.$"
    .endif

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
    .string "あッれー！\n"
    .string "その　ジムバッジ‥‥\l"
    .string "すげえな　タケシに　かったのかよ！\p"
    .string "かんどう　したから\n"
    .string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully::
    .string "なかには　きのみが　はいってるぜ\p"
    .string "やくに　たつ　きのみも\n"
    .string "はいって　いるから\l"
    .string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
    .string "ポケモンに　きのみを\n"
    .string "もたせて　おけば\l"
    .string "たたかっている　ときに\l"
    .string "かってに　つかって　くれるんだ\p"
    .string "キズぐすり　とか　どくけし　より\n"
    .string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer::
    .ifdef ENGLISH
    .string "Oh, {PLAYER}{KUN}!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, {PLAYER}{KUN}!$"
    .endif

PewterCity_Text_AskedToDeliverThis::
    .ifdef ENGLISH
    .string "I'm glad I caught up to you.\n"
    .string "I'm PROF. OAK's AIDE.\p"
    .string "I've been asked to deliver this,\n"
    .string "so here you go.$"
    .endif
    .ifdef SPANISH
    .string "Menos mal que te pillo, soy\n"
    .string "AYUDANTE del PROF. OAK.\p"
    .string "Me han pedido que te diera una\n"
    .string "cosa, aquí tienes.$"
    .endif

PewterCity_Text_ReceivedRunningShoesFromAide::
    .ifdef ENGLISH
    .string "{PLAYER} received the\n"
    .string "RUNNING SHOES from the AIDE.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió las DEPORTIVAS\n"
    .string "de manos del AYUDANTE!$"
    .endif

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .ifdef ENGLISH
    .string "{PLAYER} switched shoes with the\n"
    .string "RUNNING SHOES.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} se ha puesto las\n"
    .string "DEPORTIVAS.$"
    .endif

PewterCity_Text_ExplainRunningShoes::
    .ifdef ENGLISH
    .string "Press the B Button to run.\n"
    .string "But only where there's room to run!$"
    .endif
    .ifdef SPANISH
    .string "Para correr, pulsa el Botón B,\n"
    .string "¡pero sólo donde haya sitio!$"
    .endif

PewterCity_Text_MustBeGoingBackToLab::
    .ifdef ENGLISH
    .string "Well, I must be going back to\n"
    .string "the LAB.\p"
    .string "Bye-bye!$"
    .endif
    .ifdef SPANISH
    .string "Bueno, tengo que volver al\n"
    .string "LABORATORIO.\p"
    .string "Hasta luego.$"
    .endif

PewterCity_Text_RunningShoesLetterFromMom::
    .ifdef ENGLISH
    .string "There's a letter attached…\p"
    .string "Dear {PLAYER},\p"
    .string "Here is a pair of RUNNING SHOES\n"
    .string "for my beloved challenger.\p"
    .string "Remember, I'll always cheer for\n"
    .string "you! Don't ever give up!\p"
    .string "From Mom$"
    .endif
    .ifdef SPANISH
    .string "Vienen con una notita...\p"
    .string "{PLAYER}, cielo:\p"
    .string "Aquí tienes un par de DEPORTIVAS,\n"
    .string "adorable valiente.\p"
    .string "Piensa que siempre voy a estar\n"
    .string "aquí para apoyarte, ¡ánimo!\p"
    .string "Mamá$"
    .endif

