PokemonTower_3F_Text_HopeIntro::
	.string "Buu... huhu...\n"
	.string "Huhu... buu...$"

PokemonTower_3F_Text_HopeDefeat::
	.string "Buu!\n"
	.string "Ich wurde erlöst!$"

PokemonTower_3F_Text_HopePostBattle::
	.string "Das SILPH SCOPE kann GEISTER\n"
	.string "identifizieren!$"

PokemonTower_3F_Text_CarlyIntro::
	.string "Buhuhuhu...\n"
	.string "Hui... buuh!$"

PokemonTower_3F_Text_CarlyDefeat::
	.string "Hmm?\n"
	.string "Was mache ich hier?$"

PokemonTower_3F_Text_CarlyPostBattle::
	.string "Tut mir Leid!\n"
	.string "Ich war besessen!$"

PokemonTower_3F_Text_PatriciaIntro::
	.string "Verschwinde, böser Geist!$"

PokemonTower_3F_Text_PatriciaDefeat::
	.string "Puh!\n"
	.string "Der Geist ist verschwunden!$"

PokemonTower_3F_Text_PatriciaPostBattle::
	.string "Auch meine Freunde waren besessen!$"

