PokemonTower_3F_Text_HopeIntro::
    .string "Urrg... aaa...\n"
    .string "Uuuu... graa...$"

PokemonTower_3F_Text_HopeDefeat::
    .string "¡Uauu!\n"
    .string "¡Estoy salvada!$"

PokemonTower_3F_Text_HopePostBattle::
    .string "Los GHOST son identificados con\n"
    .string "el SCOPE SILPH.$"

PokemonTower_3F_Text_CarlyIntro::
    .string "Gaaaa...\n"
    .string "¡Gaaah!$"

PokemonTower_3F_Text_CarlyDefeat::
    .string "¿Mmm?\n"
    .string "¿Pero qué hago?$"

PokemonTower_3F_Text_CarlyPostBattle::
    .string "¡Perdona!\n"
    .string "¡Estaba fuera de mí!$"

PokemonTower_3F_Text_PatriciaIntro::
    .string "¡Fuera, espíritu malvado!$"

PokemonTower_3F_Text_PatriciaDefeat::
    .string "¡El espíritu se fue!$"

PokemonTower_3F_Text_PatriciaPostBattle::
    .string "¡Mis amigos también estaban\n"
    .string "fuera de sí!$"
