PokemonTower_3F_Text_HopeIntro::
    .ifdef ENGLISH
    .string "Urrg… Awaa…\n"
    .string "Huhu… Graa…$"
    .endif
    .ifdef SPANISH
    .string "Urrg... aaa...\n"
    .string "Uuuu... graa...$"
    .endif

PokemonTower_3F_Text_HopeDefeat::
    .ifdef ENGLISH
    .string "Hwa!\n"
    .string "I'm saved!$"
    .endif
    .ifdef SPANISH
    .string "¡Uauu!\n"
    .string "¡Estoy salvada!$"
    .endif

PokemonTower_3F_Text_HopePostBattle::
    .ifdef ENGLISH
    .string "The ghosts can be identified by\n"
    .string "the SILPH SCOPE.$"
    .endif
    .ifdef SPANISH
    .string "Los GHOST son identificados con\n"
    .string "el SCOPE SILPH.$"
    .endif

PokemonTower_3F_Text_CarlyIntro::
    .ifdef ENGLISH
    .string "Kekeke…\n"
    .string "Kwaaah!$"
    .endif
    .ifdef SPANISH
    .string "Gaaaa...\n"
    .string "¡Gaaah!$"
    .endif

PokemonTower_3F_Text_CarlyDefeat::
    .ifdef ENGLISH
    .string "Hmm?\n"
    .string "What am I doing?$"
    .endif
    .ifdef SPANISH
    .string "¿Mmm?\n"
    .string "¿Pero qué hago?$"
    .endif

PokemonTower_3F_Text_CarlyPostBattle::
    .ifdef ENGLISH
    .string "Sorry!\n"
    .string "I was possessed!$"
    .endif
    .ifdef SPANISH
    .string "¡Perdona!\n"
    .string "¡Estaba fuera de mí!$"
    .endif

PokemonTower_3F_Text_PatriciaIntro::
    .ifdef ENGLISH
    .string "Be gone!\n"
    .string "Malevolent spirit!$"
    .endif
    .ifdef SPANISH
    .string "¡Fuera, espíritu malvado!$"
    .endif

PokemonTower_3F_Text_PatriciaDefeat::
    .ifdef ENGLISH
    .string "Whew!\n"
    .string "The spirit left!$"
    .endif
    .ifdef SPANISH
    .string "¡El espíritu se fue!$"
    .endif

PokemonTower_3F_Text_PatriciaPostBattle::
    .ifdef ENGLISH
    .string "The others above…\n"
    .string "They must have been possessed.$"
    .endif
    .ifdef SPANISH
    .string "¡Mis amigos también estaban\n"
    .string "fuera de sí!$"
    .endif

