Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough::
    .ifdef ENGLISH
    .string "Hi! Remember me?\n"
    .string "I'm one of PROF. OAK's AIDES.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on {STR_VAR_1} species, I'm supposed to\l"
    .string "give you a reward.\p"
    .string "PROF. OAK entrusted me with the\n"
    .string "{STR_VAR_2} for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "{STR_VAR_1} kinds of POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¡Hola! ¿Te acuerdas de mí?\n"
    .string "¡Soy AYUDANTE del PROF. OAK!\p"
    .string "¡Si ya tienes {STR_VAR_1} tipos de POKéMON,\n"
    .string "se supone que debería darte\l"
    .string "{STR_VAR_2}!\p"
    .string "Dime, {PLAYER}. ¿Tienes ya al menos\n"
    .string "{STR_VAR_1} tipos de POKéMON?$"
    .endif

Route15_WestEntrance_2F_Text_GreatHereYouGo::
    .ifdef ENGLISH
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"
    .endif
    .ifdef SPANISH
    .string "¡Bien! ¡Has logrado {STR_VAR_3} tipos\n"
    .string "de POKéMON!\p"
    .string "¡Enhorabuena!\n"
    .string "¡Aquí tienes!$"
    .endif

Route15_WestEntrance_2F_Text_ReceivedItemFromAide::
    .ifdef ENGLISH
    .string "{PLAYER} received the {STR_VAR_2}\n"
    .string "from the AIDE.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo {STR_VAR_2}\n"
    .string "de manos del AYUDANTE!$"
    .endif

Route15_WestEntrance_2F_Text_ExplainExpShare::
    .ifdef ENGLISH
    .string "EXP. SHARE is an item to be held\n"
    .string "by a POKéMON.\p"
    .string "The POKéMON will receive a share\n"
    .string "of the EXP. Points without having\l"
    .string "to battle.$"
    .endif
    .ifdef SPANISH
    .string "REPARTIR EXP. es un objeto\n"
    .string "que puede llevar un POKéMON.\p"
    .string "Dará puntos de EXPERIENCIA\n"
    .string "al POKéMON que lo lleve, aunque\l"
    .string "no luche.$"
    .endif

Route15_WestEntrance_2F_Text_LargeShiningBird::
    .ifdef ENGLISH
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "A large, shining bird is flying\n"
    .string "toward the sea.$"
    .endif
    .ifdef SPANISH
    .string "Has usado los prismáticos...\p"
    .string "Un pájaro grande y brillante vuela\n"
    .string "hacia el mar.$"
    .endif

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon::
    .ifdef ENGLISH
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "It looks like a small island on\n"
    .string "the horizon!$"
    .endif
    .ifdef SPANISH
    .string "Has usado los prismáticos...\p"
    .string "¡Parece que hay una pequeña isla!$"
    .endif

