Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough::
	.string "Hallo! Erinnerst du dich?\n"
	.string "Ich bin PROF. EICHs\l"
	.string "ASSISTENT!\p"
	.string "Wenn du mindestens {STR_VAR_1} verschiedene\n"
	.string "POKéMON gefangen hast, habe ich\l"
	.string "ein Geschenk für dich:\l"
	.string "{STR_VAR_2}\p"
	.string "Also, {PLAYER}, hast du {STR_VAR_1}\n"
	.string "unterschiedliche POKéMON gefangen?$"

Route15_WestEntrance_2F_Text_GreatHereYouGo::
	.string "Super! Du hast {STR_VAR_3} verschiedene\n"
	.string "POKéMON gefangen!\p"
	.string "Einfach klasse! Hier, das hast du\n"
	.string "dir redlich verdient!$"

Route15_WestEntrance_2F_Text_ReceivedItemFromAide::
	.string "{PLAYER} erhält\n"
	.string "{STR_VAR_2}!$"

Route15_WestEntrance_2F_Text_ExplainExpShare::
	.string "Der EP-TEILER kann einem\n"
	.string "POKéMON zum Tragen gegeben\l"
	.string "werden.\l"
	.string "Mit dem EP-TEILER bekommt das\l"
	.string "POKéMON, das ihn trägt, nach einem\l"
	.string "Kampf E.-Punkte, ohne gekämpft\l"
	.string "zu haben.$"

Route15_WestEntrance_2F_Text_LargeShiningBird::
	.string "Du schaust durch das Fernrohr.\p"
	.string "Ein großer Vogel fliegt anmutig\n"
	.string "aufs Meer hinaus.$"

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon::
	.string "Du schaust durch das Fernrohr.\p"
	.string "Hmm, das sieht wie eine kleine\n"
	.string "Insel aus!$"

