SilphCo_9F_Text_YouShouldTakeQuickNap::
	.string "Après tant d'efforts, tu\n"
	.string "devrais faire une sieste!$"

SilphCo_9F_Text_DontGiveUp::
	.string "Courage!$"

SilphCo_9F_Text_ThankYouSoMuch::
	.string "Merci mille fois!$"

SilphCo_9F_Text_Grunt1Intro::
	.string "Tes POKéMON ont l'air de t'aimer!$"

SilphCo_9F_Text_Grunt1Defeat::
	.string "Ghaaah!$"

SilphCo_9F_Text_Grunt1PostBattle::
	.string "Si j'avais commencé avec les\n"
	.string "POKéMON à ton âge…$"

SilphCo_9F_Text_EdIntro::
	.string "Tes POKéMON ont des points faibles!\n"
	.string "Ah-ah!$"

SilphCo_9F_Text_EdDefeat::
	.string "Non!\n"
	.string "J'ai perdu!$"

SilphCo_9F_Text_EdPostBattle::
	.string "Jouer sur les points faibles est\n"
	.string "la clé! Pense aux différents types!$"

SilphCo_9F_Text_Grunt2Intro::
	.string "Je suis l'un des 4 FRERES ROCKET!$"

SilphCo_9F_Text_Grunt2Defeat::
	.string "Frères!\n"
	.string "J'suis nul!$"

SilphCo_9F_Text_Grunt2PostBattle::
	.string "Mes frères me vengeront!$"

SilphCo_9F_Text_FloorSign::
	.string "SYLPHE SARL.\n"
	.string "8ème étage.$"

