SilphCo_9F_Text_YouShouldTakeQuickNap::
    .string "¡Tienes cara de cansancio!\n"
    .string "¡Deberías echarte una siestecita!$"

SilphCo_9F_Text_DontGiveUp::
    .string "¡No te rindas!$"

SilphCo_9F_Text_ThankYouSoMuch::
    .string "¡Muchísimas gracias!$"

SilphCo_9F_Text_Grunt1Intro::
    .string "¡Tus POKéMON parecen adorarte!$"

SilphCo_9F_Text_Grunt1Defeat::
    .string "¡Buaah!$"

SilphCo_9F_Text_Grunt1PostBattle::
    .string "Si yo hubiera empezado como\n"
    .string "ENTRENADOR a tu edad...$"

SilphCo_9F_Text_EdIntro::
    .string "¡Tus POKéMON tienen puntos\n"
    .string "débiles! ¡Yo puedo verlos!$"

SilphCo_9F_Text_EdDefeat::
    .string "¡Me has machacado!$"

SilphCo_9F_Text_EdPostBattle::
    .string "¡Aprovechar sus puntos débiles\n"
    .string "funciona! ¡Piensa en los tipos!$"

SilphCo_9F_Text_Grunt2Intro::
    .string "¡Soy uno de los 4\n"
    .string "HERMANOS ROCKET!$"

SilphCo_9F_Text_Grunt2Defeat::
    .string "¡Hermanos!\n"
    .string "¡He perdido!$"

SilphCo_9F_Text_Grunt2PostBattle::
    .string "¡Mis hermanos me vengarán!$"

SilphCo_9F_Text_FloorSign::
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P8$"
