SilphCo_9F_Text_YouShouldTakeQuickNap::
    .ifdef ENGLISH
    .string "You look tired.\n"
    .string "You should take a quick nap.$"
    .endif
    .ifdef SPANISH
    .string "¡Tienes cara de cansancio!\n"
    .string "¡Deberías echarte una siestecita!$"
    .endif

SilphCo_9F_Text_DontGiveUp::
    .ifdef ENGLISH
    .string "Don't give up!$"
    .endif
    .ifdef SPANISH
    .string "¡No te rindas!$"
    .endif

SilphCo_9F_Text_ThankYouSoMuch::
    .ifdef ENGLISH
    .string "Thank you so much.$"
    .endif
    .ifdef SPANISH
    .string "¡Muchísimas gracias!$"
    .endif

SilphCo_9F_Text_Grunt1Intro::
    .ifdef ENGLISH
    .string "Your POKéMON seem to adore you,\n"
    .string "kid!$"
    .endif
    .ifdef SPANISH
    .string "¡Tus POKéMON parecen adorarte!$"
    .endif

SilphCo_9F_Text_Grunt1Defeat::
    .ifdef ENGLISH
    .string "Ghaaah!$"
    .endif
    .ifdef SPANISH
    .string "¡Buaah!$"
    .endif

SilphCo_9F_Text_Grunt1PostBattle::
    .ifdef ENGLISH
    .string "If I had started as a TRAINER at\n"
    .string "your age…$"
    .endif
    .ifdef SPANISH
    .string "Si yo hubiera empezado como\n"
    .string "ENTRENADOR a tu edad...$"
    .endif

SilphCo_9F_Text_EdIntro::
    .ifdef ENGLISH
    .string "Your POKéMON have weak points!\n"
    .string "I can nail them!$"
    .endif
    .ifdef SPANISH
    .string "¡Tus POKéMON tienen puntos\n"
    .string "débiles! ¡Yo puedo verlos!$"
    .endif

SilphCo_9F_Text_EdDefeat::
    .ifdef ENGLISH
    .string "You hammered me!$"
    .endif
    .ifdef SPANISH
    .string "¡Me has machacado!$"
    .endif

SilphCo_9F_Text_EdPostBattle::
    .ifdef ENGLISH
    .string "Exploiting weak spots does work.\n"
    .string "Think about type advantages.$"
    .endif
    .ifdef SPANISH
    .string "¡Aprovechar sus puntos débiles\n"
    .string "funciona! ¡Piensa en los tipos!$"
    .endif

SilphCo_9F_Text_Grunt2Intro::
    .ifdef ENGLISH
    .string "I am one of the four ROCKET\n"
    .string "BROTHERS!$"
    .endif
    .ifdef SPANISH
    .string "¡Soy uno de los 4\n"
    .string "HERMANOS ROCKET!$"
    .endif

SilphCo_9F_Text_Grunt2Defeat::
    .ifdef ENGLISH
    .string "Warg!\n"
    .string "Brothers, I lost!$"
    .endif
    .ifdef SPANISH
    .string "¡Hermanos!\n"
    .string "¡He perdido!$"
    .endif

SilphCo_9F_Text_Grunt2PostBattle::
    .ifdef ENGLISH
    .string "My brothers will avenge me!$"
    .endif
    .ifdef SPANISH
    .string "¡Mis hermanos me vengarán!$"
    .endif

SilphCo_9F_Text_FloorSign::
    .ifdef ENGLISH
    .string "SILPH CO. HEAD OFFICE\n"
    .string "9F$"
    .endif
    .ifdef SPANISH
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P8$"
    .endif

