SilphCo_9F_Text_YouShouldTakeQuickNap::
	.string "Du siehst müde aus!\n"
	.string "Komm, ruhe dich kurz aus!$"

SilphCo_9F_Text_DontGiveUp::
	.string "Gib nicht auf!$"

SilphCo_9F_Text_ThankYouSoMuch::
	.string "Vielen, vielen Dank!$"

SilphCo_9F_Text_Grunt1Intro::
	.string "Deine POKéMON scheinen dich sehr\n"
	.string "zu mögen!$"

SilphCo_9F_Text_Grunt1Defeat::
	.string "Waaah!$"

SilphCo_9F_Text_Grunt1PostBattle::
	.string "Hätte ich doch auch schon in\n"
	.string "deinem Alter als TRAINER begonnen!$"

SilphCo_9F_Text_EdIntro::
	.string "Ich finde die Schwachstellen\n"
	.string "deiner POKéMON und besiege sie!$"

SilphCo_9F_Text_EdDefeat::
	.string "Du hast mich besiegt!$"

SilphCo_9F_Text_EdPostBattle::
	.string "Mach dir die Schwachstellen zu\n"
	.string "Nutze! Denke an die Elementklassen!$"

SilphCo_9F_Text_Grunt2Intro::
	.string "Ich bin einer der vier berüchtigten\n"
	.string "ROCKET-BRÜDER!$"

SilphCo_9F_Text_Grunt2Defeat::
	.string "Oje!\n"
	.string "Ich wurde besiegt!$"

SilphCo_9F_Text_Grunt2PostBattle::
	.string "Aber meine Brüder rächen mich!$"

SilphCo_9F_Text_FloorSign::
	.string "SILPH CO. HAUPTSITZ\n"
	.string "8 OG$"

