Route25_Text_JoeyIntro::
    .string "¡Los ENTRENADORES de la zona\n"
    .string "vienen aquí a practicar!$"

Route25_Text_JoeyDefeat::
    .string "Eres espectacular.$"

Route25_Text_JoeyPostBattle::
    .string "Todo POKéMON tiene sus puntos\n"
    .string "débiles.\p"
    .string "Lo suyo es entrenar varios tipos.$"

Route25_Text_DanIntro::
    .string "¡Mi padre me llevó a una gran\n"
    .string "fiesta en el S.S. ANNE, en\l"
    .string "CIUDAD CARMÍN!$"

Route25_Text_DanDefeat::
    .string "¡No estoy enfadado!$"

Route25_Text_DanPostBattle::
    .string "En el S.S. ANNE vi a ENTRENADORES\n"
    .string "de todo el mundo.$"

Route25_Text_FlintIntro::
    .string "Soy un buen chico.\n"
    .string "¡Y tengo novia!$"

Route25_Text_FlintDefeat::
    .string "Vaya...$"

Route25_Text_FlintPostBattle::
    .string "Bueno, mi chica me animará.$"

Route25_Text_KelseyIntro::
    .string "¡Hola!\n"
    .string "¡Mi chico es genial!$"

Route25_Text_KelseyDefeat::
    .string "¡No estaba en muy buena forma!$"

Route25_Text_KelseyPostBattle::
    .string "¡Ojalá mi chico fuera tan bueno\n"
    .string "como tú!$"

Route25_Text_ChadIntro::
    .string "¡Sabía que tendría que luchar\n"
    .string "contigo!$"

Route25_Text_ChadDefeat::
    .string "¡Sabía que iba a perder!$"

Route25_Text_ChadPostBattle::
    .string "Si tu POKéMON sufre confusión, lo\n"
    .string "mejor es que lo cambies por otro.\p"
    .string "Es la mejor táctica.$"

Route25_Text_HaleyIntro::
    .string "Mi amigo tiene unos POKéMON\n"
    .string "muy monos. ¡Qué envidia!$"

Route25_Text_HaleyDefeat::
    .string "¡No estoy enfadada!$"

Route25_Text_HaleyPostBattle::
    .string "¿Vienes del MT. MOON?\n"
    .string "¿Me das un CLEFAIRY?$"

Route25_Text_FranklinIntro::
    .string "¡Acabo de bajar del MT. MOON,\n"
    .string "pero estoy listo!$"

Route25_Text_FranklinDefeat::
    .string "¡Te has esforzado mucho!$"

Route25_Text_FranklinPostBattle::
    .string "¡Aaaaaaargh!\n"
    .string "Me ha mordido un ZUBAT.$"

Route25_Text_NobIntro::
    .string "¡Estoy buscando a un coleccionista\n"
    .string "de POKéMON en el cabo!$"

Route25_Text_NobDefeat::
    .string "¡Me has ganado!$"

Route25_Text_NobPostBattle::
    .string "El coleccionista tiene muchos\n"
    .string "POKéMON raros.$"

Route25_Text_WayneIntro::
    .string "¿Vas a ver a BILL?\n"
    .string "¡Pues luchemos primero!$"

Route25_Text_WayneDefeat::
    .string "¡Me rindo!$"

Route25_Text_WaynePostBattle::
    .string "La ruta de abajo es un atajo\n"
    .string "a CIUDAD CELESTE.$"

Route25_Text_SeaCottageSign::
    .string "LA CASA del MAR\n"
    .string "¡BILL vive aquí!$"

Route25_Text_MistyHighHopesAboutThisPlace::
    .string "En este cabo queda mucha gente.\p"
    .string "MISTY, la LÍDER del GIMNASIO,\n"
    .string "suele venir por aquí.$"

Route25_Text_AreYouHereAlone::
    .string "¿Has venido sin nadie\n"
    .string "que te acompañe?\p"
    .string "Si estás en el cabo de CELESTE,\n"
    .string "¡deberías aprovechar para buscar\l"
    .string "compañía!...$"
