Route25_Text_JoeyIntro::
    .ifdef ENGLISH
    .string "Local TRAINERS come here to\n"
    .string "practice.$"
    .endif
    .ifdef SPANISH
    .string "¡Los ENTRENADORES de la zona\n"
    .string "vienen aquí a practicar!$"
    .endif

Route25_Text_JoeyDefeat::
    .ifdef ENGLISH
    .string "You're decent.$"
    .endif
    .ifdef SPANISH
    .string "Eres espectacular.$"
    .endif

Route25_Text_JoeyPostBattle::
    .ifdef ENGLISH
    .string "All POKéMON have weaknesses.\n"
    .string "Even the strongest ones.\p"
    .string "That's why it's best to raise\n"
    .string "POKéMON of different types.$"
    .endif
    .ifdef SPANISH
    .string "Todo POKéMON tiene sus puntos\n"
    .string "débiles.\p"
    .string "Lo suyo es entrenar varios tipos.$"
    .endif

Route25_Text_DanIntro::
    .ifdef ENGLISH
    .string "Dad took me to a great party on\n"
    .string "the S.S. ANNE at VERMILION CITY.$"
    .endif
    .ifdef SPANISH
    .string "¡Mi padre me llevó a una gran\n"
    .string "fiesta en el S.S. ANNE, en\l"
    .string "CIUDAD CARMÍN!$"
    .endif

Route25_Text_DanDefeat::
    .ifdef ENGLISH
    .string "I'm not mad!$"
    .endif
    .ifdef SPANISH
    .string "¡No estoy enfadado!$"
    .endif

Route25_Text_DanPostBattle::
    .ifdef ENGLISH
    .string "On the S.S. ANNE, I saw TRAINERS\n"
    .string "from around the world.$"
    .endif
    .ifdef SPANISH
    .string "En el S.S. ANNE vi a ENTRENADORES\n"
    .string "de todo el mundo.$"
    .endif

Route25_Text_FlintIntro::
    .ifdef ENGLISH
    .string "I'm a cool guy.\n"
    .string "I've got a girlfriend!$"
    .endif
    .ifdef SPANISH
    .string "Soy un buen chico.\n"
    .string "¡Y tengo novia!$"
    .endif

Route25_Text_FlintDefeat::
    .ifdef ENGLISH
    .string "Aww, darn…$"
    .endif
    .ifdef SPANISH
    .string "Vaya...$"
    .endif

Route25_Text_FlintPostBattle::
    .ifdef ENGLISH
    .string "Oh, well.\n"
    .string "My girlfriend will cheer me up.$"
    .endif
    .ifdef SPANISH
    .string "Bueno, mi chica me animará.$"
    .endif

Route25_Text_KelseyIntro::
    .ifdef ENGLISH
    .string "Hi!\n"
    .string "My boyfriend is cool!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola!\n"
    .string "¡Mi chico es genial!$"
    .endif

Route25_Text_KelseyDefeat::
    .ifdef ENGLISH
    .string "My conditioning isn't the best…$"
    .endif
    .ifdef SPANISH
    .string "¡No estaba en muy buena forma!$"
    .endif

Route25_Text_KelseyPostBattle::
    .ifdef ENGLISH
    .string "I wish my boyfriend was as good\n"
    .string "as you.$"
    .endif
    .ifdef SPANISH
    .string "¡Ojalá mi chico fuera tan bueno\n"
    .string "como tú!$"
    .endif

Route25_Text_ChadIntro::
    .ifdef ENGLISH
    .string "I had this feeling…\n"
    .string "I knew I had to battle you!$"
    .endif
    .ifdef SPANISH
    .string "¡Sabía que tendría que luchar\n"
    .string "contigo!$"
    .endif

Route25_Text_ChadDefeat::
    .ifdef ENGLISH
    .string "I knew I'd lose, too!$"
    .endif
    .ifdef SPANISH
    .string "¡Sabía que iba a perder!$"
    .endif

Route25_Text_ChadPostBattle::
    .ifdef ENGLISH
    .string "If your POKéMON gets confused,\n"
    .string "switch it out.\p"
    .string "That's a good tactic.$"
    .endif
    .ifdef SPANISH
    .string "Si tu POKéMON sufre confusión, lo\n"
    .string "mejor es que lo cambies por otro.\p"
    .string "Es la mejor táctica.$"
    .endif

Route25_Text_HaleyIntro::
    .ifdef ENGLISH
    .string "My friend has many cute POKéMON.\n"
    .string "I'm so jealous!$"
    .endif
    .ifdef SPANISH
    .string "Mi amigo tiene unos POKéMON\n"
    .string "muy monos. ¡Qué envidia!$"
    .endif

Route25_Text_HaleyDefeat::
    .ifdef ENGLISH
    .string "I'm not so jealous!$"
    .endif
    .ifdef SPANISH
    .string "¡No estoy enfadada!$"
    .endif

Route25_Text_HaleyPostBattle::
    .ifdef ENGLISH
    .string "You came from MT. MOON?\n"
    .string "May I have a CLEFAIRY?$"
    .endif
    .ifdef SPANISH
    .string "¿Vienes del MT. MOON?\n"
    .string "¿Me das un CLEFAIRY?$"
    .endif

Route25_Text_FranklinIntro::
    .ifdef ENGLISH
    .string "I just got down from MT. MOON,\n"
    .string "but I've still got gas in the tank!$"
    .endif
    .ifdef SPANISH
    .string "¡Acabo de bajar del MT. MOON,\n"
    .string "pero estoy listo!$"
    .endif

Route25_Text_FranklinDefeat::
    .ifdef ENGLISH
    .string "You worked hard!$"
    .endif
    .ifdef SPANISH
    .string "¡Te has esforzado mucho!$"
    .endif

Route25_Text_FranklinPostBattle::
    .ifdef ENGLISH
    .string "Drat!\n"
    .string "A ZUBAT bit me back in that cave.$"
    .endif
    .ifdef SPANISH
    .string "¡Aaaaaaargh!\n"
    .string "Me ha mordido un ZUBAT.$"
    .endif

Route25_Text_NobIntro::
    .ifdef ENGLISH
    .string "I'm off to see a POKéMANIAC's\n"
    .string "collection at the cape.$"
    .endif
    .ifdef SPANISH
    .string "¡Estoy buscando a un coleccionista\n"
    .string "de POKéMON en el cabo!$"
    .endif

Route25_Text_NobDefeat::
    .ifdef ENGLISH
    .string "You done got me, and real good,\n"
    .string "too!$"
    .endif
    .ifdef SPANISH
    .string "¡Me has ganado!$"
    .endif

Route25_Text_NobPostBattle::
    .ifdef ENGLISH
    .string "The POKéMANIAC sure lives up to\n"
    .string "his name.\p"
    .string "His collection includes many rare\n"
    .string "species of POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "El coleccionista tiene muchos\n"
    .string "POKéMON raros.$"
    .endif

Route25_Text_WayneIntro::
    .ifdef ENGLISH
    .string "You're going to see BILL?\n"
    .string "First, we battle!$"
    .endif
    .ifdef SPANISH
    .string "¿Vas a ver a BILL?\n"
    .string "¡Pues luchemos primero!$"
    .endif

Route25_Text_WayneDefeat::
    .ifdef ENGLISH
    .string "You're something.$"
    .endif
    .ifdef SPANISH
    .string "¡Me rindo!$"
    .endif

Route25_Text_WaynePostBattle::
    .ifdef ENGLISH
    .string "The trail below is a shortcut to\n"
    .string "CERULEAN CITY.$"
    .endif
    .ifdef SPANISH
    .string "La ruta de abajo es un atajo\n"
    .string "a CIUDAD CELESTE.$"
    .endif

Route25_Text_SeaCottageSign::
    .ifdef ENGLISH
    .string "SEA COTTAGE\n"
    .string "BILL lives here!$"
    .endif
    .ifdef SPANISH
    .string "LA CASA del MAR\n"
    .string "¡BILL vive aquí!$"
    .endif

Route25_Text_MistyHighHopesAboutThisPlace::
    .ifdef ENGLISH
    .string "This cape is a famous date spot.\p"
    .string "MISTY, the GYM LEADER, has high\n"
    .string "hopes about this place.$"
    .endif
    .ifdef SPANISH
    .string "En este cabo queda mucha gente.\p"
    .string "MISTY, la LÍDER del GIMNASIO,\n"
    .string "suele venir por aquí.$"
    .endif

Route25_Text_AreYouHereAlone::
    .ifdef ENGLISH
    .string "Hello, are you here alone?\p"
    .string "If you're out at CERULEAN's cape…\n"
    .string "Well, it should be as a couple.$"
    .endif
    .ifdef SPANISH
    .string "¿Has venido sin nadie\n"
    .string "que te acompañe?\p"
    .string "Si estás en el cabo de CELESTE,\n"
    .string "¡deberías aprovechar para buscar\l"
    .string "compañía!...$"
    .endif

