ThreeIsland_Port_Text_WereKantoRiderFederation::
    .ifdef ENGLISH
    .string "We're the KANTO RIDER FEDERATION!\n"
    .string "Vroom! Vavavavooom! Vroom!\p"
    .string "My bike's wimpy, so I have to\n"
    .string "make exhaust noises myself!$"
    .endif
    .ifdef SPANISH
    .string "FEDERACIÓN MOTORISTA de KANTO\n"
    .string "¡Rrruuunn! ¡Rrruuun! ¡Rruunnn!\p"
    .string "¡Mi moto no es muy potente,\n"
    .string "por eso hago los ruidos yo mismo!$"
    .endif

ThreeIsland_Port_Text_ForkOverMoney::
    .ifdef ENGLISH
    .string "Hey, hey, lady!\n"
    .string "Fork over some spending money!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, señora! ¡Déjese caer\n"
    .string "y denos algo de pasta!$"
    .endif

ThreeIsland_Port_Text_IllCallThePolice::
    .ifdef ENGLISH
    .string "Aiyeeh!\p"
    .string "Wh-who are you?!\n"
    .string "I… I'll call the police!$"
    .endif
    .ifdef SPANISH
    .string "¡Aaaaaaah!\p"
    .string "Pero ¿qui-qui-quiénes sois?\n"
    .string "Voy a... ¡a llamar a la policía!$"
    .endif

ThreeIsland_Port_Text_ThankGoodnessBikersGone::
    .ifdef ENGLISH
    .string "Those BIKERS…\n"
    .string "Are they gone?\p"
    .string "Oh, thank goodness!\n"
    .string "They certainly had me terrified!$"
    .endif
    .ifdef SPANISH
    .string "¡Dichosos MOTORISTAS!...\n"
    .string "¿Se han marchado ya?\p"
    .string "¡Menos mal!\n"
    .string "¡Me han dado un susto tremendo!$"
    .endif

ThreeIsland_Port_Text_EverythingTurnedOutForBest::
    .ifdef ENGLISH
    .string "Those BIKERS ran off, and\n"
    .string "LOSTELLE was found safe.\p"
    .string "Everything turned out for the best!$"
    .endif
    .ifdef SPANISH
    .string "Bueno, ya no hay problema.\n"
    .string "Los MOTORISTAS se han marchado\p"
    .string "y PEDRITA ha aparecido sana y\n"
    .string "salva, ¡eso es lo importante!$"
    .endif

