ThreeIsland_Port_Text_WereKantoRiderFederation::
    .string "FEDERACIÓN MOTORISTA de KANTO\n"
    .string "¡Rrruuunn! ¡Rrruuun! ¡Rruunnn!\p"
    .string "¡Mi moto no es muy potente,\n"
    .string "por eso hago los ruidos yo mismo!$"

ThreeIsland_Port_Text_ForkOverMoney::
    .string "¡Eh, señora! ¡Déjese caer\n"
    .string "y denos algo de pasta!$"

ThreeIsland_Port_Text_IllCallThePolice::
    .string "¡Aaaaaaah!\p"
    .string "Pero ¿qui-qui-quiénes sois?\n"
    .string "Voy a... ¡a llamar a la policía!$"

ThreeIsland_Port_Text_ThankGoodnessBikersGone::
    .string "¡Dichosos MOTORISTAS!...\n"
    .string "¿Se han marchado ya?\p"
    .string "¡Menos mal!\n"
    .string "¡Me han dado un susto tremendo!$"

ThreeIsland_Port_Text_EverythingTurnedOutForBest::
    .string "Bueno, ya no hay problema.\n"
    .string "Los MOTORISTAS se han marchado\p"
    .string "y PEDRITA ha aparecido sana y\n"
    .string "salva, ¡eso es lo importante!$"
