PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{RIVAL}: ¡Hola, {PLAYER}!\n"
    .string "¡El abuelo no está!$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{RIVAL}: ¡Abuelo!\n"
    .string "¡Estoy harto de esperar!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{RIVAL}: ¡Oye abuelo!\n"
    .string "¿Y yo qué?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{RIVAL}: ¡Yo no soy tan egoísta\n"
    .string "como tú!\p"
    .string "¡Venga, elige uno, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{RIVAL}: ¡Pues éste para mí!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "¡{RIVAL} recibió el {STR_VAR_1}\n"
    .string "de manos del PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{RIVAL}: Mi POKéMON parece mucho\n"
    .string "más fuerte.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{RIVAL}: ¡Espera, {PLAYER}!\n"
    .string "¡Probemos a nuestros POKéMON!\p"
    .string "¡Adelante, luchemos!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "¿QUÉ?\n"
    .string "¡Increíble!\l"
    .string "¡Tu POKéMON es mejor que el mío!$"

@ Also used for early Route 22 battle
Text_RivalVictory::
    .string "{RIVAL}: ¡Bien!\n"
    .string "¿No soy el mejor?$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{RIVAL}: ¡Vale! ¡Haré luchar a mi\n"
    .string "POKéMON para fortalecerlo!\p"
    .string "¡{PLAYER}! ¡Abuelo!\n"
    .string "¡Hasta luego!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: ¡Abuelo!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: ¿Qué quieres de mí?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: ¡No te preocupes,\n"
    .string "abuelo!\l"
    .string "¡Déjalo en mis manos!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "¡{PLAYER}, que quede claro que no\n"
    .string "te necesito!\p"
    .string "¡Le pediré a mi hermana su MAPA!\p"
    .string "¡Y le diré que no te dé ninguno\n"
    .string "a ti! ¡Ja, ja, ja!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "OAK: ¿{RIVAL}?\n"
    .string "Déjame pensar...\p"
    .string "¡Ah, sí! Te pedí que vinieras.\n"
    .string "Espera...\p"
    .string "¡{PLAYER}, toma!\p"
    .string "¡Aquí hay tres POKéMON!\p"
    .string "¡Bien!\p"
    .string "¡Están dentro de las POKé BALLS!\p"
    .string "¡Cuando yo era joven, era un\n"
    .string "buen ENTRENADOR de POKéMON!\p"
    .string "Pero ahora sólo me quedan tres.\n"
    .string "Te daré uno. ¿Cuál quieres?$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "OAK: ¡Tranquilo, {RIVAL}!\n"
    .string "¡Te daré otro a ti!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "OAK: A ver, {PLAYER}.\p"
    .string "Esas tres POKé BALLS contienen\n"
    .string "un POKéMON cada una.\p"
    .string "¿Cuál quieres para ti?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "OAK: ¡Oye!\n"
    .string "¡No te vayas aún!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "¡Así que CHARMANDER!\n"
    .string "Pues ten paciencia con él.\p"
    .string "Bueno, {PLAYER}, entonces ¿quieres\n"
    .string "el POKéMON tipo FUEGO CHARMANDER?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "¡Así que SQUIRTLE!\n"
    .string "Merece la pena, sí, sí.\p"
    .string "Bueno, {PLAYER}, entonces ¿quieres\n"
    .string "el POKéMON tipo AGUA SQUIRTLE?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "¡Así que BULBASAUR!\n"
    .string "Resulta muy fácil criarlo.\p"
    .string "Bueno, {PLAYER}, entonces ¿quieres\n"
    .string "el POKéMON tipo PLANTA BULBASAUR?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "¡Ese POKéMON tiene mucha energía!$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "¡{PLAYER} recibió el {STR_VAR_1}\n"
    .string "de manos del PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "OAK: ¡Si aparece un POKéMON\n"
    .string "salvaje, tu POKéMON podrá luchar\l"
    .string "contra él!\p"
    .string "Junto a él, no te será difícil\n"
    .string "llegar a la siguiente ciudad.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "OAK: ¡{PLAYER}, entrena a tu joven\n"
    .string "POKéMON luchando!$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "OAK: ¡{PLAYER}!\n"
    .string "¿Cómo va tu POKéMON?\p"
    .string "¡Creo que te quiere mucho!\p"
    .string "¡Pareces ser muy hábil\n"
    .string "entrenando POKéMON!\p"
    .string "¿Qué? ¿Tienes algo para mí?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} entregó el CORREO de OAK.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "¡Ah, sí! ¡Es la POKé BALL que\n"
    .string "había encargado! ¡Gracias!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "OAK: ¡Ah, sí!\n"
    .string "Quería pediros un favor.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "¡En la mesa hay un invento mío,\n"
    .string "la POKéDEX!\p"
    .string "¡Registra automáticamente datos\n"
    .string "sobre los POKéMON que vayáis\l"
    .string "viendo o capturando!\p"
    .string "¡Es una tecno-enciclopedia!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "OAK: ¡{PLAYER} y {RIVAL}!\n"
    .string "¡Tomad las POKéDEX!$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "¡{PLAYER} obtuvo una POKéDEX\n"
    .string "de manos del PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "OAK: ¡No se aprenden cosas sobre\n"
    .string "los POKéMON con sólo verlos!\p"
    .string "¡Hay que atraparlos!\p"
    .string "Esto es lo que hace falta\n"
    .string "para atraparlos...$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "¡{PLAYER} obtuvo 5 POKé BALLS!$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "Cuando aparezca un POKéMON\n"
    .string "salvaje, lo suyo es luchar\l"
    .string "contra él.\p"
    .string "¡Hay que lanzarle una POKé BALL\n"
    .string "para capturarlo!\p"
    .string "¡Pero esto no siempre funciona!\p"
    .string "¡Un POKéMON sano podría huir!\n"
    .string "¡También cuenta la suerte!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "Quería hacer una guía de todos\n"
    .string "los POKéMON del mundo...\p"
    .string "¡Era mi sueño!\p"
    .string "¡Pero ya soy muy viejo y no puedo\n"
    .string "hacerlo!\p"
    .string "¡Por eso quiero que vosotros\n"
    .string "hagáis realidad ese sueño!\p"
    .string "¡Adelante, id en su busca!\p"
    .string "¡Será una gran proeza en la\n"
    .string "historia de los POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "¡{PLAYER}, los POKéMON del mundo\n"
    .string "te esperan!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "¡Hola, {PLAYER}!\n"
    .string "¿Qué tal llevas la POKéDEX?\p"
    .string "{RIVAL} ya ha atrapado algunos\n"
    .string "POKéMON y ha añadido sus datos.\p"
    .string "Venga, {PLAYER}, deja que vea tu\n"
    .string "POKéDEX.\p"
    .string "¡Pero bueno!... ¿Qué pasa?\n"
    .string "¡Pero si no hay datos!\p"
    .string "Toma, anda, pon un poco\n"
    .string "de tu parte.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "OAK: Ven a verme de vez en\n"
    .string "cuando.\p"
    .string "¡Mantenme informado sobre cómo\n"
    .string "te va con tu POKéDEX!$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "¡Es como una enciclopedia, pero\n"
    .string "las páginas están en blanco!$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "¡Eso de ahí son las POKé BALLS!\n"
    .string "¡Dentro de ellas hay POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "¡Ése es el último POKéMON del\n"
    .string "PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "¡Pulsa START para abrir el menú!$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "En la pantalla del menú está\n"
    .string "la opción GUARDAR.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "Todo POKéMON tiene sus puntos\n"
    .string "débiles y fuertes frente al resto.$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "¡Hay un correo electrónico!\p"
    .string "...\p"
    .string "¡Aviso a todos los ENTRENADORES\n"
    .string "de POKéMON!\p"
    .string "¡Los ENTRENADORES de élite de la\n"
    .string "LIGA POKéMON están listos para\l"
    .string "desafiaros a todos!\p"
    .string "¡Traed a vuestros mejores POKéMON\n"
    .string "para ver lo buenos que sois!\p"
    .string "CG de la LIGA POKéMON, MESETA\n"
    .string "AÑIL\p"
    .string "PD: ¡PROF. OAK, visítenos por\n"
    .string "favor!...$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "Estudio a los POKéMON.\n"
    .string "¡Soy ayudante del PROF. OAK!$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "Hola, {PLAYER}. Seguro que has\n"
    .string "hecho buenas migas con tus\l"
    .string "POKéMON.\p"
    .string "A todo esto, ¿conoces a DALIA?\p"
    .string "Si le enseñas a DALIA tus POKéMON,\n"
    .string "sabrá decirte si les gustas o no.\p"
    .string "Y puede que les dé un lavado de\n"
    .string "cara para que estén presentables.\l"
    .string "Pero no vayas diciéndolo por ahí.$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "El PROF. OAK va a tener pronto\n"
    .string "su propio programa de radio.\p"
    .string "Será el SEMINARIO sobre POKéMON\n"
    .string "del PROF. OAK.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "¡El PROF. OAK es un experto\n"
    .string "en POKéMON!\p"
    .string "¡Es admirado por muchos de los\n"
    .string "ENTRENADORES POKéMON!$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "¡Ah, una cosa importante!\n"
    .string "{PLAYER}, tengo que pedirte otro\l"
    .string "gran favor.\p"
    .string "Necesito que prestes atención.$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "Hace poco, se han visto especies\n"
    .string "de POKéMON raros.\p"
    .string "Es decir, POKéMON que jamás\n"
    .string "se han visto en KANTO.\p"
    .string "Me encantaría comprobarlo con mis\n"
    .string "propios ojos, pero ya soy mayor.\p"
    .string "Ya que yo no puedo, ¿podrías ir tú\n"
    .string "en mi lugar, {PLAYER}?$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: ¡Eh, lo he oído todo!\p"
    .string "¡Ya está bien de favoritismos!\n"
    .string "¡Prefieres a {PLAYER} antes que\l"
    .string "a mí, abuelo!\p"
    .string "¡Yo he atrapado más POKéMON,\n"
    .string "y en menos tiempo!\p"
    .string "¡Deberías dejar que yo me ocupe\n"
    .string "de todo!$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "OAK: No, hombre, no te pongas así.\n"
    .string "Tú también me ayudas mucho, majo.\p"
    .string "A ver, enseñadme vuestras\n"
    .string "POKéDEX.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "PROF. OAK tomó las dos POKéDEX.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "... ... ... ... ... ...\p"
    .string "... ... ... ... ... ...\p"
    .string "...¡Listo!\p"
    .string "Ahora podrán guardar datos\n"
    .string "de muchos más POKéMON.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "¡La POKéDEX de {PLAYER} tiene\n"
    .string "ahora más capacidad!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "Bueno, {PLAYER} y {RIVAL},\n"
    .string "ya está.\p"
    .string "Ahora tenéis que trabajar mucho\n"
    .string "y completar las POKéDEX.\p"
    .string "¡Serán las mejores y las más\n"
    .string "completas de todos los tiempos!\p"
    .string "¡Vamos a dar un paso de gigante\n"
    .string "en la historia de los POKéMON!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: Tranqui, abuelo, que te\n"
    .string "va a dar algo...\p"
    .string "Yo completaré mi POKéDEX,\n"
    .string "no te preocupes.\p"
    .string "Creo que iré a ISLA PRIMA,\n"
    .string "en primer lugar.\p"
    .string "Bueno, me piro, vampiro.$"
