PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .ifdef ENGLISH
    .string "{RIVAL}: What, it's only {PLAYER}?\n"
    .string "Gramps isn't around.$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Hola, {PLAYER}!\n"
    .string "¡El abuelo no está!$"
    .endif

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .ifdef ENGLISH
    .string "{RIVAL}: Gramps!\n"
    .string "I'm fed up with waiting!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Abuelo!\n"
    .string "¡Estoy harto de esperar!$"
    .endif

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .ifdef ENGLISH
    .string "{RIVAL}: Hey! Gramps! No fair!\n"
    .string "What about me?$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Oye abuelo!\n"
    .string "¿Y yo qué?$"
    .endif

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .ifdef ENGLISH
    .string "{RIVAL}: Heh, I don't need to be\n"
    .string "greedy like you. I'm mature!\p"
    .string "Go ahead and choose, {PLAYER}!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Yo no soy tan egoísta\n"
    .string "como tú!\p"
    .string "¡Venga, elige uno, {PLAYER}!$"
    .endif

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .ifdef ENGLISH
    .string "{RIVAL}: I'll take this one, then!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Pues éste para mí!$"
    .endif

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .ifdef ENGLISH
    .string "{RIVAL} received the {STR_VAR_1}\n"
    .string "from PROF. OAK!$"
    .endif
    .ifdef SPANISH
    .string "¡{RIVAL} recibió el {STR_VAR_1}\n"
    .string "de manos del PROF. OAK!$"
    .endif

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .ifdef ENGLISH
    .string "{RIVAL}: My POKéMON looks a lot\n"
    .string "tougher than yours.$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: Mi POKéMON parece mucho\n"
    .string "más fuerte.$"
    .endif

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .ifdef ENGLISH
    .string "{RIVAL}: Wait, {PLAYER}!\n"
    .string "Let's check out our POKéMON!\p"
    .string "Come on, I'll take you on!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Espera, {PLAYER}!\n"
    .string "¡Probemos a nuestros POKéMON!\p"
    .string "¡Adelante, luchemos!$"
    .endif

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .ifdef ENGLISH
    .string "WHAT?\n"
    .string "Unbelievable!\l"
    .string "I picked the wrong POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¿QUÉ?\n"
    .string "¡Increíble!\l"
    .string "¡Tu POKéMON es mejor que el mío!$"
    .endif

@ Also used for early Route 22 battle
Text_RivalVictory::
    .ifdef ENGLISH
    .string "{RIVAL}: Yeah!\n"
    .string "Am I great or what?$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Bien!\n"
    .string "¿No soy el mejor?$"
    .endif

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .ifdef ENGLISH
    .string "{RIVAL}: Okay! I'll make my\n"
    .string "POKéMON battle to toughen it up!\p"
    .string "{PLAYER}! Gramps!\n"
    .string "Smell you later!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Vale! ¡Haré luchar a mi\n"
    .string "POKéMON para fortalecerlo!\p"
    .string "¡{PLAYER}! ¡Abuelo!\n"
    .string "¡Hasta luego!$"
    .endif

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .ifdef ENGLISH
    .string "{RIVAL}: Gramps!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Abuelo!$"
    .endif

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .ifdef ENGLISH
    .string "{RIVAL}: I almost forgot!\n"
    .string "What did you call me for?$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¿Qué quieres de mí?$"
    .endif

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .ifdef ENGLISH
    .string "{RIVAL}: All right, Gramps!\n"
    .string "Leave it all to me!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡No te preocupes,\n"
    .string "abuelo!\l"
    .string "¡Déjalo en mis manos!$"
    .endif

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .ifdef ENGLISH
    .string "{PLAYER}, I hate to say it, but you\n"
    .string "won't be necessary for this.\p"
    .string "I know! I'll borrow a TOWN MAP\n"
    .string "from my sis!\p"
    .string "I'll tell her not to lend you one,\n"
    .string "{PLAYER}! Hahaha!\p"
    .string "Don't bother coming around to\n"
    .string "my place after this!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER}, que quede claro que no\n"
    .string "te necesito!\p"
    .string "¡Le pediré a mi hermana su MAPA!\p"
    .string "¡Y le diré que no te dé ninguno\n"
    .string "a ti! ¡Ja, ja, ja!$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .ifdef ENGLISH
    .string "OAK: {RIVAL}?\n"
    .string "Let me think…\p"
    .string "Oh, that's right, I told you to\n"
    .string "come! Just wait!\p"
    .string "Here, {PLAYER}.\p"
    .string "There are three POKéMON here.\p"
    .string "Haha!\p"
    .string "The POKéMON are held inside\n"
    .string "these POKé BALLS.\p"
    .string "When I was young, I was a serious\n"
    .string "POKéMON TRAINER.\p"
    .string "But now, in my old age, I have\n"
    .string "only these three left.\p"
    .string "You can have one.\n"
    .string "Go on, choose!$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¿{RIVAL}?\n"
    .string "Déjame pensar...\p"
    .string "¡Ah, sí! Te pedí que vinieras.\n"
    .string "Espera...\p"
    .string "¡{PLAYER}, toma!\p"
    .string "¡Aquí hay tres POKéMON!\p"
    .string "¡Bien!\p"
    .string "¡Están dentro de las POKé BALLS!\p"
    .string "¡Cuando yo era joven, era un\n"
    .string "buen ENTRENADOR de POKéMON!\p"
    .string "Pero ahora sólo me quedan tres.\n"
    .string "Te daré uno. ¿Cuál quieres?$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .ifdef ENGLISH
    .string "OAK: Be patient, {RIVAL}.\n"
    .string "You can have one, too!$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡Tranquilo, {RIVAL}!\n"
    .string "¡Te daré otro a ti!$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .ifdef ENGLISH
    .string "OAK: Now, {PLAYER}.\p"
    .string "Inside those three POKé BALLS are\n"
    .string "POKéMON.\p"
    .string "Which one will you choose for\n"
    .string "yourself?$"
    .endif
    .ifdef SPANISH
    .string "OAK: A ver, {PLAYER}.\p"
    .string "Esas tres POKé BALLS contienen\n"
    .string "un POKéMON cada una.\p"
    .string "¿Cuál quieres para ti?$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .ifdef ENGLISH
    .string "OAK: Hey!\n"
    .string "Don't go away yet!$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡Oye!\n"
    .string "¡No te vayas aún!$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .ifdef ENGLISH
    .string "Ah! CHARMANDER is your choice.\n"
    .string "You should raise it patiently.\p"
    .string "So, {PLAYER}, you're claiming the\n"
    .string "FIRE POKéMON CHARMANDER?$"
    .endif
    .ifdef SPANISH
    .string "¡Así que CHARMANDER!\n"
    .string "Pues ten paciencia con él.\p"
    .string "Bueno, {PLAYER}, entonces ¿quieres\n"
    .string "el POKéMON tipo FUEGO CHARMANDER?$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .ifdef ENGLISH
    .string "Hm! SQUIRTLE is your choice.\n"
    .string "It's one worth raising.\p"
    .string "So, {PLAYER}, you've decided on the\n"
    .string "WATER POKéMON SQUIRTLE?$"
    .endif
    .ifdef SPANISH
    .string "¡Así que SQUIRTLE!\n"
    .string "Merece la pena, sí, sí.\p"
    .string "Bueno, {PLAYER}, entonces ¿quieres\n"
    .string "el POKéMON tipo AGUA SQUIRTLE?$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .ifdef ENGLISH
    .string "I see! BULBASAUR is your choice.\n"
    .string "It's very easy to raise.\p"
    .string "So, {PLAYER}, you want to go with\n"
    .string "the GRASS POKéMON BULBASAUR?$"
    .endif
    .ifdef SPANISH
    .string "¡Así que BULBASAUR!\n"
    .string "Resulta muy fácil criarlo.\p"
    .string "Bueno, {PLAYER}, entonces ¿quieres\n"
    .string "el POKéMON tipo PLANTA BULBASAUR?$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .ifdef ENGLISH
    .string "This POKéMON is really quite\n"
    .string "energetic!$"
    .endif
    .ifdef SPANISH
    .string "¡Ese POKéMON tiene mucha energía!$"
    .endif

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .ifdef ENGLISH
    .string "{PLAYER} received the {STR_VAR_1}\n"
    .string "from PROF. OAK!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió el {STR_VAR_1}\n"
    .string "de manos del PROF. OAK!$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .ifdef ENGLISH
    .string "OAK: If a wild POKéMON appears,\n"
    .string "your POKéMON can battle it.\p"
    .string "With it at your side, you should be\n"
    .string "able to reach the next town.$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡Si aparece un POKéMON\n"
    .string "salvaje, tu POKéMON podrá luchar\l"
    .string "contra él!\p"
    .string "Junto a él, no te será difícil\n"
    .string "llegar a la siguiente ciudad.$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .ifdef ENGLISH
    .string "OAK: {PLAYER}, raise your young\n"
    .string "POKéMON by making it battle.\p"
    .string "It has to battle for it to grow.$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡{PLAYER}, entrena a tu joven\n"
    .string "POKéMON luchando!$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .ifdef ENGLISH
    .string "OAK: Oh, {PLAYER}!\n"
    .string "How is my old POKéMON?\p"
    .string "Well, it seems to be growing more\n"
    .string "attached to you.\p"
    .string "You must be talented as a POKéMON\n"
    .string "TRAINER.\p"
    .string "What's that?\n"
    .string "You have something for me?$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡{PLAYER}!\n"
    .string "¿Cómo va tu POKéMON?\p"
    .string "¡Creo que te quiere mucho!\p"
    .string "¡Pareces ser muy hábil\n"
    .string "entrenando POKéMON!\p"
    .string "¿Qué? ¿Tienes algo para mí?$"
    .endif

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .ifdef ENGLISH
    .string "{PLAYER} delivered OAK'S PARCEL.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} entregó el CORREO de OAK.$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .ifdef ENGLISH
    .string "Ah! \n"
    .string "It's the custom POKé BALL!\p"
    .string "I had it on order.\n"
    .string "Thank you!$"
    .endif
    .ifdef SPANISH
    .string "¡Ah, sí! ¡Es la POKé BALL que\n"
    .string "había encargado! ¡Gracias!$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .ifdef ENGLISH
    .string "OAK: Oh, right!\n"
    .string "I have a request for you two.$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡Ah, sí!\n"
    .string "Quería pediros un favor.$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .ifdef ENGLISH
    .string "On the desk there is my invention,\n"
    .string "the POKéDEX!\p"
    .string "It automatically records data on\n"
    .string "POKéMON you've seen or caught.\p"
    .string "It's a high-tech encyclopedia!$"
    .endif
    .ifdef SPANISH
    .string "¡En la mesa hay un invento mío,\n"
    .string "la POKéDEX!\p"
    .string "¡Registra automáticamente datos\n"
    .string "sobre los POKéMON que vayáis\l"
    .string "viendo o capturando!\p"
    .string "¡Es una tecno-enciclopedia!$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .ifdef ENGLISH
    .string "OAK: {PLAYER} and {RIVAL}.\n"
    .string "Take these with you.$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡{PLAYER} y {RIVAL}!\n"
    .string "¡Tomad las POKéDEX!$"
    .endif

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .ifdef ENGLISH
    .string "{PLAYER} received the POKéDEX\n"
    .string "from PROF. OAK.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo una POKéDEX\n"
    .string "de manos del PROF. OAK!$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .ifdef ENGLISH
    .string "OAK: You can't get detailed data\n"
    .string "on POKéMON by just seeing them.\p"
    .string "You must catch them to obtain\n"
    .string "complete data.\p"
    .string "So, here are some tools for\n"
    .string "catching wild POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡No se aprenden cosas sobre\n"
    .string "los POKéMON con sólo verlos!\p"
    .string "¡Hay que atraparlos!\p"
    .string "Esto es lo que hace falta\n"
    .string "para atraparlos...$"
    .endif

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .ifdef ENGLISH
    .string "{PLAYER} received five POKé BALLS.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo 5 POKé BALLS!$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .ifdef ENGLISH
    .string "When a wild POKéMON appears,\n"
    .string "it's fair game.\p"
    .string "Just throw a POKé BALL at it and\n"
    .string "try to catch it!\p"
    .string "This won't always work, however.\p"
    .string "A healthy POKéMON can escape.\n"
    .string "You have to be lucky!$"
    .endif
    .ifdef SPANISH
    .string "Cuando aparezca un POKéMON\n"
    .string "salvaje, lo suyo es luchar\l"
    .string "contra él.\p"
    .string "¡Hay que lanzarle una POKé BALL\n"
    .string "para capturarlo!\p"
    .string "¡Pero esto no siempre funciona!\p"
    .string "¡Un POKéMON sano podría huir!\n"
    .string "¡También cuenta la suerte!$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .ifdef ENGLISH
    .string "To make a complete guide on all\n"
    .string "the POKéMON in the world…\p"
    .string "That was my dream!\p"
    .string "But, I'm too old.\n"
    .string "I can't get the job done.\p"
    .string "So, I want you two to fulfill my\n"
    .string "dream for me.\p"
    .string "Get moving, you two.\p"
    .string "This is a great undertaking in\n"
    .string "POKéMON history!$"
    .endif
    .ifdef SPANISH
    .string "Quería hacer una guía de todos\n"
    .string "los POKéMON del mundo...\p"
    .string "¡Era mi sueño!\p"
    .string "¡Pero ya soy muy viejo y no puedo\n"
    .string "hacerlo!\p"
    .string "¡Por eso quiero que vosotros\n"
    .string "hagáis realidad ese sueño!\p"
    .string "¡Adelante, id en su busca!\p"
    .string "¡Será una gran proeza en la\n"
    .string "historia de los POKéMON!$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .ifdef ENGLISH
    .string "POKéMON around the world wait for\n"
    .string "you, {PLAYER}!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER}, los POKéMON del mundo\n"
    .string "te esperan!$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .ifdef ENGLISH
    .string "Ah, {PLAYER}!\n"
    .string "How is your POKéDEX shaping up?\p"
    .string "{RIVAL} has already caught some\n"
    .string "POKéMON and added to the data.\p"
    .string "So, {PLAYER}, let's have a look at\n"
    .string "your POKéDEX.\p"
    .string "…What's the matter?\n"
    .string "You've added no new data at all.\p"
    .string "I'll give you these, so do try a\n"
    .string "little harder.$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, {PLAYER}!\n"
    .string "¿Qué tal llevas la POKéDEX?\p"
    .string "{RIVAL} ya ha atrapado algunos\n"
    .string "POKéMON y ha añadido sus datos.\p"
    .string "Venga, {PLAYER}, deja que vea tu\n"
    .string "POKéDEX.\p"
    .string "¡Pero bueno!... ¿Qué pasa?\n"
    .string "¡Pero si no hay datos!\p"
    .string "Toma, anda, pon un poco\n"
    .string "de tu parte.$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .ifdef ENGLISH
    .string "OAK: Come see me sometime.\p"
    .string "After all, I want to know how your\n"
    .string "POKéDEX is coming along.$"
    .endif
    .ifdef SPANISH
    .string "OAK: Ven a verme de vez en\n"
    .string "cuando.\p"
    .string "¡Mantenme informado sobre cómo\n"
    .string "te va con tu POKéDEX!$"
    .endif

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .ifdef ENGLISH
    .string "It's like an encyclopedia, but the\n"
    .string "pages are blank.$"
    .endif
    .ifdef SPANISH
    .string "¡Es como una enciclopedia, pero\n"
    .string "las páginas están en blanco!$"
    .endif

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .ifdef ENGLISH
    .string "Those are POKé BALLS.\n"
    .string "They contain POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Eso de ahí son las POKé BALLS!\n"
    .string "¡Dentro de ellas hay POKéMON!$"
    .endif

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .ifdef ENGLISH
    .string "That's PROF. OAK's last POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Ése es el último POKéMON del\n"
    .string "PROF. OAK!$"
    .endif

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .ifdef ENGLISH
    .string "Press START to open the MENU!$"
    .endif
    .ifdef SPANISH
    .string "¡Pulsa START para abrir el menú!$"
    .endif

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .ifdef ENGLISH
    .string "The SAVE option is on the MENU.\n"
    .string "Use it regularly.$"
    .endif
    .ifdef SPANISH
    .string "En la pantalla del menú está\n"
    .string "la opción GUARDAR.$"
    .endif

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .ifdef ENGLISH
    .string "All POKéMON types have strong and\n"
    .string "weak points against others.$"
    .endif
    .ifdef SPANISH
    .string "Todo POKéMON tiene sus puntos\n"
    .string "débiles y fuertes frente al resto.$"
    .endif

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .ifdef ENGLISH
    .string "There's an e-mail message here.\p"
    .string "…\p"
    .string "Finally!\n"
    .string "The ultimate TRAINERS of the\l"
    .string "POKéMON LEAGUE are ready to\l"
    .string "take on all comers!\p"
    .string "Bring your best POKéMON and see\n"
    .string "how you rate as a TRAINER!\p"
    .string "POKéMON LEAGUE HQ\n"
    .string "INDIGO PLATEAU\p"
    .string "PROF. OAK, please visit us!\n"
    .string "…$"
    .endif
    .ifdef SPANISH
    .string "¡Hay un correo electrónico!\p"
    .string "...\p"
    .string "¡Aviso a todos los ENTRENADORES\n"
    .string "de POKéMON!\p"
    .string "¡Los ENTRENADORES de élite de la\n"
    .string "LIGA POKéMON están listos para\l"
    .string "desafiaros a todos!\p"
    .string "¡Traed a vuestros mejores POKéMON\n"
    .string "para ver lo buenos que sois!\p"
    .string "CG de la LIGA POKéMON, MESETA\n"
    .string "AÑIL\p"
    .string "PD: ¡PROF. OAK, visítenos por\n"
    .string "favor!...$"
    .endif

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .ifdef ENGLISH
    .string "I study POKéMON as PROF. OAK's\n"
    .string "AIDE.$"
    .endif
    .ifdef SPANISH
    .string "Estudio a los POKéMON.\n"
    .string "¡Soy ayudante del PROF. OAK!$"
    .endif

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .ifdef ENGLISH
    .string "Hi, {PLAYER}. I bet you've become\n"
    .string "good friends with your POKéMON.\p"
    .string "By the way, did you know about\n"
    .string "DAISY?\p"
    .string "If you show DAISY your POKéMON,\n"
    .string "she can tell how much it likes you.\p"
    .string "Occasionally, she will even groom\n"
    .string "a POKéMON for you.\p"
    .string "This is a secret, so please don't\n"
    .string "tell anyone.$"
    .endif
    .ifdef SPANISH
    .string "Hola, {PLAYER}. Seguro que has\n"
    .string "hecho buenas migas con tus\l"
    .string "POKéMON.\p"
    .string "A todo esto, ¿conoces a DALIA?\p"
    .string "Si le enseñas a DALIA tus POKéMON,\n"
    .string "sabrá decirte si les gustas o no.\p"
    .string "Y puede que les dé un lavado de\n"
    .string "cara para que estén presentables.\l"
    .string "Pero no vayas diciéndolo por ahí.$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .ifdef ENGLISH
    .string "PROF. OAK is going to have his own\n"
    .string "radio show soon.\p"
    .string "The program will be called PROF.\n"
    .string "OAK's POKéMON SEMINAR.$"
    .endif
    .ifdef SPANISH
    .string "El PROF. OAK va a tener pronto\n"
    .string "su propio programa de radio.\p"
    .string "Será el SEMINARIO sobre POKéMON\n"
    .string "del PROF. OAK.$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .ifdef ENGLISH
    .string "PROF. OAK may not look like much,\n"
    .string "but he's the authority on POKéMON.\p"
    .string "Many POKéMON TRAINERS hold him in\n"
    .string "high regard.$"
    .endif
    .ifdef SPANISH
    .string "¡El PROF. OAK es un experto\n"
    .string "en POKéMON!\p"
    .string "¡Es admirado por muchos de los\n"
    .string "ENTRENADORES POKéMON!$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .ifdef ENGLISH
    .string "Ah, now this is excellent!\p"
    .string "{PLAYER}, I have another important\n"
    .string "favor to ask of you.\p"
    .string "I need you to listen closely.$"
    .endif
    .ifdef SPANISH
    .string "¡Ah, una cosa importante!\n"
    .string "{PLAYER}, tengo que pedirte otro\l"
    .string "gran favor.\p"
    .string "Necesito que prestes atención.$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .ifdef ENGLISH
    .string "Recently, there have been sightings\n"
    .string "of many rare POKéMON species.\p"
    .string "I'm talking about POKéMON that\n"
    .string "have never been seen in KANTO.\p"
    .string "I would love to go see things for\n"
    .string "myself, but I'm much too old.\p"
    .string "Since I can't do it, {PLAYER}, I'd\n"
    .string "like you to go in my place.$"
    .endif
    .ifdef SPANISH
    .string "Hace poco, se han visto especies\n"
    .string "de POKéMON raros.\p"
    .string "Es decir, POKéMON que jamás\n"
    .string "se han visto en KANTO.\p"
    .string "Me encantaría comprobarlo con mis\n"
    .string "propios ojos, pero ya soy mayor.\p"
    .string "Ya que yo no puedo, ¿podrías ir tú\n"
    .string "en mi lugar, {PLAYER}?$"
    .endif

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .ifdef ENGLISH
    .string "{RIVAL}: Hey, I heard that!\p"
    .string "Gramps, what's with favoring\n"
    .string "{PLAYER} over me all the time?\p"
    .string "I went and collected more POKéMON,\n"
    .string "and faster, too.\p"
    .string "You should just let me handle\n"
    .string "everything.$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Eh, lo he oído todo!\p"
    .string "¡Ya está bien de favoritismos!\n"
    .string "¡Prefieres a {PLAYER} antes que\l"
    .string "a mí, abuelo!\p"
    .string "¡Yo he atrapado más POKéMON,\n"
    .string "y en menos tiempo!\p"
    .string "¡Deberías dejar que yo me ocupe\n"
    .string "de todo!$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .ifdef ENGLISH
    .string "OAK: I know, I know.\n"
    .string "Of course I need your help, too.\p"
    .string "Now, I need to see both your\n"
    .string "POKéDEXES.$"
    .endif
    .ifdef SPANISH
    .string "OAK: No, hombre, no te pongas así.\n"
    .string "Tú también me ayudas mucho, majo.\p"
    .string "A ver, enseñadme vuestras\n"
    .string "POKéDEX.$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .ifdef ENGLISH
    .string "PROF. OAK took both POKéDEX\n"
    .string "units.$"
    .endif
    .ifdef SPANISH
    .string "PROF. OAK tomó las dos POKéDEX.$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .ifdef ENGLISH
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "…And that's done!\p"
    .string "Now these units can record data on\n"
    .string "a lot more POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "... ... ... ... ... ...\p"
    .string "... ... ... ... ... ...\p"
    .string "...¡Listo!\p"
    .string "Ahora podrán guardar datos\n"
    .string "de muchos más POKéMON.$"
    .endif

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .ifdef ENGLISH
    .string "{PLAYER}'s POKéDEX was upgraded!$"
    .endif
    .ifdef SPANISH
    .string "¡La POKéDEX de {PLAYER} tiene\n"
    .string "ahora más capacidad!$"
    .endif

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .ifdef ENGLISH
    .string "Now, {PLAYER} and {RIVAL}!\p"
    .string "This time, you really must work\n"
    .string "towards filling your POKéDEXES.\p"
    .string "I urge you to make them the best\n"
    .string "and the most complete of all time!\p"
    .string "Truly, this is a monumentally great\n"
    .string "undertaking in POKéMON history!$"
    .endif
    .ifdef SPANISH
    .string "Bueno, {PLAYER} y {RIVAL},\n"
    .string "ya está.\p"
    .string "Ahora tenéis que trabajar mucho\n"
    .string "y completar las POKéDEX.\p"
    .string "¡Serán las mejores y las más\n"
    .string "completas de todos los tiempos!\p"
    .string "¡Vamos a dar un paso de gigante\n"
    .string "en la historia de los POKéMON!$"
    .endif

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .ifdef ENGLISH
    .string "{RIVAL}: Gramps, calm down.\n"
    .string "Don't get so excited.\p"
    .string "I'll get the POKéDEX completed,\n"
    .string "don't you worry about a thing.\p"
    .string "I think I'll try looking around\n"
    .string "ONE ISLAND first…\p"
    .string "Anyways, I'm outta here!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: Tranqui, abuelo, que te\n"
    .string "va a dar algo...\p"
    .string "Yo completaré mi POKéDEX,\n"
    .string "no te preocupes.\p"
    .string "Creo que iré a ISLA PRIMA,\n"
    .string "en primer lugar.\p"
    .string "Bueno, me piro, vampiro.$"
    .endif

