FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland::
    .ifdef ENGLISH
    .string "We've had a great and powerful\n"
    .string "TRAINER grow up on this island.\p"
    .string "I bet even you'd know her.\n"
    .string "It's LORELEI of the ELITE FOUR!\p"
    .string "When LORELEI was just a tyke,\n"
    .string "I taught her about POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "En esta isla nació y creció una\n"
    .string "ENTRENADORA fuerte y poderosa\l"
    .string "como pocas.\p"
    .string "Seguro que la conoces, se llama\n"
    .string "LORELEI y es del ALTO MANDO.\p"
    .string "Yo le enseñé muchas cosas sobre\n"
    .string "los POKéMON cuando aún era un\l"
    .string "comino.$"
    .endif

FourIsland_Mart_Text_IcefallCaveIsFrigid::
    .ifdef ENGLISH
    .string "The SEVII ISLANDS are in a warm\n"
    .string "region overall.\p"
    .string "But there is one exception you\n"
    .string "need to know about.\p"
    .string "The ICEFALL CAVE is frigid because\n"
    .string "of the POKéMON that live in it.$"
    .endif
    .ifdef SPANISH
    .string "En realidad, ARCHI7 está\n"
    .string "en una zona cálida.\p"
    .string "Pero hay una excepción de la que\n"
    .string "quiero hablarte.\p"
    .string "La CUEVA GLACIADA es un lugar\n"
    .string "frío por el POKéMON que la habita.$"
    .endif

