@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull::
    .string "{PLAYER}{KUN}の　バッグ\n"
    .string "いっぱい　みたい　だね$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
    .ifdef ENGLISH
    .string "Don't you think it's hard to think\n"
    .string "up good names for POKéMON?\p"
    .string "Especially if you've caught a\n"
    .string "whole bunch?\p"
    .string "In LAVENDER TOWN, there's a man\n"
    .string "who rates POKéMON nicknames.\p"
    .string "He can even help you rename your\n"
    .string "POKéMON, too.$"
    .endif
    .ifdef SPANISH
    .string "Cuando atrapas a muchos POKéMON,\n"
    .string "¿A que es difícil darles motes?\p"
    .string "En PUEBLO LAVANDA hay un hombre\n"
    .string "que evalúa los motes de los\l"
    .string "POKéMON.\p"
    .string "¡Y te ayudará a renombrarlos!$"
    .endif

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
    .ifdef ENGLISH
    .string "If you're aiming to reach LAVENDER\n"
    .string "TOWN, take ROCK TUNNEL.\p"
    .string "You can get to ROCK TUNNEL from\n"
    .string "CERULEAN CITY.$"
    .endif
    .ifdef SPANISH
    .string "Si quieres ir a PUEBLO LAVANDA,\n"
    .string "ve por el TÚNEL ROCA.\p"
    .string "Podrás tomar el TÚNEL ROCA desde\n"
    .string "CIUDAD CELESTE.$"
    .endif

