Route9_Text_AliciaIntro::
    .string "¡Tienes algunos POKéMON!\n"
    .string "¡En guardia!$"

Route9_Text_AliciaDefeat::
    .string "¡Me has dejado...!$"

Route9_Text_AliciaPostBattle::
    .string "El túnel que hay cerca de aquí\n"
    .string "está muy oscuro.\p"
    .string "Necesitarás DESTELLO para poder\n"
    .string "cruzarlo sin problemas.$"

Route9_Text_ChrisIntro::
    .string "¿Quién anda por ahí con esos\n"
    .string "POKéMON con tan buen aspecto?$"

Route9_Text_ChrisDefeat::
    .string "¡Esto se acabó!$"

Route9_Text_ChrisPostBattle::
    .string "¡Sigue caminando!$"

Route9_Text_DrewIntro::
    .string "¡Tomaré el TÚNEL ROCA para ir\n"
    .string "a PUEBLO LAVANDA!$"

Route9_Text_DrewDefeat::
    .string "¡Soy muy malo! ¡Buaaa!$"

Route9_Text_DrewPostBattle::
    .string "¿Vas a ir también al TÚNEL ROCA?$"

Route9_Text_CaitlinIntro::
    .string "¡No te andes con contemplaciones!$"

Route9_Text_CaitlinDefeat::
    .string "¡Eres demasiado!$"

Route9_Text_CaitlinPostBattle::
    .string "¡Tienes madera!\n"
    .string "¡Buena suerte!$"

Route9_Text_JeremyIntro::
    .string "¡Ja!\n"
    .string "¡Qué bien! ¡Me estaba aburriendo!$"

Route9_Text_JeremyDefeat::
    .string "¡Sigue luchando!\p"
    .string "Espera, ¡si no tengo más POKéMON!$"

Route9_Text_JeremyPostBattle::
    .string "¡Debes de ser muy valiente para\n"
    .string "desafiarme!$"

Route9_Text_BriceIntro::
    .string "¡Eh!\n"
    .string "¿Me enseñas la fuerza que tienes?$"

Route9_Text_BriceDefeat::
    .string "¿Qué ha pasado?$"

Route9_Text_BricePostBattle::
    .string "¡Vaya, sí que tienen fuerza\n"
    .string "los niños de hoy!$"

Route9_Text_BrentIntro::
    .string "¡Madrugo todos los días para\n"
    .string "cuidar a mis POKéMON CAPULLO!$"

Route9_Text_BrentDefeat::
    .string "¿QUÉ?\p"
    .string "¡Qué gran pérdida de tiempo!$"

Route9_Text_BrentPostBattle::
    .string "Tengo que recoger algo más que\n"
    .string "bichos para ser más fuerte...$"

Route9_Text_AlanIntro::
    .string "¡Jajajaja!\n"
    .string "¡Vamos, adelante!$"

Route9_Text_AlanDefeat::
    .string "¡Jajajaja!\n"
    .string "¡Me has ganado!$"

Route9_Text_AlanPostBattle::
    .string "¡Jajaja!\n"
    .string "¡Los más fuertes siempre reímos!$"

Route9_Text_ConnerIntro::
    .string "¡Adelante mis geniales POKéMON\n"
    .string "BICHO!$"

Route9_Text_ConnerDefeat::
    .string "Mis bichos...$"

Route9_Text_ConnerPostBattle::
    .string "Desde luego a ti no te gustan\n"
    .string "los POKéMON BICHO...$"

Route9_Text_RouteSign::
    .string "RUTA 9:\n"
    .string "CIUDAD CELESTE - TÚNEL ROCA$"
