Route9_Text_AliciaIntro::
    .ifdef ENGLISH
    .string "You have POKéMON with you!\n"
    .string "You're mine!$"
    .endif
    .ifdef SPANISH
    .string "¡Tienes algunos POKéMON!\n"
    .string "¡En guardia!$"
    .endif

Route9_Text_AliciaDefeat::
    .ifdef ENGLISH
    .string "You deceived me…$"
    .endif
    .ifdef SPANISH
    .string "¡Me has dejado...!$"
    .endif

Route9_Text_AliciaPostBattle::
    .ifdef ENGLISH
    .string "The tunnel coming up is pitch-black\n"
    .string "inside.\p"
    .string "You'll need FLASH to get through\n"
    .string "there.$"
    .endif
    .ifdef SPANISH
    .string "El túnel que hay cerca de aquí\n"
    .string "está muy oscuro.\p"
    .string "Necesitarás DESTELLO para poder\n"
    .string "cruzarlo sin problemas.$"
    .endif

Route9_Text_ChrisIntro::
    .ifdef ENGLISH
    .string "Who's that walking there with those\n"
    .string "good-looking POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¿Quién anda por ahí con esos\n"
    .string "POKéMON con tan buen aspecto?$"
    .endif

Route9_Text_ChrisDefeat::
    .ifdef ENGLISH
    .string "Out like a light!$"
    .endif
    .ifdef SPANISH
    .string "¡Esto se acabó!$"
    .endif

Route9_Text_ChrisPostBattle::
    .ifdef ENGLISH
    .string "Keep walking!$"
    .endif
    .ifdef SPANISH
    .string "¡Sigue caminando!$"
    .endif

Route9_Text_DrewIntro::
    .ifdef ENGLISH
    .string "I'm taking the ROCK TUNNEL to\n"
    .string "go to LAVENDER…$"
    .endif
    .ifdef SPANISH
    .string "¡Tomaré el TÚNEL ROCA para ir\n"
    .string "a PUEBLO LAVANDA!$"
    .endif

Route9_Text_DrewDefeat::
    .ifdef ENGLISH
    .string "Can't measure up…$"
    .endif
    .ifdef SPANISH
    .string "¡Soy muy malo! ¡Buaaa!$"
    .endif

Route9_Text_DrewPostBattle::
    .ifdef ENGLISH
    .string "Are you off to ROCK TUNNEL, too?$"
    .endif
    .ifdef SPANISH
    .string "¿Vas a ir también al TÚNEL ROCA?$"
    .endif

Route9_Text_CaitlinIntro::
    .ifdef ENGLISH
    .string "Don't you dare patronize me!$"
    .endif
    .ifdef SPANISH
    .string "¡No te andes con contemplaciones!$"
    .endif

Route9_Text_CaitlinDefeat::
    .ifdef ENGLISH
    .string "No!\n"
    .string "You're too much.$"
    .endif
    .ifdef SPANISH
    .string "¡Eres demasiado!$"
    .endif

Route9_Text_CaitlinPostBattle::
    .ifdef ENGLISH
    .string "You're obviously talented.\n"
    .string "Good luck to you!$"
    .endif
    .ifdef SPANISH
    .string "¡Tienes madera!\n"
    .string "¡Buena suerte!$"
    .endif

Route9_Text_JeremyIntro::
    .ifdef ENGLISH
    .string "Bwahaha!\n"
    .string "Great! I was bored, eh!$"
    .endif
    .ifdef SPANISH
    .string "¡Ja!\n"
    .string "¡Qué bien! ¡Me estaba aburriendo!$"
    .endif

Route9_Text_JeremyDefeat::
    .ifdef ENGLISH
    .string "Keep it coming, eh!\p"
    .string "Oh wait.\n"
    .string "I'm out of POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Sigue luchando!\p"
    .string "Espera, ¡si no tengo más POKéMON!$"
    .endif

Route9_Text_JeremyPostBattle::
    .ifdef ENGLISH
    .string "You sure had guts standing up to\n"
    .string "me there, eh?$"
    .endif
    .ifdef SPANISH
    .string "¡Debes de ser muy valiente para\n"
    .string "desafiarme!$"
    .endif

Route9_Text_BriceIntro::
    .ifdef ENGLISH
    .string "Hahaha!\n"
    .string "Aren't you a little toughie!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh!\n"
    .string "¿Me enseñas la fuerza que tienes?$"
    .endif

Route9_Text_BriceDefeat::
    .ifdef ENGLISH
    .string "What's that?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué ha pasado?$"
    .endif

Route9_Text_BricePostBattle::
    .ifdef ENGLISH
    .string "Hahaha!\n"
    .string "Kids should be tough!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya, sí que tienen fuerza\n"
    .string "los niños de hoy!$"
    .endif

Route9_Text_BrentIntro::
    .ifdef ENGLISH
    .string "I got up early every day to raise\n"
    .string "my POKéMON from cocoons!$"
    .endif
    .ifdef SPANISH
    .string "¡Madrugo todos los días para\n"
    .string "cuidar a mis POKéMON CAPULLO!$"
    .endif

Route9_Text_BrentDefeat::
    .ifdef ENGLISH
    .string "WHAT?\p"
    .string "What a total waste of time!$"
    .endif
    .ifdef SPANISH
    .string "¿QUÉ?\p"
    .string "¡Qué gran pérdida de tiempo!$"
    .endif

Route9_Text_BrentPostBattle::
    .ifdef ENGLISH
    .string "I have to collect more than bugs\n"
    .string "to get stronger…$"
    .endif
    .ifdef SPANISH
    .string "Tengo que recoger algo más que\n"
    .string "bichos para ser más fuerte...$"
    .endif

Route9_Text_AlanIntro::
    .ifdef ENGLISH
    .string "Hahahaha!\n"
    .string "Bring it on!$"
    .endif
    .ifdef SPANISH
    .string "¡Jajajaja!\n"
    .string "¡Vamos, adelante!$"
    .endif

Route9_Text_AlanDefeat::
    .ifdef ENGLISH
    .string "Hahahaha!\n"
    .string "You beat me fair!$"
    .endif
    .ifdef SPANISH
    .string "¡Jajajaja!\n"
    .string "¡Me has ganado!$"
    .endif

Route9_Text_AlanPostBattle::
    .ifdef ENGLISH
    .string "Hahahaha!\n"
    .string "Us hearty guys always laugh!$"
    .endif
    .ifdef SPANISH
    .string "¡Jajaja!\n"
    .string "¡Los más fuertes siempre reímos!$"
    .endif

Route9_Text_ConnerIntro::
    .ifdef ENGLISH
    .string "Go, my super BUG POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Adelante mis geniales POKéMON\n"
    .string "BICHO!$"
    .endif

Route9_Text_ConnerDefeat::
    .ifdef ENGLISH
    .string "My bugs…$"
    .endif
    .ifdef SPANISH
    .string "Mis bichos...$"
    .endif

Route9_Text_ConnerPostBattle::
    .ifdef ENGLISH
    .string "If you don't like BUG POKéMON,\n"
    .string "you bug me!$"
    .endif
    .ifdef SPANISH
    .string "Desde luego a ti no te gustan\n"
    .string "los POKéMON BICHO...$"
    .endif

Route9_Text_RouteSign::
    .ifdef ENGLISH
    .string "ROUTE 9\n"
    .string "CERULEAN CITY - ROCK TUNNEL$"
    .endif
    .ifdef SPANISH
    .string "RUTA 9:\n"
    .string "CIUDAD CELESTE - TÚNEL ROCA$"
    .endif

