Route9_Text_AliciaIntro::
	.string "Du trägst POKéMON bei dir! Lass\n"
	.string "uns kämpfen!$"

Route9_Text_AliciaDefeat::
	.string "Du hast gewonnen!$"

Route9_Text_AliciaPostBattle::
	.string "Du benötigst eine Lichtquelle, um\n"
	.string "den Tunnel zu durchqueren!$"

Route9_Text_ChrisIntro::
	.string "Heh, wer bist du?\n"
	.string "Deine POKéMON sehen fit aus!$"

Route9_Text_ChrisDefeat::
	.string "Schnell und präzise besiegt!$"

Route9_Text_ChrisPostBattle::
	.string "O.K., geh einfach weiter!$"

Route9_Text_DrewIntro::
	.string "Ich gehe durch den FELSTUNNEL\n"
	.string "nach LAVANDIA...$"

Route9_Text_DrewDefeat::
	.string "Mit dir habe ich mich übernommen!$"

Route9_Text_DrewPostBattle::
	.string "Möchtest du auch den FELSTUNNEL\n"
	.string "benutzen?$"

Route9_Text_CaitlinIntro::
	.string "Trau dich ruhig, mit mir zu\n"
	.string "kämpfen!$"

Route9_Text_CaitlinDefeat::
	.string "Das war zu viel des Guten!$"

Route9_Text_CaitlinPostBattle::
	.string "Du hast sehr viel Talent! Viel\n"
	.string "Glück auf deinem weiteren Weg!$"

Route9_Text_JeremyIntro::
	.string "Endlich kommt jemand!\n"
	.string "Mir war richtig langweilig!$"

Route9_Text_JeremyDefeat::
	.string "War das etwa schon alles?\p"
	.string "Oh! Ich habe kein einsatzbereites\n"
	.string "POKéMON übrig!$"

Route9_Text_JeremyPostBattle::
	.string "Deine Knie haben ganz schön\n"
	.string "geschlackert, oder?$"

Route9_Text_BriceIntro::
	.string "Du hast keine Chance, du nerviges\n"
	.string "Balg!$"

Route9_Text_BriceDefeat::
	.string "Was ist passiert?$"

Route9_Text_BricePostBattle::
	.string "Haha!\n"
	.string "Kinder sollten Hallodris sein!$"

Route9_Text_BrentIntro::
	.string "Ich stehe jeden Tag früh auf, um\n"
	.string "meine POKéMON in ihren Kokons zu\l"
	.string "pflegen!$"

Route9_Text_BrentDefeat::
	.string "WAS?\p"
	.string "Das war die reinste\n"
	.string "Zeitverschwendung!$"

Route9_Text_BrentPostBattle::
	.string "Ich sollte nicht nur Käfer sammeln,\n"
	.string "um stärker zu werden...$"

Route9_Text_AlanIntro::
	.string "Ha!\n"
	.string "Wie wäre es mit einem Kampf?$"

Route9_Text_AlanDefeat::
	.string "Haha!\n"
	.string "Ein fairer Kampf!$"

Route9_Text_AlanPostBattle::
	.string "Haha!\n"
	.string "Wir Scherzbolde lachen ständig!$"

Route9_Text_ConnerIntro::
	.string "Du hast keine Chance gegen meine\n"
	.string "KÄFER-POKéMON!$"

Route9_Text_ConnerDefeat::
	.string "Meine KÄFER-POKéMON...$"

Route9_Text_ConnerPostBattle::
	.string "Wer keine Käfer mag, den mag ich\n"
	.string "auch nicht!$"

Route9_Text_RouteSign::
	.string "ROUTE 9\n"
	.string "AZURIA CITY - FELSTUNNEL$"

