PokemonLeague_ChampionsRoom_Text_Intro::
    .ifdef ENGLISH
    .string "{RIVAL}: Hey, {PLAYER}!\p"
    .string "I was looking forward to seeing\n"
    .string "you, {PLAYER}.\p"
    .string "My rival should be strong to keep\n"
    .string "me sharp.\p"
    .string "While working on my POKéDEX, I\n"
    .string "looked all over for POKéMON.\p"
    .string "Not only that, I assembled teams\n"
    .string "that would beat any POKéMON type.\p"
    .string "And now…\p"
    .string "I'm the POKéMON LEAGUE CHAMPION!\p"
    .string "{PLAYER}!\n"
    .string "Do you know what that means?\p"
    .string "I'll tell you.\p"
    .string "I am the most powerful TRAINER in\n"
    .string "the world!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Hola!\p"
    .string "¡Estaba deseando verte, {PLAYER}!\p"
    .string "¡Mi rival debería ser fuerte para\n"
    .string "poder mantenerme en forma!\p"
    .string "¡Utilizando mi POKéDEX, he buscado\n"
    .string "los POKéMON más fuertes!\p"
    .string "¡Y he creado varios equipos que\n"
    .string "derrotarían a cualquier tipo de\l"
    .string "POKéMON!\p"
    .string "¡Y ahora!\p"
    .string "¡Yo soy el campeón de la LIGA\n"
    .string "POKéMON!\p"
    .string "¡{PLAYER}!\n"
    .string "¿Sabes lo que significa eso?\p"
    .string "¡Te lo diré!\p"
    .string "¡Yo soy el mejor ENTRENADOR\n"
    .string "del mundo!$"
    .endif

PokemonLeague_ChampionsRoom_Text_RematchIntro::
    .ifdef ENGLISH
    .string "{RIVAL}: Hey, {PLAYER}!\p"
    .string "You came back, {PLAYER}!\n"
    .string "Hahah, that is so great!\p"
    .string "My rival should be strong to keep\n"
    .string "me sharp.\p"
    .string "While working on my POKéDEX, I\n"
    .string "looked all over for POKéMON.\p"
    .string "Not only that, I assembled teams\n"
    .string "that would beat any POKéMON type.\p"
    .string "And now…\p"
    .string "I'm the POKéMON LEAGUE CHAMPION!\p"
    .string "{PLAYER}!\n"
    .string "Do you know what that means?\p"
    .string "I'll tell you.\p"
    .string "I am the most powerful TRAINER in\n"
    .string "the world!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Hola!\p"
    .string "¡Aquí estás de nuevo, {PLAYER}!\p"
    .string "¡Mi rival debería ser fuerte para\n"
    .string "poder mantenerme en forma!\p"
    .string "¡Utilizando mi POKéDEX, he buscado\n"
    .string "los POKéMON más fuertes!\p"
    .string "¡Y he creado varios equipos que\n"
    .string "derrotarían a cualquier tipo de\l"
    .string "POKéMON!\p"
    .string "¡Y ahora!\p"
    .string "¡Yo soy el campeón de la LIGA\n"
    .string "POKéMON!\p"
    .string "¡{PLAYER}!\n"
    .string "¿Sabes lo que significa eso?\p"
    .string "¡Te lo diré!\p"
    .string "¡Yo soy el mejor ENTRENADOR\n"
    .string "del mundo!$"
    .endif

PokemonLeague_ChampionsRoom_Text_Defeat::
    .ifdef ENGLISH
    .string "NO!\n"
    .string "That can't be!\l"
    .string "You beat me at my best!\p"
    .string "After all that work to become\n"
    .string "the LEAGUE CHAMP?\p"
    .string "My reign is over already?\n"
    .string "It's not fair!$"
    .endif
    .ifdef SPANISH
    .string "¡NO!\n¡Eso es imposible!\l"
    .string "¡Me has derrotado!\p"
    .string "¡Tras tantos esfuerzos por\n"
    .string "convertirme en campeón de LIGA!\p"
    .string "¿Se ha terminado ya mi reinado?\n"
    .string "¡No es justo!$"
    .endif

PokemonLeague_ChampionsRoom_Text_Victory::
    .string "はーはッ！\n"
    .string "かった！　かった！　かった！\p"
    .string "{PLAYER}に　まける　ような\n"
    .string "おれさま　では　なーい！\p"
    .string "ま！　ポケモンの\n"
    .string "てんさい　{RIVAL}さま　あいてに\l"
    .string "ここまで　よく　がんばった！\p"
    .string "ほめて　つかわす！\n"
    .string "はーッ！　はーはッはッ！$"

PokemonLeague_ChampionsRoom_Text_PostBattle::
    .ifdef ENGLISH
    .string "Why?\n"
    .string "Why did I lose?\p"
    .string "I never made any mistakes raising\n"
    .string "my POKéMON…\p"
    .string "Darn it! You're the new POKéMON\n"
    .string "LEAGUE CHAMPION!\p"
    .string "Although I don't like to admit it…$"
    .endif
    .ifdef SPANISH
    .string "¿Qué?\n"
    .string "¿Cómo he podido perder?\p"
    .string "He entrenado a mis POKéMON\n"
    .string "a la perfección.\p"
    .string "¡No puedo soportar que hayas\n"
    .string "ganado la LIGA POKéMON!\p"
    .string "Aunque no me guste admitirlo.$"
    .endif

PokemonLeague_ChampionsRoom_Text_OakPlayer::
    .ifdef ENGLISH
    .string "OAK: {PLAYER}!$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡{PLAYER}!$"
    .endif

PokemonLeague_ChampionsRoom_Text_OakCongratulations::
    .ifdef ENGLISH
    .string "OAK: So, you've won!\n"
    .string "Sincerely, congratulations!\p"
    .string "You're the new POKéMON LEAGUE\n"
    .string "CHAMPION!\p"
    .string "You've grown up so much since you\n"
    .string "first left with {STR_VAR_1} to work\l"
    .string "on the POKéDEX.\p"
    .string "{PLAYER}, you have come of age!$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡Has ganado!\n"
    .string "¡Enhorabuena!\p"
    .string "¡Has ganado la LIGA POKéMON!\p"
    .string "¡Has crecido tanto desde que\n"
    .string "te fuiste con {STR_VAR_1} para\l"
    .string "completar tu POKéDEX!\p"
    .string "¡{PLAYER}, ya eres mayor!$"
    .endif

PokemonLeague_ChampionsRoom_Text_OakImDisappointedRival::
    .ifdef ENGLISH
    .string "OAK: {RIVAL}…\n"
    .string "I'm disappointed in you.\p"
    .string "I came when I heard you'd beaten\n"
    .string "the ELITE FOUR.\p"
    .string "But, when I got here, you had\n"
    .string "already lost!\p"
    .string "{RIVAL}, do you understand why\n"
    .string "you lost?\p"
    .string "You have forgotten to treat your\n"
    .string "POKéMON with love and trust.\p"
    .string "Without them, you will never\n"
    .string "become a CHAMP again!$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡{RIVAL}!\n"
    .string "¡Estoy desolado!\p"
    .string "¡Vine en cuanto supe que habías\n"
    .string "derrotado al ALTO MANDO!\p"
    .string "¡Pero cuando llegué aquí, ya\n"
    .string "te habían vencido!\p"
    .string "¡{RIVAL}!\n"
    .string "¿Entiendes por qué has perdido?\p"
    .string "¡Olvidaste tratar a tus POKéMON\n"
    .string "con cariño y confianza!\p"
    .string "¡Y sin ellos, jamás volverás\n"
    .string "a ganar!$"
    .endif

PokemonLeague_ChampionsRoom_Text_OakPlayerComeWithMe::
    .ifdef ENGLISH
    .string "OAK: {PLAYER}.\p"
    .string "You understand that your victory\n"
    .string "was not just your own doing.\p"
    .string "The bond you share with your\n"
    .string "POKéMON is marvelous.\p"
    .string "{PLAYER}!\n"
    .string "Come with me!$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡{PLAYER}!\p"
    .string "¡Sabes que tu victoria no fue\n"
    .string "debida sólo a ti!\p"
    .string "¡El vínculo que mantienes con\n"
    .string "tus POKéMON es maravilloso!\p"
    .string "¡{PLAYER}!\n"
    .string "¡Ven conmigo!$"
    .endif

