FiveIsland_PokemonCenter_1F_Text_OnMyWayToPrepareMeal::
    .ifdef ENGLISH
    .string "I'm on my way to prepare a meal\n"
    .string "for a certain high-society person.$"
    .endif
    .ifdef SPANISH
    .string "Voy a preparar una comida para\n"
    .string "una persona muy importante.$"
    .endif

FiveIsland_PokemonCenter_1F_Text_YoureOnQuestToCatchEveryMon::
    .ifdef ENGLISH
    .string "You're on a quest to catch every\n"
    .string "single kind of POKéMON?\p"
    .string "…How incredible. Please tell me if\n"
    .string "you catch a strong one!$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres atrapar a todos los\n"
    .string "POKéMON que te encuentres?\p"
    .string "¡Qué increíble!... ¡Oye, pues\n"
    .string "avísame si atrapas alguno fuerte!$"
    .endif

