Route24_Text_JustEarnedFabulousPrize::
    .ifdef ENGLISH
    .string "Congratulations! You beat our\n"
    .string "five contest TRAINERS!\p"
    .string "You just earned a fabulous prize!$"
    .endif
    .ifdef SPANISH
    .string "¡Enhorabuena! ¡Has ganado\n"
    .string "a nuestros 5 ENTRENADORES!\p"
    .string "¡Has ganado un premio fabuloso!$"
    .endif

Route24_Text_ReceivedNuggetFromMysteryTrainer::
    .ifdef ENGLISH
    .string "{PLAYER} received a NUGGET\n"
    .string "from the mystery TRAINER!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo una PEPITA\n"
    .string "de manos del ENTRENADOR\l"
    .string "misterioso!$"
    .endif

Route24_Text_YouDontHaveAnyRoom::
    .ifdef ENGLISH
    .string "You don't have any room!$"
    .endif
    .ifdef SPANISH
    .string "¡No te queda sitio!$"
    .endif

Route24_Text_JoinTeamRocket::
    .ifdef ENGLISH
    .string "By the way, how would you like to\n"
    .string "join TEAM ROCKET?\p"
    .string "We're a group of professional\n"
    .string "criminals specializing in POKéMON!\p"
    .string "Want to join?\p"
    .string "Are you sure?\p"
    .string "Come on, join us!\p"
    .string "I'm telling you to join!\p"
    .string "…Okay, you need convincing!\p"
    .string "I'll make you an offer you can't\n"
    .string "refuse!$"
    .endif
    .ifdef SPANISH
    .string "¿Te gustaría unirte al TEAM\n"
    .string "ROCKET?\p"
    .string "¡Somos un grupo dedicado a hacer\n"
    .string "maldades con los POKéMON!\p"
    .string "¿Te interesa?\p"
    .string "¿Seguro?\p"
    .string "Únete a nosotros.\p"
    .string "¡Ya te he dicho que te unas\n"
    .string "a nosotros!\p"
    .string "Necesitas que te convenza.\p"
    .string "¡Te haré una oferta que no podrás\n"
    .string "rechazar!$"
    .endif

Route24_Text_RocketDefeat::
    .ifdef ENGLISH
    .string "Arrgh!\n"
    .string "You are good!$"
    .endif
    .ifdef SPANISH
    .string "¡Arrgh!\n"
    .string "¡Eres genial!$"
    .endif

Route24_Text_YoudBecomeTopRocketLeader::
    .ifdef ENGLISH
    .string "With your ability, you'd become\n"
    .string "a top leader in TEAM ROCKET.\p"
    .string "Come on, think of the opportunity!\n"
    .string "Don't let this chance go to waste.$"
    .endif
    .ifdef SPANISH
    .string "¡Con tu capacidad podrías ser\n"
    .string "líder del TEAM ROCKET!\p"
    .string "¡Piénsatelo, sería una buena\n"
    .string "oportunidad para ti!$"
    .endif

Route24_Text_ShaneIntro::
    .ifdef ENGLISH
    .string "I saw your feat from the grass!$"
    .endif
    .ifdef SPANISH
    .string "¡Vi tu hazaña desde la hierba!$"
    .endif

Route24_Text_ShaneDefeat::
    .ifdef ENGLISH
    .string "I thought not!$"
    .endif
    .ifdef SPANISH
    .string "¡Creía que no me ibas a ganar!$"
    .endif

Route24_Text_ShanePostBattle::
    .ifdef ENGLISH
    .string "I hid because the people on the\n"
    .string "bridge frightened me.$"
    .endif
    .ifdef SPANISH
    .string "¡Me oculté porque me asustaron\n"
    .string "los del puente!$"
    .endif

Route24_Text_EthanIntro::
    .ifdef ENGLISH
    .string "Okay! I'm No. 5!\n"
    .string "I'll stomp you!$"
    .endif
    .ifdef SPANISH
    .string "¡Yo soy el 5.º!\n"
    .string "¡Voy a acabar contigo!$"
    .endif

Route24_Text_EthanDefeat::
    .ifdef ENGLISH
    .string "Whoa!\n"
    .string "Too much!$"
    .endif
    .ifdef SPANISH
    .string "¡Uauu!\n"
    .string "¡Ha sido mucha tela!$"
    .endif

Route24_Text_EthanPostBattle::
    .ifdef ENGLISH
    .string "I did my best. I have no regrets!$"
    .endif
    .ifdef SPANISH
    .string "¡He hecho lo que he podido!$"
    .endif

Route24_Text_ReliIntro::
    .ifdef ENGLISH
    .string "I'm No. 4!\n"
    .string "Getting tired?$"
    .endif
    .ifdef SPANISH
    .string "¡Yo soy la 4.ª!\n"
    .string "¿Te quedan fuerzas?$"
    .endif

Route24_Text_ReliDefeat::
    .ifdef ENGLISH
    .string "I lost, too!$"
    .endif
    .ifdef SPANISH
    .string "¡También he perdido!$"
    .endif

Route24_Text_ReliPostBattle::
    .ifdef ENGLISH
    .string "I did my best, so I've no regrets!$"
    .endif
    .ifdef SPANISH
    .string "¡He hecho lo que he podido!$"
    .endif

Route24_Text_TimmyIntro::
    .ifdef ENGLISH
    .string "Here's No. 3!\n"
    .string "I won't be easy!$"
    .endif
    .ifdef SPANISH
    .string "¡Yo soy el 3.º!\n"
    .string "¡Te va a costar!$"
    .endif

Route24_Text_TimmyDefeat::
    .ifdef ENGLISH
    .string "Ow!\n"
    .string "Stomped flat!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye!\n"
    .string "¡Me has machacado!$"
    .endif

Route24_Text_TimmyPostBattle::
    .ifdef ENGLISH
    .string "I did my best. I have no regrets!$"
    .endif
    .ifdef SPANISH
    .string "¡He hecho lo que he podido!$"
    .endif

Route24_Text_AliIntro::
    .ifdef ENGLISH
    .string "I'm second!\n"
    .string "Now it's serious!$"
    .endif
    .ifdef SPANISH
    .string "¡Yo soy la 2.ª!\n"
    .string "¡En guardia!$"
    .endif

Route24_Text_AliDefeat::
    .ifdef ENGLISH
    .string "How could I lose?$"
    .endif
    .ifdef SPANISH
    .string "¿Cómo he podido perder?$"
    .endif

Route24_Text_AliPostBattle::
    .ifdef ENGLISH
    .string "I did my best. I have no regrets!$"
    .endif
    .ifdef SPANISH
    .string "¡He hecho lo que he podido!$"
    .endif

Route24_Text_CaleIntro::
    .ifdef ENGLISH
    .string "People call this the NUGGET\n"
    .string "BRIDGE!\p"
    .string "Beat us five TRAINERS and win\n"
    .string "a fabulous prize!\p"
    .string "Think you got what it takes?$"
    .endif
    .ifdef SPANISH
    .string "¡Éste es el PUENTE PEPITA!\n"
    .string "¡Derrótanos a los 5 y gana un\l"
    .string "fabuloso premio!\p"
    .string "¿Crees que puedes hacerlo?$"
    .endif

Route24_Text_CaleDefeat::
    .ifdef ENGLISH
    .string "Whoo!\n"
    .string "Good stuff!$"
    .endif
    .ifdef SPANISH
    .string "¡Uau!\n"
    .string "¡Bien hecho!$"
    .endif

Route24_Text_CalePostBattle::
    .ifdef ENGLISH
    .string "I did my best. I have no regrets!$"
    .endif
    .ifdef SPANISH
    .string "¡He hecho lo que he podido!$"
    .endif
