Route24_Text_JustEarnedFabulousPrize::
    .string "¡Enhorabuena! ¡Has ganado\n"
    .string "a nuestros 5 ENTRENADORES!\p"
    .string "¡Has ganado un premio fabuloso!$"

Route24_Text_ReceivedNuggetFromMysteryTrainer::
    .string "¡{PLAYER} obtuvo una PEPITA\n"
    .string "de manos del ENTRENADOR\l"
    .string "misterioso!$"

Route24_Text_YouDontHaveAnyRoom::
    .string "¡No te queda sitio!$"

Route24_Text_JoinTeamRocket::
    .string "¿Te gustaría unirte al TEAM\n"
    .string "ROCKET?\p"
    .string "¡Somos un grupo dedicado a hacer\n"
    .string "maldades con los POKéMON!\p"
    .string "¿Te interesa?\p"
    .string "¿Seguro?\p"
    .string "Únete a nosotros.\p"
    .string "¡Ya te he dicho que te unas\n"
    .string "a nosotros!\p"
    .string "Necesitas que te convenza.\p"
    .string "¡Te haré una oferta que no podrás\n"
    .string "rechazar!$"

Route24_Text_RocketDefeat::
    .string "¡Arrgh!\n"
    .string "¡Eres genial!$"

Route24_Text_YoudBecomeTopRocketLeader::
    .string "¡Con tu capacidad podrías ser\n"
    .string "líder del TEAM ROCKET!\p"
    .string "¡Piénsatelo, sería una buena\n"
    .string "oportunidad para ti!$"

Route24_Text_ShaneIntro::
    .string "¡Vi tu hazaña desde la hierba!$"

Route24_Text_ShaneDefeat::
    .string "¡Creía que no me ibas a ganar!$"

Route24_Text_ShanePostBattle::
    .string "¡Me oculté porque me asustaron\n"
    .string "los del puente!$"

Route24_Text_EthanIntro::
    .string "¡Yo soy el 5.º!\n"
    .string "¡Voy a acabar contigo!$"

Route24_Text_EthanDefeat::
    .string "¡Uauu!\n"
    .string "¡Ha sido mucha tela!$"

Route24_Text_EthanPostBattle::
    .string "¡He hecho lo que he podido!$"

Route24_Text_ReliIntro::
    .string "¡Yo soy la 4.ª!\n"
    .string "¿Te quedan fuerzas?$"

Route24_Text_ReliDefeat::
    .string "¡También he perdido!$"

Route24_Text_ReliPostBattle::
    .string "¡He hecho lo que he podido!$"

Route24_Text_TimmyIntro::
    .string "¡Yo soy el 3.º!\n"
    .string "¡Te va a costar!$"

Route24_Text_TimmyDefeat::
    .string "¡Oye!\n"
    .string "¡Me has machacado!$"

Route24_Text_TimmyPostBattle::
    .string "¡He hecho lo que he podido!$"

Route24_Text_AliIntro::
    .string "¡Yo soy la 2.ª!\n"
    .string "¡En guardia!$"

Route24_Text_AliDefeat::
    .string "¿Cómo he podido perder?$"

Route24_Text_AliPostBattle::
    .string "¡He hecho lo que he podido!$"

Route24_Text_CaleIntro::
    .string "¡Éste es el PUENTE PEPITA!\n"
    .string "¡Derrótanos a los 5 y gana un\l"
    .string "fabuloso premio!\p"
    .string "¿Crees que puedes hacerlo?$"

Route24_Text_CaleDefeat::
    .string "¡Uau!\n"
    .string "¡Bien hecho!$"

Route24_Text_CalePostBattle::
    .string "¡He hecho lo que he podido!$"
