ThreeIsland_Mart_Text_TrueThatCeldadonDeptStoreBigger::
    .ifdef ENGLISH
    .string "Is it true?\p"
    .string "CELADON DEPT. STORE is several\n"
    .string "times bigger than this shop?$"
    .endif
    .ifdef SPANISH
    .string "¿De verdad?\p"
    .string "¿Seguro que el CENTRO COMERCIAL\n"
    .string "de AZULONA es mucho mayor que\l"
    .string "esta tienda?$"
    .endif

ThreeIsland_Mart_Text_PeopleHealWithBerriesFromForest::
    .ifdef ENGLISH
    .string "I sometimes buy medicine here.\p"
    .string "But a lot of people heal POKéMON\n"
    .string "with BERRIES from BERRY FOREST.\p"
    .string "After all, BERRIES are free and\n"
    .string "they never run out.$"
    .endif
    .ifdef SPANISH
    .string "A veces compro medicinas aquí.\p"
    .string "Pero hay mucha gente que cura a\n"
    .string "los POKéMON con BAYAS del BOSQUE\l"
    .string "BAYA.\p"
    .string "Hombre, yo lo entiendo; las BAYAS\n"
    .string "son gratis y nunca se acaban.$"
    .endif

ThreeIsland_Mart_Text_BikersWereAboutToTrashMart::
    .ifdef ENGLISH
    .string "Those BIKERS were about to trash\n"
    .string "this POKéMON MART.\p"
    .string "Am I glad they decided to leave!$"
    .endif
    .ifdef SPANISH
    .string "Los MOTORISTAS han estado a punto\n"
    .string "de destrozar la TIENDA POKéMON.\p"
    .string "Menos mal que se han ido.$"
    .endif

