SafariZone_Center_Text_WhereDidErikGo::
    .ifdef ENGLISH
    .string "SARA: Where did my boyfriend,\n"
    .string "ERIK, go?$"
    .endif
    .ifdef SPANISH
    .string "SARA: ¿Adónde fue mi amigo\n"
    .string "ENRIQUE?$"
    .endif

SafariZone_Center_Text_CatchingMonsAsGifts::
    .ifdef ENGLISH
    .string "I'm catching POKéMON to take home\n"
    .string "as gifts.$"
    .endif
    .ifdef SPANISH
    .string "¡Estoy atrapando POKéMON para\n"
    .string "llevarlos a casa como regalos!$"
    .endif

