ThreeIsland_BondBridge_Text_NikkiIntro::
    .string "El intenso olor a sal del mar,\n"
    .string "aaaah... me llega al corazón.$"

ThreeIsland_BondBridge_Text_NikkiDefeat::
    .string "Pero ahora me huele... ¡a derrota!$"

ThreeIsland_BondBridge_Text_NikkiPostBattle::
    .string "¿No serán tus POKéMON los que\n"
    .string "huelen mal?$"

ThreeIsland_BondBridge_Text_VioletIntro::
    .string "¿Por qué vas con tanta prisa?$"

ThreeIsland_BondBridge_Text_VioletDefeat::
    .string "¡Estás entrenando a tus POKéMON\n"
    .string "de maravilla!$"

ThreeIsland_BondBridge_Text_VioletPostBattle::
    .string "Si sigues el camino que llevas,\n"
    .string "llegarás al BOSQUE BAYA.$"

ThreeIsland_BondBridge_Text_AmiraIntro::
    .string "Mi mami me ha dicho que no debo\n"
    .string "nadar sin flotador.$"

ThreeIsland_BondBridge_Text_AmiraDefeat::
    .string "¡Buaaaaa!\n"
    .string "¡Buaaaaaaaaaaa!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle::
    .string "Este año, seguro que aprendo\n"
    .string "a nadar sola.$"

ThreeIsland_BondBridge_Text_AlexisIntro::
    .string "¡POKéMON, POKéMON!\n"
    .string "¡A mí me gustan los POKéMON!$"

ThreeIsland_BondBridge_Text_AlexisDefeat::
    .string "¿Qué ha pasado?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle::
    .string "¿Mis POKéMON me han fallado?$"

ThreeIsland_BondBridge_Text_TishaIntro::
    .string "¡No, no, déjame, por favor!\n"
    .string "¡Déjame en paz!$"

ThreeIsland_BondBridge_Text_TishaDefeat::
    .string "Vale, has ganado, ¿te irás ahora?$"

ThreeIsland_BondBridge_Text_TishaPostBattle::
    .string "¡Un POKéMON me ha enganchado\n"
    .string "por el bañador!\p"
    .string "¡No me puedo mover!$"

ThreeIsland_BondBridge_Text_JoyIntro::
    .string "FELI: Te vamos a enseñar cuál es\n"
    .string "nuestro POKéMON preferido.$"

ThreeIsland_BondBridge_Text_JoyDefeat::
    .string "FELI: Oh..., MATI...$"

ThreeIsland_BondBridge_Text_JoyPostBattle::
    .string "FELI: Bueno, me lo he pasado bien.\n"
    .string "Espero que podamos repetirlo.$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
    .string "FELI: Con un POKéMON no tienes\n"
    .string "nada que hacer.\p"
    .string "Para eso, lucho con MATI.$"

ThreeIsland_BondBridge_Text_MegIntro::
    .string "MATI: Te vamos a enseñar cuál es\n"
    .string "nuestro POKéMON favorito.$"

ThreeIsland_BondBridge_Text_MegDefeat::
    .string "MATI: Oh..., FELI...$"

ThreeIsland_BondBridge_Text_MegPostBattle::
    .string "MATI: FELI, ¿te lo has pasado\n"
    .string "bien?$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
    .string "MATI: Con un POKéMON no tienes\n"
    .string "nada que hacer.\p"
    .string "Para eso, lucho con FELI.$"

ThreeIsland_BondBridge_Text_BerryForestAhead::
    .string "HACIA EL BOSQUE BAYA$"

ThreeIsland_BondBridge_Text_BondBridgeSign::
    .string "PUENTE UNIÓN\n"
    .string "Crucen con cuidado.\p"
    .string "HACIA EL BOSQUE BAYA$"
