ThreeIsland_BondBridge_Text_NikkiIntro::
	.string "Der salzige Geruch des Wassers…\n"
	.string "Er erfüllt mein Herz mit Freude.$"

ThreeIsland_BondBridge_Text_NikkiDefeat::
	.string "… schnief, schnief…\n"
	.string "Irgendetwas riecht unangenehm…$"

ThreeIsland_BondBridge_Text_NikkiPostBattle::
	.string "Vielleicht ist es der verschwitzte\n"
	.string "Körper eines deiner POKéMON,\l"
	.string "der hier so riecht…$"

ThreeIsland_BondBridge_Text_VioletIntro::
	.string "Wo willst du so eilig hin?$"

ThreeIsland_BondBridge_Text_VioletDefeat::
	.string "Du trainierst einige eindrucks-\n"
	.string "volle POKéMON.$"

ThreeIsland_BondBridge_Text_VioletPostBattle::
	.string "Wenn du hier weiterläufst, kommst\n"
	.string "du in den BEERENFORST.$"

ThreeIsland_BondBridge_Text_AmiraIntro::
	.string "Meine Mutter sagt, dass ich ohne\n"
	.string "meinen Schwimmreif nicht\l"
	.string "schwimmen kann.$"

ThreeIsland_BondBridge_Text_AmiraDefeat::
	.string "Wah!\n"
	.string "Wah!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle::
	.string "Dieses Jahr werde ich endlich\n"
	.string "das Schwimmen lernen!$"

ThreeIsland_BondBridge_Text_AlexisIntro::
	.string "Jo, jo!\n"
	.string "POKéMON!$"

ThreeIsland_BondBridge_Text_AlexisDefeat::
	.string "Was geschieht jetzt?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle::
	.string "Habe ich gerade gewonnen?\n"
	.string "Oder verloren?$"

ThreeIsland_BondBridge_Text_TishaIntro::
	.string "Oh, nein, komm nicht näher!\n"
	.string "Bleib mir bitte vom Leib!$"

ThreeIsland_BondBridge_Text_TishaDefeat::
	.string "O.K., du hast gewonnen!\n"
	.string "Gehst du jetzt bitte weg?$"

ThreeIsland_BondBridge_Text_TishaPostBattle::
	.string "Ein POKéMON hat durch meinen\n"
	.string "Badeanzug gebissen.\p"
	.string "Ich kann nicht aus dem Wasser!$"

ThreeIsland_BondBridge_Text_JoyIntro::
	.string "UTE: Wir zeigen dir unser\n"
	.string "Lieblings-POKéMON!$"

ThreeIsland_BondBridge_Text_JoyDefeat::
	.string "UTE: Oh…\n"
	.string "IDA!$"

ThreeIsland_BondBridge_Text_JoyPostBattle::
	.string "UTE: Hat das nicht Spaß gemacht?\n"
	.string "Ich hoffe, wir wiederholen das!$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
	.string "UTE: Ich wollte wirklich mit IDA\n"
	.string "kämpfen.\p"
	.string "Ein POKéMON reicht nicht aus!$"

ThreeIsland_BondBridge_Text_MegIntro::
	.string "IDA: Wir zeigen dir unsere\n"
	.string "Lieblings-POKéMON.$"

ThreeIsland_BondBridge_Text_MegDefeat::
	.string "IDA: Oh…\n"
	.string "UTE!$"

ThreeIsland_BondBridge_Text_MegPostBattle::
	.string "IDA: UTE, das war ein Spaß!$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
	.string "IDA: Ich möchte mit UTE\n"
	.string "kämpfen.\p"
	.string "Ein POKéMON ist nicht genug.$"

ThreeIsland_BondBridge_Text_BerryForestAhead::
	.string "BEERENFORST VORAUS$"

ThreeIsland_BondBridge_Text_BondBridgeSign::
	.string "BUNDBRÜCKE\n"
	.string "Beim Überqueren bitte Ruhe!\p"
	.string "BEERENFORST VORAUS$"

