ThreeIsland_BondBridge_Text_NikkiIntro::
    .ifdef ENGLISH
    .string "The salty tang of the sea…\n"
    .string "It tickles my heart.$"
    .endif
    .ifdef SPANISH
    .string "El intenso olor a sal del mar,\n"
    .string "aaaah... me llega al corazón.$"
    .endif

ThreeIsland_BondBridge_Text_NikkiDefeat::
    .ifdef ENGLISH
    .string "…Sniff, sniff…\n"
    .string "Something smells unpleasant…$"
    .endif
    .ifdef SPANISH
    .string "Pero ahora me huele... ¡a derrota!$"
    .endif

ThreeIsland_BondBridge_Text_NikkiPostBattle::
    .ifdef ENGLISH
    .string "Perhaps that reek is your sweaty\n"
    .string "POKéMON's body odor…$"
    .endif
    .ifdef SPANISH
    .string "¿No serán tus POKéMON los que\n"
    .string "huelen mal?$"
    .endif

ThreeIsland_BondBridge_Text_VioletIntro::
    .ifdef ENGLISH
    .string "Where are you off to in such\n"
    .string "a hurry?$"
    .endif
    .ifdef SPANISH
    .string "¿Por qué vas con tanta prisa?$"
    .endif

ThreeIsland_BondBridge_Text_VioletDefeat::
    .ifdef ENGLISH
    .string "You're raising some wonderful\n"
    .string "POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Estás entrenando a tus POKéMON\n"
    .string "de maravilla!$"
    .endif

ThreeIsland_BondBridge_Text_VioletPostBattle::
    .ifdef ENGLISH
    .string "If you keep going this way, you'll\n"
    .string "eventually reach BERRY FOREST.$"
    .endif
    .ifdef SPANISH
    .string "Si sigues el camino que llevas,\n"
    .string "llegarás al BOSQUE BAYA.$"
    .endif

ThreeIsland_BondBridge_Text_AmiraIntro::
    .ifdef ENGLISH
    .string "My mommy said that I can't swim\n"
    .string "without my float ring.$"
    .endif
    .ifdef SPANISH
    .string "Mi mami me ha dicho que no debo\n"
    .string "nadar sin flotador.$"
    .endif

ThreeIsland_BondBridge_Text_AmiraDefeat::
    .ifdef ENGLISH
    .string "Waaah!\n"
    .string "Waaah!$"
    .endif
    .ifdef SPANISH
    .string "¡Buaaaaa!\n"
    .string "¡Buaaaaaaaaaaa!$"
    .endif

ThreeIsland_BondBridge_Text_AmiraPostBattle::
    .ifdef ENGLISH
    .string "This year, I'm going to finally\n"
    .string "learn how to swim!$"
    .endif
    .ifdef SPANISH
    .string "Este año, seguro que aprendo\n"
    .string "a nadar sola.$"
    .endif

ThreeIsland_BondBridge_Text_AlexisIntro::
    .ifdef ENGLISH
    .string "Yay, yay!\n"
    .string "POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡POKéMON, POKéMON!\n"
    .string "¡A mí me gustan los POKéMON!$"
    .endif

ThreeIsland_BondBridge_Text_AlexisDefeat::
    .ifdef ENGLISH
    .string "What happens now?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué ha pasado?$"
    .endif

ThreeIsland_BondBridge_Text_AlexisPostBattle::
    .ifdef ENGLISH
    .string "Did I just win?\n"
    .string "Or did I lose?$"
    .endif
    .ifdef SPANISH
    .string "¿Mis POKéMON me han fallado?$"
    .endif

ThreeIsland_BondBridge_Text_TishaIntro::
    .ifdef ENGLISH
    .string "Oh, no, don't come here!\n"
    .string "Please, stay away from me!$"
    .endif
    .ifdef SPANISH
    .string "¡No, no, déjame, por favor!\n"
    .string "¡Déjame en paz!$"
    .endif

ThreeIsland_BondBridge_Text_TishaDefeat::
    .ifdef ENGLISH
    .string "Okay, you've won!\n"
    .string "Now will you please go away?$"
    .endif
    .ifdef SPANISH
    .string "Vale, has ganado, ¿te irás ahora?$"
    .endif

ThreeIsland_BondBridge_Text_TishaPostBattle::
    .ifdef ENGLISH
    .string "A POKéMON bit through my \n"
    .string "swimsuit.\p"
    .string "I can't get out of the water!$"
    .endif
    .ifdef SPANISH
    .string "¡Un POKéMON me ha enganchado\n"
    .string "por el bañador!\p"
    .string "¡No me puedo mover!$"
    .endif

ThreeIsland_BondBridge_Text_JoyIntro::
    .ifdef ENGLISH
    .string "JOY: We'll teach you what our\n"
    .string "favorite POKéMON is!$"
    .endif
    .ifdef SPANISH
    .string "FELI: Te vamos a enseñar cuál es\n"
    .string "nuestro POKéMON preferido.$"
    .endif

ThreeIsland_BondBridge_Text_JoyDefeat::
    .ifdef ENGLISH
    .string "JOY: Ohh…\n"
    .string "MEG!$"
    .endif
    .ifdef SPANISH
    .string "FELI: Oh..., MATI...$"
    .endif

ThreeIsland_BondBridge_Text_JoyPostBattle::
    .ifdef ENGLISH
    .string "JOY: Wasn't that fun?\n"
    .string "I hope we can battle again!$"
    .endif
    .ifdef SPANISH
    .string "FELI: Bueno, me lo he pasado bien.\n"
    .string "Espero que podamos repetirlo.$"
    .endif

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
    .ifdef ENGLISH
    .string "JOY: I really want to battle with\n"
    .string "MEG.\p"
    .string "One POKéMON isn't enough.$"
    .endif
    .ifdef SPANISH
    .string "FELI: Con un POKéMON no tienes\n"
    .string "nada que hacer.\p"
    .string "Para eso, lucho con MATI.$"
    .endif

ThreeIsland_BondBridge_Text_MegIntro::
    .ifdef ENGLISH
    .string "MEG: We'll show you our favorite\n"
    .string "POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "MATI: Te vamos a enseñar cuál es\n"
    .string "nuestro POKéMON favorito.$"
    .endif

ThreeIsland_BondBridge_Text_MegDefeat::
    .ifdef ENGLISH
    .string "MEG: Ohh…\n"
    .string "JOY!$"
    .endif
    .ifdef SPANISH
    .string "MATI: Oh..., FELI...$"
    .endif

ThreeIsland_BondBridge_Text_MegPostBattle::
    .ifdef ENGLISH
    .string "MEG: JOY, wasn't that fun?$"
    .endif
    .ifdef SPANISH
    .string "MATI: FELI, ¿te lo has pasado\n"
    .string "bien?$"
    .endif

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
    .ifdef ENGLISH
    .string "MEG: I want to battle together\n"
    .string "with JOY.\p"
    .string "One POKéMON isn't enough.$"
    .endif
    .ifdef SPANISH
    .string "MATI: Con un POKéMON no tienes\n"
    .string "nada que hacer.\p"
    .string "Para eso, lucho con FELI.$"
    .endif

ThreeIsland_BondBridge_Text_BerryForestAhead::
    .ifdef ENGLISH
    .string "BERRY FOREST AHEAD$"
    .endif
    .ifdef SPANISH
    .string "HACIA EL BOSQUE BAYA$"
    .endif

ThreeIsland_BondBridge_Text_BondBridgeSign::
    .ifdef ENGLISH
    .string "BOND BRIDGE\n"
    .string "Please be quiet when crossing.\p"
    .string "BERRY FOREST AHEAD$"
    .endif
    .ifdef SPANISH
    .string "PUENTE UNIÓN\n"
    .string "Crucen con cuidado.\p"
    .string "HACIA EL BOSQUE BAYA$"
    .endif

