FiveIsland_ResortGorgeous_Text_DaisyIntro::
    .string "¡Con mis manos, crearé mi propia\n"
    .string "victoria!$"

FiveIsland_ResortGorgeous_Text_DaisyDefeat::
    .string "Qué vergüenza...\n"
    .string "Estoy como un tomate...$"

FiveIsland_ResortGorgeous_Text_DaisyPostBattle::
    .string "¡Se me han caído todos los tubos\n"
    .string "de pintura!$"

FiveIsland_ResortGorgeous_Text_CelinaIntro::
    .string "Perdona, estoy pintando,\n"
    .string "¿te puedes quitar de ahí?$"

FiveIsland_ResortGorgeous_Text_CelinaDefeat::
    .string "Qué forma de perder...\n"
    .string "Estoy abatida.$"

FiveIsland_ResortGorgeous_Text_CelinaPostBattle::
    .string "GALENIA, por favor gira un poco\n"
    .string "la cabeza. ¡Así, perfecto!$"

FiveIsland_ResortGorgeous_Text_RaynaIntro::
    .string "Mmm...\n"
    .string "Este ángulo no es el mejor...$"

FiveIsland_ResortGorgeous_Text_RaynaDefeat::
    .string "Oh... Qué tristeza tan profunda...$"

FiveIsland_ResortGorgeous_Text_RaynaPostBattle::
    .string "El mar y el cielo son tan...\n"
    .string "volubles.\l"
    .string "Es difícil plasmarlos en el lienzo.$"

FiveIsland_ResortGorgeous_Text_JackiIntro::
    .string "Estoy de visita en la zona de\n"
    .string "recreo, para tu información.$"

FiveIsland_ResortGorgeous_Text_JackiDefeat::
    .string "¡Qué fuerte eres!$"

FiveIsland_ResortGorgeous_Text_JackiPostBattle::
    .string "Es un auténtico placer combatir\n"
    .string "disfrutando de la brisa marina.$"

FiveIsland_ResortGorgeous_Text_GillianIntro::
    .string "Estoy pensando en construir una\n"
    .string "piscina para mis POKéMON.$"

FiveIsland_ResortGorgeous_Text_GillianDefeat::
    .string "¡Aaaaaaah! ¡Qué bochorno!$"

FiveIsland_ResortGorgeous_Text_GillianPostBattle::
    .string "Una piscina no estaría nada mal,\n"
    .string "pero un solárium sería fabuloso.$"

FiveIsland_ResortGorgeous_Text_DestinIntro::
    .string "No hay nadie que corra más rápido\n"
    .string "que yo.$"

FiveIsland_ResortGorgeous_Text_DestinDefeat::
    .string "¡Vaya, la velocidad no lo es todo!$"

FiveIsland_ResortGorgeous_Text_DestinPostBattle::
    .string "Cuando corro en el sentido del\n"
    .string "viento es como si volara.$"

FiveIsland_ResortGorgeous_Text_TobyIntro::
    .string "La fauna marina de esta zona\n"
    .string "me fascina.$"

FiveIsland_ResortGorgeous_Text_TobyDefeat::
    .string "¡Que me pase esto a mí!$"

FiveIsland_ResortGorgeous_Text_TobyPostBattle::
    .string "Me parece que te lo has tomado\n"
    .string "demasiado en serio.$"

FiveIsland_ResortGorgeous_Text_SelphyThanksYouMayGoNow::
    .string "CONSU: Gracias.\p"
    .string "Ya te puedes ir.$"

FiveIsland_ResortGorgeous_Text_SelphysHouse::
    .string "CASA de CONSU$"
