FiveIsland_ResortGorgeous_Text_DaisyIntro::
    .ifdef ENGLISH
    .string "With these hands, I will create\n"
    .string "my victory!$"
    .endif
    .ifdef SPANISH
    .string "¡Con mis manos, crearé mi propia\n"
    .string "victoria!$"
    .endif

FiveIsland_ResortGorgeous_Text_DaisyDefeat::
    .ifdef ENGLISH
    .string "The shame of this…\n"
    .string "I'm red-faced…$"
    .endif
    .ifdef SPANISH
    .string "Qué vergüenza...\n"
    .string "Estoy como un tomate...$"
    .endif

FiveIsland_ResortGorgeous_Text_DaisyPostBattle::
    .ifdef ENGLISH
    .string "Uh-oh, my paint tubes have\n"
    .string "scattered everywhere!$"
    .endif
    .ifdef SPANISH
    .string "¡Se me han caído todos los tubos\n"
    .string "de pintura!$"
    .endif

FiveIsland_ResortGorgeous_Text_CelinaIntro::
    .ifdef ENGLISH
    .string "Excuse me!\n"
    .string "I'm trying to paint.\l"
    .string "Please keep out of my sight!$"
    .endif
    .ifdef SPANISH
    .string "Perdona, estoy pintando,\n"
    .string "¿te puedes quitar de ahí?$"
    .endif

FiveIsland_ResortGorgeous_Text_CelinaDefeat::
    .ifdef ENGLISH
    .string "This loss…\n"
    .string "I feel like I'm whiting out…$"
    .endif
    .ifdef SPANISH
    .string "Qué forma de perder...\n"
    .string "Estoy abatida.$"
    .endif

FiveIsland_ResortGorgeous_Text_CelinaPostBattle::
    .ifdef ENGLISH
    .string "GILLIAN?\n"
    .string "Please tilt your head slightly…\l"
    .string "There! That's the look I want!$"
    .endif
    .ifdef SPANISH
    .string "GALENIA, por favor gira un poco\n"
    .string "la cabeza. ¡Así, perfecto!$"
    .endif

FiveIsland_ResortGorgeous_Text_RaynaIntro::
    .ifdef ENGLISH
    .string "Hmm…\n"
    .string "The angle, it is not quite there…$"
    .endif
    .ifdef SPANISH
    .string "Mmm...\n"
    .string "Este ángulo no es el mejor...$"
    .endif

FiveIsland_ResortGorgeous_Text_RaynaDefeat::
    .ifdef ENGLISH
    .string "Oh…\n"
    .string "My feelings, they are blue…$"
    .endif
    .ifdef SPANISH
    .string "Oh... Qué tristeza tan profunda...$"
    .endif

FiveIsland_ResortGorgeous_Text_RaynaPostBattle::
    .ifdef ENGLISH
    .string "The sky and the sea…\n"
    .string "They are so fickle.\p"
    .string "Their changing expressions make\n"
    .string "them difficult to capture.$"
    .endif
    .ifdef SPANISH
    .string "El mar y el cielo son tan...\n"
    .string "volubles.\l"
    .string "Es difícil plasmarlos en el lienzo.$"
    .endif

FiveIsland_ResortGorgeous_Text_JackiIntro::
    .ifdef ENGLISH
    .string "I am visiting my friend's retreat,\n"
    .string "if you must know.$"
    .endif
    .ifdef SPANISH
    .string "Estoy de visita en la zona de\n"
    .string "recreo, para tu información.$"
    .endif

FiveIsland_ResortGorgeous_Text_JackiDefeat::
    .ifdef ENGLISH
    .string "Oh, my, so strong.$"
    .endif
    .ifdef SPANISH
    .string "¡Qué fuerte eres!$"
    .endif

FiveIsland_ResortGorgeous_Text_JackiPostBattle::
    .ifdef ENGLISH
    .string "I find it pleasurable to leisurely\n"
    .string "battle in the gentle sea breeze.$"
    .endif
    .ifdef SPANISH
    .string "Es un auténtico placer combatir\n"
    .string "disfrutando de la brisa marina.$"
    .endif

FiveIsland_ResortGorgeous_Text_GillianIntro::
    .ifdef ENGLISH
    .string "I'm thinking of having a pool\n"
    .string "made specially for POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "Estoy pensando en construir una\n"
    .string "piscina para mis POKéMON.$"
    .endif

FiveIsland_ResortGorgeous_Text_GillianDefeat::
    .ifdef ENGLISH
    .string "Oh, my goodness gracious!$"
    .endif
    .ifdef SPANISH
    .string "¡Aaaaaaah! ¡Qué bochorno!$"
    .endif

FiveIsland_ResortGorgeous_Text_GillianPostBattle::
    .ifdef ENGLISH
    .string "A pool would be nice, but I must\n"
    .string "say, a sun-room may be sublime.$"
    .endif
    .ifdef SPANISH
    .string "Una piscina no estaría nada mal,\n"
    .string "pero un solárium sería fabuloso.$"
    .endif

FiveIsland_ResortGorgeous_Text_DestinIntro::
    .ifdef ENGLISH
    .string "I'm a good runner.\n"
    .string "I'm really fast!$"
    .endif
    .ifdef SPANISH
    .string "No hay nadie que corra más rápido\n"
    .string "que yo.$"
    .endif

FiveIsland_ResortGorgeous_Text_DestinDefeat::
    .ifdef ENGLISH
    .string "Oops!\n"
    .string "I rushed things!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya, la velocidad no lo es todo!$"
    .endif

FiveIsland_ResortGorgeous_Text_DestinPostBattle::
    .ifdef ENGLISH
    .string "When I run with the wind, it feels\n"
    .string "like I could fly!$"
    .endif
    .ifdef SPANISH
    .string "Cuando corro en el sentido del\n"
    .string "viento es como si volara.$"
    .endif

FiveIsland_ResortGorgeous_Text_TobyIntro::
    .ifdef ENGLISH
    .string "I say, this marine life here at\n"
    .string "this resort agrees with me.$"
    .endif
    .ifdef SPANISH
    .string "La fauna marina de esta zona\n"
    .string "me fascina.$"
    .endif

FiveIsland_ResortGorgeous_Text_TobyDefeat::
    .ifdef ENGLISH
    .string "That's a shocker!\n"
    .string "You must be joking.$"
    .endif
    .ifdef SPANISH
    .string "¡Que me pase esto a mí!$"
    .endif

FiveIsland_ResortGorgeous_Text_TobyPostBattle::
    .ifdef ENGLISH
    .string "Getting so serious over this…\n"
    .string "How nonsensical.$"
    .endif
    .ifdef SPANISH
    .string "Me parece que te lo has tomado\n"
    .string "demasiado en serio.$"
    .endif

FiveIsland_ResortGorgeous_Text_SelphyThanksYouMayGoNow::
    .ifdef ENGLISH
    .string "SELPHY: Thank you.\p"
    .string "You may go now.$"
    .endif
    .ifdef SPANISH
    .string "CONSU: Gracias.\p"
    .string "Ya te puedes ir.$"
    .endif

FiveIsland_ResortGorgeous_Text_SelphysHouse::
    .ifdef ENGLISH
    .string "SELPHY'S HOUSE$"
    .endif
    .ifdef SPANISH
    .string "CASA de CONSU$"
    .endif

