Route18_EastEntrance_2F_Text_PalletTownInWest::
    .ifdef ENGLISH
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "PALLET TOWN is in the west.$"
    .endif
    .ifdef SPANISH
    .string "Has usado los prismáticos...\p"
    .string "¡PUEBLO PALETA está al oeste!$"
    .endif

Route18_EastEntrance_2F_Text_PeopleSwimming::
    .ifdef ENGLISH
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "There are people swimming.$"
    .endif
    .ifdef SPANISH
    .string "Has usado los prismáticos...\p"
    .string "¡Hay gente nadando!$"
    .endif

