CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
    .ifdef ENGLISH
    .string "REPEL not only keeps bugs away,\n"
    .string "it also works on weak POKéMON.\p"
    .string "Put your strongest POKéMON at the\n"
    .string "left of the POKéMON LIST.\p"
    .string "If your first POKéMON is strong,\n"
    .string "REPEL's effect is boosted.$"
    .endif
    .ifdef SPANISH
    .string "Usa el REPELENTE para evitar a los\n"
    .string "bichos y a los POKéMON débiles.\p"
    .string "¡Pon a tu POKéMON más fuerte el\n"
    .string "primero de la lista para conseguir\l"
    .string "mejores resultados!\p"
    .string "Si tu primer POKéMON es fuerte,\n"
    .string "el REPELENTE tendrá mayor efecto.$"
    .endif

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
    .ifdef ENGLISH
    .string "Do you know about RARE CANDY?\n"
    .string "They don't sell it in shops.\p"
    .string "I think it makes POKéMON grow\n"
    .string "very quickly all of a sudden.$"
    .endif
    .ifdef SPANISH
    .string "¿Has visto algún CARAMELORARO?\p"
    .string "¡Dicen que los POKéMON suben\n"
    .string "un nivel si se comen uno!$"
    .endif

