Route11_Text_HugoIntro::
    .ifdef ENGLISH
    .string "Win, lose, or draw!$"
    .endif
    .ifdef SPANISH
    .string "¡Gana, pierde o empata!$"
    .endif

Route11_Text_HugoDefeat::
    .ifdef ENGLISH
    .string "Atcha!\n"
    .string "Didn't go my way!$"
    .endif
    .ifdef SPANISH
    .string "¡Vale!\n"
    .string "¡Has ganado!$"
    .endif

Route11_Text_HugoPostBattle::
    .ifdef ENGLISH
    .string "POKéMON is life!\n"
    .string "And to live is to play games!$"
    .endif
    .ifdef SPANISH
    .string "¡Los POKéMON son vida!\n"
    .string "¡Y vivir es jugar!$"
    .endif

Route11_Text_JasperIntro::
    .ifdef ENGLISH
    .string "Competition!\n"
    .string "I can't get enough!$"
    .endif
    .ifdef SPANISH
    .string "¡Competición!\n"
    .string "¡No me canso de competir!$"
    .endif

Route11_Text_JasperDefeat::
    .ifdef ENGLISH
    .string "I had a chance!$"
    .endif
    .ifdef SPANISH
    .string "¡He perdido la oportunidad!$"
    .endif

Route11_Text_JasperPostBattle::
    .ifdef ENGLISH
    .string "You can't be a coward in the world\n"
    .string "of POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡No se puede ser cobarde\n"
    .string "en el mundo de los POKéMON!$"
    .endif

Route11_Text_EddieIntro::
    .ifdef ENGLISH
    .string "Let's go, but don't cheat!$"
    .endif
    .ifdef SPANISH
    .string "¡Vamos allá, pero no hagas\n"
    .string "trampas!$"
    .endif

Route11_Text_EddieDefeat::
    .ifdef ENGLISH
    .string "Huh?\n"
    .string "That's not right!$"
    .endif
    .ifdef SPANISH
    .string "¿Qué?\n"
    .string "¡No puede ser!$"
    .endif

Route11_Text_EddiePostBattle::
    .ifdef ENGLISH
    .string "I did my best.\n"
    .string "I have no regrets.$"
    .endif
    .ifdef SPANISH
    .string "¡He hecho lo que he podido!\n"
    .string "¡Y no me arrepiento!$"
    .endif

Route11_Text_BraxtonIntro::
    .ifdef ENGLISH
    .string "Careful!\n"
    .string "I'm laying down some cables!$"
    .endif
    .ifdef SPANISH
    .string "¡Cuidado!\n"
    .string "¡Estoy colocando unos cables!$"
    .endif

Route11_Text_BraxtonDefeat::
    .ifdef ENGLISH
    .string "That was electric!$"
    .endif
    .ifdef SPANISH
    .string "¡Electrizante!$"
    .endif

Route11_Text_BraxtonPostBattle::
    .ifdef ENGLISH
    .string "Spread the word to save energy!$"
    .endif
    .ifdef SPANISH
    .string "¡Di a todos que ahorren energía!$"
    .endif

Route11_Text_DillonIntro::
    .ifdef ENGLISH
    .string "I just became a TRAINER.\n"
    .string "But, I think I can win.$"
    .endif
    .ifdef SPANISH
    .string "¡Me acabo de hacer ENTRENADOR!\n"
    .string "¡Pero creo que puedo ganar!$"
    .endif

Route11_Text_DillonDefeat::
    .ifdef ENGLISH
    .string "My POKéMON couldn't win…\n"
    .string "Haven't they grown enough?$"
    .endif
    .ifdef SPANISH
    .string "¡Mis POKéMON han perdido!$"
    .endif

Route11_Text_DillonPostBattle::
    .ifdef ENGLISH
    .string "What now?\n"
    .string "Leave me alone!$"
    .endif
    .ifdef SPANISH
    .string "¿Qué quieres?\n"
    .string "¡Déjame en paz!$"
    .endif

Route11_Text_DirkIntro::
    .ifdef ENGLISH
    .string "Fwahaha!\n"
    .string "I have never lost!$"
    .endif
    .ifdef SPANISH
    .string "¡Ja, ja, ja!\n"
    .string "¡No he perdido nunca!$"
    .endif

Route11_Text_DirkDefeat::
    .ifdef ENGLISH
    .string "My first loss!$"
    .endif
    .ifdef SPANISH
    .string "¡La primera vez que pierdo!$"
    .endif

Route11_Text_DirkPostBattle::
    .ifdef ENGLISH
    .string "You were just lucky, that's all.$"
    .endif
    .ifdef SPANISH
    .string "¡Has tenido mucha suerte!$"
    .endif

Route11_Text_DarianIntro::
    .ifdef ENGLISH
    .string "I have never won before…$"
    .endif
    .ifdef SPANISH
    .string "Nunca he ganado...$"
    .endif

Route11_Text_DarianDefeat::
    .ifdef ENGLISH
    .string "I saw this coming…$"
    .endif
    .ifdef SPANISH
    .string "Lo veía venir...$"
    .endif

Route11_Text_DarianPostBattle::
    .ifdef ENGLISH
    .string "I was unlucky, as always.$"
    .endif
    .ifdef SPANISH
    .string "Has tenido mucha suerte.$"
    .endif

Route11_Text_YasuIntro::
    .ifdef ENGLISH
    .string "I'm the best in my class.\n"
    .string "I train every morning.$"
    .endif
    .ifdef SPANISH
    .string "¡Soy el mejor de mi clase!$"
    .endif

Route11_Text_YasuDefeat::
    .ifdef ENGLISH
    .string "Darn!\n"
    .string "My POKéMON need to be stronger!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya! ¡Mis POKéMON deberían\n"
    .string "ser más fuertes!$"
    .endif

Route11_Text_YasuPostBattle::
    .ifdef ENGLISH
    .string "There's a fat POKéMON that comes\n"
    .string "down from the mountains.\p"
    .string "I bet it'd be strong if you can\n"
    .string "catch it.$"
    .endif
    .ifdef SPANISH
    .string "Hay un POKéMON muy gordo\n"
    .string "que baja de las montañas.\p"
    .string "Seguro que es muy fuerte.$"
    .endif

Route11_Text_BernieIntro::
    .ifdef ENGLISH
    .string "Watch out for live wires!$"
    .endif
    .ifdef SPANISH
    .string "¡Cuidado con esos cables!$"
    .endif

Route11_Text_BernieDefeat::
    .ifdef ENGLISH
    .string "Whoa!\n"
    .string "You spark plug!$"
    .endif
    .ifdef SPANISH
    .string "¡Uaauu!\n"
    .string "¡Vaya chispazo!$"
    .endif

Route11_Text_BerniePostBattle::
    .ifdef ENGLISH
    .string "Well, better get back to work.$"
    .endif
    .ifdef SPANISH
    .string "¡Más vale que vuelva al trabajo!$"
    .endif

Route11_Text_DaveIntro::
    .ifdef ENGLISH
    .string "I raised my POKéMON carefully.\n"
    .string "They should be ready by now!$"
    .endif
    .ifdef SPANISH
    .string "¡Mis POKéMON ya deberían\n"
    .string "estar listos!$"
    .endif

Route11_Text_DaveDefeat::
    .ifdef ENGLISH
    .string "Bye-bye!\n"
    .string "Thank you, and good-bye!$"
    .endif
    .ifdef SPANISH
    .string "¡Soy demasiado joven!$"
    .endif

Route11_Text_DavePostBattle::
    .ifdef ENGLISH
    .string "Tch…\n"
    .string "I better go find stronger ones!$"
    .endif
    .ifdef SPANISH
    .string "¡Voy a buscarme unos más fuertes!$"
    .endif

Route11_Text_DiglettsCave::
    .ifdef ENGLISH
    .string "DIGLETT'S CAVE$"
    .endif
    .ifdef SPANISH
    .string "CUEVA DE DIGLETT$"
    .endif

