CeladonCity_House1_Text_SlotsReelInTheDough::
    .ifdef ENGLISH
    .string "Hehehe!\p"
    .string "The slots just reel in the dough,\n"
    .string "big-time!$"
    .endif
    .ifdef SPANISH
    .string "¡Jejeje!\p"
    .string "¡He ganado una pasta!\n"
    .string "¡Bravo!$"
    .endif

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
    .ifdef ENGLISH
    .string "CHIEF!\p"
    .string "We just shipped two thousand\n"
    .string "more POKéMON as slot prizes\l"
    .string "again today!$"
    .endif
    .ifdef SPANISH
    .string "¡JEFE!\p"
    .string "¡Acabamos de enviar 2.000\n"
    .string "POKéMON a modo de premio!$"
    .endif

CeladonCity_House1_Text_DontTouchGameCornerPoster::
    .ifdef ENGLISH
    .string "Don't touch the poster at the GAME\n"
    .string "CORNER!\p"
    .string "There's no secret switch behind it!$"
    .endif
    .ifdef SPANISH
    .string "¡No toques el cartel del CASINO!\p"
    .string "¡No hay ningún botón secreto\n"
    .string "detrás!$"
    .endif

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of DIGLETT.", and is removed altogether in FRLG
Text_ItsABuddhistAltar::
    .string "ぶつだん　だ‥$"
