SixIsland_OutcastIsland_Text_RocketIntro::
    .ifdef ENGLISH
    .string "There're no rare POKéMON around\n"
    .string "these parts! Not a one!\p"
    .string "That burns me up, man.\n"
    .string "I'll take it out on you!$"
    .endif
    .ifdef SPANISH
    .string "Por aquí no hay ni un sólo\n"
    .string "POKéMON raro. ¡Ni uno!\p"
    .string "¡Estoy hasta el gorro de buscar!\n"
    .string "¡Te ha tocado pagar el mosqueo,\l"
    .string "lo siento!$"
    .endif

SixIsland_OutcastIsland_Text_RocketDefeat::
    .ifdef ENGLISH
    .string "…Huh?$"
    .endif
    .ifdef SPANISH
    .string "¡¿Qué?!$"
    .endif

SixIsland_OutcastIsland_Text_RocketPostBattle::
    .ifdef ENGLISH
    .string "So listen, you haven't seen any\n"
    .string "rare POKéMON, have you?$"
    .endif
    .ifdef SPANISH
    .string "Tú no has visto ningún POKéMON\n"
    .string "raro, ¿no?$"
    .endif

SixIsland_OutcastIsland_Text_TylorIntro::
    .ifdef ENGLISH
    .string "I'm having no luck at all.\n"
    .string "A battle'd be a change of pace!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué mala suerte tengo hoy!\n"
    .string "¡Igual la cosa cambia si luchamos!$"
    .endif

SixIsland_OutcastIsland_Text_TylorDefeat::
    .ifdef ENGLISH
    .string "Nope, no luck at all…$"
    .endif
    .ifdef SPANISH
    .string "Nada, hoy no es mi día.$"
    .endif

SixIsland_OutcastIsland_Text_TylorPostBattle::
    .ifdef ENGLISH
    .string "I can't very well go home without\n"
    .string "catching something, though.$"
    .endif
    .ifdef SPANISH
    .string "¡Pero es que no puedo volver\n"
    .string "a casa con las manos vacías!$"
    .endif

SixIsland_OutcastIsland_Text_MymoIntro::
    .ifdef ENGLISH
    .string "Gasp… Gasp…\p"
    .string "I swam here from SIX ISLE PORT\n"
    .string "in one go.$"
    .endif
    .ifdef SPANISH
    .string "Ufff... Ufff...\p"
    .string "Vengo nadando desde el PUERTO\n"
    .string "de ISLA EXTA sin parar.$"
    .endif

SixIsland_OutcastIsland_Text_MymoDefeat::
    .ifdef ENGLISH
    .string "Gasp…\n"
    .string "Gasp…$"
    .endif
    .ifdef SPANISH
    .string "Ufff...\n"
    .string "Ufff...$"
    .endif

SixIsland_OutcastIsland_Text_MymoPostBattle::
    .ifdef ENGLISH
    .string "I'm only at the halfway point…\n"
    .string "I'm beat…$"
    .endif
    .ifdef SPANISH
    .string "Voy por la mitad...\n"
    .string "Y ya no puedo más...$"
    .endif

SixIsland_OutcastIsland_Text_NicoleIntro::
    .ifdef ENGLISH
    .string "It's not so easy sending POKéMON\n"
    .string "out while swimming, you know?$"
    .endif
    .ifdef SPANISH
    .string "No es fácil sacar POKéMON mientras\n"
    .string "se nada, ¿lo sabías?$"
    .endif

SixIsland_OutcastIsland_Text_NicoleDefeat::
    .ifdef ENGLISH
    .string "I didn't lose to you at swimming.\n"
    .string "This doesn't bother me.$"
    .endif
    .ifdef SPANISH
    .string "He perdido, pero seguro que\n"
    .string "nadando no me ganas.$"
    .endif

SixIsland_OutcastIsland_Text_NicolePostBattle::
    .ifdef ENGLISH
    .string "Are you headed for the island up\n"
    .string "past here?\p"
    .string "I didn't see anything interesting\n"
    .string "there.$"
    .endif
    .ifdef SPANISH
    .string "¿Vas a la isla que hay al norte?\n"
    .string "Yo no vi nada de interés.$"
    .endif

SixIsland_OutcastIsland_Text_AvaIntro::
    .ifdef ENGLISH
    .string "AVA: Let's have a two-on-two\n"
    .string "marine battle!$"
    .endif
    .ifdef SPANISH
    .string "ALI: ¡Vamos a echarnos un combate\n"
    .string "disfrutando de la brisa marina!$"
    .endif

SixIsland_OutcastIsland_Text_AvaDefeat::
    .ifdef ENGLISH
    .string "AVA: Oh, you're amazing!\n"
    .string "Even better, you're on your own!$"
    .endif
    .ifdef SPANISH
    .string "ALI: ¡Eres increíble! ¡Además\n"
    .string "no te hace falta nadie de apoyo!$"
    .endif

SixIsland_OutcastIsland_Text_AvaPostBattle::
    .ifdef ENGLISH
    .string "AVA: You know, I do prefer the\n"
    .string "sea over any pool.$"
    .endif
    .ifdef SPANISH
    .string "ALI: Prefiero mil veces el mar\n"
    .string "antes que la piscina.$"
    .endif

SixIsland_OutcastIsland_Text_AvaNotEnoughMons::
    .ifdef ENGLISH
    .string "AVA: You're challenging us to\n"
    .string "a battle?\p"
    .string "You'll need at least two POKéMON\n"
    .string "if you want to do that.$"
    .endif
    .ifdef SPANISH
    .string "ALI: ¿Quieres luchar con nosotros?\p"
    .string "Pues te hacen falta dos POKéMON\n"
    .string "por lo menos para luchar.$"
    .endif

SixIsland_OutcastIsland_Text_GebIntro::
    .ifdef ENGLISH
    .string "GEB: Big Sister, help!\n"
    .string "Please battle with me!$"
    .endif
    .ifdef SPANISH
    .string "ROS: Hermanita, ¡ayuda!\n"
    .string "¡Lucha conmigo!$"
    .endif

SixIsland_OutcastIsland_Text_GebDefeat::
    .ifdef ENGLISH
    .string "GEB: Wow, Big Sister, this person's\n"
    .string "really good!$"
    .endif
    .ifdef SPANISH
    .string "ROS: Hermanita, ¡qué fuerte es!$"
    .endif

SixIsland_OutcastIsland_Text_GebPostBattle::
    .ifdef ENGLISH
    .string "GEB: I'm hanging onto my sister\n"
    .string "because I can't touch the bottom.$"
    .endif
    .ifdef SPANISH
    .string "ROS: Yo me agarro a mi hermanita,\n"
    .string "porque no hago pie.$"
    .endif

SixIsland_OutcastIsland_Text_GebNotEnoughMons::
    .ifdef ENGLISH
    .string "GEB: Please battle against me and\n"
    .string "my sister!\p"
    .string "…Oh, you don't have two POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "ROS: ¡Lucha con mi hermanita\n"
    .string "y conmigo!\p"
    .string "Ah..., ¿no tienes dos POKéMON?\n"
    .string "Entonces, no.$"
    .endif
