Route14_Text_CarterIntro::
	.string "Damit POKéMON starke Attacken\n"
	.string "erlernen, muss man TM einsetzen!$"

Route14_Text_CarterDefeat::
	.string "Ich war zu schlecht!$"

Route14_Text_CarterPostBattle::
	.string "Eine durch eine VM erlernte Attacke\n"
	.string "können POKéMON nicht so leicht\l"
	.string "wieder vergessen!$"

Route14_Text_MitchIntro::
	.string "Meine Vogel-POKéMON sind gut auf\n"
	.string "Kämpfe vorbereitet!$"

Route14_Text_MitchDefeat::
	.string "Sie waren nicht stark genug...$"

Route14_Text_MitchPostBattle::
	.string "Sie müssen stärkere Attacken\n"
	.string "lernen!$"

Route14_Text_BeckIntro::
	.string "In PRISMANIA CITY kann man TMs\n"
	.string "kaufen.\p"
	.string "VMs besitzen allerdings nur wenige\n"
	.string "Personen.$"

Route14_Text_BeckDefeat::
	.string "Ohh! So ein Mist!$"

Route14_Text_BeckPostBattle::
	.string "Bringe POKéMON ihrem Element\n"
	.string "entsprechende Attacken bei, um ihre\l"
	.string "volle Stärke auszunutzen!$"

Route14_Text_MarlonIntro::
	.string "Hast du einem Vogel-POKéMON\n"
	.string "schon das FLIEGEN beigebracht?$"

Route14_Text_MarlonDefeat::
	.string "War das eine Bruchlandung!$"

Route14_Text_MarlonPostBattle::
	.string "Meine Leidenschaft sind Vogel-\n"
	.string "POKéMON!$"

Route14_Text_DonaldIntro::
	.string "Hast du die Legende von den\n"
	.string "Illusionen mit Flügeln gehört?$"

Route14_Text_DonaldDefeat::
	.string "Warum hab ich verloren?$"

Route14_Text_DonaldPostBattle::
	.string "Nun, die Illusionen mit Flügeln sind\n"
	.string "die legendären Vogel-POKéMON.\p"
	.string "Es gibt drei: ARKTOS, ZAPDOS\n"
	.string "und LAVADOS.$"

Route14_Text_BennyIntro::
	.string "Ich will nicht unbedingt, aber lass\n"
	.string "uns dennoch kämpfen!$"

Route14_Text_BennyDefeat::
	.string "Ich wusste, ich würde verlieren!$"

Route14_Text_BennyPostBattle::
	.string "Längerfristig ist es egal, ob man\n"
	.string "gewinnt oder verliert!$"

Route14_Text_LukasIntro::
	.string "Los, los! Lass uns kämpfen. Auf in\n"
	.string "den Kampf! Los!$"

Route14_Text_LukasDefeat::
	.string "Arrgh!\n"
	.string "Hau bloß ab!$"

Route14_Text_LukasPostBattle::
	.string "Was, was, was?\n"
	.string "Was willst du?$"

Route14_Text_IsaacIntro::
	.string "Sehr gut!\n"
	.string "Ich brauche einen Zeitvertreib!$"

Route14_Text_IsaacDefeat::
	.string "Du hast mich besiegt?\n"
	.string "Oh Mann!$"

Route14_Text_IsaacPostBattle::
	.string "Es ist ganz schön mühselig,\n"
	.string "POKéMON zu trainieren!$"

Route14_Text_GeraldIntro::
	.string "Wir kommen öfter her, weil es hier\n"
	.string "so unglaublich viel Platz gibt!$"

Route14_Text_GeraldDefeat::
	.string "Kurz und schmerzlos!$"

Route14_Text_GeraldPostBattle::
	.string "Cool!\n"
	.string "Deine POKéMON sind wirklich stark!\p"
	.string "Macht geht vor Recht!\n"
	.string "Du hast es begriffen!$"

Route14_Text_MalikIntro::
	.string "Ein POKéMON-KAMPF?\n"
	.string "Cool! Leg los, Balg!$"

Route14_Text_MalikDefeat::
	.string "Voll erwischt!$"

Route14_Text_MalikPostBattle::
	.string "Du gegen mich!\n"
	.string "Du weißt, wer gewinnt!$"

Route14_Text_RouteSign::
	.string "ROUTE 14\n"
	.string "WESTEN: FUCHSANIA CITY$"

Route14_Text_KiriIntro::
	.string "BERTA: ENKE, lass es uns\n"
	.string "wirklich zusammen versuchen.$"

Route14_Text_KiriDefeat::
	.string "BERTA: Wimmer…\n"
	.string "Wir haben verloren, oder?$"

Route14_Text_KiriPostBattle::
	.string "BERTA: Haben wir\n"
	.string "meinetwegen verloren?$"

Route14_Text_KiriNotEnoughMons::
	.string "BERTA: Wir können kämpfen, wenn\n"
	.string "du zwei POKéMON hast.$"

Route14_Text_JanIntro::
	.string "ENKE: BERTA, los jetzt!\n"
	.string "Wir müssen uns anstrengen!$"

Route14_Text_JanDefeat::
	.string "ENKE: Argh!\n"
	.string "Oh, nein!$"

Route14_Text_JanPostBattle::
	.string "ENKE: Weine nicht, BERTA!\n"
	.string "Wir strengen uns beim nächsten\l"
	.string "Mal noch mehr an!$"

Route14_Text_JanNotEnoughMons::
	.string "ENKE: Du möchtest kämpfen?\n"
	.string "Du hast nicht genug POKéMON!$"

