Route14_Text_CarterIntro::
    .ifdef ENGLISH
    .string "You need to use TMs to teach good\n"
    .string "moves to POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Usa las MT para enseñar a tus\n"
    .string "POKéMON buenos movimientos!$"
    .endif

Route14_Text_CarterDefeat::
    .ifdef ENGLISH
    .string "Not good enough quite yet.$"
    .endif
    .ifdef SPANISH
    .string "¡No lo he hecho muy bien!$"
    .endif

Route14_Text_CarterPostBattle::
    .ifdef ENGLISH
    .string "You have some HMs, right? POKéMON\n"
    .string "can't forget those moves easily.$"
    .endif
    .ifdef SPANISH
    .string "Tienes MO, ¿no? Los POKéMON\n"
    .string "jamás olvidarán esos movimientos.$"
    .endif

Route14_Text_MitchIntro::
    .ifdef ENGLISH
    .string "My bird POKéMON should be ready\n"
    .string "for battle.$"
    .endif
    .ifdef SPANISH
    .string "Mis pájaros POKéMON deberían\n"
    .string "poder luchar.$"
    .endif

Route14_Text_MitchDefeat::
    .ifdef ENGLISH
    .string "Not ready yet!$"
    .endif
    .ifdef SPANISH
    .string "¡No estoy listo!$"
    .endif

Route14_Text_MitchPostBattle::
    .ifdef ENGLISH
    .string "My bird POKéMON need to learn\n"
    .string "better moves.$"
    .endif
    .ifdef SPANISH
    .string "Necesitan saber mejores ataques.$"
    .endif

Route14_Text_BeckIntro::
    .ifdef ENGLISH
    .string "They have TMs on sale at the\n"
    .string "CELADON DEPT. STORE.\p"
    .string "TMs aren't really rare, but not\n"
    .string "many people have HMs.$"
    .endif
    .ifdef SPANISH
    .string "¡Se venden MT en AZULONA!\n"
    .string "¡Pero pocas personas tienen MO!$"
    .endif

Route14_Text_BeckDefeat::
    .ifdef ENGLISH
    .string "Aww, bummer!$"
    .endif
    .ifdef SPANISH
    .string "¡Ayy! ¡Qué mal!$"
    .endif

Route14_Text_BeckPostBattle::
    .ifdef ENGLISH
    .string "Try teaching POKéMON a move that's\n"
    .string "the same type as it.\p"
    .string "That apparently boosts the power\n"
    .string "of the move.$"
    .endif
    .ifdef SPANISH
    .string "Enseña a tus POKéMON ataques\n"
    .string "de sus mismos tipos para conseguir\l"
    .string "más potencia.$"
    .endif

Route14_Text_MarlonIntro::
    .ifdef ENGLISH
    .string "Have you taught your bird POKéMON\n"
    .string "how to FLY?\p"
    .string "You'll be able to soar with it into\n"
    .string "the sky!$"
    .endif
    .ifdef SPANISH
    .string "¿Has enseñado a VOLAR a tus\n"
    .string "pájaros POKéMON?\p"
    .string "¡Es genial para ir por el cielo!$"
    .endif

Route14_Text_MarlonDefeat::
    .ifdef ENGLISH
    .string "Shot down in flames!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué forma de perder!$"
    .endif

Route14_Text_MarlonPostBattle::
    .ifdef ENGLISH
    .string "Bird POKéMON are my one true love.\n"
    .string "I don't want to raise anything else.$"
    .endif
    .ifdef SPANISH
    .string "¡Adoro a los pájaros POKéMON!\n"
    .string "¡Son los que me gusta criar!$"
    .endif

Route14_Text_DonaldIntro::
    .ifdef ENGLISH
    .string "Have you heard the legend of the\n"
    .string "winged mirages?$"
    .endif
    .ifdef SPANISH
    .string "¿Has oído hablar de los\n"
    .string "misteriosos seres alados?$"
    .endif

Route14_Text_DonaldDefeat::
    .ifdef ENGLISH
    .string "Why?\n"
    .string "Why'd I lose?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué?\n"
    .string "¿Cómo he podido perder?$"
    .endif

Route14_Text_DonaldPostBattle::
    .ifdef ENGLISH
    .string "Well, the winged mirages are the\n"
    .string "legendary bird POKéMON.\p"
    .string "There are three of them: ARTICUNO,\n"
    .string "ZAPDOS, and MOLTRES.$"
    .endif
    .ifdef SPANISH
    .string "Los misteriosos seres alados son\n"
    .string "legendarios pájaros POKéMON.\p"
    .string "Hay tres: ARTICUNO, ZAPDOS\n"
    .string "y MOLTRES.$"
    .endif

Route14_Text_BennyIntro::
    .ifdef ENGLISH
    .string "I'm not into it, but okay.\n"
    .string "Let's go!$"
    .endif
    .ifdef SPANISH
    .string "¡No me apetece!\n"
    .string "Pero vale.$"
    .endif

Route14_Text_BennyDefeat::
    .ifdef ENGLISH
    .string "I knew it!$"
    .endif
    .ifdef SPANISH
    .string "¡Lo sabía!$"
    .endif

Route14_Text_BennyPostBattle::
    .ifdef ENGLISH
    .string "Winning, losing… It's insignificant\n"
    .string "under this huge sky.$"
    .endif
    .ifdef SPANISH
    .string "¡No es que sea tan importante\n"
    .string "ganar o perder!$"
    .endif

Route14_Text_LukasIntro::
    .ifdef ENGLISH
    .string "C'mon, c'mon.\n"
    .string "Let's go, let's go, let's go!$"
    .endif
    .ifdef SPANISH
    .string "¡Venga, venga!\n"
    .string "¡Vamos, vamos! ¡Adelante!$"
    .endif

Route14_Text_LukasDefeat::
    .ifdef ENGLISH
    .string "Arrg!\n"
    .string "Lost! Get lost!$"
    .endif
    .ifdef SPANISH
    .string "¡Arg!\n"
    .string "¡He perdido! ¡Lárgate!$"
    .endif

Route14_Text_LukasPostBattle::
    .ifdef ENGLISH
    .string "What, what, what?\n"
    .string "What do you want still?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué, qué, qué?\n"
    .string "¿Qué quieres?$"
    .endif

Route14_Text_IsaacIntro::
    .ifdef ENGLISH
    .string "I need to burn some time.\n"
    .string "Shut up and battle.$"
    .endif
    .ifdef SPANISH
    .string "¡Perfecto!\n"
    .string "¡Así pasaré el rato!$"
    .endif

Route14_Text_IsaacDefeat::
    .ifdef ENGLISH
    .string "What?\n"
    .string "You!?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué?\n"
    .string "¿¡Tú!?$"
    .endif

Route14_Text_IsaacPostBattle::
    .ifdef ENGLISH
    .string "Raising POKéMON is a drag, man.$"
    .endif
    .ifdef SPANISH
    .string "¡Entrenar POKéMON es un rollo!$"
    .endif

Route14_Text_GeraldIntro::
    .ifdef ENGLISH
    .string "We ride out here because of the\n"
    .string "wide-open spaces.$"
    .endif
    .ifdef SPANISH
    .string "¡Salimos por aquí porque hay\n"
    .string "más espacio!$"
    .endif

Route14_Text_GeraldDefeat::
    .ifdef ENGLISH
    .string "Wipeout!$"
    .endif
    .ifdef SPANISH
    .string "¡Descalificado!$"
    .endif

Route14_Text_GeraldPostBattle::
    .ifdef ENGLISH
    .string "It's cool you made your POKéMON so\n"
    .string "strong.\p"
    .string "Might is right!\n"
    .string "And you know it!$"
    .endif
    .ifdef SPANISH
    .string "¡Muy bien!\n"
    .string "¡Tus POKéMON son superfuertes!\p"
    .string "¡La fuerza mola!\n"
    .string "¡Y tú lo sabes!$"
    .endif

Route14_Text_MalikIntro::
    .ifdef ENGLISH
    .string "POKéMON battle?\n"
    .string "Cool! Rumble!$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres pelear con tus POKéMON?\n"
    .string "¡Pues vale!$"
    .endif

Route14_Text_MalikDefeat::
    .ifdef ENGLISH
    .string "Blown away!$"
    .endif
    .ifdef SPANISH
    .string "¡Pulverizado!$"
    .endif

Route14_Text_MalikPostBattle::
    .ifdef ENGLISH
    .string "You know who'd win, you and me\n"
    .string "one-on-one!$"
    .endif
    .ifdef SPANISH
    .string "¡Ya sabes quién ganaría\n"
    .string "si peleáramos tú y yo!$"
    .endif

Route14_Text_RouteSign::
    .ifdef ENGLISH
    .string "ROUTE 14\n"
    .string "West to FUCHSIA CITY$"
    .endif
    .ifdef SPANISH
    .string "RUTA 14:\n"
    .string "CIUDAD FUCSIA, al oeste$"
    .endif

Route14_Text_KiriIntro::
    .ifdef ENGLISH
    .string "KIRI: JAN, let's try really,\n"
    .string "really hard together.$"
    .endif
    .ifdef SPANISH
    .string "LENA: TEA, vamos a poner todo\n"
    .string "de nuestra parte.$"
    .endif

Route14_Text_KiriDefeat::
    .ifdef ENGLISH
    .string "KIRI: Whimper…\n"
    .string "We lost, didn't we?$"
    .endif
    .ifdef SPANISH
    .string "LENA: Vaya, snif, snif...\n"
    .string "Hemos perdido, ¿verdad?$"
    .endif

Route14_Text_KiriPostBattle::
    .ifdef ENGLISH
    .string "KIRI: Did we lose because of me?$"
    .endif
    .ifdef SPANISH
    .string "LENA: ¿Hemos perdido por mi culpa?$"
    .endif

Route14_Text_KiriNotEnoughMons::
    .ifdef ENGLISH
    .string "KIRI: We can battle if you have\n"
    .string "two POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "LENA: Lucharemos cuando tengas\n"
    .string "dos POKéMON.$"
    .endif

Route14_Text_JanIntro::
    .ifdef ENGLISH
    .string "JAN: KIRI, here we go!\n"
    .string "We have to try hard!$"
    .endif
    .ifdef SPANISH
    .string "TEA: LENA, ¡vamos allá!\n"
    .string "¡A por todas!$"
    .endif

Route14_Text_JanDefeat::
    .ifdef ENGLISH
    .string "JAN: Eeeeh!\n"
    .string "No fair!$"
    .endif
    .ifdef SPANISH
    .string "TEA: ¡Eeeh! ¡No es justo!$"
    .endif

Route14_Text_JanPostBattle::
    .ifdef ENGLISH
    .string "JAN: KIRI, don't cry!\n"
    .string "We'll just try harder next time.$"
    .endif
    .ifdef SPANISH
    .string "TEA: ¡LENA, no llores! ¡Ya lo\n"
    .string "haremos mejor la próxima vez!$"
    .endif

Route14_Text_JanNotEnoughMons::
    .ifdef ENGLISH
    .string "JAN: You want to battle?\n"
    .string "You don't have enough POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "TEA: ¿Quieres luchar?\n"
    .string "¡Te hacen falta dos POKéMON!$"
    .endif
