ViridianCity_School_Text_TryingToMemorizeNotes::
    .ifdef ENGLISH
    .string "Whew! I'm trying to memorize all my\n"
    .string "notes.$"
    .endif
    .ifdef SPANISH
    .string "Estoy intentando memorizar todos\n"
    .string "mis apuntes.$"
    .endif

ViridianCity_School_Text_ReadBlackboardCarefully::
    .ifdef ENGLISH
    .string "Okay!\p"
    .string "Be sure to read what's on the\n"
    .string "blackboard carefully!$"
    .endif
    .ifdef SPANISH
    .string "¡Muy bien!\p"
    .string "¡No olvides leer la pizarra con\n"
    .string "mucha atención!$"
    .endif

ViridianCity_School_Text_NotebookFirstPage::
    .ifdef ENGLISH
    .string "Let's check out the notebook.\p"
    .string "First page…\p"
    .string "POKé BALLS are used to catch\n"
    .string "POKéMON.\p"
    .string "Up to six POKéMON can be carried\n"
    .string "in your party.\p"
    .string "People who raise and battle\n"
    .string "with POKéMON are called TRAINERS.$"
    .endif
    .ifdef SPANISH
    .string "A ver qué pone en el cuaderno...\p"
    .string "Primera página...\p"
    .string "Las POKé BALLS son para atrapar\n"
    .string "a los POKéMON.\p"
    .string "Puedes llevar hasta 6 POKéMON.\p"
    .string "Los ENTRENADORES son la gente\n"
    .string "que entrena y hace pelear a sus\l"
    .string "POKéMON.$"
    .endif

ViridianCity_School_Text_NotebookSecondPage::
    .ifdef ENGLISH
    .string "Second page…\p"
    .string "A healthy POKéMON may be hard to\n"
    .string "catch, so weaken it first.\p"
    .string "Poison, burn, or cause another\n"
    .string "status problem to weaken it.$"
    .endif
    .ifdef SPANISH
    .string "Segunda página...\p"
    .string "¡Un POKéMON sano no es tan fácil\n"
    .string "de atrapar, conviene debilitarlo\l"
    .string "primero!\p"
    .string "¡Los venenos, las quemaduras y\n"
    .string "otros daños son muy efectivos!$"
    .endif

ViridianCity_School_Text_NotebookThirdPage::
    .ifdef ENGLISH
    .string "Third page…\p"
    .string "POKéMON TRAINERS seek others to\n"
    .string "engage in POKéMON battles.\p"
    .string "To TRAINERS, the taste of victory\n"
    .string "is sweet, indeed.\p"
    .string "Battles are constantly waged at\n"
    .string "POKéMON GYMS everywhere.$"
    .endif
    .ifdef SPANISH
    .string "Tercera página...\p"
    .string "Los ENTRENADORES POKéMON luchan\n"
    .string "contra otros, en combates POKéMON.\p"
    .string "Lo cierto es que la victoria tiene\n"
    .string "un sabor muy dulce.\p"
    .string "En los GIMNASIOS siempre se están\n"
    .string "librando combates POKéMON.$"
    .endif

ViridianCity_School_Text_NotebookFourthPage::
    .ifdef ENGLISH
    .string "Fourth page…\p"
    .string "The ultimate goal for all POKéMON\n"
    .string "TRAINERS is simple.\p"
    .string "It is to defeat the top eight\n"
    .string "POKéMON GYM LEADERS.\p"
    .string "Do so to earn the right to face…\p"
    .string "The ELITE FOUR of the POKéMON\n"
    .string "LEAGUE!$"
    .endif
    .ifdef SPANISH
    .string "Cuarta página...\p"
    .string "El objetivo de todo ENTRENADOR\n"
    .string "es derrotar a los 8 mejores\l"
    .string "LÍDERES de GIMNASIO.\p"
    .string "Si lo consigue, podrá desafiar...\p"
    .string "¡Al ALTO MANDO de la LIGA\n"
    .string "POKéMON!$"
    .endif

ViridianCity_School_Text_TurnThePage::
    .ifdef ENGLISH
    .string "Turn the page?$"
    .endif
    .ifdef SPANISH
    .string "¿Paso la página?$"
    .endif

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .ifdef ENGLISH
    .string "GIRL: Hey!\n"
    .string "Don't look at my notes!$"
    .endif
    .ifdef SPANISH
    .string "NIÑA: ¡Oye!\n"
    .string "¡No mires mis apuntes!$"
    .endif

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .ifdef ENGLISH
    .string "The blackboard lists POKéMON\n"
    .string "STATUS problems during battles.$"
    .endif
    .ifdef SPANISH
    .string "La pizarra indica los cambios de\n"
    .string "las CARACTERÍSTICAS de los\l"
    .string "POKéMON durante los combates.$"
    .endif

ViridianCity_School_Text_ReadWhichTopic::
    .ifdef ENGLISH
    .string "Which topic do you want to read?$"
    .endif
    .ifdef SPANISH
    .string "¿Sobre qué tema te gustaría leer?$"
    .endif

ViridianCity_School_Text_ExplainSleep::
    .ifdef ENGLISH
    .string "A POKéMON can't attack if it's\n"
    .string "asleep.\p"
    .string "POKéMON will stay asleep even\n"
    .string "after battles.\p"
    .string "Use AWAKENING to awaken one\n"
    .string "from sleep.$"
    .endif
    .ifdef SPANISH
    .string "¡Un POKéMON no puede atacar si\n"
    .string "está dormido!\p"
    .string "¡Los POKéMON seguirán dormidos\n"
    .string "incluso después de pelear!\p"
    .string "¡Usa DESPERTAR y se despertarán!$"
    .endif

ViridianCity_School_Text_ExplainBurn::
    .ifdef ENGLISH
    .string "A burn reduces ATTACK power.\n"
    .string "It also causes ongoing HP loss.\p"
    .string "A burn remains after a battle.\n"
    .string "Use BURN HEAL to cure a burn.$"
    .endif
    .ifdef SPANISH
    .string "Toda quemadura reduce la fuerza\n"
    .string "del ATAQUE y va restando PS.\p"
    .string "Las quemaduras permanecerán tras\n"
    .string "el combate.\p"
    .string "¡ANTIQUEMAR curará las\n"
    .string "quemaduras!$"
    .endif

ViridianCity_School_Text_ExplainPoison::
    .ifdef ENGLISH
    .string "When poisoned, a POKéMON's health\n"
    .string "steadily drops.\p"
    .string "Poison lingers after battles.\n"
    .string "Use an ANTIDOTE to cure poison!$"
    .endif
    .ifdef SPANISH
    .string "Todo POKéMON envenenado\n"
    .string "seguirá perdiendo energía.\p"
    .string "El veneno sigue haciendo efecto\n"
    .string "tras el combate.\p"
    .string "¡Usa un ANTÍDOTO para curar\n"
    .string "el envenenamiento!$"
    .endif

ViridianCity_School_Text_ExplainFreeze::
    .ifdef ENGLISH
    .string "A frozen POKéMON becomes\n"
    .string "helplessly immobile.\p"
    .string "It stays frozen even after the\n"
    .string "battle ends.\p"
    .string "Use ICE HEAL to thaw out the\n"
    .string "suffering POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Todo POKéMON congelado no podrá\n"
    .string "moverse!\p"
    .string "Y permanecerá congelado tras el\n"
    .string "combate.\p"
    .string "¡Usa el ANTIHIELO para\n"
    .string "descongelar a los POKéMON!$"
    .endif

ViridianCity_School_Text_ExplainParalysis::
    .ifdef ENGLISH
    .string "Paralysis reduces SPEED and may\n"
    .string "prevent the POKéMON from moving.\p"
    .string "Paralysis remains after battles.\n"
    .string "Use PARLYZ HEAL for treatment.$"
    .endif
    .ifdef SPANISH
    .string "¡La parálisis podría anular ciertos\n"
    .string "movimientos!\p"
    .string "Y permanece tras el combate.\p"
    .string "Usa ANTIPARALIZAR para liberar a\n"
    .string "los POKéMON que estén paralizados.$"
    .endif

