Route10_Text_MarkIntro::
    .ifdef ENGLISH
    .string "Wow, you came all the way here?\n"
    .string "Maybe you're a POKéMANIAC, too?\l"
    .string "Want to see my collection?$"
    .endif
    .ifdef SPANISH
    .string "¿Eres como los POKéMANÍACOS?\n"
    .string "¿Quieres ver mi colección?$"
    .endif

Route10_Text_MarkDefeat::
    .ifdef ENGLISH
    .string "Humph.\n"
    .string "I'm not angry!$"
    .endif
    .ifdef SPANISH
    .string "¿Qué?\n"
    .string "¡No estoy enfadado!$"
    .endif

Route10_Text_MarkPostBattle::
    .ifdef ENGLISH
    .string "I have more rare POKéMON at home!$"
    .endif
    .ifdef SPANISH
    .string "¡En casa tengo más POKéMON\n"
    .string "superraros!$"
    .endif

Route10_Text_ClarkIntro::
    .ifdef ENGLISH
    .string "Ha-hahah-ah-ha!$"
    .endif
    .ifdef SPANISH
    .string "¡A-aa-a-a!$"
    .endif

Route10_Text_ClarkDefeat::
    .ifdef ENGLISH
    .string "Ha-haha!\n"
    .string "Not laughing!\l"
    .string "Ha-hay fever! Haha-ha-choo!$"
    .endif
    .ifdef SPANISH
    .string "¡A-aa!\n"
    .string "¡No me estoy riendo!\l"
    .string "¡Es a-a-a-lergia! ¡A-a-a-chús!$"
    .endif

Route10_Text_ClarkPostBattle::
    .ifdef ENGLISH
    .string "Haha-ha-choo!\n"
    .string "Ha-choo!\l"
    .string "Snort! Snivel!$"
    .endif
    .ifdef SPANISH
    .string "¡A-a-a-chús!\n"
    .string "¡A-chús!\l"
    .string "Ufff...$"
    .endif

Route10_Text_HermanIntro::
    .ifdef ENGLISH
    .string "Hi, kid!\n"
    .string "Want to see my POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, hola!\n"
    .string "¿Quieres ver mis POKéMON?$"
    .endif

Route10_Text_HermanDefeat::
    .ifdef ENGLISH
    .string "Oh, no!\n"
    .string "My POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh, no!\n"
    .string "¡Mis POKéMON!$"
    .endif

Route10_Text_HermanPostBattle::
    .ifdef ENGLISH
    .string "I don't like you.\n"
    .string "I don't like anyone better than me!$"
    .endif
    .ifdef SPANISH
    .string "¡No me gustas cuando ganas!$"
    .endif

Route10_Text_HeidiIntro::
    .ifdef ENGLISH
    .string "I've been out at a POKéMON GYM\n"
    .string "a few times.\p"
    .string "…But I always lose.$"
    .endif
    .ifdef SPANISH
    .string "He estado varias veces en un\n"
    .string "GIMNASIO POKéMON.\p"
    .string "¡Y he perdido siempre!$"
    .endif

Route10_Text_HeidiDefeat::
    .ifdef ENGLISH
    .string "Ohh!\n"
    .string "After all my training!$"
    .endif
    .ifdef SPANISH
    .string "¡Volví a perder!$"
    .endif

Route10_Text_HeidiPostBattle::
    .ifdef ENGLISH
    .string "I noticed some POKéMANIACS\n"
    .string "prowling around.\p"
    .string "Can you imagine? Them?\n"
    .string "Up here in the mountains?$"
    .endif
    .ifdef SPANISH
    .string "Hay algunos POKéMANÍACOS por ahí.\p"
    .string "Y la verdad, creo que no pintan\n"
    .string "nada en la montaña, ¿no?$"
    .endif

Route10_Text_TrentIntro::
    .ifdef ENGLISH
    .string "Ah!\n"
    .string "This mountain air is delicious!$"
    .endif
    .ifdef SPANISH
    .string "¡Ah!\n"
    .string "¡Me encanta el aire de montaña!$"
    .endif

Route10_Text_TrentDefeat::
    .ifdef ENGLISH
    .string "That cleared my head!$"
    .endif
    .ifdef SPANISH
    .string "¡Me has espabilado!$"
    .endif

Route10_Text_TrentPostBattle::
    .ifdef ENGLISH
    .string "I feel bloated on mountain air!$"
    .endif
    .ifdef SPANISH
    .string "A mí el aire de la montaña\n"
    .string "me atonta.$"
    .endif

Route10_Text_CarolIntro::
    .ifdef ENGLISH
    .string "I'm feeling a bit faint.\n"
    .string "I haven't hiked in some time.$"
    .endif
    .ifdef SPANISH
    .string "¡Me siento débil tras la escalada!$"
    .endif

Route10_Text_CarolDefeat::
    .ifdef ENGLISH
    .string "I'm too tired.\n"
    .string "I wasn't up for it.$"
    .endif
    .ifdef SPANISH
    .string "No estaba lo suficientemente\n"
    .string "preparada...$"
    .endif

Route10_Text_CarolPostBattle::
    .ifdef ENGLISH
    .string "The POKéMON here in the mountains\n"
    .string "are so chunky…\p"
    .string "I wish there were pink POKéMON\n"
    .string "with a floral pattern!$"
    .endif
    .ifdef SPANISH
    .string "¡Estos POKéMON son tan toscos!\p"
    .string "¡Debería haber alguno rosa con\n"
    .string "bonitas flores!$"
    .endif

Route10_Text_RockTunnelDetourToLavender::
    .ifdef ENGLISH
    .string "ROCK TUNNEL\n"
    .string "Detour to LAVENDER TOWN$"
    .endif
    .ifdef SPANISH
    .string "TÚNEL ROCA\n"
    .string "Desvío hacia PUEBLO LAVANDA.$"
    .endif

Route10_Text_RockTunnel::
    .ifdef ENGLISH
    .string "ROCK TUNNEL$"
    .endif
    .ifdef SPANISH
    .string "TÚNEL ROCA$"
    .endif

Route10_Text_PowerPlant::
    .ifdef ENGLISH
    .string "POWER PLANT$"
    .endif
    .ifdef SPANISH
    .string "CENTRAL ENERGÍA$"
    .endif

