Route10_Text_MarkIntro::
    .string "¿Eres como los POKéMANÍACOS?\n"
    .string "¿Quieres ver mi colección?$"

Route10_Text_MarkDefeat::
    .string "¿Qué?\n"
    .string "¡No estoy enfadado!$"

Route10_Text_MarkPostBattle::
    .string "¡En casa tengo más POKéMON\n"
    .string "superraros!$"

Route10_Text_ClarkIntro::
    .string "¡A-aa-a-a!$"

Route10_Text_ClarkDefeat::
    .string "¡A-aa!\n"
    .string "¡No me estoy riendo!\l"
    .string "¡Es a-a-a-lergia! ¡A-a-a-chús!$"

Route10_Text_ClarkPostBattle::
    .string "¡A-a-a-chús!\n"
    .string "¡A-chús!\l"
    .string "Ufff...$"

Route10_Text_HermanIntro::
    .string "¡Eh, hola!\n"
    .string "¿Quieres ver mis POKéMON?$"

Route10_Text_HermanDefeat::
    .string "¡Oh, no!\n"
    .string "¡Mis POKéMON!$"

Route10_Text_HermanPostBattle::
    .string "¡No me gustas cuando ganas!$"

Route10_Text_HeidiIntro::
    .string "He estado varias veces en un\n"
    .string "GIMNASIO POKéMON.\p"
    .string "¡Y he perdido siempre!$"

Route10_Text_HeidiDefeat::
    .string "¡Volví a perder!$"

Route10_Text_HeidiPostBattle::
    .string "Hay algunos POKéMANÍACOS por ahí.\p"
    .string "Y la verdad, creo que no pintan\n"
    .string "nada en la montaña, ¿no?$"

Route10_Text_TrentIntro::
    .string "¡Ah!\n"
    .string "¡Me encanta el aire de montaña!$"

Route10_Text_TrentDefeat::
    .string "¡Me has espabilado!$"

Route10_Text_TrentPostBattle::
    .string "A mí el aire de la montaña\n"
    .string "me atonta.$"

Route10_Text_CarolIntro::
    .string "¡Me siento débil tras la escalada!$"

Route10_Text_CarolDefeat::
    .string "No estaba lo suficientemente\n"
    .string "preparada...$"

Route10_Text_CarolPostBattle::
    .string "¡Estos POKéMON son tan toscos!\p"
    .string "¡Debería haber alguno rosa con\n"
    .string "bonitas flores!$"

Route10_Text_RockTunnelDetourToLavender::
    .string "TÚNEL ROCA\n"
    .string "Desvío hacia PUEBLO LAVANDA.$"

Route10_Text_RockTunnel::
    .string "TÚNEL ROCA$"

Route10_Text_PowerPlant::
    .string "CENTRAL ENERGÍA$"
