LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
    .ifdef ENGLISH
    .string "I recently moved to this town.\p"
    .string "I hear that MR. FUJI's not from\n"
    .string "these parts originally, either.$"
    .endif
    .ifdef SPANISH
    .string "Acabo de mudarme a este pueblo.\p"
    .string "He oído que el SR. FUJI tampoco\n"
    .string "es de por aquí.$"
    .endif

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
    .ifdef ENGLISH
    .string "That's odd, MR. FUJI isn't here.\n"
    .string "Where'd he go?$"
    .endif
    .ifdef SPANISH
    .string "El SR. FUJI no está aquí.\n"
    .string "¡Qué raro! ¿Adónde ha ido?$"
    .endif

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
    .ifdef ENGLISH
    .string "MR. FUJI had been praying alone\n"
    .string "for CUBONE's mother.$"
    .endif
    .ifdef SPANISH
    .string "El SR. FUJI estaba rindiendo\n"
    .string "homenaje a la madre de CUBONE.$"
    .endif

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
    .ifdef ENGLISH
    .string "This is really MR. FUJI's house.\p"
    .string "He's really kind.\p"
    .string "He looks after abandoned and\n"
    .string "orphaned POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "Ésta es la casa del SR. FUJI.\p"
    .string "¡Es muy amable!\p"
    .string "¡Cuida de los POKéMON huérfanos\n"
    .string "y abandonados!$"
    .endif

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
    .ifdef ENGLISH
    .string "It's so warm!\n"
    .string "POKéMON are so nice to hug.$"
    .endif
    .ifdef SPANISH
    .string "¡Es tan bonito abrazar a los\n"
    .string "POKéMON!$"
    .endif

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
    .ifdef ENGLISH
    .string "NIDORINO: Gaoo!$"
    .endif
    .ifdef SPANISH
    .string "NIDORINO: ¡Nidor!$"
    .endif

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
    .ifdef ENGLISH
    .string "PSYDUCK: Gwappa!$"
    .endif
    .ifdef SPANISH
    .string "PSYDUCK: ¡Psydu!$"
    .endif

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
    .ifdef ENGLISH
    .string "MR. FUJI: {PLAYER}…\p"
    .string "Your POKéDEX quest is one that\n"
    .string "requires strong dedication.\p"
    .string "Without deep love for POKéMON,\n"
    .string "your quest may fail.\p"
    .string "I'm not sure if this will help you,\n"
    .string "but I'd like you to have it.$"
    .endif
    .ifdef SPANISH
    .string "SR. FUJI: {PLAYER}.\p"
    .string "Te va a costar mucho esfuerzo\n"
    .string "completar la POKéDEX.\p"
    .string "Si no adoras a tus POKéMON,\n"
    .string "te resultará difícil finalizarla.\p"
    .string "Creo que esto te ayudará.$"
    .endif

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
    .ifdef ENGLISH
    .string "{PLAYER} received a POKé FLUTE\n"
    .string "from MR. FUJI.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo la POKé FLAUTA\n"
    .string "de manos del SR. FUJI!$"
    .endif

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
    .ifdef ENGLISH
    .string "Upon hearing the POKé FLUTE,\n"
    .string "sleeping POKéMON will spring awake.\p"
    .string "Try using it on POKéMON that are\n"
    .string "sleeping obstacles.$"
    .endif
    .ifdef SPANISH
    .string "Cuando escuchen la POKé FLAUTA,\n"
    .string "los POKéMON dormidos se\l"
    .string "despertarán.\p"
    .string "Funciona con todos los POKéMON\n"
    .string "dormidos.$"
    .endif

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
    .ifdef ENGLISH
    .string "You must make room for this!$"
    .endif
    .ifdef SPANISH
    .string "¡No tienes sitio para esto!$"
    .endif

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
    .ifdef ENGLISH
    .string "MR. FUJI: Has my POKé FLUTE\n"
    .string "helped you?$"
    .endif
    .ifdef SPANISH
    .string "SR. FUJI: ¿Te ayudó mi POKé\n"
    .string "FLAUTA?$"
    .endif

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
    .ifdef ENGLISH
    .string "POKéMON FAN MAGAZINE\n"
    .string "Monthly Grand Prize Drawing!\p"
    .string "The application form is…\p"
    .string "Gone! It's been clipped out.\n"
    .string "Someone must have applied already.$"
    .endif
    .ifdef SPANISH
    .string "REVISTA POKéMON\n"
    .string "¡Gran concurso mensual de dibujo\l"
    .string "POKéMON!\p"
    .string "El formulario de inscripción está\n"
    .string "en...\p"
    .string "¡Anda, se lo han llevado!\n"
    .string "¡Se ha debido de inscribir alguien!$"
    .endif

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
    .ifdef ENGLISH
    .string "POKéMON magazines line the shelf.\p"
    .string "POKéMON INSIDER…\p"
    .string "POKéMON FAN…$"
    .endif
    .ifdef SPANISH
    .string "¡Revistas de los POKéMON!\p"
    .string "¡Cuadernos de los POKéMON!\p"
    .string "¡Dibujos de los POKéMON!$"
    .endif

