LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
	.string "Ich bin erst vor kurzem in diese\n"
	.string "Stadt gezogen!\p"
	.string "Ich hörte, dass MR. FUJI auch\n"
	.string "nicht von hier stammt!$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
	.string "MR. FUJI ist nicht zu Hause.\n"
	.string "Wohin mag er gegangen sein?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
	.string "MR. FUJI hat oft für TRAGOSSOs\n"
	.string "Mutter gebetet.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
	.string "Das hier ist MR. FUJIs Haus.\p"
	.string "Er ist sehr fürsorglich!\p"
	.string "Er kümmert sich um ausgesetzte\n"
	.string "und verwaiste POKéMON!$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
	.string "Sie sind so putzig! POKéMON sind\n"
	.string "wunderbare Schmusetiere!$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
	.string "NIDORINO: Nido!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
	.string "ENTON: Quacka!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
	.string "MR. FUJI: {PLAYER}!\p"
	.string "Du kannst deinen POKéDEX nicht\n"
	.string "vollenden, wenn du deinen POKéMON\l"
	.string "nicht genügend Liebe und Respekt\l"
	.string "entgegenbringst.\p"
	.string "Dies wird dir bei deinem Abenteuer\n"
	.string "helfen.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
	.string "{PLAYER} erhält\n"
	.string "eine POKéFLÖTE!$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
	.string "Schlafende POKéMON wachen auf,\n"
	.string "wenn sie das Spiel der POKéFLÖTE\l"
	.string "hören!\p"
	.string "Du kannst damit alle schlafenden\n"
	.string "POKéMON wecken!$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
	.string "Du hast keinen Platz für weitere\n"
	.string "Items!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
	.string "MR. FUJI: War die FLÖTE schon von\n"
	.string "Nutzen für dich?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
	.string "GROSSES POKéMON-GEWINNSPIEL!\p"
	.string "Es sind keine Teilnahmekarten mehr\n"
	.string "vorhanden!\p"
	.string "Sie wurden alle abgeschickt!$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
	.string "POKéMON-Zeitschriften!\p"
	.string "POKéMON-Notizbücher!\p"
	.string "POKéMON-Schaubilder!$"

