RockTunnel_1F_Text_LennyIntro::
    .string "¡Este oscuro túnel recorre\n"
    .string "un largo camino!$"

RockTunnel_1F_Text_LennyDefeat::
    .string "¡Uauu!\n"
    .string "¡Tú ganas!$"

RockTunnel_1F_Text_LennyPostBattle::
    .string "Cuidado con ONIX.\n"
    .string "¡Podría apretarte las tuercas!$"

RockTunnel_1F_Text_OliverIntro::
    .string "Mmm.\n"
    .string "Puede que me haya perdido...$"

RockTunnel_1F_Text_OliverDefeat::
    .string "A ver, con calma. \n"
    .string "¿Qué hago?\l"
    .string "¿Por dónde salgo?$"

RockTunnel_1F_Text_OliverPostBattle::
    .string "Ese POKéMON dormido de la RUTA 12\n"
    .string "me obligó a desviarme.$"

RockTunnel_1F_Text_LucasIntro::
    .string "¡La gente de fuera como tú\n"
    .string "debería respetarme!$"

RockTunnel_1F_Text_LucasDefeat::
    .string "¡Me rindo!$"

RockTunnel_1F_Text_LucasPostBattle::
    .string "¡Tienes madera para escalar!$"

RockTunnel_1F_Text_AshtonIntro::
    .string "¡Lucha POKéMON!\n"
    .string "¿Empezamos? ¡Pues venga!$"

RockTunnel_1F_Text_AshtonDefeat::
    .string "¡Se acabó!$"

RockTunnel_1F_Text_AshtonPostBattle::
    .string "¡Conseguiré un ZUBAT por el\n"
    .string "camino!$"

RockTunnel_1F_Text_LeahIntro::
    .string "¡Oye!\p"
    .string "¡No hagas tonterías en la\n"
    .string "oscuridad!$"

RockTunnel_1F_Text_LeahDefeat::
    .string "¡Estaba demasiado oscuro!$"

RockTunnel_1F_Text_LeahPostBattle::
    .string "¡Vi a un MACHOP en este túnel!$"

RockTunnel_1F_Text_DanaIntro::
    .string "¡Vine hasta aquí por los POKéMON!$"

RockTunnel_1F_Text_DanaDefeat::
    .string "¡Me he quedado sin POKéMON!$"

RockTunnel_1F_Text_DanaPostBattle::
    .string "¡No parecía que tuvieras ni la\n"
    .string "más mínima agresividad!$"

RockTunnel_1F_Text_ArianaIntro::
    .string "¡Tienes POKéMON!\n"
    .string "¡Empecemos!$"

RockTunnel_1F_Text_ArianaDefeat::
    .string "¡No te andas con tonterías!$"

RockTunnel_1F_Text_ArianaPostBattle::
    .string "¡Ufff!\n"
    .string "¡Estoy sudando!$"

RockTunnel_1F_Text_RouteSign::
    .string "TÚNEL ROCA:\n"
    .string "CIUDAD CELESTE - PUEBLO LAVANDA$"
