RockTunnel_1F_Text_LennyIntro::
	.string "Dieser Tunnel ist verdammt lang!$"

RockTunnel_1F_Text_LennyDefeat::
	.string "Oha!\n"
	.string "Du hast gewonnen!$"

RockTunnel_1F_Text_LennyPostBattle::
	.string "Nimm dich vor ONIX in Acht! Es\n"
	.string "quetscht dich wie eine Zitrone aus!$"

RockTunnel_1F_Text_OliverIntro::
	.string "Könnte es sein, dass ich mich\n"
	.string "verlaufen habe?$"

RockTunnel_1F_Text_OliverDefeat::
	.string "Sachte!\n"
	.string "Wo bin ich?\l"
	.string "Wo geht es nach draußen?$"

RockTunnel_1F_Text_OliverPostBattle::
	.string "Diesen Umweg muss ich nur wegen\n"
	.string "des auf Route 12 schlafenden\l"
	.string "POKéMON machen.$"

RockTunnel_1F_Text_LucasIntro::
	.string "Ein Möchtegern wie du sollte etwas\n"
	.string "mehr Respekt zeigen!$"

RockTunnel_1F_Text_LucasDefeat::
	.string "Ich gebe auf!$"

RockTunnel_1F_Text_LucasPostBattle::
	.string "Du hast Talent!\n"
	.string "Du kannst kein Möchtegern sein!$"

RockTunnel_1F_Text_AshtonIntro::
	.string "Meine POKéMON wollen kämpfen!\n"
	.string "Los!$"

RockTunnel_1F_Text_AshtonDefeat::
	.string "GAME OVER!$"

RockTunnel_1F_Text_AshtonPostBattle::
	.string "Unterwegs werde ich mir ein ZUBAT\n"
	.string "fangen!$"

RockTunnel_1F_Text_LeahIntro::
	.string "Huch!\p"
	.string "Komm mir im Dunkeln bloß nicht zu\n"
	.string "nahe!$"

RockTunnel_1F_Text_LeahDefeat::
	.string "Es war zu dunkel!$"

RockTunnel_1F_Text_LeahPostBattle::
	.string "Ich habe hier im Tunnel ein\n"
	.string "MASCHOCK gesehen!$"

RockTunnel_1F_Text_DanaIntro::
	.string "Ich bin wegen der POKéMON hierher\n"
	.string "gekommen!$"

RockTunnel_1F_Text_DanaDefeat::
	.string "Alle meine POKéMON wurden besiegt!$"

RockTunnel_1F_Text_DanaPostBattle::
	.string "Dabei sahst du so süß und harmlos\n"
	.string "aus!$"

RockTunnel_1F_Text_ArianaIntro::
	.string "Du besitzt POKéMON!\n"
	.string "Lass uns kämpfen!$"

RockTunnel_1F_Text_ArianaDefeat::
	.string "Du bist ein harter Brocken!$"

RockTunnel_1F_Text_ArianaPostBattle::
	.string "Puh!\n"
	.string "Ich bin ganz nass geschwitzt!$"

RockTunnel_1F_Text_RouteSign::
	.string "FELSTUNNEL\n"
	.string "AZURIA CITY - LAVANDIA$"

