RockTunnel_1F_Text_LennyIntro::
    .ifdef ENGLISH
    .string "This tunnel goes a long way, kid!$"
    .endif
    .ifdef SPANISH
    .string "¡Este oscuro túnel recorre\n"
    .string "un largo camino!$"
    .endif

RockTunnel_1F_Text_LennyDefeat::
    .ifdef ENGLISH
    .string "Doh!\n"
    .string "You win!$"
    .endif
    .ifdef SPANISH
    .string "¡Uauu!\n"
    .string "¡Tú ganas!$"
    .endif

RockTunnel_1F_Text_LennyPostBattle::
    .ifdef ENGLISH
    .string "Watch for ONIX.\n"
    .string "They appear only occasionally.\p"
    .string "High-level ones can put the\n"
    .string "squeeze on you!$"
    .endif
    .ifdef SPANISH
    .string "Cuidado con ONIX.\n"
    .string "¡Podría apretarte las tuercas!$"
    .endif

RockTunnel_1F_Text_OliverIntro::
    .ifdef ENGLISH
    .string "Hmm.\n"
    .string "Maybe I'm lost in here…$"
    .endif
    .ifdef SPANISH
    .string "Mmm.\n"
    .string "Puede que me haya perdido...$"
    .endif

RockTunnel_1F_Text_OliverDefeat::
    .ifdef ENGLISH
    .string "Ease up!\n"
    .string "What am I doing?\l"
    .string "Which way is out?$"
    .endif
    .ifdef SPANISH
    .string "A ver, con calma. \n"
    .string "¿Qué hago?\l"
    .string "¿Por dónde salgo?$"
    .endif

RockTunnel_1F_Text_OliverPostBattle::
    .ifdef ENGLISH
    .string "That sleeping POKéMON on ROUTE 12\n"
    .string "forced me to take this detour.$"
    .endif
    .ifdef SPANISH
    .string "Ese POKéMON dormido de la RUTA 12\n"
    .string "me obligó a desviarme.$"
    .endif

RockTunnel_1F_Text_LucasIntro::
    .ifdef ENGLISH
    .string "Outsiders like you need to show me\n"
    .string "some respect!$"
    .endif
    .ifdef SPANISH
    .string "¡La gente de fuera como tú\n"
    .string "debería respetarme!$"
    .endif

RockTunnel_1F_Text_LucasDefeat::
    .ifdef ENGLISH
    .string "I give!$"
    .endif
    .ifdef SPANISH
    .string "¡Me rindo!$"
    .endif

RockTunnel_1F_Text_LucasPostBattle::
    .ifdef ENGLISH
    .string "You're talented enough to hike!$"
    .endif
    .ifdef SPANISH
    .string "¡Tienes madera para escalar!$"
    .endif

RockTunnel_1F_Text_AshtonIntro::
    .ifdef ENGLISH
    .string "POKéMON fight!\n"
    .string "Ready, go!$"
    .endif
    .ifdef SPANISH
    .string "¡Lucha POKéMON!\n"
    .string "¿Empezamos? ¡Pues venga!$"
    .endif

RockTunnel_1F_Text_AshtonDefeat::
    .ifdef ENGLISH
    .string "Game over!$"
    .endif
    .ifdef SPANISH
    .string "¡Se acabó!$"
    .endif

RockTunnel_1F_Text_AshtonPostBattle::
    .ifdef ENGLISH
    .string "Oh well, I'll get a ZUBAT as I go!$"
    .endif
    .ifdef SPANISH
    .string "¡Conseguiré un ZUBAT por el\n"
    .string "camino!$"
    .endif

RockTunnel_1F_Text_LeahIntro::
    .ifdef ENGLISH
    .string "Eek!\p"
    .string "Don't try anything funny in the\n"
    .string "dark!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye!\p"
    .string "¡No hagas tonterías en la\n"
    .string "oscuridad!$"
    .endif

RockTunnel_1F_Text_LeahDefeat::
    .ifdef ENGLISH
    .string "It was too dark…$"
    .endif
    .ifdef SPANISH
    .string "¡Estaba demasiado oscuro!$"
    .endif

RockTunnel_1F_Text_LeahPostBattle::
    .ifdef ENGLISH
    .string "I saw a MACHOP in this tunnel.$"
    .endif
    .ifdef SPANISH
    .string "¡Vi a un MACHOP en este túnel!$"
    .endif

RockTunnel_1F_Text_DanaIntro::
    .ifdef ENGLISH
    .string "I came this far looking for wild\n"
    .string "POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Vine hasta aquí por los POKéMON!$"
    .endif

RockTunnel_1F_Text_DanaDefeat::
    .ifdef ENGLISH
    .string "I'm out of POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Me he quedado sin POKéMON!$"
    .endif

RockTunnel_1F_Text_DanaPostBattle::
    .ifdef ENGLISH
    .string "You looked cute and harmless.\n"
    .string "Was I ever wrong!$"
    .endif
    .ifdef SPANISH
    .string "¡No parecía que tuvieras ni la\n"
    .string "más mínima agresividad!$"
    .endif

RockTunnel_1F_Text_ArianaIntro::
    .ifdef ENGLISH
    .string "You have POKéMON!\n"
    .string "Let's start!$"
    .endif
    .ifdef SPANISH
    .string "¡Tienes POKéMON!\n"
    .string "¡Empecemos!$"
    .endif

RockTunnel_1F_Text_ArianaDefeat::
    .ifdef ENGLISH
    .string "You play hard!$"
    .endif
    .ifdef SPANISH
    .string "¡No te andas con tonterías!$"
    .endif

RockTunnel_1F_Text_ArianaPostBattle::
    .ifdef ENGLISH
    .string "Whew!\n"
    .string "I'm all sweaty now.$"
    .endif
    .ifdef SPANISH
    .string "¡Ufff!\n"
    .string "¡Estoy sudando!$"
    .endif

RockTunnel_1F_Text_RouteSign::
    .ifdef ENGLISH
    .string "ROCK TUNNEL\n"
    .string "CERULEAN CITY - LAVENDER TOWN$"
    .endif
    .ifdef SPANISH
    .string "TÚNEL ROCA:\n"
    .string "CIUDAD CELESTE - PUEBLO LAVANDA$"
    .endif

