CeladonCity_Restaurant_Text_TakingBreakRightNow::
    .string "¡Hola!\p"
    .string "Ahora estamos descansando.$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
    .string "Suelo visitar la FARMACIA, porque\n"
    .string "mis POKéMON son débiles.$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
    .string "¡Psss!\n"
    .string "Hay un sótano debajo del CASINO.$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
    .string "Oye...\p"
    .string "El hombre de esa mesa lo perdió\n"
    .string "todo en las tragaperras.$"

CeladonCity_Restaurant_Text_TakeThisImBusted::
    .string "¡Venga! ¡Ríete!\n"
    .string "¡Estoy arruinado!\p"
    .string "¡No más tragaperras para mí!\n"
    .string "¡Yo me largo!\p"
    .string "¡Toma esto!\n"
    .string "¡Ya no lo necesito!$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan::
    .string "¡{PLAYER} recibió un MONEDERO\n"
    .string "de manos del hombre!$"

CeladonCity_Restaurant_Text_MakeRoomForThis::
    .string "¡Haz sitio para esto!$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack::
    .string "Pensaba que iba a recuperarme...$"
