CeladonCity_Restaurant_Text_TakingBreakRightNow::
    .ifdef ENGLISH
    .string "Hi!\p"
    .string "Sorry, but we're taking a break\n"
    .string "right now.$"
    .endif
    .ifdef SPANISH
    .string "¡Hola!\p"
    .string "Ahora estamos descansando.$"
    .endif

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
    .ifdef ENGLISH
    .string "My POKéMON are weak, so I often\n"
    .string "have to go to the DRUGSTORE.$"
    .endif
    .ifdef SPANISH
    .string "Suelo visitar la FARMACIA, porque\n"
    .string "mis POKéMON son débiles.$"
    .endif

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
    .ifdef ENGLISH
    .string "Psst! There's a basement under the\n"
    .string "GAME CORNER, I hear.$"
    .endif
    .ifdef SPANISH
    .string "¡Psss!\n"
    .string "Hay un sótano debajo del CASINO.$"
    .endif

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
    .ifdef ENGLISH
    .string "Munch…\p"
    .string "The man at that table lost it all\n"
    .string "at the slots.$"
    .endif
    .ifdef SPANISH
    .string "Oye...\p"
    .string "El hombre de esa mesa lo perdió\n"
    .string "todo en las tragaperras.$"
    .endif

CeladonCity_Restaurant_Text_TakeThisImBusted::
    .ifdef ENGLISH
    .string "Go ahead! Laugh!\n"
    .string "I'm flat-out busted!\p"
    .string "No more slots for me!\n"
    .string "I'm going straight!\p"
    .string "Here!\n"
    .string "I won't be needing this anymore!$"
    .endif
    .ifdef SPANISH
    .string "¡Venga! ¡Ríete!\n"
    .string "¡Estoy arruinado!\p"
    .string "¡No más tragaperras para mí!\n"
    .string "¡Yo me largo!\p"
    .string "¡Toma esto!\n"
    .string "¡Ya no lo necesito!$"
    .endif

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan::
    .ifdef ENGLISH
    .string "{PLAYER} received a COIN CASE\n"
    .string "from the man.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió un MONEDERO\n"
    .string "de manos del hombre!$"
    .endif

CeladonCity_Restaurant_Text_MakeRoomForThis::
    .ifdef ENGLISH
    .string "Make room for this!$"
    .endif
    .ifdef SPANISH
    .string "¡Haz sitio para esto!$"
    .endif

CeladonCity_Restaurant_Text_ThoughtIdWinItBack::
    .ifdef ENGLISH
    .string "I always thought I was going to\n"
    .string "win it back…$"
    .endif
    .ifdef SPANISH
    .string "Pensaba que iba a recuperarme...$"
    .endif

