CeladonCity_Restaurant_Text_TakingBreakRightNow::
	.string "Hallo!\p"
	.string "Wir machen gerade eine Pause.$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
	.string "Meine POKéMON sind ziemlich\n"
	.string "schwach, deshalb gehe ich oft zur\l"
	.string "DROGERIE.$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
	.string "Pst! Unter der SPIELHALLE\n"
	.string "befindet sich ein Keller!$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
	.string "Mampf...\p"
	.string "Der Mann dort drüben am Tisch hat\n"
	.string "Haus und Hof verzockt.$"

CeladonCity_Restaurant_Text_TakeThisImBusted::
	.string "Ja, lach mich ruhig aus!\p"
	.string "Ich bin pleite!\p"
	.string "Jetzt ist Schluss damit! Ich werde\n"
	.string "niemals wieder zocken!\p"
	.string "Hier, das kann ich jetzt nicht mehr\n"
	.string "gebrauchen!$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan::
	.string "{PLAYER} erhält\n"
	.string "einen MÜNZKORB!$"

CeladonCity_Restaurant_Text_MakeRoomForThis::
	.string "Du solltest etwas Platz schaffen!$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack::
	.string "Ich dachte immer, ich könnte den\n"
	.string "Jackpot knacken!$"

