TwoIsland_House_Text_TeachMonMoveForMushroom::
    .ifdef ENGLISH
    .string "I'm the POKéMON MOVE MANIAC.\p"
    .string "I know every single move that\n"
    .string "POKéMON learn growing up.\p"
    .string "I'm also a mushroom maniac.\p"
    .string "Bring me two TINYMUSHROOMS,\n"
    .string "or one BIG MUSHROOM.\p"
    .string "If you do that for me, I'll teach\n"
    .string "a move to one POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "Soy el TUTOR de MOVIMIENTOS.\p"
    .string "Me sé todos los movimientos que\n"
    .string "aprenden los POKéMON. Todos,\l"
    .string "toditos, todos. Y puedo enseñar.\p"
    .string "También soy EXPERTO en SETAS.\p"
    .string "Si me traes dos MINI SETAS o una\n"
    .string "SETA GRANDE, le enseñaré un\l"
    .string "movimiento a uno de tus POKéMON.$"
    .endif

TwoIsland_House_Text_WantMeToTeachMove::
    .ifdef ENGLISH
    .string "Sniff, sniff…\n"
    .string "Hm! You smell of MUSHROOMS!\p"
    .string "Do you want me to teach a move\n"
    .string "to a POKéMON of yours?$"
    .endif
    .ifdef SPANISH
    .string "Sniff, sniff...\n"
    .string "¡Mmm! ¡Hueles a SETA!\p"
    .string "¿Quieres que le enseñe un\n"
    .string "movimiento a uno de tus POKéMON?$"
    .endif

TwoIsland_House_Text_TutorWhichMon::
    .ifdef ENGLISH
    .string "Which POKéMON needs tutoring?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué POKéMON quieres que lo\n"
    .string "aprenda?$"
    .endif

TwoIsland_House_Text_TeachWhichMove::
    .ifdef ENGLISH
    .string "Which move should I teach?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué movimiento quieres que\n"
    .string "aprenda?$"
    .endif

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .ifdef ENGLISH
    .string "Sorry…\p"
    .string "It doesn't appear as if I have a\n"
    .string "move I can teach that POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "Perdona...\p"
    .string "Parece que no puedo enseñar ningún\n"
    .string "movimiento a ese POKéMON...$"
    .endif

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .ifdef ENGLISH
    .string "Then, I'll need a MUSHROOM or two.\n"
    .string "What are you going to give me?$"
    .endif
    .ifdef SPANISH
    .string "Pues tendrás que darme una SETA\n"
    .string "o un par de ellas.\l"
    .string "¿Qué me das?$"
    .endif

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .ifdef ENGLISH
    .string "{PLAYER} handed over two\n"
    .string "TINYMUSHROOMS in exchange.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} entregó dos MINI SETAS\n"
    .string "a cambio de la lección.$"
    .endif

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .ifdef ENGLISH
    .string "{PLAYER} handed over one\n"
    .string "BIG MUSHROOM in exchange.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} entregó una SETA GRANDE\n"
    .string "a cambio de la lección.$"
    .endif

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .ifdef ENGLISH
    .string "If your POKéMON need to learn a\n"
    .string "move, I need a MUSHROOM or two.$"
    .endif
    .ifdef SPANISH
    .string "Si quieres que le enseñe un\n"
    .string "movimiento a algún POKéMON,\l"
    .string "tráeme una SETA o dos.$"
    .endif

TwoIsland_House_Text_CantTeachAnEgg::
    .ifdef ENGLISH
    .string "Hunh? There isn't a single move\n"
    .string "that I can teach an EGG.$"
    .endif
    .ifdef SPANISH
    .string "¿Eh? No puedo enseñar\n"
    .string "absolutamente ningún movimiento\l"
    .string "a un HUEVO...$"
    .endif

