SixIsland_DottedHole_SapphireRoom_Text_FoundSapphire::
    .ifdef ENGLISH
    .string "{PLAYER} found a SAPPHIRE!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} encontró un ZAFIRO!$"
    .endif

SixIsland_DottedHole_SapphireRoom_Text_IWasRightInTailingYou::
    .ifdef ENGLISH
    .string "Fufu… Fufufufu…\n"
    .string "I guessed right.\p"
    .string "I was right in tailing you!$"
    .endif
    .ifdef SPANISH
    .string "Bien... Estupendo...\n"
    .string "Justo lo que pensaba.\p"
    .string "He hecho bien en seguirte.$"
    .endif

SixIsland_DottedHole_SapphireRoom_Text_SellToTeamRocketTellPassword::
    .ifdef ENGLISH
    .string "I knew that there was a SAPPHIRE\n"
    .string "here, so it belongs to me!\p"
    .string "I'll sell it to TEAM ROCKET for\n"
    .string "serious money.\p"
    .string "…D-don't glare at me like that!\p"
    .string "If you want it back, why don't you\n"
    .string "go get it after I sell it?\p"
    .string "I'll even tell you one of the\n"
    .string "passwords to TEAM ROCKET's\l"
    .string "WAREHOUSE.\p"
    .string "The WAREHOUSE password I know is\n"
    .string "“Yes, nah, CHANSEY.”\p"
    .string "I'm done.\n"
    .string "Don't think badly of me!$"
    .endif
    .ifdef SPANISH
    .string "Sabía que había un ZAFIRO aquí,\n"
    .string "¡así que para mí!\p"
    .string "¡Se lo venderé al TEAM ROCKET\n"
    .string "por una buena cantidad!\p"
    .string "Eh... no me mi-mires así.\p"
    .string "Si lo quieres, ¿por qué no vas a\n"
    .string "por él cuando lo venda?\p"
    .string "Te diré una de las contraseñas\n"
    .string "del ALMACÉN ROCKET y todo...\p"
    .string "La contraseña que yo conozco es\n"
    .string "“HO-OH es ese HO-OH”.\p"
    .string "Hala, yo ya estoy.\n"
    .string "¡No te mosquees conmigo!$"
    .endif

