FiveIsland_MemorialPillar_Text_MiloIntro::
    .string "Soy el mayor de los HERMANOS\n"
    .string "PÁJARO.\p"
    .string "Lo mejor que tienen los pájaros\n"
    .string "debe de ser el pico.$"

FiveIsland_MemorialPillar_Text_MiloDefeat::
    .string "¡Eso sí que ha sido como\n"
    .string "un picotazo!$"

FiveIsland_MemorialPillar_Text_MiloPostBattle::
    .string "Desde aquí se puede ir volando\n"
    .string "a ISLA QUARTA.$"

FiveIsland_MemorialPillar_Text_ChazIntro::
    .string "Soy el mediano de los HERMANOS\n"
    .string "PÁJARO.\p"
    .string "Lo mejor que tienen los pájaros\n"
    .string "deben de ser las alas.$"

FiveIsland_MemorialPillar_Text_ChazDefeat::
    .string "¡Qué batida!$"

FiveIsland_MemorialPillar_Text_ChazPostBattle::
    .string "Más adelante hay un tipo de lo\n"
    .string "más extraño.$"

FiveIsland_MemorialPillar_Text_HaroldIntro::
    .string "Soy el pequeño de los HERMANOS\n"
    .string "PÁJARO.\p"
    .string "Lo mejor que tienen los pájaros\n"
    .string "deben de ser las plumas.$"

FiveIsland_MemorialPillar_Text_HaroldDefeat::
    .string "Con tanta pluma me he\n"
    .string "despistado...$"

FiveIsland_MemorialPillar_Text_HaroldPostBattle::
    .string "A mí me encanta ver pájaros\n"
    .string "POKéMON jugueteando tan contentos.$"

FiveIsland_MemorialPillar_Text_ScrubScrub::
    .string "Mmm, así me gusta, que esté\n"
    .string "reluciente...$"

FiveIsland_MemorialPillar_Text_YourMonsLookHealthy::
    .string "Hola, tus POKéMON tienen\n"
    .string "una pinta estupenda.$"

FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix::
    .string "Aquí descansa mi ONIX...\n"
    .string "Se llamaba TECTONIX...$"

FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering::
    .string "“Aquí yace TECTONIX”, pone\n"
    .string "en una piedra.\p"
    .string "Enfrente, hay una LIMONADA\n"
    .string "a modo de ofrenda.$"

FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering::
    .string "¿Quieres dejar otra LIMONADA\n"
    .string "a modo de ofrenda?$"

FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade::
    .string "{PLAYER} colocó una LIMONADA\n"
    .string "frente a la piedra.$"

FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis::
    .string "Gra-gracias...\p"
    .string "Era el refresco preferido\n"
    .string "de mi TECTONIX...\p"
    .string "No sé, pero el detalle que has\n"
    .string "tenido me ha animado un poco.\p"
    .string "Deja que te lo agradezca\n"
    .string "con esto.$"

FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo::
    .string "Tú también deberías comportarte \n"
    .string "con tus POKéMON.$"

FiveIsland_MemorialPillar_Text_DontHaveRoomForIt::
    .string "Si no te queda sitio, te la\n"
    .string "guardaré para cuando vuelvas.$"

FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks::
    .string "Anda, si eres tú...\p"
    .string "Aquí tengo lo que quería darte\n"
    .string "como muestra de mi agradecimiento.$"

FiveIsland_MemorialPillar_Text_ScrubScrubTectonix::
    .string "Yo creo que se ve bastante\n"
    .string "limpia...\p"
    .string "... ... ...\n"
    .string "Mi TECTONIX...$"

FiveIsland_MemorialPillar_Text_HereLiesTectonix::
    .string "Cantos y rocas apilados de manera\n"
    .string "ordenada forman una especie\l"
    .string "de monumento.\p"
    .string "“Aquí yace TECTONIX”, pone\n"
    .string "en una piedra.$"
