FiveIsland_MemorialPillar_Text_MiloIntro::
	.string "Ich bin der älteste der\n"
	.string "VOGEL-BRÜDER.\p"
	.string "Das Beste an Vögeln…\n"
	.string "Das muss der Schnabel sein.$"

FiveIsland_MemorialPillar_Text_MiloDefeat::
	.string "Oh, so scharf!$"

FiveIsland_MemorialPillar_Text_MiloPostBattle::
	.string "Von hier kannst du nach EILAND\n"
	.string "VIER fliegen.$"

FiveIsland_MemorialPillar_Text_ChazIntro::
	.string "Ich bin der zweitälteste der\n"
	.string "VOGEL-BRÜDER.\p"
	.string "Das Beste an Vögeln…\n"
	.string "Das müssen die Flügel sein.$"

FiveIsland_MemorialPillar_Text_ChazDefeat::
	.string "Flatter, flatter!$"

FiveIsland_MemorialPillar_Text_ChazPostBattle::
	.string "Da entlang war ein wahrhaft\n"
	.string "ernster Typ.$"

FiveIsland_MemorialPillar_Text_HaroldIntro::
	.string "Ich bin der jüngste der\n"
	.string "VOGEL-BRÜDER.\p"
	.string "Das Beste an Vögeln…\n"
	.string "Das muss das Gefieder sein.$"

FiveIsland_MemorialPillar_Text_HaroldDefeat::
	.string "Die Federn sind so weich…\n"
	.string "Ich könnte schlafen…$"

FiveIsland_MemorialPillar_Text_HaroldPostBattle::
	.string "Es freut mich, wenn Vogel-POKéMON\n"
	.string "verspielt Männchen machen…$"

FiveIsland_MemorialPillar_Text_ScrubScrub::
	.string "Putz, putz…$"

FiveIsland_MemorialPillar_Text_YourMonsLookHealthy::
	.string "Hallo…\n"
	.string "Deine POKéMON sehen gesund aus…$"

FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix::
	.string "Hier habe ich mein ONIX begraben…\n"
	.string "Es hieß TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering::
	.string "“TECTONIX ruht hier in\n"
	.string "Frieden” ist in den Stein\l"
	.string "gemeißelt.\p"
	.string "Vor dem Grab wurde eine LIMONADE\n"
	.string "zum Gedenken dargereicht.$"

FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering::
	.string "Möchtest du auch eine LIMONADE\n"
	.string "darreichen?$"

FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade::
	.string "{PLAYER} reichte eine Dose LIMONADE\n"
	.string "dar.$"

FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis::
	.string "D-danke…\p"
	.string "Das war das Lieblingsgetränk von\n"
	.string "meinem TECTONIX…\p"
	.string "Ich kenne dich nicht, aber du hast\n"
	.string "Edelmut bewiesen…\p"
	.string "Das hat mich aufgemuntert.\p"
	.string "Nimm dies bitte als Zeichen meiner\n"
	.string "Wertschätzung. Danke!$"

FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo::
	.string "Bitte behandle deine POKéMON gut!$"

FiveIsland_MemorialPillar_Text_DontHaveRoomForIt::
	.string "Wenn du keinen Platz hast, bewahre\n"
	.string "ich es bis zum nächsten Mal für\l"
	.string "dich auf.$"

FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks::
	.string "Ah, du bist es, von neulich…\p"
	.string "Ich habe es immer noch und du\n"
	.string "solltest es als Zeichen meiner\l"
	.string "Wertschätzung erhalten.$"

FiveIsland_MemorialPillar_Text_ScrubScrubTectonix::
	.string "Putz, putz…\p"
	.string "………\n"
	.string "TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonix::
	.string "Die Felsen und Steine bilden eine\n"
	.string "ordentlich angelegte Pyramide.\p"
	.string "“TECTONIX ruht hier in\n"
	.string "Frieden” ist in den Stein\l"
	.string "gemeißelt.$"

