FiveIsland_MemorialPillar_Text_MiloIntro::
    .ifdef ENGLISH
    .string "I'm the eldest of the BIRD\n"
    .string "BROTHERS.\p"
    .string "The best thing about birds…\n"
    .string "It has to be the beak.$"
    .endif
    .ifdef SPANISH
    .string "Soy el mayor de los HERMANOS\n"
    .string "PÁJARO.\p"
    .string "Lo mejor que tienen los pájaros\n"
    .string "debe de ser el pico.$"
    .endif

FiveIsland_MemorialPillar_Text_MiloDefeat::
    .ifdef ENGLISH
    .string "Oh, so sharp!$"
    .endif
    .ifdef SPANISH
    .string "¡Eso sí que ha sido como\n"
    .string "un picotazo!$"
    .endif

FiveIsland_MemorialPillar_Text_MiloPostBattle::
    .ifdef ENGLISH
    .string "You can fly to FOUR ISLAND from\n"
    .string "here.$"
    .endif
    .ifdef SPANISH
    .string "Desde aquí se puede ir volando\n"
    .string "a ISLA QUARTA.$"
    .endif

FiveIsland_MemorialPillar_Text_ChazIntro::
    .ifdef ENGLISH
    .string "I'm the middle kid of the BIRD\n"
    .string "BROTHERS.\p"
    .string "The best thing about birds…\n"
    .string "It has to be the wings.$"
    .endif
    .ifdef SPANISH
    .string "Soy el mediano de los HERMANOS\n"
    .string "PÁJARO.\p"
    .string "Lo mejor que tienen los pájaros\n"
    .string "deben de ser las alas.$"
    .endif

FiveIsland_MemorialPillar_Text_ChazDefeat::
    .ifdef ENGLISH
    .string "Flap, flap!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué batida!$"
    .endif

FiveIsland_MemorialPillar_Text_ChazPostBattle::
    .ifdef ENGLISH
    .string "There was a really somber guy\n"
    .string "over that way.$"
    .endif
    .ifdef SPANISH
    .string "Más adelante hay un tipo de lo\n"
    .string "más extraño.$"
    .endif

FiveIsland_MemorialPillar_Text_HaroldIntro::
    .ifdef ENGLISH
    .string "I'm the youngest of the BIRD\n"
    .string "BROTHERS.\p"
    .string "The best thing about birds…\n"
    .string "It has to be the down.$"
    .endif
    .ifdef SPANISH
    .string "Soy el pequeño de los HERMANOS\n"
    .string "PÁJARO.\p"
    .string "Lo mejor que tienen los pájaros\n"
    .string "deben de ser las plumas.$"
    .endif

FiveIsland_MemorialPillar_Text_HaroldDefeat::
    .ifdef ENGLISH
    .string "Down is so comfy…\n"
    .string "It makes me drowsy…$"
    .endif
    .ifdef SPANISH
    .string "Con tanta pluma me he\n"
    .string "despistado...$"
    .endif

FiveIsland_MemorialPillar_Text_HaroldPostBattle::
    .ifdef ENGLISH
    .string "It fills me with happiness when\n"
    .string "bird POKéMON beg playfully…$"
    .endif
    .ifdef SPANISH
    .string "A mí me encanta ver pájaros\n"
    .string "POKéMON jugueteando tan contentos.$"
    .endif

FiveIsland_MemorialPillar_Text_ScrubScrub::
    .ifdef ENGLISH
    .string "Scrub, scrub…$"
    .endif
    .ifdef SPANISH
    .string "Mmm, así me gusta, que esté\n"
    .string "reluciente...$"
    .endif

FiveIsland_MemorialPillar_Text_YourMonsLookHealthy::
    .ifdef ENGLISH
    .string "Hello…\n"
    .string "Your POKéMON look healthy…$"
    .endif
    .ifdef SPANISH
    .string "Hola, tus POKéMON tienen\n"
    .string "una pinta estupenda.$"
    .endif

FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix::
    .ifdef ENGLISH
    .string "This is where I buried my ONIX…\n"
    .string "It was named TECTONIX…$"
    .endif
    .ifdef SPANISH
    .string "Aquí descansa mi ONIX...\n"
    .string "Se llamaba TECTONIX...$"
    .endif

FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering::
    .ifdef ENGLISH
    .string "“Here lies TECTONIX” is engraved\n"
    .string "on a boulder.\p"
    .string "There is a LEMONADE placed as an\n"
    .string "offering in front of the grave.$"
    .endif
    .ifdef SPANISH
    .string "“Aquí yace TECTONIX”, pone\n"
    .string "en una piedra.\p"
    .string "Enfrente, hay una LIMONADA\n"
    .string "a modo de ofrenda.$"
    .endif

FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering::
    .ifdef ENGLISH
    .string "Would you like to leave another\n"
    .string "LEMONADE as an offering?$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres dejar otra LIMONADA\n"
    .string "a modo de ofrenda?$"
    .endif

FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade::
    .ifdef ENGLISH
    .string "{PLAYER} placed a can of LEMONADE\n"
    .string "in front of the grave.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} colocó una LIMONADA\n"
    .string "frente a la piedra.$"
    .endif

FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis::
    .ifdef ENGLISH
    .string "Th-thank you…\p"
    .string "That was my TECTONIX's favorite\n"
    .string "drink…\p"
    .string "I don't even know you, but your\n"
    .string "act of kindness…\p"
    .string "It's uplifted me a little.\p"
    .string "Can you please take this as my\n"
    .string "thanks?$"
    .endif
    .ifdef SPANISH
    .string "Gra-gracias...\p"
    .string "Era el refresco preferido\n"
    .string "de mi TECTONIX...\p"
    .string "No sé, pero el detalle que has\n"
    .string "tenido me ha animado un poco.\p"
    .string "Deja que te lo agradezca\n"
    .string "con esto.$"
    .endif

FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo::
    .ifdef ENGLISH
    .string "Please be good to your POKéMON,\n"
    .string "too.$"
    .endif
    .ifdef SPANISH
    .string "Tú también deberías comportarte \n"
    .string "con tus POKéMON.$"
    .endif

FiveIsland_MemorialPillar_Text_DontHaveRoomForIt::
    .ifdef ENGLISH
    .string "If you don't have room for it,\n"
    .string "I'll hold it for you till next time.$"
    .endif
    .ifdef SPANISH
    .string "Si no te queda sitio, te la\n"
    .string "guardaré para cuando vuelvas.$"
    .endif

FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks::
    .ifdef ENGLISH
    .string "Oh, it's you from that time…\p"
    .string "I still have that thing I wanted\n"
    .string "you to have as my thanks.$"
    .endif
    .ifdef SPANISH
    .string "Anda, si eres tú...\p"
    .string "Aquí tengo lo que quería darte\n"
    .string "como muestra de mi agradecimiento.$"
    .endif

FiveIsland_MemorialPillar_Text_ScrubScrubTectonix::
    .ifdef ENGLISH
    .string "Scrub, scrub…\p"
    .string "… … …\n"
    .string "TECTONIX…$"
    .endif
    .ifdef SPANISH
    .string "Yo creo que se ve bastante\n"
    .string "limpia...\p"
    .string "... ... ...\n"
    .string "Mi TECTONIX...$"
    .endif

FiveIsland_MemorialPillar_Text_HereLiesTectonix::
    .ifdef ENGLISH
    .string "Boulders and rocks are neatly piled\n"
    .string "up as a cairn.\p"
    .string "“Here lies TECTONIX” is engraved\n"
    .string "on a boulder.$"
    .endif
    .ifdef SPANISH
    .string "Cantos y rocas apilados de manera\n"
    .string "ordenada forman una especie\l"
    .string "de monumento.\p"
    .string "“Aquí yace TECTONIX”, pone\n"
    .string "en una piedra.$"
    .endif

