OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays::
    .ifdef ENGLISH
    .string "On sunny days, I step out and gaze\n"
    .string "upon the volcano.\p"
    .string "That's my daily routine.$"
    .endif
    .ifdef SPANISH
    .string "Cuando hace buen día, salgo\n"
    .string "a contemplar el volcán.\p"
    .string "Es lo que hago siempre.$"
    .endif

OneIsland_House1_Text_LastTimeMtEmberErupted::
    .ifdef ENGLISH
    .string "Let me think… When was the last\n"
    .string "time MT. EMBER erupted?$"
    .endif
    .ifdef SPANISH
    .string "Mmm, no consigo acordarme...\n"
    .string "¿Cuándo fue la última vez que\l"
    .string "entró en erupción el MT. ASCUAS?$"
    .endif

