Text_UltimateMoveThatMon::
    .ifdef ENGLISH
    .string "I perfected the ultimate move of\n"
    .string "its type…\p"
    .string "But will no one take it for\n"
    .string "future use?\p"
    .string "…Hm? Hmmm!\p"
    .string "Y-you…\n"
    .string "Th-that {STR_VAR_1}…$"
    .endif
    .ifdef SPANISH
    .string "He perfeccionado el último\n"
    .string "movimiento de este tipo...\p"
    .string "Bueno, y ahora, ¿a quién se lo\n"
    .string "enseño?\p"
    .string "Mmmm...\p"
    .string "Ese {STR_VAR_1} tuyo...$"
    .endif

Text_JustMistaken::
    .ifdef ENGLISH
    .string "…No…\n"
    .string "I was just mistaken.$"
    .endif
    .ifdef SPANISH
    .string "No, no...\n"
    .string "Me he equivocado...$"
    .endif

Text_AllowMeToTeachMonUltimateMove::
    .ifdef ENGLISH
    .string "Oh! This is the one!\n"
    .string "This is the POKéMON!\p"
    .string "This {STR_VAR_1} is worthy of\n"
    .string "learning my ultimate move!\p"
    .string "Will you allow it?\p"
    .string "Will you allow your {STR_VAR_1} to\n"
    .string "learn my {STR_VAR_2}?$"
    .endif
    .ifdef SPANISH
    .string "¡Anda, éste es!\n"
    .string "¡Éste es el POKéMON!\p"
    .string "¡Este {STR_VAR_1} se merece\n"
    .string "aprender mi último movimiento!\p"
    .string "¿Te parece bien?\p"
    .string "¿Quieres que le enseñe\n"
    .string "mi {STR_VAR_2} a tu {STR_VAR_1}?$"
    .endif

Text_YouRejectIt::
    .ifdef ENGLISH
    .string "Gaah! You reject it?\n"
    .string "No, I won't be dissuaded!$"
    .endif
    .ifdef SPANISH
    .string "¿Cómo, que no?\n"
    .string "¡No me lo puedo creer!$"
    .endif

Text_LetMeConferUltimateMove::
    .ifdef ENGLISH
    .string "You will allow it?\p"
    .string "Then, let me confer my ultimate\n"
    .string "{STR_VAR_2} on your {STR_VAR_1}.\p"
    .string "Ggggrah-awooo!$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres?\p"
    .string "Pues voy a enseñarle\n"
    .string "mi {STR_VAR_2} a tu {STR_VAR_1}.\p"
    .string "¡Allá voy!$"
    .endif

Text_TaughtMove::
    .ifdef ENGLISH
    .string "Gasp, gasp, gasp…\p"
    .string "I didn't think I could teach that\n"
    .string "move while I still lived…$"
    .endif
    .ifdef SPANISH
    .string "Qué emoción...\p"
    .string "No pensé que llegara a enseñar\n"
    .string "al final el movimiento...$"
    .endif

Text_MakeBestUseOfMove::
    .ifdef ENGLISH
    .string "I implore you to make the best\n"
    .string "use of that move and gain power!$"
    .endif
    .ifdef SPANISH
    .string "¡Espero que lo uses bien y\n"
    .string "le saques el mayor partido!$"
    .endif

Text_PassedOnEverythingIKnow::
    .ifdef ENGLISH
    .string "Gasp, gasp, gasp…\p"
    .string "I have no regrets now.\n"
    .string "I've passed on everything I know.\p"
    .string "Now I can live out my life knowing\n"
    .string "my work is done.$"
    .endif
    .ifdef SPANISH
    .string "Qué emoción...\p"
    .string "Qué tranquilidad.\n"
    .string "Ya he transmitido todo lo que sé.\p"
    .string "Qué satisfacción cumplir con el\n"
    .string "deber...$"
    .endif

Text_FeelRejuvenated::
    .ifdef ENGLISH
    .string "After I passed on my knowledge to\n"
    .string "you, I felt so much relief.\p"
    .string "In fact, I feel rejuvenated,\n"
    .string "as if I were younger again!$"
    .endif
    .ifdef SPANISH
    .string "Ahora que sabes lo que yo, siento\n"
    .string "una tranquilidad enorme.\p"
    .string "¡Me siento hasta más joven!\n"
    .string "¡Es como si me hubiera quitado\l"
    .string "años de encima!$"
    .endif
