Route1_Text_WorkAtPokeMartTakeSample::
    .ifdef ENGLISH
    .string "Hi!\n"
    .string "I work at a POKéMON MART.\p"
    .string "It's part of a convenient chain\n"
    .string "selling all sorts of items.\p"
    .string "Please, visit us in VIRIDIAN CITY.\p"
    .string "I know, I'll give you a sample.\n"
    .string "Here you go!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola!\n"
    .string "Trabajo en una TIENDA POKéMON.\p"
    .string "Tenemos muchas cosas. Visítanos\n"
    .string "en CIUDAD VERDE.\p"
    .string "¡Mira, te daré una muestra!\n"
    .string "¡Aquí tienes!$"
    .endif

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .ifdef ENGLISH
    .string "Please come see us if you need\n"
    .string "POKé BALLS for catching POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡También tenemos POKé BALLS\n"
    .string "para capturar los POKéMON!$"
    .endif

Route1_Text_PutPotionAway::
    .ifdef ENGLISH
    .string "{PLAYER} put the POTION away in\n"
    .string "the BAG's ITEMS POCKET.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} puso la POCIÓN\n"
    .string "en el BOLSILLO de OBJETOS\l"
    .string "de la MOCHILA.$"
    .endif

Route1_Text_CanJumpFromLedges::
    .ifdef ENGLISH
    .string "See those ledges along the road?\p"
    .string "It's a bit scary, but you can jump\n"
    .string "from them.\p"
    .string "You can get back to PALLET TOWN\n"
    .string "quicker that way.$"
    .endif
    .ifdef SPANISH
    .string "¿Ves esos bordes del camino?\p"
    .string "Dan miedo, pero puedes saltar\n"
    .string "por encima de ellos.\p"
    .string "¡De esa forma podrás volver más\n"
    .string "rápidamente a PUEBLO PALETA!$"
    .endif

Route1_Text_RouteSign::
    .ifdef ENGLISH
    .string "ROUTE 1\n"
    .string "PALLET TOWN - VIRIDIAN CITY$"
    .endif
    .ifdef SPANISH
    .string "RUTA 1:\n"
    .string "PUEBLO PALETA - CIUDAD VERDE$"
    .endif

