PokemonTower_5F_Text_RestHereInPurifiedSpace::
    .string "¡Ven, ven! ¡Sellé este lugar\n"
    .string "con magia blanca!\l"
    .string "¡Aquí puedes descansar!$"

PokemonTower_5F_Text_TammyIntro::
    .string "Dame...\n"
    .string "tu... esencia...$"

PokemonTower_5F_Text_TammyDefeat::
    .string "¿Uh?$"

PokemonTower_5F_Text_TammyPostBattle::
    .string "¡Estaba fuera de mí!$"

PokemonTower_5F_Text_RuthIntro::
    .string "Ven... con...\n"
    .string "nosotros...$"

PokemonTower_5F_Text_RuthDefeat::
    .string "¡Vaya pesadilla!$"

PokemonTower_5F_Text_RuthPostBattle::
    .string "¡Estaba fuera de mí!$"

PokemonTower_5F_Text_KarinaIntro::
    .string "¡Zombis!$"

PokemonTower_5F_Text_KarinaDefeat::
    .string "¿Ja?$"

PokemonTower_5F_Text_KarinaPostBattle::
    .string "¡He recuperado la razón!$"

PokemonTower_5F_Text_JanaeIntro::
    .string "¡Oooo!...\n"
    .string "¡Uuuu!...$"

PokemonTower_5F_Text_JanaeDefeat::
    .string "¡Uuuu!$"

PokemonTower_5F_Text_JanaePostBattle::
    .string "¡A pesar de mi entrenamiento\n"
    .string "me atraparon los espíritus!$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
    .string "¡Has entrado en una zona de pureza\n"
    .string "y seguridad!\p"
    .string "¡Los POKéMON de {PLAYER} están\n"
    .string "curados!$"
