PokemonTower_5F_Text_RestHereInPurifiedSpace::
	.string "Komm her! Ich habe diese Stelle\n"
	.string "mit weißer Magie versiegelt!\l"
	.string "Du kannst dich hier ausruhen!$"

PokemonTower_5F_Text_TammyIntro::
	.string "Gib... mir...\n"
	.string "deine... Seele...$"

PokemonTower_5F_Text_TammyDefeat::
	.string "Puh!$"

PokemonTower_5F_Text_TammyPostBattle::
	.string "Etwas muss von mir Besitz ergriffen\n"
	.string "haben!$"

PokemonTower_5F_Text_RuthIntro::
	.string "Es... gibt... kein...\n"
	.string "Entkommen...$"

PokemonTower_5F_Text_RuthDefeat::
	.string "Welch ein Alptraum!$"

PokemonTower_5F_Text_RuthPostBattle::
	.string "Ich war verhext!$"

PokemonTower_5F_Text_KarinaIntro::
	.string "Zombies!$"

PokemonTower_5F_Text_KarinaDefeat::
	.string "Was?$"

PokemonTower_5F_Text_KarinaPostBattle::
	.string "So langsam komme ich wieder zu\n"
	.string "Sinnen!$"

PokemonTower_5F_Text_JanaeIntro::
	.string "Buuh...\n"
	.string "Buhuhu...$"

PokemonTower_5F_Text_JanaeDefeat::
	.string "Das war knapp!$"

PokemonTower_5F_Text_JanaePostBattle::
	.string "Trotz meiner Erfahrung bin ich dem\n"
	.string "Bösen verfallen!$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
	.string "Du hast einen geschützten Bereich\n"
	.string "betreten!\p"
	.string "Die POKéMON von {PLAYER}\n"
	.string "wurden geheilt!$"

