PokemonTower_5F_Text_RestHereInPurifiedSpace::
	.string "Approche, enfant!\p"
	.string "J'ai scellé cet endroit grâce à\n"
	.string "ma sainte magie blanche!\p"
	.string "Tu peux te reposer ici!$"

PokemonTower_5F_Text_TammyIntro::
	.string "Donne… moi…\n"
	.string "ton… âme…$"

PokemonTower_5F_Text_TammyDefeat::
	.string "Glargh!$"

PokemonTower_5F_Text_TammyPostBattle::
	.string "J'étais possédée!$"

PokemonTower_5F_Text_RuthIntro::
	.string "Viens… avec…\n"
	.string "nous…$"

PokemonTower_5F_Text_RuthDefeat::
	.string "Hein!\n"
	.string "J'ai fait un cauchemar!$"

PokemonTower_5F_Text_RuthPostBattle::
	.string "J'étais possédée!$"

PokemonTower_5F_Text_KarinaIntro::
	.string "Zombis!$"

PokemonTower_5F_Text_KarinaDefeat::
	.string "Hein?$"

PokemonTower_5F_Text_KarinaPostBattle::
	.string "Je suis revenue à la raison!$"

PokemonTower_5F_Text_JanaeIntro::
	.string "Poyé Polomi!\n"
	.string "Le mal est parmi nous…$"

PokemonTower_5F_Text_JanaeDefeat::
	.string "Quoi?\n"
	.string "Jeune taoïste, tu oses m'ôter le\l"
	.string "yang de la bouche!$"

PokemonTower_5F_Text_JanaePostBattle::
	.string "Mon Tao à moi, c'est le plus beau\n"
	.string "des Taos!$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
	.string "Vous pénétrez dans une zone\n"
	.string "sanctuaire!\p"
	.string "Les POKéMON de {PLAYER} sont\n"
	.string "soignés!$"

