PokemonTower_5F_Text_RestHereInPurifiedSpace::
    .ifdef ENGLISH
    .string "Come, child!\n"
    .string "I have purified this space.\l"
    .string "You can rest here.$"
    .endif
    .ifdef SPANISH
    .string "¡Ven, ven! ¡Sellé este lugar\n"
    .string "con magia blanca!\l"
    .string "¡Aquí puedes descansar!$"
    .endif

PokemonTower_5F_Text_TammyIntro::
    .ifdef ENGLISH
    .string "Give…me…\n"
    .string "your…all…$"
    .endif
    .ifdef SPANISH
    .string "Dame...\n"
    .string "tu... esencia...$"
    .endif

PokemonTower_5F_Text_TammyDefeat::
    .ifdef ENGLISH
    .string "Gasp!$"
    .endif
    .ifdef SPANISH
    .string "¿Uh?$"
    .endif

PokemonTower_5F_Text_TammyPostBattle::
    .ifdef ENGLISH
    .string "I was under possession.$"
    .endif
    .ifdef SPANISH
    .string "¡Estaba fuera de mí!$"
    .endif

PokemonTower_5F_Text_RuthIntro::
    .ifdef ENGLISH
    .string "You…shall…\n"
    .string "join…us…$"
    .endif
    .ifdef SPANISH
    .string "Ven... con...\n"
    .string "nosotros...$"
    .endif

PokemonTower_5F_Text_RuthDefeat::
    .ifdef ENGLISH
    .string "What a nightmare!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya pesadilla!$"
    .endif

PokemonTower_5F_Text_RuthPostBattle::
    .ifdef ENGLISH
    .string "I was possessed.$"
    .endif
    .ifdef SPANISH
    .string "¡Estaba fuera de mí!$"
    .endif

PokemonTower_5F_Text_KarinaIntro::
    .ifdef ENGLISH
    .string "Zombies!$"
    .endif
    .ifdef SPANISH
    .string "¡Zombis!$"
    .endif

PokemonTower_5F_Text_KarinaDefeat::
    .ifdef ENGLISH
    .string "Ha?$"
    .endif
    .ifdef SPANISH
    .string "¿Ja?$"
    .endif

PokemonTower_5F_Text_KarinaPostBattle::
    .ifdef ENGLISH
    .string "I regained my senses.$"
    .endif
    .ifdef SPANISH
    .string "¡He recuperado la razón!$"
    .endif

PokemonTower_5F_Text_JanaeIntro::
    .ifdef ENGLISH
    .string "Urgah…\n"
    .string "Urff…$"
    .endif
    .ifdef SPANISH
    .string "¡Oooo!...\n"
    .string "¡Uuuu!...$"
    .endif

PokemonTower_5F_Text_JanaeDefeat::
    .ifdef ENGLISH
    .string "Whoo!$"
    .endif
    .ifdef SPANISH
    .string "¡Uuuu!$"
    .endif

PokemonTower_5F_Text_JanaePostBattle::
    .ifdef ENGLISH
    .string "I fell to evil spirits despite my\n"
    .string "training in the mountains…$"
    .endif
    .ifdef SPANISH
    .string "¡A pesar de mi entrenamiento\n"
    .string "me atraparon los espíritus!$"
    .endif

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
    .ifdef ENGLISH
    .string "Entered the purified and protected\n"
    .string "zone.\p"
    .string "{PLAYER}'s POKéMON were fully\n"
    .string "healed.$"
    .endif
    .ifdef SPANISH
    .string "¡Has entrado en una zona de pureza\n"
    .string "y seguridad!\p"
    .string "¡Los POKéMON de {PLAYER} están\n"
    .string "curados!$"
    .endif

