Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad::
	.string "Interdit aux piétons!\n"
	.string "PISTE CYCLABLE!$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse::
	.string "La PISTE CYCLABLE est une superbe\n"
	.string "route menant à la mer.$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp::
	.string "Pardon!\n"
	.string "Hé, pardon!$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort::
	.string "Comment t'as fait pour arriver\n"
	.string "jusqu'ici?$"

