Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad::
    .string "¡Los peatones no pueden andar\n"
    .string "por el CAMINO de BICIS!$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse::
    .string "El CAMINO de BICIS va cuesta\n"
    .string "abajo junto al mar. ¡Es estupendo!$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp::
    .string "¡Perdona!\n"
    .string "¡Espera!$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort::
    .string "¿Cómo has llegado hasta aquí?\n"
    .string "¡Bien hecho!$"
