Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad::
    .ifdef ENGLISH
    .string "No pedestrians are allowed on\n"
    .string "CYCLING ROAD!$"
    .endif
    .ifdef SPANISH
    .string "¡Los peatones no pueden andar\n"
    .string "por el CAMINO de BICIS!$"
    .endif

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse::
    .ifdef ENGLISH
    .string "CYCLING ROAD is a downhill course\n"
    .string "by the sea. It's a great ride.$"
    .endif
    .ifdef SPANISH
    .string "El CAMINO de BICIS va cuesta\n"
    .string "abajo junto al mar. ¡Es estupendo!$"
    .endif

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp::
    .ifdef ENGLISH
    .string "Excuse me!\n"
    .string "Wait up, please!$"
    .endif
    .ifdef SPANISH
    .string "¡Perdona!\n"
    .string "¡Espera!$"
    .endif

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort::
    .ifdef ENGLISH
    .string "How'd you get in?\n"
    .string "Good effort!$"
    .endif
    .ifdef SPANISH
    .string "¿Cómo has llegado hasta aquí?\n"
    .string "¡Bien hecho!$"
    .endif

