Route12_FishingHouse_Text_DoYouLikeToFish::
    .ifdef ENGLISH
    .string "I'm the FISHING GURU's younger\n"
    .string "brother.\p"
    .string "I simply looove fishing!\n"
    .string "I can't bear to go without.\p"
    .string "Tell me, do you like to fish?$"
    .endif
    .ifdef SPANISH
    .string "¡Soy hermano del GURÚ PESCADOR!\p"
    .string "¡Simplemente me encanta pescar!\p"
    .string "¿Te gusta pescar?$"
    .endif

Route12_FishingHouse_Text_TakeThisAndFish::
    .ifdef ENGLISH
    .string "Grand! I like your style.\n"
    .string "I think we can be friends.\p"
    .string "Take this and fish, young friend!$"
    .endif
    .ifdef SPANISH
    .string "¡Fenomenal!\n"
    .string "¡Me gusta tu estilo!\p"
    .string "¡Toma esto y pesca, anda!$"
    .endif

Route12_FishingHouse_Text_ReceivedSuperRod::
    .ifdef ENGLISH
    .string "{PLAYER} received a SUPER ROD from\n"
    .string "the FISHING GURU's brother.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo una SUPERCAÑA\n"
    .string "del hermano del GURÚ PESCADOR!$"
    .endif

Route12_FishingHouse_Text_IfYouCatchBigMagikarpShowMe::
    .ifdef ENGLISH
    .string "Fishing is a way of life!\n"
    .string "It is like the finest poetry.\p"
    .string "From the seas to rivers, go out\n"
    .string "and land the big one, my friend.\p"
    .string "Now, I have a request.\p"
    .string "If you catch a big MAGIKARP \n"
    .string "with that ROD, I want to see it.\p"
    .string "As much as I love to fish, I also\n"
    .string "love seeing gigantic MAGIKARP.$"
    .endif
    .ifdef SPANISH
    .string "¡La pesca es una forma de vida!\n"
    .string "¡Es un arte!\p"
    .string "¡En el mar, en los ríos, da igual,\n"
    .string "hay que pescar el más grande!\p"
    .string "A ver, tengo que pedirte algo.\p"
    .string "Si consigues un MAGIKARP con\n"
    .string "esa CAÑA, me gustaría que me\l"
    .string "lo enseñaras.\p"
    .string "Pescar me gusta tanto como ver\n"
    .string "MAGIKARP enormes.$"
    .endif

Route12_FishingHouse_Text_OhThatsDisappointing::
    .ifdef ENGLISH
    .string "Oh…\n"
    .string "That's so disappointing…$"
    .endif
    .ifdef SPANISH
    .string "Oh... Estoy tan decepcionado...$"
    .endif

Route12_FishingHouse_Text_TryFishingBringMeMagikarp::
    .ifdef ENGLISH
    .string "Hello there, {PLAYER}!\n"
    .string "Have you been fishing?\p"
    .string "Try fishing with the SUPER ROD in\n"
    .string "any body of water.\p"
    .string "You'll find different POKéMON in\n"
    .string "different places.\p"
    .string "Oh, and don't forget to bring me\n"
    .string "gigantic MAGIKARP.$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, {PLAYER}!\p"
    .string "¡Utiliza la SUPERCAÑA en todo tipo\n"
    .string "de aguas! Puedes pescar diferentes\l"
    .string "tipos de POKéMON.\p"
    .string "¡Pesca siempre que puedas!\p"
    .string "¡Y no te olvides de traerme\n"
    .string "un MAGIKARP gigante!$"
    .endif

Route12_FishingHouse_Text_OhMagikarpAllowMeToSee::
    .ifdef ENGLISH
    .string "Oh? {PLAYER}?\n"
    .string "Why, if it isn't a MAGIKARP!\p"
    .string "Allow me to see it, quick!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, {PLAYER}!\n"
    .string "¡Anda, un MAGIKARP!\p"
    .string "¡Deja, deja que lo vea!$"
    .endif

Route12_FishingHouse_Text_WhoaXInchesTakeThis::
    .ifdef ENGLISH
    .string "… … …Whoa!\n"
    .string "{STR_VAR_2} inches!\p"
    .string "You have a rare appreciation for\n"
    .string "the fine, poetic aspects of fishing!\p"
    .string "You must take this.\n"
    .string "I insist!$"
    .endif
    .ifdef SPANISH
    .string "¡Guaaaau, {STR_VAR_2} cm!\p"
    .string "¡Tienes una forma muy peculiar\n"
    .string "de entender el arte de la pesca!\p"
    .string "Toma esto, por favor.$"
    .endif

Route12_FishingHouse_Text_LookForwardToGreaterRecords::
    .ifdef ENGLISH
    .string "I'll look forward to seeing greater\n"
    .string "records from you!$"
    .endif
    .ifdef SPANISH
    .string "Espero que me traigas piezas aún\n"
    .string "mejores.$"
    .endif

Route12_FishingHouse_Text_HuhXInchesSameSizeAsLast::
    .ifdef ENGLISH
    .string "Huh?\n"
    .string "{STR_VAR_2} inches?\p"
    .string "This is the same size as the one\n"
    .string "I saw before.$"
    .endif
    .ifdef SPANISH
    .string "¿Mmm?\n"
    .string "¿{STR_VAR_2} cm?\p"
    .string "¡Pero si tiene el mismo tamaño\n"
    .string "que el anterior!$"
    .endif

Route12_FishingHouse_Text_HmmXInchesDoesntMeasureUp::
    .ifdef ENGLISH
    .string "Hmm…\n"
    .string "This one is {STR_VAR_2} inches long.\p"
    .string "It doesn't measure up to the\n"
    .string "{STR_VAR_3}-inch one you brought before.$"
    .endif
    .ifdef SPANISH
    .string "Mmm...\n"
    .string "Este mide {STR_VAR_2} cm de largo...\p"
    .string "¡Pero si el de antes medía {STR_VAR_3} cm!$"
    .endif

Route12_FishingHouse_Text_DoesntLookLikeMagikarp::
    .ifdef ENGLISH
    .string "Uh… That doesn't look much like\n"
    .string "a MAGIKARP.$"
    .endif
    .ifdef SPANISH
    .string "Eh... me parece a mí que eso\n"
    .string "no es un MAGIKARP.$"
    .endif

Route12_FishingHouse_Text_NoRoomForGift::
    .ifdef ENGLISH
    .string "Oh, no!\p"
    .string "I had a gift for you, but you have\n"
    .string "no room for it.$"
    .endif
    .ifdef SPANISH
    .string "¡Oh, no!\p"
    .string "¡Tenía un regalo para ti, pero no\n"
    .string "tienes sitio!$"
    .endif

Route12_FishingHouse_Text_MostGiganticMagikarpXInches::
    .ifdef ENGLISH
    .string "The most gigantic MAGIKARP\n"
    .string "I have ever witnessed…\p"
    .string "{STR_VAR_3} inches!$"
    .endif
    .ifdef SPANISH
    .string "¡Madre mía, es el MAGIKARP más\n"
    .string "grande que he visto en mi vida!\p"
    .string "¡{STR_VAR_3} cm!$"
    .endif

Route12_FishingHouse_Text_BlankChartOfSomeSort::
    .ifdef ENGLISH
    .string "It's a blank chart of some sort.\p"
    .string "It has spaces for writing in\n"
    .string "records of some kind.$"
    .endif
    .ifdef SPANISH
    .string "Es una especie de cuadro y\n"
    .string "está en blanco.\p"
    .string "Tiene casillas para anotar cosas.$"
    .endif

