CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
    .ifdef ENGLISH
    .string "There is nothing that I don't know,\n"
    .string "like I wrote on the blackboard.\p"
    .string "I know about the world of POKéMON\n"
    .string "in your GAME BOY ADVANCE!\p"
    .string "Get together with your friends and\n"
    .string "enjoy trading POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "Ya lo dice la pizarra, no hay nada\n"
    .string "que no sepa.\p"
    .string "¡Yo lo sé todo sobre el mundo de\n"
    .string "los POKéMON de tu GAME BOY\l"
    .string "ADVANCE!\p"
    .string "¡Reúnete con tus amigos y cambia\n"
    .string "POKéMON!$"
    .endif

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
    .ifdef ENGLISH
    .string "{PLAYER} obtained an EEVEE!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo un EEVEE!$"
    .endif

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull::
    .string "ポケモンが　いっぱいだ\n"
    .string "ボックスを　かえて　きなさい$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
    .ifdef ENGLISH
    .string "POKéMON Lecture\p"
    .string "Playing with the Wireless Adapter$"
    .endif
    .ifdef SPANISH
    .string "Temario POKéMON\p"
    .string "El Conector inalámbrico de GBA.$"
    .endif

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading::
    .ifdef ENGLISH
    .string "Which heading do you want to read?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué capítulo quieres leer?$"
    .endif

CeladonCity_Condominiums_RoofRoom_Text_ExplainWirelessClub::
    .ifdef ENGLISH
    .string "The POKéMON WIRELESS CLUB is\n"
    .string "upstairs at any POKéMON CENTER.\p"
    .string "Visit one to link up with friend(s)\n"
    .string "using your Wireless Adapter.$"
    .endif
    .ifdef SPANISH
    .string "El CLUB INALÁMBRICO POKéMON\n"
    .string "está en el piso de arriba de los\l"
    .string "CENTROS POKéMON.\p"
    .string "Visita uno para conectarte con tus\n"
    .string "amigos usando el Conector\l"
    .string "inalámbrico de GBA.$"
    .endif

CeladonCity_Condominiums_RoofRoom_Text_ExplainDirectCorner::
    .ifdef ENGLISH
    .string "To link only with a friend, go to\n"
    .string "the DIRECT CORNER.\p"
    .string "It is the right counter at the\n"
    .string "POKéMON WIRELESS CLUB.\p"
    .string "Go into the TRADE CORNER or the\n"
    .string "COLOSSEUM with your friend.$"
    .endif
    .ifdef SPANISH
    .string "Para conectarte sólo con un amigo,\n"
    .string "ve a la ZONA DIRECTA.\p"
    .string "Es el mostrador de la derecha\n"
    .string "del CLUB INALÁMBRICO POKéMON.\p"
    .string "Entra con tu amigo en el CENTRO\n"
    .string "de CAMBIO o en el COLISEO.$"
    .endif

CeladonCity_Condominiums_RoofRoom_Text_ExplainUnionRoom::
    .ifdef ENGLISH
    .string "To link and communicate with\n"
    .string "anyone, go to the UNION ROOM.\p"
    .string "It is the left counter at the\n"
    .string "POKéMON WIRELESS CLUB.\p"
    .string "Go to the UNION ROOM and enjoy\n"
    .string "meeting other TRAINERS.$"
    .endif
    .ifdef SPANISH
    .string "Para conectarte y comunicarte con\n"
    .string "cualquiera, ve a la SALA UNIÓN.\p"
    .string "Es el mostrador de la izquierda\n"
    .string "del CLUB INALÁMBRICO POKéMON.\p"
    .string "Entra en la SALA UNIÓN y disfruta\n"
    .string "del encuentro con otros\l"
    .string "ENTRENADORES.$"
    .endif

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .ifdef ENGLISH
    .string "It's a pamphlet on TMs.\p"
    .string "… …\p"
    .string "There are fifty TMs in all.\p"
    .string "There are also seven HMs that\n"
    .string "can be used repeatedly.\p"
    .string "SILPH CO.$"
    .endif
    .ifdef SPANISH
    .string "Es un informe sobre las MT.\p"
    .string "...\p"
    .string "Hay un total de 50 MT.\p"
    .string "Y siete MO, que pueden usarse\n"
    .string "una y otra vez.\p"
    .string "SILPH S.A.$"
    .endif

