CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon::
    .ifdef ENGLISH
    .string "I sure do fancy that PORYGON!\n"
    .string "But, it's hard to win at slots!$"
    .endif
    .ifdef SPANISH
    .string "¡Quiero el PORYGON tan mono\n"
    .string "que tienen!\p"
    .string "¡Pero es difícil ganar a las\n"
    .string "tragaperras!$"
    .endif

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday::
    .ifdef ENGLISH
    .string "Gahaha! I raked it in today!\n"
    .string "If only every day were like this…$"
    .endif
    .ifdef SPANISH
    .string "¡He ganado mucho hoy!\n"
    .string "¡Ojalá fuera todos los días igual!$"
    .endif

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired::
    .ifdef ENGLISH
    .string "A COIN CASE is required…$"
    .endif
    .ifdef SPANISH
    .string "¡Se requiere un MONEDERO!$"
    .endif

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes::
    .ifdef ENGLISH
    .string "We exchange your COINS for prizes.$"
    .endif
    .ifdef SPANISH
    .string "Canjea tus FICHAS por premios.$"
    .endif

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize::
    .ifdef ENGLISH
    .string "Which prize would you like?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué premio quieres?$"
    .endif

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo::
    .string "はい どうぞ$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize::
    .ifdef ENGLISH
    .string "So, you want the {STR_VAR_1}?$"
    .endif
    .ifdef SPANISH
    .string "Bien, ¿quieres {STR_VAR_1}?$"
    .endif

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM::
    .ifdef ENGLISH
    .string "Okay, a TM of {STR_VAR_2}\n"
    .string "is what you want?$"
    .endif
    .ifdef SPANISH
    .string "Muy bien, ¿entonces quieres\n"
    .string "una MT de {STR_VAR_2}?$"
    .endif

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins::
    .ifdef ENGLISH
    .string "Sorry, you'll need more COINS\n"
    .string "than that.$"
    .endif
    .ifdef SPANISH
    .string "Perdón, necesitas más FICHAS.$"
    .endif

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom::
    .string "おきゃくさん もう もてないよ$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen::
    .string "あっ そう$"

