CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon::
	.string "JE VEUX LE JOLI PORYGON!\p"
	.string "Mais c'est dur de gagner avec\n"
	.string "ces machines à sous!$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday::
	.string "La chance…\n"
	.string "C'est mon truc!$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired::
	.string "Vous n'avez pas de BOITE JETON!$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes::
	.string "Nous échangeons des prix contre\n"
	.string "des JETONS.$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize::
	.string "Quel prix désirez-vous?$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo::
	.string "はい どうぞ$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize::
	.string "{STR_VAR_1}?$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM::
	.string "OK, une CT {STR_VAR_2}.\n"
	.string "C'est ce que vous voulez?$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins::
	.string "Vous n'avez pas assez de JETONS.$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom::
	.string "おきゃくさん もう もてないよ$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen::
	.string "あっ そう$"

