CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon::
    .string "¡Quiero el PORYGON tan mono\n"
    .string "que tienen!\p"
    .string "¡Pero es difícil ganar a las\n"
    .string "tragaperras!$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday::
    .string "¡He ganado mucho hoy!\n"
    .string "¡Ojalá fuera todos los días igual!$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired::
    .string "¡Se requiere un MONEDERO!$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes::
    .string "Canjea tus FICHAS por premios.$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize::
    .string "¿Qué premio quieres?$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo::
    .string "はい どうぞ$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize::
    .string "Bien, ¿quieres {STR_VAR_1}?$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM::
    .string "Muy bien, ¿entonces quieres\n"
    .string "una MT de {STR_VAR_2}?$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins::
    .string "Perdón, necesitas más FICHAS.$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom::
    .string "おきゃくさん もう もてないよ$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen::
    .string "あっ そう$"
