CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon::
	.string "Ich hätte gerne ein PORYGON!\p"
	.string "Aber ich habe kein Glück an den\n"
	.string "einarmigen Banditen!$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday::
	.string "Ich hatte heute eine\n"
	.string "Glückssträhne!$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired::
	.string "Du benötigst einen MÜNZKORB!$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes::
	.string "Wir tauschen MÜNZEN gegen Preise\n"
	.string "ein.$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize::
	.string "Welcher Preis soll es sein?$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo::
	.string "はい どうぞ$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize::
	.string "Du möchtest also {STR_VAR_1}\n"
	.string "haben?$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM::
	.string "O.K.! Du willst eine\n"
	.string "TM von {STR_VAR_2}?$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins::
	.string "Schade. Du hast zu wenig MÜNZEN!$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom::
	.string "おきゃくさん もう もてないよ$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen::
	.string "あっ そう$"

