SixIsland_PatternBush_Text_BethanyIntro::
    .ifdef ENGLISH
    .string "I'm curious, how do you raise your\n"
    .string "POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "Oye, que me pica la curiosidad,\n"
    .string "¿cómo crías a tus POKéMON?$"
    .endif

SixIsland_PatternBush_Text_BethanyDefeat::
    .ifdef ENGLISH
    .string "You raise your POKéMON with a\n"
    .string "whole lot of love!$"
    .endif
    .ifdef SPANISH
    .string "¡Veo que con mucho cariño!$"
    .endif

SixIsland_PatternBush_Text_BethanyPostBattle::
    .ifdef ENGLISH
    .string "In the same way your mother raised\n"
    .string "you full of love, you should raise\l"
    .string "your POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "Hay que criarlos con el mismo\n"
    .string "cariño con el que una madre cría\l"
    .string "a sus pequeños.$"
    .endif

SixIsland_PatternBush_Text_AllisonIntro::
    .ifdef ENGLISH
    .string "I'm working to preserve the natural\n"
    .string "ecology of POKéMON here.$"
    .endif
    .ifdef SPANISH
    .string "Yo me encargo de preservar el\n"
    .string "entorno natural de los POKéMON.$"
    .endif

SixIsland_PatternBush_Text_AllisonDefeat::
    .ifdef ENGLISH
    .string "Oh, for someone so young, you are\n"
    .string "tremendous!$"
    .endif
    .ifdef SPANISH
    .string "¡Para la edad que tienes,\n"
    .string "eres increíble!$"
    .endif

SixIsland_PatternBush_Text_AllisonPostBattle::
    .ifdef ENGLISH
    .string "I'm not saying that you shouldn't\n"
    .string "catch POKéMON.\p"
    .string "I just want people to raise their\n"
    .string "POKéMON responsibly.$"
    .endif
    .ifdef SPANISH
    .string "¡Yo no he dicho que no debas\n"
    .string "atrapar POKéMON!\p"
    .string "Sólo quiero que la gente los críe\n"
    .string "de forma responsable.$"
    .endif

SixIsland_PatternBush_Text_GarretIntro::
    .ifdef ENGLISH
    .string "I caught a BUG POKéMON that lives\n"
    .string "only around here!$"
    .endif
    .ifdef SPANISH
    .string "He atrapado un POKéMON del tipo\n"
    .string "BICHO que sólo vive por aquí.$"
    .endif

SixIsland_PatternBush_Text_GarretDefeat::
    .ifdef ENGLISH
    .string "Heheh…\n"
    .string "Isn't my POKéMON awesome?$"
    .endif
    .ifdef SPANISH
    .string "Je, je, je...\n"
    .string "¿No es impresionante mi POKéMON?$"
    .endif

SixIsland_PatternBush_Text_GarretPostBattle::
    .ifdef ENGLISH
    .string "There's a girl near the BUSH who\n"
    .string "measures HERACROSS for TRAINERS.$"
    .endif
    .ifdef SPANISH
    .string "Hay una chica cerca del arbusto,\n"
    .string "que mide las fuerzas de HERACROSS.$"
    .endif

SixIsland_PatternBush_Text_JonahIntro::
    .ifdef ENGLISH
    .string "You know, it just doesn't feel right\n"
    .string "if I don't use BUG POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¿Sabes? Si no uso POKéMON del tipo\n"
    .string "BICHO, no disfruto los combates.$"
    .endif

SixIsland_PatternBush_Text_JonahDefeat::
    .ifdef ENGLISH
    .string "It's okay, losing is a fun part of\n"
    .string "POKéMON's appeal, too.$"
    .endif
    .ifdef SPANISH
    .string "No pasa nada, perder tiene también\n"
    .string "su encanto.$"
    .endif

SixIsland_PatternBush_Text_JonahPostBattle::
    .ifdef ENGLISH
    .string "By the way, “appeal” is a weird\n"
    .string "word, if you think about it.\p"
    .string "Like, is it like an orange peel?\n"
    .string "Or like a ringing bell?$"
    .endif
    .ifdef SPANISH
    .string "A todo esto, lo del “encanto”\n"
    .string "lo digo porque hay que saber\l"
    .string "ganar y perder.\p"
    .string "Es como el blanco y el negro,\n"
    .string "como el día y la noche. ¿No?$"
    .endif

SixIsland_PatternBush_Text_VanceIntro::
    .ifdef ENGLISH
    .string "Yeah, yeah, yeah!\n"
    .string "Look at all the BUG POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Mira qué POKéMON del tipo BICHO\n"
    .string "tengo! ¡Sí, señor!$"
    .endif

SixIsland_PatternBush_Text_VanceDefeat::
    .ifdef ENGLISH
    .string "I got beat while I was still busy\n"
    .string "celebrating!$"
    .endif
    .ifdef SPANISH
    .string "¡Me han ganado en plena euforia!$"
    .endif

SixIsland_PatternBush_Text_VancePostBattle::
    .ifdef ENGLISH
    .string "I'm going to bring my little brother\n"
    .string "here next time.$"
    .endif
    .ifdef SPANISH
    .string "La próxima vez, me vengo con mi\n"
    .string "hermano pequeño.$"
    .endif

SixIsland_PatternBush_Text_NashIntro::
    .ifdef ENGLISH
    .string "Look, look! There are funny\n"
    .string "patterns on the ground.$"
    .endif
    .ifdef SPANISH
    .string "¡Mira al suelo!\n"
    .string "Qué dibujos más raros... ¿verdad?$"
    .endif

SixIsland_PatternBush_Text_NashDefeat::
    .ifdef ENGLISH
    .string "Super awesome!$"
    .endif
    .ifdef SPANISH
    .string "¡Increíble!$"
    .endif

SixIsland_PatternBush_Text_NashPostBattle::
    .ifdef ENGLISH
    .string "The funny patterns on the ground…\p"
    .string "They look like the patterns on my\n"
    .string "grandpa's clothes.$"
    .endif
    .ifdef SPANISH
    .string "Los dibujos tan raros del suelo...\p"
    .string "¡Se parecen al estampado de\n"
    .string "la ropa de mi abuelo!$"
    .endif

SixIsland_PatternBush_Text_CordellIntro::
    .ifdef ENGLISH
    .string "I bet you think I'm just some guy,\n"
    .string "don't you, eh?$"
    .endif
    .ifdef SPANISH
    .string "Crees que soy inofensivo, ¿eh?$"
    .endif

SixIsland_PatternBush_Text_CordellDefeat::
    .ifdef ENGLISH
    .string "I bet you think I'm weak,\n"
    .string "don't you, eh?$"
    .endif
    .ifdef SPANISH
    .string "Crees que soy débil, ¿no?$"
    .endif

SixIsland_PatternBush_Text_CordellPostBattle::
    .ifdef ENGLISH
    .string "Ayup, you townies come around all\n"
    .string "so dandy with a hat that flashy…\p"
    .string "How about giving me that?$"
    .endif
    .ifdef SPANISH
    .string "La gente de ciudad siempre viene\n"
    .string "dándose demasiados aires...\p"
    .string "Aunque a mí no me vendrían\n"
    .string "mal unos pocos...$"
    .endif

SixIsland_PatternBush_Text_DaliaIntro::
    .ifdef ENGLISH
    .string "Take a deep breath.\n"
    .string "Isn't the air delicious?$"
    .endif
    .ifdef SPANISH
    .string "¡Mmmm, respira hondo!\n"
    .string "Qué aire tan puro...$"
    .endif

SixIsland_PatternBush_Text_DaliaDefeat::
    .ifdef ENGLISH
    .string "If you'd like, I can teach you how\n"
    .string "to breathe properly.$"
    .endif
    .ifdef SPANISH
    .string "Si quieres, puedo enseñarte\n"
    .string "técnicas de respiración.$"
    .endif

SixIsland_PatternBush_Text_DaliaPostBattle::
    .ifdef ENGLISH
    .string "First, exhale.\n"
    .string "Blow everything out.\p"
    .string "When you can't exhale anymore,\n"
    .string "inhale the clean air!\p"
    .string "Isn't it refreshing?$"
    .endif
    .ifdef SPANISH
    .string "Espira...\n"
    .string "Hasta que no te quede aire...\p"
    .string "Cuando no puedas espirar más,\n"
    .string "¡inspira!\p"
    .string "¿No es una sensación de frescor\n"
    .string "fantástica?$"
    .endif

SixIsland_PatternBush_Text_JoanaIntro::
    .ifdef ENGLISH
    .string "I love BUG POKéMON.\n"
    .string "That's why I'm here all the time.\p"
    .string "Am I the only girl like that?$"
    .endif
    .ifdef SPANISH
    .string "Me encantan los POKéMON del tipo\n"
    .string "BICHO. Por eso estoy siempre aquí.\p"
    .string "Supongo que no seré la única...$"
    .endif

SixIsland_PatternBush_Text_JoanaDefeat::
    .ifdef ENGLISH
    .string "I lost, but I'm still laughing.\n"
    .string "Am I the only girl like that?$"
    .endif
    .ifdef SPANISH
    .string "No pienso perder la sonrisa.\n"
    .string "Supongo que no soy la única...$"
    .endif

SixIsland_PatternBush_Text_JoanaPostBattle::
    .ifdef ENGLISH
    .string "I'm going to keep on collecting\n"
    .string "BUG POKéMON.\p"
    .string "Am I the only girl like that?$"
    .endif
    .ifdef SPANISH
    .string "Voy a seguir coleccionando\n"
    .string "POKéMON del tipo BICHO.\p"
    .string "Supongo que no soy la única...$"
    .endif

SixIsland_PatternBush_Text_RileyIntro::
    .ifdef ENGLISH
    .string "This is a good spot.\n"
    .string "I'll pitch my tent here.$"
    .endif
    .ifdef SPANISH
    .string "Este sitio es estupendo.\n"
    .string "Voy a colocar la tienda aquí.$"
    .endif

SixIsland_PatternBush_Text_RileyDefeat::
    .ifdef ENGLISH
    .string "Wimped out…$"
    .endif
    .ifdef SPANISH
    .string "Qué paliza...$"
    .endif

SixIsland_PatternBush_Text_RileyPostBattle::
    .ifdef ENGLISH
    .string "I'm going to observe the night sky\n"
    .string "here.$"
    .endif
    .ifdef SPANISH
    .string "Me quedaré aquí para observar\n"
    .string "las estrellas.$"
    .endif

SixIsland_PatternBush_Text_MarcyIntro::
    .ifdef ENGLISH
    .string "Oh, yuck!\n"
    .string "I think a bug stung me!$"
    .endif
    .ifdef SPANISH
    .string "¡Ay!\n"
    .string "Creo que me ha picado algo...$"
    .endif

SixIsland_PatternBush_Text_MarcyDefeat::
    .ifdef ENGLISH
    .string "It wasn't a bug.\n"
    .string "I cut my shin on some grass.$"
    .endif
    .ifdef SPANISH
    .string "No ha sido ningún bicho, me he\n"
    .string "cortado con el césped.$"
    .endif

SixIsland_PatternBush_Text_MarcyPostBattle::
    .ifdef ENGLISH
    .string "A little cut like that…\n"
    .string "A little spit's enough to cure it!$"
    .endif
    .ifdef SPANISH
    .string "Un cortecillo así...\n"
    .string "Se cura con un poco de saliva.$"
    .endif

SixIsland_PatternBush_Text_LaytonIntro::
    .ifdef ENGLISH
    .string "Have you noticed something odd\n"
    .string "about these parts?$"
    .endif
    .ifdef SPANISH
    .string "¿Has visto algo raro por aquí?$"
    .endif

SixIsland_PatternBush_Text_LaytonDefeat::
    .ifdef ENGLISH
    .string "Have you taken a good look around\n"
    .string "your feet?$"
    .endif
    .ifdef SPANISH
    .string "Yo que tú, miraría bien\n"
    .string "por el suelo.$"
    .endif

SixIsland_PatternBush_Text_LaytonPostBattle::
    .ifdef ENGLISH
    .string "There are places here in PATTERN\n"
    .string "BUSH where grass won't grow.\p"
    .string "What could be the cause of such\n"
    .string "a phenomenon?$"
    .endif
    .ifdef SPANISH
    .string "Hay sitios en el BOSQUEJO,\n"
    .string "en los que no crece la hierba.\p"
    .string "¿Por qué será?$"
    .endif

