SilphCo_10F_Text_GruntIntro::
    .ifdef ENGLISH
    .string "Welcome to 10F!\n"
    .string "So good of you to join me!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, éste es el noveno piso!\n"
    .string "¡Me alegra que hayas venido!$"
    .endif

SilphCo_10F_Text_GruntDefeat::
    .ifdef ENGLISH
    .string "I'm stunned!$"
    .endif
    .ifdef SPANISH
    .string "¡Estoy aturdido!$"
    .endif

SilphCo_10F_Text_GruntPostBattle::
    .ifdef ENGLISH
    .string "Nice try, but the boardroom is up\n"
    .string "one more floor.$"
    .endif
    .ifdef SPANISH
    .string "¡Bien hecho, pero la sala del\n"
    .string "consejo está un piso más arriba!$"
    .endif

SilphCo_10F_Text_TravisIntro::
    .ifdef ENGLISH
    .string "Enough of your silly games!$"
    .endif
    .ifdef SPANISH
    .string "¡Ya está bien de tonterías!$"
    .endif

SilphCo_10F_Text_TravisDefeat::
    .ifdef ENGLISH
    .string "No continues left!$"
    .endif
    .ifdef SPANISH
    .string "¡Se acabó lo que se daba!$"
    .endif

SilphCo_10F_Text_TravisPostBattle::
    .ifdef ENGLISH
    .string "Are you satisfied with beating me?\n"
    .string "Then go on home!$"
    .endif
    .ifdef SPANISH
    .string "¿Te alegra haberme ganado?\n"
    .string "¡Pues vete a casa!$"
    .endif

SilphCo_10F_Text_WaaaImScared::
    .ifdef ENGLISH
    .string "Waaaaa!\n"
    .string "I'm scared!$"
    .endif
    .ifdef SPANISH
    .string "¡Buaaaa!\n"
    .string "¡Tengo miedo!$"
    .endif

SilphCo_10F_Text_KeepMeCryingASecret::
    .ifdef ENGLISH
    .string "About me crying…\n"
    .string "Please keep it a secret.$"
    .endif
    .ifdef SPANISH
    .string "¡Por favor, no le digas a nadie\n"
    .string "que he llorado!$"
    .endif

SilphCo_10F_Text_FloorSign::
    .ifdef ENGLISH
    .string "SILPH CO. HEAD OFFICE\n"
    .string "10F$"
    .endif
    .ifdef SPANISH
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P9$"
    .endif

