SilphCo_10F_Text_GruntIntro::
	.string "Willkommen im 9. Stock! Es ist\n"
	.string "nett, dass du vorbeischaust!$"

SilphCo_10F_Text_GruntDefeat::
	.string "Ich bin geschockt!$"

SilphCo_10F_Text_GruntPostBattle::
	.string "Netter Versuch!\n"
	.string "Der Sitzungssaal befindet sich aber\l"
	.string "noch ein Stockwerk höher!$"

SilphCo_10F_Text_TravisIntro::
	.string "Genug von deinen dummen Spielchen!$"

SilphCo_10F_Text_TravisDefeat::
	.string "Meine Reserven sind erschöpft!$"

SilphCo_10F_Text_TravisPostBattle::
	.string "Freut es dich, mich besiegt zu\n"
	.string "haben? Mann, hau endlich ab!$"

SilphCo_10F_Text_WaaaImScared::
	.string "Hilfe!\n"
	.string "Ich habe Angst!$"

SilphCo_10F_Text_KeepMeCryingASecret::
	.string "Verrate bitte niemandem, dass ich\n"
	.string "geweint habe!$"

SilphCo_10F_Text_FloorSign::
	.string "SILPH CO. HAUPTSITZ\n"
	.string "9 OG$"

