SilphCo_10F_Text_GruntIntro::
	.string "Bienvenue au 9ème étage!\n"
	.string "C'est sympa de passer!$"

SilphCo_10F_Text_GruntDefeat::
	.string "Aïe!\n"
	.string "Bobo!$"

SilphCo_10F_Text_GruntPostBattle::
	.string "Bien joué, mais la salle du\n"
	.string "conseil est au-dessus!$"

SilphCo_10F_Text_TravisIntro::
	.string "Maintenant…\n"
	.string "Fini de jouer!$"

SilphCo_10F_Text_TravisDefeat::
	.string "Oh!\n"
	.string "Game Over!$"

SilphCo_10F_Text_TravisPostBattle::
	.string "T'as gagné!\n"
	.string "Alors retourne chez toi!$"

SilphCo_10F_Text_WaaaImScared::
	.string "Waaaaa!\n"
	.string "Mamaaaan!$"

SilphCo_10F_Text_KeepMeCryingASecret::
	.string "Ne raconte à personne que j'ai\n"
	.string "pleuré!$"

SilphCo_10F_Text_FloorSign::
	.string "SYLPHE SARL.\n"
	.string "9ème étage.$"

