SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale::
    .ifdef ENGLISH
    .string "{PLAYER}: Hi!\n"
    .string "Do you like POKéMON?\p"
    .string "{PLAYER}: Uh, no, I just asked you.\p"
    .string "{PLAYER}: Huh?\n"
    .string "You're strange!\p"
    .string "COPYCAT: Hmm? Quit mimicking?\n"
    .string "But, that's my favorite hobby!$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER}: ¡Hola!\n"
    .string "¿Te gustan los POKéMON?\p"
    .string "{PLAYER}: ¿No?\n"
    .string "Oye, te he hecho una pregunta.\p"
    .string "{PLAYER}: ¿Eh?\n"
    .string "Eres un poquito raro, ¿no?\p"
    .string "COPIONA: ¿Qué? ¿Que deje\n"
    .string "de imitar? ¡Es mi hobby favorito!$"
    .endif

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale::
    .ifdef ENGLISH
    .string "{PLAYER}: Hi.\n"
    .string "You must like POKéMON.\p"
    .string "{PLAYER}: No, not me.\n"
    .string "I asked you.\p"
    .string "{PLAYER}: Pardon?\n"
    .string "You're weird!\l"
    .string " \l"
    .string "COPYCAT: Hmm? Quit mimicking?\l"
    .string "But that's my favorite hobby!$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER}: ¡Hola!\n"
    .string "¿Te gustan los POKéMON?\p"
    .string "{PLAYER}: ¿No?\n"
    .string "Oye, te he hecho una pregunta.\p"
    .string "{PLAYER}: ¿Eh?\n"
    .string "Eres un poquito rara, ¿no?\p"
    .string "COPIONA: ¿Qué? ¿Que deje\n"
    .string "de imitar? ¡Es mi hobby favorito!$"
    .endif

Text_MimicTeach::
    .ifdef ENGLISH
    .string "Oh wow!\n"
    .string "A POKé DOLL!\p"
    .string "For me?\n"
    .string "Thank you!\p"
    .string "You know what?\n"
    .string "I can teach the move MIMIC.$"
    .endif
    .ifdef SPANISH
    .string "¡Uauuu!\n"
    .string "¡Un POKé MUÑECO!\p"
    .string "¿Es para mí?\n"
    .string "¡Gracias!\p"
    .string "¿Sabes una cosa? Podría\n"
    .string "enseñarte el movimiento MIMÉTICO.$"
    .endif

Text_MimicDeclined::
    .ifdef ENGLISH
    .string "Don't you like MIMIC?$"
    .endif
    .ifdef SPANISH
    .string "¿No tienes interés en MIMÉTICO?$"
    .endif

Text_MimicWhichMon::
    .ifdef ENGLISH
    .string "I really love MIMIC!\n"
    .string "Who's going to learn it?$"
    .endif
    .ifdef SPANISH
    .string "¡Bien, a mí me encanta!\n"
    .string "¿A qué POKéMON quieres que\l"
    .string "le enseñe MIMÉTICO?$"
    .endif

Text_MimicTaughtMale::
    .ifdef ENGLISH
    .string "{PLAYER}: Hi!\n"
    .string "Thanks for earlier!\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it that fun to mimic my\n"
    .string "every move?\p"
    .string "COPYCAT: You bet!\n"
    .string "It's a scream!$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER}: ¡Hola!\n"
    .string "¡Gracias por lo de antes!\p"
    .string "{PLAYER}: ¿Sí?\p"
    .string "{PLAYER}: ¿Te divierte imitar cada\n"
    .string "uno de mis movimientos?\p"
    .string "COPIONA: ¿Verdad?\n"
    .string "¡Es muy divertido!$"
    .endif

Text_MimicTaughtFemale::
    .ifdef ENGLISH
    .string "{PLAYER}: Hi!\n"
    .string "Thanks for what you did for us.\p"
    .string "{PLAYER}: Pardon?\p"
    .string "{PLAYER}: Is it really that fun to\n"
    .string "copy what I say and do?\p"
    .string "COPYCAT: You bet!\n"
    .string "It's a scream!$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER}: ¡Hola!\n"
    .string "¡Gracias por lo de antes!\p"
    .string "{PLAYER}: ¿Sí?\p"
    .string "{PLAYER}: ¿Te divierte imitar cada\n"
    .string "uno de mis movimientos?\p"
    .string "COPIONA: ¿Verdad?\n"
    .string "¡Es muy divertido!$"
    .endif

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag::
    .string "にもつが　いっぱいね！$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP::
    .string "{PLAYER}“やあ！　こんにちは！\n"
    .string "きみ　ポケモン　すきかい？\p"
    .string "{PLAYER}“ぼく　じゃなくって\n"
    .string "きみに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥‥　えー　なんだよ！\n"
    .string "ヘンな　やつ　だなあ！\p"
    .string "モノマネむすめ“‥‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし　\n"
    .string "ものまね　しゅみ　なんだ　もん！”$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP::
    .string "{PLAYER}“こんにちは！\n"
    .string "ポケモン　すきなのね？\p"
    .string "{PLAYER}“わたし　じゃなくって\n"
    .string "あなたに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥　えー　なんなの！\n"
    .string "おかしなこ　ねー！\p"
    .string "モノマネむすめ“‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし\n"
    .string "ものまね　しゅみ　なんだ　もん！$"

SaffronCity_CopycatsHouse_2F_Text_Doduo::
    .ifdef ENGLISH
    .string "DODUO: Giiih!\p"
    .string "PRETTY MIRROR LOOK AT ME,\n"
    .string "SEE HOW PRETTY I CAN BE?$"
    .endif
    .ifdef SPANISH
    .string "DODUO: ¡Dodu!\p"
    .string "¡ESPEJO, ESPEJITO! ¿QUIÉN ES\n"
    .string "LA MÁS BELLA DE TODAS?$"
    .endif

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll::
    .ifdef ENGLISH
    .string "This is a rare POKéMON!\n"
    .string "Huh? It's only a doll!$"
    .endif
    .ifdef SPANISH
    .string "¡Éste es un POKéMON raro!\n"
    .string "¿Eh? ¡Pero si es un muñeco!$"
    .endif

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
    .ifdef ENGLISH
    .string "A game with MARIO wearing a bucket\n"
    .string "on his head!$"
    .endif
    .ifdef SPANISH
    .string "¡Un juego de MARIO con un cubo\n"
    .string "en la cabeza!$"
    .endif

SaffronCity_CopycatsHouse_2F_Text_MySecrets::
    .ifdef ENGLISH
    .string "…\p"
    .string "My Secrets!\p"
    .string "Skill: Mimicry!\n"
    .string "Hobby: Collecting dolls!\l"
    .string "Favorite POKéMON: CLEFAIRY!$"
    .endif
    .ifdef SPANISH
    .string "...\p"
    .string "¡Éstos son mis secretos!\p"
    .string "Habilidad: imitar.\n"
    .string "Hobby: coleccionar muñecos.\l"
    .string "POKéMON favorito: ¡CLEFAIRY!$"
    .endif

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee::
    .string "？　みえないぞ‥$"
