PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .ifdef ENGLISH
    .string "MOM: …Right.\n"
    .string "All boys leave home someday.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"
    .endif
    .ifdef SPANISH
    .string "MAMÁ: En fin...\n"
    .string "Todos los niños se van de casa\l"
    .string "algún día. ¡Así es la vida!\p"
    .string "Ah, nuestro vecino, el PROF. OAK,\n"
    .string "quería verte.$"
    .endif

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .ifdef ENGLISH
    .string "MOM: …Right.\n"
    .string "All girls dream of traveling.\l"
    .string "It said so on TV.\p"
    .string "Oh, yes. PROF. OAK, next door, was\n"
    .string "looking for you.$"
    .endif
    .ifdef SPANISH
    .string "MAMÁ: En fin...\n"
    .string "Todos los niños se van de casa\l"
    .string "algún día. ¡Así es la vida!\p"
    .string "Ah, nuestro vecino, el PROF. OAK,\n"
    .string "quería verte.$"
    .endif

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .ifdef ENGLISH
    .string "MOM: {PLAYER}!\n"
    .string "You should take a quick rest.$"
    .endif
    .ifdef SPANISH
    .string "MAMÁ: ¡{PLAYER}!\n"
    .string "Deberías tomarte un descanso.$"
    .endif

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .ifdef ENGLISH
    .string "MOM: Oh, good! You and your\n"
    .string "POKéMON are looking great.\l"
    .string "Take care now!$"
    .endif
    .ifdef SPANISH
    .string "MAMÁ: ¡Muy bien! ¡Tú y tus\n"
    .string "POKéMON estáis en plena forma!\l"
    .string "¡Cuídate!$"
    .endif

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .ifdef ENGLISH
    .string "There's a movie on TV.\n"
    .string "Four boys are walking on railroad\l"
    .string "tracks.\p"
    .string "…I better go, too.$"
    .endif
    .ifdef SPANISH
    .string "Están poniendo una peli...\n"
    .string "Salen cuatro niños caminando\l"
    .string "por las vías del tren...\p"
    .string "Bueno, voy a ponerme en marcha.$"
    .endif

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .ifdef ENGLISH
    .string "There's a movie on TV.\n"
    .string "A girl with her hair in pigtails is\l"
    .string "walking up a brick road.\p"
    .string "…I better go, too.$"
    .endif
    .ifdef SPANISH
    .string "Están poniendo una peli...\n"
    .string "Sale una chica con coletas andando\l"
    .string "por una calle empedrada...\p"
    .string "Bueno, voy a ponerme en marcha.$"
    .endif

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .ifdef ENGLISH
    .string "Oops, wrong side…$"
    .endif
    .ifdef SPANISH
    .string "¡Ay! Me he equivocado de lado.$"
    .endif

