PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "MAMÁ: En fin...\n"
    .string "Todos los niños se van de casa\l"
    .string "algún día. ¡Así es la vida!\p"
    .string "Ah, nuestro vecino, el PROF. OAK,\n"
    .string "quería verte.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "MAMÁ: En fin...\n"
    .string "Todos los niños se van de casa\l"
    .string "algún día. ¡Así es la vida!\p"
    .string "Ah, nuestro vecino, el PROF. OAK,\n"
    .string "quería verte.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "MAMÁ: ¡{PLAYER}!\n"
    .string "Deberías tomarte un descanso.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "MAMÁ: ¡Muy bien! ¡Tú y tus\n"
    .string "POKéMON estáis en plena forma!\l"
    .string "¡Cuídate!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "Están poniendo una peli...\n"
    .string "Salen cuatro niños caminando\l"
    .string "por las vías del tren...\p"
    .string "Bueno, voy a ponerme en marcha.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "Están poniendo una peli...\n"
    .string "Sale una chica con coletas andando\l"
    .string "por una calle empedrada...\p"
    .string "Bueno, voy a ponerme en marcha.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "¡Ay! Me he equivocado de lado.$"
