LavenderTown_House2_Text_WantMeToRateNicknames::
    .ifdef ENGLISH
    .string "Hello, hello!\n"
    .string "I am the official NAME RATER!\p"
    .string "Want me to rate the nicknames of\n"
    .string "your POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¡Je, je! ¡Hola!\n"
    .string "¡Soy el INSPECTOR de los MOTES!\l"
    .string "¡El adivinador de nombres!\p"
    .string "Estaré encantado de evaluar\n"
    .string "el nombre de tu POKéMON, je, je.$"
    .endif

LavenderTown_House2_Text_CritiqueWhichMonsNickname::
    .ifdef ENGLISH
    .string "Which POKéMON's nickname should\n"
    .string "I critique?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué nombre de POKéMON\n"
    .string "quieres que adivine y evalúe?$"
    .endif

LavenderTown_House2_Text_GiveItANicerName::
    .ifdef ENGLISH
    .string "{STR_VAR_1}, is it?\n"
    .string "That is a decent nickname!\p"
    .string "But, would you like me to give it\n"
    .string "a nicer name?\p"
    .string "How about it?$"
    .endif
    .ifdef SPANISH
    .string "Mmmmm... {STR_VAR_1}, ¿a que sí?\n"
    .string "No está mal, no está mal...\p"
    .string "Pero ¿no crees que podríamos\n"
    .string "encontrar un nombre aún mejor?$"
    .endif

LavenderTown_House2_Text_WhatShallNewNicknameBe::
    .ifdef ENGLISH
    .string "Ah, good. Then, what shall the new\n"
    .string "nickname be?$"
    .endif
    .ifdef SPANISH
    .string "Así me gusta. A ver... \n"
    .string "¿Cuál será el nuevo nombre?$"
    .endif

LavenderTown_House2_Text_FromNowOnShallBeKnownAsName::
    .ifdef ENGLISH
    .string "Done! From now on, this POKéMON\n"
    .string "shall be known as {STR_VAR_1}!\p"
    .string "It is a better name than before!\n"
    .string "How fortunate for you!$"
    .endif
    .ifdef SPANISH
    .string "¡Ya está! ¡A partir de ahora,\n"
    .string "el nombre de este POKéMON\l"
    .string "será {STR_VAR_1}!\p"
    .string "Es un nombre mucho mejor que\n"
    .string "el anterior, ¡qué suerte tienes!$"
    .endif

LavenderTown_House2_Text_ISeeComeVisitAgain::
    .ifdef ENGLISH
    .string "I see.\n"
    .string "Do come visit again.$"
    .endif
    .ifdef SPANISH
    .string "Muy bien...\n"
    .string "Entonces vuelve cuando quieras.$"
    .endif

LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName::
    .ifdef ENGLISH
    .string "Done! From now on, this POKéMON\n"
    .string "shall be known as {STR_VAR_1}!\p"
    .string "It looks no different from before,\n"
    .string "and yet, this is vastly superior!\p"
    .string "How fortunate for you!$"
    .endif
    .ifdef SPANISH
    .string "¡Ya está! ¡A partir de ahora,\n"
    .string "el nombre de este POKéMON\l"
    .string "será {STR_VAR_1}!\p"
    .string "No parece muy diferente\n"
    .string "del anterior y, sin embargo,\l"
    .string "es muchísimo mejor.\p"
    .string "¡Qué suerte tienes!$"
    .endif

LavenderTown_House2_Text_TrulyImpeccableName::
    .ifdef ENGLISH
    .string "{STR_VAR_1}, is it?\n"
    .string "That is a truly impeccable name!\p"
    .string "Take good care of {STR_VAR_1}!$"
    .endif
    .ifdef SPANISH
    .string "¿{STR_VAR_1}?\n"
    .string "¡Ese nombre es perfecto!\p"
    .string "¡Cuida bien de {STR_VAR_1}!$"
    .endif

LavenderTown_House2_Text_ThatIsMerelyAnEgg::
    .ifdef ENGLISH
    .string "Now, now.\n"
    .string "That is merely an EGG!$"
    .endif
    .ifdef SPANISH
    .string "Pero vamos a ver...\n"
    .string "¡Esto es sólo un HUEVO!$"
    .endif

