RocketHideout_B3F_Text_Grunt1Intro::
    .ifdef ENGLISH
    .string "Stop meddling in TEAM ROCKET's\n"
    .string "affairs or else!$"
    .endif
    .ifdef SPANISH
    .string "¡Deja de meterte en los asuntos\n"
    .string "del TEAM ROCKET!$"
    .endif

RocketHideout_B3F_Text_Grunt1Defeat::
    .ifdef ENGLISH
    .string "Oof!\n"
    .string "Taken down!$"
    .endif
    .ifdef SPANISH
    .string "¡Uff!\n"
    .string "¡Me ha machacado!$"
    .endif

RocketHideout_B3F_Text_Grunt1PostBattle::
    .ifdef ENGLISH
    .string "SILPH SCOPE?\n"
    .string "Oh, that machine the BOSS stole.\p"
    .string "It's here somewhere.$"
    .endif
    .ifdef SPANISH
    .string "¿El SCOPE SILPH?\n"
    .string "Ah, la máquina que robó el JEFE.\p"
    .string "Debe de estar por aquí.$"
    .endif

RocketHideout_B3F_Text_Grunt2Intro::
    .ifdef ENGLISH
    .string "We got word from upstairs that you\n"
    .string "were coming!$"
    .endif
    .ifdef SPANISH
    .string "¡Nos dijeron desde arriba que\n"
    .string "venías!$"
    .endif

RocketHideout_B3F_Text_Grunt2Defeat::
    .ifdef ENGLISH
    .string "What?\n"
    .string "I lost? No!$"
    .endif
    .ifdef SPANISH
    .string "¿Qué?\n"
    .string "¿He perdido? ¡NO!$"
    .endif

RocketHideout_B3F_Text_Grunt2PostBattle::
    .ifdef ENGLISH
    .string "Go ahead and go!\p"
    .string "But you can't run the elevator\n"
    .string "without the LIFT KEY.$"
    .endif
    .ifdef SPANISH
    .string "¡Venga, adelante!\p"
    .string "¡Pero necesitarás la LLAVE\n"
    .string "del ASCENSOR!$"
    .endif

