RocketHideout_B3F_Text_Grunt1Intro::
    .string "¡Deja de meterte en los asuntos\n"
    .string "del TEAM ROCKET!$"

RocketHideout_B3F_Text_Grunt1Defeat::
    .string "¡Uff!\n"
    .string "¡Me ha machacado!$"

RocketHideout_B3F_Text_Grunt1PostBattle::
    .string "¿El SCOPE SILPH?\n"
    .string "Ah, la máquina que robó el JEFE.\p"
    .string "Debe de estar por aquí.$"

RocketHideout_B3F_Text_Grunt2Intro::
    .string "¡Nos dijeron desde arriba que\n"
    .string "venías!$"

RocketHideout_B3F_Text_Grunt2Defeat::
    .string "¿Qué?\n"
    .string "¿He perdido? ¡NO!$"

RocketHideout_B3F_Text_Grunt2PostBattle::
    .string "¡Venga, adelante!\p"
    .string "¡Pero necesitarás la LLAVE\n"
    .string "del ASCENSOR!$"
