SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies::
    .ifdef ENGLISH
    .string "POKéMON growth rates differ from\n"
    .string "species to species.$"
    .endif
    .ifdef SPANISH
    .string "La velocidad de crecimiento de los\n"
    .string "POKéMON varía de una especie a\l"
    .string "otra.$"
    .endif

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame::
    .ifdef ENGLISH
    .string "SILPH CO. is widely known to all.\p"
    .string "It's a victim of its own fame - it\n"
    .string "attracted TEAM ROCKET.$"
    .endif
    .ifdef SPANISH
    .string "SILPH S.A. es muy famosa.\p"
    .string "¡Por eso el TEAM ROCKET tiene\n"
    .string "tanto interés en ella!$"
    .endif

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets::
    .ifdef ENGLISH
    .string "Sigh…\n"
    .string "Wouldn't this be great?\p"
    .string "If the ELITE FOUR came and\n"
    .string "stomped TEAM ROCKET?$"
    .endif
    .ifdef SPANISH
    .string "¡Sería estupendo que el ALTO\n"
    .string "MANDO viniera y machacara al TEAM\l"
    .string "ROCKET!$"
    .endif

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff::
    .ifdef ENGLISH
    .string "TEAM ROCKET took off!\n"
    .string "We can go out safely again!\l"
    .string "That's great!$"
    .endif
    .ifdef SPANISH
    .string "¡El TEAM ROCKET se ha ido!\n"
    .string "¡Ahora podemos salir sin peligro!\l"
    .string "¡Bien!$"
    .endif

