SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies::
	.string "Der Zeitpunkt der Entwicklung ist\n"
	.string "von POKéMON zu POKéMON\l"
	.string "unterschiedlich.$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame::
	.string "Die SILPH CO. ist sehr bekannt.\p"
	.string "Deshalb wurde das TEAM ROCKET auf\n"
	.string "sie aufmerksam!$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets::
	.string "Ich wünschte, die TOP VIER kämen\n"
	.string "und stampften das TEAM ROCKET in\l"
	.string "den Boden!$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff::
	.string "Das TEAM ROCKET ist geflohen! Wir\n"
	.string "können wieder aus dem Haus gehen!$"

