Route16_House_Text_FoundMySecretRetreat::
    .ifdef ENGLISH
    .string "Oh, dear.\n"
    .string "You've found my secret retreat.\p"
    .string "Please don't tell anyone I'm here.\n"
    .string "I'll make it up to you with this!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh!\n"
    .string "¡Has encontrado mi escondite!\p"
    .string "Por favor, no le digas a nadie que\n"
    .string "estoy aquí, ¡te ayudaré!$"
    .endif

Route16_House_Text_ReceivedHM02FromGirl::
    .ifdef ENGLISH
    .string "{PLAYER} received HM02\n"
    .string "from the girl.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo la MO02\n"
    .string "de manos de la chica!$"
    .endif

Route16_House_Text_ExplainHM02::
    .ifdef ENGLISH
    .string "HM02 is FLY.\n"
    .string "It's a wonderfully convenient move.\p"
    .string "Please, put it to good use.$"
    .endif
    .ifdef SPANISH
    .string "MO02 es VOLAR. Ésta te llevará\n"
    .string "de vuelta a cualquier ciudad.\p"
    .string "¡Úsala bien!$"
    .endif

Route16_House_Text_DontHaveAnyRoomForThis::
    .ifdef ENGLISH
    .string "You don't have any room for this.$"
    .endif
    .ifdef SPANISH
    .string "No tienes sitio para esto.$"
    .endif

Route16_House_Text_Fearow::
    .ifdef ENGLISH
    .string "FEAROW: Kyueen!$"
    .endif
    .ifdef SPANISH
    .string "FEAROW: ¡Fea, row, row!$"
    .endif

