Route16_House_Text_FoundMySecretRetreat::
    .string "¡Oh!\n"
    .string "¡Has encontrado mi escondite!\p"
    .string "Por favor, no le digas a nadie que\n"
    .string "estoy aquí, ¡te ayudaré!$"

Route16_House_Text_ReceivedHM02FromGirl::
    .string "¡{PLAYER} obtuvo la MO02\n"
    .string "de manos de la chica!$"

Route16_House_Text_ExplainHM02::
    .string "MO02 es VOLAR. Ésta te llevará\n"
    .string "de vuelta a cualquier ciudad.\p"
    .string "¡Úsala bien!$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "No tienes sitio para esto.$"

Route16_House_Text_Fearow::
    .string "FEAROW: ¡Fea, row, row!$"
