PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .ifdef ENGLISH
    .string "POKéMON TOWER was erected in the\n"
    .string "memory of POKéMON that died.$"
    .endif
    .ifdef SPANISH
    .string "La TORRE POKéMON fue erigida\n"
    .string "en memoria de los POKéMON\l"
    .string "que se han debilitado.$"
    .endif

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .ifdef ENGLISH
    .string "Did you come to pay respects?\p"
    .string "Bless your POKéMON-loving heart,\n"
    .string "son.$"
    .endif
    .ifdef SPANISH
    .string "¿Has venido a rendirles homenaje?\p"
    .string "¡Qué majo!$"
    .endif

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .ifdef ENGLISH
    .string "Did you come to pay respects?\p"
    .string "Bless your POKéMON-loving heart,\n"
    .string "girl.$"
    .endif
    .ifdef SPANISH
    .string "¿Has venido a rendirles homenaje?\p"
    .string "¡Qué maja!$"
    .endif

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .ifdef ENGLISH
    .string "I came to pray for my dearly\n"
    .string "departed CLEFAIRY.\p"
    .string "Sniff!\n"
    .string "I'm awash in tears…$"
    .endif
    .ifdef SPANISH
    .string "Vine a rendir homenaje\n"
    .string "a mi CLEFAIRY.\p"
    .string "¡Sniff!\n"
    .string "No puedo dejar de llorar...$"
    .endif

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .ifdef ENGLISH
    .string "My GROWLITHE…\n"
    .string "Why did you die?$"
    .endif
    .ifdef SPANISH
    .string "Mi GROWLITHE... ¿Por qué\n"
    .string "has tenido que debilitarte?$"
    .endif

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .ifdef ENGLISH
    .string "I am a CHANNELER.\p"
    .string "There are spirits up to mischief.\n"
    .string "I sense them high in the TOWER.$"
    .endif
    .ifdef SPANISH
    .string "¡Soy EXORCISTA!\p"
    .string "¡Hay espíritus muy revoltosos\n"
    .string "en esta TORRE!$"
    .endif

