PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
	.string "Der POKéMON-TURM wurde im Andenken\n"
	.string "an verblichene POKéMON errichtet.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
	.string "Bist du hier, um dein Mitgefühl\n"
	.string "auszudrücken? Sei gesegnet!$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
	.string "Bist du hier, um dein Mitgefühl\n"
	.string "auszudrücken? Sei gesegnet!$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
	.string "Ich bete für PIEPI...\p"
	.string "Schluchz! Ich kann nicht aufhören\n"
	.string "zu weinen...$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
	.string "FUKANO...\n"
	.string "Warum hast du mich verlassen?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
	.string "Ich bin eine EXORZISTIN!\n"
	.string "Die Geister hier stiften Unruhe!$"

