PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "La TORRE POKéMON fue erigida\n"
    .string "en memoria de los POKéMON\l"
    .string "que se han debilitado.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "¿Has venido a rendirles homenaje?\p"
    .string "¡Qué majo!$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "¿Has venido a rendirles homenaje?\p"
    .string "¡Qué maja!$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "Vine a rendir homenaje\n"
    .string "a mi CLEFAIRY.\p"
    .string "¡Sniff!\n"
    .string "No puedo dejar de llorar...$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "Mi GROWLITHE... ¿Por qué\n"
    .string "has tenido que debilitarte?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "¡Soy EXORCISTA!\p"
    .string "¡Hay espíritus muy revoltosos\n"
    .string "en esta TORRE!$"
