FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
    .ifdef ENGLISH
    .string "We nicknamed the WARDEN\n"
    .string "“SLOWPOKE.”\p"
    .string "You know, he has that vacant look\n"
    .string "like a SLOWPOKE.$"
    .endif
    .ifdef SPANISH
    .string "Al GUARDA le pusimos de mote:\n"
    .string "SLOWPOKE.\p"
    .string "¡Se parecen un montón; todo\n"
    .string "el día sin hacer nada!$"
    .endif

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
    .ifdef ENGLISH
    .string "WARDEN SLOWPOKE is very\n"
    .string "knowledgeable about POKéMON.\p"
    .string "He even has some fossils of rare,\n"
    .string "extinct POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡SLOWPOKE sabe mucho sobre los\n"
    .string "POKéMON!\p"
    .string "¡Tiene hasta varios fósiles de\n"
    .string "POKéMON raros y extintos!$"
    .endif

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
    .ifdef ENGLISH
    .string "WARDEN SLOWPOKE came in, but\n"
    .string "I couldn't understand him.\p"
    .string "I think he's got a speech problem!$"
    .endif
    .ifdef SPANISH
    .string "SLOWPOKE vino, pero no conseguí\n"
    .string "entenderle nada.\p"
    .string "Creo que no sabe articular bien.$"
    .endif

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
    .ifdef ENGLISH
    .string "WARDEN SLOWPOKE is running a\n"
    .string "promotion campaign right now.\p"
    .string "Try to get to the farthest corner\n"
    .string "of the SAFARI ZONE.\p"
    .string "If you can make it, you'll win a\n"
    .string "very convenient prize.$"
    .endif
    .ifdef SPANISH
    .string "SLOWPOKE ha organizado\n"
    .string "un concurso.\p"
    .string "Intenta llegar al último rincón\n"
    .string "de la ZONA del SAFARI.\p"
    .string "Si lo consigues, ganarás un premio\n"
    .string "realmente útil.$"
    .endif

