Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .ifdef ENGLISH
    .string "The types of POKéMON match up\n"
    .string "differently with each other.\p"
    .string "Every type is stronger than some\n"
    .string "types and weaker than others.$"
    .endif
    .ifdef SPANISH
    .string "¡Los POKéMON de ciertos elementos\n"
    .string "son más o menos fuertes que otros!$"
    .endif

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .ifdef ENGLISH
    .string "A NUGGET is totally useless.\n"
    .string "So I sold it for ¥5000.$"
    .endif
    .ifdef SPANISH
    .string "¡Vendí una inútil PEPITA\n"
    .string "por 5.000¥!$"
    .endif

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .ifdef ENGLISH
    .string "I heard that ghosts haunt\n"
    .string "LAVENDER TOWN.$"
    .endif
    .ifdef SPANISH
    .string "¡Dicen que hay fantasmas en\n"
    .string "PUEBLO LAVANDA!$"
    .endif

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .ifdef ENGLISH
    .string "Oh… {PLAYER}!\n"
    .string "I've been looking for you!\p"
    .string "It's me, one of the ever-present\n"
    .string "AIDES to PROF. OAK.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on twenty species, I'm supposed to\l"
    .string "give you a reward from PROF. OAK.\p"
    .string "He entrusted me with this\n"
    .string "EVERSTONE.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "twenty kinds of POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¡Hola! ¿Te acuerdas de mí?\n"
    .string "¡Soy AYUDANTE del PROF. OAK!\p"
    .string "¡Si ya tienes 20 tipos de POKéMON,\n"
    .string "se supone que debería darte\l"
    .string "PIEDRAETERNA!\p"
    .string "Dime, {PLAYER}. ¿Tienes ya al menos\n"
    .string "20 tipos de POKéMON?$"
    .endif

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .ifdef ENGLISH
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"
    .endif
    .ifdef SPANISH
    .string "¡Bien! ¡Has logrado {STR_VAR_3} tipos\n"
    .string "de POKéMON!\p"
    .string "¡Enhorabuena!\n"
    .string "¡Aquí tienes!$"
    .endif

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .ifdef ENGLISH
    .string "{PLAYER} received the EVERSTONE\n"
    .string "from the AIDE.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo la\n"
    .string "PIEDRAETERNA de manos\l"
    .string "del AYUDANTE!$"
    .endif

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .ifdef ENGLISH
    .string "Making POKéMON evolve certainly\n"
    .string "can add to the POKéDEX.\p"
    .string "However, at times, you may not\n"
    .string "want a certain POKéMON to evolve.\p"
    .string "In that case, give the EVERSTONE\n"
    .string "to that POKéMON.\p"
    .string "It will prevent evolution according\n"
    .string "to the PROFESSOR.$"
    .endif
    .ifdef SPANISH
    .string "Si dejas evolucionar a los\n"
    .string "POKéMON, tu POKéDEX\l"
    .string "se verá beneficiada.\p"
    .string "Aunque habrá algún caso en el\n"
    .string "que no quieras que evolucionen.\p"
    .string "Para evitarlo, dale al POKéMON\n"
    .string "que quieras una PIEDRAETERNA.\p"
    .string "Según dice el PROFESOR,\n"
    .string "el POKéMON que la lleve,\l"
    .string "no evolucionará.$"
    .endif

