SixIsland_Mart_Text_AgathaOldestEverEliteFourMember::
    .ifdef ENGLISH
    .string "Play with POKéMON lots and live\n"
    .string "a long life!\p"
    .string "Take AGATHA, for example.\p"
    .string "She set a record for being the\n"
    .string "oldest-ever ELITE FOUR member.\p"
    .string "She spurs me to do bigger things.$"
    .endif
    .ifdef SPANISH
    .string "¡Juega con los POKéMON y vivirás\n"
    .string "mucho tiempo!\p"
    .string "Mira a AGATHA, por ejemplo.\p"
    .string "Es el miembro de más edad\n"
    .string "del ALTO MANDO.\p"
    .string "¡A mí me anima a superarme\n"
    .string "día a día!$"
    .endif

SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter::
    .ifdef ENGLISH
    .string "I should buy some MAIL and write\n"
    .string "him a letter…$"
    .endif
    .ifdef SPANISH
    .string "Debería escribir alguna CARTA...$"
    .endif

