CeruleanCity_Text_RivalIntro::
    .ifdef ENGLISH
    .string "{RIVAL}: Yo! {PLAYER}!\p"
    .string "You're still struggling along back\n"
    .string "here?\p"
    .string "I'm doing great! I caught a bunch\n"
    .string "of strong and smart POKéMON!\p"
    .string "Here, let me see what you caught,\n"
    .string "{PLAYER}!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Hola, {PLAYER}!\p"
    .string "¿Qué, esto es más difícil de lo\n"
    .string "que te pensabas, eh?\p"
    .string "¡Pues a mí me va de escándalo!\n"
    .string "¡He atrapado un montón de listos\l"
    .string "y fuertes POKéMON!\p"
    .string "¡Bueno, {PLAYER}, vamos a ver qué\n"
    .string "has atrapado!$"
    .endif

CeruleanCity_Text_RivalDefeat::
    .ifdef ENGLISH
    .string "Hey!\n"
    .string "Take it easy!\l"
    .string "You won already!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye!\n"
    .string "¡Calma!\l"
    .string "¡Ya has ganado!$"
    .endif

CeruleanCity_Text_RivalPostBattle::
    .ifdef ENGLISH
    .string "{RIVAL}: Hey, guess what?\p"
    .string "I went to BILL's and got him to\n"
    .string "show me his rare POKéMON.\p"
    .string "That added a lot of pages to my\n"
    .string "POKéDEX!\p"
    .string "After all, BILL's world famous as a\n"
    .string "POKéMANIAC.\p"
    .string "He invented the POKéMON Storage\n"
    .string "System on PC, too.\p"
    .string "Since you're using his system,\n"
    .string "you should go thank him.\p"
    .string "Well, I better get rolling!\n"
    .string "Smell ya later!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¿Sabes qué me pasó?\p"
    .string "¡Estuve con BILL y conseguí que\n"
    .string "me enseñara sus raros POKéMON!\p"
    .string "¡Y eso añadió muchas páginas a mi\n"
    .string "POKéDEX!\p"
    .string "¡Por algo BILL es mundialmente \n"
    .string "conocido como POKéMANÍACO!\p"
    .string "¡Él fue también el que inventó el\n"
    .string "Sistema de Almacenamiento de\l"
    .string "POKéMON para PC!\p"
    .string "¡Ya que estás usando su sistema,\n"
    .string "deberías darle las gracias!\p"
    .string "¡En fin, sigo con lo mío!\n"
    .string "¡Hasta luego!$"
    .endif

CeruleanCity_Text_OhRightLittlePresentAsFavor::
    .ifdef ENGLISH
    .string "Oh, yeah, right.\p"
    .string "I feel sorry for you. No, really.\n"
    .string "You're always plodding behind me.\p"
    .string "So here, I'll give you a little\n"
    .string "present as a favor.$"
    .endif
    .ifdef SPANISH
    .string "En el fondo...\p"
    .string "En el fondo me das pena, te lo\n"
    .string "digo en serio. Siempre vas a\l"
    .string "trancas y barrancas detrás de mí.\p"
    .string "Toma, te voy a dar un regalito\n"
    .string "porque me da no sé qué.$"
    .endif

CeruleanCity_Text_ExplainFameCheckerSmellYa::
    .ifdef ENGLISH
    .string "A chatty gossip like you…\n"
    .string "That thing's perfect.\p"
    .string "I don't need it because I don't\n"
    .string "give a hoot about others.\p"
    .string "All right, this time I really am\n"
    .string "gone. Smell ya!$"
    .endif
    .ifdef SPANISH
    .string "Yo creo que esto es perfecto para\n"
    .string "alguien tan cotilla como tú...\p"
    .string "A mí no me hace falta, porque\n"
    .string "yo voy a mi bola.\p"
    .string "Bueno, me piro, vampiro.$"
    .endif

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory::
    .string "なんたって！\n"
    .string "おれは　てんさい　だからよ！$"

CeruleanCity_Text_GruntIntro::
    .ifdef ENGLISH
    .string "Hey! Stay out!\n"
    .string "It's not your yard!\p"
    .string "…Huh?\n"
    .string "Me?\p"
    .string "I'm an innocent bystander!\n"
    .string "Don't you believe me?{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"
    .endif
    .ifdef SPANISH
    .string "¡Oye! ¡Fuera de aquí!\n"
    .string "¡Esto no te pertenece!\p"
    .string "¿Quién?\n"
    .string "¿Yo?\p"
    .string "¡Soy un ciudadano normal\n"
    .string "y corriente!\l"
    .string "¿No me crees?$"
    .endif

CeruleanCity_Text_GruntDefeat::
    .ifdef ENGLISH
    .string "GRUNT: Stop! I give up!\n"
    .string "I'll leave quietly!$"
    .endif
    .ifdef SPANISH
    .string "SOLDADO: ¡Alto! ¡Me rindo!\n"
    .string "¡Me iré tranquilamente!$"
    .endif

CeruleanCity_Text_OkayIllReturnStolenTM::
    .ifdef ENGLISH
    .string "…Okay.\n"
    .string "I'll return the TM I stole.$"
    .endif
    .ifdef SPANISH
    .string "¡Vale!\n"
    .string "¡Devolveré la MT que robé!$"
    .endif

CeruleanCity_Text_RecoveredTM28FromGrunt::
    .ifdef ENGLISH
    .string "{PLAYER} recovered TM28 from\n"
    .string "the TEAM ROCKET GRUNT.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recuperó\n"
    .string "la MT28!$"
    .endif

CeruleanCity_Text_BetterGetMovingBye::
    .ifdef ENGLISH
    .string "I better get moving!\n"
    .string "Bye!$"
    .endif
    .ifdef SPANISH
    .string "¡Yo me voy de aquí!\n"
    .string "¡Adiós!$"
    .endif

CeruleanCity_Text_MakeRoomForThisCantRun::
    .ifdef ENGLISH
    .string "Make room for this!\n"
    .string "I can't run until I give it to you!$"
    .endif
    .ifdef SPANISH
    .string "¡Hazle sitio a esto! ¡No puedo\n"
    .string "irme hasta que no te lo dé!$"
    .endif

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
    .ifdef ENGLISH
    .string "You're a TRAINER, too?\p"
    .string "Collecting, battling…\n"
    .string "It's a tough life, isn't it?$"
    .endif
    .ifdef SPANISH
    .string "¿También entrenas POKéMON?\p"
    .string "Atrapar, luchar, ¡qué vida tan\n"
    .string "dura la nuestra!$"
    .endif

CeruleanCity_Text_YouCanCutDownSmallTrees::
    .ifdef ENGLISH
    .string "Did you know that you can CUT down\n"
    .string "small trees?\p"
    .string "Even that small tree in front of\n"
    .string "the shop can be CUT down.\p"
    .string "I think there's a way around it,\n"
    .string "though.$"
    .endif
    .ifdef SPANISH
    .string "Los POKéMON pueden CORTAR\n"
    .string "pequeños arbustos.\p"
    .string "Por ejemplo, el que está casi\n"
    .string "enfrente de la tienda, también.\p"
    .string "Con todo, creo que se puede dar\n"
    .string "un rodeo...$"
    .endif

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
    .ifdef ENGLISH
    .string "If that SLOWBRO wasn't there, you\n"
    .string "could CUT down the small tree.\p"
    .string "That way, you could get to the\n"
    .string "other side.\p"
    .string "I think there's a way around it,\n"
    .string "though.$"
    .endif
    .ifdef SPANISH
    .string "Si ese SLOWBRO no estuviera ahí,\n"
    .string "podrías CORTAR el arbusto.\p"
    .string "Así podrías pasar al otro lado.\p"
    .string "Con todo, creo que se puede dar\n"
    .string "un rodeo...$"
    .endif

CeruleanCity_Text_PokemonEncyclopediaAmusing::
    .ifdef ENGLISH
    .string "You're making an encyclopedia on\n"
    .string "POKéMON? That sounds amusing.$"
    .endif
    .ifdef SPANISH
    .string "¿Estás haciendo una enciclopedia\n"
    .string "de los POKéMON? ¡Qué increíble!$"
    .endif

CeruleanCity_Text_PeopleHereWereRobbed::
    .ifdef ENGLISH
    .string "The people here were robbed.\p"
    .string "It's obvious that TEAM ROCKET is\n"
    .string "behind this most heinous crime!\p"
    .string "Even our POLICE FORCE has\n"
    .string "trouble with the ROCKETS!$"
    .endif
    .ifdef SPANISH
    .string "A esta gente le han robado.\p"
    .string "¡Seguro que el TEAM ROCKET guarda\n"
    .string "relación con esta barbaridad!\p"
    .string "¡Hasta nuestra POLICÍA tiene\n"
    .string "problemas con los ROCKET!$"
    .endif

CeruleanCity_Text_SlowbroUseSonicboom::
    .ifdef ENGLISH
    .string "Okay! SLOWBRO!\n"
    .string "Use SONICBOOM!$"
    .endif
    .ifdef SPANISH
    .string "¡BIEN! ¡SLOWBRO!\n"
    .string "¡Usa BOMBA SÓNICA!$"
    .endif

CeruleanCity_Text_SlowbroPayAttention::
    .ifdef ENGLISH
    .string "Come on, SLOWBRO, pay attention!$"
    .endif
    .ifdef SPANISH
    .string "¡Venga, SLOWBRO, presta atención!$"
    .endif

CeruleanCity_Text_SlowbroPunch::
    .ifdef ENGLISH
    .string "SLOWBRO, punch!$"
    .endif
    .ifdef SPANISH
    .string "¡SLOWBRO, dale un puñetazo!$"
    .endif

CeruleanCity_Text_NoYouBlewItAgain::
    .ifdef ENGLISH
    .string "No!\n"
    .string "You blew it again!$"
    .endif
    .ifdef SPANISH
    .string "¡No!\n"
    .string "¡Has vuelto a fallar!$"
    .endif

CeruleanCity_Text_SlowbroWithdraw::
    .ifdef ENGLISH
    .string "SLOWBRO, WITHDRAW!$"
    .endif
    .ifdef SPANISH
    .string "¡SLOWBRO, REFUGIO!$"
    .endif

CeruleanCity_Text_HardToControlMonsObedience::
    .ifdef ENGLISH
    .string "No! That's wrong!\n"
    .string "It's so hard to control POKéMON!\p"
    .string "Your POKéMON's obedience depends\n"
    .string "on your abilities as a TRAINER.$"
    .endif
    .ifdef SPANISH
    .string "¡No! ¡Qué mal!\p"
    .string "¡Es tan difícil controlar a los\n"
    .string "POKéMON!\p"
    .string "¡La obediencia de tus POKéMON\n"
    .string "depende de tus habilidades como\l"
    .string "ENTRENADOR!$"
    .endif

CeruleanCity_Text_SlowbroTookSnooze::
    .ifdef ENGLISH
    .string "SLOWBRO took a snooze…$"
    .endif
    .ifdef SPANISH
    .string "SLOWBRO se durmió...$"
    .endif

CeruleanCity_Text_SlowbroLoafingAround::
    .ifdef ENGLISH
    .string "SLOWBRO is loafing around…$"
    .endif
    .ifdef SPANISH
    .string "SLOWBRO está holgazaneando...$"
    .endif

CeruleanCity_Text_SlowbroTurnedAway::
    .ifdef ENGLISH
    .string "SLOWBRO turned away…$"
    .endif
    .ifdef SPANISH
    .string "SLOWBRO se alejó...$"
    .endif

CeruleanCity_Text_SlowbroIgnoredOrders::
    .ifdef ENGLISH
    .string "SLOWBRO ignored orders…$"
    .endif
    .ifdef SPANISH
    .string "SLOWBRO ignoró las órdenes...$"
    .endif

CeruleanCity_Text_WantBrightRedBicycle::
    .ifdef ENGLISH
    .string "I want a bright red bicycle.\p"
    .string "I'll keep it at home, so it won't\n"
    .string "get dirty.$"
    .endif
    .ifdef SPANISH
    .string "Quiero una bonita BICICLETA roja.\p"
    .string "¡La guardaré en casa para que no\n"
    .string "se ensucie!$"
    .endif

CeruleanCity_Text_ThisIsCeruleanCave::
    .ifdef ENGLISH
    .string "This is CERULEAN CAVE.\p"
    .string "Horribly strong POKéMON live inside\n"
    .string "there.\p"
    .string "It takes a very special TRAINER to\n"
    .string "be allowed inside there.\p"
    .string "You'd have to be strong enough to\n"
    .string "become the POKéMON LEAGUE\l"
    .string "CHAMPION for starters.\p"
    .string "And, you would have to have\n"
    .string "made a great achievement.$"
    .endif
    .ifdef SPANISH
    .string "¡Ésta es la CUEVA CELESTE!\p"
    .string "¡En ella viven unos POKéMON\n"
    .string "superfuertes!\p"
    .string "¡Sólo pueden entrar ENTRENADORES\n"
    .string "que sean realmente especiales!\p"
    .string "Para llegar a ser CAMPEÓN de la\n"
    .string "LIGA POKéMON, hay que ser muy,\l"
    .string "muy fuerte.\p"
    .string "La LIGA supone un gran desafío.$"
    .endif

CeruleanCity_Text_CitySign::
    .ifdef ENGLISH
    .string "CERULEAN CITY\n"
    .string "A Mysterious, Blue Aura Surrounds\l"
    .string "It$"
    .endif
    .ifdef SPANISH
    .string "¡CIUDAD CELESTE!\n"
    .string "¡Una misteriosa aura azulada la\l"
    .string "rodea!$"
    .endif

CeruleanCity_Text_TrainerTipsHeldItems::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "A POKéMON can be made to hold\n"
    .string "an item.\p"
    .string "Some items can even be used by\n"
    .string "the holding POKéMON in battle.$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "A los POKéMON se les puede\n"
    .string "entregar objetos.\p"
    .string "Además, pueden llegar a usarlos\n"
    .string "en combate.$"
    .endif

CeruleanCity_Text_BikeShopSign::
    .ifdef ENGLISH
    .string "Grass and caves handled easily!\n"
    .string "BIKE SHOP$"
    .endif
    .ifdef SPANISH
    .string "TIENDA DE BICIS\n"
    .string "¡Césped y cuevas bajo control!$"
    .endif

CeruleanCity_Text_GymSign::
    .ifdef ENGLISH
    .string "CERULEAN CITY POKéMON GYM\n"
    .string "LEADER: MISTY\l"
    .string "The Tomboyish Mermaid!$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CELESTE: MISTY\l"
    .string "¡La sirena distorsionada!$"
    .endif

