CeruleanCity_Text_RivalIntro::
	.string "{RIVAL}: Yo! {PLAYER}!\p"
	.string "Alors tu t'en sors?\p"
	.string "Moi c'est l'pied! J'ai attrapé plein\n"
	.string "de POKéMON super puissants!\p"
	.string "Fais-moi voir ce que t'as\n"
	.string "attrapé, {PLAYER}!$"

CeruleanCity_Text_RivalDefeat::
	.string "Houlà!\n"
	.string "Calmos!\l"
	.string "T'as gagné, OK!$"

CeruleanCity_Text_RivalPostBattle::
	.string "{RIVAL}: Hé! T'sais quoi?\p"
	.string "J'suis allé chez LEO et y m'a\n"
	.string "montré ses POKéMON rares!\p"
	.string "Ça m'a rajouté plein d'pages à\n"
	.string "mon POKéDEX!\p"
	.string "Tout l'monde sait que LEO est\n"
	.string "un POKéMANIAC!\p"
	.string "Il a même inventé le stockage des\n"
	.string "POKéMON sur PC!\p"
	.string "T'as qu'à aller l'voir!\p"
	.string "Bon, je trace.\n"
	.string "Tchao!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
	.string "Ouais, c'est ça…\p"
	.string "J'ai les boules pour toi. J'te jure,\n"
	.string "t'es toujours derrière moi.\p"
	.string "Bon, j'vais te donner un cadeau,\n"
	.string "mais c'est une faveur.$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
	.string "C'est parfait pour une pipelette\n"
	.string "comme toi.\p"
	.string "J'en ai pas besoin parce que\n"
	.string "j'en ai rien à faire des autres.\p"
	.string "Allez, j'suis plus là,\n"
	.string "tchao!$"

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory::
	.string "なんたって！\n"
	.string "おれは　てんさい　だからよ！$"

CeruleanCity_Text_GruntIntro::
	.string "Holà!\n"
	.string "C'est pas chez toi, ici…\p"
	.string "Quoi? Moi?\p"
	.string "J'suis innocent! Hein? Quoi?\n"
	.string "Tu m'crois pas? Tu m'cherches?$"

CeruleanCity_Text_GruntDefeat::
	.string "SBIRE: Stop!\n"
	.string "J'me rends! J'fais pas le poids!$"

CeruleanCity_Text_OkayIllReturnStolenTM::
	.string "OK! Voilà la CT qu'j'ai volée!$"

CeruleanCity_Text_RecoveredTM28FromGrunt::
	.string "{PLAYER} récupère\n"
	.string "CT28!$"

CeruleanCity_Text_BetterGetMovingBye::
	.string "J'décampe…\n"
	.string "Bye bye!$"

CeruleanCity_Text_MakeRoomForThisCantRun::
	.string "Tu dois faire de la place\n"
	.string "si tu veux que je te la donne!$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
	.string "T'es un DRESSEUR aussi?\p"
	.string "Capturer… Collectionner…\n"
	.string "Combattre… Dur, hein?$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
	.string "Les POKéMON peuvent couper des\n"
	.string "petits buissons avec COUPE.\p"
	.string "Même le petit arbre devant la\n"
	.string "boutique peut être coupé.\p"
	.string "Mais il doit bien y avoir un autre\n"
	.string "moyen de passer.$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
	.string "Si ce FLAGADOSS n'était pas là,\n"
	.string "tu pourrais couper ces arbustes.\p"
	.string "Comme ça, tu pourrais passer\n"
	.string "de l'autre côté.\p"
	.string "Mais il doit bien y avoir un autre\n"
	.string "moyen de passer.$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
	.string "Tu fais une encyclopédie sur les\n"
	.string "POKéMON? Pas mal.$"

CeruleanCity_Text_PeopleHereWereRobbed::
	.string "Ces pauvres gens ont été volés.\p"
	.string "L'odieuse TEAM ROCKET est\n"
	.string "derrière tout ça. C'est sûr!\p"
	.string "Même les forces de police ont du\n"
	.string "mal à lutter!$"

CeruleanCity_Text_SlowbroUseSonicboom::
	.string "Allez! FLAGADOSS!\n"
	.string "Attaque! Attaque!$"

CeruleanCity_Text_SlowbroPayAttention::
	.string "Allez, FLAGADOSS, fais\n"
	.string "un peu attention.$"

CeruleanCity_Text_SlowbroPunch::
	.string "FLAGADOSS, cogne!$"

CeruleanCity_Text_NoYouBlewItAgain::
	.string "Mais non!\n"
	.string "Tu fais n'importe quoi!$"

CeruleanCity_Text_SlowbroWithdraw::
	.string "FLAGADOSS, REPLI!$"

CeruleanCity_Text_HardToControlMonsObedience::
	.string "Non! Pas ça! Pfff…\n"
	.string "C'est dur de contrôler un POKéMON!\p"
	.string "Seuls les bons DRESSEURS se font\n"
	.string "obéir de leurs POKéMON!$"

CeruleanCity_Text_SlowbroTookSnooze::
	.string "FLAGADOSS pionce comme une masse.$"

CeruleanCity_Text_SlowbroLoafingAround::
	.string "FLAGADOSS flâne…$"

CeruleanCity_Text_SlowbroTurnedAway::
	.string "FLAGADOSS se balade…$"

CeruleanCity_Text_SlowbroIgnoredOrders::
	.string "FLAGADOSS ignore les ordres…$"

CeruleanCity_Text_WantBrightRedBicycle::
	.string "Je veux une jolie bicyclette!\p"
	.string "Je la veux toute rouge!$"

CeruleanCity_Text_ThisIsCeruleanCave::
	.string "Des POKéMON trop puissants vivent\n"
	.string "ici, dans la CAVE AZUREE!\p"
	.string "Seuls les DRESSEURS spéciaux\n"
	.string "ont le droit d'y pénétrer.\p"
	.string "Il te faudra tout d'abord devenir\n"
	.string "le MAITRE de la LIGUE\p"
	.string "POKéMON, mais aussi\n"
	.string "avoir réussi un excellent parcours.$"

CeruleanCity_Text_CitySign::
	.string "AZURIA\n"
	.string "Baignée par une aura d'un bleu\l"
	.string "mystérieux$"

CeruleanCity_Text_TrainerTipsHeldItems::
	.string "ASTUCE\p"
	.string "Les POKéMON peuvent porter\n"
	.string "des objets.\p"
	.string "Certains objets portés peuvent\n"
	.string "même être utilisés en combat.$"

CeruleanCity_Text_BikeShopSign::
	.string "Plus vite que le vent, plus vite\n"
	.string "dans les villes!\p"
	.string "… CYCLES A GOGO$"

CeruleanCity_Text_GymSign::
	.string "ARENE POKéMON d'AZURIA\n"
	.string "CHAMPION: ONDINE\l"
	.string "La sirène en shorts.$"

