CeruleanCity_Text_RivalIntro::
    .string "{RIVAL}: ¡Hola, {PLAYER}!\p"
    .string "¿Qué, esto es más difícil de lo\n"
    .string "que te pensabas, eh?\p"
    .string "¡Pues a mí me va de escándalo!\n"
    .string "¡He atrapado un montón de listos\l"
    .string "y fuertes POKéMON!\p"
    .string "¡Bueno, {PLAYER}, vamos a ver qué\n"
    .string "has atrapado!$"

CeruleanCity_Text_RivalDefeat::
    .string "¡Oye!\n"
    .string "¡Calma!\l"
    .string "¡Ya has ganado!$"

CeruleanCity_Text_RivalPostBattle::
    .string "{RIVAL}: ¿Sabes qué me pasó?\p"
    .string "¡Estuve con BILL y conseguí que\n"
    .string "me enseñara sus raros POKéMON!\p"
    .string "¡Y eso añadió muchas páginas a mi\n"
    .string "POKéDEX!\p"
    .string "¡Por algo BILL es mundialmente \n"
    .string "conocido como POKéMANÍACO!\p"
    .string "¡Él fue también el que inventó el\n"
    .string "Sistema de Almacenamiento de\l"
    .string "POKéMON para PC!\p"
    .string "¡Ya que estás usando su sistema,\n"
    .string "deberías darle las gracias!\p"
    .string "¡En fin, sigo con lo mío!\n"
    .string "¡Hasta luego!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
    .string "En el fondo...\p"
    .string "En el fondo me das pena, te lo\n"
    .string "digo en serio. Siempre vas a\l"
    .string "trancas y barrancas detrás de mí.\p"
    .string "Toma, te voy a dar un regalito\n"
    .string "porque me da no sé qué.$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
    .string "Yo creo que esto es perfecto para\n"
    .string "alguien tan cotilla como tú...\p"
    .string "A mí no me hace falta, porque\n"
    .string "yo voy a mi bola.\p"
    .string "Bueno, me piro, vampiro.$"

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory::
    .string "なんたって！\n"
    .string "おれは　てんさい　だからよ！$"

CeruleanCity_Text_GruntIntro::
    .string "¡Oye! ¡Fuera de aquí!\n"
    .string "¡Esto no te pertenece!\p"
    .string "¿Quién?\n"
    .string "¿Yo?\p"
    .string "¡Soy un ciudadano normal\n"
    .string "y corriente!\l"
    .string "¿No me crees?$"

CeruleanCity_Text_GruntDefeat::
    .string "SOLDADO: ¡Alto! ¡Me rindo!\n"
    .string "¡Me iré tranquilamente!$"

CeruleanCity_Text_OkayIllReturnStolenTM::
    .string "¡Vale!\n"
    .string "¡Devolveré la MT que robé!$"

CeruleanCity_Text_RecoveredTM28FromGrunt::
    .string "¡{PLAYER} recuperó\n"
    .string "la MT28!$"

CeruleanCity_Text_BetterGetMovingBye::
    .string "¡Yo me voy de aquí!\n"
    .string "¡Adiós!$"

CeruleanCity_Text_MakeRoomForThisCantRun::
    .string "¡Hazle sitio a esto! ¡No puedo\n"
    .string "irme hasta que no te lo dé!$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
    .string "¿También entrenas POKéMON?\p"
    .string "Atrapar, luchar, ¡qué vida tan\n"
    .string "dura la nuestra!$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
    .string "Los POKéMON pueden CORTAR\n"
    .string "pequeños arbustos.\p"
    .string "Por ejemplo, el que está casi\n"
    .string "enfrente de la tienda, también.\p"
    .string "Con todo, creo que se puede dar\n"
    .string "un rodeo...$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
    .string "Si ese SLOWBRO no estuviera ahí,\n"
    .string "podrías CORTAR el arbusto.\p"
    .string "Así podrías pasar al otro lado.\p"
    .string "Con todo, creo que se puede dar\n"
    .string "un rodeo...$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
    .string "¿Estás haciendo una enciclopedia\n"
    .string "de los POKéMON? ¡Qué increíble!$"

CeruleanCity_Text_PeopleHereWereRobbed::
    .string "A esta gente le han robado.\p"
    .string "¡Seguro que el TEAM ROCKET guarda\n"
    .string "relación con esta barbaridad!\p"
    .string "¡Hasta nuestra POLICÍA tiene\n"
    .string "problemas con los ROCKET!$"

CeruleanCity_Text_SlowbroUseSonicboom::
    .string "¡BIEN! ¡SLOWBRO!\n"
    .string "¡Usa BOMBA SÓNICA!$"

CeruleanCity_Text_SlowbroPayAttention::
    .string "¡Venga, SLOWBRO, presta atención!$"

CeruleanCity_Text_SlowbroPunch::
    .string "¡SLOWBRO, dale un puñetazo!$"

CeruleanCity_Text_NoYouBlewItAgain::
    .string "¡No!\n"
    .string "¡Has vuelto a fallar!$"

CeruleanCity_Text_SlowbroWithdraw::
    .string "¡SLOWBRO, REFUGIO!$"

CeruleanCity_Text_HardToControlMonsObedience::
    .string "¡No! ¡Qué mal!\p"
    .string "¡Es tan difícil controlar a los\n"
    .string "POKéMON!\p"
    .string "¡La obediencia de tus POKéMON\n"
    .string "depende de tus habilidades como\l"
    .string "ENTRENADOR!$"

CeruleanCity_Text_SlowbroTookSnooze::
    .string "SLOWBRO se durmió...$"

CeruleanCity_Text_SlowbroLoafingAround::
    .string "SLOWBRO está holgazaneando...$"

CeruleanCity_Text_SlowbroTurnedAway::
    .string "SLOWBRO se alejó...$"

CeruleanCity_Text_SlowbroIgnoredOrders::
    .string "SLOWBRO ignoró las órdenes...$"

CeruleanCity_Text_WantBrightRedBicycle::
    .string "Quiero una bonita BICICLETA roja.\p"
    .string "¡La guardaré en casa para que no\n"
    .string "se ensucie!$"

CeruleanCity_Text_ThisIsCeruleanCave::
    .string "¡Ésta es la CUEVA CELESTE!\p"
    .string "¡En ella viven unos POKéMON\n"
    .string "superfuertes!\p"
    .string "¡Sólo pueden entrar ENTRENADORES\n"
    .string "que sean realmente especiales!\p"
    .string "Para llegar a ser CAMPEÓN de la\n"
    .string "LIGA POKéMON, hay que ser muy,\l"
    .string "muy fuerte.\p"
    .string "La LIGA supone un gran desafío.$"

CeruleanCity_Text_CitySign::
    .string "¡CIUDAD CELESTE!\n"
    .string "¡Una misteriosa aura azulada la\l"
    .string "rodea!$"

CeruleanCity_Text_TrainerTipsHeldItems::
    .string "PISTAS ENTRENADOR\p"
    .string "A los POKéMON se les puede\n"
    .string "entregar objetos.\p"
    .string "Además, pueden llegar a usarlos\n"
    .string "en combate.$"

CeruleanCity_Text_BikeShopSign::
    .string "TIENDA DE BICIS\n"
    .string "¡Césped y cuevas bajo control!$"

CeruleanCity_Text_GymSign::
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CELESTE: MISTY\l"
    .string "¡La sirena distorsionada!$"
