CeruleanCity_BikeShop_Text_WelcomeToBikeShop::
    .ifdef ENGLISH
    .string "Hi!\n"
    .string "Welcome to our BIKE SHOP.\p"
    .string "Have we got just the BIKE for\n"
    .string "you!$"
    .endif
    .ifdef SPANISH
    .string "¡Ésta es la TIENDA de BICIS!\p"
    .string "¡Tenemos la BICI que buscabas!$"
    .endif

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt::
    .ifdef ENGLISH
    .string "Sorry!\n"
    .string "You can't afford it!$"
    .endif
    .ifdef SPANISH
    .string "¡Lo siento!\n"
    .string "¡No tienes dinero para pagarla!$"
    .endif

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo::
    .ifdef ENGLISH
    .string "Oh, that's…\p"
    .string "A BIKE VOUCHER!\p"
    .string "Okay!\n"
    .string "Here you go!$"
    .endif
    .ifdef SPANISH
    .string "Anda, pero si tienes...\p"
    .string "¡Un BONO para una BICICLETA!\p"
    .string "¡Muy bien!\n"
    .string "¡Toda tuya!$"
    .endif

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle::
    .ifdef ENGLISH
    .string "{PLAYER} exchanged the\n"
    .string "BIKE VOUCHER for a BICYCLE.$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} cambió el BONO por una\n"
    .string "BICICLETA.$"
    .endif

CeruleanCity_BikeShop_Text_ThankYouComeAgain::
    .ifdef ENGLISH
    .string "Thank you!\n"
    .string "Come back again sometime!$"
    .endif
    .ifdef SPANISH
    .string "¡Vuelve cuando quieras!$"
    .endif

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle::
    .ifdef ENGLISH
    .string "How do you like your new BICYCLE?\n"
    .string "Do you like how it rides?\p"
    .string "You can take it out on CYCLING\n"
    .string "ROAD and even into caves!$"
    .endif
    .ifdef SPANISH
    .string "¿Te gusta tu nueva BICICLETA?\p"
    .string "¡Puedes usarla por el CAMINO\n"
    .string "de BICIS y por las cuevas!$"
    .endif

CeruleanCity_BikeShop_Text_MakeRoomForBicycle::
    .ifdef ENGLISH
    .string "You better make room for your\n"
    .string "BICYCLE!$"
    .endif
    .ifdef SPANISH
    .string "¡No tienes sitio para esto!$"
    .endif

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe::
    .ifdef ENGLISH
    .string "A plain city bike is good enough\n"
    .string "for me.\p"
    .string "After all, you can't put a shopping\n"
    .string "basket on a mountain bike.$"
    .endif
    .ifdef SPANISH
    .string "¡Sólo necesito una BICICLETA\n"
    .string "normal!\p"
    .string "¡No puedes poner una cesta en una\n"
    .string "MOTOCICLETA!$"
    .endif

CeruleanCity_BikeShop_Text_BikesCoolButExpensive::
    .ifdef ENGLISH
    .string "These bikes are cool, but they're\n"
    .string "way expensive!$"
    .endif
    .ifdef SPANISH
    .string "¡Estas BICIS son geniales, pero\n"
    .string "muy caras!$"
    .endif

CeruleanCity_BikeShop_Text_WowYourBikeIsCool::
    .ifdef ENGLISH
    .string "Wow.\n"
    .string "Your BIKE is really cool!$"
    .endif
    .ifdef SPANISH
    .string "¡Uauu!\n"
    .string "¡Vaya BICI tan chula!$"
    .endif

@ Unused
CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket::
    .string "ついに　はつばい！\p"
    .string "ドイツ　せい　さいこうきゅう\n"
    .string "おりたたみ　じてんしゃ！$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle::
    .ifdef ENGLISH
    .string "A shiny new BICYCLE!$"
    .endif
    .ifdef SPANISH
    .string "¡Una BICI nueva y reluciente!$"
    .endif

