FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
    .ifdef ENGLISH
    .string "There are many POKéMON locked\n"
    .string "away in the pen…$"
    .endif
    .ifdef SPANISH
    .string "Hay un montón de POKéMON\n"
    .string "encerrados en el cobertizo...$"
    .endif

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
    .ifdef ENGLISH
    .string "The pen door is unlocked.\n"
    .string "The POKéMON appear to have fled.$"
    .endif
    .ifdef SPANISH
    .string "La puerta está abierta.\n"
    .string "Se ve que los POKéMON han huido.$"
    .endif

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
    .ifdef ENGLISH
    .string "Did you come here knowing it's\n"
    .string "TEAM ROCKET's WAREHOUSE?$"
    .endif
    .ifdef SPANISH
    .string "¿Has venido hasta aquí sabiendo\n"
    .string "que era el ALMACÉN ROCKET?$"
    .endif

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
    .ifdef ENGLISH
    .string "What do you think you're doing?!$"
    .endif
    .ifdef SPANISH
    .string "Pero bueno, ¿tú qué te crees?$"
    .endif

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
    .ifdef ENGLISH
    .string "TEAM ROCKET broke up?\n"
    .string "What planet are you from?$"
    .endif
    .ifdef SPANISH
    .string "¿Que si el TEAM ROCKET se ha\n"
    .string "separado?\l"
    .string "Pero ¿tú de qué planeta vienes?$"
    .endif

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
    .ifdef ENGLISH
    .string "Oh, now your POKéMON look strong.\n"
    .string "You're willing to sell them?\p"
    .string "Oh?\n"
    .string "You wanted to battle?$"
    .endif
    .ifdef SPANISH
    .string "Tus POKéMON parecen muy fuertes.\n"
    .string "¿No te gustaría venderlos?\p"
    .string "¡Ah, que quieres luchar!$"
    .endif

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
    .ifdef ENGLISH
    .string "Oh, but…\n"
    .string "Too much!$"
    .endif
    .ifdef SPANISH
    .string "Ufff...\n"
    .string "Ha sido mucha paliza...$"
    .endif

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
    .ifdef ENGLISH
    .string "We can give you a great price.\n"
    .string "Sell us your POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye, te podemos pagar mucho\n"
    .string "por tus POKéMON!$"
    .endif

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
    .ifdef ENGLISH
    .string "I got word about you from the\n"
    .string "others.\p"
    .string "But there's no way a kid like you'd\n"
    .string "know our BOSS GIOVANNI!$"
    .endif
    .ifdef SPANISH
    .string "Me han hablado mucho de ti.\p"
    .string "¡Ante nuestro JEFE GIOVANNI\n"
    .string "no vas a poder hacer nada!$"
    .endif

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
    .ifdef ENGLISH
    .string "Don't…you…dare…laugh…$"
    .endif
    .ifdef SPANISH
    .string "No... te... rías... Grrr...$"
    .endif

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
    .ifdef ENGLISH
    .string "Don't mess in the doings of adults,\n"
    .string "you jumped-up pip-squeak!$"
    .endif
    .ifdef SPANISH
    .string "¡No deberías meter las narices en\n"
    .string "las cosas de los mayores, cotilla!$"
    .endif

FiveIsland_RocketWarehouse_Text_Admin1Intro::
    .ifdef ENGLISH
    .string "I don't know or care if what I'm\n"
    .string "doing is right or wrong…\p"
    .string "I just put my faith in GIOVANNI\n"
    .string "and do as I am told.$"
    .endif
    .ifdef SPANISH
    .string "Ni sé ni me importa si lo que hago\n"
    .string "está bien o no...\p"
    .string "Yo confío en GIOVANNI y cumplo\n"
    .string "con lo que se me dice.$"
    .endif

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
    .ifdef ENGLISH
    .string "I…\n"
    .string "I'm shattered…$"
    .endif
    .ifdef SPANISH
    .string "Es-estoy... sin aliento...$"
    .endif

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
    .ifdef ENGLISH
    .string "You're doing things according to\n"
    .string "your beliefs and morals.\p"
    .string "I understand now…$"
    .endif
    .ifdef SPANISH
    .string "Entiendo que lo que haces responde\n"
    .string "a tus principios.\p"
    .string "Ahora lo entiendo.$"
    .endif

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
    .ifdef ENGLISH
    .string "I've made it so you can come back\n"
    .string "in through there.\p"
    .string "Why don't you go get rested and\n"
    .string "refreshed for what lies ahead?\p"
    .string "The ADMIN after me outranks me\n"
    .string "thoroughly as a TRAINER.\p"
    .string "You'd better steel yourself for one\n"
    .string "harsh challenge.$"
    .endif
    .ifdef SPANISH
    .string "He dejado esto así para que\n"
    .string "puedas volver a entrar.\p"
    .string "¿No quieres descansar antes de\n"
    .string "continuar con lo que te queda?\p"
    .string "El ADMINISTRADOR que me sigue\n"
    .string "es mejor ENTRENADOR que yo.\p"
    .string "Más vale que te prepares para\n"
    .string "un difícil encuentro.$"
    .endif

FiveIsland_RocketWarehouse_Text_Admin2Intro::
    .ifdef ENGLISH
    .string "That's quite enough of you \n"
    .string "playing the hero, kid.\p"
    .string "Spreading lies about how TEAM\n"
    .string "ROCKET has disbanded…\p"
    .string "It's such an obvious attempt to\n"
    .string "cause confusion in our ranks.\p"
    .string "Fortunately, we're not so ignorant\n"
    .string "to fall for the lies of a child!\p"
    .string "And now, I'll show you how scary\n"
    .string "an angry adult can be!$"
    .endif
    .ifdef SPANISH
    .string "Ya está bien de ir de guay.\p"
    .string "Lo de contar que el TEAM ROCKET\n"
    .string "se ha separado es...\p"
    .string "un intento descarado de causar\n"
    .string "el desconcierto entre nosotros.\p"
    .string "Pero afortunadamente no somos\n"
    .string "lelos y no nos tragamos semejantes\l"
    .string "chorradas.\p"
    .string "¡Te vas a enterar de lo que llegan\n"
    .string "a molestar estas cosas!$"
    .endif

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
    .ifdef ENGLISH
    .string "Urgh…\n"
    .string "You were too strong…\p"
    .string "…\n"
    .string "Th-that's GIOVANNI's BADGE!\p"
    .string "So it's true?\n"
    .string "TEAM ROCKET really has disbanded?$"
    .endif
    .ifdef SPANISH
    .string "Grrrrrr...\n"
    .string "¡Eres demasiado fuerte!...\p"
    .string "¡Eh!...\n"
    .string "¡Ésa es la MEDALLA de GIOVANNI!\p"
    .string "Entonces, ¿es verdad que el TEAM\n"
    .string "ROCKET se ha disuelto?$"
    .endif

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
    .ifdef ENGLISH
    .string "We will abandon this WAREHOUSE…\p"
    .string "But don't think this is over.\n"
    .string "I won't let this be the end.\p"
    .string "I will find GIOVANNI.\n"
    .string "And I will resurrect TEAM ROCKET!\l"
    .string "I will…\p"
    .string "Until then, farewell!$"
    .endif
    .ifdef SPANISH
    .string "¡Nos iremos del ALMACÉN!...\p"
    .string "Pero no te pienses que la cosa\n"
    .string "se queda ahí. ¡Ya me ocuparé yo!\p"
    .string "Iré a buscar a GIOVANNI y reuniré\n"
    .string "al TEAM ROCKET. ¡Ya lo verás!\p"
    .string "¡Hasta entonces, ya nos veremos!$"
    .endif

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
    .ifdef ENGLISH
    .string "A report with graphs and text is on\n"
    .string "the PC monitor.\p"
    .string "“The Influence of Magnetic Waves\n"
    .string "on POKéMON Evolution”…\p"
    .string "… … … … … …\p"
    .string "It's too difficult to understand…$"
    .endif
    .ifdef SPANISH
    .string "Hay un informe con gráficos\n"
    .string "y anotaciones en el monitor del PC.\p"
    .string "“La influencia de las ondas\n"
    .string "magnéticas en la evolución de los\l"
    .string "POKéMON”...\p"
    .string "... ... ... ... ... ...\p"
    .string "Cualquiera entiende esto...$"
    .endif

FiveIsland_RocketWarehouse_Text_GideonIntro::
    .ifdef ENGLISH
    .string "I almost managed to sell the\n"
    .string "SAPPHIRE for huge money…\p"
    .string "Then, you just had to come along\n"
    .string "and blow the whole deal apart!\p"
    .string "Fufu… Fufufufu…\n"
    .string "There's no forgiveness for you!$"
    .endif
    .ifdef SPANISH
    .string "He estado a punto de vender\n"
    .string "el ZAFIRO por un buen pellizco...\p"
    .string "¡Y vas tú y apareces justo cuando\n"
    .string "iba a cerrar el trato!\p"
    .string "¡Grrrrrrrrrrrrrrrrr...!\n"
    .string "¡No tienes perdón!$"
    .endif

FiveIsland_RocketWarehouse_Text_GideonDefeat::
    .ifdef ENGLISH
    .string "Gah! Darn!\n"
    .string "Darn! Darn!$"
    .endif
    .ifdef SPANISH
    .string "¡Ufff! ¿Será posible?\n"
    .string "¡Grrrrrrr!$"
    .endif

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
    .ifdef ENGLISH
    .string "If I can't sell it, it's worthless!\n"
    .string "Go ahead, take it!$"
    .endif
    .ifdef SPANISH
    .string "Si no voy a poder venderlo, no lo\n"
    .string "quiero para nada. ¡Quédatelo tú!$"
    .endif

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
    .ifdef ENGLISH
    .string "What do you want now?\n"
    .string "Go on, get lost, leave me be.$"
    .endif
    .ifdef SPANISH
    .string "¿Y ahora qué?\n"
    .string "¿Quieres dejarme ya en paz?$"
    .endif

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
    .ifdef ENGLISH
    .string "What, you again?\p"
    .string "You… You're not GIOVANNI's kid,\n"
    .string "are you?\p"
    .string "No, that can't be right!\n"
    .string "GIOVANNI's kid has red hair.\p"
    .string "You don't have any reasons for\n"
    .string "bugging me. Leave me alone!$"
    .endif
    .ifdef SPANISH
    .string "Pero ¿otra vez tú?\p"
    .string "Tú... tú no eres el retoño\n"
    .string "de GIOVANNI, ¿verdad?\p"
    .string "No, no puede ser, el retoño\n"
    .string "de GIOVANNI es pelirrojo.\p"
    .string "Bueno, ¿y por qué me incordias?\n"
    .string "Déjame, anda.$"
    .endif

