CeruleanCity_House3_Text_PleaseTradeWithMyHusband::
    .ifdef ENGLISH
    .string "My husband likes trading POKéMON.\p"
    .string "You're collecting POKéMON for your\n"
    .string "POKéDEX, aren't you?\p"
    .string "Would you please trade with him?$"
    .endif
    .ifdef SPANISH
    .string "A mi marido le gusta intercambiar\n"
    .string "POKéMON.\p"
    .string "Si eres coleccionista, ¿podrías\n"
    .string "intercambiar con él?\p"
    .string "¡Te vendría de perlas para tu\n"
    .string "POKéDEX!$"
    .endif

