CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
    .ifdef ENGLISH
    .string "Hello!\n"
    .string "Welcome to CELADON DEPT. STORE.\p"
    .string "The board on the right describes\n"
    .string "the store layout.$"
    .endif
    .ifdef SPANISH
    .string "¡Hola! Éste es el CENTRO\n"
    .string "COMERCIAL de AZULONA.\p"
    .string "El tablero de la derecha es un\n"
    .string "plano de las tiendas.$"
    .endif

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
    .ifdef ENGLISH
    .string "1F: SERVICE COUNTER\p"
    .string "2F: TRAINER'S MARKET\p"
    .string "3F: TV GAME SHOP\p"
    .string "4F: WISE MAN GIFTS\p"
    .string "5F: DRUGSTORE\p"
    .string "ROOFTOP SQUARE: VENDING MACHINES$"
    .endif
    .ifdef SPANISH
    .string "PB: PUESTO DE INFORMACIÓN\p"
    .string "P1: TIENDA DE ENTRENADORES\p"
    .string "P2: VIDEOJUEGOS\p"
    .string "P3: REGALOS\p"
    .string "P4: FARMACIA\p"
    .string "ÚLTIMO PISO: DISTRIBUIDORES$"
    .endif

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
    .ifdef ENGLISH
    .string "1F: SERVICE COUNTER$"
    .endif
    .ifdef SPANISH
    .string "PB: PUESTO DE INFORMACIÓN$"
    .endif

