@ Unused
FiveIsland_Meadow_Text_DoorNeedsTwoPasswords::
    .string "とびらを　あけるには\n"
    .string "パスワードが　2つ　いるようだ$"

FiveIsland_Meadow_Text_EnteredPasswordAnotherNeeded::
    .ifdef ENGLISH
    .string "{PLAYER} entered a password.\p"
    .string "“GOLDEEN need log.”\p"
    .string "… …  … …  … …\p"
    .string "Another password is needed to\n"
    .string "open the door…$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} introdujo una contraseña.\p"
    .string "“GARON ama a NORA”.\p"
    .string "... ... ... ... ... ...\p"
    .string "Para abrir la puerta hace falta\n"
    .string "otra contraseña más...$"
    .endif

FiveIsland_Meadow_Text_EnteredPasswordDoorOpened::
    .ifdef ENGLISH
    .string "{PLAYER} entered two passwords.\p"
    .string "“GOLDEEN need log.”\n"
    .string "“Yes, nah, CHANSEY.”\p"
    .string "… …  … …  … …\p"
    .string "The WAREHOUSE's door opened!$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER} introdujo dos contraseñas.\p"
    .string "“ARON ama a NORA”.\n"
    .string "“HO-OH es ese HO-OH”.\p"
    .string "... ... ... ... ... ...\p"
    .string "¡La puerta del ALMACÉN\n"
    .string "se ha abierto!$"
    .endif

FiveIsland_Meadow_Text_WarehouseDoorAlreadyOpen::
    .ifdef ENGLISH
    .string "The WAREHOUSE's door is already\n"
    .string "open.$"
    .endif
    .ifdef SPANISH
    .string "La puerta del ALMACÉN\n"
    .string "ya está abierta.$"
    .endif

FiveIsland_Meadow_Text_Rocket1Intro::
    .ifdef ENGLISH
    .string "This area's strictly off-limits!\n"
    .string "Out, out!$"
    .endif
    .ifdef SPANISH
    .string "¡Ésta es una zona privada!\n"
    .string "¡Fuera de aquí!$"
    .endif

FiveIsland_Meadow_Text_Rocket1Defeat::
    .ifdef ENGLISH
    .string "Is this for real?$"
    .endif
    .ifdef SPANISH
    .string "¿Por qué me pasa esto a mí?$"
    .endif

FiveIsland_Meadow_Text_Rocket1PostBattle::
    .ifdef ENGLISH
    .string "You don't have any business here!\n"
    .string "Go home!$"
    .endif
    .ifdef SPANISH
    .string "Aquí no tienes nada que hacer.\n"
    .string "¡Vete a casa!$"
    .endif

FiveIsland_Meadow_Text_Rocket2Intro::
    .ifdef ENGLISH
    .string "There's nothing past here except\n"
    .string "our WAREHOUSE.\p"
    .string "So what brings you here?$"
    .endif
    .ifdef SPANISH
    .string "Esto no es más que nuestro\n"
    .string "ALMACÉN.\p"
    .string "No entiendo qué te trae por aquí.$"
    .endif

FiveIsland_Meadow_Text_Rocket2Defeat::
    .ifdef ENGLISH
    .string "That wasn't supposed to happen…$"
    .endif
    .ifdef SPANISH
    .string "No entiendo cómo he podido\n"
    .string "perder...$"
    .endif

FiveIsland_Meadow_Text_Rocket2PostBattle::
    .ifdef ENGLISH
    .string "You're wanting to know what's inside\n"
    .string "this WAREHOUSE?\p"
    .string "It's better you didn't know.\n"
    .string "For your own sake, I mean.$"
    .endif
    .ifdef SPANISH
    .string "¿Tienes curiosidad por ver qué hay\n"
    .string "en el ALMACÉN?\p"
    .string "Yo creo que es mejor que no lo\n"
    .string "sepas. Por tu propio bien...$"
    .endif

FiveIsland_Meadow_Text_Rocket3Intro::
    .ifdef ENGLISH
    .string "You'd be wasting time even if you\n"
    .string "were to get by me.$"
    .endif
    .ifdef SPANISH
    .string "Aunque me ganaras, estarías\n"
    .string "perdiendo el tiempo.$"
    .endif

FiveIsland_Meadow_Text_Rocket3Defeat::
    .ifdef ENGLISH
    .string "Oh, that makes me furious!$"
    .endif
    .ifdef SPANISH
    .string "¡Agggrrr! ¡Qué fastidio!$"
    .endif

FiveIsland_Meadow_Text_Rocket3PostBattle::
    .ifdef ENGLISH
    .string "You won't be able to get in without\n"
    .string "the passwords anyway.$"
    .endif
    .ifdef SPANISH
    .string "Bueno, de todas formas no vas\n"
    .string "a poder entrar sin las contraseñas.$"
    .endif

