CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
    .ifdef ENGLISH
    .string "Captured POKéMON are registered\n"
    .string "with an ID No. and the OT.\p"
    .string "OT stands for “Original TRAINER” -\n"
    .string "the TRAINER that caught it first.$"
    .endif
    .ifdef SPANISH
    .string "¡Los POKéMON capturados tienen un\n"
    .string "N.º IDENTIDAD y un EO, el nombre\p"
    .string "del ENTRENADOR ORIGINAL\n"
    .string "que lo atrapó!$"
    .endif

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
    .ifdef ENGLISH
    .string "All right!\p"
    .string "My buddy's going to trade me his\n"
    .string "KANGASKHAN for my HAUNTER!$"
    .endif
    .ifdef SPANISH
    .string "¡Muy bien!\p"
    .string "¡Mi compañero va a cambiarme su\n"
    .string "KANGASKHAN por mi GRAVELER!$"
    .endif

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
    .ifdef ENGLISH
    .string "Come on, HAUNTER!\p"
    .string "I love HAUNTER!\n"
    .string "I collect them!\p"
    .string "Huh?\p"
    .string "HAUNTER turned into a different\n"
    .string "POKéMON while being traded!$"
    .endif
    .ifdef SPANISH
    .string "¡Un GRAVELER!\p"
    .string "¡Me gustan los GRAVELER!\n"
    .string "¡Los colecciono!\p"
    .string "¿Qué?\p"
    .string "¡GRAVELER se transformó en otro\n"
    .string "POKéMON!$"
    .endif

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
    .ifdef ENGLISH
    .string "You can identify POKéMON you get\n"
    .string "in trades by their ID Numbers.$"
    .endif
    .ifdef SPANISH
    .string "¡Puedes identificar a los POKéMON\n"
    .string "que hayas cambiado por su N.º ID!$"
    .endif

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
    .ifdef ENGLISH
    .string "It's a Super NES.$"
    .endif
    .ifdef SPANISH
    .string "¡Es una SUPER NINTENDO!$"
    .endif

CeladonCity_DepartmentStore_3F_Text_AnRPG::
    .ifdef ENGLISH
    .string "An RPG!\n"
    .string "There's no time for that!$"
    .endif
    .ifdef SPANISH
    .string "Un juego de rol.\n"
    .string "¡Genial! ¡Pero no tengo tiempo!$"
    .endif

CeladonCity_DepartmentStore_3F_Text_SportsGame::
    .ifdef ENGLISH
    .string "A sports game!\n"
    .string "Dad'll like that!$"
    .endif
    .ifdef SPANISH
    .string "¡Un juego de deportes!\n"
    .string "¡A mi padre le gustan!$"
    .endif

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
    .ifdef ENGLISH
    .string "A puzzle game!\n"
    .string "Looks addictive!$"
    .endif
    .ifdef SPANISH
    .string "¡Un juego de puzzles!\n"
    .string "¡Parece muy adictivo!$"
    .endif

CeladonCity_DepartmentStore_3F_Text_FightingGame::
    .ifdef ENGLISH
    .string "A fighting game!\n"
    .string "Looks tough!$"
    .endif
    .ifdef SPANISH
    .string "¡Un juego de lucha!\n"
    .string "¡Parece muy difícil!$"
    .endif

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
    .ifdef ENGLISH
    .string "3F: TV GAME SHOP$"
    .endif
    .ifdef SPANISH
    .string "P2: VIDEOJUEGOS$"
    .endif

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
    .ifdef ENGLISH
    .string "Red and Green!\n"
    .string "Both are POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Rojo y Verde!\n"
    .string "¡Dos juegos de POKéMON!$"
    .endif

Text_CounterTeach::
    .ifdef ENGLISH
    .string "Oh, hi!\n"
    .string "I finally finished POKéMON.\p"
    .string "Not done yet? How about I teach\n"
    .string "you a good move?\p"
    .string "The move I have in mind is\n"
    .string "COUNTER.\p"
    .string "Not like the one I'm leaning on,\n"
    .string "mind you!$"
    .endif
    .ifdef SPANISH
    .string "¡Hola! ¡Ya me he acabado\n"
    .string "POKéMON!\p"
    .string "¿Tú no? ¿Quieres que te enseñe\n"
    .string "un movimiento?\p"
    .string "He pensado en CONTADOR.\p"
    .string "¡No te voy a enseñar el que acabo\n"
    .string "de aprender, claro!$"
    .endif

Text_CounterDeclined::
    .ifdef ENGLISH
    .string "You're not interested? Come see\n"
    .string "me if you change your mind.$"
    .endif
    .ifdef SPANISH
    .string "¿No te interesa? Bueno, vuelve\n"
    .string "si cambias de opinión.$"
    .endif

Text_CounterWhichMon::
    .ifdef ENGLISH
    .string "Which POKéMON should I teach\n"
    .string "COUNTER to?$"
    .endif
    .ifdef SPANISH
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe CONTADOR?$"
    .endif

Text_CounterTaught::
    .ifdef ENGLISH
    .string "Are you using that COUNTER move\n"
    .string "I taught your POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¿Estás usando el movimiento\n"
    .string "CONTADOR que le enseñé\l"
    .string "a tu POKéMON?$"
    .endif
