CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
	.string "Jedes gefangene POKéMON erhält\n"
	.string "eine ID-Nr. und wird mit dem Namen\l"
	.string "des ORIGINALTRAINERs, OT,\l"
	.string "registriert. \p"
	.string "Der OT ist der TRAINER, der das\n"
	.string "POKéMON gefangen hat!$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
	.string "Cool!\p"
	.string "Mein Kumpel tauscht sein KANGAMA\n"
	.string "gegen mein GEOROK!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
	.string "Komm, GEOROK!\p"
	.string "Ich bin GEOROK-Sammler!\p"
	.string "Nanu?\p"
	.string "GEOROK hat sich zu einem anderen\n"
	.string "POKéMON entwickelt!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
	.string "Anhand ihrer ID-Nr. kannst du\n"
	.string "POKéMON, die du bei einem Tausch\l"
	.string "erhalten hast, identifizieren!$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
	.string "Das ist ein SUPER NINTENDO!$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
	.string "Ein Rollenspiel!\n"
	.string "Ich habe keine Zeit! Schade!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
	.string "Ein Rennspiel!\n"
	.string "Das würde meinem Vater gefallen!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
	.string "Ein Puzzle-Spiel!\n"
	.string "Es ist bestimmt fesselnd!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
	.string "Ein Kampfsport-Spiel!\n"
	.string "Aufregend!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
	.string "2S: VIDEOSPIELE-SHOP$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
	.string "Die Rote und die Grüne POKéMON-\n"
	.string "Edition! Cool!$"

Text_CounterTeach::
	.string "Hallo! Ich habe kürzlich POKéMON\n"
	.string "durchgespielt!\p"
	.string "Du bist noch nicht soweit?\n"
	.string "Vielleicht hilft dir das hier!\p"
	.string "Ich denke an die Attacke KONTER.\p"
	.string "Nicht, dass ich mich darauf\n"
	.string "verlassen würde!$"

Text_CounterDeclined::
	.string "Du hast kein Interesse? Komme\n"
	.string "wieder, wenn du deine Meinung\l"
	.string "geändert hast!$"

Text_CounterWhichMon::
	.string "Welches POKéMON soll sie lernen?$"

Text_CounterTaught::
	.string "Setzt du die KONTER-Attacke ein,\n"
	.string "die ich einem deiner POKéMON\l"
	.string "beigebracht habe?$"

