Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30::
    .ifdef ENGLISH
    .string "Hi! Remember me?\n"
    .string "I'm one of PROF. OAK's AIDES.\p"
    .string "If your POKéDEX has complete data\n"
    .string "on {STR_VAR_1} species, I'm supposed to\l"
    .string "give you a reward.\p"
    .string "PROF. OAK entrusted me with the\n"
    .string "{STR_VAR_2} for you.\p"
    .string "So, {PLAYER}, let me ask you.\p"
    .string "Have you gathered data on at least\n"
    .string "{STR_VAR_1} kinds of POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¡Hola! ¿Te acuerdas de mí?\n"
    .string "¡Soy AYUDANTE del PROF. OAK!\p"
    .string "¡Si ya tienes {STR_VAR_1} tipos de POKéMON,\n"
    .string "se supone que debería darte\l"
    .string "{STR_VAR_2}!\p"
    .string "Dime, {PLAYER}. ¿Tienes ya al menos\n"
    .string "{STR_VAR_1} tipos de POKéMON?$"
    .endif

Route11_EastEntrance_2F_Text_GreatHereYouGo::
    .ifdef ENGLISH
    .string "Great! You have caught or owned\n"
    .string "{STR_VAR_3} kinds of POKéMON!\p"
    .string "Congratulations!\n"
    .string "Here you go!$"
    .endif
    .ifdef SPANISH
    .string "¡Bien! ¡Has logrado {STR_VAR_3} tipos\n"
    .string "de POKéMON!\p"
    .string "¡Enhorabuena!\n"
    .string "¡Aquí tienes!$"
    .endif

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide::
    .ifdef ENGLISH
    .string "{PLAYER} received the {STR_VAR_2}\n"
    .string "from the AIDE.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo {STR_VAR_2}\n"
    .string "de manos del AYUDANTE!$"
    .endif

Route11_EastEntrance_2F_Text_ExplainItemfinder::
    .ifdef ENGLISH
    .string "There are items on the ground that\n"
    .string "may be hidden from view.\p"
    .string "Use the ITEMFINDER to detect any\n"
    .string "hidden items close to you.\p"
    .string "The machine is a bit limited.\n"
    .string "It can't pinpoint item locations.\p"
    .string "What it does is show the direction\n"
    .string "where the item is.\p"
    .string "Use it to get your bearings, then\n"
    .string "search the suspect area by hand.$"
    .endif
    .ifdef SPANISH
    .string "En el suelo hay objetos que no se\n"
    .string "pueden ver.\p"
    .string "El BUSCAOBJETOS detectará\n"
    .string "los objetos que tengas cerca.\p"
    .string "¡Pero no puede señalar dónde están\n"
    .string "exactamente!\p"
    .string "¡Tú tendrás que encontrarlos!$"
    .endif

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
    .ifdef ENGLISH
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "A big POKéMON is asleep on a road!$"
    .endif
    .ifdef SPANISH
    .string "Has usado los prismáticos...\p"
    .string "¡Un gran POKéMON está durmiendo\n"
    .string "en el camino!$"
    .endif

Route11_EastEntrance_2F_Text_WhatABreathtakingView::
    .ifdef ENGLISH
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "What a breathtaking view!$"
    .endif
    .ifdef SPANISH
    .string "Has usado los prismáticos...\p"
    .string "¡Qué vista tan bonita!$"
    .endif

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
    .ifdef ENGLISH
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "To get to LAVENDER TOWN from\n"
    .string "CERULEAN CITY…\p"
    .string "ROCK TUNNEL appears to be a good\n"
    .string "route to take.$"
    .endif
    .ifdef SPANISH
    .string "Has usado los prismáticos...\p"
    .string "¡Puedes ir de CIUDAD CELESTE\n"
    .string "a PUEBLO LAVANDA por el TÚNEL\l"
    .string "ROCA!$"
    .endif

