Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30::
	.string "Hallo! Erinnerst du dich?\n"
	.string "Ich bin PROF. EICHs ASSISTENT!\p"
	.string "Wenn du mindestens {STR_VAR_1} verschiedene\n"
	.string "POKéMON gefangen hast, habe ich\l"
	.string "ein Geschenk für dich:\l"
	.string "{STR_VAR_2}\p"
	.string "Also, {PLAYER}, hast du {STR_VAR_1}\n"
	.string "unterschiedliche POKéMON gefangen?$"

Route11_EastEntrance_2F_Text_GreatHereYouGo::
	.string "Super! Du hast {STR_VAR_3} verschiedene\n"
	.string "POKéMON gefangen!\p"
	.string "Einfach klasse! Hier, das hast du\n"
	.string "dir redlich verdient!$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide::
	.string "{PLAYER} erhält\n"
	.string "{STR_VAR_2}!$"

Route11_EastEntrance_2F_Text_ExplainItemfinder::
	.string "Auf dem Boden liegen oft Items,\n"
	.string "die man nicht sehen kann.\p"
	.string "Der DETEKTOR spürt Items in deiner\n"
	.string "Nähe auf!\p"
	.string "Allerdings ortet er nicht die\n"
	.string "exakte Position!\p"
	.string "Er zeigt nur in die Richtung, wo\n"
	.string "das Item liegt.\p"
	.string "Benutze ihn, um dich zu orientieren\n"
	.string "und suche dann manuell!$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
	.string "Du schaust durch das Fernrohr.\p"
	.string "Mitten auf dem Weg schläft ein\n"
	.string "großes POKéMON!$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView::
	.string "Du schaust durch das Fernrohr.\p"
	.string "Du hast eine wunderschöne Aussicht!$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
	.string "Du schaust durch das Fernrohr.\p"
	.string "Der einzige Weg von AZURIA CITY\n"
	.string "nach LAVANDIA führt durch den\l"
	.string "FELSTUNNEL.$"

