PewterCity_House1_Text_Nidoran::
    .string "NIDORAN♂: ¡Nidor!$"

PewterCity_House1_Text_NidoranSit::
    .string "¡Siéntate, NIDORAN!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
    .string "Nuestro POKéMON es forastero,\n"
    .string "y es difícil de manejar.\p"
    .string "Un forastero es un POKéMON\n"
    .string "intercambiado con otro jugador.\p"
    .string "¡Crece deprisa, pero a veces\n"
    .string "no hace caso a los ENTRENADORES\l"
    .string "novatos en combates!\p"
    .string "¡Ojalá tuviéramos algunas\n"
    .string "MEDALLAS!$"
