PewterCity_House1_Text_Nidoran::
	.string "NIDORAN♂: Nidoni!$"

PewterCity_House1_Text_NidoranSit::
	.string "NIDORAN, assis!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
	.string "Notre POKéMON est un échangé, il\n"
	.string "est difficile à maîtriser.\p"
	.string "Un échangé est un POKéMON échangé\n"
	.string "avec un autre joueur.\p"
	.string "Il grandit vite, mais il n'en fait\n"
	.string "qu'à sa tête pendant les combats!\p"
	.string "Si seulement nous avions des\n"
	.string "BADGES…$"

