PewterCity_House1_Text_Nidoran::
    .ifdef ENGLISH
    .string "NIDORAN♂: Bowbow!$"
    .endif
    .ifdef SPANISH
    .string "NIDORAN♂: ¡Nidor!$"
    .endif

PewterCity_House1_Text_NidoranSit::
    .ifdef ENGLISH
    .string "NIDORAN, sit!$"
    .endif
    .ifdef SPANISH
    .string "¡Siéntate, NIDORAN!$"
    .endif

PewterCity_House1_Text_TradeMonsAreFinicky::
    .ifdef ENGLISH
    .string "Our POKéMON's an outsider, so it's\n"
    .string "finicky and hard to handle.\p"
    .string "An outsider is a POKéMON that you\n"
    .string "get in a trade.\p"
    .string "It grows fast, but it may ignore an\n"
    .string "unskilled TRAINER in battle.\p"
    .string "If only we had some BADGES…$"
    .endif
    .ifdef SPANISH
    .string "Nuestro POKéMON es forastero,\n"
    .string "y es difícil de manejar.\p"
    .string "Un forastero es un POKéMON\n"
    .string "intercambiado con otro jugador.\p"
    .string "¡Crece deprisa, pero a veces\n"
    .string "no hace caso a los ENTRENADORES\l"
    .string "novatos en combates!\p"
    .string "¡Ojalá tuviéramos algunas\n"
    .string "MEDALLAS!$"
    .endif

