Route13_Text_SebastianIntro::
	.string "Meine Vogel-POKéMON wollen\n"
	.string "kämpfen!$"

Route13_Text_SebastianDefeat::
	.string "Mein Vogel-Team hat verloren?$"

Route13_Text_SebastianPostBattle::
	.string "Meine POKéMON sind fröhlich, obwohl\n"
	.string "sie verloren haben!$"

Route13_Text_SusieIntro::
	.string "Man sagt, für ein Kind würde ich\n"
	.string "gut kämpfen!$"

Route13_Text_SusieDefeat::
	.string "Oh!\n"
	.string "Ich hab verloren!$"

Route13_Text_SusiePostBattle::
	.string "Ich werde fleißig üben, damit ich\n"
	.string "ein guter TRAINER werde!$"

Route13_Text_ValerieIntro::
	.string "Wow!\n"
	.string "Deine ORDEN sind supercool!$"

Route13_Text_ValerieDefeat::
	.string "Das hat nicht ganz gereicht!$"

Route13_Text_ValeriePostBattle::
	.string "Du hast diese ORDEN im Kampf\n"
	.string "gegen ARENALEITER gewonnen, oder?$"

Route13_Text_GwenIntro::
	.string "Meine niedlichen POKéMON möchten\n"
	.string "dich gern kennen lernen.$"

Route13_Text_GwenDefeat::
	.string "Wow!\n"
	.string "Du hast mit Leichtigkeit gewonnen!$"

Route13_Text_GwenPostBattle::
	.string "POKéMON müssen viel kämpfen, damit\n"
	.string "sie stark werden!$"

Route13_Text_AlmaIntro::
	.string "Ich habe in einer Höhle CARBON\n"
	.string "gefunden!$"

Route13_Text_AlmaDefeat::
	.string "Ich habe es vermasselt!$"

Route13_Text_AlmaPostBattle::
	.string "Mit dem CARBON habe ich die\n"
	.string "INITIATIVE meiner POKéMON erhöht.$"

Route13_Text_PerryIntro::
	.string "Bin unterwegs und habe\n"
	.string "Rückenwind...$"

Route13_Text_PerryDefeat::
	.string "Der Wind dreht sich!$"

Route13_Text_PerryPostBattle::
	.string "Ich bin besiegt!\n"
	.string "Ich werde nach Hause fliegen!$"

Route13_Text_LolaIntro::
	.string "Natürlich werde ich mit dir\n"
	.string "spielen!$"

Route13_Text_LolaDefeat::
	.string "Oh!\n"
	.string "Du durchtriebenes Balg!$"

Route13_Text_LolaPostBattle::
	.string "Wenn es männliche und weibliche\n"
	.string "POKéMON gäbe, welche wären wohl\l"
	.string "stärker?$"

Route13_Text_SheilaIntro::
	.string "Lass deine POKéMON gegen meine\n"
	.string "antreten!$"

Route13_Text_SheilaDefeat::
	.string "Das war schon alles?$"

Route13_Text_SheilaPostBattle::
	.string "Ich habe keine Ahnung von POKéMON.\p"
	.string "Aber manche finde ich wirklich\n"
	.string "cool!$"

Route13_Text_JaredIntro::
	.string "Was schaust du so dumm aus der\n"
	.string "Wäsche?$"

Route13_Text_JaredDefeat::
	.string "Zack!\n"
	.string "Getriebeschaden!$"

Route13_Text_JaredPostBattle::
	.string "Hau bloß ab!$"

Route13_Text_RobertIntro::
	.string "Meine Vogel-POKéMON begleiten\n"
	.string "mich immer!$"

Route13_Text_RobertDefeat::
	.string "Die Luft ist raus!$"

Route13_Text_RobertPostBattle::
	.string "Ach, wenn ich doch wie TAUBSI und\n"
	.string "TAUBOGA fliegen könnte...$"

Route13_Text_LookToLeftOfThatPost::
	.string "TIPPS FÜR TRAINER\p"
	.string "Schaue links neben den Pfosten!$"

Route13_Text_SelectToSwitchItems::
	.string "TIPPS FÜR TRAINER\p"
	.string "Drücke SELECT, um die Positionen\n"
	.string "von Items im Menü zu tauschen.$"

Route13_Text_RouteSign::
	.string "ROUTE 13\n"
	.string "NORDEN: STILLE BRÜCKE$"

