Route13_Text_SebastianIntro::
    .string "¡Mis pájaros POKéMON quieren\n"
    .string "pelear!$"

Route13_Text_SebastianDefeat::
    .string "¿Perdió mi combinación de pájaros?$"

Route13_Text_SebastianPostBattle::
    .string "Mis POKéMON parecen felices\n"
    .string "aunque hayan perdido.$"

Route13_Text_SusieIntro::
    .string "¡Dicen que soy muy buena\n"
    .string "para ser tan pequeña!$"

Route13_Text_SusieDefeat::
    .string "¡Oh!\n"
    .string "¡He perdido!$"

Route13_Text_SusiePostBattle::
    .string "Quiero ser una gran ENTRENADORA.\n"
    .string "Voy a entrenarme mucho.$"

Route13_Text_ValerieIntro::
    .string "¡Qué chulas son tus MEDALLAS!$"

Route13_Text_ValerieDefeat::
    .string "¡No he estado a la altura!$"

Route13_Text_ValeriePostBattle::
    .string "¡Sé que lograste esas MEDALLAS\n"
    .string "de los LÍDERES del GIMNASIO!$"

Route13_Text_GwenIntro::
    .string "Mis simpáticos POKéMON quieren\n"
    .string "conocerte.$"

Route13_Text_GwenDefeat::
    .string "¡Uauu!\n"
    .string "¡Me has machacado!$"

Route13_Text_GwenPostBattle::
    .string "¡Tienes que hacer luchar a tus\n"
    .string "POKéMON para fortalecerlos!$"

Route13_Text_AlmaIntro::
    .string "¡Una vez encontré CARBURANTE\n"
    .string "en una cueva!$"

Route13_Text_AlmaDefeat::
    .string "¡Lo he hecho fatal!$"

Route13_Text_AlmaPostBattle::
    .string "El CARBURANTE aumentó la\n"
    .string "VELOCIDAD de mis POKéMON.$"

Route13_Text_PerryIntro::
    .string "No voy a perder.\n"
    .string "¡El viento sopla en mi dirección!$"

Route13_Text_PerryDefeat::
    .string "¡El viento ha cambiado!$"

Route13_Text_PerryPostBattle::
    .string "He perdido. Creo que usaré\n"
    .string "VOLAR para ir a casa.$"

Route13_Text_LolaIntro::
    .string "¡Claro que jugaré contigo!$"

Route13_Text_LolaDefeat::
    .string "¡Oh!\n"
    .string "¡Qué salvaje eres!$"

Route13_Text_LolaPostBattle::
    .string "¿Cuál es más fuerte, un POKéMON\n"
    .string "macho o hembra?$"

Route13_Text_SheilaIntro::
    .string "¿Quieres jugar conmigo\n"
    .string "a POKéMON?$"

Route13_Text_SheilaDefeat::
    .string "¿Ya se ha terminado?$"

Route13_Text_SheilaPostBattle::
    .string "¡No sé nada sobre los POKéMON!\n"
    .string "¡Me gustan los más chulos!$"

Route13_Text_JaredIntro::
    .string "¿Y tú qué miras?$"

Route13_Text_JaredDefeat::
    .string "¡Vaya!\n"
    .string "¡Qué patinazo!$"

Route13_Text_JaredPostBattle::
    .string "¡Olvídame!$"

Route13_Text_RobertIntro::
    .string "¡Me encantan los pájaros POKéMON!$"

Route13_Text_RobertDefeat::
    .string "¡Me he quedado sin energía!$"

Route13_Text_RobertPostBattle::
    .string "Ojalá pudiera volar como PIDGEY\n"
    .string "y PIDGEOTTO...$"

Route13_Text_LookToLeftOfThatPost::
    .string "PISTAS ENTRENADOR\p"
    .string "¡Mira a la izquierda de ese poste!$"

Route13_Text_SelectToSwitchItems::
    .string "PISTAS ENTRENADOR\p"
    .string "¡Usa SELECT para cambiar objetos\n"
    .string "en la ventana OBJETOS!$"

Route13_Text_RouteSign::
    .string "RUTA 13:\n"
    .string "PUENTE SILENCIO, al norte$"
