Route13_Text_SebastianIntro::
    .ifdef ENGLISH
    .string "My bird POKéMON want to battle\n"
    .string "with you!$"
    .endif
    .ifdef SPANISH
    .string "¡Mis pájaros POKéMON quieren\n"
    .string "pelear!$"
    .endif

Route13_Text_SebastianDefeat::
    .ifdef ENGLISH
    .string "My PIDGEY and PIDGEOTTO combo\n"
    .string "lost?$"
    .endif
    .ifdef SPANISH
    .string "¿Perdió mi combinación de pájaros?$"
    .endif

Route13_Text_SebastianPostBattle::
    .ifdef ENGLISH
    .string "My POKéMON look happy even though\n"
    .string "they lost.$"
    .endif
    .ifdef SPANISH
    .string "Mis POKéMON parecen felices\n"
    .string "aunque hayan perdido.$"
    .endif

Route13_Text_SusieIntro::
    .ifdef ENGLISH
    .string "I'm told I'm good for a kid.$"
    .endif
    .ifdef SPANISH
    .string "¡Dicen que soy muy buena\n"
    .string "para ser tan pequeña!$"
    .endif

Route13_Text_SusieDefeat::
    .ifdef ENGLISH
    .string "Ohh!\n"
    .string "I lost!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh!\n"
    .string "¡He perdido!$"
    .endif

Route13_Text_SusiePostBattle::
    .ifdef ENGLISH
    .string "I want to become a good TRAINER.\n"
    .string "I'll train hard, just watch.$"
    .endif
    .ifdef SPANISH
    .string "Quiero ser una gran ENTRENADORA.\n"
    .string "Voy a entrenarme mucho.$"
    .endif

Route13_Text_ValerieIntro::
    .ifdef ENGLISH
    .string "Wow!\n"
    .string "Your BADGES are too cool!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué chulas son tus MEDALLAS!$"
    .endif

Route13_Text_ValerieDefeat::
    .ifdef ENGLISH
    .string "Not enough!$"
    .endif
    .ifdef SPANISH
    .string "¡No he estado a la altura!$"
    .endif

Route13_Text_ValeriePostBattle::
    .ifdef ENGLISH
    .string "You got those BADGES from GYM\n"
    .string "LEADERS. I know!$"
    .endif
    .ifdef SPANISH
    .string "¡Sé que lograste esas MEDALLAS\n"
    .string "de los LÍDERES del GIMNASIO!$"
    .endif

Route13_Text_GwenIntro::
    .ifdef ENGLISH
    .string "My cute POKéMON wish to make your\n"
    .string "acquaintance.$"
    .endif
    .ifdef SPANISH
    .string "Mis simpáticos POKéMON quieren\n"
    .string "conocerte.$"
    .endif

Route13_Text_GwenDefeat::
    .ifdef ENGLISH
    .string "Good going!\n"
    .string "You totally won!$"
    .endif
    .ifdef SPANISH
    .string "¡Uauu!\n"
    .string "¡Me has machacado!$"
    .endif

Route13_Text_GwenPostBattle::
    .ifdef ENGLISH
    .string "You have to make POKéMON battle\n"
    .string "to toughen them up.$"
    .endif
    .ifdef SPANISH
    .string "¡Tienes que hacer luchar a tus\n"
    .string "POKéMON para fortalecerlos!$"
    .endif

Route13_Text_AlmaIntro::
    .ifdef ENGLISH
    .string "I found CARBOS in a cave once\n"
    .string "while I was spelunking.$"
    .endif
    .ifdef SPANISH
    .string "¡Una vez encontré CARBURANTE\n"
    .string "en una cueva!$"
    .endif

Route13_Text_AlmaDefeat::
    .ifdef ENGLISH
    .string "Oh, too bad!\n"
    .string "I just messed up!$"
    .endif
    .ifdef SPANISH
    .string "¡Lo he hecho fatal!$"
    .endif

Route13_Text_AlmaPostBattle::
    .ifdef ENGLISH
    .string "CARBOS boosted the SPEED of my\n"
    .string "POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "El CARBURANTE aumentó la\n"
    .string "VELOCIDAD de mis POKéMON.$"
    .endif

Route13_Text_PerryIntro::
    .ifdef ENGLISH
    .string "I'm not going to lose.\n"
    .string "Not when the wind's blowing my way!$"
    .endif
    .ifdef SPANISH
    .string "No voy a perder.\n"
    .string "¡El viento sopla en mi dirección!$"
    .endif

Route13_Text_PerryDefeat::
    .ifdef ENGLISH
    .string "The wind turned!$"
    .endif
    .ifdef SPANISH
    .string "¡El viento ha cambiado!$"
    .endif

Route13_Text_PerryPostBattle::
    .ifdef ENGLISH
    .string "I'm beat.\n"
    .string "I guess I'll FLY home.$"
    .endif
    .ifdef SPANISH
    .string "He perdido. Creo que usaré\n"
    .string "VOLAR para ir a casa.$"
    .endif

Route13_Text_LolaIntro::
    .ifdef ENGLISH
    .string "Sure, I'll play with you, sweetie.$"
    .endif
    .ifdef SPANISH
    .string "¡Claro que jugaré contigo!$"
    .endif

Route13_Text_LolaDefeat::
    .ifdef ENGLISH
    .string "Oh!\n"
    .string "You little beast!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh!\n"
    .string "¡Qué salvaje eres!$"
    .endif

Route13_Text_LolaPostBattle::
    .ifdef ENGLISH
    .string "I wonder which is stronger, male or\n"
    .string "female POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¿Cuál es más fuerte, un POKéMON\n"
    .string "macho o hembra?$"
    .endif

Route13_Text_SheilaIntro::
    .ifdef ENGLISH
    .string "Do you want to battle some\n"
    .string "POKéMON with me?$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres jugar conmigo\n"
    .string "a POKéMON?$"
    .endif

Route13_Text_SheilaDefeat::
    .ifdef ENGLISH
    .string "It's over already?$"
    .endif
    .ifdef SPANISH
    .string "¿Ya se ha terminado?$"
    .endif

Route13_Text_SheilaPostBattle::
    .ifdef ENGLISH
    .string "I don't know anything about\n"
    .string "POKéMON actually.\p"
    .string "The ones I use… I picked them\n"
    .string "for their looks!$"
    .endif
    .ifdef SPANISH
    .string "¡No sé nada sobre los POKéMON!\n"
    .string "¡Me gustan los más chulos!$"
    .endif

Route13_Text_JaredIntro::
    .ifdef ENGLISH
    .string "What're you lookin' at?$"
    .endif
    .ifdef SPANISH
    .string "¿Y tú qué miras?$"
    .endif

Route13_Text_JaredDefeat::
    .ifdef ENGLISH
    .string "Dang!\n"
    .string "Stripped gears!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya!\n"
    .string "¡Qué patinazo!$"
    .endif

Route13_Text_JaredPostBattle::
    .ifdef ENGLISH
    .string "Get lost!$"
    .endif
    .ifdef SPANISH
    .string "¡Olvídame!$"
    .endif

Route13_Text_RobertIntro::
    .ifdef ENGLISH
    .string "I always go with bird POKéMON.\n"
    .string "I've dedicated myself to them.$"
    .endif
    .ifdef SPANISH
    .string "¡Me encantan los pájaros POKéMON!$"
    .endif

Route13_Text_RobertDefeat::
    .ifdef ENGLISH
    .string "Out of power!$"
    .endif
    .ifdef SPANISH
    .string "¡Me he quedado sin energía!$"
    .endif

Route13_Text_RobertPostBattle::
    .ifdef ENGLISH
    .string "I wish I could fly like PIDGEY and\n"
    .string "PIDGEOTTO…$"
    .endif
    .ifdef SPANISH
    .string "Ojalá pudiera volar como PIDGEY\n"
    .string "y PIDGEOTTO...$"
    .endif

Route13_Text_LookToLeftOfThatPost::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "Look, look!\n"
    .string "Look to the left of that post!$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "¡Mira a la izquierda de ese poste!$"
    .endif

Route13_Text_SelectToSwitchItems::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "Use SELECT to switch items in the\n"
    .string "ITEMS window.$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "¡Usa SELECT para cambiar objetos\n"
    .string "en la ventana OBJETOS!$"
    .endif

Route13_Text_RouteSign::
    .ifdef ENGLISH
    .string "ROUTE 13\n"
    .string "North to SILENCE BRIDGE$"
    .endif
    .ifdef SPANISH
    .string "RUTA 13:\n"
    .string "PUENTE SILENCIO, al norte$"
    .endif

