VermilionCity_PokemonCenter_1F_Text_TrainerMonsStrongerThanWild::
    .ifdef ENGLISH
    .string "Even if they are the same level,\n"
    .string "POKéMON can have very different\l"
    .string "stats and abilities.\p"
    .string "A POKéMON raised by a TRAINER is\n"
    .string "stronger than one in the wild.$"
    .endif
    .ifdef SPANISH
    .string "Aunque sean del mismo nivel, los\n"
    .string "POKéMON pueden tener diferentes\l"
    .string "habilidades.\p"
    .string "Un POKéMON entrenado es más fuerte\n"
    .string "que uno salvaje.$"
    .endif

VermilionCity_PokemonCenter_1F_Text_PoisonedMonFaintedWhileWalking::
    .ifdef ENGLISH
    .string "My POKéMON was poisoned!\n"
    .string "It fainted while we were walking!$"
    .endif
    .ifdef SPANISH
    .string "¡Mi POKéMON fue envenenado y\n"
    .string "se debilitó mientras caminábamos!$"
    .endif

VermilionCity_PokemonCenter_1F_Text_AllMonWeakToSpecificTypes::
    .ifdef ENGLISH
    .string "It is true that a higher-level\n"
    .string "POKéMON will be more powerful…\p"
    .string "But, all POKéMON will have weak\n"
    .string "points against specific types.\p"
    .string "So, there appears to be no\n"
    .string "universally strong POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "Es cierto que un POKéMON de un\n"
    .string "nivel superior es más fuerte.\p"
    .string "Pero todos los POKéMON son\n"
    .string "vulnerables ante ciertos tipos.\p"
    .string "Es decir, que no hay POKéMON\n"
    .string "invulnerables.$"
    .endif

VermilionCity_PokemonCenter_1F_Text_UrgeToBattleSomeoneAgain::
    .ifdef ENGLISH
    .string "The urge to battle with someone\n"
    .string "you've tangled with before…\p"
    .string "Have you ever had that urge?\n"
    .string "I'm sure you have.\p"
    .string "I wanted to battle certain people\n"
    .string "again over and over, too.\p"
    .string "So, I've been giving these away.\n"
    .string "Please, take one!$"
    .endif
    .ifdef SPANISH
    .string "Esa necesidad de luchar de nuevo\n"
    .string "con gente a la que ya te has\l"
    .string "enfrentado...\p"
    .string "¿Sabes a lo que me refiero?\n"
    .string "Seguro que la has sentido alguna\l"
    .string "vez.\p"
    .string "Yo quería luchar una y otra vez\n"
    .string "con mis antiguos rivales.\p"
    .string "Y me dieron esto.\n"
    .string "¡Toma uno para ti!$"
    .endif

VermilionCity_PokemonCenter_1F_Text_UseDeviceForRematches::
    .ifdef ENGLISH
    .string "Use that device and you'll find\n"
    .string "TRAINERS looking for a rematch.\p"
    .string "You have to charge its battery to\n"
    .string "use it, though.$"
    .endif
    .ifdef SPANISH
    .string "Usa este dispositivo para ver qué\n"
    .string "ENTRENADOR quiere luchar de\l"
    .string "nuevo contigo.\p"
    .string "Ten en cuenta que debes cargar\n"
    .string "la batería.$"
    .endif

VermilionCity_PokemonCenter_1F_Text_ExplainVSSeeker::
    .ifdef ENGLISH
    .string "How do you use the VS SEEKER?\n"
    .string "There's nothing to it.\p"
    .string "Use it like beep-beep-beep, and\n"
    .string "TRAINERS around you will notice.\p"
    .string "If any TRAINER wants a rematch,\n"
    .string "it will let you know immediately.\p"
    .string "Charge its battery and use it\n"
    .string "while you're on a road.$"
    .endif
    .ifdef SPANISH
    .string "¿Que cómo se usa el BUSCAPELEA?\n"
    .string "No tiene mayor misterio.\p"
    .string "Al usarlo, emitirá un ruidito que\n"
    .string "alertará a los ENTRENADORES\l"
    .string "que haya por la zona.\p"
    .string "Si alguno quisiera luchar otra\n"
    .string "vez contigo, te lo hará saber\l"
    .string "de inmediato.\p"
    .string "Carga la batería y úsalo cuando\n"
    .string "vayas por ahí.$"
    .endif
