ViridianCity_Text_CanCarryMonsAnywhere::
	.string "C'est une POKé BALL que je vois!\n"
	.string "Alors t'as aussi des POKéMON?\p"
	.string "C'est cool de pouvoir s'en servir\n"
	.string "quand on veut, hein?$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
	.string "Cette ARENE POKéMON est\n"
	.string "toujours fermée.\p"
	.string "Mais qui en est le CHAMPION?$"

ViridianCity_Text_ViridiansGymLeaderReturned::
	.string "Le CHAMPION de l'ARENE de\n"
	.string "JADIELLE est de retour!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
	.string "Tu veux tout savoir sur les deux\n"
	.string "types de POKéMON chenille?$"

ViridianCity_Text_OhOkayThen::
	.string "Bon, OK!$"

ViridianCity_Text_ExplainCaterpieWeedle::
	.string "Contrairement à CHENIPAN, ASPICOT\n"
	.string "est venimeux.\p"
	.string "Attention à son DARD-VENIN!$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
	.string "Papy!\n"
	.string "Ne sois pas si méchant.\p"
	.string "Je suis désolée.\n"
	.string "Il n'a pas encore eu son café.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
	.string "Je passe par la FORET DE JADE\n"
	.string "pour faire mes courses à ARGENTA.$"

ViridianCity_Text_ThisIsPrivateProperty::
	.string "Je t'interdis de passer par là!\p"
	.string "C'est une propriété privée!$"

ViridianCity_Text_ShowYouHowToCatchMons::
	.string "Il me fallait juste un café pour\n"
	.string "être sur pied!\p"
	.string "Hum? Qu'est-ce que c'est que\n"
	.string "cette boîte rouge que tu as?\p"
	.string "Ah, alors tu travailles sur\n"
	.string "ton POKéDEX.\p"
	.string "Laisse-moi te donner un\n"
	.string "petit conseil.\p"
	.string "Le POKéDEX se met à jour dès\n"
	.string "que tu attrapes un POKéMON.\p"
	.string "… Tu ne sais pas attraper\n"
	.string "de POKéMON?\p"
	.string "Je crois que je ferais mieux de\n"
	.string "te montrer alors!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
	.string "Et voilà! Si tu n'as pas compris\n"
	.string "avec ça…\p"
	.string "Je voudrais aussi que tu\n"
	.string "prennes ceci.$"

ViridianCity_Text_WatchThatToLearnBasics::
	.string "S'il y a quelque chose que tu\n"
	.string "ne comprends pas, regarde bien.\p"
	.string "Cela t'apprendra les bases pour\n"
	.string "être DRESSEUR de POKéMON.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
	.string "Ahh… Un p'tit somme, un bon café\n"
	.string "et hop! La pêche pour la journée!\p"
	.string "Mais j'ai dû le faire trop fort.\n"
	.string "J'ai la migraine maintenant.\p"
	.string "Au fait, est-ce que tu remplis\n"
	.string "ton POKéDEX?\p"
	.string "Pense à bien affaiblir les\n"
	.string "POKéMON avant de les attraper.$"

ViridianCity_Text_HowsTeachyTVHelping::
	.string "Ahh… Un p'tit somme, un bon café\n"
	.string "et hop! La pêche pour la journée!\p"
	.string "Mais j'ai dû le faire trop fort.\n"
	.string "J'ai la migraine maintenant.\p"
	.string "Au fait, est-ce que tu regardes\n"
	.string "souvent TV ABC?$"

ViridianCity_Text_MyGrandsonOnTheShow::
	.string "Ahaha!\n"
	.string "C'est mon petit-fils à la télé!\p"
	.string "Avec lui, tu vas tout comprendre!$"

ViridianCity_Text_TooBusyForTeachyTV::
	.string "Hum. Tu dois avoir trop de choses\n"
	.string "à faire pour regarder la télé.\p"
	.string "Le temps c'est de l'argent,\n"
	.string "t'as bien raison.$"

ViridianCity_Text_CitySign::
	.string "JADIELLE\n"
	.string "Verte comme l'espérance$"

ViridianCity_Text_CatchMonsForEasierBattles::
	.string "ASTUCE\p"
	.string "Attrapez des POKéMON et\n"
	.string "agrandissez votre collection!\p"
	.string "Plus vous en capturez, plus\n"
	.string "les combats sont faciles!$"

ViridianCity_Text_MovesLimitedByPP::
	.string "ASTUCE\p"
	.string "Les attaques sont limitées par des\n"
	.string "PP (Points de Pouvoir).\p"
	.string "Pour disposer de tous vos PP,\n"
	.string "faites soigner vos POKéMON dans\l"
	.string "un CENTRE POKéMON!$"

ViridianCity_Text_GymSign::
	.string "ARENE POKéMON de JADIELLE$"

ViridianCity_Text_GymDoorsAreLocked::
	.string "Les portes de l'ARENE sont\n"
	.string "fermées…$"

