ViridianCity_Text_CanCarryMonsAnywhere::
    .string "¿Llevas POKé BALLS?\n"
    .string "¡Entonces tú tienes POKéMON!\p"
    .string "¡Es genial poder llevar y usar los\n"
    .string "POKéMON en cualquier momento\l"
    .string "y lugar!$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "Este GIMNASIO POKéMON está\n"
    .string "siempre cerrado.\p"
    .string "Me pregunto quién será su LÍDER.$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "¡El LÍDER del GIMNASIO VERDE\n"
    .string "ha vuelto!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "¿Quieres saber algo sobre los 2\n"
    .string "tipos de orugas POKéMON?$"

ViridianCity_Text_OhOkayThen::
    .string "Vale, pues nada.$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "¡CATERPIE no tiene veneno; pero\n"
    .string "WEEDLE, sí!\p"
    .string "¡Cuidado con su PICOTAZO\n"
    .string "VENENOSO!$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "¡Oh, abuelo!\n"
    .string "¡No seas tan malo!\p"
    .string "Lo siento, todavía no se ha tomado\n"
    .string "un café...$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "¡Cuando voy de compras a\n"
    .string "CIUDAD PLATEADA, tomo el sinuoso\l"
    .string "camino del BOSQUE VERDE!$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "¡No puedes pasar por aquí!\p"
    .string "¡Es propiedad privada!$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "Lo bien que me sienta tomarme\n"
    .string "un cafelito... ¡me pone las pilas!\p"
    .string "¿Y esa caja roja que llevas ahí?\p"
    .string "Ah, así que estás trabajando\n"
    .string "en tu POKéDEX...\p"
    .string "Pues deja que te diga algo.\p"
    .string "Cuando atrapes un POKéMON,\n"
    .string "la POKéDEX actualizará sus datos\l"
    .string "de forma automática.\p"
    .string "¿Cómo? ¿Que no sabes atrapar\n"
    .string "POKéMON?\p"
    .string "¡Pues haber empezado por ahí!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "Bueno, no me dirás que no ha sido\n"
    .string "ilustrativo, ¿eh?\p"
    .string "Anda, toma, esto es para ti.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "Úsala cuando haya alguna cosilla\n"
    .string "que no entiendas.\p"
    .string "Te explicará muy bien lo básico\n"
    .string "para ser buen ENTRENADOR POKéMON.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "Lo bien que me sienta tomarme\n"
    .string "un cafelito... ¡me pone las pilas!\p"
    .string "Aunque..., creo que estaba muy\n"
    .string "cargado... Me duele la cabeza.\p"
    .string "A todo esto, ¿estás completando\n"
    .string "la POKéDEX?\p"
    .string "No olvides que conviene agotar\n"
    .string "todo lo posible a los POKéMON\l"
    .string "antes de intentar atraparlos.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "Lo bien que me sienta tomarme\n"
    .string "un cafelito... ¡me pone las pilas!\p"
    .string "Aunque..., creo que estaba muy\n"
    .string "cargado... Me duele la cabeza.\p"
    .string "A todo esto, ¿te está sirviendo\n"
    .string "mi vieja POKé TELE?$"

ViridianCity_Text_MyGrandsonOnTheShow::
    .string "¡No me extraña, el chico es\n"
    .string "mi nieto!\p"
    .string "¡Con él aprende hasta el menos\n"
    .string "espabilado, je!$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "Mmm... Supongo que será porque\n"
    .string "no tienes apenas tiempo de\l"
    .string "encenderla...\p"
    .string "El tiempo es oro, tú sabrás cómo\n"
    .string "lo administras...$"

ViridianCity_Text_CitySign::
    .string "CIUDAD VERDE\n"
    .string "El paraíso del eterno verdor.$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "PISTAS ENTRENADOR\p"
    .string "¡Atrapa los POKéMON y amplía\n"
    .string "tu colección!\p"
    .string "¡Cuantos más tengas, más fácil\n"
    .string "te será luchar!$"

ViridianCity_Text_MovesLimitedByPP::
    .string "PISTAS ENTRENADOR\p"
    .string "Los ataques de los POKéMON\n"
    .string "dependen de sus PUNTOS de PODER\l"
    .string "o PP.\p"
    .string "¡Para rellenar tus PP, deja que\n"
    .string "tus cansados POKéMON descansen\l"
    .string "en un CENTRO POKéMON!$"

ViridianCity_Text_GymSign::
    .string "GIMNASIO POKéMON DE CIUDAD VERDE$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "Las puertas del GIMNASIO están\n"
    .string "cerradas...$"
