ViridianCity_Text_CanCarryMonsAnywhere::
	.string "Diese POKéBÄLLE an deinem Gürtel\n"
	.string "zeigen mir, dass du POKéMON\l"
	.string "besitzt!\p"
	.string "Es ist Klasse, dass man jederzeit\n"
	.string "POKéMON tragen und einsetzen kann,\l"
	.string "nicht wahr?$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
	.string "Diese POKéMON-ARENA ist stets\n"
	.string "geschlossen!\p"
	.string "Ich frage mich, wer hier wohl der\n"
	.string "ARENALEITER sein mag?$"

ViridianCity_Text_ViridiansGymLeaderReturned::
	.string "Der ARENALEITER von VERTANIA CITY\n"
	.string "ist zurück!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
	.string "Möchtest du etwas über die zwei\n"
	.string "RAUPEN-POKéMON erfahren?$"

ViridianCity_Text_OhOkayThen::
	.string "O.K., alles klar!$"

ViridianCity_Text_ExplainCaterpieWeedle::
	.string "RAUPY ist nicht giftig, aber\n"
	.string "HORNLIU!\p"
	.string "Achte auf seinen GIFTSTACHEL!$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
	.string "Großvater!\n"
	.string "Sei nicht so gemein!\p"
	.string "Er hatte noch keinen Kaffee!!!$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
	.string "Wenn ich zum Einkaufen nach\n"
	.string "MARMORIA CITY möchte, muss ich\l"
	.string "immer durch den VERTANIA-WALD\l"
	.string "gehen.$"

ViridianCity_Text_ThisIsPrivateProperty::
	.string "Du kannst hier nicht durch!\p"
	.string "Das ist ein Privatgelände!$"

ViridianCity_Text_ShowYouHowToCatchMons::
	.string "Nun, jetzt hatte ich meinen\n"
	.string "Kaffee und das ist alles, was\l"
	.string "ich brauche, um loszulegen!\l"
	.string "Hmm?\l"
	.string "Was ist das für eine rote Box?\p"
	.string "Ah, du arbeitest an einem\n"
	.string "POKéDEX.\p"
	.string "Dann will ich dir einen Ratschlag\n"
	.string "geben.\p"
	.string "Der POKéDEX wird mit jedem neu\n"
	.string "gefangenen POKéMON aktualisiert.\p"
	.string "… du weißt nicht, wie man\n"
	.string "POKéMON fängt?\p"
	.string "Ich sollte es dir wohl besser\n"
	.string "zeigen!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
	.string "So! Das war doch perfekter\n"
	.string "Anschauungsunterricht, oder?\p"
	.string "Und hier, nimm dies auch noch!$"

ViridianCity_Text_WatchThatToLearnBasics::
	.string "Falls es etwas gibt, das du nicht\n"
	.string "verstehst, dann schau da rein!\l"
	.string "Dort erfährst du die Grundlagen\l"
	.string "über den Beruf eines POKéMON\l"
	.string "TRAINERs.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
	.string "Ahh, ich habe endlich meinen\n"
	.string "Kaffee bekommen!\l"
	.string "Aber er war zu stark. Jetzt habe\l"
	.string "ich Kopfschmerzen…\p"
	.string "Vervollständigst du zufällig einen\n"
	.string "POKéDEX?\p"
	.string "Konzentriere dich zunächst darauf,\n"
	.string "das POKéMON zu schwächen, ehe\l"
	.string "du es fangen möchtest.$"

ViridianCity_Text_HowsTeachyTVHelping::
	.string "Ahh, ich habe endlich meinen\n"
	.string "Kaffee bekommen!\p"
	.string "Aber er war zu stark. Jetzt habe\n"
	.string "ich Kopfschmerzen…\p"
	.string "Hilft dir mein LEHRKANAL?$"

ViridianCity_Text_MyGrandsonOnTheShow::
	.string "Wahaha!\n"
	.string "Mein Enkel ist im Fernsehen!\p"
	.string "Da er den Unterricht leitet,\n"
	.string "musst du lernen.$"

ViridianCity_Text_TooBusyForTeachyTV::
	.string "Hm… du hast keine Zeit, um\n"
	.string "den LEHRKANAL anzuschauen…\l"
	.string "Zeit ist Geld und keines davon\l"
	.string "sollte man leichtsinnig\l"
	.string "verschwenden…$"

ViridianCity_Text_CitySign::
	.string "VERTANIA CITY\n"
	.string "Das immergrüne Paradies!$"

ViridianCity_Text_CatchMonsForEasierBattles::
	.string "TIPPS FÜR TRAINER\p"
	.string "Fange POKéMON, um deine Sammlung\n"
	.string "zu erweitern!\p"
	.string "Je mehr du besitzt, desto leichter\n"
	.string "werden die Kämpfe!$"

ViridianCity_Text_MovesLimitedByPP::
	.string "TIPPS FÜR TRAINER\p"
	.string "Die Attacken der POKéMON werden\n"
	.string "durch ihre ANGRIFFSPUNKTE, AP,\l"
	.string "limitiert.\p"
	.string "Um die AP wieder aufzufüllen, musst\n"
	.string "du die POKéMON in ein POKéMON-\l"
	.string "CENTER bringen!$"

ViridianCity_Text_GymSign::
	.string "VERTANIA CITY POKéMON-ARENA$"

ViridianCity_Text_GymDoorsAreLocked::
	.string "Die Türen der ARENA sind\n"
	.string "verschlossen...$"

