ViridianCity_Text_CanCarryMonsAnywhere::
    .ifdef ENGLISH
    .string "Those POKé BALLS at your waist!\n"
    .string "You have POKéMON, don't you?\p"
    .string "It's great that you can carry and\n"
    .string "use POKéMON anytime, anywhere.$"
    .endif
    .ifdef SPANISH
    .string "¿Llevas POKé BALLS?\n"
    .string "¡Entonces tú tienes POKéMON!\p"
    .string "¡Es genial poder llevar y usar los\n"
    .string "POKéMON en cualquier momento\l"
    .string "y lugar!$"
    .endif

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .ifdef ENGLISH
    .string "This POKéMON GYM is always closed.\p"
    .string "I wonder who the LEADER is?$"
    .endif
    .ifdef SPANISH
    .string "Este GIMNASIO POKéMON está\n"
    .string "siempre cerrado.\p"
    .string "Me pregunto quién será su LÍDER.$"
    .endif

ViridianCity_Text_ViridiansGymLeaderReturned::
    .ifdef ENGLISH
    .string "VIRIDIAN GYM's LEADER returned!$"
    .endif
    .ifdef SPANISH
    .string "¡El LÍDER del GIMNASIO VERDE\n"
    .string "ha vuelto!$"
    .endif

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .ifdef ENGLISH
    .string "You want to know about the two\n"
    .string "kinds of caterpillar POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¿Quieres saber algo sobre los 2\n"
    .string "tipos de orugas POKéMON?$"
    .endif

ViridianCity_Text_OhOkayThen::
    .ifdef ENGLISH
    .string "Oh, okay then!$"
    .endif
    .ifdef SPANISH
    .string "Vale, pues nada.$"
    .endif

ViridianCity_Text_ExplainCaterpieWeedle::
    .ifdef ENGLISH
    .string "CATERPIE has no poison,\n"
    .string "but WEEDLE does.\p"
    .string "Watch that your POKéMON aren't\n"
    .string "stabbed by WEEDLE's POISON STING.$"
    .endif
    .ifdef SPANISH
    .string "¡CATERPIE no tiene veneno; pero\n"
    .string "WEEDLE, sí!\p"
    .string "¡Cuidado con su PICOTAZO\n"
    .string "VENENOSO!$"
    .endif

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .ifdef ENGLISH
    .string "Oh, Grandpa!\n"
    .string "Don't be so mean!\p"
    .string "I'm so sorry.\n"
    .string "He hasn't had his coffee yet.$"
    .endif
    .ifdef SPANISH
    .string "¡Oh, abuelo!\n"
    .string "¡No seas tan malo!\p"
    .string "Lo siento, todavía no se ha tomado\n"
    .string "un café...$"
    .endif

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .ifdef ENGLISH
    .string "I go shopping in PEWTER CITY\n"
    .string "occasionally.\p"
    .string "I have to take the winding trail in\n"
    .string "VIRIDIAN FOREST when I go.$"
    .endif
    .ifdef SPANISH
    .string "¡Cuando voy de compras a\n"
    .string "CIUDAD PLATEADA, tomo el sinuoso\l"
    .string "camino del BOSQUE VERDE!$"
    .endif

ViridianCity_Text_ThisIsPrivateProperty::
    .ifdef ENGLISH
    .string "I absolutely forbid you from\n"
    .string "going through here!\p"
    .string "This is private property!$"
    .endif
    .ifdef SPANISH
    .string "¡No puedes pasar por aquí!\p"
    .string "¡Es propiedad privada!$"
    .endif

ViridianCity_Text_ShowYouHowToCatchMons::
    .ifdef ENGLISH
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "Hm?\n"
    .string "What is that red box you have?\p"
    .string "Ah, so you're working on your\n"
    .string "POKéDEX.\p"
    .string "Then let me give you a word of\n"
    .string "advice.\p"
    .string "Whenever you catch a POKéMON,\n"
    .string "the POKéDEX automatically updates\l"
    .string "its data.\p"
    .string "…You don't know how to catch\n"
    .string "a POKéMON?\p"
    .string "I suppose I had better show you\n"
    .string "then!$"
    .endif
    .ifdef SPANISH
    .string "Lo bien que me sienta tomarme\n"
    .string "un cafelito... ¡me pone las pilas!\p"
    .string "¿Y esa caja roja que llevas ahí?\p"
    .string "Ah, así que estás trabajando\n"
    .string "en tu POKéDEX...\p"
    .string "Pues deja que te diga algo.\p"
    .string "Cuando atrapes un POKéMON,\n"
    .string "la POKéDEX actualizará sus datos\l"
    .string "de forma automática.\p"
    .string "¿Cómo? ¿Que no sabes atrapar\n"
    .string "POKéMON?\p"
    .string "¡Pues haber empezado por ahí!$"
    .endif

ViridianCity_Text_ThatWasEducationalTakeThis::
    .ifdef ENGLISH
    .string "There! Now tell me, that was\n"
    .string "educational, was it not?\p"
    .string "And here, take this, too.$"
    .endif
    .ifdef SPANISH
    .string "Bueno, no me dirás que no ha sido\n"
    .string "ilustrativo, ¿eh?\p"
    .string "Anda, toma, esto es para ti.$"
    .endif

ViridianCity_Text_WatchThatToLearnBasics::
    .ifdef ENGLISH
    .string "If there's something you don't\n"
    .string "understand, watch that.\p"
    .string "It will teach you about the basics\n"
    .string "of being a POKéMON TRAINER.$"
    .endif
    .ifdef SPANISH
    .string "Úsala cuando haya alguna cosilla\n"
    .string "que no entiendas.\p"
    .string "Te explicará muy bien lo básico\n"
    .string "para ser buen ENTRENADOR POKéMON.$"
    .endif

ViridianCity_Text_WeakenMonsFirstToCatch::
    .ifdef ENGLISH
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, are you filling your\n"
    .string "POKéDEX?\p"
    .string "At first, focus on weakening the\n"
    .string "POKéMON before trying to catch it.$"
    .endif
    .ifdef SPANISH
    .string "Lo bien que me sienta tomarme\n"
    .string "un cafelito... ¡me pone las pilas!\p"
    .string "Aunque..., creo que estaba muy\n"
    .string "cargado... Me duele la cabeza.\p"
    .string "A todo esto, ¿estás completando\n"
    .string "la POKéDEX?\p"
    .string "No olvides que conviene agotar\n"
    .string "todo lo posible a los POKéMON\l"
    .string "antes de intentar atraparlos.$"
    .endif

ViridianCity_Text_HowsTeachyTVHelping::
    .ifdef ENGLISH
    .string "Well, now, I've had my coffee, and\n"
    .string "that's what I need to get going!\p"
    .string "But I made it too strong.\n"
    .string "It gave me a headache…\p"
    .string "Incidentally, is my old TEACHY TV\n"
    .string "helping you?$"
    .endif
    .ifdef SPANISH
    .string "Lo bien que me sienta tomarme\n"
    .string "un cafelito... ¡me pone las pilas!\p"
    .string "Aunque..., creo que estaba muy\n"
    .string "cargado... Me duele la cabeza.\p"
    .string "A todo esto, ¿te está sirviendo\n"
    .string "mi vieja POKé TELE?$"
    .endif

ViridianCity_Text_MyGrandsonOnTheShow::
    .ifdef ENGLISH
    .string "Wahaha!\n"
    .string "It's my grandson on the show!\p"
    .string "Since he's the one doing the\n"
    .string "teaching, you're bound to learn.$"
    .endif
    .ifdef SPANISH
    .string "¡No me extraña, el chico es\n"
    .string "mi nieto!\p"
    .string "¡Con él aprende hasta el menos\n"
    .string "espabilado, je!$"
    .endif

ViridianCity_Text_TooBusyForTeachyTV::
    .ifdef ENGLISH
    .string "Hm… You're too busy to not even\n"
    .string "have the time for TEACHY TV…\p"
    .string "Time is money, and neither should\n"
    .string "be ill spent…$"
    .endif
    .ifdef SPANISH
    .string "Mmm... Supongo que será porque\n"
    .string "no tienes apenas tiempo de\l"
    .string "encenderla...\p"
    .string "El tiempo es oro, tú sabrás cómo\n"
    .string "lo administras...$"
    .endif

ViridianCity_Text_CitySign::
    .ifdef ENGLISH
    .string "VIRIDIAN CITY \n"
    .string "The Eternally Green Paradise$"
    .endif
    .ifdef SPANISH
    .string "CIUDAD VERDE\n"
    .string "El paraíso del eterno verdor.$"
    .endif

ViridianCity_Text_CatchMonsForEasierBattles::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "Catch POKéMON and expand your\n"
    .string "collection.\p"
    .string "The more you have, the easier it\n"
    .string "is to battle.$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "¡Atrapa los POKéMON y amplía\n"
    .string "tu colección!\p"
    .string "¡Cuantos más tengas, más fácil\n"
    .string "te será luchar!$"
    .endif

ViridianCity_Text_MovesLimitedByPP::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "The battle moves of POKéMON are\n"
    .string "limited by their POWER POINTS, PP.\p"
    .string "To replenish PP, rest your tired\n"
    .string "POKéMON at a POKéMON CENTER.$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "Los ataques de los POKéMON\n"
    .string "dependen de sus PUNTOS de PODER\l"
    .string "o PP.\p"
    .string "¡Para rellenar tus PP, deja que\n"
    .string "tus cansados POKéMON descansen\l"
    .string "en un CENTRO POKéMON!$"
    .endif

ViridianCity_Text_GymSign::
    .ifdef ENGLISH
    .string "VIRIDIAN CITY POKéMON GYM$"
    .endif
    .ifdef SPANISH
    .string "GIMNASIO POKéMON DE CIUDAD VERDE$"
    .endif

ViridianCity_Text_GymDoorsAreLocked::
    .ifdef ENGLISH
    .string "VIRIDIAN GYM's doors are locked…$"
    .endif
    .ifdef SPANISH
    .string "Las puertas del GIMNASIO están\n"
    .string "cerradas...$"
    .endif

