@ The 5 texts below are supposed to be in FourIsland_House1
Text_BodySlamTeach::
    .ifdef ENGLISH
    .string "Ready?\n"
    .string "Boing!\p"
    .string "We're having a BODY SLAM match\n"
    .string "to see who wimps out first.\p"
    .string "If you were to join us, you'd be\n"
    .string "squashed like a bug, though…\p"
    .string "How about I teach BODY SLAM to\n"
    .string "a POKéMON of yours instead?$"
    .endif
    .ifdef SPANISH
    .string "¿Ya?\n"
    .string "¡Toma!\p"
    .string "Estamos usando GOLPE CUERPO para\n"
    .string "ver quién machaca antes a quién.\p"
    .string "Si te metieras en la pelea, no\n"
    .string "tendrías nada que hacer...\p"
    .string "¿Quieres que le enseñe GOLPE\n"
    .string "CUERPO a alguno de tus POKéMON?$"
    .endif

Text_BodySlamDeclined::
    .ifdef ENGLISH
    .string "Come again!\n"
    .string "Boing!$"
    .endif
    .ifdef SPANISH
    .string "¡Venga, otra vez!\n"
    .string "¡Toma!$"
    .endif

Text_BodySlamWhichMon::
    .ifdef ENGLISH
    .string "Which POKéMON wants to learn how\n"
    .string "to BODY SLAM?$"
    .endif
    .ifdef SPANISH
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe GOLPE CUERPO?$"
    .endif

Text_BodySlamTaught::
    .ifdef ENGLISH
    .string "Boioing!$"
    .endif
    .ifdef SPANISH
    .string "¡Uauuu!$"
    .endif

FourIsland_House1_Text_FatMan::
    .string "それ　ぼよーん！\n"
    .string "おまえ　おもいなあー！$"

FourIsland_PokemonCenter_1F_Text_RareIceMonsInCave::
    .ifdef ENGLISH
    .string "There's a rare kind of ICE POKéMON\n"
    .string "that lives in the cave.\p"
    .string "We get a lot of visitors hoping to\n"
    .string "see that POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "En la CUEVA GLACIADA hay un\n"
    .string "POKéMON raro del tipo HIELO.\p"
    .string "Aquí viene mucha gente para\n"
    .string "verlo.$"
    .endif

FourIsland_PokemonCenter_1F_Text_DayCarePeopleFoundEggBefore::
    .ifdef ENGLISH
    .string "Oh? A POKéMON EGG?\n"
    .string "…I have no idea.\p"
    .string "…Oh, wait. The DAY-CARE people\n"
    .string "in town were saying something.\p"
    .string "They said that they'd found EGGS\n"
    .string "before on their property.$"
    .endif
    .ifdef SPANISH
    .string "¿Cómo? ¿Un HUEVO POKéMON?\n"
    .string "Ni idea...\p"
    .string "Eh..., sí, espera, los ENCARGADOS\n"
    .string "de la GUARDERÍA comentaron algo\l"
    .string "sobre eso.\p"
    .string "Dijeron que habían encontrado\n"
    .string "HUEVOS en la propia GUARDERÍA.$"
    .endif

FourIsland_PokemonCenter_1F_Text_NewPokemonJournalHasntArrived::
    .ifdef ENGLISH
    .string "What's this?\p"
    .string "The new POKéMON JOURNAL hasn't\n"
    .string "arrived on this island?$"
    .endif
    .ifdef SPANISH
    .string "¡Pero bueno!\p"
    .string "¿Que aún no ha llegado el nuevo\n"
    .string "DIARIO POKéMON a esta isla?$"
    .endif

