CeruleanCity_House4_Text_NothingEntertaining::
    .ifdef ENGLISH
    .string "Sigh…\n"
    .string "Too much time, too little to do…\p"
    .string "Is nothing entertaining happening\n"
    .string "anywhere?$"
    .endif
    .ifdef SPANISH
    .string "Uff... Tengo tanto tiempo\n"
    .string "y tan poco que hacer...\p"
    .string "¿No hay nada divertido cociéndose\n"
    .string "por ahí?$"
    .endif

CeruleanCity_House4_Text_NewNewsInformativeHaveThis::
    .ifdef ENGLISH
    .string "Ah!\n"
    .string "A new news report!\p"
    .string "Hmm…\p"
    .string "I see!\n"
    .string "That was quite informative!\p"
    .string "I applaud you for taking interest\n"
    .string "in the news at your young age.\p"
    .string "As my thanks for sharing the news\n"
    .string "with me, I want you to have this.$"
    .endif
    .ifdef SPANISH
    .string "¡Anda, hay novedades!\n"
    .string "¡Un boletín informativo!\p"
    .string "A ver, a ver...\p"
    .string "¡Interesante!\n"
    .string "¡Interesantísimo!\p"
    .string "Muy bien, me encanta que la gente\n"
    .string "joven como tú se interese por las\l"
    .string "noticias.\p"
    .string "Quiero agradecerte el haberme\n"
    .string "traído estas noticias, toma.$"
    .endif

CeruleanCity_House4_Text_IncredibleNewsHaveBerries::
    .ifdef ENGLISH
    .string "Oh, oh!\n"
    .string "Th-this news report!\p"
    .string "Hmm…\p"
    .string "Amazing!\n"
    .string "What an incredible piece of news!\p"
    .string "I haven't seen a news story this\n"
    .string "incredible in too long a time!\p"
    .string "Thanks for sharing this fantastic\n"
    .string "news. Have a bunch of BERRIES!$"
    .endif
    .ifdef SPANISH
    .string "¡Por fin!\n"
    .string "¡Un boletín informativo!\p"
    .string "A ver, a ver...\p"
    .string "¡Maravilloso!\n"
    .string "¡Maravillosísimo!\p"
    .string "Hacía tiempo que no leía nada\n"
    .string "igual.\p"
    .string "Gracias por traerme semejantes\n"
    .string "noticias, toma, unas BAYITAS.$"
    .endif

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers::
    .ifdef ENGLISH
    .string "It seems such a shame to not share\n"
    .string "this news with other folks…\p"
    .string "I wish I could tell someone…\n"
    .string "Let others know the news…$"
    .endif
    .ifdef SPANISH
    .string "Sería una pena no compartir estas\n"
    .string "noticias...\p"
    .string "Me encantaría poder pasárselas\n"
    .string "a alguien...\l"
    .string "Compártelas con más gente...$"
    .endif

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis::
    .ifdef ENGLISH
    .string "Ah, you've spread the news for me?\p"
    .string "Good news becomes worthwhile when\n"
    .string "all sorts of people share it.\p"
    .string "As my thanks for your spreading\n"
    .string "the news, take this!$"
    .endif
    .ifdef SPANISH
    .string "¿Has pasado las noticias\n"
    .string "a más gente?\p"
    .string "¡Las buenas noticias hay que\n"
    .string "compartirlas con quien se pueda!\p"
    .string "Gracias por pasárselas a otras\n"
    .string "personas, toma, anda.$"
    .endif

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries::
    .ifdef ENGLISH
    .string "You've spread the news some more?\n"
    .string "Magnificent!\p"
    .string "That piece of news must be\n"
    .string "delighted to be passed around so.\p"
    .string "Yes, indeed!\p"
    .string "Consider this a show of\n"
    .string "appreciation from me and the news.\p"
    .string "I'll give you more BERRIES than\n"
    .string "I usually do.$"
    .endif
    .ifdef SPANISH
    .string "¿Has pasado las noticias\n"
    .string "a más gente todavía?\p"
    .string "¡Las propias noticias deben\n"
    .string "de estar encantadas de la vida!\p"
    .string "¡Lo que yo te diga!\p"
    .string "¡En mi nombre y en nombre\n"
    .string "de las propias noticias, toma!\p"
    .string "¡Voy a darte más BAYITAS\n"
    .string "que de costumbre!$"
    .endif

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews::
    .ifdef ENGLISH
    .string "I'm quite enjoying myself with all\n"
    .string "sorts of news.\p"
    .string "Yes, I am satisfied!\n"
    .string "I won't be bored for a while.$"
    .endif
    .ifdef SPANISH
    .string "Yo me lo paso pipa leyendo\n"
    .string "noticias. Todas me gustan, todas.\p"
    .string "¡Ya estoy contento! ¡Voy a estar\n"
    .string "entretenido para rato!$"
    .endif

CeruleanCity_House4_Text_YourBerryPouchIsFull::
    .ifdef ENGLISH
    .string "Hm? Your BERRY POUCH is full.\n"
    .string "My gift remains ungiven, then.$"
    .endif
    .ifdef SPANISH
    .string "Vaya, tienes el SACO de las BAYAS\n"
    .string "hasta arriba. Vuelve a por ellas\l"
    .string "cuando tengas sitio.$"
    .endif

