ThreeIsland_House3_Text_WantedToLiveSomewhereQuiet::
    .ifdef ENGLISH
    .string "I bought this house because I\n"
    .string "wanted to live somewhere quiet.\p"
    .string "Today, I think I'll go out fishing.$"
    .endif
    .ifdef SPANISH
    .string "Me compré esta casa porque\n"
    .string "quería vivir en un sitio tranquilo.\p"
    .string "Hoy, creo que voy a ir a pescar.$"
    .endif

