PokemonLeague_AgathasRoom_Text_Intro::
    .ifdef ENGLISH
    .string "I am AGATHA of the ELITE FOUR.\p"
    .string "I hear OAK's taken a lot of\n"
    .string "interest in you, child.\p"
    .string "That old duff was once tough and\n"
    .string "handsome.\p"
    .string "But that was decades ago.\n"
    .string "He's a shadow of his former self.\p"
    .string "Now he just wants to fiddle with\n"
    .string "his POKéDEX.\p"
    .string "He's wrong.\n"
    .string "POKéMON are for battling!\p"
    .string "{PLAYER}! I'll show you how a real\n"
    .string "TRAINER battles!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif
    .ifdef SPANISH
    .string "¡Yo soy AGATHA, del ALTO MANDO!\p"
    .string "He oído que OAK te tiene\n"
    .string "mucha admiración, criatura.\p"
    .string "Ese carcamal era fuerte y guapote,\n"
    .string "pero ya hace mucho de eso.\p"
    .string "Han pasado muchos años, sí.\n"
    .string "Es la sombra de lo que fue.\p"
    .string "¡Ahora sólo juguetea con su\n"
    .string "POKéDEX! ¡Pero está equivocado!\l"
    .string "¡Los POKéMON son para luchar!\p"
    .string "¡{PLAYER}! ¡Yo te enseñaré cómo\n"
    .string "lucha un gran ENTRENADOR!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif

PokemonLeague_AgathasRoom_Text_RematchIntro::
    .ifdef ENGLISH
    .string "I am AGATHA of the ELITE FOUR.\p"
    .string "You're the child that OAK's taken\n"
    .string "under his wing, aren't you?\p"
    .string "That old duff was once tough and\n"
    .string "handsome.\p"
    .string "But that was decades ago.\n"
    .string "He's a shadow of his former self.\p"
    .string "Now he just wants to fiddle with\n"
    .string "his POKéDEX.\p"
    .string "He's wrong.\n"
    .string "POKéMON are for battling!\p"
    .string "{PLAYER}! I'll show you how a real\n"
    .string "TRAINER battles!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif
    .ifdef SPANISH
    .string "¡Yo soy AGATHA, del ALTO MANDO!\p"
    .string "He oído que eres el ojito derecho\n"
    .string "de OAK, ¿eh?\p"
    .string "Ese carcamal era fuerte y guapote,\n"
    .string "pero ya hace mucho de eso.\p"
    .string "Han pasado muchos años, sí.\n"
    .string "Es la sombra de lo que fue.\p"
    .string "¡Ahora sólo juguetea con su\n"
    .string "POKéDEX! ¡Pero está equivocado!\l"
    .string "¡Los POKéMON son para luchar!\p"
    .string "¡{PLAYER}! ¡Yo te enseñaré cómo\n"
    .string "lucha un gran ENTRENADOR!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif

PokemonLeague_AgathasRoom_Text_Defeat::
    .ifdef ENGLISH
    .string "Oh, my!\n"
    .string "You're something special, child!$"
    .endif
    .ifdef SPANISH
    .string "¡Oh, oh!\n¡Eres bastante especial!$"
    .endif

PokemonLeague_AgathasRoom_Text_PostBattle::
    .ifdef ENGLISH
    .string "You win!\p"
    .string "I see what the old duff sees in\n"
    .string "you now.\p"
    .string "I have nothing else to say.\n"
    .string "Run along now, child!$"
    .endif
    .ifdef SPANISH
    .string "¡Tú ganas!\p"
    .string "¡Ya sé por qué ese viejo\n"
    .string "inútil te aprecia tanto!\p"
    .string "¡No tengo nada más que decir!\n"
    .string "¡Vete ya!$"
    .endif

