VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon::
    .ifdef ENGLISH
	.string "Hi!\n"
	.string "Do you have a {STR_VAR_1}?\p"
	.string "Want to trade it for my\n"
	.string "{STR_VAR_2}?$"
    .endif
    .ifdef SPANISH
    .string "¡Hola! ¿Tienes un {STR_VAR_1}?\p"
    .string "¿Quieres cambiarlo por\n"
    .string "mi {STR_VAR_2}?$"
    .endif

VermilionCity_House2_Text_ThatsTooBad::
    .ifdef ENGLISH
	.string "That's too bad.$"
    .endif
    .ifdef SPANISH
    .string "¡Qué pena!$"
    .endif

VermilionCity_House2_Text_ThisIsNoMon::
    .ifdef ENGLISH
	.string "…This is no {STR_VAR_1}.\p"
	.string "If you get one, please trade it\n"
	.string "to me!$"
    .endif
    .ifdef SPANISH
    .string "Éste no es un {STR_VAR_1}.\p"
    .string "¡Si consigues uno, cámbiamelo!$"
    .endif

VermilionCity_House2_Text_ThankYou::
    .ifdef ENGLISH
	.string "Thank you!$"
    .endif
    .ifdef SPANISH
    .string "¡Gracias!$"
    .endif

VermilionCity_House2_Text_HowIsMyOldMon::
    .ifdef ENGLISH
	.string "How is my old {STR_VAR_2}?\p"
	.string "My {STR_VAR_1} is doing great!$"
    .endif
    .ifdef SPANISH
    .string "¿Cómo está mi viejo {STR_VAR_2}?\p"
    .string "¡Mi {STR_VAR_1} está fenomenal!$"
    .endif
