VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon::
	.string "Salut!\n"
	.string "T'as un {STR_VAR_1}?\p"
	.string "Contre un joli {STR_VAR_2}, OK?$"

VermilionCity_House2_Text_ThatsTooBad::
	.string "Dommage.$"

VermilionCity_House2_Text_ThisIsNoMon::
	.string "… C'est pas un {STR_VAR_1}.\p"
	.string "Reviens me voir avec un vrai!$"

VermilionCity_House2_Text_ThankYou::
	.string "Merci beaucoup!$"

VermilionCity_House2_Text_HowIsMyOldMon::
	.string "Il va bien mon vieux\n"
	.string "{STR_VAR_2}?\p"
	.string "Mon {STR_VAR_1} a trop la pêche!$"

