CeladonCity_Text_GotMyKoffingInCinnabar::
    .ifdef ENGLISH
    .string "I got my KOFFING in CINNABAR.\p"
    .string "It's usually nice, but it breathes\n"
    .string "poison when it's angry.$"
    .endif
    .ifdef SPANISH
    .string "¡Conseguí a mi KOFFING en\n"
    .string "CIUDAD CANELA!\p"
    .string "¡Es muy simpático, pero echa\n"
    .string "veneno cuando se enfada!$"
    .endif

CeladonCity_Text_GymIsGreatFullOfWomen::
    .ifdef ENGLISH
    .string "Heheh! This GYM is great!\n"
    .string "It's full of women!$"
    .endif
    .ifdef SPANISH
    .string "¡Jeje! ¡Este GIMNASIO es genial!\n"
    .string "¡Está lleno de chicas!$"
    .endif

CeladonCity_Text_GameCornerIsBadForCitysImage::
    .ifdef ENGLISH
    .string "CELADON takes pride in its efforts\n"
    .string "to keep the city beautiful.\p"
    .string "That's why the new GAME CORNER is\n"
    .string "bad for our city's image.$"
    .endif
    .ifdef SPANISH
    .string "AZULONA presume de estar bonita\n"
    .string "y cuidada.\p"
    .string "¡El CASINO no es bueno para la\n"
    .string "imagen de nuestra ciudad!$"
    .endif

CeladonCity_Text_BlewItAllAtSlots::
    .ifdef ENGLISH
    .string "Moan…\n"
    .string "I blew it all at the slots!\p"
    .string "I knew I should have cashed in my\n"
    .string "COINS for prizes!$"
    .endif
    .ifdef SPANISH
    .string "¡Ayyy! ¡Lo he perdido todo\n"
    .string "en las tragaperras!\p"
    .string "¡Debería haber cambiado todas\n"
    .string "mis fichas por premios!$"
    .endif

CeladonCity_Text_MyTrustedPalPoliwrath::
    .ifdef ENGLISH
    .string "This is my trusted pal, POLIWRATH.\p"
    .string "It evolved from a POLIWHIRL when\n"
    .string "I used a WATER STONE.$"
    .endif
    .ifdef SPANISH
    .string "¡Éste es mi fiel compañero,\n"
    .string "POLIWRATH!\p"
    .string "¡Evolucionó del POLIWHIRL al usar\n"
    .string "la PIEDRA AGUA!$"
    .endif

CeladonCity_Text_Poliwrath::
    .ifdef ENGLISH
    .string "POLIWRATH: Ribi ribit!$"
    .endif
    .ifdef SPANISH
    .string "POLIWRATH: ¡Poli, poli!$"
    .endif

CeladonCity_Text_GetLostOrIllPunchYou::
    .ifdef ENGLISH
    .string "What are you staring at?\n"
    .string "Get lost, or I'll punch you.$"
    .endif
    .ifdef SPANISH
    .string "¿Qué estás mirando?$"
    .endif

CeladonCity_Text_KeepOutOfTeamRocketsWay::
    .ifdef ENGLISH
    .string "Keep out of TEAM ROCKET's way!$"
    .endif
    .ifdef SPANISH
    .string "¡No te cruces en el camino del\n"
    .string "TEAM ROCKET!$"
    .endif

CeladonCity_Text_ExplainXAccuracyDireHit::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "X ACCURACY boosts the accuracy of\n"
    .string "techniques.\p"
    .string "DIRE HIT jacks up the likelihood\n"
    .string "of critical hits.\p"
    .string "Get your items at the CELADON\n"
    .string "DEPT. STORE!$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "¡PRECISIÓN X aumenta la precisión\n"
    .string "de los ataques!\p"
    .string "¡El DIRECTO aumenta la posibilidad\n"
    .string "de golpes críticos!\p"
    .string "¡Compra tus objetos en el\n"
    .string "CENTRO COMERCIAL de AZULONA!$"
    .endif

CeladonCity_Text_CitySign::
    .ifdef ENGLISH
    .string "CELADON CITY\n"
    .string "The City of Rainbow Dreams$"
    .endif
    .ifdef SPANISH
    .string "CIUDAD AZULONA\n"
    .string "La ciudad de los sueños de\l"
    .string "arco iris.$"
    .endif

CeladonCity_Text_GymSign::
    .ifdef ENGLISH
    .string "CELADON CITY POKéMON GYM\n"
    .string "LEADER: ERIKA\l"
    .string "The Nature-Loving Princess!$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de AZULONA: ERIKA\l"
    .string "¡Princesa amante de la Naturaleza!$"
    .endif

CeladonCity_Text_MansionSign::
    .ifdef ENGLISH
    .string "CELADON MANSION$"
    .endif
    .ifdef SPANISH
    .string "MANSIÓN AZULONA$"
    .endif

CeladonCity_Text_DeptStoreSign::
    .ifdef ENGLISH
    .string "Find what you need at the\n"
    .string "CELADON DEPT. STORE!$"
    .endif
    .ifdef SPANISH
    .string "¡Compra lo que necesites en el\n"
    .string "CENTRO COMERCIAL de AZULONA!$"
    .endif

CeladonCity_Text_GuardSpecProtectsFromStatus::
    .ifdef ENGLISH
    .string "TRAINER TIPS\p"
    .string "GUARD SPEC. protects POKéMON\n"
    .string "from status-reduction moves during\l"
    .string "battle.\p"
    .string "Get your items at the\n"
    .string "CELADON DEPT. STORE!$"
    .endif
    .ifdef SPANISH
    .string "PISTAS ENTRENADOR\p"
    .string "¡PROTECCIÓN ESP. protege a tus\n"
    .string "POKéMON de ataques como el agua y\l"
    .string "el fuego!\p"
    .string "¡Compra tus objetos en el CENTRO\n"
    .string "COMERCIAL de AZULONA!$"
    .endif

CeladonCity_Text_PrizeExchangeSign::
    .ifdef ENGLISH
    .string "COINS exchanged for prizes!\n"
    .string "PRIZE EXCHANGE$"
    .endif
    .ifdef SPANISH
    .string "CAMBIO DE PREMIOS\n"
    .string "¡Se cambian fichas por premios!$"
    .endif

CeladonCity_Text_GameCornerSign::
    .ifdef ENGLISH
    .string "ROCKET GAME CORNER\n"
    .string "The playground for grown-ups!$"
    .endif
    .ifdef SPANISH
    .string "CASINO ROCKET\n"
    .string "¡El parque de los adultos!$"
    .endif

CeladonCity_Text_ScaldedTongueOnTea::
    .ifdef ENGLISH
    .string "Aaaagh, ow…\n"
    .string "I scalded my tongue!\p"
    .string "This nice old lady in the MANSION\n"
    .string "gave me some TEA.\p"
    .string "But it was boiling hot!\n"
    .string "Gotta cool it to drink it.$"
    .endif
    .ifdef SPANISH
    .string "¡Aaaagh, ayyyy...!\n"
    .string "¡Me he achicharrado la lengua!\p"
    .string "La ancianita tan agradable que hay\n"
    .string "en la MANSIÓN, me ha dado un TÉ.\p"
    .string "¡Pero está hirviendo!\n"
    .string "Voy a esperar a ver si se enfría...$"
    .endif

Text_SoftboiledTeach::
    .ifdef ENGLISH
    .string "Hello, there!\p"
    .string "I've seen you about, but I never\n"
    .string "had a chance to chat.\p"
    .string "It must be good luck that brought\n"
    .string "us together finally.\p"
    .string "I'd like to celebrate by teaching\n"
    .string "you the move SOFTBOILED.$"
    .endif
    .ifdef SPANISH
    .string "¡Hola!\p"
    .string "¡Te había visto, pero nunca había\n"
    .string "podido hablar contigo!\p"
    .string "Yo creo que ha sido la suerte\n"
    .string "la que nos ha vuelto a reunir.\p"
    .string "Para celebrarlo, me gustaría\n"
    .string "enseñarte AMORTIGUADOR.$"
    .endif

Text_SoftboiledDeclined::
    .ifdef ENGLISH
    .string "I'll always be keeping an eye out\n"
    .string "for you.\p"
    .string "I hope we can chat again.$"
    .endif
    .ifdef SPANISH
    .string "Bueno, aquí me tienes para cuando\n"
    .string "te haga falta.$"
    .endif

Text_SoftboiledWhichMon::
    .ifdef ENGLISH
    .string "So, who's the POKéMON that gets\n"
    .string "the chance to learn SOFTBOILED?$"
    .endif
    .ifdef SPANISH
    .string "¿A qué POKéMON quieres que\n"
    .string "le enseñe AMORTIGUADOR?$"
    .endif

Text_SoftboiledTaught::
    .ifdef ENGLISH
    .string "I wish you the best of luck!$"
    .endif
    .ifdef SPANISH
    .string "¡Que te vaya muy bien!$"
    .endif

CeladonCity_Text_SomeoneStoleSilphScope::
    .ifdef ENGLISH
    .string "Oh, what am I to do…\p"
    .string "Someone stole our SILPH SCOPE.\p"
    .string "The thief came running this way,\n"
    .string "I'm sure of it.\p"
    .string "But I lost sight of him!\n"
    .string "Where'd he go?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué voy a hacer ahora?...\p"
    .string "¡Nos han robado el SILPH SCOPE!\p"
    .string "Quien haya sido, vino por aquí.\n"
    .string "De eso no me cabe duda.\p"
    .string "¡Pero no sé por dónde se fue!\n"
    .string "¡No tengo ni idea!$"
    .endif

