ViridianCity_Mart_Text_YouCameFromPallet::
    .ifdef ENGLISH
    .string "Hey!\n"
    .string "You came from PALLET TOWN?$"
    .endif
    .ifdef SPANISH
    .string "¡Oye!\n"
    .string "¿Vienes de PUEBLO PALETA?$"
    .endif

ViridianCity_Mart_Text_TakeThisToProfOak::
    .ifdef ENGLISH
    .string "You know PROF. OAK, right?\p"
    .string "His order came in.\n"
    .string "Can I get you to take it to him?$"
    .endif
    .ifdef SPANISH
    .string "¿Conoces al PROFESOR OAK?\p"
    .string "Tiene correo.\n"
    .string "¿Se lo puedes llevar?$"
    .endif

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .ifdef ENGLISH
    .string "{PLAYER} received OAK'S PARCEL\n"
    .string "from the POKéMON MART clerk.$"
    .endif
    .ifdef SPANISH
    .string "¡El empleado de la TIENDA PKMN le\n"
    .string "dio a {PLAYER} el CORREO de OAK!$"
    .endif

ViridianCity_Mart_Text_SayHiToOakForMe::
    .ifdef ENGLISH
    .string "Okay, thanks! Please say hi to\n"
    .string "PROF. OAK for me, too.$"
    .endif
    .ifdef SPANISH
    .string "¡Bueno, gracias!\n"
    .string "¡Saluda al PROF. OAK de mi parte!$"
    .endif

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .ifdef ENGLISH
    .string "This shop does good business in\n"
    .string "ANTIDOTES, I've heard.$"
    .endif
    .ifdef SPANISH
    .string "En esta tienda venden muchos\n"
    .string "ANTÍDOTOS, creo.$"
    .endif

ViridianCity_Mart_Text_GotToBuySomePotions::
    .ifdef ENGLISH
    .string "I've got to buy some POTIONS.\p"
    .string "You never know when your POKéMON\n"
    .string "will need quick healing.$"
    .endif
    .ifdef SPANISH
    .string "Yo tengo algunas POCIONES.\p"
    .string "Nunca sabes cuándo pueden\n"
    .string "necesitarlas tus POKéMON.$"
    .endif

