ViridianCity_Mart_Text_YouCameFromPallet::
    .string "¡Oye!\n"
    .string "¿Vienes de PUEBLO PALETA?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "¿Conoces al PROFESOR OAK?\p"
    .string "Tiene correo.\n"
    .string "¿Se lo puedes llevar?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "¡El empleado de la TIENDA PKMN le\n"
    .string "dio a {PLAYER} el CORREO de OAK!$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "¡Bueno, gracias!\n"
    .string "¡Saluda al PROF. OAK de mi parte!$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "En esta tienda venden muchos\n"
    .string "ANTÍDOTOS, creo.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "Yo tengo algunas POCIONES.\p"
    .string "Nunca sabes cuándo pueden\n"
    .string "necesitarlas tus POKéMON.$"
