VermilionCity_Gym_Text_LtSurgeIntro::
    .ifdef ENGLISH
    .string "Hey, kid! What do you think you're\n"
    .string "doing here?\p"
    .string "You won't live long in combat!\n"
    .string "Not with your puny power!\p"
    .string "I tell you, kid, electric POKéMON\n"
    .string "saved me during the war!\p"
    .string "They zapped my enemies into\n"
    .string "paralysis!\p"
    .string "The same as I'll do to you!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif
    .ifdef SPANISH
    .string "¡Oye!\n"
    .string "¿Pero qué haces?\p"
    .string "¡No resistirás mucho luchando!\n"
    .string "¡Seguro!\p"
    .string "¡Los POKéMON ELÉCTRICOS\n"
    .string "me salvaron en combate!\p"
    .string "¡Paralizaron a mis enemigos!\p"
    .string "¡Y eso mismo voy a hacer yo\n"
    .string "contigo!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"
    .endif

VermilionCity_Gym_Text_LtSurgePostBattle::
    .ifdef ENGLISH
    .string "A little word of advice, kid!\p"
    .string "Electricity is sure powerful!\p"
    .string "But, it's useless against GROUND-\n"
    .string "type POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Te daré un pequeño consejo!\p"
    .string "¡La electricidad es muy potente!\p"
    .string "¡Pero no afecta a los POKéMON\n"
    .string "del tipo TIERRA!$"
    .endif

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
    .ifdef ENGLISH
    .string "The THUNDERBADGE cranks up your\n"
    .string "POKéMON's SPEED!\p"
    .string "It also lets your POKéMON FLY\n"
    .string "lightning-quick anytime, kid!\p"
    .string "You're special, kid!\n"
    .string "Take this!$"
    .endif
    .ifdef SPANISH
    .string "¡La MEDALLA TRUENO aumenta la\n"
    .string "VELOCIDAD de tus POKéMON!\p"
    .string "¡Y permite volar a tus POKéMON\n"
    .string "cuando quieran!\p"
    .string "¡Tú eres muy especial!\n"
    .string "¡Toma esto!$"
    .endif

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
    .ifdef ENGLISH
    .string "{PLAYER} received TM34\n"
    .string "from LT. SURGE.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} recibió la MT34\n"
    .string "de manos de LT. SURGE!$"
    .endif

VermilionCity_Gym_Text_ExplainTM34::
    .ifdef ENGLISH
    .string "TM34 contains SHOCK WAVE!\p"
    .string "Teach it to an ELECTRIC POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡MT34 contiene ONDA VOLTIO!\p"
    .string "¡Enséñaselo a un POKéMON\n"
    .string "eléctrico!$"
    .endif

VermilionCity_Gym_Text_MakeRoomInYourBag::
    .ifdef ENGLISH
    .string "Yo, kid, make room in your BAG!$"
    .endif
    .ifdef SPANISH
    .string "¡Más vale que le hagas sitio!$"
    .endif

VermilionCity_Gym_Text_LtSurgeDefeat::
    .ifdef ENGLISH
    .string "Now that's a shocker!\p"
    .string "You're the real deal, kid!\p"
    .string "Fine, then, take the THUNDERBADGE!$"
    .endif
    .ifdef SPANISH
    .string "¡Guau!\p"
    .string "¡Tú sí que eres fuerte!\p"
    .string "¡Anda, toma la MEDALLA TRUENO!$"
    .endif

VermilionCity_Gym_Text_TuckerIntro::
    .ifdef ENGLISH
    .string "When I was in the Army, LT. SURGE\n"
    .string "was my strict CO.\p"
    .string "He was a hard taskmaster.$"
    .endif
    .ifdef SPANISH
    .string "¡Cuando estaba en el ejército,\n"
    .string "el LT. SURGE era muy estricto!$"
    .endif

VermilionCity_Gym_Text_TuckerDefeat::
    .ifdef ENGLISH
    .string "Stop!\n"
    .string "You're very good!$"
    .endif
    .ifdef SPANISH
    .string "¡Alto!\n"
    .string "¡Eres genial!$"
    .endif

VermilionCity_Gym_Text_TuckerPostBattle::
    .ifdef ENGLISH
    .string "It's not easy opening that door.\p"
    .string "LT. SURGE was always famous for\n"
    .string "his cautious nature in the Army.$"
    .endif
    .ifdef SPANISH
    .string "No es fácil abrir esta puerta...\p"
    .string "¡El LT. SURGE siempre fue muy\n"
    .string "cauteloso en el ejército!$"
    .endif

VermilionCity_Gym_Text_BailyIntro::
    .ifdef ENGLISH
    .string "I'm a lightweight, but I'm good\n"
    .string "with electricity!\p"
    .string "That's why I joined this GYM.$"
    .endif
    .ifdef SPANISH
    .string "¡No es que yo sea muy fuerte,\n"
    .string "pero soy muy bueno con la\l"
    .string "electricidad!$"
    .endif

VermilionCity_Gym_Text_BailyDefeat::
    .ifdef ENGLISH
    .string "Fried!$"
    .endif
    .ifdef SPANISH
    .string "¡Qué paliza!$"
    .endif

VermilionCity_Gym_Text_BailyPostBattle::
    .ifdef ENGLISH
    .string "Okay, I'll talk!\p"
    .string "LT. SURGE said he hid door\n"
    .string "switches inside something.$"
    .endif
    .ifdef SPANISH
    .string "¡Vale, hablaré!\p"
    .string "¡LT. SURGE dijo que ocultaría los\n"
    .string "botones de la puerta dentro de\l"
    .string "algo!$"
    .endif

VermilionCity_Gym_Text_DwayneIntro::
    .ifdef ENGLISH
    .string "This is no place for kids!\n"
    .string "Not even if you're good!$"
    .endif
    .ifdef SPANISH
    .string "¡Este lugar no es para niños!\n"
    .string "¡Por muy fuerte que seas!$"
    .endif

VermilionCity_Gym_Text_DwayneDefeat::
    .ifdef ENGLISH
    .string "Wow!\n"
    .string "Surprised me!$"
    .endif
    .ifdef SPANISH
    .string "¡Uuuaa!\n"
    .string "¡Me dejas a cuadros!$"
    .endif

VermilionCity_Gym_Text_DwaynePostBattle::
    .ifdef ENGLISH
    .string "LT. SURGE installed the traps in\n"
    .string "the GYM himself.\p"
    .string "He set up double locks everywhere.\n"
    .string "Let me give you a hint.\p"
    .string "When you open the first lock, the\n"
    .string "second lock is right next to it.$"
    .endif
    .ifdef SPANISH
    .string "LT. SURGE colocó cerraduras\n"
    .string "dobles en el GIMNASIO.\p"
    .string "¡Las puso por todos sitios!\n"
    .string "¡Te daré una pista!\p"
    .string "¡Tras abrir la 1.ª cerradura, la\n"
    .string "2.ª está al lado!$"
    .endif

VermilionCity_Gym_Text_GymGuyAdvice::
    .ifdef ENGLISH
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "LT. SURGE has a nickname.\p"
    .string "People refer to him as the\n"
    .string "Lightning American!\p"
    .string "He's an expert on electric\n"
    .string "POKéMON.\p"
    .string "BIRD/WATER-type POKéMON match\n"
    .string "poorly against the ELECTRIC type.\p"
    .string "Beware of paralysis, too.\p"
    .string "LT. SURGE is very cautious.\p"
    .string "He's locked himself in, so it won't\n"
    .string "be easy getting to him.$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, aspirante al título!\p"
    .string "El LT. SURGE tiene un mote. La\n"
    .string "gente le llama: ¡Rayo americano!\p"
    .string "¡Es un experto en POKéMON\n"
    .string "eléctricos!\p"
    .string "¡Los POKéMON voladores y los\n"
    .string "acuáticos están en peligro! ¡Ten\l"
    .string "cuidado con la parálisis!\p"
    .string "¡El LT. SURGE es muy cuidadoso!\p"
    .string "¡Descifra un código y llegarás a\n"
    .string "él!$"
    .endif

VermilionCity_Gym_Text_GymGuyPostVictory::
    .ifdef ENGLISH
    .string "Whew!\n"
    .string "That match was electric!$"
    .endif
    .ifdef SPANISH
    .string "¡Uau!\n"
    .string "¡Vaya pelea tan eléctrica!$"
    .endif

VermilionCity_Gym_Text_GymStatue::
    .ifdef ENGLISH
    .string "VERMILION POKéMON GYM\n"
    .string "LEADER: LT. SURGE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CARMÍN: LT. SURGE\p"
    .string "ENTRENADOR GANADOR:\n"
    .string "{RIVAL}$"
    .endif

VermilionCity_Gym_Text_GymStatuePlayerWon::
    .ifdef ENGLISH
    .string "VERMILION POKéMON GYM\n"
    .string "LEADER: LT. SURGE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"
    .endif
    .ifdef SPANISH
    .string "LÍDER del GIMNASIO POKéMON\n"
    .string "de CARMÍN: LT. SURGE\p"
    .string "ENTRENADORES GANADORES:\n"
    .string "{RIVAL} y {PLAYER}$"
    .endif

VermilionCity_Gym_Text_NopeOnlyTrashHere::
    .ifdef ENGLISH
    .string "Nope!\n"
    .string "There's only trash here.$"
    .endif
    .ifdef SPANISH
    .string "¡No, aquí sólo hay basura!$"
    .endif

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
    .ifdef ENGLISH
    .string "Hey! There's a switch under the\n"
    .string "trash! Turn it on!\p"
    .string "The first electric lock opened!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye! ¡Hay un botón debajo de la\n"
    .string "basura!\p"
    .string "¡Púlsalo!\n"
    .string "Abierto primer cierre eléctrico.$"
    .endif

VermilionCity_Gym_Text_AnotherSwitchInTrash::
    .string "ガサゴソ‥！\n"
    .string "おっと！　ゴミばこの　そこに\l"
    .string "また　スイッチが　あった！\l"
    .string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened::
    .ifdef ENGLISH
    .string "The second electric lock opened!\n"
    .string "The motorized door opened!$"
    .endif
    .ifdef SPANISH
    .string "Abierto segundo cierre eléctrico.\p"
    .string "¡Abierta la puerta mecánica!$"
    .endif

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
    .ifdef ENGLISH
    .string "Nope!\n"
    .string "There's only trash here.\p"
    .string "Hey!\n"
    .string "The electric locks were reset!$"
    .endif
    .ifdef SPANISH
    .string "¡No! Aquí sólo hay basura.\p"
    .string "¡Las cerraduras eléctricas fueron\n"
    .string "reajustadas!$"
    .endif

