VermilionCity_Gym_Text_LtSurgeIntro::
    .string "Ehi, tu!\n"
    .string "Cosa fai qui?\p"
    .string "Non ce la farai a vincere, puoi\n"
    .string "contarci!\p"
    .string "Devi sapere che i POKéMON elettrici\n"
    .string "mi hanno salvato in guerra!\p"
    .string "Hanno paralizzato i miei nemici!\p"
    .string "Proprio quello che succederà a te!{PLAY_BGM MUS_ENCOUNTER_GYM_LEADER}$"

VermilionCity_Gym_Text_LtSurgePostBattle::
    .string "Voglio darti un consiglio!\p"
    .string "L'elettricità è potentissima!\p"
    .string "Ma non ha effetto sui POKéMON di\n"
    .string "tipo TERRA!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
    .string "La MEDAGLIA TUONO aumenta la\n"
    .string "VELOCITÀ dei tuoi POKéMON!\p"
    .string "E i tuoi POKéMON potranno volare\n"
    .string "in ogni momento!\p"
    .string "Sei speciale!\n"
    .string "Prendi questo!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
    .string "{PLAYER} riceve\n"
    .string "la MT34!$"

VermilionCity_Gym_Text_ExplainTM34::
    .string "La MT34 contiene ONDASHOCK!\p"
    .string "Insegnala a un POKéMON elettrico!$"

VermilionCity_Gym_Text_MakeRoomInYourBag::
    .string "Fai spazio per questo!$"

VermilionCity_Gym_Text_LtSurgeDefeat::
    .string "Wow!\p"
    .string "Tu sì che sei forte, caspita!\p"
    .string "Bene, prendi la MEDAGLIA TUONO!$"

VermilionCity_Gym_Text_TuckerIntro::
    .string "Quando ero nell'esercito, LT. SURGE\n"
    .string "era molto severo!$"

VermilionCity_Gym_Text_TuckerDefeat::
    .string "Stop!\n"
    .string "Abbi pietà!$"

VermilionCity_Gym_Text_TuckerPostBattle::
    .string "Non riesci a oltrepassare la\n"
    .string "barriera?\p"
    .string "LT. SURGE è sempre stato prudente!$"

VermilionCity_Gym_Text_BailyIntro::
    .string "Sono un peso piuma, ma sono forte\n"
    .string "con l'elettricità!$"

VermilionCity_Gym_Text_BailyDefeat::
    .string "Sono fritto!$"

VermilionCity_Gym_Text_BailyPostBattle::
    .string "Va bene, parlerò!\p"
    .string "LT. SURGE ha nascosto gli\n"
    .string "apriporta dentro qualcosa!$"

VermilionCity_Gym_Text_DwayneIntro::
    .string "Non è posto per bambini questo!$"

VermilionCity_Gym_Text_DwayneDefeat::
    .string "Wow!\n"
    .string "Sei un portento!$"

VermilionCity_Gym_Text_DwaynePostBattle::
    .string "LT. SURGE ha messo doppi\n"
    .string "lucchetti nella PALESTRA.\l"
    .string "Un consiglio…!\p"
    .string "Una volta aperto il 1º, il secondo\n"
    .string "è subito accanto!$"

VermilionCity_Gym_Text_GymGuyAdvice::
    .string "Ehi!\n"
    .string "Aspirante CAMPIONE!\p"
    .string "LT. SURGE ha un soprannome.\p"
    .string "La gente lo chiama l'americano\n"
    .string "illuminato!\p"
    .string "È un esperto di POKéMON elettrici!\p"
    .string "I POKéMON di tipo VOLANTE e\n"
    .string "ACQUA sono a rischio.\p"
    .string "Fai attenzione alle paralisi!\p"
    .string "LT. SURGE è molto prudente!\p"
    .string "Dovrai decifrare un codice per\n"
    .string "arrivare a lui!$"

VermilionCity_Gym_Text_GymGuyPostVictory::
    .string "Wow!\n"
    .string "Una lotta elettrizzante!$"

VermilionCity_Gym_Text_GymStatue::
    .string "CAPOPALESTRA di ARANCIOPOLI:\n"
    .string "LT. SURGE\p"
    .string "ALLENATORI VINCENTI:\n"
    .string "{RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
    .string "CAPOPALESTRA di ARANCIOPOLI:\n"
    .string "LT. SURGE\p"
    .string "ALLENATORI VINCENTI:\n"
    .string "{RIVAL}, {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
    .string "Acqua!\n"
    .string "C'è solo spazzatura qui!$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
    .string "Fuoco! C'è un pulsante sotto il\n"
    .string "bidone! Premilo!\p"
    .string "Primo lucchetto elettrico aperto!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
    .string "ガサゴソ‥！\n"
    .string "おっと！　ゴミばこの　そこに\l"
    .string "また　スイッチが　あった！\l"
    .string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened::
    .string "Secondo lucchetto elettrico\n"
    .string "aperto. Si apre la porta\l"
    .string "automatica!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
    .string "Acqua!\n"
    .string "Qui c'è solo spazzatura.\p"
    .string "Ehi!\n"
    .string "I lucchetti sono stati richiusi!$"

