FuchsiaCity_SafariZone_Entrance_Text_WelcomeToSafariZone::
    .ifdef ENGLISH
    .string "Welcome to the SAFARI ZONE!$"
    .endif
    .ifdef SPANISH
    .string "¡Ésta es la ZONA del SAFARI!$"
    .endif

FuchsiaCity_SafariZone_Entrance_Text_PlaySafariGameFor500::
    .ifdef ENGLISH
    .string "For just ¥500, you can play the\n"
    .string "SAFARI GAME.\p"
    .string "You can roam the wide-open safari\n"
    .string "and catch what you like.\p"
    .string "Would you like to play?$"
    .endif
    .ifdef SPANISH
    .string "¡Por sólo 500¥, podrás atrapar a\n"
    .string "todos los POKéMON que quieras\l"
    .string "en el parque!\p"
    .string "¿Te gustaría probar?$"
    .endif

FuchsiaCity_SafariZone_Entrance_Text_ThatllBe500WeOnlyUseSpecialBalls::
    .ifdef ENGLISH
    .string "That'll be ¥500, please!\p"
    .string "We only use a special kind of \n"
    .string "POKé BALLS here.$"
    .endif
    .ifdef SPANISH
    .string "¡Son 500¥, por favor!\p"
    .string "Aquí sólo usamos un tipo\n"
    .string "concreto de POKé BALL.$"
    .endif

FuchsiaCity_SafariZone_Entrance_Text_PlayerReceived30SafariBalls::
    .ifdef ENGLISH
    .string "{PLAYER} received 30 SAFARI BALLS\n"
    .string "from the attendant.$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER} obtuvo 30 SAFARI BALLS\n"
    .string "del recepcionista!$"
    .endif

FuchsiaCity_SafariZone_Entrance_Text_CallYouOnPAWhenYouRunOut::
    .ifdef ENGLISH
    .string "We'll call you on the PA when you\n"
    .string "run out of time or SAFARI BALLS.\p"
    .string "Well, I'll wish you the best of\n"
    .string "luck!$"
    .endif
    .ifdef SPANISH
    .string "¡Te avisaremos cuando se agoten\n"
    .string "tus SAFARI BALLS o tu tiempo!\p"
    .string "¡Que te vaya muy bien!$"
    .endif

FuchsiaCity_SafariZone_Entrance_Text_OkayPleaseComeAgain::
    .ifdef ENGLISH
    .string "Okay.\n"
    .string "Please come again!$"
    .endif
    .ifdef SPANISH
    .string "¡Bien!\n"
    .string "¡Vuelve cuando quieras!$"
    .endif

FuchsiaCity_SafariZone_Entrance_Text_OopsNotEnoughMoney::
    .ifdef ENGLISH
    .string "Oops!\n"
    .string "Not enough money!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya!\n"
    .string "¡No tienes suficiente dinero!$"
    .endif

FuchsiaCity_SafariZone_Entrance_Text_GoingToLeaveSafariZoneEarly::
    .ifdef ENGLISH
    .string "Are you going to leave the\n"
    .string "SAFARI ZONE early?$"
    .endif
    .ifdef SPANISH
    .string "¿Ya te vas de la ZONA del\n"
    .string "SAFARI?$"
    .endif

FuchsiaCity_SafariZone_Entrance_Text_PleaseReturnSafariBalls::
    .ifdef ENGLISH
    .string "Please return any SAFARI BALLS\n"
    .string "you may have left.$"
    .endif
    .ifdef SPANISH
    .string "Devuelve las SAFARI BALLS\n"
    .string "que te sobren.$"
    .endif

FuchsiaCity_SafariZone_Entrance_Text_GoodLuck::
    .ifdef ENGLISH
    .string "Good luck!$"
    .endif
    .ifdef SPANISH
    .string "¡Buena suerte!$"
    .endif

FuchsiaCity_SafariZone_Entrance_Text_CatchFairShareComeAgain::
    .ifdef ENGLISH
    .string "Did you catch your fair share?\n"
    .string "Come again!$"
    .endif
    .ifdef SPANISH
    .string "¿Te ha ido bien?\n"
    .string "¡Vuelve cuando quieras!$"
    .endif

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone::
    .ifdef ENGLISH
    .string "Hi! Is it your first time here at\n"
    .string "the SAFARI ZONE?$"
    .endif
    .ifdef SPANISH
    .string "¡Hola!\n"
    .string "¿Es tu primera vez aquí?$"
    .endif

FuchsiaCity_SafariZone_Entrance_Text_ExplainSafariZone::
    .ifdef ENGLISH
    .string "The SAFARI ZONE actually has\n"
    .string "four zones in it.\p"
    .string "Each zone has different kinds of\n"
    .string "POKéMON, even some rare ones.\p"
    .string "Use the supplied SAFARI BALLS to\n"
    .string "catch them.\p"
    .string "You can also throw BAIT or ROCKS\n"
    .string "besides the SAFARI BALLS.\p"
    .string "If you throw BAIT, the POKéMON\n"
    .string "becomes less likely to flee, but\l"
    .string "harder to catch.\p"
    .string "If you throw ROCKS, the POKéMON\n"
    .string "becomes more likely to flee, but\l"
    .string "easier to catch.\p"
    .string "When you run out of time or SAFARI\n"
    .string "BALLS, it's game over for you!$"
    .endif
    .ifdef SPANISH
    .string "La ZONA del SAFARI tiene 4 ZONAS.\p"
    .string "Cada zona tiene diferentes tipos de\n"
    .string "POKéMON, y algunos son raros.\p"
    .string "¡Usa las SAFARI BALLS para\n"
    .string "atraparlos!\p"
    .string "¡También podrás usar CEBO\n"
    .string "y ROCAS para atraerlos!\p"
    .string "¡Si tiras CEBO, será difícil que\n"
    .string "escapen, pero te costará más\l"
    .string "atraparlos!\p"
    .string "¡Si tiras ROCAS, será fácil que\n"
    .string "escapen, pero te costará menos\l"
    .string "atraparlos!\p"
    .string "¡Cuando se te acabe el tiempo\n"
    .string "o las SAFARI BALLS, el juego\l"
    .string "se dará por terminado!$"
    .endif

FuchsiaCity_SafariZone_Entrance_Text_SorryYoureARegularHere::
    .ifdef ENGLISH
    .string "Sorry, you're a regular here!$"
    .endif
    .ifdef SPANISH
    .string "¡Oye, tú vienes mucho por aquí!$"
    .endif

