FuchsiaCity_SafariZone_Entrance_Text_WelcomeToSafariZone::
    .string "¡Ésta es la ZONA del SAFARI!$"

FuchsiaCity_SafariZone_Entrance_Text_PlaySafariGameFor500::
    .string "¡Por sólo 500¥, podrás atrapar a\n"
    .string "todos los POKéMON que quieras\l"
    .string "en el parque!\p"
    .string "¿Te gustaría probar?$"

FuchsiaCity_SafariZone_Entrance_Text_ThatllBe500WeOnlyUseSpecialBalls::
    .string "¡Son 500¥, por favor!\p"
    .string "Aquí sólo usamos un tipo\n"
    .string "concreto de POKé BALL.$"

FuchsiaCity_SafariZone_Entrance_Text_PlayerReceived30SafariBalls::
    .string "¡{PLAYER} obtuvo 30 SAFARI BALLS\n"
    .string "del recepcionista!$"

FuchsiaCity_SafariZone_Entrance_Text_CallYouOnPAWhenYouRunOut::
    .string "¡Te avisaremos cuando se agoten\n"
    .string "tus SAFARI BALLS o tu tiempo!\p"
    .string "¡Que te vaya muy bien!$"

FuchsiaCity_SafariZone_Entrance_Text_OkayPleaseComeAgain::
    .string "¡Bien!\n"
    .string "¡Vuelve cuando quieras!$"

FuchsiaCity_SafariZone_Entrance_Text_OopsNotEnoughMoney::
    .string "¡Vaya!\n"
    .string "¡No tienes suficiente dinero!$"

FuchsiaCity_SafariZone_Entrance_Text_GoingToLeaveSafariZoneEarly::
    .string "¿Ya te vas de la ZONA del\n"
    .string "SAFARI?$"

FuchsiaCity_SafariZone_Entrance_Text_PleaseReturnSafariBalls::
    .string "Devuelve las SAFARI BALLS\n"
    .string "que te sobren.$"

FuchsiaCity_SafariZone_Entrance_Text_GoodLuck::
    .string "¡Buena suerte!$"

FuchsiaCity_SafariZone_Entrance_Text_CatchFairShareComeAgain::
    .string "¿Te ha ido bien?\n"
    .string "¡Vuelve cuando quieras!$"

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone::
    .string "¡Hola!\n"
    .string "¿Es tu primera vez aquí?$"

FuchsiaCity_SafariZone_Entrance_Text_ExplainSafariZone::
    .string "La ZONA del SAFARI tiene 4 ZONAS.\p"
    .string "Cada zona tiene diferentes tipos de\n"
    .string "POKéMON, y algunos son raros.\p"
    .string "¡Usa las SAFARI BALLS para\n"
    .string "atraparlos!\p"
    .string "¡También podrás usar CEBO\n"
    .string "y ROCAS para atraerlos!\p"
    .string "¡Si tiras CEBO, será difícil que\n"
    .string "escapen, pero te costará más\l"
    .string "atraparlos!\p"
    .string "¡Si tiras ROCAS, será fácil que\n"
    .string "escapen, pero te costará menos\l"
    .string "atraparlos!\p"
    .string "¡Cuando se te acabe el tiempo\n"
    .string "o las SAFARI BALLS, el juego\l"
    .string "se dará por terminado!$"

FuchsiaCity_SafariZone_Entrance_Text_SorryYoureARegularHere::
    .string "¡Oye, tú vienes mucho por aquí!$"
