Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze::
    .ifdef ENGLISH
    .string "Are you going to VIRIDIAN FOREST?\n"
    .string "It's a natural maze in there.\l"
    .string "Be careful you don't get lost.$"
    .endif
    .ifdef SPANISH
    .string "¿Piensas ir al BOSQUE VERDE?\n"
    .string "¡Ten cuidado!\l"
    .string "¡Es un auténtico laberinto!$"
    .endif

Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite::
    .ifdef ENGLISH
    .string "RATTATA may be small, but don't\n"
    .string "underestimate its wicked bite.\p"
    .string "Have you caught one already?$"
    .endif
    .ifdef SPANISH
    .string "¡Puede que RATTATA sea pequeño,\n"
    .string "pero su mordisco es muy potente!\p"
    .string "¿Tienes alguno?$"
    .endif

