SaffronCity_PokemonTrainerFanClub_Text_HuhYou::
    .ifdef ENGLISH
    .string "Huh?\n"
    .string "You…$"
    .endif
    .ifdef SPANISH
    .string "¿Mm?\n"
    .string "Tú...$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_YourePlayerWereYourFansNow::
    .ifdef ENGLISH
    .string "Are you maybe…\n"
    .string "… …\p"
    .string "You are!\n"
    .string "You are {PLAYER}!\p"
    .string "We were just talking about you!\p"
    .string "We were talking about how an\n"
    .string "incredibly good TRAINER appeared.\p"
    .string "And that someone is you!\n"
    .string "You're so cool!\p"
    .string "So, we decided that we'll become\n"
    .string "your FAN CLUB!\p"
    .string "We all hope you'll keep battling\n"
    .string "and show us how cool you are.\p"
    .string "That way, maybe other people will\n"
    .string "become fans just like me.$"
    .endif
    .ifdef SPANISH
    .string "¿Tú no eras...?\p"
    .string "¡Sí!\n"
    .string "¡Tú eres {PLAYER}!\p"
    .string "¡Estábamos hablando de ti\n"
    .string "ahora mismo!\p"
    .string "¡Estábamos diciendo que había\n"
    .string "alguien que se salía ENTRENANDO\l"
    .string "POKéMON!\p"
    .string "¡Y ese alguien eres tú!\n"
    .string "¡Eres guay!\p"
    .string "¡Nos ha entrado tanta emoción\n"
    .string "que hemos decidido crear tu CLUB\l"
    .string "de FANS!\p"
    .string "¡Esperamos que sigas luchando\n"
    .string "y enseñándonos lo guay que eres!\p"
    .string "¡Así seguro que te salen muchos\n"
    .string "más fans como yo!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_AlwaysCheerForYou::
    .ifdef ENGLISH
    .string "I'll always be cheering for you!\p"
    .string "Go, {PLAYER}, go!$"
    .endif
    .ifdef SPANISH
    .string "¡Pienso animarte siempre!\p"
    .string "¡A la bim, a la bam, a la bim,\n"
    .string "bom, bam! ¡{PLAYER}, {PLAYER}, y\l"
    .string "nadie más! ¡A la bim, bom, bam!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_IllAlwaysBelieveInYou::
    .ifdef ENGLISH
    .string "I'll always believe in you,\n"
    .string "{PLAYER}.\p"
    .string "Please show the others what you're\n"
    .string "like when you battle seriously.$"
    .endif
    .ifdef SPANISH
    .string "¡Pienso apoyarte siempre, {PLAYER}!\p"
    .string "¡Enséñale al mundo de lo que\n"
    .string "eres capaz cuando te lo propones!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_WasYourFanNotAnymore::
    .ifdef ENGLISH
    .string "I'm sorry.\n"
    .string "I was your fan before.\p"
    .string "But now, you seem to have lost\n"
    .string "the drive you had before.\p"
    .string "Lately, I think {STR_VAR_1} has been\n"
    .string "a lot cooler.$"
    .endif
    .ifdef SPANISH
    .string "Lo siento.\n"
    .string "Yo era tu fan...\p"
    .string "Pero has perdido mucho tirón...\p"
    .string "Últimamente, quien parte la pana\n"
    .string "es {STR_VAR_1}, la verdad...$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_EveryonesYourFanButICantBe::
    .ifdef ENGLISH
    .string "Oh!\n"
    .string "{PLAYER}!\p"
    .string "Everyone's been all excited about\n"
    .string "you recently.\p"
    .string "I can understand why.\n"
    .string "I know that you're strong.\p"
    .string "But, do you know what?\p"
    .string "Once I became {STR_VAR_1}'s fan,\n"
    .string "I can't just stop being a fan.$"
    .endif
    .ifdef SPANISH
    .string "¡Hola, {PLAYER}!\p"
    .string "¡Últimamente todo el mundo está\n"
    .string "revolucionado contigo!\p"
    .string "Y lo entiendo, eres muy fuerte...\p"
    .string "Pero ¿sabes qué pasa?\p"
    .string "Que me hice fan de {STR_VAR_1}\n"
    .string "y no es plan de echarme atrás\l"
    .string "ahora, ¿no?$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_TrainersCoolWhenBattling::
    .ifdef ENGLISH
    .string "I think TRAINERS are so cool when\n"
    .string "they're battling.\p"
    .string "Don't you think so, too?$"
    .endif
    .ifdef SPANISH
    .string "A mí me parece que no hay nada\n"
    .string "más guay que ver luchar a los\l"
    .string "ENTRENADORES.\p"
    .string "¿No te parece?$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_CanYouAutographShorts::
    .ifdef ENGLISH
    .string "Oh! It's {PLAYER}!\n"
    .string "Too cool!\p"
    .string "Oh!\n"
    .string "Oh, yeah!\p"
    .string "Can you autograph something?\n"
    .string "How about my shorts?$"
    .endif
    .ifdef SPANISH
    .string "¡Madre mía, pero si es {PLAYER}!\n"
    .string "¡Guau, qué pasada!\p"
    .string "¡Qué guay, qué guay!\n"
    .string "¡Qué emoción!\p"
    .string "¿Me firmas un autógrafo?\n"
    .string "¡Fírmame en los pantalones,\l"
    .string "no pasa nada!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_CountingOnYou::
    .ifdef ENGLISH
    .string "However hot it's been…\p"
    .string "And however cold it may get…\p"
    .string "I've always believed in, and worn,\n"
    .string "shorts!\p"
    .string "I'm counting on you to keep\n"
    .string "winning!\p"
    .string "I believe in you just as much as\n"
    .string "I believe in shorts!$"
    .endif
    .ifdef SPANISH
    .string "¡Yo siempre llevo pantalones\n"
    .string "cortos, como tú!\p"
    .string "¡Ya llueva, nieve, o ventee!\p"
    .string "¡Yo iré con pantalón corto,\n"
    .string "como tú!\p"
    .string "¡Venga, debes ir a por todas!\p"
    .string "¡Yo confío en ti y no me pienso\n"
    .string "quitar los pantalones cortos!\l"
    .string "¡Pantalones cortos al poder!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_BrocksMyHero::
    .ifdef ENGLISH
    .string "BROCK's my hero!\n"
    .string "He's a man among men!\p"
    .string "Heheh, I got my mom to do\n"
    .string "something for me.\p"
    .string "I got her to embroider “BROCK”\n"
    .string "on my shorts!$"
    .endif
    .ifdef SPANISH
    .string "¡BROCK es mi héroe!\n"
    .string "No hay otro como él.\p"
    .string "¡Lo admiro tanto que le he\n"
    .string "pedido a mi madre que me borde\l"
    .string "su nombre en los pantalones, je!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_BrocksFanToBitterEnd::
    .ifdef ENGLISH
    .string "…  …\p"
    .string "…  …\n"
    .string "I'm BROCK's fan!\p"
    .string "Even if I were his only fan,\n"
    .string "I swear it on my rock-hard will,\l"
    .string "and on my shorts!\p"
    .string "I'll be his fan to the bitter end!$"
    .endif
    .ifdef SPANISH
    .string "Eh... Yo soy fan de BROCK.\p"
    .string "Y aunque fuera su único seguidor,\n"
    .string "no lo abandonaría nunca.\p"
    .string "¡Pongo a mis pantalones cortos\n"
    .string "como testigo!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_BrocksLastWordOnCool::
    .ifdef ENGLISH
    .string "BROCK's the last word on cool,\n"
    .string "end of story!\p"
    .string "Now there's a guy who I want to\n"
    .string "be like!$"
    .endif
    .ifdef SPANISH
    .string "BROCK es la caña, punto.\p"
    .string "¡Ya me gustaría a mí ser como él!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_HadPleasureOfWatchingYouBattle::
    .ifdef ENGLISH
    .string "{PLAYER}, I've had the pleasure of\n"
    .string "watching you battle.\p"
    .string "It brings back sweet memories of\n"
    .string "my own long-lost youth.\p"
    .string "May you continue to find success.\n"
    .string "You have a fan in me!$"
    .endif
    .ifdef SPANISH
    .string "{PLAYER}, he tenido el placer\n"
    .string "de verte luchar.\p"
    .string "Y me he visto de joven. Ah, qué\n"
    .string "dulces y lejanos recuerdos...\p"
    .string "Sigue por el camino que llevas.\n"
    .string "Pienso seguirte siempre.$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_NeverSeenTrainerOfYourMagnificence::
    .ifdef ENGLISH
    .string "I have journeyed far and wide\n"
    .string "across the lands.\p"
    .string "But never have I seen a TRAINER\n"
    .string "of your magnificence.\p"
    .string "Take courage in your abilities\n"
    .string "and keep battling on!\p"
    .string "Make that a promise to me,\n"
    .string "my young idol!$"
    .endif
    .ifdef SPANISH
    .string "He viajado por mil sitios y puedo\n"
    .string "decir que ningún ENTRENADOR\l"
    .string "te llega a la suela del zapato.\p"
    .string "¡Confía en tus posibilidades\n"
    .string "y sigue luchando!\p"
    .string "¡Di que vas a seguir luchando!\n"
    .string "¡Muy bien, joven!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_HmmAndYouAre::
    .ifdef ENGLISH
    .string "Hmm…\n"
    .string "And you are?\p"
    .string "Were you hoping to sign up for\n"
    .string "a membership in our FAN CLUB?$"
    .endif
    .ifdef SPANISH
    .string "¿Mm?\n"
    .string "¿Y tú quién eres?\p"
    .string "¿Vienes a apuntarte al CLUB?$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_YouveStillAWaysToGo::
    .ifdef ENGLISH
    .string "Ah, so you are the much-\n"
    .string "talked-about {PLAYER}.\p"
    .string "You certainly do have the look of\n"
    .string "a winner.\p"
    .string "But for me to accept you as\n"
    .string "a true POKéMON great…\p"
    .string "… …\p"
    .string "You've still a ways to go!$"
    .endif
    .ifdef SPANISH
    .string "Anda, así que eres {PLAYER}...\n"
    .string "Todo el mundo habla de ti\l"
    .string "últimamente.\p"
    .string "La verdad es que tienes pinta\n"
    .string "de ser fuerte, sí, sí.\p"
    .string "Pero para mí..., no sé,\n"
    .string "te veo un poco verde todavía.$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_YoullBeTalkedAboutIfYouKeepWinning::
    .ifdef ENGLISH
    .string "All of us gathered here are fans\n"
    .string "of POKéMON TRAINERS.\p"
    .string "The way they look in battle…\n"
    .string "They are the picture of coolness.\p"
    .string "Perhaps you will be talked about\n"
    .string "here, too, if you keep winning.$"
    .endif
    .ifdef SPANISH
    .string "Todos los que estamos aquí somos\n"
    .string "fans de ENTRENADORES POKéMON.\p"
    .string "La imagen que dan cuando luchan...\n"
    .string "¡Son supercarismáticos!\p"
    .string "No sé, si ganas más combates,\n"
    .string "¡igual acabamos hablando todos\l"
    .string "de ti!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeYouOneDay::
    .ifdef ENGLISH
    .string "It's {PLAYER}!\n"
    .string "It's {PLAYER}!\p"
    .string "I want to be like {PLAYER} one day!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, que es {PLAYER}!\n"
    .string "¡Es {PLAYER}!\p"
    .string "¡Yo quiero llegar a ser como\n"
    .string "{PLAYER}!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_EveryoneButMeStoppedBeingYourFan::
    .ifdef ENGLISH
    .string "Everyone stopped being {PLAYER}'s\n"
    .string "fan…\p"
    .string "But that means I can have {PLAYER}\n"
    .string "all to myself!\p"
    .string "Yay! Go for it!\n"
    .string "My one and only {PLAYER}!$"
    .endif
    .ifdef SPANISH
    .string "Todo el mundo ha dejado de ser\n"
    .string "fan de {PLAYER}...\p"
    .string "¡Me da igual, así me tiene sólo\n"
    .string "a mí!\p"
    .string "¡{PLAYER}, {PLAYER}, {PLAYER}!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeSabrina::
    .ifdef ENGLISH
    .string "Do you know what?\n"
    .string "I want to be like SABRINA!\p"
    .string "I want to be a psychic girl just\n"
    .string "like her!$"
    .endif
    .ifdef SPANISH
    .string "¿Sabes qué?\n"
    .string "¡Me encantaría ser como SABRINA!\p"
    .string "¡Y dominar los poderes psíquicos,\n"
    .string "como ella!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingSabrinasFan::
    .ifdef ENGLISH
    .string "Even if I'm the only one, I won't\n"
    .string "stop being SABRINA's fan.\p"
    .string "My dream is to be like SABRINA,\n"
    .string "cute, but cool.\p"
    .string "I want to be a psychic girl just\n"
    .string "like her!$"
    .endif
    .ifdef SPANISH
    .string "No pienso dejar nunca a SABRINA.\n"
    .string "¡Aunque sea su única fan!.\p"
    .string "Mi sueño es llegar a ser como\n"
    .string "ella; dulce, pero guay a la vez.\p"
    .string "¡Y dominar los poderes psíquicos,\n"
    .string "como ella!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_CanIBecomeCoolTrainerOneDay::
    .ifdef ENGLISH
    .string "I wonder if I can become a cool\n"
    .string "TRAINER one day?$"
    .endif
    .ifdef SPANISH
    .string "¿Llegaré a ser buena ENTRENADORA\n"
    .string "algún día?$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_TheWayYouBattleIsCool::
    .ifdef ENGLISH
    .string "Oh, man, oh, man!\n"
    .string "Cool! Too cool!\p"
    .string "…Huh?\n"
    .string "No, not you.\p"
    .string "Just the way you battle.\n"
    .string "That's cool.$"
    .endif
    .ifdef SPANISH
    .string "¡Qué pasada, qué pasada!\n"
    .string "¡Qué guay, qué guay!\p"
    .string "¿Mm?...\n"
    .string "No, no lo digo por ti.\p"
    .string "Lo digo por tu forma de luchar.\n"
    .string "Es guay.$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_ImOnlyOneLeftOfYourFans::
    .ifdef ENGLISH
    .string "Yo, {PLAYER}!\p"
    .string "Looks like I'm the only one left\n"
    .string "out of your fans.\p"
    .string "But, you know, I like being an only\n"
    .string "fan… It's less stressful.\p"
    .string "Keep up and at it!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, {PLAYER}!\p"
    .string "Creo que soy el único fan que\n"
    .string "tienes.\p"
    .string "Pero oye, tiene su lado positivo,\n"
    .string "te evitas mucho estrés.\p"
    .string "¡Sigue como hasta ahora!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_LoveWayTrainerTalks::
    .ifdef ENGLISH
    .string "{STR_VAR_1}'s cool, huh?\n"
    .string "I love the way he talks.\p"
    .string "I'd really relish a chance to meet\n"
    .string "him in person once.$"
    .endif
    .ifdef SPANISH
    .string "Qué guay es {STR_VAR_1}, ¿verdad?\n"
    .string "Me gusta hasta su forma de hablar.\p"
    .string "¡Me encantaría que viniera alguna\n"
    .string "vez por aquí!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_ImLoneTrainerFan::
    .ifdef ENGLISH
    .string "Huh, can you believe it?\n"
    .string "Everyone turned into your fans.\p"
    .string "So after all we've been through,\n"
    .string "I'm the lone {STR_VAR_1} fan?\p"
    .string "Eh, being the one and only\n"
    .string "{STR_VAR_1} fan's my style, anyway.$"
    .endif
    .ifdef SPANISH
    .string "¿Será posible?\n"
    .string "¡Todo el mundo es fan tuyo!\p"
    .string "O sea, ¿que soy el único fan\n"
    .string "de {STR_VAR_1}?\p"
    .string "Bueno, en realidad, ¿qué más\n"
    .string "me da?$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_AdoreWayYouBattle::
    .ifdef ENGLISH
    .string "Oh, my goodness!\n"
    .string "Is it really you, {PLAYER}?\p"
    .string "I have to tell you, I adore the\n"
    .string "way you battle.\p"
    .string "I hope you'll keep at it.\n"
    .string "I'll be your number one fan!$"
    .endif
    .ifdef SPANISH
    .string "¡No me lo puedo creer!\n"
    .string "¿Eres {PLAYER}, en serio?\p"
    .string "Tengo que decirte que me encanta\n"
    .string "la forma de luchar que tienes.\p"
    .string "Espero que no cambies nunca.\n"
    .string "¡Soy tu fan más fan!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_ImYourNumberOneFan::
    .ifdef ENGLISH
    .string "Oh, my goodness!\n"
    .string "If it isn't {PLAYER}!\p"
    .string "It's so disappointing… I realized\n"
    .string "I'm your number-one-and-only fan!\p"
    .string "Well, it can't be helped!\n"
    .string "Let me cheer you on, at least!\p"
    .string "Hurray, hurray, {PLAYER}!$"
    .endif
    .ifdef SPANISH
    .string "¡No me lo puedo creer!\n"
    .string "¡Pero si es {PLAYER}!\p"
    .string "Quería decirte que estoy un poco\n"
    .string "chafada, porque soy tu única fan.\p"
    .string "Pero bueno, pienso animarte\n"
    .string "de todas formas.\p"
    .string "¡Viva {PLAYER}!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_TrainerHasBeenOnFire::
    .ifdef ENGLISH
    .string "Recently, {STR_VAR_1} has been on\n"
    .string "fire.\p"
    .string "The way he battles… It's just \n"
    .string "the way that I like it!$"
    .endif
    .ifdef SPANISH
    .string "Quien ha estado en boca de todos\n"
    .string "últimamente es {STR_VAR_1}.\p"
    .string "Lucha de una manera...\n"
    .string "Como a mí me gusta, vaya.$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_EveryoneTalksAboutYou::
    .ifdef ENGLISH
    .string "Oh, hello!\n"
    .string "If it isn't {PLAYER}!\p"
    .string "Lately, all everyone talks about\n"
    .string "is you.\p"
    .string "I'm feeling lonesome because I\n"
    .string "prefer {STR_VAR_1}.$"
    .endif
    .ifdef SPANISH
    .string "¡Anda, pero si es {PLAYER}!\p"
    .string "Se ve que está de moda hablar\n"
    .string "de ti.\p"
    .string "¡Yo me he quedado más sola\n"
    .string "que la una animando a {STR_VAR_1}!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_YouReallyAreAmazing::
    .ifdef ENGLISH
    .string "Amazing!\n"
    .string "{PLAYER}, you really are amazing!\p"
    .string "Instead of just watching, maybe\n"
    .string "I should become a TRAINER, too.$"
    .endif
    .ifdef SPANISH
    .string "¡Guay, guay y guay!\n"
    .string "¡{PLAYER}, eres realmente guay!\p"
    .string "¡De tanto verte, he decidido\n"
    .string "convertirme en ENTRENADORA!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_ImYourOnlyFan::
    .ifdef ENGLISH
    .string "I'm your only fan…\n"
    .string "Sigh… This is lonely…\p"
    .string "Can't you try harder and make the\n"
    .string "others take notice of you?$"
    .endif
    .ifdef SPANISH
    .string "Soy tu única fan...\n"
    .string "Y... me encuentro tan sola...\p"
    .string "¿Por qué no te esfuerzas un poco\n"
    .string "para que se fijen en ti?$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_WhyCantOthersSeeMastersDignity::
    .ifdef ENGLISH
    .string "Master {STR_VAR_1} is so dignified…\n"
    .string "He is so my type.\p"
    .string "Why can't the others see the\n"
    .string "dignity he simply oozes?$"
    .endif
    .ifdef SPANISH
    .string "La verdad es que {STR_VAR_1}\n"
    .string "impone... A mí me encanta.\p"
    .string "¿Soy yo la única que percibe el\n"
    .string "aura de solemnidad que le rodea?$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_BelieveInMasterWithAllMyHeart::
    .ifdef ENGLISH
    .string "I believe in Master {STR_VAR_1}\n"
    .string "with all my heart.\p"
    .string "Even if I am the only one to\n"
    .string "believe in him.\p"
    .string "I won't ever feel lonesome, though.\p"
    .string "Not if I keep thinking about Master\n"
    .string "{STR_VAR_1}.$"
    .endif
    .ifdef SPANISH
    .string "Yo confío profundamente\n"
    .string "en {STR_VAR_1}.\p"
    .string "Me da igual ser la única.\p"
    .string "Mientras tenga a mi ídolo\n"
    .string "{STR_VAR_1}, no me sentiré sola.$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_YourBattleStyleIsEducational::
    .ifdef ENGLISH
    .string "Hiyah!\p"
    .string "Your battling style is most\n"
    .string "educational.\p"
    .string "I hope that you will keep plugging\n"
    .string "away at success, hiyah!$"
    .endif
    .ifdef SPANISH
    .string "¡Guau!\p"
    .string "¡Tu forma de luchar es ejemplar!\p"
    .string "¡Espero que nunca dejes de tener\n"
    .string "éxito! ¡Ánimo!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingYourFan::
    .ifdef ENGLISH
    .string "Instead of just watching others\n"
    .string "battle, battle yourself!\p"
    .string "…My DOJO's MASTER chewed me out\n"
    .string "like that…\p"
    .string "But I won't let that stop me from\n"
    .string "being your fan!\p"
    .string "I can't stop being your fan!$"
    .endif
    .ifdef SPANISH
    .string "¡No te entretengas mirando cómo\n"
    .string "lucha el resto! ¡Lucha tú!\p"
    .string "Mi MAESTRO me echó del DOJO\n"
    .string "como el que no quiere la cosa...\p"
    .string "Pero, me da igual, yo voy a seguir\n"
    .string "siendo tu fan.\p"
    .string "¡No pienso dejar de serlo!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_OnlyMasterHasMyRespect::
    .ifdef ENGLISH
    .string "Hiyah! There is but one TRAINER\n"
    .string "who has my respect.\p"
    .string "And that is none other than my\n"
    .string "MASTER at the FIGHTING DOJO.\p"
    .string "You should become a fan of my\n"
    .string "MASTER like me! Hiyah!$"
    .endif
    .ifdef SPANISH
    .string "¡Hiyah! Sólo tengo respeto por\n"
    .string "un ENTRENADOR.\p"
    .string "Por mi MAESTRO. No hay nadie\n"
    .string "como él sobre el DOJO.\p"
    .string "Deberías hacerte su fan, como yo.\n"
    .string "¡Hiyah!$"
    .endif

SaffronCity_PokemonTrainerFanClub_Text_NeverBeFanOfAnyoneButMaster::
    .ifdef ENGLISH
    .string "Hiyah! I respect my MASTER at the\n"
    .string "FIGHTING DOJO.\p"
    .string "I will never become a fan of\n"
    .string "anyone other than my MASTER!\p"
    .string "I will even sneak out of the DOJO\n"
    .string "to spread word of his greatness.\p"
    .string "Hiyah!$"
    .endif
    .ifdef SPANISH
    .string "¡Hiyah! Tengo un respeto enorme\n"
    .string "por mi MAESTRO.\l"
    .string "Es el mejor sobre el DOJO.\p"
    .string "No pienso ser fan de nadie más.\p"
    .string "Voy a ir diciendo por ahí lo bueno\n"
    .string "que es.\p"
    .string "¡Hiyah!$"
    .endif

