Route8_Text_AidanIntro::
    .ifdef ENGLISH
    .string "You look good at POKéMON, but how\n"
    .string "is your chemistry grade?$"
    .endif
    .ifdef SPANISH
    .string "Parece que sabes mucho sobre\n"
    .string "POKéMON, pero...\l"
    .string "¿Qué tal en química?$"
    .endif

Route8_Text_AidanDefeat::
    .ifdef ENGLISH
    .string "Ow!\n"
    .string "Meltdown!$"
    .endif
    .ifdef SPANISH
    .string "¡Ah!\n"
    .string "¡Fusión nuclear!$"
    .endif

Route8_Text_AidanPostBattle::
    .ifdef ENGLISH
    .string "I am better at school than this!$"
    .endif
    .ifdef SPANISH
    .string "¡Se me da mejor en el cole!$"
    .endif

Route8_Text_StanIntro::
    .ifdef ENGLISH
    .string "All right!\n"
    .string "Let's play a game!$"
    .endif
    .ifdef SPANISH
    .string "¡Muy bien!\n"
    .string "¡Echemos los dados!$"
    .endif

Route8_Text_StanDefeat::
    .ifdef ENGLISH
    .string "Drat!\n"
    .string "Came up short!$"
    .endif
    .ifdef SPANISH
    .string "¡Vaya!\n"
    .string "¡Me he quedado corto!$"
    .endif

Route8_Text_StanPostBattle::
    .ifdef ENGLISH
    .string "Things didn't work today.$"
    .endif
    .ifdef SPANISH
    .string "¡Hoy no es mi día de suerte!$"
    .endif

Route8_Text_GlennIntro::
    .ifdef ENGLISH
    .string "You should be informed.\n"
    .string "You need strategy to win at this!$"
    .endif
    .ifdef SPANISH
    .string "¡Necesitas una buena estrategia!$"
    .endif

Route8_Text_GlennDefeat::
    .ifdef ENGLISH
    .string "It's not logical!$"
    .endif
    .ifdef SPANISH
    .string "¡No es lógico!$"
    .endif

Route8_Text_GlennPostBattle::
    .ifdef ENGLISH
    .string "Go with GRIMER first…and…\n"
    .string "…and…then…$"
    .endif
    .ifdef SPANISH
    .string "Usa a GRIMER primero... y...\n"
    .string "y... después...$"
    .endif

Route8_Text_PaigeIntro::
    .ifdef ENGLISH
    .string "I like NIDORAN, so I collect them!$"
    .endif
    .ifdef SPANISH
    .string "¡Me gustan los NIDORAN\n"
    .string "y por eso los colecciono!$"
    .endif

Route8_Text_PaigeDefeat::
    .ifdef ENGLISH
    .string "Why?\n"
    .string "Why??$"
    .endif
    .ifdef SPANISH
    .string "Pero ¿por qué?$"
    .endif

Route8_Text_PaigePostBattle::
    .ifdef ENGLISH
    .string "When POKéMON grow up, they get\n"
    .string "ugly! They shouldn't evolve.$"
    .endif
    .ifdef SPANISH
    .string "¡Cuando los POKéMON crecen\n"
    .string "se vuelven muy feos!\l"
    .string "¡No me gustan cuando evolucionan!$"
    .endif

Route8_Text_LeslieIntro::
    .ifdef ENGLISH
    .string "School is fun, but so are POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "¡Me gusta el colegio, y los\n"
    .string "POKéMON!$"
    .endif

Route8_Text_LeslieDefeat::
    .ifdef ENGLISH
    .string "You made it clear to me that\n"
    .string "I should stick with school.$"
    .endif
    .ifdef SPANISH
    .string "Prefiero el colegio, está claro\n"
    .string "que se me da mucho mejor.$"
    .endif

Route8_Text_LesliePostBattle::
    .ifdef ENGLISH
    .string "I was planning on getting some\n"
    .string "fresh air for a change, but…\p"
    .string "We're stuck here because of the\n"
    .string "gates at SAFFRON.$"
    .endif
    .ifdef SPANISH
    .string "Querría darme una vuelta, pero...\p"
    .string "La entrada a AZAFRÁN está\n"
    .string "bloqueada...$"
    .endif

Route8_Text_AndreaIntro::
    .ifdef ENGLISH
    .string "MEOWTH is so cute, meow, meow,\n"
    .string "meow!$"
    .endif
    .ifdef SPANISH
    .string "¡MEOWTH es muy mono, meow, meow!$"
    .endif

Route8_Text_AndreaDefeat::
    .ifdef ENGLISH
    .string "Meeeeyow!$"
    .endif
    .ifdef SPANISH
    .string "¡Meow!$"
    .endif

Route8_Text_AndreaPostBattle::
    .ifdef ENGLISH
    .string "I think PIDGEY and RATTATA are\n"
    .string "cute, too!$"
    .endif
    .ifdef SPANISH
    .string "¡Creo que PIDGEY y RATTATA\n"
    .string "también son muy monos!$"
    .endif

Route8_Text_MeganIntro::
    .ifdef ENGLISH
    .string "We must look silly standing here\n"
    .string "like this.$"
    .endif
    .ifdef SPANISH
    .string "¡Debemos de tener un aspecto muy\n"
    .string "tonto!$"
    .endif

Route8_Text_MeganDefeat::
    .ifdef ENGLISH
    .string "Look what you did to my poor, cute\n"
    .string "POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "¡Mira lo que has hecho!$"
    .endif

Route8_Text_MeganPostBattle::
    .ifdef ENGLISH
    .string "SAFFRON's gatekeeper won't let us\n"
    .string "go through.\p"
    .string "I know he's doing his job, but I\n"
    .string "think he's mean.$"
    .endif
    .ifdef SPANISH
    .string "El guardián de la entrada a\n"
    .string "AZAFRÁN no nos dejará pasar.\p"
    .string "¡Sé que hace su trabajo,\n"
    .string "pero es que es lo peor!$"
    .endif

Route8_Text_RichIntro::
    .ifdef ENGLISH
    .string "I'm a rambling, gaming dude!$"
    .endif
    .ifdef SPANISH
    .string "¡Soy un jugón errante!$"
    .endif

Route8_Text_RichDefeat::
    .ifdef ENGLISH
    .string "Missed the big chance!$"
    .endif
    .ifdef SPANISH
    .string "¡He perdido el gran premio!$"
    .endif

Route8_Text_RichPostBattle::
    .ifdef ENGLISH
    .string "Playing games and POKéMON are like\n"
    .string "eating peanuts! I just can't stop!$"
    .endif
    .ifdef SPANISH
    .string "¡Cuando juego y entreno POKéMON\n"
    .string "no puedo parar!$"
    .endif

Route8_Text_JuliaIntro::
    .ifdef ENGLISH
    .string "What's a cute, round, and fluffy\n"
    .string "POKéMON?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué POKéMON es mono, redondo\n"
    .string "y blando?$"
    .endif

Route8_Text_JuliaDefeat::
    .ifdef ENGLISH
    .string "Stop!\p"
    .string "Don't be so mean to my CLEFAIRY!$"
    .endif
    .ifdef SPANISH
    .string "¡Ya basta!\p"
    .string "¡No seas cruel con mis CLEFAIRY!$"
    .endif

Route8_Text_JuliaPostBattle::
    .ifdef ENGLISH
    .string "I read that CLEFAIRY evolves when\n"
    .string "it's exposed to a MOON STONE.\p"
    .string "I read that in a POKéMON JOURNAL.\n"
    .string "I wonder if it's true?$"
    .endif
    .ifdef SPANISH
    .string "He leído que CLEFAIRY evoluciona\n"
    .string "cuando es expuesto a una PIEDRA\l"
    .string "LUNAR.\p"
    .string "Lo leí en el DIARIO POKéMON.\n"
    .string "¿Será verdad?$"
    .endif

Route8_Text_UndergroundPathSign::
    .ifdef ENGLISH
    .string "UNDERGROUND PATH\n"
    .string "CELADON CITY - LAVENDER TOWN$"
    .endif
    .ifdef SPANISH
    .string "VÍA SUBTERRÁNEA:\n"
    .string "CIUDAD AZULONA - PUEBLO LAVANDA$"
    .endif

Route8_Text_EliIntro::
    .ifdef ENGLISH
    .string "ELI: Twin power is fantastic.\n"
    .string "Did you know?$"
    .endif
    .ifdef SPANISH
    .string "TITA: La fuerza que tienen los\n"
    .string "hermanos gemelos es enorme,\l"
    .string "¿lo sabías?$"
    .endif

Route8_Text_EliDefeat::
    .ifdef ENGLISH
    .string "ELI: But…\n"
    .string "We used our twin power…$"
    .endif
    .ifdef SPANISH
    .string "TITA: Pero si hemos unido nuestras\n"
    .string "fuerzas...$"
    .endif

Route8_Text_EliPostBattle::
    .ifdef ENGLISH
    .string "ELI: I caught my POKéMON with\n"
    .string "ANNE!$"
    .endif
    .ifdef SPANISH
    .string "TITA: Yo atrapé mi POKéMON\n"
    .string "con LIN.$"
    .endif

Route8_Text_EliNotEnoughMons::
    .ifdef ENGLISH
    .string "ELI: We can't battle if you don't\n"
    .string "have two POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "TITA: Si no tienes dos POKéMON,\n"
    .string "no podemos luchar contigo.$"
    .endif

Route8_Text_AnneIntro::
    .ifdef ENGLISH
    .string "ANNE: We'll shock you with our twin\n"
    .string "power!$"
    .endif
    .ifdef SPANISH
    .string "LIN: ¡No vas a poder con estas\n"
    .string "gemelas!$"
    .endif

Route8_Text_AnneDefeat::
    .ifdef ENGLISH
    .string "ANNE: Our twin power…$"
    .endif
    .ifdef SPANISH
    .string "LIN: Pues sí que has podido...$"
    .endif

Route8_Text_AnnePostBattle::
    .ifdef ENGLISH
    .string "ANNE: I'm raising POKéMON with\n"
    .string "ELI.$"
    .endif
    .ifdef SPANISH
    .string "LIN: Yo crío a mi POKéMON\n"
    .string "con TITA.$"
    .endif

Route8_Text_AnneNotEnoughMons::
    .ifdef ENGLISH
    .string "ANNE: Hi, hi! Let's battle!\n"
    .string "But bring two POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "LIN: Nos gustaría luchar contigo,\n"
    .string "pero necesitas dos POKéMON.$"
    .endif

Route8_Text_RicardoIntro::
    .ifdef ENGLISH
    .string "My bike's acting up, man.$"
    .endif
    .ifdef SPANISH
    .string "¡Mi moto está como una moto!$"
    .endif

Route8_Text_RicardoDefeat::
    .ifdef ENGLISH
    .string "Aww, man.\n"
    .string "I'm not into this.$"
    .endif
    .ifdef SPANISH
    .string "No sé qué me ha pasado...$"
    .endif

Route8_Text_RicardoPostBattle::
    .ifdef ENGLISH
    .string "I got grass caught up in my\n"
    .string "spokes, man.$"
    .endif
    .ifdef SPANISH
    .string "Se me ha enganchado césped\n"
    .string "en los radios de las ruedas...$"
    .endif

Route8_Text_JarenIntro::
    .ifdef ENGLISH
    .string "Clear the way, or I'll run you\n"
    .string "down!$"
    .endif
    .ifdef SPANISH
    .string "Apártate si no quieres que te pase\n"
    .string "por encima.$"
    .endif

Route8_Text_JarenDefeat::
    .ifdef ENGLISH
    .string "You for real, kid?$"
    .endif
    .ifdef SPANISH
    .string "Tú vas en serio, ¿no?$"
    .endif

Route8_Text_JarenPostBattle::
    .ifdef ENGLISH
    .string "Don't think you're all special and\n"
    .string "all just because of this.$"
    .endif
    .ifdef SPANISH
    .string "Tampoco te pongas en plan tonto\n"
    .string "por haber ganado.$"
    .endif
