Route8_Text_AidanIntro::
    .string "Parece que sabes mucho sobre\n"
    .string "POKéMON, pero...\l"
    .string "¿Qué tal en química?$"

Route8_Text_AidanDefeat::
    .string "¡Ah!\n"
    .string "¡Fusión nuclear!$"

Route8_Text_AidanPostBattle::
    .string "¡Se me da mejor en el cole!$"

Route8_Text_StanIntro::
    .string "¡Muy bien!\n"
    .string "¡Echemos los dados!$"

Route8_Text_StanDefeat::
    .string "¡Vaya!\n"
    .string "¡Me he quedado corto!$"

Route8_Text_StanPostBattle::
    .string "¡Hoy no es mi día de suerte!$"

Route8_Text_GlennIntro::
    .string "¡Necesitas una buena estrategia!$"

Route8_Text_GlennDefeat::
    .string "¡No es lógico!$"

Route8_Text_GlennPostBattle::
    .string "Usa a GRIMER primero... y...\n"
    .string "y... después...$"

Route8_Text_PaigeIntro::
    .string "¡Me gustan los NIDORAN\n"
    .string "y por eso los colecciono!$"

Route8_Text_PaigeDefeat::
    .string "Pero ¿por qué?$"

Route8_Text_PaigePostBattle::
    .string "¡Cuando los POKéMON crecen\n"
    .string "se vuelven muy feos!\l"
    .string "¡No me gustan cuando evolucionan!$"

Route8_Text_LeslieIntro::
    .string "¡Me gusta el colegio, y los\n"
    .string "POKéMON!$"

Route8_Text_LeslieDefeat::
    .string "Prefiero el colegio, está claro\n"
    .string "que se me da mucho mejor.$"

Route8_Text_LesliePostBattle::
    .string "Querría darme una vuelta, pero...\p"
    .string "La entrada a AZAFRÁN está\n"
    .string "bloqueada...$"

Route8_Text_AndreaIntro::
    .string "¡MEOWTH es muy mono, meow, meow!$"

Route8_Text_AndreaDefeat::
    .string "¡Meow!$"

Route8_Text_AndreaPostBattle::
    .string "¡Creo que PIDGEY y RATTATA\n"
    .string "también son muy monos!$"

Route8_Text_MeganIntro::
    .string "¡Debemos de tener un aspecto muy\n"
    .string "tonto!$"

Route8_Text_MeganDefeat::
    .string "¡Mira lo que has hecho!$"

Route8_Text_MeganPostBattle::
    .string "El guardián de la entrada a\n"
    .string "AZAFRÁN no nos dejará pasar.\p"
    .string "¡Sé que hace su trabajo,\n"
    .string "pero es que es lo peor!$"

Route8_Text_RichIntro::
    .string "¡Soy un jugón errante!$"

Route8_Text_RichDefeat::
    .string "¡He perdido el gran premio!$"

Route8_Text_RichPostBattle::
    .string "¡Cuando juego y entreno POKéMON\n"
    .string "no puedo parar!$"

Route8_Text_JuliaIntro::
    .string "¿Qué POKéMON es mono, redondo\n"
    .string "y blando?$"

Route8_Text_JuliaDefeat::
    .string "¡Ya basta!\p"
    .string "¡No seas cruel con mis CLEFAIRY!$"

Route8_Text_JuliaPostBattle::
    .string "He leído que CLEFAIRY evoluciona\n"
    .string "cuando es expuesto a una PIEDRA\l"
    .string "LUNAR.\p"
    .string "Lo leí en el DIARIO POKéMON.\n"
    .string "¿Será verdad?$"

Route8_Text_UndergroundPathSign::
    .string "VÍA SUBTERRÁNEA:\n"
    .string "CIUDAD AZULONA - PUEBLO LAVANDA$"

Route8_Text_EliIntro::
    .string "TITA: La fuerza que tienen los\n"
    .string "hermanos gemelos es enorme,\l"
    .string "¿lo sabías?$"

Route8_Text_EliDefeat::
    .string "TITA: Pero si hemos unido nuestras\n"
    .string "fuerzas...$"

Route8_Text_EliPostBattle::
    .string "TITA: Yo atrapé mi POKéMON\n"
    .string "con LIN.$"

Route8_Text_EliNotEnoughMons::
    .string "TITA: Si no tienes dos POKéMON,\n"
    .string "no podemos luchar contigo.$"

Route8_Text_AnneIntro::
    .string "LIN: ¡No vas a poder con estas\n"
    .string "gemelas!$"

Route8_Text_AnneDefeat::
    .string "LIN: Pues sí que has podido...$"

Route8_Text_AnnePostBattle::
    .string "LIN: Yo crío a mi POKéMON\n"
    .string "con TITA.$"

Route8_Text_AnneNotEnoughMons::
    .string "LIN: Nos gustaría luchar contigo,\n"
    .string "pero necesitas dos POKéMON.$"

Route8_Text_RicardoIntro::
    .string "¡Mi moto está como una moto!$"

Route8_Text_RicardoDefeat::
    .string "No sé qué me ha pasado...$"

Route8_Text_RicardoPostBattle::
    .string "Se me ha enganchado césped\n"
    .string "en los radios de las ruedas...$"

Route8_Text_JarenIntro::
    .string "Apártate si no quieres que te pase\n"
    .string "por encima.$"

Route8_Text_JarenDefeat::
    .string "Tú vas en serio, ¿no?$"

Route8_Text_JarenPostBattle::
    .string "Tampoco te pongas en plan tonto\n"
    .string "por haber ganado.$"
