FiveIsland_LostCave_Room10_Text_SelphyIntro::
	.string "Wa-was hast du mit mir vor?$"

FiveIsland_LostCave_Room10_Text_SelphyDefeat::
	.string "Oh… ich hatte Angst,\n"
	.string "du wolltest mir weh tun!$"

FiveIsland_LostCave_Room10_Text_MayIAskYouToTakeMeHome::
	.string "Ich bin so froh, dass du hier bist!\p"
	.string "Mir wurde beim Laufen schon\n"
	.string "langweilig.\p"
	.string "Darf ich dich bitten, mich nach\n"
	.string "Hause zu bringen?$"

