FiveIsland_LostCave_Room10_Text_SelphyIntro::
    .string "¿Qué qui-quieres de mí?$"

FiveIsland_LostCave_Room10_Text_SelphyDefeat::
    .string "Qué susto, no sabía muy bien\n"
    .string "lo que querías.$"

FiveIsland_LostCave_Room10_Text_MayIAskYouToTakeMeHome::
    .string "Me alegro de que hayas venido.\p"
    .string "Estaba ya aburridísima y cansada\n"
    .string "de tanto andar.\p"
    .string "¿Te importaría llevarme a casa?$"
