FiveIsland_LostCave_Room10_Text_SelphyIntro::
    .ifdef ENGLISH
    .string "W-what do you intend to do with\n"
    .string "me?$"
    .endif
    .ifdef SPANISH
    .string "¿Qué qui-quieres de mí?$"
    .endif

FiveIsland_LostCave_Room10_Text_SelphyDefeat::
    .ifdef ENGLISH
    .string "Oh… I was afraid that you meant to\n"
    .string "harm me.$"
    .endif
    .ifdef SPANISH
    .string "Qué susto, no sabía muy bien\n"
    .string "lo que querías.$"
    .endif

FiveIsland_LostCave_Room10_Text_MayIAskYouToTakeMeHome::
    .ifdef ENGLISH
    .string "I am so glad that you happened\n"
    .string "here.\p"
    .string "I grew rather bored of walking,\n"
    .string "and I am feeling fatigued.\p"
    .string "May I ask you to take me home\n"
    .string "from here?$"
    .endif
    .ifdef SPANISH
    .string "Me alegro de que hayas venido.\p"
    .string "Estaba ya aburridísima y cansada\n"
    .string "de tanto andar.\p"
    .string "¿Te importaría llevarme a casa?$"
    .endif

