CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
    .ifdef ENGLISH
    .string "I'm getting a present for my\n"
    .string "girlfriend.\p"
    .string "I guess a POKé DOLL will be it.\n"
    .string "It's the popular thing.$"
    .endif
    .ifdef SPANISH
    .string "¡Compraré un POKé MUÑECO\n"
    .string "para mi novia!\p"
    .string "Seguro que es el último grito\n"
    .string "en regalos.$"
    .endif

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
    .ifdef ENGLISH
    .string "I heard something useful.\p"
    .string "If a wild POKéMON appears, you can\n"
    .string "distract it with a POKé DOLL.\p"
    .string "You can run away while the wild\n"
    .string "POKéMON is distracted.$"
    .endif
    .ifdef SPANISH
    .string "¡Me han contado una cosa!\p"
    .string "¡Puedes huir de un POKéMON\n"
    .string "salvaje si le distraes con un\l"
    .string "POKé MUÑECO!$"
    .endif

CeladonCity_DepartmentStore_4F_Text_FloorSign::
    .ifdef ENGLISH
    .string "Express yourself with gifts!\n"
    .string "4F: WISE MAN GIFTS\p"
    .string "Evolution Special!\n"
    .string "Element STONES on sale now!$"
    .endif
    .ifdef SPANISH
    .string "¡Dilo con un regalo!\p"
    .string "P3: REGALOS\p"
    .string "¡Evolución Especial!\n"
    .string "¡Diversas PIEDRAS elementales\l"
    .string "en venta!$"
    .endif
