ViridianCity_House_Text_NicknamingIsFun::
	.string "Es macht Spaß, sich Spitznamen\n"
	.string "auszudenken. Aber es erfordert viel\l"
	.string "Einfallsreichtum!\p"
	.string "Einfache Namen kann man sich\n"
	.string "leichter merken!$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
	.string "Mein Papa mag POKéMON auch sehr\n"
	.string "gerne!$"

ViridianCity_House_Text_Speary::
	.string "WILLI: Habi! HABITAK!$"

ViridianCity_House_Text_SpearowNameSpeary::
	.string "HABITAK\n"
	.string "Spitzname: WILLI$"

