ViridianCity_House_Text_NicknamingIsFun::
    .ifdef ENGLISH
    .string "Coming up with nicknames is fun,\n"
    .string "but it's not so easy to do.\p"
    .string "Clever names are nice, but simple\n"
    .string "names are easier to remember.$"
    .endif
    .ifdef SPANISH
    .string "Inventarse motes es divertido, pero\n"
    .string "difícil.\p"
    .string "Es más fácil recordar nombres\n"
    .string "sencillos.$"
    .endif

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .ifdef ENGLISH
    .string "My daddy loves POKéMON, too.$"
    .endif
    .ifdef SPANISH
    .string "¡A mi padre también le gustan los\n"
    .string "POKéMON!$"
    .endif

ViridianCity_House_Text_Speary::
    .ifdef ENGLISH
    .string "SPEARY: Tetweet!$"
    .endif
    .ifdef SPANISH
    .string "SPEARY: ¡Spe-pe-peeary!$"
    .endif

ViridianCity_House_Text_SpearowNameSpeary::
    .ifdef ENGLISH
    .string "SPEAROW\n"
    .string "Name: SPEARY$"
    .endif
    .ifdef SPANISH
    .string "SPEAROW\n"
    .string "Nombre: SPEARY$"
    .endif

