SilphCo_3F_Text_WhatAmIToDo::
	.string "Ich arbeite für die SILPH CO.!\n"
	.string "Was soll ich bloß machen?$"

SilphCo_3F_Text_YouAndYourMonsSavedUs::
	.string "{PLAYER}! Du hast uns mit Hilfe\n"
	.string "deiner POKéMON gerettet!$"

SilphCo_3F_Text_GruntIntro::
	.string "Hör endlich auf, uns zu nerven!$"

SilphCo_3F_Text_GruntDefeat::
	.string "Ich gebe auf!$"

SilphCo_3F_Text_GruntPostBattle::
	.string "Ein Tipp? Du brauchst einen\n"
	.string "TÜRÖFFNER!$"

SilphCo_3F_Text_JoseIntro::
	.string "Ich arbeite für das TEAM ROCKET,\n"
	.string "die SILPH CO. zahlt zu wenig!!!$"

SilphCo_3F_Text_JoseDefeat::
	.string "Du hast mich erwischt!$"

SilphCo_3F_Text_JosePostBattle::
	.string "Mist...\p"
	.string "Das TEAM ROCKET hätte mich für\n"
	.string "meine Hilfe die POKéMON studieren\l"
	.string "lassen!$"

SilphCo_3F_Text_FloorSign::
	.string "SILPH CO. HAUPTSITZ\n"
	.string "2 OG$"

