SilphCo_3F_Text_WhatAmIToDo::
    .ifdef ENGLISH
    .string "I work for SILPH CO.\n"
    .string "What am I to do?$"
    .endif
    .ifdef SPANISH
    .string "Trabajo para SILPH S.A.\n"
    .string "¿Qué debería hacer?$"
    .endif

SilphCo_3F_Text_YouAndYourMonsSavedUs::
    .ifdef ENGLISH
    .string "{PLAYER}!\n"
    .string "You and your POKéMON saved us!$"
    .endif
    .ifdef SPANISH
    .string "¡{PLAYER}! ¡Tú y tus POKéMON\n"
    .string "nos habéis salvado!$"
    .endif

SilphCo_3F_Text_GruntIntro::
    .ifdef ENGLISH
    .string "Quit messing with us, kid!$"
    .endif
    .ifdef SPANISH
    .string "¡Eh, no nos molestes más!$"
    .endif

SilphCo_3F_Text_GruntDefeat::
    .ifdef ENGLISH
    .string "I give up!$"
    .endif
    .ifdef SPANISH
    .string "¡Me rindo!$"
    .endif

SilphCo_3F_Text_GruntPostBattle::
    .ifdef ENGLISH
    .string "A hint? You can open doors with\n"
    .string "a CARD KEY!$"
    .endif
    .ifdef SPANISH
    .string "¿Una pista? ¡Para abrir las puertas\n"
    .string "utiliza una LLAVE MAGNÉTICA!$"
    .endif

SilphCo_3F_Text_JoseIntro::
    .ifdef ENGLISH
    .string "I support TEAM ROCKET more than\n"
    .string "I support SILPH CO.!$"
    .endif
    .ifdef SPANISH
    .string "¡¡¡Apoyo más al TEAM ROCKET\n"
    .string "que a SILPH S.A.!!!$"
    .endif

SilphCo_3F_Text_JoseDefeat::
    .ifdef ENGLISH
    .string "You really got me!$"
    .endif
    .ifdef SPANISH
    .string "¡Me has derrotado!$"
    .endif

SilphCo_3F_Text_JosePostBattle::
    .ifdef ENGLISH
    .string "Humph…\p"
    .string "TEAM ROCKET said that if I helped\n"
    .string "them, they'd let me study POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "Mmmm...\p"
    .string "¡El TEAM ROCKET me dijo que si\n"
    .string "les ayudaba, me dejarían estudiar\l"
    .string "a los POKéMON!$"
    .endif

SilphCo_3F_Text_FloorSign::
    .ifdef ENGLISH
    .string "SILPH CO. HEAD OFFICE\n"
    .string "3F$"
    .endif
    .ifdef SPANISH
    .string "OFICINA CENTRAL DE SILPH S.A.\n"
    .string "P2$"
    .endif

