PalletTown_Text_OakDontGoOut::
	.string "EICH: Warte!\n"
	.string "Geh nicht raus!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
	.string "PROF. EICH: Draußen ist es\n"
	.string "gefährlich! Wilde POKéMON leben im\l"
	.string "hohen Gras!\p"
	.string "Du brauchst eigene POKéMON, um\n"
	.string "dich zu schützen.\p"
	.string "Komm, folge mir!$"

PalletTown_Text_RaisingMonsToo::
	.string "Auch ich ziehe POKéMON auf!\p"
	.string "Wenn sie stark sind, können sie mich\n"
	.string "beschützen!$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
	.string "Die Technik heutzutage ist\n"
	.string "unglaublich!\p"
	.string "Man kann sogar Items und POKéMON\n"
	.string "via PC lagern und wieder abrufen!$"

PalletTown_Text_OakPokemonResearchLab::
	.string "PROFESSOR EICH\n"
	.string "POKéMON-LABOR$"

PalletTown_Text_PlayersHouse::
	.string "Haus von {PLAYER}$"

PalletTown_Text_RivalsHouse::
	.string "Haus von {RIVAL}$"

PalletTown_Text_TownSign::
	.string "ALABASTIA\n"
	.string "Dich erwarten aufregende\l"
	.string "Abenteuer!$"

PalletTown_Text_OakLetMeSeePokedex::
	.string "EICH: Ah, {PLAYER}!\n"
	.string "Du bist also zurück?\p"
	.string "Wie ist es denn um deinen\n"
	.string "POKéDEX bestellt?\p"
	.string "Darf ich ihn sehen?\p"
	.string "Aha…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
	.string "Du hast {STR_VAR_2} gefangen…\p"
	.string "Hmm, es scheint, du würdest dich\n"
	.string "wirklich anstrengen.\p"
	.string "Wenn du mehr Einträge hast,\n"
	.string "musst du ihn mir erneut zeigen.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
	.string "Du hast {STR_VAR_2} gefangen…\n"
	.string "Das ist wirklich beeindruckend!\p"
	.string "Es gibt etwas, das ich dich fragen\n"
	.string "wollte, {PLAYER}.\p"
	.string "Komm!\n"
	.string "Folge mir!$"

PalletTown_Text_OakYouEnjoyingTraveling::
	.string "EICH: Ah, {PLAYER}!\n"
	.string "Dir scheint das Reisen Spaß zu\l"
	.string "machen!\l"
	.string "Da ich dich kenne, {PLAYER},\l"
	.string "kann ich mir vorstellen, dass du\l"
	.string "auch abgelegene Orte bereist.\p"
	.string "Das ist gut!\n"
	.string "Hoho!$"

