PalletTown_Text_OakDontGoOut::
	.string "CHEN: Hé, attends!\n"
	.string "Ne pars pas!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
	.string "CHEN: C'est très dangereux!\n"
	.string "Des POKéMON sauvages infestent\l"
	.string "les hautes herbes!\p"
	.string "Il te faut un POKéMON pour te\n"
	.string "protéger… Je sais!\p"
	.string "Suis-moi!$"

PalletTown_Text_RaisingMonsToo::
	.string "J'élève des POKéMON, moi aussi!\p"
	.string "Une fois forts, ils pourront me\n"
	.string "protéger!$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
	.string "Le progrès… C'est dément!\p"
	.string "On peut désormais stocker et même\n"
	.string "retirer des objets ou des\l"
	.string "POKéMON via un PC!$"

PalletTown_Text_OakPokemonResearchLab::
	.string "LABO POKéMON DU PROF. CHEN$"

PalletTown_Text_PlayersHouse::
	.string "Maison de {PLAYER}$"

PalletTown_Text_RivalsHouse::
	.string "Maison de {RIVAL}$"

PalletTown_Text_TownSign::
	.string "BOURG PALETTE\n"
	.string "Un monde de couleurs\l"
	.string "s'ouvre à vous!$"

PalletTown_Text_OakLetMeSeePokedex::
	.string "CHEN: Ah, {PLAYER}!\n"
	.string "Tu es de retour?\p"
	.string "As-tu bien complété ton POKéDEX?\p"
	.string "Je peux voir?\p"
	.string "Voyons, voyons…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
	.string "Tu as attrapé {STR_VAR_2} POKéMON.\p"
	.string "Hum, on dirait que tu te donnes\n"
	.string "du mal.\p"
	.string "Mais reviens me voir quand tu en\n"
	.string "auras plus, s'il te plaît.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
	.string "Tu en as attrapé… {STR_VAR_2}!?\n"
	.string "C'est vraiment impressionant!\p"
	.string "Il y a quelque chose que je\n"
	.string "voudrais te donner, {PLAYER}.\p"
	.string "Viens.\n"
	.string "Suis-moi.$"

PalletTown_Text_OakYouEnjoyingTraveling::
	.string "CHEN: Ah, {PLAYER}! On dirait que\n"
	.string "tu apprécies ton voyage.\p"
	.string "Te connaissant, je peux facilement\n"
	.string "imaginer que tu comptes déjà\p"
	.string "te rendre dans des endroits\n"
	.string "encore plus exotiques.$"

