PalletTown_Text_OakDontGoOut::
    .string "OAK: ¡Eh! ¡Alto!\n"
    .string "¡No te vayas!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "OAK: ¡Cuidado! ¡En la hierba viven\n"
    .string "POKéMON salvajes!\p"
    .string "¡Necesitas a tu propio POKéMON\n"
    .string "como protección!\p"
    .string "¡Vente conmigo, anda!$"

PalletTown_Text_RaisingMonsToo::
    .string "¡Yo también entreno a mis POKéMON!\p"
    .string "¡Cuando se hagan fuertes me\n"
    .string "protegerán!$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "¡La tecnología es increíble!\p"
    .string "¡Ahora puedes guardar y sacar\n"
    .string "objetos y POKéMON, vía PC!$"

PalletTown_Text_OakPokemonResearchLab::
    .string "LABORATORIO DE INVESTIGACIÓN\n"
    .string "DE POKéMON DEL PROFESOR OAK$"

PalletTown_Text_PlayersHouse::
    .string "Casa de {PLAYER}$"

PalletTown_Text_RivalsHouse::
    .string "Casa de {RIVAL}$"

PalletTown_Text_TownSign::
    .string "PUEBLO PALETA\n"
    .string "¡Un lienzo en blanco de tu viaje!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "OAK: ¡Ah, {PLAYER}!\n"
    .string "¡Has vuelto!\p"
    .string "¿Qué tal va tu POKéDEX?\p"
    .string "¿Me dejas que le eche un vistazo?\p"
    .string "A ver...$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "Llevas {STR_VAR_2}...\p"
    .string "Se ve que te estás esforzando\n"
    .string "mucho.\p"
    .string "Ven a verme cuando consigas más.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "Llevas... ¿¡{STR_VAR_2}!?\n"
    .string "¡Impresionante!\p"
    .string "Quiero preguntarte algo, {PLAYER}.\p"
    .string "Ven.\n"
    .string "Sígueme.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "OAK: ¡Eh, {PLAYER}! Estás\n"
    .string "disfrutando de tu aventura, ¿eh?\p"
    .string "Conociéndote, {PLAYER}, imagino que\n"
    .string "vas a ir a más lugares exóticos\l"
    .string "de los que te gustan.\p"
    .string "Pues nada, nada.\n"
    .string "¡A mí me parece estupendo!$"
