PalletTown_Text_OakDontGoOut::
    .ifdef ENGLISH
    .string "OAK: Hey! Wait!\n"
    .string "Don't go out!$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡Eh! ¡Alto!\n"
    .string "¡No te vayas!$"
    .endif

PalletTown_Text_OakGrassUnsafeNeedMon::
    .ifdef ENGLISH
    .string "OAK: It's unsafe!\n"
    .string "Wild POKéMON live in tall grass!\p"
    .string "You need your own POKéMON for\n"
    .string "your protection.\p"
    .string "I know!\n"
    .string "Here, come with me!$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡Cuidado! ¡En la hierba viven\n"
    .string "POKéMON salvajes!\p"
    .string "¡Necesitas a tu propio POKéMON\n"
    .string "como protección!\p"
    .string "¡Vente conmigo, anda!$"
    .endif

PalletTown_Text_RaisingMonsToo::
    .ifdef ENGLISH
    .string "I'm raising POKéMON, too.\p"
    .string "When they get strong, they can\n"
    .string "protect me.$"
    .endif
    .ifdef SPANISH
    .string "¡Yo también entreno a mis POKéMON!\p"
    .string "¡Cuando se hagan fuertes me\n"
    .string "protegerán!$"
    .endif

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .ifdef ENGLISH
    .string "Technology is incredible!\p"
    .string "You can now store and recall items\n"
    .string "and POKéMON as data via PC.$"
    .endif
    .ifdef SPANISH
    .string "¡La tecnología es increíble!\p"
    .string "¡Ahora puedes guardar y sacar\n"
    .string "objetos y POKéMON, vía PC!$"
    .endif

PalletTown_Text_OakPokemonResearchLab::
    .ifdef ENGLISH
    .string "OAK POKéMON RESEARCH LAB$"
    .endif
    .ifdef SPANISH
    .string "LABORATORIO DE INVESTIGACIÓN\n"
    .string "DE POKéMON DEL PROFESOR OAK$"
    .endif

PalletTown_Text_PlayersHouse::
    .ifdef ENGLISH
    .string "{PLAYER}'s house$"
    .endif
    .ifdef SPANISH
    .string "Casa de {PLAYER}$"
    .endif

PalletTown_Text_RivalsHouse::
    .ifdef ENGLISH
    .string "{RIVAL}'s house$"
    .endif
    .ifdef SPANISH
    .string "Casa de {RIVAL}$"
    .endif

PalletTown_Text_TownSign::
    .ifdef ENGLISH
    .string "PALLET TOWN\n"
    .string "Shades of your journey await!$"
    .endif
    .ifdef SPANISH
    .string "PUEBLO PALETA\n"
    .string "¡Un lienzo en blanco de tu viaje!$"
    .endif

PalletTown_Text_OakLetMeSeePokedex::
    .ifdef ENGLISH
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You're back, are you?\p"
    .string "How much have you filled in your\n"
    .string "POKéDEX?\p"
    .string "May I see it?\p"
    .string "Let's see…$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡Ah, {PLAYER}!\n"
    .string "¡Has vuelto!\p"
    .string "¿Qué tal va tu POKéDEX?\p"
    .string "¿Me dejas que le eche un vistazo?\p"
    .string "A ver...$"
    .endif

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .ifdef ENGLISH
    .string "You've caught {STR_VAR_2}…\p"
    .string "Hm, it looks as if you're putting\n"
    .string "in an honest effort.\p"
    .string "When you manage to fill it some\n"
    .string "more, come show me, please.$"
    .endif
    .ifdef SPANISH
    .string "Llevas {STR_VAR_2}...\p"
    .string "Se ve que te estás esforzando\n"
    .string "mucho.\p"
    .string "Ven a verme cuando consigas más.$"
    .endif

PalletTown_Text_CaughtXImpressiveFollowMe::
    .ifdef ENGLISH
    .string "You've caught… {STR_VAR_2}!?\n"
    .string "Now, this is impressive!\p"
    .string "There's something I wanted to ask\n"
    .string "of you, {PLAYER}.\p"
    .string "Come.\n"
    .string "Follow me.$"
    .endif
    .ifdef SPANISH
    .string "Llevas... ¿¡{STR_VAR_2}!?\n"
    .string "¡Impresionante!\p"
    .string "Quiero preguntarte algo, {PLAYER}.\p"
    .string "Ven.\n"
    .string "Sígueme.$"
    .endif

PalletTown_Text_OakYouEnjoyingTraveling::
    .ifdef ENGLISH
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You seem to be enjoying traveling.\p"
    .string "Knowing you, {PLAYER}, I can easily\n"
    .string "imagine you going out to even more\l"
    .string "exotic locales.\p"
    .string "Good for you, good for you.\n"
    .string "Hohoho.$"
    .endif
    .ifdef SPANISH
    .string "OAK: ¡Eh, {PLAYER}! Estás\n"
    .string "disfrutando de tu aventura, ¿eh?\p"
    .string "Conociéndote, {PLAYER}, imagino que\n"
    .string "vas a ir a más lugares exóticos\l"
    .string "de los que te gustan.\p"
    .string "Pues nada, nada.\n"
    .string "¡A mí me parece estupendo!$"
    .endif

