ThreeIsland_BerryForest_Text_HelpScaryPokemon::
    .ifdef ENGLISH
    .string "LOSTELLE: Whimper… Sniff…\n"
    .string "Oh! Please, help!\p"
    .string "A scary POKéMON appeared there\n"
    .string "a little while ago.\p"
    .string "It kept scaring.\n"
    .string "It made LOSTELLE scared.\p"
    .string "I'm too scared to move!\n"
    .string "But I want to go home…$"
    .endif
    .ifdef SPANISH
    .string "PEDRITA: Buuuua... ¡BUAAAA!...\n"
    .string "¡Ayúdame, ayúdame!\p"
    .string "POKéMON ho-horrible...\n"
    .string "Mmme he sustado ucho...\p"
    .string "Buaaaaa... Sustado a PEDRITA...\p"
    .string "Teno miedo...\n"
    .string "Quiedo id a casa...$"
    .endif

ThreeIsland_BerryForest_Text_HereItComesAgain::
    .ifdef ENGLISH
    .string "Oh! Here it comes again!\n"
    .string "No! Go away! It's scaring me!\p"
    .string "Waaaaaaah!\n"
    .string "I want my daddy!$"
    .endif
    .ifdef SPANISH
    .string "¡Ta ahí, ta ahí!\n"
    .string "¡Fuela, fuela! ¡Teno miedo!\p"
    .string "¡Buaaaaaaaaa!\n"
    .string "¡Papiiiiiiiiii!$"
    .endif

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
    .ifdef ENGLISH
    .string "Ohh! That was so scary!\n"
    .string "Thank you!\p"
    .string "LOSTELLE came to pick some\n"
    .string "BERRIES.\p"
    .string "You can have this!$"
    .endif
    .ifdef SPANISH
    .string "Aaaah... POKéMON malo...\n"
    .string "¡Acias!\p"
    .string "PEDRITA quedía BAYAS.\p"
    .string "Toma, cara ti.$"
    .endif

ThreeIsland_BerryForest_Text_LetsGoHome::
    .ifdef ENGLISH
    .string "What's your name?\p"
    .string "LOSTELLE's scared, so can I go\n"
    .string "with you to my daddy's house?\p"
    .string "Okay!\n"
    .string "Let's go home!$"
    .endif
    .ifdef SPANISH
    .string "¿Quién ede?\p"
    .string "PEDRITA sustada, lleva a casa\n"
    .string "con papi a PEDRITA.\p"
    .string "¡A casa con papi!\n"
    .string "¡Con papi!$"
    .endif

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
    .ifdef ENGLISH
    .string "Your BERRY POUCH is full.\n"
    .string "I guess you don't want this.$"
    .endif
    .ifdef SPANISH
    .string "El SACO de las BAYAS está lleno.$"
    .endif

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
    .ifdef ENGLISH
    .string "Welcome to the BERRY FOREST\p"
    .string "Be friendly and share BERRIES with\n"
    .string "others and POKéMON.$"
    .endif
    .ifdef SPANISH
    .string "Éste es el BOSQUE BAYA.\p"
    .string "¡Hay que compartir BAYAS\n"
    .string "con la gente y los POKéMON!$"
    .endif

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
    .ifdef ENGLISH
    .string "Beware of wild, BERRY-loving\n"
    .string "POKéMON!$"
    .endif
    .ifdef SPANISH
    .string "Atención:\n"
    .string "Presencia de POKéMON salvajes\l"
    .string "devoradores de BAYAS.$"
    .endif

