CeladonCity_Hotel_Text_ThisHotelIsForPeople::
	.string "Des POKéMON quoi?\n"
	.string "C'est un hôtel ici…\p"
	.string "Et c'est complet.$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
	.string "Je suis en vacances avec mon\n"
	.string "frère et mon petit ami.\p"
	.string "CELADOPOLE est si belle!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
	.string "Pourquoi?\n"
	.string "Mais pourquoi y'a son frère?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
	.string "Je suis en vacances avec ma\n"
	.string "sœur… Ça craint à mort!$"

