CeladonCity_Hotel_Text_ThisHotelIsForPeople::
	.string "In diesem Hotel sind keine POKéMON\n"
	.string "erlaubt!\p"
	.string "Tut mir Leid.$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
	.string "Ich mache hier mit meinem Bruder\n"
	.string "und meinem Freund Urlaub.\p"
	.string "PRISMANIA CITY ist wunderschön!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
	.string "Warum nur musste sie ihren Bruder\n"
	.string "mitnehmen?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
	.string "Dieser Urlaub war eine Idee meiner\n"
	.string "Schwester!$"

