CeladonCity_Hotel_Text_ThisHotelIsForPeople::
    .ifdef ENGLISH
    .string "POKéMON?\n"
    .string "No, this is a hotel for people.\p"
    .string "We're full up, unfortunately.$"
    .endif
    .ifdef SPANISH
    .string "¿POKéMON?\n"
    .string "No, éste es un hotel para gente.\p"
    .string "¡Está completo!$"
    .endif

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
    .ifdef ENGLISH
    .string "I'm on vacation with my brother and\n"
    .string "boyfriend.\p"
    .string "CELADON is such a pretty city!$"
    .endif
    .ifdef SPANISH
    .string "Estoy de vacaciones con mi\n"
    .string "hermano y con mi novio.\p"
    .string "¡AZULONA es una bonita ciudad!$"
    .endif

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
    .ifdef ENGLISH
    .string "Why?\n"
    .string "Why did she bring her brother?$"
    .endif
    .ifdef SPANISH
    .string "¿Por qué trajo a su hermano?$"
    .endif

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
    .ifdef ENGLISH
    .string "Yippee! I'm on vacation!\n"
    .string "My sis brought me along! Awesome!$"
    .endif
    .ifdef SPANISH
    .string "¡Mi hermana me trajo de\n"
    .string "vacaciones!$"
    .endif

