FourIsland_Text_IslandSign::
    .ifdef ENGLISH
    .string "FOUR ISLAND\n"
    .string "The Warm, Blue, Floe Island$"
    .endif
    .ifdef SPANISH
    .string "ISLA QUARTA\n"
    .string "La isla cálida, azul y rara.$"
    .endif

FourIsland_Text_LoreleiHasReturned::
    .ifdef ENGLISH
    .string "LORELEI has returned.\p"
    .string "Did she find the city life too\n"
    .string "stressful, I wonder?$"
    .endif
    .ifdef SPANISH
    .string "LORELEI ha vuelto.\p"
    .string "Creo que la vida de la ciudad le\n"
    .string "resultaba demasiado estresante...$"
    .endif

FourIsland_Text_LoreleiMetLaprasAsChild::
    .ifdef ENGLISH
    .string "LORELEI has gone back.\p"
    .string "The LAPRAS she has, I imagine it\n"
    .string "to be the one she met as a child.\p"
    .string "I believe it was in ICEFALL CAVE\n"
    .string "that she caught it.\p"
    .string "Perhaps that POKéMON has been with\n"
    .string "her ever since.$"
    .endif
    .ifdef SPANISH
    .string "LORELEI ha vuelto.\p"
    .string "Creo que el LAPRAS que tiene,\n"
    .string "es el mismo que atrapó de pequeña.\p"
    .string "Yo creo que se hizo con él\n"
    .string "en la CUEVA GLACIADA...\p"
    .string "Me parece que lo tiene desde\n"
    .string "entonces.$"
    .endif

FourIsland_Text_RivalAlreadyGotEggBeSmellingYa::
    .ifdef ENGLISH
    .string "{RIVAL}: Hey!\n"
    .string "{PLAYER}!\p"
    .string "What are you doing here in the\n"
    .string "SEVII ISLANDS?\p"
    .string "You should quit copying me,\n"
    .string "you know?\p"
    .string "Anyways, I already got my POKéMON\n"
    .string "EGG, so I'm done with this island.\p"
    .string "Heh, I bet you don't even know\n"
    .string "about POKéMON EGGS.\p"
    .string "You'll never fill your NATIONAL\n"
    .string "POKéDEX that way.\p"
    .string "By the way, I saw someone we both\n"
    .string "know on this island.\p"
    .string "Why don't you go look around if\n"
    .string "it makes you curious?\p"
    .string "Me, I don't have the time to\n"
    .string "waste.\p"
    .string "Be smelling ya!$"
    .endif
    .ifdef SPANISH
    .string "{RIVAL}: ¡Eh, {PLAYER}!\p"
    .string "¿Qué estás haciendo en\n"
    .string "ARCHI7?\p"
    .string "Deberías dejar de copiarte de todo\n"
    .string "lo que hago.\p"
    .string "Bueno, yo ya tengo mi HUEVO\n"
    .string "POKéMON, así que no me queda\l"
    .string "nada más que hacer en esta isla.\p"
    .string "No sé ni para qué te cuento esto,\n"
    .string "seguro que no tienes ni idea de\l"
    .string "lo que es un HUEVO POKéMON.\p"
    .string "Así no vas a completar la POKéDEX\n"
    .string "NACIONAL en la vida.\p"
    .string "Por cierto, he visto a alguien a\n"
    .string "quien conocemos en la isla.\p"
    .string "¿No te das una vuelta a ver\n"
    .string "quién es?\l"
    .string "¿No te pica la curiosidad?\p"
    .string "Yo me largo, no tengo tiempo.\p"
    .string "¡Nos vemos!$"
    .endif

FourIsland_Text_LoreleiHasLotsOfStuffedDolls::
    .ifdef ENGLISH
    .string "Oh, you found me!\n"
    .string "Please don't tell LORELEI.\p"
    .string "Did you know that LORELEI has lots\n"
    .string "and lots of stuffed dolls?\p"
    .string "Every time she comes back to\n"
    .string "FOUR ISLAND, her collection grows!$"
    .endif
    .ifdef SPANISH
    .string "¡Me has encontrado!\n"
    .string "¡No se lo digas a LORELEI!\p"
    .string "¿Sabías que LORELEI tiene un\n"
    .string "montón de muñecos de peluche?\p"
    .string "¡Cada vez que vuelve a ISLA\n"
    .string "QUARTA, aumenta la colección!$"
    .endif

FourIsland_Text_MadeSlushieUsingIcefallCaveIce::
    .ifdef ENGLISH
    .string "Ooh, chilly!\p"
    .string "I made a slushie using ice I\n"
    .string "shaved inside ICEFALL CAVE.\p"
    .string "It's chilly and tasty!$"
    .endif
    .ifdef SPANISH
    .string "¡Uyyy, qué fresquito!\p"
    .string "Me he hecho un granizado con\n"
    .string "hielo de la CUEVA GLACIADA.\p"
    .string "¡Está fresquito y riquísimo!$"
    .endif

FourIsland_Text_LoreleisHouse::
    .ifdef ENGLISH
    .string "LORELEI'S HOUSE$"
    .endif
    .ifdef SPANISH
    .string "CASA DE LORELEI$"
    .endif

